### ISSUE TITLE
Clear semantic highlights when the server has been stopped

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#1002]
Currently, the highlights stay as they are.

**Comment by yyoncho** [comment]
cc @sebastiansturm

**Comment by sebastiansturm** [comment]
Adding `(remove-overlays (point-min) (point-max) 'lsp-sem-highlight t)` after the `(remhash ...`) line within `lsp--remove-cur-overlays` might be sufficient, though the different handling of highlighting and semantic-highlighting overlays is a bit ugly IMO (one type being kept in a hash, the other type being identified via the `lsp-sem-highlight` property).
On the other hand, semantic highlighting overlays have to be found and removed per line during incremental updates so representing them differently probably makes sense.

Are you ok with that one-line patch?

**Comment by yyoncho** [comment]
I am fine with the patch but it should not be in lsp--remove-cur-overlays because it is called before the symbol highlights are cleared. A better place would be lsp--create-sentinel.
