### ISSUE TITLE
Don't restart language server if all associated buffers have been closed

### ISSUE THREAD

**Issue by sebastiansturm** [emacs-lsp/lsp-mode#1018]
when closing the last buffer associated with some language server (or closing all of them using, e.g., `projectile-kill-buffers`), the ensuing language server shutdown causes lsp-mode to ask if it should be restarted. On my copy of lsp-mode, I'm suppressing that behavior using the following extra check within `lsp--restart-if-needed` (specifically, the first line `(when (--any? ...))`:
```
(defun lsp--restart-if-needed (workspace)
  "Handler restart for WORKSPACE."
  (when (--any? (buffer-live-p it) (lsp--workspace-buffers workspace))
    (when (or (eq lsp-restart 'auto-restart)
              (eq (lsp--workspace-shutdown-action workspace) 'restart)
              (and (eq lsp-restart 'interactive)
                   (let ((query (format "Server %s exited with status %s. Do you want to restart it?"
                                        (lsp--workspace-print workspace)
                                        (process-status (lsp--workspace-proc workspace)))))
                     (y-or-n-p query))))
      (--each (lsp--workspace-buffers workspace)
        (when (buffer-live-p it)
          (with-current-buffer it
            (if lsp--buffer-deferred
                (lsp-deferred)
              (lsp--info "Restarting LSP in buffer %s" (buffer-name))
              (lsp))))))))
```
If that seems like an acceptable solution, I'll open a PR (if not, what's a better place to perform that check?)

**Comment by yyoncho** [comment]
> If that seems like an acceptable solution, I'll open a PR (if not, what's a better place to perform that check?)

What about introducing `lsp-restart` value which enables that behaviour?

**Comment by sebastiansturm** [comment]
personally, I don't think I have a use for language servers with no associated buffers. But I'll gladly make the change if you think that a separate setting is a better solution

**Comment by yyoncho** [comment]
It doesn't seem to be consistent with what we currently have: For example, if you have one buffer and the server has a bug causing a crash when you close a buffer. In this case, the server won't restart although you have set the `lsp-restart` to `auto`.

**Comment by yyoncho** [comment]
> To me as a user, the action "close last buffer associated to server" is a kind of deliberate workspace shutdown

We have a setting for that behaviour - `lsp-keep-workspace-alive`.

**Comment by sebastiansturm** [comment]
ah, I didn't know, sorry. Guess I should have RTFM first.

In that case there's no need to change anything, setting `lsp-keep-workspace-alive` to `nil` should fix the unwanted restart attempts (and it seems it does, just tried a few times). I suspect `nil` may be a less surprising default for many users than `t`, but since I'm biased by my own usage patterns that may well not be the case. Since there is no bug to fix I'll close this issue

**Comment by yyoncho** [comment]
> I suspect nil may be a less surprising default for many users than t, but since I'm biased by my own usage patterns that may well not be the case. 

It is a matter of personal usecase. E. g. some language servers start very slow (5+ minutes) and there was even a request to keep the server alive even after emacs restart. This is one of the reasons I wanted to introduce a setting instead of introducing a hardcoded behaviour - you never know whether you are breaking someone's flow. And of course, there is no default setting that everybody likes...
