### ISSUE TITLE
use get-file-buffer instead of visiting

### ISSUE THREAD

**Issue by aureumleonis** [emacs-lsp/lsp-mode#1027]
**Describe the bug**
Changes done on #976 break diagnostics for files with symlinks.

**To Reproduce**
Open a file on a symlink'd directory. In this case the filename returned by the server differs from `(buffer-file-name)` and no diagnostics are stored for the buffer.

**Expected behavior**
Diagnostics should've been reported

**Which Language Server did you use**
lsp-java

**OS**
Arch linux

**Error callstack**
None (current behavior is to ignore)

**Comment by yyoncho** [comment]
cc @muirrn

**Comment by muirrn** [comment]
Hmm, I guess we need to change to maintaining our own mapping from filename to buffer. What gopls does it maintain a full file path and a base name map. First it checks the full path map, and if not present it checks if any file in the base name map is identical (and then adds it to the full path map).

**Comment by yyoncho** [comment]
Alternative approaches: 
1 . cache `file-truename` calls 
2. Similar to what you are suggesting - when lsp-mode is enabled - calculate the path and then when the server sends data we can look for the buffer only in the list of managed lsp-mode buffers.

**Comment by aureumleonis** [comment]
I wrote a workaround to cache the real filenames after posting this

```
(setq lsp--buffer-file-name-cache (make-hash-table))
(defun lsp--buffer-for-file (filename)
  (if (eq system-type 'windows-nt)
      (find-buffer-visiting filename)
    (let ((cached-name (gethash filename lsp--buffer-file-name-cache)))
      (if cached-name
          (get-file-buffer cached-name)
        (let ((buffer (find-buffer-visiting filename)))
          (when buffer (puthash filename (buffer-file-name buffer) lsp--buffer-file-name-cache))
          buffer)))))
```
I don't have a windows setup so I left that part unchanged. This solved the issue for me

**Comment by yyoncho** [comment]
@aureumleonis this case is not sufficient since if the file is not present you still will hit the find-buffer-visiting on each diagnostic report.

**Comment by yyoncho** [comment]
I tried to create cache for file-truename but yelds ony 30% speedup which IMO is insufficient to solve the problem. 

```
(defvar lsp--file-true-name-cache (ht))

(defmacro lsp--with-filetrue-cache (&rest body)
  `(let ((old-fn (symbol-function 'file-truename)))
     (unwind-protect
         (progn
           (fset 'file-truename
                 (lambda (file-name &optional counter prev-dirs)
                   (or (gethash file-name lsp--file-true-name-cache)
                       (puthash file-name (apply old-fn (list file-name counter prev-dirs))
                                lsp--file-true-name-cache))))
           ,@body)
       (fset 'file-truename old-fn))))

(lsp--with-filetrue-cache
 (benchmark-run 1000 (find-buffer-visiting "/home/kyoncho/Sources/lsp/lsp-mode/lsp.el")) )

(benchmark-run 1000 (find-buffer-visiting "/home/kyoncho/Sources/lsp/lsp-mode/lsp.el")) 
```

**Comment by aureumleonis** [comment]
I've been using a simple hash based cache for a while and it works well enough for me. Since my workspaces live on symlinked locations it's either this or having no flycheck at all
