### ISSUE TITLE
Flycheck(by lsp-ui) errors are not consistent with compiling errors (javascript)

### ISSUE THREAD

**Issue by uqix** [emacs-lsp/lsp-mode#1029]
Flycheck(by lsp-ui) errors
![image](https://user-images.githubusercontent.com/10142314/65004382-c8acc680-d92e-11e9-8530-86ab04c0ddf9.png)

compiling(by create-react-app) errors
![image](https://user-images.githubusercontent.com/10142314/65004390-cd717a80-d92e-11e9-95ce-2bf7b04fff3f.png)

**Comment by yyoncho** [comment]
lsp-mode is just a frontend and it is not responsible for detecting the errors but only for displaying them. So, in order to consider something as a lsp-mode bug, you should find a inconsistently with what server is reporting and what lsp-mode is displaying.
