### ISSUE TITLE
 No parentheses after selecting the method in js file

### ISSUE THREAD

**Issue by taigacute** [emacs-lsp/lsp-mode#1033]
**Describe the bug**

No parentheses after selecting the method in js file . i used typescript-language-server

**To Reproduce**
1. a js file
2. input `console.`
3. choose log method
4. i got `console.log`
**Expected behavior**
`console.log()`

**Which Language Server did you use**
lsp-typescript

**OS**
macos
**Error callstack**
If there is an error please reproduce the issue with `toggle-debug-on-error` and after setting `lsp-print-io` to t, and then include the callstack and attach the content of `*lsp-log*` buffer.

``` emacs-lisp
(setq lsp-print-io t)
```
```
*lsp-log* buferr
Command "javascript-typescript-stdio" is not present on the path.
Command "typescript-language-server --stdio" is present on the path.
Found the following clients for /Users/pendragon/workspace/test/test.js: (server-id ts-ls, priority -2)
The following clients were selected based on priority: (server-id ts-ls, priority -2)
[tsserver] /bin/sh: /usr/local/Cellar/node/12.10.0/bin/npm: No such file or directory

```
```

**Comment by yyoncho** [comment]
This depends on the server, lsp-mode/company-lsp are inserting whatever the server is sending. So report your issue in the corresponding language server repository.

**Comment by yyoncho** [comment]
> inserting whatever the server is sending.

Full client/server log is available in `*lsp-log: ts-ls:`
