### ISSUE TITLE
lsp-find-definition does not push marker onto stack

### ISSUE THREAD

**Issue by jimmywongroo** [emacs-lsp/lsp-mode#1034]
**Describe the bug**
In Emacs 27, `(lsp-find-locations)` does not push mark to stack, so xref's `M-,` does not work. The reason is `xref-show-definitions-function` does not push a mark before displaying the definition.

**To Reproduce**

1. Use any `(lsp-find-definition)` function when point is on a symbol
2. Type `M-,`

**Expected behavior**
Emacs will switch back to the buffer the `(lsp-find-definition)` command was issued from.

**Which Language Server did you use**
lsp-typescript

**OS**
macOS

**Comment by firstrow** [comment]
I'm currently using next commands for navigation and it works as expected. 
```
  xref-find-definitions
  xref-pop-marker-stack
```
So M-. and M-, are working good without any configuration.

**Comment by lordvarys** [comment]
Closing this if you are going to deprecate the `lsp-find-*`

**Comment by JohnC32** [comment]
I tried using xref. It doesn't let one go back and forth.  I've been using RTags, https://github.com/Andersbakken/rtags navigation capabilities for a while and the ability to go forward and backward is very a major benefit in code navigation. See their rtags-location-stack-back and 'rtags-location-stack-forward. Please consider adding both directions. Thanks

**Comment by seagle0128** [comment]
xref works fine for me.

**Comment by JohnC32** [comment]
xref does work for some items, but not others. 

For example, run M-x xref-find-references and from the list of items shown, pick one. You can then run M-x xref-pop-marker-stack to jump back. However, there's no jump forward. If I want to go forward to where I just was, I need to re-run M-x xref-find-references and then pick the desired item, or I can use ^X^B, etc. There's no clean way to move forward.

In addition, xref doesn't work for other key items such as M-x lsp-find-implementation (to find all implementations of virtual C++ methods), select one of them and you can jump back.

The paradigm in RTags is super helpful. It covers all navigation capabilities, definition, references, virtual method implementations, etc. and lets me go back, *then* forward. This makes it very easy to focus on the code an not having to worry about switching between buffers.

The top navigation items I find for C++ code are: definitions, references, virtual method implementations, and navigation back and forward. The last two may seem not that important, but once you have them they are a major win.

I could write wrappers around the key lsp/xref commands to give back and *forward* navigation, though it would be much nicer to see these concepts as part of lsp-mode. Thoughts?

**Comment by yyoncho** [comment]
> I could write wrappers around the key lsp/xref commands to give back and forward navigation,

There was an implementation of forward for xref in stackoverflow(?) but I am unable to find it out now. 
Maybe @dgutov could help with that.

As for lsp-find-implementation, it does not work indeed. I think that it only needs to push the marker on the stack. I prefer this solution instead of implementing backward/forward on top of xref since it will lead to less code.

**Comment by dgutov** [comment]
@yyoncho I haven't seen it, and I'm sure you know that if the author does not intend to assign the copyright, I better not see the implementation (if you want it in Emacs core).

It should be fairly easy to add, though (I just use the `history` package, myself).

**Comment by JohnC32** [comment]
Can you give a pointer to the history package? It doesn't seem to come with Emacs25 and googling on emacs history isn't so helpful. Thanks

**Comment by seagle0128** [comment]
I'm using `C-u C-SPC` for markers.

**Comment by dgutov** [comment]
https://melpa.org/#/history

**Comment by yyoncho** [comment]
@JohnC32 if `history` package or  @seagle0128 solution does not work for you, feel free to open another issue. 

> we should deprecate the lsp-find-* equivalents 

I gave up on that due to https://github.com/emacs-lsp/lsp-mode/issues/1117 .

**Comment by yuchunzhou** [comment]
I still meet this problem, is it fixed in new releases?
