### ISSUE TITLE
emacs hang on the condition that  a remote go file is opened by tramp

### ISSUE THREAD

**Issue by weiwei-xiao** [emacs-lsp/lsp-mode#1035]
**Describe the bug**
Emacs always hang when I open  go file in my vm by tramp. I have to type C-g to stop this situation.
The init configuration is 
```
  (require 'lsp-mode)
   (lsp-register-client
    (make-lsp-client :new-connection (lsp-tramp-connection
                                      (lambda () (cons "gopls" lsp-gopls-server-args)))
                     :major-modes '(go-mode)
                     :priority 10
                     :server-id 'gopls-remote
                     :remote? t
                     ))
```
When I comment the above init configuration code and open go file in my vm by tramp, emacs act normally.

**Which Language Server did you use**
lsp-go

**OS**
local: MacOS
vm: centos-linux-7

**Error callstack**
Debugger entered--Lisp error: (quit)
* accept-process-output(#<process *tramp/ssh root@10.211.55.3*> 1 nil 0)
  tramp-accept-process-output(#<process *tramp/ssh root@10.211.55.3*> 1)
  tramp-wait-for-regexp(#<process *tramp/ssh root@10.211.55.3*> nil "\\(^\\|\0\\)[^#$\n]*///e790f5431490a44393d13fd6e75db7b7#\\$\\(\033[[0-9]+n\\)?\015?$")
  tramp-wait-for-output(#<process *tramp/ssh root@10.211.55.3*>)
  tramp-send-command((tramp-file-name #("ssh" 0 3 (helm-ff-file t)) #("root" 0 4 (helm-ff-file t)) nil #("10.211.55.3" 0 11 (helm-ff-file t)) nil "/usr/local/go/src/syscall/sockcmsg_linux.go" nil) "\\readlink --canonicalize-missing /usr/local/go/src/syscall/sockcmsg_linux.go 2>/dev/null; echo tramp_exit_status $?")
  tramp-send-command-and-check((tramp-file-name #("ssh" 0 3 (helm-ff-file t)) #("root" 0 4 (helm-ff-file t)) nil #("10.211.55.3" 0 11 (helm-ff-file t)) nil "/usr/local/go/src/syscall/sockcmsg_linux.go" nil) "\\readlink --canonicalize-missing /usr/local/go/src/syscall/sockcmsg_linux.go")
  tramp-sh-handle-file-truename(#("/ssh:root@10.211.55.3:/usr/local/go/src/syscall/sockcmsg_linux.go" 1 4 (helm-ff-file t) 5 9 (helm-ff-file t) 10 21 (helm-ff-file t)))
  apply(tramp-sh-handle-file-truename #("/ssh:root@10.211.55.3:/usr/local/go/src/syscall/sockcmsg_linux.go" 1 4 (helm-ff-file t) 5 9 (helm-ff-file t) 10 21 (helm-ff-file t)))
  tramp-sh-file-name-handler(file-truename #("/ssh:root@10.211.55.3:/usr/local/go/src/syscall/sockcmsg_linux.go" 1 4 (helm-ff-file t) 5 9 (helm-ff-file t) 10 21 (helm-ff-file t)))
  apply(tramp-sh-file-name-handler file-truename #("/ssh:root@10.211.55.3:/usr/local/go/src/syscall/sockcmsg_linux.go" 1 4 (helm-ff-file t) 5 9 (helm-ff-file t) 10 21 (helm-ff-file t)))
  tramp-file-name-handler(file-truename #("/ssh:root@10.211.55.3:/usr/local/go/src/syscall/sockcmsg_linux.go" 1 4 (helm-ff-file t) 5 9 (helm-ff-file t) 10 21 (helm-ff-file t)))
  file-truename(#("/ssh:root@10.211.55.3:/usr/local/go/src/syscall/sockcmsg_linux.go" 1 4 (helm-ff-file t) 5 9 (helm-ff-file t) 10 21 (helm-ff-file t)))
  find-buffer-visiting(#("/ssh:root@10.211.55.3:/usr/local/go/src/syscall/sockcmsg_linux.go" 1 4 (helm-ff-file t) 5 9 (helm-ff-file t) 10 21 (helm-ff-file t)))
  lsp--on-diagnostics(#s(lsp--workspace :parser #s(lsp--parser :headers nil :body nil :reading-body nil :body-length nil :body-received nil :leftovers "Content-Length:" :workspace #1) :server-capabilities #<hash-table equal 15/65 0x5bc37535> :registered-server-capabilities nil :root #("/ssh:root@10.211.55.3:/usr/local/go/src/syscall/" 1 4 (helm-ff-file t) 5 9 (helm-ff-file t) 10 21 (helm-ff-file t)) :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x5ae5c75d>) :test\? #f(compiled-function () #<bytecode 0x5ae5efa9>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x5ae5efb5> :request-handlers #<hash-table equal 0/65 0x5ae5f28d> :response-handlers #<hash-table eql 6/65 0x5ae5f331> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x5ae5f351> :action-handlers #<hash-table equal 0/65 0x5ae5f741> :major-modes (go-mode) :activation-fn nil :priority 10 :server-id gopls-remote :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? t :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil) :host-root #("/ssh:root@10.211.55.3:" 1 4 (helm-ff-file t) 5 9 (helm-ff-file t) 10 21 (helm-ff-file t)) :proc #<process gopls-remote<2>> :cmd-proc #<process gopls-remote<2>> :buffers (#<buffer syscall.go>) :highlight-overlays #<hash-table eq 0/65 0x59f4a221> :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x59f4a2c5> :watches #<hash-table equal 0/65 0x5bceafb5> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x5bceafd5> :ewoc nil) #<hash-table equal 2/65 0x5bd69539>)
  lsp--on-notification(#s(lsp--workspace :parser #s(lsp--parser :headers nil :body nil :reading-body nil :body-length nil :body-received nil :leftovers "Content-Length:" :workspace #1) :server-capabilities #<hash-table equal 15/65 0x5bc37535> :registered-server-capabilities nil :root #("/ssh:root@10.211.55.3:/usr/local/go/src/syscall/" 1 4 (helm-ff-file t) 5 9 (helm-ff-file t) 10 21 (helm-ff-file t)) :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x5ae5c75d>) :test\? #f(compiled-function () #<bytecode 0x5ae5efa9>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x5ae5efb5> :request-handlers #<hash-table equal 0/65 0x5ae5f28d> :response-handlers #<hash-table eql 6/65 0x5ae5f331> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x5ae5f351> :action-handlers #<hash-table equal 0/65 0x5ae5f741> :major-modes (go-mode) :activation-fn nil :priority 10 :server-id gopls-remote :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? t :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil) :host-root #("/ssh:root@10.211.55.3:" 1 4 (helm-ff-file t) 5 9 (helm-ff-file t) 10 21 (helm-ff-file t)) :proc #<process gopls-remote<2>> :cmd-proc #<process gopls-remote<2>> :buffers (#<buffer syscall.go>) :highlight-overlays #<hash-table eq 0/65 0x59f4a221> :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x59f4a2c5> :watches #<hash-table equal 0/65 0x5bceafb5> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x5bceafd5> :ewoc nil) #<hash-table equal 3/65 0x5d71e459>)
  lsp--parser-on-message(#s(lsp--parser :headers nil :body nil :reading-body nil :body-length nil :body-received nil :leftovers "Content-Length:" :workspace #s(lsp--workspace :parser #1 :server-capabilities #<hash-table equal 15/65 0x5bc37535> :registered-server-capabilities nil :root #("/ssh:root@10.211.55.3:/usr/local/go/src/syscall/" 1 4 (helm-ff-file t) 5 9 (helm-ff-file t) 10 21 (helm-ff-file t)) :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x5ae5c75d>) :test\? #f(compiled-function () #<bytecode 0x5ae5efa9>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x5ae5efb5> :request-handlers #<hash-table equal 0/65 0x5ae5f28d> :response-handlers #<hash-table eql 6/65 0x5ae5f331> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x5ae5f351> :action-handlers #<hash-table equal 0/65 0x5ae5f741> :major-modes (go-mode) :activation-fn nil :priority 10 :server-id gopls-remote :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? t :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil) :host-root #("/ssh:root@10.211.55.3:" 1 4 (helm-ff-file t) 5 9 (helm-ff-file t) 10 21 (helm-ff-file t)) :proc #<process gopls-remote<2>> :cmd-proc #<process gopls-remote<2>> :buffers (#<buffer syscall.go>) :highlight-overlays #<hash-table eq 0/65 0x59f4a221> :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x59f4a2c5> :watches #<hash-table equal 0/65 0x5bceafb5> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x5bceafd5> :ewoc nil)) "{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/publishDiagnostics\",\"params\":{\"uri\":\"file:///usr/local/go/src/syscall/sockcmsg_linux.go\",\"diagnostics\":[]}}")
  #f(compiled-function (proc output) #<bytecode 0x5ad8b195>)(#<process gopls-remote<2>> "Content-Length: 147\015\n\015\n{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/publishDiagnostics\",\"params\":{\"uri\":\"file:///usr/local/go/src/syscall/sockcmsg_linux.go\",\"diagnostics\":[]}}Content-Length: 152\015\n\015\n{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/publishDiagnostics\",\"params\":{\"uri\":\"file:///usr/local/go/src/syscall/zsysnum_linux_amd64.go\",\"diagnostics\":[]}}Content-Length: 144\015\n\015\n{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/publishDiagnostics\",\"params\":{\"uri\":\"file:///usr/local/go/src/syscall/export_test.go\",\"diagnostics\":[]}}Content-Length: 142\015\n\015\n{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/publishDiagnostics\",\"params\":{\"uri\":\"file:///usr/local/go/src/syscall/exec_unix.go\",\"diagnostics\":[]}}Content-Length: 138\015\n\015\n{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/publishDiagnostics\",\"params\":{\"uri\":\"file:///usr/local/go/src/syscall/flock.go\",\"diagnostics\":[]}}Content-Length: 148\015\n\015\n{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/publishDiagnostics\",\"params\":{\"uri\":\"file:///usr/local/go/src/syscall/setuidgid_linux.go\",\"diagnostics\":[]}}Content-Length:")

**Comment by yyoncho** [comment]
Emacs version? lsp-mode version?

**Comment by yyoncho** [comment]
Latest lsp-mode does not use `find-file-visiting` but `get-file-buffer` on MacOS. Can you update lsp-mode version and retry?

Also, can you execute the following piece:

``` 
(file-truename #("/ssh:root@10.211.55.3:/usr/local/go/src/syscall/sockcmsg_linux.go" 1 4 (helm-ff-file t) 5 9 (helm-ff-file t) 10 21 (helm-ff-file t)))
```

**Comment by weiwei-xiao** [comment]
> Emacs version? lsp-mode version?

Emacs version is 26.2
lsp-mode version is lsp-mode-20190807.507

**Comment by yyoncho** [comment]
> lsp-mode version is lsp-mode-20190807.507

A good practice before logging a bug is to reproduce the issue after upgrading to the latest version of the package. So, can you upgrade to latest melpa version and try the same thing and report back?

**Comment by weiwei-xiao** [comment]
> Latest lsp-mode does not use `find-file-visiting` but `get-file-buffer` on MacOS. Can you update lsp-mode version and retry?
> 
> Also, can you execute the following piece:
> 
> ```
> (file-truename #("/ssh:root@10.211.55.3:/usr/local/go/src/syscall/sockcmsg_linux.go" 1 4 (helm-ff-file t) 5 9 (helm-ff-file t) 10 21 (helm-ff-file t)))
> ```

Firstly, I execute in eshell and get response immediately.
```
(file-truename #("/ssh:root@10.211.55.3:/usr/local/go/src/syscall/sockcmsg_linux.go" 1 4 (helm-ff-file t) 5 9 (helm-ff-file t) 10 21 (helm-ff-file t)))
/ssh:root@10.211.55.3:/usr/local/go/src/syscall/sockcmsg_linux.go
```
And I  update lsp-mode version to 20190918.1903 and it seems to be normal now. Thanks for your  advices.

**Comment by weiwei-xiao** [comment]
> > lsp-mode version is lsp-mode-20190807.507
> 
> A good practice before logging a bug is to reproduce the issue after upgrading to the latest version of the package. So, can you upgrade to latest melpa version and try the same thing and report back?

I shall remember to upgrade to latest version next time. Thanks a lot.
