### ISSUE TITLE
common (wrong-type-argument hash-table-p nil) when code is updated (this gets broken every few releases)

### ISSUE THREAD

**Issue by prittjam** [emacs-lsp/lsp-mode#1036]
**Describe the bug**

**To Reproduce**
start editing some python

**Which Language Server did you use**
lsp-python-ms

**OS**
Which os do you use?
Liinux

**Error callstack**
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  puthash("/home/jbpritts/src/calibration/agnostic/example.py" (#s(lsp-diagnostic :range (:start (:line 0 :column 5) :end (:line 0 :column 14)) :line 0 :column 5 :severity 2 :code "unresolved-import" :source "Python" :message "Python: unresolved import 'extractor'" :original #<hash-table equal 5/65 0x1fc7025>) #s(lsp-diagnostic :range (:start (:line 1 :column 5) :end (:line 1 :column 12)) :line 1 :column 5 :severity 2 :code "unresolved-import" :source "Python" :message "Python: unresolved import 'pyutils'" :original #<hash-table equal 5/65 0x214cd11>) #s(lsp-diagnostic :range (:start (:line 31 :column 15) :end (:line 31 :column 20)) :line 31 :column 15 :severity 1 :code "undefined-variable" :source "Python" :message "Python: Undefined variable: 'image'" :original #<hash-table equal 5/65 0x214cd51>) #s(lsp-diagnostic :range (:start (:line 32 :column 21) :end (:line 32 :column 26)) :line 32 :column 21 :severity 1 :code "undefined-variable" :source "Python" :message "Python: Undefined variable: 'image'" :original #<hash-table equal 5/65 0x27c8705>) #s(lsp-diagnostic :range (:start (:line 53 :column 14) :end (:line 53 :column 22)) :line 53 :column 14 :severity 1 :code "undefined-variable" :source "Python" :message "Python: Undefined variable: 'LMDBDict'" :original #<hash-table equal 5/65 0x27c8765>) #s(lsp-diagnostic :range (:start (:line 64 :column 40) :end (:line 64 :column 49)) :line 64 :column 40 :severity 1 :code "undefined-variable" :source "Python" :message "Python: Undefined variable: 'Extractor'" :original #<hash-table equal 5/65 0x1c103f1>) #s(lsp-diagnostic :range (:start (:line 75 :column 21) :end (:line 75 :column 36)) :line 75 :column 21 :severity 1 :code "undefined-variable" :source "Python" :message "Python: Undefined variable: 'undistort_image'" :original #<hash-table equal 5/65 0x1400601>)) nil)
  lsp--on-diagnostics(#s(lsp--workspace :parser #s(lsp--parser :headers nil :body nil :reading-body nil :body-length nil :body-received nil :leftovers "" :workspace #1) :server-capabilities #<hash-table equal 15/65 0x137bcfd> :registered-server-capabilities nil :root "/home/jbpritts/ovrsource/" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x18b00f5>) :test\? #f(compiled-function () #<bytecode 0x18b1571>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 5/65 0x18b157d> :request-handlers #<hash-table equal 0/65 0x18b21c9> :response-handlers #<hash-table eql 0/65 0x18b21e9> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x18b68b9> :action-handlers #<hash-table equal 0/65 0x18b68d9> :major-modes (python-mode) :activation-fn nil :priority 1 :server-id mspyls :multi-root nil :initialization-options lsp-python-ms--extra-init-params :custom-capabilities nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn #f(compiled-function (workspace) #<bytecode 0x18b00b9>) :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil) :host-root nil :proc #<process mspyls> :cmd-proc #<process mspyls> :buffers (#<buffer example.py>) :highlight-overlays #<hash-table eq 0/65 0x199a52d> :semantic-highlighting-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x199a54d> :watches #<hash-table equal 0/65 0x19e8b79> :workspace-folders nil :last-id 0 :status-string "::Started" :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x134df95> :ewoc nil) #<hash-table equal 2/65 0x1fc7005>)
  lsp--on-notification(#s(lsp--workspace :parser #s(lsp--parser :headers nil :body nil :reading-body nil :body-length nil :body-received nil :leftovers "" :workspace #1) :server-capabilities #<hash-table equal 15/65 0x137bcfd> :registered-server-capabilities nil :root "/home/jbpritts/ovrsource/" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x18b00f5>) :test\? #f(compiled-function () #<bytecode 0x18b1571>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 5/65 0x18b157d> :request-handlers #<hash-table equal 0/65 0x18b21c9> :response-handlers #<hash-table eql 0/65 0x18b21e9> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x18b68b9> :action-handlers #<hash-table equal 0/65 0x18b68d9> :major-modes (python-mode) :activation-fn nil :priority 1 :server-id mspyls :multi-root nil :initialization-options lsp-python-ms--extra-init-params :custom-capabilities nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn #f(compiled-function (workspace) #<bytecode 0x18b00b9>) :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil) :host-root nil :proc #<process mspyls> :cmd-proc #<process mspyls> :buffers (#<buffer example.py>) :highlight-overlays #<hash-table eq 0/65 0x199a52d> :semantic-highlighting-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x199a54d> :watches #<hash-table equal 0/65 0x19e8b79> :workspace-folders nil :last-id 0 :status-string "::Started" :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x134df95> :ewoc nil) #<hash-table equal 3/65 0x1fc6d2d>)
  lsp--parser-on-message(#s(lsp--parser :headers nil :body nil :reading-body nil :body-length nil :body-received nil :leftovers "" :workspace #s(lsp--workspace :parser #1 :server-capabilities #<hash-table equal 15/65 0x137bcfd> :registered-server-capabilities nil :root "/home/jbpritts/ovrsource/" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x18b00f5>) :test\? #f(compiled-function () #<bytecode 0x18b1571>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 5/65 0x18b157d> :request-handlers #<hash-table equal 0/65 0x18b21c9> :response-handlers #<hash-table eql 0/65 0x18b21e9> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x18b68b9> :action-handlers #<hash-table equal 0/65 0x18b68d9> :major-modes (python-mode) :activation-fn nil :priority 1 :server-id mspyls :multi-root nil :initialization-options lsp-python-ms--extra-init-params :custom-capabilities nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn #f(compiled-function (workspace) #<bytecode 0x18b00b9>) :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil) :host-root nil :proc #<process mspyls> :cmd-proc #<process mspyls> :buffers (#<buffer example.py>) :highlight-overlays #<hash-table eq 0/65 0x199a52d> :semantic-highlighting-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x199a54d> :watches #<hash-table equal 0/65 0x19e8b79> :workspace-folders nil :last-id 0 :status-string "::Started" :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x134df95> :ewoc nil)) "{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/publishDiagnostics\",\"params\":{\"uri\":\"file:///home/jbpritts/src/calibration/agnostic/example.py\",\"diagnostics\":[{\"range\":{\"start\":{\"line\":0,\"character\":5},\"end\":{\"line\":0,\"character\":14}},\"severity\":2,\"code\":\"unresolved-import\",\"source\":\"Python\",\"message\":\"unresolved import 'extractor'\"},{\"range\":{\"start\":{\"line\":1,\"character\":5},\"end\":{\"line\":1,\"character\":12}},\"severity\":2,\"code\":\"unresolved-import\",\"source\":\"Python\",\"message\":\"unresolved import 'pyutils'\"},{\"range\":{\"start\":{\"line\":31,\"character\":15},\"end\":{\"line\":31,\"character\":20}},\"severity\":1,\"code\":\"undefined-variable\",\"source\":\"Python\",\"message\":\"Undefined variable: 'image'\"},{\"range\":{\"start\":{\"line\":32,\"character\":21},\"end\":{\"line\":32,\"character\":26}},\"severity\":1,\"code\":\"undefined-variable\",\"source\":\"Python\",\"message\":\"Undefined variable: 'image'\"},{\"range\":{\"start\":{\"line\":53,\"character\":14},\"end\":{\"line\":53,\"character\":22}},\"severity\":1,\"code\":\"undefined-variable\",\"source\":\"Python\",\"message\":\"Undefined variable: 'LMDBDict'\"},{\"range\":{\"start\":{\"line\":64,\"character\":40},\"end\":{\"line\":64,\"character\":49}},\"severity\":1,\"code\":\"undefined-variable\",\"source\":\"Python\",\"message\":\"Undefined variable: 'Extractor'\"},{\"range\":{\"start\":{\"line\":75,\"character\":21},\"end\":{\"line\":75,\"character\":36}},\"severity\":1,\"code\":\"undefined-variable\",\"source\":\"Python\",\"message\":\"Undefined variable: 'undistort_image'\"}]}}")
  #f(compiled-function (proc output) #<bytecode 0x199a56d>)(#<process mspyls> "Content-Length: 40\015\n\015\n{\"jsonrpc\":\"2.0\",\"result\":null,\"id\":217}Content-Length: 40\015\n\015\n{\"jsonrpc\":\"2.0\",\"result\":null,\"id\":218}Content-Length: 1417\015\n\015\n{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/publishDiagnostics\",\"params\":{\"uri\":\"file:///home/jbpritts/src/calibration/agnostic/example.py\",\"diagnostics\":[{\"range\":{\"start\":{\"line\":0,\"character\":5},\"end\":{\"line\":0,\"character\":14}},\"severity\":2,\"code\":\"unresolved-import\",\"source\":\"Python\",\"message\":\"unresolved import 'extractor'\"},{\"range\":{\"start\":{\"line\":1,\"character\":5},\"end\":{\"line\":1,\"character\":12}},\"severity\":2,\"code\":\"unresolved-import\",\"source\":\"Python\",\"message\":\"unresolved import 'pyutils'\"},{\"range\":{\"start\":{\"line\":31,\"character\":15},\"end\":{\"line\":31,\"character\":20}},\"severity\":1,\"code\":\"undefined-variable\",\"source\":\"Python\",\"message\":\"Undefined variable: 'image'\"},{\"range\":{\"start\":{\"line\":32,\"character\":21},\"end\":{\"line\":32,\"character\":26}},\"severity\":1,\"code\":\"undefined-variable\",\"source\":\"Python\",\"message\":\"Undefined variable: 'image'\"},{\"range\":{\"start\":{\"line\":53,\"character\":14},\"end\":{\"line\":53,\"character\":22}},\"severity\":1,\"code\":\"undefined-variable\",\"source\":\"Python\",\"message\":\"Undefined variable: 'LMDBDict'\"},{\"range\":{\"start\":{\"line\":64,\"character\":40},\"end\":{\"line\":64,\"character\":49}},\"severity\":1,\"code\":\"undefined-variable\",\"source\":\"Python\",\"message\":\"Undefined variable: 'Extractor'\"},{\"range\":{\"start\":{\"line\":75,\"character\":21},\"end\":{\"line\":75,\"character\":36}},\"severity\":1,\"code\":\"undefined-variable\",\"source\":\"Python\",\"message\":\"Undefined variable: 'undistort_image'\"}]}}")

**Comment by yyoncho** [comment]
Unable to reproduce with a clean installation so please delete all `.elc` files in your `.emacs.d/elpa` directory and retry. Reopen the issue if this does not fix it for you.

**Comment by hlolli** [comment]
calling `find . -type f -name '*.elc' -delete` inside .emacs.d/elpa fixed this for me.

**Comment by djhunter67** [comment]
> calling `find . -type f -name '*.elc' -delete` inside .emacs.d/elpa fixed this for me.

This worked for me as well! Thank you!
