### ISSUE TITLE
Typescript server stuck on "status:starting", no capabilities.

### ISSUE THREAD

**Issue by obviousneil** [emacs-lsp/lsp-mode#1040]
I'm working on a React/Gatsby project with a bunch of .jsx files. I'm having a hard time getting lsp-mode working with anything so far. I'm not actually making use of any typescript in the project, but ES6 javascript along with JSX.

I've finally got lsp-mode installed and configured as per the readme. I've installed typescript-language-server as per the instructions.

The minibuffer displays "LSP :: Connected to [ts-ls:30247 status:starting]". In the modeline, I see "[ts-ls:30247 status:starting]" which follows an infinitely looping progress bar. It can't seem to get out of the "starting" status.

In the lsp-log buffer, I'm seeing:

```
Command "javascript-typescript-stdio" is not present on the path.
Command "typescript-language-server --stdio" is present on the path.
Found the following clients for /Users/neil/Documents/GitHub/me-site/src/pages/index.jsx: (server-id ts-ls, priority -2)
The following clients were selected based on priority: (server-id ts-ls, priority -2)
```
Hope someone can pass along some insight.

**Comment by yyoncho** [comment]
1. Can you check the stderr buffer for the server.
2. Can you set lsp-print-io to t and then attach the client/server log(it is located in \*lsp-log SERVER:pid*`  file. 

This behaviour indicates some kind of problem with the language server that you are using.

Also, can you make sure that you have `M-x toggle-debug-on-error` in case there is a hidden error somewhere.

**Comment by obviousneil** [comment]
I revisited this a few hours later, having worked without lsp-mode. Set `debug-on-error` to t, `lsp-print-io` to t, and upon command`M-x lsp` the server connected immediately. Seemed alright for a second, but it seems the server may have crashed shortly after. 

*Messages* shows:

```
Error running timer: (error "Process ts-ls not running")
eldoc error: (error Process ts-ls not running)
user-error: Minibuffer window is not active
Error running timer: (error "Process ts-ls not running")
eldoc error: (error Process ts-ls not running)
Error running timer: (error "Process ts-ls not running")
user-error: Minibuffer window is not active
Error running timer: (error "Process ts-ls not running")
```

**Comment by yyoncho** [comment]
Please start clean and provide the information requested in the previous comment.

**Comment by sk1e** [comment]
>     1. Can you check the stderr buffer for the server.
> 
>     2. Can you set lsp-print-io to t and then attach the client/server log(it is located in *lsp-log SERVER:pid*`  file.
> 
> 
> This behaviour indicates some kind of problem with the language server that you are using.
> 
> Also, can you make sure that you have `M-x toggle-debug-on-error` in case there is a hidden error somewhere.

Having the same issue. stderr buffer for the server is empty,  `*lsp-log SERVER:pid*` buffer contains:
```
[Trace - 10:14:31 ] Sending request 'initialize - (1)'.
Params: {
  "processId": 26481,
  "rootPath": "/home/kotik/Projects/react-redux-starter-kit/",
  "rootUri": "file:///home/kotik/Projects/react-redux-starter-kit/",
  "capabilities": {
    "workspace": {
      "workspaceEdit": {
        "documentChanges": true,
        "resourceOperations": [
          "create",
          "rename",
          "delete"
        ]
      },
      "applyEdit": true,
      "symbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        }
      },
      "executeCommand": {
        "dynamicRegistration": false
      },
      "didChangeWatchedFiles": {
        "dynamicRegistration": true
      },
      "workspaceFolders": true,
      "configuration": true
    },
    "textDocument": {
      "declaration": {
        "linkSupport": true
      },
      "definition": {
        "linkSupport": true
      },
      "implementation": {
        "linkSupport": true
      },
      "typeDefinition": {
        "linkSupport": true
      },
      "synchronization": {
        "willSave": true,
        "didSave": true,
        "willSaveWaitUntil": true
      },
      "documentSymbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        },
        "hierarchicalDocumentSymbolSupport": true
      },
      "formatting": {
        "dynamicRegistration": true
      },
      "rangeFormatting": {
        "dynamicRegistration": true
      },
      "rename": {
        "dynamicRegistration": true
      },
      "semanticHighlightingCapabilities": {
        "semanticHighlighting": null
      },
      "codeAction": {
        "dynamicRegistration": true,
        "codeActionLiteralSupport": {
          "codeActionKind": {
            "valueSet": [
              "",
              "quickfix",
              "refactor",
              "refactor.extract",
              "refactor.inline",
              "refactor.rewrite",
              "source",
              "source.organizeImports"
            ]
          }
        }
      },
      "completion": {
        "completionItem": {
          "snippetSupport": true,
          "documentationFormat": [
            "markdown"
          ]
        },
        "contextSupport": true
      },
      "signatureHelp": {
        "signatureInformation": {
          "parameterInformation": {
            "labelOffsetSupport": true
          }
        }
      },
      "documentLink": {
        "dynamicRegistration": true
      },
      "hover": {
        "contentFormat": [
          "markdown",
          "plaintext"
        ]
      },
      "foldingRange": {
        "dynamicRegistration": true,
        "rangeLimit": null,
        "lineFoldingOnly": false
      }
    }
  },
  "initializationOptions": {
    "plugins": null,
    "logVerbosity": "info"
  }
}


[Trace - 10:14:31 ] Received response 'initialize - (1)' in 101ms.
Result: null
```

**Comment by yyoncho** [comment]
@sk1e can you check whether the language server is alive in process explorer? From what I can see the server has returned the response to the initialize request. Also, can you check whether you have install tsserver and it is on the path?

**Comment by sk1e** [comment]
> @sk1e can you check whether the language server is alive in process explorer? From what I can see the server has returned the response to the initialize request. Also, can you check whether you have install tsserver and it is on the path?

Language server is still alive, tsserver is installed and on the path. Maybe something wrong with request parameters?

**Comment by yyoncho** [comment]
@sk1e I have never seen anything like that. Can you try reinstalling the components and also can you try with the other language server for the JS? Which version of node do you use?

**Comment by isubasti** [comment]
I've got the same problem as well saying that `Request initialize failed with message: plugins is not itterable` which sounds like a problem caused by this commit https://github.com/emacs-lsp/lsp-mode/commit/ed0e5d22f0b3fdd71c264b4a4b5c0b346197950a

**Comment by isubasti** [comment]
created a PR https://github.com/emacs-lsp/lsp-mode/pull/1058 that provides correct default plugins

**Comment by sk1e** [comment]
> @sk1e I have never seen anything like that. Can you try reinstalling the components and also can you try with the other language server for the JS? Which version of node do you use?

It's becoming fine when I switch from typescript-language-server to  javascript-typescript-langserver which results in different request
```
-  "initializationOptions": {
-    "plugins": null,
-    "logVerbosity": "info"
-  }
+  "initializationOptions": null
```

**Comment by isubasti** [comment]
> > @sk1e I have never seen anything like that. Can you try reinstalling the components and also can you try with the other language server for the JS? Which version of node do you use?
> 
> It's becoming fine when I switch from typescript-language-server to javascript-typescript-langserver which results in different request
> 
> ```
> -  "initializationOptions": {
> -    "plugins": null,
> -    "logVerbosity": "info"
> -  }
> +  "initializationOptions": null
> ```

https://github.com/emacs-lsp/lsp-mode/commit/ed0e5d22f0b3fdd71c264b4a4b5c0b346197950a added initialization options to add plugins for `typescript-language-server` with `nil` as the default value for the plugins. `typescript-language-server`expected a `vector` instead of `nil` hence the error. `javascript-typescript-langserver` works fine as it doesn't have the initialization options. https://github.com/emacs-lsp/lsp-mode/pull/1058 should fix this issue

**Comment by yyoncho** [comment]
Thank you @isubasti , marking the issue as closed. @obviousneil if you still have the issue please provide the information requested in https://github.com/emacs-lsp/lsp-mode/issues/1040#issuecomment-534383851
