### ISSUE TITLE
Setting lsp-clients-rust-progress-string makes modeline flash with messages on every edit

### ISSUE THREAD

**Issue by valignatev** [emacs-lsp/lsp-mode#1042]
I'm not sure if this is the best place to report this (or it's better to be asked as a question in Gitter chat), so excuse me in advance :)

The question is about this line: https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-rust.el#L262

Basically, it reintroduces https://github.com/emacs-lsp/lsp-mode/issues/643, but on the modeline level: every time I edit a rust-mode buffer, modeline flashes with "Building - myproject" messages. I'm using [doom-modeline](https://github.com/seagle0128/doom-modeline) if it matters.

Easy solution for me is to delete `lsp-clients-rust-progress-string` from the `global-mode-string`, but I don't want to get rid of rls output completely. 
It would be really nice to see it when rls initially builds project dependencies in the background, as well as other possible long-running tasks it performs.
Unfortunately, I don't know if it's possible to configure it conveniently, so any advice is appreciated.

**Comment by yyoncho** [comment]
> It would be really nice to see it when rls initially builds project dependencies in the background, as well as other possible long-running tasks it performs.
Unfortunately, I don't know if it's possible to configure it conveniently, so any advice is appreciated

Such a configuration does not exist ATM and I am not sure whether the initial messages are different from the messages received during completion. You may check that by setting lsp-print-io and then inspecting the client-server communication. Then in case, this is possible you may customize the `rls` client `request-handler` map with your custom handler or if you think that this could be useful for the other users you could open a PR introducing a customization option.

**Comment by valignatev** [comment]
Thanks! Will try to inspect the output closer and see what I can do.
