### ISSUE TITLE
Support workspace/workspaceFolders request method

### ISSUE THREAD

**Issue by rlivings39** [emacs-lsp/lsp-mode#1045]
This method is supported as of [LSP 3.6](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#workspace_workspaceFolders) when multi-workspace folders were supported. It is convenient to query this at some points rather than doing the accounting of adding a deleting folders based on the DidChangeWorkspaceFolders event.

This came up in https://github.com/EmmyLua/EmmyLua-LanguageServer/issues/10 as well where the user mentioned shadowing `lsp-warn` to get around the warning.

**Comment by yyoncho** [comment]
@rlivings39 I added support for emmy lua, but I didnt hit https://github.com/EmmyLua/EmmyLua-LanguageServer/issues/10 , can you help with the steps to reproduce the issue so I can test the method?

**Comment by rlivings39** [comment]
Sure thing. I hit this while learning the protocol and working with a toy server. If I fork and add something representative to Microsoft's [lsp-sample](https://github.com/Microsoft/vscode-extension-samples/tree/master/lsp-sample) server would that be enough for you to test?

**Comment by yyoncho** [comment]
Yes.

**Comment by rlivings39** [comment]
https://github.com/rlivings39/vscode-extension-samples has my example in the `lsp-sample` folder. Search the file `lsp-sample/server/src/server.ts` for my username `rlivings39` to see the usage of workspace folder queries.

To set up:
```bash
git clone git@github.com:rlivings39/vscode-extension-samples.git
cd vscode-extension-samples/lsp-sample
npm install
npm run compile
```

Edit `lsp-sample.el` to point to `server/out/server.js` in your clone. Then

1. Open Emacs
2. `M-x load-file /path/to/lsp-sample.el`
3. Open any `.txt` file and start `lsp-mode`
4. Notice the warning in Emacs: `Warning (lsp-mode): Unknown request method: workspace/workspaceFolders`
