### ISSUE TITLE
lsp-format-buffer when server supports textDocument/rangeFormatting but not textDocument/formatting

### ISSUE THREAD

**Issue by alypeng** [emacs-lsp/lsp-mode#1048]
Some servers have support for the `textDocument/rangeFormatting` capability but not the `textDocument/formatting` capability so `lsp-format-buffer` fails.

Examples:
- [vscode-html-languageserver](https://github.com/vscode-langservers/vscode-html-languageserver)
- [vscode-json-languageserver](https://github.com/vscode-langservers/vscode-json-languageserver)

Would it make sense for `lsp-format-buffer` to apply a range format to the content of the buffer when this is the case?

**Comment by yyoncho** [comment]
Sounds good to me, willing to provide a PR?

**Comment by alypeng** [comment]
I'll give it a go
