### ISSUE TITLE
Multiple clients per major mode?

### ISSUE THREAD

**Issue by phst** [emacs-lsp/lsp-mode#105]
Please correct me if I'm wrong, I've only studied the code a bit. IIUC `lsp-mode` currently only supports one client per mode and selects the one that was defined last. How about supporting more than one client (with different servers) per mode? Different servers could provide different capabilities, and `lsp-mode` could always select a server providing a certain capability. If more than one server provides some capability, the server to use could be picked using a priority property of the client. Does that sound reasonable?

**Comment by yyoncho** [comment]
@TysonAndre was right - #424 was duplicate. Described by @phst is the way VSCode works except that we have to merge some of the results (e. g. symbol search).
