### ISSUE TITLE
React Native LSP for Emacs?

### ISSUE THREAD

**Issue by sereymongkol** [emacs-lsp/lsp-mode#1054]
Hi, I just found out that there is a really useful lsp server provided by Microsoft for React Native. Here is a [link](https://github.com/Microsoft/vscode-react-native). If we could have this support for Emacs, it would useful for current react native developer and the future developer.

**Comment by yyoncho** [comment]
AFAICS there is no language server in that repo. There is WIP PR at https://github.com/emacs-lsp/dap-mode/pull/118 (cc @darioceccoli ).

I will close this report, and the work on support of react-native will be tracked in dap-mode repo.
