### ISSUE TITLE
lsp-clients-typescript-plugins does not specify :type

### ISSUE THREAD

**Issue by iquiw** [emacs-lsp/lsp-mode#1066]
**Describe the bug**

[lsp-clients-typescript-plugins](https://github.com/emacs-lsp/lsp-mode/blob/e4a230bdd4eba2eeb211dd87d16de0f616665179/lsp-clients.el#L139) does not specify `:type`, which causes CI failures for Emacs 26.1 and 26.2.

**To Reproduce**
Run Travis CI build, or run `cask exec ert-runner -t "!no-win"`.

**Expected behavior**
Test passed.

**Which Language Server did you use**
_N/A_

**OS**
On Travis CI.

**Error callstack**

```
In toplevel form:
lsp-clients.el:139:1:Error: defcustom for ‘lsp-clients-typescript-plugins’ fails to specify type
...............Test lsp-byte-compilation-test backtrace:

(snip)

Test lsp-byte-compilation-test condition:

    (cl-assertion-failed
     ((byte-compile-file
       (save-excursion
	 (find-library "lsp-clients")
	 (buffer-file-name)))
      "Failed to byte-compile" "/home/travis/build/emacs-lsp/lsp-mode/lsp-clients.el"))
```

**Comment by yyoncho** [comment]
@iquiw  Willing to work on that?

**Comment by iquiw** [comment]
I'm not sure what the correct type is.

Do you think `'(vector (plist :key-type symbol :value-type string))` is proper?

**Comment by iquiw** [comment]
> Do you think `'(vector (plist :key-type symbol :value-type string))` is proper?

Hmm, looks not.

**Comment by yyoncho** [comment]
I thought that you already have a PR. We may try to use `(repeat...` and then convert to vector when using to work around the fact that there is no `vector` type. I could take a look at that later today.

**Comment by iquiw** [comment]
It would be fine if you could take up this. Thank you.

Emacs Stack Exchange link I found, for the record.

* [customize - How to create a defcustom variable that accepts only a vector of strings? - Emacs Stack Exchange](https://emacs.stackexchange.com/questions/42531/how-to-create-a-defcustom-variable-that-accepts-only-a-vector-of-strings)
* [Defining New Types - GNU Emacs Lisp Reference Manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Defining-New-Types.html)

**Comment by yyoncho** [comment]
Thank you for the links, pushed a fix and the tests are now green.
