### ISSUE TITLE
Support for JSON Language Server

### ISSUE THREAD

**Issue by iquiw** [emacs-lsp/lsp-mode#1073]
I'm [working on this](https://github.com/iquiw/lsp-mode/commits/lsp-json).

Language server: https://github.com/vscode-langservers/vscode-json-languageserver

There are 2 issues I am facing.

1. Completion does not work while server responses `textDocument/completion`. I did not check the detail yet and it could be taken up separately.
2. With default setting (`lsp-clients-json-schemas` is `nil`), the language server does not detect any schema.
  In VSCode, its client also does not send schemas in default, but its server knows some well-known files, such as `package.json`, `tsconfig.json`, etc.
  Should we provide some schemas as default setting?

**Comment by yyoncho** [comment]
IMO we should have as much stuff working as possible by default and usually what vscode does by default can be used as a reference.

AFAICS vscode sends the following notification which is not present in your code:

```
[Trace - 7:11:12 PM] Sending notification 'json/schemaAssociations'.
Params: {
    "vscode://defaultsettings/keybindings.json": [
        "vscode://schemas/keybindings"
    ],
    "/User/keybindings.json": [
        "vscode://schemas/keybindings"
    ],
    "vscode://defaultsettings/settings.json": [
        "vscode://schemas/settings/default"
    ],
    "/User/settings.json": [
        "vscode://schemas/settings/user"
    ],
    "/Machine/settings.json": [
        "vscode://schemas/settings/machine"
    ],
    "/Workspaces/*/workspace.json": [
        "vscode://schemas/workspaceConfig"
    ],
    "/**/*.code-workspace": [
        "vscode://schemas/workspaceConfig"
    ],
    "/User/locale.json": [
        "vscode://schemas/locale"
    ],
    "/.vscode/settings.json": [
        "vscode://schemas/settings/folder"
    ],
    "/.vscode/launch.json": [
        "vscode://schemas/launch"
    ],
    "/.vscode/tasks.json": [
        "vscode://schemas/tasks"
    ],
    "/User/snippets/*.json": [
        "vscode://schemas/snippets"
    ],
    "/**/*.code-snippets": [
        "vscode://schemas/global-snippets"
    ],
    "/.vscode/extensions.json": [
        "vscode://schemas/extensions"
    ],
    "/.devcontainer/devcontainer.json": [
        "file:///usr/share/code/resources/app/extensions/configuration-editing/schemas/devContainer.schema.json"
    ],
    "/.devcontainer.json": [
        "file:///usr/share/code/resources/app/extensions/configuration-editing/schemas/devContainer.schema.json"
    ],
    "/*.css-data.json": [
        "https://raw.githubusercontent.com/Microsoft/vscode-css-languageservice/master/docs/customData.schema.json"
    ],
    "/package.json": [
        "vscode://schemas/vscode-extensions",
        "file:///usr/share/code/resources/app/extensions/markdown-language-features/schemas/package.schema.json",
        "https://schemastore.azurewebsites.net/schemas/json/package.json",
        "file:///usr/share/code/resources/app/extensions/typescript-language-features/schemas/package.schema.json"
    ],
    "/*language-configuration.json": [
        "vscode://schemas/language-configuration"
    ],
    "/*icon-theme.json": [
        "vscode://schemas/icon-theme"
    ],
    "/*color-theme.json": [
        "vscode://schemas/color-theme"
    ],
    "/*.html-data.json": [
        "https://raw.githubusercontent.com/Microsoft/vscode-html-languageservice/master/docs/customData.schema.json"
    ],
    "/.bowerrc": [
        "https://schemastore.azurewebsites.net/schemas/json/bowerrc.json"
    ],
    "/.babelrc": [
        "https://schemastore.azurewebsites.net/schemas/json/babelrc.json"
    ],
    "/.babelrc.json": [
        "https://schemastore.azurewebsites.net/schemas/json/babelrc.json"
    ],
    "/jsconfig.json": [
        "https://schemastore.azurewebsites.net/schemas/json/jsconfig.json",
        "file:///usr/share/code/resources/app/extensions/javascript/schemas/jsconfig.schema.json"
    ],
    "/jsconfig.*.json": [
        "https://schemastore.azurewebsites.net/schemas/json/jsconfig.json",
        "file:///usr/share/code/resources/app/extensions/javascript/schemas/jsconfig.schema.json"
    ],
    "/*.schema.json": [
        "http://json-schema.org/draft-07/schema#"
    ],
    "/bower.json": [
        "https://schemastore.azurewebsites.net/schemas/json/bower.json"
    ],
    "/composer.json": [
        "https://getcomposer.org/schema.json"
    ],
    "/tsconfig.json": [
        "https://schemastore.azurewebsites.net/schemas/json/tsconfig.json",
        "file:///usr/share/code/resources/app/extensions/typescript-basics/schemas/tsconfig.schema.json"
    ],
    "/tsconfig.*.json": [
        "https://schemastore.azurewebsites.net/schemas/json/tsconfig.json",
        "file:///usr/share/code/resources/app/extensions/typescript-basics/schemas/tsconfig.schema.json"
    ],
    "/tsconfig-*.json": [
        "file:///usr/share/code/resources/app/extensions/typescript-basics/schemas/tsconfig.schema.json",
        "https://schemastore.azurewebsites.net/schemas/json/tsconfig.json"
    ],
    "/typings.json": [
        "https://schemastore.azurewebsites.net/schemas/json/typings.json"
    ],
    "/.condarc": [
        "file:///home/kyoncho/.vscode/extensions/ms-python.python-2019.9.34911/schemas/condarc.json"
    ],
    "/environment.yml": [
        "file:///home/kyoncho/.vscode/extensions/ms-python.python-2019.9.34911/schemas/conda-environment.json"
    ],
    "/meta.yaml": [
        "file:///home/kyoncho/.vscode/extensions/ms-python.python-2019.9.34911/schemas/conda-meta.json"
    ]
}
```

**Comment by iquiw** [comment]
> IMO we should have as much stuff working as possible by default and usually what vscode does by default can be used as a reference.

I see.

> AFAICS vscode sends the following notification which is not present in your code:

Overlooked, thanks!

**Comment by kiennq** [comment]
Hey, what is the status of `lsp-json`?
I'm working on [similar thing](https://github.com/kiennq/lsp-mode/commits/feat/lsp-json) and wonder if we can work together to give this an PR ASAP?
For now I'm at the point of being able to show the completion candidate (via `company-lsp`), however since the trigger characters for the json language server is `[" :]`, I have to type double double quote (`""`) before the completion candidate can be shown up.
![f1244a60-ec71-4939-9d4f-52bac1933551](https://user-images.githubusercontent.com/2631472/70637238-3f313a00-1c7a-11ea-8afa-6ea610addb33.gif)

**Comment by yyoncho** [comment]
@kiennq company-lsp does not initialize `company-auto-complete-chars`. IMO we should also check what is the previous char after insertion of company-lsp and eventually trigger a second completion.

**Comment by kiennq** [comment]
@yyoncho Can you elaborate more? Is there any example somewhere? I'm not particularly familiar with company mode so ...

**Comment by yyoncho** [comment]
@kiennq 
> however since the trigger characters for the json language server is [" :],

I believ ethat if company-auto-complete-chars are correctly set to the `[" :]` then you wont have to type double ".

**Comment by kiennq** [comment]
Turns out the reason is because `company-lsp` purposely  don't do completion with string or comment. And `"` is string opening.
Setting `  :completion-in-comments? t` solve that.

**Comment by yyoncho** [comment]
@kiennq ah, yes. We should revisit all language server settings regarding completion in comments.

**Comment by iquiw** [comment]
@kiennq Thank you for taking up this!

I have some concern & wish.

* It uses https://schemastore.azurewebsites.net, which I suppose http://schemastore.org mirror (for VSCode ?). Its site policy and "term of use" are not clear to me. So I think it is better to use http://schemastore.org instead.
* It is better to have an option to disable `json/schemaAssociations` notification for those who don't want to use these external sites.

**Comment by kiennq** [comment]
> * It uses https://schemastore.azurewebsites.net, which I suppose http://schemastore.org mirror (for VSCode ?). Its site policy and "term of use" are not clear to me. So I think it is better to use http://schemastore.org instead.

Ah, I didn't know about that. I agree, we should switch to http://schemastore.org instead of https://schemastore.azurewebsites.net

> * It is better to have an option to disable `json/schemaAssociations` notification for those who don't want to use these external sites.

Can you elaborate more why we need this?
User can set `lsp-json-schemas` to have some degrees of schema overriding though.

**Comment by iquiw** [comment]
> Can you elaborate more why we need this?
> User can set lsp-json-schemas to have some degrees of schema overriding though.

Just for one's policy/preference. Well, I am not sure the actual need. Maybe not necessary.

**Comment by kiennq** [comment]
@iquiw Thank you, I will update the schema link in next PR.

@yyoncho I notice that there's no *async* request handler in `lsp-mode`. Would it be fine for me to add something similar to that?
The reason is because json language server request client to serve it url content (or file content) with `vscode/content`. That operation currently is blocking (sync) and may take time to finish.

I think `async-request-handlers` can take something like `(workspace request params callback)` as parameters and require to call `callback` on its result. What do you think?

**Comment by yyoncho** [comment]
Already added by @kiennq

**Comment by shubham-cpp** [comment]
How one would set this

```elisp
(setq lsp-json-schemas '(("package.json" "https://schemastore.azurewebsites.net/schemas/json/package.json")))
```

gives error. Wrong argument type symbolp

**Comment by yyoncho** [comment]
AFAICS package.json is already set it  `lsp-json--schema-associations` you may want to change that variable.

**Comment by shubham-cpp** [comment]
But then I don't get any completions within package.json. I'm using doom emacs with emacs 27.2.(I've enabled the json lsp and it's active)

**Comment by yyoncho** [comment]
I tested with M-x lsp-start-plain and it works fine. What OS do you use?

**Comment by shubham-cpp** [comment]
Npx envinfo
```bash
System:
    OS: Linux 5.15 void
    CPU: (4) x64 AMD A8-6410 APU with AMD Radeon R5 Graphics
    Memory: 4.83 GB / 6.75 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.9.1 - /usr/bin/node
    Yarn: 1.22.17 - ~/.local/share/npm/bin/yarn
    npm: 7.21.1 - /usr/bin/npm
  Utilities:
    Make: 4.3 - /usr/bin/make
    GCC: 10.2.1 - /usr/bin/gcc
    Git: 2.34.1 - /usr/bin/git
  IDEs:
    Emacs: 27.2 - /usr/bin/emacs
  Databases:
    SQLite: 3.37.2 - /usr/bin/sqlite3
  Browsers:
    Firefox: 95.0.1
```

**Comment by yyoncho** [comment]
I tested with gitpod https://gitpod.io/#ORG=emacs-lsp,PROJECT=demo-projects,PROFILE=vanilla/https://github.com/emacs-lsp/lsp-gitpod (also with doom config).

**Comment by shubham-cpp** [comment]
Ok, I re-installed doom emacs with only lsp and json+lsp enabled and it works.
Maybe its and issue with config. Sorry for false alarm
