### ISSUE TITLE
Investigate replacing travis with emacs github action 

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#1081]
Link: https://github.com/marketplace/actions/set-up-emacs

**Comment by ericdallo** [comment]
`lsp-dart` is [using `set-up-emacs` action](https://github.com/emacs-lsp/lsp-dart/blob/master/.github/workflows/test.yml)

**Comment by ericdallo** [comment]
Migrated `lsp-java` to use GH actions too: https://github.com/emacs-lsp/lsp-java/pull/218

**Comment by yyoncho** [comment]
We are done here.
