### ISSUE TITLE
[Rust] Setting lsp-rust-clippy-preference to "on" produces no effect

### ISSUE THREAD

**Issue by SamirHafez** [emacs-lsp/lsp-mode#1083]
The Rust LSP implementation provides a `lsp-rust-clippy-preference` variable which states:

```
"Controls eagerness of clippy diagnostics when available. Valid values are (case-insensitive):
- \"off\": Disable clippy lints.
- \"opt-in\": Clippy lints are shown when crates specify `#![warn(clippy)]`.
- \"on\": Clippy lints enabled for all crates in workspace.
You need to install clippy via rustup if you haven't already."
```

By default, this variable is set to `opt-in` but changing it to either `off` or `on` doesn't seem to produce the desired effect (I still need to explicitly set the macro for the diagnostics to pop-up). 

I've tried setting the variable and restarting the process (both `rls` and `emacs`) to no avail.

I've confirmed that the `vscode` implementation produced the expected results on my machine against the same `rustup` `cargo` `rls` and `clippy` versions.

**Comment by yyoncho** [comment]
I am not Rust user, I even do not know what clippy is(lsp-mode supports 30+ languages). Can you provide sample project + what you are doing + what is happening + what is expected to happen?
