### ISSUE TITLE
How to ignore folder for watch

### ISSUE THREAD

**Issue by ztlevi** [emacs-lsp/lsp-mode#1085]
I am running a bazel project and it has some local symlinks in the projects stores the build, e.g. bazel-out, bazel-genfiles. 

bazel-code is symlinked to `/home/ztlevi/.cache/bazel/_bazel_user/933c2f549343e099e3a6911b282cb71c/execroot/{project_root}/` and it's being watched by lsp-mode.

Even if I add entries to `lsp-file-watch-ignored`, files linked to `.cache` is still being watched. How to make lsp-mode ignore watching these files?
```
  (dolist (dir '(
                 "[/\\\\]bazel-*"
                 "[/\\\\]\\.cache"
                 "[/\\\\]_build"
                 "[/\\\\]\\.clwb$"
                 ))
    (push dir lsp-file-watch-ignored))
```

**Comment by yyoncho** [comment]
Can you do `M-x trace-function RET lsp--string-match-any RET` and check the trace buffer?

**Comment by ztlevi** [comment]
I got this. The last item is a folder in the project. Not sure when did this one added to `lsp-file-watch-ignored`.
```
1 <- lsp--string-match-any: nil
 ======================================================================
 1 -> (lsp--string-match-any ("[/\\\\]\\.clwb$" "[/\\\\]_build" "[/\\\\]\\.cache" "[/\\\\]bazel-*" "[/\\\\]\\.pytest-cache$" "[/\\\\]\\.mypy-cache$" "[/\\\\]\\.ccls-cache$" .... "[/\\\\]target$" "[/\\\\]\\.deps$" "[/\\\\]build-aux$" "[/\\\\]autom4te.cache$" "[/\\\\]\\.reference$") "/home/ztlevi/{project_root}/{sub_dir}/subsystems/metadata/test_bench/..")
 1 <- lsp--string-match-any: nil
```

**Comment by yyoncho** [comment]
As you can see the regexes that you have added do not match the root folder, so the behaviour is the expected one.

**Comment by ztlevi** [comment]
So what would be proper way to write the regex for folders outside the root of the project? I don't really understand the `[/\\\\]` part, looks like a different regex standard for me...

**Comment by yyoncho** [comment]
@ztlevi AFAICS you have to prepare a regex which matches the path to the symlink and if you simply put the full path to it will match, e. g. something simple `subsystems/metadata/test_bench` will work.

**Comment by yyoncho** [comment]
I am closing the issue since apparently there is no bug, in the code. 

 `[/\\\\] `

means any of `\/`

**Comment by benmaia** [comment]
@ztlevi did you fixed it?

**Comment by ztlevi** [comment]
@benmaia  Yes. https://github.com/ztlevi/doom-config/blob/bfb9f0a3c46131869f69fdc0fc3b22435cf3df19/%2Bprog.el#L140
