### ISSUE TITLE
Package ‘spinner-1.7.3’ is unavailable

### ISSUE THREAD

**Issue by jessekelly881** [emacs-lsp/lsp-mode#1095]
Firstly, I appologize for not following the recomended format, but considering the nature of this issue I figured that many of the recomended points were obvious. 

I am having issues installing lsp-mode. I have been trying for several days to get it installed with no result. When I try to install it using "package-install" I get the error "Package ‘spinner-1.7.3’ is unavailable" and I also cannot seem to install spinner.el either. I have the following package repo config:

(setq package-archives
      '(("GNU ELPA"     . "https://elpa.gnu.org/packages/")
        ("MELPA Stable" . "https://stable.melpa.org/packages/")
        ("MELPA"        . "https://melpa.org/packages/"))
      package-archive-priorities
      '(("MELPA Stable" . 10)
        ("MELPA"     . 5)
        ("GNU ELPA"        . 0)))

I have tried running "package-refresh-contents" before installing as adding the spinner.el repo as a submodule and using load to install spinner.el with no luck. I will keep trying to get this to work as I am extremely interesting in getting lsp-mode to work and I will post any progress I have installing it. But, if anyone know how to solve this issue I would greatly appreciate it. It will probably save me a lot of time and frustration. Haha. Thanks!

**Comment by jessekelly881** [comment]
Ah. So, I believe I got it working. Opening the spinner.el file and running package-install-file did the trick. Still, having to do this seems excessive. There must be a better way?

**Comment by brotzeit** [comment]
Does this work `gpg2 --keyserver hkp://pool.sks-keyservers.net:80 --homedir $HOME/.emacs.d/elpa/gnupg --recv-keys 066DAFCB81E42C40 || true` ?

**Comment by jessekelly881** [comment]
It works, as in, the command run successfully. However, I got it working with the method above. I.e. installing spinner.el manually. It seems like spinner.el isn't currently in melpa stable, melpa, or gnu elpa. Which is strange. I've had no problems with installing packages otherwise.

**Comment by brotzeit** [comment]
It is in elpa, but it seems you have to update the keyserver ? Somebody told me to use this command and it worked for me.

**Comment by seagle0128** [comment]
@jessekelly881 I think you missed this https://elpa.gnu.org/packages/gnu-elpa-keyring-update.html.

**Comment by jessekelly881** [comment]
Ah. I did indeed. Thanks!

**Comment by yyoncho** [comment]
Fixed by adding a FAQ entry.

**Comment by zoechi** [comment]
I was able to make it work by adding 
```
(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")
```
from https://emacs.stackexchange.com/questions/51721/failed-to-download-gnu-archive
and install `spinner` from GNU archive
