### ISSUE TITLE
Invalid type <nil> for []string option "experimentalDisabledAnalyses" in lsp-go

### ISSUE THREAD

**Issue by seagle0128** [emacs-lsp/lsp-mode#1096]
Recently many people got this error while using `lsp-go`. 

```elisp
LSP :: Invalid type <nil> for []string option "experimentalDisabledAnalyses"
```

**Comment by yyoncho** [comment]
@Gastove this seems to be related to your PR #1086, willing to take a look?

**Comment by seagle0128** [comment]
I found the root cause. It's related to https://github.com/emacs-lsp/lsp-mode/pull/1086. 

`lsp-gopls-experimental-disabled-analyses` should be an array while not a list according to https://github.com/golang/tools/blob/master/gopls/doc/settings.md#experimental.

**Comment by seagle0128** [comment]
I am trying to fix it, but more and more issues occur. e.g.

```elisp
LSP :: invalid config gopls.env type string
LSP :: unexpected config staticcheck
```

I'd like leave this to @Gastove to check all settings in #1086.

**Comment by Gastove** [comment]
Ruh-roh. @yyoncho yes, happy to take a look; I'm tied up for the next eight hours or so, but can dig in after that.

**Comment by yyoncho** [comment]
Sure, meanwhile we may revert the PR, @seagle0128 @Gastove  WDYT?

**Comment by seagle0128** [comment]
It's fine if @Gastove can fix soon, since the basic completion functionality does work well. Thank you!

**Comment by Gastove** [comment]
I'm content either way. I'll get to this as quick as I can, and the fix PR will be clearer if we don't revert.

**Comment by Gastove** [comment]
Hokay, one of these I misunderstood on the first pass, and the other I just straight-up got wrong.

So, just to make sure I now have this right: 
- `lsp-gopls-experimental-disabled-analyses` nees to be an array of strings, so should default to `[]`, not `(list)`
- `lsp-gopls-env` should serialize to an object, which means a list of pairs, right? E.G. `'(("ENV_VAR" . "var value"))`. 

@yyoncho can you confirm the above is correct?

**Comment by yyoncho** [comment]
Yes, you can use also plist and hash-table if you want to have a object on the wire.

**Comment by Gastove** [comment]
Great. Do y'all have a standard practice? I've no strong attachment to any particular approach, would rather do what's most normal.

**Comment by yyoncho** [comment]
We don't have a standard for this.
