### ISSUE TITLE
Investigate configuration errors from `gopls`

### ISSUE THREAD

**Issue by Gastove** [emacs-lsp/lsp-mode#1099]
While working on #1097, there were reports of this error emerging: 

`LSP :: unexpected config staticcheck`

It's not clear that this is an LSP problem, as many of the configuration parameters accepted by `gopls` are marked experimental, and `gopls` is under heavy, active development. However, it would be very good to make sure of this, and potentially update the docstrings of the `lsp-go` `defcustom`s to warn users about configurations with unexpected side-effects.

**Comment by Gastove** [comment]
@seagle0128 Can you post the configs you were using for `lsp-go` here, along with your current `gopls` version?

**Comment by seagle0128** [comment]
@Gastove  My lsp and go config is here: https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-lsp.el and https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-go.el .

The core config is below.
```elisp
(use-package lsp-mode
     :diminish lsp-mode
     :hook (prog-mode . lsp-deferred)
     :bind (:map lsp-mode-map
            ("C-c C-d" . lsp-describe-thing-at-point))
     :init (setq lsp-auto-guess-root t       ; Detect project root
                 lsp-prefer-flymake nil      ; Use lsp-ui and flycheck
                 flymake-fringe-indicator-position 'right-fringe))
```

**Comment by Gastove** [comment]
Thanks @seagle0128. I'll tuck in to this soon!

**Comment by seagle0128** [comment]
BTW, I updated gopls to the latest version just now and still get this error.

**Comment by muirrn** [comment]
Slightly off topic, but personally I don't think we should add gopls config flags to lsp-mode until they are stable. Things change frequently, and we will be left with a lot hard-to-delete experimental cruft once the dust settles. I would prefer an interface where users can set experimental config flags manually a la loosey-goosey JSON config in VSCode. For example:

```elisp
(lsp-configure 'gopls "crazySetting" "on")
```

That way it is all on the user to deal with experimental settings.

**Comment by psanford** [comment]
Yes I agree. The gopls team just renamed a bunch of the experimental flags recently.

**Comment by Gastove** [comment]
Uh, okay -- this feedback would have been very helpful when I PRed those flags in :grimacing: 

I'm not a core member of the `lsp-mode` team, just an enthusiastic user. Personally, marking those flags as `experimental` in the name seems fine to me, but again -- not *my* project. That said, I'm not going to put more time in tot debugging those flags until I hear for certain about their future.

How do y'all want to proceed?

**Comment by yyoncho** [comment]
> I'm not a core member of the lsp-mode team, just an enthusiastic user. Personally, marking those flags as experimental in the name seems fine to me, but again -- not my project.

lsp-mode project is a community-driven project so it doesn't matter whether someone is part of a code team or whatever. We do what makes sense and everyone's opinion will be taken into account. We try to do what will be the best for the users not what maintainers want :)

**Comment by Gastove** [comment]
> lsp-mode project is a community-driven project so it doesn't matter whether someone is part of a code team or whatever. We do what makes sense and everyone's opinion will be taken into account. We try to do what will be the best for the users not what maintainers want :)

Appreciated very much! Just trying not to step on any toes :sweat_smile: Thanks, sir.

**Comment by muirrn** [comment]
Moving hijack discussion to #1100

**Comment by Gastove** [comment]
Okay, an update on the original topic of this issue: digging in to `gopls`, I have found that this is the list of default analyzers:

```go
var defaultAnalyzers = []*analysis.Analyzer{
	// The traditional vet suite:
	asmdecl.Analyzer,
	assign.Analyzer,
	atomic.Analyzer,
	atomicalign.Analyzer,
	bools.Analyzer,
	buildtag.Analyzer,
	cgocall.Analyzer,
	composite.Analyzer,
	copylock.Analyzer,
	httpresponse.Analyzer,
	loopclosure.Analyzer,
	lostcancel.Analyzer,
	nilfunc.Analyzer,
	printf.Analyzer,
	shift.Analyzer,
	stdmethods.Analyzer,
	structtag.Analyzer,
	tests.Analyzer,
	unmarshal.Analyzer,
	unreachable.Analyzer,
	unsafeptr.Analyzer,
	unusedresult.Analyzer,
	// Non-vet analyzers
	sortslice.Analyzer,
}
```
`staticcheck` is only added if the (experimental!) `lsp-gopls-experimental-staticcheck` var is non-nil, which it is not by default. So -- if `staticcheck` is part of disabled checkers, it will error unless staticheck has explicitly been enabled. Otherwise, it's a problem with `gopls` reading its own options :upside_down_face:

**Comment by seagle0128** [comment]
@Gastove As @yyoncho mentioned above, `lsp-mode` is a community-driven project, and we respect all opinions and suggestion. I was a user, then a contributor, now a collaborator. So don't worry about it! BTW, @yyoncho is very kind and enthusiastic.

I agree to just add stable options for now to keep the project stable and clean.

**Comment by Gastove** [comment]
Thanks, @seagle0128 -- appreciated. Like I say, I just... am fussy about landing too hard on things before I have full context :) 

In other news: I'm pretty sure this is _not_ a problem with `lsp-mode`; IMHO this ticket can be closed :+1:

**Comment by yyoncho** [comment]
Closing based on(reopen if you disagree):

> Otherwise, it's a problem with gopls reading its own options

As a side note, once lsp-mode starts to manage the server download process we will be able to ensure what that lsp-mode is configured to work against a particular server version. ATM `latest` is pretty random...

**Comment by jsravn** [comment]
I'm getting this error after a recent update to lsp-mode. `lsp-gopls-experimental-staticcheck` is set to `nil`. Any ideas?

**Comment by yyoncho** [comment]
@jsravn see https://github.com/emacs-lsp/lsp-mode/issues/1099#issuecomment-544584178
