### ISSUE TITLE
Consider ad-hoc config interface

### ISSUE THREAD

**Issue by muirrn** [emacs-lsp/lsp-mode#1100]
We have been recently adding experimental gopls config flags to lsp-mode. The elisp variables have "experimental" in their names, but I'm not sure we will be able to easily delete the variables when the config flags are removed/changed in gopls.

I like "first class" elisp variables for stable config options, but for unstable config values I propose we switch to an ad-hoc interface where the user can easily try out settings without immortalizing them as lsp-mode variables. 

For example, the interface might look something like:

```elisp
(lsp-configure 'gopls "crazySetting" "on")
```

This way users can easily play around with settings and lsp-mode doesn't need to accumulate experimental config baggage.

We can also update the Emacs docs on the gopls side accordingly.

**Comment by yyoncho** [comment]
I think that we support that ATM:

```
(defvar lsp-pyls-rope-rope-folder nil)
(lsp-register-custom-settings '(("pyls.rope.ropeFolder" lsp-pyls-rope-rope-folder)))
```

**Comment by muirrn** [comment]
My proposal has two main differences with the existing way to define options:
1. A single step (easier for users to play around with)
1. Doesn't require defining a variable

My goal was something as easy as setting a variable but without the need to define a variable.

My proposal also makes it easier (?) to validate the user configured a valid server id. We could also have a list of all possible config flags and issue a warning if the user configures an invalid option.

**Comment by yyoncho** [comment]
We can wrap that in a macro and make it a single step and cover 1/2. 

> My proposal also makes it easier (?) to validate the user configured a valid server id. 

ATM there is no mapping `config section` -> `server-id`. Also, some of the servers have multiple config sections. The section is encoded in the variable path, just like vscode does.
