### ISSUE TITLE
Clean up use of `:type (vector string)`

### ISSUE THREAD

**Issue by Gastove** [emacs-lsp/lsp-mode#1106]
In a recent set of PRs (#1086, #1097), there was a little confusion about the correct `:type` key for representing vectors of strings. To summarize: `:type '(vector string)` is valid elisp, but not the type we want, as it specifies a _vector of length 1_, specifically. The correct `:type` is a `restricted-sexp`, using a function that `and`s `vectorp` with checking that all elements are of type `string`. 

Just to add flavor: the two _existing_ usages of `restricted-sexp`, both in `lsp-rust`, are incorrect. (They use the form `restricted-sexp :match-alternatives (lambda (xs)`, which doesn't work -- the argument to `:match-alternatives` is a list, not a function.)

To make this easier to get right, particularly for newcomers, I propose defining a new `:type`, `lsp-vector`. [New types](https://www.gnu.org/software/emacs/manual/html_node/elisp/Defining-New-Types.html#Defining-New-Types) are declared as new "widgets" (thanks Emacs, that's very obvious). As a first pass, this could look like so: 

```emacs-lisp
(defun lsp--string-vector-p (candidate)
  "Returns true if CANDIDATE is a vector data structure, and
every element of it is of type string."
  (and
   (vectorp candidate)
   (seq-every-p #'stringp candidate)))

(define-widget 'lsp-string-vector 'lazy
       "A vector of any length, every element of which is a string."
       :offset 4
       :tag "Vector"
       :type '(restricted-sexp
               :match-alternatives (list #'lsp--string-vector-p)))
```
This could then be used like: 
```emacs-lisp
(defcustom lsp-cool-variable ["arg"] "a variable"
    :type lsp-string-vector)
```

**Comment by yyoncho** [comment]
Looks good to me. We may consider renaming the type to `lsp-json-string-array` since this is what it really represents.

cc @iquiw

**Comment by yyoncho** [comment]
`lsp-string-vector` is good enough.

**Comment by seagle0128** [comment]
I will update `lsp-python-ms` once this PR is merged.
