### ISSUE TITLE
C# completion - candidates don't match the context

### ISSUE THREAD

**Issue by sebasmonia** [emacs-lsp/lsp-mode#1108]
**Describe the bug**

In C#, completion suggests items that are outside the current context. Example, if I type `this.` I would expect to get a list of items for the current class, instead I get...basically everything (namespaces, functions, etc.)

![image](https://user-images.githubusercontent.com/1651857/66951537-d467d780-f017-11e9-90b5-e6ae130725e4.png)

Also in some circumstance I get...almost nothing:

![image](https://user-images.githubusercontent.com/1651857/66951531-d2057d80-f017-11e9-9915-648c823569ba.png)

**Which Language Server did you use**
Omsnisharp-roslyn

**OS**
Windows 10

**Error callstack**
No error

Can't include logs from my current project, but can try to generate a minimal solution _soon_.

**Comment by yyoncho** [comment]
lsp-mode is responsible only for showing the completions, not for calculating them. The server is doing that. So we should gather enough information and report it upstream.

**Comment by sebasmonia** [comment]
Hi, sorry it took me this long to get back to you. I tried a minimal project and got the same result.
I set `(setq lsp-print-io t)` but couldn't see any log info in a buffer or Messages? Couldn't gather from the lsp-mode code where it logs :)

I tested with a different LSP package the completion results are different:

![image](https://user-images.githubusercontent.com/1651857/67352736-0b555600-f50e-11e9-86fc-db4e9a39da80.png)

Compared to lsp-mode, which for that context is picking up some global keywords:

![image](https://user-images.githubusercontent.com/1651857/67352759-1b6d3580-f50e-11e9-8edd-cc56c0f86963.png)

Since the test project is not part of a repository I also get a warning that the file is not in the project or it is blacklisted, don't know if that's related?
Anyway this comparison is why I think the issue might be some configuration between lsp-mode and the omnisharp server, rather than server error.

I know and appreciate how much the lsp-mode team cares about a good out of the box experience so if we can adjust something to make it better, let's give it a try!

**Comment by yyoncho** [comment]
> Hi, sorry it took me this long to get back to you. I tried a minimal project and got the same result.
I set (setq lsp-print-io t) but couldn't see any log info in a buffer or Messages? 

Use lsp-workspace-show-logs.


> Since the test project is not part of a repository I also get a warning that the file is not in the project or it is blacklisted, don't know if that's related?

This message means that lsp-mode is not started in the buffer. Can you verify that by lsp-describe-session? In case it is not part of a project, please make sure that you have lsp-auto-guess-root set no nil and reopen the project? If you still get that message you have probably blacklisted the project - use lsp-workspace-blacklist-remove to fix that.

**Comment by sebasmonia** [comment]
`lsp-auto-guess-root` is set to `t`, after reading that variable I created a .projectile file and now LSP starts when I open the buffer.

Completion is back to the very first screenshot, where after the dot I get _everything_ under the sun.

The log buffer shows the data below, which seems like an Omnisharp problem, but I see similar exceptions for eglot and still get completion, so maybe there's a workaround.

One thing that I recalled now looking at my config, is that sometimes the server sends a `nil` response for markup, and I adviced a function in eglot to replace nil with empty string to avoid breakage.

I see no errors for lsp though.

```
Handler Selected: OmniSharp.LanguageServerProtocol.Handlers.OmniSharpSignatureHelpHandler via [**/*.cs], [**/*.csx] (targeting OmniSharp.Extensions.JsonRpc.IJsonRpcRequestHandler`2[[OmniSharp.Extensions.LanguageServer.Protocol.Models.SignatureHelpParams, OmniSharp.Extensions.LanguageProtocol, Version=0.13.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022],[OmniSharp.Extensions.LanguageServer.Protocol.Models.SignatureHelp, OmniSharp.Extensions.LanguageProtocol, Version=0.13.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]])
Starting: Routing Request (36) textDocument/signatureHelp
Converting params for Request (36) textDocument/signatureHelp to OmniSharp.Extensions.LanguageServer.Protocol.Models.SignatureHelpParams
Failed to handle notification textDocument/signatureHelp - System.NullReferenceException: Object reference not set to an instance of an object.

   at OmniSharp.LanguageServerProtocol.Handlers.OmniSharpSignatureHelpHandler.<Handle>d__3.MoveNext() in D:\a\1\s\src\OmniSharp.LanguageServerProtocol\Handlers\OmniSharpSignatureHelpHandler.cs:line 45

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.<Handle>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>d__6.MoveNext()
Finished: Routing Request (36) textDocument/signatureHelp in 0ms
```

**Comment by yyoncho** [comment]
I guess there is slight differences in the initialization request which breaks lsp-mode. Can you include the client/server log from both?

**Comment by sebasmonia** [comment]
[lsp-log.txt](https://github.com/emacs-lsp/lsp-mode/files/3791960/lsp-log.txt)
[eglot-events.txt](https://github.com/emacs-lsp/lsp-mode/files/3791961/eglot-events.txt)

Attached the two logs. Hope you find them useful! The program code is very simple, line 15 char 20 is where completion is triggered.
```
using System;

namespace testapp
{
    class Program
    {
        private static int a_number;

        static void Main(string[] args)
        {

            System.Diagnostics.Debugger.Launch();
            System.Diagnostics.Debugger.Break();
            Console.WriteLine("Hello World!");
            Program.
            System.Diagnostics.Debugger.Break();
            Console.WriteLine("Bye  World!");
        }
    }
}
```

**Comment by razzmatazz** [comment]
The issue here was that omnisharp-roslyn didn't sync the file properly. I have a PR for omnisharp-roslyn that fixes this (at least for me):
 - https://github.com/OmniSharp/omnisharp-roslyn/pull/1754

**Comment by sebasmonia** [comment]
Thinking we should close this since #1125 is tracking it.

@yyoncho or @razzmatazz do you know why I can work fine with Omnisharp in Eglot, but needs the additional fix for lsp-mode?

And thank you for the follow up in #1125 and PRs submitted to Omnisharp-roslyn. Can't wait to test lsp-mode w/ Roslyn :)

**Comment by yyoncho** [comment]
@sebasmonia IIRC it is side effect from lsp-mode using hash-tables and eglot using plists. If the server returns nil (incorrectly) the hashtable operation will fail while plist operation will be successful. Generally, we could add guards against this invalid input. But AFAIK the server is in bad state either way, right, @razzmatazz ?

**Comment by sebasmonia** [comment]
Thank you! 
Like I said, I'm ok to close this issue.

**Comment by razzmatazz** [comment]
> @sebasmonia IIRC it is side effect from lsp-mode using hash-tables and eglot using plists. If the server returns nil (incorrectly) the hashtable operation will fail while plist operation will be successful. Generally, we could add guards against this invalid input. But AFAIK the server is in bad state either way, right, @razzmatazz ?

I am not the original developer of omnisharp server nor someone who is involved a lot, but it appears LSP was/is second-class operation mode (in contrast to native custom protocol) of omnisharp-roslyn server thus there are still rough edges on LSP implementation. It returns null/invalid responses because internally LSP is a layer on top of a native omnisharp-protocol bits which does not always map 1:1 to LSP thus the impedance mismatch, and frankly, the LSP layer was not getting tested that much so far.

Hopefully, withthe  basics working we will get more C# users of LSP mode of omnisharp and thus more fixes in the form of PRs to omnisharp-roslyn :)

**Comment by sebasmonia** [comment]
Created https://github.com/OmniSharp/omnisharp-roslyn/issues/1806, posting here since the other ticket is closed now.

**Comment by yyoncho** [comment]
@razzmatazz do you think there is anything to do or this issue on lsp-mode side?

**Comment by razzmatazz** [comment]
@yyoncho I am pretty sure the original issue (related to documents-being-out-of-sync) has been fixed with the latest versions of the server.

**Comment by yyoncho** [comment]
Thank you, I am closing the issue.
