### ISSUE TITLE
Support toggling lsp-mode

### ISSUE THREAD

**Issue by Wilfred** [emacs-lsp/lsp-mode#111]
`M-x lsp-mode` followed by `M-x lsp-mode` again produces `user-error: LSP mode is already enabled for this buffer`. I'd expect a second `lsp-mode` to disable the mode.

**Comment by alanz** [comment]
There is a draft implementation of this [here](https://github.com/alanz/lsp-mode/tree/toggle-rebased-2) but it is not standards-compliant, and I do not know enough to make it so. 

See also https://github.com/emacs-lsp/lsp-mode/pull/82

**Comment by phst** [comment]
Similarly, `(lsp-mode 0)` should turn `lsp-mode` off.
