### ISSUE TITLE
(file-error "Read error" "Is a directory" "/path/to/a/directory")

### ISSUE THREAD

**Issue by JohnC32** [emacs-lsp/lsp-mode#1113]
When running lsp-find-references on a heavily used C++ class (I'm using lsp-mode with ccls), sometimes I see:

    Debugger entered--Lisp error: (file-error "Read error" "Is a directory" "/path/to/a/directory")
      insert-file-contents("" nil nil nil nil)
      insert-file-contents-literally("")
      #[514 .....
      apply(#[514 .....
      #[128 .....
      mapcar(#[128 .....
      #[514 .....
      apply(#[514 .....
      seq-map(#[128 .....
      lsp-find-references()
      funcall-interactively(lsp-find-references)
      call-interactively(lsp-find-references nil nil)
      command-execute(lsp-find-references)

lsp--locations-to-xref-items, is calling (file-readable-p filename) and (insert-file-contents-literally filename), with filename equal to "". This causes it to insert the current directory. 

Why is filename empty?

I can work around the problem by modifying lsp--locations-to-xref-items to protect against an empty file name using the following "FIX". However this seems like it is masking a more fundamental issue. Can you help provide more insight as to what I can do to get to the root cause of the empty filename?

Thanks

````emacs-lisp
(defun lsp--locations-to-xref-items (locations)
  "Return a list of `xref-item' from Location[] or LocationLink[]."
  (setq locations (if (sequencep locations) locations (list locations)))

  (unless (seq-empty-p locations)
    (cl-labels ((get-xrefs-in-file
                 (file-locs location-link)
                 (let ((filename (seq-first file-locs)))
                   (when (not (equal filename ""))        ;;;          FIX?????
                     (let ((visiting (lsp--buffer-for-file filename))
                           (fn (lambda (loc)
                                 (lsp--xref-make-item filename
                                                      (if location-link (or (gethash "targetSelectionRange" loc)
                                                                      (gethash "targetRange" loc))
                                                        (gethash "range" loc))))))
                       (if visiting
                           (with-current-buffer visiting
                             (seq-map fn (cdr file-locs)))
                         (when (file-readable-p filename)
                           (with-temp-buffer
                             (insert-file-contents-literally filename)
                             (seq-map fn (cdr file-locs))))))))))
      (apply #'append
             (if (gethash "uri" (seq-first locations))
                 (seq-map
                  (-rpartial #'get-xrefs-in-file nil)
                  (seq-group-by
                   (-compose #'lsp--uri-to-path (-partial 'gethash "uri"))
                   locations))
               (seq-map
                (-rpartial #'get-xrefs-in-file t)
                (seq-group-by
                 (-compose #'lsp--uri-to-path (-partial 'gethash "targetUri"))
                 locations)))))))

````

**Comment by yyoncho** [comment]
The issue seems to be on the server(not providing the uri) but it might be lsp-mode not reading the correct map key. Can you provide the client-server communication for that request?

**Comment by JohnC32** [comment]
I'm very new to lsp-mode and just setting it up and thus not that familiar with the structure. How do I get the client-server communication?

**Comment by JohnC32** [comment]
Thanks for the tip. The log is 26K lines long. I'm not familiar with the protocol. I do see numerous entries of the form. Every uri has a valid file name on disk (it's always a *.cpp or *.hpp) file.

    [Trace - 09:51:37 AM] Sending request 'textDocument/hover - (124)'.
    Params: {
      "textDocument": {
        "uri": "file:///path/to/some/file.cpp"
      },
      "position": {
        "line": 21,
        "character": 23
      }
    }

After a number of these, I see:

    [Trace - 09:51:37 AM] Received response 'textDocument/hover - (124)' in 9ms.
    Result: {
      "range": {
        "end": {
          "character": 37,
          "line": 21
        },
        "start": {
          "character": 22,
          "line": 21
        }
      },
      "contents": [
        "doc description text",
        {
          "value": "class NAME {}",
          "language": "cpp"
        }
      ]
    }

To me the data from the server seems correct (I have another non-emacs front end using ccls which has no issue).

**Comment by yyoncho** [comment]
You should look for `textDocument/references` and for the corresponding response.

**Comment by JohnC32** [comment]
There are two entries:

    [Trace - 10:20:47 AM] Sending request 'textDocument/references - (35)'.
    Params: {
      "textDocument": {
        "uri": "file:///path/to/file.cpp"
      },
      "position": {
        "line": 21,
        "character": 25
      },
      "context": {
        "includeDeclaration": false
      }
    }
    
    
    [Trace - 10:20:48 AM] Received response 'textDocument/references - (35)' in 542ms.
    Result: [
      {
        "range": {
          "end": {
            "character": 27,
            "line": 21
          },
          "start": {
            "character": 12,
            "line": 21
          }
        },
        "uri": "file:///path/to/file.cpp"
      },
      .....
      ]

I did validate all uri paths are existing plain files by saving the log to log.txt and running the following checkit.pl to verify all paths are good.

```` perl
use strict;
use warnings;
use File::Slurp;

my @contents = read_file('log.txt');

foreach my $line (@contents) {
    if ($line =~ /^\s*"uri"\s*:\s*"file:\/\/([^"]+)"/) {
        my $file = $1;
        if ($file !~ /\.(?:cpp|hpp)$/) {
            die "$file is not a C/C++ file";
        }
        if (-f $file) {
            print "$file: ok\n";
        } else {
            die "! -f $file";
        }
    }
}

````

**Comment by yyoncho** [comment]
can you validate that all entries have uri key?

**Comment by JohnC32** [comment]
There is one entry that is invalid (my prior perl script missed it):

    {
      "range": {
        "end": {
          "character": 56,
          "line": 25
        },
        "start": {
          "character": 41,
          "line": 25
        }
      },
      "uri": "file://"
    },

In case it helps, I used this script to find it because the size is too large to visually parse.

````perl
use strict;
use warnings;
use JSON;

my $response;

open(my $fh, "<", "log.txt") || die "open: $!";
my $found=0;
while (my $line = <$fh>) {
    if ($found==0) {
        if ($line =~ /^\[Trace - [^]]+\] Received response 'textDocument\/references/) {
            $found = 1;
        }
    } else {
        $response .= $line;
        if ($line =~ /^\]/) {
            $found = 2;
            last;
        }
    }
}
close($fh) || die "close: $!";

if ($found != 2) {
    die "failed to find response";
}
if ($response !~ s/^Result: //) {
    die "response doesn't start with Result:";
}

my $contentsAPtr = JSON::from_json($response);

foreach my $hPtr (@$contentsAPtr) {
    if (!exists($hPtr->{uri})) {
        die "uri is missing";
    } else {
        my $uri = $hPtr->{uri};
        if ($uri !~ /file:\/\/(.+)/) {
            die "bad uri: $uri";
        } else {
            my $file = $1;
            if ($file !~ /\.(?:cpp|hpp)$/) {
                die "$file is not a C/C++ file";
            }
            if (-f $file) {
                print "$file: ok\n";
            } else {
                die "! -f $file";
            }
        }
    }
}
````

**Comment by yyoncho** [comment]
IMO the correct solution would be:

1. try/catch the error (print a warning when the file does not exist).
2. Report the invalid path in ccls repo

(cc @MaskRay )

**Comment by JohnC32** [comment]
I created https://github.com/emacs-lsp/lsp-mode/pull/1115 to catch the error and continue. I will work with the ccls maintainers to fix the root cause. Thanks

**Comment by MaskRay** [comment]
This can be closed. It is out of scope of lsp-mode.
