### ISSUE TITLE
Add notification when LSP is ready

### ISSUE THREAD

**Issue by JohnC32** [emacs-lsp/lsp-mode#1114]
The current workflow for a large C++ project I'm setting up using lsp-mode with ccls is to:

1. Pregenerate the index using ccls -init="..." on our project.This takes many hours using 12 threads because of the size - many millions of lines of code.
2. Launch emacs and when a C++ file is loaded, activate lsp-mode.

The activation of lsp mode does take a while. Looking at "*ccls::stderr*" I see it takes a couple of minutes from the first line to the following "ready" line:

    10:19:10 ccls             pipeline.cc:485 I loaded project. Refresh semantic highlight for all working file.

It would be great if a message is displayed when this ready line appears, i.e. a call to

    (message "LSP ready - reload files to refresh semantic highlighting")

were added when the above log line is seen.

**Comment by yyoncho** [comment]
I am not sure I understand 100% what you are asking for. If `I loaded project...` message shows at the same time server sends `initialize` response, you could use `lsp-after-initialize-hook` hook to add your custom behaviour(e. g. refresh semantics). 

If you want only to have a message I added it here - https://github.com/emacs-lsp/lsp-mode/commit/66780e026da6711a4219802bc20b7cb165ea44b2

**Comment by JohnC32** [comment]
It would be helpful to see a message when lsp/ccls has finished loading and is ready for use. Adding the ability to refresh buffers would also be nice. Using https://github.com/emacs-lsp/lsp-mode/commit/66780e026da6711a4219802bc20b7cb165ea44b2 , I see:

    LSP :: Connected to [ccls:64240 status:starting].
    LSP :: ccls:64240 initialized successfully
    LSP :: not indexed [2 times]

The 'initialized successfully' message comes immediately after ccls starts, then a couple minutes later in the *ccls::stderr* buffer I see that lsp/ccls is ready when it prints the line 

    12:11:10 ccls             pipeline.cc:485 I loaded project. Refresh semantic highlight for all working file.

Note, there are many thousands of "I loaded cache for file.cpp" lines prior to the "I loaded project" line.

Thanks

**Comment by yyoncho** [comment]
This means that the initialization of ccls is not related to lsp event which makes your request out of scope for lsp core code but it should recide in the language server specific code. In this case, this is in a separate repo. I am closing the issue - you should follow up with a feature request in emacs ccls repo. 

(cc @MaskRay )
