### ISSUE TITLE
Incorrect determination of the availability of php-language-server

### ISSUE THREAD

**Issue by xuhdev** [emacs-lsp/lsp-mode#1123]
The default of `lsp-clients-php-server-command` is   `("php" ,(expand-file-name "~/.composer/vendor/felixfbecker/language-server/bin/php-language-server.php"))`, but in lsp-mode.el, its availability is determined by the existence of `php`. In other words, for someone who has php installed but has no interest in lsp for php, this will always lead to a false positive.

I understand that it can be customized out, but it is more like a hack and by default the false positive shouldn't be present for most people who only occasionally opens php files and do not want to set up lsp for php. IMO, the customization should be for someone who installs php-language-server.php in a different location.

This can be reproduced by opening a php file, where `php` is available but `php-language-server.php` is unavailable. `*lsp-log*` buffer shows:

```
Command "intelephense --stdio" is not present on the path.
Command "php /home/hong/.composer/vendor/felixfbecker/language-server/bin/php-language-server.php" is present on the path.
Found the following clients for /home/hong/tmp/a.php: (server-id php-ls, priority -2)
The following clients were selected based on priority: (server-id php-ls, priority -2)
```

**Comment by yyoncho** [comment]
The solution is to do what we do with XML language server: https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-xml.el#L203 . @xuhdev willing to try to provide a PR?

**Comment by xuhdev** [comment]
Thanks. Sure, I've put this on my TODO list.
