### ISSUE TITLE
Consider unpublishing lsp-go and friends from MELPA

### ISSUE THREAD

**Issue by muirrn** [emacs-lsp/lsp-mode#1136]
It would be good if we could get the deprecated `lsp-go` package out of MELPA. It's easy to accidentally install when trying to set things up. 

It looks like the recipe was removed a while ago, so I'm not sure how to proceed. We can start by opening an issue in the melpa project. Should I do that?

**Comment by yyoncho** [comment]
I don't see it here - https://melpa.org/#/?q=lsp-go&sort=downloads&asc=false ?

**Comment by muirrn** [comment]
Hmm... I still see it in Emacs when I run `package-list-packages`. I tried removing cache files and refreshing stuff, but I still see it. Do you see it in Emacs?

**Comment by yyoncho** [comment]
Yes, I still see it when I start emacs -q and download melpa packages. I guess we should ask in melpa repo.

**Comment by psanford** [comment]
It still shows up here: https://melpa.org/packages/archive-contents

**Comment by muirrn** [comment]
I opened https://github.com/melpa/melpa/issues/6501

**Comment by muirrn** [comment]
The deed is done.
