### ISSUE TITLE
Function definition is void: lsp-define-stdio-client after update lsp-mode today

### ISSUE THREAD

**Issue by ccqpein** [emacs-lsp/lsp-mode#1137]
**Describe the bug**
I just update lsp-mode this morning and I cannot auto start lsp-mode and run `lsp` when I open my Golang file.

+ Mini buffer gives me `Symbol’s function definition is void: lsp-define-stdio-client` when I open my go file.
+ When I run `lsp` after manually enroll `lsp-mode`, it return same error.
+ `gopls` in my PATH, and it works last night.
+ Other languages files have same issues too.

**Expected behavior**
Let me choice which lsp server I want to use, then start it automatically after I open Golang file.

**Which Language Server did you use**
gopls
rls&rust-analyzer 

**OS**
macOS, emacs version is `GNU Emacs 27.0.50`

**Other info**
I checked [changelog.org](https://github.com/emacs-lsp/lsp-mode/blob/3cd411f217f3783e981b8efd5db2510e7b4d4061/doc/changelog.org) and find out you change function `lsp-define-stdio-client` to `lsp-register-client`. Looks like it appear again.

**Comment by yyoncho** [comment]
You have the deprecated package lsp-go on your path. Please delete it (make sure it won't be installed again) and restart emacs.
