### ISSUE TITLE
Emacs hangs/locks up with ElixirLS and opening config.exs file

### ISSUE THREAD

**Issue by jsmestad** [emacs-lsp/lsp-mode#1143]
**Describe the bug**
When using the latest version of [elixir-lsp/elixir-ls](https://github.com/elixir-lsp/elixir-ls) OR [JakeBecker/elixir-ls](https://github.com/JakeBecker/elixir-ls), if you generate a brand new Phoenix application, then try to edit `config/config.exs` file, Emacs will freeze/lock up. Sometimes on a small project I can get it to load after several seconds and the on others, it will never load.

**To Reproduce**
Install elixir-ls with either Emacs 27.x or 26.3, generate a new phoenix app (here is a [test one](https://github.com/jsmestad/elixir-lsp-bug)).

If you open say the `mix.exs` file, LSP will work fine. If you open `config/config.exs` it locks up Emacs.

**Expected behavior**
The `config/config.exs` file works as you would expect. It works 100% normally in VSCode using the same Elixir LS projects.

**Which Language Server did you use**
ElixirLS (both original and the community fork)

**OS**
Fedora 31 and Ubuntu 19.04

**Error callstack**
I tried debug-on-quit with C-g but cannot get output.

**Comment by yyoncho** [comment]
I have updated the lsp-docker project to have elixir-ls and also I have added your project. Then I tested with start-emacs.sh script which uses /emacs.d/init.el minimal configuration and I was unable to reproduce the issue. Here it is the relevant commit: Here are the relevant changes: https://github.com/emacs-lsp/lsp-docker/commit/90e527a28f89f2fb226535dbf3fc0406bf7d65f3#diff-ebacf6f6ae4ee68078bb16454b23247d

**Comment by jsmestad** [comment]
@yyoncho I think the version of Elixir is really old (1.3.3 vs 1.9.2). I can give that a try installing the old elixir version locally this evening and see if that gives a different result.

For reference, the elixir-ls repo uses the following versions:
```
elixir 1.7.4-otp-20
erlang 20.3.8.9
```

**Comment by yyoncho** [comment]
Ok. Can you try one more thing - you stated that C-g does not unbreaks the emacs, right? Can you try: 1. Press C-g multiple times 
2. Kill the elixir-ls process outside of emacs.

Also, does it unfreeze after some time?

**Comment by jsmestad** [comment]
I will give that a shot as well. I'll report back soon. Thanks for the help figuring this out :)

**Comment by jsmestad** [comment]
Ok this is not caused by emacs-lsp as I disabled it and am still having the issue. :tada: I will report back if I figure out the cause, but maybe its 27.0.50 from git that is failing me 😞
