### ISSUE TITLE
`ocaml-language-server` appears to no longer be available

### ISSUE THREAD

**Issue by Gastove** [emacs-lsp/lsp-mode#1159]
The README lists `ocaml-language-server` as an available backend for OCaml. However, it appears to no longer be available on Github. This is the only link I can find for the thing, and it's dead:

https://github.com/freebroccolo/ocaml-language-server

It appears some part of it is available on whatever "npm.taobao.com" is https://npm.taobao.org/package/ocaml-language-server -- but that site doesn't exactly inspire great confidence. 

Should `ocaml-language-server` be removed from the README? Does anyone know where it went?

**Comment by yyoncho** [comment]
Here it is the original integration https://github.com/emacs-lsp-legacy/lsp-ocaml it links to https://github.com/freebroccolo/ocaml-language-server . If it doesn't exist and it is not supported then it makes sense to be deleted from the readme

**Comment by yyoncho** [comment]
Fixed with https://github.com/emacs-lsp/lsp-mode/commit/47923d4d03656b8f70587c7a708eefe5f5654a71 by @contrun .
