### ISSUE TITLE
Consider using softer colours for symbol references

### ISSUE THREAD

**Issue by alanz** [emacs-lsp/lsp-mode#116]
I have customised mine to match the ones in `vscode`, using

```elisp
 '(lsp-face-highlight-read ((t (:background "gray"))))
 '(lsp-face-highlight-write ((t (:background "SteelBlue1"))))
```

Should these be the default? Or something similar, not the bright red and green.

**Comment by bkchr** [comment]
Sound like a good idea.

**Comment by vibhavp** [comment]
My idea was to use colors that go with the default emacs "angry fruit salad" theme. Would there be a way to use softer colors that still fit with it?

**Comment by bkchr** [comment]
Or it could be made configurable, the current color looks really annoying in my theme ^^

**Comment by vibhavp** [comment]
All lsp faces are changeable, see <kbd>M-x </kbd> `customize-group` -> `lsp-mode`, and choose the _Lsp Faces_ subgroup at the bottom of the options list.

**Comment by vibhavp** [comment]
Alternatively, use `(set-face-attributes 'lsp-face-highlight-{textual,read,write} nil :background "color")`

**Comment by bkchr** [comment]
Ohh ^^ Maybe it would be enough to document this.

**Comment by vibhavp** [comment]
Well, if the plan is to get this into emacs core, so yeah. We should probably use softer colors though, yeah.

**Comment by alanz** [comment]
Ok. I think the "out of the box" experience should be as good as we can get it. Perhaps adjust the defaults if/when it goes into the core.

But at the end of the day it *can* be customised, so is not a big deal either way.

**Comment by JJPandari** [comment]
It can be customized but this is one of the few times I tell myself, "ah, this is intrusive, I have to change this face". `gray` and `steelblue1`may not look smooth on all themes, I'm a newbie but  something theme-dependent may be better? Like `font-lock-keyword-face` `font-lock-constant-face`? (and yeah they have their own problems like when the word at point is keyword itself, thus no visual change on hovering)
