### ISSUE TITLE
Support stopped servers

### ISSUE THREAD

**Issue by MaskRay** [emacs-lsp/lsp-mode#1160]
https://github.com/MaskRay/ccls/wiki/Debugging If you set the environment variable `CCLS_TRACEME=s` (`raise(SIGSTOP)`), ccls will stop itself before handling client requests.

If you do this, however, after `M-x lsp`, you will immediately receive a prompt `Server ccls:16154 status:starting exited with status signal. Do you want to restart it? (y or n) `. This makes lsp-mode unsuitable for debugging initialization problems of a language server.

Any tips debugging lsp-mode code will be highly appreciated. I try to do:

* ` C-u C-M-x` at `lsp--restart-if-needed`  (emacs will automatically set a breakpoint at the entry. I don't want this implicit behavior, but I don't know how to suppress it)

and use edebug, but my edebug session is frequently interrupted by the ` Do you want to restart it? (y or n) .` prompt.

Note: a stopped server used to work (more than 1 year ago) when the auto restarting feature was not implemented.

**Comment by yyoncho** [comment]
Isn't `(setq lsp-restart 'ignore)` what you are looking for?

**Comment by MaskRay** [comment]
but I want to auto-restarting functionality. I just don't want it to consider a stopped process exited/signaled.

**Comment by yyoncho** [comment]
I see - seems like an issue in `lsp--create-sentinel` - we probably misinterpret sentinel event.

**Comment by yyoncho** [comment]
I added tracing of the signal and the signal received when traceme variable is set are `'stop` and `'signal` so I believe the proper fix is https://github.com/yyoncho/lsp-mode/commit/785497ce2d59e9721f7ae4831682ca934c190f1f
