### ISSUE TITLE
Invalid save notification support checks.

### ISSUE THREAD

**Issue by ssbb** [emacs-lsp/lsp-mode#1162]
**Describe the bug**
`didSave`/`willSave` (functions like `lsp--send-did-save-p`) server capabilities checks not follow current specification.

`textDocumentSync` allows `TextDocumentSyncOptions` (used in this checks right now) or number from 0 to 2 (`TextDocumentSyncKind`). For example elm-language-server sending `1` here which means Full sync so functions like `lsp--send-did-save-p` should return `t`. 

**Expected behavior**
Handle `TextDocumentSyncKind` numbers in this checks.

**Which Language Server did you use**
elm-language-server

**OS**
MacOS

**Comment by yyoncho** [comment]
Ah, I haven't pressed a "Comment" button.

You are right, willing to provide a PR?

**Comment by ssbb** [comment]
Yeah, will do soon 👍
