### ISSUE TITLE
rust-analyzer inlay hints stopped working with 75969ab

### ISSUE THREAD

**Issue by brotzeit** [emacs-lsp/lsp-mode#1165]
I wanted to add an option for the length of the hints and noticed it.

**Comment by yyoncho** [comment]
Are you going to look at the issue? IMO you may try first to delete the lsp-session file (start with clean session) to see whether this fixes the issue. If this does not fix the issue it is probably a regression in `lsp-find-workspace`/`lsp-find-session-folder`.

**Comment by brotzeit** [comment]
I will take a look at it.

**Comment by brotzeit** [comment]
I don't know the appropriate fix but it works with:

```diff
modified   lsp-mode.el
@@ -5934,7 +5934,8 @@ such."
                         (lsp--find-clients)))
         (-if-let (project-root (-some-> session
                                         (lsp--calculate-root (buffer-file-name))
-                                        (lsp-cannonical-file-name)))
+                                        ;; (lsp-cannonical-file-name)
+                                        ))
             (progn
               ;; update project roots if needed and persist the lsp session
               (unless (-contains? (lsp-session-folders session) project-root)
```

**Comment by yyoncho** [comment]
We need that line to ensure that the folders are named in a consistent manner. I will take a look, can you help me with providing a file which should display hints?

**Comment by brotzeit** [comment]
Most let bindings with type inference will display an inlay hint, but you can use a file of rustfmt: rustfmt/src/format-diff/main.rs

**Comment by brotzeit** [comment]
And you should now that it takes some time that the inlay hints get activated. It seems to happen when the workspace is initialized and you moved the cursor or made a change in the buffer(this should probably be fixed).

**Comment by yyoncho** [comment]
I am getting zero hints:

```
[Trace - 06:32:14 PM] Sending request 'rust-analyzer/inlayHints - (107)'.
Params: {
  "textDocument": {
    "uri": "file:///Projects/Rust/rustfmt/src/format-diff/main.rs"
  }
}


[Trace - 06:32:14 PM] Received response 'rust-analyzer/inlayHints - (107)' in 35ms.
Result: []

```

**Comment by yyoncho** [comment]
As a side note, I noticed that rust-analyzer supports code lenses and they are not configured on our side. 

![Screenshot](https://user-images.githubusercontent.com/13259670/68699667-3f132100-058c-11ea-8df6-00a2f55e5d7b.png)

**Comment by brotzeit** [comment]
> I am getting zero hints

Did you revert the commit ? It seems you don't get any response with it.

> As a side note, I noticed that rust-analyzer supports code lenses and they are not configured on our side.

I have issues with setting configurations. I don't get any responses of cargo watch for example #1179

**Comment by yyoncho** [comment]
> Did you revert the commit ? It seems you don't get any response with it

I was able to get some hints. I will continue with the investigations.

> enableCargoWatchOnStartup

AFAIK is the cargo watch server side feature of rust analyzer? I read somewhere in reddit that is is implemented on the client side until rust-analyzer gets the real diagnostics.

**Comment by brotzeit** [comment]
I see, that's the purpose of the additional option. However I also can't set the maximum length of inlay hints with `rust-analyzer.maxInlayHintLength`.

**Comment by yyoncho** [comment]
What do you mean by can't set?

**Comment by brotzeit** [comment]
It doesn't show any effect.

**Comment by yyoncho** [comment]
It is client-side setting: https://github.com/rust-analyzer/rust-analyzer/search?q=maxInlayHintLength&unscoped_q=maxInlayHintLength

**Comment by yyoncho** [comment]
I spent some time investigating the issue and it is caused by entry in the .lsp-session-file which ends with `/` which was added before 75969aba4504e22f0bc2c67242a062db64022a61 . 

Proposed solutions:

1. Add suffix `v2` to the lsp-session-file which will force the users to read there workspace folders.
2. Add code to load session function to fix the folder names. 
3. Disregard the issue and document that users should delete all workspace folders.

**Comment by brotzeit** [comment]
I'm not sure where to document this. It seems nobody besides me noticed this, so maybe we should just close this issue ?

**Comment by andrewbanchich** [comment]
@brotzeit I've been missing the inlay hints for a while and wondering what caused this. Was this closed because it should be fixed now?

**Comment by fbodr** [comment]
@brotzeit how is the current status of this ?
Im trying to enable inline inlays (in a very simple hello world rust project), but I get nothing.

**Comment by yyoncho** [comment]
@fbodr  ATM it should work.

**Comment by fbodr** [comment]
@yyoncho . Im trying it in doom emacs + rust-analyzer(master) , but it shows no inlay types at all. 
rust-analyzer seems to be working, as the inlay hints are properly shown in vscode

**Comment by nbfalcon** [comment]
What are inlay hints supposed to look like?

**Comment by fbodr** [comment]
Here is a screenshot:
https://emacs-lsp.github.io/lsp-mode/page/lsp-rust/#inlay-hints
the inferred type is displayed near the variables

**Comment by yyoncho** [comment]
@fbodr you should be setting this variable before loading lsp-mode, right?

**Comment by fbodr** [comment]
this is my config.el for doom:
`(use-package! lsp-rust
  :config
  (setq! lsp-rust-analyzer-cargo-watch-enable t
         lsp-rust-analyzer-cargo-watch-command "clippy"
         lsp-rust-analyzer-proc-macro-enable t
         lsp-rust-analyzer-cargo-load-out-dirs-from-check t
         lsp-rust-analyzer-inlay-hints-mode t
         lsp-rust-analyzer-display-chaining-hints t
         lsp-rust-analyzer-display-parameter-hints t))`

**Comment by yyoncho** [comment]
AFACS you should set  `lsp-rust-analyzer-server-display-inlay-hints`

**Comment by nbfalcon** [comment]
Yup, it defaults to `nil`.

**Comment by fbodr** [comment]
you were right, thanks. 
I ll double check the sites I got the values from, to see if it could be a documentation problem, or only lack of attention  😅
