### ISSUE TITLE
Rework association between major modes and clients

### ISSUE THREAD

**Issue by phst** [emacs-lsp/lsp-mode#117]
Currently, clients are per major mode. This implies that

- modes need to be registered twice, once in their mode hook and once in the client definitions

- derived modes don't work unless there's also a client for each derived mode whose parent already has a client.

Therefore I'd propose to remove the association between major modes and clients altogether - I don't think it's needed, but it adds some complexity and coupling of otherwise unrelated concepts. How about giving clients an identity (e.g. a symbol name) and assigning them to buffers based on a buffer-local variable, like this:

```elisp
(defvar-local lsp-client nil)
(define-minor-mode lsp-mode ...
  (unless lsp-client
     (user-error "lsp-client not set"))
  ...
```

Then users could just set `lsp-client` in the mode hook or however they like.

**Comment by vibhavp** [comment]
> How about giving clients an identity (e.g. a symbol name) and assigning them to buffers based on a buffer-local variable

That's actually done with the variable `lsp--cur-workspace` in `lsp-methods.el`. Because the client is simply a object for sending and receiving messages, `lsp--cur-workspace` stores a list of files/buffers associated with a workspace and their corresponding version numbers, the client object, etc.

> Therefore I'd propose to remove the association between major modes and clients altogether - I don't think it's needed, but it adds some complexity and coupling of otherwise unrelated concepts

The coupling of language major modes and the client is a consequence of how the [API for defining clients to language server](https://github.com/emacs-lsp/lsp-mode/blob/4f05cf0960c4a5b125df48902146e923b172c916/doc/API.org) is designed. IMO, defining a client should be as little work as possible, to comply with the intended purpose of the Language Server Procotol.

**Comment by phst** [comment]
> The coupling of language major modes and the client is a consequence of how the API for defining clients to language server is designed.

There are two issues with this coupling:

1. It doesn't work well with derived modes. Essentially you'd have to register all derived modes individually, but you can't know in advance what derived modes exist.
2. It starts more LSP clients than necessary. Often a single LSP client could serve most/all modes, but right now one LSP client is required per mode.

**Comment by vibhavp** [comment]
If we do decouple modes and clients, hooking `lsp-mode` into a programming mode would have to be done with something like `(add-hook 'rust-mode-hook 'lsp-mode-rust)`, right? The code for managing client and workspace lifecycle is a little messy, so redoing this association would be worth it.

**Comment by phst** [comment]
Yes, where `lisp-mode-rust` would be a user-supplied function, like this:

```elisp
(defun lsp-mode-rust ()
  (lsp-add-stdio-client :command '("/path/to/rust-languageserver") :workspace-root default-directory)
```

**Comment by vibhavp** [comment]
Just created this PR: https://github.com/emacs-lsp/lsp-mode/pull/131. Reviews + feedback would be appreciated.

**Comment by phst** [comment]
Thanks for these changes! I think that's great progress.
One more thing: Just like modes, language IDs should also be independent from clients. There are language servers that can serve multiple languages. The language should be a property of the buffers, just like the major modes.
