### ISSUE TITLE
lsp-organize-imports errors out if action not available

### ISSUE THREAD

**Issue by muirdm** [emacs-lsp/lsp-mode#1177]
Servers such as gopls and java only offer the "organizeImports" action if there are changes to be made. This means `lsp-organize-imports` errors out when there is nothing to organize, which makes it not work very well as a before-save-hook.

I propose we change lsp-organize-imports to hide the "No actions to select from" error, or at least hide it if invoked non-interactively.

**Comment by yyoncho** [comment]
Yes, this error does not make sense even for the interactive version - it could be changed to informative message.

One more thing: it will be good if we can make it async. For example, when JDT ls server is importing a project all server calls will block and if someone has it configured on before-save-hook will be stuck. 

What I am proposing is to intercept the save action and artificially make it asynchronous. E. g.

1. User initiates save
2. lsp-mode performs one or more async calls to the server
3. User has an indication in modeline that lsp-mode is performing some action(or something else?)
4. server returns, lsp-mode performs the action and saves the buffer.
5. We provide an action - `cancel lsp mode save actions` which result in the file being saved without applying the actions.

**Comment by muirdm** [comment]
I like the idea of not waiting for slow hooks, but I don't like the idea of asynchronous saving. As a user I expect synchronous saving. Also, what happens if the user types more stuff before the asynchronous call finishes? You can't necessarily apply the organizeImport edits anymore since the file has changed, and it isn't clear if we should save the old or new version of the file.

**Comment by yyoncho** [comment]
> Also, what happens if the user types more stuff before the asynchronous call finishes? 

What about making the buffer read-only until that happens? IMO the alternative "freezing" is just not fine.

**Comment by muirdm** [comment]
> making the buffer read-only

That sounds like a reasonable compromise, but I still think there is potential risk because users are used to the file actually being saved once the save action finishes.

What about something like this:
1. Add a 100ms timeout waiting for before-save actions
1. If they time out, save the file anyway and activate async action mode
1. If user edits file, restart the async actions after inactivity timeout
1. Once actions complete, perform formatting edits and save file again if necessary

**Comment by yyoncho** [comment]
> That sounds like a reasonable compromise, but I still think there is potential risk because users are used to the file actually being saved once the save action finishes.

What you are saying makes sense and if we go in this direction we should make the async behaviour very explicit (e. g. we may fade out the buffer as `avy` does). We may introduce our command `lsp-buffer-actions-and-save`(or similar name) and users could remap the save-buffer command if they want. 

> Add a 100ms timeout waiting for before-save actions

Still, if I do `Save all` and I have 30 buffers open it will be 3 seconds. 

> If user edits file, restart the async actions after inactivity timeout

I do not like the non-determined behaviour where you get certain functionality depending on timeouts/user actions.

**Comment by muirdm** [comment]
Can we split the async stuff into a separate issue?

**Comment by yyoncho** [comment]
> Can we split the async stuff into a separate issue?

Sure.

**Comment by yyoncho** [comment]
Closing (it was reopened by mistake).
