### ISSUE TITLE
Prefer current workspace when jumping to library code 

### ISSUE THREAD

**Issue by muirdm** [emacs-lsp/lsp-mode#1178]
Currently when jumping into library code not under an active workspace we seem to randomly choose a workspace to open the file in. This causes things to break for gopls since gopls will not work properly for the library package unless it is a dependency of the current workspace.

I propose we change the library workspace selection to prefer the current buffer's workspace if it can't otherwise find a suitable workspace.

**Comment by yyoncho** [comment]
unfortunately, it is not that easy since there is no "current buffer workspace"(e. g. by default the xrefs are displayed in a buffer). What we can try is to keep somewhere the last used workspace and use it if it s `library-folders-fn` matches. 

WDYT?

**Comment by muirdm** [comment]
Remembering the last workspace would fix it in most cases but not all (e.g. you click a link in an old xref buffer after switching workspaces). If there is no way to "remember" the workspace through xref interactions then I think what you propose is the next best thing.
