### ISSUE TITLE
lsp-go: Failure = cannot find an enclosing function

### ISSUE THREAD

**Issue by bittopaz** [emacs-lsp/lsp-mode#1181]
I'm seeing a lot of messages in *lsp-log buffer when using `lsp-mode` with `gopls`, both of `lsp-mode` and `gopls` are at latest versions.

```
2019/11/14 14:42:56 no signature help
	At = {1354 0}
	Failure = cannot find an enclosing function
```

I just wonder if there is anyone else also in this situation.

**Comment by yyoncho** [comment]
This is happening because gopls returns an error instead of an empty result when lsp-mode is checking for document signature on a place where there is no function invocation. You may ignore these entries.

**Comment by seh** [comment]
Does that warrant an issue filed against _gopls_, then?

**Comment by yyoncho** [comment]
> Does that warrant an issue filed against _gopls_, then?

Yes, I think that this was already reported in gopls repo. @muirdm, can you confirm?
