### ISSUE TITLE
completion-at-point not working in prototype php-language-server integration

### ISSUE THREAD

**Issue by NateEag** [emacs-lsp/lsp-mode#119]
As an Emacser who's wished for good PHP integration many times in the past decade, and who just discovered LSP and lsp-mode, I've tried hooking [php-language-server](https://github.com/felixfbecker/php-language-server) up to lsp-mode [in my PHP config](https://github.com/NateEag/.emacs.d/blob/8261d90ca053af74632c57983620df0ed66fe7ce/site-lisp/mode-configs/php-mode-init.el#L96).

Jump to definition works nicely, so I know the basics are working, but `completion-at-point` always fails, either returning "[No matches]" (in cases where that's true) or failing with the error "Wrong type argument: stringp, nil".

I've written one or two elisp packages, so I'm not afraid of getting my hands dirty, but the few times I've glanced at this so far, I haven't figured out a clear angle of attack on the problem (largely because I don't really know either codebase, and am new to LSP in general).

Any advice on how I might approach debugging this?

I realize this isn't a great bug report - I can assemble a minimal reproduction if someone else wants to take a look at it.

**Comment by NateEag** [comment]
In case it's helpful, here's an example request/response pair for the "Wrong type argument: stringp, nil" error I get. I've formatted the documents for readability and redacted a path from the request.

Request:

```json
{
    "jsonrpc": "2.0",
    "method": "textDocument/completion",
    "params": {
        "textDocument": {
            "uri": "file:///<filepath>.php"
        },
        "position": {
            "line": 22,
            "character": 15
        }
    },
    "id": 56
}
```

Response:

```json
{
    "result": {
        "isIncomplete": true,
        "items": [
            {
                "label": "Controller",
                "kind": 7,
                "detail": "Laravel\\Lumen\\Routing",
                "documentation": null,
                "sortText": null,
                "filterText": null,
                "insertText": null,
                "textEdit": null,
                "additionalTextEdits": null,
                "command": null,
                "data": null
            }
        ]
    },
    "id": 56,
    "jsonrpc": "2.0"
}
```

**Comment by NateEag** [comment]
...okay, as it turns out, I wound up having to wait several hours in a lobby with no distractions but a droning TV and my laptop this evening. (Really, that's what occasioned the bug report at all - it just turned out to be a much longer wait than I expected.)

I believe I have gotten to the bottom of this as a result.

`lsp--make-completion-item` calls `(gethash "insertText" item (gethash "label" item))` to get the text to actually insert.

That would work admirably (and presumably does) if the `insertText` key didn't exist at all, but since it does in this case  (see the above response), it dutifully returns `nil`, causing this failure.

Looking at the LSP spec, I see that [CompletionItems are not required to contain `insertText`](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#completion-request), hence the defaulting behavior implemented in `lsp--make-completion-item`.

However, the `insertText` field of the CompletionItem interface isn't just marked optional - the comment above it in the spec says "When `falsy` the label is used."

Given that, I believe we need to handle both the case where `insertText` does not exist *and* the case where it is a falsy value such as `null`.

Note that the spec describes analogous behavior for the `sortText` and `filterText` fields.

Would a PR implementing the described behavior be accepted?

**Comment by alanz** [comment]
I'm pretty sure it would be

**Comment by vibhavp** [comment]
LGTM. Also, you can replace `(or (gethash "insertText" item (gethash "label" item)) (gethash "label" item))` with just `(or (gethash "insertText" item) (gethash "label" item))`

**Comment by NateEag** [comment]
@vibhavp Ah, good idea. Thanks!

A wrinkle that occurred to me yesterday:

In TypeScript, the language used in the LSP spec, the empty string is falsy, and thus we should use `label` in event that `insertText` is an empty string. In Emacs Lisp, empty string is truthy (since everything but nil is)

It shouldn't be hard to account for, I just realized it's an error in my approach.

I'll try to get a PR for this submitted this weekend.

**Comment by NateEag** [comment]
Last weekend wound up being busier than I expected, so I haven't gotten to this yet.

I've put it on my calendar for Saturday morning (EST), so hopefully I'll be able to get to it then.

**Comment by NateEag** [comment]
Okay, this weekend wound up busier than I expected, too.

I did find a little time to work on this. It's not a PR yet because I haven't actually tested the code with the php-language-server yet, but I think it should do the job:

https://github.com/NateEag/lsp-mode/commit/684a7a45058d28211997772b194c538850c2929e

Does this approach look reasonable? Is there anything missing I'd need in a PR?

**Comment by NateEag** [comment]
I found a few minutes to actually test what I've written, and it works with the php-language-server.

So, I'm going ahead and issuing a PR.

If anything seems off about the change just let me know.
