### ISSUE TITLE
Make nonlocal on-idle-hooks local?

### ISSUE THREAD

**Issue by sebastiansturm** [emacs-lsp/lsp-mode#1193]
Both `lsp--document-highlight` and `lsp--document-links` are currently registered as nonlocal on-idle hooks, so starting up a language server supporting one of these methods will trigger errors in previously started workspaces that don't. I'd just add `... nil t` to the relevant `add-hook` calls, unless someone sees a problem with that?

**Comment by yyoncho** [comment]
Yes - this is the correct solution.
