### ISSUE TITLE
Highlighting is no longer shown

### ISSUE THREAD

**Issue by alanz** [emacs-lsp/lsp-mode#1195]
There was a melpa update which I installed today, to `lsp-mode-20191120.1942`.

Document highlighting no longer works with it.

Bisecting shows the bad commit to be ff30589219666ad10953ac08cd3e0847c05ec0d9

```
git bisect log
git bisect start
# bad: [39fca2d9ef944f56b86d1ad761370064ed5ff2fd] Merge pull request #1194 from jaaso/patch-1
git bisect bad 39fca2d9ef944f56b86d1ad761370064ed5ff2fd
# good: [c2f34567777bd376784de45c4628d8a74a5aa40e] [imp] default pylint to off (#1185)
git bisect good c2f34567777bd376784de45c4628d8a74a5aa40e
# bad: [6edaa27ae57c387f76f283dd6e30cf0c7cb0af0c] indent elisp
git bisect bad 6edaa27ae57c387f76f283dd6e30cf0c7cb0af0c
# bad: [21be38df51478f844decea718ab2387515be54e1] Change the face for lsp-face-highlight-write
git bisect bad 21be38df51478f844decea718ab2387515be54e1
# good: [cbfd11770667c7bdf7c2097380356084d2b0240e] Add support for passing environment variables to language servers (#1184)
git bisect good cbfd11770667c7bdf7c2097380356084d2b0240e
# bad: [ff30589219666ad10953ac08cd3e0847c05ec0d9] Implement unified way to handle recurring lsp features
git bisect bad ff30589219666ad10953ac08cd3e0847c05ec0d9
# good: [f61f3eacfdfabe34f3db9bfdf0b7f5ca81542a84] Uri is not correctly translated to path in Windows and also the tramp path is not correctly expanded (#1189)
git bisect good f61f3eacfdfabe34f3db9bfdf0b7f5ca81542a84
# first bad commit: [ff30589219666ad10953ac08cd3e0847c05ec0d9] Implement unified way to handle recurring lsp features
```

**Comment by yyoncho** [comment]
I assume using hie?

**Comment by alanz** [comment]
Actually using an under development branch of https://github.com/alanz/erlang_ls/tree/232-implement-documenthighlight.

But it goes from showing highlights to not showing them on that commit.  Does it still work with other language servers? I do not have any set up, on a new work machine.  And it's a Mac, foreign to me.

**Comment by alanz** [comment]
Here is an extract from the lsp-mode log, that works with the older version.

```
[Trace - 02:58:49 pm] Sending request 'textDocument/documentHighlight - (6369)'.
Params: {
  "textDocument": {
    "uri": "file:///Users/alanzimm/repos/erlang_ls/erlang_ls/test/els_references_SUITE.erl"
  },
  "position": {
    "line": 154,
    "character": 16
  }
}


[Trace - 02:58:49 pm] Received response 'textDocument/documentHighlight - (6369)' in 35ms.
Result: [
  {
    "range": {
      "start": {
        "line": 154,
        "character": 2
      },
      "end": {
        "line": 154,
        "character": 24
      }
    }
  }
]
```

**Comment by yyoncho** [comment]
> Does it still work with other language servers?

I have tested with 10+ servers and it works fi.

 If you can provide the initialize response? I will try to reproduce it locally with erlang_ls.

**Comment by alanz** [comment]
Here is a gist.  It is a new feature I am still adding, so it is very likely I am doing something wrong. It was just disconcerting to have it disappear, probably because my implementation is wrong, and the previous version was more forgiving.

https://gist.github.com/alanz/d86b19f27920e184690289de80915da9

**Comment by yyoncho** [comment]
The new version discards the highlights response does not contain the current cursor position. Is it possible that you hit that issue? Also, is this log from working or from non-working lsp-mode?

**Comment by alanz** [comment]
It is from the last good commit, https://github.com/emacs-lsp/lsp-mode/commit/ff30589219666ad10953ac08cd3e0847c05ec0d9.

I will compare to hie on my home machine now, and experiment a bit.

**Comment by alanz** [comment]
I am closing this, have to debug my implementation. Sorry to bug you.

**Comment by alanz** [comment]
Coming back to this, I think the problem is with the identified commit.

As I read it, https://github.com/emacs-lsp/lsp-mode/commit/ff30589219666ad10953ac08cd3e0847c05ec0d9#diff-b1e9bc82c3b6bd6e95470e18ee41a19bR4157 is set to *require* the `kind` parameter,  which is optional according to the [spec](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_documentHighlight).

If I set my response to return a value for `kind`, then the highlights show up again.
