### ISSUE TITLE
lsp-dart enhancement

### ISSUE THREAD

**Issue by itome** [emacs-lsp/lsp-mode#1196]
I plan to enhance lsp-dart by implementing same feature as [vim-lsc-dart](https://github.com/natebosch/vim-lsc-dart)(which is officially recommended by dart team).

And I have some question how to implement features.
- How to implement `SkipYamlRequests` feature in vim-lsc-dart?
https://github.com/natebosch/vim-lsc-dart/blob/e5477cb0de5f96e36c472a189da510afe32b6e53/ftplugin/dart.vim#L63

- How to specify initialize option?
https://github.com/natebosch/vim-lsc-dart/blob/e5477cb0de5f96e36c472a189da510afe32b6e53/ftplugin/dart.vim#L47

- How to move cursor after completion?
dart_analysis_server often send completion like `child: ,`, I want move cursor before `,`.

**Comment by itome** [comment]
How about stopping support for `dart_language_server`? It is already obsolete and guiding to use `dart_analysis_server` --lsp mode instead in its document.

https://github.com/natebosch/dart_language_server

**Comment by yyoncho** [comment]
> * How to implement `SkipYamlRequests` feature in vim-lsc-dart?
>   https://github.com/natebosch/vim-lsc-dart/blob/e5477cb0de5f96e36c472a189da510afe32b6e53/ftplugin/dart.vim#L63

ATM we do not have facilities to make that happen easily. IIUC the code supresses certain server features in YAML files. I will check the code how easy would be to make that possible on our side. 

> * How to specify initialize option?
>   https://github.com/natebosch/vim-lsc-dart/blob/e5477cb0de5f96e36c472a189da510afe32b6e53/ftplugin/dart.vim#L47

You could specify `:initialization-options` when create the lsp--client. It could be also a function returning the intialization options.

> * How to move cursor after completion?
>   dart_analysis_server often send completion like `child: ,`, I want move cursor before `,`.


Usually, this is implemented by the server by specifying $0 in the snippet. We have to see how this is implemented by the other clients. I think that there were plans to add "command" to each completion item but I am not sure whether this works using this feature.


> How about stopping support for dart_language_server? It is already obsolete and guiding to use dart_analysis_server --lsp mode instead in its document.
> https://github.com/natebosch/dart_language_server


We rely on the lagnuage users to keep the language specific stuff up to date. If you are dart user you will know much better than us (lsp-mode maintainers) which dart related settings make sense to be part of default lsp-mode configuration. If you find something that shouldn't be there feel free to provide a PR.

**Comment by itome** [comment]
I made PR for initialization options
https://github.com/emacs-lsp/lsp-mode/pull/1197

**Comment by itome** [comment]
@yyoncho 

- About `SkipYamlRequests`
I read natebosch/vim-lsc-dart:ftplugin/dart.vim@e5477cb#L63 again and I noticed that we don't have to support this feature in `lsp-mode`, because `lsp-mode` only support `.dart` file.

- About completion snippets.
I opened issue in dart-sdk -> https://github.com/dart-lang/sdk/issues/39500. I continue to discuss in this thread.

**Comment by yyoncho** [comment]
> About SkipYamlRequests
I read natebosch/vim-lsc-dart:ftplugin/dart.vim@e5477cb#L63 again and I noticed that we don't have to support this feature in lsp-mode, because lsp-mode only support .dart file.

We could easily add support for yaml files by altering the definition of dart client(you could list several modes in the :modes). Can you check what is the behaviour when you are in yaml you perform completion? I would speculate that we will just work and SkipYamlRequests is needed only for clients that do not support multiple language servers in a single file(lsp-mode support that). I think that lsp protocol will support per language capabilities in the future versions.

**Comment by itome** [comment]
Completion snippets from dart analysis server is now works fine in nightly build.

I enabled lsp-dart in my project's yaml file, But it doesn't show nothing.

**Comment by yyoncho** [comment]
@itome I suggest asking about that in dart repo - I think that dart ls might not have any functionality in yaml file but it might be interested only in the content of the file.

**Comment by yyoncho** [comment]
Is there anything more to do regarding this issue report?

**Comment by itome** [comment]
Sorry replying late. I'll ask about yaml file for dart analysis server. I close.
