### ISSUE TITLE
Wrong type argument: listp

### ISSUE THREAD

**Issue by kdeberk** [emacs-lsp/lsp-mode#1207]
**Describe the bug**
When I start lsp-mode with a buffer in go-mode and with the gopls lsp, I get the following error:
```
Wrong type argument: listp, #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("triggerCharacters" ["(" ","] ...))
```
Having enabled debug mode, I get the following backtrace:
```
Debugger entered--Lisp error: (wrong-type-argument listp #<hash-table equal 1/65 0x1190651>)
  lsp-managed-mode(1)
  lsp--text-document-did-open()
  lsp--open-in-workspace(#s(lsp--workspace :ewoc #s(ewoc :buffer #<buffer *lsp-log: gopls:189038*> :pretty-printer lsp--log-entry-pp ....
  #f(compiled-function (response) #<bytecode 0x11624ed>)(#<hash-table equal 2/65 0x118f619>)
  #f(compiled-function () #<bytecode 0x116251d>)()
  #f(compiled-function (result) #<bytecode 0x116253d>)(#<hash-table equal 2/65 0x118f619>)
```
and looking at the minor mode definition of `lsp-managed-mode`, it seems that I can avoid this error by replacing the `-when-let` value of `signature-help-handler` will `nil`.

This is what gopls sends as `triggerCharacters`:
```
    "signatureHelpProvider": {
      "triggerCharacters": [
        "(",
        ","
      ]
    },
```

**To Reproduce**
I suppose that any simple go file with a recent gopls program will raise this.

**Expected behavior**
No error, and functional LSP behavior.

**Which Language Server did you use**
gopls

**OS**
Which os do you use? Linux

**Error callstack**
See above

**Comment by yyoncho** [comment]
Hm, can you make sure that you are using the latest version of dash?

What does this evaluate to on your system?

```
(-let [(&hash? "test") (ht ("test" "test"))]
  test)
```

**Comment by yyoncho** [comment]
Also, if dash is the latest version, can you make sure that lsp-mode is compiled against the it. The easiest way to do that is to delete the elc files in the elpa dir.

**Comment by kdeberk** [comment]
Thanks for the quick response.

I though I was using the latest version of dash, but it turned out that `dash-functional` was up to date, and `dash` itself was from February. I will close this issue.
