### ISSUE TITLE
when add to program language mode hoook, lsp-deferred conflicted with set company-backends function

### ISSUE THREAD

**Issue by phenix3443** [emacs-lsp/lsp-mode#1209]
**Describe the bug**
i have some code to  config lsp-mode,company-lsp,company-lua to work together,  like follow:

(use-package lsp-mode
  :ensure t
  :commands (lsp lsp-deferred)
  :config

(use-package company-lua
  :ensure t
  :after (company)
  :config
  )

(defun set-company-backends-for-lua()
  "Set lua company backend."
  (setq-local company-backends '(
                                 (
                                  company-lua
                                  company-lsp
                                  company-keywords
                                  )
                                 company-gtags
                                 company-capf
                                 company-dabbrev-code
                                 company-files
                                 )))

(use-package lua-mode
  :ensure t
  :mode "\\.lua$"
  :interpreter "lua"
  :hook (
         (lua-mode . set-company-backends-for-lua)
         (lua-mode . lsp-deferred)  
         )
  :config
  )
)

when i open a lua file, the company-backends should be( i expecte):
`
((company-lua company-lsp company-keywords)
 company-gtags company-capf company-dabbrev-code company-files)
`
but in face it is 
` lisp
(company-lsp
 (company-lua company-lsp company-keywords)
 company-gtags company-dabbrev-code company-files)
`
in the case, the group backends i configured do not works. now my solution Is  that add lsp to lua-mode-hook intead of lsp-deferred, just as 

(use-package lua-mode
  :ensure t
  :mode "\\.lua$"
  :interpreter "lua"
  :hook (
         (lua-mode . set-company-backends-for-lua)
         (lua-mode . lsp)      ; keep this cofigure order, and do not use lsp-deferred
         )

  :config
  )

suggestion：delete the following code in lsp--auto-configure function in lsp-mode.el at line 5439:
`
      (add-to-list 'company-backends 'company-lsp)
 `

**Comment by yyoncho** [comment]
@phenix3443 

What you have described is the desired behaviour. 

> suggestion：delete the following code in lsp--auto-configure function in lsp-mode.el at line 5439:
(add-to-list 'company-backends 'company-lsp)

This is what autoconfiguration do - it provides default configuration - deleting this line will break thousand of configs so this is no go. If the auto-configure logic does not work for you - you could disable it via setting `lsp-auto-configure` to `nil`.
