### ISSUE TITLE
Powershell formatting is not supported

### ISSUE THREAD

**Issue by r-darwish** [emacs-lsp/lsp-mode#1212]
**Describe the bug**
`lsp-format-buffer` does not work in Powershell even though the server supports formatting

**To Reproduce**
Run `lsp-format-buffer` in a Powershell buffer

**Expected behavior**
Formatting should work like in Visual Studio Code

**Which Language Server did you use**
Powershell

**OS**
macOS

**Error callstack**
```
Debugger entered--Lisp error: (lsp-capability-not-supported "documentFormattingProvider")
  signal(lsp-capability-not-supported ("documentFormattingProvider"))
  (cond ((or (lsp--capability "documentFormattingProvider") (lsp--registered-capability "textDocument/formatting")) (let ((edits (lsp-request "textDocument/formatting" (lsp--make-document-formatting-params)))) (lsp--apply-formatting edits))) ((or (lsp--capability "documentRangeFormattingProvider") (lsp--registered-capability "textDocument/rangeFormatting")) (save-restriction (widen) (lsp-format-region (point-min) (point-max)))) (t (signal (quote lsp-capability-not-supported) (list "documentFormattingProvider"))))
  lsp-format-buffer()
  funcall-interactively(lsp-format-buffer)
  call-interactively(lsp-format-buffer record nil)
  command-execute(lsp-format-buffer record)
  execute-extended-command(nil "lsp-format-buffer" "lsp-format-bu")
  funcall-interactively(execute-extended-command nil "lsp-format-buffer" "lsp-format-bu")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by yyoncho** [comment]
@kiennq willing to take a look?

**Comment by kiennq** [comment]
Powershell language server [PSES](https://github.com/PowerShell/PowerShellEditorServices) is really tricky, it declares that it doesn't support document formatting in capabilities.
However, client can still manually request for it.
https://github.com/PowerShell/PowerShellEditorServices/pull/516

**Comment by yyoncho** [comment]
we might implement patch like adf5ac5cda6dd76bef6a4722321a553f50239c27 (this commit removes the patch).

**Comment by kiennq** [comment]
> we might implement patch like [adf5ac5](https://github.com/emacs-lsp/lsp-mode/commit/adf5ac5cda6dd76bef6a4722321a553f50239c27) (this commit removes the patch).

Nice, I've created a PR for this

**Comment by r-darwish** [comment]
For reference: #1215
