### ISSUE TITLE
lsp-rust auto-import missing module

### ISSUE THREAD

**Issue by jiacai2050** [emacs-lsp/lsp-mode#1214]
I use lsp-mode for rust development, everything work fine, but it seems that it can't auto-import missing module, is there any configurations to do this?
Since vscode can do this, I think emacs can do it too.
rust-lang/rls-vscode#221

![image](https://user-images.githubusercontent.com/3848910/69942816-cb778a80-151f-11ea-89a1-da23d68172b0.png)

`M-x lsp-execute-code-action` returns `No actions to select from`

```
rls -V
rls 1.39.0 (80a1d34 2019-09-20)

lsp-mode-20190831.1803/
```

**Comment by kiennq** [comment]
It seems that you are victim of rust-lang/rust#55338

**Comment by jiacai2050** [comment]
![image](https://user-images.githubusercontent.com/3848910/69964191-e3193800-154c-11ea-94ef-f4648d2e090f.png)

@kiennq Thanks, I try `let b: BTreeMap;` and then lsp-execute-code-action, it indeed popup selection window, but when I choose one, following error happens:

```
Wrong type argument: hash-table-p, nil
```
Any ideas?

**Comment by yyoncho** [comment]
@jiacai2050 can you include the callstack after `M-x toggle-debug-on-error`?

**Comment by jiacai2050** [comment]
```
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  gethash("edit" nil)
  lsp-execute-code-action(nil)
  funcall-interactively(lsp-execute-code-action nil)
  call-interactively(lsp-execute-code-action record nil)
  command-execute(lsp-execute-code-action record)
  helm-M-x(nil #("lsp-execute-code-action" 0 23 (match-part "lsp-execute-code-action")))
  funcall-interactively(helm-M-x nil #("lsp-execute-code-action" 0 23 (match-part "lsp-execute-code-action")))
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)

```

**Comment by yyoncho** [comment]
>  lsp-execute-code-action(nil)

You have somehow bypassed the action selection can you also share what keys do you press after you do see the select action dialog? I am able to reproduce your issue if I press C-RET instead of pressing RET (assuming you are using helm).

**Comment by jiacai2050** [comment]
![image](https://user-images.githubusercontent.com/3848910/69969285-1bbe0f00-1557-11ea-9fee-e2cbeab524cf.png)
This is what I got after `M-x lsp-execute-code-action`, and press `Enter` on line 2

BTY, I am using helm.

**Comment by yyoncho** [comment]
Looks like helm has an issue if there is a new line in the label. I will report it upstream and temporarily do a fix on our side. As a side note, have you tried yo click with the mouse on the overlays in the side line? You could use that as a workaround until we fix the core issue.

**Comment by jiacai2050** [comment]
Thanks, click with mouse works as expected.

**Comment by yyoncho** [comment]
Seems like there is nothing to fix here. (Please reopen if you disagree).
