### ISSUE TITLE
Read only mode

### ISSUE THREAD

**Issue by Jefftree** [emacs-lsp/lsp-mode#1217]
Not sure if this is the intended behavior, but I noticed that ever since installing this, all my buffers have been opening in read-only mode. Is there a way to disable that?

**Comment by yyoncho** [comment]
Can you provide a bit more details, language server, project layout, etc? ATM we use readonly mode only for files that are considered not part of the project.

**Comment by Jefftree** [comment]
I'm using lsp-mode and lsp-ui in go-mode. The language server is gopls which looks to be supported. The project is just a regular git project following the standard golang directory structure.

Sorry I should clarify that opening files is fine, but when using something like `xref-find-definitions` or `xref-find-references`, they jump to buffers that open in read only mode. This did not happen before installing lsp-mode.

**Comment by yyoncho** [comment]
This is by desing. We are openning the files that are not part of the project in view-mode

```
(defun lsp--try-open-in-library-workspace ()
  "Try opening current file as library file in any of the active workspace.
The library folders are defined by each client for each of the active workspace."
  (when-let (workspace (->> (lsp-session)
                            (lsp--session-workspaces)
                            (--first
                             (and (-contains? (-> it lsp--workspace-client lsp--client-major-modes)
                                              major-mode)
                                  (when-let (library-folders-fn
                                             (-> it lsp--workspace-client lsp--client-library-folders-fn))
                                    (-first (lambda (library-folder)
                                              (f-ancestor-of? library-folder (buffer-file-name)))
                                            (funcall library-folders-fn it)))))))
    (lsp--open-in-workspace workspace)
   (defun lsp--try-open-in-library-workspace ()
  "Try opening current file as library file in any of the active workspace.
The library folders are defined by each client for each of the active workspace."
  (when-let (workspace (->> (lsp-session)
                            (lsp--session-workspaces)
                            (--first
                             (and (-contains? (-> it lsp--workspace-client lsp--client-major-modes)
                                              major-mode)
                                  (when-let (library-folders-fn
                                             (-> it lsp--workspace-client lsp--client-library-folders-fn))
                                    (-first (lambda (library-folder)
                                              (f-ancestor-of? library-folder (buffer-file-name)))
                                            (funcall library-folders-fn it)))))))
    (lsp--open-in-workspace workspace)
;;    (view-mode t)
    (list workspace)))
    (list workspace)))
```

Evaluate this in order to remove this behaviour.

**Comment by yyoncho** [comment]
@muirdm @psanford can you comment whether having view-mode enabled in library files make sense for golang? I have implemented in that way, it makes sense for java files but I am not sure it makes sense for the other languages.

**Comment by Jefftree** [comment]
What is the scope of project in this case? I can understand if it opens external library files in read-only, but this is occurring for files within the same git project as the opened file (both files are part of the same lsp-workspace-folder)

**Comment by yyoncho** [comment]
@Jefftree I am not very familiar with go library folders implementation -  probably `lsp-clients-go-library-directories-include-go-modules` is what you are looking for. If you set it to `nil` it will prevent the view mode behaviour.

**Comment by Jefftree** [comment]
@yyoncho: Thanks for your help! I did some further digging and this line seems to be the culprit (https://github.com/emacs-lsp/lsp-mode/blob/68faced9e9dcee61efc3bb7eca07331df9206b6b/lsp-go.el#L150:12).

Due to certain restrictions, my home directory is in the `/usr/...` directory, so all my files were treated as library files. I got around this by just overriding `lsp-clients-go-library-directories`, and everything works perfectly after.

I don't know how common my case is, so feel free to close if this isn't something that needs to be supported.

**Comment by Jefftree** [comment]
Just a follow up: Changing `'("/usr")` to `'("/usr/lib" "usr/local/lib)` fixes my issue. I'm not too familiar with the cross platform compatibility for this library, but if this change is acceptable I can make a PR for it.

**Comment by yyoncho** [comment]
@Jefftree make sense. I also think that adding one message like "Opening file in readonly mode since it is under library folder `foo`" will be helpful too. It would be great if you do a PR.

**Comment by muirdm** [comment]
> view-mode enabled in library files make sense for golang?

Both the standard library and the module cache are read only to the user, so I think it makes sense.

**Comment by seagle0128** [comment]
My two cents.

It does make sense that the library and cache files are read-only. Perhaps the scope of `/usr` is too wide here.
But I am surprised people put the home directory into `/usr`. 😂

**Comment by muirdm** [comment]
This change breaks library path on Mac because Go installs to "/usr/local/go". I'm not sure we should change the default library path to work around one user who puts their home directory under "/usr". What if we instead just add a warning/error message if the project root is inside the language's library dirs?

**Comment by yyoncho** [comment]
I thought that there is an agreement on that - my understanding was that having these library paths is more precise. I would rather not change lsp-mode.el for odd configuration - the logic is complex enough even now. What about adding `/usr/local/go` to the library paths as well? If @Jefftree is fine I could revert the commit as well.

**Comment by muirdm** [comment]
Another option is to leave it "/usr" and change the library check to see if file is under both project root dir and library dir. If it is under both, choose project or library based on which one is closer (i.e. has fewer directories in between).
