### ISSUE TITLE
`lsp` delays running mode hooks

### ISSUE THREAD

**Issue by nverno** [emacs-lsp/lsp-mode#1221]
**Describe the bug**
Calling `lsp` delays running mode hooks until after various configurable variables are used.

**To Reproduce**
Invoke `lsp`

**Expected behavior**
I don't necessarily *expect* this, as this happens with a number of packages, but it makes me happy when initialization hooks run prior to a package using configurable various.

This allows autoloaded, mode specific user configurations to run first.  In the case of lsp-mode, especially, I think this is quite useful given the massive amount of configuration possible in this case.

I suppose a workaround that I use when necessary is something like
```
(with-eval-after-load 'lsp-mode
  (require 'my-lsp-config))
```
but in most cases simply autoloading, eg. `my-lisp-hook` from a configuration file, and having just
`(add-hook 'lsp-mode-hook 'my-lisp-hook)` in the init somewhere is enough to load everything from the config file at the proper time and in the proper order.

**Which Language Server did you use**
Just generic `lsp` in this case.

**OS**
Ubuntu

**Comment by yyoncho** [comment]
1. If you want to use configure the server before it is started - use lsp-before-initialized-hook
2. If you want to run code after lsp-mode is managing a particular buffer - use lsp-mode-hook
3. If you want to perform configuration one time before anything else has been run on lsp-mode side - use with-eval-after load.

Let me know if you need anything more than that.

**Comment by nverno** [comment]
Thanks! I hadn't found the lsp-before-initialized-hook.  None of these hooks handle what I was describing, however, since a fair amount of configuration is run after calling `lsp` (like reading session configuration), but before any hooks are called.  As you say, with-eval-after-load is a fine workaround, though

**Comment by yyoncho** [comment]
@nverno I wouldn't call it workaround, it is a standard pattern for executing code after a package has been loaded. Do you see any problem with using `with-eval-after-load`?

**Comment by nverno** [comment]
> Do you see any problem with using with-eval-after-load?

No, not at all, I didn't mean to imply it was a problem, and I do use the `with-eval-after-load` quite often.  I guess I was thinking about `lsp` like a stereotypical mode where an autoloaded hook would be sufficient, and the entry point would be `(lsp-mode)`.  Thanks for bearing with me ;D
