### ISSUE TITLE
Disable doc help buffer at the bottom?

### ISSUE THREAD

**Issue by ianpan870102** [emacs-lsp/lsp-mode#1223]
Notice the doc buffer for Python's print function at the bottom of this screenshot:

<img width="1105" alt="Screenshot 2019-12-05 at 17 45 35" src="https://user-images.githubusercontent.com/36686900/70224270-f5cb8100-1787-11ea-9bd8-4181590654ab.png">

I have tried the solution `(setq lsp-eldoc-hook nil)` as suggested in #1028 . But the  problem doesn't seem to be coming from eldoc, because the doc buffer still pops up even when eldoc mode is disabled.

The lsp doc help is helpful sometimes, but I don't want it to automatically pop up whenever my cursor is in the parentheses of a function. I'd love to have it disabled or perhaps bind it to a key.

All in all this project is wonderful and I have high respect for its devs. Thanks again.

**Comment by ianpan870102** [comment]
For your reference, this is all the config code I have regarding emacs-lsp:

```
(use-package lsp-mode
  :hook ((c-mode ; clangd
          c-or-c++-mode ; clangd
          java-mode ; eclipse-jdtls
          js-mode ; typescript-language-server
          python-mode ; pyls
          dart-mode
          web-mode) . lsp)
  :commands lsp
  :config
  (setq lsp-prefer-flymake nil)
  (setq lsp-eldoc-hook nil)
  (setq lsp-enable-symbol-highlighting nil)
  (use-package lsp-java :after lsp))

(use-package company-lsp
  :commands company-lsp
  :config (setq company-lsp-cache-candidates 'auto))

```

**Comment by yyoncho** [comment]
Use lsp-enable-signature-help.

**Comment by ianpan870102** [comment]
Cheers! It worked.

**Comment by yyoncho** [comment]
@ianpan870102 FYI you may request it on demand `C-S-SPC`

**Comment by isolet** [comment]
Fantastic!

**Comment by jstaursky** [comment]
None of the above worked for me, so I came up with this
```elisp
  (use-package python
    :if (featurep 'lsp-mode)
    :config
    (setq lsp-eldoc-hook nil)           ;; doesn't seem to work
    (fmakunbound 'lsp-signature-activate)
    (defun lsp-signature-activate ()
      (message nil)
      )
    ;; retain the C-S-SPC functionality
    :bind (([remap lsp-signature-activate] . (lambda () (interactive)
                          (setq-local lsp--last-signature nil)
                          (setq-local lsp--last-signature-index nil)
                          (setq-local lsp--last-signature-buffer nil)
                          (add-hook 'lsp-on-idle-hook #'lsp-signature nil t)
                          (add-hook 'post-command-hook #'lsp-signature-maybe-stop)
                          (lsp-signature-mode t)
                          )))
    )
```

**Comment by ianpan870102** [comment]
Really? Try my config:
```emacs-lisp
(use-package lsp-mode
  :hook ((c-mode          ; clangd
          c-or-c++-mode   ; clangd
          java-mode       ; eclipse-jdtls
          js-mode         ; ts-ls (tsserver wrapper)
          typescript-mode ; ts-ls (tsserver wrapper)
          python-mode     ; mspyls
          ) . lsp)
  :commands lsp
  :custom
  (lsp-diagnostic-package :none)
  (lsp-enable-symbol-highlighting nil)
  (lsp-enable-on-type-formatting nil)
  (lsp-signature-auto-activate nil))
```

**Comment by Yevgnen** [comment]
While setting `lsp-signature-auto-activate` to `nil` disable the whole help buffer, can I have something like this?

<img width="137" alt="Screen Shot 2020-03-09 at 11 14 40 AM" src="https://user-images.githubusercontent.com/16749790/76179860-34ddf800-61f7-11ea-8912-df9cba297251.png">
<img width="287" alt="Screen Shot 2020-03-09 at 11 14 44 AM" src="https://user-images.githubusercontent.com/16749790/76179865-37405200-61f7-11ea-86cc-b4f1886b22c7.png">


i.e. showing current inputing param? Params info only shows when the cursor is above function name, not in a param list.

**Comment by yyoncho** [comment]
@Yevgnen set lsp-signature-render-documentation  to nil.

**Comment by Yevgnen** [comment]
@yyoncho That seems work. Thanks. Just one more question, can I avoid the newline of the signature? 

<img width="284" alt="Screen Shot 2020-03-09 at 7 33 13 PM" src="https://user-images.githubusercontent.com/16749790/76209482-ed7a5a80-623c-11ea-8b0e-05622c469dab.png">
<img width="407" alt="Screen Shot 2020-03-09 at 7 32 35 PM" src="https://user-images.githubusercontent.com/16749790/76209488-eeab8780-623c-11ea-9935-5437137d75d8.png">

**Comment by yyoncho** [comment]
ATM no, since the line is coming from lv package, it is in fact a new window with no borders.

**Comment by Yevgnen** [comment]
In this case, can the signature be displayed in echo area? Maybe I'm wrong but I remember this is what used to be? (before `lsp-signature-auto-activate` was introduced?)

**Comment by yyoncho** [comment]
> In this case, can the signature be displayed in echo area? Maybe I'm wrong but I remember this is what used to be? (before `lsp-signature-auto-activate` was introduced?)

ATM no, I separated both signature and hover information into two separate controls.

**Comment by Yevgnen** [comment]
I don't understand why displaying in echo area when `lsp-signature-render-documentation` is `nil` and `lsp-signature-auto-activate` is `t` would be difficult? Can you elaborate?

**Comment by yyoncho** [comment]
I haven't said that it is difficult. I said that I have split both hover info and signature info so they both could be available at the same time.

**Comment by Yevgnen** [comment]
OK, I understand what you mean now. Thanks.
