### ISSUE TITLE
[poll] review some default settings

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#1226]
I released 6.2 version so we can review some of the default settings:

1. lsp-prefer-flymake - we have flymake as a default but IME most of the users prefer flycheck even if flymake is the default checker. 
2. lsp-ui-doc-enable - it is getting mixed reviews since the the UI control is failing in some common scenarions (e. g. if there is a long identifier lsp-ui-doc might cover the code). 
3. ?

Please share your opinion for 1/2 and eventually propose other changes.

**Comment by muirdm** [comment]
Since flycheck is optional to install, it makes sense to me if we prefer flycheck by default if it is installed.

I don't have a useful opinion about lsp-ui-doc-enable because I disable all overlays/popups (except for completions). Since cursor position is not always "intent" for displaying extra info, I find it distracting to have stuff pop up by default. Maybe having things pop up on mouseover at the mouse position might be better since that is clearer intent? I would be interested to hear from people who run with lsp-ui-doc-mode enabled.

**Comment by jtl5770** [comment]
Prefer flycheck if installed seems reasonable.

I generally I would like the doc popup, but in practice the current implementation is more often than not not correctly sizing the overlay. see e.g. https://github.com/emacs-lsp/lsp-ui/issues/334

Actually I would propose another solution: As the current signature information with lv works pretty well - why not combine the doc for objects with the lookup of signature help? Maybe make it customizable if one wants to (automatically) see only signatures or also doc for the class itself. What should be shown would be determined by the cursor position obviously, if on a type (or a variable) show the doc for the type, if on a method show signature help (as now, show all signatures as e.g. "3/6" if needed, and if already a valid signature is written the right one will be selected by default). So you can still M-n or M-p through the possible signatures if you want to see alternatives.
Ofc one should still be able to trigger doc display by key presses, if you want to have a more permanent display in a separate window.

**Comment by yyoncho** [comment]
I went a bit more radical than suggested in the issue description - Proposed solution - do not enable lsp-ui at all by default:  https://github.com/emacs-lsp/lsp-mode/pull/1238 . I will merge/reject it based on the voting in the PR.

**Comment by muirdm** [comment]
Since lsp-ui is optional to install, I think that already counts as intent to use, so lsp-mode should enable lsp-ui by default. I'm more in favor of just disabling/fixing lsp-ui features that people don't like. The problem with that is I have no idea what parts of lsp-ui people like or don't like (other than the reports you mentioned above).

**Comment by kurnevsky** [comment]
Configs that I use:

https://github.com/kurnevsky/dotfiles/blob/c35492426823d03f582eb54bea5c989d6df15000/.emacs.d/init.el#L975-L994

I like lsp-ui as it shows a lot info with no my effort at all.

**Comment by laurynas-biveinis** [comment]
Re. flycheck vs flymake, unfortunately the former is not compatible with Tramp buffers, which is not obvious, pretends to work initially, but results in buffer corruption.

(sorry for a drive-by comment)

**Comment by yyoncho** [comment]
@laurynas-biveinis 

> Re. flycheck vs flymake, unfortunately the former is not compatible with Tramp buffers, which is not obvious, pretends to work initially, but results in buffer corruption.

Is this lsp-mode related? If so, would you report an issue?

**Comment by laurynas-biveinis** [comment]
@yyoncho, no, in my debugging it appeared to be purely flycheck-related, and seemed to be confirmed by Flycheck/TRAMP googling ("sometimes it works, sometimes it doesn't, never supported officially").

**Comment by yyoncho** [comment]
@laurynas-biveinis thank you. I believe that in the context of lsp-mode flycheck should work over tramp - the issues with flycheck and tramp mode are caused probably by remote process managing which in lsp-mode case is handled by lsp-mode itself. Please correct me if I am wrong and you have issues with flycheck and lsp-mode over tramp. I want to have at least one reliable solution for displaying lsp-mode errors.

**Comment by yyoncho** [comment]
Adding point 3.

```lsp-signature-auto-activate``` - I thought that everybody will like it but apparently it is controversial.

**Comment by laurynas-biveinis** [comment]
@yyoncho, I see, I will try to create a minimum reproducer which can then be triaged whether it's something fixable in lsp-mode

**Comment by yyoncho** [comment]
marking as closed - https://github.com/emacs-lsp/lsp-mode/pull/1384 will indirectly solve https://github.com/emacs-lsp/lsp-mode/issues/1226#issue-533546087 .
