### ISSUE TITLE
File Watch counts files in ignored folders?

### ISSUE THREAD

**Issue by groundflyer** [emacs-lsp/lsp-mode#1235]
I have a small project with a git repo set and every time I open a file a warning popups that there are too many files to watch.
I suspect LSP counts files in the .git directory though there is "[/\\\\]\\.git$" regexp in lsp-file-watch-ignored.

**Comment by yyoncho** [comment]
We use the following function to find the files that has to be watched:

```
(lsp--directory-files-recursively  "<put project directory here>" ".*" t)
```

**Comment by groundflyer** [comment]
Okay, I see, so it considers all the files.

**Comment by yyoncho** [comment]
`lsp--directory-files-recursively` should skip the files that match the lsp-file-watch-ignored. Can you confirm that?

**Comment by groundflyer** [comment]
After a bit of testing I can confirm it works. It doesn't skip the ignored folders themselves though.
Also, I can't make it ignore emacs backups with "~$", but `string-match` matches it.

**Comment by yyoncho** [comment]
Closing based on:

> Edit: the actual reason for warning is bigger than expected submodules.

Please reopen if you disagree.

**Comment by ryuusetou** [comment]
I also have a small project with a git repo set,and I find that LSP counts files in my home dir.

**Comment by yyoncho** [comment]
@ryuusetou use M-x lsp-describe-session and then M-x lsp-workspace-folders-remove

**Comment by ryuusetou** [comment]
@yyoncho after using lsp-describe-session I find that there is a workplace with "/home/ryuusetou"，but the real path of my project is "/home/ryuusetou/hml".I use ccls as c++ backend.

**Comment by yyoncho** [comment]
@ryuusetou as I mentioned use lsp-workspace-folders-remove and the next time you are asked about the project root make sure you pick the correct folder.

**Comment by ryuusetou** [comment]
It works!Thank you!
