### ISSUE TITLE
[Feature Request]Provide not so intrusive alternative for lsp-ui-sideline actions

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#1237]
We may follow what vscode does and display bulb to indicate that there is an code action either by using overlay or indicator in the modeline.

**Comment by ericdallo** [comment]
I could help on that, just don't know the better UI for that, if we show as an overlay on the right fringe/on the end of the line/on minibuffer, or something else...

**Comment by ericdallo** [comment]
Thinking better, minibuffer could not be a good choice, as emacs uses to present all kind of interactions with the user, and a simple `message` can replace the code actions icon.

**Comment by yyoncho** [comment]
yes, seems like there are 3 options.

1. Modeline( the easiest to implement)
2. Just a bulb like vscode do
3. bulb + summary as @matklad suggested

**Comment by ericdallo** [comment]
for the modeline, we can just add and remove the icon to the `global-mode-string` easily
