### ISSUE TITLE
Latest Angular Language Service introduced breaking change.

### ISSUE THREAD

**Issue by JSiebelink** [emacs-lsp/lsp-mode#1241]
**Describe the bug**
The latest release of the angular language service has introduced a breaking change where the entry point of the server is nog called index.js. Therefore the server cannot be initiated using the default lsp-mode config. 

A workaround is to rename the index.js file to server.js. However, the server then crashes due to it not being able to find the required typescript version, namely version 3.6.0.

**To Reproduce**
- Download and install latest vscode-ng-service: https://github.com/angular/vscode-ng-language-service/releases
- Open angular project
- Emacs asks you to restart the angular service
- Rename ~/.angular/extension/server/index.js to server.js
- Angular service now crashes because it cannot find required dependency (typescript 3.6.0)

**Expected behavior**
- Angular service starts and provides diagnostics, auto-completion etc.

**Which Language Server did you use**
vscode-ng-language-service

**OS**
MacOS

**Comment by yyoncho** [comment]
Hi @kyliau ,

Sorry for bothering. We are emacs LSP client and try to support as much language servers as possible. ATM we are downloading the vsix extracting it and running it with `nodejs`. Can you advise on how would be the easies way to run angular language server.

Thanks,
Ivan

**Comment by kyliau** [comment]
@yyoncho We have published a new NPM [package](https://www.npmjs.com/package/@angular/language-server), `@angular/language-server` for all LSP clients. All you need to do is download the package from npm/yarn and install the required dependencies.
There's detailed help instructions when you run `node index.js --help`.
Please let me know if you need more info, thank you!

**Comment by yyoncho** [comment]
@kyliau thank you! 

@JSiebelink I was able to make it work using this command:

```
node ./index.js --ngProbeLocations /home/kyoncho/Sources/vscode-ng-language-service/server/node_modules/ --tsProbeLocations /usr/lib/node_modules --stdio
```

and it works fine but when it is combined with html language server I am having some issues. So ATM you may use it, but on in combination with the html ls. I will update the instructions once I solve the multi-language server issue.

**Comment by JSiebelink** [comment]
@yyoncho & @kyliau:  Thank you so much for looking into this. I am using lsp as a daily driver at work and I am really enjoying it, so this kind of support is really appreciated! 

I will see if I can give it a spin today and see if I can get it working the same. Otherwise I will look forward to the instructions and see if I can figure it out then. Again, thanks so much.

**Comment by JSiebelink** [comment]
@yyoncho: If I understand correctly, this uses the vscode angular service and not the npm package?

**Comment by yyoncho** [comment]
@JSiebelink 
1. Install @angular/language-server & typescript from npm
2. The required version of angular language service was not up to date in npm repository so I cloned the vscode project and built it locally.

**Comment by kyliau** [comment]
@yyoncho the latest language service is published as "next" version.
You can install it using the command `yarn add @angular/language-service@next`, or the npm equivalent.
See complete versions here: https://www.npmjs.com/package/@angular/language-service

**Comment by yyoncho** [comment]
Thank you @kyliau.

@JSiebelink I updated the installation wiki - https://github.com/emacs-lsp/lsp-mode/wiki/Install-Angular-Language-server
