### ISSUE TITLE
Angular language service cannot resolve modules relative to file undefined

### ISSUE THREAD

**Issue by JSiebelink** [emacs-lsp/lsp-mode#1242]
**Describe the bug**
The angular language service version 0.800 cannot find the angular dependencies of the project. Instead it logs an error stating that it cannot resolve modules relative to file 'undefined'.

**To Reproduce**
- Install vscode-ng-language-service version 0.80x or earlier: https://github.com/angular/vscode-ng-language-service/releases?after=v0.900.0-next.4
- Open an angular project by opening an template (html) file
- The angular-ls::stderr buffer prints the relevant error messages

**Expected behavior**
- Correct diagnostics and autocompletion.

**Which Language Server did you use**
angular-ls

**OS**
MacOS

**Error callstack**
![image](https://user-images.githubusercontent.com/24893462/70639203-6ff17f00-1c3a-11ea-8cf7-b46a87b95837.png)

**Comment by yyoncho** [comment]
FYI information I have tested with `0.802.2` and back then it was working fine(at least I didn't receive a bug reports). We will focus on fixing https://github.com/emacs-lsp/lsp-mode/issues/1241 .
