### ISSUE TITLE
Automatically decompile java class feature break after upgrade to version 6.3

### ISSUE THREAD

**Issue by xqliu** [emacs-lsp/lsp-mode#1244]
Before logging the bug, please make sure that:

1. You are using the latest version of `lsp-mode` related packages.
2. You may also try reproduce the issue using clean environment using the following command:
3. Check FAQ and Troubleshooting section (https://github.com/emacs-lsp/lsp-mode#faq and https://github.com/emacs-lsp/lsp-mode#troubleshooting)
``` bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` could be downloaded from `https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el`.
Alternatively, in will be great if you can reproduce the issue using [lsp-docker](https://github.com/emacs-lsp/lsp-docker/) which provides the minimal configurations for `lsp-mode` and ships with most of the language servers.
3. Consider providing a minimal project to reproduce the issue with. Note that `lsp-mode` supports 30+ languages and the maintainers of the project are not familiar with all of the languages and a sample project + full steps to reproduce will help a lot.

**Describe the bug**
Currently after upgrade to lsp-mode 6.3, jump from source to a class definition can not show decompiled class source.

Configuration: 

```
(setq lsp-java-content-provider-preferred "fernflower")
```

**To Reproduce**
1. Open a java file, 
2. Write reference to a class don't have source enable in workspace.
3. invoke lsp-ui-peek-find-definitions, it jumps to a buffer only contains method list of the class, while in previous version, it can show a buffer with decompiled class.

**Expected behavior**
It should show decompiled source.

**Which Language Server did you use**
lsp-java

**OS**
Macos 10.14.6

**Error callstack**
No error.

``` emacs-lisp
(setq lsp-print-io t)
```

```
[Trace - 04:29:20 AM] Sending notification 'textDocument/didOpen'.
Params: {
  "textDocument": {
    "uri": "jdt://contents/xxx.jar/xxx/xxx.class?=boe-library/%5C/Users%5C/xxx%5C/Dropbox%5C/Codes%5C/xxx%5C/xxx%5C/lib%5C/xxx.jar%3Cxxx",
    "languageId": "java",
    "version": 0,
    "text": " // Failed to get sources. Instead, stub sources have been generated by the disassembler.\n // Implementation of methods is unavailable.\nxxxxx(omit the generated stubs)"
  }
}

```

**Comment by xqliu** [comment]
Seems some of the class is not working, while others works.

**Comment by yyoncho** [comment]
This must be reported in the upstream in the decompiler extension including:

1. Test project
2. All details about JDK version/os 
3. Client-server communication. 

I am closing the bug and tagging it as upstream.
