### ISSUE TITLE
lsp-ocaml

### ISSUE THREAD

**Issue by anmonteiro** [emacs-lsp/lsp-mode#125]
I've pushed `lsp-ocaml` to https://github.com/anmonteiro/lsp-ocaml and I'm happy to transfer it to this org. Would you be interested?

I held off on submitting it to melpa because the Github URL may not be final.

**Comment by vibhavp** [comment]
Sure, I can create a new repository under this org and add you to it. Is that okay?

**Comment by anmonteiro** [comment]
I dont think you need to do that. I can just transfer the repo here

**Comment by vibhavp** [comment]
LGTM, go ahead.

**Comment by anmonteiro** [comment]
@vibhavp Apparently I need permissions to create a repo in the organization in order to transfer the repository here.

How do you want to proceed?

**Comment by vibhavp** [comment]
I've created the repository https://github.com/emacs-lsp/lsp-ocaml and given you write access.

**Comment by anmonteiro** [comment]
Thanks, I've pushed my commits to the new repo.
I'll work on submitting it to melpa
