### ISSUE TITLE
How to complete pygobject code

### ISSUE THREAD

**Issue by Baloneo** [emacs-lsp/lsp-mode#1253]
I used fakegir and put the generated files in the virtualenv directory. I found that I couldn't jump to gi.repository during the completion and it didn't work properly. But I put the file generated by fakegir into my project directory, renamed the folder to `gii`, and it works fine. 
```
project
---gii
--- test.py
```
gii 
```
gii
├── __init__.py
├── __pycache__
│   └── __init__.cpython-36.pyc
└── repository
    ├── AppIndicator3.py
    ├── Atk.py
    ├── Atspi.py
    ├── cairo.py
    ├── Dazzle.py
    ├── DBusGLib.py
    ├── Dbusmenu.py
    ├── DBus.py
    ├── fontconfig.py
    ├── freetype2.py
    ├── GdkPixbuf.py
    ├── Gdk.py
    ├── GdkX11.py
    ├── Gio.py
    ├── GIRepository.py
    ├── GLib.py
    ├── GL.py
    ├── GModule.py
    ├── GObject.py
    ├── Gtk.py
    ├── HarfBuzz.py
    ├── __init__.py
    ├── libxml2.py
    ├── PangoCairo.py
    ├── PangoFT2.py
    ├── Pango.py
    ├── PangoXft.py
    ├── win32.py
    ├── xfixes.py
    ├── xft.py
    ├── xlib.py
    └── xrandr.py
```
test.py
```
from gii.repository import Gdk

root_window = Gdk.get_default_root_window()
childs = root_window.get_children()
print(childs)
```

How do I set the  `gii` directory to be added to the autocomplete search range?

**Comment by yyoncho** [comment]
Which language server do you use?

**Comment by Baloneo** [comment]
> Which language server do you use?

pyls

**Comment by yyoncho** [comment]
I am not python expert but I think it is supposed to install pyls in your virtual env and point lsp-mode to use the pyls that is part of it. Use lsp-pyls-server-command to do that. I am closing the issue but you could use it for further questions.
