### ISSUE TITLE
Use character U+25A0 instead of U+2B1B on document color overlay

### ISSUE THREAD

**Issue by kevindragon** [emacs-lsp/lsp-mode#1254]
Looks like Emacs does not support the character between U+2B00 - U+2BFF on Windows properly. So I suggest use U+25A0 instead.

This is what U+2B1B showing in my overlay:
![image](https://user-images.githubusercontent.com/409478/71142619-dbe37100-2252-11ea-9b32-892943a99bd7.png)

Emacs Version:
GNU Emacs 27.0.50 (build 1, x86_64-w64-mingw32)
 of 2019-11-12

My OS:
Windows 10

**Comment by kiennq** [comment]
U+2B1B is displayed perfectly in my environment which is also Windows 10.
I think that you may need a font for that. For now I'm using [CascadiaCodePL](https://github.com/microsoft/cascadia-code/releases), can you try with that font?
Also Symbola fonts may help too

**Comment by kevindragon** [comment]
@kiennq using font CascadiaCodePl can show the U+2B1B character correctly. I prefer out-of-box.

BTW, I use font courier new.
