### ISSUE TITLE
Setting lsp-debounce-full-sync-notifications to nil causes invalid didChange notification 

### ISSUE THREAD

**Issue by kraigher** [emacs-lsp/lsp-mode#1256]
**Describe the bug**
When setting `lsp-debounce-full-sync-notifications` to nil is causes the client to send an invalid contentChanges JSON object:

```json
"contentChanges": ["vector", ["lsp--full-change-event"]]
```

I can trace this back to the codebase on master: https://github.com/emacs-lsp/lsp-mode/blob/348d5e476cc4fda70e20efe5b55d8f50e74e3745/lsp-mode.el#L3417-L3421

I am only superficially familiar with lisp but it seems it could be related to some quoting or missing macro evaluation.

**To Reproduce**
Set `lsp-debounce-full-sync-notifications` to `nil` and trigger a `textDocument/didChange` by editing a file.

**Expected behavior**
A valid `contentChanges` notification is sent.

**Which Language Server did you use**
https://github.com/kraigher/rust_hdl

**Comment by yyoncho** [comment]
@kraigher can you test with the latest lsp-mode? I think this was fixes yesterday.

**Comment by kraigher** [comment]
Yes you are right, it seems to have been fixed by this commit: https://github.com/emacs-lsp/lsp-mode/commit/348d5e476cc4fda70e20efe5b55d8f50e74e3745
