### ISSUE TITLE
lsp-after-uninitialized-hook not following "abnormal hook" conventions

### ISSUE THREAD

**Issue by laurynas-biveinis** [emacs-lsp/lsp-mode#1257]
`lsp-after-uninitialized-hook` name ends with `-hook` and is documented as "List of functions to be called after a Language Server has been uninitialized."

Based on this, one would try to write a regular hook function, i.e. one that takes no args and whose return value is ignored. But this will fail with a "wrong number of arguments" error, because the `lsp-after-uninitialized-hook` passes workspace arg to hook functions.

Based on [Emacs Lisp manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Hooks.html), hooks that take args are called "abnormal hooks", their naming convention is to end with `-functions` instead of `-hook`, and the documentation should describe what is passed (or what is done with the return value).

Grepping for `run-hook-with-args` suggests that there is one more abnormal hook like this one: `lsp-workspace-folders-changed-hook`. This one is documented to take args, but is not suffixed with `-functions` neither.

**Comment by yyoncho** [comment]
Thank you, I was unaware of that convention. We will rename those to end up with `-functions`.

**Comment by laurynas-biveinis** [comment]
Thank you - please also consider `define-obsolete-variable-alias` for some time to make the switch easier for users
