### ISSUE TITLE
Vue: "File local-variables error: (error Invalid command list)", no `vls`

### ISSUE THREAD

**Issue by dennismayr** [emacs-lsp/lsp-mode#1263]
**Describe the bug**
When opening `.vue` files using the `lsp` backend, I'm getting the following error today, visible on the modeline and *Messages* buffer:

`File local-variables error: (error Invalid command list)`

At the same time, `lsp` does not invoke `vls` in version `lsp-20191221`. Reverting back to version `lsp-20191219` works fine though

**To Reproduce**
Create a `.vue` file, like this:

```vue
<template>
  <div>
    <div v-bind:key="todo.id" v-for="todo in todos">
      <!-- go through each todo -->
      <ToDoItem v-bind:todo="todo" v-on:del-todo="$emit('del-todo', todo.id)" />
      <!-- show each individual todo from above-->
    </div>
  </div>
</template>

<script>
import ToDoItem from "./TodoItem.vue";

export default {
  name: "Todos",
  components: { ToDoItem },
  props: ["todos"]
};
</script>
<style scoped></style>
```

**Expected behavior**
`lsp` starts the _vue language server_ (`vls`), code is highlighted as usual, error messages are shown where applicable

**Which Language Server did you use**
lsp-20191221

**Last Working Version**
lsp-20191219

**OS**
ElementaryOS 5.1 / Ubuntu 18.04

**Comment by clement-buchart** [comment]
Hello,
 
Just to help with troubleshooting, i'm getting the same `Invalid command list` error when trying to start lsp on a plain typescript file (typescript-mode), in a project which had lsp running fine prior to a recent upgrade.

**Comment by yyoncho** [comment]
It is caused by missing eslint sever. I will do a fix. Commenting the register call in lsp-eslint.el will fix the issue.

**Comment by clement-buchart** [comment]
Ok, thanks !

**Comment by clement-buchart** [comment]
Confirming that cloning https://github.com/microsoft/vscode-eslint in `~/.doom.emacs.d/.local/etc` folder and setting 
```
        lsp-eslint-server-command `("node"
                                       ,(concat doom-etc-dir "vscode-eslint/server/out/eslintServer.js")
                                       "--stdio")
```
gets everything working, with eslint as a bonus :)
