### ISSUE TITLE
lsp-find-definition pushes marker to xref--marker-ring twice.

### ISSUE THREAD

**Issue by kangjianbin** [emacs-lsp/lsp-mode#1265]
My Emacs version is 26.3. 

Before `lsp-find-definition`, the value of `xref--marker-ring` is:
```
xref--marker-ring is a variable defined in ‘xref.el’.
Its value is
(0 0 .
   [nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil])
```

After `lsp-find-definition`, the value is:
```
(0 2 .
   [#<marker at 2337 in mintty-src/base64.c> #<marker at 2337 in mintty-src/base64.c> nil nil nil nil nil nil nil nil nil nil nil nil nil nil])

```
Looks like the problem is in `lsp-show-xrefs`. It calls `xref-push-marker-stack` to push a marker, then call `xref--show-xrefs` to jump to destination. However, `xref--show-xrefs` will call `xref-push-marker-stack` again.

**Comment by yyoncho** [comment]
I think that this is caused by differences between emacs 26/27. 

ATM lsp-find-definition is not needed - it was introduced since we were unable to find a way to integrate lsp with xref smoothly. This is no longer the case and you can use xref-find-definition instead of lsp-find-definition.

**Comment by kangjianbin** [comment]
Switching to xref-find-definition works. Thanks.
Is lsp-find-definition function deprecated? If yes, we can close the issue.

**Comment by MaskRay** [comment]
The `xref-lsp` backend does not provide all features of `lsp-find-{definition,references,implementation,declaration,type-definition}`

```elisp
(cl-defmethod xref-backend-definitions ((_backend (eql xref-lsp)) identifier) ...

(cl-defmethod xref-backend-references ((_backend (eql xref-lsp)) identifier) ...
```

`lsp-find-definition` is still useful for consistency.

**Comment by muirdm** [comment]
`lsp-find-implementation` seems to also add the starting position to the xref ring twice.

**Comment by danielmartin** [comment]
Has this behavior changed between Emacs 26 and 27? Handling the marker stack seems like the responsibility of `xref.el`, so I'd remove our call to `xref-push-marker-stack` from the affected functions.

> The xref-lsp backend does not provide all features of lsp-find-{definition,references,implementation,declaration,type-definition}

Yeah, differences are tiny in the case of `definition` and `references`, but there are some LSP-specific methods that do not have a counterpart in Xref, so we need to keep them. We need to update the documentation a bit to make the differences more clear to users, though.

**Comment by yyoncho** [comment]
let's keep lsp-find* methods for now since it is not clear what will happen with https://github.com/emacs-lsp/lsp-mode/issues/1117 

I agree with @MaskRay - we may keep it for consistently and better discoverability.

**Comment by muirdm** [comment]
That change doesn't seem to make any difference for me when using `lsp-find-implementation` (Emacs 26.3). If I delete the `(xref-push-marker-stack)` in `lsp-show-xrefs` then it works properly (i.e. it doesn't stop twice at the same place going back with `xref-pop-marker-stack`).

`xref--show-xrefs` always pushes a marker, so doing it in `lsp-show-xrefs` causes duplicate marker. What is the reason we can't remove the call to `xref-push-marker-stack` from `lsp-show-xrefs`?

**Comment by yyoncho** [comment]
Hm, I will redo my testing with `emacs -q` - apparently `evil-mode` is doing some magic on my side since I am unable to reproduce the issue after the change.

**Comment by MaskRay** [comment]
I find the interface of xref not very adequate (for my use cases). `(xref-push-marker-stack)` `(xref-pop-marker-stack)` is the "backward" button, but there is no "forward" button. So I ended up using a jump list  implemented on top of evil-jumps. If someone wants to file/has filed a feature request, this is something worth mentioning.

**Comment by yyoncho** [comment]
Agreed - opened https://debbugs.gnu.org/cgi/bugreport.cgi?bug=38797
