### ISSUE TITLE
lsp-mode race condition when flycheck configured to be applied on file save

### ISSUE THREAD

**Issue by melton1968** [emacs-lsp/lsp-mode#1267]
Before logging the bug, please make sure that:

1. You are using the latest version of `lsp-mode` related packages.
2. You may also try reproduce the issue using clean environment using the following command:
3. Check FAQ and Troubleshooting section (https://github.com/emacs-lsp/lsp-mode#faq and https://github.com/emacs-lsp/lsp-mode#troubleshooting)

Using latest version of everything from the elpa repo and a vanilla configuration with only the changes listed below.

**Describe the bug**

When I save an emacs c++ or Scala buffer, the language server immediately performs a syntax check on the file which is the correct action. However, the language server consistently processes a stale version of the file. I presume this is a race condition between the language server invoking clangd or Scala and the emacs buffer actually being flushed to disk.

This issue is likely masked when using live reporting since that uses the contents of the buffer directly.

**To Reproduce**
In .emacs:

(use-package flycheck
  :init (global-flycheck-mode)
  :config (setq flycheck-check-syntax-automatically '(save mode-enabled))
  (setq flycheck-clang-args (list "-extra-arg-before=-xc++")))

(use-package lsp-mode
  ;; Optional - enable lsp-mode automatically in scala files
  :hook ((c++-mode . lsp) (scala-mode . lsp))
  :config (setq lsp-prefer-flymake nil)
  (setq lsp-clients-clangd-args (cons "--query-driver=/opt/local/bin/clang*9.0" nil))
  (setq lsp-clients-clangd-executable "/opt/local/bin/clangd-mp-9.0"))

(use-package lsp-ui
  :config (setq lsp-ui-flycheck-live-reporting nil))

Load any source file, make a modification, save the buffer.

**Expected behavior**

The language server should process an update-to-date version of the file. 

**Which Language Server did you use**

clangd-mp-9.0 and also Scala.

**OS**
Mac OS X 10.15.2

**Error callstack**

None.

 ** Current work-around **

Save the file. Add and removing a character to mark the buffer dirty and then save the file again.

**Comment by yyoncho** [comment]
> Expected behavior
The language server should process an update-to-date version of the file.

I think that the language server is doing that but the flycheck configuration is not updating the errors since the errors are reveited after the save is performed. E. g.

1. save buffer
2. Flycheck does validation
3. Server sends the diagnostics.

When you disable the live reporting it is up to flycheck and the user to make sure the errors are up to date. Note that lsp-mode does not control when the server is doing the error checking and I don't think that `lsp-ui-flycheck-live-reporting` can work correctly.

**Comment by melton1968** [comment]
Yes, I totally misdiagnosed the issue.

How to we get the intended behavior of having the errors updated on save consistent with what is actually in the buffer?

**Comment by yyoncho** [comment]
@melton1968 the issue is that we cannot onSave checks on the client. The options are:

1. Do not use lsp-ui-flycheck-live-reporting = nil
2. Call manually `flycheck-buffer` manually from time to time which I think might be used for a workaround.

**Comment by melton1968** [comment]
This is addressed in [lsp-ui issue 347](https://github.com/emacs-lsp/lsp-ui/issues/347). The comments contain a one-line patch to work around the issue until it is fixed.
