### ISSUE TITLE
multiple gopls instances are started

### ISSUE THREAD

**Issue by lpan** [emacs-lsp/lsp-mode#1275]
![image](https://user-images.githubusercontent.com/12106903/71536703-39755e80-28e0-11ea-93b1-1ba32ec4c845.png)

It seems that when I jump to another package/project, and if I decide to add it as another root, it would start another instance of `gopls`. Is it an expected behaviour?

**Comment by yyoncho** [comment]
Yes. For servers that do not support workspace folders, we have to fire up new instance for each project root. If the server supports multiple roots it should be registered with `:multi-root t`.

**Comment by seagle0128** [comment]
Some discussions are https://github.com/golang/go/issues/32394.
