### ISSUE TITLE
workDoneProgress is not handled correctly

### ISSUE THREAD

**Issue by alanz** [emacs-lsp/lsp-mode#1277]
**Describe the bug**

Running [haskell-ide-engine](https://github.com/haskell/haskell-ide-engine) current master results in warnings being displayed, as

```
Warning (lsp-mode): Unknown request method: window/workDoneProgress/create
```

According to the current [LSP 3.15 spec](https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#initiatingWorkDoneProgress) the server can initiate progress reporting.

This feature is gated by the client setting a capability, which is done in `lsp-mode` at https://github.com/emacs-lsp/lsp-mode/blob/7ed4422fe4f546ac9e42c19524b6cecf04b7095c/lsp-mode.el#L2637.

The behaviour of this feature changed during the evolution of LSP 3.15, and `lsp-mode` has not kept up.

**To Reproduce**

Install haskell-ide-engine from the repo (tested with c686b63cea7eaacb692a854e450515893707b6c1), open a haskell project.

**Expected behavior**

Progress is reported as the project is loaded.

**Which Language Server did you use**

lsp-haskell

**OS**
Which os do you use?

Debian

Related:  https://github.com/emacs-lsp/lsp-haskell/issues/59

**Comment by mattsawyer77** [comment]
Not sure what the release process is, but I was curious if it would be possible to tag/publish a new release for this issue? currently, attempting to do Haskell development is frustrating due to the constant warnings.

**Comment by alanz** [comment]
@mattsawyer77 I got an update on this via MELPA (I think) earlier today.
