### ISSUE TITLE
Snip is not expanding in Dart lsp

### ISSUE THREAD

**Issue by ram535** [emacs-lsp/lsp-mode#1278]
When selecting a function from the autocomplete list, it is not expanded.

For example selecting the print(...) function from the list inserts `print(...)`  including the dots.
It also feels laggy. It takes like 4 sec. to appear the list of autocomplete options.

```
Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (3 weeks ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
```
I attached the lsp-workspace-show-log output.

[log.txt](https://github.com/emacs-lsp/lsp-mode/files/4008491/log.txt)

**Comment by yyoncho** [comment]
@ram535  is it possible that you are using company-tng frontend (probably when using evil-collection)?

To check that do `M-: company-frontends RET`

**Comment by ram535** [comment]
yes, I am using company-tng.

**Comment by yyoncho** [comment]
company-tng is incompatible with lsp-mode (and with any backend that has snippets) - see https://github.com/company-mode/company-mode/issues/891 . ATM the workaround is to disable it.
