### ISSUE TITLE
Kind annotation is removed from candidate annotation.

### ISSUE THREAD

**Issue by kiennq** [emacs-lsp/lsp-mode#1282]
**Describe the bug**
Kind annotation is removed from candidate annotation.

**To Reproduce**
With 45cb3c70e788, in `lsp--annotate` the candidate kind information is removed.
This resulted in some (potentially) confusion about completion candidate.
An example is when using `lsp-json`, with the following buffer

```jsonc
{
    "$schema": "https://raw.githubusercontent.com/Microsoft/vscode-css-languageservice/master/docs/customData.schema.json",
    "v|
}
``` 
Here is what displayed now
![image](https://user-images.githubusercontent.com/2631472/71573331-ac701680-2b26-11ea-92af-f8b164616a83.png)

**Expected behavior**
Kind annotation should be displayed
![image](https://user-images.githubusercontent.com/2631472/71573353-cc9fd580-2b26-11ea-9a47-e5772b5e01b4.png)

@yyoncho: Can you enlighten me why the kind property is removed from annotation?

**Which Language Server did you use**
`lsp-json`

**OS**
Windows 10

**Comment by yyoncho** [comment]
Thank you. I was experimenting with capf and I have forgotten to revert that part.
