### ISSUE TITLE
web-mode and json-mode revert failed when the file changed on disk

### ISSUE THREAD

**Issue by jadestrong** [emacs-lsp/lsp-mode#1289]
https://github.com/hlissner/doom-emacs/issues/2279

**Which Language Server did you use**
web-mode: vscode-html-languageserver-bin vue-language-server
json-mode: vscode-json-languageserver

**OS**
macOS 10.15.2

I tried uninstall corresponsing language-server, these files can revert as expect.
Then I debugged the lsp-mode:
![EE51B6A7-53DA-4058-A5E5-8993BD72CAE2](https://user-images.githubusercontent.com/18475217/71705352-403d2d80-2e1a-11ea-93db-fe3cae0938a4.png)
https://github.com/emacs-lsp/lsp-mode/blob/f0a9f6931fb58b3028f78d193c31f33a9f13812b/lsp-mode.el#L3365
doom-emacs use **auto-revert** package, when I focus emacs,  `(not revert-buffer-in-progress-p)` print `nil`,  so `textDocument/didChange` doesn't execute, I'm not sure if `lsp--on-change-debounce` will try re-execute lsp-on-change function, but the result show that **the file not revert as expect, and textDocument/didChange execute again**.

**Comment by yyoncho** [comment]
Fixed with https://github.com/yyoncho/lsp-mode/commit/0fc942084d66487e53cc33764a64b5a7f57f9982
