### ISSUE TITLE
Error on trying to close buffer

### ISSUE THREAD

**Issue by MageSlayer** [emacs-lsp/lsp-mode#129]
Hi

Sometimes I get following error with stack when trying to close rust file buffer.
```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  lsp--send-changes(nil)
  lsp--text-document-did-close()
  #<subr kill-buffer>("ast.rs")
  ad-Advice-kill-buffer(#<subr kill-buffer> "ast.rs")
  apply(ad-Advice-kill-buffer #<subr kill-buffer> "ast.rs")
  kill-buffer("ast.rs")
  funcall-interactively(kill-buffer "ast.rs")
  call-interactively(kill-buffer nil nil)
  command-execute(kill-buffer)
```

Shouldn't lsp--text-document-did-close contain  "(when lsp--cur-workspace ..." just as lsp--text-document-did-save does?

Tested under Emacs-25.2.1 + lsp-mode-20171010.545

**Comment by vibhavp** [comment]
Can you try using the `remove-mode-client-association` branch and see if the issue still persists?

**Comment by MageSlayer** [comment]
I've used this branch for 2 hours and this issue does not appear.
I guess it's fixed in this branch.
