### ISSUE TITLE
"replace-match-maybe-edit: Match data clobbered by buffer modification hooks" from lsp-on-change

### ISSUE THREAD

**Issue by paulbdavis** [emacs-lsp/lsp-mode#1293]
When trying to use `replace-string` in a JavaScript(VueJS) buffer using `vls` I get the error `replace-match-maybe-edit: Match data clobbered by buffer modification hooks`

Searching around I was able to solve the issue by wrapping the body of the `lsp-on-change` function in the `(save-match-data ...)` macro.

Interestingly, this issue does not affect golang buffers using `gopls`

**Comment by yyoncho** [comment]
Make sense, willing to provide a PR?

**Comment by il-santo** [comment]
Same problem for me and same solution.

**Comment by ag91** [comment]
@yyoncho I am afraid that this same issue sneaked into `lsp-managed-mode`: I am going to come back with a way to reproduce this. Should I open a new issue for that?

**Comment by yyoncho** [comment]
@ag91 better to have a separate issue.
