### ISSUE TITLE
Java annotations completion bug after last upgrade

### ISSUE THREAD

**Issue by rrudakov** [emacs-lsp/lsp-mode#1303]
**Describe the bug**
After completion of annotation the `@` symbol replaced by first letter of candidate. I use `(setq lsp-prefer-capf t)`.
![output-2020-01-07-11:32:59](https://user-images.githubusercontent.com/6093590/71889397-57458d80-3142-11ea-9914-e7fe8a5cb3c2.gif)

**Which Language Server did you use**
lsp-java

**OS**
Linux 5.4.8-arch1-1 #1 SMP PREEMPT Sat, 04 Jan 2020 23:46:18 +0000 x86_64 GNU/Linux

**emacs version**
GNU Emacs 27.0.60 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.17.3, Xaw3d scroll bars) of 2020-01-07

**Comment by yyoncho** [comment]
I already have a fix, will push it soon.
