### ISSUE TITLE
 Symbol’s value as variable is void: vscode-json-languageserver, can't initialize lsp-mode

### ISSUE THREAD

**Issue by shaneikennedy** [emacs-lsp/lsp-mode#1304]
**Describe the bug**
Failing to initialize lsp-mode

**OS**
macOS 10.15.2

**Error callstack**
`Error (use-package): lsp-mode/:catch: Symbol’s value as variable is void: vscode-json-languageserver`

I'm not familiar enough with elisp or this project to submit a PR but I tracked the issue down to this commit 
```
commit c8ba6171438630b8f2079916ce72e3bb04d7271e
Date:   Mon Jan 6 18:19:24 2020 +0900

    Correct npm installing commands and path for Windows (#1299)
```

When I clone the repo and reset HEAD to right before this commit, lsp-mode can load successfully and connect to lsp clients.

**Comment by yyoncho** [comment]
I tested with `emacs -q -l lsp-start-plain.el` and it works fine. `lsp-dependency` is a macro and the issue might be caused if you have byte compile lsp-json.el after you have loaded old version of lsp-mode which does not have that macro. This will result in a runtime error.

**Comment by tam5** [comment]
@yyoncho confirmed... I am using straight and I had the error, but after rebuilding the package it works fine

**Comment by yyoncho** [comment]
closing based on the previous comment.
