### ISSUE TITLE
company-capf endgame

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#1305]
We miss the following features:

1. Caching - we should cache and filter right after `isIncomplete` is nil
2. Fuzzy/Partial matching - now we match only exact string match. There are categories in emacs completion framework and they have flex matching in emacs 27. We should decide whether to reuce the emacs builtin completion style facilities or create ad-hoc solution. 
3. Fix gui to display matches (see :company-match in company-capf docs).

**Comment by yyoncho** [comment]
@kiennq

**Comment by kiennq** [comment]
> 2\. Fuzzy/Partial matching - now we match only exact string match. There are categories in emacs completion framework and they have flex matching in emacs 27. We should decide whether to reuce the emacs builtin completion style facilities or create ad-hoc solution.

I think we are kind of done for this already. We've already using `completion-all-completion` to filter candidates based on `completion-styles`.
Once we have caching and reuse cache, we will have some degree of fuzzy/partial matching regardless of language server.
For now only language server that return all candidates (like `lsp-json`) can have fuzzy/partial matching.

**Comment by yyoncho** [comment]
Ah, now I got it what do you mean - your implementation is a great way to handle the fact that we should filter based on filterText!

I am not sure we are supposed to use `completion-styles` directly but we should define a completion category and then configure that category with the corresponding style. The completion-styles are global and even if we change it buffer-locally it will probably affect other stuff. This could be easily fixed in the future though.

Let me know if you want to work on this issue.

**Comment by kiennq** [comment]
> Let me know if you want to work on this issue.

Sure, let me work on this issue.

Although, as a side note https://www.gnu.org/software/emacs/manual/html_node/elisp/Completion-in-Buffers.html said that
>Additionally, the collection should generally not be pre-filtered based on the current text between start and end, because that is the responsibility of the caller of completion-at-point-functions to do that according to the completion styles it decides to use.

This actually only true for collection that is not a function (like `elisp-completion-at-point`), in case we're using programmed completion with a function, we're responsible for filtering candidate inside the collection lambda.

**Comment by yyoncho** [comment]
This is ready thanks to @kiennq  - `company-capf` is feature complete and now is in a testing period. After it is over we will update the docs to recommend it over company-lsp.
