### ISSUE TITLE
add ra-emacs-lsp.el automatically

### ISSUE THREAD

**Issue by andrewbanchich** [emacs-lsp/lsp-mode#1308]
`rust-analyzer` [requires us](https://github.com/rust-analyzer/rust-analyzer/tree/master/docs/user#emacs) to manually "add ra-emacs-lsp.el to load path and require it in init.el"

Could this be done automatically by `lsp-mode`? This would also help because I've had times when I update `rust-analyzer` and needed to manually update `ra-emacs-lsp.el`.

**Comment by yyoncho** [comment]
It is already part of lsp-rust.el. The only thing we have to do is to update the rust analyzer docs.
