### ISSUE TITLE
Signature documentation consumes entire frame

### ISSUE THREAD

**Issue by WhiteExponent** [emacs-lsp/lsp-mode#1315]
**Describe the bug**

When `lsp-signature-render-documentation` is non-`nil`, with some functions, the displayed documentation is so large that it occupies almost the entire frame.

**To Reproduce**
Note: This could probably be encountered in any language, but here I am giving the example that I encountered.
1. Install `python-language-server`
2. Find a Python buffer
3. Enter `open(`, and a very large documentation section should open up in the echo area.

**Expected behavior**
The documentation should (IMO) be limited to at most half the frame, as if it was split with `C-x 2`.

**Which Language Server did you use**
`lsp-python`, but I think it will happen with any language server that supports documentation.

**OS**
Debian GNU/Linux 10

**Screenshot**
![image](https://user-images.githubusercontent.com/50279956/72298447-2f3cb980-366f-11ea-9e05-11bb08b6a43b.png)

**Comment by yyoncho** [comment]
I propose showing N lines from the docs by default and having a shortcut to toggle from the full docs to the N lines docs.

**Comment by yyoncho** [comment]
Alternatively we may simply limit the size of the LV window.

**Comment by yyoncho** [comment]
- added `lsp-signature-doc-lines` (default 20) to limit the number of lines to show from the docs
- added function to toggle from full/truncated view - `lsp-signature-toggle-full-docs` (bound to M-a by default in the signature map).
