### ISSUE TITLE
Lsp for groovy - Github repo archived. Support for active implementation

### ISSUE THREAD

**Issue by CsBigDataHub** [emacs-lsp/lsp-mode#1318]
Language server for groovy - https://github.com/palantir/language-servers - has been archive.
does LSP mode support active implementation ? - https://github.com/prominic/groovy-language-server

If so, I guess we need to update that in README!

**Comment by yyoncho** [comment]
Fixed with https://github.com/emacs-lsp/lsp-mode/pull/1319 by @aconchillo
