### ISSUE TITLE
Signature view momentarily takes focus from main buffer

### ISSUE THREAD

**Issue by WhiteExponent** [emacs-lsp/lsp-mode#1322]
**Describe the bug**
When `lsp-signature-mode` is active and a function's signature is displayed, the focus is temporarily shifted to the echo area, which in Emacs Prelude means the file is auto-saved. If you have a package which runs linters on file save, this means every time a function signature is displayed the editor freezes for 2-3 seconds, and in case of `js2-mode` with `prettier-mode`, prevents you from adding arguments to the function (`prettier-mode` deletes trailing commas on file save, and the signature is re-focused when you type a comma).

**To Reproduce**
1. Install Emacs Prelude
2. Enable `lsp-signature-mode`
3. Find any code file
4. Type a function which can display a signature, like Python's `open` 

**Expected behavior**
The signature displayed in the echo area shouldn't take focus away from the main buffer.

**Which Language Server did you use**
`lsp-typescript` and `lsp-python` in my case, but any language server can have this issue.

**OS**
Debian 10

**Comment by yyoncho** [comment]
> When lsp-signature-mode is active and a function's signature is displayed, the focus is temporarily shifted to the echo area, which in Emacs Prelude means the file is auto-saved. 

This sounds like a bug in the component that prelude is using. 

> Expected behavior
The signature displayed in the echo area shouldn't take focus away from the main buffer.

This is not the echo area but separate window - this is how `lv` package works which several other packages use(e. g. hydra).

**Comment by yyoncho** [comment]
I am closing based on the description in https://github.com/jming422/emacs-config/commit/5f61ad97bad46235c7fb4d5650962f2c32e1fde1 (thank you @jming422) . @WhiteExponent please report the issue in supper-save repo.

**Comment by jming422** [comment]
@yyoncho Only now noticed the mention - you're very welcome! Glad the comments in my config ended up being helpful 😄
