### ISSUE TITLE
[Feature Request] Tsserver for JavaScript/TypeScript

### ISSUE THREAD

**Issue by ianpan870102** [emacs-lsp/lsp-mode#1324]
Tsserver is language server that is used by Emacs tide as well as Microsoft Visual Studio Code for Javascript and Typescript development. IMO it is one of the best-implemented servers out there.
Is there a plan to use tsserver as an optional language server backend for emacs lsp-mode? I believe that would be a wonderful option for web developers. Cheers!

References:
https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-%28tsserver%29
https://github.com/ananthakumaran/tide

**Comment by kiennq** [comment]
Emacs `lsp-mode` already has builtin [typescript-language-server](https://github.com/theia-ide/typescript-language-server) which is a wrapper for `tsserver`. You can use that.

**Comment by ianpan870102** [comment]
Ah, I didn't know the typescript-language-server was a wrapper of tsserver. I just checked the docs and you're right. Closing this issue now. Thanks for the reply!
