### ISSUE TITLE
Guidance with .dir-locals.el

### ISSUE THREAD

**Issue by btoconnor** [emacs-lsp/lsp-mode#1325]
Note: I don't have a Gitter account and it's looking for a few more permissions on the OAuth integrations than I'm looking to give out for a quick question.  If asking questions here is a non-starter, I can look into Gitter again.

I'm looking for some guidance on structuring a `.dir-locals.el` file for use with `lsp-mode`.  I've seen a bunch of references[1] searching through Google, but never really any concrete examples.  Specifically, I'm looking for an example of adding specific entries to `lsp-file-watch-ignore`.  I've figured out how to completely override the list, but I'm more interested in adding a few entries to the default rather than completely overriding.  Additionally, I know I can add
`(eval . (add-to-list 'lsp-file-watch-ignore "foo"))`, but that registers as an unsafe modification.  I'd much much much prefer to do something that was considered "safe".

I have other requests for concrete examples in `.dir-locals.el` that I can add if desired, but I figured I'd start with this one first.

1 - https://gitter.im/emacs-lsp/lsp-mode?at=5de0d8a0d64a052fb68277f1

**Comment by yyoncho** [comment]
Based on this it seems like it cannot set the variable to something evaluated on runtime: https://www.emacswiki.org/emacs/DirectoryVariables 

> (eval . (add-to-list 'lsp-file-watch-ignore "foo")), but that registers as an unsafe modification. I'd much much much prefer to do something that was considered "safe".

This won't create .dir-local but it will affect the global `lsp-file-watch-ignore`

IMO  the options are:

1. Use the full list (which you have working).
2. Write some elisp which does what you want. The challenge is that it is not clear what would be the current context when the server requests the files to watch. 
3. Use code like this ```(eval . (setq-local lsp-file-watch-ignore (cons "foo" lsp-file-watch-ignore)))``` this will work if you do not switch the current buffer until the server has been initialized. I think that there is a way to suppress the unsafe warnings for that statement.

**Comment by btoconnor** [comment]
Okay - thanks for the information.  Given the restrictions outlined above, is there any desire to add maybe a variable that a user can specify that by default gets added to `lsp-file-watch-ignore`, that `lsp-mode` appends to `lsp-file-watch-ignore`?

Something along the lines of `lsp-file-watch-ignore-additional`?  I'm not sure how hard that would be to do or how much work that would be.  This way a user could specify an additional `foo` entry to be ignored in a `.dir-locals.el` file without overriding the whole list (and losing any defaults from `lsp-mode`).

Thanks again for your response!

**Comment by yyoncho** [comment]
This is not hard but it is not the natural thing to do. I will think more about it and let you know.

**Comment by yyoncho** [comment]
I think that the following would work: I will introduce a public function in lsp-mode which then could be advised in users' config with custom logic which will allow you to implement the additional local variable or in some other way. Let me know if it makes sense to you.

**Comment by btoconnor** [comment]
I'm still somewhat new to elisp and emacs configuration in general so I'm not sure I followed that completely.  I think it would work - would you mind providing an example of how it would look when implemented?

**Comment by yyoncho** [comment]
Sure.

**Comment by yyoncho** [comment]
Example usage:

``` emacs-lisp

(add-function :around (symbol-function 'lsp-file-watch-ignored)
              (lambda (orig)
                (message "Using the following root %s" (lsp--workspace-root (cl-first (lsp-workspaces))))
                (cons "path-to-add" (funcall orig))))
```

**Comment by btoconnor** [comment]
Thanks for the example usage - I think I'm missing a critical part.  I added that to my `.dir-locals.el` file for the project, and I'm getting a warning in emacs that this is a risky add.  Did I understand this incorrectly?

**Comment by yyoncho** [comment]
This example is not for dir locals but for your config. It also contains an example of how to obtain the current project root so you can write: `if project-root=".." <this> else <that>`.

**Comment by howdoicomputer** [comment]
@yyoncho Hm, how do you use that example? What does that block do?

**Comment by howdoicomputer** [comment]
This fixed the issue I was having: https://github.com/elixir-lsp/elixir-ls/issues/448#issuecomment-760384853
