### ISSUE TITLE
Semantic highlighting while typing

### ISSUE THREAD

**Issue by cprussin** [emacs-lsp/lsp-mode#1326]
I notice that the semantic highlighting isn't updating while I type, it only updates if I re-run `lsp`.  Is there some option that controls this?

**Comment by cprussin** [comment]
Answered in gitter

**Comment by marc0s** [comment]
Can you reproduce the solution in here for the sake of searchability? thanks!

**Comment by cprussin** [comment]
Ah yes, sorry about that.  It is the responsibility of the language server to expose the capability.  `lsp-mode` will automatically send the updates while you type and apply the semantic highlights if the language server announces the capability.  If this isn't working for you for some language it's very likely the language server isn't announcing the capability, check the initial json payload sent by the server in your debug logs.
