### ISSUE TITLE
(setq lsp-pyls-plugins-pydocstyle-enabled nil) doesn't work

### ISSUE THREAD

**Issue by kaiwk** [emacs-lsp/lsp-mode#1327]
**Describe the bug**
I want to use flake8, so before enable lsp-mode, i put this in init.el:

```elisp
(setq lsp-pyls-plugins-pydocstyle-enabled nil)
(setq lsp-pyls-plugins-flake8-enabled t)
```

but when i enable lsp-mode in python-mode, both pycodestyle and flake8 will be enabled.

**To Reproduce**
```elisp
(defun setup-python-ide ()
  (lsp))
(with-eval-after-load 'lsp
  (setq lsp-pyls-plugins-pydocstyle-enabled nil)
  (setq lsp-pyls-plugins-flake8-enabled t))
(add-hook 'python-mode-hook #'setup-python-ide)
```

**Expected behavior**
enable flake8 only in python-mode.

**Which Language Server did you use**
python-language-server

**OS**
Mac OS X 10.14.4

**Comment by yyoncho** [comment]
@mpanarin willing to take a look?

**Comment by mpanarin** [comment]
@kaiwk its `lsp-pyls-plugins-pycodestyle-enabled`, not `lsp-pyls-plugins-pydocestyle-enabled` :)

**Comment by yyoncho** [comment]
@mpanarin thank you!
Closing based on the previous comment.

**Comment by zhangjie2012** [comment]
> @kaiwk its `lsp-pyls-plugins-pycodestyle-enabled`, not `lsp-pyls-plugins-pydocstyle-enabled` :)

```
  (setq
   lsp-pyls-plugins-pycodestyle-enabled nil
   lsp-pyls-plugins-autopep8-enabled nil
   lsp-pyls-plugins-flake8-enabled t
   )
```
not worked for me.

**Comment by yyoncho** [comment]
if you are using `pylsp` settings won't work. You should use the equivalent settings
