### ISSUE TITLE
Note: LSP 3.15 has now been officially published

### ISSUE THREAD

**Issue by alanz** [emacs-lsp/lsp-mode#1328]
See https://microsoft.github.io/language-server-protocol/specifications/specification-current/
and
https://www.npmjs.com/package/vscode-languageclient/v/6.0.0

**Comment by yyoncho** [comment]
Thank you. We now should look for servers implementing the new functionality and start covering the new functionality.

**Comment by yyoncho** [comment]
Closing - in favour of concrete issues: https://github.com/emacs-lsp/lsp-mode/labels/3.15 .
