### ISSUE TITLE
lsp-xml cannot access the jar given in `lsp-xml-jar-file`

### ISSUE THREAD

**Issue by CsBigDataHub** [emacs-lsp/lsp-mode#1343]
my setting -

```emacs-lisp
  (setq lsp-xml-jar-file 
(concat user-emacs-directory "custom-el-scripts/lsp/org.eclipse.lsp4xml-0.3.0-uber.jar"))
```

I have a hook configured for xml-mode to start lsp.

when i open a pom.xml LSP will quit immediately.

error from *xmlls::stderr*

```error
Error: Unable to access jarfile ~/.emacs.d/custom-el-scripts/lsp/org.eclipse.lsp4xml-0.3.0-uber.jar

Process xmlls stderr finished

```

I have also did a `C-h v` on `lsp-xml-server-command` and this is what i get
```
lsp-xml-server-command is a variable defined in ‘lsp-xml.el’.
Its value is
("java" "-jar" "~/.emacs.d/custom-el-scripts/lsp/org.eclipse.lsp4xml-0.3.0-uber.jar")

  This variable may be risky if used as a file-local variable.
```

**Comment by CsBigDataHub** [comment]
Updated - *Relative path* does not work when setting `lsp-xml-jar-file ` value. please use *Absolute path*

**Comment by pythys** [comment]
I think this issue should not be closed, the bug still remains and a fix is needed. Setting lsp-xml-jar-file is a workaround but not fixing the problem from its roots

**Comment by ChetanKoneru** [comment]
Hi @pythys This is not a work around, Java cli do not accept `relative path`, simply using -

` (setq lsp-xml-jar-file ((expand-file-name "~/.emacs.d/custom-el-scripts/lsp/org.eclipse.lsp4xml-0.3.0-uber.jar"))` , will expand to the Absolute path.

I do not think this is something to do with the `lsp-xml-jar-file` variable, just how Java works.

**Comment by pythys** [comment]
That doesn't make sense. Why would I write any code to get LSP working properly for xml using xmlls? Shouldn't the activation work automatically? I just M-X lsp and get rolling. The idea that I have to write any code on my end to get LSP working defeats the purpose doesn't it?
