### ISSUE TITLE
module can only be default-imported using the esmoduleinterop

### ISSUE THREAD

**Issue by jack2gs** [emacs-lsp/lsp-mode#1350]
Hi,

I'm trying to us lsp-mode to do React development with typescript. But it reports following errors.

```tsx
import React from 'react'; // error happens in this line.
import logo from './logo.svg';
import './App.css';
```

Could you give me some advice on how to solve this please?

Thanks,
Jack

**Comment by yyoncho** [comment]
Check this - https://github.com/eclipse-theia/theia/issues/6720#issuecomment-563488535

**Comment by jack2gs** [comment]
Thanks! It's solved. Close it now. :)
