### ISSUE TITLE
Provide method for downloading external dependencies

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#1351]
Requirements:

1. The method should be async to fit in what we currently have in lsp-mode about server installation. 
2. Method signature should be `(success-callback error-callback url download-location)` (unless I am missing something). Refer to lsp-async-start-process .
3. The method should leverage command-line utilities if they are present (e. g. wget/curl/powershell, etc)
4. User should be able to disable certain tool(e. g. curl) and add new tools. 
5. If no download command-line utilities are present we should fallback to emacs built-in facilities.
6. Ability to report progress will be great. 

See lsp-pwsh.el for Powershell implementation.

**Comment by yyoncho** [comment]
cc @lxsameer who is willing to work on that - let me know if you have questions/concerns.

**Comment by akirak** [comment]
> Ability to report progress will be great.

I implemented this feature in my [nix-env-install](https://github.com/akirak/nix-env-install) package. It automatically closes the progress window on success but keeps it on failure. Perhaps it can be altered to support the requirements above with slight modifications:

![screencast](https://raw.githubusercontent.com/akirak/nix-env-install/screenshots/nix-env-install-npm.gif)

**Comment by yyoncho** [comment]
@lxsameer did you had a change to work on that?

**Comment by apiraino** [comment]
If I may suggest, also `company-tabnine` has a nice downloader that seems to tick many boxes of this issue.

**Comment by yyoncho** [comment]
This is fixed.

**Comment by axelson** [comment]
> This is fixed.

That's great! :confetti_ball: 

Are there any docs about how to use this for language server developers?

**Comment by yyoncho** [comment]
No docs, here is an example of how to use it

https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-rust.el#L628
https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-rust.el#L659

It is pretty straightforward but if you have questions on that don't hesitate to ask here or in gitter/discord.

**Comment by axelson** [comment]
Cool, thanks for the examples.
