### ISSUE TITLE
Unable to find server supporting this file. 

### ISSUE THREAD

**Issue by thepreacher** [emacs-lsp/lsp-mode#1358]
A few days ago I decided to tweak my emacs.d so I deleted all the auto installed packages, dirs etc. I made the changes I wanted and started emacs. It all appeared to go well until I started editing a javascript file.  I now get the message `Unable to find server supporting this file. The following servers could be installed automatically`. Thing is I have both `typescript-language-server` and `javascript-typescript-stdio` installed via pnpm in the global scope. I can access all my global node packages via the command line without issues.

I thought maybe that installing the packages using `pnpm` instead of `npm` was the issues but the issue still persisted even after in reinstalled the servers using `npm`.

My other languages `elixir` and `python` work fine. My question is:
1. Why doesn't lsp-mode now find the globally installed language server for javascript and instead opts to installed another one. 
2. Where does it installed this version of the language server and will it overwrite or installed alongside the existing one?

**Comment by yyoncho** [comment]
> Why doesn't lsp-mode now find the globally installed language server for javascript and instead opts to installed another one.

We use `executable-find` to look for global server installation. Probably you do not have these binaries on the path.

> Where does it installed this version of the language server and will it overwrite or installed alongside the existing one?

They are installed in `lsp-server-install-dir` with default `~/.emacs.d/.cache/lsp`

**Comment by yyoncho** [comment]
> We use executable-find to look for global server installation. Probably you do not have these binaries on the path.

By "path" I mean the path that emacs uses.

**Comment by thepreacher** [comment]
I switched from `emacs-plus` to railwaycat's package of Mitsuharu Yamamoto's emacs for mac and I read (can't remember from where now) that with it solved the path problem on mac osx that `exec-path-from-shell` solved, natively, so I took the `exec-path-from-shell package` out and that is the cause of my problem. Your pointer to check the path drew my attention to what the fact.

The only downside is adding that package alone doubles my startup time. Thanks

**Comment by createyourpersonalaccount** [comment]
My problem was that I was running Emacs in daemon mode on Linux and the environment variables `CARGO_HOME` and `RUSTUP_HOME` were not set (although I export them in `~/.profile`). The solution as @thepreacher mentioned is to install `exec-path-from-shell` and follow the instructions of the package in the README to have it load up the env variables correctly.

You can check with `M-x getenv CARGO_HOME`, etc.
