### ISSUE TITLE
Display symbols informations on the current line in the margin

### ISSUE THREAD

**Issue by sebastiencs** [emacs-lsp/lsp-mode#136]
I've written some code and I thought it could be usefull to others.
It displays informations from `lsp-info-under-point` for all the symbols on the current line.
I'm wondering if I can make a PR or create a separate package.

What do you think ?

![peek 21-10-2017 06-08](https://user-images.githubusercontent.com/5273820/31847952-cdbd1f3a-b626-11e7-9e6c-afb3287b89ae.gif)

**Comment by vibhavp** [comment]
Looks good. Does this use any external packages?

**Comment by sebastiencs** [comment]
No external packages, I'm using some recent functions/macros from emacs (like when-let*) so I think I just need to check that to make a PR

**Comment by vibhavp** [comment]
Sure. You can send a PR, I'll try adding some customization options if I can.

**Comment by vibhavp** [comment]
This is now present in lsp-ui, so we can close this.
