### ISSUE TITLE
Problem in web-mode, scss-mode

### ISSUE THREAD

**Issue by BiserStoilov** [emacs-lsp/lsp-mode#1360]
I have installed vscode-css-languageservice and vscode-html-languageserver-bin. Lsp is connected to servers, but not check errors. Any ideas?
Thanks in advance.

**Comment by yyoncho** [comment]
It is hard to tell with that much information. Have you checked the client/server communication? What do you have in `M-x lsp-describe-session`? Does it fail for all files you have tried? Are you on windows? Which version of emacs do you use?

**Comment by BiserStoilov** [comment]
os - OpenSuse 15.1
Emacs 28
![1](https://user-images.githubusercontent.com/2819988/73394810-f5161d80-42e6-11ea-9bc2-92579fc5e023.png)
:sp works with php, python, ruby

**Comment by yyoncho** [comment]
As per feature list here: https://github.com/vscode-langservers/vscode-html-languageserver-bin the html language server does not support diagnostics.
