### ISSUE TITLE
lsp breaks magit-log-trace-definition

### ISSUE THREAD

**Issue by agzam** [emacs-lsp/lsp-mode#1363]
`magit-log-definition` depends on `(which-function)` to figure out name of the function. Because lsp-mode changes `imenu--index-alist` (by appending things like `(Function)` or `(Variable)` to each item) and `(which-function)` depends on it, this breaks aforementioned function. 

And who knows, maybe it's not only this specific function, perhaps many other things that depend on `(which-function)` to return strictly the name of the function, now would break as well.

Can someone suggest a workaround, please?

**Comment by agzam** [comment]
For now I've settled by doing `(setq lsp-enable-imenu nil)`. But that's more like a temp. workaround and not the fix.

**Comment by yyoncho** [comment]
lsp-mode does not just append `(Function)` and `(Variable)` but implements imenu provider. It seems like there is either a which-function bug or lsp-mode is not providing the correct imenu format.

**Comment by yyoncho** [comment]
@agzam can you tell me which mode is broken?

**Comment by agzam** [comment]
it breaks `(which-function)`, when you run it with the cursor being anywhere inside a function body it should return just the name of the function. But when `lsp-enable-imenu` is set to true and lsp gets connected to a lsp-server (in my case that's clojure-lsp), it returns something like: `foo (Function)`. I believe I have explained it in the top comment. Let me know if it remains unclear even after reviewing it.

**Comment by yyoncho** [comment]
I see - most likely those tags `(Function)` are not needed. I will take a look if they can be removed at all.

**Comment by agzam** [comment]
I think it's useful for imenu to show distinction between variables and functions, I don't know if this feature necessarily has to be removed [in order for (which-function) to work properly]. I haven't had time to actually dig a bit more. Maybe I will get a chance to look into this over the weekend. I'll let you know if I find anything interesting. Thank you!

**Comment by yyoncho** [comment]
Proposed fix at https://github.com/emacs-lsp/lsp-mode/pull/1368
