### ISSUE TITLE
Function void: json-serialize

### ISSUE THREAD

**Issue by ianpan870102** [emacs-lsp/lsp-mode#1364]
Lately I've been encountering too many crashes on Emacs 28.0.50 on macOS so I reverted back to the stable version 26.3

However, lsp-mode seems to "not be supported" in Emacs 26.3? If I invoke "lsp" either through "M-x" or by adding a prog-mode hook, it tells me that the function `json-serialize` is void, which is a function introduced after Emacs 27.

Does this mean Emacs 26 will not be able to use lsp-mode?

For your reference, here are my lsp-related configs:

```emacs-lisp
(use-package lsp-mode
  :hook ((c-mode          ; clangd
          c-or-c++-mode   ; clangd
          java-mode       ; eclipse-jdtls
          js-mode         ; ts-ls (tsserver wrapper)
          typescript-mode ; ts-ls (tsserver wrapper)
          python-mode     ; mspyls
          ) . lsp)
  :commands lsp
  :custom
  (lsp-prefer-flymake nil)
  (lsp-enable-symbol-highlighting nil)
  (lsp-signature-auto-activate nil))

```

**Comment by yyoncho** [comment]
It is supported but if you switch emacs version you should byte-compile it again or delete it to force redownloading the package.

**Comment by ianpan870102** [comment]
Thanks, it works after I reinstalled the package. Just to understand a bit more: is it because the lsp-mode package detects the Emacs version upon installation, to decide whether or not to use `json-serialize`?

**Comment by yyoncho** [comment]
Yes - but not upon installation but upon byte-compilation(which is not necessarily the same thing). We do that to make lsp-mode faster.

In general, it is a good practice to delete the packages byte-compiled with different emacs version - new versions of emacs might introduce new instructions that do not work on older versions of emacs.

**Comment by ianpan870102** [comment]
I see, I'll do a cleanup and re-new of my packages then. Thanks for the reply

**Comment by nour-dev** [comment]
I have the same problem . I use emacs doom . and when try to run `(functionp 'json-serialize)` the output is `nil`

**Comment by yyoncho** [comment]
... and does the same solution work for you?

**Comment by rudolfkral** [comment]
@yyoncho I had the same problem as @nour-dev , my solution was to install [Jansson](http://www.digip.org/jansson/) before building Emacs.

As Emacs 27 is still not released yet - meaning everybody using native JSON has to compile it on their own, and there is no easily available information on that non-trivial requirement - maybe we could add the requirement of Jansson in the README?

**Comment by yyoncho** [comment]
@rudolfkral make sense - ideally, we should link the emacs docs.

**Comment by rudolfkral** [comment]
https://github.com/emacs-mirror/emacs/blob/a37166eb80458e87880893e7b8aa98a2a7ce394b/etc/NEWS#L27

@yyoncho This is the best thing I could find, concerning emacs docs. I got it from [a flycheck issue](https://github.com/flycheck/flycheck/issues/1471#issue-326829588).
