### ISSUE TITLE
support rust-analyzer auto-import

### ISSUE THREAD

**Issue by brotzeit** [emacs-lsp/lsp-mode#1365]
The work is already done in https://github.com/rust-analyzer/rust-analyzer/pull/2963 thanks to @flodiebold. Pull requests are very welcome. I'm a little short on time currently.

**Comment by nilehmann** [comment]
Please do 🙏

**Comment by yyoncho** [comment]
@flodiebold what do you think about moving the rust analyzer emacs client-side effort in lsp-mode repo? Do you have some concerns? I want to avoid duplicate work and I do not have strong opinion where the should live (but ideally it should be accessible from melpa).

**Comment by brotzeit** [comment]
Yeah, that would be great. I'm just working on a PR for this and I always feel a little silly to just copy your work and put my name on it =)
But if you want to concentrate on rust-analyzer, no problem. I really appreciate your work.

**Comment by flodiebold** [comment]
I've wondered that myself, this situation is certainly not the best... I think there are still some things missing (in particular the runnables support)? We could remove everything that has been moved from RA though, and just keep a file with 'experimental' addons in the RA repo.

**Comment by yyoncho** [comment]
@flodiebold thank you.

FWIW I wont be against experimental features being added to lsp-mode as well as long as they are documented as experimental(for obvious reasons). I could add you to lsp-mode team if your concern is not having commit rights to the repo. I have mentioned this several times but I prefer all language-specific decisions to be made either by the language users or by language-specific maintainer(in this case @brotzeit ) and it will be even better for lsp-mode if we have someone who takes part of the server-side development. Let me know what you think.

**Comment by brotzeit** [comment]
#1390
