### ISSUE TITLE
lsp-mode python complete show error message

### ISSUE THREAD

**Issue by TPLinux** [emacs-lsp/lsp-mode#1366]
Hi guys, i installed lsp-mode

i tried to use it for python 

i created new project, and new virtual environment

then activated it by (pyvirtualenv) and installed numpy , pyls[all] , flake8 to ensure that all modules i will use is exists in virtualenv

and when i tried a test code . like :
```

import numpy as np

x = np.
```

when the cursor on (DOT) after (np)

i got this message without completion

> LSP :: ValueError: Should not happen. type: del_stmt

i hope you to help me to solve this issue

OS: Mac OS

**Comment by yyoncho** [comment]
CC @mpanarin 

I think that the issue might be related to the fact that you havent started pyls that is coming from venv but @mpanarin is more familiar with that server.

**Comment by mpanarin** [comment]
This looks like a `jedi`error.

Please, post the contents of `pyls: stderr`, as well as installed version of pyls and jedi

**Comment by mpanarin** [comment]
Here is the same issue in jedi repo with the solution

https://github.com/davidhalter/jedi/issues/1484
