### ISSUE TITLE
Running language server inside docker container. How to connect from host?

### ISSUE THREAD

**Issue by we138-go** [emacs-lsp/lsp-mode#1369]
Hello! I am trying to understand this https://github.com/emacs-lsp/lsp-mode#tramp. I am using `solargraph` language server inside docker container and trying to connect from host machine. I confused for this part: 

```
(lsp-register-client
 (make-lsp-client :new-connection (lsp-tramp-connection "binary-or-full-path")
                  :major-modes '(python-mode)
                  :remote? t
                  :server-id 'pyls-remote))
```

what path I should to pass to `lsp-tramp-connection`?

**Comment by yyoncho** [comment]
> what path I should to pass to lsp-tramp-connection?

Local path on the remote machine.

**Comment by yyoncho** [comment]
I am closing the bug but you could still use it for further questions.
