### ISSUE TITLE
Integration with CEDET

### ISSUE THREAD

**Issue by vibhavp** [emacs-lsp/lsp-mode#137]

**Comment by alanz** [comment]
How does this compare with projectile?

**Comment by s-kostyaev** [comment]
> How does this compare with projectile?

CEDET is part of emacs and projectile is third-party project.

**Comment by vibhavp** [comment]
IIRC, projectile concerns itself with locating and managing project files, while CEDET is more to do with browsing the code structurally (symbol references, list of classes, functions, etc).

**Comment by seagle0128** [comment]
CEDET is too slow...

**Comment by vibhavp** [comment]
CEDET is slow mostly because of Semantic, the underlying parsing backend. We can make CEDET use LSP methods and commands instead.

**Comment by seagle0128** [comment]
@vibhavp Good thoughts! 👍 
The first of all is improving the efficiency and stability of `lsp-mode`. I am usging `lsp-go` and `lsp-python`, but they seem not fast and stable. Have to back to `go-mode` and `anaconda-mode` for now. I believe `lsp` is the right direction, but what the devs need is fast and reliable auto completion, refactoring and code analysis, which make Emacs like a modern slight and fast IDE if you want.

**Comment by yyoncho** [comment]
I propose closing as `won't fix` and continue with implementing the code browsing controls in lsp-ui and lsp-treemacs. @vibhavp, what do you think?

**Comment by yyoncho** [comment]
Closing as per offline discussion with @vibhavp
