### ISSUE TITLE
Eldoc mode is empty now, by default

### ISSUE THREAD

**Issue by ratnesh1729** [emacs-lsp/lsp-mode#1376]
I was using lsp from Nov 2019 - and when I reach a function such as `insert( ..)` using my cursor (i.e. hover) - I used to get function overloads in the eldoc area. Now post I updated to new emacs-lsp I could not get these.  
I have to explicitly do `C-S-SPC` to look over overloads. I am also not getting signature helps.
I am using clangd for my CPP and on my ubuntu 16.04.

When I use lsp describe-session - 

<img width="426" alt="Screen Shot 2020-02-02 at 4 39 35 PM" src="https://user-images.githubusercontent.com/11953515/73618185-a1ebe580-45da-11ea-8245-b4e71ff277b9.png">

Let me know any more information is needed. I summarize the settings here -
1. Ubuntu 16, Clangd 9
2. Today's MELPA Emacs-lsp

(Thanks for this great library)

**Comment by yyoncho** [comment]
We recently changed the way signature info is handled. Before that we were calling signatureinfo as part of eldoc. This was adhoc solution. Now signature help is moved into separate control and it is triggered when you press a signature trigger chars (which are `(` and `,` for clangd based on this screenshot). I guess you miss the signature autoactivation right after you perform completion  - you could automatically trigger it via the following snippet:

```
  (add-hook 'company-completion-finished-hook 
            (lambda (candidate) 
              (lsp-signature-activate)))
```

**Comment by yyoncho** [comment]
I am closing the bug but you could use it for further questions.

**Comment by ratnesh1729** [comment]
Thanks for quick help
How would I get the Eldoc area to show function overloads? For example when I used (on earlier emacs version) to place the cursor - eldoc automatically used to show the overloads. This was really helpful feature

**Comment by yyoncho** [comment]
@ratnesh1729 ATM you cannot use eldoc for overloads - this was replaced by signature info.

If you want to display it on cursor move, you could use: `(add-hook 'lsp-on-idle-hook 'lsp-signature-activate)`. When signature is active you could use M-n/M-p to browse through the signatures.
