### ISSUE TITLE
lsp-keymap-prefix set via customize is not respected

### ISSUE THREAD

**Issue by WJCFerguson** [emacs-lsp/lsp-mode#1381]
**Describe the bug**

When `lsp-keymap-prefix` is set via `customize`, it is not respected and the keymap is still on `s-l`.

(side-note, `s-l` is a very popular key related to hjkl directional movement, in sample/default configurations for EXWM, this bug is killing my window manager.  I assume perhaps I can fix it with a `setq`, (Edit: confirmed working) but since it's a full logout under EXWM I haven't yet checked)

**To Reproduce**
`M-x customize-variable <RET> lsp-keymap-prefix`, set it to something else (`s-p` in my case), restart Emacs.

**Expected behavior**
the configuration setting is respected

**Which Language Server did you use**
lsp-python

**OS**
Ubuntu 18.04 Linux

**Error callstack**
N/A

**Comment by WJCFerguson** [comment]
Edited description to include info that setting `lsp-keymap-prefix` via `setq` does work, it's purely an issue with proper handling of customized variables.  Sorry I don't know what the crux of it is - how to make your package properly deal with customized variables, presumably something about the code structure makes it execute before customize is run.

**Comment by yyoncho** [comment]
> it's purely an issue with proper handling of customized variables. 

The property is read during the initialization while the customization settings are loaded after that. In this case, there is nothing we can do except for documenting it. We could try to do some tricks with custom property getters/setters but considering the fact that there is "workaround" it won't pay the effort.

**Comment by yyoncho** [comment]
I am closing the issue, please let me know if you disagree and if you want to eventually work on the fix.

**Comment by shepmaster** [comment]
> there is nothing we can do except for documenting it

Was this documented somewhere? I ran into the same problem, but only found this issue?

**Comment by WMaxZimmerman** [comment]
I am experiencing this same thing. Is there a place that is recommended for setting this variable? Or if that documentation does exist, where might that be?

**Comment by WMaxZimmerman** [comment]
using require I got the prefix to be respected by having the setq very early (first line) of my init
