### ISSUE TITLE
lsp-json seems won't work on win10 

### ISSUE THREAD

**Issue by zijianyue** [emacs-lsp/lsp-mode#1382]
On win10 64bit, emacs 26.2, a simple json file in json-mode(I have json-mode.el installed) ,
after I enable lsp, none of functions of lsp ,such as imenu can work.
The capabilities of lsp-json seems ok, so I don't know why it can't work.

![image](https://user-images.githubusercontent.com/6119928/73769424-97d20e80-47b5-11ea-9739-10172ab60d2a.png)

**Comment by kiennq** [comment]
Did you try this?
> Json completion doesn’t seem working?
The latest vscode-json-languageserver is broken. You will need to install the earlier version of it npm i vscode-json-languageserver@1.2.1

It's on the FAQ section.

**Comment by zijianyue** [comment]
I cleared all my npm packages and reinstall vscode-json-languageserver@1.2.1,but lsp-mode reported json-ls was not found.
![image](https://user-images.githubusercontent.com/6119928/73820807-86c4e400-482d-11ea-95c0-d6265c970454.png)
![image](https://user-images.githubusercontent.com/6119928/73820839-98a68700-482d-11ea-814c-a10669bb26cb.png)

**Comment by yyoncho** [comment]
Dont you need the -g flag? Lsp-mode is using executable-find to find the binary(check \*lsp-log\* for details).

**Comment by zijianyue** [comment]
> Dont you need the -g flag? Lsp-mode is using executable-find to find the binary(check *lsp-log* for details).

OK, it works now
