### ISSUE TITLE
Opening files starting with "env" always invokes bash-ls 

### ISSUE THREAD

**Issue by rnikoopour** [emacs-lsp/lsp-mode#1389]
**Describe the bug**
Any files starting with "env" starts `bash-ls` instead of the proper language server.
i.e. `env.py`, `envelope.go`, `environment.c` all start `bash-ls`

**To Reproduce**
Add `(add-hook 'prog-mode-hook 'lsp-deferred)` in your `~/.emacs`
Open file `/tmp/envelope.go` 
See that `bash-ls` is in use instead of `gopls`

**Expected behavior**
The correct language server is started regardless of the first 3 letters of the filename

**OS**
OSX

**versions**
GNU Emacs 26.1
lsp-mode 20200207.517

**Comment by rnikoopour** [comment]
Current work around is to switch to the major mode you intended to use using `M-x`

**Comment by yyoncho** [comment]
ATM lsp-mode is calculating the language server based on the major mode so this is by design.

**Comment by rnikoopour** [comment]
Ah okay, so this is a bug in Emacs not `lsp-mode`?

**Comment by yyoncho** [comment]
Hm, I tested on my side and I am unable to reproduce that behavior. 

1. What is the major mode when you open `env.py` `(do M-: major-mode RET` to find it out)?
2. What is the major mode when you open that same fine and you have started emacs like that `emacs -q` ?

**Comment by rnikoopour** [comment]
>.<

After reading through my `.emacs` some more I noticed a bad regex that was causing my issue.  Sorry

**Comment by yyoncho** [comment]
> `>.<`
> 
> After reading through my `.emacs` some more I noticed a bad regex that was causing my issue. Sorry and thank you for helping

No worries.
