### ISSUE TITLE
[README bug] Sentence is repeated twice

### ISSUE THREAD

**Issue by ianpan870102** [emacs-lsp/lsp-mode#1399]
In the documentation (README.org), this sentence is repeated twice: **Semantic highlighting (as currently implemented by JDT LS and unreleased builds of clangd, cf. Semantic highlighting spec)**

**Comment by yyoncho** [comment]
I don't see it - can you link the lines?

**Comment by ianpan870102** [comment]
You have already fixed it in this commit: https://github.com/emacs-lsp/lsp-mode/commit/a2b13ddfd20fb5db67a1ba4891dad2e005ffaf87#diff-aacb4ce123f9200898dff4a35e6a8461

Closing issue.
