### ISSUE TITLE
Process lifecycle not managed

### ISSUE THREAD

**Issue by alanz** [emacs-lsp/lsp-mode#14]
Prior to exiting, each process should receive a [ShutdownRequest](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#shutdown) followed by an [Exit Notification](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#exit-notification).

This does not currently happen, and I gather the subprocess has to exit on a SIGHUP from emacs.

**Comment by alanz** [comment]
@vibhavp , perhaps we should consider doing this: https://github.com/jsierant/lsp-mode/commit/b4c125dbb02804add5ea67c32aa04b831d3ccc43

**Comment by yyoncho** [comment]
@alanz at this point lsp-mode sends the required notifications but it kills the server right after that. Can you advice whether this is the correct behaviour or lsp should wait for the server to tear down by itself and kill it only if it takes too long?

**Comment by alanz** [comment]
The protocol says that the client should send a shutdown request, wait for the ack then send the notification.

I can imagine an LSP server that receives the request, does an orderly flush of it's cache, saves values that need to be persisted, then sends the ack.

For servers not using this notification to persist state, I don't think it really matters.  But my preference would be to do it according to the spec, with a timeout.

**Comment by yyoncho** [comment]
It seems like we are ok after https://github.com/emacs-lsp/lsp-mode/pull/689 .
