### ISSUE TITLE
Download rust-analyzer automatically

### ISSUE THREAD

**Issue by flodiebold** [emacs-lsp/lsp-mode#1400]
rust-analyzer provides binary GitHub releases; it would be nice to provide automatic download support for them. It seems that there's already very similar existing support for C#, maybe it makes sense to extract some common code there?

**Comment by yyoncho** [comment]
related: https://github.com/emacs-lsp/lsp-mode/issues/1351

**Comment by ccqpein** [comment]
I have a [common lisp installation/updations script](https://github.com/ccqpein/ccQ-Emacs-d/blob/master/plugins/update-rust-analyzer.lisp). If you guys wanna refer to. 
Thank you.

**Comment by yyoncho** [comment]
Already fixed.
