### ISSUE TITLE
Make lsp--apply-text-document-edit magit-aware?

### ISSUE THREAD

**Issue by zilti** [emacs-lsp/lsp-mode#1405]
I noticed that `lsp-rename` also renames files (depending on the LSP server). I for now just rename the file first using `magit-file-rename` and then run `lsp-rename`, but then I get `lsp--apply-text-document-edit: File already exists`. I thought maybe it'd be worth thinking about making it magit-aware, so it would do the file rename using magit when available?

**Comment by yyoncho** [comment]
> I for now just rename the file first using `magit-file-rename` and then run `lsp-rename`, but then I get `lsp--apply-text-document-edit: File already exists`.

This sounds like a bug. Which language server did you use to reproduce that behavior?

In general, sounds like a good idea - we try to integrate with as many packages as possible and provide a fluent experience. 

As a side note, AFAIK magit(or git itself) will detect that this was a rename once the file is staged, right?

**Comment by zilti** [comment]
I used Intelephense. Without using `magit-file-rename` first, `lsp-rename` properly renamed it.

> As a side note, AFAIK magit(or git itself) will detect that this was a rename once the file is staged, right?

The renamed file showed up as untracked file in Magit afterwards. I doubt magit/git detect this, but I have nothing to back that up with.

**Comment by yyoncho** [comment]
> The renamed file showed up as untracked file in Magit afterwards. I doubt magit/git detect this, but I have nothing to back that up with.

That is true but do you get the expected behaviour when you stage the files?

**Comment by zilti** [comment]
I just checked and, yes, magit detects it.

**Comment by yyoncho** [comment]
> I just checked and, yes, magit detects it.

Base on this I think the whole integration will bring little to no improvements so I am closing the bug. Let me know if you disagree.
