### ISSUE TITLE
On-type formatting doesn't happen if electric-indent-mode is active

### ISSUE THREAD

**Issue by geza-herman** [emacs-lsp/lsp-mode#1416]
**Describe the bug**
I use ccls for editing C++ code, so I'm not sure whether this is an lsp or ccls bug. The bug is, if electric-indent-mode is active, then automatic (on-type) formatting doesn't happen at the closing '}' brace.

**To Reproduce**
Install lsp and ccls packages. I use this init.el file:
```
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package)
)

(eval-when-compile (require 'use-package))

(setq use-package-always-ensure t)

(use-package lsp-mode)
(use-package ccls)
```
Now, open a C++ mode buffer, enable lsp-mode `M-x lsp RET` (ccls server should be started by this) and insert this simple code:
```
int main() {
  if (a==b) {
  }
}
```
Notice, when typing the closing `}` of the `if`, code is not re-formatted: spaces are not inserted around `a==b`. The default ccls formatting (if `.clang-format` doesn't exist) is to put spaces around `a==b`. This doesn't happen.

Now, if you repeat this process, but before typing this code, you disable electric-indent-mode `M-x electric-indent-mode RET`, then you'll notice that at the closing `}` of the `if`, code gets re-formatted: spaces are inserted, and the if becomes `if (a == b) {`

**Expected behavior**
Code should be re-formatted when typing the closing `}`.

**Which Language Server did you use**
lsp-ccls

**OS**
Debian Linux, emacs 26.3

**Note**
The bug can be avoided in the described case, if I turn off electric-indent-mode. However, I'd like to use this mode, as it does other indenting automatically. Like putting `private:` at the right place at typing ':' (and maybe there are other cases as well).

**Comment by yyoncho** [comment]
I am unable to reproduce using the provided init file and when using emacs 26.3. Note that if you type a char which triggers on type formatting and a major mode edits the file after that lsp-mode will discard the server result since the edits that are send by the server no longer can be applied to the file. Can you upload \*lsp-log\* and client-server communication?

**Comment by geza-formlabs** [comment]
I created a little screencast about the problem. I used the `init.el` shown before. I executed emacs by `emacs t.cpp`. Then I first show how it works with electric-indent-mode on (the default, here no re-formatting happens), then I turn it off, and show how it works with electric-indent-mode off (here, code gets re-formatted).

If you still cannot reproduce it, please tell how can I log client-server communication for you.
Thanks!

![output](https://user-images.githubusercontent.com/51319552/74562113-59351480-4f6a-11ea-8681-fa366c672f97.gif)

**Comment by geza-herman** [comment]
I created a little screencast about the problem. I used the `init.el` shown before. I executed emacs by `emacs t.cpp`. Then I first show how it works with electric-indent-mode on (the default, here no re-formatting happens), then I turn it off, and show how it works with electric-indent-mode off (here, code gets re-formatted).

If you still cannot reproduce it, please tell how I can log client-server communication for you.
Thanks!

![output](https://user-images.githubusercontent.com/27892988/74562578-6f8fa000-4f6b-11ea-92a8-80ec5f702d9a.gif)

**Comment by yyoncho** [comment]
> If you still cannot reproduce it, please tell how I can log client-server communication for you.

The instructions are part of issue template.

**Comment by yyoncho** [comment]
Actually, there is no need from the logs - I watched the screencast closely and as you can see the eletric mode is performing indentation. This breaks lsp-mode onTypeFormatting and there is nothing we can do about it - if buffer is modified after we have called the server we cannot apply the text edit.

**Comment by yyoncho** [comment]
TBH we could fix it doing ugly hacks, eg. patching electric-indent-mode to wait for lsp-mode to finish but this is out of lsp-mode scope. I would suggest you to file a feature request agaist ccls to add the onTypeFormatting that are missing.

**Comment by geza-herman** [comment]
Isn't it possible to do the reverse? I mean, to make lsp-mode wait for electric-indent-mode to finish? 

As I see, both lsp and electric-indent registers to `post-self-insert-hook`. So if first electric-indent run, then lsp, it should work, isn't it?

I tried to do this, but it is not that simple, because as it seems, electric-indent-mode always registers into the global post-self-insert-hook, while lsp registers to the local one. And I suppose the order between these is fixed.

**Comment by yyoncho** [comment]
Lsp-mode call is async. Also, the electric indent mode could do random manipulation - we cannot assume that the condition to trigger indentation which is triggerChar pressed still holds.

**Comment by geza-herman** [comment]
For future reference, maybe it helps other people, I found a workaround. Call this in `c-mode-common-hook`: `(define-key (current-local-map) "}" (lambda () (interactive) (c-electric-brace 1)))`. Because of the `1` parameter to `c-electric-brace`, it doesn't perform its electric action.
