### ISSUE TITLE
Cannot select a C++ function in imenu, if it has a static variable

### ISSUE THREAD

**Issue by geza-herman** [emacs-lsp/lsp-mode#1424]
**Describe the bug**
If a C++ function has a static variable, the function itself doesn't show up as an entry in imenu.

**To Reproduce**
Here's init.el:
```
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package)
)

(setq use-package-always-ensure t)

(eval-when-compile (require 'use-package))

(use-package lsp-mode)
(use-package ccls)
(use-package helm)
```
Here's a simple .cpp file:
```
struct StructType {
};

int main() {
	static char x = 0;
}
```

If I enable lsp mode `M-x lsp RET`, then I use `M-x helm-imenu`, it looks like this:
![after_lsp](https://user-images.githubusercontent.com/27892988/74608323-51977c00-50e0-11ea-8358-b49a24e700c1.png)

As you can see, there is no menu entry for `main`. Only for the static variable `x`. The other subtle bug is, that `StructType` is under the `Function` category (not under `Type` or `Class`. But this may be a helm-imenu bug).

If I remove `static`, then `main` will have a menu entry (but no entry for `x` - this is not a problem for me, as I mostly use imenu to navigate between functions):

![no_static](https://user-images.githubusercontent.com/27892988/74608362-a3d89d00-50e0-11ea-910c-fde42a56d3f9.png)

The original code looks like this without lsp-mode (it is OK):
![before_lsp](https://user-images.githubusercontent.com/27892988/74608244-d0d88000-50df-11ea-85a8-b323f134e56e.png)

Note, that this may be connected to the fact, that if I put a struct with a member into a .cpp file, then the struct itself doesn't have an entry in imenu, just the member variables (just like the `main` function). This behavior is consistent among the emacs-embedded `imenu` and the `lsp-ui-imenu` as well.

**Expected behavior**
I think that functions should always have an entry in imenu.
Types should be under the `Function` category (this can be a `helm-imenu` problem, not lsp's).

**Which Language Server did you use**
lsp-ccls

**OS**
Debian Linux, emacs 26.3

**Comment by yyoncho** [comment]
This seems to be a combination of imenu limitation that you cannot select parents and the fact that ccls considers static fields as imenu entries.

I tested with `App.java`  and `emacs -q` 

``` java
package temp;

class App {
    public static void main(final String[] args) {
    }
    
    public static void main2(final String[] args) {
    }
}
```

here it is the corresponding piece of code in lsp-mode:

``` elisp
(if (seq-empty-p (gethash "children" sym))
        (cons name start-point)
      (cons name
            (lsp--imenu-create-hierarchical-index (gethash "children" sym))))
```

Note that we do not provide a point if a particular element has children.

Possible solutions:

1. Ask a question in emacs-devel and file a bug there is no option for that.
2. Ask @MaskRay to provide a setting in ccls to ignore variables in function bodies.  
3. Use alternative that works - lsp-treemacs-symbols works fine.
4. File a feature request for helm-lsp to implement imenu like interface without losing this info.

**Comment by geza-formlabs** [comment]
Okay, thanks! I think that in the short term, 2. is a good option (I think I found why static variables included: there is an `ignore` function in ccls, which doesn't report function static variables to be ignored). On the long term, 4. would be the perfect solution, but I'm not sure it's worth the effort, if "non-leaf nodes can be selected" was the only difference.

**Comment by geza-herman** [comment]
Okay, thanks! I think that in the short term, 2. is a good option (I think I found why static variables included: there is an `ignore` function in ccls, which doesn't report function static variables to be ignored). On the long term, 4. would be the perfect solution, but I'm not sure it's worth the effort, if "non-leaf nodes can be selected" was the only difference.

**Comment by yyoncho** [comment]
> "non-leaf nodes can be selected" was the only difference.

Few more things that are missing:

1. Ability to select the whole function.
2. The server reports also if a symbol is deprecated.
3. The server also reports symbols that are not defined in the current buffer(e. g. fields/methods from super class).

In general, we try to expose all the features/info coming from the server. I am also considering implementing treemacs buffer as a source for helm which will allow us to write the code once and then expose it as a tree and as a searchable tree.
