### ISSUE TITLE
eslint marks `?.` as syntax error even thought optional chaining support in turned on

### ISSUE THREAD

**Issue by shackra** [emacs-lsp/lsp-mode#1430]
**Describe the bug**
In TypeScript and Javascript, I'm using [optional chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining) to safely access attributes of objects that can be potentially null or unexpected. Even thought babel and `tsc` have no issues compiling lines with `?.` eslint manages to mark the dots with the error "Expression expected" 

![imagen](https://user-images.githubusercontent.com/1055216/74719135-1472dd00-51f9-11ea-896c-dd059cd248ef.png)

**To Reproduce**
without changing anything eslint related in lsp-mode, create a .ts file and try accessing some object attributes with `?.`

**Expected behavior**
no diagnostics for that syntax, the eslint use by lsp-mode matches the configuration and reporting of eslint configured in my project.

**Comment by yyoncho** [comment]
Which language server do you use?

**Comment by shackra** [comment]
According to \*lsp-log\*:

```
Command "/home/jorge/.asdf/shims/javascript-typescript-stdio" is present on the path.
Found the following clients for /home/jorge/code/kue/fero/dev/frontend/src/context/invoice/detalle.tsx: (server-id jsts-ls, priority -3)
The following clients were selected based on priority: (server-id jsts-ls, priority -3)
```

**Comment by yyoncho** [comment]
I think that this is a limitation of jsts-ls server or at least we do not control that. Try typescript-langauge-server and follow: https://github.com/emacs-lsp/lsp-mode/issues/1350

**Comment by shackra** [comment]
yes, switching to `typescript-language-server` solved this issue
