### ISSUE TITLE
typescript language server doesn't work without typescript

### ISSUE THREAD

**Issue by rnikoopour** [emacs-lsp/lsp-mode#1435]
**Describe the bug**
When `typescript-language-server` is installed without `typescript` you are prompted to install `ts-ls` or `jsts-ls`

**To Reproduce**
Open a typescript project while only having `typescript-language-server` installed without installing `typescript`

**Expected behavior**
Message saying "typescript-language-server found but could not find typescript

**Comment by rnikoopour** [comment]
Note: The server will start fine on the host.  `lsp-mode` won't start the server

**Comment by yyoncho** [comment]
AFAICS this is what we have right now, marking as closed.
