### ISSUE TITLE
lsp-register-client behaving oddly

### ISSUE THREAD

**Issue by dolphrundgren** [emacs-lsp/lsp-mode#1436]
[message-buffer.txt](https://github.com/emacs-lsp/lsp-mode/files/4222768/message-buffer.txt)
[debugger_log.txt](https://github.com/emacs-lsp/lsp-mode/files/4222769/debugger_log.txt)
[init.el.txt](https://github.com/emacs-lsp/lsp-mode/files/4222773/init.el.txt)

**Describe the bug**
I get the following error message after the init.el file is loaded on startup:

```emacs-lisp
Debugger entered--Lisp error: (void-function lsp-register-client)
  (lsp-register-client (make-lsp-client :new-connection (lsp-stdio-connection "pyls") :major-modes (quote (python-mode)) :server-id (quote pyls)))
  eval-buffer(#<buffer  *load*> nil "/home/username/.emacs.d/init.el" nil t)  ; Reading at buffer position 540
  load-with-code-conversion("/home/username/.emacs.d/init.el" "/home/username/.emacs.d/init.el" t t)
  load("/home/username/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x1df6a1>)()
  command-line()
  normal-top-level()
```

Could be entirely my fault, but I've been running in circles trying to track it down. My elisp ain't so hot either. 

I am using the most recent version of lsp-mode.

**To Reproduce**
Try using the same init.el file that is attached to this bug report.

**Expected behavior**
lsp-register-client shouldn't be described as void.

**Which Language Server did you use**
pyls

**OS**
Arch Linux

**Error callstack**
I've attached files containing the contents of the Backtrace buffer and the Messages buffer, though the latter doesn't appear very enlightening in this case. I did not observe a lsp buffer despite setting lsp-print-io to true.

**Comment by yyoncho** [comment]
lsp-register-client is not autoloaded so you should either (require 'lsp-mode) or use the :config section of use-package.
