### ISSUE TITLE
Consider Documenting Which Version of the LSP lsp-mode Targets

### ISSUE THREAD

**Issue by kat-co** [emacs-lsp/lsp-mode#144]
It appears `lsp-mode` might be targeting the evolving [3.0 spec](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md).

We might also want to consider adopting [semantic versioning](http://semver.org/) and making statements about what changing the major.minor.patch portions mean in relation to this and to `lsp-mode` itself.

**Comment by vibhavp** [comment]
Currently, the package version corresponds to the public facing API provided by `lsp-mode` itself. Switching to semantic versioning is a good idea once we start doing stable releases.

**Comment by kat-co** [comment]
Sounds good.

What version of the LSP is `lsp-mode` targeting? And can we document that somewhere? Perhaps the README?

**Comment by vibhavp** [comment]
> What version of the LSP is lsp-mode targeting?

It aims_to target 3.0 ATM.

> And can we document that somewhere?

What about adding a variable `lsp-version-support` with the value "3.0"? I think a few emacs package indicate version support in a similar manner. 

> Perhaps the README?

That too.

**Comment by kat-co** [comment]
That sounds like a good idea so that we have this information consumable by both code and humans.

Do you have any examples of the `*-version-support` pattern I can reference? A cursory search on my end isn't turning up anything.
