### ISSUE TITLE
textDocument/documentLink requests sent even when no documentLinkProvider defined

### ISSUE THREAD

**Issue by jfacorro** [emacs-lsp/lsp-mode#1441]
**Describe the bug**
lsp-mode client keeps sending `textDocument/documentLink` requests even though the server does not include that capability in its response from `initialize`.

**To Reproduce**
Open any file whose server doesn't define the `documentLinkProvider` capability. Navigate the file and check that the `*lsp-log ...*` buffer contains a lot of `textDocument/documentLink` requests. 

As a workaround I disabled `lsp-enable-links` (i.e. `(setq lsp-enable-links nil)`) to avoid all the unwanted requests, but I think this might not be the best way to avoid them.

**Expected behavior**
Since the `documentLinkProvider` is an optional field in the list of server `capabilities`, don't assume the server supports it when the provider is missing.

**Which Language Server did you use**
`lsp-erlang`.

**OS**
Mac OS X 10.15.3

**Error callstack**
There is no error therefore there is no callstack, but the `*lsp-log*` buffers shows that the client is sending a lot of these:
```
[Trace - 03:06:32 PM] Sending request 'textDocument/documentLink - (861)'.
Params: {
  "textDocument": {
    "uri": "file:///Users/juan.facorro/path/to/module.erl"
  }
}
```

**Comment by yyoncho** [comment]
Here it is how we enable it:

```
(when (and lsp-enable-links
               (lsp-feature? "textDocument/documentLink"))
      (add-hook 'lsp-on-idle-hook #'lsp--document-links nil t))
```

Can you report back what `(lsp-feature? "textDocument/documentLink")` returns?

**Comment by jfacorro** [comment]
Evaluating the expression using `M-x eval-expression` and then `(lsp-feature? "textDocument/documentLink")` is showing `Apparently circular structure being printed`.

If I paste `(lsp-feature? "textDocument/documentLink")` in a buffer connected to a language server through `lsp-mode` and run `M-x eval-last-sexp` I get:
```
Debugger entered--Lisp error: (error "Apparently circular structure being printed")
  prin1-to-string((#s(lsp--workspace :ewoc #s(ewoc :buffer #<buffer *lsp-log: erlang-ls:77107*> :pretty-printer lsp--log-entry-pp :header [[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[
```

**Comment by yyoncho** [comment]
Hm, can you include client-server communication from the start to the error?

**Comment by jfacorro** [comment]
> Hm, can you include client-server communication from the start to the error?
The client-server communication is not failing though.

The error above is just happening when I try to evaluate the expression `(lsp-feature? "textDocument/documentLink")` in isolation using the methods I described above (i.e. `M-x eval-expression` and `M-x eval-last-expr`).

> Can you report back what `(lsp-feature? "textDocument/documentLink")` returns?
Maybe I should check what that function call returns in some other way?

**Comment by yyoncho** [comment]
Some of the server capabilities are registered dynamically that's why I want to see whole client/server communication.

**Comment by kiennq** [comment]
To be fair, in `lsp--on-request`, the request `client/registerCapability` and `client/unregisterCapability` seems not to be logged.

**Comment by yyoncho** [comment]
Ah, we have to fix that...

@jfacorro can you do `M-x trace-function RET lsp--server-register-capability RET`

**Comment by yyoncho** [comment]
or `M-: (lsp--workspace-registered-server-capabilities (first (lsp-workspaces))) RET`

**Comment by jfacorro** [comment]
```
M-: (lsp--workspace-registered-server-capabilities (first (lsp-workspaces)))
```
Returns `nil`.

**Comment by jfacorro** [comment]
I'm not sure what happened but event after re-enabling `lsp-enable-links` I can't see the message in the logs anymore. I will re-open the issue if I can get reproduce it consistently. 

I opened the issue in the first place because it was happening all the time though. 😞 

Sorry for the noise.
