### ISSUE TITLE
[Question] Understanding the capf interface v.s. company-lsp

### ISSUE THREAD

**Issue by ianpan870102** [emacs-lsp/lsp-mode#1442]
I'd love to gain a little bit more insight into the new 'capf' interface; how it is potentially superior to company-lsp; and how one can configure/make use of it.

Some content that led me here:

A comment on a Reddit post by @yyoncho :

> [capf is] much faster due since the flex matching in implemented in C and performs client-side filtering out of the box while company-lsp has to be configured additionally.

An amazing short clip he posted to demo lsp-mode's responsiveness: https://www.youtube.com/watch?v=NNi3m2bc4Xs

I've always experienced flickering/flashing when company-box or company-posframe filters the candidates as I type. I wonder if it is an OS-performance issue. I'm on macOS, what is the OS used in the YouTube clip?

Note that I'm not planning to switch to Spacemacs for the OOTB experience -- however, I am dedicated to investing time into my own config and would like to know more in-depth.

**Comment by yyoncho** [comment]
You enable it either by deleting company-lsp or by setting lsp-prefer-capf to t. 

Company-box: I have some fixes in the following branch: https://github.com/yyoncho/company-box/tree/WIP . I have changed the way company-box is placed and the way the size of the box is calculated which reduces the flickering.
