### ISSUE TITLE
[lsp capf] Company tooltip persists even after Evil insert escapes to normal

### ISSUE THREAD

**Issue by ianpan870102** [emacs-lsp/lsp-mode#1447]
The described behaviour occurs only when `lsp-prefer-capf` is set to `t`.

### Note
Insert state and Normal state are terms used in Evil mode.

### Expected behaviour:
Using Evil, the user finishes typing the word and escapes back to Normal state. The company tooltip should disappear as soon as the escape key is pressed, despite more possible completions at the cursor's position exist.

### Observed behaviour:
The company tooltip still shows the candidates that are possible at the cursor's position, even after the escape key is pressed to enter Normal state.

### Screenshots (the bug happens in the 3rd screenshot)

<img width="460" alt="Screenshot 2020-02-24 at 01 47 37" src="https://user-images.githubusercontent.com/36686900/75116898-c9990f80-56a7-11ea-9148-4e23f1de7b82.png">

<img width="466" alt="Screenshot 2020-02-24 at 01 48 06" src="https://user-images.githubusercontent.com/36686900/75116905-d61d6800-56a7-11ea-8706-4aada43e9b2a.png">

<img width="472" alt="Screenshot 2020-02-24 at 01 48 17" src="https://user-images.githubusercontent.com/36686900/75116909-de75a300-56a7-11ea-9899-a016efd5fb40.png">

**Comment by yyoncho** [comment]
From lsp-mode point of view, switching from normal to insert mode is equivalent to moving a char back. If you want the popup to close bind ESC in company-mode-map to switch to normal+close company popup.

**Comment by kiennq** [comment]
It actually doesn't happens with other capf backends.
In `lsp-mode` capf, we're returning `(symbols-start . (point))` as prefix bound, and it causes this problem.
We can probably follow others and returns `(symbols-start . symbol-end) as prefix bounds.
WDYT?

**Comment by yyoncho** [comment]
If this does not break the case when you trigger completion when you are in the middle of the symbol I am fine with that. Because this case does not work with company-lsp.

**Comment by yyoncho** [comment]
See https://github.com/tigersoldier/company-lsp/issues/122

**Comment by kiennq** [comment]
The `company-capf` will compare the bounds and stop asking for completions when we're in middle of   returned bounds. So yes, this will break the use-case of trigger completion when you are in middle of symbol.

I wonder what's the real use case of trigger completion when in the middle of symbol?

I've used `lsp-pwsh`, `lsp-rust`, `lsp-mspyls` and when trigger the completion in the middle of symbol, they just suggest completions which doesn't end in the suffix after cursor. And when I select a completion, they just replace the suffix with the new candidate.

What's wrong with Emacs way of only showing suggestion when you're at the end of symbol?

**Comment by yyoncho** [comment]
Here it is how it works with jdtls right now: 

![override](https://user-images.githubusercontent.com/13259670/75118808-e7557d00-5685-11ea-9345-e6c1038dc160.gif)

note that going to the end of the currently inserted item only to be able to trigger completion is inconvenient.

Also, in LSP repository they are currently discussion extending the protocol to support 2 behaviours: completion insert and completion override.

**Comment by yyoncho** [comment]
Here it is the lsp issue - https://github.com/microsoft/language-server-protocol/issues/793

**Comment by kiennq** [comment]
> Here it is how it works with jdtls right now:

Isn't that just the completions result of prefix `to` only, even if you delete the `String` part, shouldn't the completions given are the same?

**Comment by yyoncho** [comment]
> Isn't that just the completions result of prefix `to` only, even if you delete the `String` part, shouldn't the completions given are the same?

Yes - you don't have to delete the stuff after `(point)` since the filtering should be performed using `(prefix-start (point))` range.

**Comment by kiennq** [comment]
Hmm, I see. It's certainly benefitable to be able to trigger completion anywhere, just in case language server can provide adequate support.
 @ianpan870102 You can try https://github.com/kiennq/company-capf-noblock which has the ability to not showing candidates when not in insertable `evil-state`

**Comment by yyoncho** [comment]
As a side note, we may fix this by forcing the completion to stop when:
`original-prefix-line` + `prefix` + `original-line-ending` != current-line

**Comment by blahgeek** [comment]
I'm having the same issue. After switching from company-lsp to company-capf, the popup does not hide after leaving evil insert state. Here's my workaround:

```elisp
  (evil-define-key nil company-active-map
    (kbd "<escape>") (lambda () (interactive) (company-abort) (evil-normal-state)))
```

**Comment by kiennq** [comment]
Alternatively you can try to use  https://github.com/kiennq/company-capf-noblock by install it via Quelpa. Or advice `company-capf` directly.
Not test but maybe something like this work

``` elisp
(advice-add 'company-capf :before-while
            (lambda (&rest _)
              (memq evil-state '(insert replace emacs))))
```
