### ISSUE TITLE
Rust Analyzer completion issues

### ISSUE THREAD

**Issue by TatriX** [emacs-lsp/lsp-mode#1452]
`rust-analyzer` completion is practically unusable.

See also #1269

**Describe the bug**
![2020-02-24-122346_840x646_scrot](https://user-images.githubusercontent.com/703150/75148582-435ce780-5700-11ea-986b-4fa76cc9832c.png)
Weird completion with `rust-analyzer`.

**To Reproduce**
```
emacs -q -l lsp-start-plain.el
```
then open `src/main.rs`, find `x.` and `M-tab`.
See attached zip for a test case.
[rust-analyzer-tests.zip](https://github.com/emacs-lsp/lsp-mode/files/4244294/rust-analyzer-tests.zip)
 

**Expected behavior**
With `(setq rustic-lsp-server 'rls)`
![2020-02-24-122657_1446x608_scrot](https://user-images.githubusercontent.com/703150/75148671-7ef7b180-5700-11ea-831c-1594b0bc1c01.png)

**Which Language Server did you use**
`rls` & `rust-analyzer`

**OS**
Arch Linux.
I'm using Emacs from master, and also tried `26.3` just in case.

**Comment by kiennq** [comment]
If you put the `use std::collections::HashMap;` outside of function, you can see the proper completions.

**Comment by TatriX** [comment]
Well, if you use for example `diesel`, then you are expected to put `use` statements in your functions. And I do this quite often if I want to test something. It's a legitimate language feature and I expect completion to work in this case.

**Comment by flodiebold** [comment]
We of course plan to support this, but it is very complicated to implement. You can follow https://github.com/rust-analyzer/rust-analyzer/issues/1165 for it.

**Comment by yyoncho** [comment]
@TatriX I am closing the PR based on the fact that this is something that has to be fixed on the server and there is nothing address on lsp-mode's side.

**Comment by TatriX** [comment]
> TBH, 'practically unusable' and 'I expect' is not the kind of tone that will motivate people to work on this for you though.

Sorry if that sounded rude, I didn't mean that. It's practically unusable *for me right now*, not in general. I understood suggestion to move use statement out of the function as "not a bug", so I just wanted to say that it should work in principle as it's what I expect after rls, not that I'm expecting someone to go and fix it for me.
