### ISSUE TITLE
Feature Request: pyls mypy configuration

### ISSUE THREAD

**Issue by ztlevi** [emacs-lsp/lsp-mode#1456]
As mentioned in the pyls-mypy [readme](https://github.com/tomv564/pyls-mypy#configuration), the mypy doesn't follow user custom PYTHONPATH and cause a lot error check.

Could you add the config there to disable the live-mode? It should only be couple lines of changes and I am willing to help testing.

Thanks!

**Comment by mpanarin** [comment]
This has already been tackled and discussed [here](https://github.com/emacs-lsp/lsp-mode/pull/1317)
