### ISSUE TITLE
Lenses does not work in rust analyzer 

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#1463]
There are at least 3 types of lenses in rust analyzer:

1. Implementation
2. Run test
3. Run app.

**Comment by yyoncho** [comment]
cc @brotzeit @flodiebold

**Comment by jacg** [comment]
As a non-expert, is there anything I could do to help with this?

**Comment by yyoncho** [comment]
@adam-r-kowalski do you have something for vscode-cpp debugger? 

@jacg it is relatively easy to integrate those, we have such integration for scala metals. But IMO the integration should be with vscode-cpp which is yet to be implemented in dap-mode.
