### ISSUE TITLE
Rust analyzer not running

### ISSUE THREAD

**Issue by rakanalh** [emacs-lsp/lsp-mode#1467]
**Describe the bug**
Running emacs and opening a rust project, LSP reports a couple of messages indicating that rust-analyzer is running and is connected.

lsp-log buffer
```
Command "rls" is present on the path.
Command "rust-analyzer" is present on the path.
```

messages buffer:
```
LSP :: rust-analyzer:4787 initialized successfully
LSP :: content modified
LSP :: workspace loaded, 772 rust packages
```

However, running `lsp-rust-analyzer-status` reports that it is not running.

**To Reproduce**
Here are my local doom emacs config:
```
(setq lsp-rust-server 'rust-analyzer)
(setq lsp-enable-file-watchers nil)
(setq lsp-enable-completion-at-point t)
(setq lsp-enable-imenu t)
(setq lsp-rust-analyzer-cargo-watch-enable nil)

(setq rustic-analyzer-command '("rust-analyzer"))
(setq rustic-lsp-server 'rust-analyzer)
(setq rustic-format-on-save nil)
(setq rustic-lsp-format nil)
```

**Expected behavior**
LSP reports that rust analyzer is not running while it is
```sh
~ ps aux | grep analyzer
rakan             4787   0.0  8.2  5703832 1376504   ??  S     4:01PM   1:46.49 /Users/rakan/.cargo/bin/rust-analyzer
```

**Which Language Server did you use**
rust-analyzer

**OS**
MacOS

**Comment by brotzeit** [comment]
Can you please try to set the absolute path of your `rust-analyzer`.

**Comment by brotzeit** [comment]
I'm on linux, can somebody please test this ? I can't reproduce it...

**Comment by brotzeit** [comment]
So nothing of the lsp-mode features is actually working ?

**Comment by rakanalh** [comment]
yea pretty much.  "goto definition" shows as "xref" list instead of lsp-ui, no auto-completion.

**Comment by brotzeit** [comment]
What happens if you use the full path of the binary ?

**Comment by yyoncho** [comment]
@rakanalh can you also include client-server logs?

**Comment by rakanalh** [comment]
Do you mean the `*rust-analyzer*` and `rust-analyzer:stderr*`?

If so, the stderr shows the following:
```
[ERROR ra_project_model] cyclic dependency frame-support -> frame-system
[ERROR ra_project_model] cyclic dependency substrate-test-runtime -> sc-executor
[ERROR ra_project_model] cyclic dependency sp-runtime-interface -> sp-core
[ERROR ra_project_model] cyclic dependency sp-runtime-interface -> sp-io
[ERROR ra_project_model] cyclic dependency sp-runtime-interface -> sp-runtime-interface-test-wasm
[ERROR ra_project_model] cyclic dependency sp-runtime-interface -> sp-state-machine
[ERROR ra_project_model] cyclic dependency sc-client -> sc-executor
[ERROR ra_project_model] cyclic dependency pallet-transaction-payment -> pallet-balances
[ERROR ra_project_model] cyclic dependency pallet-babe -> substrate-test-runtime
[ERROR ra_project_model] cyclic dependency sc-client-api -> sc-executor
[ERROR ra_project_model] cyclic dependency substrate-test-runtime-client -> sc-client
[ERROR ra_project_model] cyclic dependency substrate-test-runtime-client -> substrate-test-client
[ERROR ra_project_model] cyclic dependency substrate-test-runtime-client -> substrate-test-runtime
[ERROR ra_project_model] cyclic dependency node-testing -> node-executor
[ERROR rust_analyzer::main_loop] overly long loop turn: 134.831756ms
```
This is from opening the [substrate project](https://github.com/paritytech/substrate) but nothing else.

Otherwise, please let me know where i can find those logs.

**Comment by yyoncho** [comment]
There are instructions in the issue template and also in the troubleshooting section of the readme.

**Comment by yyoncho** [comment]
As a side note, based on the stderr log IMO the rust analyzer is not able to handle your project and this is probably a server issue. Can you try if it works with hello world project?

**Comment by yyoncho** [comment]
cc @flodiebold

**Comment by rakanalh** [comment]
I tried again on a simpler project, `lsp-rust-analyzer-status` works. These cyclic dependencies might be preventing rust-analyzer from running.

**Comment by flodiebold** [comment]
@rakanalh Can you report a bug at https://github.com/rust-analyzer/rust-analyzer/issues?

**Comment by rakanalh** [comment]
@flodiebold done. Closing this issue.

**Comment by rakanalh** [comment]
Reopening as i can see this issue again:
I have executed `lsp-rust-analyzer-status multiple times and in `*Messages*` buffer i see:
```
rust-analyzer not running.
rust-analyzer not running.
```

The client-server logs are here:
[client-server.log](https://github.com/emacs-lsp/lsp-mode/files/4277869/client-server.log)

There's no `rust-analyzer/analyzerStatus` being logged (not sure if it is supposed to be).

**Comment by yyoncho** [comment]
Didn't we agree that it is a server-side issue based on the stderr buffer?

**Comment by rakanalh** [comment]
This time, i couldn't see any panics from the server in the `lsp-log` buffer.

**Comment by yyoncho** [comment]
> The question is... should the client-server logs show this call?

I think that we have a bug and we miss some of the communication.

Do you use the same project to hit the issue?

**Comment by rakanalh** [comment]
That is correct, i am only working on the substrate project at the moment.

**Comment by nilehmann** [comment]
I have a related issue, `rust-analyzer` works just fine except that when I try to use `lsp-rust-analyzer-expand-macro` (or `lsp-rust-analyzer-status`) I get "rust-analyzer not running."

If I change https://github.com/emacs-lsp/lsp-mode/blob/f6be9cce4fd296c1448db2ad7b7b143951213aec/lsp-rust.el#L583

for
```elisp
  (-if-let (workspace (lsp-find-workspace 'rust-analyzer))
```
it works just fine.

**Comment by brotzeit** [comment]
@nilehmann This is odd. Can you please confirm that `default-directory` contains the correct path when you execute these commands.

**Comment by brotzeit** [comment]
Are you using rust-mode ?

**Comment by nilehmann** [comment]
Oh, yeah forgot to mention. I'm using the rust layer in spacemacs (develop), which I think uses `rust-mode`

**Comment by passchaos** [comment]
I have also encountered this problem. Completion and jump functions are normal, but rust-analyzer related commands such as 'lsp-rust-analyzer-status' will prompt 'rust-analyzer not running' when executed. 
```
LSP :: rust-analyzer:82111 initialized successfully
LSP :: content modified
rust-analyzer not running.
```
*rust-analyzer::stderr* and *rust-analyzer* are both empty, and the contents of *lsp-log* are as follows:
```
Command "rls" is not present on the path.
Command "rust-analyzer" is present on the path.
Command "rls" is not present on the path.
Command "rust-analyzer" is present on the path.
Found the following clients for /Users/passchaos/Work/timer-learn/src/main.rs: (server-id rust-analyzer, priority 1)
The following clients were selected based on priority: (server-id rust-analyzer, priority 1)
Command "rls" is not present on the path.
Command "rust-analyzer" is present on the path.
Command "rls" is not present on the path.
Command "rust-analyzer" is present on the path.
Found the following clients for /Users/passchaos/Work/timer-learn/src/main.rs: (server-id rust-analyzer, priority 1)
The following clients were selected based on priority: (server-id rust-analyzer, priority 1)
Creating watch for /Users/passchaos/Work/timer-learn
Creating watch for /Users/passchaos/Work/timer-learn/.cargo
Creating watch for /Users/passchaos/Work/timer-learn/.vscode
Creating watch for /Users/passchaos/Work/timer-learn/src
```

**Comment by brotzeit** [comment]
Please test it with https://github.com/emacs-lsp/lsp-mode/commit/3b75d8b9f43b826b2674c5673cac0fe6c5fdf3e9

**Comment by nilehmann** [comment]
@brotzeit, https://github.com/emacs-lsp/lsp-mode/commit/3b75d8b9f43b826b2674c5673cac0fe6c5fdf3e9 is working for me.

**Comment by passchaos** [comment]
> Please test it with [3b75d8b](https://github.com/emacs-lsp/lsp-mode/commit/3b75d8b9f43b826b2674c5673cac0fe6c5fdf3e9)

Working for me too.

**Comment by yyoncho** [comment]
It seems like there is nothing more to do here. Please reopen if you disagree.
