### ISSUE TITLE
Use lsp-mode offline ?

### ISSUE THREAD

**Issue by deb75** [emacs-lsp/lsp-mode#1479]
Hello,

Can I use lsp-mode without an internet connexion ? I am behind a firewall that prevents outgoing connexions from all programs except a few ones (mail and web).

Regards

**Comment by yyoncho** [comment]
lsp-mode once installed does not require internet connection. What you can do is to download lsp-mode + lsp-mode's deps zip them and then unzip them in the elpa dir on your PC.

The same is true for the language servers. I am closing the issue but you could use it for further questions.

**Comment by deb75** [comment]
Hi,

I am happy to hear that because I thought at first that `lsp-mode` required to access to some server to work. I would like to use it for `java`.

Behind the firewall, I can manually install lsp-mode by downloading the file from melpa. However, where do I find lsp-mode's deps zip ?

Regards

**Comment by yyoncho** [comment]
I think what would work best for you is to install it on your personal PC and then zip the ~/emacs.d/elpa dir. Also, you should package `lsp-server-install-dir`. You could do the installation manually downloading every dependency one by one but this will be harder to do.

**Comment by deb75** [comment]
I tried to modify `lsp-server-install-dir` to another location, after having moved the server to that location :
```
(use-package lsp-mode
  ;; set prefix for lsp-command-keymap (few alternatives - "C-l", "C-c l")
  :init
(setq-default lsp-server-install-dir "~/.emacs.d/lsp/server")
(setq lsp-server-install-dir "~/.emacs.d/lsp/server")
```
But each time I open a java file, it complains it does not find the server. Did I miss something ?
