### ISSUE TITLE
Error processing message (error "Selecting deleted buffer").

### ISSUE THREAD

**Issue by jjYBdx4IL** [emacs-lsp/lsp-mode#1505]
lsp-mode version 20200310.2120
clang/clangd version 9.0.0 (Ubuntu 18.04 LTS amd64).
emacs 26.3

If I start lsp-mode for C/C++ files inside a workspace that is symbolically linked, I get the message:

    Error processing message (error "Selecting deleted buffer").

i.e. $HOME/cpp/someProjectWorkspace where $HOME/cpp is a symbolic link to a sub-folder of checked out subversion repository. I can't find any hints in the workspace IO log.

Every other package except use-package was removed from the emacs installation.

**Comment by yyoncho** [comment]
Can you provide a callstack?

**Comment by jjYBdx4IL** [comment]
sorry, no

**Comment by s-kostyaev** [comment]
I saw the same messages with `gopls` after `desktop-read`.
