### ISSUE TITLE
Show doc tooltip of completion candidates using company-capf

### ISSUE THREAD

**Issue by liushihao456** [emacs-lsp/lsp-mode#1513]
When using company-lsp, the documentation of the selected candidate (not confirmed yet) will be shown in a hover frame besides if company-quickhelp or company-box is installed. As I saw in your documentation lately that company-capf is preferred, I switched to it. And the feature above stopped working..

After reading some relevant documentation, I realized that this is because (lsp-completion-at-point) function returns a plist without the :company-doc-buffer entry, which is used by company-quickhelp/box to fetch candidate documentation and render it.

Can this be implemented? I see it's not very hard, judging by the relevant code in company-lsp. I wanted to write it myself but I'm not very good at elisp and lsp...

**Comment by yyoncho** [comment]
@kiennq willing to take a look?

**Comment by kiennq** [comment]
let me take a look
