### ISSUE TITLE
Pause after completion (Emacs 28, Ubuntu, ReasonML language server)

### ISSUE THREAD

**Issue by yashrk** [emacs-lsp/lsp-mode#1516]
After completing a symbol I have several seconds of rotating cursor and irresponsive Emacs.

I tried all the recommendations from `README.md`, there was no effect (except `(setq lsp-prefer-capf t)` breaks autocompletion at all).

Ubuntu 19.10, Emacs from Ubuntu Emacs Lisp team (https://launchpad.net/~ubuntu-elisp/+archive/ubuntu/ppa), rebuilt manually with `libjasson` support for fast JSON functions.

In `*lsp-log*` I see only
```
Buffer modified ignoring response. Method textDocument/hover.
```

Profiler report is in an attachment. The most interesting lines are probably the following:
```
              - lsp--resolve-completion                          2333  96%
               - mapcar                                          2333  96%
                - #<compiled -0x1a19c66d9b74373d>                2333  96%
                 - lsp-request                                   2332  96%
                  - accept-process-output                           4   0%
```

[profiler-report.txt](https://github.com/emacs-lsp/lsp-mode/files/4331846/profiler-report.txt)

**Comment by yashrk** [comment]
I found a workaround. Adding `'company-capf` to `company-backends` fixes the problem.

So I added to my `.emacs`:
```
(add-hook 'reason-mode-hook (lambda ()
                              (add-hook 'before-save-hook 'refmt-before-save)
                              (lsp)
                              (company-mode 1)
                              (lsp-treemacs-sync-mode 1)
                              (merlin-mode)
                              (push 'company-capf company-backends)))                  ; <--- This line was changed
```

But IMHO described above is still a bug, this solution isn't described in `README.md`, and looks like it isn't described anywhere in the Net. I even found the recomendation to _remove_ `company-capf` from `company-backends`.

Maybe this behavior should be fixed or at least documented.

**Comment by yyoncho** [comment]
> I found a workaround. Adding 'company-capf to company-backends fixes the problem.

This is equivalent to sent lsp-prefer-capf to t. I am closing the issue since it is related to company-lsp which tries to resolve the item before it is inserted which is wrong. And also company-lsp is no longer supported and company-capf is the recommended way to do completion.

**Comment by yashrk** [comment]
But `(setq lsp-prefer-capf t)` on the same string in the same hook doesn't help. Moreover, when I uninstall company-lsp, the bug remains — so it's probably _not_ related with company-lsp.

And `(push 'company-capf company-backends)` solves the problem.

**Comment by kiennq** [comment]
When did you set `lsp-prefer-capf`? It has to be set before activating `lsp`

**Comment by yashrk** [comment]
> When did you set `lsp-prefer-capf`? 

I tried to call `lsp-prefer-capf` on the same line where I call `push` manually in [this](https://github.com/emacs-lsp/lsp-mode/issues/1516#issuecomment-598979783) comment above: 3 lines after calling `(lsp)`.

**Comment by kiennq** [comment]
> I tried to call `lsp-prefer-capf` on the same line where I call `push` manually in [this](https://github.com/emacs-lsp/lsp-mode/issues/1516#issuecomment-598979783) comment above: 3 lines after calling `(lsp)`

You need to set `lsp-prefer-capf` before that. Something like
``` elisp
(setq lsp-prefer-capf t)
(add-hook 'reason-mode-hook (lambda ()
                              (add-hook 'before-save-hook 'refmt-before-save)
                              (lsp)
                              (company-mode 1)
                              (lsp-treemacs-sync-mode 1)
                              (merlin-mode))
```

**Comment by yashrk** [comment]
> You need to set lsp-prefer-capf before that.

It works perfectly, thank you!
