### ISSUE TITLE
add vscode-rf-language-server support (help wanted)

### ISSUE THREAD

**Issue by dalanicolai** [emacs-lsp/lsp-mode#1518]
**Describe the bug**
Trying to register the  [vscode-rf-language-server](https://github.com/tomi/vscode-rf-language-server) to the list of lsp-clients but only receive empty responses from the server. (Help wanted)

**To Reproduce**
- Install [vscode-rf-language-server](https://github.com/tomi/vscode-rf-language-server) (probably easiest to install the extension called "robot framework intellisense", within vscode install package with Ctrl-shift-x).

- download the followong file, change the extension to .el and open the file in emacs:
[lsp-robot.txt](https://github.com/emacs-lsp/lsp-mode/files/4333281/lsp-robot.txt)
set/review the proper default values for the variables and enter the correct path to the server.js file (requires nodejs to run the server).
More info is found [here](https://github.com/tomi/vscode-rf-language-server/tree/master/client) and as there is no explanation how to use with other clients, maybe inspect the [rf-server-client.ts](https://github.com/tomi/vscode-rf-language-server/blob/master/client/src/rf-server-client.ts) file
Finally load/evaluate the code.

- optionally load the robot-mode.el file from [here](https://github.com/dougm/robot-mode)

- put the following two files in the same folder and change both their extensions to .robot
[Keywords.txt](https://github.com/emacs-lsp/lsp-mode/files/4333269/Keywords.txt)
[test.txt](https://github.com/emacs-lsp/lsp-mode/files/4333306/test.txt)

- now open the test.robot file with emacs and start the lsp server with M-x lsp

- check the output in the *lsp-log: rf-intellisense...* buffer in a separate buffer while scrolling through the test.robot file

- finally, optionally compare the output with the output from the rf-intellisense server in vscode
(to make the server work correctly with the two files add the folder containing the files as a workspace, see the following animation)

the following image shows the highlighting of symbols in vscode (in robot framework symbols are often full sentences)
![Screencast-from-03-14-2020-09_00_47-PM](https://user-images.githubusercontent.com/18429791/76689596-c6a29680-6637-11ea-9f78-10be6ef9a45d.gif)

the next animation shows output from the server 
![Screencast-from-03-14-2020-09_02_19-PM](https://user-images.githubusercontent.com/18429791/76689713-dff81280-6638-11ea-8e71-468a2b1e60fb.gif)
in vscode

and the next animation shows the output in (space)emacs (and no highlighting of the symbols, although I got it to work at some point but I after restarting emacs it did not work anymore and I could not get it to work again)
![Screencast-from-03-14-2020-09_02_48-PM](https://user-images.githubusercontent.com/18429791/76689752-66acef80-6639-11ea-8dbe-b90bf089c927.gif)

This last animation shows the go to definition feature in vscode
![Screencast-from-03-14-2020-09_21_21-PM](https://user-images.githubusercontent.com/18429791/76689805-07031400-663a-11ea-82a4-9c0921013940.gif)

Finally the output of the emacs lsp-log is in the following file
[lsp-log_emacs.txt](https://github.com/emacs-lsp/lsp-mode/files/4333307/lsp-log_emacs.txt)

**Expected behavior**
I was hoping to get the recognition of symbols (with the highlighting) and the goto defintion feature to work like in vscode

**Which Language Server did you use**
The link to the server is included above

**OS**
GNU/linux, fedora 31
with the spacemacs distribution emacs 26.3

**Error callstack**
If there is an error please reproduce the issue with `toggle-debug-on-error` and after setting `lsp-print-io` to t, and then include the callstack and attach the content of `*lsp-log*` buffer and the content of the server log(use `lsp-workspace-show-log`)

If `emacs` hangs plase do `M-x` `toggle-debug-on-quit` and then do `C-g` when emacs hangs and include the callstack as part of the issue report.

``` emacs-lisp
(setq lsp-print-io t)
```

**Comment by yyoncho** [comment]
I will take a look.

**Comment by yyoncho** [comment]
You got everything working except this:

```
(with-current-buffer "test.robot"
  (lsp-request "buildFromFiles" (list :files ["/home/kyoncho/Videos/robot/test.robot"
                                              "/home/kyoncho/Videos/robot/Keywords.robot"])))
```

Once the server has started vscode sends the list of files that are part of the project(or something like that, I am not familiar with robot). After you execute the method above, everything works as expected. I think that vscode uses the include/exclude regexes to gather which files to send to the server.

**Comment by dalanicolai** [comment]
Wow, it works great! You think you will add it to lsp-mode? Or should I document this on my blog? Even after your answer I could not find any information about lsp-request, except for the docstring of course (but maybe I should look even harder). Anyway really big thanks for your time, help and very quick reply.

**Comment by yyoncho** [comment]
> You think you will add it to lsp-mode? 

It will be great if you can provide a PR.

> Even after your answer I could not find any information about lsp-request, except for the docstring of course (but maybe I should look even harder). 

I did the following: started the robot plugin in vscode and enabled client-server communication. I saw that we send the same initial requests but it still does not work on our side. Then I inspected what vscode sending after initialization and I saw that request. `lsp-request` and `lsp-request-async` are part of our API.

**Comment by dalanicolai** [comment]
I am happy to make a PR of course, but I don't know how to implement this lsp-request. Also, I tried to just start the server, without any config and only followed by that lsp-request because I suspected that would have been sufficient to make it work, and indeed that way it worked already. So I do not know if any of the customization part of my code actually works so that I don't know if I should add that part. Additionally I don't know how I should take care of that lsp-request. Can I just put it after the `:library-folders-fn` keyword of the `make-lsp-client` function? Or should I add a hook somewhere? I am really new to emacs, and trying to learn all this, by just experimenting a lot, but it is a lot to learn of course and I often do not know exactly what I am doing, just trying things and hope to learn something from it. Anyway, if you have some suggestions I am really happy to contribute

**Comment by yyoncho** [comment]
> I am happy to make a PR of course, but I don't know how to implement this lsp-request. 

You should put the call in :initialized-fn (there are few examples in lsp-mode repo).

> Can I just put it after the :library-folders-fn keyword of the make-lsp-client function? Or should I add a hook somewhere? 

Can you elaborate?

Other than that check `client/src/extension.ts` in the robot repo. AFAICS you are supposed to do that "parse call" after the client has started and also we should have a call to manually trigger the same after the server has started(e. g. after you add new file). 

Also, if you have quick elisp/lsp-mode questions feel free to ask them in lsp-mode gitter chat.

**Comment by yyoncho** [comment]
We are done here.
