### ISSUE TITLE
How to turn off typescript lintings while preserving eslint lintings

### ISSUE THREAD

**Issue by uqix** [emacs-lsp/lsp-mode#1520]
After setting up typescript-language-server and vscode-eslint, typescript and eslint show the same errors.

![image](https://user-images.githubusercontent.com/10142314/76697846-2dc35800-66d7-11ea-9e85-2cfc6b6d5ac3.png)

**Comment by yyoncho** [comment]
ATM I think this is not possible, we should extend flycheck related code to allow that.

**Comment by mbriggs** [comment]
I'm looking for this too, was running tide with `tide-disable-suggestions`. How involved would it be to implement? If it isnt too nasty i could potentially help with a PR

**Comment by yyoncho** [comment]
@mbriggs we should track if this is exposed by typescript-language-server

**Comment by mbriggs** [comment]
@yyoncho as far as I can tell, thats not a thing. I checked tide, and that option seems to be ignoring output

https://github.com/ananthakumaran/tide/blob/10e5c19de798aba2d57fb1ec83ad3d1369e6547a/tide.el#L2154

**Comment by yyoncho** [comment]
@mbriggs I see - we could introduce a configurable filter for diagnostics so the user could use it to hide the diagnostics he/she does not want to see.

**Comment by mbriggs** [comment]
Poked around the codebase a bit. I am assuming a filter would happen in `lsp--on-diagnostics`. What I am less confident in is which of the structs the client should exist on.

**Comment by vikigenius** [comment]
@yyoncho I just stumbled onto this issue and I am experiencing the same in `.tsx` files. Doesn't help that the tutorial also suggests both these servers but provides no warning or workaround to avoid this issue: https://emacs-lsp.github.io/lsp-mode/tutorials/reactjs-tutorial/

Do you have any suggestions for this. I really like the completion provided by `ts-ls` but would like to keep the linting from eslint.

I tried `(setq lsp-typescript-validate-enable nil)` but that seems to have no effect. You have any ideas?

**Comment by yyoncho** [comment]
@vikigenius I will try to do a PR this weekend.

**Comment by yyoncho** [comment]
PR at #2596
