### ISSUE TITLE
Questioning dim gray as a choice for the unnecessary diagnostic tag

### ISSUE THREAD

**Issue by valignatev** [emacs-lsp/lsp-mode#1522]
Hi lsp!
Recently there was an update that added support for the diagnostic tag, and it's a great addition: #1050 

However, dim gray was chosen as an additional face attribute, and that's how it looks in warious themes:
Spacemacs light:
![image](https://user-images.githubusercontent.com/7038954/76767022-fa9dc900-67a9-11ea-8919-61ad36c6261b.png)

Spacemacs dark: 
![image](https://user-images.githubusercontent.com/7038954/76767107-25881d00-67aa-11ea-8775-bf60293af6d7.png)

Doom one light
![image](https://user-images.githubusercontent.com/7038954/76767155-3a64b080-67aa-11ea-8d94-6635e9b2dfb6.png)

Doom one dark:
![image](https://user-images.githubusercontent.com/7038954/76767243-56685200-67aa-11ea-8816-7ef537a2c837.png)

So while it looks just s little bit suboptimal for the dark themes (although still usable in some cases), it totally breaks all the light themes that I've tried.

Do we really need to change background for the variable under a warning since it'll be underlined (and maybe even have an indicator on the fringe) anyway?

We can customize the variable, sure, but do we have to force every light theme user to go through this?

**Comment by yyoncho** [comment]
I generally agree with you - what is your suggestion?

**Comment by valignatev** [comment]
As I've said - the variable will be underlined anyway because lsp-mode calculates the error level, so maybe don't do any background at all. Like provide customization like it is done now but don't set any default.

The perfect option IMO would to dim the variable itself somehow based on its initial color. In spacemacs-light case it would be slightly dimmer red, in doom-one-light slightly dimmed brown (yellow?) etc. Kinda like IntelliJ IDEs do it:

![image](https://user-images.githubusercontent.com/7038954/76771141-eeb50580-67af-11ea-9ddf-039fd786bbe2.png)

But I don't think that emacs has a way of doing that automatically. Spacemacs theme has some dim options for the faces (base-dim and highlight-dim) but I don't know how universal it is in Emacs world.

Btw what I'm saying applies to the unnecessary tag. Strikethrough as the default for deprecated things looks totally reasonable to me.

**Comment by yyoncho** [comment]
> Like provide customization like it is done now but don't set any default.

I don't like that because the majority of the user won't see that feature.

The dim option looks fine but it won't be possible to implement it since we have to pass static face to flycheck and we cannot calculate it based on the active face. 

Instead of changing the background colour, we may change foreground color, maybe this will be less disturbing? Also, if there is a common face from core we can use it's property. I was using the shadow face foreground in some of the first versions of the code but it still didn't look fine.

**Comment by valignatev** [comment]
Changing foreground would definitely be less disturbing, I agree.

**Comment by mullr** [comment]
If you want to keep the background, you could also add `:distant-foreground` to at least keep things readable. I'm just using `:underline "dim-grey"` locally, and it seems to be ok in a variety of situations.

**Comment by tspiteri** [comment]
I've hit this and can't even customize the face. If I go on the unreadable text and `M-x customize-face`, the default is `lsp-lsp-flycheck-warning-unnecessary-face`, and when I customize that to change the dark gray to something readable on a light theme, the text becomes readable. But then when I restart emacs the customization is ineffective, as that face is generated in `lsp--flycheck-level`. And the variable `lsp-diagnostics-attributes` itself is not customizable. In the end I had to add `(add-to-list 'lsp-diagnostics-attributes '(unnecessary :background "dark gray"))` after `(require 'lsp-mode)`.

**Comment by yyoncho** [comment]
Proposed fix at https://github.com/emacs-lsp/lsp-mode/pull/1610 . I decided not to use underline as suggested by @mullr since it is hiding the information whether this is an error or warning(this depends on the colour of the line).

**Comment by yyoncho** [comment]
Here it is how it looks like:

![Screenshot](https://user-images.githubusercontent.com/13259670/80271480-34c38a00-86c9-11ea-943b-3c2ccc351d92.png)
