### ISSUE TITLE
Support scaladoc auto completion on type `/**`

### ISSUE THREAD

**Issue by ashkan-leo** [emacs-lsp/lsp-mode#1525]
Scala metals added support for auto completion on type `/**`. The relevant PR can be found here: https://github.com/scalameta/metals/pull/1250

However, on Emacs this doesn't seem to work. It would be nice to add it.

**Comment by yyoncho** [comment]
cc @kurnevsky

**Comment by yyoncho** [comment]
@ashkan-leo as a side note, make sure that you are using company-capf.

**Comment by kurnevsky** [comment]
`lsp-mode` doesn't send `textDocument/completion` in this case for some reason...

**Comment by kiennq** [comment]
This seems due to the prefix is sent to `company` is nil, thus `company` deny to send completion request.
We can probably workaround by setting some `:company-prefix-length` in completion at point function

**Comment by yyoncho** [comment]
This code works in java but I have to call company-complete after typing `/** */`

**Comment by kiennq** [comment]
Also, we may need to enable completion in comment for metals, else the completion will not be trigger since it's inside comment
