### ISSUE TITLE
Hope lsp-mode can improve keybinding prefix names

### ISSUE THREAD

**Issue by stardiviner** [emacs-lsp/lsp-mode#1529]
![image](https://user-images.githubusercontent.com/378699/77133070-b279f180-6a9c-11ea-8988-fb2a924e9b92.png)

As you can see in the screenshot, [which-key](https://github.com/justbur/emacs-which-key) display lsp-mode keybindings prefix has no names. User is hard to recognize them. Define keybindings with meaningful names will be helpful. WDYT?

**Comment by kiennq** [comment]
Did you run `lsp-enable-which-key-integration`?
``` elisp
(use-package lsp-mode
  ;; set prefix for lsp-command-keymap (few alternatives - "C-l", "C-c l")
  :init (setq lsp-keymap-prefix "s-l")
  :hook (;; replace XXX-mode with concrete major-mode(e. g. python-mode)
         (XXX-mode . lsp)
         ;; if you want which-key integration
         (lsp-mode . lsp-enable-which-key-integration))
  :commands lsp)
```

**Comment by seagle0128** [comment]
I think you  didn't call `lsp-enable-which-key-integration`.

**Comment by stardiviner** [comment]
I have not noticed this function.
Now I added hook:
```
(add-hook 'lsp-mode-hook #'lsp-enable-which-key-integration)
```

Thanks @seagle0128
