### ISSUE TITLE
Can we add ("js-jsx-mode" . "javascriptreact") to language ID?

### ISSUE THREAD

**Issue by ianpan870102** [emacs-lsp/lsp-mode#1533]
Looking at the values of language ID config that concerns JavaScript, we have:

```emacs-lisp
 (".*\\.jsx$" . "javascriptreact")
 (rjsx-mode . "javascript")
 (js2-mode . "javascript")
 (js-mode . "javascript")
```

However, in the front-end development industry nowadays, it's a common practice to name our files XXX.js and "still use JSX syntax" within the files. For that reason, can we please include either of the 2 language ID configs below? The reason that I use js-jsx-mode is that it provides better indentation for React.js projects than pure js-mode.

```emacs-lisp
("js-jsx-mode" . "javascriptreact")
("js-jsx-mode" . "javascript")
```

**Comment by ianpan870102** [comment]
I have tried the following in my config:
```emacs-lisp
  (add-to-list 'lsp-language-id-configuration '("js-jsx-mode" . "javascript"))
```
However, lsp-mode still gives me the warning when I load a XXX.js file with js-jsx-mode: 
```
Warning (lsp-mode): Unable to calculate the languageId for current buffer. Take a look at lsp-language-id-configuration.
```

**Comment by yyoncho** [comment]
"js-jsx-mode"  -> 'js-jsx-mode

**Comment by ianpan870102** [comment]
Just tried it:
```emacs-lisp
  (add-to-list 'lsp-language-id-configuration '('js-jsx-mode . "javascript"))
```
Warning still exists -- Do I have another typo?

**Comment by ianpan870102** [comment]
Fixed it:
```
(add-to-list 'lsp-language-id-configuration '(js-jsx-mode . "javascript"))
```
