### ISSUE TITLE
annoying doc popup in separate buffer, cannot turn off

### ISSUE THREAD

**Issue by aentity** [emacs-lsp/lsp-mode#1535]
Occasionally, usually _after_ code completion, extremely annoying docs appear in a split buffer below (along with lsp-ui docs on side). The amount of docs showed can be quite large and takes up half of editing buffer sometimes.

![bad_doc](https://user-images.githubusercontent.com/55963758/77368918-91263900-6d1a-11ea-97a3-2022054ab39f.png)

This breaks code editing flow, is unrequested, and I cannot discover how to turn off.

I use lsp-ui; turning off every feature of lsp-ui still has these docs pop up in bottom buffer. So I think its unrelated.

Please at very least, help me to turn this off, makes for me lsp-mode not usable.

Here is my .emacs for lsp, i have `lsp-ui` and `helm` installed, not much else.:

```emacs-lisp
(require 'lsp-mode)

(setq lsp-prefer-capf t)

(require 'rust-mode)
(setq lsp-rust-server 'rust-analyzer)
(add-hook 'rust-mode-hook #'lsp-deferred)
```

**Describe the bug**
Unrequested documentation is shown in buffer below, and I cannot discover how to turn off.

**To Reproduce**
code complete; inside of a closure, for example in rust.

**Expected behavior**
Only show lsp-ui docs, or no docs at all unless I request. Optionally allow me to turn this off somehow.

**Which Language Server did you use**
rust-analyzer

**OS**
macos/linux

**Comment by kiennq** [comment]
That is method signature. You can make it not showing by either:
- Set `lsp-signature-auto-activate` to `nil`. That will make the signature not showing up by default. You can still request the signature manually.
- Set `lsp-signature-render-document` to `nil`. That will make the signature documentation not showing up.

Given your case, I think you may want to set `lsp-siganture-render-document` to `nil`

**Comment by yyoncho** [comment]
Also, the toggles are under `<s-l> T`.

**Comment by aentity** [comment]
wow thank you all so much, `lsp-signature-auto-activate` off is what i need! Might i suggest to you turn off by default? It has very unintuitive behavior and is disruptive for default, in my opinion.

Anyway, thank you!

**Comment by hniksic** [comment]
I stumbled upon this issue and would like to ask the devs to reconsider turning the feature off by default, or at least limiting the size of the window to max 3-4 lines. As pointed out by the submitter, it is quite disruptive and hurts usability of Emacs compared to both normal Emacs editing experience and that of other IDEs.

**Comment by ericdallo** [comment]
This could help: https://emacs-lsp.github.io/lsp-mode/tutorials/how-to-turn-off/

**Comment by yyoncho** [comment]
FTR at some point we will switch to UI IDE-like popup which will be less intrusive than what we currently have. see https://github.com/emacs-lsp/lsp-mode/pull/1999

**Comment by hniksic** [comment]
@ericdallo Thanks for the link. Do note, however, that I am aware how to disable the the feature, which is also explained in the preceding comments. I just found it sufficiently disconcerting (the description even calls it _annoying_, with which I must concur) that I wanted to ask the developers to reconsider it being the default behavior. The description of this issue does say "cannot turn off", but I felt it might be better to leave a comment here than to open a whole new issue for something that was already discussed.

@yyoncho That looks like a welcome change, thanks for the comment. Is it something that will be usable soon? I might like to test the functionality myself, as I definitely want IDE-like features, just not at the cost of usability that the current implementation incurs.
