### ISSUE TITLE
How to use lsp-mode in existing docker container?

### ISSUE THREAD

**Issue by FirstLoveLife** [emacs-lsp/lsp-mode#1537]
Say that I have a running docker, which has some cpp files in it. I can use [docker.el](https://github.com/Silex/docker.el) to open files in docker. I hope to use ccls for those cpp files:
```
(after! lsp-mode
  (lsp-register-client
   (make-lsp-client :new-connection (lsp-tramp-connection "/projects/github/ccls/Release/ccls")
                    :major-modes '(c++-mode)
                    :remote? t
                    :server-id 'ccls-docker))
  (lsp-register-client
   (make-lsp-client :new-connection (lsp-tramp-connection "/projects/github/ccls/Release/ccls")
                    :major-modes '(c-mode)
                    :remote? t
                    :server-id 'ccls-docker))
  )
```

And I also have ccls built in docker's path: 
```
root@7be0e470c9ea:/projects/github/ccls/Release# ls /projects/github/ccls/Release/ccls
```

But lsp-log tells me `Command "/projects/github/ccls/Release/ccls" is not present on the path.`. Where goes wrong?

**Comment by yyoncho** [comment]
lsp-mode uses `(executable-find <binary> t)` to check if the binary is present. You may try to execute it when you are in the tramp buffer.

**Comment by FirstLoveLife** [comment]
Thanks for reply. I tried execute it in tramp buffer and `(executable-find "/projects/github/ccls/Release/ccls" t)` returns nil. So does it mean it doesn't look for path under inside docker? If so, how to let it know `/projects/github/ccls/Release/ccls` is the docker container's path?

**Comment by yyoncho** [comment]
I don't know which part is failing, you may try to debug the method. What you can try is  to symlink ccls in /usr/bin on the remote machine and have the remote server set to "ccls".

**Comment by FirstLoveLife** [comment]
> have the remote server set to "ccls".

You mean `:server-id 'ccls-docker`? BTW, what `:new-connection (lsp-tramp-connection ...")` should be set now?

**Comment by yyoncho** [comment]
Set the tramp connection to "ccls" and put symlink in `/usr/bin`. The :server-id does not play a role. But I suggest you to debug the executable-find function to see where it breaks.

**Comment by yyoncho** [comment]
@FirstLoveLife is there anything more that you need here?
