### ISSUE TITLE
Latex texlab

### ISSUE THREAD

**Issue by sodalom** [emacs-lsp/lsp-mode#1538]
Texlab server starts fine in emacs lsp-mode but no completions. Executing company-diag shows it is running company-lsp but completions: none. Tried disabling company-lsp and using company-capf but falls back to company-dabrev. Btw, texlab server works fine with VSCode so the problem seems to be in lsp-mode interface.

Emacs version 28.0.50 x-64-mingw32 on Windows 10.

**Comment by yyoncho** [comment]
Please provide the information as per debug template (especially the logs).

**Comment by sodalom** [comment]
Running lsp-workspace-show-log gives this response, didn't copy the whole log but this section stood out for me.

[Trace - 06:11:07 pm] Sending response 'workspace/configuration - (0)'. Processing request took 0ms
Params: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": [
    null
  ]
}

**Comment by sodalom** [comment]
no issue with lsp-mode, lsp-start-plain.el works fine with texlab.
