### ISSUE TITLE
Evil's "jump to tag" keybind causes "not part of any project" menu to disappear

### ISSUE THREAD

**Issue by WhiteExponent** [emacs-lsp/lsp-mode#1539]
I am using `lsp-mode` and `evil`. When I use <kbd>C-]</kbd> which is bound to `evil-jump-to-tag` on an identifier in another package, `lsp-mode` asks for whether to import the project root with a menu. However, this menu disappears as soon as it appears when I use the key combination and I have to choose without seeing the menu. If I run `M-x evil-jump-to-tag`, this doesn't happen and the menu shows up normally. Similarly, if I run `M-x xref-find-definitions` which `evil-jump-to-tag` uses, the menu appears normally without disappearing.

`lsp-mode` version: 20200321.1659 (from Melpa)
`evil` version: 20200304.1421

**Comment by yyoncho** [comment]
This is how emacs works - if you have menu in minibuffer and some other process uses the minibuffer the menu is hidden. Probably there is a function that can restore the content but I am not aware of such.

**Comment by yyoncho** [comment]
Closing based on the previous comment, please reopen if you disagree.
