### ISSUE TITLE
lsp-fsharp using old version of FsAutoComplete

### ISSUE THREAD

**Issue by mpardalos** [emacs-lsp/lsp-mode#1543]
I believe lsp-fsharp is downloading an old version of fsac. If I run `lsp-fsharp-update-fsac` and then run  `dotnet fsautocomplete.dll` in the directory where it was downloaded it gives:
```
FsAutoComplete 0.38.2 (git sha 7db211bec017e54fdd4a0e10ead2de6760dcaab5)
```
Where the latest version that should be available is 0.41.1.

Deleting and re-running `lsp-install-server` also gives the same result.

This is causing #1508 to occur even though the bug causing it was fixed in fsac.

We are currently downloading fsac from the following appveyor link:

https://ci.appveyor.com/api/projects/fsautocomplete/fsautocomplete/artifacts/bin/pkgs/fsautocomplete.netcore.zip?branch=master

According to [fsautocomplete's README](https://github.com/fsharp/FsAutoComplete), they are currently using Azure pipelines for their CI. Does this mean we are using an old download link?

The latest downloads are available on their [github releases](https://github.com/fsharp/FsAutoComplete/releases). Maybe we should be downloading it from there?

**Comment by yyoncho** [comment]
> The latest downloads are available on their [github releases](https://github.com/fsharp/FsAutoComplete/releases). Maybe we should be downloading it from there?

I suggest checking where vscode download it from.

**Comment by mpardalos** [comment]
ionide/ionide-vscode-fsharp seems to build fsac master at build time: 

https://github.com/ionide/ionide-vscode-fsharp/blob/9f2aa197bcadcfa665be959bbf50c1fd3bc605bd/build.fsx#L33.

**Comment by mpardalos** [comment]
I was looking to see if there's a way to get the latest github release. It turns out there is no stable link, however they do have an API endpoint for getting a list of releases where we can get the link to the last release. You can get the link with this jq expression:

```
curl https://api.github.com/repos/fsharp/fsautocomplete/releases/latest \
| jq '.assets | .[] | select(.name == "fsautocomplete.netcore.zip") | .browser_download_url'
```

I am not sure if it's easy to integrate this into the current `lsp-install-server`. Do we have to provide a direct link to the download or can we directly provide a download function?

If that's possible I could submit a PR to get the zip from there.

**Comment by razzmatazz** [comment]
I was hit by this issue too.

@mpardalos: actually `lsp-csharp` does this same thing by quering via github API and retrieves the latest version of the server. Which is what we probably want to do here as well?
 - https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-csharp.el#L71
 - https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-csharp.el#L110
 - https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-csharp.el#L123

**Comment by mpardalos** [comment]
This seems to be exactly what we need! Should we try to reuse that code somehow or should it just be copied to lsp-fsharp? I guess the functionality could go into lsp-mode.el somehow?

**Comment by razzmatazz** [comment]
> This seems to be exactly what we need! Should we try to reuse that code somehow or should it just be copied to lsp-fsharp? I guess the functionality could go into lsp-mode.el somehow?

Hold on, I think I will have PR in a couple of mins, the code already works for me.

**Comment by razzmatazz** [comment]
I have made a PR to make lsp-fsharp query github api and download the latest server from github, the same way lsp-csharp does.

**Comment by razzmatazz** [comment]
> This seems to be exactly what we need! Should we try to reuse that code somehow or should it just be copied to lsp-fsharp? I guess the functionality could go into lsp-mode.el somehow?

I guess @yyoncho can decide what common things can be extracted off lsp-csharp and lsp-fsharp now.

**Comment by yyoncho** [comment]
> I guess @yyoncho can decide what common things can be extracted off lsp-csharp and lsp-fsharp now.

Let's keep it as it is for now.
