### ISSUE TITLE
angular-ls is not starting if the angular project is on sub folder

### ISSUE THREAD

**Issue by zer09** [emacs-lsp/lsp-mode#1545]
**Describe the bug**
angular-ls is not starting when the angular project is part of non angular mono-repo.

**To Reproduce**
1. Create a new non angular project and initialize the local git repo.
2. Create a new sub folder, and initial the angular app there.
3. Open the project and open the app.component.html
4. Check the session using `M-x lsp-describe-session`, only the `html-ls` is started, the `angular-ls` is missing.

**Expected behavior**
`angular-ls` and `html-ls` should be running.

**Which Language Server did you use**
For angular:  ` @angular/language-service@next typescript  @angular/language-server` this was installed.
`vscode-html-languageserver-bin` is also installed.

**OS**
Pop!_OS 19.10

**Comment by seungmu** [comment]
I have same issue here.
How did you fix this issue?

**Comment by yyoncho** [comment]
@seungmu paste the content of \*lsp-log\*

**Comment by seungmu** [comment]
> @seungmu paste the content of *lsp-log*

Never mind, It's due to wrong workspace path. I set  subfolder of angular project as workspace as long as angular project folder.
