### ISSUE TITLE
[Discuss] Performance improvements

### ISSUE THREAD

**Issue by seagle0128** [emacs-lsp/lsp-mode#1549]
cc @yyoncho 

In recent discussion in the forum, someone told me he did some researches and made a prototype, and found disabling real-time docs (while typing) could improve the performance significantly, since it saved lots of communications between server and client. He has already leveraged `eglot` to prove that. I'm wondering what's the situation in `lsp-mode`. If it's not implemented, can we make it in `lsp-mode`?

Refer to https://github.com/manateelazycat/nox.

**Comment by yyoncho** [comment]
We inhibit error reporting/highlighting/lenses/links/etc via `lsp-inhibit-lsp-hooks` while the completion is active. The eldoc uses separate hook and it is not inhibited but there is `eldoc-idle-delay` which should suppress the eldoc documentation unless you are typing very slowly. So, having this mechanism we achieve good performance while you are performing completion and at the same time, we provide all Language Server features. So while typing we should be as fast as nox.

In general, before doing any optimizations I would like to see performance report/benchmarks.

**Comment by Alexander-Miller** [comment]
How about some micro optimizations? I've just recently discovered some interesting options in the cl-lib package. This line:

```Èlisp
(cl-declaim (optimize (speed 3) (safety 0)))
```
Will disable runtime type-checking for your cl-structs. That does result in a considerable speedup, at least as far as direct comparisons are concerned. Given this code:
```Elisp
(require 'cl-lib)
(cl-declaim (optimize (speed 3) (safety 0)))
(cl-defstruct box value)
```
and this benchmark:
```Elisp
(setf testbox (make-box :value 123))
(benchmark-run-compiled 1000000
  (box-value testbox))
```
the runtime on my system changes between ~200ms and ~930ms, depending on whether the test file was compiled with the declaimer or without.

**Comment by yyoncho** [comment]
@Alexander-Miller this is interesting, I guess this is going to result in some speed up. Related to that in 2fc61a9bc5001a1d3526fff4f020ae7ee1fb872b I removed the access to the structures in favour of using captures to hold the state in the critical sections of the code.

**Comment by Alexander-Miller** [comment]
Declaim difference is quite small, the closure version is still faster. 
`(0.002553091999999999 0 0.0)`  vs
`(0.014881542 0 0.0)`

**Comment by Alexander-Miller** [comment]
Wait, I did it wrong, I declaimed lsp-mode, but not the benchmark struct. Result is actually
`(0.006471027 0 0.0)`
Much closer, though the closure is still faster.

**Comment by Alexander-Miller** [comment]
Aaaand I got it down to `(0.00051556 0 0.0)`.

If you compile and load this:
```Elisp
(require 'cl-lib)
(cl-declaim (optimize (speed 3) (safety 0)))
(cl-defstruct my/struct counter)

(define-inline test-counter-inc (self)
  (inline-letevals (self)
    (inline-quote
     (setf (my/struct-counter ,self) (1+ (my/struct-counter ,self))))))
```

And benchmark like this:
```Elisp
(setf testcounter (make-my/struct :counter 0))
(benchmark-run-compiled 10000 (test-counter-inc testcounter))
```
the struct will in fact be faster. Which is really not surprising since we've whittled the code down to 1) read array 2) inc 3) write array and thanks to the define inline there isn't any funcall overhead.

**Comment by yyoncho** [comment]
> define inline

The purpose of the benchmark is to compare the lsp-mode use case for the process filter function thus you cannot inline it...

**Comment by Alexander-Miller** [comment]
Using defun instead I still get `(0.0005643610000000002 0 0.0)`.

I don't think I understand the use-case well enough to judge what it means for this particular case, but I think the benchmarks do show that this whole inlining & declaiming thing is worthwhile in general.

**Comment by yyoncho** [comment]
Here it is the benchmark with real data: https://github.com/emacs-lsp/lsp-mode/blob/master/test/lsp-benchmarks.el 

Here it is how the actual code looks like:

```
(defun lsp--create-filter-function (workspace)
  "Make filter for the workspace."
  (let ((body-received 0)
        leftovers body-length body chunk)
    (lambda (_proc input)
      (setf chunk (concat leftovers (with-no-warnings (string-as-unibyte input))))
      ... processing
      )))
```

The question here is where to keep the state(leftovers, body-lenght, chunk) - in struct or in variables and how much faster is the access to variable(get/set) compared to access to struct.

**Comment by Alexander-Miller** [comment]
As process filter using a closure is the best option, a struct would only make sense if you wanted to pass it around.

>  (setf chunk (concat leftovers (with-no-warnings (string-as-unibyte input))))

I think this part looks interesting. Have you tried inserting the input into a buffer instead of concatenating? It's how I do it in pfuture, though I cannot remember whether performance was the reason for making that change.

**Comment by yyoncho** [comment]
> I think this part looks interesting. Have you tried inserting the input into a buffer instead of concatenating?

I have implemented a version which uses buffers for concatenation and it was slower. The most efficient way to concatenate strings I found is using concat but calling it only once, e. g. instead of inserting the parts in the buffer it is better to collect them in list and then call concat once - this is what I do few lines bellow.

**Comment by yyoncho** [comment]
After this bug report, we got several speed improvements so I think that it should be ok to be closed. If you disagree please reopen after going through https://emacs-lsp.github.io/lsp-mode/page/performance/ .
