### ISSUE TITLE
can clangd support argument --compile-commands-dir 

### ISSUE THREAD

**Issue by Jackson-soft** [emacs-lsp/lsp-mode#1552]
Please ask your questions at https://gitter.im/emacs-lsp/lsp-mode

`clangd --help`

`--compile-commands-dir=<string> - Specify a path to look for compile_commands.json. If path is invalid, clangd will look in the current directory and parent paths of each source file`

**Comment by kiennq** [comment]
You can set `lsp-clients-clangd-args` to desired command flags

**Comment by Hi-Angel** [comment]
For completeness: given a project with a build directory `build/` and a generated file `build/compile_commands.json`, to make clangd use it execute:

```
(add-to-list 'lsp-clients-clangd-args "--compile-commands-dir=./build")
```

Yeah, a path relative to the project root works. You may want to add it to `.dir-locals.el` of the project.

Gotchas:
* the `lsp-clients-clangd-args` is unfortunately a global variable, not specific to a project. So if you have two different projects open using clangd server, they both will search for the json file in `./build` dir.
* just bear in mind in case you build the project in a Podman/Docker container that resulting `compile_commands.json` will have full paths that may mismatch the ones on your host.
