### ISSUE TITLE
How does one use tsserver plugins?

### ISSUE THREAD

**Issue by JacksonGariety** [emacs-lsp/lsp-mode#1553]
I found [this wiki page](https://github.com/emacs-lsp/lsp-mode/wiki/Using-Plugins-In-Typescript-Language-Server), installed intellicode, and set the relevant variable. How do I now make use of the plugin with, e.g., `company-mode`?

**Comment by yyoncho** [comment]
It should work out of the box - the server uses intellicode and lsp-mode calls the server and passes it to company-mode.

**Comment by JacksonGariety** [comment]
Wow this is amazing. :+1:
