### ISSUE TITLE
[lsp-clangd] Strange completion after right angle bracket

### ISSUE THREAD

**Issue by condy0919** [emacs-lsp/lsp-mode#1555]
**My Config**
```elisp
(use-package company
  :ensure t
  :hook (prog-mode . company-mode)
  :custom
  (company-idle-delay 0)
  (company-echo-delay 0)
  (company-show-numbers t)
  (company-require-match nil)
  (company-minimum-prefix-length 3)
  (company-tooltip-align-annotations t)
  (company-backends '(company-capf)))

(use-package lsp-mode
  :ensure t
  :hook (prog-mode . lsp-deferred)
  :custom
  (lsp-keymap-prefix "C-c l")
  (lsp-enable-indentation nil)
  (lsp-enable-on-type-formatting nil)
  (lsp-auto-guess-root t)
  (lsp-prefer-capf t)              
  (lsp-keep-workspace-alive nil)
  (lsp-eldoc-enable-hover nil)
  (lsp-signature-auto-activate nil))
```

**Describe the bug**
Code completion after a single `>` character.

![image](https://user-images.githubusercontent.com/4024656/78218438-5b3e3d00-74f0-11ea-99f1-522652a48438.png)

**To Reproduce**
Open a `a.cpp` with the following content:

```cpp
int main() {
    
}
```

type `>` in the `main` function.

A single `:` meets the same issue.

![image](https://user-images.githubusercontent.com/4024656/78219078-6f366e80-74f1-11ea-83ae-c983036271ad.png)

**Expected behavior**

No completion.

**Which Language Server did you use**

`lsp-clangd`

# Background

It has been discussed in 

- https://github.com/MaskRay/ccls/issues/144
- https://github.com/joaotavora/eglot/issues/173

**Comment by kiennq** [comment]
I will take a look at this

**Comment by condy0919** [comment]
![image](https://user-images.githubusercontent.com/4024656/79337717-9d3b9a00-7f58-11ea-85ed-073da02ccf18.png)

It seems not fixed after three dots (variadic template and `sizeof...` operator)
