### ISSUE TITLE
Rust analyzer: out-of-date initialization options

### ISSUE THREAD

**Issue by hghwng** [emacs-lsp/lsp-mode#1559]
**Describe the bug**
`lsp-rust-analyzer--make-init-options` in [lsp-rust.el](https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-rust.el#L399) does not match [rust-analyzer's config parser](https://github.com/rust-analyzer/rust-analyzer/blob/47a48505a54a08939ef7958243bf8d87aa045bd4/crates/rust-analyzer/src/config.rs#L113).

See also: [VSC's config keys](https://github.com/rust-analyzer/rust-analyzer/blob/09b8ee30bab7040ec983968aaca90814029f4dc0/editors/code/package.json)

**To Reproduce**
For example, set `lsp-rust-all-targets` to `t`, and functions in `cfg(test)` won't get diagnostics.

**Expected behavior**
Unit tests get diagnostics.

**Which Language Server did you use**
lsp-rust

**OS**
Arch Linux; emacs 26.3-1; Spacemacs 1d797ffa4a57ec9b4f46f0cfd22652141c2559d1; lsp-mode 20200315.

**Comment by brotzeit** [comment]
Thanks for the bug report! Do you want to open a pull request ?

**Comment by brotzeit** [comment]
@hghwng Test #1568 please.

**Comment by hghwng** [comment]
@brotzeit It works! The lsp-log buffer (with `lsp-log-io`) also agrees with me.

(And ... sorry for the late reply :-( － I could have opened a pull request)

**Comment by brotzeit** [comment]
No problem. You can always open pull requests to improve stuff.
