### ISSUE TITLE
[Dart] Feature request: new variables for initialization options

### ISSUE THREAD

**Issue by jpprime** [emacs-lsp/lsp-mode#1560]
I would really love to see variables to control the new three initialization option on the analysis server. Specifically you can now toggle closingLabels, outline and flutterOutline on or off. More information on these options can be found [here](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool/lsp_spec/README.md).

**Comment by ericdallo** [comment]
@jpprime, [this](https://github.com/emacs-lsp/lsp-mode/pull/1561) add the variables, but Im not sure if lsp has the support for these features currently.

**Comment by ericdallo** [comment]
Currently `lsp-mode` has support only for the `closingLabels` feature. I added support on the PR :point_up:

**Comment by jpprime** [comment]
The `closingLabels` is actually the feature I was mostly missing, since the `outline` and `flutterOutline` features are available in the DevTools, although it would be really nice if I could not use Chromium just for that and have it available on Emacs. Is it possible to add the outline features? I am willing to help.

**Comment by ericdallo** [comment]
I don't know how to implement these features as `lsp-treemacs` currently does not has this support like said it here.
@yyoncho, do you have any idea if we can implement these features in any way?

**Comment by yyoncho** [comment]
> I don't know how to implement these features as `lsp-treemacs` currently does not has this support like said it here.
> @yyoncho, do you have any idea if we can implement these features in any way?

Yes, we can - we have created multiple tree views in lsp-treemacs/lsp-java/dap-mode/ccls/. You may take a look at `lsp-treemacs-call-hierarchy`. Feel free to ping me if you need more clarification.

**Comment by jpprime** [comment]
I guess this should be closed and maybe moved to `lsp-treemacs` then, since the option that could be implemented on the main `lsp-mode` has been implemented thanks to @ericdallo.

**Comment by ericdallo** [comment]
@jpprime we are thinking on implement those temporary on lsp-mode then move to a separated `lsp-dart` repository.
The PR is here: https://github.com/emacs-lsp/lsp-mode/pull/1573

**Comment by ericdallo** [comment]
I think we can close this given the above merged PR @yyoncho

**Comment by yyoncho** [comment]
Yes, thanks.
