### ISSUE TITLE
Use lsp in cperl-mode (enhanced perl-mode)

### ISSUE THREAD

**Issue by ianpan870102** [emacs-lsp/lsp-mode#1569]
I've installed the Perl language server and it connects fine when I'm in a perl-mode buffer.
However, I prefer to use cperl-mode, and would like lsp to treat a cperl-mode buffer as a perl-mode one.
So far I've tried these two lines:
```emacs-lisp
  (add-to-list 'lsp-language-id-configuration '(cperl-mode . "perl"))
  (add-to-list 'lsp-language-id-configuration '(".*\\.pl$" . "perl"))
```
But lsp-mode still throws the following error:
```
There are no language servers supporting current mode cperl-mode registered with 'lsp-mode'.
```
If I describe variable `lsp-language-id-configuration`, it looks like so:
```
((".*\\.pl$" . "perl")
 (cperl-mode . "perl")
 (".*\\.vue$" . "vue")
 (".*\\.tsx$" . "typescriptreact")
 (".*\\.ts$" . "typescript")
 (".*\\.jsx$" . "javascriptreact")
 (".*\\.xml$" . "xml")
...
...
...
```
Any help would be appreciated!

**Comment by yyoncho** [comment]
You should change it here: https://github.com/emacs-lsp/lsp-mode/blob/360a1ace15254b4ed99f16eec47bad03b5967c90/lsp-perl.el#L59

**Comment by ianpan870102** [comment]
After changing that line to `:major-modes '(cperl-mode)` the server connects automatically. For some reason, the status keeps getting stuck at 'starting' and never finishes. But it could just be that my computer is slow.

So is there no way to put something in my config that can enable my wanted behaviour of cperl-mode + lsp, or is changing that line in `.emacs.d/elpa/lsp-perl.el` the only way?

**Comment by yyoncho** [comment]
Fixed thanks to @kubo39 .
