### ISSUE TITLE
Allow other packages to register new client capabilities

### ISSUE THREAD

**Issue by tigersoldier** [emacs-lsp/lsp-mode#157]
As of tigersoldier/company-lsp#5, company-lsp is planning to support expanding completion snippets. A proper way to support it is to set `TextDocumentClientCapabilities.completion.completionItem.snippetSupport` to be true on initialization, or allow company-lsp to dynamically register it.

However, we shouldn't just set snippetSupport to true unconditionally. lsp-mode itself doesn't support post-completion actions, so cannot support snippet expansion. It should only be turn on when company-lsp is in use.

That said, lsp-mode needs to provide an API to allow other packages to register and unregister client capabilities that is not supported by the core. Ideally it should extend the initial client capability if possible, because not all language servers support dynamic registration.

**Comment by bkchr** [comment]
@vibhavp This ticket can be closed :)

**Comment by vibhavp** [comment]
yup, thanks.
