### ISSUE TITLE
eslint working directory and plugin resolution

### ISSUE THREAD

**Issue by vikigenius** [emacs-lsp/lsp-mode#1572]
Given a multi project directory structure like this

```
project_root/
  python_proj/
  js_proj/
    node_modules
    ....
```

lsp determines the project root to be project_root and runs eslint from there.
However, this won't find any of the plugins because it expects node_modules to be in $CWD/node_modules. https://eslint.org/docs/user-guide/configuring#how-personal-configuration-file-behaves.

A workaround is https://eslint.org/docs/user-guide/command-line-interface#--resolve-plugins-relative-to

But I don't know how to use that with lsp-eslint, VSCode apparently allows this configuration:

```
  "eslint.workingDirectories": [
    {
      "changeProcessCWD": true,
      "directory": "./js_proj"
    }
  ],
```

I see that there is a variable `lsp-eslint-working-directories`, but I don't know how to set it?

Any help would be appreciated.

**EDIT:**

As a workaround is there anyway I can easily control which folder gets set as the project root from where the server starts. Maybe I can set it up in a .dir-locals.el inside the js-proj folder.

**Comment by komali2** [comment]
Having this issue as well, and as someone that uses LSP through Emacs, I also can't set variables through vscode settings.

**Comment by nbfalcon** [comment]
If you run `M-x lsp`, you will be prompted to select a workspace root (only needs to be done once). Also, VSCode settings are mapped to `Emacs` `defcustom`s, so you can set them in .dir-locals like any others. They will be loaded before the server starts.
