### ISSUE TITLE
Add an lsp-version command?

### ISSUE THREAD

**Issue by Ekleog** [emacs-lsp/lsp-mode#1574]
The bug report template says to check one isusing the latest version of `lsp-mode`, yet as far as I can find there is no `lsp-version` command that allows to actually check that. (maybe I'll have other bugs to provide sometime later, but it's most likely a PEBKAC, so… let's see :) but lsp is already pretty impressive, even though I'm not yet able to reproduce all that's on GIFs!)

**Comment by kiennq** [comment]
You can find the version from `list-packages`.
I'm using `helm` so normally I use `package-delete` then filter to package I want to see the version and copy its number.

**Comment by Ekleog** [comment]
Oh right :) I was used to `org-mode` and `org-version`. I guess this should be closed, then, though feel free to reopen if you feel like an `lsp-version` (or explanation of how to find the version in the issue template for emacs newbies like me) is required.

Thank you!
