### ISSUE TITLE
gopls panics because file paths are not properly converted to URIs

### ISSUE THREAD

**Issue by codesuki** [emacs-lsp/lsp-mode#1590]
lsp-mode uses the the function url-hexify-string to convert a path to an URI.
Following down the rabbit hole you find this line
;; Allow % to avoid re-encoding %-encoded sequences.
https://github.com/emacs-mirror/emacs/blob/master/lisp/url/url-util.el#L415

The following PR would solve the issue I think, but it breaks with emacs < 26.x
https://github.com/emacs-lsp/lsp-mode/pull/1089

This PR to gopls that broke it.
https://github.com/golang/tools/commit/f8e42dc47720b31a0fedf0b422ee4cbd171ab163

**Comment by yyoncho** [comment]
> The following PR would solve the issue I think, but it breaks with emacs < 26.x
> #1089

We can make that conditional.

**Comment by yyoncho** [comment]
Can you include sample url which will break lsp-mode?

**Comment by codesuki** [comment]
I don't have the log anymore but Bazel creates paths like `/var/.../architecture%/test_main.go`. Then gopls panicks with `%/t` is not a valid URI escape.
