### ISSUE TITLE
lsp-enable-which-key-integration does not work with vue-mode

### ISSUE THREAD

**Issue by bimbiltu** [emacs-lsp/lsp-mode#1598]
**Describe the bug**
vue-mode uses mmm-mode to activate different major modes depending on where your cursor is. This causes issues with `lsp-enable-which-key-integration` since that function sets which-key descriptions only for the activated major mode.

Is there any downside to changing [this line](https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el#L2371) to use `which-key-add-key-based-replacements` instead? I tried this change locally and my which-key descriptions worked as expected.

**To Reproduce**
This can be seen by pressing the lsp keymap prefix when the cursor is in a spot where the major mode is not vue-mode

I made a small example project in this branch: https://github.com/bimbiltu/lsp-playground/tree/vue-which-key-prefixes-not-named

Note that I set the lsp-keymap-prefix to "C-c l" in this branch. If you move the cursor
outside of the <script> block, where the major mode is vue-mode, which-key looks like this:
```
= → +formatting F → +folders G → +peek T → +toggle a → +code actions g → +goto h → +help r → +refactor s → +sessions
```

and if you move the cursor inside the <script> block, where the major mode is js-mode, which-key looks like this:
```
= → +prefix F → +prefix G → +prefix T → +prefix a → +prefix g → +prefix h → +prefix r → +prefix s → +prefix`
```

**Expected behavior**
It would be nice to call `lsp-enable-which-key-integration` and have it work over the entire .vue file

**Which Language Server did you use**
lsp-vetur

**Comment by yyoncho** [comment]
I am not a which-key expert but based on the docs you will still have the which-key bindings even for the modes in which lsp-mode is not enabled? 

The alternative fix would be to change lsp-enable-which-key-integration to accept major-mode as param so you could manually invoke it for the modes you are interested in? We do that workaround for flycheck as well (see FAQ section). 

If you think that the suggestion from above is not enough, I am fine with your suggestion but this behaviour should be enabled explicitly with current behaviour as default.

**Comment by bimbiltu** [comment]
I figured given [the examples in the readme](https://github.com/emacs-lsp/lsp-mode#which-key-integration) that people will generally only call this function when lsp-mode is enabled, although I suppose theres no real guarantee people are following those examples

**Comment by yyoncho** [comment]
> I figured given [the examples in the readme](https://github.com/emacs-lsp/lsp-mode#which-key-integration) that people will generally only call this function when lsp-mode is enabled, although I suppose theres no real guarantee people are following those examples

Once we allow calling lsp-enable-which-key-integration with major mode is allowed we will document it there and in the FAQ.

**Comment by bimbiltu** [comment]
I think I like the idea of adding a param to `lsp-enable-which-key-integration` that makes it enable which-key integration for all major modes more. While vue-mode does make all possible major modes available as part of the `vue-modes` variable it would be a bit easier for people to be able to enable which-key integration for all modes. I'd also be happy to submit a PR for either of the solutions mentioned here

**Comment by yyoncho** [comment]
I am for the option with the param. The other thing won't work for frameworks like spacemacs which have multiple different layers and the global which key prefixes will mess that up.
