### ISSUE TITLE
Support unbound progress reports

### ISSUE THREAD

**Issue by robertoaloi** [emacs-lsp/lsp-mode#1599]
In #1586 support for progress reports has been introduced, but they only work with percentages.

It looks like you can invoke the progress reporter by setting min-value and max-value to nil to get a rotating spinner. That would be useful for cases where the total time is not known in advance (e.g. when running tests via a code lens). This is actually part of the protocol itself, where the percentage value in the `begin` message is optional and should be used exactly for this purpose. So I suggest that, if the `begin` message does not contain a percentage, we fall back to `nil` both for the `min-value` (instead of `0` and for the `max-value` (instead of `100`).

https://www.gnu.org/software/emacs/manual/html_node/elisp/Progress.html

**Comment by robertoaloi** [comment]
Also, it would be nice to add a space between the message coming from the server and the percentage / done message.

Current:

`Indexing dependencies...67%`

Nicer:

`Indexing dependencies... 67%`

**Comment by alanz** [comment]
In that case we pass the string "Indexing dependencies" as the title, the dots and number are added by the `progress-reporter`. So I guess an issue needs to be filed elsewhere for that.

**Comment by robertoaloi** [comment]
@alanz I see, thanks for checking.
