### ISSUE TITLE
LSP language ID may differ across files in the same workspace

### ISSUE THREAD

**Issue by anmonteiro** [emacs-lsp/lsp-mode#160]
the `ocaml-language-server` applies different heuristics (e.g. on text document formatting) according to whether the current file is ReasonML (`.re` / `.rei`) or OCaml (`.ml` / `.mli`).

However, the language ID in `emacs-lsp` is static (when `lsp-define-stdio-client` is called).

I'd like to see a per-file Language ID, because a single workspace can share both ReasonML and OCaml files. I think the VSCode client has this capability.

**Comment by vibhavp** [comment]
Can you review this branch and see whether it suits your purpose? https://github.com/emacs-lsp/lsp-mode/tree/language-id-function

**Comment by anmonteiro** [comment]
@vibhavp that branch seems to work except I had to pass `:langauge-id-fn` instead of `:language-id-fn` (there seems to be a typo in the source)

**Comment by vibhavp** [comment]
Fixed and pushed in c15863fddc8f5e389bd1c2712b2352a9bc3970c3. Thanks.

**Comment by anmonteiro** [comment]
Thanks, fixed downstream in https://github.com/emacs-lsp/lsp-ocaml/commit/690b95dd6ed293e307e984e9d0e8cff02f85f8c3
