### ISSUE TITLE
calling lsp-organize-imports on before-save-hook leaves file unsaved

### ISSUE THREAD

**Issue by aconchillo** [emacs-lsp/lsp-mode#1604]
**Describe the bug**

When adding `lsp-organize-import` to `before-save-hook` imports are organized but file is kept unsaved. Actually, you can see it's saved for a short time and then becomes unsaved without any additional modifications.

**To Reproduce**

```
(require 'lsp-java)

(defun my-java-mode-hook ()
  (setq c-basic-offset 4)
  (add-hook 'before-save-hook 'lsp-organize-imports))

(add-hook 'java-mode-hook 'my-java-mode-hook)
(add-hook 'java-mode-hook #'lsp)
```

Edit any Java file with imports, move them around and save.

I also tried using `lsp-java-organize-imports` and it has the same effect.

**Expected behavior**

Imports are organized and file is saved just once and is kept saved.

**Which Language Server did you use**

lsp-java

**OS**

macOS Catalina 10.15.3

Emacs 26.3 (from brew) using terminal.

**Comment by aconchillo** [comment]
This only happens if there are any actual imports to reorganize. If imports are correct, file is saved properly and stays saved.

**Comment by yyoncho** [comment]
Hm, it is really something tricky, I tried with a different function that modifies the buffer and the issue does not reproduce...

**Comment by aconchillo** [comment]
Could you reproduce with java imports?

**Comment by yyoncho** [comment]
Yes - I found out what is the reason - lsp-organize-imports is async when used with jdt ls. I will provide a solution for you.

**Comment by yyoncho** [comment]
Use (setq lsp-java-save-actions-organize-imports t) + 9f5c847

**Comment by aconchillo** [comment]
Works great! Thank you!

**Comment by yyoncho** [comment]
Your welcome and thank you for the support!

**Comment by zoechi** [comment]
Would this cause similar issues in other languages like Dart, Rust, ...
