### ISSUE TITLE
Missing Package-Requires for s.el

### ISSUE THREAD

**Issue by laurynas-biveinis** [emacs-lsp/lsp-mode#1605]
**Describe the bug**

lsp-mode package has a direct dependency on s >= 20171201 (or thereabouts) now

**To Reproduce**

Install s.el from melpa-stable, 1.12.0. Then install the latest lsp-mode, which uses s-replace-regexp, which is not available in s.el 1.12.0.

**Expected behavior**
s.el should be upgraded on lsp-mode installation? Not sure how Emacs package dependency hell is supposed to work in this case. Nevertheless, s should be added to Package-Requires?

**Comment by yyoncho** [comment]
If we add the dependency it still won't work when you install the packages from melpa stable. The solution is to ask `s` maintainers to tag a new release.

**Comment by laurynas-biveinis** [comment]
Trying that at https://github.com/magnars/s.el/issues/135
