### ISSUE TITLE
Spacemacs develop branch lsp-mode does not work for Dart / Flutter

### ISSUE THREAD

**Issue by MrMic** [emacs-lsp/lsp-mode#1606]
**Describe the bug**
Works perfectly fine last week but since the last update this weekend 18 April, 
Cannot launch LSP with my dart files for developing with Flutter
- The command: flutter doctor est OK and Flutter is up to date.

**To Reproduce**
Open a dart file in a flutter project that should trigger LSP-mode for dart and
got:

LSP :: There are no language servers supporting current mode dart-mode registered with `lsp-mode'.

**Expected behavior**
Should trigger the LSP-mode for Dart

**Which Language Server did you use**
Dart / Flutter

**OS**
Mac OSX

Thanks for the reply and help.
Can you fix it quickly?

All works fine last week and the weeks before, but not after the last update of 
Emacs . I am on the develop branch as the title says ...

Rgds,

**Comment by yyoncho** [comment]
Adding lsp-dart to your additional packages would fix the issue. Fixing the rootcause must happen in spacemacs's dart layer.

**Comment by MrMic** [comment]
Thank you for the quick reply.
Works fine again.
Thank you very much!  I was stuck ...

I close.

Rgds,

**Comment by yyoncho** [comment]
sse https://github.com/syl20bnr/spacemacs/pull/13518
