### ISSUE TITLE
Cannot get Company completions to work in LaTeX mode with LSP

### ISSUE THREAD

**Issue by swarnendubiswas** [emacs-lsp/lsp-mode#1611]
Before logging the bug, please make sure that:

1. You are using the latest version of `lsp-mode` related packages. Yes
2. You may also try reproduce the issue using clean environment using the following command:
3. Check FAQ and Troubleshooting section (https://github.com/emacs-lsp/lsp-mode#faq and https://github.com/emacs-lsp/lsp-mode#troubleshooting)
``` bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` could be downloaded from `https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el`.

I tried this, but the bug (or a mistake in my setup) exists.

**Describe the bug**

I am trying to customize LaTeX-specific backends for `company` to work with `LSP`. My problem is I cannot seem to get all the desired backends to work well together. For example, `company-capf` seems to give me completions for `\ref{sec:*}` and BIB entries, but then `company-dabbrev` or `company-ispell` is not completing English words. Is it not possible to get them both to work together? Thanks.

I posted this on [Company webpage](https://github.com/company-mode/company-mode/issues/976), and Dmitry suggests the problem might lie with LSP.

**To Reproduce**

I have TexLab v2.0 installed for use with LSP, with Emacs version 28.0.50 on Ubuntu 19.10.

```
(eval-when-compile
  (require 'package)
  (setq package-user-dir (expand-file-name (concat user-emacs-directory "elpa"))
        ;; Avoid loading packages twice
        package-enable-at-startup nil)
  (package-initialize)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t))

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-when-compile
  (require 'use-package))

(use-package company
  :ensure t
  :hook (after-init . global-company-mode)
  :custom (company-dabbrev-downcase nil) ; Do not downcase returned candidates
  :bind (:map company-active-map
              ("C-n" . company-select-next)
              ("C-p" . company-select-previous)))

(use-package company-math
  :ensure t
  :ensure math-symbol-lists
  :demand t)

(use-package company-bibtex
  :ensure t
  :demand t)

(use-package company-reftex
  :ensure t
  :demand t)

(dolist (hook '(text-mode-hook markdown-mode-hook))
  (add-hook hook
            (lambda ()
              (make-local-variable 'company-backends)
              (setq-local company-backends '(company-capf
                                             company-dabbrev
                                             company-abbrev
                                             company-ispell)))))
(dolist (tex-hooks '(latex-mode-hook LaTeX-mode-hook plain-tex-mode-hook))
  (add-hook tex-hooks
            (lambda ()
              (set (make-local-variable 'company-backends) '(company-capf
                                                             company-ispell
                                                             company-dabbrev
                                                             company-bibtex
                                                             company-reftex-labels
                                                             company-reftex-citations
                                                             company-math-symbols-latex
                                                             company-latex-commands
                                                             company-math-symbols-Unicode
                                                             company-abbrev)))))

(use-package lsp-mode
  :ensure t
  :hook ((latex-mode plain-tex-mode) . lsp-deferred)
  :custom (lsp-prefer-capf t))
```

Here is a simple LaTeX document. 
```
\documentclass[12pt,a4paper]{article}
\usepackage{lipsum}
\begin{document}
\title{Company Test}
\author{Swarnendu Biswas}
\date{}
\maketitle

\section*{Introduction}
\label{sec:intro}
\lipsum

\section*{Methodology}
This is a long paragraph about nothing that makes sense. I do not understand what is going wrong.

\section*{Conclusion}
\label{sec:conc}

The shutdown on cricket in England and Wales will remain until at least 1 July, meaning the postponement of England's Test series against West Indies.

No domestic competitions have been cancelled yet, but the England and Wales Cricket Board (ECB) will meet on Wednesday to discuss the inaugural season of The Hundred, which is due to start on 17 July.

The domestic season, scheduled to start on 12 April, had been delayed until at least 28 May because of coronavirus.

The ECB says it will look to schedule all international cricket between July and the end of September.

England women's limited-overs series against India - scheduled to start on 25 June - has also been postponed.

ECB chief executive Tom Harrison said: "As much as we remain hopeful that we can deliver some cricket this summer, we are in the midst of a worldwide crisis and our priority - over and above the playing of professional sport - will be to protect the vulnerable, key workers and society as a whole.
\end{document}
```

**Expected behavior**
I expect both LSP completions like \cite{}, \ref{}, and completions for regular English words to work. For my setup, I do not get word completions for regular English words. 

**Which Language Server did you use**
Texlab v2

**OS**
Ubuntu 19.10

**Comment by kiennq** [comment]
Can you also post the *lsp-log*?
https://github.com/emacs-lsp/lsp-mode#troubleshooting
Just toggle the `lsp-toggle-trace-io` before you type and toggle it off after that.
And paste the log here

**Comment by swarnendubiswas** [comment]
```
Command "digestif" is present on the path.
Command "texlab" is present on the path.
Command "digestif" is present on the path.
Command "texlab" is present on the path.
Found the following clients for /home/swarnendu/Desktop/document.tex: (server-id digestif, priority -1), (server-id texlab, priority 1)
The following clients were selected based on priority: (server-id texlab, priority 1)
Cancelling textDocument/documentLink(27) in hook after-change-functions
Cancelling textDocument/documentLink(26) in hook after-change-functions
Cancelling textDocument/hover(25) in hook after-change-functions
Cancelling textDocument/documentLink(24) in hook after-change-functions
Cancelling textDocument/documentLink(23) in hook after-change-functions
Cancelling textDocument/documentLink(30) in hook after-change-functions
Cancelling textDocument/documentLink(29) in hook after-change-functions
Cancelling textDocument/documentLink(37) in hook after-change-functions
Cancelling textDocument/documentLink(42) in hook after-change-functions
Cancelling textDocument/documentLink(41) in hook after-change-functions
Cancelling textDocument/documentLink(40) in hook after-change-functions
Cancelling textDocument/documentLink(39) in hook after-change-functions
Cancelling textDocument/hover(38) in hook after-change-functions
Cancelling textDocument/documentLink(69) in hook after-change-functions
Cancelling textDocument/documentLink(68) in hook after-change-functions
Cancelling textDocument/documentLink(67) in hook after-change-functions
Cancelling textDocument/documentLink(66) in hook after-change-functions
Cancelling textDocument/documentLink(65) in hook after-change-functions
Cancelling textDocument/documentLink(64) in hook after-change-functions
Cancelling textDocument/documentLink(63) in hook after-change-functions
Cancelling textDocument/documentLink(62) in hook after-change-functions
Cancelling textDocument/documentLink(61) in hook after-change-functions
Cancelling textDocument/documentLink(60) in hook after-change-functions
Cancelling textDocument/documentLink(59) in hook after-change-functions
Cancelling textDocument/documentLink(58) in hook after-change-functions
Cancelling textDocument/documentLink(57) in hook after-change-functions
Cancelling textDocument/documentLink(56) in hook after-change-functions
Cancelling textDocument/documentLink(55) in hook after-change-functions
Cancelling textDocument/documentLink(99) in hook after-change-functions
Cancelling textDocument/documentLink(98) in hook after-change-functions
Cancelling textDocument/hover(97) in hook after-change-functions
```

**Comment by kiennq** [comment]
These too:
> - set `lsp-log-io` to t to inspect communication between client and the server. Use `lsp-workspace-show-log` to switch to the corresponding log buffer.
> - `lsp-describe-session` will show the current projects roots + the started severs and allows inspecting the server capabilities.

**Comment by swarnendubiswas** [comment]
[lsp-texlab.log](https://github.com/emacs-lsp/lsp-mode/files/4532666/lsp-texlab.log)
[lsp-log.log](https://github.com/emacs-lsp/lsp-mode/files/4532667/lsp-log.log)
[lsp-describe-session.log](https://github.com/emacs-lsp/lsp-mode/files/4532668/lsp-describe-session.log)

**Comment by kiennq** [comment]
If this is what you want:
> My problem is I cannot seem to get all the desired backends to work well together. For example, company-capf seems to give me completions for \ref{sec:*} and BIB entries, but then company-dabbrev or company-ispell is not completing English words. Is it not possible to get them both to work together? Thanks

You can probably customize `company-backends` to include `(company-capf :with company-ispell company-dabbrev :separate)`.
This allows multi backends for company.
@dgutov for confirmation.

However, you need to do some tweak so `lsp-auto-configure` doesn't mess with your `company-backends`. @yyoncho can help.

Btw, here is how I configure my `lsp-mode` so `lsp-auto-configure` doesn't mess with my company backends:
``` elisp
(use-package lsp-mode
  :ensure t
  :defer t
  :hook (lsp-managed-mode . (lambda ()
                              (lsp--flymake-setup)
                              (flymake-start t)
                              (let ((lsp-keymap-prefix "SPC l"))
                                (lsp-enable-which-key-integration))
                              (lsp-diagnostics-modeline-mode 1)))
  :init
  (setq lsp-keep-workspace-alive nil
        lsp-signature-doc-lines 5
        lsp-idle-delay 1
        lsp-prefer-capf t)
  :config
  (advice-add #'lsp--auto-configure :override #'ignore)
```

**Comment by yyoncho** [comment]
> However, you need to do some tweak so `lsp-auto-configure` doesn't mess with your `company-backends`. @yyoncho can help.

I think that we should introduce value of lsp-prefer-capf - :none which means do not touch backends similar to what we do for flycheck/flymake. But as a side note the backends could be ovewritten in lsp-managed-mode-hook.

**Comment by dgutov** [comment]
Ideally, though, the completion function should return nil when it's on plain English text instead of LaTeX instructions. I wonder how hard that would be to implement.

**Comment by kiennq** [comment]
> Ideally, though, the completion function should return nil when it's on plain English text instead of LaTeX instructions. I wonder how hard that would be to implement.

Do you want to implement new behavior for `company-mode`? Right now from `company-backends` document, I have impression of `company-mode` will just check backends' `prefix` to see if it should use that backend or not.
Since latex language server has space as it trigger character, every new word will trigger completion and pass the `prefix` check.

**Comment by swarnendubiswas** [comment]
@kiennq I tried your suggestions. 
```
(eval-when-compile
  (require 'package)
  (setq package-user-dir (expand-file-name (concat user-emacs-directory "elpa"))
        package-enable-at-startup nil)
  (package-initialize)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t))

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-when-compile
  (require 'use-package))

(use-package company
  :ensure t
  :init (global-company-mode 1))

(dolist (hook '(latex-mode-hook LaTeX-mode-hook plain-tex-mode-hook))
  (add-hook 'hook
            (lambda ()
              (set (make-local-variable 'company-backends) '((company-capf
                                                              :with company-ispell
                                                              company-dabbrev :separate)
                                                             )))))

(use-package lsp-mode
  :ensure t
  :hook ((latex-mode plain-tex-mode) . lsp-deferred)
  :custom
  (lsp-prefer-capf t)
  (lsp-log-io t)
  :config (advice-add #'lsp--auto-configure :override #'ignore))
```

I can see completions if I manually invoke `M-x company-dabbrev` or `M-x company-ispell`, however they do not autostart (which is what I expect). LaTeX completions like `\ref{}` continue to work fine.

**Comment by kiennq** [comment]
Can you check value of `company-backends` in your latex buffer?
As I can see, this `add-hook 'hook` should be `add-hook hook` (without quote).

**Comment by swarnendubiswas** [comment]
Thanks @kiennq. I get both types of completions for the example. 

Can this be improved?

![Screenshot from 2020-04-26 12-06-29](https://user-images.githubusercontent.com/7343807/80300079-205dbb00-87b7-11ea-9524-815a120d3c35.png)

I get similar problems with `\cite{}`.

**Comment by dgutov** [comment]
@kiennq 

> Do you want to implement new behavior for company-mode?

I don't see how.

> Right now from company-backends document, I have impression of company-mode will just check backends' prefix to see if it should use that backend or not.

Indeed. What else could it do?

> Since latex language server has space as it trigger character, every new word will trigger completion and pass the prefix check.

If LSP provides no way to distinguish, that is unfortunate. Maybe it could provide spelling suggestions itself.

Failing that, I guess @swarnendubiswas could bind `company-other-backend` to a key and use it in such situations.

**Comment by yyoncho** [comment]
@kiennq is there anything more here?

**Comment by dgutov** [comment]
> Also I notice it can pass stop as prefix of company backend, what will company-mode will do in that case?

It will stop. :-) To pass control to the next backend, return `nil`.

> Something like if completion-at-point-function return some special value for prefix via :company-prefix-length that will wait to see if there's any completion from capf before passing it to other backends?

I think there's an existing property for that: `:exclusive`. I'll look into supporting it, but not tomorrow or next week. You can file an issue to track it better.

**Comment by kiennq** [comment]
Thanks, opened new issue

**Comment by yyoncho** [comment]
Seems like there is nothing to do on lsp-mode side, please reopen if you disagree.
