### ISSUE TITLE
Source ~/.profile ?

### ISSUE THREAD

**Issue by Shooooooooo** [emacs-lsp/lsp-mode#1617]
Hi, maybe this question has been asked somewhere else but I could not find it.
I am experimenting ccls + lsp + tramp.
On the remote machine, because I don't have sudo privilege, all the tools like ccls or libclang are installed in my home directory. And the `PATH` and `LD_LIBRARY_PATH` are set in my ~/.profile.
I could launch emacs on the remote machine and have ccls working.
But, I couldn't launch emacs on my local machine and connect to remote language server.
It was complaining ccls couldn't be found, so I assuming ~/.profile was not being sourced.
Is there anyway to launch a login shell so that ~/.profile being sourced before looking for language server? Thanks!

**Comment by yyoncho** [comment]
You may register the tramp configuration with full path to the server. I am not that familiar with tramp to answer your original question.

**Comment by yyoncho** [comment]
Marking as closed but you may use it for further questions.
