### ISSUE TITLE
Cannot use on Emacs 26 if package installed in Emacs 27

### ISSUE THREAD

**Issue by tspiteri** [emacs-lsp/lsp-mode#1626]
I alternate between Emacs 26 and 27 on my machine. If I install the lsp-mode package inside Emacs 27, it works fine. But then when I try to use lsp-mode in Emacs 26, I get an error about void `json-serialize`.  

The macro `lsp--json-serialize` contains a condition to check whether `json-serialize` is a bound function, but this condition is checked during compile time, so when byte compilation takes place in Emacs 27, this condition will always evaluate to true, and the macro is expanded during compilation into the `json-serialize` branch. Then in Emacs 26 I get an error that the void function `json-serialize` is used.

There is also another macro `lsp--read-json` which has the same fault.

**Comment by yyoncho** [comment]
You should not expect that something bytecompiled with a newer version of emacs will work on older version of emacs and lsp-mode is not the only package that performs compile-time optimizations for the specific emacs version and also the elc is not forward compatible. I would suggest you use different package directories. You could achieve that by setting `package-user-dir` based on your current emacs version.

**Comment by tspiteri** [comment]
I kinda had that suspicion but wanted to make sure. Thanks!
