### ISSUE TITLE
Flycheck not always executed due to lsp

### ISSUE THREAD

**Issue by damienrg** [emacs-lsp/lsp-mode#1629]
If a user activates `lsp-flycheck-live-reporting` and uses a language server that does not support diagnostics, `flycheck` will not be executed.

The issue is in the following code (comment from me) :

```lisp
(defun lsp-flycheck-enable (&rest _)
  "Enable flycheck integration for the current buffer."
  (flycheck-mode 1)
  (when lsp-flycheck-live-reporting
    (setq-local flycheck-check-syntax-automatically nil)) ;; this prevent flycheck to run automatically
  (setq-local flycheck-checker 'lsp)
  (lsp-flycheck-add-mode major-mode)
  (add-to-list 'flycheck-checkers 'lsp)
  (add-hook 'lsp-after-diagnostics-hook #'lsp--flycheck-report nil t)) ;; if the server does not support diagnostics lsp--flycheck-report will never be called
```

Steps to reproduce:
  1. Create a bash script with:

```bash
#!/usr/bin/env bash

foo="test bar"
echo $foo
```
  2. ensure you have installed `bash-language-server` and that you have configured set `(flycheck-add-next-checker 'lsp 'sh-shellcheck)`
  3. open the script and start `lsp`
  4. modify the script (comment/uncomment lines) and see that you have to call `flycheck-buffer` explicitly to update lints

**Comment by yyoncho** [comment]
We should reorganize `lsp` -> `flycheck` integration. Here it is what I think that we should do:

1. Remove `lsp-flycheck-live-reporting` and keep original `flycheck-check-syntax-automatically`
2. Do not call `flycheck-buffer` each time the diagnostics are received but only mark them as dirty. Clear that flag when diagnostics are published.
3. If `flycheck-check-syntax-automatically` has `idle-change` make sure the diagnostics are published at some point even if the diagnostics have been received after `idle-change` has been triggered.

This will yield better performance and it will make `lsp` checker easier to integrate with the rest of the flycheck ecosystem.

**Comment by damienrg** [comment]
If `lsp` relies on `flycheck-check-syntax-automatically` (ie we only do 1.), I would say that diagnostics will be published automatically.

But based on your comment and since I am not familiar with `lsp` nor `flycheck`internals, it seems a bit more complicated.

For now, this is how I understand the code:
- `lsp` save diagnostics via `textDocument/publishDiagnostics` from server
- `flycheck` is run automatically on some events and it calls `lsp--flycheck-start`
- `lsp--flycheck-start` transforms saved diagnostics to `flycheck` info/warning/error

**Comment by yyoncho** [comment]
Flyckeck might run before LSP has received the diagnostics that's why we cannot reply solely on flyckeck.

**Comment by noctuid** [comment]
It would also be nice if there was some way to let flycheck act as normal even for servers that give diagnostics. Or maybe there is already some way to do this? For example, I want to use microsoft's python language server but just want to use standard python linters instead of their linting. Right now, flycheck warnings/errors do not update live.

**Comment by yyoncho** [comment]
@noctuid the workaround, for now, is setting lsp-flycheck-live-reporting to nil which kind of works but sometimes you have to save the file to have to get the latest diagnostics.
