### ISSUE TITLE
Deleted directories in session wrongly detected as root for files

### ISSUE THREAD

**Issue by tspiteri** [emacs-lsp/lsp-mode#1630]
If I have a directory /tmp/a in the session and then delete the directory, opening a file /tmp/a.rs will cause an error `File mode specification error: (file-missing Setting current directory No such file or directory /tmp/a)`.

This is because /tmp/a is still in the lsp session. Then `(lsp-find-session-folder (lsp-session) "/tmp/a.rs")` returns `"/tmp/a"`. Creating a new directory /tmp/a would make this go away. I think that `lsp-find-session-folder` should check `(f-dir? it)` before checking `(f-ancestor-of? it file-name-canonical)`.

**Comment by yyoncho** [comment]
Alternatively, we may wrap the call lsp-session-folders call and check if the root directory exists each time the function is called and delete those that are not present.  WDYT?

**Comment by tspiteri** [comment]
That does seem like a better solution, fixing the cause rather than the symptom. But I think we need to be mindful of consequences. For example if someone normally works on a network drive and the network is temporarily down, would all the directories on that drive be deleted?

**Comment by yyoncho** [comment]
Yeah - this will be problematic. Also, checking if directory exists everywhere may cause perf issues. I guess your initial suggestion is acceptable, willing to provide a PR?
