### ISSUE TITLE
lsp-eslint-auto-fix-on-save implemented?

### ISSUE THREAD

**Issue by jkdufair** [emacs-lsp/lsp-mode#1634]
I have

`(setq lsp-eslint-auto-fix-on-save t)`

and it appears to have no effect. Looking at the source, perhaps this is not implemented yet? If not, I can attempt a PR.

**Comment by yyoncho** [comment]
definitely something that is not implemented, PR would be great. Feel free to ask questions here or in gitter chat(generally, the first step is to find out what vscode does).

**Comment by jkdufair** [comment]
Since we already have `lsp-eslint-apply-all-fixes` would it be sufficient to simply run that when we save? I've just added it as a `before-save-hook` in my Emacs startup for the time being and it works perfectly. Or is it more involved than that?

**Comment by yyoncho** [comment]
It depends on what you are looking for: if you just want to apply the fixes - I think we are good with that solution. We are looking for feature parity with vscode - in this case, vscode might be doing more.

**Comment by leungbk** [comment]
The `eslint` server supports the `source.fixAll` code action, so this should be the same issue as https://github.com/emacs-lsp/lsp-mode/issues/1842.

**Comment by yyoncho** [comment]
Closing as duplicate of #1842
