### ISSUE TITLE
lsp-mode 6.3: which package provide the functions `s-replace-regexp'?

### ISSUE THREAD

**Issue by netjune** [emacs-lsp/lsp-mode#1636]
I upgrade lsp-mode from 6.2.1 to 6.3. And there is an error message like this:
```
Company: backend company-capf error "Symbol’s function definition is void: s-replace-regexp" with args (post-completion App_name)
```

I can't find s-replace-regexp in latest s.el.

Then I installed lsp-mode with emacs package manager. And `s-replace-regexp` is still not defined.

**Comment by yyoncho** [comment]
There is this: https://github.com/magnars/s.el/issues/135 . If it is not fixed by the EOD I will remove the usage of that function and tag 6.3.1.

**Comment by netjune** [comment]
I have upgraded s.el to its master branch. 
Thanks for the new version.
