### ISSUE TITLE
Rust autocomplete gives very long information

### ISSUE THREAD

**Issue by haoyuan80s** [emacs-lsp/lsp-mode#1639]
Here is an example. It shows the full path where the keywords are defined.
![image](https://user-images.githubusercontent.com/9064146/80872592-a8d0d580-8c67-11ea-9da3-565983f2c84f.png)
Any config to make the information more concise?

**Comment by yyoncho** [comment]
company-tooltip-maximum-width  ?

**Comment by haoyuan80s** [comment]
Yes, it is also my current approach. I just wonder whether there are some better ways to config it. I saw some autocomplete like the picture below from https://github.com/emacs-lsp/lsp-mode/issues/1269#issuecomment-590295023.
![image](https://user-images.githubusercontent.com/9064146/80891807-53062880-8c7b-11ea-9479-95140e1decd0.png)

**Comment by yyoncho** [comment]
We may add an option to skip the details, @kiennq willing to take that?

**Comment by haoyuan80s** [comment]
I solved it by adding this line: `(setq rustic-lsp-server 'rust-analyzer)`. Now the company looks better:
![image](https://user-images.githubusercontent.com/9064146/80894280-77b7cb80-8c8e-11ea-8972-7de279b1d78e.png)

**Comment by kiennq** [comment]
> We may add an option to skip the details, @kiennq willing to take that?

Sure let me add an option for that
