### ISSUE TITLE
Is there a way to never go to a declaration when requesting a definition?

### ISSUE THREAD

**Issue by johndebord** [emacs-lsp/lsp-mode#1648]
Sometimes when I call `lsp-find-definition` I get brought to the declaration.
This goes on until the the information of where the definition has been obtained (from background processing/indexing I'm assuming).

So, I'm wondering if there is a way to prevent this behavior and only have `lsp-find-definition` to bring me to the definition and NEVER to the declaration.

**Comment by yyoncho** [comment]
There is no such setting on protocol level(declaration/definition separation are pretty much language specific). You may ask the question in the server repo if they support this configuration.
