### ISSUE TITLE
Can't fuzzy match for more than 2 characters

### ISSUE THREAD

**Issue by abbaswasim** [emacs-lsp/lsp-mode#1652]
```
Before logging the bug, please make sure that:
1. You are using the latest version of `lsp-mode` related packages.
```
Yes, lsp version from melpa `20200504.643` is that correct version? I looked this up via `package-list-packages`.

```
2. You may also try reproduce the issue using clean environment using the following command:
emacs -q -l lsp-start-plain.el
```
I tried this and the issue is still there. Although one caveat the completions when I use `lsp-start-plain.el` are coming from `company-clang` and I use `company-capf` as recommended by the documentation. So it's might not be representative of the real issue.

```
3. Check FAQ and Troubleshooting section (https://github.com/emacs-lsp/lsp-mode#faq and https://github.com/emacs-lsp/lsp-mode#troubleshooting)
```
Nothing in FAQ related to this.

```
Alternatively, in will be great if you can reproduce the issue using [lsp-docker](https://github.com/emacs-lsp/lsp-docker/)  which provides the minimal configurations for `lsp-mode` and ships with most of the language servers.
```
I looked into this but since the docker uses `ccls` for C++ it doesn't apply. I use `clangd` and `company-capf` backend so I thought it won't reproduce my environment so I didn't try it. Still happy to try it but I think it's irrelevant.

```
3. Consider providing a minimal project to reproduce the issue with. 
```
[lsp-company-mode-test.zip](https://github.com/emacs-lsp/lsp-mode/files/4574348/lsp-company-mode-test.zip) is the project, build using `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .`

```
company-backends '(company-capf)
company-version  0.9.12
completion-at-point-functions == (lsp-completion-at-point)
emacs-version = GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.5.0, Carbon Version 158 AppKit 1671.4) of 2019-08-29)
``` 

**Describe the bug**
Only 2 characters can be used to complete potential candidates. More details https://github.com/company-mode/company-mode/issues/979 the folks over there saying its an lsp-issue.

More details with a gif.
![](https://user-images.githubusercontent.com/5260991/80928715-43333500-8d9e-11ea-95f1-06bd0f744f8b.gif)

**To Reproduce**
Open the `main.cpp` make sure `clangd` server is used with `company-capf` as the `company-backend`.

Type `VA` at line 15. You will see its completed to many options including the ones in the current file. `VertexAttribute` and `VertexAttributeSimpleSemantic`. If you type `VAS` however it's not completing to `VertexAttributeSimpleSemantic`. However if you type `VS` it's completed to `VertexAttributeSimpleSemantic`. This tell me the fuzzy matches are only working for at most 2 characters? While I would expect all of `VA` or `VAS` or `VASS` should all complete to `VertexAttributeSimpleSemantic`

**Expected behavior**
Typing `VAS` or `VASS` should find `VertexAttributeSimpleSemantic` as completion candidate.

**Which Language Server did you use**
I am using `clangd` with `company-capf` as the only completion backend. `clandg` is called like `clangd -j=8 -background-index -log=verbose`

**OS**
MacOs Catalina 10.15.4

**Error callstack**
No errors produced while trying to complete.

**Comment by kiennq** [comment]
Can you follow https://github.com/emacs-lsp/lsp-mode#troubleshooting and provide the buffer in `lsp-workspace-show-log`?

When I try it with my environment, it works fine and does show the expected candidates with `VASS`.
We don't filter `clangd` completion candidates since it's requesting that. So whatever showing is directly returned from `clangd`.
With the log, we can investigate more.

Also, just in case, can you try to set `(setq-default completion-ignore-case t)` to see if the candidate is showing up?

**Comment by abbaswasim** [comment]
*lsp-log* output:

```
Command "clangd -j=8 -background-index -log=verbose" is present on the path.
Command "clangd -j=8 -background-index -log=verbose" is present on the path.
Found the following clients for /development/temp/lsp-company-test/main.cpp: (server-id clangd, priority -1)
The following clients were selected based on priority: (server-id clangd, priority -1)
Command "clangd -j=8 -background-index -log=verbose" is present on the path.
Command "clangd -j=8 -background-index -log=verbose" is present on the path.
Found the following clients for /System/Volumes/Data/development/temp/lsp-company-mode-test/main.cpp: (server-id clangd, priority -1)
The following clients were selected based on priority: (server-id clangd, priority -1)
Command "clangd -j=8 -background-index -log=verbose" is present on the path.
Command "clangd -j=8 -background-index -log=verbose" is present on the path.
Found the following clients for /System/Volumes/Data/development/temp/lsp-company-mode-test/main.cpp: (server-id clangd, priority -1)
The following clients were selected based on priority: (server-id clangd, priority -1)
```

Have tried this `(setq-default completion-ignore-case t)`it doesn't help. Although VSS gives some other random suggestion because its not anymore but it's not the suggestion I am looking for.

And `lap-workspace-show-log` quite verbose but here you go.

[lap-workspace-show-log.txt](https://github.com/emacs-lsp/lsp-mode/files/4575346/lap-workspace-show-log.txt)

**Comment by abbaswasim** [comment]
> (setq lsp-completion-styles '(helm-flex))

This solution works. Both for `VASS` and something like `VerASS` which is cool.

![Uploading Screenshot 2020-05-04 at 16.08.18.png…]()

In this case however it has a slight issue. You can't complete common bits of `VertexAttribute` anymore because Fuzzy match is choosing `_Attribute` and it means there are no "common" bits anymore.

**Comment by kiennq** [comment]
> In this case however it has a slight issue. You can't complete common bits of `VertexAttribute` anymore because Fuzzy match is choosing `_Attribute` and it means there are no "common" bits anymore.

I think just type a few more chars will narrow down to a single candidate, which is much faster than complete common bits?

**Comment by yyoncho** [comment]
> In this case however it has a slight issue.

This is not an issue but the expected behaviour.

**Comment by abbaswasim** [comment]
> I think just type a few more chars will narrow down to a single candidate, which is much faster than complete common bits?

**Comment by kiennq** [comment]
> In this case it's not. It keeps going until the end with the two candidates;
> 
> 'VertexAttributeSimpleSemantic' vs 'Vertex_Attribute_Simple_Semantic'

Type `_` to help it differentiate?

**Comment by abbaswasim** [comment]
> Type _ to help it differentiate?

**Comment by kiennq** [comment]
In that case, I think you can bind <kbd>tab<kbd> to `company-complete-common-or-cycle`, that will help you select the next one if the common is not there.

**Comment by yyoncho** [comment]
Closed with FAQ entry. ATM this seems to be the best thing we can do.
