### ISSUE TITLE
How to pass configuration data to language server?

### ISSUE THREAD

**Issue by sivakov512** [emacs-lsp/lsp-mode#167]
With vscode, I can send the settings to the language server. for example, the path to the virtual environment or used linters for`pyls`. How to do it with this plugin?

**Comment by bkchr** [comment]
See [here](https://github.com/emacs-lsp/lsp-rust/blob/239e0cb8912749266a6226b68c6bc3b4362876c1/lsp-rust.el#L79), that is the way it is done for the rust language server.

**Comment by vibhavp** [comment]
Could you give an example? What kind of settings are you talking about?

**Comment by cryptomaniac512** [comment]
As far as I know this is a `workspace/didChangeConfiguration`.
It allow to pass settings for concrete language server. For example, `pyls.configurationSources`.

vscode accept a reference from language server like this https://github.com/palantir/python-language-server/blob/develop/vscode-client/package.json#L19

Without this feature I can not use this this plugin (

**Comment by bkchr** [comment]
Yeah, as I have shown, you need to use  `lsp--set-configuration` to send a `workspace/didChangeConfiguration`. You probably need to add a pr for lsp-python. The code would need to look like the following:

```
(defvar lsp-python--config-options (make-hash-table))

(defun lsp-python--set-configuration ()
  (lsp--set-configuration `(:rust ,lsp-python--config-options)))

(add-hook 'lsp-after-initialize-hook 'lsp-python--set-configuration)

(defun lsp-python-set-config (name option)
  "Set a config option in the python lsp server."
  (puthash name option lsp-python--config-options))

(defun lsp-python-set-jedi-completion-enabled (enable)
  "Enable(t)/Disable(nil) the jedi completion plugin."
(lsp-python-set-config "pyls.plugins.jedi_completion.enabled" enable))
``` 

You will need to look into the linked package.json for all supported properties.

**Comment by cryptomaniac512** [comment]
@bkchr, thanks for help!
As it is then used? just call the appropriate function in my .`dir-locals`?

**Comment by cryptomaniac512** [comment]
I do not have a good experience with elisp ... @bkchr, can you help me with an example of how to set a value for a `configurationSources` property?

```json
"pyls.configurationSources": {
                    "type": "array",
                    "default": ["pycodestyle"],
                    "description": "List of configuration sources to use.",
                    "items": {
                        "type": "string",
                        "enum": ["pycodestyle", "pyflakes"]
                    }
```

**Comment by bkchr** [comment]
Sorry for the late answer. I'm also not the greatest elisp pro.

You could try:
```
 (lsp--set-configuration `(:pyls , (:configurationSources . ("pycodestyle", "pyflakes")))
```

You need to call this function after the lsp-workspace was setup correctly, so I'm unsure if the `.dirlocals` is the right file for that. I don't know when this file is loaded.

**Comment by cryptomaniac512** [comment]
Thanks for the help!

It seems to me that such implementations at the level of a separate plugin are rather complicated. It would be cool to be able to describe the configuration yaml-file at the project level.

**Comment by bkchr** [comment]
Or maybe directly as json :D

**Comment by cryptomaniac512** [comment]
json is too hard for humans, but yaml is great =)

In any case it seems to me more convenient than writing functions in each separate plugin

**Comment by vibhavp** [comment]
How does vscode do it? If it's JSON or YAML, we can simply read that
instead.

**Comment by cryptomaniac512** [comment]
vscode store setting in `<project_dir/.vscode/settings.json`
For example
```json
{
    "python.pythonPath": "/home/cryptomaniac/Devel/Envs/py3_backoffice/bin/python",
    "python.envFile": "${workspaceRoot}/src/app/.env"
  }
```

Plugins provides allowed settings for vscode with files like [this](https://github.com/palantir/python-language-server/blob/develop/vscode-client/package.json)

**Comment by bkchr** [comment]
I like the general idea, but for example for the rust language server I use some options that are globally the same for all my projects. I would not want to create configurations per project. So, we should find a way on how we could integrate both.

@cryptomaniac512 would you maybe want to create a pull request? Or do you think that your elisp knowledge is not be enough?

**Comment by cryptomaniac512** [comment]
> I would not want to create configurations per project.

vscode allow to store settings globally as user. For example this is [my vscode settings](https://github.com/cryptomaniac512/vscode-user-settings/blob/master/settings.json) (I tried to use it)

**Comment by cryptomaniac512** [comment]
> vscode store setting in <project_dir/.vscode/settings.json

In reading the settings it's the problem that they do not describe the configuration for the language server, but for the plug-in for the vscode that uses the language server

**Comment by cryptomaniac512** [comment]
> would you maybe want to create a pull request? Or do you think that your elisp knowledge is not be enough?

I want it, but my knowledge elisp knowledge is bad (

it would be cool to quickly study it and try to do it yourself, for example, but I could not find worthy materials for this...

**Comment by ptxmac** [comment]
Any update on this?

**Comment by cpbotha** [comment]
I'm currently doing it like this:

```
  ;; send pyls config via lsp-after-initialize-hook -- harmless for
  ;; other servers due to pyls key, but would prefer only sending this
  ;; when pyls gets initialised (:initialize function in
  ;; lsp-define-stdio-client is invoked too early (before server
  ;; start)) -- cpbotha
  (defun lsp-set-cfg ()
    (let ((lsp-cfg `(:pyls (:configurationSources ("flake8")))))
      ;; TODO: check lsp--cur-workspace here to decide per server / project
      (lsp--set-configuration lsp-cfg)))
 
  (add-hook 'lsp-after-initialize-hook 'lsp-set-cfg)
```

**Comment by yyoncho** [comment]
Now dir locals could be used in combination of `:initialized-fn` function in `lsp--client` .

**Comment by arkhan** [comment]
Greetings @yyoncho , some example to be able to replicate it?

**Comment by yyoncho** [comment]
@arkhan - which language server do you want to use?

**Comment by arkhan** [comment]
> @arkhan - which language server do you want to use?

Python

**Comment by yyoncho** [comment]
@arkhan 
Here it is the example what has to be performed for python and I have added 2 of the required properties:

https://github.com/yyoncho/lsp-mode/commit/72186e1adc089d772c87ed8f287eb3333b66bfa7

The rest of the settings(+ defaults) are here: https://raw.githubusercontent.com/palantir/python-language-server/develop/vscode-client/package.json 

Do you want to provide a PR adding the rest of the properties? ( I could finish the PR when I have more time)

**Comment by arkhan** [comment]
@yyoncho 
I'm trying to use only falke8 but I can not find a way to do it

**Comment by yyoncho** [comment]
@arkhan 
If there is no such setting in https://raw.githubusercontent.com/palantir/python-language-server/develop/vscode-client/package.json you should ask in pyls project how to do that. My guess is that you could specify what pyls should use when it is installed, e. g. `pip install 'python-language-server[yapf]'`

**Comment by noctuid** [comment]
@yyoncho It would be awesome to have `lsp-clients-python-settings`. Does it actually need to contain all settings to work or could it just contain the settings that are different from the defaults?

**Comment by yyoncho** [comment]
@noctuid I do not use pyls, my guess is that the settings should be present in the set configuration request or it will default to nil/false.

**Comment by yyoncho** [comment]
@noctuid just saw that user @hrehfeld have converted the vscode json to elisp - I will cleanup/organize and commit the changes.

**Comment by axelson** [comment]
Is there an example of setting configuration when you run with only `use-package` instead of a custom plugin that calls `lsp-register-client`?

**Comment by yyoncho** [comment]
@axelson the best option is to extend the language server configuration that you want to use in lsp-clients.el to expose these options as a defcustom and then you could customize them in use-package. You may take a look at lsp-clients.el (go lang server in particular). 

You may register a function or the language server settings your language server using lsp-mode internal api but the approach with defcustoms is the recommended one. 

```
(setf (lsp--client-initialization-options (gethash 'ccls lsp-clients))  options...)
```

**Comment by axelson** [comment]
@yyoncho okay, thanks. I'll give that a shot.
