### ISSUE TITLE
gdscript-lsp constant error messages

### ISSUE THREAD

**Issue by Mo0dy** [emacs-lsp/lsp-mode#1670]
**Describe the bug**
Constant messages of the type:
Error processing message (lsp-unknown-message-type #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("error" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("code" -32601 "message" "Method not found")) "id" nil "jsonrpc" "2.0"))). [2 times]

**To Reproduce**
start lsp in doom with gdscript-mode

**Which Language Server did you use**
lsp-godot

**OS**
archlinux
[server.log](https://github.com/emacs-lsp/lsp-mode/files/4600396/server.log)

**Comment by yyoncho** [comment]
@ofrank123 have you seen something like that?

**Comment by ofrank123** [comment]
Yes, it's due to some issue on the godot lsp end.  I'll try to fix it over there because it's not on lsp-mode's end.

**Comment by ofrank123** [comment]
Should be fixed on [this PR](https://github.com/godotengine/godot/pull/38767)

**Comment by yyoncho** [comment]
Thank you @ofrank123 - I am closing the issue since it does not require actions on our side.
