### ISSUE TITLE
Warning (lsp-mode): Unknown notification: window/progress

### ISSUE THREAD

**Issue by artamudo** [emacs-lsp/lsp-mode#1682]
I don’t know if this is a bug or not, but still I’ll ask.

When using lsp-mode with Tramp on a remote host, such errors occur.

`Warning (lsp-mode): Unknown notification: window/progress
Warning (lsp-mode): Unknown notification: window/progress
Warning (lsp-mode): Unknown notification: window/progress
Warning (lsp-mode): Unknown notification: window/progress
Warning (lsp-mode): Unknown notification: window/progress
Warning (lsp-mode): Unknown notification: window/progress
Warning (lsp-mode): Unknown notification: window/progress
Warning (lsp-mode): Unknown notification: window/progress
Warning (lsp-mode): Unknown notification: window/progress`

https://imgur.com/a/nRBhXeF

Maybe this is only a tramp error, but it only occurs when using the lsp-mode

**Comment by yyoncho** [comment]
What is your config? Note that when you register tramp server you should register the notification-handlers as well as the original client do.

**Comment by artamudo** [comment]
Doom Emacs Config: https://pastebin.com/e75ugADm

> Note that when you register tramp server you should register the notification-handlers as well as the original client do.

I didn't that. Give me the link how make it.

**Comment by artamudo** [comment]
So nobody helps me.

**Comment by yyoncho** [comment]
It has been 10 hours - as per readme you should copy all other properties that the client that you have converted to tramp client has: here it is how the register call looks like: https://github.com/emacs-lsp/lsp-mode/blob/057e8789638a0bf493930637185694b6b09ea58e/lsp-rust.el#L303 .
