### ISSUE TITLE
[discussion] refactor to remove hash-tables and improve the code quality

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#1683]
There are multiple problems with using hashmaps in lsp-mode:

1. HT literal is unreadable
2. they cannot be compared (easily)
3. They are a bit slower when deserialized
4. They are slower with small number of elements (our usecase)
5. Has to be checked for nil
6. ?

The issue is that we have 20k+ lines of code in emacs-lsp that relies on maps. As part of https://github.com/emacs-lsp/dap-mode/pull/274 suggested the following code for since @adam-r-kowalski was looking for some typechecking and I suggested the following code:

``` elisp
(defun dash-expand:&lsp-point (key source)
  (unless (member key '(:line :character))
    (error "Unknown key:  %s" key))
  `(gethash ,(substring (symbol-name key) 1) ,source))

;; works 
(-let [(&lsp-point :line) (ht ("line" 10)
                              ("character" 10))]
  line)

;; fails compile time
(-let [(&lsp-point :line2) (ht ("line" 10)
                               ("character" 10))]
  line2)
```

I was thinking about this idea right after dash introduced the expand feature but I was looking for making the code more beautiful(e. g. remove the strings) but now IMO if we go into that direction we could - autogenerate the expand functions from the spec see https://github.com/microsoft/language-server-protocol/issues/67

The benefits will be: 

1. Code will be a bit safer (and more beautiful?)
2. We will get rid of the "strings!@#"
3. Once we fix all places - we could switch to plists/alists and be happy.

ATM I cannot think of any drawbacks.

WDYT?

**Comment by kiennq** [comment]
Totally agree with this

**Comment by yyoncho** [comment]
> I think with current destructuring syntax, we've already be able to get rid of string, and be able to use either quote symbol `'a` or colon symbol `:a` instead?

Yes, we will be able to use :fieldName and be warned if the field name is not present. 

I will create a small prototype. We could create a few more things on top of the example above:
1. The optional fields will end with `?`
2. The camel case will be automatically replaced with snake-case.

**Comment by yyoncho** [comment]
I have autogenerated the dash bindings: https://gist.github.com/yyoncho/030ed484bd1a215335b97b8df2058a18 

Example ussage:

```
(-let [(&ApplyWorkspaceEditResponse :failure-reason?) (ht ("failureReason" "..."))]
  failure-reason?)
```

We may also try to generate bindings for the actual methods as well.

**Comment by yyoncho** [comment]
Closing in favour of https://github.com/emacs-lsp/lsp-mode/issues/1751
