### ISSUE TITLE
`lsp-server-present?` cannot resolve remote absolute paths

### ISSUE THREAD

**Issue by FelipeLema** [emacs-lsp/lsp-mode#1688]
**Describe the bug**
Using an absolute path as lsp command _in a remote file_ results in lsp not finding the path (because `lsp-server-present?` is not resolving it correctly)

**To Reproduce**
``` emacs-lisp
(let ((default-directory (concat "/ssh:localhost:" default-directory))
   (lsp-server-present? '("/some/absolute/path/lsp_command"))) ;; returns nil, logs that couldn't find a proper server
```

`executable-find` searches a command in all paths, but `/some/absolute/path/lsp_command` is not in any of them (there's no `/bin/some/absolute/path/lsp_command` or `/usr/local/bin/some/absolute/path/lsp_command`)

**Expected behavior**
Remote absolute values should be resolved to the proper path (and thus, no "couldn't find /abs/path/lsp_cmd" message is printed).

**Which Language Server did you use**
`clangd`, but affects all LSP servers

**OS**
debian bullseye

**Error callstack**
N/A

**Comment by yyoncho** [comment]
AFAICS the issue is a bug in tramp/ executable-find (or it is by design?). I am testing on emacs 27 and if I do 
` (executable-find "/bin/ls" t)` works fine but it breaks if I move `ls` in a folder which is not on the remote path(?). We can work around the issue on our side by checking if file exists.

(cc @Eli-Zaretskii)

**Comment by Eli-Zaretskii** [comment]
I suggest to either ask a question on `emacs-devel` or report a bug with all the details.  Michael Albinus, the developer of Tramp, will definitely help you with this.

**Comment by yyoncho** [comment]
@Eli-Zaretskii thank you

**Comment by yyoncho** [comment]
As advised by Eli I asked Michael. The issue is that the full path that you are checking should be prefixed with `ssh:localhost:`. It should be the real full path including the host name. I will update the docs.
