### ISSUE TITLE
lsp-vue

### ISSUE THREAD

**Issue by cryptomaniac512** [emacs-lsp/lsp-mode#169]
I made a [support](https://github.com/cryptomaniac512/lsp-vue) for Vue.js using [vls](https://github.com/vuejs/vetur/tree/master/server)

Can I move it to your organization?

I also have a number of problems with it, which I would like to discuss in a way that is convenient for you.

**Comment by vibhavp** [comment]
I've created https://github.com/emacs-lsp/lsp-vue, and added you as a collaborator, thanks.

**Comment by cryptomaniac512** [comment]
Thanks!
