### ISSUE TITLE
Unit test integration

### ISSUE THREAD

**Issue by razzmatazz** [emacs-lsp/lsp-mode#1690]
I am not sure how to approach the issue of implementing unit test runners.

From my experience, in `omnisharp-emacs`, in conjunction with `omnisharp-roslyn` server, we use a model where a `run-test` command is sent to server, and then a notification for each line of the output + metadata from the test runs are received in a "notification fashion" and are shown in a `compilation-mode`-derived buffer (so we get ability to go-to-error, like in regular `*compilation*` buffer).

What is the proposed model for `emacs-lsp/lsp-mode` and LSP in general? I was browsing LSP specification and did not notice much on the mechanism to forward output from processed started by a command (e.g. to run a test). And I did not find any `lsp-mode` customization regarding this in this project. The only things was a mention in LSP specification where it says that code lens may provide references to commands that can be used to run tests, but that was it.

Is this something each language server + clients needs to invent using custom notification handlers or have I missed something?

**Comment by yyoncho** [comment]
Generally, this is handled by dap-mode and DAP protocol.

**Comment by razzmatazz** [comment]
Implementation of DAP protocol looks way too complicated a chore just to get unit testing working, which for omnisharp-roslyn is feasible fairly easily as omnisharp-roslyn already supports this using the native protocol.

Also, C# lands does not have a stable portable interface for debuggers AFAIK (yet) and that job is way over my head (and will).

Would it be a grave sin to implement a custom notification handler, (say `csharp/omnisharp/unit-test-output`) and server bits just for unit test run functionality in `lsp-csharp`? It would scratch my itch of not being able to run tests from lsp-mode (as I have been accustomized with `omnisharp-emacs`). Implementation-wise in `lsp-mode` I would create a new `lsp-csharp-unit-test-mode` based on top of `compilation-mode` where the output from those `csharp/omnisharp/unit-test-output` notifications would simply get appended to a `*lsp-csharp-unit-test*` buffer which would use `lsp-csharp-unit-test-mode`.

**Comment by yyoncho** [comment]
> Would it be a grave sin to implement a custom notification handler, (say csharp/omnisharp/unit-test-output) and server bits just for unit test run functionality in lsp-csharp?

If it is perfectly fine - but IMO as long as vscode is able to run/debug you will be able to do the same with lsp-mode + dap-mode (except if there is a license restriction). Also, if you want you could spin off lsp-csharp.el into a separate project. You might be interested in this as well - https://github.com/emacs-lsp/dap-mode/pull/138

**Comment by razzmatazz** [comment]
> > Would it be a grave sin to implement a custom notification handler, (say csharp/omnisharp/unit-test-output) and server bits just for unit test run functionality in lsp-csharp?
> 
> If it is perfectly fine - but IMO as long as vscode is able to run/debug you will be able to do the same with lsp-mode + dap-mode (except if there is a license restriction). Also, if you want you could spin off lsp-csharp.el into a separate project. You might be interested in this as well - [emacs-lsp/dap-mode#138](https://github.com/emacs-lsp/dap-mode/pull/138)

`omnisharp-vscode` actually uses `omnisharp-roslyn` native protocol for running tests with the same mechanism (but not layered over LSP as I think about doing here). Well, unless you launch a test in a debugger. You are correct, that the debugger that omnisharp-vscode uses has different licensing (non-MIT) and it is provided in binary-only form. emacs-lsp/dap-mode#138 uses a different debugger, from Samsung, than omnisharp-vscode uses.

In any case, my proposed implementation would do the same thing as `omnisharp-vscode` does (AFAIK) but over LSP.  So.. OK, I will take a look at implementing it the way I propose so at least we have something working before there are come better means (via DAP or otherwise) to run the tests.

**Comment by razzmatazz** [comment]
Closing this issue as I’ve decided to use custom commands and notifications to implement the flow with lsp-csharp. Thanks for the input!

**Comment by serezlan** [comment]
Hi @razzmatazz ,

Could you share your solution for unit test runner?

Thx

**Comment by razzmatazz** [comment]
> Hi @razzmatazz ,
> 
> Could you share your solution for unit test runner?
> 
> Thx

Hey,

You can find those functions on `M-x`, in particular:
- lsp-csharp-run-all-tests-in-buffer
- lsp-csharp-run-test-at-point
- lsp-csharp-run-test-in-buffer

You shouldn't need any special configuration, except maybe binding these fns to your preferred shortcuts. Also, this works with omnisharp LSP server only.

I probably need to add documentation to emacs-lsp/lsp-mode repo on this..
