### ISSUE TITLE
eldoc error: invalid-function

### ISSUE THREAD

**Issue by rattit0** [emacs-lsp/lsp-mode#170]
https://github.com/emacs-lsp/lsp-mode/blob/0e1d308d8635bfad4f4f4b7c49c76eb2a3d61fad/lsp-methods.el#L1164-L1167
I'm confused about the `#'string-equal` here. And I got an error message after upgrading today:
`eldoc error: (invalid-function (renderer (alist-get (gethash language e) renderers nil nil (function string-equal))))`
Changing it to `(if-let ((renderer (alist-get (gethash "language" e) renderers)))` might fix.

**Comment by vibhavp** [comment]
From the `alist-get`'s docstring:

> `(alist-get KEY ALIST &optional DEFAULT REMOVE TESTFN)`

If TESTFN is not provided, it uses `eq`, which doesn't work for strings. I doubt that is causing this problem. I've replaced it with `assoc-string` anyway, does that fix it?

**Comment by rattit0** [comment]
OK, I know what's happening here.
https://github.com/emacs-mirror/emacs/blob/76e1f7d00fbff7bf8183ba85db2f67a11aa2d5ce/etc/NEWS#L1119-L1124
`TESTFN` is only supported since Emacs 26.1. But I'm using Emacs 25.

**Comment by rattit0** [comment]
https://github.com/emacs-mirror/emacs/blob/76e1f7d00fbff7bf8183ba85db2f67a11aa2d5ce/etc/NEWS#L1293-L1297
And so is `if-let*`.

**Comment by vibhavp** [comment]
ah, I should start testing with Emacs 25 instead.
