### ISSUE TITLE
Performance section in docs missing while link is still in place

### ISSUE THREAD

**Issue by imsodin** [emacs-lsp/lsp-mode#1700]
In the [readme's why section](https://github.com/emacs-lsp/lsp-mode#why) there's a link to a performance section, which leads to the install page, which doesn't mention performance. That section was removed in https://github.com/emacs-lsp/lsp-mode/commit/7dcaa224a91151002cadcf5eea94db9dfa2a6591 and doesn't seem to be available anymore anywhere. Which looks like that removal was a mistake, maybe should have been a move, where the new file was left behind by accident? If the removal of the performance section was intentional (though some info there looks totally helpful), the link in the readme should be removed too.

**Comment by yyoncho** [comment]
@ericdallo ?

**Comment by ericdallo** [comment]
Thanks for the report @imsodin, I think I accidentally removed when moving some sections, fixed it [here](https://github.com/emacs-lsp/lsp-mode/commit/93057777c66e8f0e9140b8d0d3215beaa2c035a9).

https://emacs-lsp.github.io/lsp-mode/page/performance
