### ISSUE TITLE
No easy way to disable lsp-ui and company integration

### ISSUE THREAD

**Issue by jech** [emacs-lsp/lsp-mode#1734]
If `lsp-auto-configure` is set, then `lsp--auto-configure` will enable `lsp-ui` and `company` integration if possible.  There are no variables to control this behaviour.

Please implement `lsp-enable-ui` and `lsp-enable-company` so that these features can be explicitly disabled.

**Comment by yyoncho** [comment]
Use lsp-enable-completion-at-point for company.
Use lsp-ui-doc-enable and lsp-ui-sigeline-enable for lsp-ui.

**Comment by jech** [comment]
I'm using LSP's support for `completion-at-point`, I'm just not using `company-mode` but the built-in completion.

**Comment by yyoncho** [comment]
company-lsp support is soon to be removed then I will do the requested change. ATM you could use lsp-managed-mode-hook to turn off the stuff you do not like.

**Comment by yyoncho** [comment]
Now we have `lsp-completion-provider` which can be set to :none. Marking as closed.
