### ISSUE TITLE
Python, long company response time when deleting the last character after dot

### ISSUE THREAD

**Issue by haoyuan80s** [emacs-lsp/lsp-mode#1737]
Start at:
![image](https://user-images.githubusercontent.com/9064146/83348221-57a41800-a2df-11ea-8a09-dee4934d6090.png)

Deleting `n,` and `a`, the response is instant:

![image](https://user-images.githubusercontent.com/9064146/83348228-70143280-a2df-11ea-8ff0-4785b9663f1b.png)

Deleting `r`, it take ~3s to complete:

![image](https://user-images.githubusercontent.com/9064146/83348234-7acec780-a2df-11ea-960d-9e59908d21c9.png)

Any fix or reason for the long response time?

**Comment by yyoncho** [comment]
Please check: https://emacs-lsp.github.io/lsp-mode/page/performance/
