### ISSUE TITLE
(wrong-type-argument hash-table-p nil) when trying to show diagnostics

### ISSUE THREAD

**Issue by jumper047** [emacs-lsp/lsp-mode#1739]
When i open python file flycheck diagnostics in mode-line shows "error", and on every cursor move in echo are appears message ```Error running timer: (wrong-type-argument hash-table-p nil)```
To reproduce bug - open any python project (no matter which language server to use).
Expected behavior - show diagnostic as usally
Language server - pyls
OS - Ubuntu 19.04
Error callstack:
[Trace - 11:29:30 ] Sending request 'textDocument/hover - (106)'.
Params: {
  "textDocument": {
    "uri": "file:///home/psh/app/model.py"
  },
  "position": {
    "line": 16,
    "character": 21
  }
}

[Trace - 11:29:30 ] Received response 'textDocument/hover - (106)' in 15ms.
Result: null

[Trace - 11:29:31 ] Sending request 'textDocument/hover - (107)'.
Params: {
  "textDocument": {
    "uri": "file:///home/psh/app/model.py"
  },
  "position": {
    "line": 16,
    "character": 21
  }
}

[Trace - 11:29:31 ] Sending request 'textDocument/documentHighlight - (108)'.
Params: {
  "textDocument": {
    "uri": "file:///home/psh/app/model.py"
  },
  "position": {
    "line": 16,
    "character": 21
  }
}

[Trace - 11:29:31 ] Received response 'textDocument/hover - (107)' in 17ms.
Result: null

[Trace - 11:29:31 ] Received response 'textDocument/documentHighlight - (108)' in 16ms.
Result: []

[Trace - 11:29:43 ] Sending request 'textDocument/hover - (109)'.
Params: {
  "textDocument": {
    "uri": "file:///home/psh/app/model.py"
  },
  "position": {
    "line": 16,
    "character": 21
  }
}

[Trace - 11:29:43 ] Received response 'textDocument/hover - (109)' in 19ms.
Result: null

Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  maphash(#f(compiled-function (file-name diagnostics) #<bytecode 0x156439ef40b5>) nil)
  #f(compiled-function (workspace) #<bytecode 0x156439ef3e15>)(#s(lsp--workspace :ewoc nil :server-capabilities #<hash-table equal 15/15 0x156439b88141> :registered-server-capabilities nil :root "/home/psh/Src/Windows/spo_kp/new_protocol" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode 0x156439915149>) :test\? #f(compiled-function () #<bytecode 0x1564399150a5>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 5/65 0x156439915155> :request-handlers #<hash-table equal 0/65 0x1564399157e5> :response-handlers #<hash-table eql 0/65 0x156439915889> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x156439915cc5> :action-handlers #<hash-table equal 0/65 0x1564399158a9> :major-modes (python-mode) :activation-fn nil :priority 1 :server-id mspyls :multi-root nil :initialization-options lsp-python-ms--extra-init-params :custom-capabilities nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn #f(compiled-function (workspace) #<bytecode 0x1564399150bd>) :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x1564399158c9> :download-server-fn #f(compiled-function (client callback error-callback update\?) #<bytecode 0x1564399150d1>) :download-in-progress? nil :buffers nil) :host-root nil :proc #<process mspyls> :cmd-proc #<process mspyls> :buffers (#<buffer model.py>) :semantic-highlighting-faces nil :semantic-highlighting-modifier-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x15643998a8a9> :watches #<hash-table equal 0/65 0x15643998ab81> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x15643998aba1> :work-done-tokens #<hash-table equal 0/65 0x15643998afc5>))
  mapc(#f(compiled-function (workspace) #<bytecode 0x156439ef3e15>) (#s(lsp--workspace :ewoc nil :server-capabilities #<hash-table equal 15/15 0x156439b88141> :registered-server-capabilities nil :root "/home/psh/Src/Windows/spo_kp/new_protocol" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode 0x156439915149>) :test\? #f(compiled-function () #<bytecode 0x1564399150a5>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 5/65 0x156439915155> :request-handlers #<hash-table equal 0/65 0x1564399157e5> :response-handlers #<hash-table eql 0/65 0x156439915889> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x156439915cc5> :action-handlers #<hash-table equal 0/65 0x1564399158a9> :major-modes (python-mode) :activation-fn nil :priority 1 :server-id mspyls :multi-root nil :initialization-options lsp-python-ms--extra-init-params :custom-capabilities nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn #f(compiled-function (workspace) #<bytecode 0x1564399150bd>) :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x1564399158c9> :download-server-fn #f(compiled-function (client callback error-callback update\?) #<bytecode 0x1564399150d1>) :download-in-progress? nil :buffers nil) :host-root nil :proc #<process mspyls> :cmd-proc #<process mspyls> :buffers (#<buffer model.py>) :semantic-highlighting-faces nil :semantic-highlighting-modifier-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x15643998a8a9> :watches #<hash-table equal 0/65 0x15643998ab81> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x15643998aba1> :work-done-tokens #<hash-table equal 0/65 0x15643998afc5>)))
  lsp-diagnostics()
  lsp-cur-line-diagnostics()
  lsp--text-document-code-action-params()
  lsp-ui-sideline--run()
  #f(compiled-function () #<bytecode 0x156439ee9505>)()
  apply(#f(compiled-function () #<bytecode 0x156439ee9505>) nil)
  timer-event-handler([t 0 0 200000 nil #f(compiled-function () #<bytecode 0x156439ee9505>) nil idle 0])

Command "pyls" is present on the path.
Command "pyls" is present on the path.
Found the following clients for /home/psh/Src/Windows/spo_kp/new_protocol/app/model.py: (server-id pyls, priority -1), (server-id mspyls, priority 1)
The following clients were selected based on priority: (server-id mspyls, priority 1)
Analysis cache path: /home/psh/.cache/Microsoft/Python Language Server
Microsoft Python Language Server version 0.5.50.0
Workspace root: /home/psh/Src/Windows/spo_kp/new_protocol
GetCurrentSearchPaths /usr/bin/python 
Interpreter search paths:
    /usr/lib/python3.7
    /usr/lib/python3.7/lib-dynload
    /usr/local/lib/python3.7/dist-packages/_pdbpp_path_hack
    /home/psh/.local/lib/python3.7/site-packages
    /usr/local/lib/python3.7/dist-packages
    /usr/local/lib/python3.7/dist-packages/deepspeech_server-1.1.0-py3.7.egg
    /usr/lib/python3/dist-packages
User search paths:
Initializing for /usr/bin/python
Analysis caching mode: None.
Analyzing in background, 1 items left...
Analyzing in background, 61 items left...
Analyzing in background, 18 items left...
Analyzing in background, 25 items left...
Analyzing in background, 19 items left...
Analyzing in background, 68 items left...
Analyzing in background, 27 items left...
Analyzing in background, 11 items left...
Analyzing in background, 9 items left...
Analyzing in background, 337 items left...
Analyzing in background, 277 items left...
Analyzing in background, 261 items left...
Analyzing in background, 237 items left...
Analyzing in background, 197 items left...
Analyzing in background, 178 items left...
Analyzing in background, 167 items left...
Analyzing in background, 157 items left...
Analyzing in background, 135 items left...
Analyzing in background, 129 items left...
Analyzing in background, 7 items left...
Analyzing in background, 5 items left...
Analyzing in background, 4 items left...
Command "pyls" is present on the path.
Command "pyls" is present on the path.
Found the following clients for /home/psh/Src/Linux/playground/test.py: (server-id pyls, priority -1), (server-id mspyls, priority 1)
The following clients were selected based on priority: (server-id mspyls, priority 1)
Command "pyls" is present on the path.
Command "pyls" is present on the path.
Found the following clients for /home/psh/Src/Linux/playground/test.py: (server-id pyls, priority -1), (server-id mspyls, priority 1)
The following clients were selected based on priority: (server-id mspyls, priority 1)
Analysis cache path: /home/psh/.cache/Microsoft/Python Language Server
Microsoft Python Language Server version 0.5.50.0
Workspace root: /home/psh/Src/Linux/playground
GetCurrentSearchPaths /usr/bin/python 
Interpreter search paths:
    /usr/lib/python3.7
    /usr/lib/python3.7/lib-dynload
    /usr/local/lib/python3.7/dist-packages/_pdbpp_path_hack
    /home/psh/.local/lib/python3.7/site-packages
    /usr/local/lib/python3.7/dist-packages
    /usr/local/lib/python3.7/dist-packages/deepspeech_server-1.1.0-py3.7.egg
    /usr/lib/python3/dist-packages
User search paths:
Initializing for /usr/bin/python
Analysis caching mode: None.

**Comment by jumper047** [comment]
Roll back to latest stable release fixes the issue (melpa-stable rocks:))

**Comment by yyoncho** [comment]
melpa would work too - just delete elc files to force bytecompiling - package.el is not doing a good job from time to time.
