### ISSUE TITLE
lsp--shut-down-p: add user option to suppress prompt

### ISSUE THREAD

**Issue by phst** [emacs-lsp/lsp-mode#174]
Some users don't like to be prompted when closing a workspace. Therefore I'd propose to add a user option to customize the behavior of `lsp--shut-down-p`, like:

```elisp
(defcustom lsp-close-server-on-kill-buffer :prompt
  :type '(choice (const :never) (const :always) (const :prompt))

(defun lsp--shut-down-p ()
  (cl-ecase sp-close-server-on-kill-buffer
    (:never nil)
     (:always t)
    (:prompt (y-or-n-p "...")))
```

**Comment by bkchr** [comment]
Why did you create two issues for your problem?

**Comment by phst** [comment]
Fixed by https://github.com/emacs-lsp/lsp-mode/pull/176
