### ISSUE TITLE
lsp rust doesn't work with flycheck

### ISSUE THREAD

**Issue by phamhm** [emacs-lsp/lsp-mode#1742]
My flycheck checker is set to 'lsp', but it doesn't show any errors. When I switch the checker to 'rust-cargo', flycheck starts working again. 

I'm unable to swap out lsp to other checkers. 

Is there a way to replace "lsp" as a flycheck checker?

**Comment by yyoncho** [comment]
Set `lsp-diagnostic-package` to :none to disable lsp checker.
