### ISSUE TITLE
Add sonarlint language-server

### ISSUE THREAD

**Issue by Sasanidas** [emacs-lsp/lsp-mode#1746]
I was trying to add the [sonarlint-language-server](https://github.com/SonarSource/sonarlint-language-server), but i don't know exactly how to proceed, reading the atom sonarlint integration (now deprecated) and the [source code](https://github.com/SonarSource/sonarlint-atom/blob/master/lib/sonarlint.js) creates a socket so the LSP can connect to, also there is this [post](https://community.sonarsource.com/t/running-sonarlint-language-server-from-shell/24440) from the sonarlint forum, with the guy explain it.
Any tips or ideas on how to continue?
Thank you :+1:

**Comment by yyoncho** [comment]
we can connect to tcp server and also we could act as tcp server and let the language server connect to us. check lsp-tcp-server-command and lsp-tcp-connection . The easies way to integrate with server is usually by starting it in vscode and checking what is the server process and then replicate that in emacs.

**Comment by yyoncho** [comment]
... and if you have more questions don't hesitate to ask.

**Comment by Sasanidas** [comment]
> ... and if you have more questions don't hesitate to ask.

Sure I'll give it a try, thanks for the answer :+1:

**Comment by Sasanidas** [comment]
Ok I manage to "start" the lsp server, this is the code:

(defun lsp-sonarlint-server-start-fun (port)
  `("java" " " "/home/username/sonarlint-server.jar " ,(number-to-string port) ))


(lsp-register-client
 (make-lsp-client
  :new-connection (lsp-tcp-server-command 'lsp-sonarlint-server-start-fun)
  :major-modes '(php-mode)
  :priority 1
  :server-id 'sonarlint
  :initialized-fn (lambda (workspace)
                    (with-lsp-workspace workspace
                      (lsp--set-configuration
                       (lsp-configuration-section "sonarlint"))))))

It tries to connect, but fails 

LSP :: Waiting for connection for sonarlint, retries: 19
helm-M-x-execute-command: Failed to create connection to sonarlint on port 37755

And the stderr buffer:

Process sonarlint stderr finished
Error: Could not find or load main class  
Caused by: java.lang.ClassNotFoundException:  


Process sonarlint stderr finished

I tried the lsp server in the vscode file, and the compiled from source version, none of the work same exception.

Any clue?

**Comment by yyoncho** [comment]
I suspect that

```
(defun lsp-sonarlint-server-start-fun (port)
`("java" " " "/home/username/sonarlint-server.jar " ,(number-to-string port) ))
```

should be

```
(defun lsp-sonarlint-server-start-fun (port)
`("java" "-jar" "/home/username/sonarlint-server.jar " ,(number-to-string port) ))
```

**Comment by yyoncho** [comment]
yes, that is the right way to pass initialization options.

**Comment by Sasanidas** [comment]
Hello again, I've been trying to set the correct initialization option without success.
Even copy the Atom options, it gives me a parse error:


[Error - 20:53:25.335] Unable to update configuration
[Error - 20:53:25.338] java.lang.NullPointerException
	at org.sonarsource.sonarlint.ls.settings.SettingsManager.parseSettings(SettingsManager.java:199)
	at org.sonarsource.sonarlint.ls.settings.SettingsManager.lambda$didChangeConfiguration$1(SettingsManager.java:127)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)


These are the options I'm using:
(lsp-register-client
 (make-lsp-client
  :new-connection (lsp-tcp-server-command 'lsp-sonarlint-server-start-fun)
  :major-modes '(java-mode)
  :priority 1
  :server-id 'sonarlint
  :initialization-options (lambda ()
			    (list
			      :productKey "emacs"
			      :productName "Emacs"
			       :disableTelemetry t
			     )
                            )
  :initialized-fn (lambda (workspace)
                    (with-lsp-workspace workspace
                      (lsp--set-configuration
                       (lsp-configuration-section "sonarlint"))))))

And the parse line error is [here](https://github.com/SonarSource/sonarlint-language-server/blob/05e8b5854edeb39082e0627954f4cb6a74287a41/src/main/java/org/sonarsource/sonarlint/ls/settings/SettingsManager.java#L199)
Any clue?
Thanks!

**Comment by yyoncho** [comment]
The issue is that you are sending empty configuration via 

```
(lsp--set-configuration
(lsp-configuration-section "sonarlint"))
```

You should use lsp-register-custom-settings and register property "sonarlint.disableTelemetry". There a lot of examples for that in lsp-mode/lsp-java source code.

**Comment by Sasanidas** [comment]
Hello again, sorry for the delay.
 I made it work!
![Screenshot from 2020-06-10 11-03-47](https://user-images.githubusercontent.com/26670956/84248723-5baf1180-aaf9-11ea-8d61-390496b34afe.png)

At least with almost all the analyser extensions, except for the java one, that doesn't apparently trigger any error, maybe is my java configuration.

The last thing left to do maybe is to configure code actions, like atom does:
![sonarlint-atom](https://user-images.githubusercontent.com/26670956/84249553-71710680-aafa-11ea-93ba-4e81e57a7b32.gif)

Thank you!

**Comment by Sasanidas** [comment]
Hello @yyoncho , these days I've been working on the implementation.
Right now, except for the code actions, is quite usable, and works with all the languages. It still need some development to be "production ready", I'm interested in the possibility to add it to the emacs-lsp family.
[Repository url](https://gitlab.com/sasanidas/lsp-sonarlint)

Thank you!

**Comment by yyoncho** [comment]
> > > The last thing left to do maybe is to configure code actions, like atom does:
> > 
> > 
> > I guess this is some kind of protocol extension. AFAIK there is no such feature in core spec.
> 
> I tried to copy the atom code but without luck
> `connection.onCustom('sonarlint/openRuleDescription', this.openRuleDescription.bind(this));`
> Seems like the returned value is just a JSON object.
> 
> When I click in the "open description" gives me this message
> `Jun 10, 2020 8:40:30 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation WARNING: Unmatched cancel notification for request id 52`
> 
> I'm sorry for all the questions, if you think this is unrelated or out the scope, if fine, really thanks!

can you provide a bit more context?

**Comment by Sasanidas** [comment]
> > > > The last thing left to do maybe is to configure code actions, like atom does:
> > > 
> > > 
> > > I guess this is some kind of protocol extension. AFAIK there is no such feature in core spec.
> > 
> > 
> > I tried to copy the atom code but without luck
> > `connection.onCustom('sonarlint/openRuleDescription', this.openRuleDescription.bind(this));`
> > Seems like the returned value is just a JSON object.
> > When I click in the "open description" gives me this message
> > `Jun 10, 2020 8:40:30 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation WARNING: Unmatched cancel notification for request id 52`
> > I'm sorry for all the questions, if you think this is unrelated or out the scope, if fine, really thanks!
> 
> can you provide a bit more context?

Hello again, I made it work! seems like it was the server version, now the code action works and render the html response:
![ezgif com-gif-maker(6)](https://user-images.githubusercontent.com/26670956/84588365-58c46180-ae16-11ea-9958-d76f47ef1d2e.gif)

**Comment by Sasanidas** [comment]
Hello again, I'm currently open a request on Melpa for the repository, right now all  the basic functionality works, it even support more languages than some of the official ones, there still some things TODO like the connection with sonarqube, but I think this is out of the scope of this issue.
Again, thank you @yyoncho !

**Comment by ericdallo** [comment]
@yyoncho Don't you think it makes sense we create a repository `lsp-sonarlint` on `emacs-lsp`?

**Comment by yyoncho** [comment]
It is up to the author of the package.

**Comment by Sasanidas** [comment]
> @yyoncho Don't you think it makes sense we create a repository `lsp-sonarlint` on `emacs-lsp`?

it have some plug-ins to configure, and the main file may become too large, and in the future i want to connect to an external service.
I think a separate repository is the right option

**Comment by Sasanidas** [comment]
I can add the repository to the emacs-lsp group, but I don't know if that is possible @yyoncho @ericdallo

**Comment by ericdallo** [comment]
If you agree, we can create a repository on emacs-lsp organization and make you admin of the repository, then you can migrate to this repository, what do you think @Sasanidas?

**Comment by Sasanidas** [comment]
> If you agree, we can create a repository on emacs-lsp organization and make you admin of the repository, then you can migrate the code from GitLab to that repository, what do you think @Sasanidas?

That would be great! :smile:

**Comment by ericdallo** [comment]
Sent you the invite to https://github.com/emacs-lsp/lsp-sonarlint

Welcome to emacs-lsp @Sasanidas :)
