### ISSUE TITLE
lsp-rust-server always set to rls

### ISSUE THREAD

**Issue by dalepsmith** [emacs-lsp/lsp-mode#1748]
Following the instructions at https://rust-analyzer.github.io/manual.html#emacs
 Step 2: "Set lsp-rust-server to 'rust-analyzer".

Either by using setq, customize-variable, or added a :custom section to use-package, this variable refused to stay at 'rust-analyzer and would always switch back to 'rls.

By used debug-on-variable-change, is seems I should be setting rustic-lsp-server instead.

And that works!  I'm now enjoying rust-analyzer goodness.

So the documentation needs to be changed to note this.

**Comment by kiennq** [comment]
Are you using `rustic-mode`? It may override the `lsp-rust-server`

**Comment by yyoncho** [comment]
cc @brotzeit

**Comment by brotzeit** [comment]
Yeah, sorry that is supposed to help users who want to use eglot. I will try to emphasize this behaviour in the readme (https://github.com/brotzeit/rustic#lsp).
