### ISSUE TITLE
comment-region in rust-mode with lsp-mode comments out the entire file

### ISSUE THREAD

**Issue by tomalexander** [emacs-lsp/lsp-mode#1752]
**Describe the bug**
When editing a rust source file with lsp-mode, if I highlight a portion of the file, hit `M-x` and run `comment-region` then comments are inserted throughout the remainder of the file instead of just on the lines that I edited. For example, starting with this file:

```rust
fn main() {
    let x = "foo";
    let y = "bar";
}

fn other() {
    let x = "baz";
    let y = "y0";
}
```

If I highlight lines 2 and 3 (the body of `main()`) and execument `comment-region` the result is:
```rust
fn main() {
    // let x = "foo";
    // let y = "bar";
}   // 

fn o// ther() {
    // let x = "baz";
    // let y = "y0";
}   // 
```

The expected behavior would be:
```rust
fn main() {
    // let x = "foo";
    // let y = "bar";
}

fn other() {
    let x = "baz";
    let y = "y0";
}
```

Through testing with `emacs -q` I've narrowed it down to only occurring whenever `lsp-mode` is either currently or previously active in that buffer (so, `M-x lsp-mode` to disable lsp-mode doesn't remove the problem, but if `lsp-mode` was never active in the buffer then the problem does not occur).

**To Reproduce**
```
emacs -q --eval "(progn (package-initialize) (add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\")) (package-refresh-contents) (package-install 'rust-mode) (package-install 'lsp-mode) (add-hook 'rust-mode-hook 'lsp))"
```
Then open a rust file with the contents of my first code block above, highlight lines 2 and 3, and run `M-x comment-region`.

Proof it does not occur without lsp-mode, if you remove the hook to launch lsp-mode but leave everything else the same, the problem does not happen:
```
emacs -q --eval "(progn (package-initialize) (add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\")) (package-refresh-contents) (package-install 'rust-mode) (package-install 'lsp-mode))"
```

**Expected behavior**
I expect only the lines that I have highlighted to be commented. This would result in the following source file:

```rust
fn main() {
    // let x = "foo";
    // let y = "bar";
}

fn other() {
    let x = "baz";
    let y = "y0";
}
```

**Which Language Server did you use**
I tested with both rust-analyzer and rls, so I do not think the language server itself is the problem. My rust-analyzer version is `20200525-1` and my rls version is `nightly-2020-02-22`

**OS**
Arch Linux

**Comment by yyoncho** [comment]
Most likely fixed by https://github.com/emacs-lsp/lsp-mode/commit/259c4afa17c0530029776e95050565d13c78d2f3

**Comment by tomalexander** [comment]
I downloaded the latest lsp-mode from melpa today and it is indeed fixed.
