### ISSUE TITLE
lsp-save-restriction-and-excursion does not cooperate with yasnippet

### ISSUE THREAD

**Issue by leungbk** [emacs-lsp/lsp-mode#1753]
## Reproduction instructions:

With `typescript-language-server` and the latest master branch of `lsp-mode`, do the following:

``` sh
npm i -g create-react-app
create-react-app hello-world
cd hello-world/src
```

Make a file `Counter.js` with the following:

``` js


import React, { Component } from "react";

class Counter extends Component {
  constructor(props) {
    super(props);
    this.state = { count: 0 };
  }

  increment() {
    // on the below line, begin to type setState and then complete with company
  }

  render() {
    const { count } = this.state;

    return (
      <div className="thing">
        <p className="count">{count}</p>
        <section className="controls">
          <button onClick={this.increment}>Increment</button>
        </section>
      </div>
    );
  }
}

export default Counter;
```

Go to the `increment` method and type the first few letters of `setState` and complete `setState (method)` with `company`. `point` will move to the end of the buffer on the latest master branch of `lsp-mode`, which is not desirable; we want it to stay at the end of `this.setState` after completing with `company`.

The reason seems to be that in `yasnippet.el`, `yas--snippet-create` will 1) run `after-change-functions`, triggering `lsp-on-change` -> `lsp--text-document-content-change-event` -> `(lsp--buffer-content)` and causing a `(widen)`, and 2) `(goto-char (point-max))` in `yas--snippet-create` after `lsp-on-change` has `widen`ed the buffer that `yas--snippet-create` originally narrowed. https://github.com/joaotavora/yasnippet/blob/5b1217ab085fab4abeb1118dccb260691b446703/yasnippet.el#L4189

I've managed to work around this by writing a `(save-excursion (save-restriction` around https://github.com/emacs-lsp/lsp-mode/blob/ad7b48915d3c9486ca63ea85e1a92922b7ea8213/lsp-mode.el#L3850
which is the event that causes the forced `widen`.

I'm not sure if this solution works well with the new org-related changes to `lsp-mode`, though, since I haven't experimented much with them. 

We can't simply wrap that section with the current version of `lsp--save-restriction-and-excursion` since this will forcibly `widen` and revert the `narrow-to-region` performed by `yasnippet`.

As an alternative to patching `lsp-mode.el`, we could patch `yasnippet` by computing `(point-max)` only once and having `point` move to that value in the end of `yas--snippet-create`. It shouldn't hurt to patch both, to guard against unexpected `widen`ing.

**Comment by yyoncho** [comment]
Thank you for the deep analysis! The issue was in lsp-save-restriction-and-excursion - it should not have any effect visible to the outside world.
