### ISSUE TITLE
[Task] investigate removing lsp--folding-range 

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#1759]
After https://github.com/emacs-lsp/lsp-mode/issues/1751 is fixed we may check if lsp--folding-range can be removed in favour of using directly the struct coming from the server. We did that for lsp-diagnostics and it resulted in better/less code overall.

**Comment by yyoncho** [comment]
cc @leungbk

**Comment by leungbk** [comment]
The `FoldingRange`s returned by LSP servers don't have a `children` property of any kind. `origami.el` treats folding ranges as trees with children. I think we should keep the `lsp--folding-range` struct for this reason.

We should be able to remove the `orig-folding-range` property on that struct, though. It doesn't seem like `lsp-focus` or `lsp-origami` makes use of it.
