### ISSUE TITLE
Error processing message (invalid-function lsp-save-restriction-and-excursion

### ISSUE THREAD

**Issue by snakebyte85** [emacs-lsp/lsp-mode#1764]
**Describe the bug**
I updated LSP and all its dependencies to last version via Emacs packages manager.

Now the following error occurs when I open any file associated to a LSP

`LSP :: Connected to [jdtls:44345 status:starting].
Error processing message (invalid-function lsp-save-restriction-and-excursion).
Error processing message (wrong-type-argument hash-table-p nil). [808 times]`

**To Reproduce**
open any file associated to the related LSP (Tried lsp-java and xml)

**OS**
Arch

**Comment by yyoncho** [comment]
Deleting elc files in lsp-mode package should be able to fix the issue.

**Comment by vkomenda** [comment]
> Deleting elc files in lsp-mode package should be able to fix the issue.

It does help indeed.
