### ISSUE TITLE
error starting lsp-server in javascript buffer

### ISSUE THREAD

**Issue by am-1t** [emacs-lsp/lsp-mode#1768]
**_Description:_** Opening a javascript buffer triggers an error ,@yyoncho described it as bug in "_lsp-clients-flow adapter_"

![emacs](https://user-images.githubusercontent.com/28247396/84122989-dd9a2e80-aa56-11ea-97ce-bca649963c09.png)

**_To Reproduce:_** 

- Used the packagae  [https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el](url)  to reproduce the issue
- Open a new buffer test.js

**_Expected Behaviour:_** lsp-server does not start, lsp-log says the language-server is present on the path

![lsp_log](https://user-images.githubusercontent.com/28247396/84123116-06babf00-aa57-11ea-9963-54cfa569a5cb.png)

_NOTE:_  Everything works fine in a _typescript_ buffer

**_Language Server:_** (_typescript-language-server_)
**_OS:_** 5.6.15-1-MANJARO 
**_version:_** _emacs 26.3_

**Comment by am-1t** [comment]
> Can you test with [yyoncho@3d0f953](https://github.com/yyoncho/lsp-mode/commit/3d0f9534ab54c0c4c2054f44928e9c21bb1672e5) ?

It produces the same error

**Comment by tom10x** [comment]
@yyoncho I run into this every time I make a new JavaScript buffer. It seems to me the problem is (insert-file-contents file-name). There needs to be check that the file exists first, right?

**Comment by yyoncho** [comment]
> @yyoncho I run into this every time I make a new JavaScript buffer. It seems to me the problem is (insert-file-contents file-name). There needs to be check that the file exists first, right?

Yes, it should but I cannot understand why `https://github.com/yyoncho/lsp-mode/commit/3d0f9534ab54c0c4c2054f44928e9c21bb1672e5` is not fixing it.

**Comment by tom10x** [comment]
@yyoncho Sorry, my bad, I've tested your fix now and it does work for me (with Emacs 27.0.90). 

Curious if there's difference in how we tested this @am-1t . I downloaded https://github.com/yyoncho/lsp-mode/archive/flowjs.zip and set load-path to the use-package expression (see below) and restarted Emacs. Now I can C-x C-f whatever.js without issue.

(use-package lsp-mode
  :load-path "/home/thomas/tmp/test/lsp-mode-flowjs"
 ;; ...
)

**Comment by yyoncho** [comment]
@tom10x thank you, I pushed that fix. Please reopen if the issue is still present and provide the new error callstack.

**Comment by am-1t** [comment]
> @yyoncho Sorry, my bad, I've tested your fix now and it does work for me (with Emacs 27.0.90).
> 
> Curious if there's difference in how we tested this @am-1t . I downloaded https://github.com/yyoncho/lsp-mode/archive/flowjs.zip and set load-path to the use-package expression (see below) and restarted Emacs. Now I can C-x C-f whatever.js without issue.
> 
> (use-package lsp-mode
> :load-path "/home/thomas/tmp/test/lsp-mode-flowjs"
> ;; ...
> )

I copied the fix in lsp-clients.el

**Comment by am-1t** [comment]
@yyoncho Sorry, it is working now with the "typescript-language-server".

**Comment by yyoncho** [comment]
Thank you.
