### ISSUE TITLE
We should forget diagnostics after file is modified

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#1792]
not doing that is causing stale diagnostics until the new one are received.

**Comment by innerout** [comment]
I have been tackling on this behavior lately with ccls and I need to make an extra modification in the buffer and then save it to make the errors disappear. I think if this is solved it will greatly improve the experience of flycheck users.

**Comment by yyoncho** [comment]
> I have been tackling on this behavior lately with ccls and I need to make an extra modification in the buffer and then save it to make the errors disappear. I think if this is solved it will greatly improve the experience of flycheck users.

This should not happen with the latest lsp-mode. The errors should either disappear after 0.5 seconds after modification or 0.5 after they are received from the server. Unless you have removed on idle from flycheck.

**Comment by innerout** [comment]
How can I verify the state of flycheck's on idle option you mention? Is there an lsp-mode option that could possibly disable it?

**Comment by yyoncho** [comment]
Check if flycheck-check-syntax-automatically has idle-change. Also, doing M-x flycheck-buffer will force lsp-mode to report the latest error reported from the server.

**Comment by innerout** [comment]
You were right, in my configuration I had the snippet below and after removing it everything works as it should.
 ```elisp
 (setq flycheck-check-syntax-automatically '(mode-enabled save))
```

**Comment by yyoncho** [comment]
I will take a look.

**Comment by scturtle** [comment]
> Check if flycheck-check-syntax-automatically has idle-change.

https://github.com/emacs-lsp/lsp-mode/blob/92b3b75268a602dcc02f8eec1c333f4551f09539/lsp-mode.el#L8290-L8293

Why `idle-change` must be checked here? There are users like me only wish to see diagnostics only after saved.

**Comment by yyoncho** [comment]
> > Check if flycheck-check-syntax-automatically has idle-change.
> 
> https://github.com/emacs-lsp/lsp-mode/blob/92b3b75268a602dcc02f8eec1c333f4551f09539/lsp-mode.el#L8290-L8293
> 
> Why `idle-change` must be checked here? There are users like me wish to see diagnostics only after saved.

That is why this check is here - do not refresh diagnostics on. But there indeed, there is a bug here. We should also update the diagnostics if the buffer is saved and user wants to update diags on save. This is what is causing your issues.
