### ISSUE TITLE
scala-mode disappeared from registered modes list 

### ISSUE THREAD

**Issue by kostafey** [emacs-lsp/lsp-mode#1800]
```
LSP :: There are no language servers supporting current mode scala-mode registered with `lsp-mode'.
```

`lsp-mode-20200614.1051`.

**Comment by yyoncho** [comment]
metals integration was moved into separate repo: https://github.com/emacs-lsp/lsp-metals

**Comment by kostafey** [comment]
@yyoncho, thank you.

**Comment by yyoncho** [comment]
For future reference, we are mentioning all breaking changes in the changelog - https://github.com/emacs-lsp/lsp-mode/blob/master/CHANGELOG.org
