### ISSUE TITLE
directory ancestry checking doesn't detect distinct directories

### ISSUE THREAD

**Issue by danp** [emacs-lsp/lsp-mode#1804]
**Describe the bug**
Using lsp-mode-20200615.1829 for editing Go. I have two directories involved, call them:

```
~/src/hello
~/src/hello-there
```

Each are distinct Go-wise, having their own `go.mod` files. When opening a file in `~/src/hello-there`, I was not prompted to import the directory as a project root. I was prompted about whether to watch all files in `~/src/hello` which was surprising.

I believe this is because the [directory ancestry checking](https://github.com/emacs-lsp/lsp-mode/blob/bf2afe653a6cffcdbf336065d2c7200853feab36/lsp-mode.el#L1228) considers `~/src/hello-there` to be an ancestor of `~/src/hello`, even though they are at the same level under `~/src`.

Once I hand-edited `~/.emacs.d/.lsp-session-v1` to have entries for each directory, things worked as expected.

**To Reproduce**
Create two Go projects/modules, one in `~/src/hello` and another in `~/src/hello-there`. Probably have to open something in `~/src/hello` first so it gets added to the session list. After that, trying to open something in `~/src/hello-there` will use a session for `~/src/hello`.

**Expected behavior**
I expect `~/src/hello-there` to be considered a distinct project/directory since it's under `~/src` alongside `~/src/hello`.

**Which Language Server did you use**
gopls

**OS**
macOS 10.15.5 (Catalina)

**Comment by danp** [comment]
Maybe related to https://github.com/emacs-lsp/lsp-mode/pull/1696?

**Comment by kiennq** [comment]
It seems that even `f-ancestor-of?` is suffered from this problem.

**Comment by danp** [comment]
Upgraded to lsp-mode-20200616.624 and verified this is fixed. Thank you!
