### ISSUE TITLE
Discrepancies between VSCode/Sublime and lsp-mode when using terraform-ls: incorrect indentation of nested blocks, extra schema stuff showing up during autocompletion

### ISSUE THREAD

**Issue by amasover** [emacs-lsp/lsp-mode#1805]
See [the issue I previously opened on terraform-ls](https://github.com/hashicorp/terraform-ls/issues/162).

I asked about this in #lsp-mode gitter and @yyoncho suggested that I open an issue for tracking purposes. I'm not sure if it's necessarily clear yet whether this should be fixed on the client or the server. Yyoncho suggested that:

> server authors would assume [this] to be correct - what vscode does, not what the spec says

Also seems that whatever way VSCode is handling this, Sublime Text seems to handle it in the same way.

**Describe the bug**

Essentially, (nested) autocompleted nested blocks do not get indented. The block itself has some indent information being returned from the language server, but when autocompleting a nested block, it is placed in the editor as if it were not nested. Example:

```hcl
resource "aws_appmesh_mesh" "test" {
  spec {
  egress_filter {
  0
}
}
}
```

The expected behavior would be to indent something like this:

```hcl
resource "aws_appmesh_mesh" "test" {
  spec {
    egress_filter {
      0
    }
  }
}
```

Also, this may be related. I'm just noticing this now that I've fired up VSCode for testing, but there's another discrepancy in the way that lsp-mode handles things. When I start typing `resource` in VSCode and autocomplete it, the resource block looks something like this:

```hcl
resource "" "name" {
  
}
```

And the cursor is placed inside the "" for you to type the resource name. In lsp-mode, it's autocompleted like this:

```hcl
resource "1" "name" {
  3
}
```

I believe the `1` and the `3` are coming from the number of required items in that part of the schema. You can see some of that above in `egress_filter`.

**To Reproduce**
Minimal project that I've been using for testing:

https://github.com/gruntwork-io/intro-to-terraform/tree/master/database

You will need to have terraform binary installed and on your path. You will also need to do a `terraform init` inside of the `database` folder.

Note: you may need to open the workspace at the level of `database` rather than top level `intro-to-terraform` (especially in VSCode, I believe in lsp-mode it will prompt you for which workspace to import). This is because currently the language server assumes that the top level of your workspace is the base level of the module. However, `intro-to-terraform` includes multiple modules.

**Which Language Server did you use**
This is in the new [terraform-ls](https://github.com/hashicorp/terraform-ls) server, which [hashicorp has started developing](https://www.hashicorp.com/blog/supporting-the-hashicorp-terraform-extension-for-visual-studio-code/) rather than Julio Sueiras's [terraform-lsp](https://github.com/juliosueiras/terraform-lsp) which lsp-mode uses by default.

**OS**
Arch Linux

**Error callstack**
Log output from the language server running both in VSCode and lsp-mode.

VSCode log:
https://gist.github.com/amasover/507b165beee1639f3c922492a8dfb6fd

lsp-mode log:
https://gist.github.com/amasover/ed2ba0c211bb84cc612f2acc21c79933

**Comment by yyoncho** [comment]
@amasover can you test with https://github.com/emacs-lsp/lsp-mode/pull/1935?

**Comment by amasover** [comment]
Yes, that has fixed the indentation problem! Thanks so much @yyoncho 

I think there's still a few differences between how VSCode and Emacs w/ lsp-mode handle things though. One of them is the example I mentioned above with the "1" and "3" being inserted:

```hcl
resource "1" "name" {
  3
}
```

There's a few other differences as well I think. VSCode seems to have a little more information in the autocomplete pop-up (e.g., `container` is a list and the minimum is 1). VSCode also seems to do a better job of placing the cursor during autocomplete (might be an issue with company-lsp?).
![vscode 2020-07-20 16-28](https://user-images.githubusercontent.com/484819/87992874-67053d80-caa6-11ea-8464-8815d5cec4d7.gif)
Lsp-mode on the other hand is putting some of the schema information into the autocompleted snippet, which is arguably a bit unintuitive. I'm assuming the "1" and the "3" are the number of required fields, but in Terraform I don't think it makes much sense for that "1" to be in the "resource type" field (where I type `azurerm_resource_group`), since it's always required.

The order of autocomplete on the `resource "1" "test" {` line seems a bit off too. As I tab through the completion, I'm filling out the "name" field first, and the "resource type" field second. Finally, when I try to complete `name = "value"`, it seems that `"value"` isn't automatically replaced, and I have to delete it first.
![emacs 2020-07-20 16-26](https://user-images.githubusercontent.com/484819/87992884-69679780-caa6-11ea-8931-ff0a9ff5826f.gif)

These are probably minor complaints. But I wonder if/how they should be resolved. Perhaps I should make another issue to track?

**Comment by yyoncho** [comment]
We are using yasnippet to expand the snippets and the differences are there. Can you provide the completion log (as described in bug template) for that particular completion? Also, do not use company-lsp it is no longer supported. Are you switching from insert->normal state during snippets navigation?

> There's a few other differences as well I think. VSCode seems to have a little more information in the autocomplete pop-up (e.g., container is a list and the minimum is 1). 

Please provide screenshots.
