### ISSUE TITLE
[Feature] Create setup wizard for lsp-mode

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#1813]
The wizard will be on by default and it will target the users that do not use
preconfigured frameworks(e. g. spacemacs).

Here are some thoughts/ideas about it.

1. The wizard could be either turned off or have a status which is like `run the
wizard again if lsp-mode gets a new feature`. ATM when we add a new feature we
have 2 options. Either to have it on by default which will irritate the users
that don't like it or not enable it by default which will pretty much make the
feature undiscoverable. With the proposed approach, when a new feature is added,
lsp-mode will show a dialog like "Do you want to enable semantic highlights by
default?".

2. The wizard will list features of lsp-mode and ask the user to select whether
   to keep them on or off.
3. The wizard will ask the user whether he wants to install packages like lsp-treemacs, helm-lsp, lsp-ivy.   
4. The wizard will ask if the user wants to install extenal client
   configurations like lsp-dart, lsp-java.
5. The wizard will install also the major mode if the major mode is not present
6. The wizard will have the option to skip it on the first step.

**Comment by ericdallo** [comment]
A really good idea of feature.
How can we persist that the user chose to opt-in some features? Would we need to check each feature checking if it's enabled via `defcustom` or if it was persisted on user emacs-dir via wizard?

**Comment by yyoncho** [comment]
> How can we persist that the user chose to opt-in some features?

A potential solution is: each of the questions has id/key. We keep a variable, something like `lsp-wizard-answered-questions`. On  `M-x lsp` startup, we check if all questions are answered. If not - we show the wizard. After we set the values we do (custom-save-all) which will write the changed settings in user's config.

**Comment by kurnevsky** [comment]
Sounds like it can be a separate package not tied up with lsp-mode.

**Comment by Compro-Prasad** [comment]
> Sounds like it can be a separate generic package not tied up with lsp-mode.

It does need to be with default `lsp-mode` package so that people coming from VS Code don't find it unpleasing of it doing so less. Sure, its kind of against the customizing facility provided by Emacs but it will definitely boost user experience. I have been thinking of something similar for so long but didn't actually do anything.

The first question should be: **Do you want suggestions from lsp-mode?** . If a person answers no, `lsp-mode` won't interrupt in any way unless invoked for a specific functionality. Else, it will start asking other questions and put up a default setup ready for the user automatically.

**Comment by sivark** [comment]
One possible solution is to create a new wrapper package called `lsp-mode-magic` (also a pun on wizard) whose role would be to 1. Ensure the `lsp-mode` package is made available 2. Set configuation for lsp-mode.

It shouldn't matter for `lsp-mode` how the configuration is generated, and state related to opt-in/opt-out when to nudge, etc. can be nicely isolated outside the `lsp-mode` package. That way, "experts" who choose `lsp-mode` (or opinionated emacs distributions which preconfigure lsp for users) need not worry about being bothered by a wizard, and newbies who want to bootstrap can happily start with the magic package.

**Comment by yyoncho** [comment]
@sivark this is definitely one way to do it but I tend to be against introducing a new package basically with the same concern as the concern behind this issue - people do not read/re-read the readme. I have seen stale artefacts in users' configs that are from 2-3 years ago. There are a lot of people that even don't update their packages and they do update them only if they have lost their emacs.d for some reason.

I believe that this wizard might be useful even for expert users or at least I wish that other packages that I use but I don't want to study in details have such a wizard. But in any case, we should have the option "Skip and dont ask me again" which hopefully will solve the issue with the expert users or at least they won't complain about that a lot.

**Comment by shackra** [comment]
>     3\. The wizard will ask the user whether he wants to install packages like lsp-treemacs, helm-lsp, lsp-ivy.

how is going this to be done? it seems that we are doing wild assumptions here, for instance, if the user is actually using something like `straight.el` the sentence for installing lsp-treemacs should be part explicitly of the initialization of the Emacs' user configuration

**Comment by nbfalcon** [comment]
This could be done using the customize interface, so that we don't have to tie `lsp-mode` to that feature. However, I don't see why new users couldn't just use a framework instead?

**Comment by yyoncho** [comment]
I am marking this as rejected. ATM it does not seem realisting to have it fixed. lsp-gitpod will fill some of the gaps.
