### ISSUE TITLE
[doc] Duplicate Entries of texlab/latex LS in webpage 

### ISSUE THREAD

**Issue by innerout** [emacs-lsp/lsp-mode#1814]
I was checking the [languages](https://emacs-lsp.github.io/lsp-mode/page/languages/) section in the page of lsp-mode and I saw there are 2 duplicate entries in the supported languages list. 

1. TeX, LaTeX, etc (texlab)
2. TeX, LaTeX, etc (latex)

Probably the second entry should be removed.

**Comment by ericdallo** [comment]
Fixed it [here](https://github.com/emacs-lsp/lsp-mode/commit/3b6f2d150000431ea71ae981796ff624c09594f8).
Thank you!

**Comment by ROCKTAKEY** [comment]
@ericdallo ( cc @yyoncho )
Hi!
It was not duplicated, because both lsp-mode native and my package [lsp-latex](https://github.com/ROCKTAKEY/lsp-latex) support texlab.

**Comment by ericdallo** [comment]
I got confused so, maybe we should just add your removed client config [here](https://github.com/emacs-lsp/lsp-mode/blob/master/docs/lsp-clients.json#L410-L417)?

**Comment by ROCKTAKEY** [comment]
@ericdallo Like the section deleted on this [commit](https://github.com/emacs-lsp/lsp-mode/commit/3b6f2d150000431ea71ae981796ff624c09594f8#diff-aded05649f01fc0edab82b17f9de2c27L400). 
URL and name of client is here.

**Comment by ROCKTAKEY** [comment]
In addition, some configurations are available, so I would like to add doc about that, if possible.

**Comment by ericdallo** [comment]
You can create a file to add custom configurations like we do fo `lsp-rust.el` [here](https://github.com/emacs-lsp/lsp-mode/blob/master/docs/page/lsp-rust.md).
@ROCKTAKEY do you mind opening a PR fixing and adding this new info?
You can test the webpage local with `make local-webpace`

**Comment by ROCKTAKEY** [comment]
@ericdallo 
OK, I will make it.
As far as I investigated, some clients, such as [bash](https://emacs-lsp.github.io/lsp-mode/page/lsp-bash/), have "available configurations" section, but there is no file like "lsp-bash.md" in doc/. I think default pages are generated from [lsp-clients.json](https://github.com/emacs-lsp/lsp-mode/blob/master/docs/lsp-clients.json), but which is "lsp-bash.md" made from? lsp-clients.json has no data of "available configurations."

**Comment by ericdallo** [comment]
@ROCKTAKEY We auto-generate the docs from with this script: https://github.com/emacs-lsp/lsp-mode/blob/master/docs/lsp-doc.el#L125-L130
ATM we only have `lsp-rust` that wants to write custom documentation, that's why we have the `lsp-rust.md` file.
You will need to create the `lsp-latex.md` file or something like that and customizes as you want

**Comment by ROCKTAKEY** [comment]
@ericdallo Thanks for your infomation.
It seem to get configurations from customization variables. Because it is annoying (and maybe not welcomed) to add installer of lsp-latex.el to the doc builder, I will write lsp-latex.md and make PR later, as you said.

**Comment by ericdallo** [comment]
Yes, thank you!
