### ISSUE TITLE
lsp-file-watch-ignored patterns seem wrong

### ISSUE THREAD

**Issue by codygman** [emacs-lsp/lsp-mode#1815]
`lsp-file-watch-ignored` assumes filepaths are only directory names meaning that the ignores don't actually work. Probably related to #713 .

Now I'm tired and could have made a mistake, but I verified my hunch here with this code:

```elisp
(setq lsp-file-watch-ignored
      '("[/\\\\]\\.git" ;; original had $ at the end, but directory-files-recursively returns full filepaths so nothing ever got ignored
        ))

(write-region
 (string-join (seq-filter
               (lambda (file-name) (not (lsp--string-match-any (lsp-file-watch-ignored) file-name)))
                (directory-files-recursively  "." ".*" t nil nil))
  "\n") nil "directories.txt")
````

**Comment by yyoncho** [comment]
> `lsp-file-watch-ignored` assumes filepaths are only directory names meaning that the ignores don't actually work. Probably related to #713 .

The idea is that you skip the whole directory and do not process it recursively.

**Comment by yyoncho** [comment]
Closing, please reopen if you find the previous comment to be wrong.

**Comment by codygman** [comment]
I'm pretty sure something is wrong here:

![Screenshot_2020-07-29_16-22-48](https://user-images.githubusercontent.com/225847/88855244-2ef1af00-d1b8-11ea-8608-350c18b9430d.png)


lsp-ui: 7d53264
lsp-haskell: 17d7d4c6615b5e6c7442828720730bfeda644af8
lsp-mode: 0131f1f4c9e7823955c3b1f80881fcd7c2eaa551
