### ISSUE TITLE
Is there a way to go to an import module file?

### ISSUE THREAD

**Issue by aang7** [emacs-lsp/lsp-mode#1818]
Please ask your questions at https://gitter.im/emacs-lsp/lsp-mode

for example, I have this import statament
![image](https://user-images.githubusercontent.com/11984605/85098836-66386d80-b1c1-11ea-9a8a-5faaa7a0c31d.png)

and the minibuffer says the module path:
![image](https://user-images.githubusercontent.com/11984605/85098930-b283ad80-b1c1-11ea-9d5d-90228bfecd6c.png)

How can I jump to that file as I can in vs code just pressing CTRL + Right click?

**Comment by yyoncho** [comment]
And did you try the same here? (I think it is left click).

**Comment by aang7** [comment]
> And did you try the same here? (I think it is left click).

Indeed I tried before and didn't work but now works! jaja thank you and sorry it's correct, it's left click.
