### ISSUE TITLE
Feature request: extract signature from multi-line onHover responses for lsp-go

### ISSUE THREAD

**Issue by exp2ipi** [emacs-lsp/lsp-mode#1828]
Current behavior when `lsp-eldoc-render-all` is `nil` is to display the first line of the onHover response.  Unfortunately, most of the time (at least in the current version of gopls), the first line does not contain the signature (and in fact frequently contains low-value information, such as an external link to documentation). It would be good to implement something like what was done for clangd in https://github.com/emacs-lsp/lsp-mode/pull/1635, at least until there's more movement on https://github.com/microsoft/language-server-protocol/issues/772

**Comment by yyoncho** [comment]
Have you tried if customizing lsp-gopls-hover-kind will fit your needs?

**Comment by scturtle** [comment]
You can write your custom `lsp-clients-extract-signature-on-hover` like this one in https://github.com/emacs-lsp/lsp-mode/pull/1740. It can be put in your config files.

**Comment by exp2ipi** [comment]
> Have you tried if customizing lsp-gopls-hover-kind will fit your needs?

Thank you, `(setq lsp-gopls-hover-kind "SingleLine")` does the trick (although this settings unfortunately seems to suffer from broken fontification).

I think an ideal solution would be to write a custom extractor as suggested by @scturtle and ensure it only applies to the echo area. This has the benefit that the signature information always appears, while more detailed information can be shown in an lsp-ui pop-up (which the user may choose to toggle on and off).

**Comment by yyoncho** [comment]
> I think an ideal solution would be to write a custom extractor as suggested by @scturtle and ensure it only applies to the echo area. This has the benefit that the signature information always appears, while more detailed information can be shown in an lsp-ui pop-up (which the user may choose to toggle on and off).

In lsp world, the client should not have that kind of logic. As a side note, there is discussion in protocol repo have two mehods. One for detailed info and one for the minimal one. 

I am closing the bug based on the previous comment(please reopen if I am missing something).
