### ISSUE TITLE
rust-analyzer: update runnables request

### ISSUE THREAD

**Issue by brotzeit** [emacs-lsp/lsp-mode#1833]
The name has changed: https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/rust-analyzer/src/lsp_ext.rs#L129

**Comment by flodiebold** [comment]
It's not just the name, but also the structure (that's why I didn't do it immediately, I think it's not a completely trivial change).

**Comment by jerrypnz** [comment]
I'm also interested in this feature and currently working on it. Will create a PR once it's ready.
