### ISSUE TITLE
Potential race condition in `lsp--text-document-hover-string'

### ISSUE THREAD

**Issue by terlar** [emacs-lsp/lsp-mode#184]
When I use [lsp-java](https://github.com/emacs-lsp/lsp-java) I get errors such as:

```
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  gethash("contents" nil)
  lsp--text-document-hover-string()
  lsp--on-hover()
  eldoc-print-current-symbol-info()
  #f(compiled-function () #<bytecode 0x2af755>)()
  apply(#f(compiled-function () #<bytecode 0x2af755>) nil)
  timer-event-handler([t 0 0 500000 nil #f(compiled-function () #<bytecode 0x2af755>) nil idle 0])
```

The reason that I believe this is a race condition / async problem is that when I run `debug-on-entry` on the `lsp--text-document-hover-string` and step through it works every time and gets the proper string from the language server.

There are two slightly related things I want to mention while we are on this subject, I guess it should have some kind of handling if the result would be nil, so you don't end up with an error.

Another related issue to the documentation hover string is that sometimes language servers return empty strings, then the documentation will display the empty string. This is not a big issue when you display the docs inside the status bar, since you won't notice it, but both for slight performance benefits (no update) and if you want to use packages that display the documentation inline (e.g. [eldoc-overlay-mode](https://github.com/stardiviner/eldoc-overlay-mode)).

Thank you for a great package, very useful.

JDT version: 0.9.0.201711151401

**Comment by terlar** [comment]
This seems to be resolved at this point. Although have some other errors, but might be specific to the `lsp-java` mode. I currently don't get any documentation, but instead a nice log line as such:

```
Nov 25, 2017 7:07:58 PM >> document/codeAction
Nov 25, 2017 7:07:58 PM >> document/documentHighlight
Nov 25, 2017 7:07:58 PM >> document/codeAction
Nov 25, 2017 7:07:58 PM >> document/hover
```

Does this come from the language server or `lsp-mode`?

**Comment by jethrokuan** [comment]
@terlar I get these log lines too, did you manage to find a fix?

**Comment by terlar** [comment]
@jethrokuan Nope, those last errors I mentioned I never found a solution for. Let me know if you find something. I haven't looked into it since then.
