### ISSUE TITLE
Performance problems with ts-ls

### ISSUE THREAD

**Issue by benwainwright** [emacs-lsp/lsp-mode#1843]
**Describe the bug**
Typescript performance problems. lsp-mode freezes periodically as I'm typing. It *seems* (thought I'm not certain) to be related to bringing up the completion popup.

**To Reproduce**
Create a minimal typescript project (I literally just started a new one), start typing in any file

**Which Language Server did you use**
ts-ls

**OS**
MacOS 10.14.6

**Logs**
* Tsserver log including **lsp-print-performance t**: https://gist.github.com/benwainwright/b5cda8aa1544be0a2f08be6546bc2395
* Profiler report: https://gist.github.com/benwainwright/1b1075fc342d9a8b023a80f270e2a7a2

**Comment by kiennq** [comment]
Look like you're running with `lsp-toggle-trace-io`, which can be seriously slow due to additional formatting + converting from Elisp object to pretty json presentation.
Can you turn it off and retaking the profile?

**Comment by benwainwright** [comment]
@kiennq Thanks for the super quick response!

I literally can't remember why I turned this on; was to debug something else. But... when I turn it off; everything is silky smooth again!

**Comment by artemkovalyov** [comment]
That saved me! I was debugging ESlint and forgot to switch it off. Wouldn't think it has such a huge toll on performance. In my case it was enabled like this:

```lisp
(use-package lsp-mode
  :init
  (setq lsp-keymap-prefix "s-m"
        lsp-prefer-capf t
        ;; lsp-log-io t ; enable debug log - can be a huge performance hit
        lsp-disabled-clients '(eslint)
        lsp-treemacs-sync-mode 1
        )

```
