### ISSUE TITLE
Serenata logs excessive warnings

### ISSUE THREAD

**Issue by xendk** [emacs-lsp/lsp-mode#1847]
**Describe the bug**
When using lsp-serenata in a buffer, it opens a window where it outputs a lot of:

```
Warning (lsp-mode): Unknown notification: serenata/didProgressIndexing
```
I was told to tag @Sasanidas 

**To Reproduce**

Clone https://github.com/xendk/dais/ and open the `dais` file. It should start spamming.

**Expected behavior**

It not opening a window with warnings

**Which Language Server did you use**
lsp-serenata

**OS**
Linux

**Comment by ericdallo** [comment]
@Sasanidas I think we should implement the notification like [here](https://github.com/emacs-lsp/lsp-dart/blob/master/lsp-dart.el#L111-L114) even doing nothing just to avoid the warnings

**Comment by xendk** [comment]
Looked it up, it seems quite useful as it shows progress in bulk scanning: https://gitlab.com/Serenata/Serenata/-/wikis/Language-Server-Protocol-Support-Table#serenatadidprogressindexing

Displaying the progress somewhere would be handy.

**Comment by Sasanidas** [comment]
> Looked it up, it seems quite useful as it shows progress in bulk scanning: https://gitlab.com/Serenata/Serenata/-/wikis/Language-Server-Protocol-Support-Table#serenatadidprogressindexing
> 
> Displaying the progress somewhere would be handy.

Ok, seems like an interesting feature, I'll try to fix the issue and add it soon.

Thank you!
