### ISSUE TITLE
out of sync errors

### ISSUE THREAD

**Issue by fuzunspm** [emacs-lsp/lsp-mode#1850]
**Describe the bug**
Actually it's hard to explain but whenever i save my file lsp mode displays error like i'm at half of current line. If i create a blank line and save it again then it catches up and clears all non-sense errors

**Which Language Server did you use**
All modes i'm using for  python,js, typescript

**OS**
both macOS and Linux (arch linux)

**Error callstack**
No error

It's better to describe with images..

**Image 1. It thinks I'm still on test as variable name but couldn't see complete name of it**

![lsp1](https://user-images.githubusercontent.com/12132746/85945469-9bbe2300-b946-11ea-8fa4-608e9e1c445c.png)

**Image 2 after re-saving again by making a blank line**

![lps2](https://user-images.githubusercontent.com/12132746/85945472-9e207d00-b946-11ea-8bc3-dbab704e1b33.png)

**Comment by yyoncho** [comment]
Can you test if this is happening with `emacs -q -l lsp-start-plain.el` where lsp-start-plain.el can be downloaded from https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el?

**Comment by fuzunspm** [comment]
No it's not happening with lsp-start-plain

**Comment by yyoncho** [comment]
Closing based on the preivous comment. If you are using your personal config please revert lsp-mode/flycheck settings and reapply them to find out which one is introducing this state. My guess is that you have disabled on idle checks in flycheck. If you are using distribution please report it in distribution repo.
