### ISSUE TITLE
How to turn off lsp-mode-modeline-code-actions-mode?

### ISSUE THREAD

**Issue by ianpan870102** [emacs-lsp/lsp-mode#1851]
I have already included this line `(setq lsp-modeline-code-actions-mode nil)` in my `init.el`, and yet lsp-mode-modeline-code-actions-mode is still enabled in my C++ lsp buffer. How can I turn it off by default? 
I even tried this: `(add-hook 'lsp-mode-hook #'(lambda () (lsp-modeline-code-actions-mode -1)))` but to no success.

**Comment by kiennq** [comment]
You need to setup `lsp-modeline-code-actions-enable` to `nil` instead.

**Comment by ianpan870102** [comment]
> You need to setup lsp-modeline-code-actions-enable to nil instead.

Thanks man, that worked! I'll close the issue now.
I wish there were a curated list of lsp-mode's "extra" functionalities that people could choose to enable or disable. As many users have debated on Reddit, people have polarising opinions about lsp-mode's approach to enable everything by default and requires users to turn them off one by one.

For instance, most of my lsp configurations are turning things off:

```emacs-lisp
(setq lsp-diagnostic-package :none)   ; disable flycheck-lsp for most modes
(setq lsp-enable-symbol-highlighting nil)
(setq lsp-enable-on-type-formatting nil)
(setq lsp-signature-auto-activate nil)
(setq lsp-modeline-code-actions-enable nil)
(setq lsp-enable-folding nil)
(setq lsp-enable-snippet nil)
(setq lsp-enable-completion-at-point nil)
```
