### ISSUE TITLE
Regression in lsp-capf after 70ea28f56eeff62f229aca6b469b60c1fd94307d

### ISSUE THREAD

**Issue by theothornhill** [emacs-lsp/lsp-mode#1852]
After 70ea28f56eeff62f229aca6b469b60c1fd94307d completion does not work correctly, at least in elm files. More specifically, company does not show completions, and throws an error.

When completing with "mai" as part of "main", I get the following error:

    Company: backend company-capf error "Wrong type argument: characterp, nil" with args (candidates mai)

The simplest way to reproduce this is:
`git clone https://github.com/rtfeldman/elm-spa-example.git`

Then if `elm-language-server` isn't installed:
`npm i -g @elm-tooling/elm-language-server`

Then open any file and start typing.

With `toggle-debug-on-error`, `lsp--capf-guess-prefix` shows up as the culprit.

Also, when reverting to the commit before the mentioned commit, everything works again.

It works fine in Csharp though.

**Comment by kiennq** [comment]
@theothornhill Can you check with the PR?

**Comment by theothornhill** [comment]
> Can you check with the PR?

Works perfectly!
Thanks for the quick fix :-)
