### ISSUE TITLE
Icons for headerline breadcrumb are missing if lsp-treemacs is not installed

### ISSUE THREAD

**Issue by astenman** [emacs-lsp/lsp-mode#1858]
**Describe the bug**
Icons for headerline breadcrumb are missing if lsp-treemacs is not installed

**To Reproduce**
Use latest lsp-mode without lsp-treemacs
![breadcrumb](https://user-images.githubusercontent.com/43724994/86119864-8aeee800-bad3-11ea-9277-db6ed2ca183d.png)

**Expected behavior**
Something else than the empty boxes should be shown

**Which Language Server did you use**
PHP Intelephense

**OS**
Windows 10

**Comment by ericdallo** [comment]
Probably the check, if `lsp-treemacs` is installed, is incorrect, I'll take a look later today, thanks for the report!

**Comment by yyoncho** [comment]
> Probably the check if `lsp-treemacs` is installed,

we should fallback gracefully if lsp-treemacs is not installed.

**Comment by ericdallo** [comment]
Weird, that's already happening @yyoncho [here](https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el#L2061-L2064), when returning nil, we just don't use the icon

**Comment by yyoncho** [comment]
@astenman are you sure that you don't have lsp-treemacs installed? Because the issue might be caused by your emacs compiled without png support.

**Comment by astenman** [comment]
Hello,

It seems that I have lsp-treemacs installed after all (although I do not
use it). I have png-support compiled in. But also imagemagick, which might
cause problems in this case.

Is it possible to force the use of all-the-icons instead of png?

Thank you for the good work!

Kind regards
/Anders

**Comment by yyoncho** [comment]
Treemacs supports themes but AFAIK treemacs does not come with all-the-icons-theme OOTB. Doom emacs has such theme but we have to implement it in lsp-treemacs as well. There is this: https://github.com/emacs-lsp/lsp-treemacs/issues/18 

Meanwhile, to diagnose the issue, can you check what are the paths when you do 

```
(treemacs-get-icon-value (lsp-treemacs-symbol-kind->icon 6))
```

Also, are you using native compilation? I think that it was causing some issues with icon paths.

**Comment by ericdallo** [comment]
This does not fix the problem, but it's somehow related: https://github.com/emacs-lsp/lsp-mode/pull/1860

**Comment by astenman** [comment]
Recompiling emacs without ImageMagick solved the problem.

**Comment by fosskers** [comment]
Sorry to resurrect an old issue, but this does still seem to be a problem. If `lsp-treemacs` is not installed, icons don't appear.

For extra context, I'm on Doom, and adding `(treemacs +lsp)` makes icons appear.

**Comment by yyoncho** [comment]
@fosskers we use lsp-treemacs if it is present. Then we fallback to all-the-icons. If you have installed all-the-icons make sure that you have installed the fonts as well. If neither is installed we don't display icons.

**Comment by fosskers** [comment]
Hm, I'm on `master` of both `lsp-mode` and `all-the-icons`, but the icons still don't appear. I removed `lsp-treemacs` completely to be sure.

**Comment by yyoncho** [comment]
Have you installed all-the-icons fonts? @ericdallo - can you confirm that all-the-icons work on doom?

**Comment by fosskers** [comment]
I have them installed both via `all-the-icons-install-fonts` and via my package manager just in case.

**Comment by ericdallo** [comment]
@yyoncho I use all-the-icons on doom and it works pretty well with breadcrumb 🤔

**Comment by fosskers** [comment]
> @yyoncho I use all-the-icons on doom and it works pretty well with breadcrumb thinking

Do you have `(treemacs +lsp)` on or off?

**Comment by ericdallo** [comment]
On: https://github.com/ericdallo/dotfiles/blob/master/.doom.d/init.el#L42

**Comment by fosskers** [comment]
Then that's what does it. I have you have it off, the icons won't appear, even though there is supposed to be a fallback (see above).

**Comment by MintSoup** [comment]
I'm having the same problem. Installing lsp-treemacs fixes it, but it doesn't work with just all-the-icons

**Comment by memeplex** [comment]
I've created a more specific issue for "icons showing but aren't all-the-icons": https://github.com/emacs-lsp/lsp-treemacs/issues/115

**Comment by timjstewart1024** [comment]
`M-x all-the-icons-install-fonts` and restarting Emacs fixed it for me.  Hope this helps.

**Comment by fosskers** [comment]
That commands downloads the fonts successfully but my headerline is still iconless.

**Comment by umgefahren** [comment]
Did you have eventual success?

**Comment by fosskers** [comment]
Not here, no.

**Comment by umgefahren** [comment]
Funny enough, it doesn't even work for me if I have lsp-treemacs installed. I use emacs-mac with imagemagick (it doesn't work without it either) and I don't get them to show up at all. I tried unpinning lsp-treemacs as well as lsp-mode, still nothing. Running

> `(treemacs-get-icon-value (lsp-treemacs-symbol-kind->icon 6))`

even shows something, so the problem is not with getting the icons.
