### ISSUE TITLE
Server jsts-ls:2849 status:starting exited with status exit. Do you want to restart it? (y or n)

### ISSUE THREAD

**Issue by petsgre** [emacs-lsp/lsp-mode#1862]
Server jsts-ls:2849 status:starting exited with status exit. Do you want to restart it? (y or n)

When a press 'y', this display again ,until i select 'n'

**Comment by ericdallo** [comment]
@petsgre Can you follow [this bug report template](https://github.com/emacs-lsp/lsp-mode/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) to provide more information?

**Comment by petsgre** [comment]
sorry, i forgot i uninstall the ts language server globally,it fine now
