### ISSUE TITLE
Set lsp-enable-links to nil doesn't disable link in code.

### ISSUE THREAD

**Issue by AllenDang** [emacs-lsp/lsp-mode#1866]
**Describe the bug**
I set the lsp-enable-links to nil but link in code still remain clickable.

**To Reproduce**
Set lsp-enable-links to nil.

**Expected behavior**
Link string in code is not clickable.

**Which Language Server did you use**
lsp-golang

**OS**
macOS v10.15.15

Here is the screenshot.

![截屏2020-07-02 下午5 00 45](https://user-images.githubusercontent.com/18550/86339279-fb3d6b00-bc85-11ea-977a-82d7eca10f7e.png)

**Comment by yyoncho** [comment]
I tested this locally and it seems to be working fine. Are you sure that you have set that value before opening the buffer and starting the server?

**Comment by yyoncho** [comment]
Marking as closed. Please reopen after confirming that you still see the issue.
