### ISSUE TITLE
lsp-ui-flycheck-live-reporting is an obsolete alias of removed lsp-flycheck-live-reporting

### ISSUE THREAD

**Issue by laurynas-biveinis** [emacs-lsp/lsp-mode#1868]
**Describe the bug**
With lsp-mode 7.0, `lsp-ui-flycheck-live-reporting` is declared as an obsolete alias of `lsp-flycheck-live-reporting`. But the latter does not exist anymore.

**To Reproduce**
Source code reading

**Expected behavior**
Not sure, because it is not entirely clear what is the upgrade path from 6.3 `lsp-flycheck-live-reporting` set to `nil` to 7.0. It seems that lsp-mode now honors `flycheck-check-syntax-automatically`? Should that be the "current alias" of both `lsp-ui-flycheck-live-reporting` and `lsp-flycheck-live-reporting`?

**Comment by yyoncho** [comment]
We should remove the lsp-ui alias.

> Not sure, because it is not entirely clear what is the upgrade path from 6.3 lsp-flycheck-live-reporting set to nil to 7.0.

This is what we have now by default

> It seems that lsp-mode now honors flycheck-check-syntax-automatically?

Yes.

> Should that be the "current alias" of both lsp-ui-flycheck-live-reporting and lsp-flycheck-live-reporting?

No, because they have different semantics.

**Comment by yyoncho** [comment]
Fixed with https://github.com/emacs-lsp/lsp-ui/commit/6b80c6c199929b0410c5270b62f6ff410b34bfca
