### ISSUE TITLE
Feature request: make vscode-eslint automatically installable

### ISSUE THREAD

**Issue by justinabrahms** [emacs-lsp/lsp-mode#1870]
Today, to make lsp-eslint work, you have to install vscode-eslint out of band. It would be much easier if that automatically installed.

This isn't easily possible to do via npm, until https://github.com/microsoft/vscode-eslint/issues/1003 lands.

When complete, we would expect folks to be prompted to see if they want to install the plugin, much like the typescript-javascript LSP does.

**Comment by yyoncho** [comment]
Here we have 2 options:

1. Wait for npm package as you suggested.
2. Move dap-mode - vscode marketplace integration in lsp-mode. This way we will be able to download the vsix package.

**Comment by danielpza** [comment]
I made a PR for vscode-eslint for a new package https://github.com/microsoft/vscode-eslint/pull/1053, hopefully it will be merged.

**Comment by yyoncho** [comment]
I created an automatic download function based on vscode package. Once they provide NPM package we will switch to it.
