### ISSUE TITLE
Support for sqls lsp server

### ISSUE THREAD

**Issue by mcraveiro** [emacs-lsp/lsp-mode#1875]
Hi LSP devs,

thanks very much for an excellent mode. I use it daily and it has changed my way of coding. I have a question / suggestion: does LSP support sqls [1]? I did a search and could find no evidence of this, but perhaps my google-fu is letting me down. If it doesn't, would you consider adding support for it? Also, it seems there already is a lsp-mssql [2]; would it be more sensible to raise this issue on that project? I don't know too much about the internals of LSP mode, I'm afraid.

Many thanks for all your contributions.

Marco

[1] https://github.com/lighttiger2505/sqls
[2] https://github.com/emacs-lsp/lsp-mssql

**Comment by yyoncho** [comment]
We have support for it: https://github.com/emacs-lsp/lsp-mode/blob/728134a2320c06d128bc5e379ee436a322086d13/lsp-sqls.el

**Comment by mcraveiro** [comment]
Aha, thanks very much @yyoncho! I shall ask the sqls devs to add a reference to LSP mode then. Cheers.
