### ISSUE TITLE
c# LSP: Viewing OmniSharp log file

### ISSUE THREAD

**Issue by mcraveiro** [emacs-lsp/lsp-mode#1876]
Hi LSP devs,

Thanks for a great mode. As per conversation in the gitter channel:

> I've been using it on windows for c# and it works quite well. One question though, is there a way to see the OmniSharp log? I can see the log of messages and replies sent to OmniSharp, but I haven't found a way to see the server log itself, like I could with omnisharp-emacs. 
> 
> the problem I am trying to troubleshoot in particular is the case where I make changes to a csproj file but it seems OmniSharp does not reload the project. This was working for omnisharp-emacs so I suspect I must have broken something, but without the log its not easy to figure out what.

@yyoncho suggested that @razzmatazz may know the answer to this question.

Many thanks for all your hard work.

Marco

**Comment by razzmatazz** [comment]
Hi @mcraveiro. I believe, the log level is configurable but we don't have configuration for it in `lsp-csharp.el` (yet). I have not personally tried configuring it (or if it actually works) but..

The code for this is there:
- https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.LanguageServerProtocol/LanguageServerHost.cs#L48

And according to code here:
- https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Host/CommandLineApplication.cs#L31

It should be configurable via `--loglevel` | `-l` switch. You should try appending `-l Debug` here:
- https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-csharp.el#L245

There has been quite some changes made recently to lsp support in omnisharp-roslyn [and more are coming](https://github.com/OmniSharp/omnisharp-roslyn/pull/1815), so it *could be* that log level configuration is broken.

**Comment by mcraveiro** [comment]
Hi @razzmatazz,

thanks for the prompt response. I will try to modify the log level and see what comes out.

Cheers

Marco

**Comment by mcraveiro** [comment]
This worked as expected. Thanks for your help.
