### ISSUE TITLE
golang gopls error textDocument/publishDiagnostics

### ISSUE THREAD

**Issue by zt9** [emacs-lsp/lsp-mode#1877]
[lsp-log-go.txt](https://github.com/emacs-lsp/lsp-mode/files/4872036/lsp-log-go.txt)
[lsp-log.txt](https://github.com/emacs-lsp/lsp-mode/files/4872037/lsp-log.txt)
[messages.txt](https://github.com/emacs-lsp/lsp-mode/files/4872038/messages.txt)
[emacs.txt](https://github.com/emacs-lsp/lsp-mode/files/4872039/emacs.txt)

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 darwin/amd64
</pre>

![ScreenFlow](https://user-images.githubusercontent.com/859075/86503983-8baca600-bd81-11ea-84bd-97b491aacc70.gif)

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/bobster/Library/Caches/go-build"
GOENV="/Users/bobster/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/bobster/code/golang.vscode"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/bobster/code/golang.vscode/src/github.com/zt9/qr.code.review/golang/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/k4/9_dj5xl9139gqq29bhdgphtw0000gn/T/go-build767431480=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Installed latest emacs and got the most simplest configuration so I can get lsp and gopls working. As soon as I type fmt.Println(" TAB I get a message ""missing ',' in argument list"" ..relevant message from the logs:

[Trace - 08:00:37 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
  "diagnostics": [
    {
      "message": "missing ',' in argument list",
      "source": "syntax",
      "severity": 1,
      "range": {
        "end": {
          "character": 18,
          "line": 30
        },
        "start": {
          "character": 18,
          "line": 30
        }
      }
    }
  ],
  "version": 17,
  "uri": "file:///Users/blobster/code/golang.vscode/src/github.com/zt9/qr.code.review/golang/cmd/server.go"
}

### What did you expect to see?
Not the error

### What did you see instead?
The error
[lsp-log-go.txt](https://github.com/golang/go/files/4872030/lsp-log-go.txt)
[lsp-log.txt](https://github.com/golang/go/files/4872031/lsp-log.txt)
[messages.txt](https://github.com/golang/go/files/4872032/messages.txt)
[emacs.txt](https://github.com/golang/go/files/4872033/emacs.txt)

@muirdm @adam-r-kowalski Please let me know if is anything you think I could try.

**Comment by muirdm** [comment]
The completion candidate inserts invalid Go code, so the syntax error is expected.

```go
fmt.Println(a ...interface{}) // invalid syntax.
```

**Comment by zt9** [comment]
@muirdm Thank you for your reply. Sorry for the dumb questions, does this mean the problem is coming from gopls and gopls is providing bad recommendation to lsp-mode? Since I do not believe there is any other completion candidate, it seems the only option is to fix gopls - please let me know if my understanding of my options are correct.

**Comment by muirdm** [comment]
Yes, it is from gopls. That behavior will be improved at some point, but for now you can set `lsp-gopls-use-placeholders` to `nil` to disable the placeholders completely.

**Comment by muirdm** [comment]
I realized the "computing fix edits" error is actually a gopls bug (it was propagating an "expected" error). It should be fixed on gopls master via https://go-review.googlesource.com/c/tools/+/243238 and will be in the next release.

Note that you will still see syntax errors pop up, but the spammy "computing fix edits" errors won't show up.
