### ISSUE TITLE
completionItem sortText not respected by lsp--capf-filter-candidates

### ISSUE THREAD

**Issue by payneca** [emacs-lsp/lsp-mode#1883]
**Describe the bug**
A change from 6.3 (working) and 7.0 (breaking), it appears that `lsp--capf-filter-candidates` scores completion items, then sorts by those scores. If a CompletionItem `sortText` field was specified, it seems to be completely overridden. 

**To Reproduce**
From a message traffic perspective, it is helpful to log a request to verify the ordering and sortText keys of the inbound completions. The displayed completion options to produce a different order. I am using a non-public language server so I cannot share a direct example. I'm unfamiliar with existing language servers that may include sortText results. 

**Expected behavior**
I expected that the server's `sortText` key would be used for sort order.

If I comment out this code in `lsp--capf-filter-candidates`, I get the expected behavior.
```
(-sort (lambda (o1 o2)
         (> (get-text-property 0 'sort-score o1)
            (get-text-property 0 'sort-score o2))))
```

**Which Language Server did you use**
Non-public

**OS**
Mac OS X 10.15.5

**Comment by yyoncho** [comment]
We did that to make client caching possible and followed what vscode does with some improvements.

@kiennq WDYT about introducing mode which is - don't cache, sort only by using sortText and ignore better prefix match?

**Comment by payneca** [comment]
Interestingly enough, it appears VSCode still respects sortText, but does give some bizarre results.

**Comment by yyoncho** [comment]
there is this: https://github.com/Microsoft/language-server-protocol/issues/348 and especially this: https://github.com/microsoft/language-server-protocol/issues/898#issuecomment-594617708

**Comment by kiennq** [comment]
@payneca If server is returning `CompletionList` with `IsIncompleted` is `true`, client side filtering will be ignored.
When server is returning completed completion list, the `sortText` will only being used for tie-breaker.
Can you modify your server to return `IsIncompleted`?

**Comment by kiennq** [comment]
> @kiennq WDYT about introducing mode which is - don't cache, sort only by using `sortText` and ignore better prefix match?

How about introducing a new private variable, some thing like `lsp--capf-no-reorder`, so while we still do filtering but will not re-order according to matching score?
Then we will have a new logic like:
- With first completed completion results from server, we will not re-ordering (trust server `sortText`)
- From the next one where we're doing fuzzy filtering, we will re-order as client logic.

I think that logic should be more correct than the current one of re-ordering always.

As a side effect, when user set `lsp--capf-no-reorder` (not recommended, but for advanced user), we will not do re-ordering.
@yyoncho WDYT?

**Comment by kiennq** [comment]
@payneca Can you see if #1886 fixes your issue?

**Comment by yyoncho** [comment]
> As a side effect, when user set `lsp--capf-no-reorder` (not recommended, but for advanced user), we will not do re-ordering.
> @yyoncho WDYT?

IMO both caching and sorting based on prefix are connected. Otherwise if user types `fooBar` and there is entry `fooBar` but we put something with fuzzy match in the first place if its score if it has a bigger score. I would find that unnatural and inconvenient.

**Comment by kiennq** [comment]
> IMO both caching and sorting based on prefix are connected. Otherwise if user types `fooBar` and there is entry `fooBar` but we put something with fuzzy match in the first place if its score if it has a bigger score. I would find that unnatural and inconvenient.

That's why the option is not recommended to set.
However, I think what user really want is that we shouldn't re-ordering completion items the first time receiving from server, since server has the best knowledge at that time, after that, due to the cache, we will do re-ordering ourselves.

I do see your point, will add a `defcustom` (`lsp-completion-no-cache`) so that we will not cache the value from server.
Combine that with what I mentioned before, we will not no reordering and cache when `lsp-completion-no-cache` is set.

**Comment by payneca** [comment]
Thanks for the "Do whatever you have to do" attitude.

Using `isIncomplete` does yield the results I expected.

Not using `isIncomplete`, but using #1886 yielded strange results. Typing the first character gave promising results, but further typing kicked into the fuzzing algorithm and destroyed the usefulness of my server's input.

Using #1886 AND setting `lsp--capf-no-reorder` makes me say WOW! I think it's providing better results than I see from VSCode. It at least gives the appearance that the server and client are cooperating to give the developer results.

You may want to consider `lsp--capf-no-reorder` as default behavior. It appears to be quite powerful.

Suggestion: I'm likely to set `lsp--capf-no-reorder` into a config file for the users of my language server -- which seems bad, since it will impact other servers as well. It may be stronger to provide this as an option in `lsp-register-client`.

**Comment by yyoncho** [comment]
> You may want to consider lsp--capf-no-reorder as default behavior. It appears to be quite powerful.

IMO the setting makes sense when the server is smart. Also, a lot of the servers are fine-tuned to work against what vscode does.

> Suggestion: I'm likely to set lsp--capf-no-reorder into a config file for the users of my language server -- which seems bad, since it will impact other servers as well. It may be stronger to provide this as an option in lsp-register-client.

There is :after-open-fn in the client registration which you can use to setq-local the corresponding setting.

**Comment by payneca** [comment]
> IMO the setting makes sense when the server is smart. Also, a lot of the servers are fine-tuned to work against what vscode does.

I hope I don't fall into that trap. I hope I fine-tune for what's best for users, not what the VSCode developers thought was best for users.

> There is :after-open-fn in the client registration which you can use to setq-local the corresponding setting.

Perfect. That works great.

**Comment by yyoncho** [comment]
> I hope I don't fall into that trap. I hope I fine-tune for what's best for users, not what the VSCode developers thought was best for users.

Yes. Generally, the server knows much better what should be the order because it is smarter than the client. But Microsoft... I hope that at some point they will allow features in the protocol that are not implemented supported by VScode.

**Comment by kiennq** [comment]
@payneca, to summarize this, there's several approach that you can take to skip filtering and re-ordering from client side:
- Changes in language server: you can either:
  - Adding `isIncomplete` into `CompletionList`, this will prevent client-side caching
  - Adding `score` to each `CompletionItem`, this will still enable caching, but client side will honor that score and use it (as multiplier) to re-ordering
- Or changes in client side:
  - Set `lsp--capf-no-reorder`, this will still cache server results, but do not do re-ordering according to fuzzyness. So it will be dangerous for longer typing sequence.
  - Set `lsp-completion-no-cache`, this will not cache server result and not reordering, which is the same with language server returns `isIncomplete`

**Comment by payneca** [comment]
I believe I can survive without PR #1886. I was not aware that I could use the `score` key.

- Setting `isIncomplete` works though emotionally I feel like I'm lying to the client.
- Adding `score` seems to yield promising results.
- Setting `lsp--capf-no-reorder` seems to yield promising results. And yes, longer typing sequences were strange.
- Setting `lsp-completion-no-cache` worked but performance tanked as expected.

Not to convolute the issue, but it may be worth thinking about rather than an enable/disable flag allowing a function that can be hooked during `lsp-register-client` that can more directly influence the scoring. It could be the scoring function itself, or the sort scoring function.

I'm happy if you'd like to close the issue.

**Comment by yyoncho** [comment]
I am glad that clangd's idea about score works. Too bad that most likely it won't make it to the spec.

> Not to convolute the issue, but it may be worth thinking about rather than an enable/disable flag allowing a function that can be hooked during `lsp-register-client` that can more directly influence the scoring. It could be the scoring function itself, or the sort scoring function.

The challenge here is what we will do if there are 2 language servers providing completion? How do we sort if one of the servers has sort function?

**Comment by payneca** [comment]
I am probably exceeding my domain knowledge. I was not aware that 2 language servers could provide completion for the same file. Composition of functions would certainly be an issue. I don't have a (good) suggestion for that.
