### ISSUE TITLE
rust-analyzer no longer supports workspace/executeCommand

### ISSUE THREAD

**Issue by leotaku** [emacs-lsp/lsp-mode#1890]
**Describe the bug**
When trying to apply a code action using `lsp-execute-code-action` using a recent version of rust-analyzer, the command fails with the following error message:

```
The connected server(s) does not support method workspace/executeCommand
To find out what capabilities support your server use ‘M-x lsp-describe-session’ and expand the capabilities section.
```

**To Reproduce**
1. Install rustup `rustup 1.21.1`
2. Install a nightly Rust toolchain using rustup. `cargo 1.46.0-nightly`
3. Install rust-analyzer using cargo `rust-analyzer 36840bd`
4. Load the following code in a clean Emacs instance. (Ensure that you have either set `CARGO_HOME`, or replace it with your OS's default location)

<details>
  <summary>Click to expand!</summary>

```emacs-lisp
(require 'package)

(setq debug-on-error t)

(let* ((package-archives '(("melpa" . "https://melpa.org/packages/")
                           ("gnu" . "https://elpa.gnu.org/packages/")))
       (no-byte-compile t)
       (package-user-dir (expand-file-name (make-temp-name "lsp-tmp-elpa")
                                           user-emacs-directory))
       (custom-file (expand-file-name "custom.el" package-user-dir))
       (pkg-list '(rust-mode lsp-mode lsp-ui yasnippet lsp-java lsp-python-ms lsp-haskell helm-lsp lsp-treemacs dap-mode lsp-origami lsp-dart company flycheck)))

  (package-initialize)
  (package-refresh-contents)

  (mapcar (lambda (pkg)
            (unless (package-installed-p pkg)
              (package-install pkg))
            (require pkg))
          pkg-list)

  (yas-global-mode)
  (add-hook 'prog-mode-hook 'lsp)
  (add-hook 'kill-emacs-hook `(lambda ()
                                (delete-directory ,package-user-dir t))))

(setq lsp-rust-server 'rust-analyzer)
(setq lsp-rust-analyzer-server-command
      (concat (getenv "CARGO_HOME") "/bin/rust-analyzer"))

```
</details>

5. Open any Rust file that is part of a cargo project.
6. Try running `lsp-execute-code-action` where a code action is advertised

**Expected behavior**

It would be unreasonable to expect this to work as rust-analyzer has lost support for `workspace/executeCommand` quite a while ago. ([rust-analyzer/#1232](https://github.com/rust-analyzer/rust-analyzer/issues/1232)) 

I would argue that lsp-mode should support the server-specific `rust-analyzer.applySourceChange` capability, as other client implementations (vim, kakoune) already do the same. Though I realize that this could represent additional maintenance burden. (@brotzeit and @kurnevsky, what do you think?)

I also think that as long as we do not support applying the changes suggested by rust-analyzer they should not be by suggested as part of the modeline, lsp-ui or the `lsp-execute-code-action` minibuffer selection.

**Which Language Server did you use**

lsp-rust with rust-analyzer

**OS**
NixOS Linux `20.09pre-git (Nightingale)`

**Comment by yyoncho** [comment]
I will do a fix.

**Comment by yyoncho** [comment]
@leotaku can you give an example for code action that does not work? I tested a few and they seems to work fine when using this version: https://github.com/rust-analyzer/rust-analyzer/releases/tag/2020-07-06

**Comment by leotaku** [comment]
Sure, all code actions I tried seemed to fail, so I did not specify one.

* `Add #[derive]`
* `Add default constructor`

These are advertised for all structs and should be easy to reproduce.

**Comment by yyoncho** [comment]
Sorry, I am not using rust on day to day basis, can you provide sample file to reproduce the issue?

**Comment by flodiebold** [comment]
`rust-analyzer.applySourceChange` is not needed by current rust-analyzer versions. Try updating your rust-analyzer (the commit you reference is 3 months old).

**Comment by leotaku** [comment]
@flodiebold is correct, I did not have an up-to-date version of rust-analyzer installed. I honestly did not give it much thought, as I did not see any newer PRs/commits referencing [the issue](https://github.com/rust-analyzer/rust-analyzer/issues/1232) in rust-analyzer but saw very recent commits in eg. kak-lsp that indicate they had to use custom logic.

@flodiebold do you by any chance have a link to the issue where this new development is discussed? Is there any reason to still support `rust-analyzer.applySourceChange`?

@yyoncho Thanks for trying to step in so quickly! I am sorry for any confusion caused by my issue.

**Comment by flodiebold** [comment]
No, there's no reason to support `applySourceChange` anymore. It was removed as part of an effort to move to extensions that can potentially be upstreamed to the protocol, which you can read about [here](https://github.com/rust-analyzer/rust-analyzer/issues/4224#issuecomment-632268145).

**Comment by leotaku** [comment]
Thanks @flodiebold. In that case I think it makes sense to just close this issue.
