### ISSUE TITLE
lsp-elm not always filtering completions

### ISSUE THREAD

**Issue by theothornhill** [emacs-lsp/lsp-mode#1892]
Hello there!

When typing from beginning of line, lsp-mode gives completions as it should, however, anywhere else it does not filter the presented candidates.

To reproduce:
`elm init` and `git init` inside some folder, then create `src/Main.elm` in root.
Now invoke lsp-mode.

Start typing: `module Main exposing (..)`

What you will see:
During `module`, we get completions, like this:
![filters](https://user-images.githubusercontent.com/26711805/86966688-dbb4af80-c169-11ea-9d02-2637cd79af13.png)

During exposing, we get this:
![doesnotfilter](https://user-images.githubusercontent.com/26711805/86966704-e40cea80-c169-11ea-9c84-34c1b22f0ea4.png)

If we at this point press `RET`, we end up with this:
![result](https://user-images.githubusercontent.com/26711805/86966868-1cacc400-c16a-11ea-8c24-9fbb82ded02a.png)

As a side note, oddly enough, when indenting the next line a space or two, lsp-mode gives no completions until the ".", then we get proper filtering again. Like this:
![oddcase](https://user-images.githubusercontent.com/26711805/86967246-aceb0900-c16a-11ea-820a-45e17bbf3318.png)

I've only found this bug in `elm-mode` files, so it may be something wrong with the syntax table there.

**Comment by yyoncho** [comment]
@kiennq willing to take a look? probably server is sending incorrect textEdit. 

@theothornhill can you provide the log from the completions that break?

**Comment by kiennq** [comment]
Yes it does seem server just return weird completion items.
It would be helped to have log from the completions that break.
I've tried with https://github.com/rtfeldman/elm-spa-example and it seems the exposing is properly filtered

**Comment by theothornhill** [comment]
Hello!

Attached is the log in empty project with only one file: `src/Main.elm` .

I've written `module Main ex` at the time of log.

Some things I noted while logging:

1. `module` filters fine, and after it is written, log is around 3k lines.
2. `Main` does not seem to increase log by much
3. `e` adds ~10k lines and `x` another ~10k and keeps doing this, so I stopped after `x`

[log.txt](https://github.com/emacs-lsp/lsp-mode/files/4908255/log.txt)

Hope this helps :)

**Comment by theothornhill** [comment]
FWIW, it seems like this was solved in CoC like this:
https://github.com/neoclide/coc.nvim/commit/af2b7f55843bbb8e3d6a1fc9c41e7f7a54d3b27d

@kiennq @yyoncho

**Comment by yyoncho** [comment]
@theothornhill can you confirm that you are using the latest lsp-mode version? We do what coc do (and much more).

**Comment by kiennq** [comment]
From your log, the reason why it's not filtered is because of language server return `isIncomplete` as `true`.

``` typescript
export interface CompletionList {
	/**
	 * This list it not complete. Further typing should result in recomputing
	 * this list.
	 */
	isIncomplete: boolean;

	/**
	 * The completion items.
	 */
	items: CompletionItem[];
}
```

We have a heuristic logic in `lsp-mode` that stop filtering when the language server return `isIncomplete`, since we expect server should do some filtering already in that case.
The reason is simple, if server doesn't do any filtering, typing more characters will just returns same candidates, which make server seems useless. 

Nevertheless , we can probably remove that heuristic and force filtering to run on every server returns.
Probably also add new variable to toggle that behavior.

@yyoncho WDYT?

**Comment by theothornhill** [comment]
@yyoncho Yeah, I also nuked my whole elpa folder just now. Still happens! Also, I confirmed it works with CoC

**Comment by yyoncho** [comment]
> Nevertheless , we can probably remove that heuristic and force filtering to run on every server returns.
> Probably also add new variable to toggle that behavior.
> 
> @yyoncho WDYT?

I was afraid that we are going to end up like this when we diverge from what vscode does... We should do either this or try to convince elm people to return isIncomplete=false. For me asking the client to filter when incomplete is true does not make any sense.

**Comment by yyoncho** [comment]
Fixing elm does not seem to be an option, their code is like this:

```
    const isIncomplete = possibleImports.length > 50;
```

and then return the first 50 elements.

**Comment by kiennq** [comment]
While I'm believe language server must has some filtering capability (else how can it offer completions item depends on context?), in `lsp-mode` we should just add a variable `lsp-completion-filter-isincomplete` so user can switch and decide what's best for them

**Comment by yyoncho** [comment]
Yes. Let's keep the default = "what vscode does" and provide variables so users could fine-tune completion handling based on server capabilities. Although, we should probably provide guidance per server.

**Comment by kiennq** [comment]
@theothornhill Can you try with #1904 to see if your issue is resolved?

**Comment by theothornhill** [comment]
@kiennq It absolutely seems to work :)

Thanks so much 🤗
