### ISSUE TITLE
Ligatures cause `lsp-ui-sideline` freeze

### ISSUE THREAD

**Issue by jilen** [emacs-lsp/lsp-mode#1893]
**Ligatures cause lsp-ui-sideline freeze**

If `lsp-ui-sideline` is turned on and there is an `flycheck` error that contains some string could be `composited` as ligatures, emacs freeze.

**OS**
Mac os

**Error callstack**

```
c-redisplay-internal
 unable to shape unibyte text
```

**Comment by kiennq** [comment]
I think this should be Emacs bug, can you file a bug on Emacs devel?
