### ISSUE TITLE
Possible to disable auto-add of includes?

### ISSUE THREAD

**Issue by nickenchev** [emacs-lsp/lsp-mode#1902]
Hey I recently updated my emacs packages and I noticed that include files are automatically being added as I use certain classes. I noticed a mess happening at the top of my files, as well as files being needlessly added since I already had the appropriate includes (Qt). Is there a way to disable this feature?

**Comment by yyoncho** [comment]
I guess this is what you are looking for:
```
(setq lsp-completion-enable-additional-text-edit nil)
```
