### ISSUE TITLE
How to disable lsp-diagnostic-package for all prog-mode except for web-mode?

### ISSUE THREAD

**Issue by ianpan870102** [emacs-lsp/lsp-mode#1903]
As titled.
Here's the solution I've tried so far, which works most of the time (e.g. web-mode buffers get the lsp checker, but not C++ modes). However, lately I've found that lsp checkers are enabled in python-mode too...

```emacs-lisp
  (setq lsp-diagnostic-package :none)   ; disable flycheck-lsp for most modes
  (add-hook 'web-mode-hook #'(lambda () ; enable flycheck-lsp for web-mode (locally)
                               (setq-local lsp-diagnostic-package :auto)))
```

**Comment by yyoncho** [comment]
Did you try to call `lsp-flycheck-enable` in web-mode-hook?

**Comment by ianpan870102** [comment]
I didn't, let me try that.

**Comment by ianpan870102** [comment]
Here's the new setting I tried:

```emacs-lisp
  (setq lsp-diagnostic-package :none)             ; disable flycheck-lsp for most modes
  (add-hook 'web-mode-hook #'lsp-flycheck-enable) ; enable flycheck-lsp for web-mode (locally)
```

Description of the problem: When I restart Emacs and open a python buffer, it doesn't use lsp-checker (disabled as I wanted it to be). But if I open a new python buffer "after" I open a web-mode buffer, both will be using lsp-checkers. It seems that the web-mode hook doesn't just activate lsp-flycheck locally, but rather it influences the buffers that open afterwards as well.

**Comment by yyoncho** [comment]
Can you try after https://github.com/emacs-lsp/lsp-mode/commit/5f72463078309071fd6446d6550218a728004110?

**Comment by ianpan870102** [comment]
Hi @yyoncho thanks for getting back.
After the latest update I can confirm that my desired behaviour can be achieved using the following config:

```emacs-lisp
  (setq lsp-diagnostic-package :none)             ; disable flycheck-lsp for most modes
  (add-hook 'web-mode-hook #'lsp-flycheck-enable) ; enable flycheck-lsp for web-mode locally
```

Purely out of curiousity, I'd love to know what changes you committed on your end -- and was it a python-specific issue? I tried digging in the commit messages but didn't really get it.

**Comment by yyoncho** [comment]
flycheckers are bound to major mode(s). lsp-mode registers dynamically flychecker when you start it in major mode X. But initially, we have to provide a major mode for the flychecker because it is mandatory and we were using python-mode so it was unconditionally enabled for python-mode.

**Comment by ianpan870102** [comment]
> ...we were using python-mode so it was unconditionally enabled for python-mode.

Ah, this makes a ton of sense! Thanks again man @yyoncho
