### ISSUE TITLE
php intelephense: variable candidates won't show up

### ISSUE THREAD

**Issue by sollidsnake** [emacs-lsp/lsp-mode#1905]
**Describe the bug**
Candidates that begin with `$` aren't fetched when `company-lsp-match-candidate-predicate` is set to `'company-lsp-match-candidate-prefix`.

**To Reproduce**
```
<?php
$someVariable = "foo";
echo $some
```
Given the scenario above, put the cursor at the end of the last line and try to invoke completion completion. It should work if `company-lsp-match-candidate-predicate` is set to `flex`, but if you set it to `prefix` no candidates show up.

**Expected behavior**
Candidates beginning with `$` to show up even when `company-lsp-match-candidate-predicate` is set to `prefix`

**Which Language Server did you use**
intelephense

**OS**
Arch Linux

**Error callstack**
Just the message "No completion found"

**Comment by yyoncho** [comment]
company-lsp is deprecated and no longer supported, please try with company-capf. You could do that by deleting company-lsp package.

**Comment by sollidsnake** [comment]
Oh, I didn't know that. It's working now. Thank you very much.
