### ISSUE TITLE
got a wrong type argument messag (go)

### ISSUE THREAD

**Issue by jongyoungcha** [emacs-lsp/lsp-mode#1918]
Before logging the bug, please make sure that:

1. You are using the latest version of `lsp-mode` related packages.
lsp :
![image](https://user-images.githubusercontent.com/7163653/87544846-11194a00-c6e2-11ea-8084-496d373ffa42.png)

gopls :
![image](https://user-images.githubusercontent.com/7163653/87545048-5b023000-c6e2-11ea-8bd7-4ffa2b022544.png)

2. You may also try reproduce the issue using clean environment using the following command:
 
 

**Describe the bug**
When I exec the function find-references, error message was showing 
![image](https://user-images.githubusercontent.com/7163653/87546186-18415780-c6e4-11ea-8a70-cb21b31f9403.png)

**To Reproduce**
 if you do find-references in golang

**Expected behavior**

**Which Language Server did you use**
gopls 
 
**OS**
ubuntu 18.04

**Error callstack**
![image](https://user-images.githubusercontent.com/7163653/87545682-568a4700-c6e3-11ea-9a0b-72e186390da2.png)

**lsp-log**
[Trace - 09:38:27 �ㅽ��] Sending request 'textDocument/references - (2863)'.
Params: {
  "textDocument": {
    "uri": "file:///home/jongyoungcha/go/src/swit/swit-gcs-file-golang/app/apiserver.go"
  },
  "position": {
    "line": 77,
    "character": 20
  },
  "context": {
    "includeDeclaration": false
  }
}

[Trace - 09:38:27 �ㅽ��] Received response 'textDocument/references - (2863)' in 4ms.
Result: [
  {
    "range": {
      "end": {
        "character": 16,
        "line": 86
      },
      "start": {
        "character": 3,
        "line": 86
      }
    },
    "uri": "file:///home/jongyoungcha/go/src/swit/swit-gcs-file-golang/app/apiserver.go"
  }
]

[Trace - 09:38:27 �ㅽ��] Sending request 'textDocument/documentLink - (2864)'.
Params: {
  "textDocument": {
    "uri": "file:///home/jongyoungcha/go/src/swit/swit-gcs-file-golang/app/apiserver.go"
  }
}

[Trace - 09:38:27 �ㅽ��] Received response 'textDocument/documentLink - (2864)' in 330ms.
Result: [
  {
    "target": "https://pkg.go.dev/context",
    "range": {
      "end": {
        "character": 9,
        "line": 3
      },
      "start": {
        "character": 2,
        "line": 3
      }
    }
  },
  {
    "target": "https://pkg.go.dev/github.com/gin-gonic/gin@v1.6.3",
    "range": {
      "end": {
        "character": 26,
        "line": 4
      },
      "start": {
        "character": 2,
        "line": 4
      }
    }
  },
  {
    "target": "https://pkg.go.dev/golang.swit.dev/grpc@v0.0.0-20200630021217-b197ccfed381/protos/auth/v4",
    "range": {
      "end": {
        "character": 45,
        "line": 5
      },
      "start": {
        "character": 10,
        "line": 5
      }
    }
  },
  {
    "target": "https://pkg.go.dev/golang.swit.dev/http@v0.0.0-20200626043943-9057b4ffdd41/middleware",
    "range": {
      "end": {
        "character": 33,
        "line": 6
      },
      "start": {
        "character": 2,
        "line": 6
      }
    }
  },
  {
    "target": "https://pkg.go.dev/swit/swit-gcs-file-golang/app/import",
    "range": {
      "end": {
        "character": 49,
        "line": 7
      },
      "start": {
        "character": 13,
        "line": 7
      }
    }
  },
  {
    "target": "https://pkg.go.dev/swit/swit-gcs-file-golang/app/others",
    "range": {
      "end": {
        "character": 38,
        "line": 8
      },
      "start": {
        "character": 2,
        "line": 8
      }
    }
  },
  {
    "target": "https://pkg.go.dev/swit/swit-gcs-file-golang/app/upload",
    "range": {
      "end": {
        "character": 38,
        "line": 9
      },
      "start": {
        "character": 2,
        "line": 9
      }
    }
  },
  {
    "target": "https://pkg.go.dev/go.opencensus.io@v0.22.4/plugin/ochttp",
    "range": {
      "end": {
        "character": 32,
        "line": 11
      },
      "start": {
        "character": 2,
        "line": 11
      }
    }
  },
  {
    "target": "https://pkg.go.dev/go.opencensus.io@v0.22.4/plugin/ochttp/propagation/b3",
    "range": {
      "end": {
        "character": 47,
        "line": 12
      },
      "start": {
        "character": 2,
        "line": 12
      }
    }
  },
  {
    "target": "https://pkg.go.dev/go.opencensus.io@v0.22.4/trace",
    "range": {
      "end": {
        "character": 24,
        "line": 13
      },
      "start": {
        "character": 2,
        "line": 13
      }
    }
  },
  {
    "target": "https://pkg.go.dev/golang.swit.dev/pkg@v0.0.0-20200626012454-e23ac57d5e6a/util",
    "range": {
      "end": {
        "character": 26,
        "line": 14
      },
      "start": {
        "character": 2,
        "line": 14
      }
    }
  },
  {
    "target": "https://pkg.go.dev/github.com/sirupsen/logrus@v1.6.0",
    "range": {
      "end": {
        "character": 32,
        "line": 16
      },
      "start": {
        "character": 6,
        "line": 16
      }
    }
  },
  {
    "target": "https://pkg.go.dev/net/http",
    "range": {
      "end": {
        "character": 10,
        "line": 17
      },
      "start": {
        "character": 2,
        "line": 17
      }
    }
  },
  {
    "target": "https://pkg.go.dev/os",
    "range": {
      "end": {
        "character": 4,
        "line": 18
      },
      "start": {
        "character": 2,
        "line": 18
      }
    }
  },
  {
    "target": "https://pkg.go.dev/os/signal",
    "range": {
      "end": {
        "character": 11,
        "line": 19
      },
      "start": {
        "character": 2,
        "line": 19
      }
    }
  },
  {
    "target": "https://pkg.go.dev/syscall",
    "range": {
      "end": {
        "character": 9,
        "line": 20
      },
      "start": {
        "character": 2,
        "line": 20
      }
    }
  },
  {
    "target": "https://pkg.go.dev/time",
    "range": {
      "end": {
        "character": 6,
        "line": 21
      },
      "start": {
        "character": 2,
        "line": 21
      }
    }
  },
  {
    "target": "https://gzip.De",
    "range": {
      "end": {
        "character": 21,
        "line": 44
      },
      "start": {
        "character": 14,
        "line": 44
      }
    }
  }
]

**Comment by yyoncho** [comment]
> 1. You are using the latest version of `lsp-mode` related packages.
>    lsp :
>    ![image](https://user-images.githubusercontent.com/7163653/87544846-11194a00-c6e2-11ea-8084-496d373ffa42.png)

This lsp-mode is like 5 months old.

**Comment by jguenther** [comment]
I'm seeing the same error today on latest lsp-mode

```
Error running timer ‘lsp--on-idle’: (wrong-type-argument listp #("  	" 2 3 (face (:family "github-octicons" :height 1.2 :inherit doom-themes-treemacs-file-face) font-lock-face (:family "github-octicons" :height 1.2 :inherit doom-themes-treemacs-file-face) display (raise 0.0) rear-nonsticky t)))
```

lsp-mode 20200714.2335
doom-themes 20200621.109
treemacs 20200715.1534

I've tried deleting *.elc and restarting, but I'm not sure how to troubleshoot further other than downgrading

**Comment by yyoncho** [comment]
> I'm seeing the same error today on latest lsp-mode
> 
> ```
> Error running timer ‘lsp--on-idle’: (wrong-type-argument listp #("  	" 2 3 (face (:family "github-octicons" :height 1.2 :inherit doom-themes-treemacs-file-face) font-lock-face (:family "github-octicons" :height 1.2 :inherit doom-themes-treemacs-file-face) display (raise 0.0) rear-nonsticky t)))
> ```
> 
> lsp-mode 20200714.2335
> doom-themes 20200621.109
> treemacs 20200715.1534
> 
> I've tried deleting *.elc and restarting, but I'm not sure how to troubleshoot further other than downgrading

This is a separate issue, most likely related to headerline. Can you provide a call stack?

**Comment by yyoncho** [comment]
Also it is probably triggered by the fact that doom-themes is altering treemacs icons with all the icons.

**Comment by jguenther** [comment]
whoops that's my bad, that's not the same thing is it, nvm :)

**Comment by yyoncho** [comment]
> whoops that's my bad, that's not the same thing is it, nvm :)

Do you still see that?

**Comment by jguenther** [comment]
@yyoncho many thanks, I just tried upgrading these packages and I'm not seeing errors anymore 😄

**Comment by yyoncho** [comment]
Thank you. 

I am marking the bug as resolved! @jongyoungcha please reopen if you still see the error with latest lsp-mode.
