### ISSUE TITLE
Prefer committing .dir-locals.el over .editorconfig?

### ISSUE THREAD

**Issue by leungbk** [emacs-lsp/lsp-mode#1924]
Everyone here uses Emacs, so anything we would use a `.editorconfig` for can be done with a `.dir-locals.el` and a `.gitattributes` file.

One concrete benefit of committing a project-wide `.dir-locals.el` is that we should be able to modify `lisp-imenu-generic-expression` to detect `lsp-defun` and `lsp-interface`, allowing `M-x imenu` to be more useful. I use `imenu` all the time, but in this project I often find myself using it to find a function and then realizing "oh right it can't detect that".

**Comment by yyoncho** [comment]
make sense to me.
