### ISSUE TITLE
Angular angular-ls is keep crashing .

### ISSUE THREAD

**Issue by gnumonk** [emacs-lsp/lsp-mode#1936]
**Describe the bug**
Enabling lsp for html (i.e Angular project), angular-ls is kept crashing. 

**To Reproduce**
Enable following option in .spacemacs 
          html-enable-lsp t
           css-enable-lsp t
           less-enable-lsp t
           scss-enable-lsp t
**Expected behavior**
angular-ls mode should not crash in .html files.

**OS**
Mac

**Error callstack**
/usr/local/lib/node_modules/@angular/language-service/bundles/language-service.umd.js:30351
finally { if (e_1) throw e_1.error; }
^

TypeError: Cannot read property 'kind' of undefined
at getConditionalFlowTypeOfType (/usr/local/lib/node_modules/typescript/lib/tsserverlibrary.js:45510:28)
at getTypeFromTypeNode (/usr/local/lib/node_modules/typescript/lib/tsserverlibrary.js:47396:20)
at getTypeOfNode (/usr/local/lib/node_modules/typescript/lib/tsserverlibrary.js:67279:40)
at Object.getTypeAtLocation (/usr/local/lib/node_modules/typescript/lib/tsserverlibrary.js:35196:31)
at getTsTypeFromBuiltinType (/usr/local/lib/node_modules/@angular/language-service/bundles/language-service.umd.js:28524:28)
at TypeScriptSymbolQuery.getBuiltinType (/usr/local/lib/node_modules/@angular/language-service/bundles/language-service.umd.js:27691:28)
at getEventDeclaration (/usr/local/lib/node_modules/@angular/language-service/bundles/language-service.umd.js:26756:30)
at getExpressionScope (/usr/local/lib/node_modules/@angular/language-service/bundles/language-service.umd.js:26781:21)
at ExpressionDiagnosticsVisitor.getExpressionScope (/usr/local/lib/node_modules/@angular/language-service/bundles/language-service.umd.js:26546:87)
at ExpressionDiagnosticsVisitor.diagnoseExpression (/usr/local/lib/node_modules/@angular/language-service/bundles/language-service.umd.js:26863:30)

Process angular-ls stderr finished
Info 0 [10:8:23.740] Format host information updated

Info 1 [10:8:23.743] reload projects.

Info 2 [10:8:23.744] Before ensureProjectForOpenFiles:

Info 3 [10:8:23.744] After ensureProjectForOpenFiles:

Info 4 [10:8:23.744] Host file extension mappings updated

**Comment by leungbk** [comment]
With Angular 10, the server crashes the first time, but after restarting it, it seems to work. Here's what I tried:

``` shell
npm i -g @angular/cli
ng new
[...]
cd my-project
npm i -D @angular/language-server
npm i
```

And then I made the following `.dir-locals.el` in the root of the project:

``` elisp
((nil
  (eval . (setq lsp-clients-angular-language-server-command
                (let ((curr-proj-root (projectile-project-root)))
                  `("node"
                    ,(concat curr-proj-root "node_modules/@angular/language-server")
                    "--ngProbeLocations"
                    ,(concat curr-proj-root "node_modules")
                    "--tsProbeLocations"
                    ,(concat curr-proj-root "node_modules")
                    "--stdio"))))))
```

I have no idea if installing `@angular/language-server` per project is actually better than using a single global one, but I tend to prefer per-project tools out of habit.

**Comment by gnumonk** [comment]
> What version of Angular are you using? It might be possible that your server version is incompatible with the version of Angular you're running. With Angular 10, the server crashes the first time for me (not sure why), but after restarting it, it seems to work. Here's what I tried:
> 
> ```shell
> npm i -g @angular/cli
> ng new
> [...]
> cd my-project
> npm i -D @angular/language-server
> npm i
> ```
> 
> And then I made the following `.dir-locals.el` in the root of the project:
> 
> ```emacs-lisp
> ((nil
>   (eval . (setq lsp-clients-angular-language-server-command
>                 (let ((curr-proj-root (projectile-project-root)))
>                   `("node"
>                     ,(concat curr-proj-root "node_modules/@angular/language-server")
>                     "--ngProbeLocations"
>                     ,(concat curr-proj-root "node_modules")
>                     "--tsProbeLocations"
>                     ,(concat curr-proj-root "node_modules")
>                     "--stdio"))))))
> ```
> 
> Then I accessed an `.html` file and restarted the Angular server once before it worked.
> 
> I have no idea if installing `@angular/language-server` per project is actually better than using a single global one, but I tend to prefer per-project tools out of habit.

Yes, Installing locally with above the suggestion, it is working.

**Comment by VizorKit** [comment]
I would prefer not to include a file in the project root. I am going to try angular 9

**Comment by nfedyashev** [comment]
@leungbk thanks a lot for posting the snippet. Not knowing how to thank you I've just donated to emacs-lsp on https://opencollective.com/emacs-lsp instead

**Comment by yyoncho** [comment]
seems like this is no longer happening(there are several users reporting that server works fine). Please reopen if you still see the issue.

**Comment by pedroqueiroga** [comment]
I'm posting this for future reference: check your typescript version and see if it matches `var MIN_TS_VERSION = "<VERSION>";`, which can be seen inside `node_modules/@angular/language-server/index.js` (`grep -i 'ts_version' node_modules/@angular/language-server/index.js` can be used, for example).

The need to restart angular-ls on emacs boot on project is related to `.dir-locals.el` being loaded *after* `lsp` is started. The solution is here: https://emacs-lsp.github.io/lsp-mode/page/faq/
