### ISSUE TITLE
Document or add `xref-find-references` to `xref-prompt-for-identifier`

### ISSUE THREAD

**Issue by MaskRay** [emacs-lsp/lsp-mode#194]
```elisp
(defcustom xref-prompt-for-identifier '(not xref-find-definitions
                                            xref-find-definitions-other-window
                                            xref-find-definitions-other-frame)
  "When t, always prompt for the identifier name.

When nil, prompt only when there's no value at point we can use,
or when the command has been called with the prefix argument.

Otherwise, it's a list of xref commands which will prompt
anyway (the value at point, if any, will be used as the default).

If the list starts with `not', the meaning of the rest of the
elements is negated."
..........
```

By default, `xref-find-definitions` does not prompt but `xref-find-references` does. When point is at a symbol, the prompting behavior is undesired. Some language clients may make use of text properties to find references. If the pattern is taken from the prompt instead of `(word-at-point)` or such, there is no text property associated with the pattern and the language client may not be able to find references.

There are probably three approaches:

* Do not suggest using `xref-find-references` and add a custom `lsp-find-references`
* Add `xref-find-references` to `xref-prompt-for-identifier`
* Document that `xref-prompt-for-identifier` should be changed

**Comment by MaskRay** [comment]
I found another hack in my config and I think having a custom `lsp-find-references` is the best

```elisp
    ;; This is required to make xref-find-references work in helm-mode.
    ;; In helm-mode, it gives a prompt and asks the identifier (which has no text property) and then passes it to lsp-mode, which requires the text property at point to locate the references.
    (setq xref-prompt-for-identifier '(not xref-find-definitions xref-find-definitions-other-window xref-find-definitions-other-frame xref-find-references spacemacs/jump-to-definition spacemacs/jump-to-reference))

    (setq xref-show-xrefs-function 'helm-xref-show-xrefs)
```

**Comment by vibhavp** [comment]
My plan with `lsp-mode` is to simply provide a framework for interacting with language servers. IMO, stuff like `lsp-find-references` would best fit in another package, like [company-lsp](https://github.com/tigersoldier/company-lsp)

**Comment by MaskRay** [comment]
Do you think a separate package called lsp-xref might be a good place to implement these features? Here is a list of features that I have seen or thought of that can improve the code navigation experience greatly.

* `textDocument/references` https://ptpb.pw/8ZNR.jpg
* `textDocument/codeLens` ( https://github.com/jacobdufault/cquery/blob/master/emacs/lsp-cquery.el `cquery-request-code-lens` ) https://ptpb.pw/JLjc.jpg
* `workspace/symbol` (LanguageClient-neovim `:Denite workspaceSymbol` useful for jumping to toplevel symbols in a project (think of it as a better outline) https://ptpb.pw/K-wo.jpg

**Comment by topisani** [comment]
maybe we turn some of the cquery stuff into a generic `lsp-ui` package? i definately understand why @vibhavp wants to keep `lsp-mode` as mostly a library, i think thats the power of it.

Here are some of the things id like to put in cquery, which could go in a generic `lsp-ui` package:

codelens (WIP)
code actions (WIP)
[peek] (https://code.visualstudio.com/docs/editor/editingevolved#_peek), which will make for a great xref ui
popup docs on completion

**Comment by sebastiencs** [comment]
@topisani That would be great. It could be the right place for [this](https://github.com/emacs-lsp/lsp-mode/issues/136) ?

**Comment by topisani** [comment]
@sebastiencs oooh you are the sorcerer behind that... yeah definately, its awesome! I could set up a `lsp-ui` package for this stuff, the only thing is, id really like to have it MIT. I know that blocks it from ending up in emacs at some point, but i personally have very little motivation to get it there. I feel like it would be too high level to belong in core anyway.
Does anyone (@sebastiencs ?) have a problem with that?

**Comment by terlar** [comment]
There is a package for peeking [source-peek](https://github.com/iqbalansari/emacs-source-peek), perhaps it could be integrated with LSP support

**Comment by vibhavp** [comment]
> I could set up a lsp-ui package for this stuff, the only thing is, id really like to have it MIT. I know that blocks it from ending up in emacs at some point, but i personally have very little motivation to get it there. I feel like it would be too high level to belong in core anyway.

Yep! If anything, I'd prefer an ecosystem of source code navigation frontends which _happen_ to use lsp-mode behind the scenes. The only thing that emacs would provide would be the library for communicating with language servers, and nothing else.

**Comment by MaskRay** [comment]
Having a `lsp-ui` package for (definitions/references/codeLens/.....) looks great!

**Comment by topisani** [comment]
@MaskRay yeah, especially since a lot of it will not actually be specific to lsp mode, but some xref extensions etc

**Comment by sebastiencs** [comment]
> Does anyone (@sebastiencs ?) have a problem with that?

I am totally ok with that.
I don't think it need to be in emacs either

**Comment by MaskRay** [comment]
If all are fine with a separate package `lsp-ui`, could the owner please set up <https://github.com/emacs-lsp/lsp-ui> ?

**Comment by vibhavp** [comment]
Done: https://github.com/emacs-lsp/lsp-ui

**Comment by topisani** [comment]
@vibhavp could i get commit access to `lsp-ui` or would you like to keep managing it with PRs?

**Comment by vibhavp** [comment]
Now that lsp-ui exists, it should be okay to close this.

**Comment by MaskRay** [comment]
Reported upstream  https://debbugs.gnu.org/cgi/bugreport.cgi?bug=29619
If you feel the same pain, please report what you feel on that bug.

```
> Currently, xref-find-references prompts for the identifier to look up,
> because it is not listed in xref-prompt-for-identifier:
> 
> (defcustom xref-prompt-for-identifier '(not xref-find-definitions
>                                              xref-find-definitions-other-window
>                                              xref-find-definitions-other-frame)
> 
> It will be much core convenient to add xref-find-references in the list.

We've discussed it before, and for now have settled on this list of 
non-prompting functions.

But thank you for your report. We may change the default if more people 
feel the same.
```
