### ISSUE TITLE
Cant connect to Godot LSP server on Windows 10 (lsp-gdscript)

### ISSUE THREAD

**Issue by underfarm** [emacs-lsp/lsp-mode#1941]
**Describe the bug**
lsp-gdscript is not able to connect (complete connection?) to the godot lsp-server on Windows 10. The client seems to be stuck on "starting":

lsp-session: `-[-] gdscript:nil status:starting

lsp-log: The following clients were selected based on priority: (server-id gdscript, priority 0)

I used the lsp-start-plain.el with emacs -q, and it is still stuck on "starting". 

The TCP connection seems to be established, though: "TCP    127.0.0.1:6008         127.0.0.1:51369        ESTABLISHED"

I am using Doom emacs, but the same configuration seems to work just fine on linux.

**To Reproduce**
Open a *.gd-file and start gdscript-mode (lsp-gdscript). 

**Expected behavior**
Expect the client to have the "connected" state.

**Which Language Server did you use**
Godot, V3.2.2 Stable

**OS**
Windows 10 (fresh install)

**Error callstack**
No error, at least one that i can find.

**Comment by yyoncho** [comment]
Can you try after 

```
(setq inhibit-eol-conversion t)
```
?

**Comment by underfarm** [comment]
That seemed to work, thanks a lot! The dosctring of "inhibit-eol-conversion" dident tell me much, but i can guess what it does, and the side effects :)

This might be a known problem, should i consider this issue closed?

**Comment by yyoncho** [comment]
Keep it open, it should work OOTB.

**Comment by yyoncho** [comment]
Can you try with https://github.com/yyoncho/lsp-mode/commit/7fcb581cee095e67e31f3772c1d0a142a4953b75 ? If this doesn't work I will have to ask in emacs devel for help.

**Comment by underfarm** [comment]
This seems to work:

``
LSP :: Connected to [gdscript:nil status:starting].
LSP :: gdscript:nil initialized successfully
``

**Comment by Mateus-Carmo31** [comment]
I know this is a closed issue, but might I ask why exactly inhibiting EOL conversion fixed this? I was having the same problem and this fixed it, but would like to understand the why behind the fix.
