### ISSUE TITLE
How to add another resource root to the project in Python

### ISSUE THREAD

**Issue by kinredon** [emacs-lsp/lsp-mode#1968]
I am new to use `lsp-mode` to write python code.

I have a python project which has a subdirectory `lib` in which there are many python packages (e.g. something like `model`).

For example in the code:
```
from model.nms.nms_wrapper import nms
```

 The `flychecker` raises:
 ```
Unable to import 'model.nms.nms_wrapper import nms'
```

In Pycharm, I can set the `lib` directory as a resource root to solve this problem.  

Is there a way to add another resource root to the project just like the Pycharm?

I struggle this a few days.  Anyone could help me?

**Comment by yyoncho** [comment]
Which language server do you use?

**Comment by kinredon** [comment]
@yyoncho I use the `python-language-server`.

This is my configuration:
```
(use-package python
  :ensure nil
  :hook
  ((inferior-python-mode . (lambda ()
                             (process-query-on-exit-flag
                              (get-process "Python"))))
   (python-mode . lsp)
   ;; (python-mode . flymake-mode)
   )
  :init
  ;; Disable readline based native completion
  (setq python-shell-completion-native-enable nil)
  :config
  ;; Default to Python 3. Prefer the versioned Python binaries since some
  ;; systems stupidly make the unversioned one point at Python 2.
  (when (and (executable-find "python3")
             (string= python-shell-interpreter "python"))
    (setq python-shell-interpreter "python3"))
  (setq lsp-pyls-plugins-flake8-enabled t)
  ;; Env vars
  (with-eval-after-load 'exec-path-from-shell
    (exec-path-from-shell-copy-env "PYTHONPATH"))
  (unbind-key "C-c C-f" python-mode-map)
  (unbind-key "C-c C-s" python-mode-map)
  (define-key python-mode-map (kbd "C-c C-s") 'helm-grep-do-git-grep)
  )
```

**Comment by yyoncho** [comment]
AFAIC pyls is using the python environment to find out the path and it is not configured from lsp-mode side: @mpanarin  - do you know what @kinredon should do to get that working?

**Comment by mpanarin** [comment]
Sorry for the wait.

There is a variable in `pyls`: `pyls.plugins.jedi.extra_paths`.
It is not currently added to lsp-mode pyls integration but you can pass it anyway with `lsp-register-custom-settings`.

**Comment by kinredon** [comment]
@mpanarin thinks for your reply. Could you tell me where I can find the document about `lsp-register-custom-settings`. 

Through search, unfortunately, I don't find it.

**Comment by mpanarin** [comment]
@kinredon 
You can use it in you emacs config or in `.dir-locals.el`
You need something like this:
```elisp
(with-eval-after-load 'lsp-mode
    (lsp-register-custom-settings '(("pyls.plugins.jedi.extra_paths" ["*/full/path/to/you/directory*"]))))
```

make sure though to use a full path there )

**Comment by kinredon** [comment]
@mpanarin I use it in `.dir-locals.el` like this:

```
(with-eval-after-load 'lsp-mode
  (lsp-register-custom-settings '(("pyls.plugins.jedi.extra_paths ["my/full/path/"]))))
```
but it raise a error:

`Error reading dir-Locals: (wrong-type-argument listp with-eval-after-load`

**Comment by yyoncho** [comment]
That syntax is for init file.

**Comment by mpanarin** [comment]
@kinredon 
you don't need `with-eval-after-load` if you use it in dir-locals.
for dir-locals use
```elisp
((python-mode .
              ((eval . (lsp-register-custom-settings '(("pyls.plugins.jedi.extra_paths" ["/your/path"])))))))
```

**Comment by kinredon** [comment]
I use this in dir-locals:
```
((python-mode .
              ((eval . (lsp-register-custom-settings '(("pyls.plugins.jedi.extra_paths" ["/Users/kinredon/Documents/github/kinredon/UDAOD/lib"])))))))
```

`C-x C-e` to eval, but found:
```
Invalid function: (python-mode (eval lsp-register-custom-settings(quote (("pyLs plugins. jedi. extra_paths"["/Users/kinredon/Documents/github/kinredon/UDAOD/Lib"))))
```

**Comment by mpanarin** [comment]
@kinredon please read [emacs documentation on dir-locals](https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html)
