### ISSUE TITLE
can't indent scala code.

### ISSUE THREAD

**Issue by madper** [emacs-lsp/lsp-mode#1969]
**Describe the bug**
Every time I press `Enter` an error message shows up. And a newline without indent created. 
```
lsp--on-type-formatting: Wrong type argument: sequencep, #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("textDocument" (:uri "file:///home/madper/source/tgf/src/main/scala/Main.scala") "options" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("tabSize" 2 "insertSpaces" t ...)) ...)) [2 times]
```

**To Reproduce**
Simply create a new project with `sbt new scala/hello-world.g8` could reproduce it.

**Expected behavior**
Indent without error message.

**Which Language Server did you use**
`lsp-metals`

**OS**
Archlinux

```
metals-emacs --version
metals 0.9.2+32-766ec242-SNAPSHOT

# Note:
#   supported Scala versions: 0.24.0, 0.24.0-RC1, 0.25.0, 0.25.0-RC2, 2.11.12, 2.12.10, 2.12.11, 2.12.12, 2.12.8, 2.12.9, 2.13.0, 2.13.1, 2.13.2, 2.13.3
```

**Error callstack**
```
Debugger entered--Lisp error: (wrong-type-argument sequencep #<hash-table equal 2/65 0x157297231a59>)
  append(#<hash-table equal 2/65 0x157297231a59> (:ch "\n" :position (:line 4 :character 0)))
  lsp--on-type-formatting("\n" ["\""])
  #f(compiled-function () #<bytecode 0x1e0148181993>)()
  self-insert-command(1)
  newline(nil 1)
  funcall-interactively(newline nil 1)
  call-interactively(newline nil nil)
  command-execute(newline)
```

**Comment by ericdallo** [comment]
@kurnevsky know something about it?

**Comment by kiennq** [comment]
Seems to be my fault, will fix it

**Comment by madper** [comment]
Howdy @kiennq ,

**Comment by yyoncho** [comment]
@madper can you delete lsp-mode, restart emacs and install it again?

**Comment by madper** [comment]
@yyoncho  Thanks a lot! I just found scala-mode is not the only mode that can't enable lsp. So I do believe it's not a regression issue caused the scala related fix. I'd try to re-install it. Thanks a lot!

**Comment by madper** [comment]
Reinstall fixes all the problem. Thanks tons!

**Comment by yyoncho** [comment]
@leungbk FTR now lsp-mode update will fail due to the fact that the macro is defined in lsp-mode.el but package.el first bytecompiles lsp-eslint.el. A potential solution is to move all macro calls in lsp-mode.el. Probably there is an alternative solution, but I got nothing in my elisp toolbox.

**Comment by leungbk** [comment]
@yyoncho Are you talking about the `lsp-make-interactive-code-action` macro? `lsp-defun` is used in `lsp-eslint` and runs with no problems; I'm guessing that simply moving `lsp-make-interactive-code-action` there won't solve the issue? How can I look at the compilation order produced with package.el?

**Comment by yyoncho** [comment]
> lsp-defun is used in lsp-eslint and runs with no problems; 

The issue is not the macro itself, but the fact that the macro is introduced in the same version in which it is is used in another file. In this case, when lsp-eslint is bytecompiled it performs `(require 'lsp-mode)` but lsp-mode is loaded so this is NOP. So, the macro stays undefined and the byte compiler fails.

> How can I look at the compilation order produced with package.el?

I don't know. I guess it is alphabetical.
