### ISSUE TITLE
Run lsp-mode in Tramp buffers

### ISSUE THREAD

**Issue by jaelsasser** [emacs-lsp/lsp-mode#197]
I've been poking around a bit at `lsp-mode` to see what it would take to [integrate it with Tramp](https://www.gnu.org/software/emacs/manual/html_node/tramp/Remote-processes.html). Blocker right now is that the call to `(make-process)` doesn't have any Tramp hooks.

Other packages use `start-file-process` to pick up Tramp support, but that function doesn't support stderr-separation. Might need to get more creative for lsp-mode.

**Comment by phst** [comment]
Probably we should add a file name handler for `make-process` to Emacs core and Tramp, similar to what `start-file-process` does.

**Comment by MaskRay** [comment]
Will be nice to have this feature.

Has anyone ever used this?
```elisp
(defun lsp--make-tcp-connection (name command command-fn host port stderr)
```

**Comment by Yevgnen** [comment]
Any news on this?

**Comment by yyoncho** [comment]
I am not sure whether `start-file-process` could do the job. At this point I believe it is feasible to make this work by doing:

1. Use TCP LSP Client. When the such is not present use `nc` to pipe stdin/stdout as a TCP socket. 
2. Change lsp--path-to-uri and lsp--uri-to-path to handle tramp buffers.

https://github.com/emacs-lsp/lsp-mode/pull/528 blocks 1.

**Comment by yyoncho** [comment]
I will start working on this when I have time since this is the most up-voted issue.

**Comment by yyoncho** [comment]
PR at https://github.com/emacs-lsp/lsp-mode/pull/578
