### ISSUE TITLE
lsp-clients-clangd-executable issue in debian

### ISSUE THREAD

**Issue by Ergus** [emacs-lsp/lsp-mode#1973]
In Debian there is not clangd executable, there are either clangd-{6,7,8} But I have a sort of portable config, so hardcoding it by hand is "problematic". And for newer users is complex to determine how to customize this

I am wondering if `lsp-clients-clangd-executable` could be set by lsp dynamically in a smarter way. I mean, using something more or less like:

```
(defcustom lsp-clients-clangd-executable nil
  "The clangd executable to use.
Leave as just the executable name to use the default behavior of
finding the executable with `exec-path'."
  :group 'lsp-clangd
  :risky t
  :type 'file)
```
and somewhere in the initialization
```
(unless lsp-clients-clangd-executable
    (setq lsp-clients-clangd-executable (locate-file "clangd" exec-path '("" "-8" "-7" "-6") 1)))
```

Could work so far to determine the available versions of clangd out of the box for all users.

**Comment by yyoncho** [comment]
This sounds like a good improvement, willing to provide a PR?

**Comment by petr-tik** [comment]
This sounds like a great idea and it will prevent me from having to create brittle symlinks on my dev box too! 

May I suggest starting with "-10", "-9" to make sure people find the most recent version of clangd, if it is installed on their machine. 

> ```
> (unless lsp-clients-clangd-executable
>     (setq lsp-clients-clangd-executable (locate-file "clangd" exec-path '("" "-8" "-7" "-6") 1)))
> ```

**Comment by Ergus** [comment]
> This sounds like a good improvement, willing to provide a PR?

Hi:

I would be fine doing so, but the api is not vary documented. I think I can add the function in the `lsp-mode-hook` but I would expect a better place maybe more specific for the major-mode or that runs earlier only once?

Maybe there is something already in `make-lsp-client` to set a function to execute the first time the mode or the client is loaded?

Should I use ACTIVATION-FN, BEFORE-FILE-OPEN-FN, INITIALIZED-FN or AFTER-OPEN-FN?

**Comment by yyoncho** [comment]
You could write your logic in `lsp-clients--clangd-command` it is responsible for calculating the actual command to run.

**Comment by petr-tik** [comment]
looks like you can close this issue now?
