### ISSUE TITLE
Flycheck two indicators in modeline

### ISSUE THREAD

**Issue by ocelaiwo** [emacs-lsp/lsp-mode#1981]
I'm using Emacs 27.0.91 with lsp-mode and flycheck. It seems that lsp-mode adds a second flycheck report indicator in the modeline. using doom-modeline:
![image](https://user-images.githubusercontent.com/57271510/88976831-3313ee80-d2d6-11ea-97d7-d0d97c5240f9.png)
Using Emacs built-in modeline:
![image](https://user-images.githubusercontent.com/57271510/88976878-4d4dcc80-d2d6-11ea-9d8c-b60bf7804897.png)
I could not find a way to disable the second (yellow number 15) indicator.

**Comment by ericdallo** [comment]
You can disable it with `(setq lsp-modeline-diagnostics-enable nil)`
https://emacs-lsp.github.io/lsp-mode/page/main-features/#project-errors-on-modeline

**Comment by ericdallo** [comment]
I have also updated the docs: https://github.com/emacs-lsp/lsp-mode/commit/c81247c337b92445e33871b4f447afc870d104a2

**Comment by ocelaiwo** [comment]
Works, thank you!

**Comment by yyoncho** [comment]
IMO we should have a recipe to disable flycheck modeline as well. IMO lsp-mode's modeline is more useful for particular use cases because it can show the errors from the whole project.

**Comment by ericdallo** [comment]
We can have a mode and enable flag for flycheck integration like the other features
