### ISSUE TITLE
textDocument/hover is not sent after using enter to complete symbol.

### ISSUE THREAD

**Issue by tshu-w** [emacs-lsp/lsp-mode#1982]
This problem was exchanged at gitter and this issue is for record, so I ignored some checks.

**Describe the bug**
`textDocument/hover` is not sent after using enter to complete symbol.

**To Reproduce**
1. open an empty python file
2. enter some prefix of any function(e.g., print)
3. use `enter` to complete the function
4. `textDocument/hover` is not sent

If I enter the function name character by character, `textDocument/hover` will be sent.

**Expected behavior**
`textDocument/hover` is sent and eldoc help show correctly.

**Which Language Server did you use**
Mention which server/language did you use (e. g. lsp-python, lsp-ccls, lsp-java, etc)
Python, lsp-pyright/lsp-python-ms

**OS**
macOS 10.15.6

**Error callstack**
[completion.log](https://github.com/emacs-lsp/lsp-mode/files/5006634/completion.log)

[no_completion.log](https://github.com/emacs-lsp/lsp-mode/files/5006635/no_completion.log)

**Comment by yyoncho** [comment]
lsp-mode does not control when sending hover requests but we respond to eldoc. As a side note, it seems like there is nothing under the cursor after completion.
