### ISSUE TITLE
New company-lsp warning provokes error if company-mode is an autoload

### ISSUE THREAD

**Issue by jimblandy** [emacs-lsp/lsp-mode#1985]
In #1983, new code was introduced to warn the user that company-lsp is no longer supported. Unfortunately, this code assumes that if `company-mode` is `fboundp`, then the `company-backends` variable is bound, which is not true if `company-mode` is an autoload. This causes an error when attempting to enable `lsp-completion-mode`.

**Comment by ericdallo** [comment]
@kiennq willing to fix on this PR: https://github.com/emacs-lsp/lsp-mode/pull/1984?

**Comment by kiennq** [comment]
@jimblandy Can you check if #1984 resolve your issue?

**Comment by jimblandy** [comment]
@kiennq Yes, it seems to fix the problem.
