### ISSUE TITLE
Flycheck not update after change conda env

### ISSUE THREAD

**Issue by wztdream** [emacs-lsp/lsp-mode#1987]
Hi,
I use spacemacs, and use lsp, python and conda layer. 

Here is the issue:
I have two conda envs, one is for python2, the other is for python3. Suppose I have a python file `a.py` follow python2 syntax, and current env is for python3, so there are some syntax errors highlights, then I switch to conda env for python2, now `a.py` can run correctly, but there all still error highlights. **It seems the flycheck not update after switch the env**, although the python interpreter have switched to python2 successfully. 

More info: If I terminate `mspyls` manually, by `SPC a p d`, then the `mspyls` will restart, then all the error highlight is gone. 

May be you can add a function to update the flycheck after switch the env?

**Comment by yyoncho** [comment]
lsp-mode is not responsible for that. lsp-mode is a frontend for language server and it displays what the server shows. lsp-mode does not know what conda is. If you switch your environment you should restart the server to pick that up.
