### ISSUE TITLE
Remove lsp-flycheck

### ISSUE THREAD

**Issue by topisani** [emacs-lsp/lsp-mode#200]
flycheck integration should be moved to [lsp-ui](https://github.com/emacs-lsp/lsp-ui) as soon as that is up and running and on melpa. Are there any other features that should go there?

**Comment by MaskRay** [comment]
Bump. https://github.com/emacs-lsp/lsp-ui/blob/master/lsp-ui-flycheck.el it more up-to-date while `lsp-flycheck.el` brings confusion to users.  https://github.com/syl20bnr/spacemacs/pull/10211
