### ISSUE TITLE
json-serialize does not encode list like json-encode

### ISSUE THREAD

**Issue by wyuenho** [emacs-lsp/lsp-mode#2008]
**Describe the bug**
In [`lsp--json-serialize`](https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el#L2501-L2509), lsp-mode naively replaces `json-encode` with `json-serialize` and ended up giving surprising results when using `lsp-configuration-section` to configure client `:initialization-options`. According to the docstring, `json-serialize` and `json-parse-*` only process vectors, so if some of the initialization options are lists, an error like the following will result:

```
Debugger entered--Lisp error: (wrong-type-argument symbolp "foo")
   json-serialize(("foo" "bar")) 
```

**To Reproduce**
```
(defvar some-lsp-server-test '("foo" "bar))

(lsp-register-custom-settings
  '(("some-lsp-server.test" some-lsp-server-test)))

...
;; Client config

:initialization-options (lambda () (lsp-configuration-section "some-lsp-server"))
...
```

**Expected behavior**
Options that are lists should be encoded without trouble just like `json-encode`.

**Comment by kiennq** [comment]
This is currently **by design** for `json-serialize`.

We can try to automatically detect and convert list to vector but, I think we want to squeeze every possible perf for json serialization in `lsp-mode` too, thus there's no such automatic conversion/checking yet.

**Comment by wyuenho** [comment]
Are you telling me lsp-mode expects client configs to use vectors instead of lists on purpose?

**Comment by kiennq** [comment]
Yes. Is there anything wrong with that?
Unless `json-serialize` can support list encoding upstream too.

**Comment by yyoncho** [comment]
There were multiple issues related to old json.el implementations and one of them was list serialization. They are fixed/removed in json.c - one of the things is that `list` is always json map and the only structure that represents json array is elisp array. It does not make sense to reintroduce the heuristic applied by json.el in lsp-mode code to make json.c and json.el comparable.

**Comment by wyuenho** [comment]
> Yes. Is there anything wrong with that?

Take a look at this [PR to lsp-jedi](https://github.com/fredcamps/lsp-jedi/pull/5/files). There are server initialization options that expect a list of strings to be serialized into JSON array. Now, the customization `repeat` type doesn't return a vector, so in order to translate this neatly custom-settings blocks to initialization options, I either have to manually construct the entire map or hack around this json-serialize problem by using the old elisp-based `json-encode` and reading it back out with the new `json-read-from-string` again. Why can't `(lsp-configuration-section)` just do it automatically?

I understand for most operations, performance and memory consumption is a concern, but initialization of a server is only done once per project, so I don't understand why this limitation is leaked all the way up to the client authors instead of nicely abstracted by lsp-mode.

**Comment by wyuenho** [comment]
The funny thing is, if I were to test this solely on emacs 26, just returning the lists directly from `lsp-configuration-section` would have worked without the json encode and read, and I wouldn't know about this issue until it's breaks lsp-jedi on a bunch of people running emacs 27.

**Comment by yyoncho** [comment]
And how are you going to send json's `[]` for `(repeat string)`? 

FTR the correct fix in lsp-jedi is to use `lsp-string-vector` for all `(repeat string)`. In the first place, the issue is caused by the fact that the settings are written manually instead of using `lsp-generate-settings.el` which inserts the correct defcustom types.

**Comment by wyuenho** [comment]
> And how are you going to send json's [] for (repeat string)?

Like the PR, `(json-parse-string (json-encode ...))`

> the correct fix in lsp-jedi is to use lsp-string-vector for all (repeat string)

That type is just an alias for sexp. What even is the point of using customize when you are asking people to write LISP?

> lsp-generate-settings.el

What is this and how to use it? Are there docs?

**Comment by yyoncho** [comment]
> Like the PR, (json-parse-string (json-encode ...)), it's not ideal, hence this issue...

that won't help - you will need elisp's vector to represent json empty list - this is the only way to do that. And as a side note, parse/encode are not symmetrical. 

> That type is just an alias for sexp. What even is the point of using customize when you are asking people to write LISP?

Fair point, I guess you may open a feature request for that. We will reach emacs-devel for guidance here. I believe we could build better customize dialog.


> What is this and how to use it? Are there docs?

https://emacs-lsp.github.io/lsp-mode/page/adding-new-language/

**Comment by wyuenho** [comment]
> you will need elisp's vector to represent json empty list

You have hacks in `lsp-configuration-section` to filter out non-boolean nil values. Not a big deal.

> I believe we could build better customize dialog.

Yes. You can mostly copy and paste the `editable-list` widget type from `wid-edit.el`, and change all the list-specific calls to vector.

That script won't help here. Not all language servers are written in Node.

**Comment by yyoncho** [comment]
> Yes. You can mostly copy and paste the `editable-list` widget type from `wid-edit.el`, and change all the list-specific calls to vector.

We may try that. 

> Finally, that script won't help here. Not all language servers are written in Node.

Usually, the servers have better supported vscode client. package.json comes from that package.
