### ISSUE TITLE
`lsp-completion--capf-exit-fn` deletes more characters than it should 

### ISSUE THREAD

**Issue by yangyingchao** [emacs-lsp/lsp-mode#2009]
**Describe the bug**
 I think `lsp-completion--capf-exit-fn` deletes more characters than it should.

**To Reproduce**
1.  I want to input `fff` before `int_a`.
![屏幕快照 2020-08-07 下午2 28 39](https://user-images.githubusercontent.com/990329/89616165-7c59d480-d8ba-11ea-8006-207d951069a6.png)
2. I typed `f` after `a.`, `company-capf` shows proper candidates, great.
![屏幕快照 2020-08-07 下午2 28 56](https://user-images.githubusercontent.com/990329/89616171-7e239800-d8ba-11ea-961e-93a584d7727c.png)
3. after I hit `ENTER`,  candidate is inserted, but it deleted more characters than it should (with `.int_a` deleted)...
![屏幕快照 2020-08-07 下午2 29 05](https://user-images.githubusercontent.com/990329/89616174-7ebc2e80-d8ba-11ea-8d13-200f3e9940d2.png)

I added some logs in company-capf.el , everything is OK before `lsp-completion--capf-exit-fn` is called. So I guess it might be `lsp-completion--capf-exit-fn` who deleted `.int_a`

Thanks.
Regards.

**Comment by yyoncho** [comment]
This is what the server has sent to us. Once protocol supports that we will have the option either to replace or to insert: see https://github.com/microsoft/language-server-protocol/issues/793

**Comment by yangyingchao** [comment]
oh, good to know, thanks.
