### ISSUE TITLE
emacs freezy

### ISSUE THREAD

**Issue by ghost** [emacs-lsp/lsp-mode#201]
Hi,
When I use emacs with hie and haskell-lsp then I get an error message (only just one file):

_2017-11-28 06:47:30.437606502 [ThreadId 8] - <--2--{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":1,"message":"haskell-lsp:no handler for. Object (fromList [("jsonrpc",String "2.0"),("params",Object (fromList [("reason",Number 2.0),("textDocument",Object (fromList [("uri",String "file:///home/lbodnar/Projects/Haskell/WebAdmin.haskell/src/Db.hs")]))])),("method",String "textDocument/willSave")])"}}2017-11-28 06:47:30.437606502 [ThreadId 8] - <--2--{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":1,"message":"haskell-lsp:no handler for. Object (fromList [("jsonrpc",String "2.0"),("params",Object (fromList [("reason",Number 2.0),("textDocument",Object (fromList [("uri",String "file:///home/lbodnar/Projects/Haskell/WebAdmin.haskell/src/Db.hs")]))])),("method",String "textDocument/willSave")])"}}__

Sometimes emacs is freezy and I have to restart it.
What causes the problem ?

**Comment by vibhavp** [comment]
@alanz any idea?

**Comment by hubola** [comment]
There is a well working emacs-lsp and lsp-haskell for hie ? Maybe the problem is that my lsp-haskell isn't up to date to the hie ? I cloned emacs-lsp and lsp-haskell from the github.

**Comment by alanz** [comment]
Current hie master deals with the "willSave" message.

But there are still some delays where synchronous messaging is used but the backend takes a long time.

**Comment by hubola** [comment]
Thanks the answers. I currently use the master branch.
I try to get more information from the problem.

**Comment by alanz** [comment]
make sure that you have run stack install, and are running the version you expect.

If you edit `hie-vscode.sh` (should be in `~/.vscode/extensions/alanz.vscode-hie-server-0.0.5/hie-vscode.sh`) and uncomment one of the options with logging, the first line of the log file it produces at `/tmp/hie.log` will have the version of hie you are running. Check that the commit is what you expect.

**Comment by alanz** [comment]
Update

I cleared the data, let it connect on wifi and sync to my node (@alanz feed only). No crash.

Followed @alanz, syncing FOAF.

It went fine, but eventually crashed with

```
11-29 13:56:34.835 10316 10340 I ReactNativeJS: 'VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc.', { dt: 488038, prevDt: 7576, contentLength: 16416.76171875 }
11-29 13:56:57.103 10316 10351 V nodejs  : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxCONNECT { host: '198.211.122.115',
11-29 13:56:57.103 10316 10351 V nodejs  :   port: 8008,
11-29 13:56:57.103 10316 10351 V nodejs  :   key: '@7snGJQdhw12HrUTzeaWMfxuBO8c2U75sG7sNkeEfYOw=.ed25519',
11-29 13:56:57.103 10316 10351 V nodejs  :   source: 'pub',
11-29 13:56:57.104 10316 10351 V nodejs  :   announcers: 1,
11-29 13:56:57.104 10316 10351 V nodejs  :   duration: null }
11-29 13:57:27.855 10316 10351 V nodejs  : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxCONNECT { host: 'eu6.woll-e.net',
11-29 13:57:27.855 10316 10351 V nodejs  :   port: 8008,
11-29 13:57:27.855 10316 10351 V nodejs  :   key: '@H1j0ybFVLhnfYx47DekUadGysJPOaOAWtKFx5Le4+hQ=.ed25519',
11-29 13:57:27.855 10316 10351 V nodejs  :   source: 'pub',
11-29 13:57:27.855 10316 10351 V nodejs  :   announcers: 1,
11-29 13:57:27.855 10316 10351 V nodejs  :   duration: null }
11-29 13:58:23.009 10316 10351 V nodejs  : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxCONNECT { host: 'ssb.nootch.net',
11-29 13:58:23.010 10316 10351 V nodejs  :   port: 8008,
11-29 13:58:23.010 10316 10351 V nodejs  :   key: '@1ZCF+Z9cUjcXGHkOPd5jNnoiuu3VJn+o6L8XEliV6Cs=.ed25519',
11-29 13:58:23.010 10316 10351 V nodejs  :   source: 'pub',
11-29 13:58:23.010 10316 10351 V nodejs  :   announcers: 2,
11-29 13:58:23.010 10316 10351 V nodejs  :   duration: null }
11-29 13:58:33.509 10316 10351 V nodejs  : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxCONNECT { host: 'freedombone.net',
11-29 13:58:33.509 10316 10351 V nodejs  :   port: 8008,
11-29 13:58:33.509 10316 10351 V nodejs  :   key: '@aCjZYf6p0k7VINLoXF2J361VLW7SX7SzzBuiE4JoQEQ=.ed25519',
11-29 13:58:33.510 10316 10351 V nodejs  :   source: 'pub',
11-29 13:58:33.510 10316 10351 V nodejs  :   announcers: 1,
11-29 13:58:33.510 10316 10351 V nodejs  :   duration: null }
11-29 13:59:07.607 10316 10351 V nodejs  : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxCONNECT { host: 'h.transitiontech.ca',
11-29 13:59:07.607 10316 10351 V nodejs  :   port: 8008,
11-29 13:59:07.607 10316 10351 V nodejs  :   key: '@+MXnwq3uxVq6ey1tZsdhD6d7ZEauA7eVJy0NgzYZ/io=.ed25519',
11-29 13:59:07.607 10316 10351 V nodejs  :   source: 'pub',
11-29 13:59:07.607 10316 10351 V nodejs  :   announcers: 2,
11-29 13:59:07.607 10316 10351 V nodejs  :   duration: null }
11-29 13:59:26.271 10316 10351 V nodejs  : CONNECT { host: '54.144.208.18',
11-29 13:59:26.272 10316 10351 V nodejs  :   port: 8008,
11-29 13:59:26.272 10316 10351 V nodejs  :   key: '@/oBboQ7B5kWuDhjsNfIpQJccKO1irnS679riDR3rdTw=.ed25519',
11-29 13:59:26.272 10316 10351 V nodejs  :   source: 'pub',
11-29 13:59:26.272 10316 10351 V nodejs  :   announcers: 1,
11-29 13:59:26.272 10316 10351 V nodejs  :   duration: null }
11-29 13:59:27.080 10316 10341 E AndroidRuntime: java.lang.RuntimeException: Cannot add a child that doesn't have a YogaNode to a parent without a measure function! (Trying to add a 'ReactVirtualTextShadowNode' to a 'LayoutShadowNode')
11-29 13:59:27.080 10316 10341 E AndroidRuntime: 	at com.facebook.react.uimanager.ReactShadowNode.addChildAt(ReactShadowNode.java:181)
11-29 13:59:27.271  1388  8750 W ActivityManager: Scheduling restart of crashed service com.mmmmm/com.staltz.reactnativenode.RNNodeService in 1000ms
```

Note

```
11-29 13:56:34.835 10316 10340 I ReactNativeJS: 'VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc.', { dt: 488038, prevDt: 7576, contentLength: 16416.76171875 }
```

This is different from the prior one.

My working theory is that the original crash is caused by me editing the profile, which I have not done yet for this test.

**Comment by hubola** [comment]
Ok, I'll rebuild it with stack again but I use emacs intead of vscode.
Is it working well with vscode ? But I can't use vscode because of the electron uifw not working on wayland...

**Comment by alanz** [comment]
emacs should be generating that log by default.

**Comment by hubola** [comment]
I rebuilt the hie and after the stack install it's working well.
I got an error a lot: error in process filter: End of buffer.
What causes it ? It make a lot of break by typing.

**Comment by myrgy** [comment]
Guys, emacs 26 has threads support. Are you going to use this ability to make requests asynchronous?
It might be great in case, when for example lsp daemon has some lags.

**Comment by yyoncho** [comment]
Please retest with latest lsp.el. The issue should be already fixed.
