### ISSUE TITLE
lsp-mode not work at rust project tests folder

### ISSUE THREAD

**Issue by C1tas** [emacs-lsp/lsp-mode#2029]
**Describe the bug**
lsp-mode not work in rust project `tests` folder

**To Reproduce**
1. `lsp-start-plain.el` add `rust-mode`
2. open lsp_rust_tests project
3. create a new file like`tests/add_tests.rs`
4. autocomplete won't work

the repo
`https://github.com/C1tas/lsp_rust_tests`

**Expected behavior**
autocomplete works in tests folder

**Which Language Server did you use**
Mention which server/language did you use (e. g. lsp-python, lsp-ccls, lsp-java, etc)
lsp-rust(rust-analyzer)

**OS**
Which os do you use?
macos 

**Error callstack**
no error

**config file use**
`lsp-start-plain.el` add `rust-mode`

**Comment by kiennq** [comment]
Did you add correct workspace folder for tests folder?
Can you also take the server trace with `lsp-toggle-trace-io` and `lsp-workspace-show-log`

**Comment by C1tas** [comment]
ok, by using `lsp-toggle-trace-io`  i found no `textDocument/completion` for my new file. old file works well

**Comment by flodiebold** [comment]
Which rust-analyzer version are you using?

**Comment by C1tas** [comment]
1. copy from vscode rust-analyzer 2b0c2f6
2. build from souce rust-analyzer e96bfd8

**Comment by flodiebold** [comment]
Please check whether restarting rust-analyzer (with `lsp-workspace-restart`) fixes the problem. Recent RA versions should automatically reload the workspace when new integration test files are added, but maybe something's not working correctly there.

**Comment by C1tas** [comment]
`lsp-workspace-restart` may works but it will show
```
server rust-analyzer:[port] exited with status exit.Do you want to restart it?
```

when i confirm it . The whole workspace exit. I need to run `M-x` `lsp` to active rust-analyzer

**Comment by C1tas** [comment]
I have test the same bin file within vscode rust-analyzer plugin。

In vscode autocomplete works well in `tests/newfile.rs`

In lsp-mode need to shutdown the workspace, then restart `lsp`.

As i see, is there has some different in lsp-mode rust logic?

**Comment by yyoncho** [comment]
I confirm the issue. I will investigate.

**Comment by yyoncho** [comment]
Ok, I got it. It is rust-analyzer bug. The difference between lsp-mode and
vscode is that when you create a file in emacs it does not exist on the disk. To
workaround the issue you may do `touch fooname.rs` and then open `fooname.rs`
and completion it will work.

Here it is quote from the spec:

> The document open notification is sent from the client to the server to signal newly opened text documents. The document's content is now managed by the client and the server must not try to read the document's content using the document's Uri. Open in this sense means it is managed by the client.

cc @flodiebold @matklad

**Comment by flodiebold** [comment]
Hmm I don't think that's currently fixable in rust-analyzer -- adding a new integration test changes the project structure, which we get from `cargo metadata`, which doesn't see files that don't exist on the file system yet. Until we can call `cargo metadata` with a virtual file system, you'll at least need to save the file.

**Comment by yyoncho** [comment]
I will provide a fix on the client. It will touch the file when it does not exist and add a log that it is doing that and also it will have an option to turn off this behavior and act like vanilla emacs. IMO this is the most practical solution considering that there are other servers with that issue(ts-ls). IIRC there were servers that that did a fix but IMO better to be practical and conform to VScode behavior...

**Comment by yyoncho** [comment]
I have already pushed client side fix(we ensure that file is present before starting the server).
