### ISSUE TITLE
[3.16] [Completion]  Support insertReplaceSupport

### ISSUE THREAD

**Issue by kiennq** [emacs-lsp/lsp-mode#2032]
https://github.com/microsoft/language-server-protocol/issues/846
and 
https://github.com/microsoft/language-server-protocol/blob/gh-pages/_specifications/specification-3-16.md#completion-request-leftwards_arrow_with_hook

**Comment by yyoncho** [comment]
CC @dgutov

**Comment by dgutov** [comment]
If I understand the new feature correctly, it's something I've been thinking of for Company as well.

Not sure if choosing the behavior depending on the key would work for us, though (like described in https://github.com/microsoft/language-server-protocol/issues/793).

**Comment by yyoncho** [comment]
> Not sure if choosing the behavior depending on the key would work for us, though

Why and what is the alternative?

**Comment by dgutov** [comment]
First of all, how do you pass which key was used through `completion-at-point-functions`?

Second, TAB or Enter seems like a personal preference and not declaration of intent. But I'm open to other opinions.

The alternative seems to be a user option. The approach that is also taken by VS Code.

**Comment by kiennq** [comment]
> First of all, how do you pass which key was used through `completion-at-point-functions`?

Can we re-use the `status` parameter in `:exit-function` for that?

**Comment by yyoncho** [comment]
> First of all, how do you pass which key was used through `completion-at-point-functions`?

this-command?

About the keybindings it is really up to the user, IMO RET and C-RET (I think this is what was mentioned for IDEA) are acceptable defaults.

**Comment by dgutov** [comment]
> Can we re-use the status parameter in :exit-function for that?

Probably not. The different values values correspond to different phases in the work of `M-x completion-at-point`. And that function probably really wants the "replace" behavior, always (at least the built-in completion functions behave that way).

> this-command?

That seems to preclude user extensibility. If you're willing to hardcode `company-` in the implementation anyway, it's better to make the choice based on some new variable?

> About the keybindings it is really up to the user,

My question is whether that approach will satisfy the majority of them.

> IMO RET and C-RET (I think this is what was mentioned for IDEA) are acceptable defaults.

Do you have a quote? My reference says different. I don't have IDEA installed.
