### ISSUE TITLE
Missing space in mode line

### ISSUE THREAD

**Issue by muirdm** [emacs-lsp/lsp-mode#2039]
After updating recently there is no longer a space after the code action mode line (missing space after the light bulb):
![Screen Shot 2020-08-10 at 11 36 15 AM](https://user-images.githubusercontent.com/11356572/89817970-d9919800-dafd-11ea-90f1-df3fac96d113.png)

Also I am having a heck of a time trying to disable the mode line diagnostic info. I set `(setq lsp-modeline-diagnostics-enable nil)` but as you see in the screenshot the diagnostic numbers still appear. I restarted Emacs and one buffer no longer shows diagnostics, but this buffer still does.

**Comment by ericdallo** [comment]
That was proposital thinking that each node on the modeling should add a prefix string. But I don't know if each node follow this pattern...

what do you think @kiennq ?

**Comment by muirdm** [comment]
Currently I'm using doom modeline with a config like this:

```
(doom-modeline-def-modeline 'main
  '(bar matches buffer-info remote-host buffer-position selection-info)
  '(bar space misc-info debug lsp minor-modes major-mode process vcs checker))
```

I have a `space` between the purple `bar` and the `misc-info`, but maybe instead that space needs to be in the clock segment?

This is my current global-mode-string:
```
((t
  (:eval lsp-modeline--code-actions-string))
 (t
  (:eval
   (-keep #'lsp--workspace-status-string
          (lsp-workspaces))))
 (t
  (:eval
   (lsp-modeline--diagnostics-update-modeline)))
 ((t lsp-java-progress-string))
 display-time-string)
```

**Comment by kiennq** [comment]
@muirdm Yes, I think you will need to add a space in the clock segment instead.
The reason we adding a prefix space only is to follow with pattern that's already inside `lsp-mode`, so that the item on mode line is showing up predictably.

Also, it seems that mode line diagnostic info is indeed disabled, since from `global-mode-string`, that info should be **behind**  code action.
What's the value of `global-mode-string` in the buffer that mode line diagnostic still showing?

**Comment by muirdm** [comment]
When I turn off my fancy modeline and use the default, I still see no space between the light bulb and the clock:
![Screen Shot 2020-08-10 at 6 57 02 PM](https://user-images.githubusercontent.com/11356572/89848565-48411680-db3b-11ea-825a-bc8cde31b351.png)

> What's the value of global-mode-string in the buffer that mode line diagnostic still showing?
That was the value from the buffer. Something must be funny with my config. I'll open a separate issue if it persists.

How do you guys not having a missing space? Is my modeline weird? Do you not have other stuff in global-mode-string?

My global-mode-string is:
```
((t
  (:eval
   (-keep #'lsp--workspace-status-string
          (lsp-workspaces))))
 (t
  (:eval
   (lsp-modeline--diagnostics-update-modeline)))
 (t
  (:eval lsp-modeline--code-actions-string))
 ((t lsp-java-progress-string))
 display-time-string)
```

**Comment by kiennq** [comment]
Can you add a space before `display-time-string`?

We have to add space either prefix or suffix for the mode line for user to easily including each segments.
From what I see, most of minor mode adopting practice of adding space prefix to actually mode line (for example: `company-mode`, `lsp-mode`, `flycheck-mode` ...).

**Comment by muirdm** [comment]
Ok, I'll figure something out.
