### ISSUE TITLE
"textDocument/definition not supported" for "lsp-find-definition" in c++-mode

### ISSUE THREAD

**Issue by Hi-Angel** [emacs-lsp/lsp-mode#2060]
**Describe the bug**

Following installation instructions for lsp-mode, and the executing a `lsp-find-definition` results in

```
lsp--send-request-async: The connected server(s) does not support method textDocument/definition.
```

It is possible I didn't configure something, but then again I followed the docs, so that means that this "something" is missing there.

Offhand, it is strange that the [languages page](https://emacs-lsp.github.io/lsp-mode/page/languages/) lists two C++ servers, but none of them require executing any LISP code *(only installing the clangd or ccls binary)*. I mean, which one would get chosen if both binaries are present…?

**To Reproduce**

1. In terminal:
    ```
    $ cat test.cpp
    void foo(){}

    int main() {
        foo();
    }
    $ emacs -Q test.cpp
    ```

2. In the Emacs:
     1. <kbd>M</kbd>-<kbd>:</kbd> <kbd>(package-initialize)</kbd>
     2. <kbd>M</kbd>-<kbd>:</kbd> <kbd>(require 'lsp-mode)</kbd>
     2. <kbd>M</kbd>-<kbd>:</kbd> <kbd>(require 'lsp-clients)</kbd>
     3. <kbd>M</kbd>-<kbd>:</kbd> <kbd>(lsp-mode)</kbd>
3. Put the caret over `foo();` line and press <kbd>M</kbd>-<kbd>x</kbd> <kbd>lsp-find-definition</kbd>

**Expected behavior**

Caret would jump to the `void foo(){}` declaration on the first line.

**Actual behavior**

Error:

```
lsp--send-request-async: The connected server(s) does not support method textDocument/definition.
To find out what capabilities support your server use ‘M-x lsp-describe-session’ and expand the capabilities section
```

Executing <kbd>M</kbd>-<kbd>x</kbd> <kbd>lsp-describe-session</kbd> as suggested pops up an empty buffer.

**Which Language Server did you use**

I don't think it even tries to start one, but I'd expected it to be `clangd`

**OS**

Archlinux.

**Error callstack**

<details>
    <summary>*Backtrace*</summary>

```
Debugger entered--Lisp error: (error "The connected server(s) does not support method te...")
  signal(error ("The connected server(s) does not support method te..."))
  error("The connected server(s) does not support method %s..." "textDocument/definition")
  lsp--send-request-async((:jsonrpc "2.0" :method "textDocument/definition" :params (:textDocument (:uri "file:///tmp/test.cpp") :position (:line 3 :character 6))) #f(compiled-function (res) #<bytecode 0x2ed737ff7ed00>) detached #f(compiled-function (err) #<bytecode 0x1e0aafa3d4279>) nil nil :sync-request)
  lsp-request-async("textDocument/definition" (:textDocument (:uri "file:///tmp/test.cpp") :position (:line 3 :character 6)) #f(compiled-function (res) #<bytecode 0x2ed737ff7ed00>) :error-handler #f(compiled-function (err) #<bytecode 0x1e0aafa3d4279>) :no-merge nil :mode detached :cancel-token :sync-request)
  lsp-request("textDocument/definition" (:textDocument (:uri "file:///tmp/test.cpp") :position (:line 3 :character 6)))
  lsp-find-locations("textDocument/definition" nil :display-action nil)
  lsp-find-definition()
  funcall-interactively(lsp-find-definition)
  call-interactively(lsp-find-definition record nil)
  command-execute(lsp-find-definition record)
  execute-extended-command(nil "lsp-find-definition" nil)
  funcall-interactively(execute-extended-command nil "lsp-find-definition" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```
</details>

Regarding `*lsp-log*`, I haven't got one. Regarding `lsp-workspace-show-log`, it expects some parameter, but none I tried providing worked. Togglng workspace completion says `[No match]`.

**Version**

lsp-mode: 20200812.409
Emacs: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.17.3) of 2020-06-04

**Comment by yyoncho** [comment]
Use M-x lsp not M-x lsp-mode.

**Comment by Hi-Angel** [comment]
> Use M-x lsp not M-x lsp-mode.

Oh, indeed, thanks!
