### ISSUE TITLE
[discussion] - Move LSP clients to a clients folder

### ISSUE THREAD

**Issue by ericdallo** [emacs-lsp/lsp-mode#2067]
With the @elxbarbosa lsp clients migration, I wonder if we should move all `lsp-XXX.el` clients to a `clients` folder, this helps to have fewer files on repo's root, improving the repo readability for new users.
If so, we should open a PR first on Melpa changing the recipe to read a `clients` folder too then move the el files to it.

**Comment by ericdallo** [comment]
Do you see any problem with this approach @kiennq @yyoncho ?

**Comment by yyoncho** [comment]
Will this break the config of straight users?

**Comment by ericdallo** [comment]
No, we should keep the same variable names, just move the files to a new folder

**Comment by kiennq** [comment]
I do agree that split all clients into clients folder is better, make clearer file structures.

This will require update the current recipe for both MELPA, `straight.el`, `quelpa`, we should announce this as breaking change and only switch this to master once MELPA change has been merged.

**Comment by ericdallo** [comment]
Yes @kiennq, I was waiting for your opinions on this issue to open a Melpa PR adding the `clients` folder in the recipe.
How should we update straight.el and quelpa?

**Comment by kiennq** [comment]
> How should we update straight.el and quelpa?

Probably a big **BREAKING NEW** on the read me :smile:
Showing the example recipe for `straight.el` and `quelpa`, ask the user to update their recipe?

**Comment by ericdallo** [comment]
I see, do you think a blog post and add on the changelog would be enough? I'm not sure adding this to the readme, the website front page is the best approach but I understand the idea.

**Comment by kiennq** [comment]
Yes, we should make this clear for user who use custom recipe, whichever way is fine, even the FAQ.
Well, `quelpa` and `straight.el` user will be broken immediately after this update so they will come and check, hopefully

**Comment by ericdallo** [comment]
Yeah, we can add to FAQ too.
What you think so @yyoncho ?

**Comment by kiennq** [comment]
Also, I think `straight.el` maintain their own MELPA clone so probably change in MELPA will be reflected in `straight.el` soon.
`quelpa` is taking recipe from MELPA directly too.
This may not have that much affect as we think

**Comment by yyoncho** [comment]
Lets go ahead with this approach and see how it will go. For me having all the files on top level is not big issue, at least when accessing the files from emacs.

**Comment by ericdallo** [comment]
Yes, from emacs is not a problem indeed, my point is for users searching for things on the repo, go to the https://github.com/emacs-lsp/lsp-mode and take a look the bunch of files you need to scroll before reaching the readme

**Comment by ericdallo** [comment]
https://github.com/melpa/melpa/pull/7084

**Comment by ericdallo** [comment]
Done in https://github.com/emacs-lsp/lsp-mode/pull/2109
