### ISSUE TITLE
Completion stops working when upgrading from v7.0 to v7.0.1

### ISSUE THREAD

**Issue by fehmud** [emacs-lsp/lsp-mode#2075]
Hello everybody and thank you for this package.

I have a working installation of LSP Mode v7.0. If I upgrade to v7.0.1, completion stops working.

A difference that I have noticed is that the broken version displays more messages like "Cancelling textDocument/codeAction(35) in hook after-change-functions" in `*lsp-log*`. In particular, it does so when completion triggers.

I have tried deleting the `lsp-session-file`. Is there any other cached file that could be interfering?

I am using Emacs v26.3.

Thank you.

**Comment by yyoncho** [comment]
1. Delete your elpa dir, restart emacs and then install everything.
2. In case the issue still exists please populate the bug template.

**Comment by ericdallo** [comment]
Just a note that the latest release of lsp-mode is `7.1`

**Comment by kiennq** [comment]
Also Emacs 27.1 is out, recommend upgrade for full native json experience

**Comment by tianhongw** [comment]
I meet the same problem after update to latest version(emacs version is 27.1).  Re-install all packages doesn't work for me. @yyoncho 
```
Cancelling textDocument/documentLink(12) in hook post-command-hook
Cancelling textDocument/codeAction(11) in hook post-command-hook
Cancelling textDocument/documentLink(44) in hook after-change-functions
Cancelling textDocument/codeAction(43) in hook after-change-functions
```

**Comment by Blade6570** [comment]
@fehmud any updates? did u try the @yyoncho, @kiennq recommendations? I am facing similar problems and just to be sure that it works after reinstalling everything.

**Comment by fehmud** [comment]
@Blade6570 No, I didn't.  This is a low-priority issue for me at the moment, also because 7.0 works fine, so I am sticking to it.

**Comment by yyoncho** [comment]
Closing, please reopen if it reproduces after

> 1. Delete your elpa dir, restart emacs and then install everything.
> 2. In case the issue still exists please populate the bug template.
