### ISSUE TITLE
[task] Extraction of lsp-clients.el clients

### ISSUE THREAD

**Issue by elxbarbosa** [emacs-lsp/lsp-mode#2086]
Hi,

I just finished extracting all clients in the `lsp-clients.el` file and its tests, javascript, clangd, to a file to each of them.

_There are up to 15 PRs submitted!_ 

That yields a bigger issue that is synchronizing the efforts to merge each of those PRs.

Once one of those is merged all the other will require conflicts to be resolved.

If you will, I am up to do the boring part.

As it will be done, I will let for you all that know better the priority of the lsp-mode project 👍🏿 

PS: As observed [here](https://github.com/emacs-lsp/lsp-mode/pull/2084), the last one should be the removal of the lsp-clients.el file

**Comment by ericdallo** [comment]
Ok, let's try to follow this order of resolve conflict/merge as every PR conflict with each other:
- [ ] Agular  https://github.com/emacs-lsp/lsp-mode/pull/2054
- [ ] VimScript https://github.com/emacs-lsp/lsp-mode/pull/2055
- [ ] Nim https://github.com/emacs-lsp/lsp-mode/pull/2057
- [ ] PHP https://github.com/emacs-lsp/lsp-mode/pull/2058
- [ ] groovy https://github.com/emacs-lsp/lsp-mode/pull/2062
- [ ] kotlin https://github.com/emacs-lsp/lsp-mode/pull/2063
- [ ] fortran https://github.com/emacs-lsp/lsp-mode/pull/2068
- [ ] hack https://github.com/emacs-lsp/lsp-mode/pull/2069
- [ ] elixir https://github.com/emacs-lsp/lsp-mode/pull/2070
- [ ] purescript https://github.com/emacs-lsp/lsp-mode/pull/2071
- [ ] tex https://github.com/emacs-lsp/lsp-mode/pull/2073
- [ ] ocaml https://github.com/emacs-lsp/lsp-mode/pull/2077
- [ ] clangd https://github.com/emacs-lsp/lsp-mode/pull/2083
- [ ] remove lsp-clients https://github.com/emacs-lsp/lsp-mode/pull/2084

This will avoid need to tag someone every time a conflict is resolved

**Comment by elxbarbosa** [comment]
at work!

**Comment by elxbarbosa** [comment]
angular is ready!

**Comment by elxbarbosa** [comment]
[vimscript](https://github.com/emacs-lsp/lsp-mode/pull/2055) is ready

**Comment by elxbarbosa** [comment]
[nim](https://github.com/emacs-lsp/lsp-mode/pull/2057) is ready!

**Comment by elxbarbosa** [comment]
[php](https://github.com/emacs-lsp/lsp-mode/pull/2058/files) is up!

**Comment by elxbarbosa** [comment]
groovy is up

**Comment by elxbarbosa** [comment]
kotlin is up

**Comment by elxbarbosa** [comment]
fortran is up

**Comment by elxbarbosa** [comment]
hack is up

**Comment by elxbarbosa** [comment]
elixir is up

**Comment by elxbarbosa** [comment]
purescript is up.

**Comment by elxbarbosa** [comment]
tex is up

**Comment by elxbarbosa** [comment]
@ericdallo 
lsp-javascript is not in that todo list :/

**Comment by elxbarbosa** [comment]
javascript is up

**Comment by ericdallo** [comment]
Thanks for all the work done @elxbarbosa :)

**Comment by elxbarbosa** [comment]
@ericdallo 
Any grunt  work, just tag me :)
