### ISSUE TITLE
Consider dropping lsp-print-performance 

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#2111]
Seems like we do not need that functionality, most of the performance issues are solved by fixing the lsp-diagnose issues.

**Comment by muirdm** [comment]
I use the ServerTime output sometimes to get a quick idea of how long the server is taking to respond to certain commands. However I've found that measurement to not be very reliable, and there is too much output to sift through. I guess I wouldn't really miss lsp-print-performance, so 👍
