### ISSUE TITLE
c++ header file extension (.h) recognized as c.

### ISSUE THREAD

**Issue by lromor** [emacs-lsp/lsp-mode#2118]
Before logging the bug, please make sure that:

1. You are using the latest version of `lsp-mode` related packages.
2. You may also try reproduce the issue using clean environment using the following command:
   ``` bash
   emacs -q -l lsp-start-plain.el
   ```
   where `lsp-start-plain.el` could be downloaded from `https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el`.
   Alternatively, in will be great if you can reproduce the issue using [lsp-docker](https://github.com/emacs-lsp/lsp-docker/) which provides the minimal configurations for `lsp-mode` and ships with most of the language servers.
3. Check FAQ and Troubleshooting section (https://emacs-lsp.github.io/lsp-mode/page/faq/ and https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/)
4. Consider providing a minimal project to reproduce the issue with. Note that `lsp-mode` supports 30+ languages and the maintainers of the project are not familiar with all of the languages and a sample project + full steps to reproduce will help a lot.

**Describe the bug**
c++-mode is active. Lsp mode with clangd is unable to detect c++ mode, hence clangd treats the header file as a c header file instead of c++.

**To Reproduce**
create a .cc and .h file. Try to include <vector>

**Expected behavior**
Irony server works with this behavior out of the box.

**Which Language Server did you use**
clangd

**OS**
linux debian

**Error callstack**
If there is an error please reproduce the issue with `toggle-debug-on-error` and after setting `lsp-print-io` to t, and then include the callstack and attach the content of `*lsp-log*` buffer and the content of the server log(use `lsp-workspace-show-log`)

If `emacs` hangs please do `M-x` `toggle-debug-on-quit` and then do `C-g` when emacs hangs and include the callstack as part of the issue report.

``` emacs-lisp
(setq lsp-print-io t)
```

**Comment by ericdallo** [comment]
@yyoncho is tehere any way to know if we should start c++ and no c server as `.h` files exist for both languages?

**Comment by yyoncho** [comment]
I don't think that there is lsp-mode issue here. Most likely @lromor does not have the correct compile_commands.json. (cc @sebastiansturm or @danielmartin )

**Comment by danielmartin** [comment]
@lromor Could you provide more information about this issue? When you say "clangd treats the header file as a c header file instead of c++", what do you mean exactly? Do you see compilation errors in your header file? Can you provide a simple C++ project to reproduce the problem?

**Comment by lromor** [comment]
@danielmartin , I just made an empty folder with a test.cc and test.h.
In test.cc:

![image](https://user-images.githubusercontent.com/1597330/91456409-851f4400-e883-11ea-9b6a-58dc7e901269.png)

in test.h, a simple test to autocomplete `#include <vector>`

![image](https://user-images.githubusercontent.com/1597330/91456540-b0a22e80-e883-11ea-946b-095c57344ab2.png)

@yyoncho 
I don't use any compile_commands.json. I have plain Makefiles. I do use in *other projects* compile_flags.txt

**Comment by lromor** [comment]
If I rename the header in `test.hpp` I get:

![image](https://user-images.githubusercontent.com/1597330/91457371-9288fe00-e884-11ea-93d9-c478d367a5f2.png)

Showing that is indeed a name extension issue.

**Comment by danielmartin** [comment]
It works correctly for me. I'm using clangd from today's `master` branch, if that makes any difference. It works even with Emacs default behaviour (assume .h files are C code, not C++).

I'd try to reproduce the problem in an extension-less Emacs (see `lsp-start-plain.el`). But the problem may be in the clangd configuration itself. I see you are using GNU/Linux. We've seen a few problems where clangd has trouble finding the C++ standard library on those systems.

It may be a good idea to open a clangd issue here: https://github.com/clangd/clangd/issues You should attach the clangd logs you can get with `(setq lsp-print-io t)`.

**Comment by lromor** [comment]
Using the `lsp-start-plain.el` I noticed that it works fine. At this point there must be some wrong configuration in doom emacs. Thank you!

**Comment by yyoncho** [comment]
Closing based on the previous comment.
