### ISSUE TITLE
lsp-mode should never stop user from editing their file

### ISSUE THREAD

**Issue by gnufied** [emacs-lsp/lsp-mode#2120]
Sometimes when there are errors in lsp-server then it is very hard to edit the files.  The cursor keeps jumping to mode-line and changing users focus. We should perhaps instead log the message rather than echoing in echo area and changing cursor focus?

```
error in process filter: Quit [2 times]
Quit
LSP :: Error from the Language Server: inconsistent vendoring (Unknown error) [4 times]
Mark set
LSP :: Error from the Language Server: inconsistent vendoring (Unknown error)
LSP :: "go mod vendor" failed with err: exit status 1: stderr: warning: ignoring symlink /home/hekumar/goal/src/k8s.io/kubernetes/bazel-bin
warning: ignoring symlink /home/hekumar/goal/src/k8s.io/kubernetes/bazel-kubernetes
warning: ignoring symlink /home/hekumar/goal/src/k8s.io/kubernetes/bazel-out
warning: ignoring symlink /home/hekumar/goal/src/k8s.io/kubernetes/bazel-testlogs
warning: ignoring symlink /home/hekumar/goal/src/k8s.io/kubernetes/cluster/gce/cos
warning: ignoring symlink /home/hekumar/goal/src/k8s.io/kubernetes/cluster/gce/custom
warning: ignoring symlink /home/hekumar/goal/src/k8s.io/kubernetes/cluster/gce/ubuntu
go: finding module for package k8s.io/kubernetes/bazel-kubernetes/test/e2e/framework
k8s.io/kubernetes/test/e2e/framework imports
	k8s.io/kubernetes/bazel-kubernetes/test/e2e/framework: no matching versions for query "latest"

Unable to load color "unspecified-fg"
mouse-minibuffer-check: Minibuffer window is not active
LSP :: Error from the Language Server: inconsistent vendoring (Unknown error)
Mark set
```

**Comment by muirdm** [comment]
I've never seen the minibuffer steal focus on LSP errors. Can you give more details like steps to reproduce, and an animated GIF of what it looks like?

**Comment by gnufied** [comment]
![Screenshot from 2020-09-09 11-45-11](https://user-images.githubusercontent.com/278/92621603-ff8f9100-f291-11ea-9ad7-7322b2684563.png)


I am trying to edit https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go

**Comment by yyoncho** [comment]
@gnufied please report that as a separate issue.

**Comment by yyoncho** [comment]
Please populate the bug template and make sure that it reproduces with lsp-start-plain.el

**Comment by jcs090218** [comment]
This issue seems need more information to progress; and I'm not able to reproduce this issue. I will mark this issue with `Unable to reproduce` and `need-info` labels for now.
