### ISSUE TITLE
Completion doesn't work if C source files contain some Unicode symbols.

### ISSUE THREAD

**Issue by mukovnin** [emacs-lsp/lsp-mode#2126]
Hi!

May be this issue related to ccls or #2080 bug.
I'm using latest `lsp-mode`, `company` and `ccls` packages from MELPA. Emacs 27.1.

**Describe the bug**
Completion doesn't work properly if C source files contain some Unicode symbols in comments.

**To Reproduce**
Create a file a.h:
```
/*
µ
*/
int Capability(int a, int *b);
```
and main.c:
```
#include "a.h"

int main()
{
}
```
Type "capa" in main(). Lsp-mode reports:

```
Warning (lsp-mode): Failed to parse the following chunk:
’’’
Content-Length: 355

{"jsonrpc":"2.0","id":16,"result":{"isIncomplete":false,"items":[{"label":"Capability(int a, int *b) -> int","kind":3,"detail":"","documentation":"�","sortText":"   !","filterText":"Capability","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":4},"end":{"line":4,"character":7}},"newText":"Capability(${1:int a}, ${2:int *b})$0"}}]}}
’’’
with message (json-parse-error unable to decode byte 0xb5 near '"' <string> 1 147 147)
```

**Which Language Server did you use**
ccls

**OS**
Arch Linux

**Error callstack**
[This.](https://pastebin.com/JVjKg7nn)

**Comment by yyoncho** [comment]
I think it is most likely https://github.com/emacs-lsp/lsp-mode/issues/1246

**Comment by yyoncho** [comment]
I tested that same setup with clangd-11 and it seems to work. Can you verify?

**Comment by mukovnin** [comment]
@yyoncho Checked with clangd 10, it works, thank you. It looks like this issue is related to ccls.

**Comment by yyoncho** [comment]
Thank you, I will close the issue and mark it as `upstream`.
