### ISSUE TITLE
Show method signature when writing the arguments of the method

### ISSUE THREAD

**Issue by amol-mandhane** [emacs-lsp/lsp-mode#214]
When writing the arguments of the method, textDocument/hover method doesn't apply and there's no documentation available. However, textDocument/signatureHelp is meant exactly for this use-case. LSP client should show the signature when writing the arguments.

signatureHelp method: https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_signatureHelp

**Comment by amol-mandhane** [comment]
I have a local change for this. If the idea sounds okay, I can send a pull request.

**Comment by vibhavp** [comment]
Sure, thanks. I'll add a few `customize` options to your PR and make it work with `SignatureHelpRegistrationOptions.triggerCharacters`, if it isn't already using it.
