### ISSUE TITLE
emacs27  gopls not work

### ISSUE THREAD

**Issue by ibytao** [emacs-lsp/lsp-mode#2140]
go 1.15    gopls 0.44

Command "gopls" is present on the path.
Command "gopls" is present on the path.
Found the following clients for /Users/nemo/Go/src/simple/main.go: (server-id gopls, priority 0)
The following clients were selected based on priority: (server-id gopls, priority 0)
2020/09/04 17:45:44 Build info
----------
golang.org/x/tools/gopls 0.4.4
    golang.org/x/tools/gopls@v0.4.4 h1:8djGYsaZ0ByP0vaXg4T+mnyfDcHpWKSZ+tpQSGv9ahk=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.0 h1:/QaMHBdZ26BB3SSst0Iwl10Epc+xhTquomWX0oZEB6w=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.3.0 h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=
    golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208 h1:qwRHBd0NqMbJxfbotnDhm2ByMI1Shq4Y6oRJo21SGJA=
    golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c h1:jLQLIAedRoS9I2Py7l/ZAGGzUxLFsdg42JXEpS/a+ow=
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2020.1.4 h1:UoveltGrhghAA7ePc+e+QYDHXrBps2PqFZiHkGR/xK8=
    mvdan.cc/gofumpt@v0.0.0-20200709182408-4fd085cb6d5f h1:gi7cb8HTDZ6q8VqsUpkdoFi3vxwHMneQ6+Q5Ap5hjPE=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=

Go info
-------
go version go1.15 darwin/amd64

Creating watch for /Users/nemo
2020/09/04 17:45:44 go/packages.Load
	snapshot=0
	directory=/Users/nemo
	query=[./ builtin]
	packages=2

2020/09/04 17:45:44 go/packages.Load
	snapshot=0
	directory=/Users/nemo
	query=[./]
	packages=1

Cancelling textDocument/documentLink(14) in hook post-command-hook
Cancelling textDocument/codeAction(13) in hook post-command-hook
Cancelling textDocument/documentLink(7) in hook post-command-hook
Cancelling textDocument/documentLink(3) in hook post-command-hook

**Comment by kiennq** [comment]
What's the problem again?

**Comment by ibytao** [comment]
Can't automatically prompt
gopls Doesn't work

**Comment by muirdm** [comment]
You need to give a better description of the problem and steps to reproduce the problem. In my experience gopls works fine with Emacs 27 and lsp-mode.

It looks like your project root is set to your home directory "/Users/nemo" which doesn't seem correct. I would make sure your lsp-mode workspace folder is set correctly.

**Comment by yyoncho** [comment]
> It looks like your project root is set to your home directory "/Users/nemo" which doesn't seem correct. I would make sure your lsp-mode workspace folder is set correctly.

You could achieve that using lsp-workspace-folders-add and lsp-workspace-folders-remove

**Comment by ibytao** [comment]
Set the directory successfully
Can the working directory be automatically identified?

**Comment by s-kostyaev** [comment]
@ibytao You can use something like this:
```elisp
(require 'f)

(defun my-try-go-mod (dir)
  "Find go project root for DIR."
  (if (and dir
           (not (f-descendant-of-p dir (or (getenv "GOPATH")
                                           (concat (getenv "HOME") "/go")))))
      (let ((result (locate-dominating-file dir "go.mod")))
        (if result
            (cons 'transient (expand-file-name result))
          (cons 'transient dir)))
    (when dir
      (cons 'transient dir))))

(defun my-set-go-project ()
  "Set project root for go project."
  (setq-local project-find-functions (list #'my-try-go-mod #'project-try-vc)))

(add-hook 'go-mode-hook #'my-set-go-project)
``` if you use `project.el` or something similar for `projectile`.
