### ISSUE TITLE
[discussion] maintaining typescript-language-server as part of the organization

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#2147]
As many of you know https://github.com/theia-ide/typescript-language-server is no longer maintained. While it is stable and "just works" there is a new development on in `tsserver` which is not exposed through the server (e. g. call hierarchy). We had a discussion in gitter with @danielmartin so I decided to move it here to see if there are other people interested in working on this.

I think that the overall complexity of `typescript-language-server` is not high because it is proxy so for someone familiar with `js/ts` won't be hard to keep up with `tsserver` features.

**Comment by danielmartin** [comment]
What's the status of https://github.com/sourcegraph/javascript-typescript-langserver? Has anyone tried this language server recently? It seems more actively developed as there's a company behind it, Sourcegraph.

If we decide that Theia is the best one, I agree about maintaining our own fork under the emacs-lsp organization. We'll need to advertise it well so that TypeScript developers that use Emacs, Vim, Sublime... can contribute to it. We can use JS/TypeScript Reddits and Twitter.

**Comment by jcs090218** [comment]
> What's the status of https://github.com/sourcegraph/javascript-typescript-langserver? Has anyone tried this language server recently? It seems more actively developed as there's a company behind it, Sourcegraph.

I have just tried this language server today. I think it is pretty decent, and mainly stable. Yet quick glance from the GitHub page; there are multiple issues not discussed. 

> If we decide that Theia is the best one, I agree about maintaining our own fork under the emacs-lsp organization. We'll need to advertise it well so that TypeScript developers that use Emacs, Vim, Sublime... can contribute to it. We can use JS/TypeScript Reddits and Twitter.

That's sounds about right! This issue most likely going to be across any other editors that use this language server.

**Comment by leungbk** [comment]
> What's the status of https://github.com/sourcegraph/javascript-typescript-langserver? Has anyone tried this language server recently?

I encountered memory leaks when I tried the Sourcegraph server a few months ago. The Theia server generally works well for me.

> It seems more actively developed as there's a company behind it, Sourcegraph.

It's not actively developed at all. Almost every commit from the last two years has been from `dependabot`.

**Comment by jcs090218** [comment]
I think the related discussion is here. https://github.com/neovim/nvim-lspconfig/issues/250

**Comment by leungbk** [comment]
The TypeScript team is slowly re-working `tsserver` to comply with LSP: https://github.com/microsoft/TypeScript/issues/39459#issuecomment-696179304

So I'm not sure if we need to worry about maintaining Theia's server anymore. In its present state, it still works well-ish for routine tasks, and anyone who needs better `tsserver` integration in the short term can always use `tide` until `tsserver` transitions fully to LSP.

**Comment by yyoncho** [comment]
@leungbk thank you. Closing the issue, if tsserver is going to support lsp there is no point to invest time in Theia server.
