### ISSUE TITLE
lsp rendering C++ oneline doc (function signatures) in markdown loses pointer's asterisks

### ISSUE THREAD

**Issue by zhaozhixu** [emacs-lsp/lsp-mode#2150]
**BUG**

When lsp-mode using clangd rendering C/C++ oneline doc in markdown and the content is just a function signature, it loses pointer's asterisks

![image](https://user-images.githubusercontent.com/12733773/92391042-90f5ea80-f14e-11ea-8e4d-ed4f3917c59d.png)

It should be `static inline void *tl_padd(void *p, ptrdiff_t offset, size_t dsize)`

**Possible reason**

https://github.com/emacs-lsp/lsp-mode/blob/4bf7c90bb153a0e6e213f8d128f4aee0b79b6718/lsp-mode.el#L4742-L4757

In the defination of `lsp--render-element` in lsp-mode.el, when there is no language specified in a doc content, it automatically uses `markdown` as the default rendering mode.

**Quick and dirty fix (or test)**

```
;; plain string
      ;; ((stringp content) (lsp--render-string content "markdown"))
      ((stringp content) (lsp--render-string content "Fundamental"))
```
I make the default rendering mode "Fundamental", it doesn't lose things anymore.

![image](https://user-images.githubusercontent.com/12733773/92391986-2b0a6280-f150-11ea-9e23-c6adb35ed3e7.png)

**Suggestion**

While I can live with the above fix for now, it's better to fix the lsp-clangd to return the correct doc content mode.

**Comment by zhaozhixu** [comment]
#2158

**Comment by danielmartin** [comment]
Fixed by https://github.com/emacs-lsp/lsp-mode/pull/2158
