### ISSUE TITLE
Add Prolog LSP to list of implementations of semantic highlighting

### ISSUE THREAD

**Issue by jamesnvc** [emacs-lsp/lsp-mode#2156]
Following up on comment on the release notes here: http://disq.us/p/2bphekw

[My Prolog LSP](https://github.com/jamesnvc/lsp_server) implementation also supports semantic highlighting (related to #1906) & could be added to the list of language servers that implement the new highlighting method.

**Comment by ericdallo** [comment]
Nice @jamesnvc, we can wait for someone to open a PR for that but as you are the maintainer and understands how the server behave, you can follow the documentation on [how to setup a server on lsp-mode](https://emacs-lsp.github.io/lsp-mode/page/adding-new-language/) too :)

**Comment by yyoncho** [comment]
> [My Prolog LSP](https://github.com/jamesnvc/lsp_server) implementation also supports semantic highlighting (related to #1906) & could be added to the list of language servers that implement the new highlighting method.

You mean to the blog entry? 

As a side note feel free to add lsp-client registration for your server to lsp-mode and link your server.

**Comment by ericdallo** [comment]
@yyoncho no, he meant that he would like to see his server on lsp-clients via the blog comment section [here](https://emacs-lsp.github.io/lsp-mode/blog/2020/7.0-release/#comment-5061495056)
