### ISSUE TITLE
Left fringe/margin of doc is larger than right

### ISSUE THREAD

**Issue by seagle0128** [emacs-lsp/lsp-mode#2181]
Please see screenshot below.

Any configuration or workaround, please?

![image](https://user-images.githubusercontent.com/140797/93173300-e89fe180-f75e-11ea-8ee5-783f8c79b16d.png)

**Comment by jcs090218** [comment]
I think this issue suppose to be post to [lsp-ui](https://github.com/emacs-lsp/lsp-ui) instead? Thanks!

**Comment by seagle0128** [comment]
Yeah. can we move it to lsp-ui? or open a new one?
