### ISSUE TITLE
lsp-ui-peek-definition across projects

### ISSUE THREAD

**Issue by deb75** [emacs-lsp/lsp-mode#2186]
- emacs 27.1, mingw64, windows 10
- lsp-mode 20200913.1918

I tried to use `lsp-ui-peek-definition` across several projects all in the same workspace.

It works but instead of opening the source file, it creates a file located in `~/.emacs.d/workspace/.cache`
and opens it in a buffer full of `^M` character at each end of line.

When I use the same function within one project, it works fine, i.e. it opens the correct source file.

How can I make it work like this between distinct projects ?

I do not think it is a bug, something not properly set in my lsp configuration perhaps.

Regards

**Comment by yyoncho** [comment]
It will work if you import both projects and if A is referencing the same version of B as the one you have imported in the workspace.

**Comment by deb75** [comment]
Got it, thanks !
