### ISSUE TITLE
Feature request: Support for Hashicorp's terraform-ls

### ISSUE THREAD

**Issue by staticaland** [emacs-lsp/lsp-mode#2189]
Hashicorp has created a new language server for Terraform - `terraform-ls` (https://github.com/hashicorp/terraform-ls). I saw that they are using it for the VSCode Terraform plugin. I also noticed @Gastove is the creator of the [current emacs-lsp client](https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-terraform.el).

Is there any interest in implementing this? Since it's only 62 lines of code, perhaps this would not be too much work. If I were to tackle this, I would be a bit unsure on how to organize it. Should I create a new `lsp-terraform.el` or make a new one with a different name?

 `lsp-terraform-hashicorp` perhaps?

**Comment by yyoncho** [comment]
> Is there any interest in implementing this? 

We are interested in everything that will improve lsp-mode's experience.

> Since it's only 62 lines of code, perhaps this would not be too much work. If I were to tackle this, I would be a bit unsure on how to organize it. Should I create a new lsp-terraform.el or make a new one with a different name?
lsp-terraform-hashicorp perhaps?

`lsp-hashicorp.el` seems like a good fit. I will accept the other variants as well, we are not that strict on clients organization.

**Comment by kiennq** [comment]
JFYI, there's `lsp-terraform` there, it would be great if you can consolidate the Hashicorp version into that one too. So user will only need to include one file to get both variants

**Comment by rnikoopour** [comment]
Was there any movement on getting this integrated?

**Comment by staticaland** [comment]
I didn't get around to it @rnikoopour, as I had a bit of Terraform hiatus lately.

**Comment by dwa** [comment]
I got this working by creating a shell script named `terraform-lsp` in `~/bin`:

```bash
#!/usr/bin/env bash
terraform-ls serve
```

**Comment by yyoncho** [comment]
FYI there is `lsp-terraform-server` which can be used to change the binary path.

If changing the binary name is sufficient, I propose closing the issue.

**Comment by iartarisi** [comment]
> If changing the binary name is sufficient, I propose closing the issue.

It's not sufficient, as there's no way to provide the `serve` command. So `*lsp-log*` says: `Command "terraform-ls serve" is not present on the path.`

OTOH, dwa's hack works nicely.

**Comment by yyoncho** [comment]
> It's not sufficient, as there's no way to provide the `serve` command. So
> `*lsp-log*` says: `Command "terraform-ls serve" is not present on the path.`

Agreed, PR at #2706 , it will allow passing list of stirng as `lsp-terraform-server`.

**Comment by yyoncho** [comment]
@zheli https://emacs-lsp.github.io/lsp-mode/page/faq/#i-have-multiple-language-servers-registered-for-language-foo-which-one-will-be-used-when-opening-a-project

**Comment by ashlineldridge** [comment]
@zheli `(setq lsp-terraform-server '("terraform-ls" "serve"))`
