### ISSUE TITLE
Keyword arguments in lsp-define-*-client

### ISSUE THREAD

**Issue by jojojames** [emacs-lsp/lsp-mode#219]
Curious if it makes more sense to &key every argument in lsp-define-stdio-client (and the tcp one).

As someone trying to write a lsp client, the parameter arguments were a little tricky to grok at first.

```
(lsp-define-stdio-client lsp-swift
                         "swift"
                         #'projectile-project-root
                         '("langserver-swift"))

(lsp-define-stdio-client :name lsp-swift
                         :language-id "swift"
                         :root #'projectile-project-root
                         :command '("langserver-swift"))
```

The second seems cleaner to me. Hopefully backwards compatibility is not a huge issue already.

Thanks!

**Comment by vibhavp** [comment]
Yup, backwards compatibility is the main issue here. Also, if you look at similar commands in elisp, all use keyword arguments for optional arguments, while necessary values are regular parameters. (See `define-minor-mode`, `flycheck-define-checker`)

**Comment by jojojames** [comment]
Thanks, not a huge issue, so I'll close this.
