### ISSUE TITLE
Replace special white space \u00A0 to make help doc easy to read

### ISSUE THREAD

**Issue by wztdream** [emacs-lsp/lsp-mode#2190]
Hi,
If we use **pyls** as python language server, there will be special white space **non-breaking space** in the help buffer, which make it noisy. This special white space with unicode value **\u00A0** can not be trim by regexp like " ". You can insert this symbol in emacs by `C-x 8 SPC`. 
![noisy](https://user-images.githubusercontent.com/39213018/93558455-0dd75e80-f9b0-11ea-96d1-1de072611c70.png)

I can replace this special space by following code(see commented line), github can not show the difference between the special space and normal space, see below image from emacs

![s-replace](https://user-images.githubusercontent.com/39213018/93558388-eb454580-f9af-11ea-82cc-b0cc4788e53c.png)

```
(defun lsp-describe-thing-at-point ()
  "Display the type signature and documentation of the thing at
point."
  (interactive)
  (let ((contents (-some->> (lsp--text-document-position-params)
                    (lsp--make-request "textDocument/hover")
                    (lsp--send-request)
                    (lsp:hover-contents))))
    (if (and contents (not (equal contents "")))
        (let ((lsp-help-buf-name "*lsp-help*"))
          (with-current-buffer (get-buffer-create lsp-help-buf-name)
            (with-help-window lsp-help-buf-name
              (insert (s-replace " " " " (string-trim-right (lsp--render-on-hover-content contents t)))))));; modify here by s-replace
      (lsp--info "No content at point."))))
``` 
But there are still special withe space in hover window, so it seems there is more places to modify. And it seems above method is not elegant, so I think it will be better to report an issue here instead of an uncompleted PR. 

BTW, I did not see this special white space using **mspyls** backend, so it seems this is also related with **pyls**, anyway this is a small issue, we should be able to handle in lsp-mode.

**Comment by kiennq** [comment]
> I can replace this special space by following code(see commented line), github can not show the difference between the special space and normal space, see below image from emacs

You can try `(s-replace "\x00A0" " ")`

Also, you can try to modify `lsp--render-string` to have special characters being completely replaced.

**Comment by wztdream** [comment]
> > I can replace this special space by following code(see commented line), github can not show the difference between the special space and normal space, see below image from emacs
> 
> You can try `(s-replace "\x00A0" " ")`
> 
> Also, you can try to modify `lsp--render-string` to have special characters being completely replaced.

yes, you are right, this seems completely solved this issue, I will open an PR for this issue.

**Comment by wztdream** [comment]
Anyone suffer from this issue, just follow [this method](https://github.com/jrblevin/markdown-mode/issues/545) to set nobreak-space face 

```
(set-face-attribute 'nobreak-space nil
                    :background nil
                    :underline nil)
```

or `M-x customize-face nobreak-space` then toggle off the face.
I think this is the best method, no need PR.
