### ISSUE TITLE
lsp-mode can't work with the latest rust-analyzer（20200914）

### ISSUE THREAD

**Issue by passchaos** [emacs-lsp/lsp-mode#2192]
Turning on lsp get the following error:
```
Failed to deserialize InitializeParams: missing field `requests`
```

see also: https://github.com/rust-analyzer/rust-analyzer/issues/5986#issue-700224267, maybe this link will be helpful: https://github.com/rust-analyzer/rust-analyzer/pull/6023/files

**Comment by yyoncho** [comment]
I tested with nightly rust analyzer and the latest lsp-mode and it seems like it is working fine.

**Comment by passchaos** [comment]
I checked the local configuration and found that is was the `lsp-enable-semantic-highlighting` that caused the problem. I turned off semantic hightling and it worked fine.

**Comment by yyoncho** [comment]
cc @sebastiansturm

**Comment by sebastiansturm** [comment]
@passchaos: could you please try the PR I just opened? Seems to work with rust-analyzer and clangd, hope it doesn't upset any other language servers

**Comment by passchaos** [comment]
@sebastiansturm This fix works!

**Comment by yyoncho** [comment]
fixed with https://github.com/emacs-lsp/lsp-mode/pull/2193
