### ISSUE TITLE
Is direct list initialization not supported?

### ISSUE THREAD

**Issue by wouterbeek** [emacs-lsp/lsp-mode#2194]
Direct list initialization is a common, if not preferred, way to initialize objects in C++, e.g.:

```cpp
const int x{0}
```

^ When typing the closing blacket, lsp-mode automatically rewrites the buffer contents to the following:

```cpp
const int x
    {
      0
    }
```

Does this mean that lsp-mode does not yet support direct list initialization, of could there be a configuration issue on my end?

**Comment by yyoncho** [comment]
AFAICS both represent the same content but formatted in a different way. LSP protocol provides a feature called on type formatting which reformats the code when you press trigger char (in your case it is is `}`).

You have two options: 
1. Provide  `.clang-format` as described in clang format docs(e. g. https://clang.llvm.org/docs/ClangFormat.html ) which formats the code the way you like. 
2. Disable on type formatting via `lsp-enable-on-type-formatting` and format everything manually. 


I am closing the issue, but you can use it for further questions.
