### ISSUE TITLE
[Help] Writing a swift lsp client

### ISSUE THREAD

**Issue by jojojames** [emacs-lsp/lsp-mode#220]
Was trying to take a stab at writing a client for swift using https://github.com/RLovelett/langserver-swift.

```
(use-package lsp-mode :ensure t
  :config
  (lsp-define-stdio-client lsp-swift
                           "swift"
                           #'projectile-project-root
                           '("langserver-swift"))

  (add-hook 'swift-mode-hook #'lsp-swift-enable))
```

Hard to tell if it should work/not work or not (or if I'm making any mistakes).

If I try to use company-lsp -> M-x company-diag, I get an error message.

```
company-call-backend-raw: Company: backend (company-lsp :with company-yasnippet company-dabbrev-code) error "Wrong type argument: lsp--workspace, nil" with args (prefix)
```

Any help appreciated! Thanks.

**Comment by vibhavp** [comment]
Did you try native completion?

**Comment by jojojames** [comment]
Hmnn, yeah, works for me. Was an unrelated issue.

**Comment by xenodium** [comment]
I'm likely missing something. I'm getting:

> Error from the Language Server: Could not find path/to/some/File.swift in the workspace. (Server Start Error)

`(use-package lsp-mode :ensure t
  :config
  (lsp-define-stdio-client lsp-swift
                           "swift"
                           #'projectile-project-root
                           '("path/to/langserver-swift/.build/x86_64-apple-macosx10.10/debug/langserver-swift")))`

Enabled with

`M-x lsp-swift-enable`

**Comment by jojojames** [comment]
@xenodium lsp works for me, the language server, however, doesn't. Same error you got.

**Comment by xenodium** [comment]
@jojojames thanks for confirming the same server issue.

> lsp works for me

Do you mean you have some lsp Swift support working? Completion/jump to definition? Mind sharing your config?

**Comment by jojojames** [comment]
The swift language server doesn't work for me. Emacs' lsp client does work though (as in, I don't think *this* not working has anything to do with emacs-lsp).

**Comment by xenodium** [comment]
Got it. Thank you.
