### ISSUE TITLE
Feature request: https://github.com/elkowar/rnix-lsp

### ISSUE THREAD

**Issue by magnetophon** [emacs-lsp/lsp-mode#2209]
A WIP Language Server for Nix!

It uses https://github.com/mlvzk/manix, a fast CLI documentation searcher for Nix.

**Comment by leungbk** [comment]
This seems useful. Is there anything prohibiting @elkowar from getting this merged into the upstream version of `rnix-lsp`? If there is, then would it make sense to simply add `$ nix-env -i -f https://github.com/elkowar/rnix-lsp/archive/master.tar.gz` in the documentation?

**Comment by elkowar** [comment]
well, not sure if there's anything prohibiting me in general per-se, but currently it's more than WIP. it barely works at all ^^'

Figuring out language server stuff has been rather challenging for me, and I've been having some issues i still need to find clean solutions for. It will take some time until the rnix-lsp fork is usable / mergeable. Also, I've been working together closely with mlvzk, also contributing to manix, which is another thing that has some time sinking into it

**Comment by magnetophon** [comment]
Thanks for the quick reply, @leungbk and @elkowar.
Does @mlvzk have anything to add?

**Comment by leungbk** [comment]
It seems like once this fork stabilizes, it should be worth merging upstream. But unless there is some difference in APIs, I don't think we should need to register a separate client on our end. Anyone who wants to use the fork in the meantime is free to install it themselves, and it should work with the current `lsp-nix.el`. For this reason, I'm closing this issue.
