### ISSUE TITLE
imenu loss function and class info after enable lsp-enable-imenu

### ISSUE THREAD

**Issue by wztdream** [emacs-lsp/lsp-mode#2212]
Hi,
I just fond if I enable `lsp-enable-imenu` in spacemacs,  imenu will loss function and class information. Not sure if this is server end issue or lsp-mode issue.

Here is the example
python code for indexing
```
def foo1():
    a = 1
    b = 2


class Foo:
    def fn1(self, x, y):
        x = 1
        y = 2
```
then `SPC j i` which runs `spacemacs/counsel-jump-in-buffer` which eventually calls `imenu`

bellow is the compare results:
**disable lsp-enable-imenu**
![disable](https://user-images.githubusercontent.com/39213018/94358027-7d47ff00-00d0-11eb-80f6-915a2fe65978.png)
We have function, class info but no variable info

**enable lsp-enable-imenu**
![enable](https://user-images.githubusercontent.com/39213018/94358060-c39d5e00-00d0-11eb-9186-96b79b0a4b12.png)
We have variable info, but no function or class info.

You can see after enable `lsp-enable-imenu` there is more info shown, like x, y, a,b, this is good. 

But we **loss funcion foo1 and class Foo item.** This is inconvenient when I want to search a function. **I can only jump to some variable *within* a function**, but **not able to jump to the function itself**, I have to move cursor to the function or class manually, this is cumbersome  if the function or class have many lines.

**Comment by yyoncho** [comment]
The issue arises from the fact that imenu cannot represent tree structures. I mean, it can but you cannot navigate to the root element. The default imenu backend does not have tree structure thus does not suffer from that issue.

**Comment by wztdream** [comment]
OK, thank you. I will close this issue. Using default imenu backend works fine for me.

**Comment by Fuco1** [comment]
What does it mean to use default imenu backend?  The built-in emacs?  I switched to https://intelephense.com/ for php and imenu is unusable as I can't navigate to functions anymore. 

Do the lsp servers send buffer positions for all nodes of the tree?  Can we flatten the list with all the markers somehow?  I actually use helm-like interface for imenu so it is flat anyway.

**Comment by yyoncho** [comment]
> Can we flatten the list with all the markers somehow?

This is what we should do. I think that it is addressed in @nbfalcon 's PR at https://github.com/emacs-lsp/lsp-mode/pull/2313

**Comment by nbfalcon** [comment]
My PR addresses this and @Fuco1's request to some degree: it works with `iph`, which I have tested it with. However, this is only the case for the new `imenu` backend, which categorizes all symbols by type, i.e. you will get a group for Functions and for Variables, etc. This means that you can jump to either a functions members (under <function>/variables or to it itself, directly under Functions/<function_name>). I can also look into fixing this for the default imenu backend, which shouldn't be broken for `iph` preferably (it is another spec violation though, I think...):

![20210206-184405](https://user-images.githubusercontent.com/69264154/107125614-5635e100-68ab-11eb-85f1-3de2ec465d19.png)
`imenu-list` on the right shows the imenu generated for some PHP code of mine using `iph`. Note how `validate` is present under `Functions` and its sub-members under `Variables`. The `v_heapsort_heapify` on the bottom is a `pyright` example.

This could be solved for the default imenu backend as well, by adding some sentinel node to all nodes with children that will point to the node itself. That way, duplicates won't show up in `imenu-list`.
