### ISSUE TITLE
How to disable lsp-completion on code comment  ?

### ISSUE THREAD

**Issue by zhangjie2012** [emacs-lsp/lsp-mode#2215]
My setting about completion: 

```
lsp-completion-enable t
lsp-completion-enable-additional-text-edit nil
```

When input any char, alway complete, is that a bug ?
 
![image](https://user-images.githubusercontent.com/2450412/94508341-5dd1e300-0244-11eb-9fc2-2e62a44a473c.png)

**Comment by kiennq** [comment]
No, it's not a bug. It seems you're using `lsp-go` client, which enable `completion-in-comment`.

**Comment by zhangjie2012** [comment]
Your are right, I found code in `lsp-go.el`

```
(lsp-register-client
 (make-lsp-client :new-connection (lsp-stdio-connection
                                   (lambda () (cons lsp-go-gopls-server-path lsp-go-gopls-server-args)))
                  :major-modes '(go-mode)
                  :language-id "go"
                  :priority 0
                  :server-id 'gopls
                  :completion-in-comments? t
                  :library-folders-fn #'lsp-go--library-default-directories
                  :after-open-fn (lambda ()
                                   ;; https://github.com/golang/tools/commit/b2d8b0336
                                   (setq-local lsp-completion-filter-on-incomplete nil))))
```

Do you know how to set `completion-in-comments` to `nil`, I can not find it in document.

**Comment by kiennq** [comment]
You can probably try `(setf (lsp--client-completion-in-comments? (gethash 'gopls lsp-clients)) nil)`

**Comment by zhangjie2012** [comment]
> You can probably try `(setf (lsp--client-completion-in-comments? (gethash 'gopls lsp-clients)) nil)`

not work.

I changed `lsp-go.el` source code, and removed lsp-go.elc file.

**Comment by nbfalcon** [comment]
@zhangjie2012 you need to `M-x eval-expression` that snippet and to add it to your init file. You also need to call `lsp-workspace-root` to restart your gopls workspace. Then comment completion should be disabled.
