### ISSUE TITLE
docs/tutorials/how-to-turn-off.md is woefully incomplete

### ISSUE THREAD

**Issue by bcmills** [emacs-lsp/lsp-mode#2223]
**Describe the bug**

I am trying to set up `lsp-mode` for use with `gopls` for Go source files.
I work on the Go toolchain, so most of the files I am editing are in `~/go/src/cmd`, where `~/go` is a Git clone of the Go repository (per https://golang.org/doc/contribute.html#sending_a_change_gerrit).

Unfortunately, when I enable `lsp-mode`, all of the source files that I open (after the first) end up implicitly in read-only mode, and `lsp-mode` activates a bunch of seemingly-irrelevant minor modes that I never asked for: I requested `lsp-mode` and `company`, and I got, in addition: `ElDoc` (probably useful), `yas` (seemingly irrelevant), and `Flymake:!` (probably not even working?).

I tried adding _literally all_ of the settings from [`docs/tutorials/how-to-turn-off.md`](https://github.com/emacs-lsp/lsp-mode/blob/6741a5667587ab20a0ad19458a6773f0227596fb/docs/tutorials/how-to-turn-off.md) to my `.emacs` file (substituting `setq-default` for `setq`), and these unwanted behaviors persist. (The implicit-read-only mode is especially annoying.)

**To Reproduce**

`.emacs`:
```elisp
(defun lsp-go-install-save-hooks ()
	(add-hook 'before-save-hook #'lsp-format-buffer t t)
	(add-hook 'before-save-hook #'lsp-organize-imports t t))

(when (require 'lsp-mode nil 'noerror)
	(add-hook 'go-mode-hook #'lsp-deferred)
	(add-hook 'go-mode-hook #'lsp-go-install-save-hooks))

(when (require 'company nil 'noerror)
	(add-hook 'after-init-hook 'global-company-mode))

(setq-default lsp-file-watch-threshold nil)
(setq-default xref-prompt-for-identifier nil)

(setq-default lsp-enable-symbol-highlighting nil)
(setq-default lsp-ui-doc-enable nil)
(setq-default lsp-ui-doc-show-with-cursor nil)
(setq-default lsp-ui-doc-show-with-mouse nil)
(setq-default lsp-lens-enable nil)
(setq-default lsp-headerline-breadcrumb-enable nil)
(setq-default lsp-ui-sideline-enable nil)
(setq-default lsp-ui-sideline-show-code-actions nil)
(setq-default lsp-ui-sideline-enable nil)
(setq-default lsp-ui-sideline-show-hover nil)
(setq-default lsp-modeline-code-actions-enable nil)
(setq-default lsp-diagnostics-provider :none)
(setq-default lsp-ui-sideline-enable nil)
(setq-default lsp-ui-sideline-show-diagnostics nil)
(setq-default lsp-eldoc-enable-hover nil)
(setq-default lsp-modeline-diagnostics-enable nil)
(setq-default lsp-signature-auto-activate nil)
(setq-default lsp-signature-render-documentation nil)
(setq-default lsp-completion-provider :none)
(setq-default lsp-completion-show-detail nil)
(setq-default lsp-completion-show-kind nil)
```

Then:
```
cd ~/go/src/cmd
emacs -nw ./go/internal/modload/load.go ./go/internal/modget/get.go ./go/internal/modload/mvs.go
```

**Expected behavior**

* The files should be opened in the usual read/write mode, with additional LSP-enabled diagnostics available via explicit commands.
* No unrequested minor modes should be enabled.

**Which Language Server did you use**
`gopls` `v0.5.0`

**OS**
Linux (Debian testing)

**Comment by yyoncho** [comment]
For the readonly - seems like using  `lsp-go-library-directories-include-go-modules` should fix it. The readonly behaviour was defined as suitable by the go users.

> with additional LSP-enabled diagnostics available via explicit commands.

What do you mean by that?

**Comment by bcmills** [comment]
> > with additional LSP-enabled diagnostics available via explicit commands.
>
> What do you mean by that?

I mean that I expect a basic, out-of-the-box configuration for `lsp-mode` to add commands and context menus of the sort described in https://github.com/emacs-lsp/lsp-mode/tree/master/refcard, **not** to disrupt basic functionality of the editor.

**Comment by bcmills** [comment]
> For the readonly - seems like using `lsp-go-library-directories-include-go-modules` should fix it.

1. The documentation for `lsp-go-library-directories-include-go-modules` says:
   > "Whether or not $GOPATH/pkg/mod should be included as a library directory."

   The files that I opened were in `$GOROOT/src/cmd`, which was also the root of the project in which I intended to work. `$GOPATH/pkg/mod` is not relevant to the reported behavior.

2. I don't understand how toggling whether a particular directly is interpreted as a library relates in any way to _turning off_ the unwanted implicit-read-only-mode behavior..?

**Comment by yyoncho** [comment]
I am done for today, I will follow up tomorrow. The logic about the library non-project files is that you want view mode to be enabled in them so you can quit them with q or at least this is what a lot of people prefer.

**Comment by yyoncho** [comment]
>
> bcmills 1 day ago
> > For the readonly - seems like using
> > `lsp-go-library-directories-include-go-modules` should fix it.
>
> 1. The documentation for `lsp-go-library-directories-include-go-modules` says:
> https://github.com/emacs-lsp/lsp-mode/blob/e0ebcb43ca58449b2540ed28a1c2264839fb3340/clients/lsp-go.el#L179
>
>    The files that I opened were in `$GOROOT/src/cmd`, which was also the root of
>    the project in which I intended to work. `$GOPATH/pkg/mod` is not relevant to
>    the reported behavior.

Is that flag sufficient to overcome the readonly issue or not? AFAICS if it is nil lsp-go--library-default-directories will return only lsp-go-library-directories

>
> 2. I don't understand how toggling whether a particular directly is interpreted
>    as a library relates in any way to _turning off_ the unwanted
>    implicit-read-only-mode behavior..?

I already answered that but it is convenient the files that are not part of the project and come from 3rd party source(e. g. node_modules, /usr/lib, etc) to be in view-mode. In your case, default lsp-mode configuration mistakenly assumes that particular file is library file. This is what we have to fix.

>
> 3. The files in `$GOPATH/pkg/mod` are _already_ marked read-only in the
>    filesystem. Why does `go-mode` need to take any explicit action for `emacs`
>    to do the right thing with them?
>

Opening read-only file does not enable view-mode.

**Comment by bcmills** [comment]
> Is that flag sufficient to overcome the readonly issue or not? AFAICS if it is nil lsp-go--library-default-directories will return only lsp-go-library-directories

I don't know — I gave up and switched to `eglot`.

**Comment by yyoncho** [comment]
Cool, if you decide to switch back and the flag is not sufficient for you feel free to reopen the issue.
