### ISSUE TITLE
Performance problems with many opened buffers

### ISSUE THREAD

**Issue by rrudakov** [emacs-lsp/lsp-mode#2224]
**Describe the bug**
When I work on relatively large java project I usually open many project buffers. When I open around 30-40 buffers I notice that server performance decreases significantly. I set `lsp-print-performance t` and I noticed that lsp-mode sends `textDocument/publishDiagnostics` request for each opened buffer for every single keystroke (which I suppose the root cause of bad server performance). Sometimes I wait for completion more than 3 seconds:

```
Perf> Request/Response
  ServerId: jdtls
  Request: textDocument/completion (82)
  Serialization took: 0.000035
  ServerTime: 3.558523 <--------
  Deserialization: 0.000001
  CallbackTime: 0.000012
Perf> notification
  ServerId: jdtls
  Notification: language/progressReport
  Deserialization: 0.000000
  Processing: 0.000004 
Perf> notification
  ServerId: jdtls
  Notification: language/progressReport
  Deserialization: 0.000000
  Processing: 0.000009 
Oct 6, 2020, 5:41:29 PM >> document/resolveCompletionItem
Perf> notification
  ServerId: jdtls
  Notification: window/logMessage
  Deserialization: 0.000000
  Processing: 0.000035 
```
When I close all buffers and leave only one the performance goes back to normal.

I've tried to reproduce this in VSCode, it looks like when many tabs are opened it also sends diagnostic request for each tab, but VSCode interface doesn't encourage to open many tabs.

Is it possible to optionally send diagnostic requests only for current buffer for emacs?

**To Reproduce**
Open 40 buffers in java project and try to request some completion.

**Which Language Server did you use**
lsp-java

**OS**
Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Logs with enabled print performance**
[lsp-perf-log.txt](https://github.com/emacs-lsp/lsp-mode/files/5335140/lsp-perf-log.txt)

**Comment by yyoncho** [comment]
> Is it possible to optionally send diagnostic requests only for current buffer for emacs?

No, it is notification coming from the server and we have no control on that.

Can you provide the perf data as described here - https://emacs-lsp.github.io/lsp-mode/page/performance/#reporting-performance-problems ?

FTR if you have lsp-treemacs-errors-list buffer penned it will cause that slowdown. There is a bug for that.

**Comment by rrudakov** [comment]
Hello @yyoncho, thank you for response I've attached performance logs to original bug report, should I provide emacs profiler report?

**Comment by rrudakov** [comment]
In the `*lsp-logs*` I see:
```
Oct 6, 2020, 6:12:44 PM begin problem for /CommonAssertions.java
Perf> notification
  ServerId: jdtls
  Notification: window/logMessage
  Deserialization: 0.000001
  Processing: 0.000064 
Oct 6, 2020, 6:12:44 PM 0 problems reported for /CommonAssertions.java
Perf> notification
  ServerId: jdtls
  Notification: window/logMessage
  Deserialization: 0.000000
  Processing: 0.000041 
Perf> notification
  ServerId: jdtls
  Notification: textDocument/publishDiagnostics
  Deserialization: 0.000000
  Processing: 0.000321 
Oct 6, 2020, 6:12:44 PM begin problem for /TestProperties.java
Perf> notification
  ServerId: jdtls
  Notification: window/logMessage
  Deserialization: 0.000000
  Processing: 0.000047 
Oct 6, 2020, 6:12:44 PM 0 problems reported for /TestProperties.java
Perf> notification
  ServerId: jdtls
  Notification: window/logMessage
  Deserialization: 0.000000
  Processing: 0.000046 
Perf> notification
  ServerId: jdtls
  Notification: textDocument/publishDiagnostics
  Deserialization: 0.000000
  Processing: 0.000262 
Oct 6, 2020, 6:12:44 PM Validated 37. Took 5463 ms
```

**Comment by rrudakov** [comment]
>  it is notification coming from the server and we have no control on that.

But then how does the server know for which files to send notifications and for which not to? I see notifications only for opened buffers.

**Comment by yyoncho** [comment]
I don't see it. I need the data from profiler-start/profiler-stop.

**Comment by rrudakov** [comment]
[emacs-profiler-report.txt](https://github.com/emacs-lsp/lsp-mode/files/5335299/emacs-profiler-report.txt)
[lsp-performance-log.txt](https://github.com/emacs-lsp/lsp-mode/files/5335300/lsp-performance-log.txt)

**Comment by yyoncho** [comment]
I don't see anything suspicious on lsp-mode side. Are you able to reproduce using `lsp-start-plain.el`? I see quite some time spent in the modeline and in helm. Also, can you use lsp-mode a bit more as part of the report in order to get a better picture because in the perf report I can see that 21% of the time is spent only for helm navigation.

>   - helm-ff--cache-mode-refresh                                    36  21%

**Comment by rrudakov** [comment]
> Are you able to reproduce using lsp-start-plain.el?

Yes.

Emacs itself performs quite well, I think it's just lsp-mode does something which slows down the server. As I mentioned before the server can respond more than 3 seconds to completion request if I open too many buffers.

```
Perf> Request/Response
  ServerId: jdtls
  Request: textDocument/completion (82)
  Serialization took: 0.000035
  ServerTime: 3.558523
  Deserialization: 0.000001
  CallbackTime: 0.000012
```

**Comment by yyoncho** [comment]
The issue here is that we don't precisely measure the server time because if emacs for some reason spend time in processing another message (e. g. diagnostics) it will be counted as server time. I have a fix in mind, but it will take some time for me to implement and test it.

**Comment by rrudakov** [comment]
Great, I'd be happy to test it.

**Comment by yyoncho** [comment]
This might improve the perf - https://github.com/yyoncho/lsp-mode/commit/c1035b13542d59f6f496a903892a475d0a3c8394

**Comment by rrudakov** [comment]
Thanks! I'll try it tomorrow and post the feedback here.

**Comment by rrudakov** [comment]
I've tried. It doesn't fix the problem :(

**Comment by yyoncho** [comment]
Hm, your project is not public, right? I will prepare a change in lsp-mode which will print what are the methods that we call. Then we will capture the vscode one and compare then. Other than I that I am not sure what we can try... I tested on my side with multiple opened files but in relatively small project and I didn't saw any delay...

**Comment by yyoncho** [comment]
> But then how does the server know for which files to send notifications and for which not to? I see notifications only for opened buffers.

Server sends changes for the whole workspace. I think that it does that even if there are no diag changes in that buffer.

**Comment by rrudakov** [comment]
> Hm, your project is not public, right?

Yes. I'll try to find relatively big open source java project for testing.

> Server sends changes for the whole workspace. I think that it does that even if there are no diag changes in that buffer.

Yeah, I see. When I open new file `lsp` command run in the hook and I think it register this buffer on server somehow and server starts to send notifications for this buffer. It's problem on the server side, I'm just wondering whether we can workaround it in lsp-mode or should I report the bug to server?

**Comment by yyoncho** [comment]
> Yeah, I see. When I open new file lsp command run in the hook and I think it register this buffer on server somehow and server starts to send notifications for this buffer. It's problem on the server side, I'm just wondering whether we can workaround it in lsp-mode or should I report the bug to server?

The opening new buffer should not affect performance unless there is a server issue. But you were unable to reproduce the issue with vscode. I would speculate that the server might be rebuilding the AST of the open buffers as a result of the didChange notifications which might be blocking the completion. There is one more thing about vscode - when testing did you disable vscode intellicode for java? Because by default vscode won't wait for the server to return when intellicode is on?

**Comment by rrudakov** [comment]
> There is one more thing about vscode - when testing did you disable vscode intellicode for java? Because by default vscode won't wait for the server to return when intellicode is on?

I used default settings, only set `"java.trace.server": "messages"`.

I'm not familiar with VSCode (just installed it to test my issue), I think it was enabled by default:
![image](https://user-images.githubusercontent.com/6093590/95299425-fdfbbd80-087d-11eb-9f9b-116fa913dbfa.png)
Should I test it with disabled intellicode?

**Comment by yyoncho** [comment]
> Should I test it with disabled intellicode?

Yes.

**Comment by rrudakov** [comment]
I can't reproduce it in VSCode. I've opened a lot of tabs:
![image](https://user-images.githubusercontent.com/6093590/95305725-ac0b6580-0886-11eb-9382-a0767d171a5d.png)

and tried to type something.

[vscode.txt](https://github.com/emacs-lsp/lsp-mode/files/5339133/vscode.txt)

I see only couple of 
```
localProcessExtensionHost.ts:253 {  message: "[Trace - 10:17:31 AM] Received notification 'textDocument/publishDiagnostics'.", level: 'info',  timestamp: '2020-10-07 10:17:31.099'}
```
messages, but in emacs I see a lot.

**Comment by yyoncho** [comment]
Then it would require more detailed analysis. I will need a reproducer for that.

**Comment by yyoncho** [comment]
@rrudakov can you test https://github.com/yyoncho/lsp-mode/commit/602ff3b94c3ef1e39e0c635d89fd2f14eaedbfbe

**Comment by rrudakov** [comment]
Looks like it doesn't work, here the log for single keystroke, I have 7 buffers open and I see 7 `Notification: textDocument/publishDiagnostics` items.

[lsp-perf-log-new.txt](https://github.com/emacs-lsp/lsp-mode/files/5342398/lsp-perf-log-new.txt)

**Comment by yyoncho** [comment]
> I have 7 buffers open and I see 7 Notification: textDocument/publishDiagnostics items.

This is expected. The issue before this change was that  lsp-mode was sending and then cancelling codeAction request per each buffer.

**Comment by rrudakov** [comment]
OK, I'll try to work on big project today and will post my update here later.

**Comment by rrudakov** [comment]
It definitely faster and more stable with this changes. Sometimes completion still takes more time than usually, but now it just single cases even with many opened buffers.

**Comment by rrudakov** [comment]
@yyoncho can we merge this changes to master?
