### ISSUE TITLE
[completion] completion sorting issues with ts-ls

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#2229]
1. `React` placed infront of `classname`

![image](https://user-images.githubusercontent.com/13259670/95370607-b27afb00-08e1-11eb-9ac7-e5563da81495.png)

2. When there is a mismatch in the case the entry is with very low flex score.

![image](https://user-images.githubusercontent.com/13259670/95370657-c6266180-08e1-11eb-9371-f32c12b67101.png)

**Comment by yyoncho** [comment]
cc @kiennq

**Comment by kiennq** [comment]
The first one looks odd, do you have log for that?

The second one is kind of expected, since the case mismatch will be ranked low, depends on `lsp-completion--fuz-case-sensitiveness`.
I can employed a smart case matching strategy: if there's upper case character, use sensitive matching, else ignore case sensitive. WDYT?

**Comment by kiennq** [comment]
Also the second order looks odd too, `MediaStreamTrack` should have lower order than `onreadystatechange`.
Do you have `company-statistics-mode` on?

**Comment by yyoncho** [comment]
> Also the second order looks odd too, `MediaStreamTrack` should have lower order than `onreadystatechange`.
> Do you have `company-statistics-mode` on?

No, this is tested with a vanilla config. I will post the project.

**Comment by yyoncho** [comment]
> > Also the second order looks odd too, `MediaStreamTrack` should have lower order than `onreadystatechange`.
> > Do you have `company-statistics-mode` on?
> 
> No, this is tested with a vanilla config. I will post the project.

Hm, I am unable to reproduce that today. I suspect that I might have run some old version of lsp-mode.
