### ISSUE TITLE
Add Wiki

### ISSUE THREAD

**Issue by MaskRay** [emacs-lsp/lsp-mode#223]
And make it publicly editable
https://help.github.com/articles/changing-access-permissions-for-wikis/

Off-topic

`xref-find-apropos` in `xref.el` is not appealing because it splits the input pattern and quotes it. This may be appropriate for its elisp backend but bad for general language servers.
```elisp
(defun xref-find-apropos (pattern)
  "Find all meaningful symbols that match PATTERN.
The argument has the same meaning as in `apropos'."
  (interactive (list (read-string
                      "Search for pattern (word list or regexp): "
                      nil 'xref--read-pattern-history)))
  (require 'apropos)
  (xref--find-xrefs pattern 'apropos
                    (apropos-parse-pattern
                     (if (string-equal (regexp-quote pattern) pattern)
                         ;; Split into words
                         (or (split-string pattern "[ \t]+" t)
                             (user-error "No word list given"))
                       pattern))
                    nil))
```

**Comment by vibhavp** [comment]
What about using github pages instead of a wiki?

**Comment by MaskRay** [comment]
Wiki can be *publicly* editable so it is easier to collaborate.

**Comment by MaskRay** [comment]
Not even members can edit the wiki. I don't understand why this still doesn't happen.

**Comment by yyoncho** [comment]
@vibhavp - can you open the wiki for public edits so we can close this issue?

**Comment by yyoncho** [comment]
Wiki opened for edits.
