### ISSUE TITLE
Typing `-` in json property removes all candidates

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#2230]
![image](https://user-images.githubusercontent.com/13259670/95374745-66cb5000-08e7-11eb-9263-7db15b46df2e.png)

I have added the following elements:
```
         :/.eslintrc.json ["http://json.schemastore.org/eslintrc"]
        :/.eslintrc ["http://json.schemastore.org/eslintrc"]
```
in  `lsp-json--schema-associations`.
        

```
{
    "env": {
        "browser": true,
        "es6": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:react/recommended"
    ],
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 2018,
        "sourceType": "module"
    },
    "plugins": [
        "react"
    ],
    "rules": {
        "no-": "error"
    }
}
```

**Comment by yyoncho** [comment]
cc @kiennq

**Comment by kiennq** [comment]
I see no problem though?
![image](https://user-images.githubusercontent.com/2631472/95401232-a6298900-0947-11eb-9db3-24dd1964d03d.png)

**Comment by yyoncho** [comment]
I will test again with vanilla, it might be an issue with my config.

**Comment by yyoncho** [comment]
I confirm that it reproduces with lsp-start-plain.el

**Comment by yyoncho** [comment]
In addition to that 
```
(when (lsp-completion--looking-back-trigger-characterp trigger-chars)
          (setq this-command 'self-insert-command))
```
in the exit function triggers completion in an inappropriate place. I suggest either deleting it or disabling it by default.

**Comment by kiennq** [comment]
> In addition to that
> 
> ```
> (when (lsp-completion--looking-back-trigger-characterp trigger-chars)
>           (setq this-command 'self-insert-command))
> ```
> 
> in the exit function triggers completion in an inappropriate place. I suggest either deleting it or disabling it by default.

Oh, that has been there for a long time. Do you know why it's added there?

**Comment by kiennq** [comment]
> I confirm that it reproduces with lsp-start-plain.el

Do you have log for that? it seems working with mine in `lsp-start-plain.el` though
![image](https://user-images.githubusercontent.com/2631472/95474581-3c999100-09c0-11eb-82a8-253a0b6be71a.png)

**Comment by yyoncho** [comment]
here it is the log: https://gist.github.com/yyoncho/9ab1a371df97bd3bebc05c48fc391444

I am using emacs27.1

**Comment by kiennq** [comment]
The log looks okay to me.
Can you try to eval `(lsp-completion--fuz-score "\"no-" "\"no-alert\"")` to see if it returns value?

**Comment by yyoncho** [comment]
> Can you try to eval `(lsp-completion--fuz-score "\"no-" "\"no-alert\"")` to see if it returns value?

I don't think this is relevant since this function is not called at all. I also tested and lsp-completion--filter-candidates is not called also.

**Comment by kiennq** [comment]
With just this
``` jsonc
{
    "env": {
        "browser": true,
        "es6": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:react/recommended"
    ],
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 2018,
        "sourceType": "module"
    },
    "plugins": [
        "react"
    ],
    // test
    "rules": {
        "no
    }
}
```
Can you check the trace of `company-capf` when type `-`?

**Comment by yyoncho** [comment]
Here it is the log after typing `no-`

**Comment by yyoncho** [comment]
https://gist.github.com/yyoncho/755825e84c7138c31789498fb20de9cd

**Comment by yyoncho** [comment]
As a side note, when reproducing, do you use `json-mode`?

**Comment by kiennq** [comment]
Okay, I think I know the reason now. If you're using the `json-mode` from MELPA, which inherits from `js-mode` this `-` is not considered as part of symbol.
Can you try with `https://github.com/kiennq/json-mode`? It has better syntax table supports

**Comment by yyoncho** [comment]
can we get these fixes in melpa's json-mode?

**Comment by kiennq** [comment]
I have PR opened for this https://github.com/joshwnj/json-mode/pull/61, but no replied from maintainer so far

**Comment by artemkovalyov** [comment]
Offtopic! Now I understand why ESlint also starts for JSON... That dirty inheritance thing.

**Comment by yyoncho** [comment]
> Offtopic! Now I understand why ESlint also starts for JSON... That dirty inheritance thing.

That should be relatively easy to fix by changing the :activation-fn for eslint.

**Comment by yyoncho** [comment]
> > Offtopic! Now I understand why ESlint also starts for JSON... That dirty inheritance thing.
> 
> That should be relatively easy to fix by changing the :activation-fn for eslint.

@artemkovalyov actually, willing to do a fix? I am asking to avoid collisions in case you want to provide a PR.

**Comment by artemkovalyov** [comment]
@yyoncho, the fix seems to be in the Rexex space: https://github.com/emacs-lsp/lsp-mode/pull/2367
The inheritance, in this case, was a fake guess after I checked the hierarchy.

**Comment by yyoncho** [comment]
@kiennq isn't that gone with your latest changes?

**Comment by kiennq** [comment]
@yyoncho Yes this can be closed
