### ISSUE TITLE
Company: backend company-capf error "Symbol’s function definition is void: :interrupted" with args (candidates std)

### ISSUE THREAD

**Issue by chenyidao110** [emacs-lsp/lsp-mode#2236]
What did you expect to happen?
...After today upgrade, there is something wrong in code complete while edit python/c/c++ source files.

What actually happened?
...
Upgrade doom-emacs as follow:
~/.emacs.d/bin/doom upgrade, then edit python/c/c++ with emacs,but code complete cannot work normally
![95418006-07158900-0969-11eb-9e46-7db9f90b4fdf](https://user-images.githubusercontent.com/14362421/95451087-dd288a80-0999-11eb-9968-e08483f27dd4.png)

Additional details:
message buffer:
Company: An error occurred in auto-begin
Company: backend company-capf error "Symbol’s function definition is void: :interrupted" with args (candidates std)

M-x company-diag:
Emacs 27.1 (x86_64-pc-linux-gnu) of 2020-10-07 on DESKTOP-1ODIMFE
Company 0.9.13

company-backends: (company-capf company-yasnippet)

Used backend: company-capf
Value of c-a-p-f: (lsp-completion-at-point)
Major mode: c++-mode
Prefix: ("" . t)

Completions: none(error fetching)

**Comment by chenyidao110** [comment]
Sorry, after reinstall and build lsp-mode, it works correctly!

**Comment by forrestchang** [comment]
Have the same issue in golang-mode.

https://github.com/hlissner/doom-emacs/issues/4235
