### ISSUE TITLE
C# lsp with flycheck - no errors

### ISSUE THREAD

**Issue by XMasterNinni** [emacs-lsp/lsp-mode#2242]
**Describe the bug**
Flycheck does not show/highlight any coding errors. 
I can successfully connect to the language server and Completion/CodeActions work flawlessly. 

When using ts-ls on a javascript project, linting works.

I've read on a reddit thread that @razzmatazz could be of help... thanks in advance! :)

**To Reproduce**
Create a new console project with `dotnet new console`, open the projectile project in Emacs, produce wrong code.
![image](https://user-images.githubusercontent.com/1691878/95617987-948dd180-0a6c-11eb-90de-086e1749e4b8.png)
[lsp-io-log.txt](https://github.com/emacs-lsp/lsp-mode/files/5356870/lsp-io-log.txt)

**Expected behavior**
Flycheck should highlight errors and show them with `list-flycheck-errors`.

**Which Language Server did you use**
lsp-csharp on latest Doom Emacs ( enabled with (csharp +lsp) in init.el )

**OS**
Linux linuxpc 5.4.67-1-lts #1 SMP Thu, 24 Sep 2020 11:35:25 +0000 x86_64 GNU/Linux

**Error callstack**
No errors with `toggle-debug-on-error` and no errors with `lsp-workspace-show-log`

**Comment by yyoncho** [comment]
AFACS the server does not report any errors. I do not see any `textDocument/publishDiagnostics` in that log.

**Comment by XMasterNinni** [comment]
Here's a more complete log (starting with initialization)
[lsp-io-log.txt](https://github.com/emacs-lsp/lsp-mode/files/5356973/lsp-io-log.txt)

I also cannot see any `textDocument/publishDiagnostics` traces.

**Comment by razzmatazz** [comment]
Hey @XMasterNinni have you tried earlier version of the omnisharp-roslyn server?

Which version are you running, presumably the latest? -- check with installed version list at `~/.emacs.d/.local/etc/lsp/omnisharp-roslyn/`.

I also run doom on Linux (besides doom on a Mac) so I can probably cross-check your findings. Can you dump your project sources somewhere (assuming it is permissable)?

**Comment by razzmatazz** [comment]
Also you might want to try running VSCode on your project. It uses the same language server, but via a different protocol and that might help us to diagnose where we might have a problem more precisely.

**Comment by XMasterNinni** [comment]
@razzmatazz 

You pushed me onto the right track!

Upon checking the omnisharp versions in `.emacs.d/.local/etc/lsp/omnisharp-roslyn`, I've noticed that i was using a pretty old build of omnisharp (v1.35.3).
I've always figured that doom might also update the language servers when running `doom upgrade`, looks like that's not the case. 

After updating it from within doom with `lsp-csharp-update-server`, everything now works as expected.

Thanks for the help and have a great day :) :100:
