### ISSUE TITLE
Difficult wording when language server not found

### ISSUE THREAD

**Issue by alanz** [emacs-lsp/lsp-mode#2248]
This is a situation that probably does not come up often, but I am setting up a new language server, and was presented with the "language server not found" text, as 

https://github.com/emacs-lsp/lsp-mode/blob/fb4c35c6978415c4cf52f85230b527d311989063/lsp-mode.el#L7720-L7722

I think the wording for point 1 should be changed, it is not at all clear to me what

"You haven't registered/loaded external language server package which doesn't ship with `lsp-mode'(e. g. `lsp-java', `lsp-metals')." means.

**Comment by jcs090218** [comment]
Good point. I feel like the current wording is acceptable yet any improvement is always welcome! 😄

**Comment by alanz** [comment]
> You haven't registered/loaded external language server package which doesn't ship with `lsp-mode'(e. g. `lsp-java', `lsp-metals').

There is a double negative, and it is not clear if the one I didn't install didn't have support. Or something.  I find it very confusing. If I look at it for a long time and think hard, I think it is trying to say something like

"The language you are trying to use does not have built-in support in `lsp-mode`. You must install the required support manually. Examples of this are `lsp-java` or `lsp-metals`."

**Comment by yyoncho** [comment]
Applies @alanz's suggestion.
