### ISSUE TITLE
Reuse LSP session of "caller" file after jumping to system header file (or files outside of the project)

### ISSUE THREAD

**Issue by MaskRay** [emacs-lsp/lsp-mode#225]
Currently `lsp--start` calls `(lsp--client-get-root client)` to associate a buffer with a workspace. This is fine with files with a common path (usually the project root). However, this get-root model is insufficient for files outside of the current project (e.g. system headers).

In cquery, `xref-find-definitions` on `#include <assert.h>` visits `assert.h`, then I lose the LSP session in the new buffer and I can no longer use LSP features. We should have some "dynamic scoping" sense here as a file can inherit the sessions from its "dynamic chain" (caller file).

VSCode supports [Multi-root Workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces) which I wonder if more or less similar.

**Comment by jiegec** [comment]
I added pr github.com/emacs-lsp/lsp-ui/pull/22, but it might break the assumption that the current file is under project root. But this already works for lsp-cquery.
