### ISSUE TITLE
Invalid face reference: lsp-flycheck-info-unnecessary

### ISSUE THREAD

**Issue by leungbk** [emacs-lsp/lsp-mode#2255]
``` python
def hello():
    def abc(args):
        print(42)

    a = 1
    print("hello world")
    a += 1
    b = 5
    c = 10
    a = [1, 2]

    d = 5

    print("hello ")
    abc(1)


hello()
print("print statement")
```

Using `lsp-pyright` with the above Python file, there are numerous Flycheck errors classified as `lsp-flycheck-info-unnecessary`. When `point` is on a line with one such error, `Invalid face reference: lsp-flycheck-info-unnecessary` appears in the `Messages` buffer. This message seems to be called by `merge_face_ref` in the `xfaces.c` file in core Emacs.

The following seems to make the message go away:

``` diff
---
 lsp-diagnostics.el | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/lsp-diagnostics.el b/lsp-diagnostics.el
index b7aa5daa..ea6d2113 100644
--- a/lsp-diagnostics.el
+++ b/lsp-diagnostics.el
@@ -93,7 +93,7 @@ g. `error', `warning') and list of LSP TAGS."
                       flycheck-level
                       (mapconcat #'symbol-name tags "-"))))
     (or (intern-soft name)
-        (let* ((face (--doto (intern (format "lsp-%s-face" name))
+        (let* ((face (--doto (intern name)
                        (copy-face (-> flycheck-level
                                       (get 'flycheck-overlay-category)
                                       (get 'face))
@@ -102,7 +102,7 @@ g. `error', `warning') and list of LSP TAGS."
                                (apply #'set-face-attribute it nil
                                       (cl-rest (assoc tag lsp-diagnostics-attributes))))
                              tags)))
-               (category (--doto (intern (format "lsp-%s-category" name))
+               (category (--doto (intern (format "%s-category" name))
                            (setf (get it 'face) face
                                  (get it 'priority) 100)))
                (new-level (intern name))
-- 
2.28.0
```

Apparently, making the `face` name match `name` does the trick, but I'm not sure why. The error levels that Flycheck defines [don't look like this](https://github.com/flycheck/flycheck/blob/cd8e0a280c9980c8c7ce31fd2458df7fd81a0acf/flycheck.el#L4388). It seems weird to define some symbol that has not only the properties assigned to it by `flycheck-define-error-level` but also is the name of a face, so we should probably find a cleaner solution.

I am not able to build Emacs from source on my machine for some reason, so I can't go into `xfaces.c` to debug this.

**Comment by yyoncho** [comment]
Willing to turn that into PR?

**Comment by indigoviolet** [comment]
@yyoncho https://github.com/emacs-lsp/lsp-mode/pull/3611

**Comment by SnichOne** [comment]
I see the exact issue with up-to-date flycheck: 20221112.1552 version. With both `pyright` and `pylsp`.

**Comment by usq** [comment]
I see the same issue

**Comment by indigoviolet** [comment]
@ericdallo @yyoncho any suggestions? I still see this as well. Please reopen if that's the right thing to do?

**Comment by ericdallo** [comment]
This issue was fized 9 months ago, the complains started 2months ago, so I suggest opening a new issue with detailed repro and link to this issue, it may be something different that is causing the same issue to final user

**Comment by yyoncho** [comment]
> @ericdallo @yyoncho any suggestions? I still see this as well. Please reopen if that's the right thing to do?

@indigoviolet are you using desktop mode or something like that? Also, before loading lsp-mode can you check if it is defined?

**Comment by davidhaley** [comment]
I'm seeing the same issue.

![image](https://user-images.githubusercontent.com/11729897/234925770-77ee9254-710b-4f72-bd45-5e3c6e9aabc5.png)

![image](https://user-images.githubusercontent.com/11729897/234925833-35993e46-2b0b-455f-939e-133bb79d0261.png)

It seems to come up as I'm typing an import for a component in SvelteKit.

Flycheck:
```
    Version: 20230306.414
     Commit: 5f2ef177cb21ae8b73714575802beef04abd0f5e
```

Doom:
```
generated  Apr 27, 2023 10:16:13
system     Ubuntu 22.04.2 LTS Linux 5.19.0-41-generic x86_64
emacs      28.2 ~/.emacs.d/
doom       3.0.0-pre PROFILE=_@0 HEAD -> master 4e105a95 2023-03-22
	   18:29:38 -0400 ~/.doom.d/
shell      /bin/bash
features   ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS
	   HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2
	   M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG
	   SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM
	   XPM GTK3 ZLIB
traits     batch server-running envvar-file custom-file
modules    :config use-package :completion (company +childframe) vertico
	   :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash
	   ophints (popup +defaults) treemacs (vc-gutter +pretty)
	   vi-tilde-fringe window-select workspaces zen :editor (evil
	   +everywhere) file-templates fold format multiple-cursors
	   snippets :emacs dired electric (undo +tree) vc :term vterm
	   :checkers syntax :tools (debugger +lsp) (eval +overlay)
	   lookup lsp magit pdf :lang emacs-lisp (go +lsp) json
	   javascript lua markdown (org +pretty +roam2 +pandoc +jupyter)
	   (python +poetry +lsp +pyright +virtualenv) sh (web +html +css
	   +lsp) yaml :config (default +bindings +smartparens)
packages   (deno-fmt) (jupyter) (svelte-mode) (focus) (transpose-frame)
	   (copilot :recipe (:host github :repo zerolfx/copilot.el
	   :files (*.el dist))) (org-fragtog)
```

**Comment by pixel-ant** [comment]
These are my findings.

# Current situation
This is what `lsp-mode` does:

For each _error_ of some _level_ and tagged with some _tags_ that LSP server yields:
1. Generate a _generated flycheck level_, a _generated category_ and a _generated face_ named after _level_ and _tags_.
   - E.g: `lsp-flycheck-info-unnecessary`, `lsp-flycheck-info-unnecessary-category` and `lsp-flycheck-info-unnecessary-face` respectively.
2. Set property `face` of _generated category_ to _generated face_.
   - E.g: `lsp-flycheck-info-unnecessary-category`.`face` <- `lsp-flycheck-info-unnecessary-face`.
3. Create a _symbol overlay_ to highlight the erroneous symbol.
   - E.g: `symbol-overlay-1`.
4. Set `category` property of _symbol overlay_ to _generated category_.
   - E.g: `symbol-overlay-1`.`category` <- `lsp-flycheck-info-unnecessary-category`.
5. Create a _sideline overlay_ to display _error message_ near the erroneous line.
   - E.g: `sideline-overlay-1`.
6. Set `face` property of _error message_ to _generated flycheck level_. BUG?????
   - E.g: "very bad done".`face` <- `lsp-flycheck-info-unnecessary`.

# Consequences
Emacs can't find the face named as _generated flycheck level_ as many times as characters in _error message_?
So many error messages like
   ```
   Invalid face reference: lsp-flycheck-info-unnecessary [38 times]
   ```
are emitted.

As `lsp-ui-sideline.el` does not define a face named as _generated flycheck level_, this must be a bug.

If authors pretended to use the same face for _symbol overlay_ and _sideline overlay_, both `face` properties should be set to _generated face_.

# Transient solution
To avoid changing the original source code, the referenced face can be defined in init file. E.g:

```elisp
(defface lsp-flycheck-info-unnecessary
  '((t))
  "Face which apply to side line for symbols not used.
Possibly erroneously redundant of lsp-flycheck-info-unnecessary-face."
  :group 'lsp-ui-sideline)
```

Then it can be themed or customized. Remember this is the face for _sideline overlay_.
This has stopped all error messages for me.

# Permanent solution
I prefer different faces for _symbol overlay_ and _sideline overlay_.
But that of _sideline overlay_ should be named `lsp-ui-sideline-{level}-{tags}-face`.
If a _generated flycheck level_ like `lsp-flycheck-info-unnecessary` is made a face name, it confuses users when searching for a face name related to sidelines.

**Comment by rdiaz02** [comment]
> This issue was fized 9 months ago, the complains started 2months ago, so I suggest opening a new issue with detailed repro and link to this issue, it may be something different that is causing the same issue to final user

Just did so in https://github.com/emacs-lsp/lsp-ui/issues/761#issuecomment-1992186359

**Comment by CeleritasCelery** [comment]
The transient solution by @pixel-ant triggers the issue https://github.com/syl20bnr/spacemacs/issues/16224 for me. Having this warning is much better than the error in `lsp--in-idle`.
