### ISSUE TITLE
Feature request: lsp version command

### ISSUE THREAD

**Issue by duianto** [emacs-lsp/lsp-mode#2266]
It might be useful to add a `M-x` `lsp-mode-version` or `lsp-version` command.

Similar to `M-x` `magit-version`:
`Magit 20201004.830, Git 2.28.0.windows.1, Emacs 27.1, windows-nt`

There was a question about how to check the current lsp-mode version:
vue layer: vls keeps throwing code action errors https://github.com/syl20bnr/spacemacs/issues/14044

My answer was:
>You can view your lsp-mode version in:
~/.emacs.d/elpa/27.1/develop/lsp-mode-20201016.1633/lsp-mode.el
>
>Currently it's: ;; Version: 7.1.0

---

It might also be helpful to include such a command in the bug reporting template.

**Comment by ericdallo** [comment]
Yeah, I like this idea, we have this for `lsp-dart` too and helps a lot debugging issues.

**Comment by duianto** [comment]
A `M-x` `lsp-version` command has been added: `lsp-mode 20201018.509, Emacs 27.1, windows-nt`

lsp-mode: adding lsp-version for easier to detect current version #2267
Thanks @kiennq
