### ISSUE TITLE
[Feature request]: Allowing users to customize the function signature display

### ISSUE THREAD

**Issue by shackra** [emacs-lsp/lsp-mode#2269]
I described this on [Emacs Stackexchange](https://emacs.stackexchange.com/q/61137/690)

I find useful to see the signature of a function on the echo area in Emacs, however for some functions the text displayed is larger than the width of the window allows, changing the height of the echo area and making text "jump" which can be distracting, here is an example:

![screenshot of Emacs](https://i.stack.imgur.com/hs5I6.png)

Asking on Emacs Stackexchange it seems that there is no straight forward way to customize the text displayed in such a way that you could, if you wish do to so, shorter the signature displayed on the echo area, for instance the text in the previous screenshot could be displayed as follows:

```
1/1 | CreateSubscription(..., identificacion_tipo model.IdentificacionTipo, ...) (*service.Subscription, error)
```

This could come handy for some languages like Typescript, I can see what props there are and their types but there are so many props (or few props with larger names and type names) that the line wraps in 3 or 4 lines.

**Comment by ericdallo** [comment]
This is a common issue with lsp-dart too, but I think it's not easy replace the args with `...` as the server responds with string for the signature. We could maybe give an option to trim the string in X characters, but I don't know if it'd be useful.

**Comment by kiennq** [comment]
Will this help? https://github.com/emacs-lsp/lsp-mode/pull/1999

**Comment by shackra** [comment]
yes, I think that would do it since the information is shown on a
child-frame

**Comment by nbfalcon** [comment]
We have two options for this - extending `lsp-hover` to allow running a hook that modifies the eldoc message or a protocol extension, so that textDocument/signatureHelp can take a maxsize field. IMHO the latter is the better option here, since the language server knows best what to cut off and what to keep.

**Comment by yyoncho** [comment]
Already fixed with https://github.com/emacs-lsp/lsp-mode/pull/1999
