### ISSUE TITLE
dap-java: Implement vscode.java.resolveMainClass

### ISSUE THREAD

**Issue by asif-mahmud** [emacs-lsp/lsp-mode#2275]
I have installed `Oracle JDK 15`, compiled and built jdtls release 0.63 and copied the `org.eclipse.jdt.ls.product/target/repository` under `~/.emacs.d/.cache/lsp` and renamed to `eclipse.jdt.ls`. Seems like it worked. Except cant use the dap mode now. When i run `dap-debug` after `(require 'dap-java)`, it says `Open an issue in lsp-mode to implement vscode.java.resolveMainClass`.

Heres my environment - 
```
OS: Archlinux 64 bit
Emacs: 27.1
JDK: 15 (Oracle)
```

I had to install manually cause despite the `lsp-install-server` worked without error, the lsp-java didn't work. But manually installing the server looks like working.

**Comment by jcs090218** [comment]
It seems like auto install module in [lsp-java](https://github.com/emacs-lsp/lsp-java) isn't working properly at this moment. I think the issue is the installation process isn't thorough due to Java development environment. 😖 

Anyway, thanks for reporting this issue us!

**Comment by yyoncho** [comment]
> I had to install manually cause despite the `lsp-install-server` worked without error, the lsp-java didn't work. But manually installing the server looks like working.

You have to either install automatically or download the bundles manually and place them in bundles directory - https://github.com/microsoft/vscode-java-debug . Refer to https://github.com/emacs-lsp/lsp-java/blob/master/install/pom.xml

**Comment by hectorhon** [comment]
Link to java debug server: https://github.com/microsoft/java-debug
