### ISSUE TITLE
Question about the Emacs status line plugin used on the LSP site

### ISSUE THREAD

**Issue by yk42bb** [emacs-lsp/lsp-mode#2283]
I was amazed when I saw the status bar in Emacs on the [LSP main site](https://emacs-lsp.github.io/lsp-ui/#intro):
![lsp-line](https://user-images.githubusercontent.com/73321225/97065398-f6752d80-157a-11eb-9891-9425171d94de.gif)
What is it? I am so desperate to make my Emacs look as cool as that!

**Comment by leungbk** [comment]
I'm guessing it's Spaceline. You can also try the doom modeline.

**Comment by yyoncho** [comment]
I think @sebastiencs is the author of this screenshot.
