### ISSUE TITLE
Make pcase match protocol-specified types

### ISSUE THREAD

**Issue by leungbk** [emacs-lsp/lsp-mode#2285]
`lsp-pcase` would work like `pcase`, but we would pattern-match against protocol-specified types. This would be helpful for type-checking server results that could be one of several types (for example, `Location | Location [] | LocationLink []`).

Actually, we might instead use `pcase-defmacro` to simply define new cases for regular `pcase`. I haven't thought about it enough.

**Comment by slippycheeze** [comment]
note: you can extend the core pcase system, see https://www.gnu.org/software/emacs/manual/html_node/elisp/Extending-pcase.html#Extending-pcase

that'd allow pattern extensions like `lsp-location` without needing to wrap pcase in your own system.  (and work with `pcase-let` and friends for free.
