### ISSUE TITLE
Is there a management UI to view all the active servers?

### ISSUE THREAD

**Issue by netjune** [emacs-lsp/lsp-mode#229]
And view all buffers associated with a server?

**Comment by terlar** [comment]
Maybe not so intuitive but in terms of server processes you can use the <kbd>M-x</kbd> `list-processes`.

**Comment by yyoncho** [comment]
Here it is what I have implemented in #469 
![emacs myoncho_060](https://user-images.githubusercontent.com/13259670/48658520-0493a880-ea4c-11e8-8f9c-91d43b4e6760.png)

**Comment by netjune** [comment]
It is cool. And it is like a org-mode buffer. Can I restart a language server in this buffer?

**Comment by yyoncho** [comment]
I haven't implemented that yet, we need to define what operations will be available(e. g. close buffer, remove folder, restart server)
