### ISSUE TITLE
Allow configuration of `lsp-modeline--code-actions-icon`

### ISSUE THREAD

**Issue by gahag** [emacs-lsp/lsp-mode#2291]
It would be nice to allow configuration of the fallback unicode icon for `lsp-modeline--code-actions-icon`. It is currently hardcoded as the 💡 (lightbulb) emoji. I use the Adobe Source Code Pro font, which has no support for this emoji:
![image](https://user-images.githubusercontent.com/7347561/97644810-0e8cf700-1a2a-11eb-9451-b802d6cfa495.png)

**Comment by ericdallo** [comment]
Hey @gahag, Do you think this would be enough?
https://github.com/emacs-lsp/lsp-mode/pull/2292

**Comment by gahag** [comment]
That looks great. Thanks for the great work on this.

Quem sabem não te pago uma cerveja quando for em sampa :D

**Comment by bk322** [comment]
For the light bulb to appear, one also need to set emoji font: https://www.reddit.com/r/emacs/comments/ggd90c/color_emoji_in_emacs_27/fq0nvxc

```lisp
;; Emoji: 😄, 🤦, 🏴
(set-fontset-font t 'symbol "Apple Color Emoji")
(set-fontset-font t 'symbol "Noto Color Emoji" nil 'append)
(set-fontset-font t 'symbol "Segoe UI Emoji" nil 'append)
(set-fontset-font t 'symbol "Symbola" nil 'append)
```
