### ISSUE TITLE
Python: No connection to Jedi / Pyls / lsp-python-ms Servers

### ISSUE THREAD

**Issue by j3cc** [emacs-lsp/lsp-mode#2295]
**Describe the bug**
Python LSP-Mode server connection: Somehow connection to Python server is not possible. I installed lsp-jedi & jedi server in python venv, then lsp-pyl and at last lsp-ms-python. I tried different hooks and all, it also shows in the lsp-logs the server type (i.e. pyls/jedi).

```Command "pyls" is present on the path.
Command "pyls" is present on the path.
Found the following clients for /xxx/xxxx/xxx/models.py: (server-id pyls, priority -1)
The following clients were selected based on priority: (server-id pyls, priority -1)
Command "pyls" is present on the path.
Command "pyls" is present on the path.
Found the following clients for /xxx/xxx/xxx/test.py: (server-id pyls, priority -1)
The following clients were selected based on priority: (server-id pyls, priority -1)
```
However, it never goes into the lsp-mode and the lsp-ui-mode. Because, if I activate via    `M x lsp-mode`
it just shows `LSP[Disconnected]` in the status bar. With only option to turn the mode off. 
However, above info shows me it finds the language servers.

When I run emacs with the provided `lsp-start-plain.el` script it runs just fine. Without any extra config.
My question is, how to properly setup lsp-mode for emacs. I just installed 
lsp-mode 7.0.1 
lsp-python-ms-0.7.0
lsp-treemacs-0.3
lsp-ui-7.0.1
lsp-jedi-0.0.1 
via package install.
my init.el contains following info:
```(pyvenv-mode 1)
(pyvenv-workon 'myvenv) ;;enable my virtual environment automatically

(use-package flycheck
  :ensure t
  :init (global-flycheck-mode))

;flycheck works like a charm. after manually calling lsp-ui-mode, the messages are displayed in lsp-ui-mode, everything below does not work


;; LSP-Mode init for python

(use-package lsp-mode
  :ensure t
  :hook (python-mode . lsp-deferred)
  :commands (lsp lsp-deferred))

; let's add the lsp company backend
(use-package company-lsp
  :ensure t
  :config
  (push 'company-lsp company-backends))

; also installs lsp as a dependency
(use-package lsp-ui
  :ensure t
  :hook (lsp-mode . lsp-ui-mode))

;; jedi lsp client, it shows to connect to jedi epc in jedi logs, but ultimately does not work (as pyls)
;(use-package lsp-jedi
;  :ensure t
;  :config
;  (with-eval-after-load "lsp-mode"
;    (add-to-list 'lsp-disabled-clients 'pyls)
;    (add-to-list 'lsp-enabled-clients 'jedi)))
;(use-package helm-lsp :commands helm-lsp-workspace-symbol)
```

with lsp-diagnose it shows:
`
Checking for Native JSON support: ERROR
Checking emacs version has `read-process-output-max': OK
Using company-capf: OK
Check emacs supports `read-process-output-max': OK
Check `read-process-output-max' default has been changed from 4k: ERROR
Byte compiled against Native JSON (recompile lsp-mode if failing when Native JSON available): ERROR
`gc-cons-threshold' increased?: ERROR
`

**To Reproduce**
I can't pinpoint the issue further down. I suspect my init.el is wrong or i am missing something different? With the provided clean script, emacs works with lsp-mode ootb

**Expected behavior**
lsp mode showing me tooltips / info about written code

**Which Language Server did you use**
lsp-python

**OS**
Linux Mint, GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.18.9) (self built)

**Error callstack**

while toggle-debug-on-error does not print anything besides a warning for a missing org-file upon startup, lsp-print-io does not produce more than the first code-block here ("Command "pyls" is present on the path. ....")
However if I load a python file it tries to run lsp and prints something to the *Messages* buffer:

```Error running timer: (wrong-type-argument listp #s(lsp--client nil nil (:connect #[1028 "\302\300!\303^C!\304!\305\306\"\307\310\311\312\313\305\314	\"\315\316\317\320\321\322\323\324&325\326\"\210\325\327!\326\"\210r\330!q\210\331 \210)\211B\266\202)\207" [#[0 \207" [lsp-python-ms-executable] 1] process-environment lsp-resolve-final-function generate-new-buffer-name lsp--compute-process-environment format "*%s::stderr*" make-process :name :connection-type pipe :buffer "*%s*" :coding no-conversion :command :filter :sentinel :stderr :noquery t set-process-query-on-exit-flag nil get-buffer-process get-buffer special-mode] 26 "

(fn FILTER SENTINEL NAME ENVIRONMENT-FN)"] :test\? #[0 "\301!\207" [lsp-python-ms-executable f-exists\?] 2]) nil nil #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("python/languageServerStarted" lsp-python-ms--language-server-started-callback "telemetry/event" ignore "python/reportProgress" lsp-python-ms--report-progress-callback "python/beginProgress" lsp-python-ms--begin-progress-callback "python/endProgress" lsp-python-ms--end-progress-callback)) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ()) #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data ()) nil #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ()) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ()) (python-mode) nil 1 mspyls nil lsp-python-ms--extra-init-params nil nil nil #[257 "\211\301\302\303!!)\207" [lsp--cur-workspace lsp--set-configuration lsp-configuration-section "python"] 4 "

(fn WORKSPACE)"] nil nil nil nil nil nil #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ()) #[1028 "\205
\0\301$\207" [lsp-python-ms-auto-install-server lsp-python-ms--install-server] 9 "

(fn CLIENT CALLBACK ERROR-CALLBACK UPDATE\\=\\?)"] nil nil))
Error during redisplay: (jit-lock-function 1) signaled (wrong-type-argument wholenump nil
Error during redisplay: (jit-lock-function 501) signaled (void-variable start)
Error during redisplay: (jit-lock-function 1001) signaled (wrong-type-argument wholenump nil 
If there is an error please reproduce the issue with `toggle-debug-on-error` and after setting `lsp-print-io` to t, and then include the callstack and attach the content of `*lsp-log*` buffer and the content of the server log(use `lsp-workspace-show-log`)```




Thank you in advance for your help

Edit: If I use `lsp-workspace-show-log` I see a prompt to specify a workspace. But no suggestions there, nothing to choose. I can't type in anything, it wont recognize a workspace. Same with `lsp-workspace-restart` . It just prompts `Select workspace:`. But if I run `lsp-describe-session` it rightly shows me the two projects running. But I can't expand them (i tried multiple keys (TAB, Space, ALT, Windows, C-c, etc.) but nothing. There is a little yellow rhomb in front of each workspace. Through pressing return I can toggle between red and yellow colors. But it seems to have no effect on anything...

**Comment by yyoncho** [comment]
> if I activate via M x lsp-mode

The proper way to start lsp-mode is using `M-x lsp`

**Comment by j3cc** [comment]
> > if I activate via M x lsp-mode
> 
> The proper way to start lsp-mode is using `M-x lsp`

Sorry if this did not become clear in my initial post. I first start lsp mode with `M-x lsp`. Then I get the Message from the initial post that is in the last code section into *Messages* buffer. But it won't start up or anything. I then do `M-x lsp-mode` which adds the LSP[Disconnected] status tag into the status bar.

**Comment by yyoncho** [comment]
Did you try to delete elpa dir and reinstall everything? Did you try to use lsp-start-plain.el as a base and add your configuration sections one by one until you find out which is the problematic piece(if any)?

**Comment by j3cc** [comment]
I deleted all lsp-mode package folders from elpa-dir. And with lsp-start-plain.el Emacs does start with lsp mode and get a connection.

**Comment by j3cc** [comment]
Ah, I got it. I renamed my complete elpa folder to backup_elpa and emacs went through all package installations. It does work now, but other old packages are broken. So I think there is an issue somewhere with unupdated packages on my part. Thanks for your help
