### ISSUE TITLE
Implement rust-analyzer code lenses

### ISSUE THREAD

**Issue by nbfalcon** [emacs-lsp/lsp-mode#2298]
- [ ] rust-analyzer.debugSingle: rust-analyzer's debugSingle works exactly like runSingle, the only difference being the "command". To implement this, we need a way to wrap cargo run commands in gdbserver (I'll make a PR), and a dap-mode command to attach to some PID. We can reuse the runSingle code and just add the wrapper-gdbserver argument.

- [x] rust-analyzer.showReferences

**Comment by yyoncho** [comment]
AFAIK vscode provides the option to select which debug adapter to use for debugging.

**Comment by nbfalcon** [comment]
Do we need to support that too, though? rust-gdb is the standard, AFAIK, so only supporting that should be enough for now.

**Comment by yyoncho** [comment]
which adapter is that?

**Comment by nbfalcon** [comment]
Its just GDB, so dap-gdb-lldb.

**Comment by yyoncho** [comment]
dap-gdb-lldb is very limited regarding functionality(e. g. no threading support, poor locals handling, etc). cpptools or code-lldb are the best options for native debugging.  We do not have support for the latter. Not sure how lldb-vscode scores against them though.

**Comment by nbfalcon** [comment]
Perhaps this might need to be made configurable after all. I think I'll do showReferences first.

**Comment by yyoncho** [comment]
FTR - https://github.com/rust-analyzer/rust-analyzer/blob/master/editors/code/package.json#L514
