### ISSUE TITLE
PHP (Serenata) paths defined in lsp-serenata-exclude-path-expressions not excluded

### ISSUE THREAD

**Issue by ribaricplusplus** [emacs-lsp/lsp-mode#2300]
**Describe the bug**

Custom paths specified in the `lsp-serenata-exclude-path-expressions` variable are not excluded. In particular, I was working on wordpress core and tried to exclude the build directory by adding `build/*` to the `lsp-serenata-exclude-path-expressions` array. That didn't work (e.g. if I look up a function definition, 2 definitions show up, one in the `src` directory and one in `build`).

To make sure it was not a globbing problem, I added `*.php` to the array of paths to exclude, and all lsp features still worked, so files were not excluded.

**To reproduce**

Use any PHP project, for example: https://github.com/tizis/php-basic-algorithms

Make sure you have Serenata language server installed.

Use one of the following two methods to setup the environment properly. After setting up the environment, all PHP files in the project should be excluded from the language server, but they are not.

Method 1:

~~~
M-x customize-variable lsp-serenata-exclude-path-expressions
~~~

Add `*.php` to the array. 

Method 2:

Use this modified `lsp-start-plain.el` to run a clean emacs session.
Modifications I added:
1. gnu-elpa-keyrig and php-mode to list of installed packages
2. Added `*.php` to `lsp-serenata-exclude-path-expressions`

Run this code with `emacs -q -l lsp-start-plain.el`.

~~~elisp
;;; lsp-start-plain.el --- LSP mode quick starter      -*- lexical-binding: t; -*-
(require 'package)

(setq debug-on-error t)

(let* ((package-archives '(("melpa" . "https://melpa.org/packages/")
                           ("gnu" . "https://elpa.gnu.org/packages/")))
       (no-byte-compile t)
       (package-user-dir (expand-file-name (make-temp-name "lsp-tmp-elpa")
                                           user-emacs-directory))
       (custom-file (expand-file-name "custom.el" package-user-dir))
       (pkg-list '(gnu-elpa-keyring-update php-mode lsp-mode lsp-ui yasnippet lsp-java lsp-python-ms lsp-haskell helm-lsp lsp-treemacs dap-mode lsp-origami lsp-dart company flycheck lsp-pyright )))

  (package-initialize)
  (package-refresh-contents)

  (mapcar (lambda (pkg)
            (unless (package-installed-p pkg)
              (package-install pkg))
            (require pkg))
          pkg-list)

  (yas-global-mode)
  (add-hook 'prog-mode-hook 'lsp)
  (add-hook 'kill-emacs-hook `(lambda ()
                                (delete-directory ,package-user-dir t)))
  )
(require 'lsp-mode)
(setq lsp-serenata-exclude-path-expressions ["/.+Test.php$/" "*.php"])
(provide 'lsp-start-plain)
;;; lsp-start-plain.el ends here

~~~

**Expected behavior**

Paths defined in `lsp-serenata-exclude-path-expressions` are excluded.

**OS and other info**

Debian bullseye(testing)
Emacs v26.3
PHP 7.4.11 
lsp-mode 20201103.2013

**Comment by yyoncho** [comment]
> No php files should be recognized, but they are.

What does this mean?

**Comment by ribaricplusplus** [comment]
> > No php files should be recognized, but they are.
> 
> What does this mean?

First of all I just want to say thank you for making this project happen, and taking the time to answer this issue.

By no php files should be "recognized" I mean they should not be indexed. If the exclude pattern is `"*.php"`, the language server should be ignoring all php files, as if they are not even there.

I know you would never do that, what I actually want is to exclude everything from `build` directory in project root. But I am not exactly sure how to write a pattern for that. Is it `build/*`? Or `build/**/*`? Or `*build/*`? So in order to make sure the problem is not with my glob pattern, I wrote `*.php` which should exclude all php files, yet they don't get excluded.

**Comment by nbfalcon** [comment]
@ribaricplusplus I think I see the issue: `lsp-serenata-exclude-path-expressions` doesn't take a list of globs, but rather a list of regular expressions. So to exclude .php files you would use "\\.php$". The option should be the same as the corresponding one in VSCode, because we send it to Serenata verbaitim.

**Comment by ribaricplusplus** [comment]
@nbfalcon Yeah, that's it. Though [the lsp documentation](https://emacs-lsp.github.io/lsp-mode/page/lsp-serenata/#lsp-serenata-exclude-path-expressions) says it is also possible to use globs. And so does [the Serenata documentation](https://gitlab.com/Serenata/Serenata/-/wikis/Setting-Up-Your-Project#excludedpathexpressions).

Symfony Finder only does matching against file basename, don't know if Serenata extends that in any way. But if it doesn't, then I don't think there is a way to exclude entire folders. That's a problem.

I'm planning to look more into this when I get some time, but this is clearly not a LSP problem, so I assume we can close this issue.
