### ISSUE TITLE
`onTypeFormatting` causing `$/cancelRequest`

### ISSUE THREAD

**Issue by AndreasMatthias** [emacs-lsp/lsp-mode#2305]
There seems to be an issue with `onTypeFormatting`. The communication goes like this:

1. Sending notification `textDocument/didChange`.
2. Sending request `textDocument/onTypeFormatting - (2)`.
3. Received response `textDocument/onTypeFormatting - (2)`.
4. Sending notification `$/cancelRequest`.
5. Sending notification `textDocument/didChange`.

The modification proposed by the server in (3) is actually applied to the buffer and confirmed in (5), which is correct. Nevertheless lsp-mode tries to cancel the request in (4), which is wrong. From here on lsp-mode is sending a `$/cancalRequest` for `id:2` after each and every keystroke.

To reproduce this issue I've written a small client `client.el` and a small server `server.py`. See below.

The server is written in python and requires the `pygls` package, which can be installed with `pip`.

To run the test do the following:

* emacs -l client.el test.txt
* M-x foobar-mode
* type some text and then `)`

'`)`' which will trigger `onTypeFormatting`, and the server will respond by inserting `xxx` at the beginning of the line.

Here is the source from `client.el` and `server.py`:

**client.el**
```
(require 'lsp-mode)

(define-derived-mode foobar-mode prog-mode "Foobar")
(add-hook 'foobar-mode-hook #'lsp)
(add-to-list 'lsp-language-id-configuration '(foobar-mode . "foobar"))

(setq lsp-log-io t)
(setq lsp-log-max t)

(eval-when-compile
  (setq server-name (concat (file-name-directory load-file-name) "server.py")))
  
(lsp-register-client
 (make-lsp-client
  :new-connection (lsp-stdio-connection `("python3" ,server-name))
  :major-modes '(foobar-mode)
  :server-id 'foobar-ls
  :language-id "foobar"))

(provide 'foobar)
```

**server.py**
```
#!/usr/bin/env python3

from pygls.features import (FORMATTING, ON_TYPE_FORMATTING)

from pygls.server import LanguageServer

from pygls.types import (Position, Range, TextEdit,
                         DocumentFormattingParams,
                         DocumentOnTypeFormattingParams)

modls = LanguageServer()

@modls.feature(FORMATTING)
def formatting (params: DocumentFormattingParams):
    return []


@modls.feature(ON_TYPE_FORMATTING,
               first_trigger_character = r')')
def onTypeFormatting (params: DocumentOnTypeFormattingParams):
    line = params.position.line
    return [TextEdit(Range(Position(line, 0), Position(line, 0)), 'xxx')]

modls.start_io()
```

**Comment by yyoncho** [comment]
Thank you. This is a really amazing bug report.

**Comment by yyoncho** [comment]
PR at #2309.

@kiennq - seems like when using :cancel-handler we are leaking cleanup handles which then calls lsp--cancel-request

**Comment by AndreasMatthias** [comment]
Thank you for your fast response. This fix is working for me.
