### ISSUE TITLE
Recent changes in imenu have broken imenu for Java:

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#2311]
![image](https://user-images.githubusercontent.com/13259670/98417973-9d34f000-208a-11eb-9b2f-fac58f132d88.png)

@nbfalcon

**Comment by nbfalcon** [comment]
By recent you mean in master?

**Comment by nbfalcon** [comment]
I cannot reproduce for `lsp-lua-emmy`.

**Comment by nbfalcon** [comment]
Also not for ccls.

**Comment by nbfalcon** [comment]
I think what the issue is.
