### ISSUE TITLE
`lsp-rename`: check if supported before prompting for a name

### ISSUE THREAD

**Issue by nbfalcon** [emacs-lsp/lsp-mode#2314]
When I start using a new language sever, I don't know what it supports. If because of that I try to rename something, even though the language server doesn't support it, I just end up wasting my time coming up with a new name.

`lsp-rename` should do a capability check + prepareRename before asking the user for a new name. This will improve discoverability, because users aren't punished for not knowing that rename doesn't work.

This will be an easy fix.

**Comment by kiennq** [comment]
Nit: I think via the default key binding and `whick-key`, the rename option will show up only when the capability is supported

**Comment by nbfalcon** [comment]
@kiennq users that use `M-x` or users that have their own custom keybindings won't benefit from that though. We should strive for a consistent, good user-interface where possible.
