### ISSUE TITLE
`lsp-configure-buffer`: doesn't configure anything

### ISSUE THREAD

**Issue by nbfalcon** [emacs-lsp/lsp-mode#2318]
**Describe the bug**
When opening a new file, after `lsp-mode` is enabled for it due to call to `lsp`, none of the features in `lsp-configure-buffer` are enabled, as I concluded from debugging that function using `edebug` (`lsp-feature?` always returned nil). I noticed this because symbol occurrences weren't highlighted.

**To Reproduce**
1. Open a file
2. `M-x lsp`
3. Note that symbols aren't highlighted

**Expected behavior**

**Which Language Server did you use**
rust-analyzer, ccls, ...

**OS**
Ubuntu 20.04 LTS

**Comment by nbfalcon** [comment]
The fix was to move `lsp-configure-buffer` into `run-with-idle-timer` in `lsp-managed-mode`. I'll submit a PR soon.

**Comment by yyoncho** [comment]
I tested with several servers and with lsp-start-plain.el and it works fine.

**Comment by nbfalcon** [comment]
Perhaps it is because I set `lsp-idle-delay` to 0.0? (I prefer instantaneous symbol highlights). I'll send a gif/video soon.

**Comment by yyoncho** [comment]
> Perhaps it is because I set `lsp-idle-delay` to 0.0? (I prefer instantaneous symbol highlights). I'll send a gif/video soon.

It works with that setting as well.

**Comment by nbfalcon** [comment]
Here is how it should work, with my fix applied (note in the above pane that `lsp-configure-buffer` has been moved into `run-with-idle-timer`):
![should](https://user-images.githubusercontent.com/69264154/98595244-03fa1980-22d6-11eb-8e04-ae1225099dce.gif)
Here is how it works without my fix:
![is](https://user-images.githubusercontent.com/69264154/98595259-0bb9be00-22d6-11eb-9c8e-f55780b75903.gif)

I have noticed that without it, `lsp-configure-buffer` is never called once, and returns nil for every `lsp-feature?` check. This might be caused by some Doom-Emacs specific advice hacks, though.

**Comment by nbfalcon** [comment]
Both of this was after `projectile-kill-project-buffers`.

**Comment by nbfalcon** [comment]
And this issue might be limited to ccls/rust-analyzer.

**Comment by nbfalcon** [comment]
From looking at Doom's lsp module code, I don't see anything that might cause problems.

**Comment by yyoncho** [comment]
work with rust analyzer as well. Did you test with lsp-start-plain.el?

**Comment by nbfalcon** [comment]
I can reproduce with lsp-start-plain.el, clangd.

**Comment by yyoncho** [comment]
I tested with clangd as well and lsp-start-plain.el and it works fine. How do you test with lsp-start-plain.el?

**Comment by nbfalcon** [comment]
- `emacs -q scripts/lsp-start-plain.el`
- `M-x eval-buffer`
- `M-x lsp` ; this buffer will be configured correctly
- `M-x find-file print_password.c`

Note that I am using Emacs 27.1, which might be related.

**Comment by nbfalcon** [comment]
I also have no idea why the fix works...

**Comment by yyoncho** [comment]
You should do M-x lsp after M-x find-file

**Comment by nbfalcon** [comment]
But `lsp` is added to `prog-mode-hook` (from which `c-mode` derives), and I got all other intellisense features, like hover and eldoc.

**Comment by nbfalcon** [comment]
Note that the issue is fixed if I do `M-x lsp` agai, but that shouldn't be necessary when everything else works fine instantly.

**Comment by trivialfis** [comment]
@nbfalcon Did you try : `M-; (lsp-configure-buffer)` after opening the C/C++ file with clangd?  I have a similar issue and were able to trace it to bd5c782cbecddde88c9e054b53a3db745fb6d8d7.

**Comment by nbfalcon** [comment]
`lsp-configure-buffer` fixes that, yes.

**Comment by nbfalcon** [comment]
That might explain why `lsp-feature?` always yielded nil.

**Comment by rrudakov** [comment]
I think this issue is related https://github.com/emacs-lsp/lsp-java/issues/292

**Comment by yyoncho** [comment]
can you test #2327? It fixes emacs-lsp/lsp-java#292

**Comment by rrudakov** [comment]
@yyoncho Tested. This change fixes the issue.
