### ISSUE TITLE
lsp-mode always asks if file-watcher should be disabled for csharp-mode buffers.

### ISSUE THREAD

**Issue by josteink** [emacs-lsp/lsp-mode#2320]
**Describe the bug**
When working with any non-trivial .NET Core solution, you typically end up with many individual sub-projects, each with their own individual build-output, which gets collated/aggregated again and again as you get higher and higher up in the overall solution/project-hierarchy.

The result is a lot of files. Enough files to trigger a warning about file-watcher limits when starting a new `csharp-mode` LSP workspace.

**To Reproduce**
1. Create a .NET Core solution
2. Create around 10 projects, with a project dependency-tree around 3-4 nodes deep.
3. Build the solution.
4. Open Emacs, try to load any C#-file in that solution and activate `lsp-mode`.

**Expected behavior**
To be able to start editing code.

I do not expect, every time, to be asked if I want to disable file-watchers due to excessive amounts of files.

**Which Language Server did you use**
lsp-csharp

**OS**
Linux, but probably not applicable to bug at hand.

**Error callstack**
None.

**Comment by yyoncho** [comment]
As per the printed message:

> LSP :: You can configure this warning with the `lsp-enable-file-watchers' and `lsp-file-watch-threshold' variables

you are supposed to touch these variables if you want to get the warning away.

**Comment by josteink** [comment]
That either disables watching all together or wastes resources on watching build output. 

Such build-output should just be ignored, like we ignore it for other language types. 

(Which is what is done in the PR)

**Comment by yyoncho** [comment]
> Such build-output should just be ignored, like we ignore it for other language types.

Ah, ok. I misunderstood what is your expected fix.
