### ISSUE TITLE
Add support for codeAction/resolve

### ISSUE THREAD

**Issue by matklad** [emacs-lsp/lsp-mode#2322]
LSP 1.16 will introduce `codeAction/resolve` request: 

https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#codeAction_resolve

This one is pretty significant for performance, so I am opening it in advance, as rust-analyzer will make heavy use of this request  (we actually do already, via a custom hacky extension) :-)

**Comment by ericdallo** [comment]
@yyoncho I believe the code would be similar to the `codeLens/resolve`, right?

**Comment by yyoncho** [comment]
> @yyoncho I believe the code would be similar to the `codeLens/resolve`, right?

IMHO it will be much simpler.

**Comment by nbfalcon** [comment]
Wouldn't this just need an
```emacs-lisp
(unless (or edit? command?)
  (setq action (lsp-request "codeAction/resolve" ...))
```
[here](https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el#L5182)? (along with constructing a correct params struct, with the data? field passed trough, and the capability).

**Comment by kiennq** [comment]
> Wouldn't this just need an
> 
> ```emacs-lisp
> (unless (or edit? command?)
>   (setq action (lsp-request "codeAction/resolve" ...))
> ```
> 
> [here](https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el#L5182)? (along with constructing a correct params struct, with the `data?` field passed trough, and the capability).

We will also need to cache the already resolved code action, decide which properties can lazy loaded (declaring `resolveSupport`) and checking server capability for that.

**Comment by yyoncho** [comment]
@ericdallo you fixed that, right?

**Comment by ericdallo** [comment]
yeah, clojure-lsp is already using that :)
