### ISSUE TITLE
[3.16] [Completion] Support resolveSupport

### ISSUE THREAD

**Issue by kiennq** [emacs-lsp/lsp-mode#2324]
This is new capability that will be replacing `completion.completionItem.resolveAdditionalTextEditsSupport`.
Please refer to new spec https://github.com/microsoft/language-server-protocol/blob/gh-pages/_specifications/specification-3-16.md#textDocument_completion

**Comment by ericdallo** [comment]
Also the spec adds: 
* `insertReplaceSupport`
* `insertTextModeSupport`
