### ISSUE TITLE
[Bug] Need config lsp twice in go-mode-hook to take effect

### ISSUE THREAD

**Issue by hainesc** [emacs-lsp/lsp-mode#2326]
**Describe the bug**
Need config `lsp` twice in go-mode-hook to take effect

After upgrade the lsp-mode to 202011xx(I didn't remember the exactly version from which it works wrong), I have to config `lsp` twice in my go-mode-hook to make it take effect. Before that, I only write one `lsp` word in the my .emacs file
```
 
'(go-mode-hook
   '(lsp lsp company-mode yas-minor-mode
...... (other hooks)
```

The first day I upgrade the lsp-mode to 202011xx, when I opened golang source file, no complete popup, no jump, it seems that the lsp-mode not enabled, so I typed `M-x lsp`, it works. When I checked the go-mode-hook, `lsp` was there as what it was, so I tried add another `lsp`, it works.

**To Reproduce**

**Expected behavior**
Only one `lsp` in config file should works well

**Which Language Server did you use**
Golang and gopls

**OS**
MacOS 10.15.6
Emacs: Version 27.1, download from https://emacsformacosx.com/

**Error callstack**
If there is an error please reproduce the issue with `toggle-debug-on-error` and after setting `lsp-print-io` to t, and then include the callstack and attach the content of `*lsp-log*` buffer and the content of the server log(use `lsp-workspace-show-log`)

If `emacs` hangs please do `M-x` `toggle-debug-on-quit` and then do `C-g` when emacs hangs and include the callstack as part of the issue report.

``` emacs-lisp
(setq lsp-print-io t)
```

**Comment by yyoncho** [comment]
proposed fix at #2327.
