### ISSUE TITLE
[Documentation] Document lsp-install-server on the website

### ISSUE THREAD

**Issue by jarivm** [emacs-lsp/lsp-mode#2336]
After having trouble installing a language server (ESLint) manually, I discovered `lsp-install-server`. This made installing ESLint trivial, so I wish I found out about it sooner. 

**Suggested changes**
- Document `lsp-install-server` on the [languages page](https://emacs-lsp.github.io/lsp-mode/page/languages/), and mention not every language server is currently supported.
- Document installing ESLint via `lsp-install-server` on the [ESLint page](https://emacs-lsp.github.io/lsp-mode/page/lsp-eslint/) and remove the link to the (now) outdated Wiki page. 

I am going to start working on this myself!

**Comment by yyoncho** [comment]
We used to document that the lsp-mode supports automatic installation - like this https://github.com/emacs-lsp/lsp-mode/blob/bc25dfb16dbfea4804c45a46504bc0fe7d9d44b9/docs/lsp-clients.json#L139 . This property is not updated for all servers that support automatic installation. It will be nice if we list the automatic and manual installation where appropriate in addition to covering lsp-install-server in the getting started section.

**Comment by ericdallo** [comment]
I think we can close this, right?
