### ISSUE TITLE
`lsp-xref`: highlights at most one ref per summary

### ISSUE THREAD

**Issue by nbfalcon** [emacs-lsp/lsp-mode#2342]
**Describe the bug**
`lsp-xref-find-references` highlights the symbol being referenced, but only one of them per line.

**To Reproduce**
1. Open an `lsp`-managed file
2. Write something like "foo = foo"
3. `xref-find-references` with `point` on foo shows a single reference line, with only one of the two `foo`s highlighted.

**Expected behavior**
All references in an `xref` summary from `lsp` should be marked, preferrably even with a custom face instead of just `highlight`.

The relevent part of `lsp` is `lsp--xref-make-item`.

**Comment by yyoncho** [comment]
It works fine on my side.

**Comment by yyoncho** [comment]
![Screenshot](https://user-images.githubusercontent.com/13259670/99589125-41f0ef00-29f4-11eb-9648-68e0a195049e.png)

**Comment by nbfalcon** [comment]
You are right, everything works as it should; my problems were due to variable scope.
