### ISSUE TITLE
Eldoc should show function signature only

### ISSUE THREAD

**Issue by amol-mandhane** [emacs-lsp/lsp-mode#235]
Currently, the eldoc of lsp-mode shows entire documentation string of the function/class/variable. This can show a lot of text in minibuffer which limits visibility (for example #96 #224). This get seriously messy with functions with long documentations. Showing full documentation on hover is more suitable for UI-oriented editors like VSCode which can show a popup with scroll-bar to show documentation in a more compact fashion.

As per [Eldoc Homepage](https://www.emacswiki.org/emacs/ElDoc), it is meant only for function signatures. Quite a lot of Emacs tooling follows this convention. LSP protocol has a method to get signature, "textDocument/signatureHelp". This should be used for eldoc instead of textDocument/hover. The hover method can be linked to a "help-at-point" kind of keybinding instead.

#226 adds signatureHelp support to LSP mode. This can be a drop in replacement for `lsp--on-hover`.

**Comment by tadfisher** [comment]
Yep, I'd suggest adding an option to display hover info in a separate window, like C-h f.

**Comment by wberrier** [comment]
Is this still an issue?

I see the `lsp-hover-text-function` customization, but when I set it to `'lsp--text-document-signature-help`, I don't get any eldoc functionality at all.

?

**Comment by yyoncho** [comment]
@wberrier you may try to `lsp-eldoc-render-all` to `nil`.

**Comment by yyoncho** [comment]
I am closing this issue since there already is support signature help in lsp-mode.

**Comment by wberrier** [comment]
@yyoncho setting `lsp-eldoc-render-all` to `nil` produces only the function documentation, but not the signature.

I guess I should open a new issue then that `'lsp--text-document-signature-help` doesn't seem to be working correctly?

**Comment by wberrier** [comment]
Opened a new issue: #443
