### ISSUE TITLE
*lsp-log* buffer undo overflow

### ISSUE THREAD

**Issue by axelson** [emacs-lsp/lsp-mode#2355]
**Describe the bug**
If running a server that generates a very large amount of output then the undo info can overflow

**To Reproduce**
I don't have this, but if it's needed I can generate one

**Expected behavior**
The undo buffer should not overflow because undo is not needed in this read-only buffer

**Which Language Server did you use**
ElixirLS (while developing on the server)

**OS**
Arch Linux

**Error callstack**
N/A

**Comment by jcs090218** [comment]
We should probably stop `undo`/`redo` in the log buffer? 😕 

Thanks for reporting this issue to us! 👍

**Comment by axelson** [comment]
yeah it seems like unnecessary memory use

**Comment by jcs090218** [comment]
This should fix by #2376. Feel free to reopen this issue if you find out useful! Thanks! 😄

**Comment by axelson** [comment]
@jcs090218 Thanks!
