### ISSUE TITLE
[elm-ls] Error from Language Server

### ISSUE THREAD

**Issue by WnP** [emacs-lsp/lsp-mode#2362]
**Describe the bug**

Opening a buffer with an elm file raise LSP errors:

```
LSP :: Connected to [elm-ls:271837 status:starting].
LSP :: elm-ls:271837 initialized successfully
LSP :: Error from the Language Server: Unhandled method textDocument/codeAction (Method not Found)
```

**To Reproduce**

1) Install install elm-language-server as described in [lsp-mode elm language documentation](https://emacs-lsp.github.io/lsp-mode/page/lsp-elm/#installation)

```sh
npm i -g @elm-tooling/elm-language-server  # alternatively use lsp-install-server if you wish
```

2) Add `elm-mode` to [lsp-start-plain.el pkg-list](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el#44), and add the following at the end:

```el
(add-hook 'elm-hook 'lsp-deferred)
```

3) Open any elm source file (even an empty one like `/tmp/Main.elm`) and look at `*Messages*` buffer.

**Expected behavior**

No errors in `*Messages*` buffer.

**Which Language Server did you use**

`elm-ls`

**OS**

Linux

**Comment by yyoncho** [comment]
Can you provide client-server log?

**Comment by WnP** [comment]
Hi @yyoncho,

Actually both `*elm-js*` and `*elm-js::stderr*` buffers are empty. Only `*lsp-log*` buffer contain some logs.

If I test on an empty project:

```console
$ mkdir /home/me/src/elm-lsp-test && cd /home/me/src/elm-lsp-test && elm init
$ cat <<EOF >./src/Main.elm
module Main exposing (foo)

foo : List Int
foo = List.filter ((/=) 2) [1,2,3,4]
EOF
$ emacs ./src/Main.elm
```

Then `*lsp-log*` buffer looks like this:


```
Command "/home/me/.yarn/bin/elm-ls --stdio" is present on the path.
Command "/home/me/.yarn/bin/elm-ls --stdio" is present on the path.
Found the following clients for /home/me/src/elm-lsp-test/src/Main.elm: (server-id elm-ls, priority -1)
The following clients were selected based on priority: (server-id elm-ls, priority -1)
Loading Elm tree-sitter syntax from ../../../../.config/yarn/global/node_modules/@elm-tooling/elm-language-server/out/tree-sitter-elm.wasm
Found 1 elm.json files for workspace /home/me/src/elm-lsp-test
Found 1 unique elmWorkspaces for workspace /home/me/src/elm-lsp-test
Starting language server for folder: file:///home/me/src/elm-lsp-test
Elm binary not found, did you install and setup the path to your binary?
Could not figure out elm version, this will impact how good the server works. 
 undefined
Reading elm.json from /home/me/src/elm-lsp-test/elm.json
2 source-dirs and test folders found
Glob /home/me/src/elm-lsp-test/src/**/*.elm
Glob /home/me/src/elm-lsp-test/tests/**/*.elm
Glob /home/me/.elm/undefined/packages/elm/browser/1.0.2/**/*.elm
Glob /home/me/.elm/undefined/packages/elm/core/1.0.5/**/*.elm
Glob /home/me/.elm/undefined/packages/elm/html/1.0.0/**/*.elm
Error parsing files for /home/me/src/elm-lsp-test/elm.json:
Error: ENOENT: no such file or directory, open '/home/me/.elm/undefined/packages/elm/browser/1.0.2/elm.json'
Received new elm-analyse report with 0 messages
```

But `elm` binary is in the path:

```console
$ which elm
/home/me/.yarn/bin//elm
```
Here is the content of `/home/me/src/elm-lsp-test/elm.json`:

```json
{
    "type": "application",
    "source-directories": [
        "src"
    ],
    "elm-version": "0.19.1",
    "dependencies": {
        "direct": {
            "elm/browser": "1.0.2",
            "elm/core": "1.0.5",
            "elm/html": "1.0.0"
        },
        "indirect": {
            "elm/json": "1.1.3",
            "elm/time": "1.0.0",
            "elm/url": "1.0.0",
            "elm/virtual-dom": "1.0.2"
        }
    },
    "test-dependencies": {
        "direct": {},
        "indirect": {}
    }
}
```

Which is the default one provide by `elm init` command. well, in fact `ENOENT` error it due to the fact it doesn't find the elm version, because the file is present in the folder if you replace `undefined` by the version number.

By the way, using a project with `elm` binary provided inside `node_modules` folder at project root I don't have this error which tell it can't find the binary, but still have the `Unhandled method` error in `*Messages*` buffer.

**Comment by WnP** [comment]
Hi @yyoncho,

I'm closing this issue because:
- `ENOENT` error can be avoided using `lsp-elm-elm-path`
- original error doesn't affect lsp-mode as far as I can see.

Also, must of the other bug I can see looks coming from the language server itself and no lsp-mode.

**Comment by yyoncho** [comment]
@WnP thank you
