### ISSUE TITLE
tsconfig.json overridden values not respected showing false positives on linting

### ISSUE THREAD

**Issue by shackra** [emacs-lsp/lsp-mode#2374]
**Describe the bug**
tsconfg.json `extends` is not being respected, highlighting several false positive.

**To Reproduce**
- clone https://github.com/shackra/stackoverflow-alias-bug
- start emacs with `-q` and load https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el
- visit `stackoverflow-alias-bug/src/App.tsx`, run `lsp` and wait for linting errors that shouldn't exist
- the linting errors should surface now:

```
 stackoverflow-alias-bug 4 /home/jorge/code
    App.tsx 4 src/
      [typescript] Module 'things/thing' was resolved to '/home/jorge/code/stackoverflow-alias-bug/src/things/thing.tsx', but '--jsx' is not set. (2:15)
      [typescript] Cannot use JSX unless the '--jsx' flag is provided. (6:4)
      [typescript] Cannot use JSX unless the '--jsx' flag is provided. (7:6)
      [typescript] Cannot use JSX unless the '--jsx' flag is provided. (8:8)
```

**Expected behavior**
since the option `jsx` is overridden from `react-jsx` to `react` via `./custom.json` these errors shouldn't show up.

**Which Language Server did you use**
ts-ls

**OS**
GNU/Linux (Arch Linux)

**Error callstack**
there is none.

**Comment by yyoncho** [comment]
What is the expected fix here? lsp-mode is reporting what the server has sent to it.

**Comment by shackra** [comment]
> What is the expected fix here? lsp-mode is reporting what the server has sent to it.

well, I wonder why the server isn't honoring `tsconfig.json`, if I change the values directly on `tsconfig.json` things works but that's a no-no with `create-react-app` applications since react-scripts override everything in the file except the `extends` option.

**Comment by shackra** [comment]
indeed, nothing to do with the client, I resolved my issue per https://github.com/theia-ide/typescript-language-server/issues/82#issuecomment-743800813
