### ISSUE TITLE
Overloads List - Minibuffer Scrolling

### ISSUE THREAD

**Issue by nickenchev** [emacs-lsp/lsp-mode#2377]
Please ask your questions at https://gitter.im/emacs-lsp/lsp-mode
Hi, can you please tell me how I can scroll the minibuffer and see the rest of the overloads for a particular method? Seems like none of my google searches about how to scroll the minibuffer yield anything.

![Screenshot_20201204_105924](https://user-images.githubusercontent.com/8262271/101185452-e2175c80-361f-11eb-86bc-5a1ce803eeca.png)

**Comment by yyoncho** [comment]
Use M-n/M-p.
