### ISSUE TITLE
How I can launch D Language server?

### ISSUE THREAD

**Issue by route616** [emacs-lsp/lsp-mode#2381]
I installed lsp-mode & d-mode and wrote the following to the config:
```emacs-lisp
(lsp-register-client
 (make-lsp-client
  :new-connection (lsp-stdio-connection '("~/.dub/packages/serve-d-0.6.0/serve-d/serve-d"))
  :major-modes '(d-mode)
  :server-id 'serve-d))
```
also tried:
```emacs-lisp
(lsp-register-client
 (make-lsp-client
  :new-connection (lsp-stdio-connection '("dls"))
  :major-modes '(d-mode)
  :server-id 'dls))
```
In response, writes to the log:
"Symbol's function definition is void: lsp-register-client"

**Comment by yyoncho** [comment]
it should be wrapped with `(with-eval-after-load 'lsp-mode ...)`

**Comment by route616** [comment]
BIG THX! I lost 3 days.)

**Comment by hyunlee1o** [comment]
saw this and fixed it in minutes rather than days, thanks :)
