### ISSUE TITLE
`lsp-interface`: don't pollute the `dash-expand` namespace

### ISSUE THREAD

**Issue by nbfalcon** [emacs-lsp/lsp-mode#2390]
`lsp-interface` creates unnamespaced expanders for every interface. As new ones get added, more and more `dash-expand` functions will be taken. This doesn't actually cause issues yet, but might in the future (wrt. backwards-compatibility).

**Comment by yyoncho** [comment]
The option here is to prefix the lsp-mode entities with lsp: and effectively create a subnamespacing in dash like we do in lsp-mode extensions. ATM I don't this is needed considering that it is technically very difficult to hit that issue given the fact that even if there is collision it most likely will work given the fact that the expand methods are used only during the compilation. I suggest closing this issue until we have something to address.

**Comment by nbfalcon** [comment]
I will close because there are no problems yet.
