### ISSUE TITLE
what 's the reason ? LSP :: one.py not in project or it is blacklisted.

### ISSUE THREAD

**Issue by roderick-liu** [emacs-lsp/lsp-mode#2392]
Please ask your questions at https://gitter.im/emacs-lsp/lsp-mode
LSP :: one.py not in project or it is blacklisted.

**Comment by jcs090218** [comment]
Is the file `one.py` inside the project or has been added to blacklist? If yes, then LSP wouldn't start.

**Comment by nbfalcon** [comment]
You probably pressed "Esc" when the "LSP import project" prompt came, unless you blacklisted it explicitly using `lsp-blacklist-project` (which is unlikely).

All you need to do to fix this is to press `M-x lsp` followed by `i`, with one.py as the current buffer.

**Comment by eeowaa** [comment]
I am having the same problem right now. After `M-x lsp`, I do not get a prompt after which I can type `i` -- I just get that error message.

**Comment by yyoncho** [comment]
1. Make sure that you do not run with lsp-auto-guess-root set to t.
2. Make sure that you havent blacklisted current folder accidentally, run `M-x lsp-workspace-blacklist-remove`

**Comment by eeowaa** [comment]
I verified that `lsp-auto-guess-root` was nil, and although the directory I was working in was not in the blacklist, one of the ancestor directories was (my home directory), so I removed that with `M-x lsp-workspace-blacklist-remove`. Unfortunately the problem still remains for me.

**Comment by yyoncho** [comment]
@eeowaa can you test with lsp-start-plain.el as described in here: https://github.com/emacs-lsp/lsp-mode/blob/master/.github/ISSUE_TEMPLATE/bug_report.md . Before that can you delete lsp-session-file?

**Comment by eeowaa** [comment]
After deleting the `lsp-session-file` and restarting Emacs, I no longer had the problem.

**Comment by yyoncho** [comment]
Marking the bug as closed. You can use it for further questions.

**Comment by avatar-lavventura** [comment]
@yyoncho The bug report link you give seems dead

**Comment by yyoncho** [comment]
@avatar-lavventura you can see the bug template when you click new issue.

**Comment by didibus** [comment]
Something annoying is that if you blacklist a parent folder, like my home dir, it seems to apply recursively, so lsp doesn't start for files under project folders inside my home folder.

**Comment by avatar-lavventura** [comment]
@didibus That was the exact issue I am having.. I wish there is a mechanism to prevent recursively folder covering.
