### ISSUE TITLE
C/C++ tutorial minimal config

### ISSUE THREAD

**Issue by HumHongeKamyaab** [emacs-lsp/lsp-mode#2396]
I found minimal config found on C/C++ lsp very useful. 
https://github.com/emacs-lsp/lsp-mode/blob/master/docs/tutorials/CPP-guide.md#lsp-mode-configuration

I have some suggestion/feedback on minimal config ...
- Can you add more comments in it to tell which line do what in emacs/elisp 
- Can you modify/suggest this config for `use-package` users
- Also some people prefer `ivy` over helm, can you suggest alternative config for it.

These changes/suggestions will help us to properly include this minimal example with our main emacs config, so that we can understand dependencies/**priority** setting of other packages like company, yasnippet, flycheck.

**Comment by yyoncho** [comment]
Thank you for the feedback. 

First, have you checked SystemCrafters tutorials https://www.youtube.com/watch?v=E-NAM9U5JYE&list=PLEoMzSkcN8oNvsrtk_iZSb94krGRofFjN ? 

What I would suggest addressing your points is to have a separate tutorial that is not language-specific. I want to keep the minimal example minimal so we can reuse it in the other language-specific tutorials. It won't be convenient to describe all packages in all language-specific tutorials but it will be better to have one generic one. Some prefer flymake over flycheck, project.el over projectile, some vanilla over helm/lsp and so on.

**Comment by HumHongeKamyaab** [comment]
Thanks for the reply.

I agree with your point. I came to lsp-mode due to SystemCrafters youtube video (https://github.com/daviwil/emacs-from-scratch) . He has not made video of C/C++ yet, so I was trying to configure it myself.

Also I would like to point that if this is minimal config, then it should not specific to `helm` package which defeats purpose of minimal config. Also in general, using `use-package` in minimal config  helps one to understand setting priorities of different packages.

Can you explain how following section is related with project root setting
https://github.com/emacs-lsp/lsp-mode/blob/master/docs/tutorials/CPP-guide.md#project-setup

What should I do to specify directory path of compile_commands.json file. I presume that project root means directory of .json file. Most people prefer to keep it in different types of build directory, how can we give path to one of them.

Thanks again for great tutorial. This made my transition from `cmake-ide` package to `lsp-mode` fairly smooth.

**Comment by yyoncho** [comment]
> Also I would like to point that if this is minimal config, then it should not be specific to `helm` package which defeats purpose of minimal config.

The idea is to have a minimal *functional* config. In general. The config will work without projectile, company, lsp-treemacs, flymake, etc. as well. We cannot create useful minimal config without performing 

> What should I do to specify directory path of compile_commands.json file. I presume that project root means directory of .json file. Most people prefer to keep it in different types of build directory, how can we give path to one of them.

You may pass it via a command like args "--compile-commands-dir" by setting `lsp-clients-clangd-args`. (run `clangd --help` for other options). Also, the project root is not always the directory that has the json. The json can be somewhere else.

**Comment by HumHongeKamyaab** [comment]
just to add, 
suppose project root folder is `~/project-root`
path of `compile_commands.json` for this project is `~/project-root/build-dir/compile_commands.json`
one can put following in `~/project-root/.dir-locals.el` file
```
((nil . ((eval .
               (setq lsp-clients-clangd-args
                     (concat "--compile-commands-dir=" (concat
                      (locate-dominating-file
                       default-directory
                       dir-locals-file)
                      "build-dir")))))))
```
It will automatically set compile arguments for `clangd` when you open any file in project.
