### ISSUE TITLE
Rust - Insert explicit type: existing shortcuts?

### ISSUE THREAD

**Issue by dannywillems** [emacs-lsp/lsp-mode#2398]
I've just switched to rust-analyzer and I find sometimes very handy to add explicit type annotations.
Like you see on the screenshot below, Emacs suggests me to add the type. That's nice and works when I click on it. However, I'd like to do it with a shortcut. Any way to do it?

![Screenshot from 2020-12-10 15-55-44](https://user-images.githubusercontent.com/6018454/101788376-4f376000-3b00-11eb-94c4-5aeb8fcc528d.png)

**Comment by yyoncho** [comment]
`M-x lsp-execute-code-action`

**Comment by dannywillems** [comment]
Thanks @yyoncho
