### ISSUE TITLE
add `lsp-restart`

### ISSUE THREAD

**Issue by m4b** [emacs-lsp/lsp-mode#24]
It would kill the current lsp if any is running, and restart a new one (without query).

This is useful for debugging, etc.

**Comment by phst** [comment]
This is somewhat related to https://github.com/emacs-lsp/lsp-mode/issues/111 or https://github.com/emacs-lsp/lsp-mode/issues/77. I.e. once `(lsp-mode 'toggle)` actually toggles, you can easily implement `lsp-restart` using

```elisp
(defun lsp-restart ()
  (lsp-mode 0)
  (lsp-mode 1))
```

**Comment by phst** [comment]
Also, lsp-mode should restart crashing language server processes automatically.

**Comment by myrgy** [comment]
Hi @m4b , I have a problem with restart function 
```
Debugger entered--Lisp error: (void-function nil)
  nil()
  lsp-restart-workspace()
  funcall-interactively(lsp-restart-workspace)
  call-interactively(lsp-restart-workspace record nil)
  command-execute(lsp-restart-workspace record)
  helm-M-x(nil #("lsp-restart-workspace" 0 21 (match-part "lsp-restart-workspace")))
  funcall-interactively(helm-M-x nil #("lsp-restart-workspace" 0 21 (match-part "lsp-restart-workspace")))
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
```
could you please provide any hints?

**Comment by m4b** [comment]
@myrgy would be better to ask the devs who worked on this, which I believe is @alanz

**Comment by alanz** [comment]
@myrgy What language are you using?  Please show me how you are configuring it.

Do you have up to date versions of `lsp-mode`, `lsp-ui`, and the client for your language?

**Comment by myrgy** [comment]
Im using emacs 26 with cquery(c++).
I got this callstack in latest version, I've checked it twice.

**Comment by alanz** [comment]
Please point me at a place where I can see the source for your client

**Comment by myrgy** [comment]
Here is elisp part: https://github.com/cquery-project/emacs-cquery
And here is the daemon: https://github.com/cquery-project/cquery

**Comment by alanz** [comment]
@MaskRay do you have any ideas?

**Comment by myrgy** [comment]
@alanz, pkease, take a look here. https://github.com/emacs-lsp/lsp-mode/issues/285
This issue was solved. Sorry for that mess. But I have another one. Thank you in advance!

**Comment by alanz** [comment]
Ok, disclaimer, this code was written to restart a currently running server.

What happens if the server has died is beyond my knowledge.

**Comment by MaskRay** [comment]
If the server dies, the command may not work?

**Comment by alanz** [comment]
I have no idea what will happen. I've never tried or experienced that.

**Comment by myrgy** [comment]
In my case I was trying to restart server after crash

**Comment by amosbird** [comment]
I'm also facing the same issue (cannot restart cquery after toggling lsp-mode).
