### ISSUE TITLE
lsp--workspace-print uses an obtrusive face

### ISSUE THREAD

**Issue by fanf2** [emacs-lsp/lsp-mode#2403]
**Describe the bug**

In my modeline, I see [**_rust-analyzer:1234_**] and the bold-italic face is very obtrusive. I can't make it less obtrusive without making bold-italic look wrong in other contexts.

**Expected behavior**

Either make the face customizable, or use the default modeline face.

**Which Language Server did you use**

rust-analyzer

**OS**

Mac OS

**Patch**

I have bodged my copy of `lsp-mode` as follows:

```
--- lsp-mode-20201211.1939/lsp-mode.el~	2020-12-12 20:26:51.000000000 +0000
+++ lsp-mode-20201211.1939/lsp-mode.el	2020-12-13 16:41:41.000000000 +0000
@@ -7528,8 +7528,8 @@
   "Visual representation WORKSPACE."
   (let* ((proc (lsp--workspace-cmd-proc workspace))
          (status (lsp--workspace-status workspace))
-         (server-id (-> workspace lsp--workspace-client lsp--client-server-id symbol-name (propertize 'face 'bold-italic)))
-         (pid (propertize (format "%s" (process-id proc)) 'face 'italic)))
+         (server-id (-> workspace lsp--workspace-client lsp--client-server-id symbol-name))
+         (pid (format "%s" (process-id proc))))
 
     (if (eq 'initialized status)
         (format "%s:%s" server-id pid)
```

**Comment by yyoncho** [comment]
I don't see a reason not to accept this patch. Willing to turn it into PR?
