### ISSUE TITLE
lsp-mode interferes with buffer indent set-up even when lsp-enable-indentation is nil

### ISSUE THREAD

**Issue by gdanov** [emacs-lsp/lsp-mode#2408]
**Describe the bug**
I'm trying to use lsp-mode alongside Cider (for clojure development). I want to use cider's buffer formatting.  (setq lsp-enable-indentation nil) does not help. The result is that some vars set-up by cider are set to nil (example: indent-region-function).

**To Reproduce**
add lsp-mode and lsp-clojure to vanilla prelude emacs, open clojure buffer and try to use cider's formatting...

**Expected behavior**
I'd expect that lsp-mode does not touch anything formatting related when indent-region-function is nil

**Which Language Server did you use**
lsp-clojure

**OS**
os x

**Error callstack**
nothing useful in any of the log bufers

**Comment by yyoncho** [comment]
We should unset `indent-region-function` only if it is set to lsp-mode's formatting function.
