### ISSUE TITLE
Map svelte-ls config keys to user options

### ISSUE THREAD

**Issue by raxod502** [emacs-lsp/lsp-mode#2409]
**Feature request**
It would be great if the configuration for the Svelte language server could be adjusted by setting user options, similar to the setup for many other language servers (e.g., to be specific, gopls).

Concretely, it would be great to be able to disable certain warnings from Svelte. Currently this can only be done through the language server configuration. I reported the problem upstream at https://github.com/sveltejs/language-tools/issues/650#issuecomment-734930568 and was pointed to [the documentation for the VS Code extension](https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode#settings) which contains a list of allowed configuration keys.

I would be happy to implement this, but don't currently have the bandwidth, so I thought I would at least create the issue for now.

**Which Language Server did you use**
`svelte-ls` (https://github.com/sveltejs/language-tools)

**OS**
Ubuntu 20.04

**Comment by yyoncho** [comment]
PR at https://github.com/emacs-lsp/lsp-mode/pull/2411 . I haven't tested it though.
