### ISSUE TITLE
Csharp mode fails on initialization

### ISSUE THREAD

**Issue by ZacheryPD** [emacs-lsp/lsp-mode#2412]
Before logging the bug, please make sure that:
**Describe the bug**
When I open a C# file (after installing the language server through the prompt) I immediately see "Server csharp: 317 status:starting exited with status exit. do you want to restart it?" It seems this happens with slightly different error codes on any .cs file in that repository.

**To Reproduce**
Use my emacs config: https://github.com/ZacheryPD/.dotfiles
Example project and file: https://github.com/ZacheryPD/S3G/blob/master/src/TemplateSubstitution/BlockConverterStrategies/ParagraphConverterStrategy.cs
(this project should build with docker, so hopefully that's easy to set up).

**Expected behavior**
I expect the server to start =( 

**Which Language Server did you use**
This was in csharp mode

**OS**
I'm running PopOS 20.10

**Error callstack**
[Trace - 09:52:56 AM] Sending request 'initialize - (7)'.
Params: {
  "processId": null,
  "rootPath": "~/Development/S3G",
  "clientInfo": {
    "name": "emacs",
    "version": "GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.21)\n of 2020-08-31"
  },
  "rootUri": "~/Development/S3G",
  "capabilities": {
    "workspace": {
      "workspaceEdit": {
        "documentChanges": true,
        "resourceOperations": [
          "create",
          "rename",
          "delete"
        ]
      },
      "applyEdit": true,
      "symbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        }
      },
      "executeCommand": {
        "dynamicRegistration": false
      },
      "didChangeWatchedFiles": {
        "dynamicRegistration": true
      },
      "workspaceFolders": true,
      "configuration": true
    },
    "textDocument": {
      "declaration": {
        "linkSupport": true
      },
      "definition": {
        "linkSupport": true
      },
      "implementation": {
        "linkSupport": true
      },
      "typeDefinition": {
        "linkSupport": true
      },
      "synchronization": {
        "willSave": true,
        "didSave": true,
        "willSaveWaitUntil": true
      },
      "documentSymbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        },
        "hierarchicalDocumentSymbolSupport": true
      },
      "formatting": {
        "dynamicRegistration": true
      },
      "rangeFormatting": {
        "dynamicRegistration": true
      },
      "rename": {
        "dynamicRegistration": true,
        "prepareSupport": true
      },
      "codeAction": {
        "dynamicRegistration": true,
        "isPreferredSupport": true,
        "codeActionLiteralSupport": {
          "codeActionKind": {
            "valueSet": [
              "",
              "quickfix",
              "refactor",
              "refactor.extract",
              "refactor.inline",
              "refactor.rewrite",
              "source",
              "source.organizeImports"
            ]
          }
        }
      },
      "completion": {
        "completionItem": {
          "snippetSupport": true,
          "documentationFormat": [
            "markdown"
          ],
          "resolveAdditionalTextEditsSupport": true
        },
        "contextSupport": true
      },
      "signatureHelp": {
        "signatureInformation": {
          "parameterInformation": {
            "labelOffsetSupport": true
          }
        }
      },
      "documentLink": {
        "dynamicRegistration": true,
        "tooltipSupport": true
      },
      "hover": {
        "contentFormat": [
          "markdown",
          "plaintext"
        ]
      },
      "foldingRange": {
        "dynamicRegistration": true
      },
      "callHierarchy": {
        "dynamicRegistration": false
      },
      "publishDiagnostics": {
        "relatedInformation": true,
        "tagSupport": {
          "valueSet": [
            1,
            2
          ]
        },
        "versionSupport": true
      }
    },
    "window": {
      "workDoneProgress": true
    }
  },
  "initializationOptions": null,
  "workDoneToken": "1"
}

**Comment by ZacheryPD** [comment]
Continuing to debug here. The installed omnisharp seems to work when started from my terminal, but when started from a shell within emacs it fails with the same errors above. I am suspicious this is a shell config error.

**Comment by yyoncho** [comment]
Can you try to start `emacs` from command line as well? It

**Comment by ZacheryPD** [comment]
This is very odd! I am running Emacs 26 in a GUI so I installed the terminal version for my distro, and that immediately started omnisharp no problem. I also then opened up GUI emacs again and it was able to find the server without a problem. After a restart to get back to ground zero, Gui Emacs can no longer see the server (presumably because it's stopped.) Curious...

**Comment by ZacheryPD** [comment]
Another update, I am running Emacs from this flatpack installation, and I'm now wondering if my shell interactions are being hampered somehow because of that.  https://flathub.org/apps/details/org.gnu.emacs

**Comment by ZacheryPD** [comment]
Following that idea, I decided to uninstall my flatpack installation and install emacs from the Ubuntu repositories. The default Ubuntu repos have 26.3, and installing that (emacs-gtk/groovy) I was able to get it working. I think this is a problem with the way that flatpack was compiled, though I'm not certain how.  For now, running the older version of emacs is not really a problem for me.

**Comment by yyoncho** [comment]
> This is very odd! I am running Emacs 27 in a GUI so I installed the terminal
> version for my distro (which happened to only package 26, odd), and that

So, the issue is not whether you are using GUI version or TUI version - the issue is that when you start emacs from icon(or not from terminal) it won't use the same env variables as the one when you have started it from the terminal. Also, you may start the GUI version from the terminal as well and it will most likely work as expected. In order to find out what is causing your issues you may execute `M-: process-environment` and then compare what is the different between both. If the issue is in the path you may use `exec-path-from-shell` to fix your issue.

**Comment by ZacheryPD** [comment]
I'm having a hard time capturing that information since emacs likes to hide the window with the `process-environment` info in it the moment any events happen. It does look like my paths are different in the flatpack vs the .deb compiled versions, which is confusing.

**Comment by yyoncho** [comment]
You can find it in \*messages\* buffer.
