### ISSUE TITLE
Enable completion without modifying company-backends

### ISSUE THREAD

**Issue by kode9** [emacs-lsp/lsp-mode#2415]
Currently there are two options for `lsp-completion-provider` :

* `:none` which will not enable `company-mode`
* `:capf` or `nil` or `t` which will enable `company-mode` **and** prepend `company-capf` to to `company-backends`

```elisp
      (cond
       ((equal lsp-completion-provider :none))
       ((and (member lsp-completion-provider '(:capf nil t))
             (fboundp 'company-mode))
        (company-mode 1)
        (when (or (null lsp-completion-provider)
                  (member 'company-lsp company-backends))
          (lsp--warn
           "`company-lsp' is not supported anymore.  Using `company-capf' as the `lsp-completion-provider'."))
        (add-to-list 'company-backends 'company-capf))
       (t
        (lsp--warn "Unable to autoconfigure company-mode.")))
```

I'd like to be able to enable completion but manage my backends without them being overwritten.

I think it's easy to achieve by either

* Changing the behavior of `nil` or `t` to enable company without changing `company-backends`
* Adding an option to `lsp-completion-provider`, e.g `:custom`
* Adding a separate `defcustom`, e.g `lsp-completion-setup-backends`

I guess I can submit a PR if needed and if it makes sense.

**Comment by kiennq** [comment]
The other approach is to use `global-company-mode` independent from `lsp-mode`.
So you will have your own backends configuration independent from `lsp-mode` too.

**Comment by ericdallo** [comment]
FYI @yyoncho

**Comment by yyoncho** [comment]
> * `:none` which will not enable `company-mode`

What about using `global-company-mode` as @kiennq suggested or `(add-hook 'lsp-mode-hook 'company-mode)`?

**Comment by kode9** [comment]
My idea was that `lsp-completion-mode` did more than just enable company and modifying its backend (all the code that comes after the snipped I posted) and so I just thought "I'll let lsp-mode handle this".

But having capf at the front of the backends is not ideal because it responds to most of the prefix (e.g it will respond to a file path without being able to complete it and won't passe it on to `company-files`).

Anyway I'll try `:none` + enable company separately to see how it goes. And I guess if I enable it **before** `lsp-completion` the code I was referring will be run still.
I guess I can also rewrite the backends after `lsp-completion` finished its setup :)
Just thought it would be nice to have this as an option.

**Comment by kode9** [comment]
> My idea was that `lsp-completion-mode` did more than just enable company and modifying its backend (all the code that comes after the snipped I posted) and so I just thought "I'll let lsp-mode handle this".
> 
> But having capf at the front of the backends is not ideal because it responds to most of the prefix (e.g it will respond to a file path without being able to complete it and won't passe it on to `company-files`).
> 
> Anyway I'll try `:none` + enable company separately to see how it goes. And if I enable it **before** `lsp-completion` the code I was referring to will still be run as well.
> I guess I can also just rewrite the backends after `lsp-completion` finished its setup :)
> Just thought it would be nice to have this as an option.

Just to be clear because I'm not sure my original post was, I do use capf, I just group it, e.g
`'((company-files company-capf :with company-yasnippet))`

**Comment by kiennq** [comment]
@kode9 I'm using `capf` with group too. Just that since I'm also use `company` for not just `lsp-mode` (spell check, `dabbrev-code`, snippet) so I enable `company-mode` before hand and instruct `lsp-mode` to not touch `company` configuration with `lsp-completion-mode` of `:none`

**Comment by yyoncho** [comment]
Marking the issue as resolved since it seems like there won't be anything to address as part of this issue report.
