### ISSUE TITLE
Question about xref-find-definition

### ISSUE THREAD

**Issue by samrayleung** [emacs-lsp/lsp-mode#242]
@MaskRay  has submitted a [post](https://redd.it/7qyl39) in Reddit, and abo-abo has an issue about `xref-find-definition`. I have same issue here, and this is the value of `xref-backend-function`: 
```
xref-backend-functions is a variable defined in ‘xref.el’.
Its value is (elpy--xref-backend t)
Local in buffer test.py; global value is 
(etags--xref-backend)
```
Since I have installed [elpy](https://github.com/jorgenschaefer/elpy) and [anaconda](https://github.com/proofit404/anaconda-mode), `elpy` overwrites  the value of  `xref-backend-function`  set by `lsp-mode`. 
I am curious that is it possible to combine `elpy`, `anaconda` with `lsp-mode`, or I only could use `lsp-mode` separately

**Comment by MaskRay** [comment]
@samrayleung Alternatively, avoid xref-find-definition and use lsp-ui-peek-find-definitions. See https://github.com/jacobdufault/cquery/wiki/Emacs#find-definitionsreferences

**Comment by samrayleung** [comment]
But `lsp-ui-peek-find-definitions` needs additional dependency(e.g. lsp-ui), and `lsp-ui` couldn't work well in terminal and also depends on some features only in emacs26

**Comment by samrayleung** [comment]
and there are some issues about `lsp-ui`
![screenshot_1](https://user-images.githubusercontent.com/14180681/35133548-bded19b2-fd0b-11e7-8b3f-c542dec3f7de.png)

**Comment by MaskRay** [comment]
Sometimes when I make a `lsp-ui-peek-jump-backward`, the peek window will be opened after the jump with no references. I haven't narrowed it down

**Comment by samrayleung** [comment]
https://github.com/emacs-lsp/lsp-ui/issues/59
I have encoutered some issues when I use `lsp-ui-peek-find-definition/reference`. So I turn back to `xref-find-definition` with `lsp-rust`, the value of `xref-backend-functions` is `(etags--xref-backend)` instead of `lsp--xref-backend`.Well, it seems it doesn't work out of box, or I need to set `lsp--xref-backend` explicitly?
