### ISSUE TITLE
Top bar needs context per buffer

### ISSUE THREAD

**Issue by fxfactorial** [emacs-lsp/lsp-mode#2420]
regularly update lsp-mode and found the new top bar (SO AWESOME THANK YOU!!!) 

but here's a bug - say I make two buffers of the same file - each buffer's pointer in a diferent spot - so diferent function context, but currently it will pick one of the two and use for both, so the top bar needs to be context depenednet per buffer i think 
![Screenshot from 2020-12-18 11-19-43](https://user-images.githubusercontent.com/3036816/102636928-1dc72180-410a-11eb-8f47-7672c1d93dbe.png)

**Comment by yyoncho** [comment]
Interesting... @ericdallo, willing to take a look?

As a side note, your font is missing the separator that we use. I guess we should make it configurable, but if you isntall all-the-icons(or use another font) the issue will go away.

**Comment by fxfactorial** [comment]
@yyoncho thanks - I tried all the `all-the-icon-` packages (4 of them) but still didn't get the icon - I'm using pragmatapro , so rather keep the font

**Comment by yyoncho** [comment]
@ericdallo I figured out the issue, I will include it in my PR.

**Comment by ericdallo** [comment]
Hum, we should really make the breacrumb buffer aware, I don't know how hard is though, I can investigate this weekend

**Comment by yyoncho** [comment]
I think the issue is that we use `(point)` which is window specific.

**Comment by fosskers** [comment]
I'm also missing some of the icons.

**Comment by yyoncho** [comment]
@fxfactorial FYI you should install https://github.com/domtronn/all-the-icons.el and then do `M-x all-the-icons-install-fonts`.

**Comment by ericdallo** [comment]
@yyoncho I though we had fallbacks when the user doesn't have the font :thinking:

**Comment by yyoncho** [comment]
@ericdallo the fallback is "›" which apparently is not present in all fonts.

**Comment by yyoncho** [comment]
... or make it configurable. Not sure if there is a way to check if the font has that char.

**Comment by ericdallo** [comment]
I'll take a look at this tomorow

**Comment by yyoncho** [comment]
@ericdallo let me finish my PR first because I am touching this code.

**Comment by yyoncho** [comment]
Can someone with issues run in their emacs `M-: (char-displayable-p ?›)`?

**Comment by fxfactorial** [comment]
> @fxfactorial FYI you should install https://github.com/domtronn/all-the-icons.el and then do `M-x all-the-icons-install-fonts`.

awesome - this worked - looks great

**Comment by yyoncho** [comment]
Unfortunately, the fix does not seem to be easy... we are using the same local variable for the header line... and when we update it updates on both windows... I am out of ideas on how to fix that without introducing performance issues.

**Comment by ericdallo** [comment]
maybe change it to a variable that holds a map with the key being the buffer?
Or using a `defvar-local`?

**Comment by yyoncho** [comment]
It is defvar-local. The issue is that on the left and on the right you have the same buffer, thus it cannot have a different value.

**Comment by ericdallo** [comment]
Got it :man_facepalming: not sure how to handle this

**Comment by fosskers** [comment]
> ?›

This displays the following in my `*Messages*` buffer:
```
#<font-object "-ADBO-Hasklig-normal-normal-normal-*-13-*-*-*-m-0-iso10646-1">
```

**Comment by yyoncho** [comment]
For those with separator issues: you can use lsp-headerline-arrow to specify what to use for separating each of the segments.

About the original issue: @ericdallo we can move the caching on different level. ATM we cache the full string, we could instead cache the symbols, the paths, etc and then let each buffer calculate the full string in the context of their position.

**Comment by fosskers** [comment]
`lsp-headerline-arrow` doesn't appear to be customizable. At least I don't see the "This value can be customized" line when I `C-h v` it.

**Comment by yyoncho** [comment]
ATM it is defvar, you could setq it. We could change it to defcustom.
