### ISSUE TITLE
LSP force watch only src directory in the top level directory

### ISSUE THREAD

**Issue by vikigenius** [emacs-lsp/lsp-mode#2423]
Is there an easy way to watch only my src directory in the project root.
My top level directory has a lot of uninteresting stuff like reports, .venv, data folders with lots of data.

I want the file watchers to watch only the src folder, and not watch anything else. I don't know if simply using a regex will work because some of my projects also have the following structure

```
appname
  - appname # Watch only this directory (ignore everything else)
  - data
  - reports
```

**Comment by yyoncho** [comment]
I think that you can blacklist fullpaths, so blacklisting anything else should be fine.

**Comment by charlie-ht** [comment]
From the documentation (https://emacs-lsp.github.io/lsp-mode/page/file-watchers/) it seems you can only ignore directories, is there an inverse provided to that? To specify only directories you want to watch, not those you wish to ignore?
