### ISSUE TITLE
Add customization lsp-enable-breadcrumbs

### ISSUE THREAD

**Issue by sebasmonia** [emacs-lsp/lsp-mode#2428]
There should be a customization `lsp-enable-breadcrumbs`, just like we have `lsp-enable-snippet` and `lsp-enable-folding`.
Either that or a "global" function for breadcrumbs mode, but since lsp-mode already did those variables above, I would expect one for breadcrumbs too.

**Expected behavior**
Want to disable the header line globally via configuration. Right now I'm looking to add a call to disable on lsp-mode hook. :)

**Comment by yyoncho** [comment]
There is `lsp-headerline-breadcrumb-enable`?

**Comment by sebasmonia** [comment]
The depressing part is that I spent at least 10 minutes _looking in lsp-mode's code_ for a way to disable it :)
I opened customize-group and rest assured, there it was.

Thanks!

**Comment by yyoncho** [comment]
FYI - https://emacs-lsp.github.io/lsp-mode/tutorials/how-to-turn-off/

**Comment by sebasmonia** [comment]
That is awesome. Turns out I do want lenses.
Thanks for pointing me to that page :)
