### ISSUE TITLE
Is there a way to remove icons from the Header Line?

### ISSUE THREAD

**Issue by XO39** [emacs-lsp/lsp-mode#2430]
Now that Header Line is enabled by default, is there away to remove/disable icons/images and keep only text? They are too big and ugly, and `treemacs-resize-icons` has no effect at all, and if can't get them get smaller I'd rather just remove them totally.

I got the Header Line disabled till I can find a solution, any ideas?

**Comment by ericdallo** [comment]
I'm working on a treemacs theme that will disable the icons on headerline: https://github.com/emacs-lsp/lsp-treemacs/pull/83
c/c @yyoncho
