### ISSUE TITLE
lsp-headerline-breadcrumb-mode is extremely slow

### ISSUE THREAD

**Issue by shrubbroom** [emacs-lsp/lsp-mode#2431]
**Describe the bug**
I am using lsp-mode in C++ with ccls. When I turn on lsp-headerline-breadcrumb-mode and perform a continuous scrolling (i.e. hold down in my keyboard). The Emacs gets extremely slow. I have the key repeat speed as high as 60 in xfce4.
**To Reproduce**
Open Emacs, enable lsp-headerline-breadcrumb-mode and hold your down in keyboard

**Expected behavior**
The scrolling in Emacs should be smooth

**Which Language Server did you use**
ccls

**OS**
Arch Linux. I am using the native compiled Emacs, version 28.0.5.

My profile report is as follow

![图片](https://user-images.githubusercontent.com/49093544/102870127-8e0dd400-4477-11eb-9aec-501afa3ddd51.png)

The headline update is too frequent. Make the headline update at idle and provide a customizable variable to set update interval may be of help.

**Comment by yyoncho** [comment]
Is this with the latest lsp-mode? Are you able to reproduce it with lsp-start-plain.el?

**Comment by shrubbroom** [comment]
> Is this with the latest lsp-mode? Are you able to reproduce it with lsp-start-plain.el?

Start with lsp-start-plain.el and everything goes well. I just found that I have
``` lisp
(setq lsp-idle-delay 0)
```
in my configuration. I think that may be the reason for the lagging. Sorry for my ignorance.
