### ISSUE TITLE
Mode specific flycheck checkers

### ISSUE THREAD

**Issue by dschrempf** [emacs-lsp/lsp-mode#2433]
Hello,

I have asked this question on Discord, but didn't get any response.

Is there a way to add mode-specific flycheck checkers after the lsp checker? At the moment, I use a snippet like the following:

```
    (add-hook 'lsp-after-initialize-hook
              (lambda ()
                (when (derived-mode-p 'sh-mode)
                  (flycheck-add-next-checker 'lsp 'sh-shellcheck))))
```

But then, `sh-shellcheck` is executed in all modes administered by `lsp-mode` (at least that is what `flycheck-verify-setup` is showing).

Thank you!

**Comment by dschrempf** [comment]
I have solved the problem, see https://github.com/hlissner/doom-emacs/issues/1530.

**Comment by yyoncho** [comment]
Closing based on the fact that there is a solution listed in flycheck ticket.
