### ISSUE TITLE
getting: jansson library not found

### ISSUE THREAD

**Issue by intrasight** [emacs-lsp/lsp-mode#2443]
On windows with emacs 28.0.50
M-: (functionp 'json-serialize) returns true.
I downloaded  the jansson source and compiled a ddl. Placed that in emacs/bin. But still get error "jansson library not found". I'm out of my league in terms of hacking emacs here.

**Comment by yyoncho** [comment]
I suggest asking this on emacs-devel unless @kiennq has a clue.

**Comment by kiennq** [comment]
@intrasight I think you're using https://alpha.gnu.org/gnu/emacs/pretest/windows/emacs-28/ which doesn't ship lib `jansson` dll together with it.
The issue has been fixed and will available on newer build (with newer date). For now, you can use:
- emacs 27 release, which contains the fix http://ftp.gnu.org/gnu/emacs/windows/emacs-27
- Using [scoop](https://scoop.sh/) with my [bucket](https://github.com/lukesampson/scoop/wiki/Buckets) https://github.com/kiennq/scoop-misc and install `emacs-snapshot`. It will also install required jansson lib for you.
