### ISSUE TITLE
lsp--apply-text-edits will reformat buffer unexpectedly after typing "}"

### ISSUE THREAD

**Issue by JohnC32** [emacs-lsp/lsp-mode#2446]
After a while in working with Emacs on C++ code, we see when typing a "}" that the buffer is reformatted. This is happening on code that hasn't been clang-format'ed so the changes are substantial and making it very hard to use emacs because one must restart emacs which is expensive given how long ccls language server takes to startup. The other way to  get around this is to stop using lsp-mode and no one wants to do that. We are selectively moving code to be compliant with clang-format and can't "just reformat code", so this issue is troublesome for us. I suspect most people are working on code that is clang-formatted, so the occasional reformat of the buffer doesn't really matter that much. However, fixing this will make lsp-mode faster for all because there will be less activity when typing "}". On restarting Emacs, we can't directly reproduce. This issue only happens after a while of working. Maybe a stray key stroke is activating this behavior? I handle the roll out of lsp-mode within our company and have been receiving complaints on this for a while and only recently had it happen to me where I could debug it a little. The frequency isn't very high, but it is painful when it does occur.  When this occurs, we do see messages like

     LSP :: Applying 47 edits to `file.cpp' ...

and this is coming from lsp--apply-text-edits. Adding "(debug)" to the entry of this function followed by eval-defun gives us the attached stack trace after typing a "}" (when this issue starts happening). I also see that in cc-cmds.el, c--call-post-self-insert-hook-more-safely-1 calls (run-hooks 'dest) which runs lsp--apply-text-edits though a byte-compiled function hook attached to 'dest.

Here's the backtrace trimmed a little to make it more readable

     lsp--apply-text-edits((#<hash-table equal 2/65 0x3c423fd> ......)
     apply(lsp--apply-text-edits (#<hash-table equal 2/65 0x3c423fd> ......))
     #f(compiled-function (&rest args) #<bytecode 0x42bd4d5>)((#<hash-table equal 2/65 0x3c423fd> ......)
     #f(compiled-function (result) #<bytecode 0x42bd509>)([#<hash-table equal 2/65 0x3c423fd> ......)
     #f(compiled-function (result) #<bytecode 0x42bd525>)([#<hash-table equal 2/65 0x3c423fd> ......)
     lsp--parser-on-message(#<hash-table equal 3/65 0x3c42359> #s(lsp--workspace .......))
     #f(compiled-function (proc input) #<bytecode 0x1f22c81>)(#<process ccls> ":{\"start\":  ......)
     recursive-edit()
     #f(compiled-function (arg-mode) #<bytecode 0x2b5f38d>)(after)
     transient--edebug--recursive-edit(#f(compiled-function (arg-mode) #<bytecode 0x2b5f38d>) after)
     apply(transient--edebug--recursive-edit #f(compiled-function (arg-mode) #<bytecode 0x2b5f38d>) after)
     edebug--recursive-edit(after)
     edebug--display-1(nil 54 after)
     edebug--display(nil 54 after)
     edebug-debugger(54 after nil)
     edebug-after(53 54 nil)
     (let ((src (edebug-after 0 1 post-self-insert-hook)) dest) .......)
     (edebug-after (edebug-before 0) .....)
     (lambda nil (edebug-after (edebug-before 0) .....)()
     edebug-enter(c--call-post-self-insert-hook-more-safely-1 .......)
     edebug-enter(c--call-post-self-insert-hook-more-safely-1 .......)
     c--call-post-self-insert-hook-more-safely-1()
     (let (safepos literal (old-blink-paren blink-paren-function) ...... (c--call-post-self-insert-hook-more-safely-1))
     c-electric-brace(nil)
     funcall-interactively(c-electric-brace nil)
     call-interactively(c-electric-brace nil nil)
     command-execute(c-electric-brace)

We're using emacs 26.1 on Debian 10 with lsp 4582cac1 from Dec-15-2020

Any tips for debugging would be greatly appreciated. 

Thanks

**Comment by yyoncho** [comment]
Maybe you are looking for `lsp-enable-on-type-formatting` ?

**Comment by JohnC32** [comment]
That's it, along with `lsp-enable-indentation`! Thank you for the quick response. I should have looked at the defcustom's and seen this.

One suggestion - on the https://github.com/emacs-lsp/lsp-mode page, there's a bullet which says "formatting", maybe make that a link to info that contains something like:

Some language servers, e.g. for C++ via clang-format, can format code as you type or when you indent using the tab key. The lsp formatting capabilities are enabled when the customizable variables, `lsp-enable-indentation` and `lsp-enable-on-type-formatting` which are enabled by default.

**Comment by yyoncho** [comment]
Yep, we need some more docs. This one and specifics regarding tab-size.
