### ISSUE TITLE
[3.16] Support CodeActionsResolve request

### ISSUE THREAD

**Issue by ericdallo** [emacs-lsp/lsp-mode#2469]
[SPEC](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#codeAction_resolve)

* Add client capabilities `textDocument.codeAction.resolveSupport`
* :leftwards_arrow_with_hook: `codeAction/resolve`

This will increase performance if the server supports it

**Comment by ericdallo** [comment]
This should improve servers performance like LSP suggest for `codeLens`, @yyoncho do you think it'd be hard to implement that? I could implement that on `clojure-lsp` server side too

**Comment by yyoncho** [comment]
I don't think it will be hard to implement, most likely localized changes in `lsp-execute-code-action`
