### ISSUE TITLE
[3.16] Support Prepare CallHierarchy request

### ISSUE THREAD

**Issue by ericdallo** [emacs-lsp/lsp-mode#2472]
[SPEC](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_prepareCallHierarchy)

* Add client capability `textDocument.callHierarchy`
* :leftwards_arrow_with_hook: support `textDocument/prepareCallHierarchy` request

**Comment by yyoncho** [comment]
call hierarchy is implemented in lsp-treemacs and it works fine with `clangd`/`rust-analyzer`.

**Comment by ericdallo** [comment]
Should we move anything from there to `lsp-mode`?

**Comment by yyoncho** [comment]
> Should we move anything from there to `lsp-mode`?

The issue is there is no convenient tree component to use. tree-widget is very slow and generally limiting compared to treemacs rendering engine.

**Comment by ericdallo** [comment]
Yeah, I mean not the render component, but the client capabilities and core lsp things

**Comment by yyoncho** [comment]
> Yeah, I mean not the render component, but the client capabilities and core lsp things

Client capability should be here(unless there is a change).

**Comment by ericdallo** [comment]
We already have that support on [lsp-treemacs](https://github.com/emacs-lsp/lsp-treemacs/blob/master/lsp-treemacs.el#L1191)
