### ISSUE TITLE
[3.16] Support CallHierarchy incoming calls request

### ISSUE THREAD

**Issue by ericdallo** [emacs-lsp/lsp-mode#2473]
[SPEC](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#callHierarchy_incomingCalls)

* :leftwards_arrow_with_hook: support `callHierarchy/incomingCalls`

**Comment by ericdallo** [comment]
This is already supported by `lsp-treemacs` and it's working with Clojure, should we close this @yyoncho and other call hierarchy 3.16 issues?

**Comment by yyoncho** [comment]
Yep.
