### ISSUE TITLE
complete can not complete strings

### ISSUE THREAD

**Issue by bensonlew** [emacs-lsp/lsp-mode#2485]
`          detail_info += json.loads(tmp_df.to_json(orient="records"))
                mean_dict = tmp_df.iloc[:, 1:-1].mean().to_dict()
                trend_dict[str(sub_cluster_id)] = mean_dict
        #
        target_file = os.path.join(cluster_output_dir, "expression_matrix.xls")
        test = "expre"`

in python mode it can not complete strings inside  ""   is this confict with company?

company-backends is 
(company-bbdb company-semantic company-cmake company-capf company-clang company-
files
              (company-dabbrev-code company-gtags company-etags company-keywords
)
              company-oddmuse company-dabbrev)

**Comment by nbfalcon** [comment]
What would you expect the completion inside strings to be?

**Comment by kiennq** [comment]
Do you want the string inside "" to be completed to already typed strings (via `company-dabbrev-code`?)?
You can try to change `company-capf` to `(company-capf :with company-dabbrev-code)`.

Also, what's your value of `lsp-completion-provider`?

**Comment by bensonlew** [comment]
> Do you want the string inside "" to be completed to already typed strings (via `company-dabbrev-code`?)?
> You can try to change `company-capf` to `(company-capf :with company-dabbrev-code)`.
> 
> Also, what's your value of `lsp-completion-provider`?

lsp-completion-provider :capf
i want it complete  already typed strings like company-dabbrev   and can complete dirs like "/usr/bin/which"  like company-
files did

**Comment by kiennq** [comment]
You should change the `lsp-completion-provider` to  `:none` and change `company-capf` to `(company-capf: with company-dabbrev  company-files)` instead

**Comment by yyoncho** [comment]
Seems like the question was answered. Feel free to use the issue for further questions.
