### ISSUE TITLE
Default TeX server

### ISSUE THREAD

**Issue by astoff** [emacs-lsp/lsp-mode#2487]
At some point, the default LaTeX server was changed from digestif to texlab. I don't know what was the perceived advantage in doing this, but I wanted to point out that this removes support for the TeX formats other than LaTeX.

By the way, the `:major-mode` entry of both servers seems misconfigured. For texlab, if their README is accurate, it should include just latex-mode. For digestif, it should include plain-tex, latex, context and texinfo modes.

**Comment by nbfalcon** [comment]
```emacs-lisp
(setq lsp-text-server 'texlab)
```

I will address the major-modes soon.

**Comment by nbfalcon** [comment]
See #2518. I don't know whether `texlab` supports `plain-tex`, so I haven't removed  and you may keep this open.

**Comment by astoff** [comment]
> See #2518. I don't know whether `texlab` supports `plain-tex`, so I haven't removed that and you may keep this open.

Their website only mentions LaTeX and BibTeX. (Digestif also supports BIbTeX, so that could be added to both.)

Finally, concerning #2518, note that `latex-mode` and `plain-tex-mode` both derive from `tex-mode`, so, assuming you check for that, you could make the list of modes shorter in the digestif config.

**Comment by yyoncho** [comment]
Seems like we are good after #2518, marking as closed.
