### ISSUE TITLE
In emacs 28 "when" parameter are mandatory in function define-obsolete-variable-alias

### ISSUE THREAD

**Issue by vpxyz** [emacs-lsp/lsp-mode#2497]
In emacs 28 (master branch), the "when" parameter are mandatory in functions make-obsolete, define-obsolete-function-alias, make-obsolete-variable and define-obsolete-variable-alias.

**Describe the bug**
In lsp.ocaml.el there are two line (60 and 61) where the "when" parameter are not defined:
(define-obsolete-variable-alias 'lsp-merlin 'lsp-ocaml-lsp-server)
(define-obsolete-variable-alias 'lsp-merlin-command 'lsp-ocaml-lsp-server-command)

this raise a error, that prevent to start the lsp server: (wrong-number-of-arguments (3 . 4) 2) 

**To Reproduce**
you need emacs 28 master branch.

**Expected behavior**

**Which Language Server did you use**
gopls, jdtls

**OS**
Fedora 33

**Error callstack**
```
Debugger entered--Lisp error: (wrong-number-of-arguments (3 . 4) 2)
  #f(compiled-function (obsolete-name current-name when &optional docstring) "Make OBSOLETE-NAME a variable alias for CURRENT-NAME and mark it obsolete.\n\nWHEN should be a string indicating when the variable was first\nmade obsolete, for example a date or a release number.\n\nThis macro evaluates all its parameters, and both OBSOLETE-NAME\nand CURRENT-NAME should be symbols, so a typical usage would look like:\n\n  (define-obsolete-variable-alias 'foo-thing 'bar-thing \"27.1\")\n\nThis macro uses `defvaralias' and `make-obsolete-variable' (which see).\nSee the Info node `(elisp)Variable Aliases' for more details.\n\nIf CURRENT-NAME is a defcustom or a defvar (more generally, any variable\nwhere OBSOLETE-NAME may be set, e.g. in an init file, before the\nalias is defined), then the define-obsolete-variable-alias\nstatement should be evaluated before the defcustom, if user\ncustomizations are to be respected.  The simplest way to achieve\nthis is to place the alias statement before the defcustom (this\nis not necessary for aliases that are autoloaded, or in files\ndumped with Emacs).  This is so that any user customizations are\napplied before the defcustom tries to initialize the\nvariable (this is due to the way `defvaralias' works).\n\nFor the benefit of Customize, if OBSOLETE-NAME has\nany of the following properties, they are copied to\nCURRENT-NAME, if it does not already have them:\n`saved-value', `saved-variable-comment'." #<bytecode -0x16ead6ec4eb23490>)('lsp-merlin 'lsp-ocaml-lsp-server)
  (define-obsolete-variable-alias 'lsp-merlin 'lsp-ocaml-lsp-server)
  eval-buffer(#<buffer  *load*> nil "/home/vincenzo/.emacs.d/elpa/lsp-mode-20210104.0/l..." nil t)  ; Reading at buffer position 2020
  load-with-code-conversion("/home/vincenzo/.emacs.d/elpa/lsp-mode-20210104.0/l..." "/home/vincenzo/.emacs.d/elpa/lsp-mode-20210104.0/l..." t t)
```

**Comment by ericdallo** [comment]
Thanks for the report! I'll fix all cases in lsp-mode ASAP

**Comment by yyoncho** [comment]
@eli-zaretskii is this breaking change expected?

**Comment by Eli-Zaretskii** [comment]
It's announced in NEWS:

                     ** The 'when' argument of `make-obsolete` and related functions is mandatory.
                     The use of those functions without a 'when' argument was marked
                      obsolete back in Emacs-23.1.  The affected functions are:
                      make-obsolete, define-obsolete-function-alias, make-obsolete-variable,
                      define-obsolete-variable-alias.

So yes, this is intended.

**Comment by yyoncho** [comment]
@Eli-Zaretskii thank you!
