### ISSUE TITLE
Completion doesn't start after "." is pressed in go-mode with gopls v0.6.1.

### ISSUE THREAD

**Issue by AllenDang** [emacs-lsp/lsp-mode#2499]
**Describe the bug**
Completion didn't start after pressed "." in go-mode with gopls v0.6.1.

Completion is triggered normally if I press one more character after ".", like `fmt.P`.

I tested with gopls v0.5.5, issue remains, seems it doesn't related with gopls.

I switched to eglot, completion works fine after "." is pressed. Seems go-mode works fine.

**To Reproduce**
Open main.go, type `fmt.`, no completion, type `fmt.P` completion started normally.

**Expected behavior**
Type `fmt.`, completion should pops up.

**Which Language Server did you use**
gopls v0.6.1

**OS**
MacOS big sur

**Error callstack**
No error.

**Comment by yyoncho** [comment]
@kiennq - is this a regression?

**Comment by kiennq** [comment]
@AllenDang can you test with `lsp-plain.el`? I cannot seem to repro this issue with latest gopls

**Comment by AllenDang** [comment]
@kiennq I'm using doom and here is my lsp config.
```lisp
(add-hook 'lsp-mode-hook
          (setq
           lsp-enable-snippet nil
           lsp-enable-links nil
           lsp-log-io nil
           lsp-print-io nil
           lsp-print-performance nil
           lsp-enable-symbol-highlighting nil
           lsp-restart 'auto-restart
           lsp-enable-folding nil
           lsp-pwsh-code-folding-enable nil))
```

**Comment by kiennq** [comment]
> And I'm a vim user, using Doom from the beginning, I don't know any emacs original hot keys, so it's hard for me to use lisp-plain.el to test.

You can modify `lsp-start-plain.el` to include `evil-mode`, that will give you the vanilla Vim key bindings for use.

**Comment by AllenDang** [comment]
@kiennq Sorry, it turns out was a issue of gccemacs. Close now.

**Comment by iris-garcia** [comment]
@AllenDang I have exactly the same issue, can you tell me how did you fix it please? I'm also using gccemacs. Thanks.

**Comment by AllenDang** [comment]
@iris-garcia I rolled back to older working version of gccemacs to solve it.

**Comment by jcs090218** [comment]
Can you give us the information regarding what version of gccemacs works? and what not? Thanks!

**Comment by AllenDang** [comment]
@jcs090218 Most recent commit 42ff68ec2f1149704da59fd692fafb095a44cce2 resolved this issue.

**Comment by oscarfv** [comment]
I'm experiencing the same problem with lsp-dart. My gccemacs contains the commit mentioned above.

**Comment by oscarfv** [comment]
For the record: an emacs compiled from the same checkout but without `-with-nativecomp` worked fine. If I put `(setq load-no-native t)` at the beginning of `emacs.el` (thus disabling native code for external packages) works fine. So I deleted the directory `.emacs.d/eln-cache`, restarted gccemacs and it worked fine.

The problem might be related to a massive package update (via `package-list-packages`, which included lsp-related packages, among others) I did after starting the gccemacs instance that showed the problem.

**Comment by lqu3j** [comment]
@oscarfv  after deleted .emacs.d/eln-cache, also can't complete

**Comment by oscarfv** [comment]
With emacs-lsp and gccemacs from two weeks ago I need to invoke the complete mechanism explicitly (C-M-i).

@lqu3j : how old is your gccemacs build?

**Comment by lqu3j** [comment]
yes, it can complete by type (C-M-i), But can't auto complete. gccemacs commit :b8d3ae78c54db7c7bb65d367a80f9be3d8744c48

**Comment by lqu3j** [comment]
I'm not sure if it's gccemacs' or lsp-mode's problem， Now using the previous version of gccemacs without problems will also have this problem

**Comment by lqu3j** [comment]
yes, it can complete by type (C-M-i), But can't auto complete. gccemacs commit :b8d3ae78c54db7c7bb65d367a80f9be3d8744c48,
I'm not sure if it's gccemacs' or lsp-mode's problem， Now using the previous version of gccemacs without problems will also have this problem
but i use emacs without native-comp has no problem

**Comment by acowley** [comment]
I'm seeing this, too, with Rust and rust-analyzer via `rustic`. emacs commit 431b098a206d27a2dff6a88312c28c36926f90e9 (from 2021-02-05) exhibits the issue where a dot character does not trigger completion unless `company-minimum-prefix-length` is zero. Using `(setq load-no-native t)` resolves it: `company-complete` is triggered as expected by dot.

**Comment by oscarfv** [comment]
I just upgraded lsp-mode and native-comp (Emacs master, actually, as the native-comp branch was merged) and the problem seems gone. Can anyone confirm?
