### ISSUE TITLE
[yaml lsp] There are no servers with automatic installation for yaml

### ISSUE THREAD

**Issue by uqix** [emacs-lsp/lsp-mode#2508]
I am using the latest version of lsp-mode and Emacs Version 27.1 (9.0)

**Describe the bug**
`lsp-install-server` results in 
> There are no servers with automatic installation

**To Reproduce**
1. Open a yaml file
2. M-x `lsp-install-server` RET

**Expected behavior**
automatic installation.

**Which Language Server did you use**
`npm install -g yaml-language-server`

**OS**
MacOS 10.15.7 (19H114)

**Error callstack**
```
helm-M-x-execute-command: There are no servers with automatic installation
```

**Comment by nbfalcon** [comment]
This is probably because you haven't loaded `lsp-yaml`, but this might also be a bug in `lsp-mode`. @yyoncho perhaps `lsp-install-server` should load all `lsp-auto-configure-packages`, similarly to `M-x lsp`?

**Comment by nbfalcon** [comment]
@uqix
```emacs-lisp
(require 'lsp-yaml)
```
`M-x lsp-install-server`

**Comment by yyoncho** [comment]
It is either already installed or you haven't loaded the packages as @nbfalcon mentioned. Generally, use `M-x lsp` in the file and lsp-mode will find the correct server to install.

**Comment by nbfalcon** [comment]
@yyoncho the problem here is that `lsp-install-server` doesn't load the `lsp-auto-configure-packages`, so it can only be used in buffers where `lsp-mode` is already configured. Perhaps we should load the packages there also, since installing is a relatively expensive operation anyway? If you consider this reasonable, I can make a PR.

**Comment by yyoncho** [comment]
@nbfalcon sounds good to me.

**Comment by nbfalcon** [comment]
With latest `lsp-mode`, everything should work and no requires are necessary.
