### ISSUE TITLE
json server not used when using js-mode for json file

### ISSUE THREAD

**Issue by albert200000** [emacs-lsp/lsp-mode#2512]
js-mode can be used for both javascript and json files but lsp-mode uses javascript server regardless of extension.

**Comment by nbfalcon** [comment]
Modes are used to look up servers and extensions only to derive the language id for servers that support multiple languages (e.g. `ccls` and `clangd`). This means that for any javascript-mode files, such language servers will be used. This will require some refactoring.

**Comment by yyoncho** [comment]
Fixed with https://github.com/emacs-lsp/lsp-mode/pull/2579#pullrequestreview-581975639
