### ISSUE TITLE
lsp-rust rust-analyzer failed to detect workspace root

### ISSUE THREAD

**Issue by kaiwk** [emacs-lsp/lsp-mode#2516]
**Describe the bug**
<img width="344" alt="Screen Shot 2021-01-11 at 3 14 37 PM" src="https://user-images.githubusercontent.com/10190397/104154573-37653b80-5420-11eb-90da-03bbe5c2fe65.png">

LSP consider the `$HOME` directory as the workspace root somehow. it do works in Rust workspace(with virtual manifest and multiple crates), but failed in the plain crate.

Does LSP cache the all workspaces root? Maybe I should clear that and try again : )

**Which Language Server did you use**
lsp-rust, rust-analyzer(latest)

**OS**
Mac OS X 10.15.5

**Comment by kaiwk** [comment]
I found the cache in a file called `session.el`,  after delete my home path and reopen the project, it can prompt me to select workspace root.

**Comment by kaiwk** [comment]
Maybe we can provide a command to clear the sessions?

**Comment by nbfalcon** [comment]
`lsp-workspace-folders-remove` allows you to delete a workspace folder. It took me a while to notice it, too.
