### ISSUE TITLE
clangd keeps crashing, help getting debugging information

### ISSUE THREAD

**Issue by floli** [emacs-lsp/lsp-mode#2517]
Hello,

I have the problem that clangd keeps crashing on every file after a couple of seconds. I know it's probably not a lsp-mode error, but I already fail at getting meaningful information about the crash.

Versions are:

* GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10) of 2020-08-17
* LSP :: lsp-mode 20210110.1933, Emacs 27.1, gnu/linux
* Ubuntu clangd version 11.0.1-++20201218093139+43ff75f2c3fe-1~exp1~20201218203800.157

Crash message is `Server clangd:24584 exited with status signal. Do you want to restart it? (y or n) n`

Setting `lsp-log-io` to `t` gives the `lsp-log: clangd:24584` buffer, however, without any obvious error message. The last message is a report about the backgroundIndexProgress.

I am unable to find any other more logging from clangd or to reproduce the problem outside of Emacs/lsp-mode.

How can I proceed further from here?

Thanks!

**Comment by yyoncho** [comment]
What do you have in stderr buffer?

**Comment by floli** [comment]
Ok, I wasn't aware of the stderr buffer. Probably a worthy addition to https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/ It actually shows the crash:
```
I[11:14:16.510] Indexed [...]/EventUtils.cpp (46 symbols, 7062 refs, 245 files)
I[11:14:16.513] --> $/progress
/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamE+0x1f)[0x7f41ca64f7df]
/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1(_ZN4llvm3sys17RunSignalHandlersEv+0x22)[0x7f41ca64db22]
/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1(+0xa99cb5)[0x7f41ca64fcb5]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12980)[0x7f41d1781980]
/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang4Sema19LookupSpecialMemberEPNS_13CXXRecordDeclENS0_16CXXSpecialMemberEbbbbb+0xb9)[0x7f41cfeb12f9]
/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang4Sema16LookupDestructorEPNS_13CXXRecordDeclE+0x20)[0x7f41cfeb2580]
/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11(+0xf31e1b)[0x7f41cfaace1b]
/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11(+0xf324a5)[0x7f41cfaad4a5]
/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11(+0xf315ef)[0x7f41cfaac5ef]
/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang4Sema17emitDeferredDiagsEv+0x1c9)[0x7f41cfaa3d19]
/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang4Sema33ActOnEndOfTranslationUnitFragmentENS0_14TUFragmentKindE+0x20d)[0x7f41cfaa39dd]
/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang4Sema25ActOnEndOfTranslationUnitEv+0x136)[0x7f41cfaa40e6]
/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang6Parser17ParseTopLevelDeclERNS_9OpaquePtrINS_12DeclGroupRefEEEb+0x411)[0x7f41cf523b51]
/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang8ParseASTERNS_4SemaEbb+0x1fd)[0x7f41cf4862ad]
/usr/lib/x86_64-linux-gnu/libclang-cpp.so.11(_ZN5clang14FrontendAction7ExecuteEv+0x48)[0x7f41d0a8d6a8]
/usr/bin/clangd[0x640c5a]
/usr/bin/clangd[0x644028]
/usr/bin/clangd[0x647f42]
/usr/bin/clangd[0x642990]
/usr/bin/clangd[0x6beb91]
/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1(+0xa9b154)[0x7f41ca651154]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7f41d17766db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f41c8fa771f]

Process clangd stderr finished
```
Do you have any idea about that crash? Or a suggestion to get more information before taking it to the llvm guys?

Best Thanks!

**Comment by yyoncho** [comment]
> Ok, I wasn't aware of the stderr buffer. Probably a worthy addition to https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/

Yes, we should add it to `Server clangd:24584 exited with status signal. Do you want to restart it? (y or n)` message as well.

> Do you have any idea about that crash? Or a suggestion to get more information before taking it to the llvm guys?

No, I am not following clangd development. @sebastiansturm might have a clue.

**Comment by sebastiansturm** [comment]
no, I don't know that crash, sorry
