### ISSUE TITLE
lsp-headerline-breadcrump-mode gets spellchecking

### ISSUE THREAD

**Issue by TheJJ** [emacs-lsp/lsp-mode#2520]
I have `lsp-mode` `20210111.1652` in Spacemacs.

My breadcrump header line gets spell correction underlines:
![image](https://user-images.githubusercontent.com/673543/104481449-18a0a980-55c6-11eb-9db1-4699f248f4d5.png)

It should not be spellchecked. I'm not sure what causes this :)

**To Reproduce**
Any file I open where a breadcrump header line is generated.

**Which Language Server did you use**
`ccls`

**Comment by yyoncho** [comment]
This is not spell checking but it shows that there is an error/warning in that resource/path.

**Comment by ericdallo** [comment]
@anonimitoraf `(setq lsp-headerline-breadcrumb-enable-diagnostics nil)`

**Comment by anonimitoraf** [comment]
Sweet, thanks :)

**Comment by thisch** [comment]
When I first saw the underlines with style `wave` in the header-line, I also thought that they are caused by my spell-checker, even though they were colored in green. Since they didn't disappear when disabling the spell-checker, I had a look at the faces in lsp-headerline.el. There I found:

```elisp
(defface lsp-headerline-breadcrumb-path-info-face
  '((t :underline (:style wave :color "Green")
       :inherit lsp-headerline-breadcrumb-path-face))
  "Face used for breadcrumb paths on headerline when there is an info under that path"
  :group 'lsp-faces)

(defface lsp-headerline-breadcrumb-path-hint-face
  '((t :underline (:style wave :color "Green")
       :inherit lsp-headerline-breadcrumb-path-face))
  "Face used for breadcrumb paths on headerline when there is an hint under that path"
  :group 'lsp-faces)
```

The docstring mentions "info/hint under that path". How is it possible to see this info/hint?

**Comment by yyoncho** [comment]
@thisch the presence of info/hint diagnostics depends on the server. For example, java language server reports the TODOs as info.

**Comment by thisch** [comment]
I see. Now it makes sense. I thought that I can somehow see the info/hints by clicking on the path in the lsp-headerline or by moving the mouse over the path.
