### ISSUE TITLE
lsp-format-buffer doesn't preserve cursor position

### ISSUE THREAD

**Issue by casouri** [emacs-lsp/lsp-mode#253]
I'm using ```lsp-mode``` and ```lsp-python```. If ```lsp-format-buffer``` modifies anything the cursor jumps to the beginning of the buffer. 
I don't know whether the problem is due to ```python-language-server``` or ```lsp-mode```. But probably ```lsp-mode```
If  ```lsp-mode``` can be confirmed as the cause, is it expected to happened and requires customization or there can be a fix?

**Comment by bkchr** [comment]
I have the same problem with `lsp-rust`.

**Comment by sebastiencs** [comment]
#258 should fix that

**Comment by casouri** [comment]
Great! Thanks.
