### ISSUE TITLE
Solargraph being called with the wrong command?

### ISSUE THREAD

**Issue by alecStewart1** [emacs-lsp/lsp-mode#2535]
I've found this strange error with using solargraph with lsp-mode.

For whatever reason, upon opening a ruby file for Gemfile lsp-mode will try to start solargraph with the `server` command which no longer exists for solargraph.

Yet the [client configuration](https://github.com/emacs-lsp/lsp-mode/blob/8ed2fa58c54fc28bb0e9257a4d93a90f73c3f97d/clients/lsp-solargraph.el#L129) doesn't use the `server` command.

What's in the `*ruby-ls::stderr*` buffer:

```
Process ruby-ls stderr finished
Could not find command "server".
Deprecation warning: Thor exit with status 0 on errors. To keep this behavior, you must define `exit_on_failure?` in `Solargraph::Shell`
You can silence deprecations warning by setting the environment variable THOR_SILENCE_DEPRECATION.
```

Which is the exact output if you run `solargraph server` or `bundle exec solargraph server` on the command line.

I'm on the 7.1 release, and there's nowhere in my configuration that sets that command.

Running Emacs with debug mode on doesn't give me anything useful.

The `*lsp-log*` buffer says

```
Command "bundle exec solargraph server" is present on the path.
Command "srb typecheck --lsp --disable-watchman" is not present on the path.
Command "bundle exec steep langserver --log-level=warn" is present on the path.
Command "bundle exec solargraph server" is present on the path.
Command "srb typecheck --lsp --disable-watchman" is not present on the path.
Command "bundle exec steep langserver --log-level=warn" is present on the path.
Found the following clients for /home/my_user/Projects/Ruby/project/Gemfile: (server-id ruby-ls, priority -1), (server-id steep-ls, priority -3)
The following clients were selected based on priority: (server-id ruby-ls, priority -1)
```

So I'm not really sure at what point lsp-mode is calling `solargraph` with the `server` command.

**Comment by yyoncho** [comment]
I don't see any "server" in latest lsp-mode. Can you make sure you are using the latest version?

**Comment by yyoncho** [comment]
Marking bug as closed. Please reopen if you still see the issue with the latest version of lsp-mode.
