### ISSUE TITLE
lsp list/highlight available codeactions for the whole buffer ?

### ISSUE THREAD

**Issue by vikigenius** [emacs-lsp/lsp-mode#2536]
Right now, the codeaction lightbulb is displayed on the modeline if i am on the line where a codeaction is available.

Is there a way to list the available codeactions for the whole buffer ? Say something like highlighting them just like warnings?

**Comment by yyoncho** [comment]
The protocol does not have such functionality. You might be interested in the lsp-treemacs-errors-list which has `Fix` functionality. Using it you may fix any fixable error in the project.
