### ISSUE TITLE
typing comment freezes emacs in lsp-python

### ISSUE THREAD

**Issue by casouri** [emacs-lsp/lsp-mode#254]
I noticed that with ```lsp-python``` and ```lsp-mode``` enabled, if I type a ```#``` - which makes the current line a comment - typing in that line almost always freezes emacs. It comes back if I keep hitting ```C-g```. But typing another one or two character freezes emacs again.
In the other hand. If I type elsewhere or type out what I want and insert ```#``` in the beginning of the line works without any issue.

Could anyone duplicate this?

**Comment by sebastiencs** [comment]
I can't reproduce, can you set those variables:
```el
(setq debug-on-quit t
      debug-ignored-errors nil)
```
And reproduce ?

**Comment by casouri** [comment]
I can reproduce.
Why is ```internal-timer-start-idle``` called?😳
<img width="1440" alt="screen shot 2018-01-24 at 9 19 19 am" src="https://user-images.githubusercontent.com/13118647/35336915-d1cc454a-00e7-11e8-935c-6c62fb06890e.png">

**Comment by casouri** [comment]
For some reason the behavior disappeared this afternoon. I'll close this issue for now. If it comes back I can ope it again.
