### ISSUE TITLE
ts-server loaded for ejs buffers instead of HTML server

### ISSUE THREAD

**Issue by ema2159** [emacs-lsp/lsp-mode#2544]
**Describe the bug**
When opening an .ejs file buffer, ts-ls is initialized instead of html-ls which causes a lot of undesired linting errors. This only happened when I updated LSP recently. 

**To Reproduce**
Create and open an .ejs template file.

**Expected behavior**
Load a proper language server (like html-ls) or don't load any. 

**Which Language Server did you use**
ts-ls, html-ls

**OS**
Linux Mint Ulyana

**Error callstack**
None

**Comment by yyoncho** [comment]
What is the major mode on your side for this extension?

**Comment by ema2159** [comment]
@yyoncho web-mode.
