### ISSUE TITLE
LSP Config for emacs c/c++ show no Capabilities !!

### ISSUE THREAD

**Issue by parminderPSR** [emacs-lsp/lsp-mode#2549]
Please ask your questions at https://discord.gg/swuxy5AAgT

HI Guys,

I have configured emacs-lsp with ccls setup, however It does not auto complete structures and filed suggestions.
In lsp-describe-session it does not show any capabilities, it parse correctly from *.json but there are no capabilities list in LSP.

I am using below code:

(use-package lsp-mode
  :commands (lsp lsp-deferred)
  :bind (:map lsp-mode-map ("C-c C-f" . lsp-format-buffer))
  :custom
  (lsp-auto-guess-root nil)
  (lsp-prefer-flymake nil) ; Use flycheck instead of flymake
  (lsp-file-watch-threshold 2000)
  (read-process-output-max (* 1024 1024))
  (lsp-eldoc-hook nil)
  (lsp-session-file (expand-file-name (format "%s.lsp-session-v1" psr--cacheDir)))
  :init
  (setq lsp-enable-text-document-color t)
  (setq lsp-diagnostics-provider :flycheck)
  (setq lsp-headerline-breadcrumb-enable t)
  (setq lsp-keymap-prefix "C-c l")  ;; Or 'C-l', 's-l'
  :config
  (require 'lsp-protocol)
  (lsp-enable-which-key-integration t))
  
  (use-package lsp-ui
  :custom-face
  (lsp-ui-doc-background ((t (:background nil))))
  (lsp-ui-doc-header ((t (:inherit (font-lock-string-face italic)))))
  :bind
  (:map lsp-ui-mode-map
        ([remap xref-find-definitions] . lsp-ui-peek-find-definitions)
        ([remap xref-find-references] . lsp-ui-peek-find-references)
        ("C-c u" . lsp-ui-imenu)
        ("M-i" . lsp-ui-doc-focus-frame))
  (:map lsp-mode-map
        ("M-n" . forward-paragraph)
        ("M-p" . backward-paragraph))
:hook (lsp-mode . lsp-ui-mode)
)

(use-package ccls
:hook ((c-mode c++-mode objc-mode cuda-mode) . (lambda () (require 'ccls) (lsp)))
:config
(setq ccls-executable "~/.local/bin/ccls")
(setq ccls-initialization-options '(:index (:comments 2)))
)

- same kind of issue exist even with clangd server.

So now i am using rtags but it is also not provide auto completion.

However NVIM using coc-lsp with ccls is working as expected.

Is there any special settings need to be done to set up correctly emacs-lsp with ccls or clangd ?

Is there also an option with lsp to go back and forward during code jumping like in rtgas?
(rtags-location-stack-back)
(rtags-location-stack-forward)

![ccls](https://user-images.githubusercontent.com/60046283/105191338-3bd3d780-5b37-11eb-817c-d34f908ae9b9.PNG)

**Comment by yyoncho** [comment]
You should place the cursor on the red diamond and press RET.

**Comment by parminderPSR** [comment]
> 
> 
> You should place the cursor on the red diamond and press RET.
Thanks :)
Any idea about auto-completion, it is not working however for NVIM coc-lsp it works ?

**Comment by yyoncho** [comment]
Do you have company-mode installed? What happens if you do M-x company-complete?

**Comment by parminderPSR** [comment]
Yes, I have installed it, with company-complete it shows all possible option from buffer not from the respective data structure.

**Comment by yyoncho** [comment]
First do M-lsp. Then do M-x company-complete. If you don't see the completions from the language server do M-x comapany-diag and post the output. Also, try M-x company-capf.

**Comment by parminderPSR** [comment]
here is the outcome:

Emacs 28.0.50 (x86_64-pc-linux-gnu) of 2020-12-28 on r10405
Company 0.9.13

company-backends: (company-bbdb company-semantic company-cmake company-capf company-clang company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)

Used backend: company-clang
Major mode: c++-mode
Prefix: stop
Completions: none

**Comment by yyoncho** [comment]
> Used backend: company-clang

Are you using the latest melpa version of *all* packages? This issue should have been fixed months ago.

**Comment by parminderPSR** [comment]
Just deleted and re-installed all, now it looks like this 
Emacs 28.0.50 (x86_64-pc-linux-gnu) of 2020-12-28 on r10405
Company 0.9.13

company-backends: (company-bbdb company-semantic company-cmake company-capf company-clang company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)

Used backend: company-capf
Value of c-a-p-f: (lsp-completion-at-point)
Major mode: c++-mode

**Comment by yyoncho** [comment]
That should work. If it doesn't work it is most likely caused by wrong project root selecton, missing compile_commands, etc.

**Comment by parminderPSR** [comment]
Ok,  i will check again and also remove rtags completely.
Thanks for info  )
