### ISSUE TITLE
`lsp-lens-mode` writes the text twice

### ISSUE THREAD

**Issue by meditans** [emacs-lsp/lsp-mode#2557]
**Describe the bug**
When I enable `lsp-lens-mode` in `doom-emacs` with a minimal configuration, the text is displayed twice. Look for the string `Evaluate` in [this example](https://imgur.com/u7zgtbT)

**Expected behavior**
The text is displayed only once. Mostly, I'd like to understand which part of the code is creating that, since the interaction of the various components of lsp-mode is unclear to me. [This is the configuration used](https://github.com/hlissner/doom-emacs/blob/develop/modules/tools/lsp/%2Blsp.el)

**Which Language Server did you use**
lsp-haskell

**OS**
linux (NixOS)

**Comment by ericdallo** [comment]
The server provides the lens, in this case the server for lsp-haskell, and lsp-mode just display at the given position, not sure if `lsp-haskell` is using default lsp-mode code-lens or is creating in its own way c/c @kurnevsky

**Comment by michaelpj** [comment]
Yeah, this seems more likely to be a `haskell-language-server` issue. Are you sure the second instance isn't a code action? Otherwise, perhaps the server is sending two lenses for some reason?

**Comment by yyoncho** [comment]
closing the issue based on the @michaelpj comment. @meditans feel free to use it for further questions.

**Comment by meditans** [comment]
The fact is, I don't think it's a `haskell-language-server` issue because the same code doesn't have that problem in `vscode`, where everything works smoothly with the default configuration. But maybe I'm missing something @michaelpj @yyoncho ?

**Comment by yyoncho** [comment]
@meditans on the original screenshot what is the duplicated thing? Evaluate? If yes, can you confirm that turning off lens mode will hide both Evaluate?

**Comment by michaelpj** [comment]
> Are you sure the second instance isn't a code action? 

Toggling of `lsp-lens-mode` should answer that question.

Otherwise, have a look at the `haskell-language-server` debug log and see if it's sending anything strange.
