### ISSUE TITLE
per-project clangd path/arguments

### ISSUE THREAD

**Issue by ejelly** [emacs-lsp/lsp-mode#2562]
I have different projects that use clangd residing at different paths, and with different arguments. (In fact, because of cross-compiling, sometimes I'd like to use different instances of those settings in the *same* project.)

It seems like the only way to tell lsp where to find clangd, and with what additional arguments to call it, is global variables. Is that correct? Would it be possible to pass the configuration to an lsp-initializing function instead, so that I can call that function properly from my own elisp code that gathers things correctly based on needed configuration?

**Comment by julien-oster** [comment]
It's worth noting that eglot supports this, e.g. by launching it like this:

`(eglot major-mode (project-current) eglot-lsp-server '("/tmp/cc1/clangd" (concat "--compile-commands-dir=" build-dir)))`

**Comment by yyoncho** [comment]
2 options:

1. Use .dir-locals (refer to FAQ for example).
2. Use this to alter lsp-clangd client definition:
```
(with-eval-after-load 'lsp-clangd
  (setf (lsp--client-new-connection (ht-get lsp-clients 'clangd))
        (lsp-stdio-connection "<your function that returns list of strings>"
                              "<your function that returns t/nil depending on whether the server is present>")))
```

I am marking the issue as closed but you can use it for further questions.
