### ISSUE TITLE
How to disable fuzzy completions?

### ISSUE THREAD

**Issue by akoppela** [emacs-lsp/lsp-mode#2563]
Hi. I do have quite large project and fuzzy completions quite slow for me. Is there a way to disable fuzzy completions?

**Comment by yyoncho** [comment]
ATM there is no way to do that. Can you post a performance report? Which language server do you use? The client-side fuzzy matching lsp-mode does is very fast so I doubt that the perf issue is in it.

**Comment by akoppela** [comment]
Thanks for you answer. I'm using Elm Language Server. Don't have time to debug it at the moment. Will switch to different completion option.

**Comment by kiennq** [comment]
@akoppela You can try to disable fuzzy matching by
``` elisp
(advice-add #'lsp-completion--regex-fuz :override #'identity)
```
That will be same as sub-string matching. I doubt the bottom neck here is fuzzy completion though

**Comment by akoppela** [comment]
I've tried that. The bottleneck is indeed not in fuzzy completion. It's probably related to the language server.

**Comment by akoppela** [comment]
I've switched to `company-dabbrev` which works really well.
