### ISSUE TITLE
Feature suggestion: derived mode support

### ISSUE THREAD

**Issue by alanz** [emacs-lsp/lsp-mode#2566]
I am experimenting with a new language server for a variant of a language, and using an emacs derived mode for the new major mode.

As [explained here](https://stackoverflow.com/a/19295380), parent mode hooks are always called, and the new mode hook is called last. This means I end up with two language servers for the language. And I do not want to just disable the original, I am using it elsewhere.

The solution I came up with is to have

```elisp
(defun lsp-derived-from-erlang-mode ()
"Call the lsp mode hook unless we are derived from erlang-mode."
    (unless (derived-mode-p 'erlang-mode)
      (lsp)))

(add-hook 'elp-mode-hook #'lsp)
(add-hook 'erlang-mode-hook #'lsp-derived-from-erlang-mode)
```

where `elp-mode` is derived from `erlang-mode`.

Should something like this be generalised? Perhaps the original `#'lsp` hook function could check in the client config if it should be ignored because it is a specific derived parent.

**Comment by yyoncho** [comment]
I think that we can fix that in `lsp--matching-clients?` but I am not sure if there are users depending on this behavior.

**Comment by alanz** [comment]
> but I am not sure if there are users depending on this behavior

I think it should be a behaviour you can set  as an option to `make-lsp-client`, so it can easily be managed.  If that is feasible.

**Comment by yyoncho** [comment]
> I think it should be a behaviour you can set as an option to `make-lsp-client`, so it can easily be managed. If that is feasible.

I don't think we need another option in `make-lsp-client` about matching a file because we have `:activation-fn` which can cover any custom matching logic.

**Comment by alanz** [comment]
> we have :activation-fn which can cover any custom matching logic.

The problem is that first the parent mode `lsp` hook runs, which starts the language server.
Some time later, separately, the derived mode `lsp` hook runs.

So to use `:activation-fn` the parent mode needs to have something set. This is problematic, because ideally deriving a mode should be transparent to the existing mode.

But this is just a discussion, I have a work-around for my current setup, there is no crying need for anything to happen.

**Comment by yyoncho** [comment]
Hm - about the original issue - I am a bit confused. I tested with 
```
(add-hook 'javascript-mode  (lambda ()
                              (message "Major Mode = %s" major-mode)))
```
and then opened json file and it printed that the current major-mode is json-mode not javascript. Thus, the fact that multiple hooks run just results in initializing the same server(the right one) 2 times. Do I miss something?

**Comment by alanz** [comment]
The bit that's missing from the original statement is that the new mode is defined something like

```elisp
(define-derived-mode elp-mode erlang-mode "elp-mode"
"Mode derived from erlang mode."
)
```
If you then define a new lsp client for `elp-mode`, and set hooks (and associate the `*.elp` extension with the new mode)

```elisp
(add-hook 'erlang-mode-hook #'lsp)
(add-hook 'elp-mode-hook #'lsp)
```
Then opening an erlang file works as expected, opening a `.elp` file will start both language servers, but the hooks run one after the other, so they cant coordinate among the options available.

**Comment by yyoncho** [comment]
What I am saying is that when `lsp` is running in `elp` buffer under the `erlang` hook the major mode is `elp-mode` so it will fire up the elp-mode associated server.

**Comment by alanz** [comment]
The [post I linked to initially](https://stackoverflow.com/questions/19280851/how-to-keep-dir-local-variables-when-switching-major-modes/19295380#19295380) has a section about how the hooks get called.  TLDR; first the ancestor mode hooks are called, and then finally the derived mode hook.

> So if we consider a mode named child-mode which is derived from parent-mode which is derived from grandparent-mode, the whole chain of events when we call (child-mode) looks something like this:

```elisp
(delay-mode-hooks
  (delay-mode-hooks
    (delay-mode-hooks
      (kill-all-local-variables) ;; runs change-major-mode-hook
      ,@grandparent-body)
    (run-mode-hooks 'grandparent-mode-hook)
    ,@parent-body)
  (run-mode-hooks 'parent-mode-hook)
  ,@child-body)
(run-mode-hooks 'child-mode-hook)
```

And this is what I observe in the lsp log buffer, they get called one after the other, starting with the parent mode.

**Comment by yyoncho** [comment]
> And this is what I observe in the lsp log buffer, they get called one after the other, starting with the parent mode.

Calling both is fine as long as the major-mode is the right one because we pick the language server based on major mode, not on the hook being called.

What major mode do you see when you do this:
```
(add-hook 'erlang-mode-hook  (lambda ()
                              (message "Major Mode = %s" major-mode)))
```
and you open a file in elp-mode?

**Comment by yyoncho** [comment]
I think that with the new `lsp-activate-on` pattern we cover that issue. Marking the issue as closed but feel free to reopen in order to continue the discussion.
