### ISSUE TITLE
C++ shows wrong candidates?

### ISSUE THREAD

**Issue by algogavin** [emacs-lsp/lsp-mode#2580]
Please ask your questions at https://discord.gg/swuxy5AAgT

There are two questions here:
1. Apparently there are 2 constructor functions defined, I would expect it should be "1/2", not sure why it's saying "1/4" ?
2. By default it only show the first candidate function, how do I navigate to other candidate functions?
![image](https://user-images.githubusercontent.com/44672953/106660711-57df6c00-656e-11eb-9f49-92bb32213f44.png)

**Comment by yyoncho** [comment]
Use M-n/M-p. We display the number of overloads based on the number provided by the server. If you think that the number is wrong should refer to server docs/issues.
