### ISSUE TITLE
Drop a line to Typescript developers

### ISSUE THREAD

**Issue by rassie** [emacs-lsp/lsp-mode#2582]
In an [effort](https://github.com/microsoft/TypeScript/issues/39459) to make the original `tsserver` (which is part of the Typescript distribution) a fully-fledged LSP server, @DanielRosenwasser (Product Manager for TypeScript at Microsoft) [asked](https://github.com/microsoft/TypeScript/issues/39459#issuecomment-772128021) client implementers to reach out to him. Would be nice if someone from the `lsp-mode` team could do just this. Thank you.

**Comment by yyoncho** [comment]
Thank you. Dropped a line.
