### ISSUE TITLE
[spacemacs.develop] lsp-go: when creating new project, error message: "could not import fmt (cannot find package "fmt" in any of...)"

### ISSUE THREAD

**Issue by dennismayr** [emacs-lsp/lsp-mode#2590]
**Describe the bug**
When creating a new simple _Go_ project, `lsp-go` cannot find packages declared as `import`.
Error message on sideline-ui: `"could not import fmt (cannot find package "fmt" in any of...)"`

**To Reproduce**
Via `treemacs` -> create directory, name directory -> create file -> `main.go`
Open `main.go`
In `main.go`, add the following sample code:
```go
package main

import "fmt"

func main() {
	fmt.Println("Testing lsp-go features.")
}
```
Next to `import "fmt"`, check the sideline-ui message:
`"could not import fmt (cannot find package "fmt" in any of...)"`

Running `M-x revert-buffer` doesn't do anything.

**Expected behavior**
`lsp-go` imports the declared packages and does not warn about not finding them.

**Which Language Server did you use**
`gopls` v0.6.5 + `lsp-go` [`lsp-mode` 20210206.1601]

**OS**
Kubuntu 20.04

**Emacs version**
Emacs 27.1 + Spacemacs [develop - commit #234144853110990d8e4e33aba805609ad89961fd] 

**Relevant Spacemacs layers**
`(go :variables
         go-backend 'lsp
         )
     `
`lsp`

**Error callstack**
In the `lsp-log` buffer, I saw the following warning:
```elisp
2021/02/06 20:41:30 no signature help: cannot get type for Fun *ast.SelectorExpr (&{fmt Println})
	position={4 13}

Cancelling textDocument/codeAction(1122) in hook after-change-functions
Cancelling textDocument/codeAction(1124) in hook after-change-functions
Cancelling textDocument/codeAction(1125) in hook after-change-functions
```

**Workaround**
Running `M-x lsp-restart-workspace` makes the problem disappear, no imports are marked as _not found_.

**Comment by yyoncho** [comment]
I am unable to reproduce. Please check if you have selected the proper project roots and test if it reproduces with `lsp-start-plain.el`.

Also, crosscheck with lsp-treemacs-errors-list to see if this error is present. 

CC @muirdm

**Comment by dennismayr** [comment]
I'm so sorry @yyoncho , I completely forgot to mention that I'm using `spacemacs` [develop branch] along with Emacs.
I've updated the report details.

About project roots, I added the project root with `M-x- lsp-workspace-folders-add`, which I normally do with other projects in different languages such as Rust.

**Comment by muirdm** [comment]
This is almost certainly a project/root issue as @yyoncho suggested. Are you using Go modules or GOPATH? Can you include the full trace between Emacs and gopls (`M-x lsp-toggle-trace-io`, reproduce issue, then `M-x lsp-workspace-show-log`)?

**Comment by dennismayr** [comment]
> This is almost certainly a project/root issue as @yyoncho suggested. Are you using Go modules or GOPATH? Can you include the full trace between Emacs and gopls (`M-x lsp-toggle-trace-io`, reproduce issue, then `M-x lsp-workspace-show-log`)?

Will do tomorrow!

**Comment by dennismayr** [comment]
Ok, I see that the way to install Go has changed and there are 2 ways, with or without GOPATH, both of which aren't properly recognized by Emacs + Spacemacs Go layer for whatever reason (everything's reachable on PATH from a terminal), so I guess I'll take this to the Spacemacs folks first.

Thanks for the heads-up
