### ISSUE TITLE
lsp-php currently is using fixed composer home directory, it can be non-fixed

### ISSUE THREAD

**Issue by chung1905** [emacs-lsp/lsp-mode#2597]
Hello,

[phpactor default path](https://github.com/emacs-lsp/lsp-mode/blob/300603b/clients/lsp-php.el#L363): `~/.composer/vendor/phpactor/phpactor/bin/phpactor`
[php-lsp default path](https://github.com/emacs-lsp/lsp-mode/blob/300603b/clients/lsp-php.el#L37): `~/.composer/vendor/felixfbecker/language-server/bin/php-language-server.php`

Both are assume composer home is: `~/.composer/`, which is correct with [composer's document](https://getcomposer.org/doc/03-cli.md#composer-home).
But in my case, my distro's using default home at: `~/.config/composer/`
And if user using different composer home, they have to add a config for this.

I'm using
```
(setq lsp-phpactor-path
      (concat
       (replace-regexp-in-string "\n$" "" (shell-command-to-string "composer config --global home"))
       "/vendor/bin/phpactor"))
```

I would like to submit this change to this repo. What do you think?
I'm more than happy to create a PR for this.

Thanks

**Comment by yyoncho** [comment]
Sounds good, but note, that this code will be executed for environments that don't have composer installed.

**Comment by yyoncho** [comment]
Are you still willing to provide a PR?

**Comment by chung1905** [comment]
Sorry for late responding, I was busy for the last few weeks. I will update by the end of this week.

**Comment by chung1905** [comment]
Here is my PR: https://github.com/emacs-lsp/lsp-mode/pull/2737
Please help me review this.

Thing I want to improve but I don't know how: 
- I'm checking if composer is installed by `(eq (shell-command "composer -V") 0)`
- I think it's bad, because it creates new buffer: `*Shell Command Output*`

Thanks for your help.

**Comment by yyoncho** [comment]
> * I'm checking if composer is installed by `(eq (shell-command "composer -V") 0)`

you may use `executable-find`

**Comment by chung1905** [comment]
I updated code.

Thanks
