### ISSUE TITLE
What to do about hooks for triggering lsp-mode?

### ISSUE THREAD

**Issue by michaelpj** [emacs-lsp/lsp-mode#2598]
The installation documentation asks users to manually set hooks so that their preferred major modes (https://emacs-lsp.github.io/lsp-mode/page/installation/#vanilla-emacs). However, `lsp-mode` already has `major-modes` for all the registered clients! It uses this (I think) to decide whether to load a particular client for a buffer... but only if `lsp-mode` is already running. So we need the original hook to get that process started.

But it seems to me that `lsp-mode` could just add that hook, i.e. in `lsp-register-client` we could do `(add-hook mode #'lsp)` for every `major-mode` listed by the client.

This would be nice: at the moment this is the *only* bit of custom setup that requires users to look at a language client specific README, all the other parts are generic. (I'm being a bit generous and saying that client configuration is generic: but it a sense it is, in that all the clients are configured with configuration options nested under the `lsp` group. So a user could find them all without ever looking at client-specific documentation.)

**Comment by yyoncho** [comment]
> But it seems to me that `lsp-mode` could just add that hook, i.e. in `lsp-register-client` we could do `(add-hook mode #'lsp)` for every `major-mode` listed by the client.

Some clients are not activated by major mode but by extension(for example). FWIW there is `prog-mode` which is base for almost all programming mode related modes, so using it should be generic enough.

**Comment by michaelpj** [comment]
Sure, but *if* we've given major modes in the client registration, we might as well use them, no?

Some clients might need to set additional hooks, sure, but at least the common cases would be handled.

**Comment by yyoncho** [comment]
> Sure, but _if_ we've given major modes in the client registration, we might as well use them, no?

The major mode does not determine the server e. g. web-mode might be for html, xml, css, etc. Also, some users do not use lsp-mode for everything although it is supported by lsp-mode and we will irritate them by forcing lsp-mode. IMHO start lsp-mode in everything that we have will be considered too intrusive by the server and in the end it saves one line in the users config(`(add-hook 'prog-mode-hook 'lsp)`)

**Comment by michaelpj** [comment]
Right, I forgot that `lsp-mode` requires all the clients so you would effectively get them all enabled.

Hmph. I guess I don't know how to make this better short of re-arranging all the clients so that `(require lsp-haskell)` could also plausibly set up the hooks (since the user has asked for it).

**Comment by nbfalcon** [comment]
@michaelpj 
```emacs-lisp
(add-hook 'prog-mode-hook #'lsp)
```
Will give you the DWIM-behaviour: if a client is available, it will be started automatically, granted with annoying messages otherwise. You can use this instead if that bothers you:
```emacs-lisp
(defun my/lsp-quiet () (cl-letf (((symbol-function #'lsp--warn) #'ignore)) (lsp)))
(add-hook 'prog-mode-hook #'my/lsp-quiet)
```
