### ISSUE TITLE
Aggressive-indent-mode deletes text in some circumstances with lsp-mode and clojure-lsp

### ISSUE THREAD

**Issue by admiralbumblebee** [emacs-lsp/lsp-mode#2600]
**Describe the bug**
Utilizing clojure-lsp.

With lsp-mode active, and aggressive-indent-mode, the buffer is changed when encountering code that returns any sort of error with lsp.

**To Reproduce**
```
(use-package lsp-mode
  :ensure t
  :hook ((clojure-mode . lsp)
         (clojurec-mode . lsp)
         (clojurescript-mode . lsp))
  :config
  (dolist (m '(clojure-mode
               clojurec-mode
               clojurescript-mode
               clojurex-mode))
    (add-to-list 'lsp-language-id-configuration `(,m . "clojure")))
  (setq lsp-clojure-server-command '("bash" "-c" "clojure-lsp")))

(use-package aggressive-indent)
```

As of time of this report, I'm using `aggressive-indent-20200824.2352` and `lsp-mode-20210209.2017`.

Open a clj file, enable aggressive-indent-mode, enable electric-pair-mode. Type `(map )`, key sequence of `(map `.

`Insufficient input. [type-mismatch]` is shown in minibuffer area. The space in `(map )` is deleted. 

This happens while typing any code that is not "correct" by time it is checked, and depending on flycheck cycle and your character input speed, a variety of text changes may occur.

**Expected behavior**

Errors/info appears, but text in buffer is not changed.

**Which Language Server did you use**
clojure-lsp

**OS**
macOS 11.1

**Error callstack**

No error.

**Comment by yyoncho** [comment]
The issue comes from the fact that clojure-lsp formatting is much more aggressive than the formatting which is performed by emacs by default(in this case, it removes the space) and aggressive indent is calling it.


There are several fixes:

1. `(setq lsp-enable-indentation nil)` which will disable lsp-mode formatting.
2. clojure-lsp to expose a setting for the formatter which makes it less aggressive.

I don't see anything to fix on lsp-mode side.

**Comment by ericdallo** [comment]
About 2. clojure-lsp use cljfmt to format, so not sure this would be possible, we'd need to check cljfmt API to something less aggressive or open an issue there

**Comment by lvh** [comment]
`(setq lsp-enable-indentation nil)` (or the equivalent customize setting) does not seem to address the behavior. Disabling aggressive-indent-mode ... mostly does? But there's still some weird lsp-mode behavior going on.

**Comment by yyoncho** [comment]
> `(setq lsp-enable-indentation nil)` (or the equivalent customize setting) does not seem to address the behavior. Disabling aggressive-indent-mode ... mostly does? But there's still some weird lsp-mode behavior going on.

check the value of `indent-region-function` in the clj buffer, if it is still set to lsp-format-region then most likely you have st lsp-enable-indentation before opening the clj buffer. Also, provide more details about the problematic behaviour

**Comment by wmealing** [comment]
An information point.

I was seeing similiar behavior to what was described, I was able to solve it by testing yyonchos instructions.

This behavior was solved by setting:

```
(setq lsp-enable-indentation nil )
```

Before loading the relevant clojure file.   I'm not sure if this has changed behavior in any other feature unexpected, but at least the programmer can now type a space after a function name.

**Comment by kayzhang** [comment]
Got the similar indentation issue with tree-sitter & lsp-mode for c++-ts-mode. Previsouly I was using `(setq lsp-enable-indentation nil)` to workaround it as suggested above. However, similar issues pop up again after the commit 1aa4740.

For example, the expected bahavior is:
```
if (condition) {
    |
    // <- After hit enter after the open curly bracket, the cursor should be put at the correct indentation
}
```

The actual behavior is:
```
if (condition) {
|
// <- After hit enter after the open curly bracket, the cursor was put incorrectly at the start of the line
}
```

To workaround this, I added an extra `(setq lsp-enable-on-type-formatting nil)`.

Hope it helps to others with the same issue.
