### ISSUE TITLE
lsp-find-workspace usage in lsp-rust

### ISSUE THREAD

**Issue by flodiebold** [emacs-lsp/lsp-mode#2603]
I noticed `lsp-rust-analyzer-expand-macro` not working for me, and apparently the reason was that it was sending the request to the wrong rust-analyzer instance (I had multiple projects open). `lsp-find-workspace` seems to just select any rust-analyzer workspace if the second parameter isn't passed. It seems the second parameter was [intentionally removed](https://github.com/emacs-lsp/lsp-mode/commit/3b75d8b9f43b826b2674c5673cac0fe6c5fdf3e9), so I'm wondering what the reason for that was. Maybe we shouldn't be using `lsp-find-workspace` at all? That might just break things when there are multiple LSP servers for the same file.

CC @brotzeit

**Comment by brotzeit** [comment]
I vaguely remember that somebody had issues due to passing the parameters(sounds weird I know) to `lsp-find-workspace`. I tried it without the parameter and it worked, and I supposed the function just uses `default-directory` as default.

**Comment by yyoncho** [comment]
FWIW doing lsp-find-workspace + with-lsp-workspace is not needed unless the command is indented to be called in buffer which is not managed by lsp-mode+rust-analyzer.

**Comment by yyoncho** [comment]
PR at #2604
