### ISSUE TITLE
Cannot disable lsp-modeline-diagnostics-mode

### ISSUE THREAD

**Issue by bradrn** [emacs-lsp/lsp-mode#2609]
**Describe the bug**

I would like to disable `lsp-modeline-diagnostics-mode`. I can disable it interactively by calling `C-: (lsp-modeline-diagnostics-mode -1) RET`, but I cannot find a way to disable it by default. I have tried adding both `(setq-default lsp-modeline-diagnostics-mode nil)` and `(add-hook 'lsp-mode-hook (lambda () (lsp-modeline-diagnostics-mode -1)))` to both the `:init` and `:config` clauses of the relevant use-package declaration in my init.el, but neither has any effect.

**To Reproduce**

Using the following LSP configuration:

```elisp
(use-package lsp-mode
  :hook
  ((haskell-mode . lsp)
   (lsp-mode . lsp-enable-which-key-integration))
  :commands lsp
  :config
  ;; mostly copied from Spacemacs
  (spc-leader-define-key
    "l" '(:ignore t :which-key "lsp")
    ;; …lots and lots of keybindings, these shouldn’t be relevant to the issue…
    "lxL" #'lsp-lens-hide))
(use-package lsp-ui :commands lsp-ui-mode)
(use-package helm-lsp :commands helm-lsp-workspace-symbol)
(use-package lsp-haskell
  :init
  ;; fix indent
  (setq-default haskell-indentation-layout-offset     4
                haskell-indentation-left-offset       4
                haskell-indentation-starter-offset    4
                haskell-indentation-where-post-offset 4
                haskell-indentation-where-pre-offset  4)

  (defun haskell-hoogle-lookup-from-local-wrapper ()
    (interactive)
    (unless (haskell-hoogle-server-live-p) (haskell-hoogle-start-server))
    (haskell-hoogle-lookup-from-local))
  (mode-leader-define-key haskell-mode-map
    "hh" #'hoogle
    "hH" #'haskell-hoogle-lookup-from-local-wrapper))
```

Add either `(setq-default lsp-modeline-diagnostics-mode nil)` or `(add-hook 'lsp-mode-hook (lambda () (lsp-modeline-diagnostics-mode -1)))` to the `(use-package lsp-mode …)` clause. There is no effect.

**Expected behavior**

Both of the statements mentioned above should disable `lsp-modeline-diagnostics-mode`, making the diagnostics display on the modeline disappear.

**Which Language Server did you use** : [`lsp-haskell`](https://github.com/emacs-lsp/lsp-haskell)

**OS** : Windows 10

**Error callstack** : N/A

**Comment by yyoncho** [comment]
Use

```
(setq lsp-modeline-code-actions-enable nil)
```

and refer to https://emacs-lsp.github.io/lsp-mode/tutorials/how-to-turn-off/

**Comment by bradrn** [comment]
@yyoncho I think you have misread my issue. I don’t want to turn off code actions (which I have been finding incredibly useful!); I want to turn off modeline diagnostics. That is, in the following image:

![](https://emacs-lsp.github.io/lsp-mode/tutorials/images/turn-off-1.png)

I want to disable (7).

Also, I have already been through the tutorial you have linked to. This advises:

> 7. Modeline code actions
>
> ```
> (setq lsp-modeline-code-actions-enable nil)
> ```

As I already mentioned in my earlier post, I already tried this and it didn’t work.

**Comment by yyoncho** [comment]
> As I already mentioned in my earlier post, I already tried this and it didn’t work.

I don't see it in the original post. 

> I want to turn off modeline diagnostics

Modeline diagnostics are item 11.

**Comment by yyoncho** [comment]
Note that some of the settings have to be set before the first time you have started lsp-mode.

**Comment by bradrn** [comment]
> I don't see it in the original post.

Here:

> I have tried adding both `(setq-default lsp-modeline-diagnostics-mode nil)` …


> > I want to turn off modeline diagnostics
> Modeline diagnostics are item 11.

Whoops, so they are! You’re right — I think my issue may have been that I was confusing modeline diagnostics and modeline code actions. I’ll try disabling both and see if that helps.

> Note that some of the settings have to be set before the first time you have started lsp-mode.

I assume that corresponds to using the `:init` block in `use-package`? I’ll place those settings there in that case.

**Comment by yyoncho** [comment]
> I assume that corresponds to using the `:init` block in `use-package`? I’ll place those settings there in that case.

Both :init and :config should do.

**Comment by yyoncho** [comment]
> Here:
> 
> > I have tried adding both `(setq-default lsp-modeline-diagnostics-mode nil)` …

I was talking about `lsp-modeline-code-actions-enable` not `lsp-modeline-diagnostics-mode`

**Comment by bradrn** [comment]
OK, so I’ve experimented a bit with my Emacs, and can confirm that I am talking about this bit to the very right of the modeline (circled):

![modeline-image](https://user-images.githubusercontent.com/17613703/107871762-9f63e180-6ef8-11eb-83a5-c7f7627fc2f9.png)

That is to say, I _am_ in fact interested in `lsp-modeline-diagnostics-mode` as per my original post, rather than `lsp-modeline-code-actions-mode`.

However, having said that, I’ve also managed to figure out the appropriate way to disable it:

```elisp
use-package lsp-mode
  :hook
  ((haskell-mode . lsp)
   (lsp-mode . lsp-enable-which-key-integration))
  :commands lsp
  :init
  (setq-default lsp-modeline-diagnostics-enable nil)  ;; <-- this is the key line
  :config
;; rest is as in first post
)
```

I’m not entirely sure why this is working now when it didn’t work before… perhaps I was doing something wrong earlier. At any rate, it seems to be working now.
