### ISSUE TITLE
lsp-angular: support inline template completions

### ISSUE THREAD

**Issue by muradm** [emacs-lsp/lsp-mode#2617]
Currently `lsp-angular` activates `angular-ls` only for `html` files, here:
https://github.com/emacs-lsp/lsp-mode/blob/8166a1fe04891efcb7f1262609e77fc48500537b/clients/lsp-angular.el#L63

If you do something like:
```
:activation-fn (lambda (&rest _args)
                                   (and (or (string-match-p "\\.ts\\'" (buffer-file-name))
                                            (string-match-p "\\.html\\'" (buffer-file-name)))
                                        (lsp-workspace-root)
                                        (file-exists-p (f-join (lsp-workspace-root) "angular.json"))))
```
Then angular language server will work for inline templates like below as well:
```
@Component({
   // ...
  template: `
    <div *ngIf="data"> {{ data.arg }} </div>
  `
})
export class SomeComponent {
  data: { arg: string, arg1: number }
}
```
I'm not sure, but I think angular language server in general could bind to any file if project has `angular.json` in its root. Thus it should support then any other file it interested in. But this have to be checked with its implementation, I could dig only up to `lsp-angular.el`, I don't have enough knowledge about LSP protocol or implementations.

At least above suggestion partially worked for me, as normally I use only inline templates. That change does not provide high-lighting, but at least provide completion. "Partially worked", because "lsp-mode" seem to not handle all angular responses in proper manner. For instance documentation pops up with `^M` symbols etc.

Another suggestion is that it would make sense to include two `lsp-clients-angular-language-server-command` variants right in `lsp-angular`, one with command relative to `lsp-workspace-root` and one for `global` packages, normally there is no other variant, and select based on `@angular/language-server` package availability in the projects `node_modules`. Then it will avoid clutter in user config. (actually there may be 3rd variant which is based on lsp in docker suggested in documentation, but not very feasible I think).

**Comment by muradm** [comment]
I simplified `activation-fn` to the following:
```
:activation-fn (lambda (&rest _args)
                        (let* ((wr (lsp-workspace-root))
                               (angular-json (expand-file-name "angular.json" wr)))
                           (file-exists-p angular-json)))
```
This seems to be working. May be additionally temporary files could be filtered out, the ones with "#".

**Comment by yyoncho** [comment]
Looking at the vscode client

```
  "activationEvents": [
    "onLanguage:html",
    "onLanguage:typescript"
  ],
```
we should do pretty much the same but we are also looking for angular.json because IIRC the server was crashing if it was not present.

**Comment by muradm** [comment]
Then this one is more correct:
```
:activation-fn (lambda (&rest _args)
                                   (and (or (string-match-p "\\.ts\\'" (buffer-file-name))
                                            (string-match-p "\\.html\\'" (buffer-file-name)))
                                        (lsp-workspace-root)
                                        (file-exists-p (f-join (lsp-workspace-root) "angular.json"))))
```

**Comment by muradm** [comment]
PR: #2620 adds `.ts` to pattern match and also fixes missing end of line check.
