### ISSUE TITLE
Horrible Unusable Tooltip Icon Size

### ISSUE THREAD

**Issue by christopherdumas** [emacs-lsp/lsp-mode#2628]
**Describe the bug**
When I put my cursor on a line in a C or C++ file with lsp-mode activated, and the lsp server has some suggestions or capabilities for that line, the tooltip that appears to make me aware of that fact has a gigantic icon that pushes all the lines above and below the current one away. Then, when I move my cursor away, it dissapears. This leads to my code jittering around all over the place as I scroll.

![image](https://user-images.githubusercontent.com/1920151/108559076-b10a0800-72af-11eb-8736-dec25a8381f2.png)

Not to mention that it's always wrapping around, no matter how long I make the window!

**To Reproduce**
Hover over a line in a C file with lsp-mode activated, and watch space and time itself warp out of proportion.

**Expected behavior**
A normal size icon, or none at all.

**Which Language Server did you use**
clangd

**OS**
Pop!_OS 20.10

**Comment by christopherdumas** [comment]
This is excruciating.

**Comment by ericdallo** [comment]
This is a lsp-ui issue that already exists https://github.com/emacs-lsp/lsp-ui/issues/573

**Comment by christopherdumas** [comment]
> This is a lsp-ui issue that already exists [emacs-lsp/lsp-ui#573](https://github.com/emacs-lsp/lsp-ui/issues/573)

thanks lol
