### ISSUE TITLE
C/C++ Clangd completion for struct members adds a space

### ISSUE THREAD

**Issue by RomeuG** [emacs-lsp/lsp-mode#2634]
**Describe the bug**
In a C/C++ project, where `clangd` is used as the backend for `lsp-mode`, when using `company-complete`' to show the results, it adds a space character instead of showing all the possibilities for the completion.

An example, using a sample project of mine (https://github.com/RomeuG/SelfDwarfDumper):

I have this struct and function:

![image](https://user-images.githubusercontent.com/2325589/108598231-5f7f7d00-7384-11eb-97e0-3f861bba9184.png)

If in the function I write `a->`, the three different struct results appear without any problems:

![image](https://user-images.githubusercontent.com/2325589/108598253-7e7e0f00-7384-11eb-8600-ec0f4075bb4c.png)

If I move the cursor and then I get back to `a->` with the cursor right after `>` and use `company-complete` a space is added:

![image](https://user-images.githubusercontent.com/2325589/108598294-b4bb8e80-7384-11eb-9643-0db10e35adb6.png)

I assume that the results should appear instead of adding a space.

Another thing that should be noted, in the second image, is that the results window seems to add a space character in the beginning. I don't know if this is problematic or not.

**To Reproduce**

You can use a sample project of mine (https://github.com/RomeuG/SelfDwarfDumper) and Emacs should be started with `lsp-start-plain.el` using the following command: `emacs -q -l ~/.config/emacs/lsp-start-plain.el`.

More information on the bug description.

**Expected behavior**
When using `company-complete` after the `>` character to access the struct attributes, those same attributes should appear for selection.

**Which Language Server did you use**
I am using `lsp-clangd`.

**OS**

```
$ uname -a
Linux xerxes 5.10.16-zen1-1-zen #1 ZEN SMP PREEMPT Sat, 13 Feb 2021 20:51:02 +0000 x86_64 GNU/Linux

$ clangd --version
clangd version 11.0.1

$ emacs --version
GNU Emacs 28.0.50
Copyright (C) 2021 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

Emacs version is from the `native-comp` branch.

**Comment by yyoncho** [comment]
This is clangd "feature". Can you test with something like:
```
  (setq lsp-clients-clangd-args `("--header-insertion-decorators=0"))
```

**Comment by RomeuG** [comment]
Indeed that solves the issue completely.

I guess this is no bug of `lsp-mode`. Do you have any recommendation regarding this and how to deal with these kinds of things? I don't think I would fix this without your help.

**Comment by yyoncho** [comment]
> Do you have any recommendation regarding this and how to deal with these kinds of things?

Opening issue or asking in gitter/discord is fine. 

> I don't think I would fix this without your help.

We try to improve our docs and provide better defaults. The option to do it by yourself is to follow the lsp-mode and/or clangd and be familiar with specifics line that.

**Comment by RomeuG** [comment]
Ok! Thank you! :-)
