### ISSUE TITLE
Lsp-format-buffer after copy file to new file replaces file content with original file.

### ISSUE THREAD

**Issue by abhijeetsrivastava** [emacs-lsp/lsp-mode#2644]
**Describe the bug**
In Emacs Editor
Lsp-format-buffer after copy file to new file(and edit) replaces the file content with original file.

**To Reproduce**
For example.
```
File1.scala
Class File1 {something}
File2.scala(copy of File1.scala)
Class File2{something more}
```

Now if one calls `lsp-format-buffer` on File2.scala it would replace the content of File2.scala with File1.scala and format it.

**Expected behavior**
File2 's content should not change with File1.scala

**Which Language Server did you use**
lsp-scala with metals.

**OS**
Macos

**Work Around**
close emacs and reopen it and now do lsp-format-buffer which now works.

**Comment by yyoncho** [comment]
> Lsp-format-buffer after copy file to new file(and edit) replaces the file content with original file.

Can you describe how do you perform copy?

**Comment by abhijeetsrivastava** [comment]
I am using spacemacs. I Just `SPC f c` to copy files.

**Comment by yyoncho** [comment]
PR at #2650

**Comment by abhijeetsrivastava** [comment]
This was super fast. Thankyou so much!
