### ISSUE TITLE
LSP in Ruby code cannot resolve requires in bundler, even with lsp-solargraph-use-bundler set

### ISSUE THREAD

**Issue by asg0451** [emacs-lsp/lsp-mode#2646]
**Describe the bug**
The language server can't require files that i've included using bundler. 
![2021-02-23-113830_943x309_scrot](https://user-images.githubusercontent.com/4358545/108875915-ad39f680-75cb-11eb-9fa8-358b0e8fbf42.png)
It doesn't know about those files at all, can't jump to them from references in the current file, etc.

I feel like I must be missing something obvious here.
[solartest.zip](https://github.com/emacs-lsp/lsp-mode/files/6030487/solartest.zip)
 

**To Reproduce**
Sample project attached. I used the lsp-start-plain.el file with one change: I added the line:
```lisp
(setq lsp-solargraph-use-bundler t)
```
Go to the `solartest/one` directory
`$ bundle install`
Open up `lib/one.rb` and try to jump to the definition of Thing. It's defined in `solartest/thelib/lib/thing.rb`.

**Expected behavior**
LSP/Solargraph, with `lsp-solargraph-use-bundler` set, should be able to use bundler dependencies. 

**Which Language Server did you use**
lsp-ruby / solargraph

**OS**
Ubuntu 18.04

**Error callstack**
No error, but here is *lsp-log*
```
Command "bundle exec solargraph stdio" is present on the path.
Command "srb typecheck --lsp --disable-watchman" is not present on the path.
Command "bundle exec steep langserver --log-level=warn" is present on the path.
Command "bundle exec solargraph stdio" is present on the path.
Command "srb typecheck --lsp --disable-watchman" is not present on the path.
Command "bundle exec steep langserver --log-level=warn" is present on the path.
Found the following clients for /home/miles/ruby/solartest/one/lib/one.rb: (server-id ruby-ls, priority -1), (server-id steep-ls, priority -3)
The following clients were selected based on priority: (server-id ruby-ls, priority -1)
Command "bundle exec solargraph stdio" is present on the path.
Command "srb typecheck --lsp --disable-watchman" is not present on the path.
Command "bundle exec steep langserver --log-level=warn" is present on the path.
Command "bundle exec solargraph stdio" is present on the path.
Command "srb typecheck --lsp --disable-watchman" is not present on the path.
Command "bundle exec steep langserver --log-level=warn" is present on the path.
Found the following clients for /home/miles/ruby/solartest/one/lib/one.rb: (server-id ruby-ls, priority -1), (server-id steep-ls, priority -3)
The following clients were selected based on priority: (server-id ruby-ls, priority -1)
Command "bundle exec solargraph stdio" is present on the path.
Command "srb typecheck --lsp --disable-watchman" is not present on the path.
Command "bundle exec steep langserver --log-level=warn" is present on the path.
Command "bundle exec solargraph stdio" is present on the path.
Command "srb typecheck --lsp --disable-watchman" is not present on the path.
Command "bundle exec steep langserver --log-level=warn" is present on the path.
Found the following clients for /home/miles/ruby/solartest/one/lib/one.rb: (server-id ruby-ls, priority -1), (server-id steep-ls, priority -3)
The following clients were selected based on priority: (server-id ruby-ls, priority -1)
```

**Comment by yyoncho** [comment]
We need someone with ruby expertise to help with that, but I am afraid that none of the maintainers is actually using ruby. (@nbfalcon ?).

**Comment by asg0451** [comment]
@yyoncho thanks, I kinda expected that. Let me open an issue in solargraph referencing this. Maybe someone there can help.

**Comment by asg0451** [comment]
@yyoncho no it's still an issue, and nobody's gotten back to me on the solargraph repo either. But I agree, probably nothing to do here.

**Comment by yyoncho** [comment]
Thank you, marking as closed.
