### ISSUE TITLE
Test emacs-lsp packages

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#2655]
It will be nice if we have once centralized test suite which checks whether
emacs-lsp packages byte compile properly since a lot of the extension packages
use lsp-mode's internal functions(e. g. `lsp--point-to-position`).

**Comment by yyoncho** [comment]
@jcs090218 willing to take a look?

**Comment by jcs090218** [comment]
Sure! How would you like to proceed this? I think I have applied a CI test for most of emacs-lsp packages.

**Comment by yyoncho** [comment]
> How would you like to proceed this?

The goal is to byte-compile the packages part of emacs-lsp organization against the version of lsp-mode under test. I am not sure what will be the best/easiest way to achieve this - we can either clone their repos or install them via package.el and then filter out the byte-compilation errors coming from non-emacs-lsp packages.

**Comment by jcs090218** [comment]
> we can either clone their repos or install them via package.el and then filter out the byte-compilation errors coming from non-emacs-lsp packages.

Hmm.. I think we will need to create a new repository to do this task? If yes, what name would you prefer? I think I can work on this over the weekend. :)

**Comment by yyoncho** [comment]
> I think we will need to create a new repository to do this task

Why? Can we use that in order to get the PRs covered?

**Comment by jcs090218** [comment]
> Why? Can we use that in order to get the PRs covered?

Okay, I think I misunderstand your plan. Can you elaborate it so I can get a better image of what you are proposing? I am guessing that you want to filter out error/warning message from the emacs-lsp packages' dependencies? So we can get debugging easier if there is something wrong from their dependencies?

I thought the line below should already work? Since it already triggered the error flag while dependency goes wrong.

https://github.com/emacs-lsp/lsp-mode/blob/89a1525be9606e60f708052f86f501e934a14397/Makefile#L55

**Comment by yyoncho** [comment]
> Can you elaborate it so I can get a better image of what you are proposing?

I want the following: Developer FOO is opening a PR which renames `lsp--position-compare` to `lsp--position-compare-new-name` . Developer FOO opens a PR and CI fails, becase `lsp-java` is using `lsp--position-compare`.

**Comment by yyoncho** [comment]
FTR seems like we should include also external packages like `ccls`. This will help us be more aggressive with fixing poor function names and with refactoring.

**Comment by ericdallo** [comment]
The @yyoncho idea is to have a test suite for lsp-mode dependent packages, if the upstream (lsp-mode) rename a function, the downstream (lsp-dart, lsp-java, etc) would fail, so the CI would catch that somehow

**Comment by jcs090218** [comment]
> if the upstream (lsp-mode) rename a function, the downstream (lsp-dart, lsp-java, etc) would fail, so the CI would catch that somehow

Ah.. This beyond my knowledge right now hence I have no idea how to achieve this at this moment. Maybe we can specify a test that calls all API from `lsp-mode` and see if it is `void function`. But then it will requires us to trigger the CI for other emacs-lsp packages or wait for someone else to open a PR, etc.

**Comment by ericdallo** [comment]
Maybe we could have a package just like `lsp-start-plain.el` that has all lsp packages, then we try to byte-compile with no warnings, the we know if there is something pointing to nothing?

**Comment by yyoncho** [comment]
> Maybe we could have a package just like `lsp-start-plain.el` that has all lsp packages, then we try to byte-compile with no warnings, the we know if there is something pointing to nothing?

Something like that but IMHO we should first install the dependencies and the bytecompile only lsp-mode related stuff. To avoid failures caused by the deps.

**Comment by yyoncho** [comment]
> Ah.. This beyond my knowledge right now hence I have no idea how to achieve this at this moment. Maybe we can specify a test that calls all API from `lsp-mode` and see if it is `void function`

It is simpler - if we byte-complite these files we will catch errors like that. We already do that for the package undertest.

**Comment by jcs090218** [comment]
Thanks for the suggestions. I think the following steps should be good enough,

1. Create workflow file for this repository `lsp-mode`. (name suggestion will be welcome)
2. Setup Linux and Cask since Linux has the best performance
3. Install all emacs-lsp packages through Melpa
4. byte compile all emacs-lsp packages

**Comment by yyoncho** [comment]
Sounds good.

> Create workflow file for this repository lsp-mode. (name suggestion will be welcome)

Wouldn't one test in our existing test suite which calls package-install be sufficient here? 

> * Install all emacs-lsp packages through Melpa
> * byte compile all emacs-lsp package

Just note that these should happen against the lsp-mode from the source tree.

**Comment by jcs090218** [comment]
> Wouldn't one test in our existing test suite which calls package-install be sufficient here?

Do you mean you want to extend the current CI workflow? I guess that would work too but it would take longer for CI to complete.

> Just note that these should happen against the lsp-mode from the source tree.

Ah, yes! Got it.

**Comment by yyoncho** [comment]
> Do you mean you want to extend the current CI workflow? I guess that would work too but it would take longer for CI to complete.

Yes, I mean running that test suite as part of the current CI build. We may have a separate test for each subpackage. I believe that it won't add much time to the CI, I guess if we keep the CI less than 10 minutes we are fine.

**Comment by jcs090218** [comment]
Okay, I can work on this over weekend. :)

**Comment by yyoncho** [comment]
Fixed with #2678
