### ISSUE TITLE
Flymake not working on json file with js-mode

### ISSUE THREAD

**Issue by albert200000** [emacs-lsp/lsp-mode#2657]
I've set diagnostic provider to flymake and opened json file with js-mode but syntax errors not appearing. JSON server loaded without errors.

**Comment by yyoncho** [comment]
I am unable to reproduce. Do you see the errors with flycheck? Do you see errors in lsp-treemacs-errors-list? Do you see errors for other language servers? Have you tested with lsp-start-plain.el?

**Comment by albert200000** [comment]
Flycheck also not working. Flymake is not initialized at all. flycheck-verify-setup not listing lsp checker. It's only problem with js-mode. With json-mode it works as expected.

**Comment by yyoncho** [comment]
I tested with the following config and with `emacs -q -l <file.el>`
``` elisp
(require 'package)

(setq debug-on-error t
      no-byte-compile t
      package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("gnu" . "https://elpa.gnu.org/packages/"))
      package-user-dir (expand-file-name (make-temp-name "lsp-tmp-elpa")
                                         user-emacs-directory)
      custom-file (expand-file-name "custom.el" package-user-dir))

(let* ((pkg-list '(lsp-mode flymake)))
  (setq lsp-enabled-clients (list 'json-ls))
  (package-initialize)
  (package-refresh-contents)

  (mapc (lambda (pkg)
          (unless (package-installed-p pkg)
            (package-install pkg))
          (require pkg))
        pkg-list)

  (add-hook 'prog-mode-hook 'lsp)
  (add-hook 'kill-emacs-hook `(lambda ()
                                (delete-directory ,package-user-dir t))))

(provide 'lsp-start-plain)
```

and I am able to see the errors after I trigger them after editing a file.

**Comment by albert200000** [comment]
It was my config fault, sorry. I've set lsp-diagnostics-disabled-modes to js-mode and forgot about it.
