### ISSUE TITLE
function name adn parameters auto show at echo area

### ISSUE THREAD

**Issue by lqu3j** [emacs-lsp/lsp-mode#2659]
![image](https://user-images.githubusercontent.com/46402560/109484449-682a2e80-7abb-11eb-9d7c-3dfde23d619c.png)
![image](https://user-images.githubusercontent.com/46402560/109484741-c2c38a80-7abb-11eb-98ec-8ad7070f70c2.png)

like this ,when i input parentheses， function name adn parameters auto show at echo area, is there any way  to turn it off?

**Comment by yyoncho** [comment]
Check this - https://emacs-lsp.github.io/lsp-mode/tutorials/how-to-turn-off/

**Comment by lqu3j** [comment]
thks
