### ISSUE TITLE
Possible mispecification of `WorkspaceFolder`

### ISSUE THREAD

**Issue by torfjelde** [emacs-lsp/lsp-mode#2661]
I'm diverging a bit from the issue template here as this is more of a question about the spec rather than reporting an issue.

I'm currently using `lsp-mode` with `LanguageServer.jl` and ran into an issue when trying to add a new project which triggers the `workspace/didChangeWorkspaceFolders` message to be sent to the server. `LanguageServer.jl` then complained that there is no field `"name"`.

I'm raising the issue here rather than there because it seems to me (with a very limited understanding) that the complaint is a valid one. Looking at the [spec](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_workspaceFolders) `name` should indeed be present for a `WorkspaceFolder` but `lsp-mode` considers it to be optional?

E.g.
https://github.com/emacs-lsp/lsp-mode/blob/b1553d5f47713a94c847069ecf9752ba626a0690/lsp-mode.el#L3474
https://github.com/emacs-lsp/lsp-mode/blob/b1553d5f47713a94c847069ecf9752ba626a0690/lsp-mode.el#L7644

And, though this just might be a misunderstanding on my end, the _generated_ spec is wrong as it considers `:name` to be optional (if I've inferred correctly: the first list represents the required fields and the second the optional fields):
https://github.com/emacs-lsp/lsp-mode/blob/5868df5a438c09b3bffc29866670580d1f9fe9bb/lsp-protocol.el#L636
This is also present in the generated JSON schema, where only `uri` is required:
https://github.com/emacs-lsp/lsp-mode/blob/89a1525be9606e60f708052f86f501e934a14397/scripts/generated.protocol.schema.json#L1730-L1741
which makes sense given that, again if I understand correctly, `lisp-protocol.el` is generated from this JSON schema and not the other way around.

So, to conclude: seems like the generated schema is slightly wrong here?

**Comment by yyoncho** [comment]
> So, to conclude: seems like the generated schema is slightly wrong here?

The schema is generated from lsp4j and in their code name is optional - https://github.com/eclipse/lsp4j/blob/d6216cd86ffdac4bbb9d8773fee07d7b0f4c66be/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/Protocol.xtend#L6818 

Either way, the schema was generated after writing this code.

**Comment by yyoncho** [comment]
PR at #2664

**Comment by torfjelde** [comment]
That's some quick work! Thanks!
