### ISSUE TITLE
Avoid running CI twice

### ISSUE THREAD

**Issue by leungbk** [emacs-lsp/lsp-mode#2671]
Right now, anyone who makes a PR will end up executing the tests twice. Each subsequent force-push also runs the tests twice. It would be nice to run the tests only once each time.

**Comment by ericdallo** [comment]
I think we can change [here](https://github.com/emacs-lsp/lsp-mode/blob/master/.github/workflows/test.yml#L3) to only: `push`

**Comment by ericdallo** [comment]
Or even better, we can keep the pull-request, but specify master branch: https://github.com/clojure-lsp/clojure-lsp/blob/master/.github/workflows/ci.yml#L3-L6

**Comment by ericdallo** [comment]
FIxed
