### ISSUE TITLE
Choice description of defcustom lsp-completion-provider is misleading

### ISSUE THREAD

**Issue by XeCycle** [emacs-lsp/lsp-mode#2674]
[Its choice list](https://github.com/emacs-lsp/lsp-mode/blob/ac456a3a8a60a9fa96a3258b0bab905237e2fa5e/lsp-completion.el#L35) says `nil` and `:none` are all "None", but [mode setup code](https://github.com/emacs-lsp/lsp-mode/blob/ac456a3a8a60a9fa96a3258b0bab905237e2fa5e/lsp-completion.el#L694) treats `nil` the same way as `:capf` and `t`.  Currently only `:none` can be used to inhibit altering `company-backends`, which is 4th entry in the choice menu, looks the same as 3rd, while the latter doesn't work.

**Comment by yyoncho** [comment]
PR at #2684
