### ISSUE TITLE
Virtual buffers that redirect/map requests to another LSP server

### ISSUE THREAD

**Issue by razzmatazz** [emacs-lsp/lsp-mode#2679]
I am thinking of implementing support for razor (MS asp.net core template engine) that is actually based on C#.

The basic design of how it works in vscode is this:
- https://devblogs.microsoft.com/aspnet/new-experimental-razor-editor-for-visual-studio/

I was investigating lsp-mode virtual buffers a bit as they are used for org mode integration, but I am now quiet sure:
- how make server responses for certain buffers (that I have registered by uri) be intercepted by my own logic, remapped and sent as response from a different one.

To be clearer, we have:
- .cshtml buffer that has rzls attached as language server
- when change is made to .cshtml file razor server sends lsp-mode a `razor/updatecsharpbuffer` notification
  - which I can handle normally, with :request-handlers, and send the contents (generated .cs code from .cshtml) to csharp language server -- that I have working in prototype
- but then there comes say diagnostics for this virtual buffer back from csharp language server -- I would like to map those onto the original cshtml buffer and send them back to razor server so it can on its behalf notify lsp-mode back again with those diagnostics, just with translated line numbers

Not sure how to do the last ^^^ part. How to intercept the handle "text/diagnostics" notification for *certain* (virtual) buffers so can notify razor server instead with those?

**Comment by razzmatazz** [comment]
I can provide a test repo for this so we can figure out if we can make it work on top of lsp-mode. Additionally, it would be nice to reuse the "virtual" buffers functionality in lsp-mode for this..

**Comment by yyoncho** [comment]
> How to intercept the handle "text/diagnostics" notification for certain (virtual) buffers so can notify razor server instead with those?

If I am reading this correctly there is no need to do that, lsp-mode will do it for you when you create your virtual buffer. Check how `:line/character->point` is used. I encourage you to read `lsp-org` function, effectively, you should rewrite it for your case. Generally, there is a lot of trickiness to make that work.

**Comment by yyoncho** [comment]
Marking as closed - it seems like there are no action items on lsp-mode's side.
