### ISSUE TITLE
ESLint server initiation fails for angular html files

### ISSUE THREAD

**Issue by nO0B** [emacs-lsp/lsp-mode#2687]
Lsp-mode tries to initiate the ESLint server but fails for html files when using the @angular-eslint/template plugin. The error message is **ESLint is not configured properly. Please ensure your eslintrc is set up for the languages you are using.**

Minimal .eslintrc.js required to reproduce:
```
module.exports = {
  parser: '@angular-eslint/template-parser',
  plugins: ['@angular-eslint/template'],
  rules: {}
}
```
With this eslintrc, opening any html files in the project produces the error. However, adding the **html** plugin to the list of plugins resolves it.

The **html** plugin should not be required if the **@angular-eslint/template** plugin is specified.

Language Server: Lsp
OS: Linux Mint 19.2

**Comment by yyoncho** [comment]
@Sorixelle do you have a clue? I am not very familiar with what are the expectations here.

**Comment by Sorixelle** [comment]
Does this work in VSCode using the [ESLint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)? If I'm reading the code for the server correctly, it looks like this also wouldn't work there. Might be wrong though.

**Comment by nO0B** [comment]
Let me check with my colleagues and get back to you. Thanks for looking
into it.

**Comment by nO0B** [comment]
Colleagues say it does work with VSCode.

**Comment by nbfalcon** [comment]
@nO0B your workspace root could be wrong. Try the following:
1. `M-x lsp-workspace-folders-remove RET`
2. `M-x lsp`
3. Press `i`
4. Choose the correct path to the project

**Comment by nO0B** [comment]
@nbfalcon No luck. The root is correct and it works fine for js and ts files.

**Comment by nbfalcon** [comment]
@nO0B can you `(setq lsp-print-io t)` and post the trace, which should be in the `*eslint: <something>*` buffer?

**Comment by yyoncho** [comment]
I followed the description in the PR, created .eslintrc.js and empty html in empty folder. Then I opened in both emacs and vscode. What I saw is that eslint does not work in vscode since it is closing the file right away, emacs is not closing the file and thus that error.

I suspect that the issue report is not sufficient to reproduce the issue. @nO0B, can you provide full project?

**Comment by nO0B** [comment]
@nbfalcon The eslint buffers are empty. The only message I get about it is in the Messages buffer. lsp-print-io is set to t.

@yyoncho I am not confident whether it is working in vscode or not since my colleague just said that it seemed to be working. If you are able to reproduce the error with the minimal set-up and vscode is failing, then I think I should take this to vscode instead.

**Comment by nO0B** [comment]
@yyoncho Could you try adding the 'html' plugin to the list of plugins please? Just to make sure? The error should go away once you do.

Thanks for all your help.

**Comment by yyoncho** [comment]
> @yyoncho Could you try adding the 'html' plugin to the list of plugins please?
> Just to make sure? The error should go away once you do.
>
> Thanks for all your help.

The issue is that lsp-mode/vscode do find eslint at all and they disable it. I will try to reproduce the issue with project with proper eslint and so on. Please, when reporting an issue note that the other side might have zero js/eslint experience so the steps to reproduce should be very detailed.

**Comment by yyoncho** [comment]
> @yyoncho I can't give you the actual project, but I'll set up another small one and share it with you. I'll get it to you in a couple of days.

any update?

**Comment by nO0B** [comment]
> > @yyoncho I can't give you the actual project, but I'll set up another small one and share it with you. I'll get it to you in a couple of days.
> 
> any update?

Sorry, yes, here is a link to the repository: https://github.com/nO0B/eslint-angular.
Here is the relevant part of my emacs init file:
```
(use-package ng2-mode
  :mode
  (("\\.html\\'" . ng2-html-mode)
   ("\\.ts\\'" . ng2-ts-mode))
  :hook
  ((ng2-html-mode . lsp-deferred)
   (ng2-html-mode . electric-pair-mode)
   (ng2-ts-mode . lsp-deferred)
   (ng2-ts-mode . electric-pair-mode))
  :custom
  (typescript-indent-level 2))
```
If you open the ts files in the src folder, you'll see that everything works fine while it fails for the html files.

**Comment by yyoncho** [comment]
I tested the same project in vscode and it seems like the eslint does not work in the html files either.

**Comment by yyoncho** [comment]
![image](https://user-images.githubusercontent.com/13259670/116869452-73175180-ac19-11eb-892a-86a29571dc4f.png)

**Comment by nO0B** [comment]
In that case, thank you for testing and confirming. Sorry for bothering you.
