### ISSUE TITLE
lsp should not put overlays in treemacs

### ISSUE THREAD

**Issue by Alexander-Miller** [emacs-lsp/lsp-mode#2701]
I can't provide all the info from the template since it's not my bug. Basically it looks like some part of lsp has inserted `lsp-link` overlays into the treemacs buffer. These overlays then break treemacs because they are somehow found instead of the text-properties based `next-button` that treemacs is looking for: https://github.com/Alexander-Miller/treemacs/issues/778

I don't know what those links are for, but if they are stored in treemacs it's probably better to use text properties instead.

**Comment by mtbar131** [comment]
I am still seeing this behavior even after updating to latest lsp-mode. I can provide more information / debug output if that helps.

**Comment by yyoncho** [comment]
@mtbar131 can you tell me which server do you use and is it easy to reproduce the issue(eventually sample project will help too).

**Comment by mtbar131** [comment]
I am using `gopls` but it is not very easy to reproduce this. I usually start seeing this after opening my projects and working with them for around half an hour or so. I will still give it a try to reproduce this with a sample project.

**Comment by yyoncho** [comment]
generally, if you set lsp-enable-links to nil, the issue should go away.

**Comment by mtbar131** [comment]
Cool, let me try that and see if that fixes the issue.
