### ISSUE TITLE
Single quotes are too fancy in online docs

### ISSUE THREAD

**Issue by MrTheSaw** [emacs-lsp/lsp-mode#2718]
In the online documentation, at least on the Python Palantir pages (https://emacs-lsp.github.io/lsp-mode/page/lsp-pyls/), the single quotes in the pip install command are the fancy matching quotes 
### ’ ‘

and not the syntactically correct if boring tick marks available on the key to the right of my semicolon key

**Comment by ericdallo** [comment]
Fixed, thank you :)
