### ISSUE TITLE
Can't auto install csharp because of Forbidden error

### ISSUE THREAD

**Issue by DirtYiCE** [emacs-lsp/lsp-mode#2732]
Trying to auto install `csharp` results in the following in `*Messages*`:

```
LSP :: Download csharp started.
Contacting host: api.github.com:443
LSP :: Server csharp install process failed with the following error message: https://api.github.com/repos/OmniSharp/omnisharp-roslyn/releases: Forbidden.
Check `*lsp-install*' and `*lsp-log*' buffer.
```

`*lsp-install*` buffer doesn't exists and `*lsp-log*` only contains a bunch of unrelated `Command "..." is (not) present on the path.` lines. Interestingly if I open that URL in a browser, I get a json file back, and in the past I've installed the bash server from lsp so it should work generally.

Using lsp-mode 7.0.1 on emacs 27.1 on gentoo linux.

**Comment by yyoncho** [comment]
@razzmatazz willing to take a look?

**Comment by razzmatazz** [comment]
Hey @DirtYiCE 

Can you try to open the url in eww inside emacs? (`M-x eww` -- then enter the url `https://api.github.com/repos/OmniSharp/omnisharp-roslyn/releases`). This should test if https (ssl) works within emacs -- I am wondering if this might be related to ssl libraries linked to your emacs version?

Also.. have you tried running `M-x lsp-csharp-update-server`? Does that work -- I am wondering if there is something wrong with lsp auto-installation mechanism integration with lsp-csharp.el.

**Comment by DirtYiCE** [comment]
Hello @razzmatazz,
`eww` gives me this:
```
Contacting host: api.github.com:443
error in process sentinel: eww-display-html: This function requires Emacs to be compiled with libxml2
error in process sentinel: This function requires Emacs to be compiled with libxml2
```
I'll try to recompile emacs with libxml2 support and see if it changes anything.

`M-x lsp-csharp-update-server` results in a similar problem:
```
Contacting host: api.github.com:443
url-http--insert-file-helper: https://api.github.com/repos/OmniSharp/omnisharp-roslyn/releases: Forbidden
```

**Comment by DirtYiCE** [comment]
Okay, after a recompile I get this:
```
Request forbidden by administrative rules. Please make sure your request has a User-Agent header (http://developer.github.com/v3/#user-agent-required). Check https://developer.github.com for other possible causes. 
```

**Comment by DirtYiCE** [comment]
Hmm, okay, with `emacs -Q` eww opens the urls fine, so I guess something is with my local config, but I can't find anything in my init.el related to http or user agents. Any ideas what could be the problem?

**Comment by razzmatazz** [comment]
I did a quick google and I found this:
- https://www.reddit.com/r/emacs/comments/40sol0/emacs_user_agent/

Maybe you can do `F1 f` and then enter `url-http-user-agent-string` so you can find which package/config redefines the user agent fn (if any)?

**Comment by DirtYiCE** [comment]
Ah, I found it, a while back I set `url-privacy-level` to `paranoid` which means don't even send a user-agent header. Setting it to `high` or lower seems to fix this issue, and I could install it.
And immediately receive a `LSP :: Error from the Language Server: Internal Error - System.NullReferenceException: Object reference not set to an instance of an object`, but I think that's not lsp-mode's fault...

**Comment by jcs090218** [comment]
> And immediately receive a LSP :: Error from the Language Server: Internal Error - System.NullReferenceException: Object reference not set to an instance of an object, but I think that's not lsp-mode's fault...

You might want to report this to upstream! I think the issue can be close now? :)
