### ISSUE TITLE
There is no way to always add or remove projects from a given directory to the workspace

### ISSUE THREAD

**Issue by Andre0991** [emacs-lsp/lsp-mode#2738]
(I guess this is more like a feature request, sorry if this is not the appropriate forum for that).

Sometimes I’m on a project and I use ‘go to definition’ in some function that comes from a lib in  `~./m2`.

Then, LSP asks if I want to add the project to the workspace list etc.

The annoying thing is that LSP always asks me if I want to add it.

So it would be nice to be able to _always_ ignore projects in a given folder (in this case, `~./m2`. (or maybe always add them)

**Comment by ericdallo** [comment]
@yyoncho I thought [this](https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-clojure.el#L228-L231) was the way to fix that, but it seems it's not working, do you know why?

**Comment by yyoncho** [comment]
> @yyoncho I thought [this](https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-clojure.el#L228-L231) was the way to fix that, but it seems it's not working, do you know why?

Maybe this

> (string-match-p ".m2/repository" (buffer-file-name))

does not work on @Andre0991 PC.

**Comment by ericdallo** [comment]
It seems to doesn't work for everyone, including me, I'm just not sure if that's is the correct way to do that  😅

**Comment by Andre0991** [comment]
I confirmed the at least the string match part does work (it's true and the when's body is executed).

```
(defun lsp-clojure--library-folders (_workspace)
  "Return the library folders path to analyze for WORKSPACE."
  (when (string-match-p ".m2/repository" (buffer-file-name))
    (message "in when")
    (list (file-name-directory (buffer-file-name)))))```

**Comment by ericdallo** [comment]
Yeah, I could repro the same thing, still lsp-mode asks for the root, not sure why

**Comment by ericdallo** [comment]
@Andre0991, Could you test on latest lsp-mode, I made some changes that may fix the issue, not sure, but it worths a shot

**Comment by Andre0991** [comment]
Sure, I'll test it. But it seems that `2021.03.24-00.41.55` is the latest version for the `clojure-lsp-native` formula yet.

**Comment by ericdallo** [comment]
I meant lsp-mode, not clojure-lsp :p

**Comment by Andre0991** [comment]
Oops, of course 😅

I confirm it works, thanks ⭐️

Note: `lsp-version` returns an error:

![image](https://user-images.githubusercontent.com/7083061/112764625-d80ad680-8fdf-11eb-8187-65dfdb46369d.png)

I dunno if this is a regression, I don't remember if I tried this command before.

Also, I use `doom-emacs`,  if this matters.

Anyway, I'm closing this issue.

**Comment by ericdallo** [comment]
Nice!
I think you re-byte-compile should fix the issue, right @yyoncho ?

**Comment by yyoncho** [comment]
> Nice!
> I think you re-byte-compile should fix the issue, right @yyoncho ?

is it working for you on doom? This function is using package.el stuff so it may not work on straight.
