### ISSUE TITLE
Lsp eslint auto install server hang my Emacs

### ISSUE THREAD

**Issue by declanqian** [emacs-lsp/lsp-mode#2739]
Lsp eslint auto install server hang my Emacs

**Describe the bug**

I only use lsp-eslint for now. So I have following setup

```
(use-package lsp
  :straight (:type git :flavor melpa :files (:defaults "lsp-mode-pkg.el") :host github :repo "emacs-lsp/lsp-mode")
  :commands (lsp lsp-deferred))

(use-package lsp-eslint
  :after lsp
  :straight (:type git :flavor melpa :files ("clients/lsp-eslint.el") :host github :repo "emacs-lsp/lsp-mode"))
```

When I in a js buffer, hit command `lsp`. It prompt to install `eslint`.
After I select eslint, my Emacs became unresponsive.

**To Reproduce**

- `emacs -q -l lsp-start-plain.el`
- Disable all other lsp clients from `(customize-group 'lsp-mode)`,
by remove registered clients other than eslint. (Cause I haven't find other way
to disable clients)
- Open a js file
- `M-x lsp`
- Choose `eslint`

**Expected behavior**

Output some error messages if any, just don't block Emacs.           

**Which Language Server did you use**

lsp-eslint

**OS**

```GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin20.3.0, NS appkit-2022.30 Version 11.2.1 (Build 20D74)) of 2021-03-21```

**Error callstack**

Below is trace from terminal.
```
2021-03-24 14:20:26.885 Emacs[38197:2370611] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff206fa6af __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff204323c9 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff20722a9a -[NSException raise] + 9
	3   AppKit                              0x00007fff22ec9460 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 321
	4   AppKit                              0x00007fff22ed7535 -[NSThemeFrame _tileTitlebarAndRedisplay:] + 111
	5   AppKit                              0x00007fff22ee9c28 -[NSTitledFrame _titleDidChange] + 158
	6   AppKit                              0x00007fff236e797a -[NSTitledFrame setTitle:subtitle:] + 722
	7   AppKit                              0x00007fff22ee9856 -[NSThemeFrame setTitle:] + 50
	8   AppKit                              0x00007fff23492cd6 -[NSFrameView _updateTitleProperties:animated:] + 51
	9   AppKit                              0x00007fff236da7e7 -[NSThemeFrame _updateTitleProperties:animated:] + 186
	10  CoreFoundation                      0x00007fff20675fec __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	11  CoreFoundation                      0x00007fff2071189b ___CFXRegistrationPost_block_invoke + 49
	12  CoreFoundation                      0x00007fff2071180f _CFXRegistrationPost + 454
	13  CoreFoundation                      0x00007fff20646bde _CFXNotificationPost + 723
	14  Foundation                          0x00007fff213b5abe -[NSNotificationCenter postNotificationName:object:userInfo:] + 59
	15  AppKit                              0x00007fff235dc0b4 -[NSWindowTitleController _propertiesChanged:] + 147
	16  AppKit                              0x00007fff23098154 -[NSWindow _setRepresentedURL:] + 94
	17  Emacs                               0x0000000106f15e98 ns_implicitly_set_name + 387
	18  Emacs                               0x0000000106dbf98c gui_consider_frame_title + 638
	19  Emacs                               0x0000000106d9b4c3 redisplay_internal + 1212
	20  Emacs                               0x0000000106e207ac read_char + 1737
	21  Emacs                               0x0000000106e1ea64 read_key_sequence + 1250
	22  Emacs                               0x0000000106e1d6f8 command_loop_1 + 865
	23  Emacs                               0x0000000106e89ebf internal_condition_case + 84
	24  Emacs                               0x0000000106e2a24a command_loop_2 + 37
	25  Emacs                               0x0000000106e89b4a internal_catch + 173
	26  Emacs                               0x0000000106e1cd7a recursive_edit_1 + 148
	27  Emacs                               0x0000000106e43450 read_minibuf + 2432
	28  Emacs                               0x0000000106e42ab2 Fread_from_minibuffer + 242
	29  minibuffer-1b0f548b-fe094e36.eln    0x000000010b41a3b9 F636f6d706c6574696e672d726561642d64656661756c74_completing_read_default_0 + 297
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by nbfalcon** [comment]
Have you tried pressing `i`? `Fread_from_minibuffer` suggests some sort of prompt, which is more-or-less blocking.

**Comment by declanqian** [comment]
Tried on Linux
GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo ve\
rsion 1.17.4) of 2021-03-21

```
[/tmp/extqNo5N0.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/extqNo5N0.zip or
        /tmp/extqNo5N0.zip.zip, and cannot find /tmp/extqNo5N0.zip.ZIP, period.


```
Then

```
Debugger entered--Lisp error: (no-catch exit nil)
  exit-minibuffer()
  completion--complete-and-exit(111 111 exit-minibuffer #f(compiled-function ()$
  completion-complete-and-exit(111 111 exit-minibuffer)
  minibuffer-complete-and-exit()
  funcall-interactively(minibuffer-complete-and-exit)
  command-execute(minibuffer-complete-and-exit)
```

**Comment by declanqian** [comment]
> Have you tried pressing `i`

i is undefined it says @nbfalcon

**Comment by declanqian** [comment]
I think there are two issues here.
- `(url-copy-file (lsp-vscode-extension-url "dbaeumer" "vscode-eslint" "2.1.14") "/tmp/output")`
<b>Sometimes</b> `out` is a text file with content, not zip file  
```{"$id":"1","innerException":null,"message":"Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on why your request was blocked, see the topic \"Rate limits\" on the Microsoft Web site (https://go.microsoft.com/fwlink/?LinkId=823950).","typeName":"Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, Microsoft.TeamFoundation.Framework.Server","typeKey":"RequestBlockedException","errorCode":0,"eventId":3000}```
- Event if `out` is a zip file. Still, after installation.

  `[key] is undefined`

  , and 

 ```
Debugger entered--Lisp error: (no-catch exit nil)
  exit-minibuffer()
  completion--complete-and-exit(111 111 exit-minibuffer #f(compiled-function ()$
  completion-complete-and-exit(111 111 exit-minibuffer)
  minibuffer-complete-and-exit()
  funcall-interactively(minibuffer-complete-and-exit)
  command-execute(minibuffer-complete-and-exit)
```

**Comment by yyoncho** [comment]
> Debugger entered--Lisp error: (no-catch exit nil)
 exit-minibuffer()
 completion--complete-and-exit(111 111 exit-minibuffer #f(compiled-function ()$
 completion-complete-and-exit(111 111 exit-minibuffer)
 minibuffer-complete-and-exit()
 funcall-interactively(minibuffer-complete-and-exit)
 command-execute(minibuffer-complete-and-exit)

What do you do to get that error?

**Comment by declanqian** [comment]
After auto installation, any keyboard input with `Ctrl` and `Meta` key I think.

However, for single `char` key, says it's undefined.

**Comment by yyoncho** [comment]
You have some kind of prompt in the minibuffer. Do y/n work? The prompt will be available in the messages buffer. 

This code will install eslint.
```
(url-copy-file (lsp-vscode-extension-url "dbaeumer" "vscode-eslint" "2.1.14") "/tmp/foo.zip")
(lsp-unzip "/tmp/foo.zip" lsp-eslint-unzipped-path)
```

**Comment by declanqian** [comment]
https://streamable.com/yxeick

**Comment by yyoncho** [comment]
Can you keep messages buffer side by side? Also, can you try with emacs 27.1? 

Apparently eslint is installed. What happens the second time you try to open the file?

**Comment by declanqian** [comment]
Eslint is installed because I did some changes to lsp-mode

```diff
diff --git a/clients/lsp-eslint.el b/clients/lsp-eslint.el
index 6e1dbd3..a121bae 100644
--- a/clients/lsp-eslint.el
+++ b/clients/lsp-eslint.el
@@ -346,7 +346,7 @@ to allow or deny it.")
                                    (funcall callback))
                                (error (funcall error-callback err))))
                            error-callback
-                           :url (lsp-vscode-extension-url "dbaeumer" "vscode-eslint" "2.1.14")
+                           :url "file:///tmp/dbaeumer.vscode-eslint-2.1.14.vsix"
                            :store-path tmp-zip)))))
 
 (provide 'lsp-eslint)
```

Below is the screen cast for emacs 27.1

https://imgur.com/maNJq4y

**Comment by yyoncho** [comment]
> https://imgur.com/maNJq4y

Press `TAB`

**Comment by declanqian** [comment]
https://imgur.com/FnBA4IN

**Comment by yyoncho** [comment]
Do you have nodejs installed on that machine and present on the path which emacs is running with? On your last video, the tab does not work because of the backtrace dialog. How do you get it?

**Comment by declanqian** [comment]
https://github.com/emacs-lsp/lsp-mode/issues/2739#issuecomment-805563136

Cause the downloaded file is not a zip file but a text file with 

```json
{"$id":"1","innerException":null,"message":"Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on why your request was blocked, see the topic \"Rate limits\" on the Microsoft Web site (https://go.microsoft.com/fwlink/?LinkId=823950).","typeName":"Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, Microsoft.TeamFoundation.Framework.Server","typeKey":"RequestBlockedException","errorCode":0,"eventId":3000}
```

**Comment by declanqian** [comment]
> On your last video, the tab does not work because of the backtrace dialog. How do you get it?

I didn't kill the emacs. the dialog if from previous video.
https://imgur.com/maNJq4y  @yyoncho

**Comment by yyoncho** [comment]
Do you have nodejs installed and on the path?

**Comment by declanqian** [comment]
yeah. I have `node` installed and it's on the path

**Comment by yyoncho** [comment]
What do `(lsp-eslint-server-command)` and `(lsp-eslint-server-exists? (lsp-eslint-server-command))` return?

**Comment by declanqian** [comment]
I mean, it works fine if I manually set `lsp-eslint-server-command`
https://github.com/emacs-lsp/lsp-mode/wiki/LSP-ESlint-integration.
All works fine. 

I was trying to point out that there is issue when using the auto installation
for the first time

**Comment by yyoncho** [comment]
Is the issue related to rate limiters or not?

**Comment by declanqian** [comment]
> I think there are two issues here.
> 
> * `(url-copy-file (lsp-vscode-extension-url "dbaeumer" "vscode-eslint" "2.1.14") "/tmp/output")`
>   Sometimes `out` is a text file with content, not zip file
>   `{"$id":"1","innerException":null,"message":"Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on why your request was blocked, see the topic \"Rate limits\" on the Microsoft Web site (https://go.microsoft.com/fwlink/?LinkId=823950).","typeName":"Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, Microsoft.TeamFoundation.Framework.Server","typeKey":"RequestBlockedException","errorCode":0,"eventId":3000}`
> * Event if `out` is a zip file. Still, after installation.
>   `[key] is undefined`
>   , and
> 
> ```
> Debugger entered--Lisp error: (no-catch exit nil)
>  exit-minibuffer()
>  completion--complete-and-exit(111 111 exit-minibuffer #f(compiled-function ()$
>  completion-complete-and-exit(111 111 exit-minibuffer)
>  minibuffer-complete-and-exit()
>  funcall-interactively(minibuffer-complete-and-exit)
>  command-execute(minibuffer-complete-and-exit)
> ```

**Comment by declanqian** [comment]
Separated I think

**Comment by yyoncho** [comment]
I tested with both emacs 27.1 and the latest emacs 28 using lsp-start-plain.el and it works fine with both. To me it looks like you are pressing C-g and then you are not pressing `c` in the backtrace dialog which is breaking Emacs..

**Comment by declanqian** [comment]
> pressing C-g and then you are not pressing c in the backtrace dialog which is breaking Emacs.

Ah, pressing c. Thanks for your time. This is new information for me.

**Comment by declanqian** [comment]
Just figured out the issue `lsp--find-root-interactively` is been called
from `lsp-download-install`'s  `make-thread` block.

According to this article https://tvraman.github.io/emacspeak/blog/async-and-threads.html#orgddc2037

> Like other asynchronous solutions (see package async for instance) one needs to make sure that the command being executed asynchronously will not require user input. In the case of package async, the asynchronous Emacs will block waiting for input; in the case of make-thread, Emacs enters a blocking loop with the minibuffer continuously displaying
No catch for ...
The only way to come out is to kill Emacs 


A simple snippet to replicated the issue
<b>(Make sure to start a new Emacs process)</b>

```
(make-thread (lambda ()
              (let* ((action (read-key "Press keyboard")))
               (print action))))
```

**Comment by miker2049** [comment]
For what its worth here, I too am not getting a zip file from either the automatic install or attempting the manual 
```
(url-copy-file (lsp-vscode-extension-url "dbaeumer" "vscode-eslint" "2.1.14") "/tmp/foo.zip")
(lsp-unzip "/tmp/foo.zip" lsp-eslint-unzipped-path)
```
and I get back the same rate limited message 
```
{"$id":"1","innerException":null,"message":"Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on why your request was blocked, see the topic \"Rate limits\" on the Microsoft Web site (https://go.microsoft.com/fwlink/?LinkId=823950).","typeName":"Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, Microsoft.TeamFoundation.Framework.Server","typeKey":"RequestBlockedException","errorCode":0,"eventId":3000}
```
building the extension manually and linking it to the defined `unzipped` folder makes it work
