### ISSUE TITLE
getting error void-function for -compose

### ISSUE THREAD

**Issue by bingoUV** [emacs-lsp/lsp-mode#2744]
In latest `lsp-mode` from melpa (lsp-mode-20210321.1904), when loading `lsp-mode`, I get an error `void-function` for `-compose`. I see that the method `-compose` is present in `dash-functional`, but `lsp-mode` requires only `dash`.

This gets fixed by adding a `require` of `dash-functional`. This will remain in my personal fixes, but I do not have the skills to fix it in a manner clean enough for this project.

**Comment by yyoncho** [comment]
-compose was moved in dash.el. If you update it it will work fine.
