### ISSUE TITLE
imenu does not leverage textDocument/documentSymbol for typescript

### ISSUE THREAD

**Issue by JordanAnthonyKing** [emacs-lsp/lsp-mode#2745]
**Describe the bug**
For typescript imenu does not categorise symbols:

![image](https://user-images.githubusercontent.com/58787893/112689612-737e3900-8e72-11eb-92e5-7eefdffff098.png)

This behaviour is as expected in other language servers such as css:

![image](https://user-images.githubusercontent.com/58787893/112689742-9872ac00-8e72-11eb-83d4-91c4b913998b.png)

I have verified that `lsp-enable-imenu` is non-nil in both cases and that `imenu-create-index-function` is `'lsp--imenu-create-index`. From there lsp's `lsp-imenu-index-function` is `'lsp-imenu-create-uncategorized-index`

**To Reproduce**
Open a typescript file and run imenu. In the screenshots I am running imenu-consul within doom.

**Expected behavior**
Entries to be listed with their `kind` for filtering.

**Which Language Server did you use**
theia-ide typescript language server, version 5.0

**OS**
Ubuntu 20.04 under Windows 10 via WSL

**Error callstack**
No errors are thrown when calling imenu, either from emacs, or the language server.

Taking a look at the lsp-log for ts-ls with log verbosity set to debug symbols do seem to be returned: 
```
[Trace - 08:49:54 PM] Sending request 'initialize - (1)'.
Params: {
  "processId": null,
  "rootPath": "/home/jordan/edm/data-dictionary-microsite",
  "clientInfo": {
    "name": "emacs",
    "version": "GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)\n of 2021-03-16"
  },
  "rootUri": "file:///home/jordan/edm/data-dictionary-microsite",
  "capabilities": {
    "workspace": {
      "workspaceEdit": {
        "documentChanges": true,
        "resourceOperations": [
          "create",
          "rename",
          "delete"
        ]
      },
      "applyEdit": true,
      "symbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        }
      },
      "executeCommand": {
        "dynamicRegistration": false
      },
      "didChangeWatchedFiles": {
        "dynamicRegistration": true
      },
      "workspaceFolders": true,
      "configuration": true
    },
    "textDocument": {
      "declaration": {
        "linkSupport": true
      },
      "definition": {
        "linkSupport": true
      },
      "implementation": {
        "linkSupport": true
      },
      "typeDefinition": {
        "linkSupport": true
      },
      "synchronization": {
        "willSave": true,
        "didSave": true,
        "willSaveWaitUntil": true
      },
      "documentSymbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        },
        "hierarchicalDocumentSymbolSupport": true
      },
[The file continues...]
```

Doing the same with css-ls shows this also being returned for that language server too however:
```
[Trace - 08:52:47 PM] Sending request 'initialize - (23)'.
Params: {
  "processId": null,
  "rootPath": "/home/jordan/edm/data-dictionary-microsite",
  "clientInfo": {
    "name": "emacs",
    "version": "GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)\n of 2021-03-16"
  },
  "rootUri": "file:///home/jordan/edm/data-dictionary-microsite",
  "capabilities": {
    "workspace": {
      "workspaceEdit": {
        "documentChanges": true,
        "resourceOperations": [
          "create",
          "rename",
          "delete"
        ]
      },
      "applyEdit": true,
      "symbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        }
      },
      "executeCommand": {
        "dynamicRegistration": false
      },
      "didChangeWatchedFiles": {
        "dynamicRegistration": true
      },
      "workspaceFolders": true,
      "configuration": true
    },
    "textDocument": {
      "declaration": {
        "linkSupport": true
      },
      "definition": {
        "linkSupport": true
      },
      "implementation": {
        "linkSupport": true
      },
      "typeDefinition": {
        "linkSupport": true
      },
      "synchronization": {
        "willSave": true,
        "didSave": true,
        "willSaveWaitUntil": true
      },
      "documentSymbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        },
        "hierarchicalDocumentSymbolSupport": true
      },
[The file continues...]
```

Thanks, please let me know if I can provide any more info.

**Comment by yyoncho** [comment]
cc @nbfalcon

**Comment by yyoncho** [comment]
> **Expected behavior**
> Entries to be listed with their `kind` for filtering.

Can you elaborate? I am not quite sure what the issue is, Imenu seems to be functional.

**Comment by JordanAnthonyKing** [comment]
> Can you elaborate? I am not quite sure what the issue is, Imenu seems to be functional.

Compare in the screenshots, imenu in the less buffer categorises items according to whether they are a class/variable/constant etc. In the typescript buffer they are categorised according to their position in the document which appears to be fallback behaviour for when the language server doesn't provide a set of _kinds_ to group by. It seems according to the logs that the typescript server is provided this information however.

**Comment by yyoncho** [comment]
I am a bit confused. First, your logs contain only the client capabilities which seem to be irrelevant. 

> when the language server doesn't provide a set of kinds to group by

I am not aware of such functionality. 

I tested ts files and when  lsp-imenu-index-function is set to lsp-imenu-create-categorized-index the items are correctly grouped by category.

**Comment by JordanAnthonyKing** [comment]
It seems that I don't understand the terminology being used exactly.

How can I have imenu categorise items according to class/variable/const etc. for `.ts` files like in it does for `.less` files?

**Comment by yyoncho** [comment]
set  lsp-imenu-index-function to lsp-imenu-create-categorized-index

**Comment by JordanAnthonyKing** [comment]
> set lsp-imenu-index-function to lsp-imenu-create-categorized-index

This works. It seems that I was being misled by the output of `lsp-imenu-create-uncategorized-index` for the .less file. Having changed the function less files are now grouped like _classes/variables/constants_ isntead of _class/variable/const_. 

.ts files are grouped as I'd expect: _classes/properties/constructors_ etc.

Thanks.
