### ISSUE TITLE
How to display parameters doc in overlay instead of minibuffer

### ISSUE THREAD

**Issue by stardiviner** [emacs-lsp/lsp-mode#2749]
![lsp display function parameters doc in minibuffer](https://user-images.githubusercontent.com/378699/112798495-8c1f6680-909f-11eb-8b4b-6ab1bc3157aa.png)

How to set lsp-mode to display the function parameter documentation in overlay popup instead of minibuffer?

**Comment by yyoncho** [comment]
After installing posframe package you may use  `(setq lsp-signature-function 'lsp-signature-posframe)`

**Comment by stardiviner** [comment]
Thanks @yyoncho
