### ISSUE TITLE
ocaml-lsp-server can't resolve paths with spaces

### ISSUE THREAD

**Issue by nosewings** [emacs-lsp/lsp-mode#2757]
**Describe the bug**

When working on a project with `ocaml-lsp-server` in a directory whose path has spaces, the server is unable to resolve files in the same directory.

**To Reproduce**

1. `mkdir "Test Directory"; cd "Test Directory"`.
2.  `touch FileA.ml`
3. `echo "open FileA" > FileB.ml`
4. `ocamlc *.ml`
5. Open `FileB.ml` in Emacs: it gives the error `Unbound module FileA`.

**Expected behavior**

`FileB` should be able to resolve `FileA`. (This works in Kate). If you replace Step 1 with `mkdir tstdir; cd tstdir`, then everything works.

Note: the error still occurs even if you create a `.merlin` file with lines `S .` and `B .`.

**Which Language Server did you use**

`ocaml-lsp-server`, with `ocamllsp` installed via `opam`.

**OS**

Linux.

**Error callstack**

N/A

**Comment by nosewings** [comment]
[lsp-mode-logs.txt](https://github.com/emacs-lsp/lsp-mode/files/6251068/lsp-mode-logs.txt)
[katelogs.txt](https://github.com/emacs-lsp/lsp-mode/files/6251070/katelogs.txt)

**Comment by yyoncho** [comment]
@nosewings AFAICS you have picked a different project root in kate. In kate, the project root is your home folder, without the part with space in it.

**Comment by nosewings** [comment]
OK, after re-testing with the appropriate project root, it still works in Kate. (The only way was able to make this work was by adding the line `{"servers": {"ocaml": {"rootIndicationFileNames": ["FileA.ml"] }}}` to the file `~/.config/kate/lspclient/settings.json`.)
[katelogs2.txt](https://github.com/emacs-lsp/lsp-mode/files/6251201/katelogs2.txt)

**Comment by yyoncho** [comment]
As far as I can see the difference is in %20 encoding which should be supported by the server as per the spec.

**Comment by yyoncho** [comment]
This is the RFC linked from the lsp spec - https://tools.ietf.org/html/rfc3986 . Please open server bug.

**Comment by nosewings** [comment]
OK, thanks for helping me locate the source of the problem.
