### ISSUE TITLE
M-. doesn't work

### ISSUE THREAD

**Issue by dackon** [emacs-lsp/lsp-mode#2770]
Hello,

I followed the tutorial(https://emacs-lsp.github.io/lsp-mode/tutorials/reactjs-tutorial/), but M-. cannot jump to the definition. The mini-buffer shows: Jump to: xxx [no match]. However, M-x lsp-find-definition can jump to the definition.

Emacs 27.2
lsp-mode 20210407.2348

**Comment by yyoncho** [comment]
I am unable to reproduce on my side, can you check if setting `xref-prompt-for-identifier` to nil fixes the issue?

**Comment by dackon** [comment]
Thanks for reply.

It doesn't work. I deleted my .emacs and .emacs.d, and copied the configuration from turtorial.

```lisp
(package-initialize)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(setq package-selected-packages '(lsp-mode yasnippet lsp-treemacs helm-lsp projectile hydra flycheck company avy which-key helm-xref dap-mode zenburn-theme json-mode))
(when (cl-find-if-not #'package-installed-p package-selected-packages)
  (package-refresh-contents)
  (mapc #'package-install package-selected-packages))
(load-theme 'zenburn t)
(helm-mode)
(require 'helm-xref)
(define-key global-map [remap find-file] #'helm-find-files)
(define-key global-map [remap execute-extended-command] #'helm-M-x)
(define-key global-map [remap switch-to-buffer] #'helm-mini)
(which-key-mode)
(add-hook 'prog-mode-hook #'lsp)
(setq gc-cons-threshold (* 100 1024 1024)
      read-process-output-max (* 1024 1024)
      company-idle-delay 0.0
      company-minimum-prefix-length 1
      create-lockfiles nil) ;; lock files will kill `npm start'
(with-eval-after-load 'lsp-mode
  (require 'dap-chrome)
  (add-hook 'lsp-mode-hook #'lsp-enable-which-key-integration)
  (yas-global-mode))

(setq xref-prompt-for-identifier nil)

```

**Comment by yyoncho** [comment]
Hm, can you do `M-: xref-backend-functions RET` in that buffer?

**Comment by yyoncho** [comment]
I am also testing with emacs 27.2

**Comment by dackon** [comment]
mini-buffer shows:
(elisp--xref-backend t)

**Comment by yyoncho** [comment]
You should eval it in the JS buffer, not in the config buffer.

**Comment by dackon** [comment]
(lsp--xref-backend t)

**Comment by yyoncho** [comment]
I got it: `(define-key js-mode-map (kbd "M-.") nil)`, this should fix the issue. Not sure if we should have it in the sample config.

**Comment by dackon** [comment]
Emacs says there's no js-mode-map

**Comment by yyoncho** [comment]
Then maybe js2-mode-map? Do `C-h k M-.`.

**Comment by dackon** [comment]
Symbol's value as variable is void: js2-mode-map

C-h k M-. shows:

M-. runs the command js-find-symbol (found in js-mode-map), which is
an interactive compiled Lisp function in ‘js.el’.

It is bound to M-..

(js-find-symbol &optional ARG)

Read a JavaScript symbol and jump to it.
With a prefix argument, restrict symbols to those from the
current buffer.  Pushes a mark onto the tag ring just like
‘find-tag’.

**Comment by yyoncho** [comment]
if you want to run `(define-key js-mode-map (kbd "M-.") nil)` in your config it should be wrapped in `(with-eval-after-load js-mode ...`

**Comment by dackon** [comment]
Doesn't work.

```lisp
(with-eval-after-load 'js-mode
  (define-key js-mode-map (kbd "M-.") nil)
)

(with-eval-after-load 'js2-mode
  (define-key js2-mode-map (kbd "M-.") nil)
)
```

**Comment by yyoncho** [comment]
Sorry, it should be:

```
(with-eval-after-load 'js
  (define-key js-mode-map (kbd "M-.") nil)
)
```

**Comment by dackon** [comment]
Thank you, it works now.

**Comment by dackon** [comment]
Will this fix merge into lsp-mode?

**Comment by yyoncho** [comment]
It won't be part of lsp-mode but most likely a point the tutorial.

**Comment by dackon** [comment]
OK, thank you.

**Comment by bhurlow** [comment]
thanks for this!
