### ISSUE TITLE
Question : lsp-lua and autocompletion and love2d engine

### ISSUE THREAD

**Issue by deb75** [emacs-lsp/lsp-mode#2782]
Hello,

I cannot access [https://discord.gg/swuxy5AAgT](https://discord.gg/swuxy5AAgT) from where I am.

I build a game with the [love2d](https://love2d.orgl) engine.
The game is written in `lua` so I tried to use `emacs` with the [lua language server](https://github.com/sumneko/lua-language-server).

Here is an example of a "hello world" game : 
```lua
local love = require "love"

function love.draw()
   love.graphics.print("Hello World", 400, 300)
end
```
This "game" is run with the love engine : `love.exe directory\where\is\the\file`

The "require" line is not mandatory for the game to start, I put it because otherwise the lua language server
considers "love" as undefined. When I put it, I assume the lua language server picks up the "love.dll" which
is in the same directory as "love.exe".

However, autocompletion does not seem to work as for regular lua package. I noticed that I am only
proposed the "love" fields and functions which are already used in the script.

How can I improve this ?

Regars

**Comment by yyoncho** [comment]
It is hard to tell. To me this seems to be out of the lsp-mode's scope - it is lua language server spec.

**Comment by yyoncho** [comment]
marking the issue as closed, but you can use the issue for further question.

**Comment by deb75** [comment]
Thanks for your answeer.

You are right yes, I confounded the language server and the client, I will ask to [https://github.com/sumneko/lua-language-server](https://github.com/sumneko/lua-language-server)
