### ISSUE TITLE
Server settings per project

### ISSUE THREAD

**Issue by alanz** [emacs-lsp/lsp-mode#279]
For `lsp-haskell`, there is a custom variable giving the executable and parameters to be used when launching the server.

Because the server needs to match the compiler used in the project, this cannot actually be a global setting.

I am considering putting a mapping between project root and server settings.

Should this go into `lsp-haskell`, or `lsp-mode`?

See also  https://github.com/emacs-lsp/lsp-haskell/blob/master/lsp-haskell.el#L20 and https://github.com/haskell/haskell-ide-engine/issues/439

**Comment by phst** [comment]
Doesn't the `:command-fn` argument already support this?

**Comment by bkchr** [comment]
Yeah, for that `:command-fn` exists.

**Comment by alanz** [comment]
To explain the situation further, it is not necessarily easy to work out which version of the server to use from the filename / project dir.

So I want to allow the user to override it, and set it for a given project.

And the options seem to be

- store it in a config file read by the server, which is part of the server usage instructions.
  This has the advantage of working regardless of the LSP client in use. The `:command-fn` would then parse the file.
- store it in a `.projectile` file (if that is possible) and get the `:command-fn` to consult it.
- Add a new `defcustom` variable similar the the `whitelist`, which keeps this info.

And for the last option, the question really is whether is is then a `lsp-haskell` thing, or should go more generally into `lsp-mode`.

Sorry for the brain dump, this is still up for decision on the server side, I am trying to understand the options.

**Comment by bkchr** [comment]
I would not add more support for this into `lsp-mode`. I think the current solution works very well and opens a lot of possibilities for the clients, how they want to handle it. I would go with a config file that is read by the `:command-fn` to find the right server.

**Comment by gpittarelli** [comment]
I really like the idea of having this be easily overriden by users with `.projectile`, I've had that use case with eg flycheck -- sometimes you've just got a nonstandard setup where the `:command-fn` we might build into a client won't suffice.

A simple solution would be to have the `lsp-define-*-client` macros create a defcustom for the executable. This is what flycheck does in `flycheck-define-checker`: https://github.com/flycheck/flycheck/blob/b73ea4d9c25b4fbc17ed8250becf40c55e811231/flycheck.el#L6013 I can't think of a reason why a LSP client wouldn't want this.

**Comment by yyoncho** [comment]
Check https://github.com/emacs-lsp/lsp-mode/issues/405#issuecomment-447545817

**Comment by yyoncho** [comment]
Refer to https://github.com/emacs-lsp/lsp-mode/issues/405#issuecomment-449113404 . Now users could use dir locals for configuring project specific settings.
