### ISSUE TITLE
Ability to see overloaded methods - similar to eglot

### ISSUE THREAD

**Issue by CsBigDataHub** [emacs-lsp/lsp-mode#2792]
I have started using `lsp-mode` for `csharp-mode` via [omnisharp](https://github.com/OmniSharp/omnisharp-roslyn).

Eglot gives list of `overloads` via `eldoc-mode` when the cursor goes to open parentheses.

cursor at method gives method documentation in `eglot` similar to `lsp-mode`
![image](https://user-images.githubusercontent.com/23665525/115298707-6b3cb500-a123-11eb-9917-925fec59502c.png)

while cursor at open parentheses or inside the parentheses gives list of `overloads` with highlighted value you are using.
![image](https://user-images.githubusercontent.com/23665525/115298864-a50dbb80-a123-11eb-9a1d-30b004c15fea.png)

I was not able to get similar functionality with `lsp-mode`.  Is there a setting I need to enable?

**Comment by yyoncho** [comment]
It is available via signature help. Use C-S-SPC to force and then `M-n/p` to browse through the signatures.

**Comment by CsBigDataHub** [comment]
thanks for the quick reply @yyoncho.
