### ISSUE TITLE
`lsp-imenu` doesn't represent structure of html documents

### ISSUE THREAD

**Issue by JordanAnthonyKing** [emacs-lsp/lsp-mode#2798]
**Describe the bug**
Unlike with many other languages lsp-imenu doesn't organise items by their relative positions in the buffer, items are all listed with the same hierarchy.

`lsp-imenu-create-uncategorised-index`
![image](https://user-images.githubusercontent.com/58787893/115772129-4a33c880-a39e-11eb-8487-e8abf089d17f.png)

`lsp-imenu-create-categorised-index` does a bit better, but note how the structure is not truly representative of the document structure:
![image](https://user-images.githubusercontent.com/58787893/115772721-f9709f80-a39e-11eb-9bd1-464062294bae.png)
`kendo-toolbar` appears under `div.col-auto.ml-auto...` but then appears again at the root level with its own children.

The `lsp-imenu-create-categorised-index` behaviour is what I'd expect given its description, but `lsp-imenu-create-uncategorised-index` isn't.

Is this a limitation of the html-ls language server or imenu?

**To Reproduce**
- Enable lsp-imenu
- Create a simple html document, simply nesting a bunch of `<div>`s should be fine
- Run lsp-imenu

**Expected behavior**
Elements of the buffer to be arranged based on where they sit in the document hierarchy ala:
![image](https://user-images.githubusercontent.com/58787893/115775274-368a6100-a3a2-11eb-9218-73556b03e738.png)

**Which Language Server did you use**
I have `html-ls` and `angular-ls` active. `angular-ls` alone gives just the entire buffer as a single imenu entry.

Thanks

**Comment by yyoncho** [comment]
`lsp-imenu-create-categorised-index` - sorts the items by kind. 
`lsp-imenu-create-uncategorized-index` - will have the items sorted by position.

**Comment by JordanAnthonyKing** [comment]
> `lsp-imenu-create-uncategorized-index` - will have the items sorted by position.
It may sort them by _position_ but it doesn't sort them by _depth_ as it does for other languages.

**Comment by yyoncho** [comment]
![image](https://user-images.githubusercontent.com/13259670/116973423-30ab4e80-acc5-11eb-9a30-040670bd9638.png)

Everything seems to be fine for me.

**Comment by JordanAnthonyKing** [comment]
![image](https://user-images.githubusercontent.com/58787893/116974270-63e1e380-acad-11eb-998c-a4d47878eaaa.png)

Create a document with more than one level of depth. Items are listed with their immediate parent only.

**Comment by yyoncho** [comment]
This is caused by the fact that html language server is returning us flat structure with only the parent element. Building the whole tree is not possible because the elements might have  the same names(e. g. two div elements will have names). This is the old protocol - when html moves to the new version then all will work fine. Most likely #2286 will fix the issue.

**Comment by yyoncho** [comment]
I am marking the issue as closed since it seems like there is nothing we can do on lsp-mode side ATM.
