### ISSUE TITLE
Please use keyword rather than positional arguments for define-minor-mode

### ISSUE THREAD

**Issue by analyticd** [emacs-lsp/lsp-mode#2802]
I hesitate to classify this as a bug because it only affects users of more modern versions of Emacs as a warning, but is annoying nonetheless and easy to fix. I am on Emacs 28.0.5. According to the docs define-minor-mode has long tolerated positional arguments even though they were deprecated a while ago. But the latest versions of Emacs bark about this. I'd do a pull request but I am not sure what the positional arguments (all set to nil) map to in keywords as I can't seem to find docs for the old, now deprecated, define-minor-mode source. Sorry about that. Oh, and thanks for the awesome mode!

**Comment by yyoncho** [comment]
https://github.com/emacs-lsp/lsp-mode/pull/2793
