### ISSUE TITLE
Trying c++ modules with the latest gcc compiler

### ISSUE THREAD

**Issue by ram535** [emacs-lsp/lsp-mode#2803]
I build gcc-trunk `(12.0.0 20210422)` to try modules. I noticed that to
be able to use the std libraries in the form `import<iostream>;`, first
I have to generate the `gcm` file of the library.

To generate the gcm file of `iostream`, I did:
```
cd ~/bin/gcc-trunk/include/c++/12.0.0
g++ -x c++-system-header iostream
```
That gave me a warning but it generate the gcm file.
```
iostream:36:13: warning: #pragma system_header ignored outside include file
   36 | #pragma GCC system_header
      |             ^~~~~~~~~~~~~
```
Now if I compile this `g++ -fmodules-ts -std=c++20 main.cpp` file, everything work as expected.
```
import<iostream>;
int main() { std::cout << "hola"; }
```
# The problem
`lsp` is showing some error when there is not really an error.
I use `cland version 11.1.0` as the server.
This is the content of the `compile_commands.json` file.
```
[
  { "directory": "/home/last/Projects/cpp/bar", "file": "main.cpp",
    "output": "a.o",
    "arguments": ["/home/last/bin/gcc-trunk/bin/g++",
                  "main.cpp",
                  "-fmodules-ts",
                  "-std=c++2a",
                  "-Wall",
                  "-o",
                  "a.o",
                  "-c",
                  "--target=x86_64-unknown-linux-gnu"]}
]
```

 This is the error `lsp-mode` is showing int the buffer.
```
Header file <iostream> (aka '/home/last/bin/gcc-trunk/bin/../lib/gcc/x86_64-unknown-linux-gnu/12.0.0/../../../../include/c++/12.0.0/iostream') cannot be imported because it is not known to be a header unit [header_import_not_header_unit]
```

![image](https://user-images.githubusercontent.com/9011002/115924064-10150600-a434-11eb-8a8d-2205987091c9.png)

I am using the last  lsp. When I do (lsp-version), I get `package-desc-version: Wrong type argument: package-desc, nil`. I use `straight` to install lsp-mode.
`GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10) of 2020-03-09`

**Comment by yyoncho** [comment]
lsp-mode is showing the information returned by the server. To me, this report sounds like server-side issue/limitation. Am I missing something?

**Comment by ram535** [comment]
It seems like it. Probably is too early to be using this feature. They are not still completely implemented.
