### ISSUE TITLE
How to set lsp-lua-workspace-library

### ISSUE THREAD

**Issue by deb75** [emacs-lsp/lsp-mode#2818]
Hello,

I use the `lua-language-server`, I have some external libraries,
how can I add them through the `lsp-lua-workspace-library` variable ?

This variable is an association list if I am not mistaken, I tried to set it
with the emacs customization interface by adding ("/path/to/library", true)
as (key, value) but, on starting the language server issued an error parsing
some json settings.

I already asked on discord, but I cannot access it for now, so my apologies
if some of you already answered me there.

Regards

**Comment by yyoncho** [comment]
try `t` instead of `true`

**Comment by deb75** [comment]
Thanks for your help.

Do the path need to be quoted or not ? "d:/path/to/my/lib" or d:/path/to/my/lib ?

Could I set directly `lsp-lua-workspace-library` like this : 
```lisp
(setq lsp-lua-workspace-library (("d:/path/tomy/lib" . t)))
``` 

Regards

**Comment by yyoncho** [comment]
The easiest way is to use ht, something like `(ht ("path" t))`. It will work fine as long it is serializable to json object. Both emacs 26/27 have different requirements for that.

**Comment by deb75** [comment]
I set it like this : 
```lisp
(setq lsp-lua-workspace-library '(("c:/Users/xxx/.emacs.d/love-api" . t)))
```

No emacs errors on startup, but when launching the lsp lua server I get : 
```
Error processing message (wrong-type-argument symbolp "c:/Users/edebry/.emacs.d/love-api").
```

**Comment by yyoncho** [comment]
Sorry, but I already provided you with working example.

**Comment by deb75** [comment]
Yes, thank you

But I do not understand how to make use of your example : 
```lisp
(setq lsp-lua-workspace-library '((ht ("c:/Users/xxx/.emacs.d/love-api" . t))))
```

like this ?

**Comment by yyoncho** [comment]
`(setq lsp-lua-workspace-library (ht ("c:/Users/xxx/.emacs.d/love-api"  t)))`

**Comment by deb75** [comment]
It works !

Thanks

Should the documentation reflect that `lsp-lua-workspace-library` is not an association list but a hash-table ?

Regards

**Comment by yyoncho** [comment]
it can be anything that serializes to json object

**Comment by deb75** [comment]
Then, do you mean that the association list I wrote is not serializable ? or maybe the way I wrote it did not produce a serializable association list ?

Sorry for going on, I am just willing to undersdand how it works.
