### ISSUE TITLE
Unknown key: :test-id.  Available keys: (:type :time :test-ıd :result :skipped :hidden)

### ISSUE THREAD

**Issue by Zaryob** [emacs-lsp/lsp-mode#2819]
Before logging the bug, please make sure that:

1. You are using the latest version of `lsp-mode` related packages.
2. You may also try reproduce the issue using clean environment using the following command:
   ``` bash
   emacs -q -l lsp-start-plain.el
   ```
   where `lsp-start-plain.el` could be downloaded from `https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el`.
   Alternatively, in will be great if you can reproduce the issue using [lsp-docker](https://github.com/emacs-lsp/lsp-docker/) which provides the minimal configurations for `lsp-mode` and ships with most of the language servers.
3. Check FAQ and Troubleshooting section (https://emacs-lsp.github.io/lsp-mode/page/faq/ and https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/)
4. Consider providing a minimal project to reproduce the issue with. Note that `lsp-mode` supports 30+ languages and the maintainers of the project are not familiar with all of the languages and a sample project + full steps to reproduce will help a lot.

**Describe the bug**
After installing lsp-mode and connected packages, I get the following error from debug console when trying to initialize in a standard way.

```
[yas] Prepared just-in-time loading of snippets (but no snippets found).
Saving file /home/zaryob/.dotfiles/editors/emacs/init.el...
Wrote /home/zaryob/.dotfiles/editors/emacs/init.el
For information about GNU Emacs and the GNU system, type C-h C-a.
Eager macro-expansion failure: (error "Unknown key: :test-id.  Available keys: (:type :time :test-ıd :result :skipped :hidden)") [2 times]
File mode specification error: (error Unknown key: :test-id.  Available keys: (:type :time :test-ıd :result :skipped :hidden))
```

It also happen some sort of lsp- commands for example I tried `lsp-org` it gives same error.
**To Reproduce**
Steps to reproduce the behavior(sample project + file which can be used to reproduce the issue with.)

I used my dotfiles https://github.com/Zaryob/dotfiles
I create my own emacs config https://github.com/Zaryob/dotfiles/blob/main/editors/emacs/init.el
I tried to made a fresh install several times it gets some error like that
```
Eager macro-expansion failure: (error "Unknown key: :test-id.  Available keys: (:type :time :test-ıd :result :skipped :hidden)") [2 times]
File mode specification error: (error Unknown key: :test-id.  Available keys: (:type :time :test-ıd :result :skipped :hidden))
Error (use-package): dap-mode/:catch: Unknown key: :test-id.  Available keys: (:type :time :test-ıd :result :skipped :hidden)
Emergency (url): Unknown proxy directive: DIRECT [8 times]
Error (use-package): Failed to install dap-dart: Package ‘dap-dart-’ is unavailable
Error (use-package): Cannot load dap-dart
```
**Expected behavior**
I'm trying to use dap-mode or some features of lsp-mode, some of commands not working and giving error like top.

**Which Language Server did you use**
Mention which server/language did you use (e. g. lsp-python, lsp-ccls, lsp-java, etc)
`lsp-dart`

**OS**
Which os do you use?
`RedHat Enterprise Linux 8.3`

**Version**
I install emacs from snap.
```emacs --version
GNU Emacs 27.2
Copyright (C) 2021 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

**Error callstack**
If there is an error please reproduce the issue with `toggle-debug-on-error` and after setting `lsp-print-io` to t, and then include the callstack and attach the content of `*lsp-log*` buffer and the content of the server log(use `lsp-workspace-show-log`)

If `emacs` hangs please do `M-x` `toggle-debug-on-quit` and then do `C-g` when emacs hangs and include the callstack as part of the issue report.

``` emacs-lisp
(setq lsp-print-io t)
```

**Comment by flodiebold** [comment]
Looks like something is lower-casing with locale...

**Comment by yyoncho** [comment]
> Looks like something is lower-casing with locale...

yes. 

@Zaryob what do you get when you do `(downcase "ID")`?

**Comment by Zaryob** [comment]
> > Looks like something is lower-casing with locale...
> 
> yes.
> 
> @Zaryob what do you get when you do `M-: (downcase "ID") RET`?

Output:
"1d"

**Comment by yyoncho** [comment]
Hi @eli-zaretskii  - what is the right way to `downcase` a string compile time ignoring the locale(I assume that @Zaryob result is affected by the locale)? Thank you.

**Comment by Eli-Zaretskii** [comment]
What do you mean by "compile time" in this case?

In any case, it isn't the locale that matters in Emacs, it's the language environment.

`downcase` uses the buffer's current case table by default.  If you want it to use any other case table, use `with-case-table`.  For example,

           (with-case-table ascii-case-table
             (downcase "ID"))

I'm not sure `ascii-case-table` is right here: isn't there a possibility that some string will be non-ASCII?  If so, maybe you should use `standard-case-table` instead.

**Comment by Zaryob** [comment]
> What do you mean by "compile time" in this case?
> 
> In any case, it isn't the locale that matters in Emacs, it's the language environment.
> 
> `downcase` uses the buffer's current case table by default. If you want it to use any other case table, use `with-case-table`. For example,
> 
> ```
>        (with-case-table ascii-case-table
>          (downcase "ID"))
> ```
> 
> I'm not sure `ascii-case-table` is right here: isn't there a possibility that some string will be non-ASCII? If so, maybe you should use `standard-case-table` instead.

As you know, from initialization newly installed emacs, it gets all archives and compiles them to make it compatible with emacs. I tried to say this. And also I'm gonna try this way as soon as possible. I also looking for change locale for just emacs.

**Comment by yyoncho** [comment]
> What do you mean by "compile time" in this case?

I just mentioned that we use downcase in a macro in case that matters.

> `downcase` uses the buffer's current case table by default. If you want it to use any other case table, use `with-case-table`. For example,
> 
> ```
>        (with-case-table ascii-case-table
>          (downcase "ID"))
> ```
> 
> I'm not sure `ascii-case-table` is right here: isn't there a possibility that some string will be non-ASCII? If so, maybe you should use `standard-case-table` instead.

`ascii-case-table` should be good.

@Zaryob I will prepare a PR.

**Comment by Zaryob** [comment]
> > What do you mean by "compile time" in this case?
> 
> I just mentioned that we use downcase in a macro in case that matters.
> 
> > `downcase` uses the buffer's current case table by default. If you want it to use any other case table, use `with-case-table`. For example,
> > ```
> >        (with-case-table ascii-case-table
> >          (downcase "ID"))
> > ```
> > 
> > 
> > I'm not sure `ascii-case-table` is right here: isn't there a possibility that some string will be non-ASCII? If so, maybe you should use `standard-case-table` instead.
> 
> `ascii-case-table` should be good.
> 
> @Zaryob I will prepare a PR.

Ok waiting for the PR. Bests,

**Comment by Zaryob** [comment]
Also note for that. I wanna mention guys thank you @Eli-Zaretskii  @yyoncho @gnufied I fixed issue with adding this into top of my init.el file

```
(set-language-environment "English")
(set-locale-environment "en.UTF-8")
(prefer-coding-system 'utf-8)
```

@yyoncho you can also open a PR for fix that issue. I think it would be much more useful to do it on the basis of the `lsp-mode` package, but I leave this method here because there are people who have lived before.

I will leave issue open for you to specify this issue on the PR.

**Comment by yyoncho** [comment]
PR at #2820
