### ISSUE TITLE
Consider disable features manual

### ISSUE THREAD

**Issue by Qquanwei** [emacs-lsp/lsp-mode#282]
Looks like I dont't like symbol highlight feature. Can I disable this feature manually？

**Comment by sebastiencs** [comment]
Yes: `(setq lsp-highlight-symbol-at-point nil)`

You can do `M-x customize-group [RET] lsp-mode [RET]` to customize how `lsp-mode` behave

**Comment by Qquanwei** [comment]
@sebastiencs Thanks
