### ISSUE TITLE
better lsp-mode performance documentation on large java project.

### ISSUE THREAD

**Issue by wenhoujx** [emacs-lsp/lsp-mode#2824]
In the past week i switched between `lsp-mode` and `eglot` multiple time to try out emacs dev on a java project ~10k classes. 

I really really want to use `lsp-mode` for the full set of features. but for some reasons it's just slow for me , i ran `lsp-doctor` and got full green checkmarks (I use gccemacs and spacemacs) 

finally this morning i realize why not bump my jdt server heap size and it fixes all my slowness issues with `lsp-mode`. I wish this is mentioned here: https://emacs-lsp.github.io/lsp-mode/page/performance/  or somewhere else. 

```
(setq lsp-java-vmargs '("-noverify" "-Xmx2G" "-XX:+UseG1GC" "-XX:+UseStringDeduplication"))
```
I know it's pointed out here: https://github.com/emacs-lsp/lsp-java#supported-settings but i wish it's better highlighted in the performance doc. 

The things i don't understand is, why is eglot performance bearable with 1G jdt server. I think @yyoncho  claimed that the refactored lsp-mode and eglot are both lightweight and defer the heavy lifting to the language server. 

anyways, I don't want to start another thread of arguments of which is better, i am very happy with lsp-mode now. 

good job team! 

happy to contribute to the doc or readme if someone can points me to the right place.

**Comment by ericdallo** [comment]
About the docs, we could probably add in https://emacs-lsp.github.io/lsp-java/ in a performance section there or something

**Comment by yyoncho** [comment]
@wenhoujx in general, lsp-mode puts more pressure on the server(because it has implemented more features especially for lsp-java). In your case, it seems like the server is having perf issues, not the client, at least this is my conclusion based on the issue description.

IMHO, the following line will result in better performance of the server. 
```
  (setq lsp-java-completion-max-results 10)
```

> I wish this is mentioned here: https://emacs-lsp.github.io/lsp-mode/page/performance/ or somewhere else.

Seems like lsp-java's FAQ section is a good fit - https://github.com/emacs-lsp/lsp-java/blob/master/README.md .

**Comment by yyoncho** [comment]
https://github.com/redhat-developer/vscode-java/blob/master/package.json#L156 here are the vscode defaults(set by the server maintainers). I guess we should unify lsp-java settings.

**Comment by wenhoujx** [comment]
https://github.com/emacs-lsp/lsp-java/pull/326 PR here.

**Comment by wenhoujx** [comment]
and another one for the unified vmargs as vscode: https://github.com/emacs-lsp/lsp-java/pull/327

**Comment by yyoncho** [comment]
Thank you, I merged both PRs.

**Comment by wenhoujx** [comment]
thanks!
