### ISSUE TITLE
yaml-mode missing from `lsp--formatting-indent-alist`

### ISSUE THREAD

**Issue by Cerebus** [emacs-lsp/lsp-mode#2828]
Add `(yaml-mode . yaml-indent-offset)` to this list.

https://github.com/emacs-lsp/lsp-mode/blob/7e8567a810e53056d46a474b308cd1bc0a2fe04f/lsp-mode.el#L5300

**Comment by kiennq** [comment]
Nice, I'm not using `yaml-ls` when creating this table so the entry is missing.
Can you turn this into a PR?
