### ISSUE TITLE
Snippet placecholder problems

### ISSUE THREAD

**Issue by kuator** [emacs-lsp/lsp-mode#2831]
I am following the emacs-lsp tutorial on c++: https://emacs-lsp.github.io/lsp-mode/tutorials/CPP-guide/
My init.el is identical to one in the tutorial. The only difference is: `(setq lsp-enable-snippet t)`.
The problem is: snippet placeholder doens't get removed
![Peek 2021-05-03 14-38](https://user-images.githubusercontent.com/25168308/116856584-38171d00-ac1d-11eb-981f-54b2b23f8fbb.gif)

**Comment by yyoncho** [comment]
Seems like yasnippet issue with 0 placeholder - it is not replaced. 

Adding the following snippet to your config will patch the issue:
``` emacs-lisp
(with-eval-after-load 'lsp-mode
  (defun lsp--to-yasnippet-snippet (snippet)
    "Convert LSP SNIPPET to yasnippet snippet."
    ;; LSP snippet doesn't escape "{" and "`", but yasnippet requires escaping it.
    (replace-regexp-in-string
     "{0.+}"
     "{0}"
     (replace-regexp-in-string (rx (or bos (not (any "$" "\\"))) (group (or "{" "`")))
                               (rx "\\" (backref 1))
                               snippet
                               nil nil 1))))
```

**Comment by kuator** [comment]
Thank you for the fix and all the amazing job! It's amazing how much little config it's needed for an ide-like experience in emacs!
