### ISSUE TITLE
Tidy up lsp-rust.md documentation

### ISSUE THREAD

**Issue by petr-tik** [emacs-lsp/lsp-mode#2848]
Checked the rust doc page 
https://emacs-lsp.github.io/lsp-mode/page/lsp-rust/
after my PR got merged 
#2776 

Three things stood out:

1. The gifs that I added aren't rendered 
https://github.com/emacs-lsp/lsp-mode/pull/2776/files?file-filters%5B%5D=.gif

I placed my gifs in docs/manual-language-docs, while all other media lives in top-level examples/

2. The server section still defaults to RLS
https://emacs-lsp.github.io/lsp-mode/page/lsp-rust/#server

Though rust-analyzer has yet to become the official LSP server for rust, it's already widely used and is the recommended server. lsp-mode documentation should reflect that and be consistent with the default config. 

3. The RLS section is above rust-analyzer
https://emacs-lsp.github.io/lsp-mode/page/lsp-rust/#rls

Same as above it's worth placing the now default rust-analyzer above rls in the docs.

**Comment by ericdallo** [comment]
Would you mind correcting the gif folder and lsp-clients.json to fix those things?
