### ISSUE TITLE
Empty completion after space

### ISSUE THREAD

**Issue by gexplorer** [emacs-lsp/lsp-mode#2857]
If **space** is among a servers **triggerCharacters** for completion, it does not return any results after a **space**.

This happens because `lsp-completion--get-context` returns `CompletionTriggerKind = 2` when completion is invoked manually but the previous character is one of **triggerCharacters**.

## Steps to Reproduce

See [example project](https://github.com/gexplorer/veturpack)

* Inside a **vue** file

### Failed completion

* Try completion with cursor separated one **space** from the curly bracket:
```js
import { | } from 'vue';
```
* The request is:
```json
Params: {
  "textDocument": {
    "uri": "file:///Users/eder/Projects/veturpack/src/Test.vue"
  },
  "position": {
    "line": 7,
    "character": 9
  },
  "context": {
    "triggerKind": 2,
    "triggerCharacter": " "
  }
}
```
* It won't return results

### Correct completion

* Try completion with cursor right after the curly bracket
```js
import {|  } from 'vue';
```
* The request is:
```json
Params: {
  "textDocument": {
    "uri": "file:///Users/eder/Projects/veturpack/src/Test.vue"
  },
  "position": {
    "line": 7,
    "character": 8
  },
  "context": {
    "triggerKind": 1
  }
}
```
* It returns the expected candidates

## Expected behavior
Completing after a space should yield the same results as right after the bracket. When completion is triggered manually the `CompletionTriggerKind` parameter sent to the server should be 1, regardless of the previous character.

## Which Language Server did you use
I encountered the problem with the **lsp-vetur** server which has **space** as a trigger character for completion.

## OS
macOS

**Comment by kiennq** [comment]
Let me see, perhaps in the case of triggered by trigger characters, we can set some variable to distinguish that

**Comment by gexplorer** [comment]
I found a possible solution and I've been using it for a few hours without any problems.

Basically before looking back for trigger characters I check that the last executed command has been `self-insert-command` which AFAIK means that the user has inserted a char.

```elisp
(defun lsp-completion--get-context (trigger-characters)
  "Get completion context with provided TRIGGER-CHARACTERS."
  (let* ((triggered-by-char (equal last-command 'self-insert-command))
         (trigger-char (if triggered-by-char
                           (lsp-completion--looking-back-trigger-characterp
                            trigger-characters)))
         (trigger-kind (cond
                        (trigger-char
                         lsp/completion-trigger-kind-trigger-character)
                        ((equal (cl-second lsp-completion--cache) :incomplete)
                         lsp/completion-trigger-kind-trigger-for-incomplete-completions)
                        (t lsp/completion-trigger-kind-invoked))))
    (apply #'lsp-make-completion-context
           (nconc
            `(:trigger-kind ,trigger-kind)
            (when trigger-char
              `(:trigger-character? ,trigger-char))))))
```

I also created some tests to make sure it worked (I used **el-mock** to be able to mock `x`):
```elisp
(ert-deftest lsp-completion-test-get-context ()
  (cl-labels ((do-test (command)
                       (let ((last-command command))
                         (hash-table-values (lsp-completion--get-context '("_"))))))
    (mocklet ((lsp-completion--looking-back-trigger-characterp))
      (should (equal (do-test 'next-line) '(1)))
      (should (equal (do-test 'self-insert-command) '(1))))
    (mocklet ((lsp-completion--looking-back-trigger-characterp => "_"))
      (should (equal (do-test 'next-line) '(1)))
      (should (equal (do-test 'self-insert-command) '(2 "_"))))))
```

**Comment by kiennq** [comment]
It's indeed a possible solution, can you submit a PR for it?

**Comment by gexplorer** [comment]
I just opened a PR #2864

**Comment by yyoncho** [comment]
This one can be closed, right?
