### ISSUE TITLE
LSP over TRAMP fails with `File mode specification error`

### ISSUE THREAD

**Issue by zilti** [emacs-lsp/lsp-mode#2860]
I updated lsp-mode today to the latest git release. I am now getting the following error when trying to use LSP over TRAMP:

`File mode specification error: (wrong-type-argument characterp stty)`

This only happens for remote connections, the normal local LSP stuff works as expected. This also happens no matter the LSP server, I tried with both a PHP file (Intelephense) and an SQL file (sqls).

**Comment by yyoncho** [comment]
PR at #2861
