### ISSUE TITLE
Add support for beancount

### ISSUE THREAD

**Issue by wangkev** [emacs-lsp/lsp-mode#2863]
There exists a [language server](https://github.com/polarmutex/beancount-language-server) for beancount, can we please add support for it in `lsp-mode`?

This was also discussed https://github.com/hlissner/doom-emacs/issues/5035#issuecomment-839161479.

**Comment by jcs090218** [comment]
The fastest way to get this to lsp-mode is to open a PR for this. I believed the community would love to see this implemented.

**Comment by jcs090218** [comment]
@wangkev We have implemented the basic support for beancount language server, see #2926.

Close this now! Thanks!

**Comment by wangkev** [comment]
Thanks!
