### ISSUE TITLE
is there a lsp-find-workspace-symbol waits me finish the query string before request language server? 

### ISSUE THREAD

**Issue by wenhoujx** [emacs-lsp/lsp-mode#2865]
hello, I am using lsp-mode with lsp-java, things works well in general. My biggest headache is `lsp-ivy-workspace-symbol` is super slow on my big java project, 2000 java files, and maybe millions of lib class :( 
Is there a command that allows me to finish typing as much as i remember then send to the language server backend for results? 

The ivy approach seems to start searching after i type just two letters. 

please close if this is not the best place to ask. I am sorry but my current working laptop blocks the discord site.

**Comment by kiennq** [comment]
Currently `lsp-ivy` is using async request for that, so unless your machine spec only allows one thread, this should not blocking your typing.
About `lsp-ivy`, can you try with https://github.com/kiennq/lsp-ivy? This fork contains a fix that will automatically cancel the request with new key type, hoping that will unload the server processing load too.

**Comment by yyoncho** [comment]
To answer your original question there are `xref-find-apropos` and `lsp-ido-workspace-symbol`. Also, after trying @kiennq  can you test if helm-lsp is working fine? And if it is not can you provide perf report?

**Comment by wenhoujx** [comment]
sure thing, will try this weekend.

**Comment by wenhoujx** [comment]
@kiennq  do know how can i check if my machine spec is only allowing one thread for emacs? this is a ubuntu VM i am running in aws.

**Comment by kiennq** [comment]
> @kiennq do know how can i check if my machine spec is only allowing one thread for emacs? this is a ubuntu VM i am running in aws.

Sorry, I should use more correct wording here, you can run `nproc` to see how many processors in your VM.
If your codebase is huge and the server process is doing work with all of the machine processors, Emacs will be slow.

**Comment by wenhoujx** [comment]
nproc == 16, i suspect this is there are other heavy processes going on, i turned this box into my gccemacs boot loader. I gues other thing running at jdtls server which i give 4g out of 64G total .

**Comment by yyoncho** [comment]
Here is https://emacs-lsp.github.io/lsp-mode/page/performance/ guide.

Marking the issue as resolved because the original question was answered. If you think that there is perf issue, please report another issue providing the information as described in the link above. (also test with helm-lsp which is optimized and based on my test it works even with huge testing).

**Comment by wenhoujx** [comment]
```
(package! lsp-ivy
  :recipe (:host github :repo "kiennq/lsp-ivy") :pin "e759d94")
```

tested with this, the UX is better, b/c i can keep typing and it get stuck less often, I worry if this mean my jdt server is getting spamming? or is it truly cancelling those previous requests? 

i think i will keep use this commit for a while and report back if there is something wrong. 

@kiennq

**Comment by kiennq** [comment]
The PR for this commit in `lsp-ivy` is here https://github.com/emacs-lsp/lsp-ivy/pull/33
