### ISSUE TITLE
Possible to change location of function warning in eslint ?

### ISSUE THREAD

**Issue by vikigenius** [emacs-lsp/lsp-mode#2869]
![scrot_20210517_020357](https://user-images.githubusercontent.com/12724810/118439573-3dac4280-b6b4-11eb-874f-b1ef16b53c70.png)

If you take a look at the function definition for `onKeyPressEscape` in the screenshot above, you can see that there is actually a warning there, on the right side margin.  I actually missed it first time around and only noticed when building produced a warning.

Is it possible to change the appearance of that warning highlight on the left side ?

**Comment by yyoncho** [comment]
lsp-mode does not display the errors we only report them to flycheck/flymake. Thus, refer to flycheck docs.
