### ISSUE TITLE
Conceptual overview missing

### ISSUE THREAD

**Issue by phst** [emacs-lsp/lsp-mode#287]
The concepts "workspace" and "client" are fundamental for `lsp-mode`, but not well documented. There should be precise and exhaustive documentation about the fundamental abstractions that these types provide, their relationship with buffers and server processes, etc.

**Comment by phst** [comment]
I actually don't quite understand the difference between workspace and client myself. It seems there's one server process per workspace, and one client per buffer, but then there's more than one buffer per workspace, so that doesn't make much sense. How about merging the two structures into a single structure?

**Comment by alanz** [comment]
I am coming to the conclusion that they should be merged, as I think a workspace always has exactly one client.

**Comment by alanz** [comment]
Except I think we *do* need both.

The `client` is the template constructed by calling `lsp-define-stdio-client` (or `lsp-define-tcp-client`) and captures the specific features related to a given language server.

The `workspace` captures the specific instance of a running language server, started up by using the relevant `client` template.

So if you open up two different haskell projects (as determined by the `get-root` function of the client), then each will have its own `workspace`, but there is still only one haskell `client`. Or one way of constructing one, as created in the `lsp-define-xxx-client` macro.

**Comment by alanz** [comment]
I am happy with either of those approaches.

**Comment by phst** [comment]
I think your suggestion is cleaner because it clearly separates the portions relating to a single server process from the "workspace factory" code. I'll send a PR.

**Comment by MaskRay** [comment]
One workspace can have multiple clients for different languages. See https://github.com/emacs-lsp/lsp-mode/issues/335

**Comment by yyoncho** [comment]
The documentation was extended in 7c55ba55af5c5e061285993c952074cbc52bfa67 (e. g. https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el#L610) please reopen if you think that  it is not enough.
