### ISSUE TITLE
No clear, discoverable option via defcustom for disabling server auto-install

### ISSUE THREAD

**Issue by TLATER** [emacs-lsp/lsp-mode#2879]
**Describe the bug**

A previous PR tried to address this (#1620) but it was shot down because it can be hacked around by changing private things in lsp-mode. This was also not documented anywhere besides in that PR. I don't think that's a desirable solution, and I don't imagine it will continue to work as long as it's undocumented private API.

Let me describe why I think this is a problem that deserves a bit more than a private hack:

---

Whenever I open a file that I have enabled lsp for (because I do sometimes write projects in the language, i.e. anything that launches `sh-mode`), but doesn't require a language server in that instance, I am asked which language server I want to automatically install.

Though it's nice that this usually fails to work anyway because I rarely have `npm` on my path, I never want it to happen in the first place; yet there is seemingly no way to say "no thanks" (though this may be due to helm), and no way to disable the prompt in the future (or globally).

This is also problematic when offline, or behind a restrictive firewall, because it will prompt to install and just fail. I don't even want to think about how this affects users on a metered connection, or in an organization that will escalate incidents of un-permitted download attempts.

If I want to use a language server, I will install it using my distro package manager that will ensure updates, or through the project package manager that respects its lockfile. Not uncontrollably to a directory in `~/.config/emacs`. This is exacerbated when using [NixOS](https://nixos.org/), where language servers are only on `$PATH` in specific project directories of my choosing, turning almost every file type I open that happens to sometimes be part of a project into an annoyance.

---

Sorry for the slightly ranty report. If it's any excuse, I just spent 10 minutes tapping enter and waiting for a failure while `desktop-mode` opened a bunch of disparate shell scripts while starting Emacs, so I'm possibly not as concise as I should be.

The feature is probably really cool if you don't care too much where, when and how software is installed, but I think being unable to disable it is a big oversight that isn't taken as seriously as it should.

I absolutely love this package otherwise, it makes it really easy to get good dev environments to work, so I feel somewhat guilty bringing this up in this way. Thanks for all the effort!

**To Reproduce**

Open any file that lsp is enabled for without having a server installed and be annoyed.

**Expected behavior**

This is about a missing feature in a way? A configuration option to always disable installation should be present.

**Which Language Server did you use**

The language in question in this particular case was bash, but no language server was used (since it can't be installed without `npm`).

**OS**

NixOS 20.09 (Nightingale)

**Error callstack**

N/A, this is a UX bug.

**Comment by TLATER** [comment]
I'll need to look more closely, but I *think* I should want `lsp-client-packages`, it just doesn't seem to do what I want it to do (which may be a configuration problem? Setting it to `nil` doesn't seem to change anything...).

**Comment by yyoncho** [comment]
`lsp-client-packages` should be set before the first time you call lsp - if you don't do that - lsp-mode will load the clients.

**Comment by TLATER** [comment]
So, in `use-package` terms:

```elisp
(use-package lsp-mode
  :hook ((sh-mode) . lsp)
  :init
  ;; Disable auto-install
  (setq lsp-client-packages nil))
```

That's what I tried when `setq`-ing failed, but no change even after a restart.

**Comment by yyoncho** [comment]
I misread the initial bug report, PR at #2882

**Comment by TLATER** [comment]
Another point is that _maybe_ the prompt shouldn't be repeated within a single emacs session; after saying no once I don't think I'll change my mind anytime soon, certainly not within less than a second.

But these are separate issues, I'll personally just disable it altogether when the next release hits. Thanks for resolving so quickly!

**Comment by michaelpj** [comment]
I would also like a `defcustom` for this, and I don't really understand why we wouldn't want one? It's a knob that's reasonable for a user to want to twiddle, and we don't *normally* say "oh you want to customize this, just mess with an internal function". There are any number of `defcustom`s we could remove in favour of FAQ entries saying "override this internal function with this blob of elisp". But that's not exactly good UX. 

Quite apart from anything else, `defcustom`s are _discoverable_, right from in Emacs itself. We wouldn't need that FAQ entry at all!

**Comment by yyoncho** [comment]
@michaelpj - we don't "override this internal function with this blob of elisp", the functions are public. The reason for not having a defcustom setting is because it is not yes/no setting and having this workflow achieved using lsp-mode API fits naturally and in order to keep the defcustoms manageable. After all, we cannot have a defcustom for every single permutation - if we have a thousand lsp-mode defcustoms they won't be discoverable for sure.

**Comment by yyoncho** [comment]
@TLATER 

> Another point is that _maybe_ the prompt shouldn't be repeated within a single emacs session; after saying no once I don't think I'll change my mind anytime soon, certainly not within less than a second.

I can see how this is useful for your setup, but typically, if you don't want to install a particular server you don't run `lsp` at all.

**Comment by unhammer** [comment]
> typically, if you don't want to install a particular server you don't run lsp at all.

I like lsp, and use it all the time in projects that I work on over time, but I also open a lot of projects "temporarily" for quick edits where I don't want to be bugged about installation for each file I open. There could be many reasons one wouldn't want to install a server for a certain project; maybe in one we use flow and another uses some typescript thing while in a third project I don't want lsp at all (but I don't want to install a dir-local "turn-off-lsp-for-this-project" for every random thing I clone); for haskell we need a different server per ghc version. Major modes where you don't want lsp may derive from major modes where you do (eg. json-mode). And the dired-query-replace example is reason enough for me to adopt a policy of simply never prompting on opening files.

However, how about just changing the prompt to a clickable overlay like what lsp-ui-sideline uses? No need for defcustoms or "remember answer" or even faq entries, just an overlay saying "Install LSP server for this language | Dismiss" and it goes away on click (and if you click the part before the | it starts installing). WDYT?

**Comment by michaelpj** [comment]
> The reason for not having a defcustom setting is because it is not yes/no setting

How about just "enable automatic installation of servers" yes or no? I think that serves most people's usecases, since `lsp-install-server` exists for manual use.

I suspect most of the people who care about this setting are of the opinion that they *never* want automatic installation and they'l manage it themselves. That's my desire, and it seems to match the other people in this thread.

> I can see how this is useful for your setup, but typically, if you don't want to install a particular server you don't run lsp at all.

I use spacemacs, and have LSP enabled globally because that's how it works, so I end up with it enabled for JSON files which I open very rarely to edit a random value, and then have to fight with the automatic server installation dialog. Yes, I could figure out how to turn off LSP for JSON. But given that I never want automatic installation, I'd rather just turn that of.

**Comment by yyoncho** [comment]
> How about just "enable automatic installation of servers" yes or no? I think that serves most people's usecases, since `lsp-install-server` exists for manual use.

99.9% of the use-cases are covered by https://github.com/emacs-lsp/lsp-mode/issues/2879#issuecomment-846057524 . If you can disable all clients at all and prevent them from asking for automatic installation, why do you need an explicit setting to disable automatic installation? @TLATER's case is a corner case and IMHO it does not justify a separate setting and increasing the complexity of the code.

**Comment by michaelpj** [comment]
> If you can disable all clients at all and prevent them from asking for automatic installation, why do you need an explicit setting to disable automatic installation?

It's not discoverable. First thing I would do is go to `customize-group 'lsp-mode`, eventually maybe I'd find the FAQ. Also, I might want the client! I just don't want `lsp-mode` to ever manage installed servers.

Turn it around: why have, say, `lsp-display-inline-image` when one could just override `lsp--display-inline-image`? I get the desire to not have lots of options, but I don't see why you don't want this one when we have plenty of other similar ones!

**Comment by yyoncho** [comment]
> It's not discoverable. First thing I would do is go to customize-group 'lsp-mode, eventually maybe I'd find the FAQ. Also, I might want the client! I just don't want lsp-mode to ever manage installed servers.

lsp-disabled/enabled-clients are discoverable so you will be able to do what you want from M-x customize-group. (lsp-enabled-clients should be changed to defcustom from defvar).

> Turn it around: why have, say, lsp-display-inline-image when one could just override lsp--display-inline-image? 

On the other side, we don't need defcustom for any config that the user might want as long as it is possible to achieve it using public functions from lsp-mode. 

> I get the desire to not have lots of options, but I don't see why you don't want this one when we have plenty of other similar ones!

I want to remove a lot of the defcustoms that we currently have but I can't because it will be breaking change.

**Comment by michaelpj** [comment]
> I want to remove a lot of the defcustoms that we currently have but I can't because it will be breaking change.

Okay, fair enough, then this makes sense. Not the direction I would personally go in but okay!

**Comment by yyoncho** [comment]
@michaelpj 

> This is feeling a little bit Rube-Goldberg-y sweat_smile Would it really not be simpler to just have an option?

Added in https://github.com/emacs-lsp/lsp-mode/pull/3230

**Comment by michaelpj** [comment]
Thank you!
