### ISSUE TITLE
LSP-mode unexpectedly triggers Webpack recompilation

### ISSUE THREAD

**Issue by tmythicator** [emacs-lsp/lsp-mode#2888]
It appears to me, that each time I type anything in any  file in webpack-project (Typescript/Javascript) without saving the changes, lsp-mode triggers recompilation, as if something was changed in project. However, it doesn't trigger anything if the lsp-mode is deactivated. 
Could it be the code-actions, that trigger it?
Is there anything that can contribute to such undesirable behavior and what are the ways to avoid this?

In order to ensure, that it doesn't have to do with lock or backup-files, I put following in my config:
`(setq make-backup-files nil)
(setq create-lock-files nil)`

lsp-version: 20120521.446, Emacs 27.2, darwin

Webpack and watch options: https://webpack.js.org/configuration/watch/

**Comment by yyoncho** [comment]
If webpack build is triggered by saved file, then my guess is that it is triggered by the server log which is stored in .log folder in the root of the project. Lsp-mode does not touch the files on the disk when typing. There is command line argument --tsserver-log-file which you can set using lsp-clients-typescript-server-args

**Comment by tmythicator** [comment]
Thanks for the answer, that looks like to be the case!
