### ISSUE TITLE
There are no active servers in the current buffer

### ISSUE THREAD

**Issue by guyuming76** [emacs-lsp/lsp-mode#2889]
Please ask your questions at https://discord.gg/swuxy5AAgT

i cannot open the link above.

i can enable lsp-mode in emacs, but it is not connected to clangd;

if i choose session -> restart, i can see error message "There are no active servers in the current buffer"

guyuming@gymGentoo ~/minidbg $ which clangd
/usr/lib/llvm/11/bin/clangd

and the path is included in M-x getenv PATH

how to troubleshoot?

lsp-diagnose returns what follows:
Checking for Native JSON support: OK
Check emacs supports `read-process-output-max': OK
Check `read-process-output-max' default has been changed from 4k: OK
Byte compiled against Native JSON (recompile lsp-mode if failing when Native JSON available): OK
`gc-cons-threshold' increased?: OK
Using gccemacs with emacs lisp native compilation (https://akrl.sdf.org/gccemacs.html): NOT AVAILABLE (OPTIONAL)

**Comment by yyoncho** [comment]
The proper way to start lsp-mode is using `M-x lsp` not `M-x lsp-mode`

**Comment by guyuming76** [comment]
> The proper way to start a connection is using `M-x lsp` not `M-x lsp-mode`

Thanks! it works!
