### ISSUE TITLE
(lsp-install-server t 'rust-analyzer) write "Not Found"

### ISSUE THREAD

**Issue by ncaq** [emacs-lsp/lsp-mode#2890]
**Describe the bug**

`lsp-install-server` uncheck http status code.
So rust-analyzer file body is `Not Found`

**To Reproduce**

~~~elisp
ELISP> (require 'lsp-mode)
lsp-mode
ELISP> (lsp-install-server t 'rust-analyzer)
(:download :url lsp-rust-analyzer-download-url :store-path lsp-rust-analyzer-store-path :set-executable\? t)

ELISP> (with-temp-buffer (find-file  "~/.emacs.d/.cache/lsp/rust/rust-analyzer") (buffer-string))
"Not Found"
~~~

`*Messages*` buffer below.

~~~console
LSP :: Download rust-analyzer started.
LSP :: Starting to download https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-linux to /home/ncaq/.emacs.d/.cache/lsp/rust/rust-analyzer...
Contacting host: github.com:443
Wrote /home/ncaq/.emacs.d/.cache/lsp/rust/rust-analyzer
LSP :: Finished downloading /home/ncaq/.emacs.d/.cache/lsp/rust/rust-analyzer...
LSP :: Server rust-analyzer downloaded, auto-starting in 0 buffers.
~~~

**Expected behavior**

The install sucessed for rust-analyzer OR install failed.

**Which Language Server did you use**
lsp-rust

**OS**
2021-05-26T19:24:45 ❯ uname -a
Linux strawberry 5.10.27-gentoo #2 SMP Thu May 6 16:48:42 JST 2021 x86_64 AMD Ryzen Threadripper 1950X 16-Core Processor AuthenticAMD GNU/Linux

**Misc**

I actually tried to open the Pull Request, but I didn't have the muscle to read and understand the macro.
I apologize for that.

**Comment by flodiebold** [comment]
rust-analyzer has dropped the uncompressed binary releases. I actually wasn't aware that lsp-mode was downloading those.

**Comment by yyoncho** [comment]
already fixed by @kiennq
