### ISSUE TITLE
[Github] support yml issue templates

### ISSUE THREAD

**Issue by ericdallo** [emacs-lsp/lsp-mode#2895]
For some reason the yml issue templates are not working on this repo.

Maybe @lukehefson can help us here?

I followed [github documentation](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) and [gitpod issue template](https://github.com/gitpod-io/gitpod/tree/main/.github/ISSUE_TEMPLATE) files.

**Comment by ericdallo** [comment]
Also, I added back the old md templates on this commit: https://github.com/emacs-lsp/lsp-mode/commit/a3cb37ad3e0b37625abf772ca19af95f733fb02e

**Comment by lukehefson** [comment]
Hey @ericdallo! I'm a little confused. Could you reiterate which orgs or repos you'd like in the alpha and I'll be happy to enable it for them.

**Comment by ericdallo** [comment]
Thanks for the help @lukehefson, our idea was to enable the issue form template on this repo: emacs-lsp/lsp-mode, do you think you could help us adding to the alpha program?

**Comment by ericdallo** [comment]
Thank you very much! sorry for bother you
