### ISSUE TITLE
Company: backend company-capf error

### ISSUE THREAD

**Issue by avatar-lavventura** [emacs-lsp/lsp-mode#2913]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).
Alternatively, it will be great if you can reproduce the issue using [lsp-docker](https://github.com/emacs-lsp/lsp-docker/) which provides the minimal configurations for `lsp-mode` and ships with most of the language servers.

### Bug description

I am using `lsp-mode` and `company` on top of Pyhton files. When I complete a function I am getting follwing error:

`
Company: backend company-capf error "[yas] ‘yas-expand-snippet’ needs properly setup ‘yas-minor-mode’" with args (post-completion get_job_block_number(requester_address, key, index))
`

### Steps to reproduce

`lsp-start-plain.el`:
```
;;

(add-hook 'python-mode-hook 'lsp)
(add-hook 'python-mode-hook #'lsp-deferred)
(setq lsp-headerline-breadcrumb-enable nil)
(setq lsp-enable-symbol-highlighting nil)
(setq lsp-modeline-diagnostics-enable 1)
(setq lsp-ui-doc-enable nil)
(setq lsp-lens-enable nil)
(setq-default lsp-pyls-configuration-sources ["flake8"])
(setq lsp-pyls-plugins-pylint-enabled nil)

;; lsp-mode
(if (not (package-installed-p 'lsp-mode))
    (progn
      (package-install 'lsp-mode)))

(diminish 'yas-minor-mode)
(setq company-auto-complete t)
(global-set-key (kbd "C-c C-k") 'company-complete)
```

==> Could be related with following question: https://emacs.stackexchange.com/questions/62183/company-backend-company-capf-error ; in comments recommended to open an issue

### Expected behavior

Completed function example:

` self.mongo_broker.get_job_block_number(${1:requester_address}, ${2:key}, ${3:index})$0`

which should be just: `self.mongo_broker.get_job_block_number()`

### Which Language Server did you use?

`lsp-python`, `python-lsp-server`

### OS

Linux

### Anything else?

Please let me know if you require further information. I am sorry if didn't provide any missing information.

**Comment by yyoncho** [comment]
seems like you are missing `(yas-global-mode)` call.

**Comment by avatar-lavventura** [comment]
When I added `(yas-global-mode)` into my `.emacs` file the problem is solved.

**Comment by dgutov** [comment]
@yyoncho Should there be some check added that `yas-global-mode` is enabled? If it's not, you could disable snippets.

Or, if that's too unreliable, instruct the user specifically to enable `yas-global-mode`.
