### ISSUE TITLE
Problems with Clangd 

### ISSUE THREAD

**Issue by GiulioCocconi** [emacs-lsp/lsp-mode#2918]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).
Alternatively, it will be great if you can reproduce the issue using [lsp-docker](https://github.com/emacs-lsp/lsp-docker/) which provides the minimal configurations for `lsp-mode` and ships with most of the language servers.

### Bug description

When I create a .c file using my raspberry pi 4 with Spacemacs, lsp tells me that I don't have the clangd server, but I've already installed the clangd-9 package (/usr/bin/clangd).

The message is the following:
`LSP :: The following servers support current file but do not have automatic
installation configuration: clangd
You may find the installation instructions at
https://emacs-lsp.github.io/lsp-mode/page/languages.
(If you have already installed the server check *lsp-log*).`

I also couldn't find any lsp-log.

### Steps to reproduce

- Create a .c file
- Wait the error message

I think it's related to the processor of the PI (it worked on the other computer I have)

### Expected behavior

LSP starts normally

### Which Language Server did you use?

C/C++ clangd

### OS

Linux

**Comment by yyoncho** [comment]
most likely clangd is not on the path that emacs sees. One way to fix is to use something like:

```
  (add-to-list 'exec-path (expand-file-name "~/go/bin"))
```

**Comment by GiulioCocconi** [comment]
clangd binary is in /usr/bin, running `(executable-find "clangd")`, emacs finds it...

**Comment by yyoncho** [comment]
Then I suggest testing with lsp-start-plain.el before we continue...

**Comment by GiulioCocconi** [comment]
It works...

**Comment by lebensterben** [comment]
This is the original issue: https://github.com/syl20bnr/spacemacs/issues/14831#issuecomment-856177214

Spacemacs doesn't apply significant changes to `c-c++-mode` when the backend is LSP (clangd or ccls).

**Comment by yyoncho** [comment]
Most likely @GiulioCocconi  has picked ccls as backend which disables clangd.

**Comment by yyoncho** [comment]
And as a side note, I see no reason for spacemacs to provide an additional layer of configuration regarding server selection. lsp-mode configuration variables should be sufficient and ergonomic enough for that.

**Comment by lebensterben** [comment]
@GiulioCocconi 
In a `.c` file buffer, what's the result of
`(lsp--filter-clients (-andfn #'lsp--matching-clients? #'lsp--server-binary-present?))` ?

**Comment by lebensterben** [comment]
@yyoncho 
I agree.
It seems that the only purpose of [additional setup](https://github.com/syl20bnr/spacemacs/blob/120ce6959d10cac04ae27b0a024f879d6d8356bf/layers/%2Blang/c-c%2B%2B/funcs.el#L77-L84) for `clangd` is to define custom `textDocument/switchSourceHeader` capability. But it's already provided in [current version](https://github.com/emacs-lsp/lsp-mode/blob/7b75d6bf01bed9ccb108cf1406d0e2af29d7e39b/clients/lsp-clangd.el#L244-L257) of `lsp-clangd.el`

**Comment by yyoncho** [comment]
> @yyoncho
> I agree.
> It seems that the only purpose of [additional setup](https://github.com/syl20bnr/spacemacs/blob/120ce6959d10cac04ae27b0a024f879d6d8356bf/layers/%2Blang/c-c%2B%2B/funcs.el#L77-L84) for `clangd` is to define custom `textDocument/switchSourceHeader` capability. But it's already provided in [current version](https://github.com/emacs-lsp/lsp-mode/blob/7b75d6bf01bed9ccb108cf1406d0e2af29d7e39b/clients/lsp-clangd.el#L244-L257) of `lsp-clangd.el`

IMHO spacemacs should not act but react. In other words, spacemacs should do their thing when a particular server is enabled. We have hooks for the server started event.

**Comment by ddovod** [comment]
I'm facing the same issue with emacs flatpak installation, I think this is because a flatpak is somehow containerized. Installing emacs using snap solved this for me.
