### ISSUE TITLE
No diagnostics from eslint LSP

### ISSUE THREAD

**Issue by ivomurrell** [emacs-lsp/lsp-mode#2923]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).
Alternatively, it will be great if you can reproduce the issue using [lsp-docker](https://github.com/emacs-lsp/lsp-docker/) which provides the minimal configurations for `lsp-mode` and ships with most of the language servers.

### Bug description

When running the typescript-language-server LSP with the eslint LSP running as an add-on I find that no linting errors are shown in flycheck. Looking at the logs it seems that the vscode-eslint server is also returning an empty array of diagnostics. In some cases it will also send a `window/logMessage` notification saying `t is not iterable`. Typescript errors are still displayed, but nothing from eslint, even when those linter errors are shown when running the `eslint` command on the command-line or using VS Code.

### Steps to reproduce

1. Create a new directory and initialise npm in it `npm init`
2. Add `eslint` as a developer dependency `npm I -D eslint`
3. Initialise eslint with default setting except selecting no frameworks, and running your code in Node rather than in the browser `nix eslint --init`
4. Create a simple javascript file with a linter error, e.g., `let test = "hello"` will warn that `test` is unused
5. Open the directory in emacs and observe that the linter error is not displayed, even when the eslint server is installed

### Expected behavior

The `test` variable should be marked with a flycheck error

### Which Language Server did you use?

lsp-typescript + lsp-eslint

### OS

MacOS

**Comment by yyoncho** [comment]
It works fine on my side after closing and reopening the file:


![image](https://user-images.githubusercontent.com/13259670/121709361-2446bc80-cae1-11eb-8aa4-4ac684ba161e.png)

**Comment by ivomurrell** [comment]
Weird, I still get the same issue even after reopening the file. Taken after running `emacs -q -l lsp-start-plain.el`:
![Emacs screenshot showing empty flycheck buffer](https://user-images.githubusercontent.com/7020796/121709950-fce7f380-cad0-11eb-88d2-347a2a14fe3e.png)
I assume the eslint LSP is also running for you and flycheck isn't falling back to `javascript-eslint` checker?

Perhaps I have a different version of the `vscode-eslint` installed? I got an error when running `(url-copy-file (lsp-vscode-extension-url "dbaeumer" "vscode-eslint" "2.1.14") "/tmp/foo.zip")` then `(lsp-unzip "/tmp/foo.zip" lsp-eslint-unzipped-path)` as the downloaded extension isn't a zip file, so had to copy the version installed by VS Code.

**Comment by yyoncho** [comment]
> Perhaps I have a different version of the `vscode-eslint` installed?

it might be. Make sure that you download the proper version. Check if lsp checker is running via flycheck-verify-setup also look for errors for vscode-elint not liking the eslint setting.

**Comment by ivomurrell** [comment]
> Make sure that you download the proper version.

The `package.json` in the unzipped directory says the version is `2.1.20`.

> Check if lsp checker is running via flycheck-verify-setup also look for errors for vscode-elint not liking the eslint setting.

No clues there unfortunately. `lsp` is selected as the checker according to flycheck, and the only configuration errors I've seen are some `probeFailed` ones when the LSP server is opened for a file that no longer exists. I'm still suspicious about the `t is not iterable` logs I'm getting after some `doChange` requests though...

**Comment by yyoncho** [comment]
> some `probeFailed` ones when the LSP server is opened for a file that no longer exists.

delete lsp-session-file and restart emacs to start with clean env. IMHO the issue is that there is something that vscode-eslint does not like in your env, e. g. global eslint version but I am familiar with server internal to tell what is the reason. Most likely it wont work with vscode too. You may delete lsp-eslint-library-choices-file  as well.

**Comment by ivomurrell** [comment]
Tried deleting both of those files and restarting, as well as testing with both locally installed and globally installed version of eslint, still nothing. Works perfectly fine in VS Code too. I'm stumped 😞 Thanks for the help though!

**Comment by yyoncho** [comment]
can you collect the logs from both vscode and emacs?

**Comment by yyoncho** [comment]
also can you test with 14 version - https://marketplace.visualstudio.com/_apis/public/gallery/publishers/dbaeumer/vsextensions/vscode-eslint/2.1.14/vspackage . This server often is making breaking changes.

**Comment by ivomurrell** [comment]
> also can you test with 14 version - https://marketplace.visualstudio.com/_apis/public/gallery/publishers/dbaeumer/vsextensions/vscode-eslint/2.1.14/vspackage . 

This fixed the issue for me! Amazing, thank you! Happy to provide further details if you want to support 2.1.20.

**Comment by yyoncho** [comment]
@ivomurrell you may open a separate issue for that. Generally, we are lacking manpower to follow their releases strictly.
