### ISSUE TITLE
DocumentLink: navigate to the position specified by range field

### ISSUE THREAD

**Issue by ananthakumaran** [emacs-lsp/lsp-mode#2924]
Is your feature related or already mentioned on [the wishlist](https://github.com/emacs-lsp/lsp-mode/discussions/2892)?
No

Describe your feature here.

![image](https://user-images.githubusercontent.com/149238/121714419-6bda4200-cafb-11eb-9949-73976bcd4c35.png)

`textDocument/documentLink` request returns a list of [DocumentLink](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#documentLink), which are highlighted using an underline. When I click the link, I expected it to take me to the start of the `range` specified in the documentLink, but it just goes to the file specified by the `target`, but not to the position specified by the `range` field. Moving to the specific position would make it very useful in cases like JSON schema file example above.

**Comment by yyoncho** [comment]
this is more like a bug, can you provide a sample file/project to reproduce the issue with(+steps to reproduce).

**Comment by ananthakumaran** [comment]
Step to reproduce
1. store the below snippet as a json file
```json
{
  "$id": "https://example.com/arrays.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "A representation of a person, company, organization, or place",
  "type": "object",
  "properties": {
    "fruits": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "vegetables": {
      "type": "array",
      "items": { "$ref": "#/$defs/veggie" }
    }
  },
  "$defs": {
    "veggie": {
      "type": "object",
      "required": [ "veggieName", "veggieLike" ],
      "properties": {
        "veggieName": {
          "type": "string",
          "description": "The name of the vegetable."
        },
        "veggieLike": {
          "type": "boolean",
          "description": "Do I like this vegetable?"
        }
      }
    }
  }
}
```
2. npm install -g vscode-json-languageserver
3. open the json file, enable lsp (should connect to json-ls) and click `"#/$defs/veggie"` (it should be a clickable overlay)

**Comment by yyoncho** [comment]
AFACS this server does not support links at all and these links come from something else.

**Comment by ananthakumaran** [comment]
it does support, please make sure to install the latest version.

```
 |-[-] json-ls:52719
 |  |-[-] Buffers
 |  |  `-[+] test.json
 |  `-[+] Capabilities
```

```
[Trace - 10:49:22 AM] Sending request 'textDocument/documentLink - (3956)'.
Params: {
  "textDocument": {
    "uri": "file:///<redacted>/test.json"
  }
}


[Trace - 10:49:22 AM] Received response 'textDocument/documentLink - (3956)' in 37ms.
Result: [
  {
    "range": {
      "end": {
        "character": 40,
        "line": 14
      },
      "start": {
        "character": 26,
        "line": 14
      }
    },
    "target": "file:///<redacted>/test.json#19,15"
  }
]
```

**Comment by ananthakumaran** [comment]
One thing I missed in the first comment is where the range is encoded. document.range points to the link range (#/$defs/veggie), the target range is actually encoded in the target link fragment part `#19,15` in the above example

**Comment by ananthakumaran** [comment]
https://github.com/microsoft/vscode-json-languageservice/blob/a0a7e02636cfb6d6c0f2a578cd81da9c9c42103d/src/services/jsonLinks.ts#L18-L21

this is the part which constructs the link on the language server side

**Comment by yyoncho** [comment]
PR at #2925

**Comment by yyoncho** [comment]
I haven't tested it manually, please check if there is off by one error due to different offset in protocol/extension.
