### ISSUE TITLE
completion does not work on a language server with completion on characters

### ISSUE THREAD

**Issue by dcermak** [emacs-lsp/lsp-mode#2929]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).
Alternatively, it will be great if you can reproduce the issue using [lsp-docker](https://github.com/emacs-lsp/lsp-docker/) which provides the minimal configurations for `lsp-mode` and ships with most of the language servers.

### Bug description

I am currently working on a language server for salt states (https://github.com/dcermak/salt-lsp), which supports some rudimentary completion on `.` and `-` trigger characters. Unfortunately this does not appear to work properly with lsp-mode, whereas it works with vscode (the other language server features work in both clients).

Judging from the log, it looks like lsp-mode will **never** send completion requests to the server, even if the current trigger character has been typed.

### Steps to reproduce

```ShellSession
$ git clone https://github.com/dcermak/salt-lsp
$ pushd salt-lsp 
$ git checkout proper_python_package
$ poetry build 
$ pip install --user --force-reinstall dist/*whl
$ popd
$ git clone https://github.com/sysrich/salt-states
$ cd salt-states
```

Now open emacs, eval-file `salt-lsp/clients/emacs/salt-lsp.el`, install `salt-mode` and open e.g. `salt-states/salt/master.sls`, launch `lsp-mode`. 

lsp-mode will correctly support go to definition for `require:` directives and it will display breadcrumbs, but autocompletion on `.` and `-` characters will not work.

### Expected behavior

- lsp-mode should send completion requests when the trigger character has been typed

### Which Language Server did you use?

https://github.com/dcermak/salt-lsp

### OS

Linux

### Error callstack

```emacs-lisp
only contains requests didChange and textDocument/documentSymbol requests and replies
```

**Comment by kiennq** [comment]
@dcermak Can you also include the trace io log?

**Comment by kiennq** [comment]
Also, can you get the completion when manually trigger the completion (using `C-M-i`)?

**Comment by dcermak** [comment]
> @dcermak Can you also include the trace io log?

Sure, you can find it here: https://fpaste.me/2XJdKyvVui

Unfortunately there are no requests for textDocument/completion at all in there for reasons that I do not understand :(

> Also, can you get the completion when manually trigger the completion (using `C-M-i`)?

Unfortunately invoking `completion-at-point` results in nothing happening.

**Comment by yyoncho** [comment]
can you upload everything from the server startup?

**Comment by dcermak** [comment]
> can you upload everything from the server startup?

Certainly: https://fpaste.me/w5XdPoChiL

That output has been created in `emacs -Q` using `lsp-start-plain.el` and installing `salt-mode` into there. I have opened the file `salt-states/salt/master.sls`, removed everything but the first dictionary in that yaml file so that it looks like this:
```yaml
saltmaster.packages:
  pkg.installed:
    - pkgs:
      - salt-master
```

Then I removed the `installed` and tried to trigger completions manually via `completion-at-point` (the completion requests would otherwise not show up in the log). Unfortunately that does **not** send a trigger character and thereby my language server does not respond to these (I could change this, so that it is more lenient in this regard). However, for some reason lsp-mode does not send any completion requests by itself.

**Comment by kiennq** [comment]
@dcermak, can you try to add `  :completion-in-comments? t` in your `make-lsp-client`?
Also, what's your `lsp-register-client` looks like?

**Comment by dcermak** [comment]
I have tried it with `:completion-in-comments? t`, but unfortunately nothing changed.

My whole file that I eval to register the language server looks like this:
```elisp
(require 'lsp-mode)
(require 'salt-mode)

(add-to-list 'lsp-language-id-configuration '(salt-mode . "salt"))

(lsp-register-client
 (make-lsp-client
  :new-connection (lsp-stdio-connection (lambda ()'("python3" "-m" "salt_lsp")))
  :activation-fn (lsp-activate-on "salt")
  :completion-in-comments? t
  :server-id 'salt-lsp))

(provide 'salt-lsp)
```

**Comment by yyoncho** [comment]
@kiennq I was able to reproduce the issue and it is related lsp-mode -> company-mode interaction. First, I had to do that 

`(add-to-list 'company-begin-commands 'yaml-electric-dash-and-dot)`

to make sure that lsp-completion-at-point is called. Then afaics lsp-completion-at-point  is not called after the first call for the range. I don't know what the reason might be...

**Comment by dcermak** [comment]
FYI, I'm also facing comparable issues with eglot: https://github.com/joaotavora/eglot/issues/706

**Comment by yyoncho** [comment]
Just want to mention that if you do:

`(add-to-list 'lsp-language-id-configuration '(text-mode . "salt"))`

and then enable text-mode in that file and then you do M-x lsp it all seems to work fine. Which makes me think that  the issue is between comapny-mode and salt-mode.

**Comment by dcermak** [comment]
@yyoncho Indeed! Thanks a lot!

So I guess this is then not a bug in lsp-mode, right?

**Comment by yyoncho** [comment]
@dcermak yes. My guess is that salt-mode (or yaml-mode) is doing stuff that breaks company-mode.

**Comment by dcermak** [comment]
@yyoncho I guess I found the offender: https://github.com/glynnforrest/salt-mode/blob/c46b24e7fdf4a46df5507dc9c533bbc0064a46fa/salt-mode.el#L50

**Comment by yyoncho** [comment]
ok, marking the issue as closed since it seems like there is nothing to do on this side.
