### ISSUE TITLE
A var for disabling auto-install of language servers

### ISSUE THREAD

**Issue by mineo** [emacs-lsp/lsp-mode#2933]
Is your feature related or already mentioned on [the wishlist](https://github.com/emacs-lsp/lsp-mode/discussions/2892)? -- No.

Let me preface this feature request with the note that I'm using spacemacs, which - unless otherwise configured - tries to enable lsp-mode in all all enabled modes that support it. I can understand if this feature request is deemed not appropriate for lsp-mode :)

Being able to install language servers automatically is a super great feature!

I find myself in a position where I'm working on different machines with different binaries installed, so some of the language can't be installed automatically on some machines: for example `bash-lsp` fails to install with `Unable to install bash-language-server via `npm' because it is not present` in `*lsp-log*` whenever I open a shell script. I'm OK with using lsp-mode only for the main codebase I'm working on via clangd, but I'm fine with not having lsp-mode support me in shell scripts. Then again, on other machines, I do not have clangd available and that's OK, too. This whole situation is made more annoying by the call to `lsp--completing-read` in the auto-install code: https://github.com/emacs-lsp/lsp-mode/blob/b294e745e254c410a1fa352b97f748d1d5bd2bf2/lsp-mode.el#L8186-L8195, popping up a question about which language server to install automatically.

Ideally, `lsp` (the function) would check whether a var (`lsp-auto-install-lsp-servers`?) is `t` before trying to install language servers. I see the following benefit to this over other solutions, like removing `lsp-mode` from `*-mode-hook` (or whatever spacemacs uses to automatically run `lsp-mode`): for users with a config that's used on different machines - some of which have language servers (or pre-requisites to auto-install them) pre-installed, some don't - there's no need for perform any checks (does clangd exist? does npm exist?) before adding `lsp-mode` to `*-mode-hook`. Instead, they can simply enable lsp-mode, knowing that it falls back to unobtrusively doing nothing if the machine is not set up for the language servers.

**Comment by yyoncho** [comment]
check https://emacs-lsp.github.io/lsp-mode/page/faq/#how-do-i-disable-automatic-installation-for-particular-language-server
