### ISSUE TITLE
File mode specification error: (void-variable get-root)

### ISSUE THREAD

**Issue by edmz** [emacs-lsp/lsp-mode#295]
Using latest lsp-mode from Melpa, running Emacs pretest 26.0.91.

I get said error while the language mode hook tries to run the enable function, in my case its #'lsp-elixir-enable and also with ruby.

**Comment by arejensen** [comment]
Does #296 work for you?

**Comment by casouri** [comment]
Maybe I did something wrong? It didn't fix it for me.

I made according changes in lsp-mode.el, recompiled it and regenerated autoloads.

**Comment by twlz0ne** [comment]
Same here

Emacs 26.0.91/27.0.50

**Comment by vibhavp** [comment]
Cannot reproduce this here. Have you tried re-compiling/re-installing *both* the language client package and lsp-mode?

**Comment by edmz** [comment]
I made the change, restarted emacs and it worked.

Now I am getting another error when I try to run lsp-capabilities: "Wrong
type argument: hash-table-p, nil". But that could be something else.

**Comment by twlz0ne** [comment]
@vibhavp This issue recurs on my computer 100%.

Here is the test code: https://gist.github.com/twlz0ne/38f9f972574abcb860ee06c33398ee97

Just 1)Download 2)Run.

**Comment by fleimgruber** [comment]
FWIW, experienced this in https://github.com/syl20bnr/spacemacs/issues/10391.  Fixed it by #296 plus 

> re-compiling/re-installing both the language client package and lsp-mode

**Comment by vv111y** [comment]
Not working in spacemacs, my backtrace and config info is here https://github.com/syl20bnr/spacemacs/issues/10449

I removed python and lsp layers and then reinstalled (this removes and reinstalls all relevant packages). No change.
