### ISSUE TITLE
Eslint watches projects beyond just the current project

### ISSUE THREAD

**Issue by JordanAnthonyKing** [emacs-lsp/lsp-mode#2969]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

I have several angular projects with a shared parent directory. The parent directory is not itself a project, nor listed in projectile.

When I open one of the projects I am always greeted by this:
![image](https://user-images.githubusercontent.com/58787893/123789106-51aaad00-d8cc-11eb-93d9-4fed1c7e5178.png)

`edm` is my shared project directory, `edm-ui-styleguide` is not my current project.
Uninstlaling the eslint file server prevents this.

I understand that it is possible to turn file watchers off for lsp servers, but why is eslint searching outside of the project directory in the first place?

### Steps to reproduce

Open an eslint applicable project in a folder with other eslint applicable projects.

### Expected behavior

Eslint to not attempt to watch directories outside of the current project

### Which Language Server did you use?

- `eslint`
- `ts-ls`
- `angular-ls`

### OS

Linux

### Anything else?

Running lsp-mode in the latest doom emacs, on Ubuntu under WSL.

**Comment by yyoncho** [comment]
this is the expected behaviour for multi-root language servers. If you want to disable that check https://emacs-lsp.github.io/lsp-mode/page/faq/#how-do-i-force-lsp-mode-to-forget-the-workspace-folders-for-multi-root

**Comment by aspiers** [comment]
Is there any chance someone could please explain this in a bit more detail?  As a newcomer to emacs-lsp, I read all the above docs and also found the above FAQ, but I still don't understand why this is the expected behaviour?  Isn't it needlessly inefficient to watch projects which the user isn't editing?

**Comment by yyoncho** [comment]
@aspiers it is more efficient to start one instance for multiple folders instead of starting a separate server for each folder/project. This is what multi-folder is for (not only). Let me know if you need more info.

**Comment by aspiers** [comment]
@yyoncho Thanks a lot for the quick reply! I understand that, but if the user wants the server for the current project *only*, and no others, as described above by the OP, why would it watch any files outside the current project?

The OP has a layout something like the following:

    /home/jordan/edm/
        project1/
        project2/
        project3/
        edm-ui-styleguide/

(He didn't give the exact names of all the project folders, so this is just a sketch.)

He said that if he opens `project1` (say), then the eslint server starts watching all the files in `edm-ui-styleguide/`, even though he's not working on the style guide and it has nothing to do with `project1` except for having a common parent.  Why does emacs-lsp (or maybe the eslint server) do that?  It seems incredibly inefficient and makes no sense to me.

**Comment by yyoncho** [comment]
No, the user has added several folders to his session. Thus, we pass them to the server and the server watches them. This is how the protocol works.

**Comment by aspiers** [comment]
> No, the user has added several folders to his session.

I don't see any evidence of that in his report.  Maybe I am misreading, or is it just that this is the only possible explanation?

I thought he was saying he only opened one project (which I assume is the same thing as a "folder" in VS Code terminology).  He wrote:

> When I open one of the projects I am always greeted by this:
>
> [screenshot with message `Do you want to watch all files in /home/jordan/edm/edm-ui-styleguide? (y or n)`]
>
> `edm` is my shared project directory, `edm-ui-styleguide` is not my current project.

**Comment by yyoncho** [comment]
When you open a project for the first time you see that: 

![import](https://user-images.githubusercontent.com/13259670/132917492-5dca539d-8c8d-4d88-9b80-1af4cb323bf3.png)

Once you import it, it is persisted. Note also that in a lot of languages, you have cross-project references, and opening all of the projects from a certain workspace is a must.

**Comment by aspiers** [comment]
Thanks!  I'm still a bit confused, but I guess this is not the best place to ask more questions, so I just posted [What are workspaces in emacs-lsp? What about multi-root? · Discussion #3095 · emacs-lsp/lsp-mode](https://github.com/emacs-lsp/lsp-mode/discussions/3095) instead.
