### ISSUE TITLE
The equivalent setting of `eglot-stay-out-of` with lsp-mode.

### ISSUE THREAD

**Issue by hongyi-zhao** [emacs-lsp/lsp-mode#2981]
Currently, I'm using eglot and texlab with the following configuration:

```emacs-lisp
(use-package eglot
  :hook 
  ((TeX-mode . eglot-ensure))
  :config
  ;https://github.com/joaotavora/eglot/issues/708#issuecomment-868616833
  (add-to-list 'eglot-stay-out-of 'company)
  ;;; ensure texlab is set as the server.
  (add-to-list 'eglot-server-programs
             '((latex-mode tex-mode context-mode texinfo-mode bibtex-mode) . ("texlab"))))
```
Now, I want to implement the similar function based on lsp-mode, texlab, and lsp-latex, but I don't know the equivalent setting of `eglot-stay-out-of` with lsp-mode.

Any hints will be highly appreciated.

Regards,
HY

**Comment by yyoncho** [comment]
`(setq lsp-completion-provider :none)`

Refer to https://emacs-lsp.github.io/lsp-mode/tutorials/how-to-turn-off/

**Comment by hongyi-zhao** [comment]
Thanks a lot. It does the trick.

**Comment by hongyi-zhao** [comment]
If so, the completion is not supplied by `lsp-mode/eglot` and `texlab` at all. So the corresponding configurations can be commented out and it will not have any influence on the final completion effect.
