### ISSUE TITLE
c++-mode ':', '>' and '/' unnecessarily begin completion

### ISSUE THREAD

**Issue by ville-h** [emacs-lsp/lsp-mode#2998]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

When editing c++ with `lsp-mode` enabled typing `:`, `>` or `/` pops up the completion box in situations where there couldn't be a relevant completion.

### Steps to reproduce

```C++
int main() {
    // on the line below try typing ':', '>' or '/'
    
    return 0;
}
```

### Expected behavior

Don't show the completion box unnecessarily.

### Which Language Server did you use?

lsp-clangd.

### OS

Linux

### Anything else?

Whilst I've no clue how `lsp-mode` implements things. It seems that a possible acceptable fix could be to check what precedes `:`, `>` or `/`. For `:` it should be preceded by another `:` as part of a `::` sequence to trigger the completion box. Similarly for `>` it should be preceded by `-` as part of a `->` sequence to trigger the completion box. Not sure why `/` would ever trigger the completion box.

**Comment by yyoncho** [comment]
As per spec, we should ask the server for completion at point when a trigger char is pressed. If there are no suitable completion the server should return no results. I don't see anything to do on the client-side here.

**Comment by ville-h** [comment]
Your answer meaning what exactly? You will consider an `lsp-mode`-side fix for now and bring the issue to the attention of the entity where it originates from? You won't consider an `lsp-mode`-side fix but will bring the issue to the attention of the entity where it originates from? You will not take any action?

**Comment by yyoncho** [comment]
What I am saying is that lsp-mode is doing the right thing - triggering completion when you press trigger character. lsp-mode is just a client and does not know what are the "situations where there couldn't be a relevant completion.". This is what the server should do.

**Comment by ville-h** [comment]
Your answer is: "will not take any action", fair enough. The correct location to file the issue would be [here](https://github.com/clangd/clangd) then?

**Comment by yyoncho** [comment]
We cant take any action. And yes, you may ask in their repo.

**Comment by ville-h** [comment]
There was the option that you would bring up the issue with clangd as it directly impacts your project. You are far more qualified to talk the ins and outs of the the language server specification, how it is supposed to work and how clangd's implementation is impacting your project.

**Comment by ville-h** [comment]
The clangd developers [indicate](https://github.com/clangd/clangd/issues/818#issuecomment-880133461) the fault is with lsp-mode .

**Comment by yyoncho** [comment]
@kiennq - willing to take a look?

**Comment by kiennq** [comment]
This is a regression from #2864. 
The `last-commdand` in `c++-mode` when types trigger characters is actually something like `c-electric-colon` or something similar, which affects the context set

**Comment by yyoncho** [comment]
Maybe check if the command is company-compete or company-indent-or-complete-common

**Comment by dgutov** [comment]
Or whether it's (not) in `company-begin-commands`.

**Comment by dgutov** [comment]
Though I'm not sure how it's supposed to work with other frontends. And it's supposed to, right?

**Comment by dgutov** [comment]
Maybe the value of `non-essential` can help.

**Comment by kiennq** [comment]
> Maybe the value of `non-essential` can help.

That's actually a good point. I think it can help too

**Comment by ville-h** [comment]
You are supposed to check if the character was a "trigger character", that the server reported when your client connected to it, and then change the number 2 rather than 1?

**Comment by kiennq** [comment]
> You are supposed to check if the character was a "trigger character", that the server reported when your client connected to it, and then change the number to 2 rather than 1?

Well, that's how it has been done. However, we don't have a good indicator if the user manually triggers completion or not (so the value should be 1 instead of 2 in that case).
Until now, we're doing that by relying on `last-command` as `self-insert` to determine if the user typed last character and assume that automatic completion is triggered by that (context is 2). However, that indicator is not good since it's intercepted by `c++-mode`.
This fix fixes that by using a more resilient indicator.

@ville-h Can you check if this fix is working for you?
