### ISSUE TITLE
add new markdown lsp support

### ISSUE THREAD

**Issue by Jackson-soft** [emacs-lsp/lsp-mode#3010]
The current markdown lsp development has stalled, do you consider supporting the new lsp?

[zeta-note](https://github.com/artempyanykh/zeta-note)

**Comment by bridgesense** [comment]
I was wondering why markdown files crash and burn with lsp.  It told me to check stderr buffer.  I imagine there's a flag we can turn on for that buffer. 

 Is this due to changes in markdown-mode?
