### ISSUE TITLE
Setting lsp-enable-indentation to nil doesn't disable indentation

### ISSUE THREAD

**Issue by doomchild** [emacs-lsp/lsp-mode#3012]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

I have an `editorconfig` file setting the indent width to 2 for C# files (`editorconfig-mode` is enabled, and I've run `editorconfig-apply`, just to be sure).  I have `lsp-enable-indentation` set to `nil`.  When I type a semicolon, the line it terminates is indented to a width of 4.

### Steps to reproduce

1. Set `indent_size` to 2 for `*.cs` files in `.editorconfig`.
2. Set `lsp-enable-indentation` to `nil`.
3. Enable `editorconfig-mode`.
4. Enable `lsp-mode` and start the server.
5. Open a C# file.
6. Type `C-x h`.
7. Hit `<tab>`.  The document should now be formatted to a width of 2.
8. In a syntactically valid place, type `int i = 0`.
9. Type a semicolon.
10. Notice that the line has shifted to the right an extra 2 spaces.

### Expected behavior

No extra indentation should be applied.

### Which Language Server did you use?

omnisharp-roslyn

### OS

MacOS

**Comment by kiennq** [comment]
@doomchild I think you need to set `lsp-enable-on-type-formatting` to `nil` instead.
Also, what's your major mode for csharp? The `editorconfig-mode` may not set correct variable when you're using `csharp-tree-sitter-mode`.

**Comment by doomchild** [comment]
Setting `lsp-enable-on-type-formatting` to `nil` has no effect.  The incorrect indentation still happens.  I'm using the major mode from `csharp-mode.el`, according to `M-x describe-mode`.

**Comment by kiennq** [comment]
Can you check the value of `c-basic-offset` in your local `csharp` buffer?
What happens if you select the line with the wrong indentation and do `M-x indent-region`?

You need to set `lsp-enable-on-type-formatting` before starting `lsp-mode` btw.

**Comment by doomchild** [comment]
Ah hah.  Setting `lsp-enable-on-type-formatting` earlier fixed it.  Thanks.
