### ISSUE TITLE
rust-analyzer over TRAMP hangs

### ISSUE THREAD

**Issue by hchencs** [emacs-lsp/lsp-mode#3020]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

Emacs hangs when I opened a Rust source file via TRAMP over SSH.

- Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 2.24.32, cairo version 1.16.0)
- lsp-mode 20210724.1836
- tramp 2.5.1
- rust-analyzer ea105f9 2021-07-25 dev

On the server, `/tmp/rust-analyzer-remote-1-stderr` is empty.

[lsp-log.txt](https://github.com/emacs-lsp/lsp-mode/files/6879900/lsp-log.txt)

### Steps to reproduce

`emacs -q -l .emacs-test.txt /ssh:server:path/to/file`
[.emacs-test.txt](https://github.com/emacs-lsp/lsp-mode/files/6879838/default.emacs-test.txt)

### Expected behavior

Emacs should not hang.

### Which Language Server did you use?

rust-analyzer ea105f9 2021-07-25 dev

### OS

Linux

### Error callstack

```emacs-lisp
`lsp-log.txt` was attached above.
```

**Comment by yyoncho** [comment]
Does it go away after C-g or multiple C-g?

**Comment by hchencs** [comment]
> Does it go away after C-g or multiple C-g?

It went away only after multiple C-g. After that, no connection with the server exists.

**Comment by hchencs** [comment]
Also I am using GccEmacs.
