### ISSUE TITLE
Warning (lsp-mode): Unknown notification: workspace/semanticTokens/refresh

### ISSUE THREAD

**Issue by sunlin7** [emacs-lsp/lsp-mode#3029]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

Got warning message:
> Warning (lsp-mode): Unknown notification: workspace/semanticTokens/refresh

It's a regression issue that commit remove the notification handler of workspace/semanticTokens/refresh:
https://github.com/emacs-lsp/lsp-mode/commit/1f7ccca8047321cee20288646c89b55825868d83#diff-413c3dbb8dc902306ccb23932847ff082352d6123fd5668ea89b24cd8ebcbedbL6049

There are response handler but no notification handler.
@sebastiansturm Please help to fix the issue.

### Steps to reproduce

Enable lua-language-server for lsp-mode.

### Expected behavior

No warning message.

### Which Language Server did you use?

lua-language-server

### OS

Linux

### Error callstack

```emacs-lisp
N/A
```

### Anything else?

N/A

**Comment by ericdallo** [comment]
c/c @sebastiansturm

**Comment by sebastiansturm** [comment]
it seems to me that lua-language-server does send out a refresh notification (cf. semantic_tokens.lua / refresh()), but AFAICS it should be a request (https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#semanticTokens_refreshRequest)

**Comment by ericdallo** [comment]
Good catch, it does seems it's correct on lsp-mode side, so it'd need to be changed/fixed on lua language server side @sunlin7

**Comment by sunlin7** [comment]
Yes, it's should be a request. I create a PR in upstream project.
https://github.com/sumneko/lua-language-server/pull/633

Thank you all ~

**Comment by c02y** [comment]
It seems lsp-mode doesn't update the code, it still download the old version `v1.17.4 2021-3-4`, the latest version is `v2.5.6 2021-12-27`
