### ISSUE TITLE
annoying message: Unknown method: window/progress

### ISSUE THREAD

**Issue by Dushistov** [emacs-lsp/lsp-mode#303]
I'm using emacs-lsp/lsp-rust, time to time it is almost impossible
to use `M-x command`. Minibuffer was spammed by messages like:

Unknown method: window/progress

May be it is possible to handle window/progress message by showing `rls` status on emacs status bar?

**Comment by Dushistov** [comment]
Thank you @vibhavp

**Comment by blitz** [comment]
@Dushistov @vibhavp I have the same issue. What is the solution?

**Comment by nbfalcon** [comment]
@blitz this looks like an event, which is handled in `lsp-rust`. Try updating and recompiling `lsp-mode` and updating `rls`.

**Comment by blitz** [comment]
Updating and recompiling did indeed help. thanks!
