### ISSUE TITLE
[help] Fixing `lsp-eldoc-hook` lsp-mode How to suppress function definitions for specific functions in python

### ISSUE THREAD

**Issue by avatar-lavventura** [emacs-lsp/lsp-mode#3038]
- Python 3.8.10
- python-lsp-jsonrpc==1.0.0
- python-lsp-server==1.2.1
--- 

Related to fixing `lsp-eldoc-hook`

I am using `lsp` under Python. I have followed: https://emacs-lsp.github.io/lsp-mode/page/installation/ for its installation.

```
(require 'lsp-mode)
(add-hook 'python-mode-hook 'lsp)
(add-hook 'python-mode-hook #'lsp-deferred)
```

When I type `print(` automatically its description shown as below window:

[![enter image description here][1]][1]

Would it be possible to disable this option for selected functions such as `print()`, hence I do not want to see its definition automatically.

  [1]: https://i.stack.imgur.com/uXQVe.png

------------

emacs.stackexchange.com discussion link: https://emacs.stackexchange.com/q/66315/18414

> I tried took a stub at it, and got a "kinda" working solution, but then my Emacs froze along with all code. Not gonna rewrite, because that was a dirty hack, and also lsp-mode folks should be ashamed of their lsp-hover function that accepts contents in what seems like a thousand of types! Anyway, your best bet is to create a report to lsp-mode and ask them to fix their lsp-eldoc-hook, which (among other problems) doesn't provide any way of extracting the docs. In my "hacky code" I had to modify lsp-hover instead, which I'm sure would break long-term due to using lsp-mode internals. 

>There is a lsp-eldoc-hook which could've been used to implement your usecase, weren't it for the fact that: 
>1) the functions that this hook executes do not accept the new documentation as an argument, 
>2) the hook is a list of functions, but there's no way to make one of them stop the list execution (which could be used by you to not execute that function that shows eldoc upon noticing "print" in docs).

**Comment by kiennq** [comment]
https://emacs-lsp.github.io/lsp-mode/tutorials/how-to-turn-off/
I think you want to set `(setq lsp-eldoc-enable-hover nil)`

**Comment by avatar-lavventura** [comment]
@yyoncho I do not want to disavle docs completely. (which setting the lsp-eldoc-enable-hover to nil does), but only for certain functions.

**Comment by avatar-lavventura** [comment]
Resolved at: https://emacs.stackexchange.com/a/68007/18414
> ```
> (defun lsp-signature-hook-function ()
>   (setq lsp-signature-doc-lines
>         (when (and lsp-signature-mode
>                    (member (python-eldoc--get-symbol-at-point) '("print")))
>           (lsp-signature-stop))))
> 
> (add-hook 'lsp-signature-mode-hook #'lsp-signature-hook-function)
> ```
