### ISSUE TITLE
[help] Fixing lsp-eldoc-hook lsp-mode How to suppress function definitions for certain functions in python. I do not want to disable docs completely 

### ISSUE THREAD

**Issue by avatar-lavventura** [emacs-lsp/lsp-mode#3039]
- Python 3.8.10
- python-lsp-jsonrpc==1.0.0
- python-lsp-server==1.2.1
--- 

## I do not want to disable docs completely. (which setting the `lsp-eldoc-enable-hover` to *nil* does), but disable docs only for certain functions. 

- Related to fixing `lsp-eldoc-hook`

- `(setq lsp-eldoc-enable-hover nil)` does not resolve my issue.
I am using `lsp` under Python. I have followed: https://emacs-lsp.github.io/lsp-mode/page/installation/ for its installation.

```
(require 'lsp-mode)
(add-hook 'python-mode-hook 'lsp)
(add-hook 'python-mode-hook #'lsp-deferred)
```

When I type `print(` automatically its description shown as below window:

[![enter image description here][1]][1]

Would it be possible to disable this option for selected functions such as `print()`, hence I do not want to see its definition automatically.

  [1]: https://i.stack.imgur.com/uXQVe.png

------------

emacs.stackexchange.com discussion link: https://emacs.stackexchange.com/q/66315/18414

> I tried took a stub at it, and got a "kinda" working solution, but then my Emacs froze along with all code. Not gonna rewrite, because that was a dirty hack, and also lsp-mode folks should be ashamed of their lsp-hover function that accepts contents in what seems like a thousand of types! Anyway, your best bet is to create a report to lsp-mode and ask them to fix their lsp-eldoc-hook, which (among other problems) doesn't provide any way of extracting the docs. In my "hacky code" I had to modify lsp-hover instead, which I'm sure would break long-term due to using lsp-mode internals. 

>There is a lsp-eldoc-hook which could've been used to implement your usecase, weren't it for the fact that: 
>1) the functions that this hook executes do not accept the new documentation as an argument, 
>2) the hook is a list of functions, but there's no way to make one of them stop the list execution (which could be used by you to not execute that function that shows eldoc upon noticing "print" in docs).

**Comment by jcs090218** [comment]
Duplicate question to https://github.com/emacs-lsp/lsp-mode/issues/1223?

**Comment by yyoncho** [comment]
Something like that should do:

```
(advice-add 'eldoc-message :around 
            (lambda (f msg)
              (unless (s-contains? "foo" msg)
                (funcall f msg))))
```

Replace "foo" with part of the message that you dont want to see.

**Comment by avatar-lavventura** [comment]
I have tried for `print(`:

```
(advice-add 'eldoc-message :around 
            (lambda (f msg)
              (unless (s-contains? "print" msg)
                (funcall f msg))))
```

But still I am seeing somethingl like:

<img width="793" alt="image" src="https://user-images.githubusercontent.com/18537398/128568702-f92290bf-dfed-4475-a9ea-e949b3aded1f.png">

**Comment by avatar-lavventura** [comment]
Resolved at: https://emacs.stackexchange.com/a/68007/18414
> ```
> (defun lsp-signature-hook-function ()
>   (setq lsp-signature-doc-lines
>         (when (and lsp-signature-mode
>                    (member (python-eldoc--get-symbol-at-point) '("print")))
>           (lsp-signature-stop))))
> 
> (add-hook 'lsp-signature-mode-hook #'lsp-signature-hook-function)
> ```
