### ISSUE TITLE
lsp-on-change: wrong-type-argument number-or-marker-p nil

### ISSUE THREAD

**Issue by brotzeit** [emacs-lsp/lsp-mode#304]
```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  lsp-on-change(790 790 24466)
  insert-file-contents("/home/brotzeit/git/remacs/rust_src/src/windows.rs" t nil nil t)
  revert-buffer-insert-file-contents--default-function("/home/brotzeit/git/remacs/rust_src/src/windows.rs" nil)
  revert-buffer--default(ignore-auto dont-ask)
  revert-buffer(ignore-auto dont-ask preserve-modes)
  #f(compiled-function () #<bytecode 0x19fbc71>)()
  apply(#f(compiled-function () #<bytecode 0x19fbc71>) nil)
  auto-revert-handler()
  #f(compiled-function () #<bytecode 0x19f5a35>)()
  apply(#f(compiled-function () #<bytecode 0x19f5a35>) nil)
  auto-revert-buffers()
  magit-auto-revert-buffers()
  magit-refresh()
  magit-run-git("checkout" "master")
  magit-checkout("master")
  funcall-interactively(magit-checkout "master")
  call-interactively(magit-checkout nil nil)
  command-execute(magit-checkout)
```

Any idea ? Thanks.

**Comment by j-piecuch** [comment]
I have the same problem, the language server goes haywire after I checkout a new branch in magit.
The error message and stack trace look identical.

**Comment by andschwa** [comment]
Also reproducing for me after switching branches using Git directly (i.e. in the shell), but then `magit-auto-revert-buffers` reverts the files for me (and I'm on Windows, for what it's worth), and this happens.

**Comment by gpittarelli** [comment]
I repro'd this. It seems that the changes made by `auto-revert-mode` trigger lsp-mode's `after-change-functions` hook (`lsp-on-change`), `buffer-file-name` is not set correctly.  So possibly an upstream bug. I have a fix in PR: https://github.com/emacs-lsp/lsp-mode/pull/341
