### ISSUE TITLE
LSP-mode doesn't match derived modes properly

### ISSUE THREAD

**Issue by slippycheeze** [emacs-lsp/lsp-mode#3053]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

[docker-compose-mode](https://melpa.org/#/docker-compose-mode) is a derived mode from `yaml-mode`, which adds some vendor-specific features.  Using LSP, this causes 

### Steps to reproduce

1. Install [docker-compose-mode](https://melpa.org/#/docker-compose-mode) or any other derived mode from YAML.
2. Visit a file in that mode, eg, `docker-compose.yml`
3. Start lsp as normal.

### Expected behavior

1. `lsp-mode` checks `lsp-language-id-configuration` and finds there is no entry for `docker-compose-mode`
2. Grab the parent mode symbol with `(get 'docker-compose-mode 'derived-mode-parent)` 
3. `lsp-language-id-configuration` inludes `yaml-mode`, the parent mode, so that is used.

### Which Language Server did you use?

lsp-yaml

### OS

Windows

### Error callstack

```emacs-lisp
no error.
```

**Comment by yyoncho** [comment]
this will increase the complexity and the potential for errors - e. g. one should make sure that all derivative modes are before their parents. I prefer adding explicit mapping either by the mode or by the file extension.
