### ISSUE TITLE
[help] How to ignore specific flycheck warning messages for Python in lsp-mode?

### ISSUE THREAD

**Issue by avatar-lavventura** [emacs-lsp/lsp-mode#3061]
My goal is to configure `lsp` in order to ignore warning messages for [`flycheck`][1] in Python version. 

When lsp is not in use, flycheck reads from my `~/.pylintrc` file in order to ignore warning messsages. But when I enable `lsp-mode` it does not ignore the warning messages that I set in `~/.pylintrc` file.

**minimal.el**:
```
(defun flycheck-python-setup ()
  (flycheck-mode))
(require 'flycheck)
(require 'flycheck-mypy)
(add-hook 'after-init-hook #'global-flycheck-mode)
(add-hook 'after-init-hook #'global-flycheck-mode)
(add-to-list 'flycheck-disabled-checkers 'python-flake8)
(add-hook 'python-mode-hook
          (lambda ()
            (setq flycheck-python-pylint-executable "~/venv/bin/pylint")
            (setq flycheck-pylintrc "~/.pylintrc")
            (setq indent-tabs-mode  nil
                  python-indent-offset  4
                  tab-width         4)
            (let ((inhibit-message  t))
              )))
(use-package python :ensure nil)
(add-hook 'python-mode-hook #'flycheck-python-setup)
(flycheck-add-next-checker 'python-flake8 'python-pylint 'python-mypy)
```

Having following lines in order to enable `lsp-mode`, changes the result for `helm-flycheck`.

```
(add-hook 'python-mode-hook 'lsp)
(add-hook 'python-mode-hook #'lsp-deferred)
```
---------

```
❯ cat ~/.pylintrc
disable=D100,  C0305, C0303, W291,  C0111, R0801, W0703, C0103,
```

Related: [flycheck cannot find module for pylint](https://emacs.stackexchange.com/a/41048/18414), https://www.reddit.com/r/emacs/comments/b5lvx6/how_do_i_force_lspui_to_use_flake8/

> ```
> (add-hook 'python-mode-hook
>   (lambda ()
>     (setq flycheck-python-pylint-executable "<your path to>/pylint")
>     (setq flycheck-pylintrc "/home/tools/.pylintrc"))) 

  [1]: https://www.flycheck.org/en/latest/

**Comment by dsyzling** [comment]
What python language server are you using?

What is the state of your flycheck checkers - if you M-x flycheck-verify-setup, do you see the flycheckers you want enabled and are the links to the next checker correctly set? 

Typically lsp will be configured to be a flycheck checker and by default this will not chain onto other checkers. Pyls can be configured to call linters internally and you can enable this with configuration - errors will be returned via lsp from the various linters. However if you are using pyright you will have to setup lsp to chain to the other checkers you want to run - see below. I'm not sure if pylint is being run on your behalf by pyls whether there's any further customisation you would need for the pylintrc - I don't think should be necessary, it should be the same as running it from the command line.

I can configure pylint in my config and disable the warnings in ~/.pylintrc and everything works as expected. However I'm using pyright and I've configured lsp to chain to the checkers I want to run. I didn't need to tell pylint where my config file was it found it automatically in the root of home (after I generated it with pylint itself). All python packages were installed into a virtual environment using (mini) conda and I use pyvenv inside Emacs to switch to the required virtual environment. This is all running on Emacs 26.2 under Arch with the latest lsp packages, I have a similar config running under WSL2 with Ubuntu.

Here's a snapshot of my config, but here I've disabled pylint, configuring a chain of lsp -> flake8 -> mypy. I did run a quick check to verify that I could enable pylint, generate the pylintrc and then disable warnings - which worked fine. I suspect there's something in your config where the flycheck checkers are not running correctly or they're not working via pyls. 

``` elisp
(use-package lsp-pyright
  :ensure t
  :config
  (setq lsp-clients-python-library-directories '("/usr/" "~/miniconda3/pkgs"))
  (setq lsp-pyright-disable-language-service nil
        lsp-pyright-disable-organize-imports nil
        lsp-pyright-auto-import-completions t
        lsp-pyright-use-library-code-for-types nil
        lsp-pyright-multi-root nil
        ;; off basic or strict - basic is the default.
        ;; lsp-pyright-typechecking-mode "strict"
        lsp-pyright-venv-path "/home/dsyzling/miniconda3/envs"
        ;; Debugger can be debugpy or ptvsd (now deprecated)
        dap-python-debugger 'debugpy)
  ;; Ensure if we're running mypy that generated files do not cause change
  ;; notifications otherwise this leads to recurring diagnostic checks.
  (push "[/\\\\]\\.mypy_cache\\'" lsp-file-watch-ignored-directories)
  :hook (python-mode . (lambda ()
                         (require 'lsp-pyright)
                         (lsp-deferred))))

;; See https://github.com/flycheck/flycheck/issues/1762
(defvar-local my/flycheck-local-cache nil)

(defun my/flycheck-checker-get (fn checker property)
  (or (alist-get property (alist-get checker my/flycheck-local-cache))
      (funcall fn checker property))) 

(advice-add 'flycheck-checker-get :around 'my/flycheck-checker-get)

(add-hook 'lsp-managed-mode-hook
          (lambda ()
            (when (derived-mode-p 'python-mode)
              ;; Disable flycheck checkers we're not using
              (add-to-list 'flycheck-disabled-checkers 'python-pylint)
              (add-to-list 'flycheck-disabled-checkers 'python-pycompile)
              (setq my/flycheck-local-cache
                    '((lsp . ((next-checkers . (python-flake8 python-mypy)))))))))

```

**Comment by avatar-lavventura** [comment]
Thank you for valuable detailed response. Your config helped. I was able to solve my issue with the help of following answer: https://emacs.stackexchange.com/a/68300/18414. 

>```
> (setq lsp-pylsp-plugins-pylint-enabled t)
> (setq lsp-pylsp-plugins-pylint-args ["--rcfile=/<absolute-path-to-home-dir/.pylintrc"]) ;; or path to your project.
>```

**Comment by avatar-lavventura** [comment]
Sorry for updated response. I observe that the prevously linked answer does not work on my end.

`M-x flycheck-verify-setup` returns following:

```
Checkers that may run as part of the first checker's chain:

  python-flake8
    - may enable:         yes
    - executable:         Found at /home/alper/venv/bin/python3
    - configuration file: Found at "/home/alper/.config/flake8"
    - `flake8' module:    Found at "/home/alper/venv/lib/python3.8/site-packages/flake8/__init__.py"
    - next checkers:      python-mypy, python-pylint

  python-mypy
    - may enable:         yes
    - executable:         Found at /home/alper/venv/bin/mypy
    - configuration file: Found at "/home/alper/trade_bot/pyproject.toml"

Checkers that could run if selected:

  python-pycheckers  select
    - may enable:         yes
    - executable:         Found at /home/alper/.emacs.d/elpa/flycheck-pycheckers-20210414.2023/bin/pycheckers.py
    - configuration file: Found at "/home/alper/.pylintrc"
 ```

-------


`/home/alper/.pylintrc` contains `[flake8] ignore = D100` but it is not get disabled. I have created same file in the name for `/home/alper/.flake8rc` .  I am just lost why it is not working as it is

**Comment by dsyzling** [comment]
No problem, personally I think the many ways you can configure all of this is confusing and it differs between language servers - which just increases the complexity. 

Once again this will depend on if you're using pyls which can run the linter plug-ins internally. In this case if you run M-x flycheck-verify-setup you should see the first checker as 'lsp'. Something like this:
```
First checker to run:

  lsp (explicitly selected)
    - may enable: yes
    - may run:    t
```

Note, no other checkers are chained to lsp by default so flycheck will not be running linters, pyls will - if they are enabled of course. If you don't see the above then lsp isn't enabled in the buffer and hasn't been run as part of the python-mode hook. 

If lsp-pyls-plugins-flake8-enabled is enabled then pyls will run flake8 and report errors/warnings via the lsp diagnostics messages. You'll see them formatted in the flycheck buffer (flycheck-list-errors) tagged as (lsp).

I personally don't use pyls so configuring linters isn't something I'm an expert on. The developers of pyls wanted to reduce the configuration surface for all the linters so they implemented configuration sources which defaults to pycodestyle. So I think by default you're supposed to configure removal of warnings via pycodestyle config file. What I have found though is that a project local setup.cfg will work - you can define a flake8 section and add your warnings to ignore or other customisations.

You can however swap the configuration source to flake8 by doing the following:

``` elisp
(setq lsp-pyls-configuration-sources ["flake8"])
```

See the code for pyks-configuration-sources in lsp-pyls.el. If you shutdown your lsp workspace and reconnect it will then use flake8 as the config source. You can now define a "\~/.config/flake8" file - if you're on Linux ("\~/.flake8" didn't work for me) - review the docs for other platforms. Now with the configuration source set and a flake8 file in the correct location warnings and settings can be configured globally for the user. 

Hope that helps.
