### ISSUE TITLE
Cannot install due to dependency / dash-functional not found

### ISSUE THREAD

**Issue by clarkhenry** [emacs-lsp/lsp-mode#3063]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

Cannot download `lsp-mode` or `lsp-ui` from https://stable.melpa.org due to `dash-functional` dependency issue:

> Error (use-package): Failed to install lsp-mode: https://stable.melpa.org/packages/dash-functional-2.19.0.el: Not found

### Steps to reproduce

```emacs-lisp
(use-package lsp-mode
  :ensure t)
```

### Expected behavior

Install successfully.

### Which Language Server did you use?

`rls` and `rust-analyzer`

### OS

Linux

**Comment by clarkhenry** [comment]
Same error from melpa [unstable]

**Comment by yyoncho** [comment]
You most likely have outdated packages. Package dash-functional was removed more than a year ago and all packages that depend on it were updated. Deleting your elpa dir and reinstalling the packages should fix your issue. Note that dash-functional is never mentioned in this repository.
