### ISSUE TITLE
Semantic tokens desync with clangd after #2790

### ISSUE THREAD

**Issue by robbert-vdh** [emacs-lsp/lsp-mode#3064]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

Since commit 1f7ccca8047321cee20288646c89b55825868d83 (from #2790) I'm sometimes getting incorrect highlighting when using semantic tokens with clangd. This looks like something got desynced. A gif is worth a thousand words, so it looks like this:

https://user-images.githubusercontent.com/748520/131123206-3f6792f9-355a-48b0-ab4c-a287df853006.mp4

This also happens with `lsp-start-plain.el` after setting `lsp-enable-semantic-highlighting` to `t`.

### Steps to reproduce

1. `(setq lsp-enable-semantic highlighting t)`
2. Make sure clangd is installed and working.
2. Create/open a `.cpp` file containing:
   ```cpp
   #include <array>
   #include <atomic>
   
   constexpr std::atomic<std::array<int32_t, 4>> some_array{{1, 2, 3, 4}};
   ```

3. Delete the `constexpr` (`dw` in evil-mode, `M-d` in plain Emacs). Similar things happen in other situations, but this was the simplest reproducible example I could come up with.

### Expected behavior

`constexpr` disappears, and the rest of the text shifts to the left without the highlighting changing.

### Which Language Server did you use?

clangd

### OS

Linux

### Anything else?

I'm using clangd version 13.0.0, built from commit 1e1f7520279c93a59fa6511028ff40412065985e and Emacs 28.0.50.148625 compiled with `--with-native-compilation` (also tried a couple more recent builds but it also happens there).

**Comment by sebastiansturm** [comment]
@robbert-vdh could you try again with my fork at sebastiansturm/lsp-mode?

**Comment by robbert-vdh** [comment]
Got rid of the `(setq lsp-semantic-tokens-allow-delta-requests nil)` and tried https://github.com/sebastiansturm/lsp-mode/commit/bc29dbb6c7e59a5a1d4a37323473504f266b3426. Seems to work great! Also did some more testing with a couple of other cases that previously broke things (like defining templates).

**Comment by sebastiansturm** [comment]
thanks for testing, and thanks again for the precise bug report! Will open a PR then

**Comment by sebastiansturm** [comment]
closing this as the PR has been merged; please reopen if you find other corner cases
