### ISSUE TITLE
The lua client can not be started correctly

### ISSUE THREAD

**Issue by yuchunzhou** [emacs-lsp/lsp-mode#3065]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

When i opened a lua file, the emacs client will be frozen for a few minutes, i couldn't edit the lua source file, at the same time the cpu went high, the log is below  
```
LSP :: Connected to [lua-language-server:92951/starting].
LSP :: lua-language-server:92951 initialized successfully in folders: (/Users/frank)
Error processing message (error "Lisp nesting exceeds ‘max-lisp-eval-depth’").
LSP :: Too large file: Documents/emacs.d/.cache/lsp/lua-language-server/extension/server/script/parser/guide.lua skipped. The currently set size limit is: 100 KB, and the file size is: 138.339 KB.
LSP :: Too large file: .emacs.d/.cache/lsp/lua-language-server/extension/server/script/parser/guide.lua skipped. The currently set size limit is: 100 KB, and the file size is: 138.339 KB.
```

### Steps to reproduce

here is the elisp code
```lisp
(use-package lua-mode
  :mode "\\.lua\\'"
  :interpreter "lua"
  :hook (lua-mode . lsp-deferred)
  :init
  (setq lua-indent-level 4)
  (setq lua-indent-string-contents t))
```

### Expected behavior

when i open a lua source file with emacs, i can edit the file immediately

### Which Language Server did you use?

https://github.com/sumneko/lua-language-server

### OS

MacOS

**Comment by yyoncho** [comment]
> LSP :: lua-language-server:92951 initialized successfully in folders: (/Users/frank)

You have selected incorrect project root. Do not use your project folder as project root becase the server might scan it all. Use M-x lsp-workspace-folders-add/remove to fix it and the next time you are asked to import a project make sure that you pick the proper project root.
