### ISSUE TITLE
npm install fails when path is not `/usr/bin/npm` 

### ISSUE THREAD

**Issue by Nathan-Furnal** [emacs-lsp/lsp-mode#3066]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

Hi,

When I'm trying to install a server via `M-x lsp-install-server`, for example `html-ls`, it fails with :  

```
Unable to install vscode-html-languageserver-bin via `npm' because it is not present
``` 

### Steps to reproduce

Install `npm` with `nvm` (a version manager for node) instead of a global install. This makes `which node` return : 

``` 
home/ME/.nvm/versions/node/v16.8.0/bin/node # is included in PATH
```
instead of `/usr/bin/node` or something similar. 

### Expected behavior

Being able to install the servers all the same. 

### Which Language Server did you use?

Any server that uses `node` to be installed. 

### OS

Linux

**Comment by ericdallo** [comment]
not sure this is a issue with lps-mode, probably this should be configured on your emacs session to find the correct npm in PATH.

**Comment by Nathan-Furnal** [comment]
Would you advise I add the npm path to exec path in the lsp config?

**Comment by ericdallo** [comment]
Yes, mostly issues with program not found are related with emacs being launched with another shell than the user one, so the PATH var miss a lot of commands, I think you can confirm that launching emacs from terminal.

**Comment by Nathan-Furnal** [comment]
I have found a suitable fix, I installed [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell) which loads the shell's path and allows the expected behavior (being able to use npm and install the servers).
