### ISSUE TITLE
Unknown Notifications when using csharp/omnisharp server

### ISSUE THREAD

**Issue by mrcc912** [emacs-lsp/lsp-mode#3080]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

Warnings fire in lsp-mode while using csharp language with an omnisharp-server:

Warning (lsp-mode): Unknown notification: o#/msbuildprojectdiagnostics
Warning (lsp-mode): Unknown notification: o#/projectadded
Warning (lsp-mode): Unknown notification: o#/projectchanged

### Steps to reproduce

Create a new file and then compile it outside of emacs (I was using Unity3d so I tabbed over to that), then come back to emacs and move to get it to recheck the buffer.

### Expected behavior

Warnings should not fire

### Which Language Server did you use?

lsp-mode in csharp with an omnisharp server

### OS

Linux

### Anything else?

I am using Unity3D version 2019.4.29f1 with emacs 26.3

**Comment by yyoncho** [comment]
@razzmatazz

**Comment by razzmatazz** [comment]
Hey @mrcc912 are you using the latest lsp-mode? Because there has been `:notification-handlers` with `'ignore` added for all the methods. Could you check lsp-csharp.el/lsp-register-client on your version of the code to make sure?

**Comment by mrcc912** [comment]
I think I was on the latest MELPA-stable at the time of writing this, but when I updated to the latest version from MELPA these no longer fired, so closing this out as fixed. Thanks!
