### ISSUE TITLE
More detailed display of "mismatched type" error in Rust code

### ISSUE THREAD

**Issue by dbr** [emacs-lsp/lsp-mode#3089]
The "mismatched types" error is quite common, but I can't see an obvious way of getting any further details of this error from lsp-mode (the actual versus expected types)

For example, this is about all I can get in a mostly-default configuration of lsp-mode + lsp-ui:

![Screenshot showing the red error text](https://user-images.githubusercontent.com/509/132775575-2bc38317-1c7c-4fe9-a47f-232dbe08ab79.png)

If I run `cargo check` in a terminal, the missing information is visible like so:

```
[E0308]: mismatched types
  --> example.rs:57:30
   |
57 |         batches.push(1.2);
   |                      ^^^ expected struct `arrow::record_batch::RecordBatch`, found floating-point number
```

It would be great if this was visible somehow - I expected to see the full error details maybe when hovering (which currently just shows `f64` in the above example)

Thanks!

**Comment by yyoncho** [comment]
Use lsp-ui-sideline-diagnostic-max-lines. If it doesn't work, report it in lsp-ui project.

**Comment by dbr** [comment]
Ah, sorry, I didn't realize lsp-ui was a separate repo!

```lisp
(setq lsp-ui-sideline-diagnostic-max-lines 3)
```
works perfectly, thank you!
