### ISSUE TITLE
Ability to disable hint diagnostics request

### ISSUE THREAD

**Issue by herberthamaral** [emacs-lsp/lsp-mode#3104]
First of all: thanks for all the work done in this project! I (we) really appreciate it!

So I've been trying to disable a very annoying "error" for some months now: a hint diagnostic that both is visually distracting (because I can't do much about it) and misleading (since it adds up to the error count):

![image](https://user-images.githubusercontent.com/92361/133777815-f3430c4e-bddd-4801-a5c7-7b2ad4d3b4ed.png)

I try to read a bunch of code from flycheck, lsp-mode, pyright and finally decided to start opening some issues. [Looks like lsp-mode asks pyright to send hint diagnostics](https://github.com/microsoft/pyright/issues/2307), so I'm wondering if we could have a way to NOT send this kind of request, just in order to not have it displayed anywhere in the editor.

I am aware of flycheck error filtering, but it is not global: it is only meant to filter errors in the error list buffer.

**Comment by yyoncho** [comment]
Before looking for other solutions, have you tried prefixing unused args with `_`?

**Comment by herberthamaral** [comment]
Hello! Just tried, doesn't work.

**Comment by dsyzling** [comment]
Did you want to simply disable that particular warning message from the type checker? If so have you tried adding:

# type: ignore 

to the line containing the warning - this should tell pyright to ignore that particular warning, this would also work if you were using mypy.

**Comment by herberthamaral** [comment]
Those are not type errors, so it doesn't ignore the diagnostic when I add `  # type: ignore`.

**Comment by yyoncho** [comment]
@herberthamaral I tested with pyright and using `_` for variable name fixes the issue.

**Comment by dsyzling** [comment]
I think the intention from the pyright team appears to be that it wasn't to be displayed as a diagnostic warning but a 'syntax highlight' indicating the variable is unused. I haven't checked any further on what supplemental information they may be supplying to indicate that distinction:
https://github.com/microsoft/pyright/issues/1118

**Comment by herberthamaral** [comment]
https://github.com/emacs-lsp/lsp-pyright/issues/39#issuecomment-882445117 > This solved the problem for me. However I suspect it is not enough for every scenario. I'm closing this for now. Thanks, everybody!
