### ISSUE TITLE
lsp-angular path to language server is not correct in a windows environment

### ISSUE THREAD

**Issue by samwdp** [emacs-lsp/lsp-mode#3105]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

When using LSP mode for Angular projects in Windows, the location that is being checked does not exist. I think the problem is the path that is being built assumes that all global node modules are put in a ```/lib/node_modules``` location. I have installed node version v14.17.6 and global modules are placed in ``` %USERPROFILE%\npm\node_modules ```. There is no lib folder.
![image](https://user-images.githubusercontent.com/7193913/133797240-d28d07fd-dbe4-4849-abbc-2aacb000096a.png)

Here is the output of my angulr-ls::stderr
```
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'C:\Users\samwd\AppData\Roaming\npm\lib\node_modules\@angular\language-server'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Process angular-ls stderr finished
```

If this is a problem with my environment then any help will be appreciated thouth this is basically a fresh install of windows 10 and Node JS

### Steps to reproduce

Windows 10

Doom Emacs with LSP enabled

Basic ng new application

### Expected behavior

The angular language server starts with no errors

### Which Language Server did you use?

lsp-angular

### OS

Windows

### Error callstack

```emacs-lisp
angular-lsp::stdrr

internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'C:\Users\samwd\AppData\Roaming\npm\lib\node_modules\@angular\language-server'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Process angular-ls stderr finished
```
```


### Anything else?

_No response_

**Comment by samwdp** [comment]
this is documented in the node modules documentation [here](https://docs.npmjs.com/cli/v8/configuring-npm/folders)

Windows does not have a "lib" folder so the lsp should accomodate this. The only fix is to add a --prefix when installing the language server but this should not be the case

**Comment by asmodeus812** [comment]
@samwdp could you elaborate further. This needs to be addressed, i stumbled upon the same issue while playing around with lsp

**Comment by asmodeus812** [comment]
This needs to be looked at, it will cause issues in the long run. Below is what i used to force install it into the /lib subfolder

`npm install --prefix C:/Users/<username>/AppData/Roaming/npm/lib @angular/language-service@next typescript @angular/language-server -g`

**Comment by WMaxZimmerman** [comment]
Is there any update on this? I am also running into this issue now. I am happy to create variable that will default the addition of 'lib/' but allow for us Windows folk to override the value. If that is an alright solution I can get that started today. I do not do a lot in the node ecosystem and so this is the first I have run into. If it should be handled in a different way i'm happy to just leave mine modified.

**Comment by yyoncho** [comment]
@WMaxZimmerman maybe there is a need just to add one `if` to handle windows/linux?

**Comment by WMaxZimmerman** [comment]
@yyoncho sorry for the delay. That would likely work as well. If no one has done that I may try to create a PR for it in the next week or so (I was pulled of of angular work for a bit but will be back at it soon).

**Comment by WMaxZimmerman** [comment]
@yyoncho I made this PR. Not sure if it will get approved, but it does work on my end

**Comment by WMaxZimmerman** [comment]
https://github.com/emacs-lsp/lsp-mode/pull/3562

**Comment by yyoncho** [comment]
Thank you @WMaxZimmerman
