### ISSUE TITLE
lsp-ui-sideline-show-diagnostics not showing diagnostic

### ISSUE THREAD

**Issue by sethen** [emacs-lsp/lsp-mode#3109]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

The lsp isn't showing diagnostics in the sideline no matter what I change.  Enabling and disabling, starting and restarting -- nothing seems to work.  According to this guide for lsp-ui (https://emacs-lsp.github.io/lsp-mode/tutorials/how-to-turn-off/) setting the variable `lsp-ui-sideline-show-diagnostics` should work but it doesn't.  However, you can pull up the diagnostic buffer and it gives you the error it's referring to.

I've attached a video trying to toggle this mode on and off for your convenience.

https://user-images.githubusercontent.com/1493530/134278794-10d287df-1b20-427d-8274-668a68fd93b0.mp4

### Steps to reproduce

Here's the code I am using for `lsp-mode`

```elisp
(require 'use-package)

(use-package lsp-mode
  :commands (lsp lsp-deferred)
  :hook
  (typescript-mode . lsp-deferred)
  (web-mode . lsp-deferred)
  :init
  (setq gc-cons-threshold 100000000)
  (setq lsp-idle-delay 0.500)
  (setq read-process-output-max (* 1024 1024)))

(provide 'sethen-lsp-mode)
```

These are the only settings for my lsp.  Use these settings, install the `ts-ls` server with `lsp-install-server` and boot up a typescript file.

### Expected behavior

The sideline show give me the diagnostics for the line in question.

### Which Language Server did you use?

`ts-ls`

### OS

Linux

**Comment by yyoncho** [comment]
AFACS you are using flymake, try using flycheck.

**Comment by sethen** [comment]
> AFACS you are using flymake, try using flycheck.

Yeah that was it, thanks!
