### ISSUE TITLE
How to prevent `()` added during company completions

### ISSUE THREAD

**Issue by avatar-lavventura** [emacs-lsp/lsp-mode#3116]
After opening multiple issues related to prevent `()` added during company completions, I end up here based on recommendations.

In [company-mode][1], when I apply `company-complete-selection`, it completes variable but sometimes adds `()` at the end of it. As I understand it depends on the backend which uses `python-lsp-server`.

Would it be possible to prevent this in all cases?

Example:
[![enter image description here][2]][2]

-------
which completed as: `self.logged_jobs_to_process()`

Based on the comment in https://emacs.stackexchange.com/a/68599/18414

> As you correctly noted at the Company Q&A, Value of `c-a-p-f: (lsp-completion-at-point)` shows `lsp-mode` is responsible for the completion. To be more precise, I expect that would be not `lsp-mode` itself, but the `Python server` you have installed. 

Related discussion in Company: https://github.com/company-mode/company-mode/discussions/1218#discussioncomment-1359841

Related opened issues:
- [How to prevent `()` added during company completions](https://emacs.stackexchange.com/questions/68595/how-to-prevent-added-during-company-completions)
- https://github.com/python-lsp/python-lsp-server/issues/89
- https://github.com/company-mode/company-mode/discussions/1218#discussioncomment-1359841

------

my setup:

```
(add-hook 'after-init-hook 'global-company-mode)
(setq company-auto-commit t)
(setq company-auto-complete t)
(global-set-key (kbd "C-c C-k") 'company-complete)
(setq company-frontends
      '(company-pseudo-tooltip-unless-just-one-frontend
        company-preview-frontend
        company-echo-metadata-frontend))
```

-------

`M-x company-diag` returns:

```
Emacs 28.0.50 (x86_64-pc-linux-gnu) of 2021-09-01 on home
Company 0.9.13

company-backends: (company-bbdb company-semantic company-cmake company-capf company-clang company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)

Used backend: company-capf
Value of c-a-p-f: (lsp-completion-at-point)
Major mode: python-mode
Prefix: "None"
Completions:
  #("None" 0 4 (lsp-completion-item #s(hash-table size 7 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("label" #("None" 0 4 (match-data (0 4 0 1 1 2 2 3 3 4))) "kind" 14
"sortText" "aNone" "insertText" "None" "data" #s(hash-table size 1 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("doc_uri" "file:///home/alper/ebloc-broker/broker/Driver.py"))
"_emacsStartPoint" 3652)) lsp-sort-text "aNone" lsp-completion-start-point 3652 lsp-completion-markers (3652 #<marker (moves after insertion) at 3656 in Driver.py>) lsp-completion-prefix
"None" match-data (0 4 0 1 1 2 2 3 3 4) face (completions-common-part))) " (Keyword)"
```

  [1]: https://company-mode.github.io
  [2]: https://i.stack.imgur.com/DG0OK.png

**Comment by yyoncho** [comment]
company-diag seems to be from something different, not the screenshot. First, it is server bug if it is inserting () on a wrong place. In your case, I believe the only way to solve it is to disable snippets by setting `lsp-enable-snippet` to nil. Make sure to restart the server/emacs.

**Comment by avatar-lavventura** [comment]
Thanks. Doing `(setq lsp-enable-snippet nil)` solved it.
