### ISSUE TITLE
Omnisharp-Roslyn not available in the list of installable servers

### ISSUE THREAD

**Issue by mcraveiro** [emacs-lsp/lsp-mode#3118]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

According to the documentation [1], Omnisharp-Roslyn should be available from the list of installable servers:

> Installation
>
> This Server supports automatic install. Install this language server with ```M-x lsp-install-server RET omnisharp RET```.
> 
> Supports automatic installation.

[1] https://emacs-lsp.github.io/lsp-mode/page/lsp-csharp-omnisharp/

### Steps to reproduce

With latest lsp-mode, ```omnisharp``` is not selectable from the list.

### Expected behavior

```omnisharp``` should be part of the list.

### Which Language Server did you use?

Omnisharp-Roslyn [1]

[1] https://github.com/OmniSharp/omnisharp-roslyn

### OS

Linux

**Comment by ericdallo** [comment]
@mcraveiro could you try with `C-u` `M-x` `lsp-install-server`? we don't show the server to install when it's already installed or lsp-mode find the program in PATH

**Comment by mcraveiro** [comment]
Hi @ericdallo, many thanks for the prompt reply, I was just about to update the ticket! :-) this is exactly the problem, the server was already installed but for some reason its not kicking in when I open up a C# file. I've uninstalled the server and then it correctly showed up on the list. Perhaps it would be nice to show installed servers with a comment ("already installed")?

**Comment by ericdallo** [comment]
Yeah, you are not the first one suggesting that, IMO we can show that and lsp-mode just force install if user select that.
WDYT @yyoncho ?

**Comment by mcraveiro** [comment]
Argh, can you believe it, I was calling ```(lsp-mode)``` in my C# hooks instead of ```(lsp)```. Typical user error! :-) all working now, thanks!

**Comment by mcraveiro** [comment]
> Yeah, you are not the first one suggesting that, IMO we can show that and lsp-mode just force install if user select that.
> WDYT @yyoncho ?

Ah actually that is a very nice idea! I mean you can just show ```omnisharp``` in the list of servers, and when the user selects it you could ask: "server is already installed, would you like to reinstall?" This would be very helpful in cases such as mine methinks.
