### ISSUE TITLE
Add node_modules directory to lsp-file-watch-ignored-directories

### ISSUE THREAD

**Issue by DeadMeme5441** [emacs-lsp/lsp-mode#3123]
I think adding a node_modules regex to the list of ignored directories for file-watch by lsp would be great because every JS framework uses it, and developers seldom edit the module files directly.

**Comment by ericdallo** [comment]
We already have it https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el#L325

**Comment by DeadMeme5441** [comment]
Sorry, I'm a little new to emacs, but does the regex search for nested directory at any level or only at the first directory level?
This one : "[/\\\\]node_modules"

**Comment by ericdallo** [comment]
I think @yyoncho knows that better, but I guess that just the first level is considered

**Comment by DeadMeme5441** [comment]
Okay thank you! I'll try changing my config to add recursive directories, and if I succeed I'll make a PR for it. Thanks for clarifying :)
