### ISSUE TITLE
lsp-pwsh fails to install server

### ISSUE THREAD

**Issue by josteink** [emacs-lsp/lsp-mode#3125]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

When invoking `powershell-mode` for the first time, `lsp-mode` offers to install the server for `lsp-pwsh`.

The server it speaks of is `PowerShellEditorServices` and can be found here https://github.com/PowerShell/PowerShellEditorServices/releases/tag/latest

However when attempting to download and extract this archive, something goes wrong and results in an empty pwsh-folder with an empty logs-folder.

See below:

````
jostein@thinkpad-t480s:~/.emacs.d/.cache/lsp$ ls -la
total 28
drwxrwxr-x 7 jostein jostein 4096 sep.  29 07:48 .
drwxrwxr-x 3 jostein jostein 4096 okt.   1  2020 ..
drwxrwxr-x 8 jostein jostein 4096 des.  14  2020 npm
drwxrwxr-x 6 jostein jostein 4096 april 15 08:30 omnisharp-roslyn
drwxrwxr-x 3 jostein jostein 4096 sep.  29 07:48 pwsh
drwxrwxr-x 2 jostein jostein 4096 feb.   8  2021 rust
jostein@thinkpad-t480s:~/.emacs.d/.cache/lsp$ find pwsh
pwsh
pwsh/logs
````

Tested on Ubuntu 21.04 with Emacs from Git master.

### Steps to reproduce

Steps to reproduce:

1. Ensure that the `pwsh` lsp-server is not installed (`rm -rf ~/.emacs.d/.cache/lsp/pwsh`)
2. Starts Emacs
3. Install `lsp-mode` from git or MELPA
4. Install `powershell-mode` (MELPA-package `powershell`)
5. Open a powershell-file (ps1-extension)
6. Ensure `lsp-mode` is activated.
7. Observe that you are asked to install a LSP-server for PowerShell, and are offered once choice only (`pwsh-ls`)
8. Confirm that you want to install `pwsh-ls`.

**Observed that:**

Language server is not installed. Language server folder is created, but remains empty:

````
jostein@thinkpad-t480s:~/.emacs.d/.cache/lsp$ ls -la
total 28
drwxrwxr-x 7 jostein jostein 4096 sep.  29 07:48 .
drwxrwxr-x 3 jostein jostein 4096 okt.   1  2020 ..
drwxrwxr-x 8 jostein jostein 4096 des.  14  2020 npm
drwxrwxr-x 6 jostein jostein 4096 april 15 08:30 omnisharp-roslyn
drwxrwxr-x 3 jostein jostein 4096 sep.  29 07:48 pwsh
drwxrwxr-x 2 jostein jostein 4096 feb.   8  2021 rust
jostein@thinkpad-t480s:~/.emacs.d/.cache/lsp$ find pwsh
pwsh
pwsh/logs
````

### Expected behavior

Language server to be downloaded and unpacked.

### Which Language Server did you use?

lsp-pwsh

### OS

Linux

### Error callstack

```emacs-lisp
No error in callstack.
```

### Anything else?

If language server is downloaded and unpacked manually in the same location ('~/.emacs.d/.cache/lsp/pwsh'), 'lsp-pwsh' works perfectly, so it seems to be an issue with installation only.

**Comment by yyoncho** [comment]
What is the content of `*lsp-install...` buffer?

**Comment by josteink** [comment]
There's no `*lsp-install...` buffer, only `*lsp-log*`. The contents of that buffer is like this:

````
Found the following clients for /home/jostein/sample-repo/script.ps1: (server-id pwsh-ls, priority -1)
The following clients were selected based on priority: (server-id pwsh-ls, priority -1)
````

**Comment by josteink** [comment]
Whee. Thanks for the quick fix!
