### ISSUE TITLE
Minibuffer can grow too big with function definitions

### ISSUE THREAD

**Issue by JulienPalard** [emacs-lsp/lsp-mode#3133]
- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections

### Bug description

Minibuffer can grow too big, espcially when I use a big font, like when I'm presenting to a room:
 
![2021-10-02-172553_1920x1080_scrot](https://user-images.githubusercontent.com/239510/135722865-c664a90b-1e7a-4f6f-89af-666007bf92b5.png)

### Steps to reproduce

Using the following config:

```lisp
(require 'use-package)
(use-package lsp-mode
  :ensure t
  :hook ((python-mode) . lsp)
)
(use-package lsp-jedi
  :ensure t)
```

open a Python file, type `open(` and wait for the too-big minibuffer to show.

### Expected behavior

I'd like the minibuffer to stay mini, like a single-line max.

### Which Language Server did you use?

[lsp-jedi](https://github.com/fredcamps/lsp-jedi).

### OS

Linux

**Comment by yyoncho** [comment]
can you test with changing lsp-signature-doc-lines  ?

**Comment by JulienPalard** [comment]
Wow, I set it to 1 and it's way better, it's now 3 lines:

```text
open(file: Union[str, bytes, int], mode: str=..., buffering: int=..., encoding: Optional[str]=..., errors: Optional[str]=..., newline: Optional[str]=..., clos$
Open file and return a stream.  Raise OSError upon failure.
Truncated...
```

I think I can accept it like this, even if I'm not a big fan of having one line occuped just to tell it's truncated.

Sorry for missing it from the documentation!
