### ISSUE TITLE
LSP Eslint Server install fails (Shell Command Error)

### ISSUE THREAD

**Issue by vikigenius** [emacs-lsp/lsp-mode#3136]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [x] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

I try to install lsp eslint server using lsp-install-server RET eslint RET

It fails with the following message in Shell Command Output

```
[/tmp/extjHiv1W.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/extjHiv1W.zip or
        /tmp/extjHiv1W.zip.zip, and cannot find /tmp/extjHiv1W.zip.ZIP, period.
```

I actually tried to unzip the file myself in question and that produces the same error as well

### Steps to reproduce

Uninstall any existing eslint installations. Run M-x lsp-install-server RET eslint RET

See the Shell Command Output buffer for errors.

eslint fails to install.

### Expected behavior

Eslint should be able to install properly

### Which Language Server did you use?

lsp-eslint

### OS

Linux

**Comment by yyoncho** [comment]
What is the content of /tmp/extjHiv1W.zip ?
