### ISSUE TITLE
rust-analyzer lsp-rust-analyzer-expand-macro output should be syntax highlighted

### ISSUE THREAD

**Issue by alanz** [emacs-lsp/lsp-mode#3137]
rust-analyzer has a command [lsp-rust-analyzer-expand-macro](https://github.com/emacs-lsp/lsp-mode/blob/8f9259af6fc80a609c2c068d0f59c371205aca89/clients/lsp-rust.el#L955) that opens a separate transient buffer with the results of expanding the macro at point, presenting rust source code.

The buffer comes up in "special-mode", but should be in "rust-mode" so that we get syntax highlighting.

**Comment by kiennq** [comment]
Maybe something like this?
``` elisp
(setq lsp-rust-analyzer-macro-expansion-method
      (-compose 'lsp-rust-analyzer-macro-expansion-default (lsp-get-renderer "rust")))
```

**Comment by alanz** [comment]
Thanks, works great.
