### ISSUE TITLE
`xref-find-references` doesn't work

### ISSUE THREAD

**Issue by rrudakov** [emacs-lsp/lsp-mode#3138]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

emacs version: `GNU Emacs 28.0.60 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4) of 2021-10-04`

### Steps to reproduce

Execute `M-x xref-find-references` command.

### Expected behavior

Pop-up with references is shown.

### Which Language Server did you use?

lsp-java

### OS

Linux

### Error callstack

```emacs-lisp
Debugger entered--Lisp error: (wrong-type-argument (or eieio-object class) #s(xref-item :summary #("    return baseService.profilePostJson(serializeOb..." 23 88 (face highlight)) :location #s(xref-file-location :file "/home/rrudakov/Work/EPAM/personalization-service/p..." :line 121 :column 23)) obj)
  #<subr eieio-oref>(#s(xref-item :summary #("    return baseService.profilePostJson(serializeOb..." 23 88 (face highlight)) :location #s(xref-file-location :file "/home/rrudakov/Work/EPAM/personalization-service/p..." :line 121 :column 23)) location)
  eieio-oref--closql-oref(#<subr eieio-oref> #s(xref-item :summary #("    return baseService.profilePostJson(serializeOb..." 23 88 (face highlight)) :location #s(xref-file-location :file "/home/rrudakov/Work/EPAM/personalization-service/p..." :line 121 :column 23)) location)
  apply(eieio-oref--closql-oref #<subr eieio-oref> (#s(xref-item :summary #("    return baseService.profilePostJson(serializeOb..." 23 88 (face highlight)) :location #s(xref-file-location :file "/home/rrudakov/Work/EPAM/personalization-service/p..." :line 121 :column 23)) location))
  slot-value(#s(xref-item :summary #("    return baseService.profilePostJson(serializeOb..." 23 88 (face highlight)) :location #s(xref-file-location :file "/home/rrudakov/Work/EPAM/personalization-service/p..." :line 121 :column 23)) location)
  helm-xref-candidates-27(#f(compiled-function () #<bytecode -0x1cf6488abc48913a>) ((window . #<window 177 on BaseService.java>) (display-action) (auto-jump)))
  helm-xref-show-xrefs-27(#f(compiled-function () #<bytecode -0x1cf6488abc48913a>) ((window . #<window 177 on BaseService.java>) (display-action) (auto-jump)))
  xref--show-xrefs(#f(compiled-function () #<bytecode -0x1cf6488abc48913a>) nil)
  xref--find-xrefs(#("profilePostJson" 0 15 (identifier-at-point t fontified t face (tree-sitter-hl-face:function tree-sitter-hl-face:function\.method))) references #("profilePostJson" 0 15 (identifier-at-point t fontified t face (tree-sitter-hl-face:function tree-sitter-hl-face:function\.method))) nil)
  xref-find-references(#("profilePostJson" 0 15 (identifier-at-point t fontified t face (tree-sitter-hl-face:function tree-sitter-hl-face:function\.method))))
  funcall-interactively(xref-find-references #("profilePostJson" 0 15 (identifier-at-point t fontified t face (tree-sitter-hl-face:function tree-sitter-hl-face:function\.method))))
  command-execute(xref-find-references)
```

**Comment by yyoncho** [comment]
First, it looks more like helm-xref issue. I believe that it will go away after reinstalling the package. Given the date of emacs compilation, I suspect that you have byte-compiled these packages with older emacs - if that's the case, better to reinstall all packages.

**Comment by rrudakov** [comment]
@yyoncho thanks for the response. You're right the issue is related to `helm-xref` package (there is no error without it). Unfortunately reinstalling it won't help, probably it's incompatible with recent version of emacs (it's built from `emacs-28` git branch).

**Comment by marcel-valdez** [comment]
I ran into this issue as well and updating helm-xref to the latest version fixed the issue for me.
