### ISSUE TITLE
Merge emacs-ccls into lsp-mode?

### ISSUE THREAD

**Issue by MaskRay** [emacs-lsp/lsp-mode#3161]
I haven't written any decent elisp code for ~3 years now and admittedly I have forgotten the little elisp knowledge I used to have. Upgrading doom-emacs has been a challenge for me as it'd be difficult to deal with possible breakage. (Also, sorry to admit that but I have also shifted some editor usage to neovim.)
I am not able to properly maintain https://github.com/MaskRay/emacs-ccls anymore.
There has been a few client-side issues I would probably never know how to address.

Would it be a good idea to merge emacs-ccls into lsp-mode and take advantage of the large community? :)

If you are interested, please let me know. If you use emacs-ccls, please show your interest, it may help someone to get decided:)

The package (emacs-ccls) exists to support a few icing on the cake:

* call/inheritance/member hierarchies
* `ccls-semantic-highlight.el`: identifier based semantic highlight (different from LSP semantic tokens)
* `ccls-code-lens.el`: I guess lsp-mode likely has equivalent features.

Feel free to rename functions or variables. I still know how to adapt my key bindings:)

**Comment by yyoncho** [comment]
Sounds good to me. As an alternative since ccls is a pretty big package and also it will be a breaking change to delete the original package I suggest moving the repo under emacs-lsp organization.
