### ISSUE TITLE
lsp cannot jump to internal definition in C#

### ISSUE THREAD

**Issue by serezlan** [emacs-lsp/lsp-mode#3172]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

LSP cannot jump into built-in definition of class/funtion in C#.

### Steps to reproduce

Using basic hello world, try to jump into Console or WriteLine definition.

### Expected behavior

Emacs will decompile and show definition of Console class or WriteLine method.

### Which Language Server did you use?

csharp:11134 

### OS

Linux

### Anything else?

[log.txt](https://github.com/emacs-lsp/lsp-mode/files/7430935/log.txt)

**Comment by serezlan** [comment]
Ah.. You're right. It's an older version of lsp.

Anyway, I update my system now I can see two option for csharp ls:

- Omnisharp roslyn
- - csharp-ls
- 
I still can't get jump to MD though. 
Am I missing something?
[log.txt](https://github.com/emacs-lsp/lsp-mode/files/7445297/log.txt)
[log-csharp.txt](https://github.com/emacs-lsp/lsp-mode/files/7445300/log-csharp.txt)

**Comment by razzmatazz** [comment]
Hey @serezlan

Would you be willing to try newer version of csharp-ls (which has just been released). Otherwise I'd ask you to open an issue on https://github.com/razzmatazz/csharp-language-server repo instead, as this appears not to be related to `lsp-mode` project per-se.

**Comment by serezlan** [comment]
Ok, I'll move this issue to csharp-ls.
