### ISSUE TITLE
LSP hangs in C# mode.

### ISSUE THREAD

**Issue by jack-faller** [emacs-lsp/lsp-mode#3176]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

Typing in a C# buffer is generally laggy, and hangs sometimes when hitting tab to get a completion.
I did a benchmark and the most run function was an unnamed lambda.
After activating the io logging, things really slowed down, after what would be about a second of normal typing (but longer due to the logging) the log buffer was much larger in size than it is in other lsp-modes.
The attached file is the log from typing System.<tab> and getting completions, this took almost a minute with logging on.
[lsp-log-omnisharp.zip](https://github.com/emacs-lsp/lsp-mode/files/7446121/lsp-log-omnisharp.zip)
For reference, I'm using emacs 27.2 and lsp-doctor prints OK for all bullet points.

### Steps to reproduce

The issue seems to occur mainly in files that related to the godot game engine and its libraries.

### Expected behavior

Typing is not slow.

### Which Language Server did you use?

Omnisharp-Roslyn

### OS

Linux

**Comment by razzmatazz** [comment]
could you check if using `csharp-ls` for a server (experimental) fixes your performance issue? if it does then emacs-lsp is most probably not at fault ant issue needs to be reported to `omnisharp-roslyn` project

**Comment by yyoncho** [comment]
Can you provide profiler report as described in https://emacs-lsp.github.io/lsp-mode/page/performance/

**Comment by yyoncho** [comment]
(also test with lsp-ui-doc turned off)

**Comment by jack-faller** [comment]
The issue seems to go away when using csharp-ls, and lsp-ui-mode doesn't make a difference.
I don't have the profiler report still (and it's a pain to get because the lag is inconstant), but I remember lsp-request-while-no-input being the main culprite.

**Comment by razzmatazz** [comment]
@jack-faller  I guess we can close it because it is not related to lsp-mode, right?
