### ISSUE TITLE
lsp-ensure-server function has become interactive

### ISSUE THREAD

**Issue by matteolel** [emacs-lsp/lsp-mode#3185]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

After the commit d92ced26d9d8bf03ce1c4cc3aa6026f32b2cd216 , the 'lsp-ensure-server' asks for prompt the server id, ignoring the passed server id.

### Steps to reproduce

In my code:
`(lsp-ensure-server 'xmlls)`

### Expected behavior

Before d92ced26d9d8bf03ce1c4cc3aa6026f32b2cd216 , the xmlls server was installed without any user prompt.
Now, user must type the server id in the mini-buffer.

### Which Language Server did you use?

xmlls

### OS

Linux

### Anything else?

I suppose the problem was removing `nil` from ` (lsp-install-server server-id)` call

**Comment by ericdallo** [comment]
Thanks for the report, I made a fix for this right now

**Comment by matteolel** [comment]
Thanks!!
