### ISSUE TITLE
Server process working directory is not the root of the project

### ISSUE THREAD

**Issue by nilehmann** [emacs-lsp/lsp-mode#319]
Currently, the server process is started in the directory of the first file visited and not the root of the project. For pyls this conflicts with the pyls-mypy plugin, because mypy will look for a configuration file in the current working directory (it will not try to find it in parent directories).

**Comment by MaskRay** [comment]
I think this is a server-side plugin issue. It should use the `:rootUri` parameter.

**Comment by rossabaker** [comment]
I'm having the same problem in lsp-scala.  The language server might be made to respect the passed in `:rootUri`, but things like logging have already started, so it starts a log in the directory of the first file I visit.

**Comment by rossabaker** [comment]
This is my workaround for now.  I don't claim that this is a good idea:

```emacs-lisp
(defun lsp-scala--run-from-root (orig &rest args)
  (let* ((client (car args))
         (lang-id (funcall (lsp--client-language-id client) (current-buffer))))
    (if (equal "scala" lang-id)
        (let ((default-directory (file-truename (funcall (lsp--client-get-root client)))))
          (apply orig args))
      (apply orig args))))
(advice-add 'lsp--start :around #'lsp-scala--run-from-root)
```

**Comment by yyoncho** [comment]
Fixed with https://github.com/emacs-lsp/lsp-mode/pull/486
