### ISSUE TITLE
Feature request: command to upgrade (or reinstall) all installed LSP servers

### ISSUE THREAD

**Issue by peterbecich** [emacs-lsp/lsp-mode#3190]
Feature request

> Is your feature related or already mentioned on [the wishlist](https://github.com/emacs-lsp/lsp-mode/discussions/2892)? 

I don't believe so

Can all installed LSP servers be upgraded automatically? Can `lsp-mode` provide a command to upgrade or re-install all LSP servers?

Something like
`M-x lsp-upgrade`

A.f.a.i.k. the current best option is to re-install each server individually, i.e. to reinstall the Purescript LSP Server: `M-x lsp-install-server` and select `pursls (Already installed)`.

Thank you

**Comment by peterbecich** [comment]
`lsp-update-server` covers most of this:
https://github.com/emacs-lsp/lsp-mode/blob/828c6c234a3231670ba5649666652e22a9bc4f35/lsp-mode.el#L7545-L7564

**Comment by ericdallo** [comment]
Yeah, we already have `lsp-update-server` as a public command, maybe we could have `lsp-update-all-servers`?

**Comment by peterbecich** [comment]
This may not work correctly: https://github.com/emacs-lsp/lsp-mode/issues/3754
