### ISSUE TITLE
Regular expression too big when auto complete

### ISSUE THREAD

**Issue by serezlan** [emacs-lsp/lsp-mode#3199]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

Auto complete failed on large project.

### Steps to reproduce

So far this happened only on one of my private project with large amount of files.

- Open the file.
- Try to autocomplete one of the variable within that class.

### Expected behavior

emacs shows suggestion list.e

### Which Language Server did you use?

omnisharp e

### OS

Linux

### Anything else?

[lsp-log.zip](https://github.com/emacs-lsp/lsp-mode/files/7509745/lsp-log.zip)
Here's my log

**Comment by yyoncho** [comment]
cc @kiennq

**Comment by serezlan** [comment]
I managed to solve this issue. It appears the problem happened for two reason:

- Really huge folders/files to watch (2000+ folders)
- aggressive setting of company completion (company-idle-timer is 0)

So, I exclude one folder that is not only has huge subfolders and also not important. And then set company-idle-timer to default value (0.2). And now the laptop is singing again :)
