### ISSUE TITLE
How to make custom requests to the server?

### ISSUE THREAD

**Issue by Trevoke** [emacs-lsp/lsp-mode#320]
Hi,

I'm using this as a client for Elixir, and the server has a capability that I'd like to take advantage of, but it means I need to be able to make some additions to lsp-mode and I don't know how to do that... Nor can I find documentation, and I'm still confused by Microsoft's LSP page as to where the documentation actually is, so I'm coming to you for help, because hopefully you've figured it out and you can point me in the right direction.

Thanks!

**Comment by alanz** [comment]
@Trevoke the haskell client uses execute-command to send additional client commands, see https://github.com/emacs-lsp/lsp-haskell/blob/master/lsp-haskell.el#L37

**Comment by Trevoke** [comment]
Awesome, thank you.
