### ISSUE TITLE
Request: embark and prefix-help-command

### ISSUE THREAD

**Issue by jdtsmith** [emacs-lsp/lsp-mode#3203]
[embark](https://github.com/oantolin/embark) offers `embark-prefix-help-command` which provides a really nice interactive key binding interface, similar to but in some ways more powerful than which-keys. I notice that the lsp-mode prefix binding does not support prefix-help-command.  It would be great if in addition to the which-keys integration, lsp-mode also supported the normal prefix-help-command, enabling `embark-prefix-help-command` to work automatically.

**Comment by yyoncho** [comment]
> I notice that the lsp-mode prefix binding does not support prefix-help-command

Do you know what is needed to support this?

**Comment by jdtsmith** [comment]
Embark just gives a nicer interface to the Emacs default `prefix-help-command` functionality:

```
Command to run when ‘help-char’ character follows a prefix key.
This command is used only when there is no actual binding
for that character after that prefix key.
```

So every normal prefix key in a keymap supports it out of the box (e.g. `C-x C-h`).  I'm not sure what lsp-mode would need to do to support the basic prefix-help, but it's a widely-used standard.

**Comment by yyoncho** [comment]
lsp-mode doesn't do anything special when binding commands. Maybe first ask on embark side why it doesn't work?

**Comment by jdtsmith** [comment]
Apologies, I had simply assumed that it didn't work even with normal prefix-help, but checking now, it indeed does.  I'll ask over on embark and report back if there's anything needed on this end.

**Comment by jdtsmith** [comment]
I have opened oantolin/embark#403.  I _believe_ the issue is lsp-mode's use of `menu-item`'s for its normal keymap bindings, which embark regards as "not real bindings".

**Comment by yyoncho** [comment]
Ok, I am closing this one since embark should support menu items.

**Comment by minad** [comment]
Indeed it should. There is an open issue for menu items: https://github.com/oantolin/embark/issues/383
