### ISSUE TITLE
Permit alternative completion-UI's

### ISSUE THREAD

**Issue by jdtsmith** [emacs-lsp/lsp-mode#3215]
Company is a great completion front-end, but if you are sticking with CAPF, other completion UIs work very well with lsp-mode.  The [kind-icon](https://github.com/jdtsmith/kind-icon) package I recently released has some examples of [corfu](https://github.com/minad/corfu) running in lsp-mode, with orderless completion style, kind icon support, etc.  It's really a very nice setup, but currently to enable this you need to explicitly disable company-mode in the lsp-mode-hook.

**Comment by yyoncho** [comment]
As per [our guide](https://emacs-lsp.github.io/lsp-mode/tutorials/how-to-turn-off/)  `(setq lsp-completion-provider :none)` will turn off autoconfiguration of company-mode.

**Comment by jdtsmith** [comment]
Thanks.  I had in fact seen that guide, but the way it is written led me to believe disabling completions would disable the entire CAPF framework, especially since the default option is `:capf` (which is in fact what corfu and others use for the completions source).   Are there other options envisioned for this variable?   If not, a boolean like `lsp-setup-company-mode` might be more discoverable.

**Comment by yyoncho** [comment]
In the past, we had another completion package `company-lsp` which is now no longer present. We have a similar variable name for diagnostics `lsp-diagnostics-provider`

**Comment by jdtsmith** [comment]
Since completions aren't disabled by this variable, just company, perhaps clarifying the guide to read something like:

> 14. Completion setup for company-mode
> (setq lsp-completion-provider :none)

would be enough.   Thanks.

**Comment by jdtsmith** [comment]
On a related note, company gets used in even when disabled in this manner; see #3225.
