### ISSUE TITLE
Documentation in R being too wide

### ISSUE THREAD

**Issue by davidbudzynski** [emacs-lsp/lsp-mode#3216]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

When using lsp mode and company-box, R documentation in ESS takes only 1 line and go across the whole width of the screen like shown in the picture: 

![image](https://user-images.githubusercontent.com/56514985/142742792-2a68074b-acfa-4384-bb9f-5dc3f21ba1d3.png)

### Steps to reproduce

Assuming you have R and laguageserver package installed

1. Create a new R file
2. Run R REPL 
2. Check for completion of any functions to see documentation being very wide

### Expected behavior

Documentation should span across many lines and should not bee too wide like show here in pyton mode:

![image](https://user-images.githubusercontent.com/56514985/142742910-ca616c03-5ade-4ad8-81dd-3b796c0cd0dd.png)

### Which Language Server did you use?

languageserver package for R 

### OS

Linux

**Comment by ericdallo** [comment]
@davidbudzynski could you [provide the communication between client and server](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/#log-client-server-json)? I suspect server is returning the doc string without `\n`, even so, we could improve the window to have a max-width if that does not exist already.

**Comment by yyoncho** [comment]
What do you use for showing the doc? Company quickhelp?

**Comment by yyoncho** [comment]
> When using lsp mode and company-box, R documentation in ESS takes only 1 line and go across the whole width of the screen like shown in the picture:

Please move this report in company-box repo. The UI in this case is responsible for wrapping the docs. In this case, lsp-mode acts only as a middle man between lsp-mode and company-box.
