### ISSUE TITLE
Headerline breadcrump causes huge CPU load and freezing

### ISSUE THREAD

**Issue by kipcd** [emacs-lsp/lsp-mode#3232]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

When `lsp-headerline-breadcrumb-mode` enabled, the CPU load is huge and repeatedly causes emacs to freeze for ~1 minute.
After disabling breadcrumbs problem disappeared.

[lsp-profiler-report.log](https://github.com/emacs-lsp/lsp-mode/files/7607068/lsp-profiler-report.log)

### Steps to reproduce

Small-medium-sized java project on JDK15
`(setq lsp-headerline-breadcrumb-enable t)`

### Expected behavior

No high CPU load and no freezing when breadcrumbs enabled

### Which Language Server did you use?

lsp-java with jdtls

### OS

Linux

### Anything else?

GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4) of 2021-03-26
Arch Linux

**Comment by yyoncho** [comment]
can you provide perf report as described in https://emacs-lsp.github.io/lsp-mode/page/performance/ ?

**Comment by yyoncho** [comment]
Nevermind, I saw the perf report.

**Comment by yyoncho** [comment]
To me it looks like this: https://github.com/emacs-lsp/lsp-mode/issues/2843

**Comment by kipcd** [comment]
Hi, for me the freezes happen when I just write the code, probably the most when requesting the completions, even if the number of completion results is limited to 10.

Any idea what is triggering this issue - my system, config, jdtls? 
Let me know if you need anything else from me

**Comment by kipcd** [comment]
Actually, spending some more time without breadcrumb, my completions are also very slow, even whith limited completion results. It hangs for 10-15 sec to show results. Here is profiler log
[profiler-report-completions.log](https://github.com/emacs-lsp/lsp-mode/files/7608589/profiler-report-completions.log)
I'm not sure if the cause is the same or it's a different issue

**Comment by yyoncho** [comment]
You have 30% GC, is your lsp-doctor green? What is your gc-cons-treshold

**Comment by kipcd** [comment]
> You have 30% GC, is your lsp-doctor green? What is your gc-cons-treshold

Yes it's green:
```
Checking for Native JSON support: OK
Check emacs supports `read-process-output-max': OK
Check `read-process-output-max' default has been changed from 4k: OK
Byte compiled against Native JSON (recompile lsp-mode if failing when Native JSON available): OK
`gc-cons-threshold' increased?: OK
Using gccemacs with emacs lisp native compilation (https://akrl.sdf.org/gccemacs.html): NOT AVAILABLE (OPTIONAL)
```

I have it like this in init.el:
``` emacs lisp
;; Speed up the initialization reducing garbage collection runs.
(setq gc-cons-threshold 100000000)
;; Increase the amount of data which Emacs reads from the process.
(setq read-process-output-max (* 1024 1024 3)) ;; 3mb

(use-package lsp-java
  :config
  (setq lsp-java-java-path (substitute-in-file-name "$HOME/.sdkman/candidates/java/16.0.1.hs-adpt/bin/java"))
  (let ((lombok-file (substitute-in-file-name "$HOME/.m2/repository/org/projectlombok/lombok/1.18.22/lombok-1.18.22.jar")))
    (setq lsp-java-vmargs
        (list "-noverify"
              "-Xmx4G"
              "-Xms100m"
              "-XX:+UseG1GC"
              "-XX:+UseStringDeduplication"
              "-Dsun.zip.disableMemoryMapping=true"
              (concat "-javaagent:" lombok-file))))
...)
```
Maybe I messed up something with VM args?

**Comment by kipcd** [comment]
I was testing with `lsp-start-plain.el` and it's much-much faster than my config, even with breadcrumb enabled, and CPU load is normal. I didn't find out yet why. I'll close the issue but will post if I find the culprit. Thank you @yyoncho

**Comment by yyoncho** [comment]
You may try testing with different theme. Or after M-x disable-theme.

**Comment by kipcd** [comment]
> You may try testing with different theme. Or after M-x disable-theme.

Nope, didn't help. I'll keep looking, thx!

**Comment by kipcd** [comment]
The problem disappeared after I removed this lines from my init.el, however when I added them again the freezes didn't come back, so it's still a mistery to me:
``` elisp
;; Follow compilation buffer output automatically
(setq compilation-scroll-output t)

;; Support for ANSI escape color codes in emacs compilation buffer
;; Fixes build and test execution output in LSP and DAP
(defun colorize-compilation-buffer ()
  (when (derived-mode-p 'compilation-mode)
    (ansi-color-process-output nil)
    (setq-local comint-last-output-start (point-marker))))
(use-package ansi-color
  :config
  (add-hook 'compilation-filter-hook
            #'colorize-compilation-buffer))

;; install command-log-mode - a buffer with a log of executed commands
(use-package command-log-mode)

;; Log of interactions with Emacs.
;; Enable with interaction-log-mode.
;; The log is in **Emacs Log** buffer
(use-package interaction-log)
```
I'll post back if I find more
