### ISSUE TITLE
Files opened via `magit-find-file` seem to be sent to the underlying server

### ISSUE THREAD

**Issue by Patryk27** [emacs-lsp/lsp-mode#3233]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

Opening an older revision of a file via `M-x magit-find-file` seems to send that old file's contents to the underlying LSP server, which breaks LSP for the original buffer (server thinks the original file gets replaced with the older revision).

### Steps to reproduce

1. Open a code repository that's compatible with LSP (e.g. Rust code),
1. Open some code file,
1. Use `M-x magit-find-file` to preview the older revision of that file,
1. See how annotations (e.g. type hints) end up in wrong places, as if the underlying file's contents were replaced with the older revision.

### Expected behavior

IMO the older revision of the file shouldn't be sent / shouldn't have `lsp-mode` activated - it's merely a read-only preview, after all.

### Which Language Server did you use?

lsp-rust

### OS

Linux

**Comment by yyoncho** [comment]
From lsp-mode point of view these files are just like the normal files. I believe that magit can avoid setting `buffer-file-name` which will prevent lsp-mode from starting..

**Comment by yyoncho** [comment]
(I will check if this can be done easily.)

**Comment by yyoncho** [comment]
Hm, when using magit-find-file for older revision, I end up with a buffer without lsp-mode being on. Can you confirm that the issue is with the temporary buffer?

**Comment by Patryk27** [comment]
Hi, I've checked this on C++ code now and the issue doesn't seem to be happening there 😅

I'm using rustic-mode & doom-emacs, so my rough guess is that either one of them is doing some additional stuff that triggers LSP to be launched in Magit's buffer; do you maybe have any idea on how I could investigate it further?

**Comment by yyoncho** [comment]
Can you give me the doom config that reproduces the issue?

**Comment by Patryk27** [comment]
Sure, a pretty minimal config such as this seems to be enough:
```elisp
;; that's init.el; config.el + packages.el remain empty

(doom! :completion
       company
       vertico

       :ui
       doom
       doom-dashboard

       :editor
       (evil +everywhere)

       :tools
       lsp
       magit

       :lang
       (rust +lsp)

       :config
       (default +bindings +smartparens))
```

**Comment by Patryk27** [comment]
Hi, is there anything more I could do / provide / debug? Not to hurry ofc., asking just in case 🙂

**Comment by yyoncho** [comment]
I debugged the issue and for some reason, `lsp` is running when buffer-file-name is set. After the buffer is open the file name is not set (that will prevent lsp-mode from starting). AFAICS doom uses hack local variables hook which I believe will cause `lsp` to run inappropriate time but I am not familiar enough with doom source code to verify that. IMHO the bug is caused by either doom or rustic calling lsp too early. I suggest opening an issue on doom side which then after investigation can be moved in rustic. From lsp-mode we point of view we are doing the right thing.

**Comment by Patryk27** [comment]
I understand; thank you very much for investigating this issue, I'll try following-up in the appropriate project 🙂
