### ISSUE TITLE
Emacs 27.2 crash with `gopls` on Void Linux

### ISSUE THREAD

**Issue by imiric** [emacs-lsp/lsp-mode#3242]
- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

I'm not sure if this is an issue with `gopls`, with `lsp-ui` or with this package, but something with this setup frequently crashes Emacs 27.2 for me during seemingly random interactions. Sometimes it happens while editing a Go struct, sometimes when changing buffers, and sometimes while idling with a Go buffer visible.

All packages were updated to the latest version (`lsp-mode-20211205.1533`, `lsp-ui-20211101.131`, `gopls v0.7.3`).

### Steps to reproduce

1. Open https://github.com/inkyblackness/imgui-go-examples/blob/main/cmd/example_glfw_opengl3/main.go.

2. Try to navigate the file. The crash doesn't happen consistently, and opening or editing other files might trigger it. This is not related to a specific project however; it happens in any Go project.

### Expected behavior

No crash :)

### Which Language Server did you use?

gopls

### OS

Linux

### Error callstack

```emacs-lisp
I can't provide an Elisp callstack, but here's the Emacs core dump backtrace when run from the CLI. This probably isn't useful without debugging symbols or without providing a core dump, so please let me know how to do that.

Fatal error 6: IOT trap
Backtrace:
emacs[0x51e5d1]
emacs[0x41f221]
emacs[0x41f6df]
emacs[0x41c884]
emacs[0x459f92]
emacs[0x45b37c]
emacs[0x45b558]
emacs[0x45b558]
emacs[0x45b558]
emacs[0x45b558]
emacs[0x45c9f6]
emacs[0x45ccbe]
emacs[0x47640c]
emacs[0x47aa4b]
emacs[0x57dc04]
emacs[0x440111]
emacs[0x466b2d]
emacs[0x468c25]
emacs[0x5c12a0]
emacs[0x4302df]
emacs[0x511169]
emacs[0x511b77]
emacs[0x51322e]
emacs[0x57db77]
emacs[0x5042cc]
emacs[0x57dad1]
emacs[0x504274]
emacs[0x5096e6]
emacs[0x509a10]
emacs[0x426b60]
/usr/lib/libc.so.6(__libc_start_main+0xea)[0x7fbdb43e5e0a]
emacs[0x42719a]
zsh: abort      emacs
```

### Anything else?

Here's the relevant part of my Emacs config:

```elisp
(use-package lsp-mode
  :ensure t
  :hook ((go-mode python-mode) . lsp-deferred)
  :commands (lsp lsp-deferred))

(use-package lsp-ui :ensure t
  :commands lsp-ui-mode)

(use-package helm-lsp :ensure t :commands helm-lsp-workspace-symbol)

(defun lsp-go-install-save-hooks ()
  (add-hook 'before-save-hook #'lsp-format-buffer t t)
  (add-hook 'before-save-hook #'lsp-organize-imports t t))
(add-hook 'go-mode-hook #'lsp-go-install-save-hooks)
```

**Comment by yyoncho** [comment]
By definition, eslip code should never cause emacs crash so you should report emacs core bug using `M-x report-emacs-bug` (if you don't have email configured in emacs you can copy and send the bug report from the email client you are using)
