### ISSUE TITLE
Org mode support is creating a lot of false positive.

### ISSUE THREAD

**Issue by sathlan** [emacs-lsp/lsp-mode#3258]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

When parsing org mode file all the block code and the org mode header are still parsed and produce a lot of false positive:

![Screenshot from 2021-12-14 10-03-19](https://user-images.githubusercontent.com/328319/145967162-b04c759f-df3d-449c-8f48-745fd1bf793d.png)
![Screenshot from 2021-12-14 10-11-57](https://user-images.githubusercontent.com/328319/145968400-b45ccfc8-25a7-4f61-8e8e-8519310fde96.png)

### Steps to reproduce

Open any org-mode file using the ltex-ls server.

### Expected behavior

The block code should not be corrected and neither should the headers.

### Which Language Server did you use?

ltex-ls.

### OS

Linux

**Comment by yyoncho** [comment]
@jcs090218 any thoughts?

**Comment by sathlan** [comment]
Hi,

I've tested the above patch locally and it worked like a charm.  Unsure if it has other side effect, I've just used it with ltex-ls.

Screenshot using the patch:
![Screenshot from 2021-12-14 10-29-48](https://user-images.githubusercontent.com/328319/145971264-90ec82d2-9a91-4525-8616-5a6613e891b6.png)
.

**Comment by jcs090218** [comment]
Ah... yes. I think you are right, I don't know what I was thinking back then. 😅
