### ISSUE TITLE
gopls does not respond any requests

### ISSUE THREAD

**Issue by novakboskov** [emacs-lsp/lsp-mode#3276]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

My `gopls` starts successfully (or at least prints `LSP :: Connected to [gopls:516].` in the echo area). However, it is completely useless as it does not do anything. It does not respond to requests from my Emacs client, and it's not busy doing indexing (as it consumes no significant CPU cycles).

The main issue seems to be that my `gopls` just never responds to any requests that I can see in `*lsp-log: gopls:516*`.
Although `gopls` is a running process, I can see that in `list-processes`.

The ugly part is that `*gopls*` is empty, I can't even tell is it OK or not. `*lsp-log*` just prints `Cancelling textDocument/documentLink(823) in hook post-command-hook` and the like for each LSP command I try to run.

The weirdest part is that I have a very suspicious `Error processing message (file-error "Opening directory" "Permission denied" "/home/novak/.dbus").` in my `*Messages*` right after `LSP :: Connected to [gopls:516].` My project is not in `/home/novak/` but in a subdirectory. I have no idea why would `gopls` touch anything in `/home/novak`. The ethereum project has `go.mod`, `go.sum` and `.git` in it. It would make sense for `gopls` to work in the root dir of my project, not in my home.

### Steps to reproduce

For example, clone `github.com/ethereum/go-ethereum` and open `cmd/evm/main.go`.

### Expected behavior

Perform LSP commands.

### Which Language Server did you use?

gopls

### OS

Linux

### Error callstack

```emacs-lisp
There is no one. I just see requests sent.
```

### Anything else?

This is probably something silly. I probably missed out on some go configuration. But I have no idea what that could be.

**Comment by js-sketch** [comment]
>Error processing message (file-error "Opening directory" "Permission denied" "/home/novak/.dbus").

.dbus contains information on how to connect to the user bus.

>There is no one. I just see requests sent.

That's funky, as you clearly get an Error. Do you have `debug-on-error` set to true? Otherwise you won't get a stack trace. `M-x toggle-debug-on-error` and re-do it.

**Comment by yyoncho** [comment]
Do `M-x lsp-describe-session` and make sure that you have selected the correct project root. If not, then use M-x lsp-workspace-folders-add/remove to fix that. Also, the client-server log can be obtained using the following instructions (part of the bug template):

> If there is an error please reproduce the issue with toggle-debug-on-error and after setting lsp-print-io to t, and then include the callstack and attach the content of *lsp-log* buffer and the content of the server log(use lsp-workspace-show-log)

**Comment by novakboskov** [comment]
@yyoncho You're right, my workspace was set to `/home/novak` (with no apparent reason). I've removed/added the correct workspace using `lsp-workspace-folders-add/remove` and now it seems like my LSP client and server communicate correctly. However, there are some other issues now. For example, the hovers that usually show function docs do not show up, although it seems like the server returns the message:

```
[Trace - 12:35:39 PM] Received response 'textDocument/hover - (161)' in 12ms.
Result: {
  "range": {
    "end": {
      "character": 39,
      "line": 148
    },
    "start": {
      "character": 22,
      "line": 148
    }
  },
  "contents": {
    "value": "```go\nfunc params.VersionWithCommit(gitCommit string, gitDate string) string\n```\n\n[`params.VersionWithCommit` on godoc.org](https://godoc.org/github.com/ethereum/go-ethereum/params#VersionWithCommit)",
    "kind": "markdown"
  }
}
```
My `lsp-ui-doc-enable` is `t`, and the hovers appear in other languages (C++ with `ccls` and Python with `pyls`). Do you perhaps know what may be the case here off top of your head, or should I open the new issue for this?

I have `toggle-debug-on-error`, no Elisp errors happen.

**Comment by yyoncho** [comment]
@novakboskov set lsp-ui-doc-show-with-cursor  and lsp-ui-doc-include-signature  to t.

**Comment by novakboskov** [comment]
That solves it all. Thanks!
