### ISSUE TITLE
Folding into function causes `run test` buttons to stack

### ISSUE THREAD

**Issue by js-sketch** [emacs-lsp/lsp-mode#3277]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

Here's a picture which shows the issue:
![test](https://user-images.githubusercontent.com/80259506/146928028-7c4e1c7f-998d-478b-ae7a-7acaa1f46c05.png)

This occurs when I middle-click the purple function name inside of the breadcrumb (this folds the code so I only see the current definition).

(there's a total of 6 tests in the file)

### Steps to reproduce

1. Open test file
2. Move cursor over into a test function such that the purple current function is changed
3. Middle click the purple text to fold into current function 

### Expected behavior

Only see the `run test` button for the currently showing test

### Which Language Server did you use?

gopls

### OS

Linux

**Comment by yyoncho** [comment]
dup of https://github.com/emacs-lsp/lsp-mode/issues/3228
