### ISSUE TITLE
lsp imenu doesn't show function arguments

### ISSUE THREAD

**Issue by myrgy** [emacs-lsp/lsp-mode#329]
Hi there,

I'm using lsp with cquery. And noticed that imenu doesn't show methods arguments, as a result overloaded functions looks identical:
![imenu](https://user-images.githubusercontent.com/2340958/38199245-ba9c0f5e-3698-11e8-9aa4-0ec6d90d6ec6.png)
but for example semantic is able to show all this information.
I've asked guys from cquery team and was told that lsp don't use all information from cquery.
So, since it's available it would be nice to show it!

Thanks!

**Comment by MaskRay** [comment]
`sudo sysdig -As999 --unbuffered -p '%evt.type %proc.exe %evt.buffer' "proc.exe contains ccls and fd.type=pipe" | egrep -v '^Content|^$'`
```
{"jsonrpc":"2.0","id":173,"result":[{"name":"main","kind":12,"location":{"uri":"file:///tmp/d/a.cc","range":{"start":{"line":5,"character":0},
"end":{"line":15,"character":1}}},"containerName":"int main()"}]}
```

LSP `SymbolInformation` contains both `name` and `containerName`. In this case the latter is more concrete.

**Comment by myrgy** [comment]
@MaskRay , is there any way to patch lsp?

**Comment by myrgy** [comment]
with latests update we have more information in lsp-imenu, but unfortunately method name is cut. It might be awesome to disable it! Thanks!
