### ISSUE TITLE
--inlay-hints option for clangd doesn't work

### ISSUE THREAD

**Issue by c02y** [emacs-lsp/lsp-mode#3292]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

I set `--inlay-hints` for clangd, but this doen't work as expected.

Here is my full `lsp-clients-clangd-args`
```
(setq lsp-clients-clangd-args
      '("-j=12" "--all-scopes-completion" "--background-index" "--clang-tidy"
        "--completion-style=detailed" "--cross-file-rename" "--header-insertion=iwyu"
        "--header-insertion-decorators" "--inlay-hints" "--pch-storage=memory"
        "--query-driver=/usr/bin/**/clang*,/bin/clang,/bin/clang++,/usr/bin/gcc,/usr/bin/g++"
        ))
```

### Steps to reproduce

1. set `--inlay-hints` for clangd
2. set lsp-clangd as the backend of c/c++
3. open a c/c++ file

### Expected behavior

 `--inlay-hints` should work

### Which Language Server did you use?

lsp-clangd

### OS

Linux

**Comment by yyoncho** [comment]
It should work after https://github.com/emacs-lsp/lsp-mode/pull/3970

**Comment by c02y** [comment]
Sorry for the delay, it (lsp-mode-20230706.655) still doesn't work.

Is it working for you?

**Comment by yyoncho** [comment]
did you set lsp-inlay-hint-enable to t?

**Comment by c02y** [comment]
I enabled `lsp-rust-analyzer-inlay-hints-mode` instead, sorry, I didn't read the code, it's been a long time since the last time I read the doc.

`lsp-inlay-hint-enable` works.
