### ISSUE TITLE
lsp-completiton failed on add-on mode

### ISSUE THREAD

**Issue by cxa** [emacs-lsp/lsp-mode#3293]
- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

I'm using lsp-svelte with [lsp-tailwindcss](https://github.com/merrickluo/lsp-tailwindcss), with `lsp-tailwindcss-add-on-mode` enabled. basically this is my config:

```elisp
(use-package svelte-mode)

(use-package lsp-tailwindcss
  :custom (lsp-tailwindcss-add-on-mode t))
```

One strange thing is, once I move out of css block, the completion from `lsp-tailwindcss` will not be called when I jump back to css block. I found a workaround, if I toggle `lsp-completion-mode`, it will work again:

```elisp
(use-package svelte-mode
  :config
  (advice-add
   'svelte--pre-command
   :after
   (lambda ()
     "Workaround: Toggle lsp-completion, otherwise lsp-tailwindcss will fail on completion"
     (when (eq svelte--last-submode svelte--css-submode)
       (lsp-completion--disable)
       (lsp-completion--enable)))))

(use-package lsp-tailwindcss
  :custom (lsp-tailwindcss-add-on-mode t))
```

Any thoughts?

### Steps to reproduce

See Bug description

### Expected behavior

See Bug description

### Which Language Server did you use?

See Bug description

### OS

MacOS

**Comment by jcs090218** [comment]
Why is this issue closed? Did you solve it? 🤔

**Comment by cxa** [comment]
No, it's inactive for a long time, just thought closing would make less pressures for maintainers because I saw no any activities on this issue.
