### ISSUE TITLE
Support URI scheme other that "file://"

### ISSUE THREAD

**Issue by zhangjunphy** [emacs-lsp/lsp-mode#330]
Currently lsp-mode only handles URI which points to a file in the filesystem, but some lsp server, such as the [eclipse jdt](https://github.com/eclipse/eclipse.jdt.core), can produce URIs like the following, which points to a source code location in a jar file:
```
"jdt://contents/rt.jar/java.util/ArrayList.class?=jdt.ls-java-project/%5C/Library%5C/Java%5C/JavaVirtualMachines%5C/jdk1.8.0_131.jdk%5C/Contents%5C/Home%5C/jre%5C/lib%5C/rt.jar%3Cjava.util(ArrayList.class"
```
The lsp client can query the server with this URI to get the actual file content.

Allowing such URIs will be useful if the lsp server wants to present temporary contents to the client. 
BTW, VS Code supports this by implementing a [TextDocumentContentProvider](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nametextdocumentcontentprovideraspan-classcodeitem-id477textdocumentcontentproviderspan) interface.

**Comment by yyoncho** [comment]
There is pull request for that with https://github.com/emacs-lsp/lsp-java/pull/22

**Comment by zhangjunphy** [comment]
Thanks for the information! Closing this.
