### ISSUE TITLE
flycheck feature not enable by default if not require lsp-headerline and lsp-diagnostics

### ISSUE THREAD

**Issue by zw963** [emacs-lsp/lsp-mode#3301]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Don't sure if this is a bug, but, anyway, i report here for check it out.

I love flycheck, it give me the red underline like following, told me the error is happen.

![image](https://user-images.githubusercontent.com/549126/148245044-62087bf1-6a09-4a53-b4da-f17b15f327df.png)

But, for this feature start to work, if not use package manager, that is, require manually, i have to require following two library manually to make this feature available.

```el
(require 'lsp-headerline)
(require 'lsp-diagnostics)
```

The issue is, 

1. lsp-headerline controller if enable flycheck, is this expected behavior?
2. can we consider enable this feature when flycheck was available by default?

### Steps to reproduce

thank you

### Expected behavior

thank you

### Which Language Server did you use?

dart

### OS

Linux

### Error callstack

```emacs-lisp
no
```

### Anything else?

no

**Comment by ericdallo** [comment]
why you just require `lsp-mode`? it should activate and make everything work already, right @yyoncho ?

**Comment by zw963** [comment]
> why you just require `lsp-mode`? it should activate and make everything work already, right @yyoncho ?

No, i try several times,  one by one, and found this detail, i am quite ensure, if not require those two manually, flycheck red line never happen, even, i enable (global-flycheck-mode) globally BEFORE require lsp-mode.

**Comment by ericdallo** [comment]
it's because they require `lsp-diagnostics`, but AFAIK these should not be required manually

**Comment by zw963** [comment]
> it's because they require `lsp-diagnostics`, but AFAIK these should not be required manually

but, i am quite sure, only require `lsp-diagnostics`,  flycheck not work.

**Comment by yyoncho** [comment]
> But, for this feature start to work, if not use package manager, that is, require manually, i have to require following two libraries manually to make this feature available.

If you are installing the package manually you have to do all the things that package.el is doing (e. g. generating autoloads).

**Comment by zw963** [comment]
> If you are installing the package manually you have to do all the things that package.el is doing (e. g. generating autoloads).

But, the issue is, flycheck not so concern with require `lsp-headline`, right? even, i can saw headline even i don't need require `lsp-headline` manually, but, flycheck not work.

**Comment by yyoncho** [comment]
> > If you are installing the package manually you have to do all the things that package.el is doing (e. g. generating autoloads).
> 
> But, the issue is, flycheck not so concern with require `lsp-headline`, right? even, i can saw headline even i don't need require `lsp-headline` manually, but, flycheck not work.

These lines are not required if you are using package.el which implies that the issue is in the way you are installing lsp-mode. We cannot invest time in supporting the scenario as described by you. If you are not installing the package the way it should be installed we cannot guarantee that it works correctly.

**Comment by zw963** [comment]
> These lines are not required if you are using package.el which implies that the issue is in the way you are installing lsp-mode. We cannot invest time in supporting the scenario as described by you. If you are not installing the package the way it should be installed we cannot guarantee that it works correctly.

Okay, it is fine to require all needed package manually. thank you.
