### ISSUE TITLE
provide facilities for sending DidChangeWatchedFiles notifications to the server

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#331]
https://microsoft.github.io/language-server-protocol/specification#workspace_didChangeWatchedFiles

**Comment by yyoncho** [comment]
@vibhavp would you assign me the issue?

**Comment by MaskRay** [comment]
This may be reopened. I recently added the relevant support to ccls https://github.com/MaskRay/ccls/pull/170 and tested it on vscode and coc.nvim, I think the expected interaction is:

* client sends `initialized`
* server sends `register/clientCapability` (RequestMessage)`
* client sends a response with `result: null`

```javascript
{"jsonrpc":"2.0","method":"initialized","params":{}}

{"jsonrpc":"2.0","method":"client/registerCapability","id":0,"params":{"registrations":[{"id":"didChangeWatchedFiles","method":"workspace/didChangeWatchedFiles","registerOptions":{"watchers":[{"globPattern":"**/*"}]}}]}}

{"jsonrpc":"2.0","id":0,"result":null}
```

A notification of an added file looks like this:
```javascript
{"jsonrpc":"2.0","method":"workspace/didChangeWatchedFiles","params":{"changes":[{"uri":"file:///tmp/d/b.cc","type":1}]}}
```

**Comment by yyoncho** [comment]
Sure, I have only added the facilities that are needed for watching files(filenotify is not recursive) and we need to wire them. Back then when I implemented the support the JDT ls server wasn't sending registerCapability request.
