### ISSUE TITLE
organize-imports fails when using ts-ls

### ISSUE THREAD

**Issue by bolivier** [emacs-lsp/lsp-mode#3317]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

organize-imports doesn't work with ts-ls.  

### Steps to reproduce

run `lsp-organize-imports`

### Expected behavior

Imports should be organized

### Which Language Server did you use?

ts-ls

### OS

MacOS

### Anything else?

The fix is to put

 ```emacs-lisp
(lsp-make-interactive-code-action organize-imports "source.organizeImports.ts-ls")
```

In your config file.  I think it'd be good to have it in the docs site somewhere.  I'm happy to open a PR with that change.

**Comment by sagittaros** [comment]
Overriding the `organize-imports` code action is going to affect non-typescript projects. My workaround is to create a new code action called `organize-imports-ts`, for example:

```elisp
(after! lsp-mode
  ;; (setq lsp-clients-typescript-init-opts '(:importModuleSpecifierPreference "non-relative"))
  (lsp-make-interactive-code-action organize-imports-ts "source.organizeImports.ts-ls"))
```

calling this macro creates a new interactive function `lsp-organize-imports-ts`, which can be key-bound.

```elisp
(map! :after lsp-mode
      (:map typescript-mode-map
       "C-c C-o" #'lsp-organize-imports-ts)
      ("C-c C-o" #'lsp-organize-imports))
```

NOTE: The example above is specific to doom emacs
