### ISSUE TITLE
When i execute the lsp-install-server it can't work.

### ISSUE THREAD

**Issue by e665107** [emacs-lsp/lsp-mode#3321]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Hi, here is my emacs backtrace:

Debugger entered--Lisp error: (void-function -compose)
  -compose(lsp--client-path->uri-fn lsp--workspace-client)
  lsp--path-to-uri("/home/e66/.emacs.d/index.sqlite")
  #f(compiled-function () #<bytecode 0x44d083d>)()
  funcall(#f(compiled-function () #<bytecode 0x44d083d>))
  eval((funcall #'#f(compiled-function () #<bytecode 0x44d083d>)))
  custom-initialize-reset(lsp-serenata-index-database-uri (funcall #'#f(compiled-function () #<bytecode 0x44d083d>)))
  custom-declare-variable(lsp-serenata-index-database-uri (funcall #'#f(compiled-function () #<bytecode 0x44d083d>)) "The location to store the index database.\nNote tha..." :group lsp-serenata :type file)
  byte-code("\301\302\303\304 \305\306\307!\310\311\312\313&\10!\210\314\315\316\317\320\321\322\323\324\325&\11\210\326\327\330\331\332DD\333\334\335\320\315\324\336&\11\210\326\337\330..." [lsp-intelephense-multi-root lsp-register-client make-lsp-client :new-connection lsp-php--create-connection :activation-fn lsp-activate-on "php" :priority -3 :server-id php-ls custom-declare-group lsp-intelephense nil "LSP support for PHP, using Intelephense." :group lsp-mode :link (url-link "https://github.com/bmewburn/vscode-intelephense") :package-version (lsp-mode . "6.1") custom-declare-variable lsp-intelephense-php-version funcall function #f(compiled-function () #<bytecode 0xe86055>) "Minimum version of PHP to refer to. Affects code a..." :type string (lsp-mode . "6.1") lsp-intelephense-files-max-size #f(compiled-function () #<bytecode 0xe86065>) "Maximum file size in bytes." number (lsp-mode . "6.1") lsp-intelephense-files-associations #f(compiled-function () #<bytecode 0xe8607d>) "Configure glob patterns to make files available fo..." (repeat string) (lsp-mode . "6.1") lsp-intelephense-files-exclude #f(compiled-function () #<bytecode 0xe860a1>) "Configure glob patterns to exclude certain files a..." (repeat string) (lsp-mode . "6.1") lsp-intelephense-stubs #f(compiled-function () #<bytecode 0xe860b1>) "Configure stub files for built in symbols and comm..." (repeat string) ...] 20)
  require(lsp-php nil t)
  #f(compiled-function (package) #<bytecode 0x10bd59d>)(lsp-php)
  mapc(#f(compiled-function (package) #<bytecode 0x10bd59d>) (ccls lsp-actionscript lsp-ada lsp-angular lsp-bash lsp-beancount lsp-clangd lsp-clojure lsp-cmake lsp-crystal lsp-csharp lsp-css lsp-d lsp-dart lsp-dhall lsp-docker lsp-dockerfile lsp-elm lsp-elixir lsp-erlang lsp-eslint lsp-fortran lsp-fsharp lsp-gdscript lsp-go lsp-graphql lsp-hack lsp-grammarly lsp-groovy lsp-haskell lsp-haxe lsp-java lsp-javascript lsp-json lsp-kotlin lsp-latex lsp-ltex lsp-lua lsp-markdown lsp-nginx lsp-nim lsp-nix lsp-metals lsp-mssql lsp-ocaml lsp-pascal lsp-perl lsp-php lsp-pwsh lsp-pyls ...))
  seq-do(#f(compiled-function (package) #<bytecode 0x10bd59d>) (ccls lsp-actionscript lsp-ada lsp-angular lsp-bash lsp-beancount lsp-clangd lsp-clojure lsp-cmake lsp-crystal lsp-csharp lsp-css lsp-d lsp-dart lsp-dhall lsp-docker lsp-dockerfile lsp-elm lsp-elixir lsp-erlang lsp-eslint lsp-fortran lsp-fsharp lsp-gdscript lsp-go lsp-graphql lsp-hack lsp-grammarly lsp-groovy lsp-haskell lsp-haxe lsp-java lsp-javascript lsp-json lsp-kotlin lsp-latex lsp-ltex lsp-lua lsp-markdown lsp-nginx lsp-nim lsp-nix lsp-metals lsp-mssql lsp-ocaml lsp-pascal lsp-perl lsp-php lsp-pwsh lsp-pyls ...))
  lsp--require-packages()
  lsp-install-server(nil)
  funcall-interactively(lsp-install-server nil)
  call-interactively(lsp-install-server record nil)
  command-execute(lsp-install-server record)
  #f(compiled-function () #<bytecode 0xe85f59>)()
  funcall(#f(compiled-function () #<bytecode 0xe85f59>))
  helm-M-x(nil #("lsp-install-server" 0 18 (match-part "lsp-install-server")))
  funcall-interactively(helm-M-x nil #("lsp-install-server" 0 18 (match-part "lsp-install-server")))
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)

### Steps to reproduce

Hi, here is my emacs config :

(use-package lsp-mode
  :commands lsp
  :hook ((lsp-mode . lsp-ui-sideline-mode)
         (lsp-mode . lsp-enable-which-key-integration))
  :bind (:map lsp-mode-map
              ("C-c C-t" . lsp-describe-thing-at-point))
  :config
  (setq lsp-prefer-flymake nil)
  (setq lsp-auto-guess-root t
        lsp-keep-workspace-alive nil))

;; Lsp UI
(use-package lsp-ui
  :config
  (define-key lsp-ui-mode-map [remap xref-find-definitions] #'lsp-ui-peek-find-definitions)
  (define-key lsp-ui-mode-map [remap xref-find-references] #'lsp-ui-peek-find-references)
  (setq
   lsp-ui-sideline-show-hover t
   lsp-ui-doc-enable t
   lsp-ui-sideline-show-diagnostics t
   lsp-ui-sideline-ignore-duplicate t))
(add-hook 'after-init-hook 'lsp-ui-sideline-mode)

### Expected behavior

I want the lsp  to  work with my c-mode.

### Which Language Server did you use?

clangd.  Does it will start automatically?

### OS

Linux

### Error callstack

```emacs-lisp
Error stack is on the above!
```

**Comment by yyoncho** [comment]
Upgrade your dash version and check the pinned issue - https://github.com/emacs-lsp/lsp-mode/issues/2615
