### ISSUE TITLE
Unable to find installed server supporting this file

### ISSUE THREAD

**Issue by mattiasdrp** [emacs-lsp/lsp-mode#3331]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

When starting lsp-mode in an F# file, a message appears:

    Unable to find installed server supporting this file. The following servers could be installed automatically: 

And the sole completion is fsac. If I complete and hit enter, the message appears again. In the messages buffer I have the following line:

```
LSP :: Download fsac started.
Contacting host: api.github.com:443
Wrote /tmp/fsautocompleteGBWGBS.zip
[/tmp/fsautocompleteGBWGBS.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/fsautocompleteGBWGBS.zip or
        /tmp/fsautocompleteGBWGBS.zip.zip, and cannot find /tmp/fsautocompleteGBWGBS.zip.ZIP, period.
LSP :: Altering permissions
LSP :: Finished altering permissions
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-/home/mattias/.emacs.d/var/lsp/server/fsautocomplete/fsautocomplete.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
LSP :: Server fsac downloaded, auto-starting in 0 buffers.
Lsp mode enabled in current buffer
```

### Steps to reproduce

- Install dotnet and fsautocomplete
- Start emacs on a F# file

### Expected behavior

The server should be installed

### Which Language Server did you use?

lsp-fsac

### OS

Linux

**Comment by yyoncho** [comment]
can you check the content of /tmp/fsautocompleteGBWGBS.zip? (FTR  it works fine on my side)

**Comment by mattiasdrp** [comment]
I tried to do it on a different computer, same error. 
When I try to unzip the /tmp/fsautocomplete[...].zip:

```
❯ unzip /tmp/fsautocompleteKLKihc.zip
Archive:  /tmp/fsautocompleteKLKihc.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/fsautocompleteKLKihc.zip or
        /tmp/fsautocompleteKLKihc.zip.zip, and cannot find /tmp/fsautocompleteKLKihc.zip.ZIP, period.
```

What I did is exactly this:

```
wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb

sudo apt-get update; \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-6.0

dotnet tool install -g fsautocomplete
```
In my lsp-mode.el file I have the following:

```
(use-package lsp-mode
  :hook (
         (elm-mode . lsp-deferred)
         (rust-mode . lsp-deferred)
         (fsharp-mode . lsp-deferred)
         (lsp-mode . lsp-enable-which-key-integration)
         )
  :custom
  (lsp-headerline-breadcrumb-enable nil)
  (lsp-keymap-prefix "M-l")
  (lsp-prefer-capf t)
  (lsp-completion-provider :capf)
  (lsp-completion-enable t)
  (lsp-enable-imenu t)
  :commands lsp
  :config
  (which-key-add-keymap-based-replacements lsp-command-map "u" "UI")

  :bind
  )

```

**Comment by mattiasdrp** [comment]
@yyoncho Am I doing something wrong with my setup? Do I need to install something more?

**Comment by yyoncho** [comment]
Can you check what do you have in the downloaded file?

**Comment by mattiasdrp** [comment]
In the zip file? I can't unzip it.

**Comment by yyoncho** [comment]
Can you open the file in emacs as a text file?

**Comment by mattiasdrp** [comment]
Oh, yes, sorry

```
❯ cat /tmp/fsautocompleteU6Byaf.zip
Not Found%
```

**Comment by mattiasdrp** [comment]
Oh, @yyoncho, I think I got the problem:
  - https://github.com/fsharp/FsAutoComplete/releases/tag/v0.50.0 doesn't contain a fsautocomplete.netcore.zip link
  - Previous versions did

I displayed the link that was generated by lsp-fsharp.el:

https://github.com/fsharp/FsAutoComplete/releases/download/v0.50.0/fsautocomplete.netcore.zip

Obviously this can't work.

**Comment by mattiasdrp** [comment]
See https://github.com/fsharp/FsAutoComplete/issues/883

**Comment by razzmatazz** [comment]
I believe [my PR](https://github.com/emacs-lsp/lsp-mode/pull/3350) should fix this issue (by switching to `dotnet tool install -g` mechanism for installing fsac)

Can some one test and confirm the changes PR work for them so we can merge it?

**Comment by 64J0** [comment]
I'm having this same problem. Just downloaded this file lots of times but Emacs keep not working:

![image](https://user-images.githubusercontent.com/50725287/159081193-7776a848-3b85-4ec5-bf8f-c84baf133751.png)

```
LSP :: Download fsac started.
Contacting host: api.github.com:443
Contacting host: github.com:443
Wrote /tmp/fsautocompleteWIKX9s.zip
[/tmp/fsautocompleteWIKX9s.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/fsautocompleteWIKX9s.zip or
        /tmp/fsautocompleteWIKX9s.zip.zip, and cannot find /tmp/fsautocompleteWIKX9s.zip.ZIP, period.
LSP :: Altering permissions
LSP :: Finished altering permissions
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-/home/gajo/.emacs.d/.cache/lsp/fsautocomplete/fsautocomplete.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
LSP :: There are language server((fsac)) installation in progress.
The server(s) will be started in the buffer when it has finished.
LSP :: Server fsac downloaded, auto-starting in 1 buffers.
Beginning of buffer
```

**Comment by razzmatazz** [comment]
the most recent version of lsp-mode installs fsac via "dotnet install" -- you seem to be running an older version of lsp-mode

are you by chance on doom-emacs? -- as it has not updated lsp-mode for some time

**Comment by 64J0** [comment]
I'm not on doom-emacs, I'll try to update my package then

**Comment by razzmatazz** [comment]
great!

**Comment by razzmatazz** [comment]
closing this issue then, as there is at least one confirmation (from @64J0) that the fix works

**Comment by mattiasdrp** [comment]
Confirming that the updated lsp-mode works for me too. Thanks a lot!
