### ISSUE TITLE
lsp-org: support non-company completion front-ends

### ISSUE THREAD

**Issue by titaniumbones** [emacs-lsp/lsp-mode#3335]
Is your feature related or already mentioned on [the wishlist](https://github.com/emacs-lsp/lsp-mode/discussions/2892)?

lsp-org seems like a very significant boost for people like me who work in org-mode buffers. However, at present it only seems to supports the company frontend for completions. Is it possible to support other completion frameworks, el.g. corfu? cf. this issue https://github.com/minad/corfu/issues/116 

Thanks!

**Comment by yyoncho** [comment]
AFAIK corfu works over compeltion-at-point-functions. That means it should work in org-mode buffers. Can you elaborate what the issue is? If you disable lsp-mode's company mode support and enable corfu it should work.

**Comment by titaniumbones** [comment]
My apologies -- further testing seems to indicate that this *does* work, at least mostly.  I am seeing some buggy behaviour, but will characterize better and see if I need to file another report.
