### ISSUE TITLE
Display inlay hints don't working in examples folder of Rust project

### ISSUE THREAD

**Issue by diaevd** [emacs-lsp/lsp-mode#3336]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

If open file from examples folder (standard path for Rust examples binaries sources) all except inlay hints working fine.

### Steps to reproduce

Just open file in expamples forder of rust cargo project with lsp-rust-analyzer-inlay-hints-mode

### Expected behavior

working inlay hints in examples tests folders

### Which Language Server did you use?

rust-analyzer

### OS

Linux

### Anything else?

lsp-rust-analyzer-update-inlay-hints call lsp-rust-analyzer-initialized? and lsp-find-workspace 'rust-analyzer return nil :)
If comment out call lsp-rust-analyzer-initialized? then display inlay hints just working.

Maybe there is another way to check rust-analyzer alive on buffer?

**Comment by yyoncho** [comment]
can you test after https://github.com/emacs-lsp/lsp-mode/pull/3970 ?

**Comment by Yuanda-Dong** [comment]
> can you test after #3970 ?

I'm getting way less inlay hints for rust projects compared to before inlay hints was in the core.

**Comment by yyoncho** [comment]
@Yuanda-Dong can you open issue/dicusssion mentioning what is missing in particular?

**Comment by Yuanda-Dong** [comment]
> @Yuanda-Dong can you open issue/dicusssion mentioning what is missing in particular?

Yes, I opened a new bug report.

**Comment by yyoncho** [comment]
Most likely fixed with https://github.com/emacs-lsp/lsp-mode/pull/4044
