### ISSUE TITLE
lsp-completion-mode clobbers completion-functions-at-point

### ISSUE THREAD

**Issue by titaniumbones** [emacs-lsp/lsp-mode#3340]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

When started, `lsp-completion-mode` sets `completion-functions-at-point` to nil and then adds `lsp-completion-at-point` to the list.  When the server disconnects, `completion-functions-at-point` is set bak to `nil`, erasing the user's customizations.  In order to resture them, the user must reopen the file without connecting lsp.  In addition, this prevents the user form using more complex completion commands, such as [CAPE's `super-cape` functions](https://github.com/minad/cape#super-capf---merging-multiple-capfs).

My suggested solution would have two parts:
- a new defcustom which holds the symbol for the completion function
- using `add-hook` with a negative priority instead of `setq` to add the lsp completion, then removing the hook on disconnect/mode off.

If that sounds like a good idea I can prepare a minor PR.

### Steps to reproduce

turn lsp-completion-mode on and then off again.

### Expected behavior

old completion configuration would still be active.

### Which Language Server did you use?

have tried with several js servers and also with lsp-css. 

### OS

Linux

### Anything else?

thank you!

**Comment by kiennq** [comment]
Thank you @titaniumbones, PR is always welcome :)

**Comment by daanturo** [comment]
For simplicity, can we just not set `completion-at-point-functions` to `nil`?
```lisp
(make-local-variable 'completion-at-point-functions)
(add-to-list 'completion-at-point-functions #'lsp-completion-at-point)
```
`(setq-local completion-at-point-functions nil)` was first introduced in 65c326643914a9ce5c6dd535e8ca3a5cdd9ac0f8 on 2016/12/07, but I don't see a commit message or a comment that explains it. The code just got moved around through refactors, therefore I think that it should be replaced.
