### ISSUE TITLE
Allow showing code action completion even when only one action is available

### ISSUE THREAD

**Issue by dallagi** [emacs-lsp/lsp-mode#3341]
Is your feature related or already mentioned on [the wishlist](https://github.com/emacs-lsp/lsp-mode/discussions/2892)? **no**

Currently, when running the `lsp-execute-code-action` command, if only one action is available at point then that action is executed immediately.
I believe it would be useful to have the option (even behind a config toggle) to show the `lsp--select-action` completion menu even when only one action is available.

The reason is that often I find myself running the `lsp-execute-code-action` command just to check which commands are available.
Sometimes it happens that it automatically executes the only action available, and it's not the action I was looking for.

If it could be helpful I'd be happy to provide a PR for this.

**Comment by yyoncho** [comment]
set lsp-auto-execute-action to nil
