### ISSUE TITLE
Signature help documentation looks ugly in OmniSharp

### ISSUE THREAD

**Issue by salehmu** [emacs-lsp/lsp-mode#3346]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

I'm not sure if this is a bug or a feature request, signature help documentation in OmniSharp makes it tough to read any of it because it's loaded with all .NET's XML documentation tags (i.e `<summary>`, `</param>`, `<exception>`), picture explain: 
![image](https://user-images.githubusercontent.com/74098495/152802642-2f85c7a6-5f07-456e-9644-2d8ac43af39d.png)
Compared to clangd: 
![image](https://user-images.githubusercontent.com/74098495/152802873-940d7976-e2cf-473e-bdff-734bfc0680ce.png)
Is there is any workaround to hide those tags? Or to make use of them (like signature help documentation highlighting or something)? 

I tried to use `csharp-ls` instead, but it didn't show any signature help at all.

### Steps to reproduce

Use a documented method with `Omnisharp` and observe signature help documentation

### Expected behavior

Clear signature help documentation

### Which Language Server did you use?

OmniSharp

### OS

Linux

**Comment by razzmatazz** [comment]
I believe this is not a problem of `lsp-mode` and should be reported to [omnisharp](https://github.com/OmniSharp/omnisharp-roslyn) instead..

**Comment by salehmu** [comment]
Are you sure? I tested it before in other text editors (VS Code for instance) and it worked just great. I don't have a lot of knowledge about how LSPs work, but what I can superficially think of, is that a procedure of translating the XML tags to make it more readable is needed (I can tell there is already such a something that C# VS Code extinction incurs).

Feb 28, 2022, 07:48 by ***@***.***:

**Comment by razzmatazz** [comment]
99% sure :)

vs code has several protocols implemented:
- vscode uses a custom ("legacy") protocol to communicate to omnisharp -- and that one has more features as well
- `lsp-mode` uses lsp protocol to communicate with omnisharp

thus apparently there is a difference how signature-help is implemented on the "custom" and "lsp" protocols in omnisharp

**Comment by salehmu** [comment]
Cool. I'll report this issue then into the OmniSharp repository, thank you.


Feb 28, 2022, 08:06 by ***@***.***:
