### ISSUE TITLE
Allow users to change project root interactively

### ISSUE THREAD

**Issue by VitalyAnkh** [emacs-lsp/lsp-mode#3357]
lsp-mode will prompt users to choose project root when opening a file for the first time with `lsp--find-root-interactively`. But it's hard to change the project root after choosing a wrong project root, or projectile/project.el is not so smart that it chooses the wrong root automately. To change the root, users should delete the lsp-session-file manually, re-open the file, then answer the question when asked, which is annoying.

I think it's better to allow users to change project root interactively. Users could run`M-x lsp-find-root-interactively`, choose the right directory, then lsp-mode reset the session according to the new directory.

**Comment by yyoncho** [comment]
There is `M-x lsp-workspace-folders-add/remove`.

**Comment by avatar-lavventura** [comment]
@yyoncho After I add the folder should we restart the emacs for the changes to take place?

**Comment by yyoncho** [comment]
@avatar-lavventura there is no need to restart.
