### ISSUE TITLE
Rust-analyzer diagnostic "inactive-code" is not greyed out when preceded by documentation

### ISSUE THREAD

**Issue by ia0** [emacs-lsp/lsp-mode#3388]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Rust-analyzer has a diagnostic called "inactive-code" for code that is gated and inactive with the current set of features. In Emacs, those appear as greyed out. However, when the inactive code is documented then it's not greyed out anymore, although other indications in Emacs are working:
- There is a hint in the left "thin bar"
- Positioning the cursor in the region shows a message that the code is inactive

### Steps to reproduce

Look at [this region](https://github.com/google/OpenSK/blob/47470db7a690b92597d74a6222035b3e68bedaef/libraries/persistent_store/src/lib.rs#L390-L402):
- `git clone git@github.com:google/OpenSK.git`
- `cd OpenSK/libraries/persistent_store`
- `emacs src/lib.rs` on a 64-bits machine. Otherwise just change the "32" to "64".

### Expected behavior

The region should be greyed out (including documentation). Note that removing the documentation but keeping the comment works as expected. But removing the commend and keeping the documentation still fails. So the documentation is the issue. Documentation in Rust is prefixed with `///` while comments are prefixed with `//`.

### Which Language Server did you use?

rust-analyzer

### OS

Linux

**Comment by yyoncho** [comment]
> The region should be greyed out (including documentation). Note that removing the documentation but keeping the comment works as expected. But removing the commend and keeping the documentation still fails. So the documentation is the issue. Documentation in Rust is prefixed with /// while comments are prefixed with //.

Have you checked the server response? lsp-mode is only a frontend and this issue sounds like rust-analyzer is not matching your expectations.

**Comment by ia0** [comment]
> Have you checked the server response? lsp-mode is only a frontend and this issue sounds like rust-analyzer is not matching your expectations.

Yes, the server responds the correct thing:

```
    {
      "tags": [
        1
      ],
      "message": "code is inactive due to #[cfg] directives: feature = \"std\" and target_pointer_width = \"32\" are disabled",
      "source": "rust-analyzer",
      "codeDescription": {
        "href": "https://rust-analyzer.github.io/manual.html#inactive-code"
      },
      "code": "inactive-code",
      "severity": 4,
      "range": {
        "end": {
          "character": 15,
          "line": 401
        },
        "start": {
          "character": 0,
          "line": 389
        }
      }
    }
```

This is also visible in Emacs as written in the bug description because other indicators of this diagnostic are working:
- the left bar stuff
- the message in mini-buffer

This really looks like a coloring issue. The documentation color may win over the inactive code coloring, in a way that even when the documentation is over, the color is not grey. Or the coloring is just not emitted in that case.

**Comment by yyoncho** [comment]
I see. Are you using sem highlighting?

**Comment by ia0** [comment]
I don't know. How can I check? I think my highlighting comes from `rust-mode`, but I don't know if `lsp-mode` or `lsp-ui` adds something one top.

**Comment by yyoncho** [comment]
check `lsp-semantic-tokens-enable`

**Comment by ia0** [comment]
It's disabled (nil), so no I'm not using them.

I tried to enable. The problem is still present and the colors are worse (documentation and comments have the same color: red, while without semantic tokens documentation is purple and comments red).

**Comment by brotzeit** [comment]
So you have the same issue when lsp-mode is turned off ?

**Comment by ia0** [comment]
> So you have the same issue when lsp-mode is turned off ?

Wow, I did not expect this magic. I'm not sure what you meant so I tried the following steps:
- Follow the steps of the first comment.
- Run `lsp-mode` to disable lsp-mode
- Remove the documentation to fix the issue (the inactive code becomes grey). I don't know which magic emacs uses to adjust the region returned by rust-analyzer (because I'm assuming rust-analyzer doesn't run on the updated code) but it's probably based on the edit sequence.

Also I realized that the problem is not about documentation or nested array element. It's actually correlated with the length of the region:
- In the documentation case, if I reduce the length of the documentation+comment to 2 lines, then the problem is fixed.
- In the array case, if I reduce the length of the inactive code to 1 line then the problem is fixed.

So this could maybe even be a feature to only grey short regions.

Do you know how I could proceed to debug this further? I don't know how rust-mode works if that's actually the culprit.

Thanks!

**Comment by ia0** [comment]
Actually to be more precise, it looks like regions of 4 lines or less are greyed out while regions of 5 lines or more are not.

**Comment by ia0** [comment]
Actually, I start to believe this is a flycheck property given the documentation on this mapping: https://github.com/emacs-lsp/lsp-mode/blob/4acf72202d47dd7f0166c69220e1f734d133db89/lsp-diagnostics.el#L61-L69

I don't know what is a `plist` but lsp-mode seems to instruct flycheck to grey the whole region. Note that rust-analyzer gives the tag "1" for inactive code which is unnecessary code according to this line: https://github.com/emacs-lsp/lsp-mode/blob/4acf72202d47dd7f0166c69220e1f734d133db89/lsp-protocol.el#L471

**Comment by ia0** [comment]
Ok so what initially looked like an lsp-mode bug was actually a flycheck feature: https://github.com/flycheck/flycheck/pull/1743

The default is indeed to change behavior at 4 lines: https://github.com/flycheck/flycheck/blob/278d0810f05eb03600d835c2bdd67d6b55a58034/flycheck.el#L647-L648

When I change `flycheck-highlighting-style` to `level-face` then it works as I expect.

Thanks @yyoncho and @brotzeit for your help debugging this. I'm closing the issue since my initial concern is resolved. Feel free to reopen if you think anything needs to be done on lsp-mode side.

**Comment by yyoncho** [comment]
> When I change `flycheck-highlighting-style` to `level-face` then it works as I expect.

do you think that the default should be fixed on flycheck side?

**Comment by ia0** [comment]
> do you think that the default should be fixed on flycheck side?

That's a good question. I think that the current default is confusing but probably the right one for most flycheck usage, based on https://github.com/flycheck/flycheck/issues/1730 asking for this feature.

My personal opinion (with the knowledge/experience I have today, so it might change in the future) would be:
- The default should not be "smart", i.e. `level-face` and not `conditional`.
- Whoever calls into flycheck should tell it to do what they want. In our case, it would be either lsp-mode or even better rust-analyzer. Because configuring the desired behavior in rust-analyzer (or lsp-mode) gives better granularity to say which diagnostics should be represented in which way. For inactive-code, greying a large amount of text is alright because the user is not meant to modify it because it's inactive. But I could see how other diagnostics would not be nice for larger amount of text.

So all in all I think I'll need to experiment with my current setting and see if there are diagnostics for which I would like a different flycheck style. Note that I'm currently looking into lsp-mode code to see if I can disable the underlying part and only keep the grey-out part. I should probably also try to have non-empty delimiters in the flycheck default, maybe I would like it.

**Comment by yyoncho** [comment]
> * Whoever calls into flycheck should tell it to do what they want. In our case, it would be either lsp-mode or even better rust-analyzer.

TBO I don't quite understand the issue but if lsp-mode can tell flycheck to override the face using flycheck interface for integrating backends(in other words, not by changing properties designed to be customized by the user) then we should do it.

**Comment by ia0** [comment]
Here is the issue how I see it:
- Programming languages have different types of diagnostics.
- Diagnostics can have at least a level (info, warning, error), a set of tags (integers), a message, and a range.
- Based on those, lsp-mode construct some flycheck-error with at least buffer, filename, message, level (see below), and range.
- The level can be taken from an existing pool (info, warning, error) or customized with at least severity, fringe bitmap, fringe face, and error list face (which I think is the one greying out according to `lsp-diagnostics-attributes`).
- Some (all default ones actually) error faces underline the region. For example a compilation error (e.g. type mismatch) would underline the region that has a type different from the type expected by the context. This region can be arbitrary long (10s of lines). This can make reading the code harder while you're trying to fix it.
- However, some diagnostics (usually info) are not really errors and in particular the user doesn't even need to look at them at all at any time (unless they reconfigure their lsp server which would then emit different diagnostics and maybe make that region relevant again, e.g. cargo features in rust). The typical example would be inactive code (i.e. code that is not even compiled for the current lsp server configuration). This is ok (and actually expected) that the whole region is grayed out.
- Flycheck can't really make the difference between those cases but it provides the possibility to define custom error level.
- lsp-mode apparently is able to distinguish between those based on the tags provided in the diagnostics (but I don't know if that's enough information in all cases) and currently customizes the face based on the `lsp-diagnostics-attributes` variable.
- However, I don't think lsp-mode has control over the flycheck-highlighting-style at the error level.

I see 2 options:
1. flycheck provides hightlighting style control at the error level definition and lsp-mode provides its users control through a variable similar to `lsp-diagnostics-attributes`.
2. lsp-mode implement the hightlighting style of flycheck (requiring users to set the flycheck highlighting style to a `level-face`) by choosing a different face based on the region size and some user-controlled variable (like `lsp-diagnostics-attributes-big-region`).

Actually writing this, I realized that l can change my `lsp-diagnostics-attributes` variable to:
```lisp
 '(lsp-diagnostics-attributes
   '((unnecessary :foreground "gray" :underline nil)  ; added :underline nil
     (deprecated :strike-through t)))
```
which permits to only remove the underline for "unnecessary" diagnostics instead of all "info" diagnostics (like it is the case by changing the `flycheck-info` face).
