### ISSUE TITLE
lsp-rust-target doesn't seem to be taken into account

### ISSUE THREAD

**Issue by ia0** [emacs-lsp/lsp-mode#3389]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

When I set `lsp-rust-target` to `thumbv7em-none-eabi` and restart the workspace, the change doesn't seem to be taken into account.

### Steps to reproduce

- Set `lsp-rust-target` to non-nil value like `thumbv7em-none-eabi`
- (for debugging) Set `lsp-log-io` to t
- Restart workspace with `lsp-workspace-restart`
- (for debugging) Check `lsp-workspace-show-log`

### Expected behavior

Code protected with `#[cfg(target_pointer_width = "32")]` should not be active but it's not.

(for debugging), we can see that `initializationOptions.cargo.target` is null. Note that when setting `lsp-rust-features` then we actually see the change in the code as well as in the logs with `initializationOptions.cargo.features` being properly set.

### Which Language Server did you use?

rust-analyzer

### OS

Linux

**Comment by yyoncho** [comment]
Seems like you should use lsp-rust-analyzer-cargo-target ?

**Comment by ia0** [comment]
> Seems like you should use lsp-rust-analyzer-cargo-target ?

That's it, thanks!

I'm not sure what `lsp-rust-target` does then. And why the naming between `lsp-rust-features` and `lsp-rust-analyzer-cargo-target` is different.

**Comment by yyoncho** [comment]
I suspect the first one is for `rls`

**Comment by ia0** [comment]
> I suspect the first one is for rls and then got reused for rust-analyzer.

I see, thanks!
