### ISSUE TITLE
Pyright getting initialized in multiple folders

### ISSUE THREAD

**Issue by 8x4y2z** [emacs-lsp/lsp-mode#3393]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

lsp-version: LSP :: lsp-mode 20211115.807, Emacs 29.0.50, windows-nt
emacs version: GNU Emacs 29.0.50 (build 1, x86_64-w64-mingw32)

In a freshly started emacs session, If I navigate to any project and open a python script, pyright server is initialized not only in current project root, but also in recently opened projects' roots. This causes significant delay, at least in windows. I'm having to repeatedly delete the `.lsp-session-v1` file and start over all again. 

I believe this is an issue with lsp-pyright, because this doesn't happen with other servers Ex: clangd

Thank You

### Steps to reproduce

In an emacs session, open python scripts in multiple projects, 

### Expected behavior

Pyright should be initialized in the current project root, and not in previously opened projects' roots.

### Which Language Server did you use?

Pyright

### OS

Windows

### Error callstack

```emacs-lisp
No error
```

**Comment by yyoncho** [comment]
this is the expected behaviour, use lsp-pyright-multi-root to change it
