### ISSUE TITLE
Replace vscode-*-languageserver-bin

### ISSUE THREAD

**Issue by sei40kr** [emacs-lsp/lsp-mode#3395]
- [vscode-css-languageserver-bin](https://github.com/vscode-langservers/vscode-css-languageserver-bin)
- [vscode-html-languageserver-bin](https://github.com/vscode-langservers/vscode-html-languageserver-bin)
- [vscode-json-languageserver-bin](https://github.com/vscode-langservers/vscode-json-languageserver-bin)

They're now all archived.

[vscode-langservers-extracted](https://github.com/hrsh7th/vscode-langservers-extracted) can replace them.
It contains the language servers extracted by VSCode.

> Microsoft provided awesome Language Servers for the community but it didn't update for a long time.
> Currently, the latest css-language-server is improved a bit than vscode-css-langserver-bin.

**Comment by kiennq** [comment]
> * [vscode-css-languageserver-bin](https://github.com/vscode-langservers/vscode-css-languageserver-bin)
> * [vscode-html-languageserver-bin](https://github.com/vscode-langservers/vscode-html-languageserver-bin)
> * [vscode-json-languageserver-bin](https://github.com/vscode-langservers/vscode-json-languageserver-bin)

I'm not even sure if those are managed by Microsoft, lol

**Comment by sei40kr** [comment]
@kiennq Thank you!
