### ISSUE TITLE
Improve typescript performance

### ISSUE THREAD

**Issue by otavioschwanck** [emacs-lsp/lsp-mode#3410]
I Compared the same language server, Vim VS Emacs, and the difference is absurd.  Emacs took 2~3s to load a completion while in vim, < 1s.

Demo gif:
![Kapture 2022-03-16 at 15 25 58](https://user-images.githubusercontent.com/9551316/158661272-8b767112-3f59-4540-b19b-88ab8836fca5.gif)

Obs: already tried gcc emacs, same results.

EDIT:

Doom config:  https://github.com/otavioschwanck/doom-emacs-on-rails
(n)vim config: https://github.com/otavioschwanck/nvim-on-rails

Emacs info: https://pastebin.com/d8ntFxmg

OS: Mac OS m1 (air 2020)

**Comment by yyoncho** [comment]
With that much info I don't think we can do anything... No step to reproduce, no sample minimal configuration to prove that you have the correct settings, etc

**Comment by otavioschwanck** [comment]
@yyoncho edited with the configurations

**Comment by yyoncho** [comment]
These configs are not minimal and still, there is no project to test with. Even more, the vim setup is not using the same server as lsp-mode...  You haven't specified any of the information required for reporting performance issues: https://emacs-lsp.github.io/lsp-mode/page/performance/
