### ISSUE TITLE
All of the Github "Edit this page" links on https://emacs-lsp.github.io/lsp-mode/ are broken

### ISSUE THREAD

**Issue by spookylukey** [emacs-lsp/lsp-mode#3413]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

On https://emacs-lsp.github.io/lsp-mode/ for example, if you click the "Edit this page" (pencil icon) link, it goes to https://github.com/emacs-lsp/lsp-mode/edit/master/docs/README.md which is a 404. I can't work out what the correct link should be.

This also means that I can't work out how to contribute help or fixes to any of the pages.

I also can't work out if this is the right place to report this bug, but there doesn't seem to be anywhere else.

### Steps to reproduce

-

### Expected behavior

-

### Which Language Server did you use?

-

### OS

Linux

**Comment by yyoncho** [comment]
The proper link is https://github.com/emacs-lsp/lsp-mode/edit/master/README.md . Maybe @ericdallo  will know how to fix the generated link.

**Comment by ericdallo** [comment]
We were discutting on discord #development, but basically we copy the readme to docs folder when generating, maybe we could symlink instead?
Butt besides that all languages page have the same issue, we would need to think in something that would fix for most pages

**Comment by elken** [comment]
This should be resolved now after the docs have built, thanks for reporting this! I actually noticed it a few days ago myself but I assumed it was just one page.
