### ISSUE TITLE
Poor performance with lua-mode (lua-language-server)

### ISSUE THREAD

**Issue by rieje** [emacs-lsp/lsp-mode#3435]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections

### Bug description

Poor performance with lua-mode (lua-language-server). Cursor jumps when moved, minibuffer and mouse cursor flickers repeatedly. Logs get spammed (not sure if normal).

### Steps to reproduce

With [these relevant settings](https://0x0.st/oqZ8.txt), I restart Emacs and open lua file. there's nothing indicating any IDE features unless I switch to another buffer and then switch back to this lua buffer, then I see the IDE-like features. If I hold down the cursor by holding up/down/left/right, cursor doesn't move slowly but instead jumps around and may take a full second to appear.

When I switched away from the lua buffer for the first time, I get `*Warnings*` buffer popup saying:

>     Warning (lsp-mode): Unknown notification: workspace/semanticTokens/refresh

Returning to the lua buffer, I also notice the minibuffer and the mouse cursor flickering really fast non-stop. In the `*Messages*` buffer, I see:

>     LSP :: Connected to [lua-language-server:220110]. [2311 times]

So it's getting spammed, not sure if this is normal. I haven't explicitly enabled run debugging tools or set them enabled. `*lsp-log*` is also spammed with: 

> The following clients were selected based on priority: (server-id lua-language-server, priority -2) Found the following clients for /home/rofic/.config/mpv/scripts/stamps.lua: (server-id lua-language-server, priority -2)

I see another [log](https://0x0.st/oqZO.txt) at `~/.emacs.d/.cache/lsp/lua-language-server/extension/server/log/file_home_rofic_mpv_scripts.log where contents are spam written to disk--again, not sure if this is normal but I assume it's being unreasonable to my SSD. 

Following the doc for [improving performance](https://emacs-lsp.github.io/lsp-mode/page/performance/), I have the variables set: `(setq read-process-output-max (* 1024 1024)) (setq gc-cons-threshold 100000000)` and satisfied `lsp-doctor` with everything except "Using emacs 28+ with native compilation*". But didn't seem to make much of a noticeable difference.

On Arch Linux, I simply installed `lua-language-server` (latest version 2.6.7) package and do not do anything else with it and on Emacs, using the latest version `lsp-mode` and `lua-mode` as of yesterday (removed elpa/{lsp*,lua*}) packages and started fresh.

### Expected behavior

Reasonable performance, e.g. cursor moves around without "input lag" as if normal.

### Which Language Server did you use?

lsp-lua. Profile report [here](https://0x0.st/oqcj.txt).

### OS

Linux

### Anything else?

Disclaimer: complete noob at Emacs and programming, don't have any experience with lsp-mode or even using Emacs as an IDE.

**Comment by yyoncho** [comment]
`(use-package lua-mode
:hook (lsp-mode . lsp-deferred))`

This is wrong and most likely causing your perf issues.

**Comment by rieje** [comment]
I changed it to simply `(use-package lua-mode)` and now am no longer experiencing any of the errors except I still get the error in `*Warning*` buffer:

    Warning (lsp-mode): Unknown notification: workspace/semanticTokens/refresh

I assume this is harmless or anything I can do about it? In any case, the primary issue is fixed, thank you.

**Comment by yyoncho** [comment]
If the warning persist after upgrading lsp-mode and the server to the latest versions then open another issue
