### ISSUE TITLE
lsp-eslint doesn't respect `working-directories` setting

### ISSUE THREAD

**Issue by PenguinToast** [emacs-lsp/lsp-mode#3438]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

`lsp-eslint` ignores the `lsp-eslint-working-directories` variable.

### Steps to reproduce

Open a file that uses `lsp-eslint` with `lsp-eslint-working-directories` set to anything, and `lsp-log-io` set to `t`. You'll see that the response to `workspace/configuration` does not include the `workingDirectores` setting.

### Expected behavior

`lsp-eslint` should send `workingDirectories` in the `workspace/configuration` response when `lsp-eslint-working-directories` is set.

### Which Language Server did you use?

lsp-eslint

### OS

Linux

### Anything else?

I was able to fix this by adding `:workingDirectories (vector lsp-eslint-working-directories)` below this line: https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-eslint.el#L281 -- however, it's unclear to me why I need to wrap `lsp-eslint-working-directories` in a vector (when the variable is already set to a vector) so I'm not sure if this is the correct fix.

**Comment by mpsq** [comment]
I can confirm this is still an issue. I set `lsp-eslint-working-directories` from `.dir-locals.el` but it is not passed to the `eslint` server, the logs show that this setting is ignored.

**Comment by mpsq** [comment]
I spent some time debugging this, it turns out that `workingDirectories` is not passed to the server, instead the lsp client transforms `workingDirectories` to `workingDirectory` alongside the other params. Example of a config set by the VSCode EsLint extension:


```
```
