### ISSUE TITLE
flycheck with lsp-mode ignores the C/C++ standard used for checking/linting

### ISSUE THREAD

**Issue by Nathan-Furnal** [emacs-lsp/lsp-mode#3450]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

I have added a hook to `c++-mode` such that: 

```elisp
(use-package cc-mode
  :ensure nil
  :hook ((c++-mode-hook . (lambda ()
			    (setq comment-start "/**")
			    (setq comment-end "*/")
			    (setq flycheck-clang-language-standard "c++20"
				  flycheck-clang-args '("-std=c++20") ;; removing this does not change anything
				  flycheck-gcc-language-standard "c++20")))
	 (c-mode-hook . (lambda ()
			  (setq flycheck-clang-language-standard "c17"
				flycheck-gcc-language-standard "c17")))))
```

Which was posted as a fix for flycheck not recognizing the proper language standards in [this SO issue](https://stackoverflow.com/questions/30949847/configuring-flycheck-to-work-with-c11). 

Yet using a recent C++17 feature is highlighted by flycheck as an error (the compiler does not complain). 

This issue is due to LSP since launching a file without LSP does not have this problem and flycheck behaves properly.

![image](https://user-images.githubusercontent.com/45597572/162017229-64bf63bc-225c-41c5-b5f1-cacf080bee1e.png)

### Steps to reproduce

1. Use flycheck with the above setup and LSP enabled when the buffer is visited.
2. Write to a `.cpp` file with a recent C++ feature like `std::optional` (added in C++17). 
```cpp
#include <optional>
#include <string>

// optional can be used as the return type of a factory that may fail
std::optional<std::string> create(bool b) {
    if (b)
        return "Godzilla";
    return {};
}
```

### Expected behavior

Flycheck allows features like `std::optional` if its language standard is appropriate to know of the feature when LSP is used.

### Which Language Server did you use?

`clang` and I'm using the master branch of Emacs.

### OS

Linux

### Error callstack

```emacs-lisp
No error call stack.
```

### Anything else?

Yes, images of the issue and the system configuration for flycheck.

Flycheck configuration: 

```
Syntax checkers for buffer optional-error.cpp in c++-mode:

First checker to run:

  lsp (explicitly selected)
    - may enable: yes
    - may run:    t

Checkers that could run if selected:

  c/c++-clang  select
    - may enable:    yes
    - executable:    Found at /usr/bin/clang
    - next checkers: c/c++-cppcheck

  c/c++-gcc  select
    - may enable:    yes
    - executable:    Found at /usr/bin/gcc
    - next checkers: c/c++-cppcheck

Checkers that are compatible with this mode, but will not run until properly configured:

  c/c++-cppcheck (automatically disabled) reset
    - may enable: no
    - executable: Not found

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled checkers.

--------------------

Flycheck version: 33snapshot (package: 20220328.1518)
Emacs version:    29.0.50
System:           x86_64-pc-linux-gnu
Window system:    pgtk
```

Using `M-x flycheck-compile` with clang or gcc, as explained in the flycheck troubleshooting guide works properly and no error is detected. The language standard I selected is also used correctly. The error only happens when LSP is enabled at startup.

![image](https://user-images.githubusercontent.com/45597572/162018265-e3a8d73b-a28e-4592-9d2a-9bea011218d2.png)

**Comment by yyoncho** [comment]
Issues like that are caused by server misconfiguration. Marking the issues as closed, but you can use it for further questions.

Have you configured compile_commands.json as described here: https://emacs-lsp.github.io/lsp-mode/tutorials/CPP-guide/ ?

**Comment by Nathan-Furnal** [comment]
I haven't, I was just using `compile_flags.txt` ([see here](https://releases.llvm.org/8.0.0/tools/clang/tools/extra/docs/clangd/Installation.html#compile-flags-txt)) because it's more understandable to me and easier to read but the issue is that I'd like to use both C and C++ in a project and the `compile_flags.txt` are only valid for one compiler at the time so it'll complain about C++ code if I write `--std=c17` and it will complain about C if I use `--std=c++17`. 

I honestly would like to just set those defaults for all my files without having yet another configuration file. If it becomes too much of a hassle I guess I'll have to generate the compile database :(

**Comment by yyoncho** [comment]
1. lsp-mode does not pass the compile flags or anything to the server - this information is gathered by the server using compile_commands. lsp-mode just starts the server and tells it where the project root is. The protocol itself does not have the notion of CPP versions, etc.
2. If flycheck-gcc and/or flycheck-clang work for you you can disable lsp checker by setting lsp-diagnostics-provider to :none

**Comment by Nathan-Furnal** [comment]
Thanks for the solutions, using `bear` like in the LSP tutorial for C/C++ might be a solution when my Makefile or CMake is setup but during the 'exploratory' phase of the project, I'll probably just disable it as you said.

Thanks for the explanation!
