### ISSUE TITLE
inlayHint method for rust-analyzer is incorrect

### ISSUE THREAD

**Issue by nebkor** [emacs-lsp/lsp-mode#3470]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

In https://github.com/rust-lang/rust-analyzer/pull/11935, merged into r-a's `master` five day ago, the method name for inlay hints was updated to reflect the official wording in the upcoming 3.17 version of the LSP spec. Within rust-analyzer, that means the method went from being named `experimental/inlayHints` to `textDocument/inlayHint`, and the parameters were changed to include a range.

### Steps to reproduce

Use rust-analyzer as an LSP server and lsp-rust as the client, and witness the errors from r-a about "method not found", and the lack of inlay hints in your Rust buffer.

### Expected behavior

Inlay hints to be properly displayed.

### Which Language Server did you use?

lsp-rust, rust-analyzer.

### OS

Linux

### Anything else?

I've already opened a PR to fix this, #3467 .

**Comment by yyoncho** [comment]
cc @shivjm

**Comment by yyoncho** [comment]
Actually, @shivjm  wrote the JS version. We have to see how to unify RA version and JS version and merge the change in core.
