### ISSUE TITLE
Nested go.mod files not handled well

### ISSUE THREAD

**Issue by raxod502-plaid** [emacs-lsp/lsp-mode#3473]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

lsp-mode does not seem to work transparently with nested modules under gopls. When having a nested go.mod file in a subdirectory of a repository, autocompletions and source navigation do not work for the code in the nested project.

### Steps to reproduce

Sample code: https://github.com/raxod502-plaid/gopls-issue-repro

Upon opening `main.go` at the root of the repository, LSP prompts to add the repository root as a workspace directory. This is correct, and required to get autocompletions for that file. Autocompletions work fine for files outside the subproject.

However, upon opening `subproject/main.go` in the subproject, LSP does not realize that it needs a separate workspace directory, and uses the existing repository root for it. This causes errors to immediately appear (e.g., in `lsp-start-plain`, errors are highlighted with Flycheck; see screenshots below).

This error appears in `*lsp-log*`:

```
2022/04/18 09:59:31 errors loading workspace: You are working in a nested module.
Please open it as a separate workspace folder. Learn more:
https://github.com/golang/tools/blob/master/gopls/doc/workspace.md.
	snapshot=16
	directory=file:///Users/rrosborough/gopls-issue-repro
```

Screenshots:

<details>

<img width="956" alt="image" src="https://user-images.githubusercontent.com/69264599/163844516-f9baf814-b131-4658-b65e-86cafc1aa195.png">
<img width="955" alt="image" src="https://user-images.githubusercontent.com/69264599/163844535-0e47a724-6cd2-462c-b5e5-516e9d245878.png">
<img width="958" alt="image" src="https://user-images.githubusercontent.com/69264599/163844550-d63e20f0-556c-4260-8c4e-400713cd5a94.png">

</details>

### Expected behavior

lsp-mode should automatically detect the nested go.mod file and use a separate workspace directory for files under that directory, with no user intervention required.

Or, if this is not possible, instructions on how to manually configure lsp-mode to work correctly for a multi-module project should be available at https://emacs-lsp.github.io/lsp-mode/page/lsp-gopls/.

### Which Language Server did you use?

gopls

### OS

macOS

### Anything else?

See also:
* https://github.com/golang/go/issues/32394
* https://github.com/emacs-lsp/lsp-mode/issues/1978
* https://github.com/emacs-lsp/lsp-mode/issues/1275

This is tested using macOS Monterey 12.3.1, Emacs 28.1 configured `--with-json --with-native-compilation`, gopls https://github.com/emacs-lsp/lsp-mode/commit/e1e2a49bb2d11490d20bd73ea0d886b775cb26ad via https://github.com/raxod502/straight.el/commit/e2de88ea0e7ccf9f4846e9e756f86e0dcf469c44, and gopls 0.7.5.

**Comment by raxod502-plaid** [comment]
It looks like with https://github.com/emacs-lsp/lsp-mode/pull/2619 it might be possible now to simply `M-x lsp-workspace-folders-add` on the subproject directory, then re-initialize with `M-x lsp`. Amazing! (Would be great if it were autodetected, though.)

**Comment by yyoncho** [comment]
> It looks like with https://github.com/emacs-lsp/lsp-mode/pull/2619 it might be possible now to simply M-x lsp-workspace-folders-add on the subproject directory, then re-initialize with M-x lsp. Amazing! (Would be great if it were autodetected, though.)

We cannot solve automatically problems like that because everything is case by case. That is why we leave to the user to interactivelly select the project roots.

**Comment by raxod502-plaid** [comment]
Would a pull request be accepted to add documentation to https://emacs-lsp.github.io/lsp-mode/page/lsp-gopls/ about how to resolve this error message?

**Comment by yyoncho** [comment]
Of course.

**Comment by raxod502-plaid** [comment]
Awesome, will try to submit something later this week.

**Comment by raxod502** [comment]
Created https://github.com/emacs-lsp/lsp-mode/pull/3483.
