### ISSUE TITLE
rust-analyzer crashes from tramp lsp-mode

### ISSUE THREAD

**Issue by buzmeg** [emacs-lsp/lsp-mode#3491]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

When attempting to open a file via tramp, the remote rust-analyzer crashes with error:

```
% cat rust-analyzer-remote-1-stderr
[ERROR rust_analyzer] Unexpected error: expected initialize request, got error: receiving on an empty and disconnected channel
expected initialize request, got error: receiving on an empty and disconnected channel
```

### Steps to reproduce

```
$ emacs -q -l lsp-start-rust-analyzer.txt /ssh:dummy@192.168.12.138:rust/rs-daplink/src/main.rs
```

lsp-start-rust-analyzer.txt included below:
[lsp-start-rust-analyzer.txt](https://github.com/emacs-lsp/lsp-mode/files/8559490/lsp-start-rust-analyzer.txt)

### Expected behavior

rust-analyzer not crashing

### Which Language Server did you use?

rust-analyzer

### OS

Linux

**Comment by patmryan** [comment]
I get the same issue. When I try to troubleshoot by setting `lsp-log-io` to `t`, the server does not immediately crash. Instead, I get an error `LSP :: Error from the Language Server: waiting for cargo metadata or cargo check (Unknown error)` and then it hangs.

**Comment by ileixe** [comment]
Me either with exactly same log reported by @patmryan

**Comment by gcohara** [comment]
i'm also having this problem. is there a way around, perhaps running `rust-analyzer` locally rather than remotely?

**Comment by kiennq** [comment]
@gcohara, which Emacs version are you on? Also do you use the latest Tramp from elpa as well?

**Comment by gcohara** [comment]
Emacs version 28.1, TRAMP version 2.5.2.28.1

**Comment by cosven** [comment]
I met the exact same problem.

GNU Emacs 28.1 (build 1, x86_64-apple-darwin21.1.0, NS appkit-2113.00 Version
 12.0.1 (Build 21A559)) of 2022-08-29
TRAMP version 2.5.2.28.1

**Comment by sp1ff** [comment]
Same here... intermittently. 

GNU Emacs 30.0.50 (built from source), tramp 2.7.0-pre. Arch Linux x86_64
