### ISSUE TITLE
Support LSP 3.17 inlayHints

### ISSUE THREAD

**Issue by kiennq** [emacs-lsp/lsp-mode#3492]
Clangd has supported inlay hints in v14, we should support it as well https://clangd.llvm.org/extensions#inlay-hints

**Comment by ericdallo** [comment]
@kiennq does that already follows LSP 3.17 inlayHints spec?

**Comment by kiennq** [comment]
Sorry for the late reply, it should follow the official inlayHints specs.
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_inlayHint

**Comment by inclyc** [comment]
May duplicate to https://github.com/emacs-lsp/lsp-mode/issues/3292. Currently I can see inlay hints works very well for rust-analyzer but not for `clangd`.
