### ISSUE TITLE
Javascript function parameters completion

### ISSUE THREAD

**Issue by kuator** [emacs-lsp/lsp-mode#3498]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

typescript-language-server added function parameters completion: https://github.com/typescript-language-server/typescript-language-server/pull/303. Setting the emacs-lsp's `lsp-javascript-suggest-complete-function-calls` setting doesn't seem to change anything.

### Steps to reproduce

```
  (use-package lsp-mode
    :config
    (add-hook 'c++-mode-hook #'lsp)
    (setq
     lsp-javascript-suggest-complete-function-calls t
     lsp-typescript-suggest-complete-function-calls t)
    :custom
    (lsp-enable-snippet t))
```

### Expected behavior

Function parameters getting completed

### Which Language Server did you use?

typescript-language-server

### OS

Linux

### Error callstack

```emacs-lisp
For some reason, the log becomes 200 000 lines long after completion and I can't paste it
```

### Anything else?

I managed to make it work with neovim

**Comment by yyoncho** [comment]
Hey @shivjm, willing to take a look?

**Comment by shivjm** [comment]
Yup, happy to!

**Comment by shivjm** [comment]
The settings are being correctly propagated from lsp-mode to the server, but the server never returns this kind of suggestion. The suggestion mechanism does seem to work for automatic imports, so it’s specific to this kind of completion. I’ll keep digging.

**Comment by kuator** [comment]
I'm not sure if it helps, but here's a discussion of the functionality's behaviour: https://github.com/hrsh7th/nvim-cmp/issues/646#issuecomment-992765479

**Comment by kuator** [comment]
Thank you!

**Comment by yyoncho** [comment]
I will keep it open - we might think of some hacky solution to avoid server bugs...

**Comment by davidmicah123** [comment]
https://openbase.com/js/typescript-language-server/documentation
