### ISSUE TITLE
yas insert unneeded parentheses

### ISSUE THREAD

**Issue by k4leg** [emacs-lsp/lsp-mode#3499]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Completion inserts unneeded parentheses.

### Steps to reproduce

Watch [the video](http://0x0.st/oANE.mp4) and see [the config](http://0x0.st/oANI.el).

### Expected behavior

No unneeded parentheses.

### Which Language Server did you use?

`pylsp`

### OS

Linux

### Error callstack

```emacs-lisp
Command "pyls" is not present on the path.
Command "pylsp" is present on the path.
Command "pyls" is not present on the path.
Command "pylsp" is present on the path.
Found the following clients for /home/k4leg/repositories/other/test/main.py: (server-id pylsp, priority -1)
The following clients were selected based on priority: (server-id pylsp, priority -1
```

### Anything else?

If you delete yas, then it works well. If you write `the_arg` instead of `the_arg=None` in function header, then it works well.  If you use `completion-at-point` instead of company-mode, then it still broke. If you use only yas (without lsp-mode, company-mode), then `dabbrev-expand`, `hippie-expand`, `pcomplete-expand` works well.

**Comment by yyoncho** [comment]
Please report that in the language server that you are using. lsp-mode is just a frontend and it just inserts whatever the server has sent.

**Comment by k4leg** [comment]
> Please report that in the language server that you are using. lsp-mode is just a frontend and it just inserts whatever the server has sent.

But... WITHOUT yasnippet it works well—`pylsp` has nothing to do with it. `pylsp` also works well in neovim with the `coq_nvim` plugin.

**Comment by yyoncho** [comment]
If yasnippet is not present the snippets are off and the server is not sending `()`. If you enable the logs as described in the bug template, you will see that the server is sending `()`. Neither lsp or yasnippet will insert `()` by themselves.

**Comment by yyoncho** [comment]
> If you write the_arg instead of the_arg=None in function header, then it works well. 

Also, this clearly indicates that the issue is on the server because lsp/yasnippet don't care about the content of the buffer.

**Comment by k4leg** [comment]
> If yasnippet is not present the snippets are off and the server is not sending `()`. If you enable the logs as described in the bug template, you will see that the server is sending `()`. Neither lsp or yasnippet will insert `()` by themselves.

Thanks for answer!  I find similar issue: https://github.com/python-lsp/python-lsp-server/issues/98.
