### ISSUE TITLE
LSP mode opens directories from every project ever opened

### ISSUE THREAD

**Issue by quodlibetor** [emacs-lsp/lsp-mode#3502]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

As soon as I activate LSP in any buffer every directory from every project -- sometimes it seems like it's only projects in the same language, sometimes it seems like it's every project irrespective of language -- I've ever opened LSP mode in.

### Steps to reproduce

* Open emacs, go to some project and open it in lsp mode
* go to a different project and open lsp mode
* close emacs
* reopen emacs, open that first project
* observe (on macos via `lsof -p EMACS_PID`) that directories from the second project are held open by emacs.

### Expected behavior

Only directories within projects that I have actively opened in this emacs session are open.

Ideally, when I close all LSP buffers from a project, the associated open files should also close.

### Which Language Server did you use?

I have observed this with `lsp-pyright`, `lsp-terraform`, `tsls`.

### OS

MacOS

**Comment by yyoncho** [comment]
That is what is expected to happen. When you have multiroot language servers - they are persisted and next time the server is started for them and then file watches are established for that root. Multi root support can be turned off for some servers, e. g.  `lsp-pyright-multi-root` for pyright.

**Comment by quodlibetor** [comment]
Ah. For other folks who get confused by this you can remove old workspaces with <kbd>M-x</kbd> `lsp-workspace-folders-remove`
