### ISSUE TITLE
Allow disable the "There are no language servers supporting current mode..." error

### ISSUE THREAD

**Issue by daanturo** [emacs-lsp/lsp-mode#3532]
Is your feature related or already mentioned on [the wishlist](https://github.com/emacs-lsp/lsp-mode/discussions/2892)?

No

Describe your feature here.

With minimal configuration:
```lisp
(add-hook 'prog-mode-hook 'lsp-deferred)
```
For major modes that derive from `prog-mode` but doesn't have LSP support, `lsp-mode` emits a pretty scary and lengthy error: "There are no language servers supporting current mode ..." which takes multiple lines in the echo area.

Also the check before that at [lsp-mode.el#L8609](https://github.com/emacs-lsp/lsp-mode/blob/11c0c7af611ecb63f7797caae66fb03ba10c8c1e/lsp-mode.el#L8609)
```lisp
(-> #'lsp--supports-buffer? lsp--filter-clients not)
```
isn't cheap to perform (~0.2s+ on average for me).

Therefore I think we should allow optionally skippping that `cond` branch.

**Comment by jenia** [comment]
I'm still getting this error for elisp files. How do I suppress it?

**Comment by jenia** [comment]
I did `(setq lsp-warn-no-matched-clients nil)` as mentioned [here](https://github.com/emacs-lsp/lsp-mode/pull/3533), seems to work.
