### ISSUE TITLE
Minimum required version of (emacs "26.1") does not contain json-parse-buffer.

### ISSUE THREAD

**Issue by Fuco1** [emacs-lsp/lsp-mode#3536]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

The function `json-parse-buffer` does not exist in older Emacs versions.  We should include some compat layer.

```
Warning (lsp-mode): Failed to parse the following chunk:
’’’
Content-Length: 126

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"May 23, 2022, 9:24:30 PM Main thread is waiting"}}
’’’
with message (void-function json-parse-buffer)
```

### Steps to reproduce

Try to parse any json on Emacs 26

### Expected behavior

Emacs should not error out with void function error.

### Which Language Server did you use?

lsp-java

### OS

Linux

**Comment by Fuco1** [comment]
Probably this check needs to test for the correct function, WDYT?

![image](https://user-images.githubusercontent.com/2664959/169894213-eec358f9-bca2-4660-b05c-ba785e75207b.png)

**Comment by yyoncho** [comment]
We require 26.3 but it should fail on a different place. Both `json-parse-buffer` and `json-parse-string` are part of `json.c` (https://github.com/emacs-mirror/emacs/blob/emacs-28/src/json.c#L925) . I would expect that issue to happen if you have compiled the code with emacs 27.1+ and then you try to use it with emacs 26.1. Although another user reported a similar issue and they ended up upgrading emacs.

**Comment by yyoncho** [comment]
do you have `json-parse-string` defined in your setup?

**Comment by Fuco1** [comment]
I'm using Emacs 26.3 and I've never had any 27+ version on this computer.  

I have the function `json-parse-string` but it comes from some package called `compat` which was pulled in probably by `no-littering` since I can't find any other package with that dependency.  For some reason the compat package does not define the `json-parse-buffer`.  It must be a bug in their code.

However, I think it would still be safer to check for the correct function in `lsp-mode`, considering the "dynamic" nature of Emacs.  BTW this compat package comes from GNU ELPA so it seems to be at least semi-supported by Emacs core.  Seems to me it's something like polyfills for JS.

------------------

About the required version, here is still 26.1.

```
;; Package-Requires: ((emacs "26.1") (dash "2.18.0") (f "0.20.0") (ht "2.3") (spinner "1.7.3") (markdown-mode "2.3") (lv "0"))
```

**Comment by yyoncho** [comment]
> For some reason the compat package does not define the `json-parse-buffer`. It must be a bug in their code.

I pushed a fix relying on this.
