### ISSUE TITLE
Upgrade XML Language Server to 0.20.0

### ISSUE THREAD

**Issue by apupier** [emacs-lsp/lsp-mode#3543]
Is your feature related or already mentioned on [the wishlist](https://github.com/emacs-lsp/lsp-mode/discussions/2892)?

Describe your feature here.

see https://github.com/eclipse/lemminx/releases/tag/0.20.0

Current version used is 0.18.0 https://github.com/emacs-lsp/lsp-mode/blob/8123c5cd33bedf3ac5e88d98ede690f73b7f1b00/clients/lsp-xml.el#L192

**Comment by Walheimat** [comment]
I'm about to open a PR to upgrade to 0.21.0 and add the new formatting options.

**Comment by yyoncho** [comment]
> I'm about to open a PR to upgrade to 0.21.0 and add the new formatting options.

sounds good, go ahead.
