### ISSUE TITLE
Customizable spinner type

### ISSUE THREAD

**Issue by visd0m** [emacs-lsp/lsp-mode#3544]
Wouldn't it be nice to be able to customize the spinner used by `lsp-mode` [here](https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el#L2059)? At the moment it seems to me that the`'progress-bar` type is "hardcoded" but I may be wrong 😅.

If the point seems reasonable I would like to add a customizable variable `lsp-progress-spinner-type` which can be set with one of the symbols handled by the [spinner package](https://github.com/Malabarba/spinner.el).

The variable if set will be used by the function `lsp-on-progress-legacy` if not the `'progress-bar` symbol will be used.

**Comment by yyoncho** [comment]
Looks ok to me.
