### ISSUE TITLE
Error: Wrong type argument: lsp--workspace, nil

### ISSUE THREAD

**Issue by stardiviner** [emacs-lsp/lsp-mode#355]
When I in JS source code file enable lsp-mode, company-lsp. I got this error:
```
Company: backend company-lsp error "Wrong type argument: lsp--workspace, nil" with args (prefix)
```
Here is my config
```elisp
(use-package lsp-mode
  :ensure t
  :defer t
  :preface (setq lsp-enable-flycheck nil
                 lsp-enable-indentation nil
                 lsp-highlight-symbol-at-point nil)
  :init (add-hook 'prog-mode-hook #'lsp-mode))

(use-package lsp-ui
  :ensure t
  :init (add-hook 'lsp-after-open-hook #'lsp-ui-mode))

(use-package company-lsp
  :ensure t
  :init (push 'company-lsp company-backends)
  :config
  (setq company-lsp-enable-recompletion t
        company-lsp-enable-snippet t
        company-lsp-cache-candidates t
        company-lsp-async t)
  )
```

**Comment by yyoncho** [comment]
Which language server do you use? Did you call the lsp-{language}-enable in the buffer you are trying to 

>> :init (add-hook 'prog-mode-hook #'lsp-mode) 

you could delete that line, lsp-{language}-enable will take care of that.

**Comment by stardiviner** [comment]
I use `lsp-javascript-typescript`.
edit file `index.js` in a JS project which initialized with `npm init`.
I execute `lsp-javascript-typescript-enable` in JS source code file. still got this error. I have `javascript-typescript-langserver` installed with `npm`.

**Comment by vibhavp** [comment]
Have you tried updating the `company-lsp` package?

**Comment by stardiviner** [comment]
I updated company-lsp before. Use latest version on MELPA. I tried again. It works now. Don't know what caused this problem. Thanks for your help @vibhavp .

**Comment by jonasws** [comment]
@stardiviner I am encountering the exact same error. Any idea on what the error may have been? Did you change something in your `init.el`? Care to post a dump of which packages you have installed, along with any relevant configs?

Would be mostly appreciated!

**Comment by yyoncho** [comment]
@jonasws what language server do you use? I usually get that error when the language server has crashed/failed to start. You may check whether the LSP server process is up and running.

**Comment by jonasws** [comment]
I am using the `javascript-typescript-langserver` language server. FYI I am using the `react` layer from Spacemacs where this error occurs. I will check out how the actual language server process is doing.

**Comment by jonasws** [comment]
I tried digging into the details of the langserver itself, without any luck. Does the langserver have to be fired up on a particular port? Isn't this supposed to be handled "automatically"?

**Comment by ar1a** [comment]
I'm getting this error whenever I quit emacs after using LSP

**Comment by jonasws** [comment]
I get the error whenever I  reach some point in the code that is eligible for completion.

**Comment by yyoncho** [comment]
@jonasws you may check whether the external process(LSP server) is running from your task manager.  At this point LSP mode does not handle server crashed event gracefully(https://github.com/emacs-lsp/lsp-mode/issues/285) so if your server has crashed/not started you will get that error.

**Comment by stardiviner** [comment]
Weird, I got this problem again! and here is the traceback:
```
Debugger entered--Lisp error: (wrong-type-argument lsp--workspace nil)
  signal(wrong-type-argument (lsp--workspace nil))
  company-lsp(prefix)
  apply(company-lsp prefix)
  company--force-sync(company-lsp (prefix) company-lsp)
  company--multi-backend-adapter((company-lsp :with company-yasnippet) prefix)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer *Org Src My JavaScript Language Syntax Reference.org[ js ]*> #<window 8 on *Org Src My JavaScript Language Syntax Reference.org[ js ]*> 50 43)
  apply(company-idle-begin (#<buffer *Org Src My JavaScript Language Syntax Reference.org[ js ]*> #<window 8 on *Org Src My JavaScript Language Syntax Reference.org[ js ]*> 50 43))
  timer-event-handler([t 23327 35142 311121 nil company-idle-begin (#<buffer *Org Src My JavaScript Language Syntax Reference.org[ js ]*> #<window 8 on *Org Src My JavaScript Language Syntax Reference.org[ js ]*> 50 43) nil 362999])
```
And the external language `lsp-javascript-typescript` is not started at all.

Here is my config:
```elisp
(use-package lsp-mode
  :ensure t
  :preface (setq lsp-enable-flycheck nil
                 lsp-enable-indentation nil
                 lsp-highlight-symbol-at-point nil)
  )

(use-package lsp-ui
  :ensure t
  :init (add-hook 'lsp-after-open-hook #'lsp-ui-mode)
  :config
  (setq lsp-ui-doc-enable nil
        lsp-ui-doc-header t
        lsp-ui-doc-include-signature t
        ;; lsp-ui-doc-position 'at-point
        )
  )

(use-package company-lsp
  :ensure t
  :init
  (defun my:company-lsp-enable ()
    (my-company-add-backend-locally 'company-lsp))
  (add-hook 'lsp-mode-hook #'my:company-lsp-enable)
  :config
  (setq company-lsp-enable-recompletion t
        company-lsp-enable-snippet t
        company-lsp-cache-candidates t
        company-lsp-async t)
  )

(use-package lsp-javascript-typescript
  :ensure t
  :init (require 'lsp-javascript-typescript)
  (add-hook 'js-mode-hook #'lsp-mode)
  (add-hook 'typescript-mode-hook #'lsp-mode) ; for typescript support
  (add-hook 'js3-mode-hook #'lsp-mode) ; for js3-mode support
  (add-hook 'rjsx-mode #'lsp-mode) ; for rjsx-mode support
  )
```

**Comment by stardiviner** [comment]
After a simple Edebug on `company-lsp`, error occurs on `(lsp--capability "completionProvider")`.

**Comment by stardiviner** [comment]
Thanks. Seems my config is deprecated for a long time.

**Comment by pavilion** [comment]
I am having the same issue with spacemacs. How can I fix it?

**Comment by yyoncho** [comment]
@pavilion which LSP server do you use? Can you paste your configuration?

**Comment by pavilion** [comment]
Hi @yyoncho 
This is my
`~/.emacs.d/layers/+tools/lsp/`
https://gist.github.com/pavilion/ed0b024054fea3c73a501b9e51d28a49

**Comment by pavilion** [comment]
Maybe you are working for [this?](https://gist.github.com/pavilion/bcc3728fae82d7bec4fafddc172c89e8)

**Comment by yyoncho** [comment]
Yes, which language server do you use? Do you call `lsp-{language}-enable`?

**Comment by pavilion** [comment]
Sorry, I actually attached you the wrong gitst. Should be [this one.](https://gist.github.com/pavilion/b39e36d3271cf824f658fd115003fd5d)

**Comment by pavilion** [comment]
And this is the issue I submitted for spacemacs
https://github.com/syl20bnr/spacemacs/issues/11015

**Comment by pavilion** [comment]
I still have not found the fix... did you have any luck? @yyoncho

**Comment by yyoncho** [comment]
The exception is usually caused by the failure in the LSP server(usually server misconfiguration). Can you check the content of the err buffer?

**Comment by pavilion** [comment]
@yyoncho 
I basically get this
`Package iswitchb is obsolete!
evil-forward-char: End of line [4 times]
Company: An error occurred in auto-begin
Company: backend company-lsp error "Wrong type argument: lsp--workspace, nil" with args (prefix)
`

**Comment by yyoncho** [comment]
There should be `*{language} stderr*` buffer. 
1. Check whether the language server you are trying to run is started.
2. Try to manually configure the LSP instead of using the layer - as I mentioned few times in this thread, probably the LSP server has died. The instructions are located here https://github.com/emacs-lsp/lsp-javascript . You have to find out why the LSP server is not starting.

**Comment by Compro-Prasad** [comment]
There is a PR related to this in spacemacs which works fine right out of the box. I have merged it with the [latest develop](https://github.com/syl20bnr/spacemacs/pull/10795#issuecomment-406164391).

**Comment by tomterl** [comment]
I get this error in php-mode buffers, using felixbecker/php-language-server, as of today (updating to the melpa version 20181211.1641); typescript/javascript works fine. The language server is up and running.  I'm not using spacemacs. Emacs is 26.1. I removed the old configuration stuff; ui-peek and sideline work, hover does not.   Did I miss something converting the configuration?

After the configuration-changes, I have left

```
  (require 'lsp)
  (require 'lsp-clients)
  (require 'lsp-ui)
  (setq lsp-prefer-flymake nil)
  (add-hook 'prog-mode-hook 'lsp)

  (flycheck-define-generic-checker 'lsp-php-ui
    "A syntax checker using the Language Server Protocol (RLS)
    provided by lsp-mode.
    See https://github.com/emacs-lsp/lsp-mode."
    :start #'lsp-ui-sideline--flycheck
    :modes '(php-mode) ; Need a default mode
    :predicate (lambda () lsp-mode)
    :error-explainer (lambda (e) (flycheck-error-message e))
    :next-checkers '((warning . php)))
```

**Comment by tomterl** [comment]
Thanks a lot, that was indeed the case.
