### ISSUE TITLE
Autocompletion popups are not working with lsp-ltex

### ISSUE THREAD

**Issue by swarnendubiswas** [emacs-lsp/lsp-mode#3550]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

I can get autocompletion to work with `txt` files, but not when I enable `lsp`. I believe this error has to do with value of `completion-at-point-functions` set by `lsp`.

### Steps to reproduce

```
(setq straight-build-dir (format "build/%d%s%d"
                                 emacs-major-version
                                 version-separator
                                 emacs-minor-version)
      straight-use-package-by-default t)

(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;; These variables need to best before loading `use-package'.
(setq use-package-hook-name-suffix nil)
(straight-use-package 'use-package)

(use-package vertico
  :hook (after-init-hook . vertico-mode)
  :bind
  (:map vertico-map
   ("C-M-j" . vertico-exit-input)
   ("<tab>" . vertico-insert)))

(use-package corfu
  :hook (after-init-hook . global-corfu-mode)
  :custom
  (corfu-auto t "Enable auto completion")
  (corfu-auto-prefix 3)
  :bind
  (:map corfu-map
        ("[tab]" . corfu-next)
        ("C-n" . corfu-next)
        ("[backtab]" . corfu-previous)
        ("C-p" . corfu-previous)
        ("<escape>" . corfu-quit)))

(use-package cape
  :after corfu
  :demand t
  :commands (cape-history ; Complete from Eshell, Comint or minibuffer history
             cape-file
             cape-keyword ; Complete programming language keyword
             cape-tex ; Complete unicode char from TeX command, e.g. \hbar.
             cape-abbrev ; Complete abbreviation at point
             cape-dict ; Complete word from dictionary at point
             cape-line ; Complete current line from other lines in buffer
             cape-symbol ; Elisp symbol
             cape-ispell ; Complete word at point with Ispell
             ;; Complete with Dabbrev at point
             cape-dabbrev)
  :custom
  (cape-dabbrev-min-length 3)
  :config
  (add-hook 'text-mode-hook
            (lambda ()
              (setq-local completion-at-point-functions
                          (list (cape-super-capf #'cape-dabbrev #'cape-file #'cape-history #'cape-ispell #'cape-dict))))))

(use-package lsp-mode
  :custom
  (lsp-completion-provider :none)
  (lsp-lens-enable nil)
  (lsp-log-io nil))

(use-package lsp-ltex
  :hook
  (text-mode-hook . (lambda ()
                      (require 'lsp-ltex)
                      (lsp-deferred)))
  :init
  (setq lsp-ltex-check-frequency "save"
        lsp-ltex-java-path "/usr/lib/jvm/java-11-openjdk-amd64"
        lsp-ltex-version "15.2.0"))
```

### Expected behavior

I expect auto-completion popups to appear with Corfu, but they do not show up. Company popups work.

The value of `completion-at-point-functions` is

```
Its value is (lsp-completion-at-point)
Local in buffer testing.txt; global value is 
(tags-completion-at-point-function)

```
I tried the following with `text-mode-hook`, but it did not resolve the problem.

```
(setq-local completion-at-point-functions
                           (list (cape-capf-properties #'lsp-completion-at-point :exclusive 'no)))
```

I have posted about the issue at other places.
 
[Autocompletion popups are not working with lsp-ltex](https://github.com/minad/corfu/issues/174#)
[Corfu autocompletion popups are not working with lsp-ltex](https://emacs.stackexchange.com/questions/71899/corfu-autocompletion-popups-are-not-working-with-lsp-ltex)

Although the issue with `lsp-ltex`, I think it is also related to `lsp-completions.el`.

I believe the following pull request is related: https://github.com/emacs-lsp/lsp-mode/pull/3525

### Which Language Server did you use?

lsp-ltex

### OS

Linux

**Comment by swarnendubiswas** [comment]
I have solved this problem with the following snippet to disable `lsp-mode` integration with `capf`.

```
(add-hook 'text-mode-hook (lambda ()
                        (setq-local lsp-completion-enable nil)))
```

Corfu and cape autocompletion now work with `text-mode` and `lsp-ltex`.

**Comment by swarnendubiswas** [comment]
I am reopening this since the integration of `lsp-completion-at-point` with `cape-*` options do not seem to work. So, although I can get text completions with `cape-dabbrev` and `cape-ispell`, I do not get LSP completions from the Texlab v4.1.0 server. How can I configure either LSP or Corfu or both to get seamless completions?

**Comment by jcs090218** [comment]
I don't think we are officially supporting cape?

**Comment by justinbarclay** [comment]
Is it possible to set `:exclusive 'no` in `lsp-completion-at-point` this would allow other completion systems to come into play when lsp fails to find a completion.
As per: https://www.gnu.org/software/emacs/manual/html_node/elisp/Completion-in-Buffers.html

**Comment by yyoncho** [comment]
> @jcs090218 Is it possible to set `:exclusive 'no` in [lsp-completion-at-point](https://github.com/emacs-lsp/lsp-mode/blob/48cf201006c9eb6077e0f4caec04a660307d6df2/lsp-completion.el#L515) this would allow other completion systems to come into play when lsp fails to find a completion. As per: https://www.gnu.org/software/emacs/manual/html_node/elisp/Completion-in-Buffers.html

I would say yes, but @kiennq is the expert here. I guess you can test and report if it works.

**Comment by kiennq** [comment]
Adding `exclusive` flag is fine to me. I haven't noticed this flag until now though :)
