### ISSUE TITLE
lsp-rust-library-directories is not documented under rust-analyzer

### ISSUE THREAD

**Issue by fynzhak** [emacs-lsp/lsp-mode#3564]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

The option, lsp-rust-library-directories, seems to be used by both rust-analyzer and rls, but it is only documented in the rls section.
This caused me a bit of confusion, since I didn't think to check the rls doc for relevant options.

### Steps to reproduce

Look at the doc for rust-analyzer and notice that lsp-rust-library-directories is not listed as a configuration variable.
It is, however, in the code of the TRAMP example.

### Expected behavior

lsp-rust-library-directories should be listed as a configuration option in rust-analyzer :)

### Which Language Server did you use?

rust-analyzer

### OS

Windows

**Comment by brotzeit** [comment]
True.
