### ISSUE TITLE
lsp-mode writes buffer to file, triggering unwanted behavior, when applying changes with go-mode

### ISSUE THREAD

**Issue by hut8** [emacs-lsp/lsp-mode#3570]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

I am using `lsp-mode` with the Go language server (`gopls`). I am running the latest versions of everything as of today (`go`,`gopls`,`lsp-mode` and all its parts). Overall, the functionality is phenomenal and thanks so much for an amazing package. There is one part that is extremely annoying. In my config, I have:

```
  (defun lsp-go-install-save-hooks ()
    (add-hook 'before-save-hook #'lsp-format-buffer t t)
    (add-hook 'before-save-hook #'lsp-organize-imports t t))
  (add-hook 'go-mode-hook #'lsp-go-install-save-hooks)
  (add-hook 'go-mode-hook #'lsp-deferred)
```

Part of `lsp-format-buffer` in the `go` language is that this:

```
fmt.Printf("Hello %v",)
```

gets turned into this (it removes the trailing comma):

```
fmt.Printf("Hello %v")
```
Note that when I type `fmt.Printf(` it turns into `fmt.Printf()` automatically. For reasons I do not yet understand (I am not an emacs lisp expert and I have been debugging this for a while), when I type `fmt.Printf("Hello %v",`, at the exact time I hit the `,` the `lsp-format-buffer` function is called and the minibuffer tells me that the file has been written. That causes the trailing `,` to be removed. So now every time I invoke a function, I have to hit `,` twice every time I want a `,`. I also do not understand why it doesn't run the second time I hit `,`.

So to temporarily fix this, I just removed the `(add-hook 'before-save-hook #'lsp-format-buffer t t)`, but I really want that, and now I have to run that function manually whenever I actually want to save the buffer.

This seems to be a go-specific issue.

### Steps to reproduce

You can clone my .emacs.d thusly:

```
git clone git@github.com/hut8/prelude .emacs.d
```

Install go (this will only work for linux-amd64, for something else, see https://go.dev/doc/install) and gopls:
```
cd
wget https://go.dev/dl/go1.18.3.linux-amd64.tar.gz
sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.18.3.linux-amd64.tar.gz
rm go1.18.3.linux-amd64.tar.gz
/usr/local/go/bin/go install golang.org/x/tools/gopls@latest
```

You should also add `/usr/local/go/bin` to your `PATH`

Then start emacs. Open a buffer `~/bug/main.go`. `go-mode` and `lsp-mode` will load. That will start `gopls` in the background. Then copy this into the buffer:

```
package main

import (
	"fmt"
)

func main() {
	fmt.Printf("test %v")
}
``` 
Put your point right after `"test %v"` before the `)`. Now type `,`. It disappears. Type it again and it will probably stay there. Right after the disappearing happens, this comes into the minibuffer:

```
Saving file /home/xxx/bug/main.go...
LSP :: Applying 1 edits to `main.go' ...
Applying 1 edits to `main.go' ...done
```

### Expected behavior

When I type `fmt.Printf("Hello %v",` I would like the `,` to stay right where I put it. I would also like to not have my buffer written if possible.

### Which Language Server did you use?

`lsp-go`

### OS

Linux

### Error callstack

```emacs-lisp
No error.
```

### Anything else?

The traces are too big to put here.
Please see https://gist.github.com/hut8/9d014245767c00a95ad9fb46841365d0

**Comment by hut8** [comment]
This is the smallest trace I could make. In this trace, the point was exactly where I wanted to insert the `,` when it starts. Then I typed `,` and it disappeared: https://gist.github.com/hut8/858103e6780a1ab6fc147b81eae963f0

**Comment by hut8** [comment]
Here's an mp4. I didn't hit backspace at all.

https://user-images.githubusercontent.com/363720/173163034-e2ce2c32-b159-46cd-a86f-eaccb7093404.mp4

**Comment by yyoncho** [comment]
I don't see any issue in lsp-mode. If the server is removing the `,` and you are somehow calling lsp-format-buffer then this is the expected behavior.

**Comment by hut8** [comment]
@yyoncho Thanks so much for the reply. Based on the message in the "messages" buffer, it's not the server that's writing the buffer, it's emacs. This behavior doesn't happen in other editors like vscode that use the same server. It's also confusing to me why it deletes the comma the first time but not the second. So my first question to you in debugging this is: why does lsp-mode save the buffer when I hit `,`? That doesn't seem necessary or wanted. If I can figure that out and disable it, then I can fix the issue without disabling formatting of the buffer.

**Comment by yyoncho** [comment]
> why does lsp-mode save the buffer when I hit ,? That doesn't seem necessary or wanted. 

It doesn't. It is something in your config that does this. And I am a bit skeptical that it happens when you are using lsp-start-plain.el(although you have checked it).

`M-x debug-on-entry RET lsp-format-buffer`  will tell you which piece is calling the format buffer function. I guess it is aggressive-ident-mode. In case it is - then close the turn it off and close the bug. But in any case, I don't see how the issue is in lsp-mode.

**Comment by hut8** [comment]
You're right, when I used `lsp-start-plain` I noticed that it does not have `go-mode` and does not start the gopls LSP server at all. I forgot to include that fact; I apologize. Your comment helped me to solve the problem though, it turns out that it was `super-save` that was causing the problem. Thank you very much for your time and I apologize for failing to debug in a sensible way.
