### ISSUE TITLE
Code action in modeline, wrong icon

### ISSUE THREAD

**Issue by deb75** [emacs-lsp/lsp-mode#3571]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Since latest `lsp` upgrade, the icon for code actions in modeline is no more displayed (see snapshot)
![plot](https://user-images.githubusercontent.com/19540378/173205000-0d73fef7-cb46-462f-915e-81a9f9171d06.png)

### Steps to reproduce

No particular step, just open a java file in a java project.

### Expected behavior

The code action icon used to be a light bulb

### Which Language Server did you use?

eclipse jdt server language

### OS

Windows

### Anything else?

emacs 29 from master, compiled a few days ago. Nothing changed in my `lsp` configuration, no similar bug either.

However, it does work with `lsp-start-plain`

**Comment by yyoncho** [comment]
that happens if the font that you are using does not have the symbol (in this case 💡). To avoid the issue use different font or change lsp-modeline-code-action-fallback-icon

**Comment by deb75** [comment]
Hi,

Thanks for your answer.

I do not understand what happened, I did not change my font (Bitstream Vera Sans Mono).

If I open `lsp-modeline.el`, the `lsp-modelin-code-action-fallback-icon` is well displayed, a light-bulb.

The trouble seems to come from function :
```elisp
(defun lsp-modeline--code-actions-icon (face)
  "Build the icon for modeline code actions using FACE."
  (if (require 'all-the-icons nil t)
      (all-the-icons-octicon "light-bulb"
                             :face face
                             :v-adjust -0.0575)
    (propertize lsp-modeline-code-action-fallback-icon 'face face)))
```

If I try in `lisp-interaction-mode` : 
```elisp
﻿(all-the-icons-octicon "light-bulb")
#("" 0 1 (face (:family "github-octicons" :height 1.2) font-lock-face (:family "github-octicons" :height 1.2) display (raise -0.24) rear-nonsticky t))
``` 
This is what I see in the modeline.

However, if I just try `M-x all-the-icons-insert-octicon light-bulb RET`, then I do set a light-bulb icon in the buffer.

If I see the icon in the buffer, it means it exists in the font, right ? so why do I have an error with previous function ?

Regards
