### ISSUE TITLE
Possibility to use locally installed server (e.g. for Typescript)

### ISSUE THREAD

**Issue by guillaumebrunerie** [emacs-lsp/lsp-mode#3576]
When working with Typescript, you can install Typescript either globally or locally (in the `node_modules` folder of the project). It looks like `lsp-mode` always uses the global version instead of the local one, which means that it can potentially report more/less/different errors than running `npx tsc` in the root of the project, for instance if the local version of Typescript has been updated but not the global one. Ideally `lsp-mode` should detect if there is a local version of the server and if so use that one.
I have no idea if it is something that is already possible or not at all.

**Comment by aisamu** [comment]
I suspect what you describe already happens.
Here's the command `lsp-mode` invoked when I ran it inside a project with `typescript` installed:
```
/<doom-path>/.local/etc/lsp/npm/typescript-language-server/bin/typescript-language-server
  --tsserver-path /<project-path>/node_modules/typescript/lib/tsserver.js 
  --stdio
```

**Comment by acanimal** [comment]
For anybody works the `ts-js` server installation that lsp-mode does automatically?  If so, which version of `npm` have you installed?

I have npm v8. In my case `typescript-language-server` and `typescript` packages are installed in the emacs cache successfully with lsp is unable to start the tsserver launching an error

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'typescript' imported from ...
```

The cli optoin `--tsserver-path` is deprecated and I think for npm 8 requires other steps to config the path were the tsserver is installed.

**Comment by yyoncho** [comment]
@acanimal see https://github.com/emacs-lsp/lsp-mode/issues/3851 and the workaround in it.

**Comment by aisamu** [comment]
I've edited the issue to explicitly call it out as a workaround https://github.com/emacs-lsp/lsp-mode/issues/3851#workaround

**Comment by MagicRB** [comment]
I'm not sure if this is related, but it looks like there is no way for LSP mode to just use `typescript-language-server` and `tssserver` from PATH and not bother nor check the global npm registry... 

This function override seems to fix it:
```lisp
  (cl-defun lsp--npm-dependency-path (&key package path &allow-other-keys)
    "Return npm dependency PATH for PACKAGE."
    (let ((path (executable-find
                 (f-join lsp-server-install-dir "npm" package
                         (cond ((eq system-type 'windows-nt) "")
                               (t "bin"))
                         path))))
      (unless (and path (f-exists? path))
        nil)
      path))
```

**Comment by tzohpilotl** [comment]
I'm also interested in this because ts-ls is throwing errors where VSCode is not for the same repo, types seem wrong. I suspect this is due to the typescript-language-server and typescript modules ts-ls uses are outside the project (they are lsp-mode globals)

**Comment by michaelsbradleyjr** [comment]
The way I get it to work is to launch VS Code from a terminal where the working directory is the top-level of my project, and that project has `typescript` and `typescript-language-server` in `devDependencies`, and I've already run `npm i`.

I launch it with the help of a shell function that's defined in my `.bashrc`:
```bash
node_modules_bin_vscode () 
{ 
    PATH="$(pwd)/node_modules/.bin:${PATH}" code
}
```

**Comment by yyoncho** [comment]
Fixed with https://github.com/emacs-lsp/lsp-mode/pull/3909
