### ISSUE TITLE
Make workspace startup asynchronous

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#360]
Also, it would be good to wait for initialized notification before sending any other requests.

**Comment by joaotavora** [comment]
> Also, it would be good to wait for initialized notification before sending any other requests.

Then I think you mean "synchronous", right?

**Comment by yyoncho** [comment]
No, I mean that it must be async since it could take a lot of time and it should not block Emacs UI thread.

**Comment by joaotavora** [comment]
Oh, I see. Well there's something eglot does differently for simplicity (actually it used to be async). What "workspaces" take a long time to create in your experience?

**Comment by joaotavora** [comment]
> JDT server initialization could take several minutes until "initialized" notification has been received.

It's probably a good idea then, assuming you mean the *response* to the `:initialize` request. The `:initialized` notification is something the [client sends to server](https://microsoft.github.io/language-server-protocol/specification#initialized).

**Comment by yyoncho** [comment]
Yes, I will update the description.

**Comment by vibhavp** [comment]
> Also, it would be good to wait for initialized notification before sending any other requests.

Good idea, but LSP has the error code `-32002` (`ServerNotInitialized`) for requests and notifications that are sent before initialization is complete. A way to queue essential notifications and requests (dynamic registration, changes, etc) could help.

**Comment by yyoncho** [comment]
@vibhavp I added this comment based on the comment in `eglot`, I am not 100% sure whether it is relevant. I just want to point out that the problems that have impact on the lsp-mode users are:

1. emacs blocks during initialize call.
2. If initialize call fails due to timeout the server lsp-mode breaks.

> Defers signature requests like textDocument/hover until server is ready. Also sends textDocument/didChange for groups of edits, not one per each tiny change.

@joaotavora can you provide a bit more info what do you mean by this statement?

**Comment by yyoncho** [comment]
@joaotavora 
> This is easy right?


yes, the question was only for the first part :) , I have already filed a bug to track the issue - #362 
> Take RLS, for example. When you complete and immediately send a hover
and a highlight request, the server didn't have time to finish the build
yet and can't answer yet. It answers back empty.

Is this by lsp spec? It looks more like a bug in RLS. I am not using rust but you could handle this behaviour in LSP mode by registering a handler for the `window/progress` notification and then refreshing onHover, symbol highlight, etc.

**Comment by joaotavora** [comment]
> Is this by lsp spec? It looks more like a bug in RLS. I am not using rust but you could handle this behaviour in LSP mode by registering a handler for the window/progress notification and then refreshing onHover, symbol highlight, etc.

Yeah, it's a limitation, more than a bug. See https://github.com/rust-lang-nursery/rls/issues/725#issuecomment-387597387. But it's nice for the client to not send requests that it knows cannot be honored. You could register this handler, but you'd be sending too many hovers more than 1, possibly. And registering this handler is rust-specific code that grows for each such request. Eglot just has a generic mechanism for customizing when the server is ready. I wouldn't make a big deal out of this, but It bothered me when I started using rls.
