### ISSUE TITLE
Elixir and `plist`s

### ISSUE THREAD

**Issue by fosskers** [emacs-lsp/lsp-mode#3602]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Fresh off the heels of https://github.com/emacs-lsp/lsp-mode/pull/3599 , I'm getting the following when using `elixir-ls`:
```
Error processing message (wrong-type-argument hash-table-p (:codeLensProvider (:resolveProvider nil) :completionProvider (:triggerCharacters ["." "@" "&" "%" "^" ":" "!"]) :definitionProvider t :documentFormattingProvider t :documentOnTypeFormattingProvider (:firstTriggerCharacter "
") :documentSymbolProvider t :executeCommandProvider (:commands ["spec:Zakk_0DydbexoqG42EVL40k0UI7EZFON" "expandMacro:Zakk_0DydbexoqG42EVL40k0UI7EZFON" "manipulatePipes:Zakk_0DydbexoqG42EVL40k0UI7EZFON"]) :foldingRangeProvider t :hoverProvider t :implementationProvider t :macroExpansion t :referencesProvider t :signatureHelpProvider (:triggerCharacters ["(" ","]) :textDocumentSync (:change 2 :openClose t :save (:includeText t)) :workspace (:workspaceFolders (:changeNotifications nil :supported nil)) :workspaceSymbolProvider t)).
```
I see this in `*Messages*` as I newly open an `.ex` buffer. Actual errors/warnings from the LSP are strangely delayed (I use `on-save`) or don't appear at all.

### Steps to reproduce

1. `(setenv "LSP_USE_PLISTS" "1")`
2. Delete `lsp`-related git clones from my `straight` directory / build caches.
3. Repull / rebuild.
4. Open Emacs, and then an Elixir project.
5. See the error in `*Messages*`.

### Expected behavior

I should see code errors as usual in my buffer.

### Which Language Server did you use?

`elixir-ls`.

### OS

Linux

### Error callstack

```emacs-lisp
*Nothing out of the ordinary here.*
```

### Anything else?

When I deactivate the plist usage and rebuild, the error disappears.

**Comment by yyoncho** [comment]
This indivates that lsp-mode is not properly compiled, most likely because LSP_USE_PLISTS is set in emacs

**Comment by fosskers** [comment]
Having it just set in emacs (as above) was enough for the related Rust fix, but let me try it again for Elixir with the external var set too.

**Comment by fosskers** [comment]
Unfortunately the error persists. The command I used was:
```
env LSP_USE_PLISTS=true doom sync
```
(in `fish` shell)

**Comment by yyoncho** [comment]
can you do M-x toggle-debug-on-error and paste the callstack?

**Comment by fosskers** [comment]
Unfortunately there was no callstack. The only thing printed in the message shown above in the original report.

**Comment by yyoncho** [comment]
Can you test this: https://github.com/yyoncho/lsp-mode/commit/d6db6931f2f74fafb25ce9053fffb35dd1323446

**Comment by fosskers** [comment]
That fixes it! Thank you!
