### ISSUE TITLE
[Feature]Code lenses support

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#361]
I noticed that the method `lsp--update-code-lenses` is not used in `lsp-mode` and `lsp-ui` it seems like this functionality is missing. Can someone comment?

**Comment by yyoncho** [comment]
@vibhavp

**Comment by vibhavp** [comment]
Yes, code lenses aren't updated in the current code. I don't know how they exactly work, can we update them in `lsp--on-hover`?

**Comment by yyoncho** [comment]
Yes, overlays is a possible solution - I have filed a bug in LSP UI for that. In `lsp-mode` we can create an interactive command which will check whether there are lenses on the current point and then select the lens to resolve via `completing-read`.

**Comment by vibhavp** [comment]
@yyoncho Forgot to inform you about it, but I added some basic support for lens in https://github.com/emacs-lsp/lsp-mode/commit/dc4a166c22780de8d83716b0191554f8f916a2b0

You can create lens buttons by evaluating `(lsp--update-code-lenses #'lsp--update-code-lens-buttons)`, though I'm not sure about where and when to update lenses.

**Comment by yyoncho** [comment]
@vibhavp I tried the code - IMO using buttons does not seem like a good idea, since there should be some context information about the code lens at the point similar to what vscode is doing, see https://camo.githubusercontent.com/348d682e4a4cc1f84e8571a9488c2087ae754c88/68747470733a2f2f692e696d6775722e636f6d2f437846506f50472e706e67 . Can you share your opininion which would be the best place to implement that feature - `lsp-mode` or `lsp-ui`? 
@sebastiencs  @MaskRay

**Comment by yyoncho** [comment]
I will be working on this - I will ccls code as a base.
