### ISSUE TITLE
can I disable diagnostics when lsp start? I do not want to start flymake automatically.

### ISSUE THREAD

**Issue by haoisli9** [emacs-lsp/lsp-mode#3612]
Is your feature related or already mentioned on [the wishlist](https://github.com/emacs-lsp/lsp-mode/discussions/2892)?
Don't find.

Describe your feature here.
I want to disable diagnostics when lsp start, and start diagnostic such as flymake or flycheck manualy. flymake sometings make my emacs slow. so i want to disable flymake when lsp start. but manualy start it when i need.

can i get that options?

thanks.

**Comment by yyoncho** [comment]
Flycheck has flycheck-check-syntax-automatically , I am not sure if flymake has the equivalent.

**Comment by yyoncho** [comment]
> I want lsp do not call flymake or flycheck when lsp-mode start. 

> but manualy start it when i need.

You cannot have both... 

This guide contains information how to turn off each feature: https://emacs-lsp.github.io/lsp-mode/tutorials/how-to-turn-off/
