### ISSUE TITLE
ts-ls: installation fails

### ISSUE THREAD

**Issue by paralin** [emacs-lsp/lsp-mode#3613]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

`pkg-info-package-version`: `20220706.42`

Reproduced with lsp-start-plain.

This was working until I updated everything yesterday, not sure what version I was on before.

### Steps to reproduce

 1. Run `lsp-start-plain`
 2. Open a TypeScript file (.ts or .tsx)
 3. "No servers installed... select a server": select ts-ls
 4. The "Comint" `npm install` script runs and finishes successfully (exits 0)
 5. The TypeScript file still has "Installing following servers: (ts-ls)" in the footer.

### Expected behavior

The Comint command succeeded; so, the ts-ls server should be started correctly.

... or at least, the process should fail somehow and print an error, and not just hang on "Installing following servers"

### Which Language Server did you use?

ts-ls

### OS

Linux

### Error callstack

```emacs-lisp
Command "deno lsp" is not present on the path.
```

**Comment by paralin** [comment]
If I install globally with `npm i -g typescript-language-server typescript` it works.

The issue is that the `npm install` step lsp is running for `ts-ls` installs only "typescript" with `npm i -g typescript` - it should also install `typescript-language-server`.

**Comment by yyoncho** [comment]
It tries to install both. cc @elken

**Comment by elken** [comment]
I just tried on the latest commit and it does indeed install fine. Without any more information there's not much we can look into here.

**Comment by yyoncho** [comment]
@paralin can you click on installing message - this should pop the installation buffer. Can you paste the content of it?

**Comment by paralin** [comment]
@elken You probably already have the language server installed globally with "npm i -g"

If I reset my node installation such that only npm and yarn are installed, and clear the lsp cache directory, and use lsp-start-plain,

![image](https://user-images.githubusercontent.com/534887/177703460-0024ed39-f877-44ac-8312-ad3722930723.png)

As you can see, it calls `install typescript` (not typescript-language-server) and then gets stuck on Installing following servers.

If I click on Installing following servers it says "No installation buffers."

**Comment by elken** [comment]
> You probably already have the language server installed globally with "npm i -g" or possibly something is not working correctly in lsp-package-ensure.

Nope, this was a system I had never installed or used node packages on :)

**Comment by paralin** [comment]
Ran into this issue again on my laptop today (normally working on my desktop).

It's not earth shattering because I can `npm i -g typescript-language-server` but I could see some other people getting hung up on this.

**Comment by Lawqup** [comment]
I'm having the same exact issue, except I do have `typescript-language-server` installed via `npm i -g` but lsp doesn't seem to recognize it.

**Comment by Lawqup** [comment]
Ok, found a slightly scuffed solution. I managed to solve the problem by going into `.emacs.d/.cache/lsp/npm`, making a directory called `typescript-language-server` (I had to guess the name) and using `npm -g --prefix ./typescript-language-server i typescript-language-server` to install `ts-ls` into that directory.

**Comment by arionrefat** [comment]
Can confirm this happens both on my personal config and on Doom config.

**Comment by kiennq** [comment]
Found the problem, the attached PR should resolve this issue.
