### ISSUE TITLE
lsp--symbol-kind unbound

### ISSUE THREAD

**Issue by gerd-moellmann** [emacs-lsp/lsp-mode#3627]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

helm-lsp uses lsp--symbol-kind as a variable which leads to errors that that variable is unbound, which is true.

### Steps to reproduce

M-x  helm-lsp-global-workspace-symbol RET

### Expected behavior

No error?

### Which Language Server did you use?

clangd

### OS

MacOS

### Anything else?

The error is caused by the defalias in lsp-mode.el for that symbol.  Defalias defines a function alias. What was meant is defvaralias.  

When I add a defvaralias to my .emacs, everything works as expected.

**Comment by yyoncho** [comment]
https://github.com/emacs-lsp/helm-lsp/search?q=lsp--symbol-kind&type=code I don't see such variable...

**Comment by gerd-moellmann** [comment]
Maybe helm-lsp is no longer using it.  The Melpa version has it.

Line 5855 in lsp-mode.el: (defalias 'lsp--symbol-kind 'lsp-symbol-kinds) 

should be wrong anyway.

**Comment by brotzeit** [comment]
In weird situations like this sometimes `rm -rf .emacs.d` helps.

**Comment by brotzeit** [comment]
Feel free to reopen if you still have this issue.
