### ISSUE TITLE
lsp lua-language-server version is not latest

### ISSUE THREAD

**Issue by basaran** [emacs-lsp/lsp-mode#3635]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

version 1.x is hardcoded:

[url (lsp-vscode-extension-url "sumneko" "lua" "1.17.4")](https://github.com/emacs-lsp/lsp-mode/blob/b2dc84128fc6b2cd0460569bae6d0451856d2e0b/clients/lsp-lua.el#L543)

Latest version from vscode marketplace 3.5.0.

### Steps to reproduce

NA

### Expected behavior

It should download the latest version

### Which Language Server did you use?

lua-language-server

### OS

Linux

### Anything else?

I downloaded the latest version manually from vscode marketplace, extracted and updated `lsp-clients-lua-language-server-bin` to the new folder, and I got format buffer enabled. I can try to send a PR if allowed.

**Comment by Mateus-Carmo31** [comment]
I think it could be a good idea to have it download the language server binary from sumneko's [github repo](https://github.com/sumneko/lua-language-server) itself. That would avoid having needless vscode-specific client plugin files in the lsp's folder. It could even check for the latest version through Github's api. I could try to get it done separately and send a PR, as well.

**Comment by basaran** [comment]
yes, that would be nice to get the `@latest` but sumneko's release page is providing different compressed files for different platforms and stuff. I don't know if the decompression routine in the lisp file can handle the tar.gz seamlessly. So  I just pulled the links from the marketplace and updated the pcases.

Marketplace download links were also different per platform. However, the roblox language server didn't have that (single zip with all platforms). But I fixed that too while I am at it. The lisp I used can most definitely be better. I tested both lang servers and they do seem fine. Please test and let me know.
