### ISSUE TITLE
Cannot rename virtual functions

### ISSUE THREAD

**Issue by YVEF** [emacs-lsp/lsp-mode#3646]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Hi. I cannot to rename virtual function in a c++ code, e.g.

I'm receiving the error message:
Cannot rename symbol: symbol is not a supported kind (e.g. namespace, macro)

It works well with non-virtual functions.

### Steps to reproduce

Define class and try to rename the "func" function.
```
class a {
public:
    virtual void func();
}
```

### Expected behavior

The target function was renamed

### Which Language Server did you use?

clangd

### OS

Linux

**Comment by yyoncho** [comment]
lsp mode just calls the server and applies the changes for that particular renaming. In this case, the server is returning error because it doesn't have support for that. There is nothing to fix on lsp-mode side. You may report it on clangd side but most likely they are already tracking this issue.
