### ISSUE TITLE
Flycheck doesn't update the buffer after typing, but only on save

### ISSUE THREAD

**Issue by bertulli** [emacs-lsp/lsp-mode#3650]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Hi all,
I don't know if this better belongs here, to rust-analyzer's team or to flycheck's. I put it also here in case it has something to do with lsp-mode too, but if that's not the case please feel free to correct me.

It seems that when editing a source file, the flycheck faces and errors are updated only when I save my file, and not on other events (like typing or switching buffer). I have noticed this with Rust (`rust-analyzer`), and from time to time with Java (`jdtls`, I still haven't managed to get a reproducible bug)
For instance, I have a simple Rust file:
![Screenshot from 2022-08-01 12-28-15](https://user-images.githubusercontent.com/10565357/182130042-41af15e7-db5d-4420-bd7f-384d4d309d40.png)
After changing the name of the function, I got this:
![Screenshot from 2022-08-01 12-28-45](https://user-images.githubusercontent.com/10565357/182130136-d09fe946-78eb-42e1-85c6-fb6a3bd98b34.png)

Notice that **the errors and warning reported in the dedicated buffer (`C-c ! l`) reflect this**.

### Steps to reproduce

- Open a Rust file (in a cargo binary package). In the screenshots I attached, I used
``` rust
use std::fmt;

use arrayvec::ArrayVec;

#[derive(Debug)]
struct Cell {
    num: i8,
    extracted: bool,
}

impl Cell {
    fn new(num: i8) -> Cell {
	Cell { num: num, extracted: false }
    }

    fn random_text_is_extracted(&self) -> bool {
	self.extracted
    }

    fn mark(&mut self) {
	self.extracted = false;
    }
}

impl PartialEq<i8> for Cell {
    fn eq(&self, other: &i8)-> bool {
	self.num == *other
    }
}

#[derive(Debug)]
struct Board {
    nums: ArrayVec<ArrayVec<Cell, 5>, 5>
    //nums: arr! [[Cell{num: 0, extracted: false}; 5]; 5],
}

impl Board {
    fn mark(&mut self, num: i8) {
	'checking:
	for i in 0..self.nums.len() {
	    for j in 0..self.nums.len() {
		if self.nums[i][j] == num {
		    self.nums[i][j].mark();
		    break 'checking;
		}
	    }
	}
    }

    fn from_string(input: &str) -> Board {
	let mut board = Board {
	    nums: ArrayVec::new()
	};
	
	for (row, ix) in input.split("\n").zip(0..) {
	    // dbg!(row);
	    let mut current_row: ArrayVec<Cell, 5> = ArrayVec::new();
	    for (num, iy) in row.trim().split_whitespace().zip(0..) {
		// dbg!(num);
		let number_to_be_stored: i8 = num.trim().parse().unwrap();
		current_row.insert(iy, Cell::new(number_to_be_stored));
	    }
	    board.nums.insert(ix, current_row);
	}
	board
    }
}

impl fmt::Display for Board {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        // Write strictly the first element into the supplied output
        // stream: `f`. Returns `fmt::Result` which indicates whether the
        // operation succeeded or failed. Note that `write!` uses syntax which
        // is very similar to `println!`.

	for row in self.nums.iter() {
	    write!(f, "|")?;
	    for cell in row {
		if cell.extracted {
		    write!(f, "X ")?;
		} else if cell.num < 10 {
		    write!(f, " {} ", cell.num)?;
		} else {
		    write!(f, "{} ", cell.num)?;
		}
	    }
	    write!(f, "|\n");	    
	}
	Ok(())
    }
}

fn main() {
    let input_string = "22 13 17 11 0\n 8  2 23  4 24\n21  9 14 16  7\n 6 10  3 18  5\n 1 12 20 15 19";
    
    let first = Board::from_string(input_string);
    println!("{first}");
}
```
- `M-x lsp-start-plain`
- Go on an error managed by flycheck
- Modify the text
- See how the error is not updated

### Expected behavior

I'd expect this buffer:
![image](https://user-images.githubusercontent.com/10565357/182130210-f56d2bee-d56c-432b-93fa-6bf9d18feac7.png)
Which is, by the way, what I got when I save the buffer (`C-x C-s`)

### Which Language Server did you use?

I use `rust-analyzer` with `rustic`

### OS

Linux

### Anything else?

My Emacs version is `GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6) of 2022-07-31` (get from [AUR](https://aur.archlinux.org/packages/emacs-git)), though I noticed this behavior also in Emacs 28 from [the normal repository](https://archlinux.org/packages/extra/x86_64/emacs/).

**Comment by yyoncho** [comment]
I think that is how it is rust analyzer working atm. It requires the file to be saved in order to run the check command.

**Comment by bertulli** [comment]
Thanks, but shouldn't the error checking be performed by flycheck?

**Comment by yyoncho** [comment]
No. lsp-mode reports to flycheck the errors sent by the server. It is up to the server to decide when to send them. On client side we just do some optimizations to speed up handling of the diagnostics.

**Comment by bertulli** [comment]
Great, thanks. I'll forward the bug to the rust-analyzer team and close this issue. Kind and fast as always, great! 🫶
And thanks for your work!

**Comment by yyoncho** [comment]
I don't think this is a but from their perspective. It is a limitation they are working on from the beginning of the project.

**Comment by bertulli** [comment]
It is indeed, [apparently](https://users.rust-lang.org/t/rust-analyzer-doesnt-check-the-buffer-on-typing-but-only-on-save-how-to-change-that/79221) the point is that rust-analyzer has no way to check the buffer if it's not saved on disk. Experimental support is on the way, but need to be enabled with the variable `lsp-rust-analyzer-diagnostics-enable-experimental`. However, it seems that **such variable is unused**. Do you know hot to enable the RA experimental features (I can open a new issue if we're going too much OT)
