### ISSUE TITLE
In `make-lsp-client`, is it `:initialization-options` or `:initializationOptions`?

### ISSUE THREAD

**Issue by c-alpha** [emacs-lsp/lsp-mode#3657]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

The documentation could be more concise.

### Steps to reproduce

```elisp
(describe-function 'make-lsp-client)
```

### Expected behavior

The documentation should unambiguously state the names of the properties.

### Which Language Server did you use?

https://metacpan.org/pod/PLS

### OS

MacOS

**Comment by kiennq** [comment]
It's `:initialization-options`. This one is Emacs `cl-defstruct` object.
