### ISSUE TITLE
xref-find-definitions ignores provided symbol name

### ISSUE THREAD

**Issue by kahatlen** [emacs-lsp/lsp-mode#366]
If I invoke xref-find-definitions with a prefix argument, by entering `C-u M-.`, and type a symbol name at the prompt, it ignores the provided symbol name and instead finds the definitions of the symbol at point.

I'm seeing this with C++ projects using lsp-mode+lsp-ui+emacs-cquery. Haven't tried other languages, so I don't know if the issue is specific to this combination.

**Comment by yyoncho** [comment]
`xref-find-definitions` backend call does not support passing symbols but only the thing at point so providing definition name is not possible. The only fix that could be implemented in `lsp-mode` is throwing an error.
Here it is specification:
https://microsoft.github.io/language-server-protocol/specification#textDocument_references

**Comment by kahatlen** [comment]
Eglot (a competing LSP client for Emacs) supports entering symbol names in xref-find-definitions, so it can't be impossible to implement. I suppose a naive implementation could send a workspace/symbol request to the server and filter out the non-exact matches.

**Comment by joaotavora** [comment]
@kahatlen but in eglot it's partly a hack. It lets you complete symbol names in the current document. But you can't enter an arbitrary symbol name somewhere in your workspace and ask the server for that, so @yyoncho is mostly right

**Comment by kahatlen** [comment]
For now I'm working around the problem by redefining xref-backend-definitions like this in my ~/.emacs:
```
(cl-defmethod xref-backend-definitions ((_backend (eql xref-lsp)) identifier)
  (let* ((maybeparams (get-text-property 0 'def-params identifier))
         (defs (if maybeparams
                   (lsp--send-request (lsp--make-request
                                       "textDocument/definition"
                                       maybeparams))
                 (cl-remove-if-not
                  (lambda (x)
                    (member identifier (split-string (gethash "name" x)
                                                     "[[:space:]:()]"
                                                     t)))
                  (lsp--send-request (lsp--make-request
                                      "workspace/symbol"
                                      (list :query identifier)))))))
    (if maybeparams
        (lsp--locations-to-xref-items (if (listp defs) defs (list defs)))
      (mapcar 'lsp--symbol-information-to-xref defs))))
```
It seems to do mostly what I want, for C++ projects at least. Apart from missing completion of symbols in other documents, as @joaotavora mentioned. But it finds the symbols in the other documents too, if I just type them right.

**Comment by MaskRay** [comment]
I am unclear what xref.el was designed for and why `xref-find-{definitions,references,apropos}` were chosen for `textDocument/definition` `textDocument/references` `workspace/symbol`

For  `textDocument/definition` `textDocument/references`, the language server protocol specification uses position information as the parameter, not the identifier. If the `xref.el` has such implication, they just don't fit well together. I am in favor of repurposing `xref-find-definitions` `xref-find-references` to use the position information and not the string.

**Comment by yyoncho** [comment]
I agree with @MaskRay - we have 2 options - implement partially working hack over `textDocument/definition` or deny the PR.

**Comment by yyoncho** [comment]
Closing based on @MaskRay's comment.

**Comment by sullivan-** [comment]
I have to say, I think you are making the wrong choice here. This breaks behavior of Xref:

> M-. (xref-find-definitions) shows the definitions of the identifier at point. With a prefix argument, or if there's no identifier at point, it prompts for the identifier.

https://www.gnu.org/software/emacs/manual/html_node/emacs/Looking-Up-Identifiers.html#Looking-Up-Identifiers

I think it would be better to not override `xref-find-definitions`, and provide a separate function for this LSP incompatible behavior instead.
