### ISSUE TITLE
Not enable lsp for files in subdirectories

### ISSUE THREAD

**Issue by YVEF** [emacs-lsp/lsp-mode#3660]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Lsp mode enables only for root directory files, but not for files in subdirectories.

### Steps to reproduce

Create directory (root)
Create CMakeLists.txt
Create file ".projectile"
Create file "any.cpp"
Create subdirectory
Go to subdirectory
Create file "any2.cpp"
(Also here I tried to add this command "projectile-add-known-project" for root)
Open file "any.cpp"
Lsp ask for configuring; (Import current root)
Open file subdirectory/any2.cpp
Receive this error: "file mode specification error: (cl-no-applicable-method project-root nil)"

### Expected behavior

Lsp works for whole hierarchy

### Which Language Server did you use?

ccls/clangd

### OS

Linux

**Comment by YVEF** [comment]
Looks like I found the reason. https://github.com/alamaison/emacs-cmake-project
It is autoloading of cmake-project-mode.
```
(defun maybe-cmake-project-mode ()
  (if (or (file-exists-p "CMakeLists.txt")
          (file-exists-p (expand-file-name "CMakeLists.txt" (car (project-roots (project-current))))))
      (cmake-project-mode)))

(add-hook 'c-mode-hook 'maybe-cmake-project-mode)
(add-hook 'c++-mode-hook 'maybe-cmake-project-mode)
```
I'm not Lisp expert, but looks like it overrides project-root with only top level dir, that contains CMakeLists.txt

**Comment by yyoncho** [comment]
install projectile or latest version of project.el package. The issue is caused by the fact that you are using incompatible version of project.el package.

**Comment by YVEF** [comment]
@yyoncho thanks for the replay. Projectile has already been installed. Moreover, initialization of git vc in the root does not affect anything, but It is advised in many articles. Only removing the above part from init.el fixed the problem.

**Comment by yyoncho** [comment]
I missed the previous comment. Then I don't see how the issue is related to lsp-mode.
