### ISSUE TITLE
lsp-go removes comma

### ISSUE THREAD

**Issue by rdeusser** [emacs-lsp/lsp-mode#3663]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [x] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

If I call a function or a method or a builtin e.g.
```go
foo = append(foo, "bar")
```

When typing that comma lsp-mode logs
```
LSP :: Applying 1 edits to `foo.go' ...
Applying 1 edits to `foo.go' ...done
```

and removes that comma. If I type it again, it doesn't apply any text edits. I've read some other issues here (namely this one https://github.com/emacs-lsp/lsp-mode/issues/2446) and setting `lsp-enable-indentation` and `lsp-enable-on-type-formatting` to `nil` do absolutely nothing. Why is lsp-go removing that comma, but then just lets me do it again without applying edits? Most importantly, how can I get it to stop?

### Steps to reproduce

1. Open a go file
2. Run `M-x lsp`
3. Try to do something like this: 
```go
foo = append(foo, "bar")
```
and pay attention to the comma as you type it.

### Expected behavior

I'd expect it _not_ to remove the comma.

### Which Language Server did you use?

gopls

### OS

MacOS

### Error callstack

```emacs-lisp
2022/08/07 15:17:06 unable to compute positions for type errors: no parsed file for  in foo/internal/bar
	package="foo/internal/bar"

2022/08/07 15:17:06 DocumentSymbols failed: invalid pos: 708169464 not in [708167202, 708169463]
	URI=file:///Users/rdeusser/src/foo/internal/bar/bar.go

2022/08/07 15:17:06 unable to compute positions for type errors: no parsed file for  in foo/internal/bar
	package="foo/internal/bar"

2022/08/07 15:17:06 DocumentSymbols failed: invalid pos: 708173996 not in [708171729, 708173995]
	URI=file:///Users/rdeusser/src/foo/internal/bar/bar.go

2022/08/07 15:17:06 imports fixes: AllImportsFixes: /Users/rdeusser/src/foo/internal/bar/bar.go:34:79: missing ',' before newline in argument list (and 69 more errors)
	file="/Users/rdeusser/src/foo/internal/bar/bar.go"

2022/08/07 15:17:06 DocumentSymbols failed: invalid pos: 708173996 not in [708171729, 708173995]
	URI=file:///Users/rdeusser/src/foo/internal/bar/bar.go
```

### Anything else?

This doesn't happen if I just use go-mode without lsp-mode.

**Comment by yyoncho** [comment]
Most likely turn off aggressive indent mode.

**Comment by rdeusser** [comment]
Hey @yyoncho thanks for the response! I removed aggressive indent mode from my config and restarted Emacs and still see the same behavior. Those errors I posted above are gone from the `*lsp-log*` buffer though. Is there a way to set a delay on lsp text edits? If it was delayed even for a second that would be enough. Here's the trace information from the lsp log right after I attempted to insert a comma and it removed it:
```
[Trace - 09:18:28 AM] Sending request 'textDocument/codeLens - (212)'.
    Params: {
        "textDocument": {
            "uri": "file:///Users/rdeusser/src/foo/internal/bar/bar.go"
        }
    }


[Trace - 09:18:28 AM] Received response 'textDocument/codeAction - (211)' in 13ms.
    Result: null


[Trace - 09:18:28 AM] Sending request 'textDocument/formatting - (213)'.
    Params: {
        "textDocument": {
            "uri": "file:///Users/rdeusser/src/foo/internal/bar/bar.go"
        },
        "options": {
            "tabSize": 4,
            "insertSpaces": false
        }
    }

[Trace - 09:18:28 AM] Received response 'textDocument/codeLens - (212)' in 12ms.
    Result: null


[Trace - 09:18:28 AM] Received response 'textDocument/formatting - (213)' in 23ms.
    Result: []


[Trace - 09:18:28 AM] Sending notification 'workspace/didChangeWatchedFiles'.
    Params: {
        "changes": [
            {
            "type": 2,
            "uri": "file:///Users/rdeusser/src/foo/internal/bar/bar.go"
        }
        ]
    }
```

**Comment by yyoncho** [comment]
Are you sure you are getting the bug with M-x lsp-start-plain as you have marked in the bug template?

There was a package related to automatic saving, not sure what was its name but I guess you may figure out what in our config is causing the issues by doing `M-x toggle-debug-on-entry RET lsp-format-buffer RET`

**Comment by rdeusser** [comment]
I figured it out. There was a random auto-save-command function defined in my config that would automatically save the buffer when the buffer was switched or the mouse left the buffer. Removing that and restarting Emacs fixed the issue. Thanks for the help!
