### ISSUE TITLE
Graphql LSP doesn't install all dependencies

### ISSUE THREAD

**Issue by Malabarba** [emacs-lsp/lsp-mode#3672]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

When installing graphql lsp, it runs
```bash
/usr/bin/npm -g --prefix ~/.cache/lsp/npm/graphql-language-service-cli install graphql-language-service-cli
```
However, once the server is activated, it complains about a missing module `graphql-language-service`. Installing that directly (in the terminal) fixed the issue.
```bash
/usr/bin/npm -g --prefix ~/.cache/lsp/npm/graphql-language-service-cli install graphql-language-service
```

I'd make a pull request, but I thought it best to report and let the experts do it. :smile: 

### Steps to reproduce

- Open a graphql file
- run `M-x lsp`
- Confirm the default lsp on the prompt

I immediately got that message saying the server exited and suggesting I check the stderr buffer.

### Expected behavior

The mode would turn on without erros

### Which Language Server did you use?

graphql-language-service

### OS

Linux

### Anything else?

Issue is fixed by installing graphql-language-service

**Comment by altschuler** [comment]
To me this seems to be a problem with how the peer dependencies were being installed. This was the faulty output from installing the graphql-lsp server

```
-*- mode: compilation; default-directory: "~/.emacs.d/.cache/lsp/npm/graphql-language-service-cli/lib/node_modules/graphql-language-service-cli/" -*-
Comint started at Fri Aug 26 11:14:12

/home/simon/.nvm/versions/node/v14.19.0/bin/npx --yes npm-install-peers

ERROR: You must supply a command.
... more irrelevant output
```

The culprit is the `--yes` argument, which needs to come last. After I ran this manually in the `~/.emacs.d/.cache/lsp/npm/graphql-language-service-cli/lib/node_modules/graphql-language-service-cli` directory, lsp started up fine.

**Comment by elken** [comment]
> which needs to come last.

Actually, it's a flag that was added after one of node's ever-famous breaking changes that breaks compatibility with older versions of node.

Apparently there's a workaround that I'm looking at, though I would also recommend upgrading from a node version that's EOL in 7 months.

**Comment by elken** [comment]
@altschuler @Malabarba please try the linked PR and see if that resolves the issue :)

**Comment by altschuler** [comment]
> @altschuler @Malabarba please try the linked PR and see if that resolves the issue :)

I've updated node, no problems since then. Thank you very much! :)

**Comment by elken** [comment]
> I've updated node, no problems since then. Thank you very much! :)

Okay, well feel free to reopen this if I've just unfixed it 😄
