### ISSUE TITLE
lsp-execute-code-action for a particular rule for whole buffer or whole project

### ISSUE THREAD

**Issue by oschonrock** [emacs-lsp/lsp-mode#3673]
provide a command and key-binding to execute the current code-action for the entire buffer or the whole project. 

If a code action eg, in c++ "modernize-use-nodiscard", is offered for a particular line, then also offer a command to apply that action (fix) to any other occurrences of the same rule within the same buffer, or even within the whole project. 

manually clang-tidy can do this for c++, from the command line with:

```
clang-tidy --config "{Checks: '-*,modernize-use-nodiscard'}" --fix source1.cpp ...
```

**Comment by yyoncho** [comment]
There is no working way to do it unless we retrieve the actions on each line and call it which is not practical. The proper way to fix the issue is to expose source-level code action from the server side.

**Comment by oschonrock** [comment]
OK, you mean like this:

https://github.com/clangd/clangd/issues/830

**Comment by yyoncho** [comment]
yes

**Comment by yyoncho** [comment]
Seems like we better close that one and let the server expose the functionality.
