### ISSUE TITLE
lsp-volar causing lsp to not work for other languages

### ISSUE THREAD

**Issue by ryanswilson59** [emacs-lsp/lsp-mode#3675]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

On a new(work) machine the second time I ran lsp in an unrelated language (java in this case) lsp did not start complaining about dependencies being void. I tracked the issue down to `lsp-volar--vue-project-p` and re evaluating the function proceeded to fix this issue.

### Steps to reproduce

I assumed this was somehow a fluke, however I just encountered the issue on my personal machine when starting lsp for the second time(since I encountered it on my work machine) again in an unrelated language (rust). The same fix worked. This is not exactly a procedure to reproduce but it confirms the issue is not a fluke (I think).

I am not sure how I would try to reproduce the issue given that re-evaluating the function (which should be idempotent) solves the issue. Is it possible that somehow bad .elc files are being provided? I wouldn't know what to do if this was the case

### Expected behavior

lsp starts without issue. 

### Which Language Server did you use?

This is independent of language server as the bug occurred in the call to `lsp--filter-clients` when invoking `lsp`. However the issue was tracked down to `lsp-volar`

### OS

Linux

**Comment by jadestrong** [comment]
Did your project has a `package.json` file and the `package.json` file has a `vue` dependencies? `lsp-volar` will detect whether it is a **vue** project through the previous two conditions? 
When you encounter this problem, could you try this to do a debug:
```
M-x eval-expression
(lsp-volar--vue-project-p)
```

**Comment by ryanswilson59** [comment]
The issue was present on a machine that I never coded in javascript on. It might have been fixed somewhere else, haven't seen it since I updated lsp semi recently.
