### ISSUE TITLE
[Feature Request] mint-lang support.

### ISSUE THREAD

**Issue by zw963** [emacs-lsp/lsp-mode#3678]
It seem like mint supported by VSCode since 2021.

https://github.com/mint-lang/mint-vscode
https://mint-lang.com/blog/mint-0.12.0

Thank you.

**Comment by yyoncho** [comment]
Adding new language support is straightforward and pretty much does not require elisp skills. Usually, the language integration is performed by someone interested in the language server. Here are the docs https://emacs-lsp.github.io/lsp-mode/page/adding-new-language/ and sample PR https://github.com/emacs-lsp/lsp-mode/pull/3653

**Comment by zw963** [comment]
Hi, @yyoncho , thanks point it out.

I try add a very elementary mint support, it works!

![image](https://user-images.githubusercontent.com/549126/185156698-ee936c0f-8945-48b8-8f24-5488d9e65ba8.png)

I consider this is a good start anyway, thank you.
