### ISSUE TITLE
find reference results are not syntax highlighted

### ISSUE THREAD

**Issue by shwsun** [emacs-lsp/lsp-mode#368]
Hi all,

The spacemacs community is working on new layers for cquery and lsp. One thing I noticed while testing the new feature is that the find reference results are not syntax highlighted.

The new lsp and cquery layer is [here](https://github.com/shwsun/spacemacs/tree/lsp-improve-and-cquery/private/layers). Is there something missing (not configured correctly)? Thank you so much.
![screenshot from 2018-06-01 11-40-57](https://user-images.githubusercontent.com/15823053/40849711-ac40d684-6590-11e8-9b76-2f9f20005622.png)
![screenshot from 2018-06-01 11-40-37](https://user-images.githubusercontent.com/15823053/40849714-ae257590-6590-11e8-8345-e6a1b19f46d3.png)

**Comment by shwsun** [comment]
@yyoncho Both of them. From the example in cquery (see [here](https://github.com/cquery-project/cquery/wiki/Emacs)), it looks like both the reference list (right part in the first screen) and the code for the references (left part) should be syntax highlighted right?

**Comment by yyoncho** [comment]
Sorry, I thought that you are talking about symbol highlight. 

So, for the first screen - there is `lsp-ui-peek-force-fontify` . Second one must be fixed in `lsp-mode` .

**Comment by shwsun** [comment]
@yyoncho thank you so much. You are right and that is part we missed. We can close this issue for now. 

Additionally, will `lsp-ui-peek-force-fontify` incur performance slow down (i.e. should we make a variable to configure or just enable it by default)?

**Comment by yyoncho** [comment]
It will fontify all of the buffers that contain a ref. Not sure what will be the impact, I haven't tested/used that option.

**Comment by shwsun** [comment]
Cool, I will close the issue for now :)

**Comment by sebastiencs** [comment]
@shwsun `lsp-ui-peek-force-fontify` won't make performance issue as long as `lsp-ui-peek-expand-function` keeps its default value.

`lsp-ui-peek-force-fontify`  will fontify all expanded buffers, since the default value of `lsp-ui-peek-expand-function` expands only 1 buffer, it won't cause trouble
