### ISSUE TITLE
Volar Vue 3 script setup does not work

### ISSUE THREAD

**Issue by teegee** [emacs-lsp/lsp-mode#3681]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Whenever the 'script setup' syntax is used in a .vue file, the script section is not assisted by Volar, the way a non-setup script would be. There is no syntax coloring, and editing is nearly impossible because all lines will be placed at column 0. See example below, where I added a newline after the 'const...values;' line.

![emacs-script-setup](https://user-images.githubusercontent.com/449362/185310722-0fa44ca1-0fd5-46e4-9add-744bfb95abc6.png)

Normal vue 3 script (without setup sugar) works fine.

A secondary issue is that lsp-mode or volar completely fails if I open something that is symlinked, hence the '/bulk/home/rob/vue' path in the image..

### Steps to reproduce

I'm using [this](https://github.com/cornflourblue/vue-3-pinia-jwt-authentication-example) as an example, file src/views/LoginView.vue.  (Not my repo)

### Expected behavior

Volar should handle 'script setup' block.

### Which Language Server did you use?

Plain lsp-mode (?). Freshly pulled and rebuild by straight. Language-server (volar-api) freshly reinstalled by lsp-install-server.

### OS

Linux

### Anything else?

I use evil-mode as well, in case that is relevant..

**Comment by yyoncho** [comment]
> There is no syntax coloring,

lsp-mode is not doing the syntax coloring. Apart from that, I don't quite understand the issue.

**Comment by teegee** [comment]
> lsp-mode is not doing the syntax coloring.

Ah ok. Which part of emacs takes care of that (and doesn't, in this case)?

> Apart from that, I don't quite understand the issue

The biggest problem is that automatic indenting of lines doesn't work as usual. Normally, if I press tab at the beginning of a line, some language mode will indent the line to the correct place. When volar is used, the indent is always zero (i.e. moves all the way to the left).

It could be that volar/lsp has nothing to do with this..? If I convert the code to a normal setup function, it looks like below, and everything works again. If I add a line below 'password: ', then it will be automatically indented correctly, etc. Vue 2 files use Vetur, which also works fine.

![emacs-script-setup2](https://user-images.githubusercontent.com/449362/185367805-131d5fe1-9713-4225-8b7a-775a495f97cb.png)

At the moment I don't use 'script setup' because emacs will be barely useable (will always reset lines to the left). If this is not related to lsp/volar, then do you have a suggestion where I should look/ask further?

**Comment by yyoncho** [comment]
> > lsp-mode is not doing the syntax coloring.
> 
> Ah ok. Which part of emacs takes care of that (and doesn't, in this case)?
> 
> > Apart from that, I don't quite understand the issue
> 
> The biggest problem is that automatic indenting of lines doesn't work as usual. Normally, if I press tab at the beginning of a line, some language mode will indent the line to the correct place. When volar is used, the indent is always zero (i.e. moves all the way to the left).

Indentation in that case and coloring is handled by the major mode.

**Comment by teegee** [comment]
Thanks, after some more searching it turns out this is caused by vue-mode not supporting script setup. There's a pull request for it, but there has been no commit since April. I switched to one of the derivative repos (https://github.com/lmissou/vue-mode), and now things work fine.

Just leaving this here in case someone runs into the same issue :)

**Comment by yyoncho** [comment]
ok, marking the issue as closed.
