### ISSUE TITLE
lsp-ansible client checks for yaml-mode, not derived modes

### ISSUE THREAD

**Issue by lukasjuhrich** [emacs-lsp/lsp-mode#3687]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

tl;dr Probably just replace `(eq major-mode 'yaml-mode)` by `(derived-mode-p 'yaml-mode)`.

When activating `lsp` in a `yml` buffer with custom major mode derived from `yaml-mode` (and `ansible` minor mode enabled), `lsp` startup claims no client supports the current major mode:

```
Warning (lsp-mode): Unable to calculate the languageId for buffer ‘site.yml’. Take a look at ‘lsp-language-id-configuration’. The ‘major-mode’ is ansible-mode Disable showing Disable logging
Warning (lsp-mode): Unable to calculate the languageId for buffer ‘site.yml’. Take a look at ‘lsp-language-id-configuration’. The ‘major-mode’ is ansible-mode Disable showing Disable logging
Warning (lsp-mode): Unable to calculate the languageId for buffer ‘site.yml’. Take a look at ‘lsp-language-id-configuration’. The ‘major-mode’ is ansible-mode Disable showing Disable logging
[…]
```

### Steps to reproduce

1. Add a major mode deriving from `yaml-mode` which activates the `ansible` minor mode:
```elisp
(define-derived-mode ansible-mode yaml-mode "Ansible"
  "Major mode which is YAML-mode + ansible minor mode."
  (ansible)
)
```
2. Open a `.yml` buffer, activating `ansible-mode`
3. run `lsp`

### Expected behavior

LSP client should start and connect to the ansible LS

### Which Language Server did you use?

lsp-ansible

### OS

Linux

### Anything else?

This bug is due to a precise `(eq …)` check on the current major mode:

https://github.com/emacs-lsp/lsp-mode/blob/480f804c1c48f7c2e929ffc1c10525ec3fecca2c/clients/lsp-ansible.el#L191-L196

Instead of `(eq major-mode yaml-mode)`, I think one would have to use
```elisp
(derived-mode-p 'yaml-mode)
```
_(But be sceptical, I know virtually nothing about elisp.)_

**Comment by brotzeit** [comment]
I'm not sure this is a bug. It looks like a rare situation. Out of curiosity, why do you need a derived yaml mode for ansible ?

**Comment by brotzeit** [comment]
But it probably don't hurt...

**Comment by brotzeit** [comment]
If you open a pull request I'll merge it.

**Comment by lukasjuhrich** [comment]
> why do you need a derived yaml mode for ansible ?

I want to be able to automatically trigger `ansible-mode` and then `lsp` when opening yaml files in certain projects.
Having to trigger these manually is too much hassle and breaks my workflow.

The solution I ended up with is to use a pattern in the `auto-mode-alist` like this:

```elisp
(add-to-list 'auto-mode-alist
   '("ansible.*/[^.].*\\.ya?ml\\'" . ansible-mode) )
(add-hook 'ansible-mode-hook #'lsp)
```

…however, `auto-mode-alist` can only map to _major modes_, hence the above snippet is preceded by
```elisp
(define-derived-mode ansible-mode yaml-mode "Ansible"
  "Major mode which is YAML-mode + ansible minor mode."
  (ansible)
)
```
I'm not sure how I would configure this otherwise without having to do more complex imperative stuff in a hook; having a designated `ansible` major mode felt like a clean solution to me.

**Comment by yyoncho** [comment]
@lukasjuhrich you can use yaml-mode-hook and trigger ansible there. But still you have to code the rules if you don't want ansible to run for all yaml files.

**Comment by jcook3701** [comment]
This worked for me.  Current behavior is that LSP starts both yamlls and ansible-ls servers.  

```
;; Note: The hook to ansible-mode might need to be removed when working on non-ansible projects
;;       This was needed to enable ls-ansible within lsp.  Otherwise only yamlls server starts.
(use-package yaml
  :hook (yaml-mode . ansible-mode)
  :mode ("\\.yml\\'" . yaml-mode)
  :interpreter ("yaml" . yaml-mode)
  :ensure t)				

;; Ansible minor mode designed to be used for modifying Ansible files.
;; 
;; Requirement
;; * yasnippet
;; *auto-complete
;;
;; Link: https://github.com/k1LoW/emacs-ansible
(use-package ansible
  :after yaml
  :hook (ansible-mode . lsp-deferred)
  :interpreter ("ansible" . ansible-mode)
  :ensure t)

;; Link: https://github.com/emacs-lsp/lsp-mode
(use-package lsp-mode
  :after company
  ;; Optional - enable lsp-mode automatically in scala files
  :commands(lsp lsp-deferred)
  :hook (lsp-mode . lsp-lens-mode)
  :config
  (setq lsp-prefer-flymake nil)
  :ensure t)
```
