### ISSUE TITLE
Support for LSP 3.17 typeHierarchy

### ISSUE THREAD

**Issue by kiennq** [emacs-lsp/lsp-mode#3689]
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_prepareTypeHierarchy

@yyoncho Perhaps this is something that can bring/share implementation with the current Java TypeHierachy.

**Comment by yyoncho** [comment]
There is lsp-treemacs-type-hierarchy

**Comment by ericdallo** [comment]
Yes, treemacs sounds enough for achieving that, WDYT?

**Comment by kiennq** [comment]
Thanks, I didn't notice that. Also, the `typeHierarchy` is not registered currently when initialize done that here https://github.com/emacs-lsp/lsp-mode/pull/3690
