### ISSUE TITLE
Move tee3/lsp-clangd to https://github.com/emacs-lsp/lsp-clangd

### ISSUE THREAD

**Issue by innerout** [emacs-lsp/lsp-mode#369]
I suggested moving the repository without the pull requests,issues etc at the moment, in order for people to be able to see that a client exists for clangd.
When @vibhavp finds sometime he should check the problem @tee3 had here https://github.com/tee3/lsp-clangd/issues/3#issuecomment-394189213 and resolve it so the transfer of the repo gets completed.

**Comment by vibhavp** [comment]
@tee3 Should I remove the lsp-clangd repo on the emacs-lsp organization, and allow a transfer?

**Comment by tee3** [comment]
Yes I think it would be much better that way.  Thanks!

I also think I should change the license to gpl3.  I think I can do that since I am the original author.  Is that your understanding as well?

**Comment by innerout** [comment]
As i can see the transfer of the repo is complete so i am going to close the issue.
