### ISSUE TITLE
HTML/CSS/JSON language server naming issue on Arch Linux

### ISSUE THREAD

**Issue by ynakao** [emacs-lsp/lsp-mode#3705]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Arch Linux provides HTML/CSS/JSON language servers built from vscode source code in [their official repository](https://archlinux.org/packages/community/any/vscode-languageservers/). They name those binaries `vscode-{html,css,json}-languageserver` (without `-` hyphen between `language` and `server`) respectively followed by [the upstream naming convention](https://github.com/microsoft/vscode/blob/d8453c04405c449b47992d1dfa08813210597a41/extensions/html-language-features/server/package.json#L2).

lsp-mode doesn't recognize the language servers installed in my system because it [assumes](https://github.com/emacs-lsp/lsp-mode/blob/828c6c234a3231670ba5649666652e22a9bc4f35/clients/lsp-html.el#L174-L177) that users should install the language servers from [vscode-langservers-extracted](https://github.com/hrsh7th/vscode-langservers-extracted) which provides language servers with different names (with `-` hyphen between `language` and `server` like `vscode-{html,css,json}-language-server`). 

So, lsp-mode prompts to install them in my case, saying `Unable to find installed server supporting this file. The following servers could be installed automatically` in mini buffer.

Is there any way that I can use the HTML/CSS/JSON language servers installed from Arch repository or do I have to install them by using `vscode-langservers-extracted` instead?

### Steps to reproduce

1. Install vscode-html-languageserver from Arch Linux repository.

2. Open HTML file.

3. Start lsp-mode with `M-x lsp`.

### Expected behavior

lsp-mode should start with `vscode-html-languageserver`.

### Which Language Server did you use?

`vscode-html-languageserver` from Arch Linux repository

### OS

Linux

### Error callstack

```emacs-lisp
None.
```

### Anything else?

lsp-mode starts properly by renaming `vscode-html-languageserver` to `vscode-html-language-server` in /usr/bin/ directory.

**Comment by yyoncho** [comment]
you may do something like this: 

```
(with-eval-after-load 'lsp-html
  (lsp-dependency 'html-language-server '(:system "<replace-with-html-ls-binary-name>")))
```

Make sure that this binary is on the path that emacs is running with.
