### ISSUE TITLE
compilation error: le-js.el:1:2: Error: Cannot open load file: No such file or directory, indium

### ISSUE THREAD

**Issue by stardiviner** [emacs-lsp/lsp-mode#3717]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

When I update the package lsp-mode, got this error in buffer `*Compilation-Log*`:
```
le-js.el:1:2: Error: Cannot open load file: No such file or directory, indium
```

### Steps to reproduce

Update package from `package-list-packages`.

### Expected behavior

lsp-mode requires indium?

### Which Language Server did you use?

lsp-js

### OS

MacOS

### Error callstack

```emacs-lisp
le-js.el:1:2: Error: Cannot open load file: No such file or directory, indium
```

**Comment by yyoncho** [comment]
I dont see how this is related to lsp-mode. Please test with `M-x lsp-start-plain` . It seems to me that you should report it in indium project.

**Comment by stardiviner** [comment]
I have not install indium, lsp-mode seems require it forcely. Is it optional? or force required?

**Comment by yyoncho** [comment]
https://github.com/search?q=org%3Aemacs-lsp+indium&ty

**Comment by stardiviner** [comment]
I found the reason, the le-js.el is from lispy package. Sorry for distrubution.
