### ISSUE TITLE
Typescript Server throwing a error with comment Type import from typescript

### ISSUE THREAD

**Issue by aadi58002** [emacs-lsp/lsp-mode#3723]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

I have imported the types from a type script file in a project with the following comment
``` js
/**
 * @type {import('vitepress').UserConfig}
 */
```
I do not get any auto completion for the typescript.

![Screenshot_20220914_221028](https://user-images.githubusercontent.com/96418027/190213058-3822f0cf-4cc3-42bd-aa7c-1df7ec1e86eb.png)

### Steps to reproduce

1. run the command lsp-start-plain
2. Import a type interface from a types file for a node_modules ( in mycase it is vitepress)
3. Does not give auto completion based on the types

### Expected behavior

Get the autocompletion for each property inside the markdown object after importing the types file as a comment.

### Which Language Server did you use?

ts-ls , eslint

### OS

Linux

### Anything else?

Warning (lsp-mode): Failed to parse the following chunk:
’’’
Content-Length: 4263

{"jsonrpc":"2.0","id":33,"result":{"items":[{"label":"constructor","kind":5,"sortText":"11\u0000constructor\u0000","commitCharacters":[".",",","("],"data":{"file":"/home/aditya-yadav/Personal/Projects/Vue/Linux-Blog/content/.vitepress/config.ts","line":6,"offset":4,"entryNames":["constructor"]}},{"label":"hasOwnProperty","kind":2,"sortText":"11\u0000hasOwnProperty\u0000","commitCharacters":[".",",","("],"data":{"file":"/home/aditya-yadav/Personal/Projects/Vue/Linux-Blog/content/.vitepress/config.ts","line":6,"offset":4,"entryNames":["hasOwnProperty"]},"insertTextFormat":2},{"label":"hasOwnProperty(v)","kind":2,"sortText":"11\u0000hasOwnProperty\u00001","commitCharacters":[".",",","("],"data":{"file":"/home/aditya-yadav/Personal/Projects/Vue/Linux-Blog/content/.vitepress/config.ts","line":6,"offset":4,"entryNames":[{"name":"hasOwnProperty(v)","source":"ObjectLiteralMethodSnippet/"}]},"insertTextFormat":2,"insertText":"hasOwnProperty(v) {\n    $0\n},"},{"label":"isPrototypeOf","kind":2,"sortText":"11\u0000isPrototypeOf\u0000","commitCharacters":[".",",","("],"data":{"file":"/home/aditya-yadav/Personal/Projects/Vue/Linux-Blog/content/.vitepress/config.ts","line":6,"offset":4,"entryNames":["isPrototypeOf"]},"insertTextFormat":2},{"label":"isPrototypeOf(v)","kind":2,"sortText":"11\u0000isPrototypeOf\u00001","commitCharacters":[".",",","("],"data":{"file":"/home/aditya-yadav/Personal/Projects/Vue/Linux-Blog/content/.vitepress/config.ts","line":6,"offset":4,"entryNames":[{"name":"isPrototypeOf(v)","source":"ObjectLiteralMethodSnippet/"}]},"insertTextFormat":2,"insertText":"isPrototypeOf(v) {\n    $0\n},"},{"label":"propertyIsEnumerable","kind":2,"sortText":"11\u0000propertyIsEnumerable\u0000","commitCharacters":[".",",","("],"data":{"file":"/home/aditya-yadav/Personal/Projects/Vue/Linux-Blog/content/.vitepress/config.ts","line":6,"offset":4,"entryNames":["propertyIsEnumerable"]},"insertTextFormat":2},{"label":"propertyIsEnumerable(v)","kind":2,"sortText":"11\u0000propertyIsEnumerable\u00001","commitCharacters":[".",",","("],"data":{"file":"/home/aditya-yadav/Personal/Projects/Vue/Linux-Blog/content/.vitepress/config.ts","line":6,"offset":4,"entryNames":[{"name":"propertyIsEnumerable(v)","source":"ObjectLiteralMethodSnippet/"}]},"insertTextFormat":2,"insertText":"propertyIsEnumerable(v) {\n    $0\n},"},{"label":"toLocaleString","kind":2,"sortText":"11\u0000toLocaleString\u0000","commitCharacters":[".",",","("],"data":{"file":"/home/aditya-yadav/Personal/Projects/Vue/Linux-Blog/content/.vitepress/config.ts","line":6,"offset":4,"entryNames":["toLocaleString"]},"insertTextFormat":2},{"label":"toLocaleString()","kind":2,"sortText":"11\u0000toLocaleString\u00001","commitCharacters":[".",",","("],"data":{"file":"/home/aditya-yadav/Personal/Projects/Vue/Linux-Blog/content/.vitepress/config.ts","line":6,"offset":4,"entryNames":[{"name":"toLocaleString()","source":"ObjectLiteralMethodSnippet/"}]},"insertTextFormat":2,"insertText":"toLocaleString() {\n    $0\n},"},{"label":"toString","kind":2,"sortText":"11\u0000toString\u0000","commitCharacters":[".",",","("],"data":{"file":"/home/aditya-yadav/Personal/Projects/Vue/Linux-Blog/content/.vitepress/config.ts","line":6,"offset":4,"entryNames":["toString"]},"insertTextFormat":2},{"label":"toString()","kind":2,"sortText":"11\u0000toString\u00001","commitCharacters":[".",",","("],"data":{"file":"/home/aditya-yadav/Personal/Projects/Vue/Linux-Blog/content/.vitepress/config.ts","line":6,"offset":4,"entryNames":[{"name":"toString()","source":"ObjectLiteralMethodSnippet/"}]},"insertTextFormat":2,"insertText":"toString() {\n    $0\n},"},{"label":"valueOf","kind":2,"sortText":"11\u0000valueOf\u0000","commitCharacters":[".",",","("],"data":{"file":"/home/aditya-yadav/Personal/Projects/Vue/Linux-Blog/content/.vitepress/config.ts","line":6,"offset":4,"entryNames":["valueOf"]},"insertTextFormat":2},{"label":"valueOf()","kind":2,"sortText":"11\u0000valueOf\u00001","commitCharacters":[".",",","("],"data":{"file":"/home/aditya-yadav/Personal/Projects/Vue/Linux-Blog/content/.vitepress/config.ts","line":6,"offset":4,"entryNames":[{"name":"valueOf()","source":"ObjectLiteralMethodSnippet/"}]},"insertTextFormat":2,"insertText":"valueOf() {\n    $0\n},"}],"isIncomplete":false}}
’’’
with message (json-parse-error \u0000 is not allowed without JSON_ALLOW_NUL <callback> 1 114 114) Disable showing Disable logging
Warning (lsp-mode): Failed to parse the following chunk:
’’’

**Comment by jadestrong** [comment]
Look at this. It might help： https://github.com/jadestrong/lsp-volar#hacks

**Comment by aadi58002** [comment]
> Look at this. It might help： https://github.com/jadestrong/lsp-volar#hacks

I added the advice.
I did not get the error this time but the auto completion is still not there.
Also the lsp i am using is ts-ls (alongside eslint) . 

![Screenshot_20220915_142047](https://user-images.githubusercontent.com/96418027/190359929-13e915ba-8511-4228-88a5-17994c12eae4.png)
