### ISSUE TITLE
Godot 4 beta uses a new port

### ISSUE THREAD

**Issue by FlySlime** [emacs-lsp/lsp-mode#3730]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

New Godot 4 beta uses a different port for the language server, needs to be updated.

### Steps to reproduce

1. Enable GDScript module
2. Open Godot 4 beta and a project
3. Open a GDScript file and start LSP
4. Error, since we are listening for the wrong port.

### Expected behavior

Expected behavior is that it should connect to Godot, however it doesn't as mentioned above.

### Which Language Server did you use?

Godot's built-in language server.

### OS

Linux

### Anything else?

What I did to fix this for now, is to write the following:

```elisp
(setq lsp-gdscript-port "6005")
```

**Comment by jcs090218** [comment]
Should we change the default to 6008?

**Comment by yyoncho** [comment]
> Should we change the default to `6005`?

sounds good

**Comment by jcs090218** [comment]
Merged #3849. Thanks for the report!
