### ISSUE TITLE
OmniSharp client is missing hoverProvider capability, causing issues with lsp-ui

### ISSUE THREAD

**Issue by theschmocker** [emacs-lsp/lsp-mode#3735]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

`(lsp--capability "hoverProvider")` returns nil when using OmniSharp. `lsp-describe-thing-at-point` correctly displays a symbol's signature/documentation, because it doesn't appear to check for this capability. `lsp-ui-doc-glance`, however, does not work, because it _does_ check for the capability.

### Steps to reproduce

I don't believe this is project-specific. Used omnisharp with a small .NET 6 project

### Expected behavior

The omnisharp client should register the hoverProvider capability and `lsp-ui-doc-glance` should work OOTB

### Which Language Server did you use?

lsp-csharp with omnisharp

### OS

MacOS

### Error callstack

```emacs-lisp
None. `lsp-ui-doc-glance` exits silently
```

### Anything else?

Advising `lsp--capability` such that it always returns true when given "hoverProvider" makes `lsp-ui-doc-glance` work.

I apologize if this repo's not the right place to report this. While the issue manifests when trying to use lsp-ui, I assume that the behavior of lsp-ui is correct in checking for the hover capability. It's possible that this is an issue with how OmniSharp identifies its capabilities. If that's the case, I'd be happy to close this issue and open one over in omnisharp/omnisharp-roslyn. Doesn't seem to be a problem with other language servers (typescript, volar, clojure, etc). For what it's worth, hover capability seems to be resolved when using neovim with [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/51775b12cfbf1b6462c7b13cd020cc09e6767aea/lua/lspconfig/server_configurations/omnisharp.lua), which doesn't seem to do anything special in relation to hoverProvider AFAICT

**Comment by yyoncho** [comment]
is it working with eldoc? If yes, then report the issue in lsp-ui. It should use lsp-feature? to check if the hover functionality is in place.

**Comment by theschmocker** [comment]
It does! Okay, I'll open an issue over in lsp-ui instead and possibly take a crack at a PR if I'm able to this evening. Thanks!

If you've got time, can you clarify how lsp-feature? works? When I eval lsp-feature? with "hoverProvider" or "textDocument/hover" (which I'm assuming is the value that should be checked) in a workspace with omnisharp running, it returns the workspace, I think as expected. But it _also_ returns the workspace when I pass it anything else, like a gibberish string, eg. "asdfkjsldkf". If it returns a result for anything, I'm wondering how it would be reliable to check for features. Is it more of a block-list thing where it will return nil only if a workspace explicity _does not_ support a feature/handle a message?

**Comment by yyoncho** [comment]
> If you've got time, can you clarify how lsp-feature? works?

There are two ways the server can register capability. lsp-feature? checks both. 

> When I eval lsp-feature? with "hoverProvider" or "textDocument/hover"

The later

**Comment by yyoncho** [comment]
> But it _also_ returns the workspace when I pass it anything else, like a gibberish string, eg. "asdfkjsldkf". If it returns a result for anything, I'm wondering how it would be reliable to check for features

If we don't have requirements for a particular method it means it is allowed.

**Comment by theschmocker** [comment]
Great, thank you for the explanation!
