### ISSUE TITLE
lsp-clients-clangd-library-directories might be being ignored

### ISSUE THREAD

**Issue by vitaminace33** [emacs-lsp/lsp-mode#3744]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Emacs variable [`lsp-clients-clangd-library-directories`](https://emacs-lsp.github.io/lsp-mode/page/lsp-clangd/#lsp-clients-clangd-library-directories) is being ignored. Includes must be added with relative path to `/usr/include`, otherwise clangd issues "file not found".

### Steps to reproduce

I will be using Octave's mex library as test scenario since it is my case of interest.

1. Add to `lsp-clients-clangd-library-directories` a folder of you interest.
```elisp
(setq lsp-clients-clangd-library-directories '("/usr" "/usr/include/octave-7.2.0/octave"))
```
2. Open a C-file with an include under the folder you added, for instance, [`mexEvalFunction.c`](https://gist.github.com/vitaminace33/73b9dd44ff6d977406705776d8a2503c).
```C
#include "mex.h"
```
3. clangd issues a "file not found" message.
```C
#include "mex.h"                    'mex.h' file no found [pp_file_not_found]
```
4. Prepend the path of `mex.h` relative to `/usr/include` and clangd won't complain.
```C
#include "octave-7.2.0/octave/mex.h"
```

### Expected behavior

Since `mex.h` is under `/usr`, it should work out of the box, clangd should find `mex.h` and don't complain, even more so when `/usr/include/octave-7.2.0/octave` is added to `lsp-clients-clangd-library-directories`.

### Which Language Server did you use?

C, lsp-clangd

### OS

Linux

### Anything else?

Up to date Spacemacsen on Emacs 28.1 on ArchLinux and Ubuntu 22.04.1 LTS.

**Comment by yyoncho** [comment]
This setting is purely client side and it is used to hint emacs to use an existing instance of clangd instead of opening a new one. The handling of the file not found error you are seeing is in clangd itself and it is controlled by compile_commands, not by lsp-mode.

**Comment by vitaminace33** [comment]
I don't get it.  [`lsp-clients-clangd-library-directories`](https://emacs-lsp.github.io/lsp-mode/page/lsp-clangd/#lsp-clients-clangd-library-directories)  states "List of directories which will be considered to be libraries". If setting this doesn't solve the problem what is the purpose of this variable? How should I set-up lsp-mode not to have this error message?

**Comment by yyoncho** [comment]
When you open a new file lsp-mode normally asks for project root and then starts the server for that file, right? But when you open a file under /usr/lib you rarely want to start a new server for that file. Instead, you want to use the server that is already started for the real project root. 

> How should I set-up lsp-mode not to have this error message?

You have to setup the proper compile_commands.json . Refer to https://clangd.llvm.org/design/compile-commands

**Comment by vitaminace33** [comment]
OK, then I was using `lsp-clients-clangd-library-directories` for another purpose than it designed for. I don't know about compile_commands.json, but I'll have a look into the link you provided.

Thx for your time and help.

**Comment by vitaminace33** [comment]
PS: Perhaps the variable description is misleading, or perhaps it's simply my lack of understanding ;-)

**Comment by yyoncho** [comment]
> PS: Perhaps the variable description is misleading, or perhaps it's simply my lack of understanding ;-)

I can see that. library from lsp-mode point of view conflicts with what library is for cpp.

**Comment by yyoncho** [comment]
FWIW you may take a look at this tutorial: https://emacs-lsp.github.io/lsp-mode/tutorials/CPP-guide/

**Comment by vitaminace33** [comment]
Solved it: I simply had to create a [YAML file to configure clangd](https://clangd.llvm.org/config).
```yaml
# clangd configuration file (refer to https://clangd.llvm.org/config)
# Location: .clangd (per project) or ~/.config/clangd/config.yaml (per user)
CompileFlags:
  Add: -I/usr/include/octave-7.2.0/octave
  Remove:
  Compiler: clang
```
