### ISSUE TITLE
`lsp-install-server` fails to overwrite cached NPM package

### ISSUE THREAD

**Issue by peterbecich** [emacs-lsp/lsp-mode#3754]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

When I attempt to re-install the LSP server for HTML `html-ls`

![2022-10-09_17-23](https://user-images.githubusercontent.com/6315338/194786283-4e4539c1-6686-4fdb-8ce5-7b5ddfe7f097.png)

which uses `vscode-langservers-extracted` (https://www.npmjs.com/package/vscode-langservers-extracted)

this error occurs:

```
130 error ENOTEMPTY: directory not empty, 
rename 
'~/.emacs.d/.cache/lsp/npm/vscode-langservers-extracted/lib/node_modules/vscode-langservers-extracted' 
-> 
'~/.emacs.d/.cache/lsp/npm/vscode-langservers-extracted/lib/node_modules/.vscode-langservers-extracted-MRkiGr9Q'
131 verbose exit -39
```

The error is correct that the directory is non-empty; in `~/.emacs.d/.cache/lsp/npm/vscode-langservers-extracted/lib/node_modules` there is:
```
 vscode-langservers-extracted  .vscode-langservers-extracted-MRkiGr9Q
```  

-------------

This also occurs for the CSS LSP server, which also depends on `vscode-langservers-extracted`.

I don't know if it also occurs for other LSP servers which depend on other NPM packages.

--------------

How can we make `lsp-install-server` overwrite the cached NPM package?

### Steps to reproduce

Install `html-ls` or `css-ls` or any of the other language servers which use https://www.npmjs.com/package/vscode-langservers-extracted

Then attempt to reinstall the same server.

### Expected behavior

Any installed language server should be upgradable

### Which Language Server did you use?

- `html-ls`
- `css-ls`

### OS

Linux

**Comment by ericdallo** [comment]
Maybe we should twak the html-ls install server to clean things before installing?

**Comment by peterbecich** [comment]
Now I cannot reproduce this issue. I've just tried `lsp-install-server html-ls` and `lsp-update-servers` and there is no issue.

I'm fairly sure this error `error ENOTEMPTY: directory not empty` did occur repeatedly, but now I am not able to replicate it reliably.

**Comment by yyoncho** [comment]
> Yes, I agree for both `html-ls` and `css-ls`.
> 
> However, now I cannot reproduce this issue. I've just tried `lsp-install-server html-ls` and `lsp-update-servers` and there is no issue.
> 
> I'm fairly sure this error `error ENOTEMPTY: directory not empty` did occur repeatedly, but now I am not able to replicate it reliably.

can we close the issue then?

**Comment by peterbecich** [comment]
I have seen this again; I think this occurs when multiple language servers using `vscode-langservers-extracted` are installed simultaneously.
