### ISSUE TITLE
[Improvement] make single entry point for lsp-mode

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#376]
Currently, every extension has its own entry point. We could change the code to start the proper LS server based on the major mode via generic method like `lsp-start`.

**Comment by gpittarelli** [comment]
Any thoughts on how best to define the mapping from major mode <-> lsp client definition? Maybe the client's language id.

More generally, I'm already working on something that'll work with the current many-packages ecosystem and basically just aim to automate the "typical case" setup (potentially even automating installing the appropriate lsp-(language) package and downloading the necessary language server executables). I hope to get it usable and published over this weekend. It may need to be yet another separate mode (in order not to pollute the main lsp-mode package with URLs of external, potentially non-GPL binaries).

**Comment by yyoncho** [comment]
I was thinking about extending `lsp-define-*-client` to include major mode(vscode is using file pattern + language id) or a function like `lsp-are-you-interested-in-that-file` but I haven't really researched the topic/options. Eglot is doing that via major-mode in define client function.
Snippet from vscode configuration:
```json
    "languages": [
      {
        "id": "java",
        "extensions": [
          ".class"
        ],
        "configuration": "./language-configuration.json"
      }
    ],
```
Few more things to consider(not sure whether it is related to your effort):

1. Multi root workspaces - I have implemented adhoc multiroot workspace handling in `lsp-java` but it is really ugly - https://github.com/emacs-lsp/lsp-java/blob/master/lsp-java.el#L489 . I am not sure how many of the lsp servers are multiroot ready but at some point it will become a problem.
2. Root detection - IMO LSP mode should never automatically "assume" the root folder but only provide a suggestion due to multiroot support and multi language workspaces. Also, the decision whether to fire up new LSP server must be in the language extension, not in `lsp-mode`(I have ugly workarounds for this in `lsp-java` too).

**Comment by seagle0128** [comment]
Vote as well.
[eglot](https://github.com/joaotavora/eglot) and [flycheck](https://github.com/flycheck/flycheck) do the similar things in the package, so that they are out of box to use.

**Comment by alyssackwan** [comment]
Please consider #393 and #397. This should be project specific.

**Comment by yyoncho** [comment]
See also: https://github.com/emacs-lsp/lsp-mode/issues/424

**Comment by yyoncho** [comment]
Work in progress: https://github.com/yyoncho/lsp-mode/tree/multi-client (check https://github.com/yyoncho/lsp-mode/blob/multi-client/lsp.el)

**Comment by stardiviner** [comment]
I vote for this too!
