### ISSUE TITLE
Customizable Face Priority for lsp-semantic-tokens-mode

### ISSUE THREAD

**Issue by drcxd** [emacs-lsp/lsp-mode#3765]
Is your feature related or already mentioned on [the wishlist](https://github.com/emacs-lsp/lsp-mode/discussions/2892)?

No.

Describe your feature here.

The detail of the problem has been described and discussed with one of the maintainers on discord:

https://discord.com/channels/789885435026604033/1030086309064224768

and he suggested that I open an issue here.

The problem is that with the default setting of lsp-semantic-tokens-mode, different semantic tokens are rendered with the same color. See the picture:

![semantic_token](https://user-images.githubusercontent.com/24535087/196359018-09a66a2f-1fdf-4ee6-876d-74a4064f96fd.png)

It is because the server sends back multiple types for a single token, and lsp-semantic-tokens-mode happens to use one of the corresponding faces to render these tokens, these tokens are of the same color.

My naive assumption is that we can use a customizable priority solution to determine which face should be used when the server returns multiple types for one single token.

Please check the discord threads for more detailed description.

**Comment by yyoncho** [comment]
cc @ericdallo @sebastiansturm @alanz

**Comment by ericdallo** [comment]
@drcxd do you know how vscode handles that? I wonder if just uses the latest token sent

**Comment by sebastiansturm** [comment]
@drcxd that discord link leads me to some "no text channels. you find yourself in a strange place..." message. So, apologies if what I'm asking had already been answered there:
- as per the spec, there's only one token type per token (though there can be multiple modifiers). So does that server in question send multiple tokens with identical ranges, or one token with multiple modifiers?
- if the server thinks that both token types (or, more likely, modifiers?) are relevant enough to send them out to the client, I'd probably want to see both instead of choosing one over the other. Would a configuration that uses orthogonal face properties (say, underline for one modifier, color for the other) serve your needs?

**Comment by alanz** [comment]
@drcxd take a look at what [lsp-rust](https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-rust.el#L939) does.

And it will help to adjust your `lsp-mode` config to log the `initialize`message from your server, by

```elisp
  (setq lsp-log-io t)
  (setq lsp-log-io-allowlist-methods '("initialize"
                                       ;; "textDocument/semanticTokens/full"
                                       ;; "textDocument/semanticTokens/full/delta"
                                       ;; "textDocument/semanticTokens/range"
                                       ))
```
Part of the initialize will list the modifier tags the server will use, you then need to map a modifier face to each of them.

**Comment by sebastiansturm** [comment]
@drcxd to add to what @alanz said: if you'd just like to experiment with a single modified face, changing the default value of `lsp-semantic-token-modifier-faces` before your lsp server is loaded should allow you to test your modification. Haven't tried the snippet below, but I expect this should work:
```
(setq-default lsp-semantic-token-modifier-faces
              (cons '("declaration" . my-custom-declaration-face)
                    (assoc-delete-all "declaration" lsp-semantic-token-modifier-faces #'string-equal)))
```
Also, if the declaration modifier is colliding with one of the other default modifiers, a simpler way would be to just modify the corresponding face `lsp-face-semhl-interface` if you don't mind also changing the look of the token types `"interface"` and `"concept"`
