### ISSUE TITLE
json-rpc-connection error in lsp-mode-20221107.1917

### ISSUE THREAD

**Issue by AriT93** [emacs-lsp/lsp-mode#3804]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

since update today to latest lsp-mode when lsp starts up I get this error and the server does not start:  

`File mode specification error: (void-function json-rpc-connection)
Error running timer: (void-function json-rpc-connection)`

lsp-log

`Command "steep langserver --log-level warn" is not present on the path.
Command "stree lsp" is present on the path.
Command "typeprof --lsp --stdio" is not present on the path.
Command "srb typecheck --lsp --disable-watchman" is not present on the path.
Command "solargraph stdio" is present on the path.
Command "steep langserver --log-level warn" is not present on the path.
Command "stree lsp" is present on the path.
Command "typeprof --lsp --stdio" is not present on the path.
Command "srb typecheck --lsp --disable-watchman" is not present on the path.
Command "solargraph stdio" is present on the path.
Found the following clients for SNIP: (server-id ruby-syntax-tree-ls, priority -4), (server-id ruby-ls, priority -1)
The following clients were selected based on priority: (server-id ruby-ls, priority -1)
Command "steep langserver --log-level warn" is not present on the path.
Command "stree lsp" is present on the path.
Command "typeprof --lsp --stdio" is not present on the path.
Command "srb typecheck --lsp --disable-watchman" is not present on the path.
Command "solargraph stdio" is present on the path.
Command "steep langserver --log-level warn" is not present on the path.
Command "stree lsp" is present on the path.
Command "typeprof --lsp --stdio" is not present on the path.
Command "srb typecheck --lsp --disable-watchman" is not present on the path.
Command "solargraph stdio" is present on the path.
Found the following clients for SNIP: (server-id ruby-syntax-tree-ls, priority -4), (server-id ruby-ls, priority -1)
The following clients were selected based on priority: (server-id ruby-ls, priority -1)`

using emacs build from todays master

### Steps to reproduce

load lsp-mode open ruby file for editing

### Expected behavior

lsp starts solargraph and completions are available

### Which Language Server did you use?

solargraph

### OS

MacOS

### Error callstack

```emacs-lisp
n/a
```

### Anything else?

n/a

**Comment by yyoncho** [comment]
I will fix this: can you tell me what happens when you do `M-x find-function RET json-rpc RET`?

**Comment by AriT93** [comment]
didn't get a chance to check that I moved back to melpa-stable and it looks like the fix is out now. but function is found in json-rpc.el

**Comment by yyoncho** [comment]
Ok, we have to choose different names for native json rpc.
