### ISSUE TITLE
lsp-execute-code-action freezes editor until mouse pointer is moved

### ISSUE THREAD

**Issue by smatting** [emacs-lsp/lsp-mode#3806]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

When I run `lsp-execute-code-action` anywhere applicable then my emacs freezes until "Timeout while waiting for response. Method: textDocument/codeAction".

However, if I move my mouse pointer by a tiny bit while emacs is frozen then emacs unfreezes and a minibuffer opens with code action to choose from.

When I run emacs within a terminal I don't have this workaround of moving the mouse.

Versions used:
lsp-mode 20221109.531
lsp-ui 20220924.850
lsp-haskell 20220809.2129

I'm using Doom emacs, but colleagues of mine using Spacemacs are experiencing the same behaviour.

### Steps to reproduce

1. Run `lsp-execute-code-action` with an active Haskell Language Server session. This leads to a frozen emacs.
2. Move mouse by a tiny bit to unfreeze

### Expected behavior

Don't freeze UI after executing code action.

### Which Language Server did you use?

haskell-language-server 1.8.0.0

### OS

Linux

**Comment by smatting** [comment]
Err sorry, I accidentally checked this. I'm not able to get a functional `lsp-start-plain` session running with the project in which the problem arises for me

**Comment by yyoncho** [comment]
Why it doesn't work? (FTR I just added haskell mode so it should be able to start right away)

What kind of frontend do you use for `completing-read`? Ivy, helm, consult? Can you try disabling it?

**Comment by smatting** [comment]
> Why it doesn't work? (FTR I just added haskell mode so it should be able to start right away)
I gave up after seeing errors. I'm going to retry this with better a better error description

> What kind of frontend do you use for completing-read?
Doom was configured to use helm for that bit. I've disabled helm (and ivy) and reinstalled Doom.
The problem still persists! As soon as I move the mouse I immediately get a "Select code action:" prompt at the bottom. If I don't then I get a timeout after a while.

**Comment by yyoncho** [comment]
> Doom was configured to use helm for that bit. I've disabled helm (and ivy) and reinstalled Doom.

And you have the vanilla UI?  And this is using normal plain emacs, not Emacs LSP fork?

**Comment by smatting** [comment]
Yes, I'm using the vanilla UI. emacs 28.2 with native compilation installed via nixos, nothing extra. I guess it must be one of the plugins pulled in by Doom, because `lsp-start-plain` doesn't exhibit the problem. I already tried disabling flags in the ":ui" section of Doom's `init.el` to no avail.

**Comment by yyoncho** [comment]
I mean, when you press key or move the mouse and it pops up, then is the UI the one you see in M-x lsp-start-plain? Also you may consider reporting this in doom channels.

**Comment by smatting** [comment]
Yes, when I've disabled helm the ui is the same ias in `lsp-start-plain`: a prompt line on the bottom.

**Comment by yyoncho** [comment]
Can you give me sample doom config? @ericdallo can you try to reproduce the issue as well in your doom config?

**Comment by smatting** [comment]
I've already included a link to my doom config above

**Comment by ericdallo** [comment]
I don't have that at all with [my doom config](https://github.com/ericdallo/dotfiles/tree/master/.doom.d)

**Comment by dschrempf** [comment]
I do have the same problem; I am also using Doom.

**Comment by michaelpj** [comment]
I've also noticed similar things, also with Doom.

**Comment by michaelpj** [comment]
I found the source of my issue: I had `lsp-log-io` set and it was slowing things down a lot. So ignore me.

**Comment by dschrempf** [comment]
Well, this is not the case here. Does nobody else have this problem? If so, this must be some werid interaction of specific packages. It is pretty annoying to always have to wait and move the mouse...

**Comment by ericdallo** [comment]
maybe debug it with `toggle-debug-on-quit`, you just need to press `C-g` when the freeze happens to get the stacktrace where emacs was at that time

**Comment by smatting** [comment]
I tried this. Unfortunately `C-g` has the same outcome as moving the mouse, so I don't get a stack trace but rather a selection of code actions to choose from. Tried this with UI and terminal. On the upside: Now I have workaround that doesn't involve the mouse :smile:

**Comment by smatting** [comment]
I think I was able to interrupt via `kill -SIGUSR2` while it was hanging. This is the stacktrace
```
* #f(compiled-function () #<bytecode 0x1100e29ab3c63aff>)()
  lsp-request("textDocument/codeAction" (:textDocument (:uri "file:///home/stefan/.....") :range (:start (:line 23 :character 7) :end (:line 23 :character 7)) :context (:diagnostics [#<hash-table equal 6/6 0x1ffeccf>])))
  lsp-code-actions-at-point()
  byte-code("\300\301 !C\207" [lsp--select-action lsp-code-actions-at-point] 2)
  command-execute(lsp-execute-code-action)
  recursive-edit()
  debug(lambda)
* clear-minibuffer-message()
```

If I select `<bytecode 0x1100e29ab3c63aff>` it expands to this
```
byte code:
  args: nil
0       constant  (nil)
1       car-safe  
2       not       
3       goto-if-nil-else-pop 1
6       constant  lsp-cancel-request-by-token
7       constant  :sync-request
8       call      1
9:1     return    
```

**Comment by smatting** [comment]
Searching for `lsp-cancel-request-by-token` lead me to this, which might be a duplicate of this issue:
https://github.com/emacs-lsp/lsp-mode/issues/3790

**Comment by yyoncho** [comment]
can you redo this after doing M-x eval-buffer in lsp-mode.el? (To avoid the byte-compilation).

**Comment by smatting** [comment]
```

Debugger entered--beginning evaluation of function call form:
* (if done\? nil (lsp-cancel-request-by-token :sync-request))
  (unwind-protect (progn (lsp-request-async method params #'(lambda (res) (setq resp-result (or res :finished)) (throw 'lsp-done '_)) :error-handler #'(lambda (err) (setq resp-error err) (throw 'lsp-done '_)) :no-merge no-merge :mode 'detached :cancel-token :sync-request) (while (not (or resp-error resp-result)) (catch 'lsp-done (accept-process-output nil (if expected-time (- expected-time send-time) 1))) (setq send-time (time-to-seconds (current-time))) (if (and expected-time (< expected-time send-time)) (progn (error "Timeout while waiting for response.  Method: %s" method)))) (setq done\? t) (cond ((eq resp-result :finished) nil) (resp-result resp-result) ((lsp-json-error\? resp-error) (error (lsp:json-error-message resp-error))) ((lsp-json-error\? (cl-first resp-error)) (error (lsp:json-error-message (cl-first resp-error)))))) (if done\? nil (lsp-cancel-request-by-token :sync-request)))
  (let* ((send-time (time-to-seconds (current-time))) (expected-time (and lsp-response-timeout (+ send-time lsp-response-timeout))) resp-result resp-error done\?) (unwind-protect (progn (lsp-request-async method params #'(lambda (res) (setq resp-result (or res :finished)) (throw 'lsp-done '_)) :error-handler #'(lambda (err) (setq resp-error err) (throw 'lsp-done '_)) :no-merge no-merge :mode 'detached :cancel-token :sync-request) (while (not (or resp-error resp-result)) (catch 'lsp-done (accept-process-output nil (if expected-time (- expected-time send-time) 1))) (setq send-time (time-to-seconds (current-time))) (if (and expected-time (< expected-time send-time)) (progn (error "Timeout while waiting for response.  Method: %s" method)))) (setq done\? t) (cond ((eq resp-result :finished) nil) (resp-result resp-result) ((lsp-json-error\? resp-error) (error (lsp:json-error-message resp-error))) ((lsp-json-error\? (cl-first resp-error)) (error (lsp:json-error-message (cl-first resp-error)))))) (if done\? nil (lsp-cancel-request-by-token :sync-request))))
  (if no-wait (lsp-notify method params) (let* ((send-time (time-to-seconds (current-time))) (expected-time (and lsp-response-timeout (+ send-time lsp-response-timeout))) resp-result resp-error done\?) (unwind-protect (progn (lsp-request-async method params #'(lambda (res) (setq resp-result ...) (throw ... ...)) :error-handler #'(lambda (err) (setq resp-error err) (throw ... ...)) :no-merge no-merge :mode 'detached :cancel-token :sync-request) (while (not (or resp-error resp-result)) (catch 'lsp-done (accept-process-output nil (if expected-time ... 1))) (setq send-time (time-to-seconds (current-time))) (if (and expected-time (< expected-time send-time)) (progn (error "Timeout while waiting for response.  Method: %s" method)))) (setq done\? t) (cond ((eq resp-result :finished) nil) (resp-result resp-result) ((lsp-json-error\? resp-error) (error (lsp:json-error-message resp-error))) ((lsp-json-error\? (cl-first resp-error)) (error (lsp:json-error-message ...))))) (if done\? nil (lsp-cancel-request-by-token :sync-request)))))
  (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:no-wait :no-merge :allow-other-keys)) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ... --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:no-wait :no-merge..." (car --cl-keys--)))))) (if no-wait (lsp-notify method params) (let* ((send-time (time-to-seconds (current-time))) (expected-time (and lsp-response-timeout (+ send-time lsp-response-timeout))) resp-result resp-error done\?) (unwind-protect (progn (lsp-request-async method params #'(lambda ... ... ...) :error-handler #'(lambda ... ... ...) :no-merge no-merge :mode 'detached :cancel-token :sync-request) (while (not (or resp-error resp-result)) (catch 'lsp-done (accept-process-output nil ...)) (setq send-time (time-to-seconds ...)) (if (and expected-time ...) (progn ...))) (setq done\? t) (cond ((eq resp-result :finished) nil) (resp-result resp-result) ((lsp-json-error\? resp-error) (error ...)) ((lsp-json-error\? ...) (error ...)))) (if done\? nil (lsp-cancel-request-by-token :sync-request))))))
  (let* ((no-wait (car (cdr (plist-member --cl-rest-- ':no-wait)))) (no-merge (car (cdr (plist-member --cl-rest-- ':no-merge))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '...) (setq --cl-keys-- (cdr ...))) ((car (cdr ...)) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:no-wait :no-merge..." (car --cl-keys--)))))) (if no-wait (lsp-notify method params) (let* ((send-time (time-to-seconds (current-time))) (expected-time (and lsp-response-timeout (+ send-time lsp-response-timeout))) resp-result resp-error done\?) (unwind-protect (progn (lsp-request-async method params #'... :error-handler #'... :no-merge no-merge :mode 'detached :cancel-token :sync-request) (while (not ...) (catch ... ...) (setq send-time ...) (if ... ...)) (setq done\? t) (cond (... nil) (resp-result resp-result) (... ...) (... ...))) (if done\? nil (lsp-cancel-request-by-token :sync-request)))))))
  lsp-request("textDocument/codeAction" (:textDocument (:uri "file:///home/stefan/....") :range (:start (:line 28 :character 11) :end (:line 28 :character 11)) :context (:diagnostics [#<hash-table equal 4/4 0xe013fb>])))
  lsp-code-actions-at-point()
  (lsp--select-action (lsp-code-actions-at-point))
  (list (lsp--select-action (lsp-code-actions-at-point)))
  command-execute(lsp-execute-code-action)
  recursive-edit()
  debug(lambda)
* #f(compiled-function () #<bytecode 0x1100e296bd8f6e73>)()
  lsp-request("textDocument/codeAction" (:textDocument (:uri "file:///home/stefan/...") :range (:start (:line 28 :character 1) :end (:line 28 :character 1)) :context (:diagnostics [#<hash-table equal 4/4 0xe013fb>])))
  lsp-code-actions-at-point()
  byte-code("\300\301 !C\207" [lsp--select-action lsp-code-actions-at-point] 2)
  command-execute(lsp-execute-code-action)
  recursive-edit()
  debug(lambda)
* substitute-command-keys("Quit")
  redisplay_internal\ \(C\ function\)()
```

(it's quite hard to get in state where quit doesn't behave the same as moving the mouse)

**Comment by smatting** [comment]
I solved this issue by upgrading to latest master via

`packages.el`
```
(package! lsp-mode :pin "bc8889c21813d61587f1310b29ce6c066d2adb859")
```
and `doom upgrade -p`
This is probably a strong an indicator that this is a duplicate of https://github.com/emacs-lsp/lsp-mode/issues/3790

**Comment by dschrempf** [comment]
I can confirm that updaing lsp mode resolves the issue. Thanks a lot for digging into this!
