### ISSUE TITLE
Prefer (float-time) to doing timestamps by hand

### ISSUE THREAD

**Issue by eggert** [emacs-lsp/lsp-mode#3822]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

There's a minor performance issue in lsp-mode: several instances of `(time-to-seconds (current-time))` should just be `(float-time)`.

[Here is a proposed patch.](https://web.cs.ucla.edu/~eggert/lsp-mode/0001-Prefer-float-time-to-doing-it-by-hand.patch)

### Steps to reproduce

Use lsp-mode to generate timestamps internally.

### Expected behavior

Cheaper timestamps.

### Which Language Server did you use?

any

### OS

Linux

**Comment by ericdallo** [comment]
@eggert sounds good to me, would you open a PR with that patch?

**Comment by eggert** [comment]
> @eggert sounds good to me, would you open a PR with that patch?

[PR#3823](https://github.com/emacs-lsp/lsp-mode/pull/3823) opened. It also has a more-important timestamp fix.
