### ISSUE TITLE
#'lsp's initialization can be made faster by caching `lsp-buffer-language`

### ISSUE THREAD

**Issue by daanturo** [emacs-lsp/lsp-mode#3836]
By profiling `M-x lsp`, I noticed that `lsp-buffer-language` was taking a
significant amount of CPU time.

```emacs-lisp
;; helper macro
(defmacro my-profiler-cpu-progn (&rest body)
  `(progn
     (profiler-start 'cpu)
     (unwind-protect
         (benchmark-progn ,@body)
       (profiler-stop)
       (profiler-report))))
```

On my machine, from the total time that `lsp` takes to execute, the profiler
reports that `lsp-buffer-language` is consistently occupying 60%+ CPU time (a
.py file was tested, with `lsp-warn-no-matched-clients` disabled).

`(my-profiler-cpu-progn (lsp))`

Elapsed time: 0.062339s
profiler report: http://ix.io/4hw3

```
31%                   - lsp-buffer-language
 1%                   - lsp-buffer-language
 1%                  - lsp-buffer-language
31%                 - lsp-buffer-language
 1%                 - lsp-buffer-language
```

`lsp` spends 65% of its time calculating the buffer's programming language,
which is quite ridiculous for `lsp-buffer-language`'s relatively simple purpose.

By `lsp-start-plain`, reported at http://ix.io/4hwb : it's even as high as 85%.

While calling it once is fine, repeated call due to (I think) multiple repeated
`lsp--filter-clients` through the number of registered servers bring overall
performance down.

After using a naive buffer-local "cache" for `lsp-buffer-language` (here:
https://github.com/daanturo/lsp-mode/commit/e96f6b8787c9b31489f8549f1cba1fae930a885b),
`lsp`'s initialization time is greatly improved. `lsp-buffer-language` is even
blown out of the profiler report:

Elapsed time: 0.020048s
profiler report: http://ix.io/4hw0

Another less prominent culprit is `lsp-workspace-root` (8% total in the just
above profiler report), as I noticed it because of `lsp-volar--activate-p` even
for irrelevant files: the same method for `lsp-buffer-language` can be applied.

**Comment by ericdallo** [comment]
WDYT @yyoncho looks like a quick win

**Comment by yyoncho** [comment]
I don't see a reason not to do it. 

> lsp-volar--activate-p

That should do first the language check, then check roots or whatever. 

@daanturo can you turn your proposal in PR with changing 

> defvar-local lsp--buffer-language 'uncomputed

to default to nil. Then we can fix `lsp-buffer-language` to be always non-nil by calculating the language by dropping `-mode` from the major mode when language-id-configuration does not match. You can do that fix if you want.

**Comment by daanturo** [comment]
> `lsp-buffer-language` to be always non-nil

I have done that, but should it warrant a breakage announcement? Since someone may probably depend on the said function's nil return value.
