### ISSUE TITLE
debugger support for lsp-mode via DAP

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#385]
For the last few weeks I am working on integration with debug adapter protocol which is used by `VSCode`/`Eclipse Che` for the debug plugins. The current state is Alpha, I hope to have beta quality in 2-3 weeks for the core debug functionallity and then I will start working on the separate UI components like separate ui for editing breakpoints/inspecting values, etc. 

https://github.com/yyoncho/dap-mode

I have added integration with `Java Debug Adapter server` and I will probably add support for one more language and I wonder which of the languages supported by `lsp-mode` have the biggest userbase. Here it is the list of supported debuggers to choose from: https://github.com/Microsoft/vscode-debugadapter-node/wiki/VS-Code-Debug-Protocol-Implementations .

**Comment by vibhavp** [comment]
Looks impressive. Do you think that GUD could potentially support DAP as well? Also, does the DAP specification use any aspects of LSP?

**Comment by yyoncho** [comment]
> Do you think that GUD could potentially support DAP as well? 

Unfortunately, both GUD and RealGUD are coupled with the notion that they will communicate with `gbd` process and without a rewrite to generalize them it will be impossible(or very hard) to fit DAP in. DAP is closer to the other emacs debuggers which use communication with remote process via some kind of RPC protocol like `ensime` but sadly the protocols are too different. I will try to reuse some of the UI components though. As you can see from the screenshot I am trying to make the multi session debugging seamless, which doesn't seem to be the case with GUD/Realgud(correct me if I am wrong, I am not `gud` expert). I hope that at some point DAP will provide IDE like debugging experience and it won't make much of a difference whether you are debugging in `Eclipse` or in `Emacs`. 

> Also, does the DAP specification use any aspects of LSP?

It uses the same wire protocol. Codign against DAP feels like coding against LSP extension. There is a bug to change DAP so it can reuse the same data structures for the common stuff(e. g. Location, completion).

**Comment by yyoncho** [comment]
The `dap-mode` has Java and Python(basic) support.  I have covered most of the features of `Debug Adapter Protocol`, now I am trying to onboard it in `melpa`. I am looking for feedback on implemented features.
