### ISSUE TITLE
javascript: clean install of ts-ls fails to start

### ISSUE THREAD

**Issue by aisamu** [emacs-lsp/lsp-mode#3851]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

(re-posting from Discord per yyoncho's instructions)

While trying to fix an annoyance with `ts-ls`[1], I figured it had been a little while since I updated the supporting dependencies. 
After force-installing  `ts-ls` (i.e. to reinstall), it no longer started:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'typescript' imported from /Users/aisamu/.doom.emacs.d/.local/etc/lsp/npm/typescript-language-server/lib/node_modules/typescript-language-server/lib/ts-protocol.js
```

Both installations were successful (`typescript-language-server` and `typescript`). 
Uninstalling and installing from scratch also didn't work.

Running the lsp-invoked command with some debugging flags revealed that it wouldn't be able to find the package in the places it was looking for.

LSP installed these:

```
/Users/aisamu/.doom.emacs.d/.local/etc/lsp/npm $ tree -L 3
├── typescript
│   ├── bin
│   │   ├── tsc -> ../lib/node_modules/typescript/bin/tsc
│   │   └── tsserver -> ../lib/node_modules/typescript/bin/tsserver
│   └── lib
│       └── node_modules
└── typescript-language-server
    ├── bin
    │   └── typescript-language-server -> ../lib/node_modules/typescript-language-server/lib/cli.js
    └── lib
        └── node_modules
```

`typescript-language-server` doesn't bundle  `typescript` (anymore?), so its `node_modules` doesn't contain a `typescript` package.

### Workaround <a href="#workaround" id="workaround">#</a>

`node_modules` are apparently searched upwards, so my workaround was to add this `node_modules` symlink:
```
/Users/aisamu/.doom.emacs.d/.local/etc/lsp/npm $ tree -L 1
├── node_modules -> typescript/lib/node_modules
├── typescript
└── typescript-language-server
```

Thanks for `lsp-mode`! 
It's such a joy to keep using Emacs 😄!

[^1]: `Error processing message (wrong-type-argument hash-table-p ",")`

### Steps to reproduce

* Open any typescript file/project
* Ask to install/reinstall `ts-ls`.
    * Reinstall because it only started happening with the version fetched today, 2022-12-12.

### Expected behavior

Server starts!

### Which Language Server did you use?

`ts-ls`

### OS

MacOS

### Anything else?

Here's what in `*ts-ls::stderr*`

```
node:internal/errors:478
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'typescript' imported from /Users/aisamu/.doom.emacs.d/.local/etc/lsp/npm/typescript-language-server/lib/node_modules/typescript-language-server/lib/ts-protocol.js
    at new NodeError (node:internal/errors:387:5)
    at packageResolve (node:internal/modules/esm/resolve:852:9)
    at moduleResolve (node:internal/modules/esm/resolve:901:20)
    at defaultResolve (node:internal/modules/esm/resolve:1115:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:837:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Process ts-ls stderr finished
```

**Comment by hotoku** [comment]
I encountered the same situation. Thank @aisamu for work around.

**Comment by acanimal** [comment]
Wich npm version have you installed?

**Comment by khinshankhan** [comment]
+1 workaround works for me too. Thanks!

**Comment by parona-source** [comment]
> typescript-language-server doesn't bundle typescript (anymore?), so its node_modules doesn't contain a typescript package.

Apparently it was never bundled but a change on typescript-language-server end introduced a hard dependency on it but it wasnt added to the dependencies so it doesnt get installed by lsp-mode when it calls npm internally. https://github.com/typescript-language-server/typescript-language-server/issues/658

**Comment by yyoncho** [comment]
@parona-source I am not an expert on the matter - do you think we should do anything on our side or we should wait for the upstream?

**Comment by parona-source** [comment]
@yyoncho https://github.com/typescript-language-server/typescript-language-server/pull/661 it should be solved now

**Comment by yyoncho** [comment]
@parona-source thank you!

**Comment by sethen** [comment]
Can confirm working for me after updating `typescript-language-server`
