### ISSUE TITLE
Completing enum variants in rust-mode fills with parentheses

### ISSUE THREAD

**Issue by ntBre** [emacs-lsp/lsp-mode#3852]
- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Rust enum variants get completed with parentheses inside the variant instead of completing just the variant name. 

I looked through the documentation for lsp-rust-analyzer and rust-analyzer itself but cannot find a way to disable this. I thought setting `lsp-rust-analyzer-completion-add-call-argument-snippets` to `nil` might fix it, but it had no effect. Is there a similar option for enum variants that I overlooked?

![Example of the issue](https://user-images.githubusercontent.com/36778786/207358102-36a06c1f-246b-41b8-b6c1-ffd1ace2a935.gif)

### Steps to reproduce

With an enum like

```rust
enum Enum {
  Variant(usize, usize)
}
```

if I type `Enum::V`, which triggers the completion, company-mode shows me a list with entries like

```rust
&Variant(...) Variant(usize, usize)
```

which looks like what I want, so I accept this completion. However, what actually gets inserted is

```rust
Enum::Variant((), ())
```

and my cursor is left  after the closing parentheses, forcing me to move back into the parentheses, delete everything inside, and then type what I actually want in there.

### Expected behavior

I would much rather the completion stop at `Enum::Variant`, allowing me to type the parentheses and their contents, or at most, for the completion snippet to leave me inside the parentheses.

### Which Language Server did you use?

rust-analyzer

### OS

Linux

**Comment by yyoncho** [comment]
cc @flodiebold @brotzeit

**Comment by flodiebold** [comment]
Hmm although it's worth noting that for me, the cursor gets placed inside the parentheses. Do you have yasnippet enabled?

**Comment by ntBre** [comment]
Apparently I did not have `lsp-enable-snippet` on. That does get my cursor inside the parentheses, but it doesn't overwrite the ()s, so I end up with `Enum::Variant(1, 2, (), ())`. Could that be another issue with my config, or is it the same for you? Thanks for your help on this!

**Comment by flodiebold** [comment]
It does overwrite the ()s for me.

**Comment by ntBre** [comment]
Ah I didn't keep hitting tab to fill the fields. I can overwrite the ()s now, but I'd still prefer to suppress the outer parens entirely as mentioned on the other issue. Thanks again for clarifying.
