### ISSUE TITLE
Emacs becomes slow after you edit same rust file with lsp-rust for long time

### ISSUE THREAD

**Issue by kurnevsky** [emacs-lsp/lsp-mode#3853]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Emacs becomes too slow after some time I write rust code. It's especially noticed when `lsp-ui-sideline-show-hover` is on. So probably lsp-mode collects some state over time that makes emacs sluggish. After I reopen the file it becomes fast again.
https://github.com/kurnevsky/nixfiles/blob/02e6b58748d21821e81e705b25717c2e6b26cabf/modules/init.el#L1170-L1213
cc @brotzeit 

### Steps to reproduce

Turn on `lsp-ui-sideline-show-hover` and write code in a single file for some time.

### Expected behavior

Emacs is fast.

### Which Language Server did you use?

lsp-rust (with rust-analyzer)

### OS

Linux

### Anything else?

Profiler report: https://gist.github.com/kurnevsky/81ebbc149670a5ae77f374f765b90940

**Comment by brotzeit** [comment]
Did you try https://github.com/emacs-lsp/emacs ? Seems to work pretty well with rust-analyzer, at least for me on linux. Great job @yyoncho.

**Comment by brotzeit** [comment]
You're not the first one who mentions this issue. I don't use rust much and didn't even noticed this issue.

> So probably lsp-mode collects some state over time that makes emacs sluggish.

I guess that if this would be the case, it would also affect other languages so there would probably be more open issues.

> Or do you actually suppose that this leak is on rust-analyzer side?

No idea, but I don't see that lsp-mode collects that much more data over time(maybe I'm wrong) ?

**Comment by brotzeit** [comment]
Could also be a rust mode issue, it's also caching some stuff so I wouldn't completely exclude this is a factor. I would be glad if we could as much old code as possible and replace it with lsp and treesitter functionality. Also a lot easier to maintain...

**Comment by yyoncho** [comment]
We had similar leaks in the past caused by captures not completely matching each other.

**Comment by brotzeit** [comment]
> We had similar leaks in the past caused by captures not completely matching each other.

@kurnevsky if you can reproduce it in certain buffers maybe you can try https://github.com/rust-lang/rust-mode/pull/467 or turn off the functionality to see if that's the reason. I'm just hesitant to merge bigger pull requests without completely understanding it. I merged too many regressions in the past and now I'm the only maintainer of rust-mode. Everybody else have left the project or are inactive :(

**Comment by kurnevsky** [comment]
I doubt it has anything to do with rust-mode. Firstly, I use tree sitter (together with rust-mode). And secondly, turning on `lsp-ui-sideline-show-hover` magnifies the problem drastically - it sends much more requests to rust-analyzer in this case.

**Comment by yyoncho** [comment]
@kurnevsky I am unable to repro(sideline enabled, using RA). Can you check the local values of the following hooks: post-command-hook, after-change-functions and kill-buffer-hook? If it leaks can you test if you get the same with M-x lsp-start-plain (I assume you have to enable sideline as well).

**Comment by kurnevsky** [comment]
post-command-hook:
```
(lsp--post-command eldoc-schedule-timer lsp-ui-doc--make-request lsp-ui-sideline jit-lock--antiblink-post-command company-post-command flycheck-perform-deferred-syntax-check flycheck-error-list-update-source flycheck-error-list-highlight-errors flycheck-maybe-display-error-at-point-soon flycheck-hide-error-buffer yas--post-command-handler t flyspell-post-command-hook)
```

after-change-functions:
```
(lsp-on-change diff-hl-edit flycheck-handle-change jit-lock-after-change flyspell-after-change-function t)
```

kill-buffer-hook: https://gist.github.com/kurnevsky/f82ce85cd07e0b7672146af88a820775

**Comment by kurnevsky** [comment]
> I am unable to repro(sideline enabled, using RA).

It takes some time to become slow, ~half an hour of real code editing for me to become noticeable, and probably another half to become really slow.

**Comment by kurnevsky** [comment]
> kill-buffer-hook: https://gist.github.com/kurnevsky/f82ce85cd07e0b7672146af88a820775

Looks like this one is not ok - it contains a lot of same functions. But I don't see it's being added by lsp-mode...

**Comment by kurnevsky** [comment]
I just removed all those hooks from `kill-buffer-hook` and buffer became fast again, so it's definitely the problem.

**Comment by yyoncho** [comment]
It is lsp-mode... Are you with native compilation?

**Comment by yyoncho** [comment]
We have to figure out whether the callbacks are not matching or we are not calling "remove" for some reason.

**Comment by kurnevsky** [comment]
It returned `t`.

**Comment by kurnevsky** [comment]
ok, now I can reproduce it - I just make a completion after each completion I have new function there.

**Comment by kurnevsky** [comment]
And the same happens with `lsp-start-plain`.

**Comment by yyoncho** [comment]
I am able to reproduce it, investigating...

**Comment by kurnevsky** [comment]
To be precise - type dot, then choose completion, then TAB to remove selection from arguments.
