### ISSUE TITLE
Formatting fails silently if the end position in the returned TextEdit is incorrect

### ISSUE THREAD

**Issue by yyadavalli** [emacs-lsp/lsp-mode#386]
When using `lsp-format-buffer` if a language server responds with an end position that is invalid for the file (for example: scala language server returns with end position as (Int.MaxValue, Int.MaxValue)) it fails silently.

This is due to `forward-char` in `lsp--position-to-point`, giving a `N` greater than characters available in the buffer, seems to terminate with message `End of buffer` without progressing further.

Even though the language server is at fault here it may be wise to have some checks on `lsp--position-to-point`, possibly using `point-max`.

**Comment by Compro-Prasad** [comment]
@vibhavp Is this fixed?
