### ISSUE TITLE
File mode specification error: (void-function rust-ts-mode)

### ISSUE THREAD

**Issue by getong** [emacs-lsp/lsp-mode#3882]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

I use the https://github.com/rksm/emacs-rust-config 
error msg is
```
File mode specification error: (void-function rust-ts-mode)
```

### Steps to reproduce

reproduce steps:
```
cd /tmp
cargo new test_issue
emacs -nw -q --load ~/emacs-rust-config/standalone.el /tmp/test_issue/src/main.rs
```

### Expected behavior

The lsp works well, but after updated lsp-mode,  it does not works.

### Which Language Server did you use?

rust

### OS

MacOS

**Comment by brotzeit** [comment]
Probably, my fault. Let me check.

**Comment by brotzeit** [comment]
Should be working again.

**Comment by brotzeit** [comment]
And thanks for the issue ;)
