### ISSUE TITLE
New client for Apache Camel LSP

### ISSUE THREAD

**Issue by apupier** [emacs-lsp/lsp-mode#389]
I'm not sure to ask at the right place, please redirect me if it is the case.

it would be nice to provide the Apache Camel Client.
The server is here https://github.com/camel-tooling/camel-language-server . it is written in Java.

is it possible to have a github repository in this organization? Or I should create it in https://github.com/camel-tooling and just add dependency to this project?

Do you have a simple client launching a java server yet so that I can start from it?

**Comment by yyoncho** [comment]
> Do you have a simple client launching a java server yet so that I can start from it?

You may take a look at https://github.com/emacs-lsp/lsp-java - it is launching java language server.

**Comment by vibhavp** [comment]
IMO, it would be better under the camel-tooling organization, as that is how most orgs maintain their vscode/atom LSP packages.

**Comment by apupier** [comment]
I created https://github.com/camel-tooling/camel-lsp-client-emacs then
