### ISSUE TITLE
Warnings listed as lsp-flycheck-warning-unnecessary

### ISSUE THREAD

**Issue by dpassen** [emacs-lsp/lsp-mode#3894]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Various warnings as reported to Flycheck have the level `lsp-flycheck-warning-unnecessary` instead of `warning`. This breaks code that relies on `(flycheck-has-current-errors-p 'warning)` for example https://github.com/flycheck/flycheck-color-mode-line/blob/575b604cfe21f65fb07c134392c382c163c87739/flycheck-color-mode-line.el#L115

### Steps to reproduce

In a Clojure buffer, with lsp-mode started and connected to a clojure-lsp server, add to the ns `:require` or `:import` clause, something unused.

### Expected behavior

I expect `flycheck-list-errors` to show the message, along with the Level of `warning`.

### Which Language Server did you use?

clojure-lsp

### OS

MacOS

**Comment by ericdallo** [comment]
@yyoncho do you know if Is it possible to change the flycheck level to `warning` but keep using the unnecessary face elsewhere?

**Comment by dpassen** [comment]
@ericdallo Looks like this has been discussed https://github.com/emacs-lsp/lsp-mode/issues/1961
