### ISSUE TITLE
[TOML] Primary catalog in `lsp-toml-schema-catalogs` is old und incomplete

### ISSUE THREAD

**Issue by rassie** [emacs-lsp/lsp-mode#3895]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

The schema JSON at https://taplo.tamasfe.dev/schema_index.json is quite old and missing multiple new TOML formats. For example, the schema for `pyproject.toml` is from 2020 and missing crucial information for Poetry >=1.2 support. Schemastore URL on the other hand includes the correct and up to date schemas. It is probably sensible to just switch both URLs so that more recent one takes priority.

### Steps to reproduce

Compare https://taplo.tamasfe.dev/schemas/pyproject.toml.json and https://json.schemastore.org/pyproject.json, note missing `group` attribute in the former.

### Expected behavior

`lsp-toml` should be using the newest available schemas.

### Which Language Server did you use?

`lsp-toml`

### OS

Linux

**Comment by yyoncho** [comment]
@buzztaiki willing to take a look? Do we need to add the new schema here: https://github.com/yyoncho/lsp-mode/blob/master/clients/lsp-toml.el#L85

**Comment by buzztaiki** [comment]
@yyoncho It appears that taplo has decided to manage all schemas at https://www.schemastore.org/json/.

- https://github.com/tamasfe/taplo/issues/288
- https://github.com/tamasfe/taplo/pull/290

I think it will be fixed by syncing the default values of the configuration with the latest taplo.

**Comment by buzztaiki** [comment]
I've create PR https://github.com/emacs-lsp/lsp-mode/pull/3925
