### ISSUE TITLE
Headerline breadcrumbs are shared across all windows within a frame

### ISSUE THREAD

**Issue by trillioneyes** [emacs-lsp/lsp-mode#3902]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

When `lsp-headerline-breadcrumb` mode is on in multiple windows, navigating between symbols in a file updates breadcrumbs for all windows in the current frame instead of just the current window.

### Steps to reproduce

Create a project with the following files:

`src/repro1.clj`:
```clojure
(ns repro1)

(def monad 10)
```

`src/repro2.clj`:
```clojure
(ns repro2)

(def dyad 20)
```

Open each file in its own window.

In either file, navigate into one of the `def` forms.

### Expected behavior

The `repro1.clj` window's headerline displays `src/repro1.clj` and the `repro2.clj` window's headerline displays `src/repro2.clj`.

### Which Language Server did you use?

lsp-clojure

### OS

Linux

### Anything else?

I think this was introduced in https://github.com/emacs-lsp/lsp-mode/pull/3856.

**Comment by yyoncho** [comment]
I think that we already have that reported and the fix was not trivial.

**Comment by trillioneyes** [comment]
Do you have a link to the issue? I searched "header" and "breadcrumb" and couldn't find it.

**Comment by Ghibranalj** [comment]
Can confirm the issue. its happening to me too with c/c++ and clangd.

**Comment by yyoncho** [comment]
Fixed with https://github.com/emacs-lsp/lsp-mode/pull/4018
