### ISSUE TITLE
lsp-rust-analyzer-cargo-check command doesn't respect CARGO_HOME env var.

### ISSUE THREAD

**Issue by apoorv569** [emacs-lsp/lsp-mode#3903]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

I have configured my `Emacs` for using `rustic-mode` though I have a problem with the `cargo check` command being run whenever you save your modified buffer.

I have changed my `CARGO_HOME` and `RUSTUP_HOME` to `~/.local/share/cargo` and `~/.local/share/rustup` respectively but the `cargo check` command that runs when you save buffer still uses `~/.cargo` which leads me to compile my project twice before I can run it as I use external terminal to run the project.

Is there a way to fix this? I have tried modifying various variables related to `cargo` `bin` path and all nothing seems to help.

I also have `exec-path-from-shell` plugin installed but it doesn't help either.
```elisp
  (use-package exec-path-from-shell
    :straight t)

  (when (memq window-system '(mac ns x))
    (exec-path-from-shell-initialize))
```

### Steps to reproduce

1. Change your `env` variable for `CARGO_HOME` and `RUSTUP_HOME` to use `~/.local/share/cargo` `~/.local/share/rustup` respectively.
2. Load a `rust` source file with `rust-mode` or `rustic-mode`.
3. Start LSP (either manually or by add a `hook` to your major mode)
4. Make some changes to the file
5. Save the modified buffer (which runs `cargo check` command)

### Expected behavior

The `cargo check` command being run should respect the `CARGO_HOME` `env` variable.

### Which Language Server did you use?

I am using `rust-analyzer`.

### OS

Linux

**Comment by yyoncho** [comment]
Sounds like this is not something that has to be fixed on the client side. 

cc @brotzeit @flodiebold

**Comment by apoorv569** [comment]
I managed to fix this.

`(getenv "CARGO_HOME")` and `(getenv "RUSTUP_HOME")` returned `nil` which made me wonder if the `exec-path-from-shell` does anything and it looks like `exec-path-from-shell` only adds `$PATH` and `$MANPATH` from the `shell` by default. 

Digging around I found this variable `exec-path-from-shell-variables` in which you can specify which `env` variable it should copy. I added all my manually exported `env` variables to this list. It is now working as expected.
