### ISSUE TITLE
How do access doc on a key press?

### ISSUE THREAD

**Issue by Compro-Prasad** [emacs-lsp/lsp-mode#391]
When the point is on an identifier, I would like to pull the doc. Is that possible? If possible can we have, a tooltip, a minibuffer and a separate buffer version?

**Comment by yyoncho** [comment]
`lsp-describe-thing-at-point` - will display help in a separate buffer. You can use https://github.com/emacs-lsp/lsp-ui to display help into popup-like frame.

**Comment by Compro-Prasad** [comment]
lsp-ui is a bit heavy. Using internal Emacs' ovelay system should be enough to show the doc. A variable can be used to control this so that the user can use either a popup, minibuffer or separate buffer.

**Comment by Compro-Prasad** [comment]
Can this be done or I should use lsp-ui?

**Comment by yyoncho** [comment]
As I mentioned in the previous comment that there is `lsp-describe-thing-at-point`. It displays help into a separate buffer, if you want to display it in tooltip - you can copy the function and replace the call to pop-to-buffer.

**Comment by Compro-Prasad** [comment]
Fine then. I am closing this!

**Comment by Compro-Prasad** [comment]
@yyoncho I found a way to do this but there is no font lock support in the tooltip which might be a reason to use an overlay instead.
```emacs-lisp
(defun my-eldoc-display-message (format-string &rest args)
  "Display eldoc message near point."
  (when format-string
    (tooltip-show (apply 'format format-string args))))
(setq eldoc-message-function #'my-eldoc-display-message)
```
