### ISSUE TITLE
headerline updating is slow (with explanation and fix)

### ISSUE THREAD

**Issue by erikarvstedt** [emacs-lsp/lsp-mode#3911]
#### Description
headerline updating, which is called frequently via `lsp--on-idle-timer`, can be slow.

#### Reason
`lsp-headerline--build-string` usually calls `lsp-headerline--build-project-string` or `lsp-headerline--build-path-up-to-project-string`, which call `lsp-workspace-root`.
`lsp-workspace-root` is very slow when the lsp session contains many folders, because it iterates all folders.

#### Possible fix
Rely on field `root` of the workspace object associated with the buffer.

```elisp
(defun lsp-headerline--workspace-root ()
  (--if-let (car lsp--buffer-workspaces)
      (lsp--workspace-root it)))

;; Alternative: Handle the case of multiple workspaces per buffer
;; I'm not sure if this is required as I'm not familiar with lsp's architecture.
(defun lsp-headerline--workspace-root ()
  (->> lsp--buffer-workspaces
       (-map 'lsp--workspace-root)
       (--max-by (> (length it) (length other)))))
```

**Comment by yyoncho** [comment]
Good catch. The first option is good enough. Willing to provide a PR?
