### ISSUE TITLE
Incorrect Vue 3 installation documentation

### ISSUE THREAD

**Issue by BenKrocke** [emacs-lsp/lsp-mode#3915]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

> This Server supports automatic install. Install this language server with `M-x lsp-install-server RET volar-api RET`

This should be:

> This Server supports automatic install. Install this language server with `M-x lsp-install-server RET vue-semantic-server RET`

### Steps to reproduce

<img width="490" alt="image" src="https://user-images.githubusercontent.com/22332245/213034512-449f1d6f-5b22-4287-becd-04e8626ace59.png">

### Expected behavior

> This Server supports automatic install. Install this language server with `M-x lsp-install-server RET vue-semantic-server RET`

### Which Language Server did you use?

`lsp-volar`

### OS

MacOS

**Comment by BenKrocke** [comment]
I'll make a PR.

**Comment by jadestrong** [comment]
Yes，you can,  the `lsp-clients.json` has not been updated.
