### ISSUE TITLE
ruby-ts-mode support

### ISSUE THREAD

**Issue by AndrewSwerlick** [emacs-lsp/lsp-mode#3918]
Is your feature related or already mentioned on [the wishlist](https://github.com/emacs-lsp/lsp-mode/discussions/2892)?

No

Describe your feature here.

With emacs 29 coming, there are a number of new major modes that use the new treesitter parsers. I see that many of these new modes have been added the lsp, but not ruby-ts-mode. I've made a personal fork where I've got this working, and I'd be happy to submit a pull request if there's interest.

**Comment by justinbarclay** [comment]
I'm running into this issue right now

**Comment by yyoncho** [comment]
@AndrewSwerlick forgot the answer here - feel free to open a PR.

**Comment by justinbarclay** [comment]
I think this can be closed now? At least, it works on my machine 🎉
