### ISSUE TITLE
Be more graceful when the lsp process dies or does not exist etc.

### ISSUE THREAD

**Issue by Fuco1** [emacs-lsp/lsp-mode#392]
`lsp-mode` hooks into a bunch of stuff including `imenu` (maybe it comes from a different package?).  Not important though.

Every time I idle for half a second I get this error.  Why should I care as the end user.  If the server does not exist just fall back to something that works, maybe print a message in the minibuffer.  I feel that in general the error handling in this package is very suboptimal.  Lots of assertions or simply assumptions that things work, and when they don't Emacs becomes completely unusable (for example you can't even kill a buffer because lsp is trying to send the "document closed" message).

```
Debugger entered--Lisp error: (cl-assertion-failed (lsp--cur-workspace "No language server is associated with this buffer."))
  cl--assertion-failed(lsp--cur-workspace "No language server is associated with this buffer." nil nil)
  lsp--get-document-symbols()
  lsp--imenu-create-index()
  imenu--make-index-alist(t)
  which-function()
  which-func-update-1(#<window 1835 on abstract-order-method.php>)
  which-func-update()
  apply(which-func-update nil)
  timer-event-handler([t 0 0 500000 t which-func-update nil idle 0])
```

I feel I am quite harsh in my words but I don't know how to express it much better.  I am critical but doing so with love :heart: Lots of great effort has gone into this package.

As a start using `user-error` over `error` would help a great deal where it makes sense.  As an elisp developer I usually have `toggle-debug-on-error` on and so this is really really getting in the way.

**Comment by vibhavp** [comment]
Yes, lsp-mode needs to be more graceful with process crashes. Automatically restarting servers (what eglot does) is a good start.
