### ISSUE TITLE
Typescript object property completion don't appear

### ISSUE THREAD

**Issue by asif-mahmud** [emacs-lsp/lsp-mode#3923]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

I have been using lsp-mode with emacs 28.2 with native compilation enabled. So far so good, only it doesn't provide completion for object properties, usually object's type is set or provided. For example if the type of an object is like this -

```
type Person = {
   name: string;
   age: string;
}
```

when i want to create an object of that type - 

```
const person: Person = {
  n...
}
```
I would expect it to provide completion at character `n` .

### Steps to reproduce

Here's my lsp-mode configuration - 

```
(use-package lsp-mode
  :straight t
  :commands (lsp lsp-deferred)
  :init
  (setq lsp-keymap-prefix "C-c l"
        lsp-enable-snippet t
        lsp-keep-workspace-alive nil
        lsp-lens-enable t
        lsp-headerline-breadcrumb-enable nil
        lsp-enable-on-type-formatting nil
        lsp-enable-indentation nil
        lsp-typescript-format-enable nil
        lsp-javascript-format-enable nil)  
  :hook (
         (json-mode . lsp-deferred)
         (css-mode . lsp-deferred)
         (scss-mode . lsp-deferred)
         (web-mode . lsp-deferred)))
```

With the above mentioned code in a typescript file you can reproduce the issue.

### Expected behavior

It should provide completion for object properties as well. I know typescript language server does that.

### Which Language Server did you use?

I am using `typescript-language-server`.

### OS

Linux

**Comment by yyoncho** [comment]
> It should provide completion for object properties as well. I know typescript language server does that.

Can you see the server returning these properties in client-server communication?

**Comment by asif-mahmud-grype** [comment]
How can i collect server responses ? from log io ? or else.

**Comment by asif-mahmud** [comment]
How can i collect server responses? log io or else ?

**Comment by asif-mahmud** [comment]
so i got this from io log -

**Comment by yyoncho** [comment]
Is this happening with M-x lsp-start-plain?

**Comment by asif-mahmud** [comment]
Sorry for late, i tried it with `lsp-start-plain`.  with the below code snippet - 

```
export type Person = {
    name: string;
    age: number;
};

const person: Person = {
    nam
};
```
when pointer was at `nam` 's `m`,  i saw the completion request like before, but after waiting for some time, i got this - 

```
Warning (lsp-mode): Failed to parse the following chunk:
’’’
Content-Length: 884

{"jsonrpc":"2.0","id":234,"result":{"items":[{"label":"age","kind":5,"sortText":"11\u0000age\u0000","commitCharacters":[".",",","("],"data":{"file":"/home/shimon/Workspace/Git/calan/packages/frontend/features/challan/tryout.ts","line":7,"offset":8,"entryNames":["age"]},"textEdit":{"newText":"age","insert":{"start":{"line":6,"character":4},"end":{"line":6,"character":7}},"replace":{"start":{"line":6,"character":4},"end":{"line":6,"character":7}}}},{"label":"name","kind":5,"sortText":"11\u0000name\u0000","commitCharacters":[".",",","("],"data":{"file":"/home/shimon/Workspace/Git/calan/packages/frontend/features/challan/tryout.ts","line":7,"offset":8,"entryNames":["name"]},"textEdit":{"newText":"name","insert":{"start":{"line":6,"character":4},"end":{"line":6,"character":7}},"replace":{"start":{"line":6,"character":4},"end":{"line":6,"character":7}}}}],"isIncomplete":false}}
’’’
with message (json-parse-error \u0000 is not allowed without JSON_ALLOW_NUL near '"11\u0000age\u0000"' <callback> 1 99 99) Disable showing Disable logging
```

**Comment by asif-mahmud** [comment]
Ok, so after looking out for similar issues here, i found this solution worked, but probably a temporary solution for emacs 28 versions i guess - [https://github.com/typescript-language-server/typescript-language-server/issues/559#issuecomment-1259470791](https://github.com/typescript-language-server/typescript-language-server/issues/559#issuecomment-1259470791)
