### ISSUE TITLE
clojure lsp emacs : usage a of mount package is showing false compilation error.

### ISSUE THREAD

**Issue by rajcspsg** [emacs-lsp/lsp-mode#3932]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

usage a of mount package is showing false compilation error.

I use the package [mount](https://github.com/tolitius/mount) in our codebase.

The code is compiling fine. and is on the [github](https://github.com/rajcspsg/guestbook) here. This code is chapter 2 of the [book web development in clojure](https://pragprog.com/titles/dswdcloj3/web-development-with-clojure-third-edition/).

The compilation of the code works fine. But the emacs IDE gives error like [this](https://imgur.com/a/iB2OhIB)

### Steps to reproduce

1. clone the [code](https://github.com/rajcspsg/guestbook)
2. use the emacs config https://github.com/rajcspsg/emacs.d. The conjure config is mostly in the [file](https://github.com/rajcspsg/emacs.d/blob/master/clojure.el)
3. open the code in emacs editor
4. open the file src/clj/guestbook/handler.clj
5. Emacs will give you compilation errors wherever defstate is used.

### Expected behavior

The code should compile fine and I should be able to go to definitions and references. 

### Which Language Server did you use?

clojure

### OS

MacOS

**Comment by ericdallo** [comment]
Probably the mount lib could deine default clj-kondo export configurations for clients don't need to do anything and just work out of the box, [example ](https://github.com/nubank/state-flow/blob/master/resources/clj-kondo.exports/nubank/state-flow/config.edn)

**Comment by rajcspsg** [comment]
Thanks @ericdallo

**Comment by rajcspsg** [comment]
There is an existing issue on mount lib https://github.com/tolitius/mount/issues/128
