### ISSUE TITLE
Rust inlay type is not showed for all variables.

### ISSUE THREAD

**Issue by nice-river** [emacs-lsp/lsp-mode#3938]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Hi all, I'm using doom-emacs in wsl2.
The problem is that inlay composite types are not displayed. As the picture shows, the variables `b, s, m` do not show types like `a, c, d`.
![image](https://user-images.githubusercontent.com/115790053/215768433-41a853f9-dc1d-44c4-8ce6-06d6971af389.png)

### Steps to reproduce

1. use doom-emacs
2. install `lsp` and `(rust +lsp)` in init.el
3. run` emacs -nw ` in wsl2 terminal

### Expected behavior

show inlay type for all variables.

### Which Language Server did you use?

lsp-rust with rust-analyzer

### OS

Linux

### Error callstack

```emacs-lisp
None
```

### Anything else?

None

**Comment by flodiebold** [comment]
This is mostly intentional, because e.g. in `let s = S { a }` adding `: S` would just be redundant. Some of those heuristics could maybe be improved though, but you'd have to report that in the rust-analyzer repo.

**Comment by yyoncho** [comment]
closing based on @flodiebold comment.
