### ISSUE TITLE
[Question] lsp multi mode

### ISSUE THREAD

**Issue by thepreacher** [emacs-lsp/lsp-mode#394]
There is now lsp-html, lsp-css, lsp-javascript and other languages to come. Is there a way to get them all to work on a buffer that contains multiple languages (say an html file that constains css, javascript etc). Something that works like web-mode does at the moment?

**Comment by gregnwosu** [comment]
I doubt it because we cannot tell infer whether code parsed successfully in an alternative syntax was by luck or by design.

**Comment by vibhavp** [comment]
This would be something that is up to the language server, not the editor.

**Comment by thepreacher** [comment]
@vibhavp I think you're right. I'll close this question and find a way to asked the question on [https://github.com/Microsoft/language-server-protocol](url). Thanks.
