### ISSUE TITLE
More rust-analyzer inlay hints

### ISSUE THREAD

**Issue by rjmac** [emacs-lsp/lsp-mode#3945]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

With the change in to fix #3896, _most_ of the inlay hints now appear - but the ones that were appearing before are now gone.  This is because rust-analyzer only mostly produces inlay hints whose labels are vectors.  A few are still strings.

For example:

![image](https://user-images.githubusercontent.com/753700/216736688-330c76c6-96a7-4ff1-bcee-bbcdb3061835.png)

That second binding has an inlay hint whose value is just `": &str"`, not a vector.

### Steps to reproduce

Uncertain; I'm not sure of the conditions which cause rust-analyzer to do this.  I've seen cases (like the one above) where what looks like almost exactly the same kind of code produces a string label in one case and a vector label in another.  In the file that generated the image above, there are 54 inlay hints processed by `lsp-rust-analyzer-update-inlay-hints`, of which only 6 are bare strings.

### Expected behavior

For all the inlay hints to show up.

### Which Language Server did you use?

lsp-rust

### OS

Linux

### Anything else?

A fix for this is obvious; I'll be making a PR for it in a few seconds.

**Comment by npajkovsky** [comment]
Oh, what version of rust-analyzer do you use?

**Comment by rjmac** [comment]
> Oh, what version of rust-analyzer do you use?

Monday's latest, f1b257f4e 2023-01-27
