### ISSUE TITLE
Code action command argument that is an array gets executed as an object

### ISSUE THREAD

**Issue by bubba** [emacs-lsp/lsp-mode#395]
When the client receives a code action response containing an array as an argument like so:
```json
{
  "result": [
    {
      "command": "10621:hsimport:import",
      "arguments": [
        [
          "file:///Users/luke/Desktop/test/src/Lib.hs",
          "Test.Hspec"
        ]
      ],
      "title": "Import module Test.Hspec"
    }
  ],
  "jsonrpc": "2.0",
  "id": 264
}
```

The client executes the command with the first item in the array as an object key, and the rest as an array:
```json
{
  "jsonrpc": "2.0",
  "method": "workspace/executeCommand",
  "params": {
    "command": "10621:hsimport:import",
    "arguments": {
      "file:///Users/luke/Desktop/test/src/Lib.hs": [
        "Test.Hspec"
      ]
    }
  },
  "id": 268
}
```

Is this intentional? LanguageClient-neovim and VS Code keep the arguments as an array
```json
//vscode
{
  "jsonrpc": "2.0",
  "id": 14,
  "method": "workspace/executeCommand",
  "params": {
    "command": "34669:hsimport:import",
    "arguments": [
      [
        "file:///Users/luke/Desktop/test/src/Lib.hs",
        "Test.Hspec"
      ]
    ]
  }
}

// LangaugeClient-neovim
{
  "jsonrpc": "2.0",
  "method": "workspace/executeCommand",
  "params": {
    "arguments": [
      [
        "file:///Users/luke/Desktop/test/src/Lib.hs",
        "Test.Hspec"
      ]
    ],
    "command": "32954:hsimport:import"
  },
  "id": 31
}
```

**Comment by yyoncho** [comment]
This is a bug - the LSP mode is deserializing arrays as lists but it is serializing lists as objects. It is not clear how this could be fixed. Change the deserializer to deserialize JSON arrays into vectors is a potential solution but this could break clients/extensions. @vibhavp any thoughts?

**Comment by vibhavp** [comment]
Do any clients use the `arguments` field? IIRC, the field is supposed to be sent as is to the server.

**Comment by yyoncho** [comment]
@vibhavp if we change the type to vector it will every result structure, not only the arguments field. I am reffering the following function: 

```elisp
(define-inline lsp--read-json (str)
  (inline-quote
    (let* ((json-array-type 'list)
            (json-object-type 'hash-table)
            (json-false nil))
      (json-read-from-string ,str))))
```

Changing `list` to `vector` will fix the issue.

**Comment by yyoncho** [comment]
I believe that changing the haskell client definition by including use-native-json will fix the issue. Can you test and report. 

Here it is the code: https://github.com/emacs-lsp/lsp-mode/blob/d1d186adcc039ccd10593c71f26acdb9e8a1cf79/lsp-mode.el#L118
