### ISSUE TITLE
Headerline produces error and fails when project path contains symlink

### ISSUE THREAD

**Issue by gc1o1** [emacs-lsp/lsp-mode#3951]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

When my project is in `~USERNAME/link_dir/project/`, where the `link_dir` points to `/mnt/c/Users/USERNAME/OtherDir`,

Then, I get the error:
```Error running timer: (wrong-type-argument stringp nil)```
and every time I move the cursor to another scope I get the similar error:
```Error running timer ‘lsp--on-idle’: (wrong-type-argument stringp nil)```

### Steps to reproduce

Create a project in a directory that is a link to another directory.

Move your cursor around, to update the breadcrumb.  

You will see an error like:
```Error running timer ‘lsp--on-idle’: (wrong-type-argument stringp nil)```
and the breadcrumb will be empty.

### Expected behavior

No errors and a correct breadcrumb.

There is no problem when I move the project to a directory that isn't a symlink.

### Which Language Server did you use?

pyright

### OS

Linux

### Error callstack

```emacs-lisp
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  f-exists\?(nil)
  lsp-f-same\?("/home/USERNAME/link_dir/project" nil)
  lsp-headerline--path-up-to-project-root("/home/USERNAME/link_dir/project" "/mnt/c/Users/USERNAME/OtherDir/project/")
  lsp-headerline--build-path-up-to-project-string()
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_23>(path-up-to-project)
  lsp-headerline--build-string()
  lsp-headerline--check-breadcrumb()
  lsp--on-idle(#<buffer run.py>)
  apply(lsp--on-idle #<buffer run.py>)
  timer-event-handler([t 0 0 500000 nil lsp--on-idle (#<buffer run.py>) idle 0 nil])
```
```


### Anything else?

I use emacs version ```GNU Emacs 28.2 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2023-01-29```

I use the `lsp-mode` version `8.0.1`, according to the comments on the top of my `lsp-mode.el` file.

**Comment by SkydiveMike** [comment]
I can confirm this with various other language servers (`clangd`, `bash-language-server` at least)

**Comment by CamJN** [comment]
I can also confirm.

**Comment by Atreyagaurav** [comment]
I can confirm it on https://github.com/valentjn/ltex-ls server. In a `.org` file inside a symlink directory.

**Comment by vitaminace33** [comment]
I just opened syl20bnr/spacemacs#15939. I can confirm it with `clangd`, `julia` and `texlab`.

**Comment by dnaeon** [comment]
Same issue observed when using `go-mode` as well with `gopls`.

**Comment by joey-coleman** [comment]
I've observed this on macOS, using emacs 28.2, with rustic 3.4 and lsp-mode 8.0.1 as well.  Backtrace below:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  f-exists\?(nil)
  lsp-f-same\?("/Users/jwc/Development/rust/treehouse" nil)
  lsp-headerline--path-up-to-project-root("/Users/jwc/Development/rust/treehouse" "/Volumes/Development/rust/treehouse/src/")
  lsp-headerline--build-path-up-to-project-string()
  #f(compiled-function (segment) #<bytecode -0x11516bdf8bf0fef0>)(path-up-to-project)
  mapconcat(#f(compiled-function (segment) #<bytecode -0x11516bdf8bf0fef0>) (path-up-to-project file symbols) "")
  lsp-headerline--build-string()
  lsp-headerline--check-breadcrumb()
  run-hooks(lsp-on-idle-hook)
  lsp--on-idle(#<buffer main.rs>)
  apply(lsp--on-idle #<buffer main.rs>)
  timer-event-handler([t 0 0 500000 nil lsp--on-idle (#<buffer main.rs>) idle 0 nil])
```

**Comment by yyoncho** [comment]
I will take a look.

**Comment by joey-coleman** [comment]
As an addendum to my comment, running the below in the scratch buffer works just fine:

```
(lsp-headerline--path-up-to-project-root "/Volumes/Development" "/Volumes/Development/rust/treehouse/src")
(lsp-headerline--path-up-to-project-root "/Volumes/Development/rust/treehouse" "/Volumes/Development/rust/treehouse/src")
(#("src" 0 3 (lsp-full-path "/Volumes/Development/rust/treehouse/src" local-map (keymap ...) help-echo "mouse-1: browse 'src' with Dired
mouse-2: browse 'src' with Dired in other window" mouse-face header-line-highlight)))
```

And, in the path `/Users/jwc/Development` in my comment above is a symlink to `/Volumes/Development` (I use a separate volume on my mac to get a case-sensitive filesystem for dev purposes).

**Comment by joey-coleman** [comment]
Thanks @yyoncho
