### ISSUE TITLE
lsp-mode trying to compile temporary files

### ISSUE THREAD

**Issue by gregnwosu** [emacs-lsp/lsp-mode#396]
I keep seeing logs such as
```FileNotFoundError: [Errno 2] No such file or directory: '/Users/greg/dev/tests/jsonformatter/tests/.#test_flask.py'```
in lsp-python stderr buffer.
This occurs when i have an unsaved buffer and lsp-mode tries to compile the tempfile created by emacs that start wih .#[unsaved-filename]
Am i missing some configuration? is there something more i should be doing?

**Comment by dangirsh** [comment]
Just hit this. Here's a quick-fix which puts those files in `/tmp`:

```
;; store all backup and autosave files in the tmp dir
(setq backup-directory-alist
      `((".*" . ,temporary-file-directory)))
(setq auto-save-file-name-transforms
      `((".*" ,temporary-file-directory t)))
```

**Comment by vibhavp** [comment]
`lsp-mode` doesn't compile files. Seems to be an issue with the language server itself, AFAIK.
