### ISSUE TITLE
Don't automatically apply code action when there is only one.

### ISSUE THREAD

**Issue by amano-kenji** [emacs-lsp/lsp-mode#3960]
If there is only one code action available, `lsp-execute-code-action` just executes it without first prompting me to confirm it after seeing the name of the code action.

When there are multiple code actions, I'm prompted to choose among many.

I had to enable `lsp-ui-sideline-show-code-actions` in order to preview code actions in sideline.

**Comment by yyoncho** [comment]
set lsp-auto-execute-action  to nil

**Comment by amano-kenji** [comment]
Thanks.
