### ISSUE TITLE
In some cases, lsp-completion--filter-candidates mistakenly filter out the completion items

### ISSUE THREAD

**Issue by jadestrong** [emacs-lsp/lsp-mode#3961]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

When use `typescript-language-server`,  in some cases, `lsp-completion--filter-candidates` mistakenly filter out the completion items.

As `filterText` is not a necessary field in lsp specification,  and in consideration of performance (because typescript-language-server often returns very complete items),  it does not want to add this additional field. https://github.com/typescript-language-server/typescript-language-server/issues/631

A completion item is as follows :
```json
    {
      "label": "charAt",
      "textEdit": {
        "range": {
          "start": {
            "line": 6,
            "character": 6
          },
          "end": {
            "line": 6,
            "character": 7
          }
        },
        "newText": "?.charAt"
      }
    },
```
Note that the corresponding `filterText: ".?.charAt"` is not provided here,  so it will use `label` to filter: https://github.com/emacs-lsp/lsp-mode/blob/a655f3600e040f872408da0e9c1b9fe65ca0aad9/lsp-completion.el#L258
https://github.com/emacs-lsp/lsp-mode/blob/a655f3600e040f872408da0e9c1b9fe65ca0aad9/lsp-completion.el#L283-L290
This line use `textEdit's start` range as start point, so the  corresponding `guess prefix` is `.ch`, and the label is `charAt`.
Here will use the guess-prefix `.ch` to generate a regexp `\(\.\)[^c]*\(c\)[^h]*\(h\)` as`fuz-query ` , the first char `.` is necessary, but the label `charAt` don't have a `.` prefix, so it will be filtered out.
https://github.com/emacs-lsp/lsp-mode/blob/a655f3600e040f872408da0e9c1b9fe65ca0aad9/lsp-completion.el#L232-L233

### Steps to reproduce

1. install typescript-language-server
2. open a typescript file, such as `test.ts`
3. insert follow code:
```typescript
interface Test {
    name?: string;
}

const s: Test = {};

s.name.ch // <- cursor 
```

### Expected behavior

Expected to complete all `string's method` completion items, but nothing, all items are filtered out.

### Which Language Server did you use?

lsp-javascript

### OS

MacOS

**Comment by ikapo** [comment]
I too am experiencing this

**Comment by jadestrong** [comment]
You can try to `advice-add` this function to override the origin one,  use `insert-text` and `text-edit` first,  finally use `label` fallback.  I feel it's OK. @ikapo 
```
(defun lsp-completion--to-internal (items)
  "Convert ITEMS into internal form."
  (--> items
       (-map (-lambda ((item &as &CompletionItem
                             :label
                             :filter-text?
                             :insert-text?
                             :text-edit?
                             :_emacsStartPoint start-point
                             :score?))
               `( :label ,(or (unless (lsp-falsy? filter-text?) filter-text?)
                              (unless (lsp-falsy? insert-text?) insert-text?)
                              (unless (lsp-falsy? text-edit?) (lsp:text-edit-new-text text-edit?))
                              label)
                  :item ,item
                  :start-point ,start-point
                  :score ,score?))
             it)))
```
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/18475217/219535255-828af91a-b566-4077-9159-9b33d647124c.png">

**Comment by yyoncho** [comment]
The client is supposed to use the textEdit range to determine the prefix to match agaist label/filterText. In this case, the server should return a properly adjusted filterText because the label cannot match the label. Using textEdit.insertText cannot work because the insert text may be something completely different in for example infix match. I think that this is a regression on the server side because ts-ls used to work correctly.

**Comment by ikapo** [comment]
To be clear I am not getting **any** completions after typing `.` (it would complete variable names but not their methods, e.g. "TEST".[no completions offered] ).
@yyoncho If you look at the issue @jadestrong posted in the first comment, you'll see that the lead maintainer of the typescript language server doesn't seem too keen on returning `filterText`.
This means that installing typescript-language-server v3.2 or above will break method completion, although the snippet posted above fixed that.
Is there some way to support this directly in `lsp-mode`? This makes the language server incredibly less useful, even though it's not this project's fault

**Comment by yyoncho** [comment]
@ikapo I answered in the original issue - I hope that the ts-ls maintainers comply with the spec.

**Comment by ikapo** [comment]
@yyoncho This kind of dedication is what keeps me coming back to Emacs, no matter what issues arise.
Thank you for your amazing work and dedication to this project

**Comment by yyoncho** [comment]
There was a commit in the language server. Can someone confirm that this issue is no longer relevant?

**Comment by jadestrong** [comment]
It's okay to close it.
