### ISSUE TITLE
Don't use lsp-format-region as indent-region-function

### ISSUE THREAD

**Issue by muffinmad** [emacs-lsp/lsp-mode#398]
Region formatting may include various corrections like whitespace around operators etc. but indent-region-function must be used just for indentation.

https://github.com/emacs-lsp/lsp-mode/blob/5ea5c6398a923e24c4fedf6d782004b4dc4cb254/lsp-methods.el#L894

**Comment by vibhavp** [comment]
Doing that would break someone else's setup. You could set `lsp-enable-indentation` to `nil` instead.
