### ISSUE TITLE
Format does not work after dynamic registration

### ISSUE THREAD

**Issue by iquiw** [emacs-lsp/lsp-mode#399]
Hi, I'm writing client for [yaml-language-server](https://github.com/redhat-developer/yaml-language-server).

yaml-language-server initially responses `"documentFormattingProvider": false`.

<details>
<summary>server capabilities</summary>

```
Output from language server: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "capabilities": {
      "textDocumentSync": 1,
      "completionProvider": {
        "resolveProvider": true
      },
      "hoverProvider": true,
      "documentSymbolProvider": true,
      "documentFormattingProvider": false
    }
  }
}
```

</details>

If client sends `yaml.format.enable = true` configuration (`workspace/didChangeConfiguration`), the server sends `client/registerCapability` with `textDocument/formatting`.

<details>
<summary>client registerCapabilities</summary>

```
Output from language server: {
  "jsonrpc": "2.0",
  "id": 0,
  "method": "client/registerCapability",
  "params": {
    "registrations": [
      {
        "id": "c4224618-c696-4391-abe0-be3bcd6c18d4",
        "method": "textDocument/formatting",
        "registerOptions": {
          "documentSelector": [
            {
              "language": "yaml"
            }
          ]
        }
      }
    ]
  }
}
```

</details>

After that, calling `lsp-format-buffer` signals the error.

`Capability not supported by the language server: "documentFormattingProvider"`

**Comment by vibhavp** [comment]
5a6cc5e53672a0f6fe0ab70ab03c3f29beeeb922 should fix this.

**Comment by iquiw** [comment]
@vibhavp Thank you!
