### ISSUE TITLE
beancount language server specification is out-of-date

### ISSUE THREAD

**Issue by lunik1** [emacs-lsp/lsp-mode#3992]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

The specification for the beancount language server in `clients/lsp-beancount.el` is outdated. The executable name has since changed, and it no longer needs a python executable (afaict).

### Steps to reproduce

Start LSP in `beancount-mode` with latest version of `beancount-language-server` (v1.2.5)

### Expected behavior

LSP should start.

### Which Language Server did you use?

beancount-lanaguage-server

### OS

Linux

### Anything else?

I have made an attempt to patch this [here](https://github.com/lunik1/lsp-mode/commit/0d7bf64650b1c6c3261fc800a94e77a5e21411d3#diff-5699382ed1bce71edf1a7ff34de77364ca15afc8a8f502942d20841e519fddfa) but have hit a wall with a couple of issues:

- The language server will not complete initialisation if `lsp-beancount-python-interpreter` is unset
- The language server crashes constantly, with no stderr output

**Comment by ericdallo** [comment]
@lunik1 thanks for the report, willing to open a PR?

**Comment by lunik1** [comment]
Sure, #4009

**Comment by lunik1** [comment]
Closed by #4134
