### ISSUE TITLE
Inlay hints for Rust project not working properly 

### ISSUE THREAD

**Issue by Yuanda-Dong** [emacs-lsp/lsp-mode#4029]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

I'm expecting the inlay hints to work for 
- variable type hints [which i think worked before #3970]
- function parameters hints [which i think didn't work even before #3970]

However, i believe i'm getting hints only for an incomplete set of variables. See the pictures below

lsp-mode 
![swappy-20230425-183801](https://user-images.githubusercontent.com/37124273/234222533-d9db19c2-a6a5-40c9-af0d-7d437340504f.png)

Eglot 
![swappy-20230425-183850](https://user-images.githubusercontent.com/37124273/234222391-adf31176-4dba-497e-9c81-7b6748b609c0.png)

### Steps to reproduce

Open any rust project with lsp-mode and rustic-mode 

### Expected behavior

Inlay hints work for all cases where the language server work

### Which Language Server did you use?

rust-analyzer 

### OS

Linux

**Comment by Yuanda-Dong** [comment]
A more minimal example, where i'm expecting the variable y has the type Vec<i32>
![swappy-20230425-185040](https://user-images.githubusercontent.com/37124273/234225244-bfeb9257-3f22-4134-adad-43c9c454a82c.png)

**Comment by ashlineldridge** [comment]
I am also seeing this bug since upgrading lsp-mode to include the changes in https://github.com/emacs-lsp/lsp-mode/pull/3970. At least for rust-analyzer, there appears to be a regression in inlay type hints.

**Comment by asandroq** [comment]
I've sent [a pull request](https://github.com/emacs-lsp/lsp-mode/pull/4044) to fix this.
