### ISSUE TITLE
Please list copyright holders

### ISSUE THREAD

**Issue by thkoch2001** [emacs-lsp/lsp-mode#404]
I'd like to package lsp-haskell (and its dependencies lsp-ui, lsp-mode) for Debian:
https://bugs.debian.org/905688

The debian/copyright file should list the copyright holders. I can guess them from the Git history, but it would be correct to look them up e.g. from an AUTHORS file in the repository. Would you be so kind to include those in at least the above repositories, maybe in all repos in this org?

This links give examples for how to create AUTHORS files:
https://www.gnu.org/prep/maintain/html_node/Recording-Contributors.html
https://opensource.google.com/docs/releasing/authors/
https://github.com/django/django/blob/master/AUTHORS
https://coderwall.com/p/jt8mpq/create-authors-file-from-git

Thank you!

**Comment by vibhavp** [comment]
Added in f0beac6c630ccc2495dac4b63ceb97d577166c3c.
