### ISSUE TITLE
Lua LSP requests the incorrect Linux release on install

### ISSUE THREAD

**Issue by Mateus-Carmo31** [emacs-lsp/lsp-mode#4042]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [x] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

One of the LSPs provided by `lsp-mode` for the Lua programming language, sumneko's (now LuaLS) `lua-language-server`, started providing a linux musl version as well as the libc linux release. However, due to how the LSP is registered in `lsp-lua.el`, the musl version is always the one downloaded, which causes users without musl to be unable to run the LSP.

### Steps to reproduce

Assuming you don't have musl on your linux machine:

1) Open a .lua file.
2) Start the lsp.
3) Select `lua-language-server` from the lsp installer.
4) The lsp will be started, but will error and fail to launch, and stderr will report a 'No file or directory' error on the executable.

### Expected behavior

The `linux-x64.tar.gz` version should be used instead of the `linux-x64-musl.tar.gz` release on computers that don't use/have musl.

### Which Language Server did you use?

`lua-language-server`

### OS

Linux

### Error callstack

```emacs-lisp
(the error isn't with the lsp-mode library or elisp code, but I provided the LSP process here)

LSP :: Download lua-language-server started.
Contacting host: api.github.com:443
Latest version found: 3.6.19
LSP :: Starting to download https://github.com/LuaLS/lua-language-server/releases/download/3.6.19/lua-language-server-3.6.19-linux-x64-musl.tar.gz to /home/carmo/.emacs.d/.local/etc/lsp/lua-language-server/lua-language-server-github.tar.gz...
Contacting host: github.com:443
Wrote /home/carmo/.emacs.d/.local/etc/lsp/lua-language-server/lua-language-server-github.tar.gz
LSP :: Finished downloading /home/carmo/.emacs.d/.local/etc/lsp/lua-language-server/lua-language-server-github.tar.gz...
LSP :: Decompressing /home/carmo/.emacs.d/.local/etc/lsp/lua-language-server/lua-language-server-github.tar.gz...
(Shell command succeeded with no output)
LSP :: Decompressed /home/carmo/.emacs.d/.local/etc/lsp/lua-language-server/lua-language-server-github...
LSP :: Server lua-language-server downloaded, auto-starting in 1 buffers.
LSP :: Sending to process failed with the following error: Process lua-language-server not running
LSP :: Guessed project root is ~/.config/awesome
LSP :: Connected to [lua-language-server:22099/starting].
LSP :: lua-language-server has exited (exited abnormally with code 127)
Server lua-language-server:22099/starting exited with status exit(check corresponding stderr buffer for details). Do you want to restart it? (y or n)
```

### Anything else?

I'm not too familiar with proper nomenclature when it comes to libc/musl, so I apologize if my phrasing sounds odd.

Also, now that sumneko has moved the project to LuaLS, maybe it'd be appropriate to change the github API link as well?

**Comment by Mateus-Carmo31** [comment]
This is not that serious a bug at all, as the LSP can easily be downloaded from the repo. However, the `lsp-lua-language-server-install-latest` and `lsp--find-latest-gh-release-url` functions aren't up to date with how LuaLS are handling the releases in the repository anymore.

**Comment by elken** [comment]
Try that PR and see if that works :)

**Comment by Mateus-Carmo31** [comment]
@elken apologies for the delay, but yes, that works!

**Comment by Mateus-Carmo31** [comment]
the download link still uses LuaLS's old username on GH, but I'm not sure if that can be an issue. the download seems to work fine now, so I'll close the issue.

**Comment by elken** [comment]
No worries, the redirect will still work fine; I wasn't aware the username also changed. Feel free to PR the change :)
