### ISSUE TITLE
Invalid face reference: lsp-flycheck-info-unnecessary (again)

### ISSUE THREAD

**Issue by vjohansen** [emacs-lsp/lsp-mode#4056]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

I get a lot of **Invalid face reference** in the messages buffer. See also latest comment here #2255

Sometimes 50 message per second in typescript buffer with lsp-mode enabled.

```
LSP :: Connected to [ts-ls:34084/starting c:/code/TCW].
Package dash-functional is obsolete; use dash 2.18.0 instead
LSP :: ts-ls:34084 initialized successfully in folders: (c:/code/TCW)
Invalid face reference: quote [198 times]
Undo
Invalid face reference: quote [69 times]
Undo
Invalid face reference: quote [3 times]
Undo
Invalid face reference: quote [171 times]
Invalid face reference: lsp-flycheck-info-unnecessary [2 times]
Invalid face reference: quote [3 times]
Invalid face reference: lsp-flycheck-info-unnecessary [2 times]
Invalid face reference: quote [3 times]
Invalid face reference: lsp-flycheck-info-unnecessary [9 times]
Invalid face reference: quote [3 times]
Invalid face reference: lsp-flycheck-info-unnecessary [7 times]
Invalid face reference: quote [3 times]
Invalid face reference: lsp-flycheck-info-unnecessary [8 times]
Invalid face reference: quote [3 times]
Invalid face reference: lsp-flycheck-info-unnecessary


```

lsp-mode version 20221207.1707

### Steps to reproduce

change a ts-file so it does not compile

### Expected behavior

No error messages in messages buffer

### Which Language Server did you use?

ts-ls it seems

### OS

Windows

**Comment by vjohansen** [comment]
Just tried it (deleted entire .emacs.d folder that included elpa folder).   Same results : a lot of warnings.

**Comment by vjohansen** [comment]
I got mislead by reading the comments in #2255. I did not actually have the fix from leungbk since it is not released yet. The lsp-mode version I get from melpa is 8.0.0. Some of the commentors in #2255 does not appear to know this.

If I change lsp-diagnostics.el to include the fix the "Invalid face reference: lsp-flycheck-info-unnecessary" issue is gone and I am left with a LOT of **"Invalid face reference: quote"**

For example if I open a tsx file and change a variable declaration name I get 'xx is declared but its value is never read'. When I move left or right while point is in the identifier 10 occurences of "Invalid face reference: quote" happen each time.

Maybe this bug report should be closed and I should make a new for "Invalid face reference: quote". But this issue seems difficult to debug.

**Comment by pixel-ant** [comment]
These are my findings.

# Current situation
This is what `lsp-mode` does:

For each _error_ of some _level_ and tagged with some _tags_ that LSP server yields:
1. Generate a _generated flycheck level_, a _generated category_ and a _generated face_ named after _level_ and _tags_.
   - E.g: `lsp-flycheck-info-unnecessary`, `lsp-flycheck-info-unnecessary-category` and `lsp-flycheck-info-unnecessary-face` respectively.
2. Set property `face` of _generated category_ to _generated face_.
   - E.g: `lsp-flycheck-info-unnecessary-category`.`face` <- `lsp-flycheck-info-unnecessary-face`.
3. Create a _symbol overlay_ to highlight the erroneous symbol.
   - E.g: `symbol-overlay-1`.
4. Set `category` property of _symbol overlay_ to _generated category_.
   - E.g: `symbol-overlay-1`.`category` <- `lsp-flycheck-info-unnecessary-category`.
5. Create a _sideline overlay_ to display _error message_ near the erroneous line.
   - E.g: `sideline-overlay-1`.
6. Set `face` property of _error message_ to _generated flycheck level_. BUG?????
   - E.g: "very bad done".`face` <- `lsp-flycheck-info-unnecessary`.

# Consequences
Emacs can't find the face named as _generated flycheck level_ as many times as characters in _error message_?
So many error messages like
   ```
   Invalid face reference: lsp-flycheck-info-unnecessary [38 times]
   ```
are emitted

As `lsp-ui-sideline.el` does not define a face named as _generated flycheck level_, this must be a bug.

If authors pretended to use the same face for _symbol overlay_ and _sideline overlay_, both `face` properties should be set to _generated face_.

# Transient solution
To avoid changing the original source code, the referenced face can be defined in init file. E.g:

```elisp
(defface lsp-flycheck-info-unnecessary
  '((t))
  "Face which apply to side line for symbols not used.
Possibly erroneously redundant of lsp-flycheck-info-unnecessary-face."
  :group 'lsp-ui-sideline)
```

Then it can be themed or customized. Remember this is the face for _sideline overlay_.
This has stopped all error messages for me.

# Permanent solution
I prefer different faces for _symbol overlay_ and _sideline overlay_.
But that of _sideline overlay_ should be named `lsp-ui-sideline-{level}-{tags}-face`.
If a _generated flycheck level_ like `lsp-flycheck-info-unnecessary` is made a face name, it confuses users when searching for a face name related to sidelines.

**Comment by rileyrg** [comment]
As a related note : customise face for this face does not work. Its saved to my custom.el but doesnt take effect the next time I start emacs. I havent at this point done any diggin but will report back when I get around to it.

**Comment by jonmoore** [comment]
Till an issue with 20240105.1735

**Comment by jonmoore** [comment]
Thanks @pixel-ant , your analysis and commentary were very helpful.
