### ISSUE TITLE
emacs 27.2 lsp mode can't find reference

### ISSUE THREAD

**Issue by zzachimed** [emacs-lsp/lsp-mode#4063]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

hi :
when i use emacs27.2 in centos stream9 and try to use lsp-mode to find c-mode function reference it show "(void-variable xref-auto-jump-to-first-xref)"

this is my lsp version and emacs version:
LSP :: lsp-mode 20230524.1820, Emacs 27.2, gnu/linux

this is my server info:
root@icx-14 /home/zhaozhou/qemu_deliever/qemu/build (master)
$ hostnamectl
 Static hostname: icx-14
       Icon name: computer-server
         Chassis: server 🖳
      Machine ID: b95b5747debe499fa9764c883224fdfe
         Boot ID: c8a08784c79f4d35b67dd1e7f036b40a
Operating System: CentOS Stream 9
     CPE OS Name: cpe:/o:centos:centos:9
          Kernel: Linux 5.14.0-305.el9.x86_64
    Architecture: x86-64
 Hardware Vendor: Inspur
  Hardware Model: NF5280M6
Firmware Version: 06.00.04

### Steps to reproduce

 1 . dnf install emacs.x86_64
 2.  create "init.el" under ~/.emacs.d/:
         ;(scroll-bar-mode -1)        ; Disable visible scrollbar
;(tool-bar-mode -1)          ; Disable the toolbar
(tooltip-mode -1)           ; Disable tooltips
;(set-fringe-mode 10)        ; Give some breathing room

(menu-bar-mode -1)            ; Disable the menu bar

;; Set up the visible bell
(setq visible-bell t)
(load-theme 'wombat)
;; Make ESC quit prompts
(global-set-key (kbd "<escape>") 'keyboard-escape-quit)

(require 'package)

;;(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("org" . "https://orgmode.org/elpa/")
                         ("elpa" . "https://elpa.gnu.org/packages/")))
(package-initialize)

(setq package-selected-packages '(lsp-mode yasnippet lsp-treemacs helm-lsp
    projectile hydra flycheck company avy which-key helm-xref dap-mode use-package))

(when (cl-find-if-not #'package-installed-p package-selected-packages)
  (package-refresh-contents)
  (mapc #'package-install package-selected-packages))

(require 'use-package)
(setq use-package-always-ensure t)

;; sample `helm' configuration use https://github.com/emacs-helm/helm/ for details
;;(helm-mode)
;;(require 'helm-xref)
;;(define-key global-map [remap find-file] #'helm-find-files)
;;(define-key global-map [remap execute-extended-command] #'helm-M-x)
;;(define-key global-map [remap switch-to-buffer] #'helm-mini)

(use-package ivy
  :diminish
  :bind (("C-s" . swiper)
         :map ivy-minibuffer-map
         ("TAB" . ivy-alt-done)
         ("C-l" . ivy-alt-done)
         ("C-j" . ivy-next-line)
         ("C-k" . ivy-previous-line)
         :map ivy-switch-buffer-map
         ("C-k" . ivy-previous-line)
         ("C-l" . ivy-done)
         ("C-d" . ivy-switch-buffer-kill)
         :map ivy-reverse-i-search-map
         ("C-k" . ivy-previous-line)
         ("C-d" . ivy-reverse-i-search-kill))
  :config
  (ivy-mode 1))

(use-package doom-modeline
  :ensure t
  :init (doom-modeline-mode 1)
  :custom ((doom-modeline-height 15)))

(add-to-list 'auto-mode-alist '("\\.h\\'" . c-mode))
(add-to-list 'auto-mode-alist '("\\.tcc\\'" . c++-mode))
(add-to-list 'auto-mode-alist '("\\.hpp\\'" . c++-mode))

;;(which-key-mode)
;;(add-hook 'c-mode-hook 'lsp)
;;(add-hook 'c++-mode-hook 'lsp)
;;(add-hook 'rust-mode-hook 'lsp)

(setq gc-cons-threshold (* 100 1024 1024)
      read-process-output-max (* 1024 1024)
      treemacs-space-between-root-nodes nil
      company-idle-delay 0.0
      company-minimum-prefix-length 1
      lsp-idle-delay 0.1)  ;; clangd is fast

(with-eval-after-load 'lsp-mode
  (add-hook 'lsp-mode-hook #'lsp-enable-which-key-integration)
  (require 'dap-cpptools)
  (yas-global-mode))

;;(use-package lsp-mode
;;  :init
;;  (setq lsp-keymap-prefix "M-.")
 ;; )

(setq lsp-clangd-binary-path "/usr/bin/clangd")
(use-package lsp-mode
  :init
  ;; set prefix for lsp-command-keymap (few alternatives - "C-l", "C-c l")
  (setq lsp-keymap-prefix "M-.")
  :hook (;; replace XXX-mode with concrete major-mode(e. g. python-mode)
         (c++-mode . lsp)
         (c-mode . lsp)
         (rust-mode . lsp)
         (python-mode . lsp)
         ;; if you want which-key integration
         (lsp-mode . lsp-enable-which-key-integration))
  :commands lsp)

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   '(thrift rust-auto-use cmake-mode modern-cpp-font-lock cask rust-mode json-mode protobuf-mode bazel ninja-mode meson-mode realgud-lldb swiper magit lsp-mode yasnippet lsp-treemacs helm-lsp projectile hydra flycheck company avy which-key helm-xref dap-mode use-package)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

 4.  git clone https://gitlab.com/qemu-project/qemu.git
 5. cd qemu && git submodule update --init --recursive
 6. mkdir build 
 7. bear -- make
 8. emacs ../migration/ram.c
 9. lsp-find-definition  "any funcion in this file"

### Expected behavior

can find function define

### Which Language Server did you use?

lsp-c

### OS

Linux

### Error callstack

```emacs-lisp
Debugger entered--Lisp error: (void-variable xref-auto-jump-to-first-xref)
  lsp-show-xrefs((#<xref-item xref-item-155ed230a9c8> #<xref-item xref-item-155ed2a49618> #<xref-item xref-item-155ed2a49670> #<xref-item xref-item-155ed2a496d4> #<xref-item xref-item-155ed2a49728> #<xref-item xref-item-155ed2a497d0> #<xref-item xref-it$
  lsp-find-locations("textDocument/references" (:context (:includeDeclaration t)) :display-action nil :references\? t)
  lsp-find-references(nil)
  funcall-interactively(lsp-find-references nil)
  call-interactively(lsp-find-references nil nil)
  command-execute(lsp-find-references)
```

### Anything else?

this is my  lsp-describe-session:
[-]/home/zhaozhou/qemu_deliever/qemu
 `-[-]clangd:571065
    |-[-]Buffers
    |  `-[X]ram.c
    `-[-]Capabilities
       |-[X]workspaceSymbolProvider: t
       |-[X]typeHierarchyProvider: t
       |-[X]typeDefinitionProvider: t
       |-[-]textDocumentSync:
       |  |-[X]save: t
       |  |-[X]openClose: t
       |  `-[X]change: 2
       |-[X]standardTypeHierarchyProvider: t
       |-[-]signatureHelpProvider:
       |  `-[X]triggerCharacters: [( ) { } < > ,]
       |-[-]semanticTokensProvider:
       |  |-[X]range: nil
       |  |-[-]legend:
       |  |  |-[X]tokenTypes: [variable variable parameter function method function property variable class interface enum enumMember type type unknown namespace typeParameter concept type macro modifier operator comment]
       |  |  `-[X]tokenModifiers: [declaration definition deprecated deduced readonly static abstract virtual dependentName defaultLibrary usedAsMutableReference usedAsMutablePointer constructorOrDestructor userDefined functionScope classScope fileScope\
 globalScope]
       |  `-[-]full:
       |     `-[X]delta: t
       |-[X]selectionRangeProvider: t
       |-[-]renameProvider:
       |  `-[X]prepareProvider: t
       |-[X]referencesProvider: t
       |-[X]memoryUsageProvider: t
       |-[X]inlayHintProvider: t
       |-[X]implementationProvider: t
       |-[X]hoverProvider: t
       |-[X]foldingRangeProvider: t
       |-[-]executeCommandProvider:
       |  `-[X]commands: [clangd.applyFix clangd.applyTweak]
       |-[X]documentSymbolProvider: t
       |-[X]documentRangeFormattingProvider: t
       |-[-]documentOnTypeFormattingProvider:
       |  |-[X]moreTriggerCharacter: []
       |  `-[X]firstTriggerCharacter:

       |-[-]documentLinkProvider:
       |  `-[X]resolveProvider: nil
       |-[X]documentHighlightProvider: t
       |-[X]documentFormattingProvider: t
       |-[X]definitionProvider: t
       |-[X]declarationProvider: t
       |-[-]completionProvider:
       |  |-[X]triggerCharacters: [. < > : " / *]
       |  `-[X]resolveProvider: nil
       |-[-]compilationDatabase:
       |  `-[X]automaticReload: t
       |-[-]codeActionProvider:
       |  `-[X]codeActionKinds: [quickfix refactor info]
       |-[X]clangdInlayHintsProvider: t
       |-[X]callHierarchyProvider: t
       `-[X]astProvider: t
[compile_commands.ZIP](https://github.com/emacs-lsp/lsp-mode/files/11623185/compile_commands.ZIP)

**Comment by zzachimed** [comment]
i test version :
LSP :: lsp-mode 20220906.1121, Emacs 27.2, gnu/linux
it seems okay

**Comment by agrover** [comment]
I'm also seeing this with lsp-rust emacs 27.1 (debian bullseye)  lsp-mode-20230608.739.

**Comment by superbear** [comment]
reinstall xref(version：1.6.3) package，it works for me.

LSP :: lsp-mode 20230614.2208, Emacs 27.2

**Comment by agrover** [comment]
@superbear that fixed it for me (thanks!), although I have no idea why.

**Comment by dgutov** [comment]
Emacs 27.1 comes with a much older version of Xref. Installing 1.6.3 is an upgrade.

If lsp-mode uses this variable, it should declare the minimum xref version it requires.

**Comment by Lunderberg** [comment]
I ran into the same issue, and agree with @dgutov that the dependencies by `lsp-mode` should be updated.  I've submitted https://github.com/emacs-lsp/lsp-mode/pull/4244, though it would be helpful if somebody more familiar with elpa takes a look at it.
