### ISSUE TITLE
update vscode-eslint configuration

### ISSUE THREAD

**Issue by NdYAG** [emacs-lsp/lsp-mode#4091]
vscode-eslint has released several versions since 2.2.2 (Oct 2021), the current release is `2.4.2`. The recent version removes the [annoying messages](https://github.com/microsoft/vscode-eslint/issues/1238), which in emacs keeps calling `completion-read` that can result displaying a popup from minibuffer. And also it add support for other experimental features, such as flat config.

While `lsp-eslint` supports customizing server-command like this,

```lisp
(setq lsp-eslint-server-command
             `(“node”
               “/Users/xxx/.vscode/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js”
               “—stdio”))
```

the eslint server starts but there’re errors due to incomplete `lsp-eslint—configuration`. The new `vscode-eslint` extension reports that:

```
  “message”: “Request textDocument/codeAction failed with message: Cannot read property ‘useFlatConfig’ of undefined”
```

```
TypeError: Cannot read property ‘shortenToSingleLine’ of undefined\n    at Object.e.create (/Users/xxx/.vscode/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:16735)
```

`experimental` & `problems` are newly added workspace configuration. If set, the errors are gone and the eslint language server works as expected:

https://github.com/emacs-lsp/lsp-mode/blob/eb224a455c3f2d2feeea27aeb87dc3d4541a47a6/clients/lsp-eslint.el#L263

```lisp
                              :codeActionOnSave (list :enable (lsp-json-bool lsp-eslint-auto-fix-on-save)
                                                      :mode lsp-eslint-fix-all-problem-type)
                              :format (lsp-json-bool lsp-eslint-format)
                              :quiet (lsp-json-bool lsp-eslint-quiet)
                              :onIgnoredFiles (if lsp-eslint-warn-on-ignored-files “warn” “off”)
                              :options (or lsp-eslint-options (ht))
++                              :experimental (ht)
++                              :problems (ht)
```

> eslint.problems.shortenToSingleLine: (@since 2.3.0) - Shortens the text spans of underlined problems to their first related line.
> eslint.experimental.useFlatConfig: (@since 2.3.0) - Enables support of experimental Flat Config (aka eslint.config.js, supported by ESLint version 8.21 or later)
> eslint.timeBudget.onValidation (@since 2.3.5) - controls the time budget that can be used for validation before a warning or an error is shown.
> eslint.timeBudget.onFixes (@since 2.3.5) - controls the time budget that can be used to compute fixes before a warning or an error is shown.
> https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

**Comment by zeorin** [comment]
@NdYAG Just wanted to say: thanks for this! The new eslint language server is much faster!
