### ISSUE TITLE
lsp-keymap-prefix launched command fail with mouse hovering over lsp buffer.

### ISSUE THREAD

**Issue by rileyrg** [emacs-lsp/lsp-mode#4118]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Emacs 29.1 Debian 12. Sway.

If my mouse pointer is over my lsp buffer then keyboard chords using lsp-keymap-prefix fail. In this video you will see my mouse near to the cursor. I hit C-l (my prefix) then shift and it bugs out with mouse movement errors. If I do the exact same thing with the mouse NOT over the buffer it works. This is both with and without lsp-ui-doc-mode on.

https://streamable.com/ada108

I asked about it here too: https://www.reddit.com/r/emacs/comments/15f6tps/lsp_prefix_and_command_invocation_fails/?utm_source=share&utm_medium=web2x&context=3

### Steps to reproduce

Set a lsp prefix, start a lsp buffer, have mouse over the buffer, isse the prefix and then shift to access, say, "F".

### Expected behavior

No error

### Which Language Server did you use?

dart and clangd

### OS

Linux

**Comment by rileyrg** [comment]
Linked to this:
https://www.reddit.com/r/emacs/comments/15bzk4a/corfu_lsp_disappearing_selections_in_a_cpp_file/

Again, moving the mouse away from the lsp buffer fixes the issue I was having with corfu.

**Comment by yyoncho** [comment]
try disabling tooltip in dap-auto-configure-features

**Comment by rileyrg** [comment]
Aargh, I didnt think to look at dap parameters. Yes, that has fixed it for me. In both the corfu drop down problem and the lsp interactive commands issue.
