### ISSUE TITLE
TailwindCSS LSP client support

### ISSUE THREAD

**Issue by gekoke** [emacs-lsp/lsp-mode#4130]
Using https://github.com/tailwindlabs/tailwindcss-intellisense/tree/HEAD/packages/tailwindcss-language-server

**Comment by jcs090218** [comment]
This https://github.com/merrickluo/lsp-tailwindcss?

**Comment by gekoke** [comment]
> This https://github.com/merrickluo/lsp-tailwindcss?

Yes, that'll do :)
