### ISSUE TITLE
"go to definition" going to wrong definition in C/C++ headers

### ISSUE THREAD

**Issue by korteland** [emacs-lsp/lsp-mode#4148]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Given a struct definition in a header file:
```
struct foo {
    other_type member1;
};
```

Putting the cursor over `other_type` and attempting to go to definition with `M-.` results in jumping to `member1` rather than the definition of `other_type`.

### Steps to reproduce

I verified this with `lsp-start-plain`:

1. `git clone https://github.com/wiredtiger/wiredtiger.git`
2. Open `wiredtiger/src/include/session.h` in Emacs. Select `wiredtiger` as the project directory and let the background compilation thing finish.
4. Find `struct __wt_session_impl`. Try to jump to one of the types of a struct member with `M-.`, I used `WT_DATA_HANDLE`.

Observe that it doesn't jump to `WT_DATA_HANDLE` in `src/include/wiredtiger.in`, but instead `dhandle` on the same line - as if the server had been asked to locate the definition of `dhandle` rather than `WT_DATA_HANDLE`. All of the other struct members do this - you can try with `WT_EVENT_HANDLER` or `WT_SESSION` and it has the same issue.

### Expected behavior

Should jump to the definition of (e.g.) `WT_DATA_HANDLE` in `src/include/wiredtiger.in`

Note that VS Code is fine with this when using the same `clangd`, so I'm pretty sure it isn't `clangd` doing the wrong thing.

### Which Language Server did you use?

clangd

### OS

Linux

### Anything else?

Please let me know if there's any information or diagnostics you need, or if you have any trouble repro-ing - this affects several people I know of.

**Comment by yyoncho** [comment]
Have you generated compile_commands.json?

**Comment by korteland** [comment]
Yes, I ran the following cmake command:

`cmake -DENABLE_DIAGNOSTIC=1 -DENABLE_STRICT=1 -DENABLE_PYTHON=1 -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -G Ninja ../.`

I then copied `compile_commands.json` to the `wiredtiger` directory, which is also the project directory (sorry if I'm getting the terminology wrong here).

If it helps, jumping to definition from source files works fine - e.g. I can open `src/txn/txn_ckpt.c` and jump to `WT_SESSION_IMPL` in `src/include/wt_internal.h`, then jump from there to `struct __wt_session_impl` in the example.

**Comment by korteland** [comment]
A more minimal working `cmake` line would be `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 ../.`.

**Comment by yyoncho** [comment]
It will be helpful if you can provide logs from vscode.

**Comment by korteland** [comment]
I can take a look tomorrow - do you know how to get logs from VS Code? I got someone else to test it on their machine running the same `clangd` so I'm really not familiar with it unfortunately.

**Comment by korteland** [comment]
I had a go at this today, but I think I was looking at the wrong set of preferences? There seems to be another set besides user preferences. I had a look for clangd in all of the preferences I could find, but couldn't see much. I'll take another stab at it tomorrow.

**Comment by korteland** [comment]
@yyoncho Here's the dump you asked for - this is the full dump, all the way from starting VSCode to jumping along the "go to definition" chain I outlined.

[vscode-lsp-output.txt](https://github.com/emacs-lsp/lsp-mode/files/12436929/vscode-lsp-output.txt)

**Comment by yyoncho** [comment]
@korteland correct me if I am wrong, but VScode is using cpptools language server, not clangd?

**Comment by korteland** [comment]
You might be right? I don't know anything about VS Code unfortunately. In that case, how would I go about determining whether the issue is clangd or lsp-mode?

**Comment by yyoncho** [comment]
So, for me, the chances for issues being in lsp-mode are very low(e. g. if there is an initialization option that we miss). That is why I was skeptical that it works in vscode with clangd. VScode is using their proprietary language server and using clangd has to be configured separately. I suggest upgrading to latest version of clangd and if it still does not work go and ask in clangd discord channel or open issue in their repo. Even if the issue is in lsp-mode it will be much easier for the server team to tell us what we are missing.

**Comment by korteland** [comment]
Ah, I didn't realise VS Code had their own proprietary thing - I assumed it was clangd. Sorry if I've wasted any of your time - I'll close this for now and chase it up elsewhere.
