### ISSUE TITLE
Unknown notification messages o#/backgrounddiagnosticstatus

### ISSUE THREAD

**Issue by phuhl** [emacs-lsp/lsp-mode#4153]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Using omnisharp with this setup

```json
{
  "RoslynExtensionsOptions": {
    "enableDecompilationSupport": true,
    "enableImportCompletion": true,
    "enableAnalyzersSupport": true,
    "inlayHintsOptions": {
      "enableForParameters": true,
      "forLiteralParameters": true,
      "forIndexerParameters": true,
      "forObjectCreationParameters": true,
      "forOtherParameters": true,
      "suppressForParametersThatDifferOnlyBySuffix": false,
      "suppressForParametersThatMatchMethodIntent": false,
      "suppressForParametersThatMatchArgumentName": false,
      "enableForTypes": true,
      "forImplicitVariableTypes": false,
      "forLambdaParameterTypes": true,
      "forImplicitObjectCreation": true
    }
  }
}
```

produces lot's of warnings which pop up while analyzing. The `"enableAnalyzersSupport": true,` setting seems to be the culprit as turning it off makes the issue go away.

The warning is this:

`Warning (lsp-mode): Unknown notification: o#/backgrounddiagnosticstatus`

### Steps to reproduce

1. Copy above shown omnisharp config to `.omnisharp/omnisharp.json`
2. Open C# file
3. Turn on LSP Mode

### Expected behavior

Either the backgrounddiagnosticstatus message is used or discarded. The warning should not be shown.

### Which Language Server did you use?

lsp-mode with omnisharp

### OS

Linux

**Comment by Xioulious** [comment]
Can confirm, recently ran an update on my system. Which I think updated omnisharp to a newer version (somehow can't downgrade to an older version of omnisharp, so can't test it to be certain) and since then lsp is constantly showing that message. Pretty much making it impossible to use.

I tried changing those settings in `.omnisharp/omnisharp.json` but it didn't solve it for me.

This is on doom emacs, using the latest versions available in it (not sure if lsp-mode is using the latest version in doom emacs, but even with it unpinned it gave the same messages) with emacs 29.1.

**Comment by phuhl** [comment]
Yes, I had the issue resolved via the configfile with `"enableAnalyzersSupport": false` but since an update yesterday (?) I have the issue again. It seems that my original workaround is not effective anymore :(

**Comment by phuhl** [comment]
For those having this issue, an ugly workaround is to patch `lsp-mode.el` like this:

```diff
(lsp-defun lsp--on-notification (workspace (&JSONNotification :params :method))
  "Call the appropriate handler for NOTIFICATION."
  (-let ((client (lsp--workspace-client workspace)))
    (when (lsp--log-io-p method)
      (lsp--log-entry-new (lsp--make-log-entry method nil params 'incoming-notif)
                          lsp--cur-workspace))
    (if-let ((handler (or (gethash method (lsp--client-notification-handlers client))
                          (gethash method lsp--default-notification-handlers))))
        (funcall handler workspace params)
      (when (and method (not (string-prefix-p "$" method)))
-        (lsp-warn "Unknown notification: %s" method)))))
+        (when (neq method "o#/backgrounddiagnosticstatus")
+          (lsp-warn "Unknown notification: %s" method))))))
```

**Comment by Xioulious** [comment]
That does indeed remove the warning message, but it makes lsp-mode really slow.
Auto completion takes multiple second before it shows, even not showing all results.
So as you said, an ugly workaround that makes it usable, but not well.
Thank you for the pointer tho!
