### ISSUE TITLE
`lsp-nix` support for `nixd` language server

### ISSUE THREAD

**Issue by peterbecich** [emacs-lsp/lsp-mode#4168]
Is your feature related or already mentioned on [the wishlist](https://github.com/emacs-lsp/lsp-mode/discussions/2892)?
No

Describe your feature here.

`lsp-nix` currently supports `rnix`: https://github.com/nix-community/rnix-lsp
https://github.com/emacs-lsp/lsp-mode/blob/bab06f930a0ee52d45189986e0dd8f28eeb3b784/clients/lsp-nix.el

`nixd` is a different language server: https://github.com/nix-community/nixd

Can it also be supported? Thank you

**Comment by jcs090218** [comment]
It will take some time to implement this. Feel free to make a PR for this!

**Comment by peterbecich** [comment]
closing, https://github.com/emacs-lsp/lsp-mode/pull/4288 was merged

**Comment by jcs090218** [comment]
Oh, didn't know it was implemented already. 👍
