### ISSUE TITLE
Astro language server not showing in lsp-install-server

### ISSUE THREAD

**Issue by bustinbung** [emacs-lsp/lsp-mode#4169]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

When trying to install the Astro language server through `lsp-install-server`, `astro-ls` does not show up. According to @hlissner on the Doom Emacs discord, it's because there is no configuration in `lsp-astro.el`. ([source](https://discord.com/channels/406534637242810369/1149540628875706498/1150868146253742080))

### Steps to reproduce

+ Install `lsp-mode`
+ Run `lsp-install-server`
+ Search for `astro-ls`
+ No entry

### Expected behavior

+ `astro-ls` should show in the list of servers, as stated in the documentation page

### Which Language Server did you use?

`astro-ls`

### OS

MacOS

### Anything else?

I also got this error, but I'm not sure it's related to this issue.
`../.emacs.d/.local/straight/build-29.1/lsp-mode/lsp-mode.el: Warning: Non-symbol arguments to cl-defgeneric: (process process) [5 times]`

**Comment by hlissner** [comment]
To spare you the trouble of hunting on our Discord server, these were my observations: the client defined in clients/lsp-astro.el lacks a `:download-server-fn` property and/or a `lsp-dependency` declaration (which I assume is the bare minimum needed for a client to show up in `M-x lsp-install-server`). Yet, [lsp-mode's docs for Astro](https://emacs-lsp.github.io/lsp-mode/page/lsp-astro/) suggest astro-ls is installable via `M-x lsp-install-server`.

**Comment by ericdallo** [comment]
Yeah, @hlissner is correct, tagging latest people that worked on that support: @tian-yi @lucafanselau @pawelkobojek.
@bustinbung feel free to open PRs if you know how lsp-mode can install astro

**Comment by jacksonSingleton** [comment]
Bumping this issue. Will look into PRing an installer, but at the very least, misleading docs should be addressed

**Comment by komali2** [comment]
Something like this? https://github.com/emacs-lsp/lsp-mode/pull/4414

**Comment by jcs090218** [comment]
It seems like you got it. I am closing this feature request now.

**Comment by komali2** [comment]
My PR might have been merged prematurely. That was my first time messing under the hood with lsp mode. `astro-ls` may get stuck in an install loop now. It is on one machine for me, but not another.
