### ISSUE TITLE
Ability to select or reset project root manually

### ISSUE THREAD

**Issue by cpitclaudel** [emacs-lsp/lsp-mode#4186]
> Is your feature related or already mentioned on [the wishlist](https://github.com/emacs-lsp/lsp-mode/discussions/2892)?

Not that I can see.

> Describe your feature here.

I commonly run into issues with LSP's project root heuristics when working in languages that allow nested projects.  For example, in Scala, I have this hierarchy

```
parent/
├── build.sbt
├── exercises
│   ├── week1
│   │   ├── build.sbt
│   │   └── …
│   ├── week2
│   │   ├── build.sbt
│   │   └── …
└── labs
    ├── week1
    │   ├── build.sbt
    │   └── …
    └── week2
        ├── build.sbt
        └── …
```

`lsp-mode` already knows about `parent/` (since I've started it a few times in that directory), so when I create a new project in `exercises/week3`, it doesn't re-prompt me to import.  Instead, it starts the Scala LSP server, called Metals in `parent/`.

Unfortunately, the Metals LSP server doesn't like this at all:

- There is one `main` function per `weekN` directory, so it complains that there is more than one `main` in the project;
- There are multiple definitions of the same types in different `weekN` folders, so it prints "duplicate definition" errors (and the presence of these break completion and navigation);
- etc.

This nested folders is pretty standard in the Scala/SBT world, IIUC; it's just that, for interactive work, users are expected to start the LSP server in the "right" root folder, which in my case would be one of the `weekN` folders and not `parent/`.

Unfortunately I don't have a completely reliable recipe for this issue — there *are* cases in which Metals does the right thing even if I open multiple subprojects.  Regardless, in other editors I explicitly open a project and I don't have this issue. 

In lsp-mode, it would be very helpful to have a way either to reset the workspace root selection (re-prompt to import), or to have an option to let the presence of a hint that there is a subproject (I suppose projectile may know how to find a `.sbt` file?).

Thanks!

**Comment by yyoncho** [comment]
`M-x lsp-workspace-folders-add` and pick the nested root?

**Comment by cpitclaudel** [comment]
Yep, that seems to be what I was missing!  I'll reopen this if I run into issues.
