### ISSUE TITLE
Always return "No language server is associated with this buffer"

### ISSUE THREAD

**Issue by kuanyui** [emacs-lsp/lsp-mode#419]
Just tried lsp-mode + javascript-flow (https://github.com/emacs-lsp/lsp-javascript/blob/master/lsp-javascript-flow.el) , but it always says `No language server is associated with this buffer`.

0. Environment is Emacs 26.1 on a Linux system. I've tried `lsp-mode 4.2` and melpa latest, but both of them has the same problem.
1. I have installed `flow-language-server`, and `M-! flow-language-server` works (so `PATH` should be no problem).
2. To simplify the problem, I wrote a simple sample:
```lisp
(lsp-define-stdio-client
 lsp-js-flow "js"
 (lambda () (locate-dominating-file "." "package.json"))
 nil
 :ignore-messages '("\[INFO].*?nuclide")
 :command-fn (lambda () `("flow-language-server" "--stdio")))
```
Then `M-x lsp-js-flow-enable` in a flow JS file, but `M-x lsp-capabilities` still always returns `No language server is associated with this buffer`

**Comment by yyoncho** [comment]
Please turn on debug-on-error and retry. I believe that the flow server is not starting at all.
