### ISSUE TITLE
lsp-mode for Mojo?

### ISSUE THREAD

**Issue by adamliter** [emacs-lsp/lsp-mode#4206]
> Is your feature related or already mentioned on [the wishlist](https://github.com/emacs-lsp/lsp-mode/discussions/2892)?

No, I didn't see it there.

Is there interest or a plan to add support for [Mojo](https://www.modular.com/mojo)? If there's interest, I'm happy to draft a PR. Not super familiar with elisp or the `lsp-mode` code base, to be totally honest, but I do have this working for myself locally by just following the instructions [in the docs](https://emacs-lsp.github.io/lsp-mode/page/adding-new-language/) (thanks for the great documentation! 🎉).

**Comment by yyoncho** [comment]
Feel free to proceed with providing a PR.
