### ISSUE TITLE
Completion-at-point incompatible with Emacs versions < 28.1

### ISSUE THREAD

**Issue by mope-life** [emacs-lsp/lsp-mode#4217]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

I am using Emacs version 27.1. `Lisp error: (void-function string-lines)` is thrown whenever `company-capf` attempts to provide a completion. This is due to the use of `string-lines` in the function `lsp-completion--company-match`. The built-in function `string-lines` was not introduced until Emacs 28.1.

### Steps to reproduce

There are probably many ways to reproduce this, but this is how I did it, using Emacs version 27.1:
- Open a new `.c` file in a new project
- Initialize the `lsp-clangd` server
- Type `#inc`. After a moment, the error should be thrown

### Expected behavior

No error.

### Which Language Server did you use?

lsp-clangd

### OS

Linux

### Error callstack

```emacs-lisp
Debugger entered--Lisp error: (void-function string-lines)
  (string-lines prefix)
  (car (string-lines prefix))
  (let* ((prefix (downcase (buffer-substring-no-properties (plist-get (text-properties-at 0 candidate) 'lsp-completion-start-point) (point)))) (prefix (car (string-lines prefix))) (prefix-len (length prefix)) (prefix-pos 0) (label (downcase candidate)) (label-len (length label)) (label-pos 0) matches start) (while (and (not matches) (< prefix-pos prefix-len)) (while (and (< prefix-pos prefix-len) (< label-pos label-len)) (if (equal (aref prefix prefix-pos) (aref label label-pos)) (progn (if start nil (setq start label-pos)) (setq prefix-pos (1+ prefix-pos))) (if start (progn (setq matches (nconc matches ...)) (setq start nil)))) (setq label-pos (1+ label-pos))) (if start (progn (setq matches (nconc matches (list (cons start label-pos)))))) (if (< prefix-pos prefix-len) (progn (setq matches nil))) (if matches nil (setq prefix-pos (1+ prefix-pos)) (setq label-pos 0))) matches)
  lsp-completion--company-match(#("include \"header\"" 0 1 (face (completions-first-difference) lsp-completion-prefix "inc" lsp-completion-markers (2 #<marker (moves after insertion) at 5 in main.c>) lsp-completion-start-point 2 lsp-sort-text "40b67681include" lsp-completion-item #<hash-table equal 9/12 0x15903f6aab7d>) 1 16 (lsp-completion-prefix "inc" lsp-completion-markers (2 #<marker (moves after insertion) at 5 in main.c>) lsp-completion-start-point 2 lsp-sort-text "40b67681include" lsp-completion-item #<hash-table equal 9/12 0x15903f6aab7d>)))
  company-capf(match #("include \"header\"" 0 1 (face (completions-first-difference) lsp-completion-prefix "inc" lsp-completion-markers (2 #<marker (moves after insertion) at 5 in main.c>) lsp-completion-start-point 2 lsp-sort-text "40b67681include" lsp-completion-item #<hash-table equal 9/12 0x15903f6aab7d>) 1 16 (lsp-completion-prefix "inc" lsp-completion-markers (2 #<marker (moves after insertion) at 5 in main.c>) lsp-completion-start-point 2 lsp-sort-text "40b67681include" lsp-completion-item #<hash-table equal 9/12 0x15903f6aab7d>)))
  [Many more lines from company-mode]
```

### Anything else?

This issue was introduced with #4193:
https://github.com/emacs-lsp/lsp-mode/blame/00932b02d74f569eccc7c55cfa38b8269d535239/lsp-completion.el#L354-L358

I already wrote a quick patch for this, but I did want to double check that this was important, i.e., that the project maintainers wish to continue supporting Emacs versions < 28.1.

**Comment by yyoncho** [comment]
@jcs090218 can you check why CI hasn't caught this issue?

**Comment by mope-life** [comment]
I thought I would point out that CI does issue a warning, it just doesn't cause a failure:
https://github.com/emacs-lsp/lsp-mode/actions/runs/6516924539/job/17700928856?pr=4193#step:12:446

**Comment by jcs090218** [comment]
We can turn warnings into errors (that will cause the CI to fail), but there are so many warnings to solve now. 🤔

**Comment by yyoncho** [comment]
> We can turn warnings into errors (that will cause the CI to fail), but there are so many warnings to solve now. 🤔

We should work on keeping this green. I think that it used to be like that. Otherwise, we don't have any way to catch issues like that.
