### ISSUE TITLE
Non-interactive server installation

### ISSUE THREAD

**Issue by RedHatter** [emacs-lsp/lsp-mode#4218]
I'm new to emacs so if this is already possible please point me in the right direction.

`lsp-install-server` is great but I would like a non-interactive version. I would love to do something like the following in my `init.el`

```
(unless (lsp-installed-p 'ts-ls)
  (lsp-install-server 'ts-ls))
```

**Comment by mope-life** [comment]
@RedHatter Interactive functions can also be called non-interactively. Use `C-h f lsp-install-server` to look at the documentation:
```
lsp-install-server is an autoloaded interactive compiled Lisp function in
‘lsp-mode.el’.

(lsp-install-server UPDATE\? &optional SERVER-ID)

Interactively install or re-install server.
When prefix UPDATE? is t force installation even if the server is present.

[back]
```

So it looks like you can use the function like this: `(lsp-install-server nil 'ts-ls)`. Unfortunately it looks like that _particular_ LSP server can't be installed automatically.

**Comment by yyoncho** [comment]
`lsp-ensure-server`
