### ISSUE TITLE
cannot use gopls server

### ISSUE THREAD

**Issue by dackon** [emacs-lsp/lsp-mode#4225]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Today I upgrade lsp-mode to 20231107.1853, when I open a go file, it shows following warnings, but I don't use semgrep

```error
LSP :: The following servers support current file but do not have automatic installation: semgrep-ls gopls
You may find the installation instructions at https://emacs-lsp.github.io/lsp-mode/page/languages.
(If you have already installed the server check *lsp-log*).
```

*lsp-log*
```log
Command "semgrep lsp" is not present on the path.
```

### Steps to reproduce

1. $ cat ~/.emacs
```lisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

(require 'lsp-mode)
(add-hook 'go-mode-hook #'lsp-deferred)

;; Set up before-save hooks to format buffer and add/delete imports.
;; Make sure you don't have other gofmt/goimports hooks enabled.
(defun lsp-go-install-save-hooks ()
  (add-hook 'before-save-hook #'lsp-format-buffer t t)
  (add-hook 'before-save-hook #'lsp-organize-imports t t))
(add-hook 'go-mode-hook #'lsp-go-install-save-hooks)
```

2. Install packages
M-x package-install go-mode lsp-mode

3. Open a go file to edit 

### Expected behavior

I should be able to use gopls directly when I open go file.

### Which Language Server did you use?

gopls

### OS

MacOS

**Comment by dackon** [comment]
it was caused by this commit 6b79afa018f92aa50794737009c7e4bc36d3a9d. I reverted lsp-go.el, it works normal now.

@ibizaman

**Comment by SammyA** [comment]
Same problem here, any way to revert to previous version? i'm using melpa.

**Comment by yyoncho** [comment]
I will fix it.

**Comment by jidibinlin** [comment]
when melpa can sync this fix?

**Comment by yyoncho** [comment]
2-3 hours. YOu can do (setq  lsp-go-server-path "gopls") and it should work on your side as well without the fix.

**Comment by ibizaman** [comment]
Thank you @yyoncho. Sorry for the hiccup here

**Comment by bnsv** [comment]
I have the same issue in snap version of Emacs with latest lsp-mode and gopls installed. Actually $GOPATH and $GOBIN are already showed on the PATH when I check via `M-x getenv RET PATH RET` but the lsp-log still throws "The following servers support current file but do not have automatic installation". In the end I manage to connect to the server by manually edit ' lsp-go-server-path' variable to `string: ~/go/bin` via `M-x customize group`.

![2024-04-16-213608_1920x1080_scrot](https://github.com/emacs-lsp/lsp-mode/assets/25299811/49a4e831-e6cf-4046-a39b-2c282e77e5dd)
