### ISSUE TITLE
Angular lsp server always responses empty block

### ISSUE THREAD

**Issue by hainesc** [emacs-lsp/lsp-mode#4237]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

I have worked a few days to setup angular develop environment following the docs. It seems that the language server was started correctly but when I open an angular project, I saw nothing magic, no completion, no code correction, no go to definition,  I have worked with lsp-mode for golang where the language server is gopls and everything are smooth. So I compared them and the differences that I found in `lsp-workspace-show-log` are:
1. No `serverInfo` block but `serverOptions` in response of initialize stage, and it is empty `"serverOption": {}`. I see the [specifications](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/) it should be serverInfo. So does it mean that the implementation of  language server break the specifications so it cannot work correctly Or does it matters?
2. The response of `textDocument/codeAction` and `textDocument/codeLen` is empty when I input a typo and hover it. The angular response is `[Trace - 04:40:20 PM] Received response 'textDocument/codeLens - (5)' in 2511ms.
Result: null [Trace - 04:40:20 PM] Received response 'textDocument/codeAction - (6)' in 2264ms.
Result: []`
The gopls response is `[Trace - 10:07:38 PM] Received response 'textDocument/codeAction - (218)' in 12ms.
Result: [
  {
    "title": "undeclared name: varWrong",
    "kind": "quickfix",
    "diagnostics": [
      {
        "range": {
          "start": {
            "line": 38,
            "character": 29
          },
          "end": {
            "line": 38,
            "character": 38
          }
        },
        "severity": 1,
        "code": "UndeclaredName",
        "codeDescription": {
          "href": "https://pkg.go.dev/golang.org/x/tools/internal/typesinternal?utm_source=gopls#UndeclaredName"
        },
        "source": "compiler",
        "message": "undeclared name: varWrong",
        "tags": [
          1
        ]
      }
    ],
    "edit": {},
    "command": {
      "title": "undeclared name: varWrong",
      "command": "gopls.apply_fix",
      "arguments": [
        {
          "Fix": "undeclared_name",
          "URI": "file:///Users/workspace/go/src/example/cmd/example.go",
          "Range": {
            "start": {
              "line": 38,
              "character": 29
            },
            "end": {
              "line": 38,
              "character": 38
            }
          }
        }
      ]
    }
  }
]
`

I don't know why the language server worked incorrectly, and I have not found any docs. So I need help here. Thanks very much!

### Steps to reproduce

1. Install or Update angular lsp package by `npm install -g @angular/language-service@next typescript @angular/language-server`
2. (setq lsp-clients-angular-language-server-command
  '("node"
    "/usr/lib/node_modules/@angular/language-server"
    "--ngProbeLocations"
    "/usr/lib/node_modules"
    "--tsProbeLocations"
    "/usr/lib/node_modules"
    "--stdio")) in your emacs config file, make sure that the path is right and the `node` command is present in your $PATH.
3. New an angular project by `ng new example`
4. Open the main.ts and change the second `err` to `errWrong` and hover it.
5. M-x lsp-workspace-show-log

### Expected behavior

The language server report the misspelled word.

### Which Language Server did you use?

angular-ls

### OS

MacOS

**Comment by hainesc** [comment]
Version Info:
Emacs: Version 29.1 (9.0)
lsp-mode: 20231108.1221
@angular/language-server: 17.0.2

**Comment by yyoncho** [comment]
I think that angular language server is supposed to work side by side with ts-ls server and you get only a small set of functionality via the angular server (e. g. completion in templates)

**Comment by hainesc** [comment]
> I think that angular language server is supposed to work side by side with ts-ls server and you get only a small set of functionality via the angular server (e. g. completion in templates)

Thanks for your reply, I will have a try.

**Comment by hainesc** [comment]
It works, thanks @yyoncho. I have never worked with two language server, it is so cool.
