### ISSUE TITLE
Test if emacs was built with json support.

### ISSUE THREAD

**Issue by syamajala** [emacs-lsp/lsp-mode#4251]
lsp-mode should test if emacs was built with json support and throw an error if it wasn't. My most recent install of emacs was not built with json support and it took me some time to figure out why lsp-mode wasn't working. 

The function `(json-available-p)` should tell you.

**Comment by jcs090218** [comment]
This doesn't look right. Can you paste the backtrace here? Thanks!

**Comment by yyoncho** [comment]
Once you switch emacs versions you are supposed to recompile lsp-mode because we check if json is available compile time to avoid the runtime check.
