### ISSUE TITLE
Add `pylyzer` support

### ISSUE THREAD

**Issue by rassie** [emacs-lsp/lsp-mode#4265]
There is a new LSP server for Python written in Rust, [pylyzer](https://github.com/mtshiba/pylyzer). Quite young and quite rough  around the edges, but maybe it has got a chance in case `ruff` doesn't move into type-checking space too.

**Comment by jcs090218** [comment]
Looks interesting! Thanks!

**Comment by jcs090218** [comment]
cc @seagle0128 You might be interested in this. 🤔

**Comment by seagle0128** [comment]
Interesting! Let me find some time to investigate.

**Comment by jcs090218** [comment]
> Interesting! Let me find some time to investigate.

By seeing lsp-python-ms and lsp-pyright. Do you think this should be a separate package? 🤔

**Comment by seagle0128** [comment]
I think so. They have different options as I see.

**Comment by seagle0128** [comment]
I implement a simple client. `pylyzer` looks pretty young, and there is no additonal options. Please try [lsp-pylyzer](https://github.com/seagle0128/lsp-pylyzer).

**Comment by jcs090218** [comment]
> I implement a simple client. `pylyzer` looks pretty young, and there is no additonal options. Please try [lsp-pylyzer](https://github.com/seagle0128/lsp-pylyzer). If everyone think it's good, I will transfer to `lsp-mode` project and publish to melpa.

Awesome work, as always! Feel free to transfer the repo at any time. :)

**Comment by jcs090218** [comment]
Hmm... we have two options:

1. Transfer it to me, then I will transfer it to the org.
2. I'll invite you to the org, and you should able to transfer it

**Comment by seagle0128** [comment]
@jcs090218 It's your call. Both are fine.

**Comment by jcs090218** [comment]
I've invited you to the org! You should be able to transfer the repo now. :)

**Comment by seagle0128** [comment]
Okay. Done!

**Comment by jcs090218** [comment]
> Okay. Done!

Nice! Thank you! :D
