### ISSUE TITLE
tabs vs spaces :(

### ISSUE THREAD

**Issue by alanz** [emacs-lsp/lsp-mode#43]
The checked out files have tabs in them.

Would it be possible to set the save functionality on your editor to make them spaces when it saves?

**Comment by vibhavp** [comment]
heh, do you think we should use [EditorConfig](http://editorconfig.org/)?

**Comment by alanz** [comment]
Not sure if emacs honours it.

But I guess the files will get fixed as they are committed.

**Comment by rski** [comment]
You have to setup your emacs to honour it iirc. ,dir-locals.el could be a solution instead, since presumably all people working on emacs-lsp would use emacs
