### ISSUE TITLE
Company with lsp-mode doesn't complete

### ISSUE THREAD

**Issue by Gustavohenribra** [emacs-lsp/lsp-mode#4310]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Everytime when i change from a buffer to other, the company stop working, the lsp charges normally but the company stop working and everytime when i press tab, it says that "No completion found"

### Steps to reproduce

My config:
;; LSP Setup
(defun efs/lsp-mode-setup ()
(setq lsp-headerline-breadcrumb-segments '(path-up-to-project file symbols))
(lsp-headerline-breadcrumb-mode))

(use-package lsp-mode
:ensure t
:commands (lsp lsp-deferred)
:hook (lsp-mode . efs/lsp-mode-setup)
:init
(setq lsp-keymap-prefix "C-c l")
:config
(lsp-enable-which-key-integration t))

(use-package lsp-ui
:hook (lsp-mode . lsp-ui-mode)
:custom
(lsp-ui-doc-position 'bottom))

(use-package lsp-treemacs
:after lsp)

(use-package lsp-ivy)

;; LSP Restart server
(defun efs/restart-lsp-server ()
(interactive)
(dolist (workspace (lsp-workspaces))
(lsp-workspace-restart workspace)))

(global-set-key (kbd "C-c l R") 'efs/restart-lsp-server)

(use-package typescript-mode
:mode "\.ts\'"
:hook (typescript-mode . lsp-deferred)
:config
(setq typescript-indent-level 2))

(use-package company
:after lsp-mode
:hook (lsp-mode . company-mode)
:bind (:map company-active-map
("" . company-complete))
(:map lsp-mode-map
("" . company-indent-or-complete-common))
:custom
(company-minimum-prefix-length 1)
(company-idle-delay 0.0))

(add-hook 'after-init-hook 'global-company-mode)

(use-package company-box
:hook (company-mode . company-box-mode))

### Expected behavior

Use tab and search for completion on every file

### Which Language Server did you use?

Typescript

### OS

Windows

### Error callstack

```emacs-lisp
Output of the command M-x company-diag
Emacs 29.1 (x86_64-w64-mingw32) of 2023-08-02 on AVALON
Company 0.10.2

company-backends: (company-bbdb company-semantic company-cmake company-capf company-clang company-files
(company-dabbrev-code company-gtags company-etags company-keywords)
company-oddmuse company-dabbrev)

Used backend: company-capf
Value of c-a-p-f: (elisp-completion-at-point t)
Major mode: emacs-lisp-mode
Prefix: "lsp-mode-map"
Completions:
#("lsp-mode-map" 0 12 (face (completions-common-part)))
```

### Anything else?

Some logs from lsp-log:
Command "deno lsp" is not present on the path.
Command "typescript-language-server --stdio" is present on the path.
Command "deno lsp" is not present on the path.
Command "typescript-language-server --stdio" is present on the path.
Found the following clients for c:/Users/Gusta/Downloads/Exa_APP/src/components/Wizard/index.tsx: (server-id ts-ls, priority -2)
The following clients were selected based on priority: (server-id ts-ls, priority -2)
Using Typescript version (user-setting) 4.9.5 from path "c:\Users\Gusta\Downloads\Exa_APP\node_modules\typescript\lib\tsserver.js"
Cancelling textDocument/codeLens(23) in hook after-change-functions
Cancelling textDocument/codeAction(21) in hook after-change-functions
Cancelling textDocument/codeAction(28) in hook after-change-functions
Cancelling textDocument/codeAction(34) in hook after-change-functions
Cancelling textDocument/codeLens(67) in hook after-change-functions
Cancelling textDocument/codeAction(65) in hook after-change-functions
Command "deno lsp" is not present on the path.
Command "typescript-language-server --stdio" is present on the path.
Command "deno lsp" is not present on the path.
Command "typescript-language-server --stdio" is present on the path.
Found the following clients for c:/Users/Gusta/Downloads/Exa_APP/src/components/Wizard/WizardProfessionalForm/ProfessionalForm.tsx: (server-id ts-ls, priority -2)
The following clients were selected based on priority: (server-id ts-ls, priority -2)
Cancelling textDocument/codeAction(179) in hook after-change-functions
Cancelling textDocument/codeAction(213) in hook after-change-functions
Cancelling textDocument/codeAction(235) in hook after-change-functions
Cancelling textDocument/codeAction(270) in hook after-change-functions
Cancelling textDocument/codeAction(276) in hook after-change-functions
Cancelling textDocument/hover(321) in hook after-change-functions
Cancelling textDocument/documentHighlight(320) in hook after-change-functions
Cancelling textDocument/codeAction(319) in hook after-change-functions
Cancelling textDocument/codeAction(324) in hook after-change-functions
Cancelling textDocument/codeAction(327) in hook post-command-hook
Cancelling textDocument/codeAction(344) in hook post-command-hook
Cancelling textDocument/codeAction(345) in hook post-command-hook
Cancelling textDocument/codeAction(358) in hook post-command-hook

Messages:

No completion found
Company: An error occurred in auto-begin
Company: backend company-capf error "Timeout while waiting for response. Method: textDocument/completion" with args (candidates Spe)

**Comment by Gustavohenribra** [comment]
Error update:
It just doesn't work on one file on my frontend, in the API works perfectly, the thing is, when i go to this file and went back to other file that works fine, it stop working, how can i solve this ? Not ironically is the same file that is preventing me from building the application

**Comment by yyoncho** [comment]
Is it possible to provide a minimalistic reproducer of this issue or share your project?

**Comment by yyoncho** [comment]
Based on this description it sounds more like something on the server?

**Comment by Gustavohenribra** [comment]
Maybe, i'm gona close this issue because i don't think it is the lsp problem
