### ISSUE TITLE
Add support for YANG LSP

### ISSUE THREAD

**Issue by esmasth** [emacs-lsp/lsp-mode#4355]
Is your feature related or already mentioned on [the wishlist](https://github.com/emacs-lsp/lsp-mode/discussions/2892)? No.

TypeFox/yang-lsp has support for YANG language, and can be integrated into emacs via this project.

**Comment by esmasth** [comment]
I have started working on this issue, and have draft ready soon.

**Comment by esmasth** [comment]
@jcs090218 can this be assigned to me now?

**Comment by jcs090218** [comment]
Completed in #4390.
