### ISSUE TITLE
[lsp-volar] Does not seem to work with new v2 vue-language-server

### ISSUE THREAD

**Issue by RedChops** [emacs-lsp/lsp-mode#4361]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [x] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

It would seem like vue-language-server v2 has changed significantly and now no diagnostics are being reported on any source files, .js, .vue, or .ts. All requests to the language server for any file just return an empty array or null. This may have to do with their decision to split in to some kind of hybrid mode.

It seems like the CSS and HTML sections of a SFC will get information just fine, except any Vue components referenced in the HTML section have no information seemingly because the language server can't seem to recognize the components themselves.

### Steps to reproduce

Just creating a new Vue project is enough: `vue create test`

### Expected behavior

Code highlighting, completion, etc should work like normal

### Which Language Server did you use?

lsp-volar

### OS

MacOS

### Anything else?

Downgrading vue-language-server to a sane version like 1.8 works as expected. Their README suggests that their new version of the language server is supported by lsp-volar, but that must be outdated

**Comment by scandar** [comment]
I did some digging because I was struggling with this problem for a while and when I looked at `ls-workspace-show-log` the server responds back with empty response all the time. 

```
[Trace - 01:33:44 PM] Sending request 'textDocument/codeAction - (332)'.
Params: {
  "textDocument": {
    "uri": "[REDACTED]"
  },
  "range": {
    "start": {
      "line": 47,
      "character": 49
    },
    "end": {
      "line": 47,
      "character": 49
    }
  },
  "context": {
    "diagnostics": []
  }
}


[Trace - 01:33:44 PM] Sending request 'textDocument/documentLink - (333)'.
Params: {
  "textDocument": {
    "uri": "[REDACTED]"
  }
}


[Trace - 01:33:44 PM] Sending request 'textDocument/documentHighlight - (334)'.
Params: {
  "textDocument": {
    "uri": "[REDACTED]"
  },
  "position": {
    "line": 47,
    "character": 49
  }
}


[Trace - 01:33:44 PM] Received response 'textDocument/codeAction - (332)' in 4ms.
Result: []


[Trace - 01:33:44 PM] Received response 'textDocument/documentLink - (333)' in 4ms.
Result: []


[Trace - 01:33:44 PM] Received response 'textDocument/documentHighlight - (334)' in 4ms.
Result: []
```
