### ISSUE TITLE
`csharp-ls` can not be found

### ISSUE THREAD

**Issue by Hi-Angel** [emacs-lsp/lsp-mode#4365]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

I installed `csharp-ls` and it is in `$PATH`. However if I open a `.cs` file and execute `lsp`, I get a `Unable to find installed server supporting this file` error. It suggests to install `omnisharp` or `csharp-ls`, but the latter is already installed.

lsp-servers for C, python and bash work fine, so it is specific to just this one.

### Steps to reproduce

1. Install `csharp-ls`
2. Start emacs and execute `lsp-start-plain`
3. Open a file `test.cs` that has the following content:
    ```
    namespace HelloWorld
    {
        class Hello {
            static void Main(string[] args)
            {
                System.Console.WriteLine("Hello World!");
            }
        }
    }
    ```
4. Execute in Emacs `lsp`

### Expected behavior

`csharp-ls` gets started

### Which Language Server did you use?

`csharp-ls`

### OS

Linux

### Error callstack

```emacs-lisp
Command "semgrep lsp" is not present on the path.
```

**Comment by Hi-Angel** [comment]
Ha! I couldn't figure out by code of lsp-mode, it's quite complicated. But I executed a [`bpftrace` to print new processes](https://unix.stackexchange.com/questions/260162/how-to-track-newly-created-processes-in-linux/606831#606831) while executing a `lsp` and found this:

```
pid: 40505, comm: emacs, args: /bin/zsh -c dotnet tool list -g
pid: 40505, comm: zsh, args: dotnet tool list -g
```

so lsp is starting this tool. Apparently it assumes the tool will print if `csharp-ls` exists, but that doesn't happen, its output is empty. Even though `csharp-ls` does exist 😊 Looking at `lsp-csharp.el` it seems like the test for just checking if `csharp-ls` binary is present is missing. So that needs to be fixed.

**Comment by psibi** [comment]
What is the output of `which csharp-ls` ?

And can you check the variable `exec-path` and see the directory where `csharp-ls` is present exists in this variable.

**Comment by psibi** [comment]
Ah, I missed that comment. I see what you mean.

**Comment by Hi-Angel** [comment]
It seems that there is actually a code that supposed to search it by name, it's in the function `lsp-csharp--cls-make-launch-cmd`. However adding a `(print "here")` inside it and evaluating the function and then trying to run `lsp` on C# file does not show a print "hello" in the \*Messages\* buffer. So for some reason this function simply does not get run.

**Comment by Hi-Angel** [comment]
So, I am not good in `lsp-mode` internals, but I would seem to me there is a bug on [this line](https://github.com/emacs-lsp/lsp-mode/blob/be36d16860087bd9722ced6ba52cf0ff5d5c2c72/clients/lsp-csharp.el#L461-L462).

It would seem that the original author assumed that function `(lsp-stdio-connection)` tests its args in order to find executable. But it works a bit different way. All in all, the first function that is actually supposed to return `/usr/bin/csharp-ls` does not get run.

At least that's my interpretation of the situation.

**Comment by Hi-Angel** [comment]
The regression was introduced in 9b3a9215807af0727b514e8c7cf440bcc0bdad44

CC: @razzmatazz the author of the commit
