### ISSUE TITLE
lsp-mode tells to language server about a file that still dont exists on disk

### ISSUE THREAD

**Issue by shackra** [emacs-lsp/lsp-mode#439]
I've notice that when visiting a new file the language server will take issue with the fact that the file still not exists on disk, cause a lot of errors messages on Emacs:

```
Error from the Language Server: ENOENT: no such file or directory, open ’/home/jorge/proyectos/udemy-maximilian/curso-react/react-complete-guide/src/Person/person.jsx’ (Unknown Error Code) [44 times]
```

some sort of precautions should be considered when lsp-mode talks with the language server to avoid such bad user experience.

**Comment by yyoncho** [comment]
As per LSP spec this is bug in the server

> The document open notification is sent from the client to the server to signal newly opened text documents. The document’s truth is now managed by the client and the server must not try to read the document’s truth using the document’s uri. Open in this sense means it is managed by the client.

**Comment by shackra** [comment]
so it should bot be fixed here or anything, right?

**Comment by yyoncho** [comment]
I think so.

**Comment by shackra** [comment]
Then it is not a bug
