### ISSUE TITLE
Unwanted Automatic Start of Common Lisp's LSP

### ISSUE THREAD

**Issue by linuxmetel** [emacs-lsp/lsp-mode#4391]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Although I do not want use LSP in lisp-mode (I am a [slime](https://github.com/slime/slime) user) and I have not made a such setting, LSP ([alive](https://github.com/nobody-famous/alive)) automatically starts each time I open a `.lisp` file after this [commit](https://github.com/emacs-lsp/lsp-mode/commit/193c714c1d74afeee154b255fbe85025cc4ee690).

`lsp-lisp.el` directly adds LSP to `lisp-mode-hook` in the auto-load process. I looked at some other lsp-clients like [lsp-clangd.el](https://github.com/emacs-lsp/lsp-mode/blob/193c714c1d74afeee154b255fbe85025cc4ee690/clients/lsp-clangd.el) and [lsp-pyls.el](https://github.com/emacs-lsp/lsp-mode/blob/193c714c1d74afeee154b255fbe85025cc4ee690/clients/lsp-pyls.el), and I found they not edit or add something to hooks. Thus, I believe that it is a strange behavior.
https://github.com/emacs-lsp/lsp-mode/blob/193c714c1d74afeee154b255fbe85025cc4ee690/clients/lsp-lisp.el#L48-L64

### Steps to reproduce

Open any `.lisp` file.

### Expected behavior

not edit hooks

### Which Language Server did you use?

(omit)

### OS

Linux

### Anything else?

This behavior is very annoying me.

**Comment by linuxmetel** [comment]
@https://github.com/linuxmetel/lsp-mode
`lsp-lisp-alive-start-ls` seems to do something required by using alive, so I think just removing them may break it. Could you explain your intention or fix this strange behavior?

**Comment by linuxmetel** [comment]
@jcs090218
`lsp-lisp-alive-start-ls` seems to do something required by using alive, so I think just removing them may break it. Could you explain your intention or fix this strange behavior?

**Comment by jcs090218** [comment]
> @jcs090218
lsp-lisp-alive-start-ls seems to do something required by using alive, so I think just removing them may break it. Could you explain your intention or fix this strange behavior?

Sorry about this. The intention was to start the language server when the file was opened. 🤔
