### ISSUE TITLE
lsp-cucumber.el compilation warnings

### ISSUE THREAD

**Issue by yetanotherboringusername** [emacs-lsp/lsp-mode#4410]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

There are compilation warnings after installing lsp-mode from MELPA

```
Warning (comp): lsp-cucumber.el:63:26: Warning: the function ‘lsp-package-ensure’ is not known to be defined.
Warning (comp): lsp-cucumber.el:58:20: Warning: the function ‘lsp-stdio-connection’ is not known to be defined.
Warning (comp): lsp-cucumber.el:57:3: Warning: the function ‘make-lsp-client’ is not known to be defined.
Warning (comp): lsp-cucumber.el:56:2: Warning: the function ‘lsp-register-client’ is not known to be defined.
Warning (comp): lsp-cucumber.el:51:2: Warning: the function ‘lsp-dependency’ is not known to be defined.
Warning (comp): lsp-cucumber.el:49:14: Warning: the function ‘lsp-package-path’ is not known to be defined.
```

### Steps to reproduce

1. Install/upgrade lsp-mode from MELPA
2. There are compilation warnings

### Expected behavior

1. Install/upgrade lsp-mode from MELPA
2. There are no compilation warnings

### Which Language Server did you use?

lsp-ccls

### OS

Linux

**Comment by jcs090218** [comment]
Fixed in #4411.
