### ISSUE TITLE
Create a new tag.

### ISSUE THREAD

**Issue by apoorv569** [emacs-lsp/lsp-mode#4415]
Please create a new `release/tag` as the last tag `8.0.0` is from a 2+ year ago.

Distributions like `GNU Guix` use `tag/version` for updating packages and because its now outdated on `GNU Guix`, `typescript-language-server` is not starting, I'm getting this error,

```
typescript error: unknown option '--tsserver-path'
```

which seems to be fixed with this PR, https://github.com/emacs-lsp/lsp-mode/pull/4202 which was merged last year.

Please create a new tag, so distributions like `GNU Guix` can update the package.

**Comment by ericdallo** [comment]
We should do that c/c @jcs090218 @yyoncho

**Comment by jcs090218** [comment]
Sounds good to me. 👍

**Comment by yyoncho** [comment]
@jcs090218 do you want to take care of this?

**Comment by jcs090218** [comment]
I can take care of this. :)

**Comment by jcs090218** [comment]
Latest release in https://github.com/emacs-lsp/lsp-mode/releases/tag/9.0.0. 🥳

**Comment by yyoncho** [comment]
We need to tag a new version for all projects in the repo. Otherwise stable repo will have new lsp-mode and old version of the other packges.

**Comment by jcs090218** [comment]
> We need to tag a new version for all projects in the repo. Otherwise stable repo will have new lsp-mode and old version of the other packges.

Done.👍  Let me know if I missed anything else! ;)

**Comment by ericdallo** [comment]
Thanks @jcs090218 !
