### ISSUE TITLE
Completions disappear after dot + symbol

### ISSUE THREAD

**Issue by Hi-Angel** [emacs-lsp/lsp-mode#4419]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

`lsp-mode` treats `.` specially for many languages, as in, it provides completions immediately even though `company-minimum-prefix-length` isn't satisfied. Which makes sense of course. Unfortunately, `lsp-mode` loses completion after typing out the next symbol, instead of reducing them to ones that start with the symbol.

So e.g. `foo.` pops up completions, but `foo.c` kills the pop up even if there are candidates.

Also asked as a question here: https://emacs.stackexchange.com/questions/80977/prevent-lsp-company-from-losing-completion-after-dot-symbol

Side note: `elgot`, the competitor mode, handles that correctly.

### Steps to reproduce

1. Create `/tmp/.emacs` as follows:
    ```lisp
    (package-initialize)
    (use-package company)
    (use-package lsp)
    ```

2. Start emacs as `emacs -Q -l /tmp/.emacs test.py`
3. Execute <kbd>M</kbd>-<kbd>x</kbd> <kbd>lsp</kbd>
3. Type `"".`

    A completion should appear

4. Type `c` to reduce completions to ones starting with that letter

### Expected behavior

Completions get reduced to ones starting with `c`, i.e. `capitalize()`, `casefold()`, etc.

### Which Language Server did you use?

`lsp-python`, `lsp-go`, `clangd`.

### OS

Linux

**Comment by jcs090218** [comment]
I'm using my own [company-fuzzy](https://www.github.com/jcs-elpa/company-fuzzy), so I don't have this issue. Let me ping one of the maintainers.

cc @kiennq
