### ISSUE TITLE
Sexp-identification in Python is arguably broken - at the least I'd like to turn it off

### ISSUE THREAD

**Issue by WJCFerguson** [emacs-lsp/lsp-mode#442]
`lsp-mode` with Python seems to transform Emacs's idea of sexps, in a way I think is incorrect, or at least undesirable.  I use this all the time, e.g. for `forward-sexp`/`backward-sexp` (`C-M-f` and `C-M-b`) and rely on the old behavior.

Old/typical behavior: cursor at `(` of `call_function(`, `forward-sexp` takes you over the parens to the end of the line, and `backward-sexp` does the reverse, back where you started.  With `lsp-mode` (and `lsp-python`), they're no longer symmetrical and back from the end of the parens takes you to before `else:` (and then behavior becomes symmetrical from there).

``` python
if condition:
    do_something()
else:
    call_function(arg1, arg2, arg3)
```

I can see how, because of (stupid) semantic whitespace, the end of that line is the end multiple sexps. But given Emacs has to choose one, I think the inner-most makes sense, while it seems to be chosing the outermost.

I'm assume this is happening because of the syntax data that the LSP provides, and how it's used in Emacs.  If you disagree with me and think it's correct, then could it become an _option_ to use the inner-most sexp to retain the old-school behavior - perhaps even to disable the lsp informing the Emacs syntactic model?  If nobody can get to that, then with some pointers on where to look I might be able to have a go.

Thanks!

**Comment by yyoncho** [comment]
> I'm assume this is happening because of the syntax data that the LSP provides, and how it's used in Emacs. 

At this point, no syntax related data is transferred from the LSP server to the LSP client.

**Comment by WJCFerguson** [comment]
So does this not happen for other people?  For me, python-mode sees sexps one way, then if lsp-mode is enabled, it sees them differently.  I shouldn't have speculated about the why.

**Comment by WJCFerguson** [comment]
Of course.  But lsp-mode changes the sexp handling.

**Comment by WJCFerguson** [comment]
Never mind - it doesn't.  It seems to be that loading `elpy` actually changes it to what I expected, and lsp-mode doesn't change anything.  Never mind, sorry.

**Comment by WJCFerguson** [comment]
In case anyone finds their way here in a search, a summary of the issue is here: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=13642.  It seems `elpy` 'fixed' it (at least for my perspective).  Nothing to do with lsp-mode.
