### ISSUE TITLE
No tool tips in the mode-line when lsp-mode is enabled

### ISSUE THREAD

**Issue by benleis1** [emacs-lsp/lsp-mode#4433]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Lsp mode seems to be surpressing the tooltips for the mode-line segments.

I can verify the help-info attributes are present but they don't show up when the mouse hovers. Switching lsp off and they work again. 

### Steps to reproduce

Tytn lsp-mode on for a file and put mouse over a mode-line segment that b should have a tool top like buffer name. Verified for a Java and python file so it doesn't seem language specific 

### Expected behavior

Tooltips should work like normal. 

### Which Language Server did you use?

Python and java

### OS

MacOS

**Comment by jcs090218** [comment]
Fixed in https://github.com/emacs-lsp/lsp-ui/pull/772.
