### ISSUE TITLE
Volar/Vue: how to get autocompletions in javascript, HTML & CSS in vue files?

### ISSUE THREAD

**Issue by pedroprieto** [emacs-lsp/lsp-mode#4446]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

I am unable to get completions in Vue files both in HTML/CSS sections (emmet) and `<script>` sections. It seems that when I get one working, the other stops.

I have tried both `eglot` and `lsp-mode`. In `eglot`, I am able to get emmet completions from vue language tools, but no javascript (maybe because `eglot` does not support multiple servers?); in `lsp-mode`, I get javascript working, including embedded javascript in Vue template section, but no emmet completions:

![imagen](https://github.com/emacs-lsp/lsp-mode/assets/7632447/afb7e478-4034-47e0-b333-1aa144dc6ac5)

![imagen](https://github.com/emacs-lsp/lsp-mode/assets/7632447/8e8d8e4b-c079-4872-95d9-fe924a8b9ccb)

I have tried with multiple major modes: `vue-mode`, `tree-sitter` and `web-mode`, with no luck.

I suspect that it is related to how those modes tell the lsp server its `languageid`, but I am not sure. Is there any kind of config that I am missing?

### Steps to reproduce

Just open a `.vue` file and run `lsp-mode`.

### Expected behavior

Emacs should show emmet completions in `<template>` and `<style>` sections inside `.vue` files.

### Which Language Server did you use?

lsp-volar

### OS

Linux

**Comment by sdvcrx** [comment]
Please try:

```elisp
(setq lsp-vetur-emmet "inMarkupAndStylesheetFilesOnly")
```

`lsp-vetur` disabled Emmet suggestions by default: 
- https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-vetur.el#L258-L265 
- https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-vetur.el#L297

**Comment by pedroprieto** [comment]
Ah, ok. I will try it. Thanks!!
