### ISSUE TITLE
Extensions / rust diagnostics

### ISSUE THREAD

**Issue by alanz** [emacs-lsp/lsp-mode#45]
I notice `rustls` uses custom diagnostics.

https://github.com/rust-lang-nursery/rls/blob/88fc39bd654c536b4f8f1cd1fc8245706f0284ec/contributing.md#extensions-to-the-language-server-protocol

"
The RLS uses some custom extensions to the Language Server Protocol. Currently
these are all sent from the RLS to an LSP client and are only used to improve
the user experience by showing progress indicators.

* `rustDocument/diagnosticsBegin`: notification, no arguments. Sent before a
  build starts and before any diagnostics from a build are sent.
* `rustDocument/diagnosticsEnd`: notification, no arguments. Sent when a build
  is complete (successfully or not, or even skipped) and all post-build analysis
  by the RLS is complete.
"

See also https://github.com/Microsoft/language-server-protocol/issues/70

**Comment by vibhavp** [comment]
I'll add a notification handler for this, thanks.
