### ISSUE TITLE
Lines not correct after expanding snippet

### ISSUE THREAD

**Issue by maggo007** [emacs-lsp/lsp-mode#450]
I am trying to use yasnippets in c++ mode with ccls as the server. Whenever I expand a snippet that adds lines highlighting isn't correct anymore.

Before inserting the snippet:
![screenshot_2018-10-23_15-32-56](https://user-images.githubusercontent.com/44403945/47365662-4eeb6900-d6dc-11e8-940d-424faed87618.png)

I inserted the "if-snippet" and expanded it:
![expand](https://user-images.githubusercontent.com/44403945/47365713-6de9fb00-d6dc-11e8-8cfb-24e5c8ec978b.png)

After correcting the condition error it stays on the last char after the bracket.
![lastchar](https://user-images.githubusercontent.com/44403945/47365750-83f7bb80-d6dc-11e8-8717-4816ff7d71c6.png)

When trying to highlight a symbol those tow expanded lines are added. logSDLError should be highlighted
![lines](https://user-images.githubusercontent.com/44403945/47365846-b43f5a00-d6dc-11e8-9e0c-c7b3bd9ba1fa.png)

It fixes itslf when i use lsp-restart-workspace.
![workspace_restart](https://user-images.githubusercontent.com/44403945/47365928-e650bc00-d6dc-11e8-8320-233301a47b88.png)

**Comment by yyoncho** [comment]
@MaskRay looks like ccls issue?

**Comment by MaskRay** [comment]
Thanks for the detailed screenshots.

> I inserted the "if-snippet" and expanded it:

The buffer content in lsp-mode's view may mismatch that of ccls's.

Also, if you use `shell-command` or `shell-command-on-region` to insert new text, the change will not be sent to the language server.

> When trying to highlight a symbol those tow expanded lines are added. logSDLError should be highlighted

ccls responds to `textDocument/hover` `textDocument/documentHighlight` resquests with its indexed version (`textDocument/didOpen` `textDocument/didSave`). It is unware of the unsaved changes. This may be a deficiency but it has other merits: lower CPU cycles, lower latency (compared with parsing/traversing the AST for each such request)

**Comment by maggo007** [comment]
Thanks for the detailed explanation. For now I solve this problem by restarting the workspace with a local hook in yas. There is probably a more elegant solution but it works for me at the moment.

`(add-hook 'c++-mode-hook
          (lambda ()
            (add-hook 'yas-after-exit-snippet-hook 'lsp-restart-workspace nil t)))`

**Comment by MaskRay** [comment]
@maggo007 I guess it does not need to be so complicated (`lsp-restart-workspace` harms performance a lot because ccls needs to load cache for all indexed files in the project). Some recent versions of yasnippet are known to be incompatible but the latest one should be good.

To be honest I don't use standalone yasnippet features, but company-lsp also uses yasnippet to provide completion and it works fine.

**Comment by yyoncho** [comment]
From what I can understand there is nothing to be fix on lsp-mode side. Please reopen if you disagree.
