### ISSUE TITLE
use lsp-install-server to install C# (csharp-roslyn) failed on mac os 14.5, M3 Pro chip

### ISSUE THREAD

**Issue by sandao** [emacs-lsp/lsp-mode#4520]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Install this language server with M-x lsp-install-server "RET" csharp-roslyn "RET" and got error:
LSP :: Server csharp-roslyn install process failed with the following error message: Unsupported platform: darwin (aarch64-apple-darwin23.5.0).

### Steps to reproduce

on mac os 14.5, M3 Pro chip;
emacs 29.4;
use cmd M-x lsp-install-server "RET" csharp-roslyn "RET";

### Expected behavior

install csharp-roslyn success；

### Which Language Server did you use?

csharp-roslyn

### OS

MacOS

**Comment by kiennq** [comment]
Probably resolve with #4558 as well

**Comment by GroundCombo** [comment]
I had this problem and it was caused by `lsp-roslyn--get-rid` misinterpreting `system-configuration`; it catches the 64 in aarch64 and returns osx-x64. Overriding lsp-roslyn--get-rid to return osx-arm64 fixed it.
