### ISSUE TITLE
Code completion not working

### ISSUE THREAD

**Issue by chernikoff** [emacs-lsp/lsp-mode#457]
After last update from melpa, code completion stopped working.
In *Messages* I get:
lsp--on-self-insert: Symbol’s function definition is void: ch

As I understand it, the problem came along with the commit b3036a7e

Host: Ubuntu 14.04, Emacs 25.3.2, lsp backend cquery

**Comment by yyoncho** [comment]
@MaskRay when-let* is not available in emacs 25.3.

**Comment by chernikoff** [comment]
I updated to 26.1. Error in *Messages* was gone, but autocompletion continues to not work :(

**Comment by yyoncho** [comment]
@chernikoff can you turn on lsp-print-io to t and inspect whether the completion requests are sent. Also, make sure that `company-backends` contain the proper backends(lsp-ui), company-mode is on, etc. Also, run `company-diag` to check what is the current completion status.

**Comment by chernikoff** [comment]
In company-diag shows that the used backend is company-lsp. Minimal completion variants shows in popup (standard types and macros).
Now noticed that the goto functionality also broke.

**Comment by yyoncho** [comment]
Looks like a `cquery` configuration problem. Can you inspect the *Messages* buffer after setting `lsp-print-io` to t? You should look for `textDocument/completion` messages.

**Comment by chernikoff** [comment]
I enabled lsp-print-io and problem possible in cquery... 
In *Messages* I always on all requests gets nullable result.
I'll try to roll back cquery...
Thanks you.

**Comment by MaskRay** [comment]
Shall we just define the two macros if `(version< emacs-version "26")

```
(defmacro if-let* (varlist then &rest else)
  "Bind variables according to VARLIST and eval THEN or ELSE.
This is like `if-let' but doesn't handle a VARLIST of the form
\(SYMBOL SOMETHING) specially."
  (declare (indent 2)
           (debug ((&rest [&or symbolp (symbolp form) (form)])
                   form body)))
  (if varlist
      `(let* ,(setq varlist (internal--build-bindings varlist))
         (if ,(caar (last varlist))
             ,then
           ,@else))
    `(let* () ,then)))

(defmacro when-let* (varlist &rest body)
  "Bind variables according to VARLIST and conditionally eval BODY.
This is like `when-let' but doesn't handle a VARLIST of the form
\(SYMBOL SOMETHING) specially."
  (declare (indent 1) (debug if-let*))
  (list 'if-let* varlist (macroexp-progn body)))
```

**Comment by yyoncho** [comment]
@MaskRay or start using `dash`.
