### ISSUE TITLE
Warning (lsp-mode): Unknown request method: workspace/diagnostic/refresh

### ISSUE THREAD

**Issue by vikigenius** [emacs-lsp/lsp-mode#4570]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Working on a Python project with two servers (basedpyright and ruff).
Lately after leaving Emacs idle for a few minutes, I always come back to this warning:

Warning (lsp-mode): Unknown request method: workspace/diagnostic/refresh

This only started happening after the switch from ruff-lsp to ruff server in this PR
https://github.com/emacs-lsp/lsp-mode/pull/4543

### Steps to reproduce

Start a python project with two servers after leaving Emacs idle for a while you get the warning

### Expected behavior

No warnings since it seems like workspace/diagnostic/refresh should be a supported function

### Which Language Server did you use?

pyright, ruff

### OS

Linux

**Comment by vikigenius** [comment]
I am able to consistently reproduce this if I make changes to pyproject.toml

**Comment by lassemaatta** [comment]
I'm experiencing the same issue with a few LSP servers (`clojure-lsp`, `lsp-tailwindcss`).

**Comment by zechs01** [comment]
I'm experiencing the same issue with (ts-ls) and (omnisharp) LSP servers and it gets reproduced each time I open emacs.

**Comment by Dushistov** [comment]
The same issue with rust-analyzer
