### ISSUE TITLE
Options for nixd language server

### ISSUE THREAD

**Issue by ircurry** [emacs-lsp/lsp-mode#4592]
Is your feature related or already mentioned on [the wishlist](https://github.com/emacs-lsp/lsp-mode/discussions/2892)?
No.

Describe your feature here.
Right now nil is the only language server for nix that can be configured. However, nixd has made considerable improvements and I think having configuration for it would be a good thing. Specifically, being able to set the formatting command, the nixpkgs expression, and options sets to use for completion.

**Comment by ircurry** [comment]
You may not want to commit this yet, I forgot there is an option to disable clients.

**Comment by breitnw** [comment]
I was having the same issue :P

I made a [fork](https://github.com/breitnw/lsp-mode) that seems to work for completions, but I haven't tested it with formatters since I don't typically use those. It _should_ in theory work with them though, since it sets `"nixd.formatting.command"`. This is how I configured it (I use Doom but you can probably adapt it pretty easily): 

```elisp
;; packages.el
(package! lsp-mode
  :recipe
  (:host nil :repo "https://github.com/breitnw/lsp-mode.git"))
(unpin! lsp-mode)

;; config.el
(after! lsp-mode
  (setq lsp-nix-nixd-nixpkgs-expr "import <nixpkgs> { }"
        lsp-nix-nixd-nixos-options-expr "(builtins.getFlake \"/home/breitnw/Documents/code/nixos\").nixosConfigurations.mnd.options"
        lsp-nix-nixd-home-manager-options-expr "(builtins.getFlake \"/home/breitnw/Documents/code/nixos\").homeConfigurations.\"breitnw@mnd\".options"))

(add-hook! 'nix-mode-hook
           ;; enable autocomplete
           (setq company-idle-delay 0.1))

```

The variable that sets the formatter is `lsp-nix-nixd-formatting-command`. Let me know if that works for you too. If everything does, I'll open a PR.

**Comment by breitnw** [comment]
Messing around a bit, I'm having some issues getting formatting to work 😅 I'll take another look at it soon when I get a chance, but in the meantime let me know if it works for you or you have any ideas.

**Comment by breitnw** [comment]
Managed to fix the formatter, it's working with nixfmt on my end :) I opened a PR, but in the meantime you can try and pin the commit (again, excuse the Doom lol)

```elisp
;; packages.el
(package! lsp-mode
  :pin "52d7313aac24212a493a836fca0704fe2865c14c"
  :recipe
  (:host nil
   :repo "https://github.com/breitnw/lsp-mode.git"))

;; config.el
(after! lsp-mode
  (setq lsp-nix-nixd-formatting-command [ "nixfmt" ]
        lsp-nix-nixd-nixpkgs-expr "import <nixpkgs> { }"
        lsp-nix-nixd-nixos-options-expr "(builtins.getFlake \"/home/breitnw/Documents/code/nixos\").nixosConfigurations.mnd.options"
        lsp-nix-nixd-home-manager-options-expr "(builtins.getFlake \"/home/breitnw/Documents/code/nixos\").homeConfigurations.\"breitnw@mnd\".options"))

(add-hook! 'nix-mode-hook
           ;; enable autocomplete
           (setq company-idle-delay 0.1))
```

**Comment by ircurry** [comment]
I am going to go ahead and close this issue. It seems to be resolved although I haven't been able to test it myself since the mechanism for updating melpa packages in nixpkgs seems to be broken (I could use an overlay but I just don't feel like doing that). Thank you @breitnw for being awesome and implementing this.
