### ISSUE TITLE
Feature: autodiscover and autoconfigure lsp

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#462]
After https://github.com/emacs-lsp/lsp-mode/issues/376 is in we may change it to automatically detect the presence of `lsp-ui` and `company-lsp` and start them accordingly. This will improve `lsp-mode` experience.

**Comment by stardiviner** [comment]
Vote for this too, I'm still confused how to start `lsp-mode`, `lsp-ui-mode`, `company-lsp` correctly.
