### ISSUE TITLE
lsp-mode doesn't show textDocument/hover in pop-up when response is MarkedString[]

### ISSUE THREAD

**Issue by niontrix** [emacs-lsp/lsp-mode#4626]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

When a language server provides a `textDocument/hover` response with a single string as content like this:
```
[Trace - 12:42:18 ] Received response 'textDocument/hover - (15)' in 4ms.
Result: {
  "contents": "File: file:///home/p0p3/workspace/tutorials/go/diy-language-server/README.md, Characters: 302"
}
```
then the documentation is shown as a pop-up.
When a language server provides a `textDocument/hover` response with as `MarkedString[]` like this:
```
[Trace - 01:04:47 ] Received response 'textDocument/hover - (8)' in 10ms.
Result: {
  "contents": [
    {
      "value": "File: file:///home/p0p3/workspace/tutorials/go/diy-language-server/README.md, Characters: 302",
      "language": "markdown"
    }
  ]
}
```
then the documentation is shown only in the minibuffer.

### Steps to reproduce

- Use for example `gopls` as a language server and open a Go file. `gopls` sends its `hover` responses as single strings.
- Use `nimlangserver` and open a Nim file. `nimlangserver` sends its `hover` responses as an array of `MarkedString`

### Expected behavior

`lsp-mode` should show `hover` responses using `MarkedString[]` as content in a pop-up.

### Which Language Server did you use?

I used `nimlangserver` v1.6.0.

### OS

Linux

### Anything else?

Also could you please explain how displaying the content of a `textDocument/hover` response works when being displayed as a pop-up as well as in the minibuffer, so I can get a better understanding of how `lsp-mode` works and maybe in the future contribute my own PR for issues like this?

**Comment by kiennq** [comment]
> Also could you please explain how displaying the content of a `textDocument/hover` response works when being displayed as a pop-up as well as in the minibuffer, so I can get a better understanding of how `lsp-mode` works and maybe in the future contribute my own PR for issues like this?

I don't think `lsp-mode` has the popup for showing the hover. Are you using `lsp-ui` for that?
For how the `textDocument/hover` works in `lsp-mode`, you can search inside `lsp-mode.el`, there're 3 places (2 for describe thing at point, 1 for eldoc) that request that, and they will eventually call `lsp--render-on-hover-content` to display the content.

**Comment by niontrix** [comment]
Yes, that is how far I understood it, but I couldn't really find how the pop-up is displayed in the end. But I think you're right this might potentially be a problem with `lsp-ui`. I'll take a look and maybe open a ticket over there.
Thanks! :+1:

**Comment by niontrix** [comment]
I made the following ticket over on `lsp-ui` - just for reference: [#783](https://github.com/emacs-lsp/lsp-ui/issues/783)
