### ISSUE TITLE
Feature: flymake integration

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#463]
This will help `lsp-mode` to become usable without additional extensions(refer to #318 )

**Comment by innerout** [comment]
This could be a problem for people that cannot install emacs 26.1 or build it from source. Am i wrong?

**Comment by yyoncho** [comment]
@innerout you are right - flymake integration will be optional and only for emacs 26.1+.

**Comment by innerout** [comment]
Could flymake integration potentially solve the problems flycheck has when changing an lsp buffer fast?

**Comment by yyoncho** [comment]
I am not aware of that issue, can you provide PR?

**Comment by innerout** [comment]
I am using mainly ccls and cquery so i don't know if this happening to all lsp-servers.We were talking about it with @MaskRay you can ask him. Probably he has a better understanding for the source of the problem.

**Comment by MaskRay** [comment]
This may be useful. eglot's implementation may give some insights.

@innerout I'll let you disappointed :( I don't know the source of problem well.

**Comment by j3kyl** [comment]
... and FlyCheck lost it most prominent/active maintainer

**Comment by yyoncho** [comment]
If there are no volunteers for the task i will hit it after migration to lsp.el is over and when i sync lsp java with the new jdt ls changes.

**Comment by yyoncho** [comment]
I will work on that.
