### ISSUE TITLE
after dec 2nd update xref stopped working 

### ISSUE THREAD

**Issue by elge70** [emacs-lsp/lsp-mode#4634]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

After Dec 2nd update, xref stopped working for typescript lsp-server. 

which-func-ff-hook error: (error "The connected server(s) does not support method textDocument/documentSymbol.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section")

lsp server capabilities along with treesitter highlighting also stopped working in the buffer

### Steps to reproduce

Update to latest lsp-mode with dec 2nd update

### Expected behavior

should be able to jump-around using xref.

### Which Language Server did you use?

typescript with ts-ls

### OS

Linux

**Comment by jcs090218** [comment]
What was the last working version? Do you know? 🤔

**Comment by elge70** [comment]
This was seen in DEC-01 melpa release. After updating DEC-02 release it starts working
