### ISSUE TITLE
Adding LS dependent methods and hooks for formatting help texts

### ISSUE THREAD

**Issue by astenman** [emacs-lsp/lsp-mode#464]
Hello,

Since I never have got "pyls" to work together with lsp-python on my windows box, I am playing around with the Microsoft Python language server. 

A few questions:

- Is it possible to add language server dependent methods? Now I get warnings about "unknown method: python/languageServerStarted".
- Are there any hooks to format the text returned by the language server? I get a lot of "^M" in the help buffer which is due to the Windows end of line convention.

**Which Language Server did you use**
lsp-python

**OS**
Windows 10, 64-bit

![image](https://user-images.githubusercontent.com/43724994/47778924-38ef3100-dcf8-11e8-9f7c-97f52db4db8b.png)

**Comment by yyoncho** [comment]
Yes, we have, you may check how it is implemented in `lsp-java`:  https://github.com/emacs-lsp/lsp-java/blob/master/lsp-java.el#L552 .
