### ISSUE TITLE
Question: cannot set false configuration value

### ISSUE THREAD

**Issue by Coffei** [emacs-lsp/lsp-mode#471]
Hi,
using this with [elixir-ls](https://github.com/JakeBecker/elixir-ls) and I'm having trouble setting configuration with `false` value.

Right now I am doing the following
```
  (defun lsp-elixir-set-configuration ()
    (let ((config `(:elixirLS (:mixEnv "dev" :dialyzerEnabled nil))))
          (lsp--set-configuration config)
          ))
  (add-hook 'lsp-after-initialize-hook 'lsp-elixir-set-configuration)
```
but the LS complains it doesn't receive boolean
```
10:07:20.112 [error] GenServer ElixirLS.LanguageServer.Server terminating
** (BadBooleanError) expected a boolean on left-side of "and", got: nil
```

I understand there's no dedicated boolean `false` value in elisp,  so how do we send `false` config to the server? I also tried `'nil`, `"false"` but none worked.

**Comment by yyoncho** [comment]
try :json-false

**Comment by Coffei** [comment]
Wonderful, that works. Thank you!
