### ISSUE TITLE
[feature request] Add swift language support as a package

### ISSUE THREAD

**Issue by fiveNinePlusR** [emacs-lsp/lsp-mode#472]
Per [this](https://github.com/syl20bnr/spacemacs/issues/11604#issuecomment-439223889) I think I need to report this here. let me know if this is not the place. 

There is an official apple LSP implementation that would be nice to have as a separate official `lsp-swift` repo/package. 

https://github.com/apple/sourcekit-lsp

**Comment by danielmartin** [comment]
I have started a package for that LSP server here: https://github.com/danielmartin/emacs-sourcekit-lsp

I'm OK with moving it to the main `emacs-lsp` org, but `sourcekit-lsp` plans to support interoperability between Swift and C languages (via clangd), so calling it `lsp-swift` may be misleading.

**Comment by yyoncho** [comment]
@danielmartin I have created https://github.com/emacs-lsp/lsp-sourcekit and added you as a admin . I used naming that is consistent with the current packages.

**Comment by yyoncho** [comment]
Closing issues related to swift will be tracked in https://github.com/emacs-lsp/lsp-sourcekit .
