### ISSUE TITLE
prog-indent-sexp jumps point to start of file

### ISSUE THREAD

**Issue by WJCFerguson** [emacs-lsp/lsp-mode#473]
When I do `prog-indent-sexp` - i.e. `C-M-q`, point is moved directly to the top of the file, and it acts as if the file is just loaded - `pop-global-mark`, for instance, doesn't take me back to where I last marked.

I'll attach a minimal config for `emacs -Q --load <file.el>` that loads it - to check it wasn't my config I just bootstrapped `use-package` and then set up `lsp-mode`.  Then in some python code, try to fix some bad indentation, like cursor before the `(` and hit `C-M-q`:

``` python
foo(
             1,
  2
)
```

**Expected behavior**
Buffer, point position, unchanged except indentation modified, as occurs without `lsp-mode` loaded

**Which Language Server did you use**
lsp-python

**OS**
Linux / Ubuntu 18.04
GNU Emacs 26.1
lsp-mode 20181103.2101

**Comment by WJCFerguson** [comment]
Minimal bootstrap config, for `emacs -Q --load <foo.el>`:

``` elisp
(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives
             '("MELPA Stable" . "https://stable.melpa.org/packages/"))
(add-to-list 'package-archives
             '("MELPA" . "https://melpa.org/packages/"))
(package-initialize)

;; Bootstrap `use-package'
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-when-compile
  (require 'use-package))
(setq use-package-always-ensure 't)

;; =============================================================================
(use-package lsp-mode
  :ensure t
  :diminish lsp-mode
  :config

  (lsp-define-stdio-client lsp-python "python"
                           #'ffip-get-project-root-directory
                           '("pyls"))

  (add-hook 'python-mode-hook #'lsp-python-enable))
```

**Comment by WJCFerguson** [comment]
Ah - I now see there's `lsp-enable-indentation` - and if I disable that, everything works ok again.  I'm assuming otherwise it asks the language server to re-indent and then just replaces the file contents wholesale or something(?).

I'm not sure what nice lsp server-indentation features I may lose, but at least I have a workaround.

**Comment by vibhavp** [comment]
IIRC, `lsp-enable-indentation` only controls tab indentation, so disabling that will only cause TAB to use emacs' own indentation logic.

**Comment by yyoncho** [comment]
@WJCFerguson can you include the log from client-server communication as per bug template?

**Comment by WJCFerguson** [comment]
All I can say is I get the bug if `lsp-enable-indentation` is set, as per default, but when I unset it I don't - when running `prog-indent-sexp`, via `C-M-q`.  This is with only the minimal config I submitted.

**Comment by yyoncho** [comment]
I checked the logs and the problem is caused by `pyls` sending one TextEdit which is starting from point 0 and thus the cursor is moves at 0 point. I will have to check what the emacs lisp pattern for preserving the point is.
