### ISSUE TITLE
lsp--should-start-p is broken with whitelist configured

### ISSUE THREAD

**Issue by kvaneesh** [emacs-lsp/lsp-mode#476]
(setq lsp-project-whitelist '("test"))
  (lsp--should-start-p "test2")
  (lsp--should-start-p "test")
  (lsp--should-start-p "tst")

All the above returns 't'. cl-notany return 't' if search list (lsp-project-blacklist) is nil.

  (cl-notany (lambda (p) (string-match-p p "test"))
		     lsp-project-blacklist)

**Comment by yyoncho** [comment]
I am not the author of that piece of code but I assume that `lsp-project-whitelist` is there to override `lsp-project-blacklist`, e. g.:

```
(setq lsp-project-blacklist '("test"))
(setq lsp-project-whitelist nil)
(lsp--should-start-p "test") ;; => nil

(setq lsp-project-blacklist '("test"))
(setq lsp-project-whitelist '("test"))
(lsp--should-start-p "test") ;; => t
```
... and this is the intended behavour. I am assuming that you want to blacklist some projects(based on your comment in spacemacs issue) so you have to add it to `lsp-project-blacklist`.

**Comment by kvaneesh** [comment]
Thanks. That helped. I wanted to enable lsp-mode only for few projects. So ended up with blacklist "."
