### ISSUE TITLE
Feature - support textDocument/foldingRange

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#477]
Refer to https://microsoft.github.io/language-server-protocol/specification

**Comment by MaskRay** [comment]
`textDocument/foldingRange` can be tested on ccls 
https://github.com/maskray/ccls/blob/master/src/messages/textDocument_foldingRange.cc#L42

**Comment by yyoncho** [comment]
I have investigated the folding solution libraries and for now https://github.com/gregsexton/origami.el seems like the only package that provides extension points for plugging range provider. Implementing the folding in lsp-mode.el wont pay off.

**Comment by yyoncho** [comment]
@vibhavp is this fixed?

**Comment by vibhavp** [comment]
Yes, mostly. I've sent a PR to MELPA for `lsp-origami` here: https://github.com/melpa/melpa/pull/6072

**Comment by yyoncho** [comment]
melpa/melpa#6072 is now in, thus closing
