### ISSUE TITLE
Port existing packages to lsp.el

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#479]
List of the packages to migrate:

- [x]  C (ccls)            [emacs-ccls](https://github.com/MaskRay/emacs-ccls)
- [x]  C (clangd)          [lsp-clangd](https://github.com/emacs-lsp/lsp-clangd)
- [x]  C (cquery)          [emacs-cquery](https://github.com/cquery-project/emacs-cquery)
- [x]  Haskell             [lsp-haskell](https://github.com/emacs-lsp/lsp-haskell)
- [x]  Java (Eclipse JDT)  [lsp-java](https://github.com/emacs-lsp/lsp-java)
- [x]  OCaml               [lsp-ocaml](https://github.com/emacs-lsp/lsp-ocaml)
- [x]  PHP                 [lsp-php](https://github.com/emacs-lsp/lsp-php)
- [x]  Ruby                [lsp-ruby](https://github.com/emacs-lsp/lsp-ruby)
- [x]  Rust                [lsp-rust](https://github.com/emacs-lsp/lsp-rust)
- [ ]  Scala               [lsp-scala](https://github.com/rossabaker/lsp-scala)
- [ ]  Vue                 [lsp-vue](https://github.com/emacs-lsp/lsp-vue)

Here it is example from lsp-java

```emacs-lisp
(eval-after-load 'lsp '(lsp-register-client
    (make-lsp--client
     :new-connection (lsp-stdio-connection 'lsp-java--ls-command)
     :major-modes '(java-mode)
     :server-id 'jdtls
     :multi-root t
     :notification-handlers (lsp-ht ("language/status" 'lsp-java--language-status-callback)
                                    ("language/actionableNotification" 'lsp-java--actionable-notification-callback)
                                    ("language/progressReport" 'lsp-java--progress-report)
                                    ("workspace/notify" 'lsp-java--workspace-notify))
     :action-handlers (lsp-ht ("java.apply.workspaceEdit" 'lsp-java--apply-workspace-edit))
     :uri-handlers (lsp-ht ("jdt" 'lsp-java--resolve-uri)
                           ("chelib" 'lsp-java--resolve-uri))
     :initialization-options (lambda ()
                               (list :settings (lsp-java--settings)
                                     :extendedClientCapabilities (list :progressReportProvider t
                                                                       :classFileContentsSupport t)
                                     :bundles (lsp-java--bundles)))
     :library-folders-fn (lambda (_workspace) (list lsp-java-workspace-cache-dir))
     :before-file-open-fn (lambda (workspace)
                            (let ((metadata-file-name (lsp-java--get-metadata-location buffer-file-name)))
                              (setq-local lsp-buffer-uri
                                          (when (file-exists-p metadata-file-name)
                                            (with-temp-buffer (insert-file-contents metadata-file-name)
                                                              (buffer-string)))))))))
```

**Comment by MaskRay** [comment]
Since `lsp-mode.el -> lsp.el` is breaking, have you considered renaming `extra-init-params` to `initialization-options`?

**Comment by yyoncho** [comment]
IMO it is a good chance to do all the cleanup that we didn't want to do due to backward compatibility issues.

**Comment by shackra** [comment]
I got this from `lsp-javascript-typescript`:

```
Error (use-package): lsp-javascript-typescript/:catch: Symbol’s function definition is void: lsp-make-traverser
```

The mode comes from https://github.com/emacs-lsp/lsp-javascript/ so it should be add to the list of clients to migrate, no?

**Comment by yyoncho** [comment]
If you are using `lsp.el` you do not need lsp-javascript package at all. You have to require `lsp-clients.el` and call  `lsp` directly.

**Comment by yyoncho** [comment]
Yes, check what is available in lsp-clients . The documentation is wip and we will apreciate any help.

**Comment by shackra** [comment]
Thanks!

**Comment by seagle0128** [comment]
Hi @yyoncho , When will `lsp-mode.el` be disabled?

**Comment by yyoncho** [comment]
@seagle0128 

1. All (or at leash all major) language packages are ported to lsp.el
2. Spacemacs layer is ported to lsp.el
3. dap-mode is ported to lsp.el
4. lsp.el is considered stable. 

Do you have something in mind?

**Comment by seagle0128** [comment]
@yyoncho It's fine with me. Eager to get the new features in lsp. Thanks a lot! Great work!

**Comment by yyoncho** [comment]
You may use it even now, refer to https://github.com/emacs-lsp/lsp-mode/blob/master/README-NEXT.md . I will wait for melpa build since https://github.com/tigersoldier/company-lsp/pull/69 was just pushed. We are looking for feedback on what we currently have.

`lsp.el` is implemented so once you require it `lsp-ui` will start working against it. But you cannot use both `lsp-mode.el` and `lsp.el`.

**Comment by alanz** [comment]
I have just realised this thing exists. What do I need to do to migrate lsp-haskell to it?

**Comment by alanz** [comment]
never mind, looking into it. PR some time soon, I hope.

**Comment by yyoncho** [comment]
I believe the minimal configuration will be sufficient for lsp-haskell. Here it is the python example:

``` emacs-lisp
(lsp-register-client
 (make-lsp-client :new-connection (lsp-stdio-connection "pyls")
                  :major-modes '(python-mode)
                  :server-id 'pyls))

```
I will update lsp-language-id-configuration include map haskell-mode to haskell.

**Comment by alanz** [comment]
Ok, just looking into it. We have various configuration options as well, I guess they can come over similar to the ones for go-lang?

**Comment by alanz** [comment]
and is there a standard way of dealing with configuration settings now?  For the `lsp--set-configuration` message.

**Comment by yyoncho** [comment]
The lsp--set-configuration is still present, that part is not changed. We have added few more extension points in registration client registration and some of the configuration like doc renderers  are handled out of the box.

**Comment by alanz** [comment]
Ok, I think I will take the java approach to start with, and keep it in lsp-haskell, to get a feel for it. 

Then as a later stage it can come into the main repo if it makes sense.

**Comment by yyoncho** [comment]
I agree, I think this is the best approach.

**Comment by alanz** [comment]
Does the new method no longer allow for providing a custom function to find the project root?

**Comment by yyoncho** [comment]
Yes. lsp.el will interactively ask once for the project root and the default suggestion will be provided by projectile/project.el . Once you select a project root it will be persisted and used for the upcoming sessions. In works like vscode but you are not forced to add the workspace folders upfront.

**Comment by MaskRay** [comment]
Haskell is not listed in https://microsoft.github.io/language-server-protocol/specification but I hope the value of `languageId` does not matter too much

`lsp-java.el` currently does:

```elisp
(require 'lsp-methods)
(eval-after-load 'lsp
  '(lsp-register-client
    (make-lsp--client
```

`emacs-ccls/ccls.el` currently does https://github.com/MaskRay/emacs-ccls/commit/7ab406d48da7c6122bc95a4fe9a0fda53a5dc299

**Comment by yyoncho** [comment]
@MaskRay you may delete the `ccls--make-renderer` as well.

**Comment by alanz** [comment]
Ok, the basics seem to be working for haskell, but the workspace/executeCommand is blowing up.

```
Debugger entered--Lisp error: (wrong-type-argument hash-table-p "7744:hie:fallbackCodeAction")
  gethash("command" "7744:hie:fallbackCodeAction")
  (lsp--send-execute-command (gethash "command" command) (gethash "arguments" command nil))
```
I think the problem is that the code action should be indexed by title, not command. We use the same command each time in `hie`, with different arguments.

The codeActions message from the server is

```json
{
  "result": [
    {
      "command": "7744:hie:fallbackCodeAction",
      "arguments": [
        {
          "fallbackWorkspaceEdit": {
            "changes": {
              "file:///home/alanz/tmp/hie-demo-project/src/B.hs": [
                {
                  "range": {
                    "start": {
                      "line": 23,
                      "character": 0
                    },
                    "end": {
                      "line": 23,
                      "character": 0
                    }
                  },
                  "newText": "ff :: IO ()\n"
                }
              ]
            }
          },
          "fallbackCommand": null
        }
      ],
      "title": "Add signature: ff :: IO ()"
    },
    {
      "command": "7744:hie:fallbackCodeAction",
      "arguments": [
        {
          "fallbackWorkspaceEdit": null,
          "fallbackCommand": {
            "command": "7744:hare:liftonelevel",
            "arguments": [
              {
                "pos": {
                  "line": 23,
                  "character": 0
                },
                "file": "file:///home/alanz/tmp/hie-demo-project/src/B.hs"
              }
            ],
            "title": "Lift ff one level"
          }
        }
      ],
      "title": "Lift ff one level"
    },
....
```

**Comment by alanz** [comment]
Nope, https://github.com/emacs-lsp/lsp-mode/pull/495

**Comment by alanz** [comment]
So I found you can do

```elisp
(eval-after-load 'lsp
  '(add-to-list 'lsp-language-id-configuration '(inc-mode . "inc") ))
```
in the language-specific config file, so the mode start-up works as for the built-in clients.

**Comment by seagle0128** [comment]
Hi @yyoncho,

I just tried new `lsp` interfaces for a few hours. Some behaviors are changed and I am not sure if they are as designed. When I was working on a complicated project including Python, Golang, HTM, Javascript and Shell, it confused me. Which client should be started? or all clients? But I observed not all clients were started successfully. Moreover, some clients haven't been ported. So I revert to `lsp-mode` for now. `lsp` is a good direction, and it simplifies the configurations like `eglot`. But needs some time to stable IMO. I will try later if I have some time. Thanks for your great work!

 Regarding `doom-modeline`, I'm pleased to add more features for `lsp-mode`. I can add new segment for `lsp-mode`. Currently `doom-modeline` displays `flycheck` info for current buffer, not for all workspace. I'd like keep the thing simple and fast. If the `flycheck` info of the whole workspace is easy and fast to get, I think I can add a new segment or replace the old one (depends on user's option). Your thoughts?

**Comment by yyoncho** [comment]
Thanks, few comments:

> When I was working on a complicated project including Python, Golang, HTML/CSS, Javascript and Shell, it confused me. Which client should be started?

When you open Python file it will start the python server and so on. There is a command `lsp-describe-session` which will list the folders and the corresponding servers and buffers associated to it. Also, as I mentioned doom-modeline does not display the info that you need in order to figure out what are the associated servers. Here it is what lsp UI is displaying.
![selection_061](https://user-images.githubusercontent.com/13259670/49423258-7fc0c280-f79f-11e8-84fa-13574cb4422a.png)

> But I observed not all clients were started successfully. Moreover, some clients haven't been ported.

All of the clients you have mentioned are ported.

> But needs some time to stable IMO. 

In order that to happen we have have concrete PR-s to work on. At this point, there are no `lsp.el` specific PRs.  

> Regarding doom-modeline, I'm pleased to add more features for lsp-mode. I can add new segment for lsp-mode. Currently doom-modeline displays flycheck info for current buffer, not for all workspace. I'd like keep the thing simple and fast. If the flycheck info of the whole workspace is easy and fast to get, 

As you might have noticed, I want to create a IDE-like experience around `lsp-mode` with integration with the following components: 

- lsp-ui for UI sugar
- Flycheck/Flymake for listing buffer errors 
- treemacs for project browser (check https://github.com/Alexander-Miller/treemacs/issues/263 @Alexander-Miller was very helpful) 
- helm/ido/ivy for management of errors/folders/workspace symbols and so on.
- dap-mode for debugger
- modeline? 

I like doom-modeline but without some of the information I mentioned in the previous comment it wont be a good fit for lsp-mode. 

I want to have the following components in the modeline:

1. Information about servers running(check screenshot)
2. Information about the state of the workspace(e. g. number of errors/warnings/infos)
3. A place to list progress tasks which will consist of percent + task description.

If you want to keep doom-modeline minimalistic, that's fine.

> I think I can add a new segment or replace the old one (depends on user's option). Your thoughts?

I believe that we need a separate one

**Comment by alanz** [comment]
A general comment on `lsp.el` approach.

I just opened a markdown file, and LSP prompted for the project root. But I do not have the markdown lsp server installed.

So perhaps we should have some way of configuring which lsp servers are available on a given machine.

**Comment by seagle0128** [comment]
@yyoncho I love this awesome plan!!! It will make Emacs more fancy definitely! `lsp` is fantastic, and the debugger is also important to the developers. I went through `dap-mode` a few days ago, and like the design. Hope it gets more powerful! Thank you!

`treemacs` is another powerful package I love. I use it instead of `neotree` I used for a long time. It's integrated to [Centaur Emacs](https://github.com/seagle0128/.emacs.d) by default. Really awesome although I don't use it frequently, especially in terminal. But it's very useful to read a new big project.

Well, I will take some time to think how to integrate it to `doom-modeline`. I'd love do that, but as you mentioned, I also want to keep it minimalistic and fast. I will make the decision after the investigation anyway.

**Comment by yyoncho** [comment]
@alanz this looks like a bug markdown which does not delay-mode-hooks when it tries to fontlock a language. I tried to reproduce it on my side but it does not reproduce. As a reference, here it is how we font-lock a language without running major mode hooks. I guess putting `(debug)` at `lsp` will reveal what is the problem.

```emacs-lisp
  (condition-case nil
      (with-temp-buffer
        (delay-mode-hooks (java-mode))
        (insert str)
        (font-lock-ensure)
        (buffer-string))
    (error str))
```

**Comment by seagle0128** [comment]
@yyoncho I implemented a simple indicator of LSP for `doom-modeline`. 

Since there are two interfaces of getting status, I leverage `lsp-mode-line` directly for now. It's same format and face as the lighter. 

![image](https://user-images.githubusercontent.com/140797/49538885-5f137c80-f907-11e8-8208-499f1f7a3c00.png)

If `lsp` is stable and `lsp-mode` is removed, I can improve it with new APIs. For example, querying status and show different icons. Your thoughts?

**Comment by yyoncho** [comment]
Looks good! I like the idea of showing the status in different colours. I am open also for improvements. 

At this point, I am considering `lsp.el` to be stable based on the lack of lsp.el specific PRs (excluding the errors caused by `lsp-mode.el` <> `lsp.el` messing up). I will try to move `lsp-mode.el` deletion forward by the end of the week.

**Comment by alanz** [comment]
And I think you can mark haskell off as ported/supported.

**Comment by yyoncho** [comment]
@seagle0128 
> I also have a comment about workgroup/layout, like Eclipse perspectives or VSCode layouts. The similar package for Emacs is persp-mode . Is it possible adding this into the plan list?

I have missed that question: sure, we can do that. Longterm we can do mouse/toolbar integration in order to attract more "traditional" users to emacs. . Treemacs already have mouse support. 
 I am planning to implement VScode/Eclipse/Intelij/etc icon themes too, dap-mode and lsp-java do support them.

**Comment by seagle0128** [comment]
@yyoncho The plan will help attracting more users, especially beginning users. `VSCode` is a role model of the modern editors. Advance users prefer keyboard. But for me I don't reject mouse :-)

I checked `dap-mode` and I'm very interested in it. `Debugging in emacs` is a missing feature in Emacs IMO, at least not good before. My experiences tell me only `gdb` works well in Emacs, others sucks. Sorry to say that! But `dap-mode` may open a new door. Microsoft is doing good things, like `lsp` and `dap` from VSCode. Awesome ideas! All editors will benefit from VS/VSC.

BTW, regarding `lsp` mode-line, I may suggest putting it in `global-mode-string` instead of `minor-mode` or providing an option. Because many emacsers don't like too many minor modes  (like me?) and disable them by `diminish` or `delight`. While the most of modelines keep `global-mode-string`. I know `display-time-mode` and `org-pomodoro` use it to display status and information. Of cause, it should be disabled by users if the standalone segments for `lsp` is provided in modeline, like `doom-modeline`.

**Comment by stardiviner** [comment]
I prompt an idea that hope lsp can provide troubleshooting of lsp itself. Let user know where is wrong. and auto generate info let developer can diagnose.

**Comment by stardiviner** [comment]
And there is other lsp clients like:
[ ] lsp-html
[ ] lsp-css

**Comment by yyoncho** [comment]
html/css are already ported. 

> I prompt an idea that hope lsp can provide troubleshooting of lsp itself. Let user know where is wrong. and auto generate info let developer can diagnose. 

I have tried to improve process error handling + error messages. You make take a look at lsp-describe-session too + the new lsp-mode lighter which lists what are the language servers connected to the current buffer.

**Comment by eubarbosa** [comment]
@yyoncho 

Hey, what is the deal with that huge el file instead of a modular one? Ive seen that eglot gone that way too...

**Comment by yyoncho** [comment]
@eubarbosa I am not (e)lisp expert but in general having one big file is not considered as bad in Lisp based languages.

**Comment by jefftrull** [comment]
Can someone point me to the documentation of how to configure a client? clangd is supposed to be "included" now but I see no reference to it in the code from MELPA, and though it is listed in the README there are several other C++ language servers, and it's not clear how the right one gets selected. Thanks.

**Comment by eubarbosa** [comment]
@yyoncho 

You know that you can still organize/structure that huge file under a org file and tangle it to .el file.

Win-win! 

I do that (3k SLOC) in a big and organized org file!

**Comment by yyoncho** [comment]
@nykma PR would be fine. If you are interested you may also consider contributing a debugger as well.

**Comment by yyoncho** [comment]
Closing this PR, the remaining servers will be tracked by: 
Vue - https://github.com/emacs-lsp/lsp-vue/issues/20 
Scala - https://github.com/rossabaker/lsp-scala/pull/9
