### ISSUE TITLE
Wrong type argument: listp, kind

### ISSUE THREAD

**Issue by topcpper** [emacs-lsp/lsp-mode#480]
**Describe the bug**
when i compile the lsp.el .
it appears an error "lsp.el:1747:1:Error: Wrong type argument: listp, kind"

emacs version 26.1

**To Reproduce**

**Expected behavior**

**Which Language Server did you use**
Mention which server/language did you use (e. g. lsp-python, lsp-ccls, lsp-java, etc)
lsp-python
**OS**
Which os do you use?
win7

**Error callstack**
If there is an error please reproduce the issue with `toggle-debug-on-error` and after setting `lsp-print-io` to t, and then include the callstack and attach the content of \*Messages\* buffer.

``` emacs-lisp
Compiling file d:/Program/emacs/.emacs.d/elpa/lsp-mode-20181128.640/lsp.el at Thu Nov 29 14:18:30 2018

In lsp--make-diag:
lsp.el:757:16:Warning: reference to free variable ‘severity’
lsp.el:758:12:Warning: reference to free variable ‘code’
lsp.el:759:14:Warning: reference to free variable ‘source’
lsp.el:760:50:Warning: reference to free variable ‘message’

In lsp--server-register-capability:
lsp.el:1091:43:Warning: reference to free variable ‘id’
lsp.el:1091:54:Warning: reference to free variable ‘method’
lsp.el:1091:70:Warning: reference to free variable ‘registerOptions’
lsp.el:1747:1:Error: Wrong type argument: listp, kind
```

**Comment by yyoncho** [comment]
Can you update your `dash` version? If this does not fix the issue, can you call toggle debug on error and attach the callstack?

**Comment by topcpper** [comment]
> Can you update your `dash` version? If this does not fix the issue, can you call toggle debug on error and attach the callstack?

dash               20180910.1856 installed 
it was the recent version.

**Comment by gnprice** [comment]
I get the same compilation error. I have `dash-20180910.1856` installed, which is the latest; and I'm on Emacs 25.1.

Here's the code in question -- the line in the error is the start of this `defun`:

```
(defun lsp--annotate (item)
  "Annotate ITEM detail."
  (-let (((&hash "detail" "kind" kind-index) (plist-get (text-properties-at 0 item) 'lsp-completion-item))
         kind)
    ;; We need check index before call `aref'.
    (when kind-index
      (setq kind (aref lsp--completion-item-kind kind-index))
      (concat " " detail (when kind (format " (%s)" kind))))))
```

I'm not familiar enough with `dash` to say whether or how there's an issue there; but the compiler seems to think so.

**Comment by yyoncho** [comment]
Can you reinstall lsp-mode and check whether the issue is still reproducible? You you have updated lsp-mode and dash at the same pass it is possible to get compilation error(like in https://github.com/emacs-lsp/lsp-mode/issues/510 )

**Comment by yyoncho** [comment]
Hm, I have pushed a new version into melpa, once it is ready I will try to reproduce the issue. Is https://github.com/emacs-lsp/lsp-mode/issues/517 still reproducible?

**Comment by gnprice** [comment]
Great, thanks! I had noticed that you've been pushing some significant changes recently :-)

It is -- and with a stack trace now! I'll follow up there.

**Comment by gnprice** [comment]
With @yyoncho 's help, I resolved this by running `M-x byte-compile-file` on dash.el. Details in #517 .
