### ISSUE TITLE
Maybe no clear instructions on how to use lsp-mode after latest update?

### ISSUE THREAD

**Issue by shackra** [emacs-lsp/lsp-mode#489]
**Describe the bug**
After the latest update some changes have to be made in order to have lsp-mode working, in my case I couldn't get auto-complete to work again.

**To Reproduce**
Modified my configuration into this:

```
(use-package lsp
  :ensure lsp-mode
  :config
  (require 'lsp-clients)
  (add-hook 'lsp-after-open-hook 'lsp-enable-imenu)
  :init
  (setf lsp-eldoc-render-all nil)
  (setq lsp-inhibit-message t)
  (setq lsp-message-project-root-warning t))

;; no changes to company-lsp thou
(use-package company-lsp
  :config
  (push 'company-lsp company-backends))

(use-package typescript-mode
  :init
  (setf typescript-indent-level shackra-webdev-indent)
  (add-to-list 'auto-mode-alist '("\\.tsx?\\'" . (lambda () (typescript-mode) (rjsx-minor-mode))))
  :config
  (with-eval-after-load "lsp-javascript-typescript"
    (add-hook 'typescript-mode-hook #'lsp)))

(use-package js2-mode
  :mode "\\.js\\'"
  :init
  (add-hook 'js2-mode-hook #'js2-imenu-extras-mode)
  (setf js2-mode-indent-inhibit-undo t)
  :config
  (with-eval-after-load "lsp-javascript-typescript"
    (add-hook 'js2-mode-hook #'lsp)))

(use-package rjsx-mode
  :init
  (add-to-list 'auto-mode-alist '("components?\\/.*\\.js\\'" . rjsx-mode))
  (add-to-list 'auto-mode-alist '("containers?\\/.*\\.js\\'" . rjsx-mode))
  (add-hook 'rjsx-mode-hook (lambda () (flyspell-mode-off) (aggressive-indent-mode -1)))
  :config
  ;; tomado de https://emacs.stackexchange.com/a/33544/690 mejora el sangrado
  ;; de lineas
  (defadvice js-jsx-indent-line (after js-jsx-indent-line-after-hack activate)
    "Workaround sgml-mode and follow airbnb component style."
    (save-excursion
      (beginning-of-line)
      (if (looking-at-p "^ +\/?> *$")
          (delete-char sgml-basic-offset))))
  (with-eval-after-load "lsp-javascript-typescript"
    (add-hook 'rjsx-mode-hook #'lsp)))
```

**Expected behavior**
I was expecting that after entering into the major mode, in my case rjsx-mode, auto-completion would be available as always.

**Which Language Server did you use**
None, only the ones provided in `lsp-clients.el`

**OS**
Arch Linux

**Comment by shackra** [comment]
Per #479 

> The documentation is wip and we will apreciate any help.

Which means that this can be closed as the documentation is in the works

**Comment by shackra** [comment]
> I am not aware how rjsx-mode work

According to the Commentary block of rjsx-mode.el:

> ;; Defines a major mode `rjsx-mode' based on `js2-mode' for editing
> ;; JSX files.  `rjsx-mode' extends the parser in `js2-mode' to support
> ;; the full JSX syntax.  This means you get all of the `js2' features
> ;; plus proper syntax checking and highlighting of JSX code blocks.

If the major mode is defined through `define-derived-mode` lsp should be started correctly, right?

**Comment by shackra** [comment]
Okay, is not the case, you need to add rjsx-mode too otherwise calling `lsp` fails with `user-error: Unable to find client(s) handling rjsx-mode`

**Comment by shackra** [comment]
After some changes as you asked, and having updated company-lsp I cannot get any auto-completion

The ts-ls is there thou:

![imagen](https://user-images.githubusercontent.com/1055216/49337457-5efa4080-f5d8-11e8-976d-ca8b63a2a5fc.png)

but no matter how much I write on my "example.jsx" file (is actually a file from a real project) the ts-ls buffer stays at `0`.

**Comment by yyoncho** [comment]
Actually, there is one more place to fix. It is lsp-language-id-configuration  it should probably have rjsx-mode -> javascript entry in it.

**Comment by yyoncho** [comment]
@shackra can you provide a sample project which I can use for testing rjsx files(assuming that they are the one that does not work)?

**Comment by shackra** [comment]
> @shackra can you provide a sample project which I can use for testing rjsx files(assuming that they are the one that does not work)?

install [create-react-app](https://www.npmjs.com/package/create-react-app) in your system using either `npm` or `yarn`, then anywhere in your system issue the command to create a project:

```
cd ~/
create-react-app myapp
```

You can then `cd` into `myapp` and create a `.jsx` file under `src/` and start testing if you wish

**Comment by shackra** [comment]
![captura de pantalla de 2018-12-02 14-35-35](https://user-images.githubusercontent.com/1055216/49344631-b8498a80-f63f-11e8-8937-fb8b2f236367.png)

The last bit was `(add-to-list 'lsp-language-id-configuration '(rjsx-mode . "javascript"))` indeed, hope @tigersoldier merges that pull request too, soon.

**Comment by yyoncho** [comment]
So everything works as expected? The pr was merged.

**Comment by yyoncho** [comment]
As a side note, I will add debugger support for JavaScript in dap mode after lap migration is over

**Comment by shackra** [comment]
> So everything works as expected? The pr was merged.

Yes, with the fixes suggested by you and as long as @tigersoldier has merged your pull request, it works as intended
