### ISSUE TITLE
Void variable range in lsp-hover

### ISSUE THREAD

**Issue by rocha** [emacs-lsp/lsp-mode#497]
**Describe the bug**
While idling over a lsp-mode enabled buffer, emacs throws a `(void-variable range)` error. Looking at the backtrace, it looks like the variable [`range`](https://github.com/emacs-lsp/lsp-mode/blob/892dd80a34df0d89a0621108c092e6d7c31e56cb/lsp-methods.el#L1881) is not defined in the `lsp-hover` method of `lsp-methods.el`

**To Reproduce**
Using spacemacs develop, open a buffer that has `'lsp` enabled as the major mode backend. For example:
``` emacs-lisp
(setq-default dotspacemacs-configuration-layers
   '(javascript :variables
               javascript-backend 'lsp))
```
An error is raised when idling on a non-empty line.

**Which Language Server did you use**
```
lsp-mode 20181202.1953
lsp-javascript-typescript-20180614.2011
spacemacs develop branch at [69a89cc4124](https://github.com/syl20bnr/spacemacs/tree/69a89cc41243cfb189238a2297fde4498d7fcf6d)
GNU emacs 26.1
```

**OS**
Which os do you use?
Ubuntu-Mate

**Error callstack**
****\*Messages\*****  
```
setq: Symbol’s value as variable is void: range
```

****\*Backtrace\*****
- [gist](https://gist.github.com/rocha/8599072343a601d7a672a996b3573c9b)

**Comment by yyoncho** [comment]
Upgrading to latest `dash` version should fix the issue.

**Comment by rocha** [comment]
@yyoncho got it thanks!
