### ISSUE TITLE
flycheck setup

### ISSUE THREAD

**Issue by alanz** [emacs-lsp/lsp-mode#50]
Using 

```elisp
(add-to-list 'load-path "<path to emacs-lsp>")
(require 'lsp-mode)
(global-lsp-mode t)
(with-eval-after-load 'lsp-mode
    (require 'lsp-flycheck)
    (lsp-flycheck-setup))
```
in my `dotspacemacs/user-config` I get  the following in the *Messages* buffer on startup:

```
(Spacemacs) Error in dotspacemacs/user-config: Symbol’s function definition is void: lsp-flycheck-setup
```

**Comment by vibhavp** [comment]
`lsp-flycheck-setup` has been shifted to `lsp--set-vars`, which does all flycheck work if flycheck is detected. I'll remove this from the README, thanks.

**Comment by alanz** [comment]
Thanks

**Comment by alanz** [comment]
`lsp--set-vars` is not in master?
