### ISSUE TITLE
Feature: textDocument/typeDefinition and textDocument/implementation (LSP 3.6)

### ISSUE THREAD

**Issue by coreyoconnor** [emacs-lsp/lsp-mode#503]
Tracking for (at least) `textDocument/typeDefinition` and `textDocument/implementation`. See 3.6 changelog:

* https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#version_3_6_0

**Comment by yyoncho** [comment]
Both methods are already implemented and exposed by lsp.el and lsp-mode.el , check lsp-goto-*

**Comment by coreyoconnor** [comment]
whoops. My mistake: got the target project wrong for this ticket :) sorry for the spam!
