### ISSUE TITLE
Start language server asynchronously?

### ISSUE THREAD

**Issue by astenman** [emacs-lsp/lsp-mode#508]
Is it possible to start the language server asynchronously? I am playing around with the Microsoft Python LS, and Emacs freezes several seconds until the language server has initialized. It would be nice if all this could be executed in the background. I am running Emacs 26 on Windows 10.

**Comment by yyoncho** [comment]
This is fixed lsp.el is starting the servers asynchronously. Refer to https://github.com/emacs-lsp/lsp-mode/blob/master/README-NEXT.md

**Comment by astenman** [comment]
OK! Maybe I am stupid, but I don't understand from the README how to configure this. When I open a Python file with the MS Python LS activated via lsp-mode, it takes 10-15 seconds until the file is shown.

**Comment by yyoncho** [comment]
There is an example in the end of the document. Also, you could refer to lsp-clients.el for more examples. Let me know if that helps.
