### ISSUE TITLE
"Start a new Language Server" question

### ISSUE THREAD

**Issue by alanz** [emacs-lsp/lsp-mode#51]
At the moment, if I choose not to use LSP for a project, it will ask me every time I open a different file in the project if I want to start a new language server.

Perhaps we should store the fact that for a given project root the answer is currently no.

**Comment by yurikhan** [comment]
Also, I started Emacs, it restored my saved desktop and decided to ask like two dozens of this question. Not useful!

**Comment by rski** [comment]
I prefer the completely manual way of ensime, where you have to do M-x ensime to start the server. It is not as user friendly as having something automatically come up and I didn't like it very much in the beginning, but I grew to prefer it and:
- it avoids the issues of when should the automatic prompt come up
- it gives you a way to start the server manually if the prompt doesn't come up for some reason
- I don't like having a find-file-hook created by plugins

**Comment by alanz** [comment]
See https://github.com/alanz/lsp-mode/commit/c92db975ed53daaaaf11b7b33b4c1397c4370ba9

**Comment by vibhavp** [comment]
@rski yeah, that sounds much better. I'm working on a similar `lsp-start` solution that you can then hook into language major modes.

**Comment by vibhavp** [comment]
`lsp-mode` is now enabled by hooking it into a major mode, so this question is never asked.

**Comment by alanz** [comment]
I am not convinced that this is the right solution.

I prefer to explicitly start a server, rather than have it start for any haskell file I open.  So the prior mechanism (one question per workspace root), or a solution as proposed by @rski would be better. In my opinion.
