### ISSUE TITLE
[Enhancement] Automatic client detection

### ISSUE THREAD

**Issue by seagle0128** [emacs-lsp/lsp-mode#512]
Hi, I am using new interface `lsp`.  Is it any possible to add automatic client detection for `lsp-clients`? Like `eglot`, then only one config to setup.

```elisp
(add-hook 'prog-mode-hook 'lsp)
```

Users don't need to care about `lsp` client should be used in which mode. `lsp` knows which client should be started in current programming mode. That's more intelligent.

**Comment by yyoncho** [comment]
I was aiming to this functionality but I am seeing https://github.com/emacs-lsp/lsp-mode/issues/506  as a prerequisite. Since we ship with predefined set of configuration, how do you think that we should handle the case when the serve is not present?

**Comment by seagle0128** [comment]
I don't think #506 is the prerequisite. 

If the binaries or packages are installed correctly, the lsp servers supported by `lsp-mode` will be started correctly as well. That's expected. The users should ensure the lsp servers they wanted are installed correctly by themselves. Otherwise, a prompt or message will be displayed.

Looking into `eglot`, and it doesn't require installing lsp servers before `eglot-ensure`.
So, if the server is not present or supported, just needs one message to users, nothing else. If introducing `system-package` here, will make the things complicated. Just keep it simple and clean.

**Comment by innerout** [comment]
If you had a specific path given from the user or specified from lsp-mode wouldn't that be convenient?

**Comment by yyoncho** [comment]
@seagle0128 some of the servers does are started like `java -jar ...`, `php args...` so there is no predefined way to check whether the server is present so we will need one more property in server definition like :server-installed? .

@innerout can you explain a bit more what do you mean?

**Comment by innerout** [comment]
If you set a predefined path about the servers to be installed that could simplify the setup. Also support for all platforms will be easier to debug and configure as you will be able to take OS specific decisions if  problems arise.

**Comment by seagle0128** [comment]
Maybe need connection test feature? Not sure how is it implemented in `eglot`. I think we can refer to it.

**Comment by yyoncho** [comment]
@seagle0128 I have made some adjustments in lsp.el (particulary not using user-error if there is no client handling a particular mode). The next step is to make lsp.el ignore the server if it is not present.

**Comment by yyoncho** [comment]
@seagle0128 #544 is proposed fix for the issue. It enables the `(add-hook 'prog-mode-hook 'lsp)` config.

**Comment by seagle0128** [comment]
@yyoncho Thanks for fixing.
