### ISSUE TITLE
LSP shows "Disconnected" despite having RLS installed. What can I do to debug it?

### ISSUE THREAD

**Issue by r-darwish** [emacs-lsp/lsp-mode#523]
I'm trying to set up LSP in for Rust. I have RLS installed via rustup and seems to be available in Emacs' `PATH`. 

When `lsp-mode` is turned on it shows `LSP[Disconnected]` in the mode line. There doesn't seem to be anything helpful in `*Messages*` and `lsp-describe-session` opens up an empty buffer. Setting up `lsp-print-io` to non-nil doesn't produce any output either.

Using Emacs 26.1 on Arch Linux.

**Comment by yyoncho** [comment]
Call lsp not lsp-mode

**Comment by r-darwish** [comment]
I just did, and answered `Import project root /home/roeyd/src/topgrade`. It then says `Unable to find client(s) handling rust-mode`.

**Comment by yyoncho** [comment]
Also do (require 'lsp-clients)
