### ISSUE TITLE
on-hover shows MarkupContent as "markdown", instead of the content

### ISSUE THREAD

**Issue by klajo** [emacs-lsp/lsp-mode#530]
The "value" and "kind" arguments are switched in this call, causing emacs to print the text "markdown" (the kind) instead of the actual content for MarkupContent on-hover-docs.

```
   ;; MarkupContent
   ((and (hash-table-p content)
         (gethash "kind" content))
    (-let [(&hash "value" "kind") content]
      (lsp--render-string kind value)))
```
https://github.com/emacs-lsp/lsp-mode/blob/master/lsp.el#L2020

Here's the definition on lsp--render-string:

```
(defun lsp--render-string (str language)
  "Render STR using `major-mode' corresponding to LANGUAGE.
When language is nil render as markup if `markdown-mode' is loaded."

```

Cheers,
Klas

**Comment by yyoncho** [comment]
Thanks for pointing this. I saw it, but I didn't pay attention
