### ISSUE TITLE
A decent way to disable lsp-document-highlight

### ISSUE THREAD

**Issue by kaiwk** [emacs-lsp/lsp-mode#531]
I don't find a way to disable `lsp-document-highlight`, so what I do is modifying `lsp-eldoc-hook`.

```elisp
(remove-hook 'lsp-eldoc-hook 'lsp-document-highlight)
```

Is there any customization option?

**Comment by yyoncho** [comment]
At this point no, alternatively you could use:
```
(setq lsp-eldoc-hook '(lsp-hover))
```
which effectively is configuration option.

**Comment by Hi-Angel** [comment]
I'm a bit confused by description, but anyway, for future readers: a way to remove highlight that was done by `(lsp-document-highlight)` is to call it again while there's no word before the caret.
