### ISSUE TITLE
Trouble converting client to new lsp-mode

### ISSUE THREAD

**Issue by rishisubramanian** [emacs-lsp/lsp-mode#532]
I've been trying to update my julia-lsp configuration to the new version of lsp-mode. When I load lsp, it doesn't connect to the server. `lsp-describe-session` comes up blank as well. 

My config:
```
(require 'lsp)
(add-hook 'julia-mode-hook 'lsp)
(add-hook 'julia-mode-hook 'lsp-mode)

(lsp-register-client
 (make-lsp-client
  :new-connection (lsp-stdio-connection '("julia" "--startup-file=no --history-file=no -e using LanguageServer; using SymbolServer; server = LanguageServer.LanguageServerInstance(stdin, stdout, false, \"/home/rishi/.julia/environments/v1.0\", \"\", Dict()); server.runlinter = true; run(server);"))
  :major-modes '(julia-mode)
  :server-id 'julia-ls))
```

**Comment by yyoncho** [comment]
I will try it when I have time but my guess is that you should split the arguments by space. like that:
```
(lsp-register-client
 (make-lsp-client
  :new-connection (lsp-stdio-connection '("julia" "--startup-file=no"
                                          "--history-file=no"
                                          "-e"
                                          "using LanguageServer; using SymbolServer; server = LanguageServer.LanguageServerInstance(stdin, stdout, false, \"/home/rishi/.julia/environments/v1.0\", \"\", Dict()); server.runlinter = true; run(server);"))
  :major-modes '(julia-mode)
  :server-id 'julia-ls))
```

can you include the content of Messages buffer with lsp-print-io set to t?

**Comment by rishisubramanian** [comment]
Tried it, didn't change anything. Nothing was printed to the message buffer either.

**Comment by yyoncho** [comment]
Sorry for the delay, what is the content of `julia-ls` server buffer? Can you verify that the server is started?

**Comment by yyoncho** [comment]
So, after you register the command like in https://github.com/emacs-lsp/lsp-mode/issues/532#issuecomment-446471843 you will have to go in julia file and call `lsp`. I am hitting https://github.com/JuliaEditorSupport/LanguageServer.jl/issues/300 and I am completely new to julia so I am struggling to start the server locally.

**Comment by rishisubramanian** [comment]
The Julia command that's being executed runs the LSP server. Right now there's no dedicates program like pyls. As for the Symbolserver error, I'm working around it by using my own fork.

**Comment by yyoncho** [comment]
Did you get it working?

**Comment by rishisubramanian** [comment]
I can run it from the command line, but Emacs doesn't start it for some 
reason.

**Comment by yyoncho** [comment]
What happens after you call `lsp` in julia file? Are there messages in Messages buffer?

**Comment by rishisubramanian** [comment]
Still nothing

**Comment by yyoncho** [comment]
And nothing in messages buffer?

**Comment by yyoncho** [comment]
Here it is PR which has successfully ported Julia server to new lsp.el https://github.com/non-Jedi/lsp-julia/pull/5/
