### ISSUE TITLE
lsp-mode no longer provides lsp-common

### ISSUE THREAD

**Issue by traxou** [emacs-lsp/lsp-mode#534]
removing `(provide 'lsp-common)` in commit 
commit 439df1e463b3778cea5ddcdb2fccbf27b6a9fb5f breaks lsp-clangd install 
Installation via melp 
lsp-clangd         20180828.1657

Error:
lsp-clangd.el:28:1:Error: Cannot open load file: No such file or directory, lsp-common

**To Reproduce**
Install lsp-clangd via melp (emacs-25 or emacs-26) 

**Expected behavior**
Installation should go through 

**Which Language Server did you use**
lsp-clangd

**OS**
ubuntu 18.04 
GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-05-29

**Comment by yyoncho** [comment]
Check https://github.com/emacs-lsp/lsp-clangd/issues/11#issuecomment-445587207
