### ISSUE TITLE
clangd config

### ISSUE THREAD

**Issue by nickenchev** [emacs-lsp/lsp-mode#537]
Hey, having trouble getting the built in support for clangd going. I'm assuming I don't need to install the lsp-clangd package since it says it is built-in. Here's what my config looks like:

```
(require 'lsp)
(require 'lsp-clients)
(add-hook 'c++-mode-hook 'lsp)
```

```Unable to find client(s) handling c++-mode. Make sure you have required lso-clients.el or proper extension.```

I looked through lsp-clients.el and it seems like the clangd client is defined there for c++-mode.

Using latest MELPA version.

If I'm not seeing where I need to specify I want clangd initialized in the documentation, please point me to what I'm missing. The getting started guide just says the above lines for init.

**Comment by yyoncho** [comment]
Sorry, this is not documented since it is terporary solution you have to call `lsp-clients-register-clangd`

**Comment by nickenchev** [comment]
What is the temporary solution you are referring to?

**Comment by tee3** [comment]
For a little more context, https://github.com/emacs-lsp/lsp-clangd/issues/11#issuecomment-445587207.

**Comment by nickenchev** [comment]
Thanks, makes sense.

**Comment by maobaoqi** [comment]
Hi, I use clangd to complete C code. But I include the glib-2.0 library header files under /usr/include dir, the lsp can not complete glib functions and variables. Would you give me a favour?
