### ISSUE TITLE
Path to `dart_language_server` is different on Windows

### ISSUE THREAD

**Issue by bradyt** [emacs-lsp/lsp-mode#539]
Path to `dart_language_server` is different on Windows.

On Windows, I've installed `emacs` and `dart-sdk` via `chocolatey`.

If I open a dart file, I get the following error.

```
Debugger entered--Lisp error: (error "Couldn’t find executable c:/Users/Administrator/AppData/Roaming/.pub-cache/bin/dart_language_server")
```

The issue is fixed with the following configuration.

``` elisp
(setq lsp-clients-dart-server-command (expand-file-name "~/Pub/Cache/bin/dart_language_server")))
```

I am wondering if we can something like the following to `lsp-mode`, in `lsp-clients.el`, for easier configuration.

``` diff
@@ -291,7 +291,11 @@ finding the executable with `exec-path'."
 
 ;; Dart
 (defcustom lsp-clients-dart-server-command
-  (expand-file-name "~/.pub-cache/bin/dart_language_server")
+  (expand-file-name
+   (concat "~/"
+           (if (equal system-type 'windows-nt)
+               "Pub/Cache"
+             ".pub-cache") "/bin/dart_language_server"))
   "The dart_language_server executable to use."
   :group 'lsp-dart
   :type 'file)
```

If it is not currently part of the project's intentions, I would consider instead submitting pull requests to `lsp-dart`, or simply updating documentation at `dart-mode` project.

**Comment by yyoncho** [comment]
Project intention is provide as much configuration out of the box so feel free to provide a PR. 

PS: Can you just use the full paths instead of using concat to improve the readability.

**Comment by bradyt** [comment]
Great! Another possibility is to use `(executable-find "dart_language_server")`.

**Comment by yyoncho** [comment]
@bradyt 
> Great! Another possibility is to use `(executable-find "dart_language_server")`. Will send PR soon with your proposal.

Definitely an option. Ideally, the language server could auto-install itself if it is not present.
