### ISSUE TITLE
Company completion is painfully slow

### ISSUE THREAD

**Issue by mpanarin** [emacs-lsp/lsp-mode#556]
**Describe the bug**
Company completions take seconds to load up, which wasn't the case before the lsp-common deprecation. I have a feeling that company now waits for the flycheck to finish its business(which is also painfully slow and no way to disable it.) I would think that this is lsp-ui issue, but only by disabling lsp-mode the completions are working properly.

**To Reproduce**
Just try to write something in a file that has more than 50 lines

**Which Language Server did you use**
lsp-python

**OS**
Linux Manjaro

**Error callstack**
no errors

**Comment by yyoncho** [comment]
I wasn't able to reproduce it with large file locally and also on a docker machine with minimal configuration. Flycheck is not related to completion.

1. Did you try to profile Emacs? If so, can you post the profile data?
2. Did you inspect the input/output between client and server?

**Comment by mpanarin** [comment]
I'll close this as I decided to revert the updates on lsp, sorry.

I noticed that it starts to slow down considerably when you activate virtualenv.
