### ISSUE TITLE
Company: backend company-lsp error "Wrong type argument: lsp--workspace, nil" with args (prefix)

### ISSUE THREAD

**Issue by algking** [emacs-lsp/lsp-mode#559]
**Describe the bug**
can not use company-lsp in vue
**To Reproduce**
M-x company-complete
**Expected behavior**

**Which Language Server did you use**
Mention which server/language did you use (e. g. lsp-python, lsp-ccls, lsp-java, etc)
lsp-vue
**OS**
Which os do you use?
mac 10.11
**Error callstack**
If there is an error please reproduce the issue with `toggle-debug-on-error` and after setting `lsp-print-io` to t, and then include the callstack and attach the content of \*Messages\* buffer.

``` emacs-lisp
(setq lsp-print-io t)
Debugger entered--Lisp error: (wrong-type-argument lsp--workspace nil)
  signal(wrong-type-argument (lsp--workspace nil))
  company-lsp(prefix)
  apply(company-lsp prefix)
  company-call-backend-raw(prefix)
  apply(company-call-backend-raw prefix)
  company--force-sync(company-call-backend-raw (prefix) company-lsp)
  company-call-backend(prefix)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-manual-begin()
  company-complete()
  funcall-interactively(company-complete)
  #<subr call-interactively>(company-complete nil nil)
  apply(#<subr call-interactively> company-complete (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> company-complete nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (company-complete nil nil))
  call-interactively(company-complete nil nil)
  command-execute(company-complete)

```

**Comment by yyoncho** [comment]
Please refer to the latest lsp-mode documentation and upgrade to the latest versions of lsp-mode.el .
The only configuration that you need after installing company-lsp and lsp-ui is: 
```
(require 'lsp)
(require 'lsp-clients)
(add-hook 'vue-mode-hook 'lsp)
```

**Comment by algking** [comment]
lsp-ui/company-lsp/lso-mode are the latest versions

I migrate lsp-vue two days ago, It works , but after I upgrade last day, this propblem shows.

I fixed this by remove all the .elc in company-lsp
