### ISSUE TITLE
Can't complete header files

### ISSUE THREAD

**Issue by maobaoqi** [emacs-lsp/lsp-mode#560]
Hi, I install new lsp-mode and it is a nice tool. I include stdio.h or iostream file, but it can not pop complete menu. However,  I write code like printf or std::cout, it work well and pop correct complete results. How I should do to config clangd and make lsp-mode complete current directory or usr/include header files? thanks!

**Comment by yyoncho** [comment]
Can you post the code fragment for which you expect to have completion so someone with C++ expertise could comment?

**Comment by yyoncho** [comment]
Please reopen after providing the requested details.
