### ISSUE TITLE
Spacemacs develop branch lsp-mode does not work for Python

### ISSUE THREAD

**Issue by handsomeyang** [emacs-lsp/lsp-mode#561]
The following is put in .spacemacs
```
dotspacemacs-configuration-layers
   '(
     ...
     lsp
     (python :variables
             python-backend 'lsp
             python-enable-yapf-format-on-save t)
     ...
     )
```
When opening a .py file, the mini buffer outputs "File mode specification error: (file-missing Cannot open load file No such file or directory lsp-common)".

**Comment by yyoncho** [comment]
You have to include https://github.com/syl20bnr/spacemacs/pull/11626 . It is not merged due to spacemacs freeze.

**Comment by handsomeyang** [comment]
Thanks.

**Comment by handsomeyang** [comment]
After merging [syl20bnr/spacemacs#11626](https://github.com/syl20bnr/spacemacs/pull/11626) into Spacemacs develop, now the *Messages* buffer says "Unable to find client(s) handling python-mode. Make sure you have required lsp-clients.el or proper extension.".

**Comment by yyoncho** [comment]
@cormacc  
after  https://github.com/emacs-lsp/lsp-mode/commit/21dcef147a75236760d757be5676a75af73c1450 it seems like the use-package does not work fine. We will probably move the content of lsp.el to lsp-mode.el (see also https://github.com/emacs-lsp/lsp-mode/issues/558 )

**Comment by cormacc** [comment]
@yyoncho - so what change do I need to make to the PR? Took a look at those links and still a bit confused :)

**Comment by yyoncho** [comment]
@cormacc I hope that after #563 no changes wound be required.

**Comment by cormacc** [comment]
@yyoncho This seems to be resolved with your most recent changes and current syl20bnr/spacemacs#11626. Can probably close?

**Comment by yyoncho** [comment]
Thanks @cormacc !
