### ISSUE TITLE
Multiple clients - multiple selection prompts for single project

### ISSUE THREAD

**Issue by cormacc** [emacs-lsp/lsp-mode#567]
**Describe the bug*
When multiple clients are registered for a given language mode, I have to select from a list of available clients for each file I open (within the same project). Problematic when using external clients where an internal client exists.

**To Reproduce**
(Using c-c++ backends)
install lsp-mode/lsp-ui and either the ccls or cquery packages.
Open a file in a c/c++ project (emacs prompts to select between clangd and ccls/cquery)
Open another file in the same project (client selection prompt appears again)
Rinse and repeat

**Expected behavior**
Only prompted to select client for first opened file
AND/OR
Able to specify preferred client per language globally and/or per-project

**Which Language Server did you use**
Reproduced with ccls and cquery

**OS**
Arch Linux

**Error callstack**
No error per se, just intrusive prompts from emacs

**Comment by yyoncho** [comment]
> Able to specify preferred client per language globally and/or per-project

At this point we have only the global option, e. g:

```
(remhash 'cquery lsp-clients)
```
But we will probably implement also
> Only prompted to select client for first opened file

**Comment by cormacc** [comment]
Thanks @yyoncho -- that fixed it -- added 
```
(remhash 'clangd lsp-clients)
```
to a lambda attached to the c-mode hooks.

Initially tried adding it to a use-package post-config hook, but that didn't work.
```
 (defun c-c++/post-init-lsp-mode ()
   (spacemacs|use-package-add-hook lsp
     :post-config
     (remhash 'clangd lsp-clients)))
```
Just out of interest -- the lambda solution works (closing)
