### ISSUE TITLE
[Feature request] Choose a default client per major mode or per project

### ISSUE THREAD

**Issue by Havner** [emacs-lsp/lsp-mode#568]
The issue I have is that I need lsp-clients.el because I use pyls and I also use ccls for c/c++. Requiring lsp-clients means that clangd client for c/c++ also gets registered.
Having two clients (clangd/ccls) for c/c++ means that every single time I open a c/cpp file (even within the same project) I get a question to choose what client I want to use. This gets really annoying.
I've looked through the code, but I don't see any simple way to actually remedy that short of removing clangd from lsp-clients by hand.

EDIT: also, even without the issue above, should client question get asked every time I open another file (same major mode) within the same project?

**Comment by yyoncho** [comment]
This is on my list, at this point the workaround is to do something like:
```
(remhash 'clangd lsp-clients)
```

**Comment by Havner** [comment]
That worked. Thanks. If you have this on a todo anyway you can close this issue if you don't need a reminder here.

**Comment by yyoncho** [comment]
After 21409b1 you will be asked only once per project. Also, I have added FAQ entry for those who want always to start a certain server. The option to customize the server per project is not there and it will be implemented if is requested.
