### ISSUE TITLE
Relative path not supported in workspace

### ISSUE THREAD

**Issue by m4b** [emacs-lsp/lsp-mode#57]
When opening new project, it asks for project root (also why can't this be found automatically based on file location?)

If We give `~/project/name/` (which is already filled in) the tilde is not expanded and the path is passed to the rls which panics. This could be fixed upstream but probably easiest to just expand the ~ if possible and pass the absolute file path to the server. 

Ideally I don't have to type this at all, as it should be discoverable by simply going up from current path until a cargo.toml is found, and if not, only then asking/aborting

**Comment by alanz** [comment]
Maybe do something similar to [this](https://github.com/tee3/emacs-lsp/commit/75bdbe934760f8b1937bdc0cfd1a95effc9ed403#diff-a1cde4c3716ddcb56829c85d0e65a937R12)

**Comment by m4b** [comment]
Ya, so iirc `cargo locate-project` will return a Json object with root : `/absolute/path/to/toml`, and non zero error code otherwise

**Comment by vibhavp** [comment]
> Ya, so iirc cargo locate-project will return a Json object with root : /absolute/path/to/toml, and non zero error code otherwise

whoa, had no idea this existed. Will use that for rust, thanks!

**Comment by m4b** [comment]
This is fixed in latest and also this emacs-lsp/lsp-rust#2
