### ISSUE TITLE
lsp-mode for dart does not guess correct project root

### ISSUE THREAD

**Issue by bradyt** [emacs-lsp/lsp-mode#576]
The prompts created by `lsp--find-root-interactively` and `lsp--suggest-project-root` will quite likely try to pass a directory having a `.git` directory, or similar. This may frequently be incorrect, as I believe the `dart_analysis_server` should be passed a directory at or above a directory with `pubspec.yaml` (or `BUILD`). I suspect we can in fact pass any directory _above_ such, in particular, the directory of current file.

This way, the prompts will be more helpful for user, and even, user can better use `lsp-auto-guess-root`.

The following diff helps ensure the right directory is passed to `dart_language_server`. (I'm making a lot of assumptions about how `dart_language_server`, LSP, and `lsp-mode` all work together.)

``` diff
@@ -1266,6 +1266,11 @@ disappearing, unset all the variables related to it."
 (defun lsp--suggest-project-root ()
   "Get project root."
   (or
+   (when (eq major-mode 'dart-mode)
+     (let ((file (buffer-file-name (current-buffer))))
+       (or (locate-dominating-file file "pubspec.yaml")
+           (locate-dominating-file file "BUILD")
+           (file-name-directory file))))
    (when (featurep 'projectile) (condition-case nil
                                     (projectile-project-root)
                                   (error nil)))
```

My assumptions are based on the following lines from https://github.com/natebosch/dart_language_server/blob/master/lib/src/utils/package_dir_detection.dart#L19-L21, and some notes about `rootUri` in the changelog at same project.

``` dart
bool _isPackageRoot(Directory dir) => dir.listSync().any((f) =>
    f.path.endsWith('${Platform.pathSeparator}pubspec.yaml') ||
    f.path.endsWith('${Platform.pathSeparator}BUILD'));
```

**Comment by bradyt** [comment]
Does lsp-mode set project root based on a response from server? If so, can we simply write the following?

``` diff
@@ -1266,6 +1266,8 @@ disappearing, unset all the variables related to it."
 (defun lsp--suggest-project-root ()
   "Get project root."
   (or
+   (when (eq major-mode 'dart-mode)
+     (file-name-directory (buffer-file-name (current-buffer))))
    (when (featurep 'projectile) (condition-case nil
                                     (projectile-project-root)
                                   (error nil)))
```

**Comment by yyoncho** [comment]
> Does lsp-mode set project root based on a response from server?

No, it doesn't. As far as I know the protocol does not provide methods for obtaining such information. As I mentioned in gitter, using current directory will not work either since for a project with multiple directories lsp-mode will start multiple language servers since the language server is associated with the root directory.

> The prompts created by lsp--find-root-interactively and lsp--suggest-project-root will quite likely try to pass a directory having a .git directory, or similar. This may frequently be incorrect, as I believe the dart_analysis_server should be passed a directory at or above a directory with pubspec.yaml (or BUILD). I suspect we can in fact pass any directory above such, in particular, the directory of current file.

Since the logic related to root detection is fairly complex IMO it would be better to rely on project.el or projectile since they are specialized in project management or we are risking to reimplement all the complex logic that is present in these projects. 

In order to get the behaviour you have described the following configuration option is needed:

```
(add-to-list 'projectile-project-root-files-bottom-up "pubspec.yaml") 
```

**Comment by bradyt** [comment]
How do we know that the notion of project as it means in project.el and projectile are in line with what it means in LSP?

**Comment by bradyt** [comment]
Ah, nice. If I understand correctly, that works because of the order of functions in `projectile-project-root-files-functions`.

Then if case users don't have `projectile` installed, we might suggest they add the following:

``` elisp
(defun project-try-dart (dir)
  (cons 'dart (or (locate-dominating-file dir "pubspec.yaml")
                  dir)))
  
(add-hook 'project-find-functions #'project-try-dart)
```

**Comment by yyoncho** [comment]
Yes. I am closing this for now and eventually, I will create FAQ entry if more people ask about configuring default root selection.
