### ISSUE TITLE
Emacs hangs when using lsp-dart

### ISSUE THREAD

**Issue by l7ssha** [emacs-lsp/lsp-mode#577]
**Describe the bug**
Emacs periodically hangs out when navigating through source code. Bug only occurs when using Dart - other supported languages didn't have such problem. When emacs hangs out lsp seems to print few errors to Messages buffer.

**To Reproduce**
 - start dart project
 - enable lsp
 - navigate/try to code
 - emacs is hanging periodically and prints few errors

**Expected behavior**
Emacs should work smoothly.

**Which Language Server did you use**
lsp-dart

**OS**
Archlinux, 4.19.9-arch1-1-ARCH

Emacs 26.1, latest lsp

**Error callstack**
https://gist.github.com/l7ssha/55b99d763a065252e6a9a1bae58e6350

Probably related to #52 #201 #232 - not resolved though

**Comment by yyoncho** [comment]
Yes, it looks like #232 . I will install dart server and I will try to reproduce. Meanwhile, can you do what I have described in  https://github.com/emacs-lsp/lsp-mode/issues/232#issuecomment-449284003 and post the output? I believe that there are some problems related to how we de-serialize lists/maps in json.

**Comment by l7ssha** [comment]
Thanks for reply @yyoncho There is thing you asked: https://gist.github.com/l7ssha/1ddf9b5b8953a90dea772e93b07c1658

**Comment by yyoncho** [comment]
Can you revaluate with setting lexical-binding to t - https://github.com/emacs-lsp/lsp-mode/issues/232#issuecomment-449296187 . Sorry for ommiting that info.

**Comment by l7ssha** [comment]
That's all I was able to gather.
https://gist.github.com/l7ssha/8e0426de0cba7bbd0bc65ec488e80520

**Comment by yyoncho** [comment]
@l7ssha 

I have installed the dart server but I was unable to reproduce the issue. Can you give me a sample project to reproduce the issue if possible?

> That's all I was able to gather.
> https://gist.github.com/l7ssha/8e0426de0cba7bbd0bc65ec488e80520

This log is still with lexical-binding set to nil

Here it is code that you need to execute and then provide the logs: Note that the error about `ignore-regexps` could happen only when lexical-binding is set to nil when evaluating the function definition. If you are on gitter you may ping me there with the results.

```
(setq lexical-binding t)

(defun lsp--parser-make-filter (p ignore-regexps)
  "Make filter for the lsp parser P ignoring IGNORE-REGEXPS."
  #'(lambda (_proc output)
      (let ((inhibit-message t)) (message ">>> RECEIVED\n%s" output))
      (when (cl-loop for r in ignore-regexps
                     ;; check if the output is to be ignored or not
                     ;; TODO: Would this ever result in false positives?
                     when (string-match r output) return nil
                     finally return t)
        (let ((messages
               (condition-case err
                   (lsp--parser-read p output)
                 (error
                  (progn
                    (lsp--parser-reset p)
                    (setf (lsp--parser-response-result p) nil
                          (lsp--parser-waiting-for-response p) nil)
                    (error "Error parsing language server output: %s" err))))))
          (dolist (m messages)
            (when lsp-print-io
              (let ((inhibit-message t))
                (lsp-message "<<<< %s\n%s"
                             (-> p lsp--parser-workspace lsp--workspace-print)
                             (lsp--json-pretty-print m))))
            (lsp--parser-on-message p m))))))
```

**Comment by l7ssha** [comment]
Weird, I set lexical-binding to t, anyway I'll do test on more time. You can use my [nyxx project](https://github.com/l7ssha/nyxx), but I have issues with every dart project.

Also this is my emacs config: https://github.com/l7ssha/dotfiles/blob/master/.emacs.d/init.el

https://gist.github.com/l7ssha/3048fa9f5ef636ace70bc4f03704089b

**Comment by yyoncho** [comment]
Hm, unless I am missing something I am unable to find any errors in the last log and everything seems to be working fine so the original issue was not reproduced in the latest log. The version that  you use for testing was not based on the last code changes though. 
I will try your project and let you know how it works on my side. I found at least 2 issues with dart server that I am going to fix but they were unrelated to your issue.

**Comment by yyoncho** [comment]
So I did test with your project and apart from a bug in applying code action I did not hit any errors. Everything code completion, hovers, references, implementations seems to be working fine. Also, I noticed that your config seems to be out of date. For example `lsp-define-stdio-client` is no longer relevant. The only config that you need in the latest version is:

1. Install lsp-mode/lsp-ui/company-lsp
2. Call `lsp` in the dart file.

I would suggest trying to reproduce the error using the code from https://github.com/emacs-lsp/lsp-mode/issues/577#issuecomment-449644369 since at this point it is not clear to me what is causing the failures(preferably with `toggle-debug-on-errors`) and also the error is not present in the logs from https://github.com/emacs-lsp/lsp-mode/issues/577#issuecomment-449645556. Based on the error text bellow I even suspect  that the error might be somewhere in markdown-mode which fails to render the content that lsp-mode is sending to it.

> error in process filter: face-attr-match-p: Wrong type argument: plistp, (:background "#100e23" :foreground "#565575" :bold)
> error in process filter: Wrong type argument: plistp, (:background "#100e23" :foreground "#565575" :bold)

**Comment by l7ssha** [comment]
To close. Theme I'm using apparently has several problems with lsp - lsp is good here.
