### ISSUE TITLE
js2-mode and derived modes displays lag when typing in large files (300 lines of code or more)

### ISSUE THREAD

**Issue by shackra** [emacs-lsp/lsp-mode#588]
**Describe the bug**
When lsp-mode is turned on in js2-mode and derived modes, like rjsx-mode, typing is a painful experience full of lag (1 or 2 seconds or even more depending on how fast you are writing code).

**To Reproduce**

1. Run `emacs -q`
1. Load the configuration [bug.txt](https://github.com/emacs-lsp/lsp-mode/files/2719137/bug.txt).
1. Download and uncompressed the frontend of one of my projects 
[fero.zip](https://github.com/emacs-lsp/lsp-mode/files/2719127/fero.zip)
1. visit the file `src/components/Invoice/detalle.jsx`
1. finally, go anywhere and hold any key, you should see lag.
1. extra: put `:disabled` under `(use-package lsp` to disabled lsp-mode, then try to reproduce, you will see that typing is smooth again.

**Expected behavior**
no lag at all like typing in large files with go-mode or python-mode and lsp-mode running.

**Which Language Server did you use**
this is included with the configuration.

**OS**
GNU/Linux (Arch)

This happens with lsp-mode version 20181228.819 and **only** on js2-mode derived modes.

**Comment by MaskRay** [comment]
1. This is apparently a server issue
2. I don't think grouping texDocument/didChange is necessary

```typescript
// src/typescript-service.ts
    public async textDocumentDidChange(params: DidChangeTextDocumentParams): Promise<void> {
        const uri = normalizeUri(params.textDocument.uri)
        let text: string | undefined
        for (const change of params.contentChanges) {
            if (change.range || change.rangeLength) {
                throw new Error('incremental updates in textDocument/didChange not supported for file ' + uri)
            }
            text = change.text
        }
        if (!text) {
```

**Comment by yyoncho** [comment]
@MaskRay IMO it is not server side issue since full sync is a valid option according to latest LSP spec and we should provide reasonable handling/performance. I am thinking about adding client-side debounce only for full sync text messages.
