### ISSUE TITLE
YaSnippet completion is putting the completed text in the wrong location

### ISSUE THREAD

**Issue by DougBeney** [emacs-lsp/lsp-mode#589]
I am not sure if this is an issue with YaSnippet or an issue with the way that lsp-mode interfaces with YaSnippet. Do let me know if I should post this elsewhere. 

[Here's the problem](https://imgur.com/VIdA7J3). I am trying to use a completion and it puts the completed text in the wrong location. 

From what it looks like, YaSnippet checks the parameter list and finds the first instance of the text before the completion. In this example it is "error." - and once it finds that first occurrence, it appends there rather than where it is supposed to. 

lsp-mode version: 20190101.1354

YaSnippet version: 20181015.1212

**Comment by yyoncho** [comment]
It seems like a company-lsp issue, can you file it in that repo? To confirm that, can you retest with company-lsp-cache-candidates set to nil?
@tigersoldier

**Comment by DougBeney** [comment]
Ok, will do. Now of course I'm having trouble reproducing the issue :/

**Comment by DougBeney** [comment]
Managed to reproduce it but after `(setq company-lsp-cache-candidates nil)` it still does the same thing. I'll report it to company-lsp.
