### ISSUE TITLE
Server logging messing with the message area

### ISSUE THREAD

**Issue by xendk** [emacs-lsp/lsp-mode#599]
**Describe the bug**
When loading large projects, php-language-server produces a lot of logging about what it parses, which seems to make messages in the echo area disappear and eldoc tips flicker.  

Apart from it makes emacs seem flaky while it's scanning, it makes the UX suffer as messages disappear to quickly to be read, and helpful prompts, like the `C-x-`one gets after pressing a prefix key, gets lost.

**To Reproduce**
You'll need a large PHP codebase:
```sh
cd /tmp
wget https://www.drupal.org/download-latest/tar.gz
tar -zxf tar.gz
```
Open `drupal-8.6.7/core/lib/Drupal.php` and check the message buffer to see the logging. Notice that pressing `C-x` looses the usual prompt and eldoc messages flicker.

**Expected behavior**
No flickering and that messages stick around as they used to.

**Which Language Server did you use**
lsp-php

**OS**
Ubuntu 18.10

**Error callstack**
No errors.

**Attempted fixes**
I've tried a few hacks to try and fix it, without success: I've tried making `lsp-message` use `(current-message)` instead of `eldoc-last-message` and I've tried making it just call `(message)`, neither which seemed to do much difference. Tried copying `:ignore-regexps '("\"message\":\"Parsing file:" "\"message\":\"Restored .*from cache")` from https://github.com/emacs-lsp/lsp-php/, which suppressed the messages in the message buffer, but also seemed to kill everything that lsp-ui added (sideline, docs, etc).

**Comment by yyoncho** [comment]
We need to investigate `with-temp-message` as well. 

I am aware of the issue and tried to fix it with creating `lsp-message` but it seems like it is not sufficient. If the suggestion above does not fix the issue we may create a separate buffer for message logging.

**Comment by xendk** [comment]
I'll try to find some time to give it a shot.
