### ISSUE TITLE
how to use particular mode from git

### ISSUE THREAD

**Issue by m4b** [emacs-lsp/lsp-mode#60]
Trying to test this, I've noticed the clients are separate repos, yet it isn't obvious to me how to use a particular language server client now; do we need to clone in the subdirectory, add it to new load path in `.emacs`, etc.?

**Comment by alanz** [comment]
This is what I am doing: https://github.com/alanz/lsp-haskell/blob/master/README.md

**Comment by m4b** [comment]
Hmmm, I tried this, but i get this error:

```
Debugger entered: ((cl-assertion-failed client "rust-mode doesn't have a defined client"))
  cl--assertion-failed(client "rust-mode doesn't have a defined client" nil nil)
  (or client (cl--assertion-failed (quote client) (format "%s doesn't have a defined client" mode) (list) (list)))
  (progn (or client (cl--assertion-failed (quote client) (format "%s doesn't have a defined client" mode) (list) (list))) nil)
  (let ((client (gethash mode lsp--defined-clients nil))) (progn (or client (cl--assertion-failed (quote client) (format "%s doesn't have a defined client" mode) (list) (list))) nil) (puthash method callback (progn nil (or (progn nil (and (vectorp client) (>= (length client) 9) (memq (aref client 0) cl-struct-lsp--client-tags) t)) (signal (quote wrong-type-argument) (list (quote lsp--client) client))) (aref client 8))))
  lsp-client-on-notification(rust-mode "rustDocument/diagnosticsBegin" (lambda (_w _p)))
  eval-buffer(#<buffer  *load*-84074> nil "/home/m4b/git/lsp-rust/lsp-rust.el" nil t)  ; Reading at buffer position 867
  load-with-code-conversion("/home/m4b/git/lsp-rust/lsp-rust.el" "/home/m4b/git/lsp-rust/lsp-rust.el" nil t)
  require(lsp-rust)
  eval-buffer(#<buffer  *load*> nil "/home/m4b/.emacs" nil t)  ; Reading at buffer position 4906
  load-with-code-conversion("/home/m4b/.emacs" "/home/m4b/.emacs" t t)
  load("~/.emacs" t t)
```

**Comment by alanz** [comment]
If [this](https://github.com/emacs-lsp/lsp-rust/blob/master/lsp-rust.el) is in your load path and you do

```elisp
(require 'lsp-rust)
(require 'lsp-mode)
(global-lsp-mode t)
```

It should work?

**Comment by vibhavp** [comment]
Language support has been split into different packages. I've submitted a PR to the melpa repo: https://github.com/melpa/melpa/pull/4718

You should be able to install `lsp-rust` soon.

**Comment by m4b** [comment]
following @alanz readme works for haskell ide, but rust still broken.

Pretty sure its these lines:

https://github.com/emacs-lsp/lsp-rust/blob/0803f16d9ac18dd1a7b3c66389bfba5ad1bd0513/lsp-rust.el#L27-L30

**Comment by vibhavp** [comment]
Those lines simply add handlers for the custom diagnostics handlers in rls. Doubt that could be the issue. I'll try setting up rls myself and see if it can be reproduced.

**Comment by vibhavp** [comment]
Oops, those lines are the issue. The handlers are being defined _before_ the rust lsp client is defined. Will push a fix, thanks.

**Comment by m4b** [comment]
Was about to push :) also I fixed another error about to report
