### ISSUE TITLE
It seems lsp-project-blacklist and lsp-project-whitelist no longer do anything

### ISSUE THREAD

**Issue by alanz** [emacs-lsp/lsp-mode#605]
**Describe the bug**
If I start a lsp session on a project, using a particular GHC compiler, I get asked to add the root as a session, and then `lsp-mode` works for the project.

If I then switch to an unsupported compiler, where lsp-mode doesn't work, I can't turn off lsp-mode

**To Reproduce**

Update whitelist and blacklist to be
```elisp
 '(lsp-project-blacklist (quote (".*")))
 '(lsp-project-whitelist
   (quote
    ("^/home/alanz/mysrc/github/some-other-project/$" )))
```
Open a project that is not in the whitelist, but was added to the session.

**Expected behavior**
lsp-mode does not start

**Which Language Server did you use**
haskell-ide-engine

**OS**
Debian Testing

**Error callstack**
N/A

**Comment by yyoncho** [comment]
These settings were replaced by `(lsp-session-folders-blacklist session)` and `(lsp-session-folders ...)` in the new version. You do not need to add them manually but you could add them after you open a file from a project for the first time. If you have already added the folder to be part of the session you may remove it and the next time you call `lsp` in the current project you may add it to the blacklist.

**Comment by alanz** [comment]
Ok, the functions seem to be called `lsp-workspace-folders-add` and `lsp-workspace-folders-remove`.
