### ISSUE TITLE
Create custom activation function for typescript servers (was typescript/tsx assumes spacemacs usage)

### ISSUE THREAD

**Issue by cwhatley** [emacs-lsp/lsp-mode#610]
**Describe the bug**
The current version activates the typescript lang server for typescript-tsx-mode which only exists for spacemacs users. Would be good to add a faq entry with a suggested typescript/tsx configuration like what I have below. This is just a copy of the spacemacs approach, but it is useful to demonstrate how to target a language server with something like web-mode that supports multiple languages.;

Here's a faq entry you could drop in:

* Web-mode, by default is set up for an HTML language server. If you use web-mode for TSX/React, you can define a derived mode as follows that will trigger the use of the typescript language server. This is not necessary if you are using spacemacs since it already handles the creation of the derived mode.

```
(use-package web-mode
  :config
  (define-derived-mode typescript-tsx-mode web-mode "TypeScript-tsx")
  (add-to-list 'auto-mode-alist '("\\.tsx\\'" . typescript-tsx-mode)))
```

**Comment by yyoncho** [comment]
As far as I can see typescript server is enabled in the following modes: `(typescript-mode typescript-tsx-mode js-mode js2-mode rjsx-mode)` and typescript-mode is not part of spacemacs.

**Comment by cwhatley** [comment]
typescript-tsx-mode is not an existing mode you can find defined in a package on melpa/elpa other than being defined by in typescript config of spacemacs:

https://github.com/syl20bnr/spacemacs/blob/a46b784e85911afe8bd6648ca55c080ffae1081c/layers/%2Blang/typescript/packages.el#L99

I'm assuming whomever contributed that list of modes was a spacemacs user. My suggestion here is just to document what non-spacemacsers would need to do to get it working.

**Comment by yyoncho** [comment]
You do not have to define **all** the layers that a particular server is defined. I believe that your sample will be useful for someone that wants to use typescript server in web-mode derived major mode but it is not must have if you want to use the typescript server(e. g. you may install typescript-mode).

**Comment by cwhatley** [comment]
You are correct that it is fine for regular typescript, but please note that I'm not talking strictly about typescript. It is a must-have if you want to have LSP working with TSX/React which is best supported now by web-mode. Most people use web-mode for TSX since rjsx-mode doesn't support typescript. Since LSP is triggering its config off of the buffer's mode, this workaround is necessary.

Fundamentally the issue here I am trying to address that lsp-mode has implicitly based its auto-config for TSX on a "develop" branch of another package.

**Comment by yyoncho** [comment]
Make sense. @danielmartin introduced a new way to configure to select a server `:activation-fn` (see https://github.com/emacs-lsp/lsp-mode/commit/960d06f7b5b7fcace9c840a7dbc2a2d3fd267172) . IMO it makes more sense to have a custom activation function for typescript(ideally implemented by someone with typescript experience) . What do you think?

**Comment by cwhatley** [comment]
That's a much better option than the derived mode approach.

**Comment by cwhatley** [comment]
@yyoncho I added a simple PR for that.
