### ISSUE TITLE
5 failing tests while building on Debian

### ISSUE THREAD

**Issue by thkoch2001** [emacs-lsp/lsp-mode#612]
I'm packaging version 6.0 now for Debian. 5 tests fail now:

1.   FAILED  lsp--parser-read--ignored-messages
2.   FAILED  lsp--test-overlapping-updates
3.   FAILED  lsp-file-watch--notifications
4.   FAILED  lsp-file-watch--relative-path
 5.  FAILED  lsp-file-watch--relative-path-glob-patterns

I reported the lsp-file-watch--* failures already in https://github.com/emacs-lsp/lsp-mode/issues/467.

This is the full build log with elisp backtraces and full dependencies:
[lsp-mode_6.0-1_amd64-2019-01-21T21:35:31Z.build.txt](https://github.com/emacs-lsp/lsp-mode/files/2784245/lsp-mode_6.0-1_amd64-2019-01-21T21.35.31Z.build.txt)

Tests 1. and 2. fail with `(void-variable method)` or `(void-variable range)` respectively.

maybe relevant dependencies:

elpa-dash (2.14.1+dfsg-1)
elpa-f (0.20.0-1)
elpa-ht (2.2-1)
elpa-s (1.12.0-2)
elpa-spinner (1.7.3-1)
emacs-nox (1:26.1+1-3)

I've no experience with elisp, so I'd be thankful for help here.

**Comment by yyoncho** [comment]
> Tests 1. and 2 

This is caused by dash being old. We are using smart destructuring which is available only in the latest dash.
@fuco1 do you have plans for releasing new dash version?

**Comment by thkoch2001** [comment]
We only have a few days left for updates to get into the next Debian stable. Do you think there is a way you could change your code to work with dash 2.14? I doubt we will be able to have an upstream release and a debian release of dash 2.20 and handle all possible problems that the dash upgrade might cause in other Debian packages.

**Comment by yyoncho** [comment]
I think that I could do that change if this is the only option. What is the deadline?

**Comment by Fuco1** [comment]
Out of curiosity why are we packaging Emacs packages for Debian?

Yes, new version of dash is quite necessary.  I'm going to release 2.15 right now.  It's been stable and we are just lazy to click the button.

**Comment by thkoch2001** [comment]
@yyoncho Thanks a lot!

The final deadline is March 1st. If an error is found afterwards there is no option to upload a fix anymore.
https://lists.debian.org/debian-devel-announce/2019/01/msg00008.html

@Fuco1: https://wiki.debian.org/AdvantagesForUpstream - It was my initiative to package this for Debian, nobody else in the emacs-lsp is involved. There are people who prefer all their software to come from a Debian repo.

**Comment by Fuco1** [comment]
I've just released dash 2.15.

**Comment by yyoncho** [comment]
@Fuco1 thanks!

@thkoch2001 can you comment whether we still need to change `lsp-mode` to work with dash 2.14.1?

**Comment by yyoncho** [comment]
As a side note, I will take a look at the other 3 failing tests with higher priority. I believe that the issue is caused by the different behaviour of file notify libraries. Can you provide more details on the Debian version on which the tests are failing? Link to ISO file will work too.

**Comment by thkoch2001** [comment]
I managed to reproduce the 3 lsp-file-watch-* failures on a Debian stable with the dependencies installed via melpa-stable and this command line:

    emacs -batch -Q -l package --eval "(add-to-list 'package-directory-list \"~/.emacs.d/elpa\")" -f package-initialize -L . -L test -l ert -l test/lsp-common-test.el -l test/lsp-file-watch-test.el -l test/lsp-io-test.el -l test/lsp-methods-test.el -f ert-run-tests-batch-and-exit

I've no other packages installed in ~/.emacs.d/elpa:

dash-2.15.0
dash-functional-2.15.0
f-0.20.0
ht-2.2
s-1.12.0
spinner-1.7.3

In an earlier run I still used dash-2.12 from Debian stable and also saw the other 2 test failures. So updating to 2.15 indeed fixes those.

I've also asked for advice whether we will be able to package dash 2.15 in the next days, maybe I'll do it myself: https://lists.debian.org/debian-emacsen/2019/01/msg00037.html

(Sorry for referring to dash 2.20 previously, that was a mistake.)

**Comment by thkoch2001** [comment]
So according to this https://lists.debian.org/debian-emacsen/2019/01/msg00038.html we will not have dash-2.15 in Debian Buster:

> "I think that this would count as a transition, because dash-el has many
> r-deps, so it is forbidden by the transitions freeze.  Let's wait until
> after buster."

So if it would be possible to make lsp-mode work with dash-2.14, that would be nice.

**Comment by Fuco1** [comment]
Note that the last change to the code was 4 months ago.  We only forgot to tag the release.

**Comment by yyoncho** [comment]
@thkoch2001 ok, I will try to fix it during the weekend.

**Comment by yyoncho** [comment]
PR here - https://github.com/emacs-lsp/lsp-mode/pull/628

@thkoch2001 do we need to make lsp-ui work against dash 2.14.1 too?

**Comment by thkoch2001** [comment]
Thank you @yyoncho! My motivation is lsp-haskell, so everything in its dependency closure should depend on stuff in Debian. To my understanding this means lsp-ui must also work with dash 2.14.1.

So thank you again for asking: yes.

**Comment by yyoncho** [comment]
@thkoch2001 here are lsp-ui changes - https://github.com/yyoncho/lsp-ui/tree/dash2.14.1
