### ISSUE TITLE
void-function contains\?

### ISSUE THREAD

**Issue by seagle0128** [emacs-lsp/lsp-mode#616]
Emacs 26.1
macOS Mojave
lsp-mode-20190123.652

Should it be `-contains?`?

```elisp
Debugger entered--Lisp error: (void-function contains\?)
  contains\?((python-mode) python-mode)
  lsp--try-open-in-library-workspace()
  lsp()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook python-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook python-mode-hook))
  run-mode-hooks(python-mode-hook)
  python-mode()
  set-auto-mode-0(python-mode nil)
  set-auto-mode()
  normal-mode(t)
```

**Comment by yyoncho** [comment]
Sorry about that: fixed with https://github.com/emacs-lsp/lsp-mode/commit/79cedadde65b17bd9e7c5f6a049ed1c3ee9d8e63

I am planning to move lsp-java integration tests in that repo to avoid such issues in the future.

**Comment by seagle0128** [comment]
Yeah, UT or IT are necessary for the rapid developments. Thank you for quick fixing!

**Comment by yyoncho** [comment]
I will keep it open until melpa kick in.
