### ISSUE TITLE
Disable flycheck in lsp-mode with ccls

### ISSUE THREAD

**Issue by mwbuksas** [emacs-lsp/lsp-mode#618]
I'm having problems with accurate results from flymake in my setup with ccls. I'd like to get these sorted out eventually, but in the meantime it would be nice to just disable flymake It is currently enabled automatically in every new buffer.

I don't believe that I'm doing anything to activate it, as my lsp configuraton is pretty minimal. Is there an option in lsp to turn it off?

My lsp/ccls configuraton code:

```
(use-package lsp-mode :commands lsp)
(use-package lsp-ui :commands lsp-ui-mode)
(use-package company-lsp :commands company-lsp)
(use-package ccls
  :defer
  :hook ((c-mode c++-mode objc-mode) .
         (lambda () (require 'ccls) (lsp))))
```

Edit: Originally said flycheck. It's actually flymake.

**Comment by yyoncho** [comment]
LSP mode has a default configuration which is in `lsp--auto-configure` you may turn off that by setting `lsp-auto-configure` to `nil` but you have to take care for configuring the rest of the components by yourself.
