### ISSUE TITLE
lsp enabled on emacs built-in package file and connected to a running pyls server

### ISSUE THREAD

**Issue by twlz0ne** [emacs-lsp/lsp-mode#625]
**Describe the bug**

lsp enabled on emacs built-in package file and connected to a running pyls server

![screenshot_2019-01-24_at_5_39_58_pm](https://user-images.githubusercontent.com/2653486/51750775-0d5cc680-20ee-11e9-8b18-7510cdbbf32b.png)

![screenshot_2019-01-24_at_5_41_11_pm](https://user-images.githubusercontent.com/2653486/51750803-1c437900-20ee-11e9-97da-d150c76c2005.png)

**To Reproduce**

1. Launch Emacs with `-nw` option
1. Open a python project
1. Enable lsp
1. `M-x xref-find-definitions setf REG` to open gv.el.gz
1. Check mode-line

    Or borrow some code from `lsp--try-open-in-library-workspace` to check:
    
```elisp
(with-current-buffer (get-buffer "gv.el.gz")
  (when-let (workspace
             (->> (lsp-session)
                  (lsp--session-workspaces)
                  (--first
                   (when-let (library-folders-fn
                              (-> it lsp--workspace-client lsp--client-library-folders-fn))
                     (-first (lambda (library-folder)
                               (f-ancestor-of? library-folder (buffer-file-name)))
                             (funcall library-folders-fn it))))))
    (cons
     (-> workspace (lsp--workspace-client) (lsp--client-server-id))
     (buffer-file-name))))
;; => (pyls . "/usr/local/Cellar/emacs/HEAD-4f0e542_1/share/emacs/27.0.50/lisp/emacs-lisp/gv.el.gz")
```
    
Because `(f-ancestor-of? library-folder (buffer-file-name))` always return `t` when openning any file under `/usr/`.
 
**Expected behavior**

DO NOT connect pyls when openning emacs built-in package file.

**Which Language Server did you use**

python.

golang should have this issue too:

```
      ;; lsp-clients.el
  33| (defcustom lsp-clients-python-library-directories '("/usr/")
 205| (defcustom lsp-clients-go-library-directories '("/usr")
```

**Environment**

- macOS 10.11.6
- Emacs 27.0.50 (Install via Homebrew)
- lsp (master: 390a7ce)

**Comment by yyoncho** [comment]
Fixed by https://github.com/emacs-lsp/lsp-mode/commit/63a421af9354ed300b1082e20b067baf2ac2e8d3 (you need also https://github.com/emacs-lsp/lsp-mode/commit/79cedadde65b17bd9e7c5f6a049ed1c3ee9d8e63)
