### ISSUE TITLE
We need a logo

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#629]

**Comment by seagle0128** [comment]
I agree. I rewrote the lsp indicator for `doom-modeline`, and added a `rocket` icon. I hope lsp-mode is like a `rocket` to speed up the development :-)

![image](https://user-images.githubusercontent.com/140797/53436089-f0891b00-3a2c-11e9-81b4-4adf8f3f56d3.png)

**Comment by joncarr** [comment]
Any ideas as to what you would like the logo to express?  How do you plan on using the logo and where would this logo be displayed?

**Comment by yyoncho** [comment]
> Any ideas as to what you would like the logo to express? How do you plan on using the logo and where would this logo be displayed?

In the readme page, profile picture for the organization, twitter account(and similar).

Here are some examples: 
https://github.com/magit/magit 
https://gitter.im/syl20bnr/spacemacs 
https://github.com/clojure-emacs/cider

**Comment by joncarr** [comment]
Would you like the text (if used in the logo) to say "Emacs-LSP" "lsp-mode" or something similar?  Sorry for all the questions, just trying to get the details....perhaps gitter is a better place for this conversation?

**Comment by yyoncho** [comment]
> Any ideas as to what you would like the logo to express?

(forgot to answer this question).
My personal opinion is that it should be expressing that `lsp-mode`(+related) brings IDE experience to Emacs - "IDE for power users" other contributors might have different ideas though.

**Comment by yyoncho** [comment]
@joncarr lets move the discussion in gitter, then we can summarize it here.

**Comment by joncarr** [comment]
Here is an idea I had.  The dots off to the left represent the many clients/languages emacs-lsp supports, all of which being channeled into a a single interface which is representative of emacs-lsp itself.  Criticisms/thoughts/ideas/moans/groans all welcome

![lsp-mode_001](https://user-images.githubusercontent.com/564071/54149881-35d22300-4405-11e9-9051-1e8980c28a40.png)

**Comment by joncarr** [comment]
![emacs_lsp_banner](https://user-images.githubusercontent.com/564071/54164442-a475a780-442a-11e9-951e-e7c767369451.png)
![emacs_lsp_core_banner](https://user-images.githubusercontent.com/564071/54164443-a475a780-442a-11e9-9a71-278172cc5363.png)
![emacs_lsp_debugger_banner](https://user-images.githubusercontent.com/564071/54164444-a475a780-442a-11e9-9f86-ab3fddca5b63.png)
![emacs_lsp_ide_banner](https://user-images.githubusercontent.com/564071/54164445-a475a780-442a-11e9-8e06-5252b120df2a.png)
![emacs_lsp_badge_dark](https://user-images.githubusercontent.com/564071/54164449-af303c80-442a-11e9-9754-877932df6237.png)
![emacs_lsp_badge_light](https://user-images.githubusercontent.com/564071/54164450-af303c80-442a-11e9-9e69-5e784a5bcf13.png)
![lsp_core_square_opaque_back](https://user-images.githubusercontent.com/564071/54164461-b8b9a480-442a-11e9-8caa-201b4c2101de.png)
![lsp_debugger_square_opaque_back](https://user-images.githubusercontent.com/564071/54164462-b8b9a480-442a-11e9-8a89-d234fcd2be97.png)
![lsp_ide_square_opaque_back](https://user-images.githubusercontent.com/564071/54164463-b8b9a480-442a-11e9-8941-4df5cf0ff3cf.png)
![lsp_square_opaque_back](https://user-images.githubusercontent.com/564071/54164464-b8b9a480-442a-11e9-84a0-2513004cad73.png)
[emacs-lsp-source.zip](https://github.com/emacs-lsp/lsp-mode/files/2954554/emacs-lsp-source.zip)

**Comment by joncarr** [comment]
See Archive at bottom of last comment `emacs-lsp-source.zip`

**Comment by yyoncho** [comment]
@vibhavp what do you think about using this https://user-images.githubusercontent.com/564071/54164464-b8b9a480-442a-11e9-84a0-2513004cad73.png for organization header and this one for startup page: https://user-images.githubusercontent.com/564071/54164442-a475a780-442a-11e9-951e-e7c767369451.png

**Comment by vibhavp** [comment]
Yeah, both look great.

**Comment by yyoncho** [comment]
@joncarr I have configured the organization icon but I was unable to place the other icon on the start page. Do you wanna try to update the readme and put the https://user-images.githubusercontent.com/564071/54164442-a475a780-442a-11e9-951e-e7c767369451.png in a way that it looks ok? @vibhavp  we have to create a Credit section to list valuable contributions.

**Comment by joncarr** [comment]
Not a problem, I'll try to get to it soon.

**Comment by joncarr** [comment]
omg....github ignores org mode attributes!!!  Killing me!!  lol

**Comment by shuxiao9058** [comment]
> @joncarr I have configured the organization icon but I was unable to place the other icon on the start page. Do you wanna try to update the readme and put the https://user-images.githubusercontent.com/564071/54164442-a475a780-442a-11e9-951e-e7c767369451.png in a way that it looks ok? @vibhavp  we have to create a Credit section to list valuable contributions. 

the logo is too complicated！
