### ISSUE TITLE
LSP :: No LSP server for c++-mode

### ISSUE THREAD

**Issue by bradprob** [emacs-lsp/lsp-mode#630]
Hi,
Trying to use lsp-mode with this configuration:
```
(use-package company-lsp
    :ensure t
    :config
    (require 'company-lsp)
    (push 'company-lsp company-backends)
    (add-hook 'after-init-hook 'global-company-mode))

  (use-package lsp-mode
    :ensure t
    :config
    (require 'lsp-mode)
    (require 'lsp-clients)
    (add-hook 'c++-mode-hook 'lsp)
    (add-hook 'c-mode-hook 'lsp)
    (add-hook 'python-mode-hook 'lsp))

  (use-package lsp-ui
    :ensure t
    :config
    (require 'lsp-ui))
```
When I open a .cpp file from a project I receive this:
`LSP :: No LSP server for c++-mode.`
Emacs: `GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.2) of 2018-12-26, modified by Debian`
clangd: `clangd-7`
Do you know what I am doing wrongly?

**Comment by yyoncho** [comment]
What does `(executable-find "clangd")` returns?

**Comment by bradprob** [comment]
empty!

**Comment by yyoncho** [comment]
make sure that "clangd" is on the path or do (setq lsp-clients-clangd-executable "path to clangd")

**Comment by bradprob** [comment]
Thanks! It seems that it caused the issue.

**Comment by VisionaryAppDev** [comment]
@yyoncho  I did face the same problem with "LSP :: No LSP server for js-mode". Please help me figure out what is going on. Here is my below configuration:

> (use-package lsp-ui :commands lsp-ui-mode)
(use-package company-lsp :commands company-lsp)
(require 'lsp-clients)
(add-hook 'js2-mode-hook #'lsp)
(add-hook 'js-mode-hook #'lsp)

;; I am not sure which one of them should I use so i put both. 
> (setq lsp-clients-typescript-server "/home/user/Data/npm/.npm-global/bin/typescript-language-server"
      lsp-clients-typescript-server-args  '("--stdio"))
> (setq lsp-clients-javascript-typescript-server "/home/user/Data/npm/.npm-global/bin/typescript-language-server")


I have execute "npm i -g typescript-language-server" successfully and get "/home/user/Data/npm/.npm-global/bin/typescript-language-server ->  /home/user/Data/npm/.npm-global/lib/node_modules/typescript-language-server/lib/cli.js typescript-language-server@0.3.7" as an output.

Before running emacs, i have run typescript-language-server by calling "./typescript-language-server" and then open js file and nothing is working.

**Comment by yyoncho** [comment]
@VisionaryAppDev lsp-mode is using `executable-find` to determine whether a particular client is present. I add some more logging to help diagnosing this kind of issues.

**Comment by yyoncho** [comment]
@VisionaryAppDev pushed https://github.com/emacs-lsp/lsp-mode/commit/89cd1d6654793f7413f7a1eea3e0ac6870015001 - improves the logging related to server selection.

**Comment by VisionaryAppDev** [comment]
@[yyoncho](/yyoncho) Now I have upgrade to the latest version and when I start open js file I got some log but i am not sure what is going on.

`LSP :: Connected to [ts-ls:30167 status:starting].
which-func-ff-hook error: (error "No workspace could handle textDocument/documentSymbol")
LSP :: Request initialize failed with message: Couldn't find 'tsserver' executable or 'tsserver.js' module
`

**Comment by yyoncho** [comment]
@VisionaryAppDev can you do `npm i -g typescript` ? I will update the readme to mention that too.

**Comment by VisionaryAppDev** [comment]
@yyoncho it is working now but I have to put (setq lsp-clients... above otherwise emacs cannot find lsp-server again. I put something like below: 
`(setq lsp-clients-typescript-server "/home/Data/npm/.npm-global/bin/typescript-language-server"
      lsp-clients-typescript-server-args  '("--stdio"))`
`(setq lsp-clients-javascript-typescript-server "/home/Data/npm/.npm-global/bin/typescript-language-server")`

`(use-package lsp-ui :commands lsp-ui-mode)`
`(use-package company-lsp :commands company-lsp)`
`(require 'lsp-clients)`
`(add-hook 'js2-mode-hook #'lsp)`
`(add-hook 'js-mode-hook #'lsp)`


Anyway, i think it's quite slow. It take around 500 or so just to show completion/suggestion while typing and during the time emacs also unresponsive.

**Comment by rsansores** [comment]
Facing the same problem,

This is in my emacs init configuration file:

```
(use-package lsp-mode
:ensure t
:config
(require 'lsp-clients)
(add-hook 'typescript-mode-hook 'lsp)
(use-package lsp-ui :commands lsp-ui-mode)
(use-package company-lsp :commands company-lsp)
```
I already installed globally typescript and typescript-lang-server. Added "~/.node-modules/bin/" to path thru /etc/profile and I can see in PATH typescript-language-server.

Tried the workaround of @VisionaryAppDev with no luck:

```
(setq lsp-clients-typescript-server "~/.node-modules/bin/typescript-language-server" lsp-clients-typescript-server-args '("--stdio"))
(setq lsp-clients-javascript-typescript-server "~/.node-modules/bin/typescript-language-server")
```

I always get the error: LSP :: No LSP server for typescript-mode.

**Comment by yyoncho** [comment]
> I already installed globally typescript and typescript-lang-server. Added "~/.node-modules/bin/" to path thru /etc/profile and I can see in PATH typescript-language-server.

Emacs should be able to find it via `executable-find`. I assume that the path is not propagated properly to it.


> Why is typescript-language-server the recommended server?
I looked into the github project and there have been no commits in 3 months while javascript-typescript-stdio have commits just today. It looks like a more mantained project.

> What are the tradeoffs?

This might no longer be the case. It when I was testing them typescript language server was providing better code actions. So we need someone(a javascript developer) to verify whether this is still the case.

**Comment by rsansores** [comment]
I can do the testing and provide a complete report between each server in order to improve the documentation of lsp-mode. I just need some advice about how to switch between servers. Are you interested that I run the the testing?

I have both servers installed and correctly configured in path. My current configuration is this:

```
(use-package lsp-mode
  :ensure t
  :config
  (require 'lsp-clients)
  (use-package lsp-ui :commands lsp-ui-mode)
  (use-package company-lsp :commands company-lsp))

(require 'typescript-mode)
(add-to-list 'auto-mode-alist '("\\.tsx?\\'" . typescript-mode))
(add-hook 'typescript-mode-hook #'lsp)
```
I don't see in the configuration anything related to the server so I think the server is being chosen when executing (require 'by lsp-clients).

What do I need to change or add to specify the server to use?

Is there a lsp-something command that allow me to verify which server is being executed?

Let me congratulate all the people that is maintaining this project!

**Comment by yyoncho** [comment]
@rsansores 

> Are you interested that I run the the testing?

We are interested in and encourage in any activity which will help us to improve lsp-mode's Emacs experience.

> I just need some advice about how to switch between servers. 

The servers are selected based on the priority (https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-clients.el#L140) and the presence of the server(you may check \*lsp-log\* buffer which logs some information about that). There are at least 5+ methods to change the server you are using using lsp-mode public API (e. g. if you unregister one of the servers(lsp-clients variable), by changing the binary to non existent one, by altering the priorities and reevaluating the buffers, etc). I think that the easiest is to use `lsp-enabled-clients` E. g. `(setq lsp-enabled-clients '(ts-ls))` will enable the typescript language server. Use `jsts-ls` for the other server.

> Is there a lsp-something command that allow me to verify which server is being executed?

Yes, there is lsp-describe-session. Also you may check lsp-log buffer. And finally, lsp-mode-line is showing which server has been selected. I guess you are using a modeline that is hiding it...


If you run into any issue or have more questions you may use the gitter chat as well.

**Comment by VisionaryAppDev** [comment]
>What do I need to change or add to specify the server to use?

If to change, I think create this interactive function might be easy especially when we need to switch back and forward.
```
(defun switching-ts-server()
  (interactive)
  (setq lsp-clients-typescript-server "~/.node-modules/bin/typescript-language-server" lsp-clients-typescript-server-args '("--stdio"))
  (setq lsp-clients-javascript-typescript-server nil))


(defun switching-js-server()
  (interactive)
  (setq lsp-clients-typescript-server nil)
  (setq lsp-clients-javascript-typescript-server "~/.node-modules/bin/typescript-language-server"))
```

Switching by calling **switching-js-server** or **switching-ts-server** and then call **lsp** to restart server.
