### ISSUE TITLE
flymake error

### ISSUE THREAD

**Issue by bradprob** [emacs-lsp/lsp-mode#631]
Hi,
I am trying to check my c++ code with flymake in a directory structure like:
```
root
 |___ src
 |___ test
 |___ libs
 |___ includes
 |___ build
           |____ debug
           |____ release
```
I build the project with camke and ninja. 
When I open xxx.cpp, flymake seems to check the code (markers are shown), though the flymake log buffer contains the following error:
Error [flymake-proc xxx.cpp]: NOMK: No buildfile (Makefile) found for root/src/xxx.cpp
Can you help please?

**Comment by yyoncho** [comment]
Can you provide some more information, e. g. Which language server do you use?
I suspect that the error is coming from legacy flymake cpp backend which I disable with 

```
  (add-hook 'c++-mode-hook
            (lambda ()
              (setq flymake-diagnostic-functions (list 'lsp--flymake-backend))))
```
Let me know whether this fixes your issue.

**Comment by bradprob** [comment]
flymake still does not work; I'll look for a solution. Thanks!
