### ISSUE TITLE
imenu items are trimmed to certain length

### ISSUE THREAD

**Issue by Coffei** [emacs-lsp/lsp-mode#634]
**Describe the bug**
imenu items (e.g. functions in a file) are trimmed to certain length, which sometimes loses the important information at the end (e.g. parameters). I experience this problem in elixir where module names can be long.

Check images at https://imgur.com/a/UHbwd1N, see the arguments of function `pris` are trimmed and if the function would have longer name event the name would be trimmed.
I see the same behaviour in `imenu` as well as `helm-imenu` and I never experienced this issue in other LSP clients (VS code, LanguageClient-neovim).

**To Reproduce**
1. Create new elixir project
2. Create new module with long name
3. Add some long function name
4. Run `imenu` and observe the function name is trimmed

**Expected behavior**
The whole function name and all parameters are shown.

**Which Language Server did you use**
JakeBecker/elixir-ls at master

**OS**
Fedora 29

**Comment by yyoncho** [comment]
```(setq imenu-max-item-length ...) ```
