### ISSUE TITLE
Fix for character encoding in lsp--read-from-file when using windows

### ISSUE THREAD

**Issue by astenman** [emacs-lsp/lsp-mode#637]
A minor fix for windows that makes paths with latin letters look better than is the case now (lsp-describe-session):

![image](https://user-images.githubusercontent.com/43724994/52209549-93160a00-2884-11e9-9533-3516366e6c41.png)

(defun lsp--read-from-file (file)
  "Read FILE content."
  (when (file-exists-p file)
    (with-demoted-errors "Failed to read file with message %S"
      (with-temp-buffer
        (insert-file-contents-literally file)
        **(if (eq system-type 'windows-nt)
            (decode-coding-region (point-min) (point-max) 'latin-1))**
        (first (read-from-string
                (buffer-substring-no-properties (point-min) (point-max))))))))

**Comment by yyoncho** [comment]
can you test https://github.com/emacs-lsp/lsp-mode/commit/ee21627416d25224c697ed92d63bb8dd8c29b859 and reopen if the issue is not fixed?

**Comment by astenman** [comment]
Yup, seems to work now. Thanks!
