### ISSUE TITLE
lsp-mode won't find php-language-server.php since I have it in ~/.config/composer/...

### ISSUE THREAD

**Issue by Kazimazi** [emacs-lsp/lsp-mode#652]
lsp-mode looks for `php-language-server.php` in `~/.composer/vendor/felixfbecker/language-server/bin/php-language-server.php`
Is there a workaround?
Can we have an option to get it from PATH?
I'm using Arch Linux.

**Comment by yyoncho** [comment]
Use  lsp-clients-php-server-command to customize the php ls location.
