### ISSUE TITLE
[Feature]  org-mode lsp-mode integration

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#655]
After spending some time reading org-mode code it seems like we may implement language support in the org-mode source block by using org-babel-tangle to save the file and translating the locations and buffer point/position using babel sources.

**Comment by stardiviner** [comment]
Do you have a prototype? Using tangling might have some edge case, like multiple source block point to same one target file, and creating empty new source block might overwrite target file. But still I think its a great solution, I saw someone use this method before.

**Comment by yyoncho** [comment]
> Do you have a prototype? 

No, just came up with the idea and decided to file the issue if someone wants to work on it. `dap-mode` could support that too.

**Comment by sxdxyxy** [comment]
is this merged into the master branch?

**Comment by yyoncho** [comment]
> is this merged into the master branch?

It is not implemented.

**Comment by kiennq** [comment]
Is this purely for org-mode or also markdown support too?
FYI, https://github.com/polymode/poly-markdown can work to a certain degree with `lsp-mode`.
![23a435f3-4cfb-4413-bf26-6147823b22f3](https://user-images.githubusercontent.com/2631472/75446229-58f53a00-59aa-11ea-9d74-1e6e38de2dd3.gif)

**Comment by sxdxyxy** [comment]
> Is this purely for org-mode or also markdown support too?
> FYI, https://github.com/polymode/poly-markdown can work to a certain degree with `lsp-mode`.
> ![23a435f3-4cfb-4413-bf26-6147823b22f3](https://user-images.githubusercontent.com/2631472/75446229-58f53a00-59aa-11ea-9d74-1e6e38de2dd3.gif)

can you offer a configuration for the screenshot  action? thanks.

**Comment by kiennq** [comment]
@sxdxyxy There's no special configuration needed.
I just install `poly-markdown`
``` elisp
(use-package poly-markdown
  :ensure t
  :defer t
  :commands (poly-markdown-mode poly-gfm-mode)
  :mode (("\\.md$" . poly-gfm-mode)
         ("\\.markdown$" . poly-markdown-mode)))
```
And configure `lsp-mode` like normal. Since the part between \```python ... \``` will automatically changed major mode to `python-mode` (via indirect buffer), it will automatically trigger `lsp-python` to work.

Not sure if it works by lucky or there's automatically point transformation somewhere

**Comment by sxdxyxy** [comment]
@kiennq  I don't know why my python in org mode doesn't work , I just simply use a configurable layer called [lsp](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+tools/lsp/README.org) , [python](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/python/README.org) and [ipython-notebook](https://github.com/syl20bnr/spacemacs/blob/develop/layers/LAYERS.org#ipython-notebook), in a single file with extension .py will work properly, but in a org file under org-mode code blocks, use 'C-c, ' ', with a extremely long waiting open the code block, but no completion ,no tips, no docstring.

**Comment by seagle0128** [comment]
@sxdxyxy I suppose you are using spacemacs, right? You should see https://github.com/emacs-lsp/lsp-mode/issues/377#issuecomment-437565673

**Comment by sxdxyxy** [comment]
@seagle0128 yes, I figured this post from #377 , but I don't know if #377  merge into the master, I add that configuration to the spacemacs  config file, still no work.

**Comment by seagle0128** [comment]
@sxdxyxy Sorry, I am not using spacemacs, but I do believe it should work.

Actually I make a new macro to support lsp in org-babel.

https://github.com/seagle0128/.emacs.d/blob/03a69b9b725a228a451ec27d7506a2d24f4d1a0f/lisp/init-lsp.el#L436


BTW, you should add `:file xxx` to the header of source block. For examle:

``` org
#+BEGIN_SRC python :results output :file test.py
  import sys
  import os

  print (sys.path)

#+END_SRC
```

Well, I will check `poly-markdown` later.

**Comment by yyoncho** [comment]
cc @vspinu

**Comment by sxdxyxy** [comment]
@seagle0128  unfortunately, I add some line in the init.el file and restart emacs, but it still doesn't work, I am not sure if my whole basic configuration of emacs is totally wrong.
![image](https://user-images.githubusercontent.com/13362677/75524344-ab853380-5a48-11ea-966a-9a13c26e60a8.png)

this my config file.
![image](https://user-images.githubusercontent.com/13362677/75524411-cce61f80-5a48-11ea-84b7-2204eecad52c.png)

**Comment by seagle0128** [comment]
@sxdxyxy Again, I am not using spacemacs. You can try vanilla Emacs or [Centaur Emacs](https://github.com/seagle0128/.emacs.d). `lsp-org-babel-enable` is a macro, not an interactive function.

Screenshot in Centaur

<img width="1444" alt="screeshot" src="https://user-images.githubusercontent.com/140797/75557446-fc158480-5a7a-11ea-8642-993c143eb8dd.png">

**Comment by yyoncho** [comment]
I am working on that right now.

**Comment by vspinu** [comment]
Would be really great to see a generic non-org-mode-only solution here. Building multi-modes with polymode simple, and there are many modes floating around already. 

I can add a generic tangler to polymode so that, say, all spans of the mode at point up to current span are saved in a temporary buffer/file etc. Just need to converge on a tangling file format so that original file buffer location could be retrieved directly from the tangled file. 

Actually such a tangler was in plan from the inception, but never found time for it.

**Comment by yyoncho** [comment]
@vspinu - make sense. Looking at what I currently have I think that it will end up generic either way.

**Comment by yyoncho** [comment]
Here it is a preview of what I currently have - https://www.youtube.com/watch?v=tnwvLyA2j4w . I started the integration with dap-mode as well. 

There are a few more tricky things to handle but soon it will land in master.

**Comment by brotzeit** [comment]
I'm looking forward to taking a look at the code.

**Comment by yyoncho** [comment]
The initial version is in. Markdown integration is possible after copying lsp-org (and then extracting the common parts). It is still in experimental/beta phase and evolving of the code/feature set depends on feedback.

https://github.com/emacs-lsp/lsp-mode/blob/master/docs/page/lsp-org.md

**Comment by rhoit** [comment]
I was able to run `lsp-org` normally but it doesn't work for `org-babel-expand-src-block` like shown by @seagle0128 [comment](https://github.com/emacs-lsp/lsp-mode/issues/655#issuecomment-592541156)

**Comment by seagle0128** [comment]
> I was able to run `lsp-org` normally but it doesn't work for `org-babel-expand-src-block` like shown by @seagle0128 [comment](https://github.com/emacs-lsp/lsp-mode/issues/655#issuecomment-592541156)

You should refer to https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-lsp.el#L444.

**Comment by mack1070101** [comment]
> You should refer to https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-lsp.el#L444.

@seagle0128 do you have any insight into how to make `org-babel-expand-src-block` work outside of `centaur-emacs`? If I open a block with `org-babel-expand-src-block` I get 
```
Lsp mode enabled in current buffer
lsp--path-to-uri: Wrong type argument: stringp, nil
```

## System info 
- `Spacemacs 0.300`
- Emacs 28.500 (Native comp branch)
- 9.4.4
- Lsp version `LSP :: lsp-mode 20210321.1904, Emacs 28.0.50, darwin`
- LSP Server [sqls](https://github.com/lighttiger2505/sqls/issues?q=is%3Aissue+is%3Aopen+org)

**Comment by martibosch** [comment]
Hello,

I am trying to make lsp work for file-wide inter-src-block completions. Here is my config: https://github.com/martibosch/snakemacs

And here is a minimal example of what I am trying to achieve:

```
#+PROPERTY: header-args:jupyter-python :session /path/to/kernel.json
#+PROPERTY: header-args:jupyter-python+ :async yes

#+begin_src jupyter-python :results output :file test.py
import numpy as np
#+end_src

#+begin_src jupyter-python :results output :file test.py
np.
#+end_src
```

I would like to have lsp features in the second block based on code from other blocks.

I encounter three main issues:

- I need to run `lsp-org` *in src each block* to have lsp working there. Luckily it connects to the same lsp process. But how can I make `lsp-org` to run by default when I am in src blocks of a specific type (e.g., python, jupyter-python...)?
- when I do `org-babel-expand-src-block`, I need to run again `lsp-org`, but I get a "user-error: You should specify file name in the src block header.", and lsp does not work.
- when I run `lsp-org`, I get the proper lsp features when all the required code is in the same src block, e.g., if I write `np.`  in the first block after the import, I get the proper completion, documentation... However, if as shown in the snippet, I write `np.` in the second block (even after running `lsp-org` in the second block as well), I do not get completion or documentation. At the same time, lsp works properly based on the information given in the same block.

Ideally, I would like to be able to use `org-babel-expand-src-block` and get lsp features based on the information of all the src blocks in the file. But fixing any of the issues noted above would already be great.

Final note: I encounter the exact three issues if I change `: results output :file test.py` for `:tangle test.py`.

Thank you. Best,
Martí
