### ISSUE TITLE
Need a timeout on server replies

### ISSUE THREAD

**Issue by alanz** [emacs-lsp/lsp-mode#66]
At the moment the emacs UI hangs for as long as the server is processing a message.

This should preferable become async, or should have some means to interrupt, or timeout.

**Comment by mattiasb** [comment]
This is probably what I've been experiencing with several modes. Emacs appears to hang, but it's just an effect of the synchronous nature of the RPC implementation then I guess.

**Comment by vibhavp** [comment]
The problem here is that lsp-mode is designed to plug into already existing emacs interfaces. As long as they're not asynchronous, we can't make lsp-mode async. However, a timeout is feasible.

**Comment by s-kostyaev** [comment]
@vibhavp you can do it with some tricks like this https://github.com/s-kostyaev/ivy-erlang-complete/commit/1dcb258a0207053a33ac207c11f2414aa89daba2

**Comment by vibhavp** [comment]
The current timeout value is 10 seconds. Is that fine, or should I further lower it?

**Comment by alanz** [comment]
That is probably fine. 

The problem is that some commands (for haskell anyway) can potentially run for a long time.

So some sort of async processing would be ideal. But let's see how this works out.

After all, this should only be triggered if there is a problem on the server, in my experience.
