### ISSUE TITLE
Clangd Header File Completion

### ISSUE THREAD

**Issue by Bee-Mar** [emacs-lsp/lsp-mode#663]
I'm having difficulty with header file completion. The code completion works just fine, but I can't seem to get header file names to be completed. I inserted two screenshots below.

This is my config for lsp/clangd. I tried using with and without `eglot`, and still have the same results.

    `(use-package eglot)
     (use-package lsp-mode
       :commands lsp
       :init
       (setq lsp-clients-clangd-executable "/usr/local/clang+llvm-7.0.0-x86_64-linux-gnu-ubuntu-16.04/bin/clangd")
       (require 'lsp-mode)
       (lsp-clients-register-clangd)
       (require 'lsp-clients))`

![2019-02-20-231248_597x389_scrot](https://user-images.githubusercontent.com/17814198/53143342-8d4b4480-3565-11e9-8b07-1ae6c1f995b6.png)
![2019-02-20-231342_1909x585_scrot](https://user-images.githubusercontent.com/17814198/53143343-8d4b4480-3565-11e9-8c1e-63468afa3b43.png)

**Comment by yyoncho** [comment]
This seems like clangd ls issue - can you open a PR at clangd repo? I don't think that there is anything we can do on lsp-mode side.

**Comment by Bee-Mar** [comment]
Will do, and thank you for getting back to me.
