### ISSUE TITLE
[Feature Request] Add Ben Mewburn's php-ls

### ISSUE THREAD

**Issue by Kazimazi** [emacs-lsp/lsp-mode#664]
Some usefull links:
[bmewburn/intelephense-docs](https://github.com/bmewburn/intelephense-docs)
[bmewburn/vscode-intelephense](https://github.com/bmewburn/vscode-intelephense) - vscode implementation
[marlonfan/coc-phpls](https://github.com/marlonfan/coc-phpls) - intelephense implementation for Vim plugin coc.nvim written in typescript
Hopefully it helps some of you php enthusiasts.

**Comment by yyoncho** [comment]
@Kazimazi seems like the server GH page has disappeared

**Comment by Kazimazi** [comment]
whats going on is it being moved?

**Comment by yyoncho** [comment]
Imo it is moved to a private repo

**Comment by Kazimazi** [comment]
replaced dead links with new documentation repo

**Comment by yyoncho** [comment]
This is some starting point for the integration:

```
;; PHP  intelephense
(defgroup lsp-php-iph nil
  "PHP."
  :group 'lsp-mode
  :tag "PHP")

(defcustom lsp-clients-php-iph-server-command
  `("intelephense" "--stdio")
  "Install directory for php-language-server."
  :group 'lsp-php-ip
  :type '(repeat string))

(lsp-register-client
 (make-lsp-client :new-connection (lsp-stdio-connection lsp-clients-php-server-command)
                  :major-modes '(php-mode)
                  :priority -1
                  :server-id 'iph))
```

**Comment by Kazimazi** [comment]
@yyoncho could you run the ls with those options?

**Comment by astenman** [comment]
I am usesing the following setting:

`(setq lsp-clients-php-iph-server-command `("intelephense" "--stdio"))
(lsp-register-client
 (make-lsp-client :new-connection (lsp-stdio-connection lsp-clients-php-iph-server-command)
                  :major-modes '(php-mode)
                  :priority -1
                  :ignore-messages '("indexing\\(Started\\|Ended\\)")
                  :server-id 'iph))`

**Comment by yyoncho** [comment]
> @yyoncho could you run the ls with those options?

Yes, it works fine, what is happening on your side?

**Comment by Kazimazi** [comment]
@yyoncho server instantly exits. In my stderr buffer I had this: 

```
emacs: /usr/bin/intelephense: Exec format error

Process iph stderr finished
```

**Comment by astenman** [comment]
I think you need to edit the /usr/bin/intelephense script if you haven't done that already. There is a bug in the script. 

https://github.com/bmewburn/intelephense-docs/issues/4

**Comment by Kazimazi** [comment]
@astenman thank you, that was the issue

**Comment by yyoncho** [comment]
@astenman @Kazimazi I suspect that this server requires more configuration, so if someone could compare the behaviour of the server in vscode and in emacs and post the client/server communication in vscode it will be very helpfull for lsp-mode team to do the required adjustments.

**Comment by yyoncho** [comment]
CC some PHP lsp users in case they want to test this PHP server(looks better than the default one) so we could eventually register it with higher priority (sorry for the spam if you are not interested).

@fuco1 @tomterl @gjm

**Comment by Kazimazi** [comment]
I've been using it in the last couple of days and I'm really satisfied with the outcome. I couldn't spot any differences compared to vscode or nvim implementation. Closing.

**Comment by yyoncho** [comment]
we still need to be included in lsp-clients.el and documented in the README.org
