### ISSUE TITLE
How to set exec_path for lsp-mode?

### ISSUE THREAD

**Issue by testinggithub1222** [emacs-lsp/lsp-mode#666]
I found that we change manually specify our executable path of javascript or typescript for lsp to work but how about lsp for html and css, how can we manually specify its path? 

Because I point my npm dir to somewhere else that normally people don't use and so lsp could not find executable for my lsp html. And i found that lsp use exec-path as default if no argument is provided. So, if my global npm dir is in "~/npm/global", then what should i do?

**Comment by yyoncho** [comment]
Sample code:
```
  (add-to-list 'exec-path "/path")
```
