### ISSUE TITLE
How to make lsp-mode to work in mix programming language?

### ISSUE THREAD

**Issue by testinggithub1222** [emacs-lsp/lsp-mode#667]
Imagine there is scenario that we have to write html mixing with php, css, plus javascript. So, my question is, how can we make lsp mode to work with all of these languages in a single file? 

I think lsp-mode is nice because it automatically recognize which mode it is but when coming to this case, then what should i do? Should there is a function that allow user to switch or manually select mode (this is good because if they work on .php extension file but it was html code). And what if lsp-mode integrate with web-mode or mmm-mode to solve these problem? (please, i am just thinking i don't know much about all of these stuff)

**Comment by yyoncho** [comment]
AFAIK vscode supports that and we have to investigate it is how it is done. I doubt that web-mode will be of any help. Note that lsp-mode is just a client and all the smartness comes from the server. I hope that the solution they are using is not coupled to the VScode itself. We may take a look at the other premium lsp clients like Theia/Che/Monaco/Eclipse as well. 

(cc @danielmartin if he had researched the problem)

**Comment by danielmartin** [comment]
I haven't investigated yet. How's that feature offered by VS Code? As far as I know, there's a PHP extension that does that, https://github.com/bmewburn/vscode-intelephense Is there anything else? Seems like for Emacs it could be a complex client created on top of `lsp-mode` and live in its own repo. It also needs special server support, as far as I can see.

**Comment by yyoncho** [comment]
@danielmartin https://code.visualstudio.com/docs/languages/html this page claims that vscode supports embedded html and js. 

> Seems like for Emacs it could be a complex client created on top of `lsp-mode` and live in its own repo.

Can you elaborate?

**Comment by kiennq** [comment]
How about [poly-mode](https://github.com/polymode/polymode? `lsp-mode` works to some degree with `polymode`.
The idea of `polymode` is quite interesting since it extracts code block and make indirect buffer with respected major mode. That explains why `lsp-mode` works some how.

**Comment by yyoncho** [comment]
poly-mode might work but in that particular case I think that we are looking for what has been described here: https://github.com/microsoft/monaco-editor/issues/56#issuecomment-422969614

**Comment by yyoncho** [comment]
I don't think that there is anything to address on lsp-mode side. Marking as closed.
