### ISSUE TITLE
MarkupContent is considered as deprecated but shouldn't be

### ISSUE THREAD

**Issue by Khady** [emacs-lsp/lsp-mode#673]
**Describe the bug**

In `lsp--render-on-hover-content`, it is written that `MarkupContent` is deprecated. But the specification says the opposite. `MarkedString` is deprecated and `MarkupContent` is not.

https://github.com/emacs-lsp/lsp-mode/blob/e069cf80e57af70aae69209f6513d5ac2e4724c9/lsp-mode.el#L2648-L2668

https://microsoft.github.io/language-server-protocol/specification#textDocument_hover

```typescript
/**
 * MarkedString can be used to render human readable text. It is either a markdown string
 * or a code-block that provides a language and a code snippet. The language identifier
 * is semantically equal to the optional language identifier in fenced code blocks in GitHub
 * issues. See https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting
 *
 * The pair of a language and a value is an equivalent to markdown:
 * ```${language}
 * ${value}
 * ```
 *
 * Note that markdown strings will be sanitized - that means html will be escaped.
* @deprecated use MarkupContent instead.
*/
type MarkedString = string | { language: string; value: string };
```

Also, it looks like the support of `MarkupContent` in incomplete. Here is an exchange between lsp-mode and ocamlmerlin-lsp. For this hover response, lsp-ui displays a box that 3 lines high. But contains nothing. If I understand `lsp-ui-doc-render-function` correctly, when it is nil, the markdown should be rendered. The box is empty only the FIRST time it is displayed.

```
>>> ocamlmerlin-lsp:543(async)
Content-Length: 218

{
  "jsonrpc": "2.0",
  "method": "textDocument/hover",
  "params": {
    "textDocument": {
      "uri": "file:///tmp/lsp/test.ml"
    },
    "position": {
      "line": 6,
      "character": 23
    }
  },
  "id": 3
}

<<<< ocamlmerlin-lsp:543
{
  "id": 3,
  "jsonrpc": "2.0",
  "result": {
    "contents": {
      "value": "```ocaml\nint\n```",
      "kind": "markdown"
    }
  }
}
```

first hover:

![image](https://user-images.githubusercontent.com/974142/53501199-ae4ef080-3aa3-11e9-9d07-97df77fcab12.png)

second hover:

![image](https://user-images.githubusercontent.com/974142/53502066-397cb600-3aa5-11e9-8cde-02e5bf877411.png)

**To Reproduce**

I don't know how to call by hand `lsp--render-on-hover-content` to reproduce easily.

**Expected behavior**

The markdown should be rendered and lsp-ui should displayed the rendered markdown

**Which Language Server did you use**

ocamlmerlin-lsp

**OS**

debian stretch, emacs 27 compiled from sources

```emacs-lisp
(use-package helm-lsp :ensure t)
(use-package lsp-ui
  :ensure t
  :custom
  (lsp-ui-doc-position 'bottom)
  (lsp-ui-doc-header t)
  (lsp-ui-sideline-enable nil))
(use-package company-lsp
  :ensure t
  :custom
  (company-lsp-cache-candidates nil)
  :config
  (push 'company-lsp company-backends))
(use-package lsp-mode
  :ensure t
  :custom
  (lsp-print-io t)
  (lsp-trace t)
  (lsp-eldoc-render-all t)
  (lsp-markup-display-all t)
  :config
  (lsp-register-client
   (make-lsp-client :new-connection (lsp-stdio-connection (lambda () (opam-which "ocamlmerlin-lsp")))
                    :major-modes '(tuareg-mode)
                    :server-id 'ocamlmerlin-lsp)))
```

**Comment by Khady** [comment]
```
>>> ocamlmerlin-lsp:8935(async)
Content-Length: 218

{
  "jsonrpc": "2.0",
  "method": "textDocument/hover",
  "params": {
    "textDocument": {
      "uri": "file:///tmp/lsp/test.ml"
    },
    "position": {
      "line": 6,
      "character": 4
    }
  },
  "id": 50
}

<<<< ocamlmerlin-lsp:8935
{
  "id": 50,
  "jsonrpc": "2.0",
  "result": {
    "contents": [
      "```\nint -> int -> int\n```"
    ]
  }
}
```

When ocamlmerlin-lsp returns a `MarkedString`, the markdown is properly rendered.

**Comment by yyoncho** [comment]
It seems like gfm-view-mode cannot handle this string:

> ;; (gfm-view-mode . "markdown")
> (markdown-mode . "markdown")

... fixes the issue in the eldoc buffer. Can you test and report back?

**Comment by Khady** [comment]
Yep it helps with eldoc buffer. Not with lsp-ui frame.

**Comment by yyoncho** [comment]
The rendering logic is not shared between lsp-ui and lsp-mode, so you should fix that in lsp-ui too. I am not sure whether this is a but in gfm-view-mode though.

**Comment by Khady** [comment]
Maybe it's because of the language name after the first 3 backticks. I'll try again later.

**Comment by Khady** [comment]
> Maybe it's because of the language name after the first 3 backticks. I'll try again later.

It doen't seem to be related :/

**Comment by Khady** [comment]
So the problem of empty buffer displayed by lsp-ui-doc is because of a race condition with eldoc. with `lsp-eldoc-render-all t` I never have the problem of empty buffer.

**Comment by Khady** [comment]
Summary:

- There is a wrong comment saying that MarkupContent is deprecated. This is false. MarkedString is deprecated.
- When rendering in eldoc, gfm-view-mode can have problems. It doesn't seem critical to me but probably worth a mention somwhere.
- When both `lsp-eldoc-render-all` and `lsp-ui-doc` are enabled, there is a race condition that can make lsp-ui display an empty frame. This is not critical either, but once again it probably deserve a mention.

I can fix those 3 things if you agree with them.

**Comment by yyoncho** [comment]
> * When both `lsp-eldoc-render-all` and `lsp-ui-doc` are enabled, there is a race condition that can make lsp-ui display an empty frame. This is not critical either, but once again it probably deserve a mention.

1) and 2) are fine. Can you elaborate on 3).

**Comment by Khady** [comment]
I don't know how to explain better. This is what is illustrated by my screenshots above. I observed that when lsp-ui-doc displays its frame, the content of the buffer in the frame is the same as the content of the minibuffer. So anything that prints to the minibuffer would also print in this lsp-ui-doc buffer and be displayed in the frame. And I have the impression that depending on the order lsp-ui-doc and lsp-eldoc run, the lsp-ui-doc buffer can end up with no content.

**Comment by yyoncho** [comment]
Should be fixed in latest lsp-mode
