### ISSUE TITLE
Flymake diagnostics don't update

### ISSUE THREAD

**Issue by hpdeifel** [emacs-lsp/lsp-mode#674]
**Describe the bug**
Flymake diagnostics are reported correctly for a few (just one?) edit operations and are not updated any more after further edits. Disabling and re-enabling `flymake-mode` fixes the problem for another edit and then it gets stuck again. This happens consistently for me in `rls` projects (I haven't tried other language servers). 

Flycheck integration works fine. `eglot`'s flymake integration also works fine.

**To Reproduce**
1. `emacs -Q`
2. load `lsp`
3. open a file in a rust project
4. `M-x lsp`
5. Type some code into the buffer

**Expected behavior**
Flymake diagnostics are correctly displayed and updated while typing.

**Which Language Server did you use**
`rls-preview 1.31.6 (bfa1371 2018-12-07)`

**OS**
Emacs :slightly_smiling_face: (actually Arch Linux)

**Comment by yyoncho** [comment]
I am unable to reproduce it with emacs27 . Which emacs version do you use?

Can you repro with using https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el (you will have to manually install rust-mode or add it to the list of packages to install)?

**Comment by hpdeifel** [comment]
I'm on Emacs 26.

I can't reproduce the exact behavior with `lsp-start-plain.el`; no idea what's different between `emacs -Q` with manually loaded packages and this temporary elpa directory...

Anyway, it's still wonky. On small projects, it seems to work alright but on larger ones it exhibits similar but not quite the same behavior: Typing very fast sometimes leads to stale flymake diagnostics that obviously refer to previous buffer content. In this case, typing a few more letters (or killing and yanking something) fixes it.

I have tried and reproduced this with the built-in flymake from Emacs 26 and the latest version from elpa. I'll try a few public rust repos so that you can try to repro with the exact same code as I have.

Since this seems to be some kind of racy heisenbug, what should I do to debug it myself?

**Comment by yyoncho** [comment]
I think that I might have found what might cause this behavour. Can you retest with this change, seems like it might fix your issue and report back to extend the solution with the proper cleanup:

```
  (defun lsp--flymake-after-diagnostics ()
    "Handler for `lsp-after-diagnostics-hook'"
    (when lsp--flymake-report-fn
      (lsp--flymake-backend lsp--flymake-report-fn)
      ;; (remove-hook 'lsp-after-diagnostics-hook 'lsp--flymake-after-diagnostics t)
      ))
```

**Comment by hpdeifel** [comment]
Alright, that took some debugging. There are three independent problems that interact in this bug:

1. Your fix in `lsp--flymake-after-diagnostics` is necessary but could be expanded a bit: Currently in lsp-mode, Flymake triggers `lsp--flymake-backend`, which updates flymake diagnostics. Updates from the LS only save diagnostics until flymake calls the backend function again. In eglot, it's the other way round: The flymake backend only saves the report function and only notifications from the LS update diagnostics. Your fix is a step in this direction but doesn't decouple flymake from diagnostics updates.

2. An independent typo in `lsp--flymake-after-diagnostics` tripped me off a lot during debugging.

3. [This bug in eglot](https://github.com/joaotavora/eglot/issues/159) also applies lsp-mode and the fix is the same: Use the `:region` parameter of the flymake report function.


I will submit some pull requests.
