### ISSUE TITLE
fortran language server arguments not called properly?

### ISSUE THREAD

**Issue by mscfd** [emacs-lsp/lsp-mode#678]
If i use the fortran fortls language server and I try to pass arguments via lsp-clients-fortls-args, then fortls is invoked in such a way that it cannot parse the arguments properly.

My emacs setup contains the following code to set argument list to the fortls language server:

```
 '(lsp-clients-fortls-args
   (quote
    ("--variable_hover --lowercase_intrinsics")))
```
If I check sys.argv on the fortls.py part, then I get

```["fortls --variable_hover --lowercase_intrinsics"]```

instead of 

```["fortls", "--variable_hover, "--lowercase_intrinsics"]```

i.e. len(sys.argv) = 1 and the argument list is not split.
As a consequence  fortls cannot parse the command line and fails. To me this looks like an issue on the side of lsp-mode, which should invoke fortls differently to pass command line arguments similar to how it is done by a shell.
BTW, I use Linux.

**Comment by yyoncho** [comment]
Please split each of the arguments in a separate string, e. g. 

```
(setq lsp-clients-fortls-args '("--variable_hover" "--lowercase_intrinsics"))
```

**Comment by mscfd** [comment]
Thanks, that works. I already saw that I misinterpreted the output 'Command "fortls ..."' line in "*lsp-log*" and indeed, fortls had ```argv = ["fortls, "--variable_hover --lowercase_intrinsics"]```.
Anyway, thanks again!
