### ISSUE TITLE
lsp--locations-to-xref-items: Symbol’s function definition is void: seq-first

### ISSUE THREAD

**Issue by mackong** [emacs-lsp/lsp-mode#683]
after upgrade lsp-mode to latest version(03/02/2019), when call **xref-find-def**, the error is occured

> Debugger entered--Lisp error: (void-function seq-first)
  seq-first((#<hash-table equal 2/65 0x180d5d9>))
  lsp--locations-to-xref-items((#<hash-table equal 2/65 0x180d5d9>))

[dash](https://github.com/magnars/dash.el) is already upgrade to latest version (21/02/2019).

**Comment by yyoncho** [comment]
@vibhavp - apparently seq-first is added in emacs 27, so we need to fix that.

**Comment by yyoncho** [comment]
@mackong 

You could define it by doing: 
```
(defun seq-first (sequence)
  "Return the first element of SEQUENCE."
  (seq-elt sequence 0))
```
