### ISSUE TITLE
shutdown is send as notification instead of as request

### ISSUE THREAD

**Issue by hpdeifel** [emacs-lsp/lsp-mode#685]
**Describe the bug**
Trying to call `lsp-shutdown-workspace` on `rls` projects results in an error with `lsp-unknown-message-type`. 

This is what happens:

1. lsp-mode sends `shutdown` as a notification
2. rls is strict about the spec and doesn't accept this. It responds with an error.
3. This error is not the reply to a request (because there is no request to reply to) but also a notification.
4. lsp-mode in turn doesn't understand this in `lsp--get-message-type`

The spec says `shutdown` should be a request, not a notification.

**Which Language Server did you use**
rls-preview 1.31.6 (bfa1371 2018-12-07)

**OS**
GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5) of 2019-03-01

**Error callstack**

```
Debugger entered--Lisp error: (lsp-unknown-message-type #<hash-table equal 3/65 0x15723f3ee85d>)
  signal(lsp-unknown-message-type (#<hash-table equal 3/65 0x15723f3ee85d>))
  (if (gethash "method" json-data nil) 'notification (signal 'lsp-unknown-message-type (list json-data)))
  (if (gethash "id" json-data nil) (if (gethash "error" json-data nil) 'response-error (if (gethash "method" json-data nil) 'request 'response)) (if (gethash "method" json-data nil) 'notification (signal 'lsp-unknown-message-type (list json-data))))
  lsp--get-message-type(#<hash-table equal 3/65 0x15723f3ee85d>)
[...]
```

And messages:

```
>>> rls:12883(async)
Content-Length: 65

{
  "jsonrpc": "2.0",
  "method": "shutdown",
  "params": null
}

>>> rls:12883(async)
Content-Length: 61

{
  "jsonrpc": "2.0",
  "method": "exit",
  "params": null
}

<<<< rls:12883
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32600,
    "message": "Invalid request"
  },
  "id": null
}
```

**Comment by yyoncho** [comment]
See also https://github.com/emacs-lsp/lsp-mode/issues/14 - we are currently not matching the spec. Willing to provide a PR?

**Comment by hpdeifel** [comment]
I can make a PR.

The whole jsonrpc handling in lsp-mode seems to be quite ad-hoc. Are there any plans to move to the jsonrpc library built into the latest Emacs?

**Comment by yyoncho** [comment]
> The whole jsonrpc handling in lsp-mode seems to be quite ad-hoc.

Can you share what are your concerns?

`lsp-mode` rpc layer is a bit different from jsonrcp one since it allows talking to many servers at the same time. From a historical perspective, we gradually moved from being able to call one server to being able to call multiple servers while we preserved the same interface which resulted in not so fluent code. So, at this point, even if we move to jsonrpc we practically wont benefit anything since we still need to wrap the calls to provide the multi-server support. We try slowly to improve the rpc interface and make it clearer and more readable so feel free to provide suggestions. 

Ideally, I had unlimited time and resources I would like to investigate writing the whole json RPC layer in  emacs module (why not using https://github.com/paritytech/jsonrpc ?) and do all the handling in such module *NOT* being in Emacs UI thread.

See also: https://github.com/emacs-lsp/lsp-mode/issues/685

**Comment by hpdeifel** [comment]
> Can you share what are your concerns?

In hindsight it's probably fine. I was referring to `lsp--get-message-type` and `lsp--parser-on-message`, which pass jsonrpc messages around in the form of hash-tables, testing and using keys as they are needed. I would have expected that the message is at some point converted into a structured type, but maybe I'm just too used to statically typed languages.

> Ideally, I had unlimited time and resources I would like to investigate writing the whole json RPC layer in emacs module (why not using https://github.com/paritytech/jsonrpc ?) and do all the handling in such module *NOT* being in Emacs UI thread.

If I understand correctly, using a C/Rust implementation would speed up json parsing but still block Emacs. Asynchronicity in dynamic modules seems to be [really tricky™](https://nullprogram.com/blog/2017/02/14/).

**Comment by yyoncho** [comment]
> I would have expected that the message is at some point converted into a structured type, but maybe I'm just too used to statically typed languages.

We may write something like that in the future, but yeah, it will be an improvement over the planned improvements.

> If I understand correctly, using a C/Rust implementation would speed up json parsing but still block Emacs. Asynchronicity in dynamic modules seems to be really tricky™.

Thanks for the link, I was really looking for something like that! Good to know that it is possible.
