### ISSUE TITLE
Symbol’s function definition is void: lsp-uri-to-path

### ISSUE THREAD

**Issue by bradprob** [emacs-lsp/lsp-mode#686]
Executing `lsp-find-definition` on a function returns `Symbol’s function definition is void: lsp-uri-to-path` without any action (it does not go to the function definition).
The language server protocol is ccls.

**Comment by yyoncho** [comment]
Already fixed https://github.com/emacs-lsp/lsp-mode/commit/ad737317eeac68e7b4e1efb00f0ac3b0da8730d3
