### ISSUE TITLE
Unknown method: client/registerCapability

### ISSUE THREAD

**Issue by qhuyduong** [emacs-lsp/lsp-mode#688]
**Describe the bug**
I'm trying to use https://github.com/jaredly/reason-language-server for reason-mode.
When starting lsp-mode, this warning's printed out all the time.

**To Reproduce**
Add this code to Emacs's `init.el`
```el
(setq lsp-reason-lang-server-command '("reason-language-server"))
(lsp-register-client
 (make-lsp-client :new-connection (lsp-stdio-connection
                                   (-const lsp-reason-lang-server-command))
                  :major-modes '(reason-mode)
                  :priority -1
                  :server-id 'reason-ls))
```

**Expected behavior**
Don't see the warning

**Which Language Server did you use**
https://github.com/jaredly/reason-language-server

**OS**
Mac OS 10.14

**Comment by yyoncho** [comment]
The issue is in the server not providing request id:

From the LSP spec:

> The client/registerCapability request is sent from the server to the client to register for a new capability on the client side. Not all clients need to support dynamic capability registration.

From the JSONRPC:

> id
> An identifier established by the Client that MUST contain a String, Number, or NULL value if included. If it is not included it is assumed to be a notification. The value SHOULD normally not be Null [1] and Numbers SHOULD NOT contain fractional parts [2]

The actual message:

```
<<<< reason-ls:21181 status:starting
{
  "jsonrpc": "2.0",
  "method": "client/registerCapability",
  "params": {
    "registrations": [
      {
        "id": "watching",
        "method": "workspace/didChangeWatchedFiles",
        "registerOptions": {
          "watchers": [
            {
              "globPattern": "**/bsconfig.json",
              "globPattern": "**/.merlin"
            }
          ]
        }
      }
    ]
  }
}
```

You may do the registration in the following way to avoid the spam until the server is fixed:

```
(lsp-register-client
 (make-lsp-client :new-connection (lsp-stdio-connection
                                   (-const lsp-reason-lang-server-command))
                  :major-modes '(reason-mode)
                  :notification-handlers (ht ("client/registerCapability" 'ignore))
                  :priority -1
                  :server-id 'reason-ls))
```

**Comment by qhuyduong** [comment]
Awesome @yyoncho . Many thanks!
