### ISSUE TITLE
Initial imenu update can be slow / hangs emacs

### ISSUE THREAD

**Issue by fjl** [emacs-lsp/lsp-mode#692]
**Describe the bug**

When I switch to a buffer with lsp-mode for the first time (a Go buffer in my case), imenu requests
the index from lsp-mode. Getting the index can take time and emacs hangs because it's waiting for an LSP RPC during redisplay.

Profile:

```text
- redisplay_internal (C function)                                  94  29%
 - imenu-update-menubar                                            93  29%
  - imenu--make-index-alist                                        93  29%
   - lsp--imenu-create-index                                       93  29%
    - lsp--get-document-symbols                                    57  18%
     - lsp-request                                                 57  18%
      - lsp--send-request                                          57  18%
       - mapcar                                                    57  18%
        - #<compiled 0x44031b69>                                   57  18%
         - lsp--send-wait                                          57  18%
          - accept-process-output                                   5   1%
           - #<compiled 0x43414f6d>                                 4   1%
            - lsp--parser-on-message                                4   1%
             + lsp--read-json                                       4   1%
           + timer-event-handler                                    1   0%
    - lsp--imenu-filter-symbols                                    35  11%
     + seq-remove                                                  35  11%
    + mapcar                                                        1   0%
```

**To Reproduce**

Switch to a buffer with many functions defined.

**Expected behavior**

I'd expect the buffer switch to be instant. imenu should be updated asynchronously when the RPC
to get the document's symbols finishes.

**Which Language Server did you use**

`bingo`

**Comment by yyoncho** [comment]
From what I can see I menu does not support async calls and we have to trick it somehow. As a temporary workaround you may disable the toolbar integration(I suspect that you are not using it).

**Comment by d125q** [comment]
I can work on an async Imenu, but it will of course have some drawbacks.  The best we can do is to send `textDocument/documentSymbol` requests on an idle timer and store the buffer's results.  How does that sound?  We can also try to hook into the `*Rescan*` functionality to force a sync update when the user needs results immediately.

---

By the way, the current implementation becomes slow when the following occurs:

1. There is an entry for Imenu in the menu bar (e.g., `imenu-add-menubar-index)`;
2. `imenu-auto-rescan` is enabled; and
3. You are in the process of actively editing the buffer.

This results in many blocking requests since the menu-bar entry is updated on `menu-bar-update-hook`.

**Comment by yyoncho** [comment]
@d125q 

Here it is a bit more efficient variation of what you are suggesting, we have it implemented for lenses/links/highlights, etc: Start a timer after the buffer on change event and cancel if there are pending timers. When the timer is triggered load the file symbols data asynchronously.

What I do not want to have is stale results when imenu is called interactively which might happen if we do not have the results for the current buffer state and we need to force sync call in that case.

Here it is an alternative solution:

Add an advice on menu-update function which will raise a buffer-local flag e. g. lsp--do-async-workspace-symbols in case we do not have the data for the current buffer state(there is buffer-modified-tick). The lsp--imenu-create-index will check that variable and will behave async (the way you have described, the call will be performed and then when callback is received the menu will be updated) or it will be sync (which will handle helm-imenu, etc). I am not sure whether all this will work though.

**Comment by d125q** [comment]
I think we can even combine both approaches:

1. Compute results on a timer every now and then in the background.  When results arrive, store them along with the modification-count.
2. When a menu-bar entry update is requested *or* the modification-tick is unchanged, simply return the previously computed results.  Otherwise, do a sync request and use its results.

**Comment by yyoncho** [comment]
In case we do not have the state for the current buffer modification tick don't we still need to differentiate whether the request is coming from the interactive call(e. g. helm-imenu) or from menubar update and block only when the call is made interactively?

**Comment by d125q** [comment]
Indeed, but isn't the idea that we don't care for the menu-bar and simply give it whatever we have?

**Comment by yyoncho** [comment]
> give it whatever we have?

Give what we have in case it is up to date. If it is not up to date do async call and force imenu update in the callback.

**Comment by d125q** [comment]
In that case we don't even need an idle timer :)

Basically, make the menu-bar entry update async and everything else sync.  If this sounds good, I will try to come up with a PR.  How does that sound?

**Comment by yyoncho** [comment]
> In that case we don't even need an idle timer :)

Yes. 

> Basically, make the menu-bar entry update async and everything else sync. If this sounds good, I will try to come up with a PR. How does that sound?

 Sound good to me. I will hold on testing https://github.com/emacs-lsp/lsp-mode/pull/765

**Comment by yyoncho** [comment]
> My initial idea was to have the menu-bar entry display possibly outdated information (there is always the `*Rescan*` button), but maybe that's not too good of an idea.

This will probably work too, we should aim for:

1. Showing up-to-date data
2. Being as efficient as possible(fewer calls to the server)

Now, when I think more about that it seems like it is not very clear which option will be the best fit. If menubar-update-imenu is called on every change we should add debounce which will effectively lead to what you are suggesting when menubar is enabled but in case the user does not have menubar enabled these calls won't be performed. 

In general, both solutions are a workaround for the emacs limitations.

**Comment by yyoncho** [comment]
@d125q one more thing to consider - we are going to create a pretty gui control in https://github.com/emacs-lsp/lsp-treemacs which will be should be updated on the fly.

**Comment by yyoncho** [comment]
fixed by @d125q with https://github.com/emacs-lsp/lsp-mode/pull/780
