### ISSUE TITLE
Out of the box support for Kotlin Language Server

### ISSUE THREAD

**Issue by joncarr** [emacs-lsp/lsp-mode#693]
Out of the box LSP support for Kotlin. Eglot uses the following:

https://github.com/fwcd/KotlinLanguageServer

Would be great to have with lsp-mode!

**Comment by yyoncho** [comment]
@joncarr willing to try to provide a pr? Here it is a sample server registration where "pyls" is the path to the binary you want to use which should be either string or list of strings in case there are multiple arguments?

``` elisp
(lsp-register-client
 (make-lsp-client :new-connection (lsp-stdio-connection "pyls")
                  :major-modes '(python-mode)
                  :server-id 'pyls))
```

**Comment by joncarr** [comment]
Sure, I'll give it a go. Going to have find a good path to default the language server to. As far as I know it's not available in linux package repos. I'll have to see if it's available on Homebrew somehow (I don't own a Mac). Same with windows. Since it's built from source with gradle, weight need to provide a variable to set the users chosen path for the client. I'll have a look a bit later today.

**Comment by yyoncho** [comment]
You may use vscode marketplace as a source for the language server if it is not available somewhere.

**Comment by joncarr** [comment]
I'm not exactly sure what to do with the `workspace/configuration` warning I am getting when kotlin language server starts.  I tried looking at the other client registrations but the only one that appeared to be sending any configuration settings was `pyls`.  I don't think the people responsible for `kotlin-language-server` have even implemented `workspace/configuration` method as implied by their response to a question I over there, which can be seen [here](https://github.com/fwcd/KotlinLanguageServer/issues/90).  Currently I am just passing an empty list but still receive the warning.  Besides that warning, seems to be working as intended.

**Comment by yyoncho** [comment]
I have misled you - it seems like `workspace/configuration` is part of the spec and it is not kotlin extension method thus it should be implemented by lsp-mode itself. Feel free to do a PR with the current configuration and open a bug about the warning and we will work on fixing it.

**Comment by joncarr** [comment]
No problem, I think I'll remove the `:request-handler` section since it isn't currently required and submit the PR for the language configuration.

**Comment by yyoncho** [comment]
@joncarr in case you are interested there seems to be a debug adapter for kotlin - https://github.com/fwcd/KotlinDebugAdapter so we can have the full IDE featureset.

**Comment by joncarr** [comment]
Sure, I'll have a look at it.
