### ISSUE TITLE
python-langauge-server: xref-find-definition goes to import statement

### ISSUE THREAD

**Issue by emosesPatreon** [emacs-lsp/lsp-mode#694]
**Describe the bug**
As of the latest version of Microsoft's `python-languge-server`, when I execute `xref-find-defintions` on a function or class, it jumps to the `import` statement in the same file.  If I execute it again (on the import statement), it follows to the definition.

**To Reproduce**
*a.py:*
```
from b import other_func

other_func('foo')
```

*b.py*
```
def other_func(s):
    print(s)
```

If I execute xref-find-definitions here in a.py (`|` is the point)
```
from b import other_func

oth|er_func('foo')
```
It jumps here
```
from b import |other_func

other_func('foo')
```
If I execute again it goes here in b.py
```
|def other_func(s):
    print(s)
```

**Expected behavior**
I would expect it to jump to the `def` in b.py on the first execution

**Which Language Server did you use**
https://github.com/Microsoft/python-language-server on master (sha 2b58358c0bd8b2d0c4b072eb2799fb255b8d752c)

lsp-mode 6.0

**OS**
OSX 10.14.2

**Error callstack**
If there is an error please reproduce the issue with `toggle-debug-on-error` and after setting `lsp-print-io` to t, and then include the callstack and attach the content of \*Messages\* buffer.

``` emacs-lisp
(setq lsp-print-io t)
```

**Comment by yyoncho** [comment]
lsp-mode does what the server is returning, you may verify that by setting `(setq lsp-print-io t)` and then inspecting \*lsp-log\* buffer(look for textDocument/definition and then the response with that same ID). After that, you may follow up with reopening this bug in case you believe that lsp-mode is doing smt wrong or filing a bug in mspyls repo in case you believe that the server is returning wrong results.

(to me it looks like more like a feature).
