### ISSUE TITLE
Linter errors is not shown with Solargraph

### ISSUE THREAD

**Issue by qhuyduong** [emacs-lsp/lsp-mode#695]
**Describe the bug**
I have enabled lsp-mode and lsp-ui in enh-ruby-mode. The server has started successfully. However linter is not working as I cannot see any warning/error in flycheck. Did I miss something?

**To Reproduce**
1. Enable lsp-mode in enh-ruby-mode
2. Don't see any warning/error in flycheck

**Expected behavior**
See warning/error in flycheck

**Which Language Server did you use**
Solargraph

**OS**
Mac OS 10.14

**Comment by yyoncho** [comment]
Based on the description here the diagnostics are not enabled by default - https://github.com/castwide/vscode-solargraph . I played a little bit with the settings but couldn't make it work. I will come back to the issue later today or this week.

You may find the full list of the settings in package.json( here it is the sample code, you may try to debug why solargraph is not picking this setting). 

``` elisp
(defun lsp-clients-ruby-make-options ()
  `(:solargraph.diagnostics t))

;; Ruby
(lsp-register-client
 (make-lsp-client :new-connection (lsp-stdio-connection '("solargraph" "stdio"))
                  :major-modes '(ruby-mode enh-ruby-mode)
                  :priority -1
                  :multi-root t
                  :initialization-options #'lsp-clients-ruby-make-options
                  :server-id 'ruby-ls))
```

**Comment by qhuyduong** [comment]
@yyoncho It should just be `:diagnostics t`. I created a PR BTW.

**Comment by yyoncho** [comment]
I am taking this bug - I will create a tool which will automatically generate the needed code from the vscode extension definition file.

**Comment by qhuyduong** [comment]
@yyoncho the new `lsp-generate-settings` method is great. However look like it only sends the configurations to server if they're changed (in `didChangeConfiguration`). So on boot up they don't take any effect. How can I fix that?

**Comment by yyoncho** [comment]
I do not quite get your question, solargraph configuration is sent explicitly like that - https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-solargraph.el#L105 . What is currently missing is updating the configuration once a property has changed.

**Comment by qhuyduong** [comment]
@yyoncho Sorry let me clarify my situation: 
1. Enable `lsp-print-io`
2. Open a Ruby file
3. Watch the log and see `initializationOptions` is `null` and there is no linter error
4. Evaluate `(setq lsp-solargraph-diagnostics t)`
5. Watch in the log and see 
```
{
  "jsonrpc": "2.0",
  "method": "workspace/didChangeConfiguration",
  "params": {
    "settings": {
      "solargraph": {
        "completion": true,
        "hover": true,
        "diagnostics": true,
        "autoformat": false,
        "formatting": true,
        "symbols": true,
        "definitions": true,
        "rename": true,
        "references": true,
        "folding": true,
        "logLevel": "warn"
      }
    }
  }
}
```
6. Make a change in Ruby file and now the errors appear.

**Comment by yyoncho** [comment]
@qhuyduong this one is not supported yet, you have to do the configuration change before starting, you may update the server manually using code similar to https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-solargraph.el#L105 . I was wondering whether to implement it but decided to do it later since it has a workaround (lsp-workspace-restart).
