### ISSUE TITLE
Add test coverage report

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#702]
This will help to track which parts of the code are covered by the tests.

Links:

https://coveralls.io/ 
https://codecov.io/

**Comment by leungbk** [comment]
I was thinking about adding something like this just now. Why did we choose to close this originally? @yyoncho

**Comment by yyoncho** [comment]
it was implemented and then reverted: https://github.com/emacs-lsp/lsp-mode/pull/1699
