### ISSUE TITLE
LSP :: Classpath is incomplete. Only syntax errors will be reported

### ISSUE THREAD

**Issue by mrbig033** [emacs-lsp/lsp-mode#706]
#### Runtime Environment

- MX Linux 18
- GNU Emacs 27.0.50
- Evil version 1.2.14
- [.emacs.d](https://github.com/mrbig033/dotfiles/tree/master/emacs/emacs_default)
- [packages](https://github.com/mrbig033/dotfiles/blob/master/emacs/emacs_default/packs.el)
- lsp-java 20190311.1710

#### Issue

How can I set a classpath variable in a way that Emacs "sees" it? I tried

`CLASSPATH=.:/usr/local/fubar/Foo.jar:/home/johndoe/myclasses`
`export CLASSPATH`

And also adding a `,project` file [as suggested](filehttps://github.com/emacs-lsp/lsp-java/issues/84#issuecomment-447240491)... the message keeps coming. 

But no dice.

**Comment by yyoncho** [comment]
The .project file should be matching the eclipse project file specification - see https://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Fproject_description_file.html . I would recommend you to create a simple maven/gradle project and use it, e. g. using https://maven.apache.org/archetypes/maven-archetype-quickstart/ and then import the root folder containing the pom.xml file. You may use this project as well - https://github.com/emacs-lsp/dap-mode/tree/master/features/fixtures/test-project .

**Comment by mrbig033** [comment]
Okay, this way more complicated than I thought. I don't need this for now, gonna stick with Eclim for a while. Thanks.
