### ISSUE TITLE
wrong-type-argument error while reverting buffers

### ISSUE THREAD

**Issue by seagle0128** [emacs-lsp/lsp-mode#712]
I got this error while reverting buffers (actually after `magit-discard`). My env is GNU Emacs 26.1 on macOS Mojave.

```elisp
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  lsp-on-change(0 2140 2140)
  lsp-on-revert()
  run-hooks(revert-buffer-internal-hook)
  revert-buffer--default(t t)
  revert-buffer(t t)
  revert-current-buffer()
  funcall-interactively(revert-current-buffer)
  call-interactively(revert-current-buffer nil nil)
  #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x400c29cf>)(revert-current-buffer nil nil nil)
  ad-Advice-command-execute(#f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x400c29cf>) revert-current-buffer)
  apply(ad-Advice-command-execute #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x400c29cf>) revert-current-buffer)
  command-execute(revert-current-buffer)
```

**Comment by yyoncho** [comment]
I see what is causing the issue, but I cannot reproduce it. Are you able to reproduce it consistently?

**Comment by seagle0128** [comment]
Not 100%, but encountered a few times. Maybe 30%, I guess. I also cannot reproduce it always.

**Comment by yyoncho** [comment]
I have pushed https://github.com/emacs-lsp/lsp-mode/commit/42adb791ee9b2580faa4ebc8a6d541c3ea8420af , it should fix the issue, please report back if it happens again.

**Comment by seagle0128** [comment]
Thank you for quick fixing!

**Comment by Daskeladden** [comment]
I get a similar error message when reverting buffers.  I'm running GNU Emacs 28.0.50 native comp.  

### Steps to reproduce
- `emacs -Q -l ~/.emacs.d/lsp-start-plain.el`
- Open a .py file
- `M-x revert-buffer`

### Traceback
`
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  =(0 nil)
  (and (= start before-start) (= length (- before-end before-start)))
  (let* ((before-end (plist-get lsp--before-change-vals :end)) (before-start (plist-get lsp--before-change-vals :start))) (and (= start before-start) (= length (- before-end before-start))))
  lsp--bracketed-change-p(0 5792)
  (if (lsp--bracketed-change-p start length) (list ':range (lsp--range (lsp--point-to-position start) (plist-get lsp--before-change-vals :end-pos)) ':rangeLength length ':text (buffer-substring-no-properties start end)) (lsp--full-change-event))
  (if (= start end) (if (lsp--bracketed-change-p start length) (cons ':range (cons (lsp--range (lsp--point-to-position start) (plist-get lsp--before-change-vals :end-pos)) (cons ':rangeLength (cons length '(:text ""))))) (lsp--full-change-event)) (if (lsp--bracketed-change-p start length) (list ':range (lsp--range (lsp--point-to-position start) (plist-get lsp--before-change-vals :end-pos)) ':rangeLength length ':text (buffer-substring-no-properties start end)) (lsp--full-change-event)))
  (if (= 0 length) (list ':range (lsp--range (lsp--point-to-position start) (lsp--point-to-position start)) ':rangeLength 0 ':text (buffer-substring-no-properties start end)) (if (= start end) (if (lsp--bracketed-change-p start length) (cons ':range (cons (lsp--range (lsp--point-to-position start) (plist-get lsp--before-change-vals :end-pos)) (cons ':rangeLength (cons length '...)))) (lsp--full-change-event)) (if (lsp--bracketed-change-p start length) (list ':range (lsp--range (lsp--point-to-position start) (plist-get lsp--before-change-vals :end-pos)) ':rangeLength length ':text (buffer-substring-no-properties start end)) (lsp--full-change-event))))
  lsp--text-document-content-change-event(0 5792 5792)
  (if content-change-event-fn (funcall content-change-event-fn start end length) (lsp--text-document-content-change-event start end length))
  (vector (if content-change-event-fn (funcall content-change-event-fn start end length) (lsp--text-document-content-change-event start end length)))
  (list :textDocument (lsp--versioned-text-document-identifier) :contentChanges (vector (if content-change-event-fn (funcall content-change-event-fn start end length) (lsp--text-document-content-change-event start end length))))
  (lsp-notify "textDocument/didChange" (list :textDocument (lsp--versioned-text-document-identifier) :contentChanges (vector (if content-change-event-fn (funcall content-change-event-fn start end length) (lsp--text-document-content-change-event start end length)))))
  (let ((lsp--cur-workspace workspace)) (lsp-notify "textDocument/didChange" (list :textDocument (lsp--versioned-text-document-identifier) :contentChanges (vector (if content-change-event-fn (funcall content-change-event-fn start end length) (lsp--text-document-content-change-event start end length))))))
  (cond ((eql val 1) (if lsp-debounce-full-sync-notifications (setq lsp--delayed-requests (cons (list workspace (current-buffer) (lsp--versioned-text-document-identifier) (lsp--full-change-event)) (-remove #'(lambda ... ...) lsp--delayed-requests))) (let ((lsp--cur-workspace workspace)) (lsp-notify "textDocument/didChange" (list :contentChanges (vector (lsp--full-change-event))))))) ((eql val 2) (let ((lsp--cur-workspace workspace)) (lsp-notify "textDocument/didChange" (list :textDocument (lsp--versioned-text-document-identifier) :contentChanges (vector (if content-change-event-fn (funcall content-change-event-fn start end length) (lsp--text-document-content-change-event start end length))))))) (t nil))
  (let* ((val (or lsp-document-sync-method (lsp--workspace-sync-method workspace)))) (cond ((eql val 1) (if lsp-debounce-full-sync-notifications (setq lsp--delayed-requests (cons (list workspace (current-buffer) (lsp--versioned-text-document-identifier) (lsp--full-change-event)) (-remove #'... lsp--delayed-requests))) (let ((lsp--cur-workspace workspace)) (lsp-notify "textDocument/didChange" (list :contentChanges (vector ...)))))) ((eql val 2) (let ((lsp--cur-workspace workspace)) (lsp-notify "textDocument/didChange" (list :textDocument (lsp--versioned-text-document-identifier) :contentChanges (vector (if content-change-event-fn ... ...)))))) (t nil)))
  (closure ((save-match-data-internal 0 21 0 11 11 21) (content-change-event-fn) (length . 5792) (end . 5792) (start . 0) cl-struct-lsp--log-entry-tags cl-struct-lsp-session-tags cl-struct-lsp--workspace-tags cl-struct-lsp--registered-capability-tags lsp-mode-menu cl-struct-lsp--folding-range-tags cl-struct-lsp-watch-tags cl-struct-lsp--client-tags lsp--log-lines yas-indent-line yas-inhibit-overlay-modification-protection c-basic-offset company-backends t) (workspace) (let* ((val (or lsp-document-sync-method (lsp--workspace-sync-method workspace)))) (cond ((eql val 1) (if lsp-debounce-full-sync-notifications (setq lsp--delayed-requests (cons ... ...)) (let (...) (lsp-notify "textDocument/didChange" ...)))) ((eql val 2) (let ((lsp--cur-workspace workspace)) (lsp-notify "textDocument/didChange" (list :textDocument ... :contentChanges ...)))) (t nil))))(#s(lsp--workspace :ewoc nil :server-capabilities #<hash-table equal 15/15 0xef92df> :registered-server-capabilities nil :root "/home/ronrande/work/fpga" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect (closure ((test-command closure (lsp-render-markdown-markup-content t) nil (f-exists\? lsp-python-ms-executable)) (command closure (lsp-render-markdown-markup-content t) nil lsp-python-ms-executable) cl-struct-lsp--log-entry-tags cl-struct-lsp-session-tags cl-struct-lsp--workspace-tags cl-struct-lsp--registered-capability-tags lsp-mode-menu cl-struct-lsp--folding-range-tags cl-struct-lsp-watch-tags cl-struct-lsp--client-tags lsp--log-lines yas-indent-line yas-inhibit-overlay-modification-protection c-basic-offset company-backends t) (filter sentinel name environment-fn) (let ((final-command ...) (process-name ...) (process-environment ...)) (let* (... ...) (set-process-query-on-exit-flag proc nil) (set-process-query-on-exit-flag ... nil) (save-current-buffer ... ...) (cons proc proc)))) :test\? (closure (lsp-render-markdown-markup-content t) nil (f-exists\? lsp-python-ms-executable))) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 5/65 0xf73407> :request-handlers #<hash-table equal 0/65 0xf7985d> :response-handlers #<hash-table eql 0/65 0xf7987d> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0xf7b479> :action-handlers #<hash-table equal 0/65 0xf7b499> :major-modes (python-mode) :activation-fn nil :priority 1 :server-id mspyls :multi-root nil :initialization-options lsp-python-ms--extra-init-params :custom-capabilities nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn (closure (lsp-render-markdown-markup-content t) (workspace) (let ((lsp--cur-workspace workspace)) (lsp--set-configuration (lsp-configuration-section "python")))) :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0xf7d499> :download-server-fn (closure (lsp-render-markdown-markup-content t) (client callback error-callback update\?) (if lsp-python-ms-auto-install-server (progn (lsp-python-ms--install-server client callback error-callback update\?)))) :download-in-progress? nil :buffers nil) :host-root nil :proc #<process mspyls> :cmd-proc #<process mspyls> :buffers (#<buffer zhit.py>) :semantic-highlighting-faces nil :semantic-highlighting-modifier-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0xf87d57> :watches #<hash-table equal 0/65 0xf88d2d> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x135c8c1> :work-done-tokens #<hash-table equal 0/65 0xf81431>))
  mapc((closure ((save-match-data-internal 0 21 0 11 11 21) (content-change-event-fn) (length . 5792) (end . 5792) (start . 0) cl-struct-lsp--log-entry-tags cl-struct-lsp-session-tags cl-struct-lsp--workspace-tags cl-struct-lsp--registered-capability-tags lsp-mode-menu cl-struct-lsp--folding-range-tags cl-struct-lsp-watch-tags cl-struct-lsp--client-tags lsp--log-lines yas-indent-line yas-inhibit-overlay-modification-protection c-basic-offset company-backends t) (workspace) (let* ((val (or lsp-document-sync-method (lsp--workspace-sync-method workspace)))) (cond ((eql val 1) (if lsp-debounce-full-sync-notifications (setq lsp--delayed-requests (cons ... ...)) (let (...) (lsp-notify "textDocument/didChange" ...)))) ((eql val 2) (let ((lsp--cur-workspace workspace)) (lsp-notify "textDocument/didChange" (list :textDocument ... :contentChanges ...)))) (t nil)))) (#s(lsp--workspace :ewoc nil :server-capabilities #<hash-table equal 15/15 0xef92df> :registered-server-capabilities nil :root "/home/ronrande/work/fpga" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect (closure ((test-command closure ... nil ...) (command closure ... nil lsp-python-ms-executable) cl-struct-lsp--log-entry-tags cl-struct-lsp-session-tags cl-struct-lsp--workspace-tags cl-struct-lsp--registered-capability-tags lsp-mode-menu cl-struct-lsp--folding-range-tags cl-struct-lsp-watch-tags cl-struct-lsp--client-tags lsp--log-lines yas-indent-line yas-inhibit-overlay-modification-protection c-basic-offset company-backends t) (filter sentinel name environment-fn) (let (... ... ...) (let* ... ... ... ... ...))) :test\? (closure (lsp-render-markdown-markup-content t) nil (f-exists\? lsp-python-ms-executable))) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 5/65 0xf73407> :request-handlers #<hash-table equal 0/65 0xf7985d> :response-handlers #<hash-table eql 0/65 0xf7987d> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0xf7b479> :action-handlers #<hash-table equal 0/65 0xf7b499> :major-modes (python-mode) :activation-fn nil :priority 1 :server-id mspyls :multi-root nil :initialization-options lsp-python-ms--extra-init-params :custom-capabilities nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn (closure (lsp-render-markdown-markup-content t) (workspace) (let ((lsp--cur-workspace workspace)) (lsp--set-configuration (lsp-configuration-section "python")))) :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0xf7d499> :download-server-fn (closure (lsp-render-markdown-markup-content t) (client callback error-callback update\?) (if lsp-python-ms-auto-install-server (progn (lsp-python-ms--install-server client callback error-callback update\?)))) :download-in-progress? nil :buffers nil) :host-root nil :proc #<process mspyls> :cmd-proc #<process mspyls> :buffers (#<buffer zhit.py>) :semantic-highlighting-faces nil :semantic-highlighting-modifier-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0xf87d57> :watches #<hash-table equal 0/65 0xf88d2d> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x135c8c1> :work-done-tokens #<hash-table equal 0/65 0xf81431>)))
  (progn (setq lsp--cur-version (1+ lsp--cur-version)) (mapc #'(lambda (workspace) (let* ((val (or lsp-document-sync-method ...))) (cond ((eql val 1) (if lsp-debounce-full-sync-notifications ... ...)) ((eql val 2) (let ... ...)) (t nil)))) (lsp-workspaces)) (if lsp--delay-timer (progn (cancel-timer lsp--delay-timer))) (setq lsp--delay-timer (run-with-idle-timer lsp-debounce-full-sync-notifications-interval nil #'lsp--flush-delayed-changes)) (lsp--remove-overlays 'lsp-highlight) (lsp--after-change (current-buffer)) (setq lsp--signature-last-index nil) (setq lsp--signature-last nil))
  (if (not revert-buffer-in-progress-p) (progn (setq lsp--cur-version (1+ lsp--cur-version)) (mapc #'(lambda (workspace) (let* ((val ...)) (cond (... ...) (... ...) (t nil)))) (lsp-workspaces)) (if lsp--delay-timer (progn (cancel-timer lsp--delay-timer))) (setq lsp--delay-timer (run-with-idle-timer lsp-debounce-full-sync-notifications-interval nil #'lsp--flush-delayed-changes)) (lsp--remove-overlays 'lsp-highlight) (lsp--after-change (current-buffer)) (setq lsp--signature-last-index nil) (setq lsp--signature-last nil)))
  (let ((inhibit-quit t)) (if (not revert-buffer-in-progress-p) (progn (setq lsp--cur-version (1+ lsp--cur-version)) (mapc #'(lambda (workspace) (let* (...) (cond ... ... ...))) (lsp-workspaces)) (if lsp--delay-timer (progn (cancel-timer lsp--delay-timer))) (setq lsp--delay-timer (run-with-idle-timer lsp-debounce-full-sync-notifications-interval nil #'lsp--flush-delayed-changes)) (lsp--remove-overlays 'lsp-highlight) (lsp--after-change (current-buffer)) (setq lsp--signature-last-index nil) (setq lsp--signature-last nil))))
  (progn (let ((inhibit-quit t)) (if (not revert-buffer-in-progress-p) (progn (setq lsp--cur-version (1+ lsp--cur-version)) (mapc #'(lambda (workspace) (let* ... ...)) (lsp-workspaces)) (if lsp--delay-timer (progn (cancel-timer lsp--delay-timer))) (setq lsp--delay-timer (run-with-idle-timer lsp-debounce-full-sync-notifications-interval nil #'lsp--flush-delayed-changes)) (lsp--remove-overlays 'lsp-highlight) (lsp--after-change (current-buffer)) (setq lsp--signature-last-index nil) (setq lsp--signature-last nil)))))
  (unwind-protect (progn (let ((inhibit-quit t)) (if (not revert-buffer-in-progress-p) (progn (setq lsp--cur-version (1+ lsp--cur-version)) (mapc #'(lambda ... ...) (lsp-workspaces)) (if lsp--delay-timer (progn (cancel-timer lsp--delay-timer))) (setq lsp--delay-timer (run-with-idle-timer lsp-debounce-full-sync-notifications-interval nil #'lsp--flush-delayed-changes)) (lsp--remove-overlays 'lsp-highlight) (lsp--after-change (current-buffer)) (setq lsp--signature-last-index nil) (setq lsp--signature-last nil))))) (set-match-data save-match-data-internal 'evaporate))
  (let ((save-match-data-internal (match-data))) (unwind-protect (progn (let ((inhibit-quit t)) (if (not revert-buffer-in-progress-p) (progn (setq lsp--cur-version (1+ lsp--cur-version)) (mapc #'... (lsp-workspaces)) (if lsp--delay-timer (progn ...)) (setq lsp--delay-timer (run-with-idle-timer lsp-debounce-full-sync-notifications-interval nil ...)) (lsp--remove-overlays 'lsp-highlight) (lsp--after-change (current-buffer)) (setq lsp--signature-last-index nil) (setq lsp--signature-last nil))))) (set-match-data save-match-data-internal 'evaporate)))
  lsp-on-change(0 5792 5792)
  (let ((n (buffer-size)) (revert-buffer-in-progress-p nil)) (lsp-on-change 0 n n))
  lsp-on-revert()
  run-hooks(revert-buffer-internal-hook)
  revert-buffer--default(t nil)
  revert-buffer(t)
  funcall-interactively(revert-buffer t)
  command-execute(revert-buffer record)
  execute-extended-command(nil "revert-buffer" "revert-buffer")
  funcall-interactively(execute-extended-command nil "revert-buffer" "revert-buffer")
  command-execute(execute-extended-command)
`
