### ISSUE TITLE
company-lsp + clangd not working.

### ISSUE THREAD

**Issue by Nethin** [emacs-lsp/lsp-mode#720]
**Describe the bug**
company-lsp can't complete with prefix, while use clangd as LSP server.

**To Reproduce**
1. load company-lsp use lsp-mode's lsp-auto-configure as default. (company-lsp has add into company-backends by lsp-mode).
2. use lsp-mode's default clangd code and configure clangd some start argument("-compile-commands-dir=/data/home/nethinwei/src/lua-5.3.4/" "-pch-storage=memory -log=verbose" "-pretty" in my case).
3. try to complete with company-lsp. like:
![image](https://user-images.githubusercontent.com/6175922/54525617-94704180-49af-11e9-99e5-bc9715e7ec3c.png)
company-lsp don't work and the minibuffer shows "No completion found".
start with not prefix can show candidates but can't continue input:
![image](https://user-images.githubusercontent.com/6175922/54525775-ea44e980-49af-11e9-9df8-6b1a10de7f6a.png)
and the minibuffer says "Matching input is required".

**Expected behavior**
complete with prefix and continue input should be working.

**Which Language Server did you use**
clangd

**OS**
Linux Ubuntu 18

**Error callstack**
clangd seems already reply correctly:
![image](https://user-images.githubusercontent.com/6175922/54525975-5889ac00-49b0-11e9-8d37-0ef4aa4a2910.png)
and short logs:
![image](https://user-images.githubusercontent.com/6175922/54526281-3cd2d580-49b1-11e9-9230-515ad244887c.png)
i remember that company-lsp would't show incomplete candicates, but i found sometimes it don't work like that.

``` emacs-lisp
(require 'projectile)

(defun nethin-projectile-project-initialize (callback)
  "Initialize use CALLBACK while function `projectile-project-root' return not nil."
  (let ((root (projectile-project-root)))
    (when (and root (functionp callback))
      (funcall callback root))))

(defun nethin-clangd-arguments-initialize (project-root)
  "Initialize clangd with PROJECT-ROOT."
  (defvar lsp-clients-clangd-args '("-pch-storage=memory")) ;; if change clangd arguments here. see clangd --help
  (let ((build-dir (expand-file-name "build" project-root))
        (compile-dir-option "-compile-commands-dir="))
    (if (file-directory-p build-dir)
        (cl-pushnew (concat compile-dir-option build-dir) lsp-clients-clangd-args)
      (cl-pushnew (concat compile-dir-option project-root) lsp-clients-clangd-args))))

(defun nethin-c/c++-mode-initilize ()
  "Initialize c/c++-mode."
  (custom-set-variables '(lsp-prefer-flymake nil))
  (custom-set-variables '(lsp-enable-completion-at-point nil))
  (nethin-projectile-project-initialize #'nethin-clangd-arguments-initialize)
  (lsp))

(add-hook 'c-mode-hook #'nethin-c/c++-mode-initilize)
(add-hook 'c++-mode-hook #'nethin-c/c++-mode-initilize)

```

thanks for your great works.

**Comment by yyoncho** [comment]
Duplicate of https://github.com/tigersoldier/company-lsp/issues/92 ?

**Comment by Nethin** [comment]
i have try company-lsp with M-x,still not work and reply the same message. it may course by the same problem.

**Comment by Nethin** [comment]
i will update it later.

**Comment by yyoncho** [comment]
Which version of company-lsp do you use?
(cc @tigersoldier )

**Comment by Nethin** [comment]
i update 20190314.710 from melpa, then it works great. thanks~.
