### ISSUE TITLE
lsp-before-uninitialized-hook is not called

### ISSUE THREAD

**Issue by seagle0128** [emacs-lsp/lsp-mode#726]
I am looking for the solution to do something after shutdown server. I found `lsp-before-uninitialized-hook` is not called by any functions. But in `lsp--uninitialize-workspace`, `lsp-workspace-uninitialized-hook` is called.

Is it as designed or an issue?

**Comment by yyoncho** [comment]
It is has regressed, I guess during the big restructuring, I will fix it.

**Comment by yyoncho** [comment]
Added `lsp-after-uninitialized-hook` which I think makes more sense. Please let me know if you need another hook `lsp-before-uninitialized-hook`.

**Comment by seagle0128** [comment]
`lsp-after-uninitialized-hook` is fine for me, but it seems `lsp-workspace-uninitialized-hook` is still undefined. Should it be removed?

**Comment by yyoncho** [comment]
> Should it be removed?

Done.

**Comment by seagle0128** [comment]
Thank you!
