### ISSUE TITLE
vue-mode document format fails, vetur config is undefined

### ISSUE THREAD

**Issue by larionov** [emacs-lsp/lsp-mode#727]
**Describe the bug**
I'm trying to use lsp with vue-mode and running `lsp-format-buffer` command on a `.vue` file.
It silently fails, document is not formatted.

**To Reproduce**
install lsp-mode, vue-mode, 

```emacs-lisp
(require 'lsp-mode)
(add-hook 'vue-mode-hook #'lsp)

(use-package lsp-mode
  :commands lsp
  :init
  (setq lsp-print-io t)
  )

(add-to-list 'auto-mode-alist '("\\.vue\\'" . vue-mode))
```

Open .vue file, run `M-x lsp-format-buffer`

**Expected behavior**
Buffer gets formatted
**Which Language Server did you use**
lsp-vue with "vue-language-server@0.0.45",
**OS**
Linux

**Error callstack**
``` json
{
  "jsonrpc": "2.0",
  "method": "textDocument/formatting",
  "params": {
    "textDocument": {
      "uri": "file:///home/larionov/projects/ui-packages/components/core/example/src/Example.vue"
    },
    "options": {
      "tabSize": 2,
      "insertSpaces": true
    }
  },
  "id": 7
}
<<<< vls:14897
{
  "jsonrpc": "2.0",
  "method": "$/displayError",
  "params": "Formatting failed: \"TypeError: Cannot read property 'format' of undefined---\"TypeError: Cannot read property 'format' of undefined\\n    at Object.format (/home/larionov/.nvm/versions/node/v10.15.0/lib/node_modules/vue-language-server/dist/modes/template/index.js:69:74)\\n    at modeRanges.forEach.range (/home/larionov/.nvm/versions/node/v10.15.0/lib/node_modules/vue-language-server/dist/services/vls.js:122:46)\\n    at Array.forEach (<anonymous>)\\n    at VLS.onDocumentFormatting (/home/larionov/.nvm/versions/node/v10.15.0/lib/node_modules/vue-language-server/dist/services/vls.js:117:20)\\n    at handleRequest (/home/larionov/.nvm/versions/node/v10.15.0/lib/node_modules/vue-language-server/node_modules/vscode-jsonrpc/lib/main.js:367:27)\\n    at processMessageQueue (/home/larionov/.nvm/versions/node/v10.15.0/lib/node_modules/vue-language-server/node_modules/vscode-jsonrpc/lib/main.js:257:17)\\n    at Immediate.setImmediate [as _onImmediate] (/home/larionov/.nvm/versions/node/v10.15.0/lib/node_modules/vue-language-server/node_modules/vscode-jsonrpc/lib/main.js:247:13)\\n    at processImmediate (timers.js:637:19)\"\nTypeError: Cannot read property 'format' of undefined---\"TypeError: Cannot read property 'format' of undefined\\n    at Object.format (/home/larionov/.nvm/versions/node/v10.15.0/lib/node_modules/vue-language-server/dist/modes/script/javascript.js:302:32)\\n    at modeRanges.forEach.range (/home/larionov/.nvm/versions/node/v10.15.0/lib/node_modules/vue-language-server/dist/services/vls.js:122:46)\\n    at Array.forEach (<anonymous>)\\n    at VLS.onDocumentFormatting (/home/larionov/.nvm/versions/node/v10.15.0/lib/node_modules/vue-language-server/dist/services/vls.js:117:20)\\n    at handleRequest (/home/larionov/.nvm/versions/node/v10.15.0/lib/node_modules/vue-language-server/node_modules/vscode-jsonrpc/lib/main.js:367:27)\\n    at processMessageQueue (/home/larionov/.nvm/versions/node/v10.15.0/lib/node_modules/vue-language-server/node_modules/vscode-jsonrpc/lib/main.js:257:17)\\n    at Immediate.setImmediate [as _onImmediate] (/home/larionov/.nvm/versions/node/v10.15.0/lib/node_modules/vue-language-server/node_modules/vscode-jsonrpc/lib/main.js:247:13)\\n    at processImmediate (timers.js:637:19)\"\nTypeError: Cannot read property 'format' of undefined---\"TypeError: Cannot read property 'format' of undefined\\n    at Object.format (/home/larionov/.nvm/versions/node/v10.15.0/lib/node_modules/vue-language-server/dist/modes/style/index.js:109:30)\\n    at modeRanges.forEach.range (/home/larionov/.nvm/versions/node/v10.15.0/lib/node_modules/vue-language-server/dist/services/vls.js:122:46)\\n    at Array.forEach (<anonymous>)\\n    at VLS.onDocumentFormatting (/home/larionov/.nvm/versions/node/v10.15.0/lib/node_modules/vue-language-server/dist/services/vls.js:117:20)\\n    at handleRequest (/home/larionov/.nvm/versions/node/v10.15.0/lib/node_modules/vue-language-server/node_modules/vscode-jsonrpc/lib/main.js:367:27)\\n    at processMessageQueue (/home/larionov/.nvm/versions/node/v10.15.0/lib/node_modules/vue-language-server/node_modules/vscode-jsonrpc/lib/main.js:257:17)\\n    at Immediate.setImmediate [as _onImmediate] (/home/larionov/.nvm/versions/node/v10.15.0/lib/node_modules/vue-language-server/node_modules/vscode-jsonrpc/lib/main.js:247:13)\\n    at processImmediate (timers.js:637:19)\"\""
}

```

I looked into the source of the error a little bit myself and looks like it expects vetur config to be present in the `:initialization-options` for every format, but lsp-mode sends null instead:
```json
>>> vls:14897 status:starting(async)
Content-Length: 3117

{
  "jsonrpc": "2.0",
  "method": "initialize",
  "params": {
    "processId": 14305,
    "rootPath": "/home/larionov/projects/ui-packages/",
    "rootUri": "file:///home/larionov/projects/ui-packages/",
    "capabilities": {
      ...
    },
    "initializationOptions": null
  },
  "id": 1
}

```

https://github.com/vuejs/vetur/blob/944529207dffc43a9baaa59cf55de791e9c968a0/server/src/modes/script/javascript.ts#L179

But I couldn't make lsp-clients to pass any options using that argument.

**Comment by yyoncho** [comment]
At this point vls configuration is not correct and there is some work that has to be done in order to expose all of the functionality that is present in the vls server, I have created the following gist in the past and I believe that it will fix your issue and also it will expose tons of other features that were not available before that(e. g. better completion, code actions, etc) - https://gist.github.com/yyoncho/1d434b0a24b0eaa1fc4292dde7f5a06c . It is pretty raw, and we should convert it to something configurable and merge it in lsp-mode.

**Comment by larionov** [comment]
@yyoncho it's working! thank you so much.

**Comment by yyoncho** [comment]
@larionov you welcome. Are you willing to help to narrow down what we really need out of this and do a PR against lsp-mode? The package.json manifest of the vscode extension is a good place to start.

**Comment by nobody-famous** [comment]
What is lsp looking for to connect? The gist solves the initial problem, but when I execute lsp it says "No LSP server found for vue-mode".

In my Emacs session,
(executable-find "vls")
returns "c:/Users/rich/AppData/Roaming/npm/vls.cmd"

and
(executable-find "vue")
returns "c:/Users/rich/AppData/Roaming/npm/vue.cmd"

**Comment by yyoncho** [comment]
you have to chage that line -> (lsp-stdio-connection "~/.vscode/extensions/octref.vetur-0.16.2/server/bin/vls")

**Comment by appledelhi** [comment]
@yyoncho I reduced your gist a little bit. It works in my emacs. https://gist.github.com/appledelhi/c2adc3e6cadba726dd417a8d659be84e

**Comment by yyoncho** [comment]
@appledelhi thanks @appledelhi . I am working on a tool that can convert the properties from vscode format to defcustoms (I am assigning the bug to me).

**Comment by larionov** [comment]
Sorry, wasn't around. I don't have much experience working with emacs packages, but wanted to try. If you won't have time for that I can try working on it.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by yyoncho** [comment]
@larionov I am already working on creating a tool which will help to expose the settings for any language server using its package.json declaration. But if you want to help, feel free to pick an issue and ask for help if needed (https://github.com/emacs-lsp/lsp-mode/issues/382 is suitable for example).
