### ISSUE TITLE
which-func-ff-hook error: (error "No workspace could handle textDocument/documentSymbol")

### ISSUE THREAD

**Issue by kaiwk** [emacs-lsp/lsp-mode#729]
**Describe the bug**
enable `which-function-mode`, and then enable `lsp`, it gives this error message.
`lsp` would work, but `which-function-mode` will not show on the mode line.

**To Reproduce**
put follow config
``` 
(which-function-mode t)
(add-hook 'python-mode-hook #'lsp)
```
in init.el, and open a python file.

**Expected behavior**
no error message

**Which Language Server did you use**
pyls

**Comment by finalpatch** [comment]
Got this in c++-mode too (with ccls)

**Comment by yyoncho** [comment]
If you are using lsp-ui you should wait for https://github.com/emacs-lsp/lsp-ui/pull/263 to be merged.
