### ISSUE TITLE
lsp-mode not activated for files opened from the command line

### ISSUE THREAD

**Issue by alanz** [emacs-lsp/lsp-mode#73]
If I do

```bash
$ emacs /tmp/Foo.hs
```
I do not get prompted to start a new LSP session.

**Comment by vibhavp** [comment]
Yes, `find-file-hook` isn't run for such files. The [lsp-start](https://github.com/emacs-lsp/lsp-mode/tree/lsp-start) branch should fix this.

**Comment by vibhavp** [comment]
Should be fixed with the latest branch.
