### ISSUE TITLE
Workspace initialization fails

### ISSUE THREAD

**Issue by MaSven** [emacs-lsp/lsp-mode#731]
**Describe the bug**
After setting up lsp in spacemacs, the first initialization fails with the following error:

> error in process filter: while: Symbol’s value as variable is void: spacemacs-jump-handlers-fundamental-mode

My user-config in spacemacs is the following.
```elisp
(defun dotspacemacs/user-config ()
  (use-package lsp-mode
    :commands lsp
    :ensure t
    :diminish lsp-mode
    :hook
    (elixir-mode . lsp)
    :init
    (add-to-list 'exec-path "/home/sven/git/elixir-ls/release"))
  (with-eval-after-load 'elixir-mode
    (spacemacs/declare-prefix-for-mode 'elixir-mode
      "mt" "tests" "testing related functionality")
    (spacemacs/set-leader-keys-for-major-mode 'elixir-mode
      "tb" 'exunit-verify-all
      "ta" 'exunit-verify
      "tk" 'exunit-rerun
      "tt" 'exunit-verify-single))
```

**To Reproduce**
Install lsp. Go to root folder of mix application. set lsp mode for the first time with C-u M-x lsp.

**Expected behavior**
Projects root gets added to lsp workspace. elixir-mode is saved as default mode.

**Which Language Server did you use**
[elixir-ls](https://github.com/elixir-lsp/elixir-ls)

**OS**
Fedora 29

**Error callstack**

> Debugger entered--Lisp error: (void-variable spacemacs-jump-handlers-fundamental-mode)
  add-to-list(spacemacs-jump-handlers-fundamental-mode (lsp-ui-peek-find-definitions :async t))
  (while --dolist-tail-- (setq m (car --dolist-tail--)) (add-to-list (intern (format "spacemacs-jump-handlers-%S" m)) '(lsp-ui-peek-find-definitions :async t)) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- modes) m) (while --dolist-tail-- (setq m (car --dolist-tail--)) (add-to-list (intern (format "spacemacs-jump-handlers-%S" m)) '(lsp-ui-peek-find-definitions :async t)) (setq --dolist-tail-- (cdr --dolist-tail--))))
  spacemacs//setup-lsp-jump-handler(fundamental-mode)
  (lambda nil "Setup xref jump handler and declare keybinding prefixes" (spacemacs//setup-lsp-jump-handler major-mode) (spacemacs//lsp-declare-prefixes-for-mode major-mode))()
  run-hooks(lsp-after-open-hook)
  lsp--text-document-did-open()
  lsp--open-in-workspace(#s(lsp--workspace :parser #s(lsp--parser :headers nil :body nil :reading-body nil :body-length nil :body-received nil :leftovers "" :workspace #1) :server-capabilities #<hash-table equal 12/65 0x27d7141> :registered-server-capabilities nil :root "/home/sven/git/gitlab_client/" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x14bd0e9>) :test\? #f(compiled-function () #<bytecode 0x14d8dc9>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x14db86d> :request-handlers #<hash-table equal 0/65 0x14db88d> :response-handlers #<hash-table eql 1/65 0x14de9d5> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x14e67c1> :action-handlers #<hash-table equal 0/65 0x14db8ad> :major-modes (elixir-mode) :activation-fn nil :priority -1 :server-id elixir-ls :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :message-trace nil) :host-root nil :proc #<process elixir-ls> :cmd-proc #<process elixir-ls> :buffers (#<buffer mix.exs>) :highlight-overlays #<hash-table eq 0/65 0x2146615> :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x21467c1> :watches #<hash-table equal 0/65 0x21467e1> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x1dd3d69>))
  lsp--find-workspace(#s(lsp-session :folders ("/home/sven/git/gitlab_client/") :folders-blacklist nil :server-id->folders #<hash-table equal 0/65 0x15af235> :folder->servers #<hash-table equal 1/65 0x15b1c39> :metadata #<hash-table equal 0/65 0x15b4b31>) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x14bd0e9>) :test\? #f(compiled-function () #<bytecode 0x14d8dc9>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x14db86d> :request-handlers #<hash-table equal 0/65 0x14db88d> :response-handlers #<hash-table eql 1/65 0x14de9d5> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x14e67c1> :action-handlers #<hash-table equal 0/65 0x14db8ad> :major-modes (elixir-mode) :activation-fn nil :priority -1 :server-id elixir-ls :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :message-trace nil) "/home/sven/git/gitlab_client/")
  #f(compiled-function (client) #<bytecode 0x316acf9>)(#s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x14bd0e9>) :test\? #f(compiled-function () #<bytecode 0x14d8dc9>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x14db86d> :request-handlers #<hash-table equal 0/65 0x14db88d> :response-handlers #<hash-table eql 1/65 0x14de9d5> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x14e67c1> :action-handlers #<hash-table equal 0/65 0x14db8ad> :major-modes (elixir-mode) :activation-fn nil :priority -1 :server-id elixir-ls :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :message-trace nil))
  mapcar(#f(compiled-function (client) #<bytecode 0x316acf9>) (#s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x14bd0e9>) :test\? #f(compiled-function () #<bytecode 0x14d8dc9>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x14db86d> :request-handlers #<hash-table equal 0/65 0x14db88d> :response-handlers #<hash-table eql 1/65 0x14de9d5> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x14e67c1> :action-handlers #<hash-table equal 0/65 0x14db8ad> :major-modes (elixir-mode) :activation-fn nil :priority -1 :server-id elixir-ls :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :message-trace nil)))
  -map(#f(compiled-function (client) #<bytecode 0x316acf9>) (#s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x14bd0e9>) :test\? #f(compiled-function () #<bytecode 0x14d8dc9>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x14db86d> :request-handlers #<hash-table equal 0/65 0x14db88d> :response-handlers #<hash-table eql 1/65 0x14de9d5> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x14e67c1> :action-handlers #<hash-table equal 0/65 0x14db8ad> :major-modes (elixir-mode) :activation-fn nil :priority -1 :server-id elixir-ls :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :message-trace nil)))
  lsp--ensure-lsp-servers(#s(lsp-session :folders ("/home/sven/git/gitlab_client/") :folders-blacklist nil :server-id->folders #<hash-table equal 0/65 0x15af235> :folder->servers #<hash-table equal 1/65 0x15b1c39> :metadata #<hash-table equal 0/65 0x15b4b31>) (#s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x14bd0e9>) :test\? #f(compiled-function () #<bytecode 0x14d8dc9>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x14db86d> :request-handlers #<hash-table equal 0/65 0x14db88d> :response-handlers #<hash-table eql 1/65 0x14de9d5> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x14e67c1> :action-handlers #<hash-table equal 0/65 0x14db8ad> :major-modes (elixir-mode) :activation-fn nil :priority -1 :server-id elixir-ls :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :message-trace nil)) "/home/sven/git/gitlab_client/" nil)
  lsp--try-project-root-workspaces(nil)
  lsp()
  funcall-interactively(lsp)
  call-interactively(lsp record nil)
  command-execute(lsp record)
  helm-M-x((4) #("lsp" 0 3 (match-part "lsp")))
  funcall-interactively(helm-M-x (4) #("lsp" 0 3 (match-part "lsp")))
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)

**Comment by yyoncho** [comment]
This is spacemacs bug, you might fix it locally by doing:

```
(defvar spacemacs-jump-handlers-fundamental-mode nil) ;; probably you will have to the same for spacemacs-jump-handlers-elixir-mode too
```

**Comment by MaSven** [comment]
this worked for me thank you.

**Comment by axelson** [comment]
Is there an upstream tracking link for this?

**Comment by yyoncho** [comment]
@axelson I don't think so. Spacemacs lsp layer is getting out of date, but there is nothing we can do. When spacemacs repo is unlocked I am planning to change the layer so you can use it without having an explicit language specific layer. Similar for dap-mode.

**Comment by axelson** [comment]
Okay, thanks
