### ISSUE TITLE
Powershell support in lsp-mode

### ISSUE THREAD

**Issue by kiennq** [emacs-lsp/lsp-mode#735]
Hi, I've made lsp-mode client that support powershell via [PowerShellEditorServices](https://github.com/PowerShell/PowerShellEditorServices).
The link is here: https://github.com/kiennq/lsp-powershell.
Can you consider adding this into this repo's README, section https://github.com/emacs-lsp/lsp-mode#supported-languages?

**Comment by yyoncho** [comment]
Sure, do you want to provide a pr?
