### ISSUE TITLE
lsp--document-highlight causes error: (wrong-type-argument stringp nil)

### ISSUE THREAD

**Issue by yangyingchao** [emacs-lsp/lsp-mode#745]
**Describe the bug**
 If I select mini-bufer after a source file was modified, but before highlight timer expires, then when timer expires and callback function is invoked, lsp--document-highlight will be called upon min-buffer, instead of original source buffer. As a result, following backtrace will appear:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  find-file-name-handler(nil file-remote-p)
  file-remote-p(nil localname t)
  lsp--path-to-uri(nil)
  lsp--buffer-uri()
  lsp--document-highlight()
  #f(compiled-function () #<bytecode 0x41667669>)()
  apply(#f(compiled-function () #<bytecode 0x41667669>) nil)
  timer-event-handler([t 0 0 200000 nil #f(compiled-function () #<bytecode 0x41667669>) nil idle 0])
  read-from-minibuffer("M-x " "^" (keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-sy
```

**To Reproduce**
1. open a source file and enable lsp (either pyls or ccls).
2. make some changes and stroke m-x quickly
3. wait a moment (wait for timer expires) and error message will be displayed.
 

**Suggestion**
In `lsp--document-highlight' , check if buffer-file-name is valid before calling `lip-request-async' can fix this error, but I'm not sure if this is the right approach. 

``` emacs-lisp

(defun lsp--document-highlight ()
  (when (buffer-file-name)
    (lsp-request-async "textDocument/documentHighlight"
                       (lsp--text-document-position-params)
                       (lsp--make-document-highlight-callback (current-buffer)))))
```

**Comment by yyoncho** [comment]
The proper fix is to try to execute the call from the original buffer if it is present(what you are suggesting will fail if you switch to a buffer without language server associated). 

(cc @sebastiencs )

**Comment by yangyingchao** [comment]
> The proper fix is to try to execute the call from the original buffer if it is present(what you are suggesting will fail if you switch to a buffer without language server associated).
> 
> (cc @sebastiencs )

yeah, that's what I planned to do, but I don't know how, so I raised this issue, and leave to you guys..
