### ISSUE TITLE
Force lsp-ui to always use flake8 for python

### ISSUE THREAD

**Issue by CSRaghunandan** [emacs-lsp/lsp-mode#746]
**Describe the bug**

I have both flake8 and pylint installed on my system and when I open python files, `lps-mode` sometimes starts the flycheck process with `pylint` and other times, it starts `flake8`. I haven't been able to reproduce when only `pylint` is used. It kinda selects randomly I guess?

**Expected behavior**
`lsp-mode` should always use `flake8` as its perforamnce is  much better than `pylint` in emacs. `pylint` suffers from huge performance on large projects.

**Which Language Server did you use**
lsp-python

**OS**
I use archlinux btw

**Comment by yyoncho** [comment]
lsp-mode does not select the linters but pyls - see https://github.com/palantir/python-language-server/issues/532

**Comment by yyoncho** [comment]
@CSRaghunandan  @tsoernes can you retest after https://github.com/emacs-lsp/lsp-mode/commit/28853d54285d3eaca264633b7123da996ce7a746 . I think that pyls just disregards the initialization option and it requires explicit set configuration after it has been started. The property to customize is `lsp-pyls-configuration-sources`  .

**Comment by tsoernes** [comment]
@yyoncho  Great, it works!
By the way I think perhaps the types of these variables are wrong:
```
(defcustom lsp-pyls-rope-extension-modules nil
  "Builtin and c-extension modules that are allowed to be
imported and inspected by rope."
  :type 'string)

 (defcustom lsp-pyls-rope-rope-folder nil
  "The name of the folder in which rope stores project
configurations and data. Pass `null` for not using such a folder
at all."
  :type '(repeat string))
```
Extension modules should probably be a list since you have many; conversely rope folder is just a single folder.

**Comment by yyoncho** [comment]
> By the way I think perhaps the types of these variables are wrong:

They are defined like that: https://github.com/palantir/python-language-server/blob/develop/vscode-client/package.json#L243 so they should be fine unless manifest is wrong.

>   (setq-default 'lsp-clients-python-library-directories
>                 ["/home/torstein/anaconda3/lib/python3.7/site-packages/",
>                  "/home/torstein/anaconda3/",
>                  "/usr/local/lib/python3.7/site-packages/"])
>   (setq-default lsp-pyls-plugins-preload-modules ["numpy", "pandas"])
>   (setq-default lsp-pyls-rope-extension-modules ["numpy", "pandas"])

yes, usually it is written like that:

``` elisp
(setq prop1 va1
         prop2 val2)
```

**Comment by tsoernes** [comment]
@yyoncho If `lsp-pyls-rope-extension-modules` is supposed to be a single string, how should multiple modules be defined? 
`(setq-default lsp-pyls-rope-extension-modules ["numpy", "pandas"])`
or
`(setq-default lsp-pyls-rope-extension-modules "numpy, pandas")
or whatever else?

**Comment by yyoncho** [comment]
Sorry, I have no clue, I am not a python programmer, you may refer to the pyls source code to find the answer. I have only exposed the pyls settings as they are defined by pyls vscode manifest.

**Comment by tsoernes** [comment]
I understand. If `val` in `setq-default prop val` is passed along to python unmodified by the emacs side of things, then indeed should be `:type '(repeat string))` and `(setq-default lsp-pyls-rope-extension-modules ["numpy", "pandas"])`. (Example: https://github.com/python-rope/rope/blob/dcfaf5b6eac6fe1b412a09a907adc0412051502a/ropetest/builtinstest.py#L474)

Conversely for `rope-folder` (example https://github.com/python-rope/rope/blob/b01da7aab5cd02129941d2a900e6e5e3b5f7d4fb/rope/base/project.py#L192).
So the manifest is incorrect. (These settings are not parsed by pyls but passed straight to rope: https://github.com/palantir/python-language-server/blob/63e3cad6f7f5bd9ffa14bd1780c785fe9788c846/pyls/workspace.py#L41)

**Comment by yyoncho** [comment]
> So the manifest is incorrect. (These settings are not parsed by pyls but passed straight to rope: 

Ok, would you like to do a PR to fix them?

**Comment by CSRaghunandan** [comment]
@yyoncho looks like this problem has resurfaced in the latest release :(

Any idea what caused the regression? It used to work before, but after updating lsp-* packages I am running into the same problem

**Comment by yyoncho** [comment]
@CSRaghunandan what information do you need to debug the issue on your side?

**Comment by CSRaghunandan** [comment]
@yyoncho I'm not sure how I can even debug this issue at this point. After adding the configuration for `lsp-pyls-configuration-sources`, it worked for a while and it was always using flake8.

but somewhere around a couple of weeks ago, it stopped working and now is using pylint or flake8 randomly.

**Comment by magonreal** [comment]
Did you set `lsp-pyls-plugins-pylint-enabled` to `nil`?
In my spacemacs, pylint is also too resource hungry. With this setting, it doesn't get activated.

**Comment by CSRaghunandan** [comment]
@magonreal I did not know about this variable.

Thanks a lot. I also found out that rope was being used instead of `jedi` by default. So, disabled that as well and now `lsp-python` is running so much better.

**Comment by AndreaOrru** [comment]
> @CSRaghunandan Did you set `lsp-pyls-plugins-pylint-enabled` to `nil`?
> In my spacemacs, pylint is also too resource hungry. With this setting, it doesn't get activated.

That variable is `nil` for me, but `lsp-ui` is still showing `pylint` errors.

**Comment by noorul** [comment]
@CSRaghunandan Any luck with this?
