### ISSUE TITLE
Emacs freeze during compilation

### ISSUE THREAD

**Issue by myrgy** [emacs-lsp/lsp-mode#748]
Hello,
I'm using spacemacs with lsp + ccls.
Not long ago I noticed, that every time I'm statring comilation inside or outside of emacs ui freeze.
Please, find  profile report below.
My main question is why lsp got notified about any changes in compilation buffer?

**To Reproduce**
enable lsp mode for project
start compilation

**Which Language Server did you use**
lsp-ccls
lsp-mode-20190403.1905
lsp-ui-20190329.357

**OS**
Fedora 29

**Error callstack**
- command-execute                                                5665  74%
 - call-interactively                                            5655  74%
  - byte-code                                                    5186  68%
   - helm-M-x-read-extended-command                              5186  68%
    - helm-comp-read                                             5186  68%
     - helm                                                      5182  68%
      - apply                                                    5182  68%
       - helm                                                    5182  68%
        - apply                                                  5182  68%
         - helm-internal                                         5182  68%
          - helm-read-pattern-maybe                              5156  68%
           - read-from-minibuffer                                4998  66%
            - command-execute                                    4118  54%
             - call-interactively                                4108  54%
              - funcall-interactively                            4106  54%
               - file-notify-handle-event                        4078  53%
                - file-notify-callback                           4071  53%
                 - #<compiled 0x29f625d>                         4017  53%
                  - #<compiled 0x19566e1>                        3945  52%
                   - apply                                       3945  52%
                    - lsp--file-process-event                    3945  52%
                     - seq-do                                    3941  52%
                      - mapc                                     3941  52%
                       - #<compiled 0x39e8ebd>                   3939  52%
                        - lsp-notify                             3718  49%
                         - lsp--send-notification                3717  49%
                          - mapcar                               3715  49%
                           - #<compiled 0x1ca6a3d>               3708  48%
                            - lsp--make-message                  3623  47%
                             - json-encode                       3613  47%
                              - json-encode-list                 3612  47%
                               - json-encode-plist               3582  47%
                                + json-encode                    1905  25%
                                - json-encode-key                1656  21%
                                 - json-read-from-string               1383  18%
                                  + #<compiled 0x37e82b5>               1205  15%
                                  + generate-new-buffer                113   1%
                                    json-read                      31   0%
                                 + json-encode                     20   0%
                                  json-join                         3   0%
                                 json-plist-p                       5   0%
                              lsp--send-no-wait                    70   0%
                        + lsp--path-to-uri                        108   1%
                        + -any?                                   103   1%
                   file-notify--event-file-name                    51   0%
               + helm-next-line                                    19   0%
                 helm-confirm-and-exit-minibuffer                   7   0%
            + timer-event-handler                                 595   7%

**Comment by yyoncho** [comment]
> My main question is why lsp got notified about any changes in compilation buffer?

lsp-mode does not send notifications when compilation buffer changes but when a file on the disk changes. You may ignore these changes by adding your build folder to `lsp-file-watch-ignored` or by disabling the file watch functionality at all via `lsp-enable-file-watchers` .

**Comment by myrgy** [comment]
Thank you @yyoncho !
and you are right - it doesn't send notification. I got it from my build dir.
added my build folder to `ilsp-file-watch-ignored `  - everything works as expected.
Hence closed.
