### ISSUE TITLE
Async processing

### ISSUE THREAD

**Issue by vibhavp** [emacs-lsp/lsp-mode#75]

**Comment by alanz** [comment]
If this means being able to send a request to the server and not wait for the result, but process it when it arrives back, then I am very much in favour.

I am using LSP mode with the haskell backend, and I find the UI hangs noticeable while it is requesting data, such as for hover.

Perhaps we should look at what flycheck does, as that is pretty unintrusive.

**Comment by vibhavp** [comment]
Added in b56a06e5ca4cf01b126521183d2820745b06f63f
