### ISSUE TITLE
[Feature] create modeline indicator for buffer/project/workspace errors statistics

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-mode#750]
We already do that in lsp-treemacs but it would be nice if we have an overview of the errors in the modeline which is visible all of the time.

![Selection_123](https://user-images.githubusercontent.com/13259670/55678279-a6366c00-58ff-11e9-8172-81fd4dcd944d.png)

Here it is what vscode has (by default it lists the errors/warnings/info for all projects in the workspace)
![Selection_124](https://user-images.githubusercontent.com/13259670/55678387-72f4dc80-5901-11e9-8e4d-637a710280a5.png)

**Comment by dangom** [comment]
Isn't this what flymake/flycheck do already?

**Comment by yyoncho** [comment]
@dangom AFAIK they display the information only for the current buffer since they do not have the notion of what project is. Also none of them can list the errors for files that are not opened.
