### ISSUE TITLE
Moving with the arrow keys in a Go project causes a lot of errors

### ISSUE THREAD

**Issue by parhamdoustdar** [emacs-lsp/lsp-mode#751]
**Describe the bug**

When moving in the Go source code buffer, I see a lot of messages like this:

```
LSP :: no identifier found [4 times]```
```

This is correct from the `gopls` point of view – most of the time, my cursor is not on an identifier name (i.e. it's on a space, or `:=`, or in a string, or pretty much anything else other than a variable/function usage).

Based on [this comment](https://github.com/golang/go/issues/31178#issuecomment-480435386) by @stamblerre:

> I would say the problem here lies with lsp-mode, I don't think it's useful to call signatureHelp every time the user moves the cursor.

It looks like this is the same issue but with the `hover` function (log pasted in the relevant section below). In other words, when the `textDocument/hover` method is used and the cursor is not on an identifier, `gopls` returns an error.

@stamblerre, can you please confirm that I understand the gopls side correctly?

**To Reproduce**

1. Install `gopls` and set up a working Go environment
2. Get a package, for example using `go get github.com/bookingcom/shipper`
3. Open one of the go files,  run `M-x lsp <RET>`,and you will see this error occurring very, very often as you move the cursor.

**Expected behavior**
I expect to not see this error.

**Which Language Server did you use**
Go and gopls.

**OS**
Mac OS 10.14.4

**Error callstack**
Here is an example part of the \*lsp-log\*:

```
>>> gopls:71766(async)
Content-Length: 226

{"jsonrpc":"2.0","method":"textDocument/hover","params":{"textDocument":{"uri":"file:///Users/pdoustdar/src/gopath/src/github.com/bookingcom/shipper/cmd/shipperctl/cmd/apply.go"},"position":{"line":2,"character":0}},"id":554}

<<<< gopls:71766
{
  "jsonrpc": "2.0",
  "error": {
    "code": 0,
    "message": "no identifier found",
    "data": null
  },
  "id": 554
}
```

In the \*Messages\* buffer, I see things like this:

```
LSP :: no identifier found [4 times]
```

**Comment by yyoncho** [comment]
As per lsp spec the language server should return null if there is no identifier at the point - https://microsoft.github.io/language-server-protocol/specification#textDocument_hover (the same is true for signatureHelp - https://microsoft.github.io/language-server-protocol/specification#textDocument_signatureHelp ) so gopsp should not return an error when there is no identifier at the point but return null. Also, lsp-mode does not call signature/hover on every cursor move but when the eldoc wants to display context at point (typically 0.5 seconds after you have moved the cursor)  and this is in sync with how eldoc typically works. In case there are performance implications related to this behaviour it could be turned off using `lsp-eldoc-enable-signature-help`. Note that the clients are not supposed to understand the language syntax and somehow "guess" what is symbol for the current language and what is not. For example, `:=` is not sybol for go but it could be symbol for haskell.  The only think that we could do is eat the errors.

**Comment by parhamdoustdar** [comment]
Thanks a lot for the detailed explanation and the links. In that case, I'll open an issue on gopls.

**Comment by shackra** [comment]
> Thanks a lot for the detailed explanation and the links. In that case, I'll open an issue on gopls.

reported correctly for you at https://github.com/golang/go/issues/32967
