### ISSUE TITLE
LSP :: No LSP server for css-mode and LSP :: No LSP server for mhtml-mode.

### ISSUE THREAD

**Issue by fetatefog** [emacs-lsp/lsp-mode#758]
I have my npm installed in custom directory and so i think emacs could not find my install plugin. I am trying to set something like ``(Setq lsp-clients-clangd-executable "path to clangd")`` but i could not find lsp-clients for css and html. Please let me know what should i do to fix this problem

**Comment by yyoncho** [comment]
Inspect \*lsp-log\* and make sure that the corresponding language servers are on the path.

**Comment by fetatefog** [comment]
In lsp-log, they give me this message:
Command "css-languageserver --stdio" is not present on the path.

I am not sure how to set its path. Please guide

**Comment by yyoncho** [comment]
https://superuser.com/questions/488173/how-can-i-edit-the-path-on-linux

**Comment by fetatefog** [comment]
@yyoncho can i use (setenv "...npm/bin") instead?

**Comment by yyoncho** [comment]
I don't know, you may try it? You may use (add-to-list 'exec-path "...") as well.

**Comment by fetatefog** [comment]
ok, will check it out and report later
