### ISSUE TITLE
Weird electric brace/indentation issue (C++)

### ISSUE THREAD

**Issue by chenz** [emacs-lsp/lsp-mode#768]
**Describe the bug**
When lsp-mode is enabled, in some circumstances upon entering a closing curly brace, code is indented in an unexpected manner.

![lsp](https://user-images.githubusercontent.com/7843/56130473-46863380-5f85-11e9-8a45-1b74eb6845d6.gif)

1) lines are collapsed joined into one
2) line below is reindented as well
3) indentation uses 2 spaces instead of 1 tab as configured

**To Reproduce**
```
;; minimal init file
(require 'package)
(package-initialize)

(defun my-c++-mode-hook ()
  (setq indent-tabs-mode t
		tab-width 4
		c-basic-offset 4))
(add-hook 'c++-mode-hook 'my-c++-mode-hook)

(use-package lsp-mode
  :commands lsp
  :hook
  (c++-mode . lsp))
```

```
// test.cpp, tab indented. Entering closing curly after "3" triggers the behaviour
struct Foo
{
	Foo()
		: bars{ 1, 2, 3 

	int bars[3];
};
```
I tried debugging on `c-electric-brace` to see what exactly is causing this, but when I step through the exection in the debugger, I cannot reproduce the behaviour.

**Expected behavior**
Without lsp-mode, the brace is inserted without any modification to the indentation.

**Which Language Server did you use**
clangd 6.0

**OS**
Ubuntu 16.04, Emacs 25.1.1,  lsp-mode 20190415.853 from melpa.

**Comment by yyoncho** [comment]
Take a look at `lsp-enable-on-type-formatting`

**Comment by chenz** [comment]
Turning `lsp-enable-on-type-formatting` off does the trick :thumbsup:

I assume that proper language server based formatting would have to be configured out-of-band (i.e. via a `.clang-format` file)?

**Comment by yyoncho** [comment]
> I assume that proper language server based formatting would have to be configured out-of-band (i.e. via a `.clang-format` file)?

I guess yes but I am not aware of clangd specifics.
