### ISSUE TITLE
lsp-mode package Issues

### ISSUE THREAD

**Issue by seagle0128** [emacs-lsp/lsp-mode#773]
Hi,

1. There is no `Homepage` or `URL` in `lsp-mode` package on melpa.
2. The legacy packages, e.g. `lsp-go`, `lsp-rust, etc. still exist in melpa repo. Should they be removed now?

**Comment by yyoncho** [comment]
Added package url with https://github.com/emacs-lsp/lsp-mode/commit/b7e3aa51160b3cdb6143a278b52d0715ebce14d1 . As far as I can see lsp-go/lsp-rust etc are removed - https://melpa.org/#/?q=lsp ( see also https://github.com/melpa/melpa/pull/5972/files).

**Comment by seagle0128** [comment]
Thank you.
