### ISSUE TITLE
Make starting/stopping the server manual

### ISSUE THREAD

**Issue by rski** [emacs-lsp/lsp-mode#78]
I'd like this instead of automatically starting the server when the mode is activated. As mentioned in https://github.com/emacs-lsp/lsp-mode/issues/51

**Comment by vibhavp** [comment]
That _should_ be possible, once `lsp-mode` can toggle correctly.

**Comment by rski** [comment]
ah ok, if you want to make toggling the mode the thing that toggles the server i'm fine with that

**Comment by alanz** [comment]
I was contemplating putting a toggle in too, for this reason. That would put the workspace root into a temporary var treaded like the current blacklist
