### ISSUE TITLE
.tsx files are handled as .ts while in web-mode

### ISSUE THREAD

**Issue by rassie** [emacs-lsp/lsp-mode#781]
**Describe the bug**
A `.tsx` file edited in `web-mode` is sent as `html` file type to the `typescript-language-server` and thus processed as `.ts` file, resulting in a lot of errors.

**To Reproduce**
1. Open a `.tsx` file with TSX expressions
2. Enable `web-mode` if not already enabled
3. Enable `lsp-mode` and behold a lot of errors in TSX expressions

**Expected behavior**
TSX should be parsed as TSX, i.e. sent as `typescriptreact` to the `typescript-language-server`.

**Which Language Server did you use**
`typescript-language-server`, which is probably `ts-ls`.

**OS**
Ubuntu Linux

EDIT: It's probably a matter of adding a `*.tsx` pattern to `lsp-language-id-configuration`

**Comment by yyoncho** [comment]
What language corresponds to tsx, typescript?

**Comment by yyoncho** [comment]
@rassie can you test https://github.com/emacs-lsp/lsp-mode/pull/782 ?

**Comment by rassie** [comment]
Thanks! I'll try to test it right away!

**Comment by rassie** [comment]
I can confirm it's sending the right language ID now. Thanks!
