### ISSUE TITLE
Race condition with imenu

### ISSUE THREAD

**Issue by yalfg** [emacs-lsp/lsp-mode#784]
First, thanks for lsp-mode!

**Describe the bug**

With the default auto-configuration, when the 'lsp' hook enables LSP mode with imenu there can be a race condition where the LSP imenu hook is called to fill the imenu content before the LSP server is ready. This triggers the following error:

    Error in menu-bar-update-hook (imenu-update-menubar): (error "No workspace could handle textDocument/documentSymbol")

The "Imenu" entry in the menu bar is created but completely empty, there's not even a *Rescan* entry to get unstuck. Reverting the buffer cleans things up.

**To Reproduce**

This is a race so it may be hard or even impossible to reproduce in a different context. On my machine I can systematically reproduce the bug by using 'desktop-save-mode', with a C++ buffer restored using lsp-mode with clangd. When I open a C++ file interactively the race doesn't happen however. 

**Expected behavior**

The Imenu content should be properly created, without error.

**Which Language Server did you use**

C++ with clangd.

**OS**

Debian Buster, with lsp-mode 6.0.

**Error location**

The issue happens when the LSP imenu hook is called on opening a file during a session restore.
When the 'lsp' hook is called, using the default settings with auto-configuration, it will turn on LSP for the buffer and immediately call lsp--auto-configure. This in turn will call lsp-enable-imenu, which will install the LSP imenu hook. Then imenu will call this hook, and if it happens before the LSP server is ready this error will happen.

**Suggestion for a fix**

I've seen there's already work related to imenu and making imenu processing more robust. This may also cover this issue in the end, in the best possible way. However because lsp-mode 6.0 is included in Debian Buster I'm also looking for a short term, simple fix for this issue that could be included in Buster as a Debian specific patch.

I could work-around the race by adding a small delay in lsp--auto-configure, just before the call to lsp-enable-imenu. Just doing a (sleep-for 0.1) there worked-around the race for me. Of course this is not a clean fix. But waiting for the LSP server to be ready there instead of a delay would seem ok to me, with something like "(lsp--wait-for-server-ready)" or like. Would you agree? If yes, what would you recommend to do this waiting? I would hope it should be simple but I'm too ignorant about LSP to fix this on my own.

Thanks!

**Comment by yyoncho** [comment]
Take a look at this commit: https://github.com/emacs-lsp/lsp-mode/commit/b024867c980f14ae1ecff70a375c7c3d2f2a7ea9

**Comment by yalfg** [comment]
Thanks, unfortunately it doesn't help  and I get the same "No workspace could handle textDocument/documentSymbol" error. So somewhat the LSP server replied with the capabilities, as the imenu hook is set-up. But when lsp--imenu-create-index is called, lsp--get-document-symbols fails? So the LSP server is ready, but not yet ready to reply to this specific request?

**Comment by yyoncho** [comment]
@yalfg if you are using lsp-ui you need https://github.com/emacs-lsp/lsp-ui/commit/705357778d8641eadf4508a7371dc00a690b842e as well. Can you toggle-debug-on-error and post the callstack.

**Comment by yalfg** [comment]
Thanks, with the lsp-ui change there is no error anymore. However the imenu content is built before the LSP hook is set in this case (it's a flat list of methods, vs the lsp-mode hierarchical menu). A rescan from the menu itself fixes this and I have the regular LSP hierarchical content. So a much better experience than an error with a blank menu.

Without the lsp-ui patch, if I set debug-on-error it changes the place where the error occurs: instead of menu-bar-update-hook, it's in which-func-ff-hook. Here's the backtrace:
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  undo-tree-current(nil)
  (undo-tree-node-previous (undo-tree-current buffer-undo-tree))
  (and undo-tree-mode (not buffer-read-only) (not (eq t buffer-undo-list)) (undo-tree-node-previous (undo-tree-current buffer-undo-tree)))
  redisplay_internal\ \(C\ function\)()
  message("which-func-ff-hook error: %S" (error "No workspace could handle textDocument/documentSymbol"))
  which-func-ff-hook()
  run-hooks(find-file-hook)
  after-find-file(nil nil)
  find-file-noselect-1(#<buffer cppfile.cc> "~/cppfile.cc" :nowarn nil "~/cppfile.cc" (2417189 49))
  find-file-noselect("/home/user/cppfile.cc" :nowarn)
  desktop-restore-file-buffer("/home/user/cppfile.cc" "cppfile.cc" nil)
  desktop-create-buffer(208 "/home/user/cppfile.cc" "cppfile.cc" c++-mode (abbrev-mode eldoc-mode override-global-mode bar-cursor-mode which-key-mode undo-tree-mode global-auto-revert-mode helm-mode subword-mode hs-minor-mode flyspell-mode lsp-mode flycheck-mode company-mode yas-minor-mode smartparens-mode diff-hl-mode projectile-mode) 16332 (3139 nil) nil nil ((show-trailing-whitespace . 1) (buffer-display-time 23741 56433 63526 238000) (buffer-file-coding-system . undecided-unix)) ((mark-ring (2883 1142 2802 2072 1012 1008 1319 1338 1367 1684 1774 1684 1880 1950 1952 1903 2075 2085 1986 16332))))
  eval-buffer(#<buffer  *load*> nil "/home/user/.emacs.desktop.x1" nil t)  ; Reading at buffer position 7214
  load-with-code-conversion("/home/user/.emacs.desktop" "/home/user/.emacs.desktop" t t)
  load("/home/user/.emacs.desktop" t t t)
  desktop-read()
  #f(compiled-function () #<bytecode 0x10260dd>)()
  run-hooks(after-init-hook delayed-warnings-hook)
  command-line()
  normal-top-level()

This is true even if I set debug-on-error in lsp-enable-imenu, to be as late as possible.

**Comment by yyoncho** [comment]
> Thanks, with the lsp-ui change there is no error anymore. However the imenu content is built before the LSP hook is set in this case (it's a flat list of methods, vs the lsp-mode hierarchical menu). A rescan from the menu itself fixes this and I have the regular LSP hierarchical content. So a much better experience than an error with a blank menu.

This one was fixed by https://github.com/emacs-lsp/lsp-mode/pull/780

**Comment by yalfg** [comment]
With #780 added everything is now fine! I attach the diff on top of 6.0 FYI. I'll follow-up on the Debian side.  Thanks for your help.

[lsp-mode.el.diff.txt](https://github.com/emacs-lsp/lsp-mode/files/3104247/lsp-mode.el.diff.txt)
