### ISSUE TITLE
lsp showing entries from .ccls-cache

### ISSUE THREAD

**Issue by hubgitname** [emacs-lsp/lsp-mode#789]
**Describe the bug**
I configured lip on the rtags project and it was working fine. Then later on when I 
tried some commands it started showing entries from .ccls-cache which is not what I 
expected as .ccls-cache is an internal database.

**To Reproduce**
Configre lsp like so:
```
  (use-package lsp-mode
    :ensure t
    :hook (prog-mode . lsp))
  (use-package lsp-ui
    :ensure t
    :custom
    (lsp-ui-flycheck-enable nil)
    ;; lsp-ui-sideline
    (lsp-ui-sideline-show-symbol t)
    (lsp-ui-sideline-show-hover t)
    (lsp-ui-sideline-enable nil)
    ;; lsp-ui-peek
    (lsp-ui-peek-enable t)
    (lsp-ui-peek-peek-height 20)
    (lsp-ui-peek-list-width 50)
    ;; never, on-demand, or always
    (lsp-ui-peek-fontify 'on-demand))
  (use-package company-lsp
    :ensure t)

  (use-package ccls
    :ensure t
    :after projectile
    :ensure-system-package ccls
    :custom
    (ccls-args nil)
    (ccls-executable (executable-find "ccls"))
    (projectile-project-root-files-top-down-recurring
     (append '("compile_commands.json" ".ccls")
             projectile-project-root-files-top-down-recurring))
    :config (push ".ccls-cache" projectile-globally-ignored-directories))

```

and index the rtags project and do a lsp-ui-peek-find-definition, you'll find it 
displays entries from the .ccls-cache as shown in the below diagram:

**Expected behavior**
As shown in the diagram I expected to see only one definition and leave out the 
.ccls-cache entries.

**Which Language Server did you use**
lsp-ccls

**OS**
MacOS 10.14.2

<img width="1076" alt="lsp-bug" src="https://user-images.githubusercontent.com/37636187/56553899-c9d6f480-6544-11e9-883e-33f8cc585fb6.png">

**Comment by yyoncho** [comment]
Please file this issue into ccls repo.

@MaskRay

**Comment by hubgitname** [comment]
Looks like this is fixed in the most recent version of ccls. Confirmed.
