### ISSUE TITLE
Open a buffer for the server's logs 

### ISSUE THREAD

**Issue by rski** [emacs-lsp/lsp-mode#79]
Ensime does this and it is immensely helpful, as far as I could tell lsp-mode doesn't

**Comment by vibhavp** [comment]
A primitive way to that would be to simply dump all communication with the language server. We can start with and work towards with more structured logs (like magit)

**Comment by vibhavp** [comment]
Also, you can get some basic logging by setting `lsp-print-io` to `t`

**Comment by alanz** [comment]
And for bonus points use the log files as replays for tests.

**Comment by yyoncho** [comment]
Fixed by  @xendk - https://github.com/emacs-lsp/lsp-mode/pull/604
