### ISSUE TITLE
LSP server takes a long time to start with a lot of files open

### ISSUE THREAD

**Issue by muirrn** [emacs-lsp/lsp-mode#792]
If I have a lot (~100) of files open when I (re)start gopls, it takes a while (~10+ seconds) before lsp commands start working. This is because we send many "didOpen" requests which makes the server busy for a while. Would it be possible to delay didOpen request until you visit the buffer for the first time? We would still need to send didOpen request for any buffers that had unsaved changes, of course. This appears to be how VSCode works (i.e. it only sends a didOpen request for the file you are currently viewing when you open VSCode).

**Comment by yyoncho** [comment]
>  Would it be possible to delay didOpen request until you visit the buffer for the first time? 

AFAIK  there is no convenient hook for that - https://stackoverflow.com/questions/47456134/emacs-lisp-hooks-for-detecting-change-of-active-buffer .

You may restart the server by creating a function that does 
```
(lsp-shutdown-workspace)
(lsp)
```

which will start the server only for the current buffer.

**Comment by muirrn** [comment]
That approach leaves all my other buffers disconnected from LSP, and doesn't help when initially starting emacs. What if instead of hooking buffer switching, we do a just-in-time didOpen before any other lsp request for a buffer if we haven't already sent a didOpen for it?

**Comment by yyoncho** [comment]
> That approach leaves all my other buffers disconnected from LSP, and doesn't help when initially starting emacs. 

You may remove `(add-hook  'go-mode-hook 'lsp)` and initiate the connection manually. But yeah, you should care that lsp-mode is started ... 

> What if instead of hooking buffer switching, we do a just-in-time didOpen before any other lsp request for a buffer if we haven't already sent a didOpen for it?

That would work, but it will require more work on lsp-mode side to make it right, e. g there are corner cases related to multiple servers associated with the buffer and it will potentially increase the complexity of the code while the hacky solution outside of lsp-mode does not have to handle these cases since they will never happen in your config. I will investigate whether I will be able to find an elegant and simple solution, otherwise, I would prefer externalizing the solution.

**Comment by muirrn** [comment]
Fair enough. It is a one time pain, so probably not worth it at this point if the only solution is really complicated.

**Comment by yyoncho** [comment]
FYI using emacs 27 with native parsing would speedup emacs a lot(especially with that patch https://lists.gnu.org/archive/html/bug-gnu-emacs/2018-04/msg00419.html ) which is going to make into core.

**Comment by muirrn** [comment]
I don't think the slowness is related to JSON serialization. The problem is Emacs sends gopls 100 files to

**Comment by yyoncho** [comment]
> The problem is Emacs sends gopls 100 files to

... which is json serialization and it is much faster in emacs 27.0.

**Comment by muirrn** [comment]
I don't think the slowness is JSON serialization. The slowness is the server (gopls) gets backed up with work and doesn't respond to queries. There could be some server optimizations to make, but in general it will provide fast startup time if we don't dump all the files to the server at once.

**Comment by fjl** [comment]
> AFAIK there is no convenient hook for that

`window-configuration-change-hook` should be enough. Idea: send `didOpen` for all buffers displayed in a window initially, then send it lazily for other buffers when they are displayed.

**Comment by muirrn** [comment]
@yyoncho would you be receptive to the change described by @fjl? I'm not an elisp expert but I can give it a try.

**Comment by yyoncho** [comment]
@muirrn the change described by @fjl does not require a change in lsp-mode. This pretty much means creating an alternative to MAJOR-mode-hook for invoking `lsp` command. We might document it in README.org though.

**Comment by muirrn** [comment]
Okay, so you are not receptive to the idea that lsp-mode could defer running `lsp` until the buffer is visible?

**Comment by yyoncho** [comment]
@muirrn no, I am fine with that change. What I am saying is that it could be implemented as an external to lsp-mode configuration. My point is that currently running `lsp` mode is configured externally(e. g. it uses major-mode-hook) and we could achieve deferring lsp-mode start without altering.

Something like that:

```
(add-hook 'window-configuration-change-hook
          (lambda () 
            (when (and (not lsp-mode)  ;; check whether lsp-mode is already started
                      (eq major-mode 'go-mode)) ;; check the mode we are interested
                                                                  ;; check buffer visible?
              (lsp))))
```

**Comment by muirrn** [comment]
I understand that you could implement it outside of lsp-mode, but I opened this issue because I think the proposed behavior would be beneficial to all lsp-mode languages/users, so why not have lsp-mode work that way by default?

In particular, users would still run `lsp` via major mode hooks, but `lsp` itself would notice the buffer isn't visible and add the buffer to a deferred list instead of proceeding with the normal initialization. The deferred list gets checked via a `window-configuration-change-hook`, and the buffer is initialized later when it becomes visible.

**Comment by yyoncho** [comment]
> I understand that you could implement it outside of lsp-mode, but I opened this issue because I think the proposed behavior would be beneficial to all lsp-mode languages/users, so why not have lsp-mode work that way by default?

My concern is that this is not something that everyone wants/expects(e. g. helm-imenu-in-all-buffers will stop working, since the language server won't know) and it may end up in confusion since this is not typical. If we want this behaviour and we want to be part of lsp-mode I would rather introduce another entry point(e. g. `lsp-start-defer`) or at least have that feature turned off by default. Also, I would expect if I have 10 files for 10 servers to have the servers started. WDYT?

**Comment by muirrn** [comment]
If there's other things that depend/assume all buffers get loaded, then it makes sense to not change the behavior of `lsp`. I will play around with an implementation for `lsp-deferred` (or whatever) and see how it works, and then we can go from there.

**Comment by muirrn** [comment]
I played around and below is what I came up with. If it looks good in general I'll clean it up and send a PR and you can give detailed feedback. One other thing that will need to change is `lsp--restart-if-needed` since that calls `(lsp)` directly. If "deferred" mode is on, it would need to call `lsp-deferred` instead, to avoid loading all open buffers at once.

I was thinking of not having a separate "deferred" option and just having the alternate `lsp-deferred` function people can use instead of `lsp` in their major mode hooks. Does that sound best to you?

```elisp
(setq lsp-emacs-started nil)
(setq lsp-deferred-buffers nil)

(defun lsp-emacs-startup ()
  (setq lsp-emacs-started t)
  ;; Now that Emacs is done starting, check if there are visible buffers.
  (dolist (buf lsp-deferred-buffers)
    (with-current-buffer buf (lsp-if-visible))))

(add-hook 'emacs-startup-hook #'lsp-emacs-startup)

(defun lsp-if-visible ()
  ;; window-configuration-change-hook gets called for all buffers while Emacs starts,
  ;; so don't trigger lsp mode until Emacs is done starting.
  (when (and lsp-emacs-started (get-buffer-window nil t))
    (lsp)
    (setq lsp-deferred-buffers (delq (current-buffer) lsp-deferred-buffers))
    (remove-hook 'window-configuration-change-hook #'lsp-if-visible)))

(defun lsp-deferred ()
  ;; If buffer is modified or visible in any window of any frame, initialize normally.
  (if (or (buffer-modified-p) (get-buffer-window nil t))
      (lsp)
    (make-local-variable 'window-configuration-change-hook)
    (add-hook 'window-configuration-change-hook #'lsp-if-visible)
    (push (current-buffer) lsp-deferred-buffers)))

(add-hook 'go-mode-hook #'lsp-deferred)
```

**Comment by yyoncho** [comment]
Can you explain why lsp-emacs-startup is needed? I assume that `get-buffer-window` does not work fine until the startup hook is run. 

> I was thinking of not having a separate "deferred" option and just having the alternate lsp-deferred function people can use instead of lsp in their major mode hooks. Does that sound best to you?

I think this is the way to go, since we already have code outside of lsp-mode (e. g. in lsp-treemacs) which assumes that `lsp` will start the server. Even if we change it, the implicit setting that changes the behaviour of lsp may lead to subtle bugs.

**Comment by yyoncho** [comment]
> Can you explain why lsp-emacs-startup is needed? I assume that `get-buffer-window` does not work fine until the startup hook is run.

To elaborate a bit more - can we go only with lsp-deferred which starts the server if it is visible, otherwise it adds the hook like you currently do?

**Comment by muirrn** [comment]
> Can you explain why lsp-emacs-startup is needed?

I started with only `lsp-deferred`, but when starting Emacs, all open buffers were still triggering `lsp` even if they did not end up being visible. It seems like when Emacs is loading the desktop file (or some other part of initialization) `(get-buffer-window)` returns true momentarily for all buffers. The easiest thing I could think of was just waiting for emacs to be done starting before checking if the buffers are visible.

**Comment by yyoncho** [comment]
> I started with only `lsp-deferred`, but when starting Emacs, all open buffers were still triggering `lsp` even if they did not end up being visible.

That is unfortunate... An alternative approach would be to attach lsp-deffered in startup hook and iterate the windows and call lsp only for the buffers that are visible and matching the interesting mode(s). I am fine with the current approach too, so you could go ahead and do a PR.

**Comment by muirrn** [comment]
> An alternative approach would be to attach lsp-deffered in startup hook and iterate the windows

I thought about that, but I was afraid of cases other than startup where you can open a lot of files but have them not be visible. In those cases too I would want the `lsp` call to be deferred.

**Comment by yyoncho** [comment]
> > An alternative approach would be to attach lsp-deffered in startup hook and iterate the windows
> 
> I thought about that, but I was afraid of cases other than startup where you can open a lot of files but have them not be visible. In those cases too I would want the `lsp` call to be deferred.

Won't lsp-deffered's check whether the window is visible guard you?

**Comment by muirrn** [comment]
I think I don't understand your alternative approach.

Here is the current problematic sequence:
1. Start Emacs
1. Emacs loads `go-mode` and calls `lsp-deferred` for all buffers
1. Emacs does something that calls `window-configuration-change-hook` for all buffers
1. `lsp-if-visible` is called for all buffers, and `get-buffer-window` returns true, so `lsp` is called
1. Emacs calls `emacs-startup-hook`

> attach lsp-deffered in startup hook and iterate the windows and call lsp only for the buffers that are visible

I don't understand the suggestion because `lsp-deferred` is already called for all buffers at startup, so doing something different in `emacs-startup-hook` is too late to fix it.

**Comment by yyoncho** [comment]
Here it is what I mean:

1. emacs starts and calls go-mode-hook, nothing happens since there is nothing attached to the hook.
2. startup hook is called and it attaches lsp-deffered to go-mode-hook and iterates all buffers in go-mode 
 and triggers lsp-deffered in them which either starts the lsp server if the buffer is visible or it defers the call(like you currently do).

**Comment by muirrn** [comment]
I see. In that case, the user then couldn't simply do `(add-hook go-mode #'lsp-deferred)` to get the deferred behavior. They would instead have to do something like `(add-to-list 'lsp-deferred-modes 'go-mode)` so lsp-mode could handle when the `lsp-deferred` hook gets added.

**Comment by yyoncho** [comment]
Yes, or have a function like which does all the work like `(lsp-setup-deffered-modes '(go-mode php-mode ...))`.I am not quite sure what do do when startup hook is already called, which is a flow in your solution too.

**Comment by muirrn** [comment]
I'm going to proceed with my original approach since that mirrors the existing `(add-hook 'go-mode-hook #'lsp)` way to hook lsp mode.
