### ISSUE TITLE
Should lsp-mode for javascript support eslint by default?

### ISSUE THREAD

**Issue by testinggithub1222** [emacs-lsp/lsp-mode#794]
I have try to configure lsp-mode and working with javascript and found out that it quite impressive than I expected but there are two things i am not satisfy yet.

1. Flycheck or lsp-ui doesn't work with eslint yet by default. I think if it auto detect .eslintrc file in the root directory and then start eslint check by default without any configuration then it would be nice! I found some tutorial from https://joppot.info/en/2017/09/06/4029 and https://github.com/felipeochoa/rjsx-mode/issues/15 but i could not make it working till now.

2. CSS class completion inside react (js2 or rjsx mode) doesn't work as in vscode.
In my case, my package.json has:
```
"dependencies": {
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-router": "^5.0.0",
    "react-router-dom": "^5.0.0",
    "react-bootstrap": "^1.0.0-beta.8",
    "bootstrap": "^4.3.1",
  }
```

And in my Home.jsx 
```
import React from 'react';

const Home = () => (
    <div className="col"></div>
);

export default Home;
```

I have boostrap and react-bootstrap inside my dependencies which mean in Home.jsx and inside className of div, by pressing Ctrl+Space, bootstrap class would appear there. It work properly inside vscode but when it is in Emacs, i press M-/ it show nothing even when i start typing the first few characters.

**Comment by yyoncho** [comment]
> Should lsp-mode for javascript support eslint by default?

No, lsp-mode is responsible only for communication with language server. If you are looking for integration with other non-lsp solutions lsp-mode is not the place to go but some starter kit or meta package responsible for merging functionality from several packages.

2) did you try to compare communication between client and server in both vscode and lsp-mode?

**Comment by testinggithub1222** [comment]
> some starter kit or meta package responsible for merging functionality from several packages
I am not sure about this. Please clarify.

> did you try to compare communication between client and server in both vscode and lsp-mode?
Not sure what does it mean.

**Comment by yyoncho** [comment]
I checked the eslint implementation in vscode and it does not use lsp backend. Thus, it is out of scope for lsp-mode since it is language server client.
