### ISSUE TITLE
No sideline using  latest version

### ISSUE THREAD

**Issue by numkem** [emacs-lsp/lsp-mode#801]
**Describe the bug**
After updating `lsp-mode` to the latest current version (`20190427.1725`) the lsp-ui sideline doesn't show up anymore. I tried forcing it maually through the configuration but it doesn't do anything.

Was working just fine prior using Go `gopls` lsp server (commit `42b1e5c1f82e56734777529fadba9291e8a9dc15` works).

**To Reproduce**
Using `gopls` with latest version of `lsp-mode` and `lsp-ui`

**Expected behavior**
Sideline should appear

**Which Language Server did you use**
`gopls`

**OS**
Which os do you use?
Arch Linux

**Error callstack**
```
Error running timer: (void-function lsp--cur-line-diagnotics)
LSP :: no identifier found
Error running timer: (void-function lsp--cur-line-diagnotics)
LSP :: no identifier found
Error running timer: (void-function lsp--cur-line-diagnotics)
LSP :: no identifier found
Error running timer: (void-function lsp--cur-line-diagnotics)
```

**Comment by gkmngrgn** [comment]
Hi, I have the same problem in these systems:
1. Win10 + WSL with Ubuntu 18.04
2. Ubuntu 18.04

**Comment by yyoncho** [comment]
Adding this line to your configs will fix the issue untill melpa kicks in.

```
(defalias 'lsp--cur-line-diagnotics 'lsp--cur-line-diagnostics)
```
