### ISSUE TITLE
markdown-mode math support enabled on every hover

### ISSUE THREAD

**Issue by numkem** [emacs-lsp/lsp-mode#802]
**Describe the bug**
The message `markdown-mode math support enabled` appears on every hover which makes it hard to see documentation that is usually on the message output. Sometimes have to try to fight/trick it in order to see the documentation.

**To Reproduce**
Hover on any token that has documentation.

**Expected behavior**
See the documentation and not the `markdown-mode math support enabled` message.

**Which Language Server did you use**
`gopls`

**OS**
Arch linux

**Error callstack**
None :(

**Comment by yyoncho** [comment]
Do you use the latest markdown-mode from melpa?  I am unable to repro using it and gopls. If you can still reproduce the issue can do M-x debug-on-entry markdown-toggle-math and then paste the callstack here so I can inspect what is causing this message.

**Comment by numkem** [comment]
Example for one case:

**Comment by yyoncho** [comment]
Can you try after evaluating this funciton: 
```
(defun lsp--render-markdown ()
  "Render markdown."

  (let((markdown-enable-math nil))
    (goto-char (point-min))
    (while (re-search-forward "&gt;" nil t)
      (replace-match ">"))

    (goto-char (point-min))

    (while (re-search-forward "&lt;" nil t)
      (replace-match "<"))

    (gfm-view-mode)
    (lsp--setup-markdown major-mode)))
```

**Comment by numkem** [comment]
After the evaluation I don't see the message anymore. What is supposed to be in the message?

**Comment by yyoncho** [comment]
>  What is supposed to be in the message?

It is how markdown-mode notifies the users that the math related functionality is on.

**Comment by numkem** [comment]
> What is supposed to be in the message?

What I meant by that is with `gocode` it usually showed the signature of the function you are inside or hovering, was just wondering how that "space" (don't know the emacs term) is supposed to be used by lsp-mode/ui to see if it's behaving correctly.

**Comment by yyoncho** [comment]
@numkem sorry, I do not get what you mean. Are you referring the minibuffer?

**Comment by numkem** [comment]
@yyoncho yes, the minibuffer.

**Comment by yyoncho** [comment]
It depends on the language server. By default, if the language server supports textDocument/signatureHelp and you are in method invocation it will be displayed. Otherwise, it falls back to textDocument/hover.
