### ISSUE TITLE
Failed to install from melpa

### ISSUE THREAD

**Issue by rsuhada** [emacs-lsp/lsp-mode#804]
It is impossible to install lsp-mode from melpa.

Using:

`(use-package lsp-mode
  :commands lsp
  :ensure t
  :config
  (add-hook 'python-mode-hook #'lsp)
  )
`
Gives:

    Failed to install lsp-mode: http://melpa.org/packages/lsp-mode-20190407.739.tar: Not found

Same for `lsp-ui` and `company-lsp`.

**Comment by yyoncho** [comment]
do package-refresh-contents and retry.

**Comment by esjmb** [comment]
Having same problem. I tried a package-refresh-contents with no success.

lsp-mode-20191203.1144.tar not found

Any other ideas?

**Comment by esjmb** [comment]
for those who come after, the problem I had was that I was including two melpa repos - melpa stable and melpa. i removed one and everything worked fine.

**Comment by omerkalkan** [comment]
package-refresh-contents worked for me
