### ISSUE TITLE
Cannot detect .dart files

### ISSUE THREAD

**Issue by LinArcX** [emacs-lsp/lsp-mode#806]
**Describe the bug**
Cannot work with .dart files.

**To Reproduce**
Install and configure lsp-mode and also install dart-language-server via:
`pub global activate dart_language_server`
It put binary file in:
`~/.pub-cache/bin/dart_language_server`
When you open emacs and try to edit a .dart file, nothing happen.

**Expected behavior**
lsp-mode should detect .dart files.

**Which Language Server did you use**
My config files:
https://github.com/LinArcX/Blogit/tree/master/Packages/Emacs

**OS**
Arch linux

**Error callstack**
If there is an error please reproduce the issue with `toggle-debug-on-error` and after setting `lsp-print-io` to t, and then include the callstack and attach the content of `*lsp-log*` buffer.

``` emacs-lisp
(setq lsp-print-io t)
```

**Comment by yyoncho** [comment]
You have to install dart-mode as well.
