### ISSUE TITLE
npm client or lsp for npm?

### ISSUE THREAD

**Issue by testinggithub1222** [emacs-lsp/lsp-mode#809]
I use vsCode and I fount that vsCode has a nice feature in package.json file. It has auto-completion for dependencies name and version. And i think if we have this feature too, it would be nice. I am not sure if it is provided by plugin or built in feature inside vsCode.

**Comment by yyoncho** [comment]
it uses json language server.

**Comment by testinggithub1222** [comment]
@yyoncho: 
https://github.com/Microsoft/vscode-json-languageservice and https://github.com/Microsoft/vscode-languageserver-node these two?

**Comment by yyoncho** [comment]
The first one.

**Comment by testinggithub1222** [comment]
@yyoncho  is there any other better LSP server than this ?

**Comment by yyoncho** [comment]
I don't get your questions. This is what used by vscode.

**Comment by testinggithub1222** [comment]
I just curious if there are other lsp server provided by another third parties and better than the one using in vscode

**Comment by yyoncho** [comment]
@iquiw is working on that as part of: https://github.com/emacs-lsp/lsp-mode/issues/1073
