### ISSUE TITLE
Disable snippet completion if yasnippet is not installed.

### ISSUE THREAD

**Issue by sakshamsharma** [emacs-lsp/lsp-mode#811]
Should not be too difficult / intrusive. I'd been seeing weird completions all the while because I don't use yasnippet.
This is what it looks like if you don't have yasnippet and snippet completions are enabled:
https://imgur.com/a/MNDRTrJ

Related:
https://github.com/emacs-lsp/lsp-mode/issues/542

**Comment by otavio** [comment]
The warning is being shown even when it is installed.

**Comment by yyoncho** [comment]
@otavio fixed with https://github.com/emacs-lsp/lsp-mode/commit/1800dac68f2a142ba551aa61037a0e35a85686db
