### ISSUE TITLE
How Use frameworks like qt?

### ISSUE THREAD

**Issue by LinArcX** [emacs-lsp/lsp-mode#813]
Hi, And thank you for this great effort.
I'm a qt developer, and for vanilla c++, lsp-mode is awesome & enough. But it can't detect qt specific headers or code:
https://raw.githubusercontent.com/LinArcX/Ganje/master/Images/LinArcx/Screenshot%20from%202019-05-01%2012-44-17.png
Is there any way to include qt path to recognize it and get autocomplete for it?

**Comment by yyoncho** [comment]
https://clang.llvm.org/extra/clangd/Installation.html#project-setup refer to clangd docs

**Comment by LinArcX** [comment]
I read it, but I can't understand how to use it and integrate it with lsp-mode.
Any sample would be very helpful.

**Comment by yyoncho** [comment]
> I read it, but I can't understand how to use it and integrate it with lsp-mode.

It does not require any integration with lsp-mode - You should create a build/configuration file for clangd which follows the clangd semantics. It would be better to ask for help in clangd channels.

**Comment by sd44** [comment]
use project_dir/compile_commands.json that created by cmake/bear , can solve this question.
