### ISSUE TITLE
Support `textDocument/selectionRange` request

### ISSUE THREAD

**Issue by matklad** [emacs-lsp/lsp-mode#817]
There's a new provisional API in the protocol: `textDocument/selectionRange`.

[spec](https://github.com/Microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.selectionRange.proposed.md)
[types](https://github.com/Microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.selectionRange.proposed.ts)

This API allows one to extend current selection to an encompassing syntactic construct, and is imo quite useful for many editing tasks. So, it's expand-region which actually knows about the source syntax. 

It might be a good idea to give this API a shot before it is stabilized in the protocol, in case something is missing.

**Comment by matklad** [comment]
Before this was an official proposal, we've implemented an ad-hoc extension for this in rust-analyzer, together with Emacs integration. This code might be a useful starting point: https://github.com/rust-analyzer/rust-analyzer/blob/aa7bdfd37f999607806cf47c0108d33a5b44b3e5/editors/emacs/ra-emacs-lsp.el#L104-L137

**Comment by yyoncho** [comment]
@matklad thanks for the heads up. As a side note, I am excited for the rest of the stuff you have mentioned in the original issue report especially point 3 - https://github.com/Microsoft/language-server-protocol/issues/613 

@vibhavp you may take a look at expand-region package. It allows plugging custom expand method function via er/try-expand-list so we can reuse pretty much everything.

**Comment by yyoncho** [comment]
Fixed with dc86bbb . I will update the readme with guide how to use it with expand-region as part of the release notes.
