### ISSUE TITLE
flow-ls in some cases stops flymake from showing warnings

### ISSUE THREAD

**Issue by MyOde** [emacs-lsp/lsp-mode#823]
**Describe the bug**
Using flymake and flymake-eslint checker, when using a custom flow type, sometimes flymake stops giving warnings.

**To Reproduce**
Fresh flow init.

This correctly reports expected eslint warnings via flymake, in this context:
no-unused-vars warnings for Foobar, foo and the console statement (as per the rules I've set):
``` javascript
// @flow

type Foobar = {
  foo: string,
  bar: number
}

const foo = "foo";

// export default (a: string): Foobar => {
export default (a: string): any => {
  console.log(a);
  return {
    foo: "aaaaa",
    bar: a.length
  };
};
```

While this does not:
```javascript
// @flow

type Foobar = {
  foo: string,
  bar: number
}

const foo = "foo";

export default (a: string): Foobar => {
// export default (a: string): any => {
  console.log(a);
  return {
    foo: "aaaaa",
    bar: a.length
  };
};
```

**Expected behavior**
Flymake warnings from the connected checker to be visible at all times (if present).

**Which Language Server did you use**
Flow language server

**OS**
Arch Linux x86_64
kernel: 5.0.10-arch1-1-ARCH

**Error callstack**
Nothing out of the ordinary in the lsp-log

``` emacs-lisp
(setq lsp-print-io t)
```

**Comment by yyoncho** [comment]
@MyOde what do flymake-running-backends return when you see the issue? Can you provide also all of the project files and eslint related configuration? (I do not use js/flow so it is hard to me to setup an env to reproduce the issue)

**Comment by MyOde** [comment]
flymake-running-backends -> flymake-eslint--checker

Sorry I did not notice the reply earlier!
I'm a bit swamped at the moment, but I'll try to put together an example for reproduction as soon as I get a breather.

**Comment by MyOde** [comment]
Whelp, as per usual, I think this was a configuration issue.
I've reworked some of My config now, and things seem to be running good,
I am sorry for possibly having wasted Your time!

Sadly I am not 100% sure which part of My configuration was causing this, and cannot write it down for future reference.
I'll be closing this now as I myself cannot reproduce it.

**Comment by yyoncho** [comment]
@MyOde No worries - IMO you were somehow overriding the lsp-mode flymake handler, based on https://github.com/emacs-lsp/lsp-mode/issues/823#issuecomment-496425517
