### ISSUE TITLE
Stopping lsp-mode doesn't completely disable it for the buffer

### ISSUE THREAD

**Issue by Stebalien** [emacs-lsp/lsp-mode#824]
**Describe the bug**
`(lsp-mode -1)` doesn't completely disable the language server for the current buffer. Specifically, it doesn't also run `(lsp--managed-mode -1)` so things like the indent function are still set.

**To Reproduce**

1. Enable lsp-mode for a buffer.
2. Disable lsp-mode for the buffer.
3. Try to indent some code. It'll still use the language server and `indent-region-function` will still be set to the lsp one.

**Comment by yyoncho** [comment]
I think that it is symmetrical to what enabling lsp-mode does - it doesn't start the lsp server. You may shutdown the server via lsp-shutdown-workspace which will result in the desired effect. If you are looking for a way to disconnect from the language server without killing the server we may introduce a method lsp-disconnect-workspace.

**Comment by Stebalien** [comment]
This is about buffer-local functionality, not the server/workspace. I'm just trying to disable lsp-mode in the current buffer to work around a bug.

**Comment by yyoncho** [comment]
Ok,  then you need disconnect function. Can you share what is the bug?

**Comment by Stebalien** [comment]
It's probably a bug in spacemacs but I'm not sure. Pasting while recording a macro seems to stop the macro recording and this appears to be related to indenting on paste.

**Comment by yyoncho** [comment]
This is probably related to on-type-formatting. You may disable it via 
```
(setq lsp-enable-on-type-formatting nil)
```

**Comment by Stebalien** [comment]
Unfortunately, spacemacs explicitly calls `indent-region` on past regardless.

**Comment by yyoncho** [comment]
I see. If this is the problem, then `(setq-local indent-region-function nil)` should be fix it.

**Comment by Stebalien** [comment]
Understood, I just want to fix the _actual_ problems (`(lsp-mode -1)` not fully disabling lsp-mode and indentation interfering with macros). However, I'll have to debug the latter a bit before reporting back.

**Comment by raxod502** [comment]
In my opinion, it is very much against best practices for disabling a minor mode to not actually disable its functionality. I had a buffer of Go code that was reporting

```
LSP :: no token file for file:///Users/raxod502/code/upm/main.go
LSP :: no file information for file:///Users/raxod502/code/upm/main.go
LSP :: no AST for file:///Users/raxod502/code/upm/main.go
LSP :: no token file for file:///Users/raxod502/code/upm/main.go
LSP :: no file information for file:///Users/raxod502/code/upm/main.go
```

in the echo area every time I moved the cursor. I didn't want to figure out that whole mess just then, so my first thought was `M-x lsp-mode` to disable it. But the errors didn't go away!

Running `M-x lsp-workspace-shutdown` fixed the issue, but this should not be necessary.
