### ISSUE TITLE
Emacs to support LSP in core?

### ISSUE THREAD

**Issue by alanz** [emacs-lsp/lsp-mode#83]
https://www.reddit.com/r/emacs/comments/696pv1/rms_supports_language_server_protocol_integration/

Is there anything we need to do?

**Comment by vibhavp** [comment]
Stability should be a main priority, IMO. Plus, it would be nice to split off flycheck support to another package, to make `lsp-mode` ELPA compatible.

**Comment by dengste** [comment]
Just a heads-up, in case you don't know: Anything that lands in core or GNU ELPA needs to have copyright assigned to the FSF. So if you're planning to eventually have emacs-lsp in GNU ELPA, you need to go through the contributors that added a non-trivial amount of code (meaning more than ~10 lines) and check if they have signed papers with the FSF.

**Comment by alanz** [comment]
FWIW I have not got this, but would be prepared to do it if required.

**Comment by vibhavp** [comment]
Yep, I'll have to talk to all contributors about the CLA, which could also it harder for a future contributor to get code into the project.

**Comment by dengste** [comment]
Yes, that's the big drawback when you work in Emacs/GNU ELPA. But if you really want to go the GNU ELPA route, you should start as early as possible to only accept contributions by people that have signed papers with the FSF. Getting people to do it later is a terribly frustrating experience, in which you'll often end up ripping code out again (which is especially frustrating when it was already rewritten but still uses traces of the original code, meaning you still have to delete it and force yourself to re-implement it some other way).

**Comment by alanz** [comment]
Perhaps we should have a poll of current contributors to see if they would agree?

**Comment by tutysara** [comment]
I can start working on signing papers with FSF if I am required to

**Comment by vibhavp** [comment]
@alanz a poll would be a good idea, yes. I'll see if I can talk to emacs-devel about this.

**Comment by rski** [comment]
If you are to do this, you should do it as soon as possible or will only get harder to say "yes" as more contributors who haven't signed the papers amass. With <18 contributors and some of them having few enough lines to not require copyright assignment it is a good a time as any to decide.

The benefits of having it in core (or ELPA) are:
- having a cool feature in core emacs which many editors seem to be adopting
- quite a big chance people with experience in Elisp will help

The negatives are higher barrier of entry to contribute plus more that I can't think of right now probably.

Have a thought about this and if you do decide to move forward, I can help round up the contributors

**Comment by vibhavp** [comment]
Inclusion is definitely  beneficial to the project. Having experienced elisp developers help out will be huge, given the recent changes related bugs @alanz and I have been facing. 
What would be the way to proceed? The forms for copyright assignment are located at https://git.savannah.gnu.org/cgit/gnulib.git/tree/doc/Copyright, but I don't know which ones are relevant to our case.

**Comment by rski** [comment]
@vibhavp in the wise words if jwigley "Send a message to assign@gnu.org". That is what I plan to do, send an email there and ask to assign copyright, they should send the required forms etc back.

**Comment by vibhavp** [comment]
Alright, will do so.
@alanz could you move the `intero` code for code actions to `lsp-haskell`? We don't own that specific code, which could be problematic during the assignment process.

**Comment by alanz** [comment]
ok

**Comment by alanz** [comment]
@vibhavp I am assuming you will make contact with assign@gnu.org and let the rest of us know what to do.

**Comment by vibhavp** [comment]
Indeed, waiting for a reply.

**Comment by rski** [comment]
@vibhavp have you gotten a response yet?

**Comment by alanz** [comment]
I'm not sure what this means. It was posted on the haskelll-ide-engine freenode channel

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=29619

**Comment by yyoncho** [comment]
After we started using dash/f/s this is no longer possible. Also, eglot is in the core. Please reopen if you disagree.
