### ISSUE TITLE
Can we support lua language?

### ISSUE THREAD

**Issue by drwx** [emacs-lsp/lsp-mode#831]
Not know well about elisp, but hope lua support by default. Thanks.

**Comment by yyoncho** [comment]
which lua language server is the best?

**Comment by shuxiao9058** [comment]
https://github.com/EmmyLua/EmmyLua-LanguageServer

https://github.com/sumneko/lua-language-server

**Comment by A6GibKm** [comment]
There is also https://github.com/Alloyed/lua-lsp, I don't know which one is better but the later can be easily installed with `luarocks`.

**Comment by yyoncho** [comment]
https://github.com/sumneko/lua-language-server seems to be the most complete but it is not very clear how to do the build outside of vscode.

https://github.com/EmmyLua/EmmyLua-LanguageServer - already has emacs configuration in its readme.

**Comment by yyoncho** [comment]
Added builtin configuration for https://github.com/EmmyLua/EmmyLua-LanguageServer
