### ISSUE TITLE
“.tsx” files are not recognized as TypeScript

### ISSUE THREAD

**Issue by mostafah** [emacs-lsp/lsp-mode#835]
**Describe the bug**
LSP mode has stopped working for TypeScript files that have a `.tsx` extension. By “stopped working” I mean when I open a `.tsx` file, `lsp-mode` is not enabled for it. Even if I enable it manually, none of the features work: jumping to definitions, code completion, highlighting current variable at point in other places, `lsp-ui` does not show any information or report any errors to Flycheck, …

I’m not familiar with how `lsp-mode` works, but I’m guessing that it does not recognize the file as a TypeScript file. Everything works as it should with `.ts` files.

It started after I updated all of my MELPA packages, including `lsp-mode`, `lsp-ui`, and `typescript-mode`. Unfortunately, I don’t remember when was the last time that I had updated them, so I am not sure which version of the packages were working correctly before the update.

**To Reproduce**
Not sure about this, but it happen with all of my `.tsx` files. Here are the parts of my config that might be relevant:

```elisp
;;; LSP

;; Enable lsp-ui.
(require 'lsp-ui)
(add-hook 'lsp-mode-hook 'lsp-ui-mode)

;; Map M-. and M-? to lsp-ui commands, instead of xref, when in lsp mode.
(define-key lsp-ui-mode-map [remap xref-find-definitions]
  #'lsp-ui-peek-find-definitions)
(define-key lsp-ui-mode-map [remap xref-find-references]
  #'lsp-ui-peek-find-references)

;; Do not prefer flymake over flycheck for LSP.
(setq lsp-prefer-flymake nil)

;; Setup company-lsp.
(require 'company-lsp)
(push 'company-lsp company-backends)

;; Setup lsp-mode.
(require 'lsp-mode)

;; Map lsp-rename to C-c C-r.
(define-key lsp-mode-map (kbd "C-c C-r") 'lsp-rename)

;;; TypeScript

;; Use TypeScript mode for .tsx files.
(add-to-list 'auto-mode-alist '("\\.tsx\\'" . typescript-mode))

;; Enable flycheck for TypeScript.
(add-hook 'typescript-mode-hook 'flycheck-mode)

;; Enable LSP mode for TypeScript.
(add-hook 'typescript-mode-hook #'lsp)
;; Disable lsp-ui-sideline for TypeScript.
(add-hook 'typescript-mode-hook (lsp-ui-sideline-mode -1))
```

**Expected behavior**
`.tsx` files should work like `.ts` files: `lsp-mode` should enable for them automatically and recognize them as TypeScript files.

**Which Language Server did you use**
[typescript-language-server](https://github.com/theia-ide/typescript-language-server)

**OS**
macOS 10.14.4

**Error callstack**
A `File mode specification error: (void-function nil)` error appears on `*Messages*`, but I don’t know if it is related to this problem or not. Here is the backtrace after opening a `.tsx` file:

```
Debugger entered--Lisp error: (void-function nil)
  nil()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook typescript-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook typescript-mode-hook))
  run-mode-hooks(typescript-mode-hook)
  typescript-mode()
  set-auto-mode-0(typescript-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer NewSidebar.tsx> "~/soovar/src/app/components/main/NewSidebar.tsx" nil nil "~/soovar/src/app/components/main/NewSidebar.tsx" (12901100902 16777223))
  find-file-noselect("/Users/mostafa/soovar/src/app/components/main/NewSidebar.tsx" nil nil nil)
  find-file("/Users/mostafa/soovar/src/app/components/main/NewSidebar.tsx")
  helm-find-file-or-marked("/Users/mostafa/soovar/src/app/components/main/NewSidebar.tsx")
  helm-execute-selection-action-1()
  helm-execute-selection-action()
  helm-internal(helm-source-find-files "/Users/mostafa/soovar/src/app/components/main/" "Find files or url: " nil "^MoreMenu\\.tsx" "*helm find files*" nil "/Users/mostafa/soovar/src/app/components/main/import" nil)
  apply(helm-internal (helm-source-find-files "/Users/mostafa/soovar/src/app/components/main/" "Find files or url: " nil "^MoreMenu\\.tsx" "*helm find files*" nil "/Users/mostafa/soovar/src/app/components/main/import" nil))
  helm(helm-source-find-files "/Users/mostafa/soovar/src/app/components/main/" "Find files or url: " nil "^MoreMenu\\.tsx" "*helm find files*" nil "/Users/mostafa/soovar/src/app/components/main/import" nil)
  apply(helm (helm-source-find-files "/Users/mostafa/soovar/src/app/components/main/" "Find files or url: " nil "^MoreMenu\\.tsx" "*helm find files*" nil "/Users/mostafa/soovar/src/app/components/main/import" nil))
  helm(:sources helm-source-find-files :input "/Users/mostafa/soovar/src/app/components/main/" :case-fold-search t :preselect "^MoreMenu\\.tsx" :ff-transformer-show-only-basename t :default "/Users/mostafa/soovar/src/app/components/main/import" :prompt "Find files or url: " :buffer "*helm find files*")
  helm-find-files-1("/Users/mostafa/soovar/src/app/components/main/" "^MoreMenu\\.tsx")
  helm-find-files(nil)
  funcall-interactively(helm-find-files nil)
  call-interactively(helm-find-files nil nil)
  command-execute(helm-find-files)
```

There was no `*lsp-log*` buffer.

**Comment by yyoncho** [comment]
This error is not related to lsp mode, probably lsp was never called. I tried the code with the latest lsp-mode and it works fine with tsx files. Can you try M-x lsp

**Comment by mostafah** [comment]
`M-x lsp` works. It enables LSP and all the features work. Thank you. So, that means there is a problem with my Emacs config, right?

Also, sorry for reporting an irrelevant bug report.

**Comment by yyoncho** [comment]
Yes. No problems.
