### ISSUE TITLE
Consider using dart_analysis_server instead of dart_language_server

### ISSUE THREAD

**Issue by itome** [emacs-lsp/lsp-mode#840]
`dart-sdk` now supports language server protocol by `dart_analysis_server`
https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool/lsp_spec/README.md

By using this implementation, we can use lsp-dart without any third party plugins.
And maybe `dart_analysis_server` is faster than `dart_language_server` (I compared with `vim-lsc` with `dart_analysis_server`)

**Comment by yyoncho** [comment]
Willing to provide a PR?

**Comment by itome** [comment]
I created pull request with minimum implementation. -> #841 
I'm not familiar with LSP and lsp-mode, so maybe this pr contains some bags.

**Comment by ram535** [comment]
How do you run **analysis_server.dart.snapshot --lsp**?

When I tried to run it, it said that it is not an executable. And even if I make it executable with **chmod +x**, I can't run it.

**Comment by itome** [comment]
@ram535 
`analysis_server.dart.snapshot` is not executable but dart file.
So we should run
`dart analysis_server.dart.snapshot --lsp`
to run analysis_server.

**Comment by ram535** [comment]
I see, thanks.
