### ISSUE TITLE
Emacs freeze when dealing with large json response.

### ISSUE THREAD

**Issue by itome** [emacs-lsp/lsp-mode#851]
Related to https://github.com/dart-lang/sdk/issues/37060
Dart LSP returns very large json response to `textDocument/completion`.
This makes emacs freeze. May be json parsing process takes long time.
Any ideas to fix this?

**Comment by yyoncho** [comment]
1. Switch to Emacs27 build from sources with native json support. It is 10 times faster(as per Eli's benchmarks).
2. Enable company-lsp caching via setting company-lsp-cache-candidates to auto/t. 

This will make Emacs kind of usable but still, there is some lag when using dart language server(it was sending ~2mbs which were parsed for ~200ms on my machine if memory serves me right).

I raised that concern in emacs-devel: http://emacs.1067599.n8.nabble.com/bug-31138-Native-json-slower-than-json-el-td453317.html  (cc @Eli-Zaretskii)

**Comment by Eli-Zaretskii** [comment]
Speed and responsiveness are two sides of the same coin.

In any case, your observations are from a year ago, how about trying the latest code?  It no longer calls UTF-8 decoding function when the string we get from Jansson library is UTF-8.

**Comment by yyoncho** [comment]
@Eli-Zaretskii I think that I tested with emacs that was compiled with decoding disabled.

@itome do you plan to test with emacs 27.0 native parsing? I could do the performance testing but IMO it would be better to have a report from someone who is actually using dart for actual work. I hope that with @Eli-Zaretskii's help we could match VScode's performance.

**Comment by itome** [comment]
@yyoncho Yeh, I will test emacs 27.
How can I get benchmark for `textDocument/completion` ?

**Comment by yyoncho** [comment]
@itome Just use emacs as you normally do when coding and if the performance is sufficient for normal use we will consider this issue as fixed. Otherwise, do:

1. `M-x profiler-start` 
2. Normal usage
3. `M-x profiler-report` and post the expanded performance report here or in a gist(`C-u` `TAB` to expand a node).

PS: do not forget to turn on company-lsp caching via `company-lsp-cache-candidates`

**Comment by Eli-Zaretskii** [comment]
If you tried the latest master branch, then I don't understand your comment.  The discussion which you cited, where you said that native JSON support is slow, was a year ago, way before the current code which avoids decoding when possible was written and committed.

**Comment by yyoncho** [comment]
@Eli-Zaretskii I meant something else but I think that there is no point to discuss that, let's focus on the current performance which is the only thing that really matters.

**Comment by itome** [comment]
I installed 27.0.50 in my mac and here is profiler report ↓
https://gist.github.com/itome/3b19e96491856d4469bbcc1098b0d0ff
Native json support may have some better performance.

**Comment by yyoncho** [comment]
It is hard to tell from the perf reports but do you get freezes and are you satisfied with the performance when using emacs 27?

**Comment by itome** [comment]
@yyoncho 
It's better but not satisfied.
Emacs freezing is fixed, but not completion is still late.

**Comment by Eli-Zaretskii** [comment]
According to the profile, `sit-for`, called by `company--fetch-candidates`, takes the lion's share of the time.  Which seems to mean Emacs just wastes time waiting for some input.  So maybe the developers of Company could help you out.

**Comment by yyoncho** [comment]
@itome can you update the lsp-mode README with instructions on how to install dart-lang SDK language server? I want to do run some performance tests. Based on the fact that emacs does not hang I think that most of the time is spent on the server and reading from stdout. I haven't checked that but if dart language server is using node IPC when it is running in vscode it does not hit the serialization related issue since there is no such. FTR this will solve our issues too: https://github.com/dart-lang/sdk/issues/37060#issuecomment-495241909

**Comment by itome** [comment]
I created PR
https://github.com/emacs-lsp/lsp-mode/pull/859

**Comment by fetatefog** [comment]
@yyoncho, would you mind give me doc or whatsoever that can help me build emacs 27 from source with some option like you state? I could not find any detail relate to this.
> build from sources with native json support.

**Comment by yyoncho** [comment]
@fetatefog look for a guide specific for your distribution, I am using this guide - https://www.reddit.com/r/emacs/comments/8pcw5a/what_is_the_most_painless_way_to_install_emacs_26/e0aem3u/

**Comment by yyoncho** [comment]
@itome can you help me create an example project which produces such big responses? I tried creating a project with 

```
stagehand console-full
```

and then when I tried completing it was very fast.

**Comment by itome** [comment]
Try `flutter` repository,
https://github.com/zesage/flutter_compass
↑ This is very simple project but completion is very slow in `build` function.

**Comment by itome** [comment]
This issue fixed for me by dart server enhancement. I close this PR. Thanks.

**Comment by itome** [comment]
Related dart issue -> https://github.com/dart-lang/sdk/issues/37060
