### ISSUE TITLE
Rust and new RLS process for every new buffer

### ISSUE THREAD

**Issue by GoingFast** [emacs-lsp/lsp-mode#861]
Not sure if its a bug or intended, but its creating a new RLS process for every single new buffer. Havent noticed any perfomance issues to make me alert, but just right now noticed almost 10GB memory used by tens of RLS processes, its bit crazy. What can be done about it?

**Comment by yyoncho** [comment]
Sounds like some misconfiguration, what does lsp-describe-session yields?

**Comment by GoingFast** [comment]
```
[X] /home/lhe/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.1.17/
[X] /home/lhe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/
[X] /home/lhe/.cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.1.15/
[-] /home/lhe/code/warptest/
 `-[-] rls:5643
    |-[-] Buffers
    |  |-[+] db.rs
    |  `-[+] users.rs
    `-[+] Capabilities
[X] /home/lhe/.cargo/registry/src/github.com-1ecc6299db9ec823/num_cpus-1.10.0/
[-] /home/lhe/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/
 `-[-] rls:6381
    |-[-] Buffers
    |  `-[+] marker.rs
    `-[+] Capabilities

```

this happens when I press "gd" which is "lsp-ui-peek-find-definitions".

my configuration:
```
(use-package lsp-mode
  :config
  (setq lsp-prefer-flymake nil
        lsp-enable-snippet nil
        lsp-eldoc-prefer-signature-help nil
        lsp-eldoc-enable-signature-help nil
        lsp-eldoc-enable-hover nil
        lsp-session-file (concat risto-emacs-cache-directory "lsp-session")
        lsp-auto-guess-root t
        lsp-keep-workspace-alive nil))

(use-package lsp-ui
  :general
  (general-define-key
   :keymaps '(lsp-ui-mode-map)
   :states 'normal
   [remap xref-find-definitions] #'lsp-ui-peek-find-definitions
   "gD" #'lsp-ui-peek-find-references)
  :config
  (setq lsp-ui-sideline-enable t
        lsp-ui-peek-fontify 'always
        lsp-ui-doc-enable nil))

```

**Comment by yyoncho** [comment]
This is the expected behaviour when you have set lsp-auto-guess-root - when you open a new folder it looks for a project and automatically creates a new one if it is missing. I would recommend that option only if you are familiar with the lsp-mode/projectile/project internals. Alternativelly, you may use :library-folderns-fn (check lsp-pyls.el) to instruct lsp-mode to use these files as part of the active workspace.

**Comment by GoingFast** [comment]
Yep :library-folders-fn works and no new processes however its not implemented for lsp-rust by default. Possible to add it?

**Comment by yyoncho** [comment]
@GoingFast feel free to provide a PR - I am not a rust user and I am not familiar with what are the appropriate defaults for library folders, etc.

**Comment by yyoncho** [comment]
@GoingFast if you need some you have questions on how to do that or need any help you may ping me here or in gitter.
