### ISSUE TITLE
Wrong `languageId` for LaTeX

### ISSUE THREAD

**Issue by astoff** [emacs-lsp/lsp-mode#863]
In `latex-mode`, a null value is sent to the server as `languageId`; it should be `latex`.

A similar issue happens for `plain-tex-mode`, but I'm not sure what the appropriate value is. I'd say stripping `-mode` from the symbol name should almost always work correctly anyway.

The language server I'm testing, in case you are interested in adding to the list of pre-configured ones, is [this one](https://github.com/astoff/digestif).

``` emacs-lisp
(lsp-register-client
 (make-lsp-client :new-connection (lsp-stdio-connection "digestif")
                  :major-modes '(latex-mode plain-tex-mode)
                  :server-id 'digestif))
```

**Comment by yyoncho** [comment]
Take a look at `lsp-language-id-configuration`.

**Comment by astoff** [comment]
So you are not going to fix this bug? The `languageId` field is not allowed to be null. Thus, lsp-mode should either refuse to start or guess the `languageId` if it's not in that list.

**Comment by yyoncho** [comment]
@astoff I thought that you are asking what to do when there is no language id for the file. Alternatively, we may add a warning when there is no language ID for the current mode.

**Comment by astoff** [comment]
How about guessing the `languageId` field from the major mode's symbol name (by removing the "-mode" at the end)? Then about half of the entries of `lsp-language-id-configuration` could be deleted.

Otherwise, providing the `languageId` essentially becomes part of registering a new server. That's fine too, but then it would make more sense to provide this as an argument of `make-lsp-client`.

**Comment by yyoncho** [comment]
> How about guessing the languageId field from the major mode's symbol name (by removing the "-mode" at the end)?

it is technically possible and it will shave some code. The drawback is that if someone is adding a new server and the mode name does not match the language the error will be hidden(like now) which IMO is worse than having few extra lines. Some of the language servers do not report an error when they see unexpected languageId but they disable certain functionality and it is virtually impossible to guess why it does not work(it has happened in the past).

> Otherwise, providing the languageId essentially becomes part of registering a new server. That's fine too, but then it would make more sense to provide this as an argument of make-lsp-client.

I agree. It is part of the registration but for some reason which I cannot remember right now, I decided to keep it out of the registration. IMO adding the possibility to specify the language id mapping while doing the registration + error/warning when there is no such will be most intuitive, what do you think?

**Comment by astoff** [comment]
> Some of the language servers do not report an error when they see unexpected languageId but they disable certain functionality and it is virtually impossible to guess why it does not work(it has happened in the past).

In this case, specifying the languageId while doing the registration sounds like a good plan. Or perhaps it's enough to just be more explicit in the example at https://github.com/emacs-lsp/lsp-mode/blob/master/README.org#registering-server (I only looked at the code snippet and missed this detail).

**Comment by yyoncho** [comment]
Which language server did you use? Can you also attach the client server communication?

**Comment by yyoncho** [comment]
I have pushed a fixed, can you take a look at comment?

**Comment by yyoncho** [comment]
I have pushed a fixed, can you take a look at comment?

**Comment by astoff** [comment]
The change in the code looks good. As to the change in the README, should't one use

``` elisp
(add-to-list 'lsp-language-id-configuration '(python-mode . "python"))
```

rather than a `defvar`?

**Comment by yyoncho** [comment]
It depends on whether you are adding the support as part of lsp-mode or you are doing that in an external package. I added https://github.com/emacs-lsp/lsp-mode/commit/f110a8f0fd316bcd87396fbea2dce3617bca9d5e to clarify that.
