### ISSUE TITLE
`lsp-symbol-highlight` should retrigger flycheck if necessary

### ISSUE THREAD

**Issue by smarter** [emacs-lsp/lsp-mode#87]
`lsp-symbol-highlight` calls `lsp--remove-cur-overlays` which may remove in-buffer highlighting done by flycheck. To counter that, `lsp-symbol-highlight` should call flycheck if it's enabled in the buffer after adding its own highlighting.

**Comment by vibhavp** [comment]
Instead of calling `flycheck-buffer` every time, what about recording previous overlays and restoring them? I think that would be less resource intensive.

**Comment by smarter** [comment]
Yes, if that's possible that would be even better :).
