### ISSUE TITLE
Typescript not recognising tsconfig.json settings

### ISSUE THREAD

**Issue by eastwood** [emacs-lsp/lsp-mode#873]
**Describe the bug**
LSP mode is reporting linting errors for typescript projects that do not adhere to `tsconfig.json` settings.

**To Reproduce**
1. Clone repo: https://github.com/eastwood/lsp-typescript-demo
2. `npm install` in repo
2. Using config settings from [here](https://github.com/eastwood/config/blob/master/emacs.d/init.el)
3. Notice that in the `src/index.ts` file I receive this error:
> An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.

Despite having `lib: ["es2015"]` and 1`target: "es6"` in my `tsconfig.json

**Expected behavior**
No linting errors. Just as if I ran `tsc` manually

**Which Language Server did you use**
typescript-language-server

**OS**
OSX

**Error callstack**
```
[Trace - 11:54:45 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {
  "diagnostics": [
    {
      "source": "typescript",
      "code": 2705,
      "severity": 1,
      "message": "An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.",
      "range": {
        "end": {
          "character": 39,
          "line": 8
        },
        "start": {
          "character": 24,
          "line": 8
        }
      }
    }
  ],
  "uri": "file:///Users/cryan/Workspace/cryan/typescript-test/src/index.ts"
}
```

**Comment by eastwood** [comment]
It's worth mentioning that enabling `tide-mode` instead of `lsp-mode` results in expected behaviour

**Comment by yyoncho** [comment]
Unable to reproduce. I do not have that error bu. Can you make sure that you have the latest of everything(lsp-mode, server components) and that you have picked the correct project root and retry?

**Comment by eastwood** [comment]
Thanks for having a go, i'll try and improve repro

**Comment by eastwood** [comment]
I've updated the `typescript-language-server` to `0.3.8`, and `lsp-mode@6.1`. How do I check the correct project root? I'm just using projectile to find it

**Comment by eastwood** [comment]
Also, did you `npm install` the package?

**Comment by yyoncho** [comment]
Yes, I did npm install.

To check the project root do `lsp-describe-session`.

**Comment by eastwood** [comment]
Yep project root is correct. When I `npm install` the error shows up, but when I delete the `node_modules`, it disappears. It's like when using `devDependencies` it's not finding the `tsconfig` correctly. And when I don't have `node_modules` installed, changing the `tsconfig` file reproduces the error i'm seeing

**Comment by yyoncho** [comment]
I tested with javascript-typescript-languageserver it works too. 

FTR I am getting the error if I do npm install and then I delete the node_modules.

**Comment by eastwood** [comment]
hmmm, mk.

Well the error disappears when I move the tsconfig.json into the `src` directory

**Comment by yyoncho** [comment]
I am not sure we can do anything on lsp-mode side since this looks like a server side issue...

**Comment by eastwood** [comment]
@yyoncho can I manually set the typescript server path to test if that's the cause?

**Comment by yyoncho** [comment]
Yes, you may alter `lsp-clients-typescript-server-args` and the language server accepts the following arguments:  

```
  --tsserver-path <path>                 Specify path to tsserver. example: --tsserver-path=tsserver
```

**Comment by eastwood** [comment]
No luck, with:
```
(defun my/use-tsserver-from-node-modules ()
  "Gets eslint exe from local path."
  (let (tslint)
    (setq tslint (projectile-expand-root "node_modules/typescript/bin/tsserver"))
    (setq-default lsp-clients-typescript-server-args `("--stdio" "--tsserver-path" ,tslint))))
```

I have found this in my `lsp-log` buffer? Could this contribute?
> Command "javascript-typescript-stdio" is not present on the path.
Command "typescript-language-server --stdio" is present on the path.
Found the following clients for /Users/cryan/Workspace/nib.com.au/cryan/typescript-test/src/index.ts: (server-id ts-ls, priority -2)
The following clients were selected based on priority: (server-id ts-ls, priority -2)

**Comment by eastwood** [comment]
Also, when upgrading to typescript latest in the repo, the error goes away. Perhaps an issue with the lsp server version and `typescript@2.3.4`?

**Comment by yyoncho** [comment]
> Also, when upgrading to typescript latest in the repo, the error goes away. Perhaps an issue with the lsp server version and `typescript@2.3.4`?

I guess so.
