### ISSUE TITLE
`lsp-describe-thing-at-point` for Rust doesn't work on macros

### ISSUE THREAD

**Issue by vishesh** [emacs-lsp/lsp-mode#876]
**Describe the bug**
`lsp-describe-thing-at-point` should show documentation for the current symbol. However, when doing so over macros such as `println!` or `assert_eq` it the documentation popup is empty. Similarly when hovering over the symbol in `lsp-ui-doc-mode` nothing shows up.

**To Reproduce**
- Write a program which uses macro such as `println!` or `assert_eq!`.
- Move cursor over the symbol, and run `lsp-describe-thing-at-point`.

**Expected behavior**
Documentation of `println!` should show up in a popup window.

**Which Language Server did you use**
`lsp-rust`

**OS**
Linux (Fedora 30), Emacs 26.2

**Comment by yyoncho** [comment]
This is up to the server to provide that information, lsp-mode is just a front end. This PR should be filed against RLS language server but IMO they are aware that fact and already have a tracking ticket.
