### ISSUE TITLE
Support for Terraform?

### ISSUE THREAD

**Issue by howdoicomputer** [emacs-lsp/lsp-mode#878]
There is a Terraform LSP in development here: https://github.com/juliosueiras/terraform-lsp

It seems to be not super far along but it's something.

**Comment by yyoncho** [comment]
There are instructions on how to make it work at  https://github.com/juliosueiras/terraform-lsp#emacs @howdoicomputer willing to test it and provide a PR?

**Comment by Gastove** [comment]
This can be assigned to me -- I've got a bunch of terraform to do anyways, having LSP for it would help :+1:
