### ISSUE TITLE
Should disable company-capf when company-lsp is present

### ISSUE THREAD

**Issue by muirrn** [emacs-lsp/lsp-mode#884]
**Describe the bug**
I use company-lsp, which works great. However, when I'm typing and company-lsp gets zero completions from the lsp server (e.g. I'm typing a comment or string literal), company mode falls back to company-capf which starts doing blocking completion calls which slows my typing way down, sometimes pausing for seconds.

**To Reproduce**
Using gopls server, type some normal code, run `company-diag` and see that it is using "company-lsp" backend. Now start typing a comment and run `company-diag` and see that it is using  "company-capf".

**Expected behavior**
I expected it to use the company-lsp results and not fall back to company-capf. They both get results from the same place, so it doesn't make sense to query the backend twice (especially considering company-capf is blocking).

**Which Language Server did you use**
gopls

**OS**
Mac

**Comment by yyoncho** [comment]
I agree - there were problems related to that in the past.
