### ISSUE TITLE
Consider "batching" requests/notifications to the server

### ISSUE THREAD

**Issue by muirrn** [emacs-lsp/lsp-mode#885]
**Describe the bug**
lsp-mode sends many individual requests/notifications to the LSP server with every keystroke. With gopls for example, every keystroke normally sends a "didChange", "documentHighlight", "signatureHelp", and "hover". When you are typing fast, this can put undue load on the server and slow things down (or cause worse problems if the LSP server doesn't handle it well). I think VSCode does some sort of "batching" to avoid sending tons of small requests when the user is typing.

**To Reproduce**
Using gopls, turn on `lsp-print-io` and start typing in a go buffer. You will see every keystroke sends a bunch of notifications/requests.

**Expected behavior**
lsp-mode is smarter and has some timeout or other smarts to avoid sending a bunch of requests that are obselete 10ms later when the next key is pressed.

**Which Language Server did you use**
gopls

**OS**
Mac

**Comment by yyoncho** [comment]
AFAIK the only request which does not have a delay is didChange, vscode does that too. This is the only request for which the client side batching will make sense. We have discussed that a lot in the past and the conclusion was that the server should add debounce processing of didChange events(hie, jdtls, ccls does that, probably the rest do that too). 

Check: `lsp-links-check-internal`, `lsp-document-highlight-delay`, `lsp-ui-sideline-delay` and `eldoc-idle-delay` .  

(IMO the default values are a bit aggressive)

**Comment by muirrn** [comment]
Ah, I see. I saw multiple "hovers" and the like, but I think one was from switching into the buffer, not from typing. If we already do the same thing as VSCode then I'm happy. I'm also working to get gopls in particular to behave better.
