### ISSUE TITLE
Company completions does not respect user input.

### ISSUE THREAD

**Issue by proofit404** [emacs-lsp/lsp-mode#886]
Hi,

Sorry to ask this question in the bug tracker but Gitter doesn't support image upload.

I don't know if this is the right behavior, but company variants do not filter according to my input.

![Untitled](https://user-images.githubusercontent.com/1862725/59547352-3fa87c80-8f46-11e9-918f-a38121c6f560.png)

This makes the auto-complete option mostly unusable to me.

**Comment by yyoncho** [comment]
Which language server do you use? Can you make sure whether company-lsp filtering is enabled by inspecting  company-lsp-filter-candidates?

**Comment by yyoncho** [comment]
Any update?

**Comment by proofit404** [comment]
Hi @yyoncho 

Sorry for the delay!

I checked out `company-lsp` filter settings. Python language server doesn't filter candidates by default.

Looks like the problem was in my config.

Thanks for suggestions!
