### ISSUE TITLE
.ts files are handled as javascript files, when using js2-mode

### ISSUE THREAD

**Issue by gustavo-depaula** [emacs-lsp/lsp-mode#887]
**To Reproduce**
Open a `.ts` file with js2/rjsx-mode (that has support for typescript), and you'll see a lot of errors like `8006`, `8011`, `8010`.

**Expected behavior**
As a typescript file is open, it should be handled as a typescript file.

**Which Language Server did you use**
`typescript-language-server`

**OS**
macOS

**Do you have any suggestions?**
The solution would be the same as the solution for #781, fixed in #782.
I solved this for my configuration using this:
```
(after! lsp-mode
  (add-to-list 'lsp-language-id-configuration '(".*.ts" . "typescript")))
```
I may open a PR adding this line `lsp-language-id-configuration` if the maintainers think that this solution should be generalized (all `ts` files should be treated as typescript files no matter the mode)

**Comment by yyoncho** [comment]
Yes, this is the proper solution. VScode maps the file pattern -> languageId which I think is the correct way to handle. Feel free to open a PR.

**Comment by gustavo-depaula** [comment]
@yyoncho noobie question, I forked, cloned, and made the modification, how do I test it on my emacs locally?

**Comment by yyoncho** [comment]
It depends on what you are using for your configuration. For example, if you are using use-package you may configure it to download the package from your fork like this - https://framagit.org/steckerhalter/quelpa-use-package .

For spacemacs I do:

`ln -s ~/Sources/lsp/lsp-mode/* ~/.emacs.d/elpa/27.0/develop/lsp-mode-*/ -f `

You could also eval lsp-mode.el manually before the melpa version is downloaded.

**Comment by gustavo-depaula** [comment]
@yyoncho pr opened: #891
