### ISSUE TITLE
Ability to set LSP server for a given project

### ISSUE THREAD

**Issue by jsmestad** [emacs-lsp/lsp-mode#896]
The README does not call this out anywhere and it's worth adding, assuming it is possible, for how to tell LSP which server I want for a given project.

For example, on a given project one Typescript/Javascript server works better than another and it would be nice to document how to tie into something like projectile to make this work.

**Comment by s-kostyaev** [comment]
You can do this with https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html

**Comment by yyoncho** [comment]
@jsmestad we have that in FAQ section, please take a look and comment whether this is sufficient.
