### ISSUE TITLE
PHP files treated as typescript

### ISSUE THREAD

**Issue by machekku** [emacs-lsp/lsp-mode#899]
**Describe the bug**
I use lsp-mode with PHP files using intelephense. After a recent lsp-mode update LSP features for PHP files stopped working. For example, lsp-describe-thing-at-point produces "No content at point" error. After investigating IO log I noticed that lsp-mode send textDocument/didOpen notification with languageId set to 'typescript':

[Trace - 11:41:21 AM] Sending notification 'textDocument/didOpen'.
Params: {
  "textDocument": {
    "uri": "file:///d/Projects/...Removed.../RepositoryService.php",
    "languageId": "typescript",
    "version": 0,
    "text": "<?php ...(removed)...",
  }
}

I checked recent changes to lsp-mode and it seems that the problem was introduced by this commit: https://github.com/emacs-lsp/lsp-mode/commit/b27990ab88240141e1f5e815626ac5f7233cddae

Commenting out  (".*.ts" . "typescript") makes things work again for me.

**To Reproduce**
Install latest lsp-mode. Install intelephense. Open a file with .php extension.

**Expected behavior**
LSP server should see content of a php file and provide its features.

**Which Language Server did you use**
lsp-intelephense

**OS**
Distributor ID: Ubuntu
Description:    Ubuntu 19.04
Release:        19.04
Codename:       disco
Running inside WSL on Microsoft Windows [Version 10.0.17763.557]

PS If there are any further questions, please note than I am emacs/spacemacs newbie.

**Comment by machekku** [comment]
I've been thinking about this strange behavior and I realized that my PHP code resides inside "Projects" dir, and "Projects" ends with "ts". If I move my code outside of this directory, than LSP works correctly. Could it be that the ".*.ts" rule for typescript actually matches all files inside Projects dir?
(Sorry, I'm not emacs-smart enough to answer this question myself)

**Comment by yyoncho** [comment]
@machekku the issue is that the regexp should be ".*\.ts$"

**Comment by machekku** [comment]
@yyoncho I can confirm that changing the regexp helps. (but I don't have typescript environment to test if it doesn't break that).
Thanks.
