### ISSUE TITLE
Controlling DidChangeTextDocument Notification

### ISSUE THREAD

**Issue by alanz** [emacs-lsp/lsp-mode#9]
The documentation for `TextDocumentSyncKind` offers `None`, `Full`, or `Incremental`.

In vscode this behaves such that omitting the parameter from the server capabilities returned to the client is effectively a fourth  option, where `DidSave` events are generated without sending document contents.

And `DidChangeTextDocument` notifications are not sent either.

Replicate this behaviour

**Comment by alanz** [comment]
See also https://github.com/Microsoft/language-server-protocol/issues/145

**Comment by vibhavp** [comment]
Hm, could it be that it's a vscode bug? If not, I'll try implementing this in emacs-lsp too once there's an answer from Microsoft on this.

**Comment by alanz** [comment]
Thanks.  I did some trial and error on it in my vscode integration as I did not want the change notifications but did want the save ones. And it seems like a good combination to be able to set, so hopefully it gets an official blessing.

**Comment by alanz** [comment]
It looks like version 3.0 of the spec will separate out the DidSave notifications. See https://github.com/Microsoft/language-server-protocol/compare/dbaeumer/3.0-spec

**Comment by alanz** [comment]
FYI Version 3 of the spec is out, where this is separated more cleanly. Now in master. https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md

**Comment by yyoncho** [comment]
This seems to be no longer relevant. Closing, please reopen if more work is required.
