### ISSUE TITLE
I'm new to Emacs, has anybody a tcp setup running for javascript-typescript-langserver.git ?

### ISSUE THREAD

**Issue by MarcWeber** [emacs-lsp/lsp-mode#90]
See https://github.com/sourcegraph/javascript-typescript-langserver.git

**Comment by vibhavp** [comment]
I've been busy with other work recently, but you could try implementing it yourself. The client API is pretty minimal, and is documented here: https://github.com/emacs-lsp/lsp-mode/blob/master/doc/API.org

**Comment by vibhavp** [comment]
`lsp--make-tcp-connection` is available, but isn't documented yet: https://github.com/emacs-lsp/lsp-mode/blob/3e93b3fd754931cfd122855659afbd070d844bac/lsp-mode.el#L46

**Comment by demyanrogozhin** [comment]
I end up with something like this:
`(lsp-define-tcp-client
     'js2-mode
     "javascript"
     'tcp
     'lsp-js--get-nodejs-root
     "cat"
     (list "cat")
     "localhost"
     2089)`

I use "cat" as command name to run, which works for me on linux, I don't know why some command required to run in my case - I got server started separately outside of emacs.
