### ISSUE TITLE
Duplicate language server

### ISSUE THREAD

**Issue by jimmywongroo** [emacs-lsp/lsp-mode#901]
**Describe the bug**

If 2 files of the same language under the same project are opened, one with ~ and another using the full path, 1 language servers will be started.

**To Reproduce**

1. Put two JS files in a git repo
2. Open one file with ~ path
3. Open the other with the full path
4. `M-x lsp-describe-session`

**Expected behavior**
The 2 files should share the same language server, given they are in the same project.

**Which Language Server did you use**
ts-ls

**OS**
macOS

**Comment by yyoncho** [comment]
I am unable to reproduce the issue with `emacs -Q`, how do you do that:

> Open one file with ~ path

Can you also try to reproduce the issue using `emacs  -q -l ~/lsp-mode/scripts/lsp-start-plain.el`?

**Comment by jimmywongroo** [comment]
I cannot reproduce this anymore. Seems to have been fixed. I'll reopen if I see this again.
