### ISSUE TITLE
importing packages hangs emacs in lsp-go

### ISSUE THREAD

**Issue by seagle0128** [emacs-lsp/lsp-mode#903]
When `import` some packages with `lsp-go` and `gopls`, the Emacs hangs.

- macOS, Linux
- Emacs 26.2/27.0.50
- the latest lsp-mode

**Comment by yyoncho** [comment]
Can you do toggle-debug-on-quit and press C-g when emacs hangs and paste the callstack?

**Comment by seagle0128** [comment]
```elisp
Debugger entered--Lisp error: (quit)
  process-send-string(#<process gopls> "Content-Length: 194\15\n\15\n{\"jsonrpc\":\"2.0\",\"method\":\"...")
  lsp--send-no-wait("Content-Length: 194\15\n\15\n{\"jsonrpc\":\"2.0\",\"method\":\"..." #<process gopls>)
  lsp--send-request-async((:jsonrpc "2.0" :method "textDocument/documentHighlight" :params (:textDocument (:uri "file:///Users/vincent/go/src/dpim/cli/ui/deploy.go") :position (:line 15 :character 12)) :id 370) #f(compiled-function (highlights) #<bytecode 0x1fe9cadcc065>) nil nil nil)
  lsp-request-async("textDocument/documentHighlight" (:textDocument (:uri "file:///Users/vincent/go/src/dpim/cli/ui/deploy.go") :position (:line 15 :character 12)) #f(compiled-function (highlights) #<bytecode 0x1fe9cadcc065>))
  lsp--document-highlight()
  #f(compiled-function () #<bytecode 0x1fe9cc41a531>)()
  apply(#f(compiled-function () #<bytecode 0x1fe9cc41a531>) nil)
  timer-event-handler([t 0 0 200000 nil #f(compiled-function () #<bytecode 0x1fe9cc41a531>) nil idle 0])
  process-send-string(#<process gopls> "Content-Length: 151\15\n\15\n{\"jsonrpc\":\"2.0\",\"method\":\"...")
  lsp--send-no-wait("Content-Length: 151\15\n\15\n{\"jsonrpc\":\"2.0\",\"method\":\"..." #<process gopls>)
  lsp--send-request-async((:jsonrpc "2.0" :method "textDocument/documentLink" :params (:textDocument (:uri "file:///Users/vincent/go/src/dpim/cli/ui/deploy.go")) :id 369) #f(compiled-function (links) #<bytecode 0x1fe9cba11ff1>) alive nil nil)
  lsp-request-async("textDocument/documentLink" (:textDocument (:uri "file:///Users/vincent/go/src/dpim/cli/ui/deploy.go")) #f(compiled-function (links) #<bytecode 0x1fe9cba11ff1>) :mode alive)
  lsp--update-document-links(#<buffer deploy.go>)
  apply(lsp--update-document-links #<buffer deploy.go>)
  timer-event-handler([t 0 0 100000 nil lsp--update-document-links (#<buffer deploy.go>) idle 0])
```

**Comment by yyoncho** [comment]
AFAIK process-send-string is async and it should not block. Can you confirm that you get this call stack each time you press C-g when emacs hangs in lsp-mode? Also, are you able to reproduce the issue if you disable lsp-enable-symbol-highlighting ? Can you check the process explorer for processes that are taking the system resources? Does the hanging disappear if you wait some time? If it disappears, can you provide a performance report? Were you able to isolate some steps to reproduce?

**Comment by seagle0128** [comment]
This time I got this backtrace:

```elisp
Debugger entered--Lisp error: (quit)
  company-dabbrev--search("\\(?:\\sw\\)+" 0.1 all)
  company-dabbrev(candidates "git")
  apply(company-dabbrev (candidates "git"))
  company-call-backend-raw(candidates "git")
  company--fetch-candidates("git")
  company-calculate-candidates("git" nil)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer deploy.go> #<window 3 on deploy.go> 908 304)
  apply(company-idle-begin (#<buffer deploy.go> #<window 3 on deploy.go> 908 304))
  timer-event-handler([t 23823 36130 975307 nil company-idle-begin (#<buffer deploy.go> #<window 3 on deploy.go> 908 304) nil 0])
```

I suspect the server is hung. Because after I press `C-g`, then continue inputing the Emacs hangs again, `C-g` got the backtrace I provided in last comment. But I didn't encounter hang issue with `gopls` in VSCode.

**Comment by yyoncho** [comment]
> I suspect the server is hung. Because after I press C-g

If the server is hung, this should not hang emacs since lsp-mode is doing async calls. To investigate further, can you exclude company-dabbrev from the company backends? We have to find out the root cause.

**Comment by seagle0128** [comment]
I use `(setq company-backends '(company-lsp))`, but the same issue.

I noticed the messages below while typing `import "com.github.com/xxx"

```elisp
LSP :: no import for ""
LSP :: no import for "c"
LSP :: no import for "co"
LSP :: no import for "com"
```

It seems very slow to search. Is it related?

**Comment by yyoncho** [comment]
Once you have removed company-dabbrev you should reproduce the issue and do C-g until we find out what is causing the issue. Also, can you post a performance report?

> It seems very slow to search. Is it related?

I am not familiar with gopls internals.

**Comment by muirrn** [comment]
Could be https://github.com/golang/go/issues/32750.

**Comment by seagle0128** [comment]
Thanks for the information, @muirrn .

It's definitely the same issue.

**Comment by muirrn** [comment]
The usptream issue has been closed. @seagle0128 can you confirm this is resolved with latest gopls?

**Comment by seagle0128** [comment]
Yep, I can confirm the issue has been resolved. Close it. Thanks!
