### ISSUE TITLE
Can't start LSP-mode in a JS-mode buffer (needs to be JS2-mode)

### ISSUE THREAD

**Issue by vidjuheffex** [emacs-lsp/lsp-mode#905]
**Describe the bug**
Can't start LSP-mode in a JS-mode buffer (needs to be JS2-mode)

**To Reproduce**
Make js2 mode not your your major mode for js files. Open js file.

**Expected behavior**
I expect LSP to open the js-mode file without it needing js2-mode.

**Which Language Server did you use**
typescript language server
**OS**
Mac Os X

**Comment by yyoncho** [comment]
I tried it with the latest lsp-mode using `emacs -q -l lsp-start-plain.el` and it works fine https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el . Please reopen if you are able to reproduce it using start plain script.

**Comment by vidjuheffex** [comment]
What is this supposed to do? When emacs starts I see it load packages, however when I open a `.js` file it doesn't start lsp mode. (also doesn't say anything in the *Messages* before, whereas before it used to say No LSP Server for js-mode)

**Comment by yyoncho** [comment]
@vidjuheffex you have to do `M-x lsp`

**Comment by vidjuheffex** [comment]
@yyoncho when I do that lsp-mode starts but says LSP[disconnected]

**Comment by yyoncho** [comment]
Are you sure that you did `M-x lsp` not `M-x lsp-mode`?

**Comment by vidjuheffex** [comment]
@yyoncho you are correct I did lsp-mode.

When I do `M-x lsp` I get `No LSP server for js-mode` again

**Comment by yyoncho** [comment]
What do you have in \*lsp-log\*?

**Comment by vidjuheffex** [comment]
```
Command "javascript-typescript-stdio" is not present on the path.
Command "typescript-language-server --stdio" is not present on the path.
Command "javascript-typescript-stdio" is not present on the path.
Command "typescript-language-server --stdio" is not present on the path.
```

**Comment by yyoncho** [comment]
... and do you have any of these on the path?

**Comment by vidjuheffex** [comment]
I thought I did? 

Thanks for the pointer, had never looked at LSP log before.

Not sure how it stopped working, I've been using LSP mode for several months.

All I did was try to follow j2-modes latest suggestions. 🤷‍♂ 

Anyway thank you!
