### ISSUE TITLE
Cannot jump to definition in certain cases in python

### ISSUE THREAD

**Issue by nthainguyen** [emacs-lsp/lsp-mode#906]
**Describe the bug**
Cannot jump to definition in certain cases while VScode can without problem

**To Reproduce**
- clone the following repo:

https://github.com/miguelgrinberg/microblog.git

- Open the file: models.py
- place the point at the line "from app import db"
- go to definition of "db" 

**Expected behavior**
- it jump to the instantiation of db in __init__ file like vscode does

**Which Language Server did you use**
microsoft python lsp

**OS**
both windows 10 and manjaro

**Error callstack**
Message in minibuffer: not found for: db

**Comment by yyoncho** [comment]
I am unable to reproduce with the latest server. Can you update the server and recompile it (I did `git clean -xfd` before that) and if it doesn't work do `(setq lsp-print-io t)` and post the client/server communication? 

![output-2019-06-26-14:46:20](https://user-images.githubusercontent.com/13259670/60177407-82f5cb80-9821-11e9-9dd2-2db9f52d24b2.gif)


```
[Trace - 02:49:05 PM] Sending request 'textDocument/definition - (45)'.
Params: {
  "textDocument": {
    "uri": "file:///home/kyoncho/temp/microblog/app/models.py"
  },
  "position": {
    "line": 12,
    "character": 17
  }
}


[Trace - 02:49:05 PM] Received response 'textDocument/definition - (45)' in 1ms.
Result: [
  {
    "range": {
      "end": {
        "character": 2,
        "line": 16
      },
      "start": {
        "character": 0,
        "line": 16
      }
    },
    "uri": "file:///home/kyoncho/temp/microblog/app/__init__.py"
  }
]

```

**Comment by nthainguyen** [comment]
it seems like the problem is at ms-lsp server. Thanks for the help.
