### ISSUE TITLE
On Type Formatting gets switched on its own

### ISSUE THREAD

**Issue by p0lyg0ne** [emacs-lsp/lsp-mode#909]
To disable on type formatting, I've customised and saved the variable lsp-enable-on-type-formatting to be nil.

When I start Emacs, initially it is switched off, but after a while it gets switched on on its own. 
After it got switched on I've checked the variable again, it was still set to nil. I pressed save and apply it got switched off again.

It is probably a function being called in the background which enables the formatting regardless of the variable. But so far I don't know exactly how to reproduce the error immediately.

**Comment by p0lyg0ne** [comment]
...forgot to mention, this is happening while editing c++ with clangd as server.

**Comment by yyoncho** [comment]
can you use `debug-on-variable-change` and report back who is changing the value?

**Comment by p0lyg0ne** [comment]
strangely it did not happen after I used debug-on-variable-change. I'll have a look at it tomorrow and try to find out how to reproduce the issue.

**Comment by yyoncho** [comment]
Ok, I will close that for now, please reopen it when you provide the requested info.
