### ISSUE TITLE
How to debug php using LSP mode?

### ISSUE THREAD

**Issue by cuhabaho** [emacs-lsp/lsp-mode#910]
I am using intelephense as the lsp backend server. I have install xdebug to my Lamp and configure it inside php.ini as following: 
```
sudo ./pecl install xdebug
# add below line to: /opt/lampp/etc/php/php.ini
zend_extension=/opt/lampp/lib/php/extensions/no-debug-non-zts-20160303/xdebug.so
xdebug.remote_enable=on
xdebug.remote_host=127.0.0.1
xdebug.remote_port=9000
xdebug.remote_handler=dbgp
xdebug.remote_autostart=on
xdebug.remote_connect_back=on
xdebug.remote_log="/tmp/xdebug.log"
xdebug.profiler_enable=1
``` 

I have checked inside phpinfo() page and saw below line which mean xdebug should work: 
```
xdebug support | enabled
-- | --
Version | 2.7.2
IDE Key | root
```

And then i open Laravel project and call M-x LSP and server start without any problem. After that, i call M-x dap-breakpoint-add to add a break point to my function. After that, I open browser and request my url that point to that function. I saw it run normal without debug at all. 

So, my question is, how can i use debug properly?

**Comment by yyoncho** [comment]
You have to do:

```
(require 'dap-php)
```

and then `M-x` `dap-debug` and select the php configuration.

**Comment by cuhabaho** [comment]
I got an error, debug session process exit with status; existed abnormally with code 1. Not sure what is going on.

![Screenshot_20190628_155905](https://user-images.githubusercontent.com/51189394/60330937-bbcaa780-99bd-11e9-8d59-816beccddbb0.png)

**Comment by cuhabaho** [comment]
Anyway, i think if possible, then under *Supported languages* and Debugger column, when click there is another page that tell us how to set up debugger. Like in my case, i could not find it anywhere.

**Comment by yyoncho** [comment]
> I got an error, debug session process exit with status; existed abnormally with code 1. Not sure what is going on.
> 
Check the stderr buffer for the session.



> Anyway, i think if possible, then under _Supported languages_ and Debugger column, when click there is another page that tell us how to set up debugger. Like in my case, i could not find it anywhere.

https://github.com/emacs-lsp/dap-mode#php
