### ISSUE TITLE
Lsp mode for php doesn't get along with aggressive mode

### ISSUE THREAD

**Issue by cuhabaho** [emacs-lsp/lsp-mode#911]
Lsp mode is working properly for a long while i have been using it. But, after not using emacs for a few weeks and come back, it stop working properly. When i want to type, "$data->property" without  quote, and i type "$data-" then i got "$data   - " and if i continue type ">" then, the whole line is disappear. More than this, sometime not only the current line, but another line also disappear without any warning. I have fact this kind of problem a while ago too in lsp for java mode and i decide to switch aggressive indent mode off in java mode. But now, it also happen in php mode too. Please check it if you get this too and if possible fix it. Thanks.

**Comment by s-kostyaev** [comment]
I think that `aggressive-indent-mode` breaks interaction with lsp server. I use this workaround:
```
(defun my-disable-aggressive-indent ()
  "Disable aggressive indent mode in current buffer."
  (interactive)
  (aggressive-indent-mode -1))

;; aggressive-indent-mode breaks interaction with lsp-server
(add-hook 'lsp-mode-hook #'my-disable-aggressive-indent)
```
For fixing it in more convenient way we should notify lsp server about buffer content changing. Also if content was changed after, for example, completion item request we should cancel this request, notify server about changes and then resend completion request. @yyoncho what do you think?

**Comment by yyoncho** [comment]
@s-kostyaev I am yet to investigate the issue. I would speculate that aggressive-indent-mode should not be needed for lsp at all since the language servers provide onTypeFormatting which is sort of aggressive indentation but in general we should work when it is enabled.

> Also if content was changed after, for example, completion item request we should cancel this request, notify server about changes and then resend completion request.

I think that we already do that in company-lsp.

**Comment by s-kostyaev** [comment]
> I think that we already do that in company-lsp.
Then it doesn't work. Then I try to complete code and aggressive indent mode changes content of current buffer I can see bugs in completion

**Comment by s-kostyaev** [comment]
Hover requests also returns error that client wants to see something after string or file ending.

**Comment by yyoncho** [comment]
> > I think that we already do that in company-lsp.
> 
> Then it doesn't work. Then I try to complete code and aggressive indent mode changes content of current buffer I can see bugs in completion

AFAICS aggresive-indent is cancelling the notification hooks in aggressive-indent--proccess-changed-list-and-indent which pretty much makes both packages incompatible since we pretty much depend on the on change hooks to sync the content with the server. This has to be investigated further.

**Comment by s-kostyaev** [comment]
Maybe request fast enough and we can't cancel it. Then we should ignore it result and resend it I think. Or add info about not working with aggressive indent mode into documentation.

**Comment by s-kostyaev** [comment]
@yyoncho maybe we can disable aggressive-indent-mode and show message about incompatibility to user? I think it can improve user experience out of the box. Another solution is add information about it to documentation. But personally I prefer first variant.

**Comment by yyoncho** [comment]
@s-kostyaev we have to do the proper investigation before committing to a solution.

1. Can we fix aggressive indent to work with lsp-mode?
2. Do we need to fix it at all?

**Comment by s-kostyaev** [comment]
I can try to do first at the weekend. Should I?

**Comment by yyoncho** [comment]
> I can try to do the first at the weekend. But before that I want to know your thoughts about the second @yyoncho

Sure, contributions are always welcome. This item is a bit unclear but feel free to give it a try.

**Comment by yyoncho** [comment]
@s-kostyaev I think that I found the root cause as part of investigating #907 so you might hold on your work on the issue.

**Comment by yyoncho** [comment]
Hi @Malabarba it looks like we could not fix that issue without changes in aggressive-indent-mode. The issue is that aggressive-indent-mode inhibits the change hooks which are used by lsp-mode to track the content of the buffer and sync it with the server. IMO one potential solution is to change the code in aggressive-indent-mode to alter before-change-hook/after-change-hook to unsubscribe itself(my understanding is that inhibit-change-hooks is needed to avoid reentrance) instead of suppressing change hooks using inhibit-change-hooks. WDYT?

**Comment by Malabarba** [comment]
Sorry for the delay. 
@yyoncho Odd that whitespace modifications would have such adverse effects on the server. :-|

In any case. Would you like to offer a PR with that change?

**Comment by yyoncho** [comment]
Pull request here - https://github.com/Malabarba/aggressive-indent-mode/pull/129 

@cuhabaho can you verify the fix?

**Comment by yyoncho** [comment]
Tested with emacs -q and latest version of the components - everything seems to be working fine.
