### ISSUE TITLE
lsp-face-highlight faces colide with expand-region.

### ISSUE THREAD

**Issue by dangom** [emacs-lsp/lsp-mode#915]
**Describe the bug**

By having `lsp-face-highlight-*` inherit from `highlight` makes it hard to refactor using expand-region because regions cannot be seen.

**To Reproduce**

Expand-region on a lsp-highlighted symbol and wonder what has been selected. That's because expand-region also uses the highlight face.

**Expected behavior**

Colors are different so one can see what's going on. I see this has already been discussed previously in #116 and "fixed" in #461, but perhaps it should be revisited.

**Which Language Server did you use**
lsp-python

**OS**
MacOS

**Comment by yyoncho** [comment]
AFAICS expand-region uses `region` face while the lsp-mode face use `highlight`. But that is irrelevant - IMO we shouldn't highlight symbol at all if there is a selected region.

**Comment by yyoncho** [comment]
> AFAICS expand-region uses region face while the lsp-mode face use highlight.

Verified with `emacs -q`. Probably the theme that you are using has the same color for both highlight and region face. I am closing the PR, please reopen if you disagree.
