### ISSUE TITLE
Pyls updated capabilities

### ISSUE THREAD

**Issue by mpanarin** [emacs-lsp/lsp-mode#916]
I made a PR to `pyls` to update its server capabilities. After its merged (and released), the workaround in `lsp-pyls` can be dropped. @yyoncho 

https://github.com/palantir/python-language-server/pull/613

**Comment by yyoncho** [comment]
Thank you. I would propose to keep the hack until a new pyls release containing the fix is performed.

**Comment by mpanarin** [comment]
@yyoncho new verison of pyls got released. You can drop its hacks :)

**Comment by mpanarin** [comment]
It also got support for multiple workspaces!

Does that mean that lsp won't start new instances of pyls all the time?

**Comment by yyoncho** [comment]
> Does that mean that lsp won't start new instances of pyls all the time

Yes, but we need to specify `:multi-root t`  in the registration.
