### ISSUE TITLE
Warning popping up with lsp metals

### ISSUE THREAD

**Issue by bomgar** [emacs-lsp/lsp-mode#922]
**Describe the bug**
Warning in a warning buffer: `Warning (lsp-mode): Unknown method: metals/treeViewDidChange`

Everything seems to work but the buffer opens to show me the message and interrupts me

**To Reproduce**
start lsp-metals

**Expected behavior**
No warning

**Which Language Server did you use**
metals 0.7.0

**OS**
linux

**Comment by jypma** [comment]
For tracking, I think https://github.com/scalameta/metals/pull/816 fixes this on the metals (server) side.
