### ISSUE TITLE
Rope completion in pyls should be False by default

### ISSUE THREAD

**Issue by mpanarin** [emacs-lsp/lsp-mode#923]
I am not sure on how the settings sync between rope and pyls, but according to pyls code, rope completion should be disabled by default (https://github.com/palantir/python-language-server/blob/develop/pyls/plugins/rope_completion.py#L14  it is also very slow and trashy), so `lsp-pyls-plugins-rope-completion-enabled` should be nil?

**Comment by yyoncho** [comment]
I have used this https://github.com/palantir/python-language-server/blob/develop/vscode-client/package.json#L244 for the defaults.

**Comment by mpanarin** [comment]
well, looks like someone forgot to update that thing :\

It was changed in this commit, and comment says that it should be disabled by defult 
https://github.com/palantir/python-language-server/commit/af4dcb325d70629435456ce253275edbb84877e1

**Comment by yyoncho** [comment]
ok - would you like to do make a PR?

**Comment by mpanarin** [comment]
Yep, sure
