### ISSUE TITLE
error in process filter: Wrong type argument: sequencep, #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data

### ISSUE THREAD

**Issue by DmitryMaletin** [emacs-lsp/lsp-mode#930]
**Describe the bug**
error in process filter: Wrong type argument: sequencep, #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("language" "PowerShell" "value" "function Get-Module"))

**To Reproduce**
Default setting. start to edit any powershell script 

**Expected behavior**

**Which Language Server did you use**
Mention which server/language did you use (e. g. lsp-powershell, etc)

**OS**
Windows; Powershell 6.2.1;  Latest version of lsp-mode, lsp-ui, lsp-company 

**Error callstack**
Debugger entered--Lisp error: (wrong-type-argument sequencep #<hash-table equal 2/65 0x3fe7029>)
  replace-regexp-in-string("\015" "" #<hash-table equal 2/65 0x3fe7029>)
  (progn (replace-regexp-in-string "\015" "" str))
  (if (and (eq system-type 'windows-nt) str) (progn (replace-regexp-in-string "\015" "" str)))
  lsp-pwsh--filter-cr(#<hash-table equal 2/65 0x3fe7029>)
  lsp-ui-sideline--extract-info([#<hash-table equal 2/65 0x3fe7029>])
  (lsp-ui-sideline--format-info (lsp-ui-sideline--extract-info (gethash "contents" info)))
  (concat (lsp-ui-sideline--format-info (lsp-ui-sideline--extract-info (gethash "contents" info))))
  (let* ((info (concat (lsp-ui-sideline--format-info (lsp-ui-sideline--extract-info (gethash "contents" info))))) (current (and (>= (point) (car bounds)) (<= (point) (cdr bounds))))) (if (and (> (length info) 0) (lsp-ui-sideline--check-duplicate symbol info)) (progn (let* ((final-string (lsp-ui-sideline--make-display-string info symbol current)) (pos-ov (lsp-ui-sideline--find-line (length final-string) bol eol)) (ov (if pos-ov (progn (make-overlay (car pos-ov) (car pos-ov)))))) (if pos-ov (progn (overlay-put ov 'info info) (overlay-put ov 'symbol symbol) (overlay-put ov 'bounds bounds) (overlay-put ov 'current current) (overlay-put ov 'after-string final-string) (overlay-put ov 'window (get-buffer-window)) (overlay-put ov 'kind 'info) (setq lsp-ui-sideline--ovs (cons ov lsp-ui-sideline--ovs))))))))
  (progn (let* ((info (concat (lsp-ui-sideline--format-info (lsp-ui-sideline--extract-info (gethash "contents" info))))) (current (and (>= (point) (car bounds)) (<= (point) (cdr bounds))))) (if (and (> (length info) 0) (lsp-ui-sideline--check-duplicate symbol info)) (progn (let* ((final-string (lsp-ui-sideline--make-display-string info symbol current)) (pos-ov (lsp-ui-sideline--find-line (length final-string) bol eol)) (ov (if pos-ov (progn (make-overlay (car pos-ov) (car pos-ov)))))) (if pos-ov (progn (overlay-put ov 'info info) (overlay-put ov 'symbol symbol) (overlay-put ov 'bounds bounds) (overlay-put ov 'current current) (overlay-put ov 'after-string final-string) (overlay-put ov 'window (get-buffer-window)) (overlay-put ov 'kind 'info) (setq lsp-ui-sideline--ovs (cons ov lsp-ui-sideline--ovs)))))))))
  (if (and (= tag (lsp-ui-sideline--calculate-tag)) (not (lsp-ui-sideline--stop-p))) (progn (let* ((info (concat (lsp-ui-sideline--format-info (lsp-ui-sideline--extract-info (gethash "contents" info))))) (current (and (>= (point) (car bounds)) (<= (point) (cdr bounds))))) (if (and (> (length info) 0) (lsp-ui-sideline--check-duplicate symbol info)) (progn (let* ((final-string (lsp-ui-sideline--make-display-string info symbol current)) (pos-ov (lsp-ui-sideline--find-line (length final-string) bol eol)) (ov (if pos-ov (progn (make-overlay (car pos-ov) (car pos-ov)))))) (if pos-ov (progn (overlay-put ov 'info info) (overlay-put ov 'symbol symbol) (overlay-put ov 'bounds bounds) (overlay-put ov 'current current) (overlay-put ov 'after-string final-string) (overlay-put ov 'window (get-buffer-window)) (overlay-put ov 'kind 'info) (setq lsp-ui-sideline--ovs (cons ov lsp-ui-sideline--ovs))))))))))
  lsp-ui-sideline--push-info("Import-Module" 1 (1 . 14) #<hash-table equal 2/65 0x3e71b41> 1 15)
  (progn (lsp-ui-sideline--push-info symbol tag bounds info bol eol))
  (if info (progn (lsp-ui-sideline--push-info symbol tag bounds info bol eol)))
  (closure ((index . 0) (position :line 0 :character 0) (bounds 1 . 14) (tag . 1) (symbol . "Import-Module") (--dash-source-192-- (:line 0 :character 0)) (input1 . 0) (input0 "Import-Module" 1 (1 . 14) (:line 0 :character 0)) (it "Import-Module" 1 (1 . 14) (:line 0 :character 0)) (it-index . 1) (list) (symbols ("Import-Module" 1 (1 . 14) (:line 0 :character 0))) (doc-id :uri "file:///d:/Projects/Repos/Powershell/test.ps1") (line-widen . 1) (tag . 1) (bol . 1) (eol . 15) t) (info) (if (eq index 0) (progn (let ((--dolist-tail-- lsp-ui-sideline--ovs)) (while --dolist-tail-- (let ((ov (car --dolist-tail--))) (if (eq (overlay-get ov 'kind) 'info) (progn (setq lsp-ui-sideline--occupied-lines (delq (overlay-get ov 'position) lsp-ui-sideline--occupied-lines)) (delete-overlay ov))) (setq --dolist-tail-- (cdr --dolist-tail--))))))) (if info (progn (lsp-ui-sideline--push-info symbol tag bounds info bol eol))))(#<hash-table equal 2/65 0x3e71b41>)
  #f(compiled-function () #<bytecode 0x383cb65>)()
  #f(compiled-function (result) #<bytecode 0x383cb7d>)(#<hash-table equal 2/65 0x3e71b41>)
  lsp--parser-on-message(#s(lsp--parser :headers nil :body nil :reading-body nil :body-length nil :body-received nil :leftovers "" :workspace #s(lsp--workspace :parser #1 :server-capabilities #<hash-table equal 19/65 0x3838c39> :registered-server-capabilities nil :root "d:/Projects/Repos/Powershell/" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect (closure ((command . lsp-pwsh--command) cl-struct-lsp--log-entry-tags cl-struct-lsp-session-tags cl-struct-lsp--workspace-tags cl-struct-lsp--registered-capability-tags cl-struct-lsp--folding-range-tags cl-struct-lsp-diagnostic-tags cl-struct-lsp-watch-tags cl-struct-lsp--client-tags cl-struct-lsp--parser-tags lsp--log-lines t) (filter sentinel name) (let ((final-command (lsp-resolve-final-function command)) (process-name (generate-new-buffer-name name))) (let ((proc (make-process :name process-name :connection-type 'pipe :buffer (format "*%s*" process-name) :coding 'no-conversion :command final-command :filter filter :sentinel sentinel :stderr (format "*%s::stderr*" process-name) :noquery t))) (set-process-query-on-exit-flag proc nil) (cons proc proc)))) :test\? (closure ((command . lsp-pwsh--command) cl-struct-lsp--log-entry-tags cl-struct-lsp-session-tags cl-struct-lsp--workspace-tags cl-struct-lsp--registered-capability-tags cl-struct-lsp--folding-range-tags cl-struct-lsp-diagnostic-tags cl-struct-lsp-watch-tags cl-struct-lsp--client-tags cl-struct-lsp--parser-tags lsp--log-lines t) nil (lsp-server-present\? (lsp-resolve-final-function command)))) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 1/65 0x1d99805> :request-handlers #<hash-table equal 0/65 0x1de2f35> :response-handlers #<hash-table eql 48/65 0x1de305d> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x1de307d> :action-handlers #<hash-table equal 0/65 0x1dde7e5> :major-modes (powershell-mode) :activation-fn nil :priority 1 :server-id pwsh-ls :multi-root nil :initialization-options lsp-pwsh--extra-init-params :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil) :host-root nil :proc #<process pwsh-ls> :cmd-proc #<process pwsh-ls> :buffers (#<buffer test.ps1>) :highlight-overlays #<hash-table eq 0/65 0x3448421> :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x366000d> :watches #<hash-table equal 0/65 0x366002d> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x3662835> :ewoc #s(ewoc :buffer #<buffer *lsp-log: pwsh-ls:16092*> :pretty-printer lsp--log-entry-pp :header [[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[

**Comment by yyoncho** [comment]
The error comes from https://github.com/kiennq/lsp-powershell , please report it in that repo.
(cc @kiennq)

**Comment by kiennq** [comment]
Fixed with kiennq/lsp-powershell@9c5f33ebe, thanks for letting me know.

**Comment by DmitryMaletin** [comment]
@kiennq Thank you. It's working now :)
