### ISSUE TITLE
support for closing idle backends and restarting them on-demand

### ISSUE THREAD

**Issue by imarko** [emacs-lsp/lsp-mode#931]
The memory use of some of the backends can be significant. Some that I use regularly (`ccls`, `gopls`, `mspyls`, `rls`) can each can grow to hundreds of MBs for large workspaces and it's easy to accumulate dozens of these over a few days. 

Currently I am dealing with this by manually killing backends every once in a while and using `(setq lsp-restart 'ignore)` to avoid the prompt storm that would result otherwise. This has the downside of having to manually re-start lsp when I enter a buffer with a killed backend.

It would be neat if lsp-mode had a configurable way to recycle idle backends and restart them on-demand when a buffer needs them again.

**Comment by yyoncho** [comment]
You could use lsp-workspace-shutdown to turn off a language server instead of described flow.

We have a method `lsp-deffered` which could be used as an entry point(e. g. instead of `lsp`). The difference between `lsp` and `lsp-deffered` is that `lsp-deffered` will start the server when you switch to that buffer(on demand). Can you try it and comment on whether it will cover your usecase?

**Comment by muirrn** [comment]
Yes, you can use `lsp-deferred` in combination with `lsp-workspace-restart`. Assuming you are using `lsp-deferred` instead of `lsp` as your entry point, after restarting the workspace the LSP server won't actually get started until you view a corresponding buffer, and even then it will only load that one file instead of all the files open in Emacs. You could then make it auto restart all workspaces once a day or whatever to keep the working set among all servers small.

**Comment by imarko** [comment]
Thanks, I didn't know about lsp-deferred, this is great!
The combination of lsp-deferred and `(setq lsp-restart 'auto-restart)` is pretty much what I was looking for and it seems to be working well so far. 

The only thing left is trying to be smarter about detecting idle backends rather killing them all wholesale. Any thoughts on that?

**Comment by yyoncho** [comment]
> The only thing left is trying to be smarter about detecting idle backends rather killing them all wholesale. Any thoughts on that?

I think it depends on what is the definition of idle server. Once we have the definition(e. g. 10 minutes without requests) for that we could expose the corresponding hooks if there are no such which will allow you to implement that logic externally.

**Comment by muirrn** [comment]
If you are okay with killing unused buffers, another option is to disable `lsp-keep-workspace-alive` and then use `midnight-mode` to automatically clean up old buffers periodically. When all the buffers corresponding to the LSP server are closed, the server will be shut down.

**Comment by imarko** [comment]
A hook on "no requests for `n` seconds" would work. Or just maintaining a timestamp of the last activity as a buffer var should be enough too, then I could have a single timer periodically scanning for backends with old timestamps. Not sure if this is worth adding though unless there are other use cases for it?

`lsp-keep-workspace-alive`/midnight is a great idea too. I'd need to customize the midnight filtering rules before I am ready to let it loose on my buffers but I've been meaning to look into that anyway.

I am already pretty happy with just `lsp-deferred` though, thanks for the help everybody!

**Comment by yyoncho** [comment]
> Not sure if this is worth adding though unless there are other use cases for it?

If we are going to do that we will add the hooks so it can be implemented outside of lsp-mode. IMO we miss only one hook - `lsp-on-request-hook` and this will be sufficient to implement the timer based solution on top of lsp-mode.

**Comment by yyoncho** [comment]
> I am already pretty happy with just `lsp-deferred` though, thanks for the help everybody!

If you are happy with what you currently have I would rather close the issue because we have a lot of work to do and we have to prioritize.

**Comment by imarko** [comment]
Ah yeah, adding an `lsp-on-request-hook` would be a good way to do it. Or I guess I could just advise `lsp-request`. In either case +1 to close this.

**Comment by yyoncho** [comment]
Yes, you are right - lsp-request and lsp-request-async are public so if one wants to implement this behaviour could do it right now or do a pr to add the hook.
