### ISSUE TITLE
How to config php lsp with intelephense, it always tell me lsp disconnect?

### ISSUE THREAD

**Issue by jirex** [emacs-lsp/lsp-mode#932]
I had run the script npm install intelephense -g and add a hook to php-mode , but it always tell me lsp disconnect, how to config it?
And if i want to edit vue file with html lsp and vue lsp at the same time , how to conifg

**Comment by yyoncho** [comment]
> I had run the script npm install intelephense -g and add a hook to php-mode , but it always tell me lsp disconnect, how to config it?

Check \*lsp-log\*. Probably the binary is not at the path that emacs is using.

> And if i want to edit vue file with html lsp and vue lsp at the same time , how to conifg

You should install the server and configure the required hooks. Do you have a concreate question?

**Comment by jirex** [comment]
\*lsp-log\*:

_Command "intelephense --stdio" is present on the path.
Command "php /Users/magikid/.composer/vendor/felixfbecker/language-server/bin/php-language-server.php" is present on the path.
Found the following clients for /Users/magikid/Web/magikidweb/backstage/api/index.php: (server-id iph, priority -1), (server-id php-ls, priority -2)
The following clients were selected based on priority: (server-id iph, priority -1)_

\*iph::stderr\*:

/usr/local/lib/node_modules/intelephense/lib/intelephense.js:40
 */!function(e){var t={};function n(r){if(t[r])return t[r].exports;var i=t[r]={i:r,l:!1,exports:{}};return e[r].call(i.exports,i,i.exports,n),i.l=!0,i.exports}n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var i in e)n.d(r,i,function(t){return e[t]}.bind(null,i));return r},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.p="",n(n.s=144)}([function(e,t){e.exports=require("path")},
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)

Process iph stderr finished

**Comment by yyoncho** [comment]
I found that - https://github.com/vapid/vapid/issues/45#issuecomment-425209170 . What version of node do you use?

**Comment by jirex** [comment]
maybe my node version is too old , 6.9.0, i'll try to update it and try again

**Comment by jirex** [comment]
lsp php with intelephense works now after i update node!  Thanks for your help! @yyoncho
