### ISSUE TITLE
fsautocomplete Won't Install

### ISSUE THREAD

**Issue by tmciver** [emacs-lsp/lsp-mode#935]
**Describe the bug**
With an F# file in the current buffer, start LSP with M-x `lsp`.  Get the message "Server is not installed. Do you want to install it?(yes or no)".  Answer "yes".  See the message "Contacting host: ci.appveyor.com:443" in the command buffer.  A short time later see the message "lsp-fsharp--fsac-install: Invalid format operation %%$".  `fsautocomplete does not get installed.

**To Reproduce**
See above description.

**Expected behavior**
Expected F# language server (`fsautocomplete`) to be installed.

**Which Language Server did you use**
`lsp-fsharp`

**OS**
Ubunutu 18.04

**Emacs Version**
25.3.2

**Error callstack**
If there is an error please reproduce the issue with `toggle-debug-on-error` and after setting `lsp-print-io` to t, and then include the callstack and attach the content of `*lsp-log*` buffer.

Callstack:
```
Debugger entered--Lisp error: (error "Invalid format operation %%$")
  format("bash -c 'mkdir -p %2$s && unzip -qq %1$s -d %2$s'" "/tmp/fsautocomplete521gcm.zip" "/home/tim/.emacs.d/fsautocomplete/")
  lsp-fsharp--fsac-install()
  lsp-fsharp--fsac-locate()
  lsp-fsharp--make-launch-cmd()
  lsp-resolve-final-function(lsp-fsharp--make-launch-cmd)
  #[0 "\301\302\300!!\207" [lsp-fsharp--make-launch-cmd lsp-server-present\? lsp-resolve-final-function] 3]()
  #[257 "\211\211\205
```

``` emacs-lisp
(setq lsp-print-io t)
```

**Comment by yyoncho** [comment]
Apparently, the format does not work on older emacs versions:

```
(format "bash -c 'mkdir -p %2$s && unzip -qq %1$s -d %2$s'" "/tmp/fsautocomplete521gcm.zip" "/home/tim/.emacs.d/fsautocomplete/")
```

@TOTBWF would you like to take a look?

**Comment by TOTBWF** [comment]
Yeah, I'll take a look at this over the weekend

**Comment by TOTBWF** [comment]
Sorry for taking so long to get back to you all on this, try
```
(defun lsp-fsharp--fsac-install ()
  "Downloads the latest version of fsautocomplete, and set `lsp-fsharp-server-path'."
  (let* ((temp-file (make-temp-file "fsautocomplete" nil ".zip"))
         (install-dir-full (expand-file-name lsp-fsharp-server-install-dir))
         (unzip-script (cond ((executable-find "unzip") (format "bash -c 'mkdir -p %s && unzip -qq %s -d %s'") install-dir-full temp-file install-dir-full)
                             ((executable-find "powershell") (format "powershell -noprofile -noninteractive -nologo -ex bypass Expand-Archive -path '%s' -dest '%s'" temp-file install-dir-full))
                             (t (user-error (format "Unable to unzip server - file %s cannot be extracted, please extract it manually") temp-file)))))
    (url-copy-file lsp-fsharp-server-download-url temp-file t)
    (shell-command unzip-script)
    (shell-command (format "%s %s --version" (lsp-fsharp--fsac-runtime-cmd) (lsp-fsharp--fsac-cmd)))))
```

**Comment by yyoncho** [comment]
Should be fixed by https://github.com/emacs-lsp/lsp-mode/pull/946/ .
