### ISSUE TITLE
False positive watched file "creates"

### ISSUE THREAD

**Issue by muirrn** [emacs-lsp/lsp-mode#937]
**Describe the bug**
lsp-mode is sending "create" `didChangeWatchedFiles` notifications (in addition to "change") every time a file is edited.

**To Reproduce**
Start an LSP server that registers "didChangeWatchedFiles" capability. Enable trace logging and edit a file under the root directory. Notice Emacs sends both a "change" and "create" event.

**Expected behavior**
Only  "change" notification is sent.

**Which Language Server did you use**
gopls (note that gopls doesn't support watching files yet - I'm working on that feature right now)

**OS**
Mac

```
[Trace - 07:58:48 PM] Sending notification 'workspace/didChangeWatchedFiles'.
Params: {
  "changes": [
    {
      "type": 1,
      "uri": "file:///Users/muir/scratch/foo/bar.go"
    }
  ]
}


[Trace - 07:58:48 PM] Sending notification 'workspace/didChangeWatchedFiles'.
Params: {
  "changes": [
    {
      "type": 2,
      "uri": "file:///Users/muir/scratch/foo/bar.go"
    }
  ]
}
```

**Comment by muirrn** [comment]
@yyoncho did you see this issue as well? Are you able to reproduce it?

**Comment by yyoncho** [comment]
I think that I was able to reproduce it but I haven't had the time to investigate yet. There are few issues related to watches that I will try to address in one PR, this one, the issue about the missing filtering. We should also process the events in between creating the watches to avoid the blocking of UI. Also, we should show a warning when the workspace is too big and watching files will cause performance issues(like vscode). My action plan is 

1. https://github.com/emacs-lsp/lsp-treemacs/issues/3 
2. Integrate code lenses with avy
3. #921 
4. Release 6.1

and after that, I will probably be able to take a look at file watches related issues. ATM the load has increased and it hard to keep up with the bug list.

**Comment by muirrn** [comment]
Ok. Maybe I will poke at this one later to see if it is something is easy to fix.

**Comment by muirrn** [comment]
Seems like this is a shortcoming in filenotify.el and unrelated to lsp-mode. When saving files in Vim, we get a "create" and then a "change" every time. src/kqueue.c detects the file's inode changed (due to how Vim writes files), and treats that as a "create -> write". Other watchers (e.g. VSCode, fswatch) handle this better and only give a single event. I can't say this behavior is "wrong", but it isn't very useful in practice.
