### ISSUE TITLE
didChangeWatchedFiles "kind" registration option not respected

### ISSUE THREAD

**Issue by muirdm** [emacs-lsp/lsp-mode#938]
**Describe the bug**
I registered for only "change" events, but my server gets sent "create" and "delete" events as well. 

**To Reproduce**
When registering for watched file events, set `DidChangeWatchedFilesRegistrationOptions.Kind` to "2" (which is `Change` only). Notice Emacs still sends "create" and "delete" notifications.

**Expected behavior**
Emacs only sends "change" notifications.

**Which Language Server did you use**
gopls (doesn't support watching files yet)

**OS**
Mac

**Comment by yyoncho** [comment]
Can you provide details on whether this is a blocker for you(e. g. does it cause some misbehaviour of the language server, anything besides the redundant messages). I want to determine the priority of the issue.

**Comment by muirrn** [comment]
Not a big deal since I can just ignore messages I don't want to handle yet.
