### ISSUE TITLE
Consider support for Mac "FSEvents" file watching

### ISSUE THREAD

**Issue by muirrn** [emacs-lsp/lsp-mode#939]
On Mac, the FSEvents library lets you efficiently do recursive file watches. This would improve performance, memory usage, and file handle exhaustion issues on Mac. Emacs filenotify.el doesn't support FSEvents, but lsp-mode (or a separate module) could support running `fswatch` directly if the user has it installed, or we could write an Emacs module with a native extension to interface directly with FSEvents. What do you think?

**Comment by yyoncho** [comment]
Sounds good to me as long as there is someone to implement/support the feature.

**Comment by muirrn** [comment]
I'm going to try to implement this as a filenotify.el backend.

**Comment by nickenchev** [comment]
Curious if this was implemented?

**Comment by muirdm** [comment]
Nope, but I wasn't imagining it to be too difficult. Knock yourself out if you are interested.
