### ISSUE TITLE
xref-find-references return no result (cause of position in params)

### ISSUE THREAD

**Issue by TxGVNN** [emacs-lsp/lsp-mode#940]
Hi lsp-mode team,
The first, thanks for your amazing work.

**OS**
Debian/Ubuntu
GNU Emacs 26.2 (build from source code)

**Describe the bug**

I don't know this is bug, small issue or my mistake. But I have >2 Emacs instance have the same issue.
I'm using lsp-mode for python-mode. And I realized `xref-find-references` is working incorrect. It did not return any results. But lsp-find-references did

**Reproduce**
Open python project, example python-language-server/pyls/python_ls.py project.
I try to debug by run `edebug-defun` on `lsp-request`. So I have a result as bellow:
1. `M-x xref-find-references`
```
params: (:textDocument (:uri "file:///home/giaptx/projects/python-language-server/pyls/python_ls.py") 
         :position #<hash-table equal 2/65 0x1ed5a7d> :context (:includeDeclaration :json-false))
```

2. `M-x lsp-find-references`
```
params: (:textDocument (:uri "file:///home/giaptx/projects/python-language-server/pyls/python_ls.py") 
         :position (:line 23 :character 6) :context (:includeDeclaration :json-false))
```

**Solution**

The difference here is `:postion`, then I modified a bit in `xref-backend-references` in order to call `lsp--make-reference-params`
```patch
-                            (or params (lsp--make-reference-params)))))
+                            (or nil (lsp--make-reference-params)))))    
```
Call `M-x xref-find-references` again, then it works well.

```
params: (:textDocument (:uri "file:///home/giaptx/projects/python-language-server/pyls/python_ls.py") 
         :position (:line 23 :character 6) :context (:includeDeclaration :json-false))
```

**Comment by yyoncho** [comment]
Can you inspect what is the content of the hashtable passed in 1. ? I have never seen that code to work. Can you share your setup? In general, our xref integration is not working 100% due to lsp protocol not able to fulfil xref expectations, this is one of the reasons we introduced `lsp-find-*`.

**Comment by TxGVNN** [comment]
> Can you inspect what is the content of the hashtable passed in 1

Yes sure, but could you guide me the best way to inspect? I'm not too master the elisp

> Can you share your setup?

My setup is simple
```
(package-install 'lsp-mode)
(package-install 'company-lsp)
(add-hook 'python-mode-hook 'lsp) ;; I use python-mode built-in
```
The full version you can check out here https://github.com/TxGVNN/dots/blob/master/.emacs#L635

> In general, our xref integration is not working 100% due to lsp protocol 

I think we should improve it.

**Comment by yyoncho** [comment]
> Yes sure, but could you guide me the best way to inspect? I'm not too master the elisp

No need to do so. I found out why it works on your machine - you are using `ivy`.

**Comment by TxGVNN** [comment]
Yeah, you're right. I'm using ivy. But I've just tested with `emacs -nw -Q` just only load `lsp-mode` (include dependencies). It works the same

**Comment by yyoncho** [comment]
@dangerousben this issue is related to the discussion in https://github.com/emacs-lsp/lsp-mode/pull/954 - are you still planning to give it a shot?

**Comment by TxGVNN** [comment]
Hi,
Today, I re-test this issue on ‘lsp-mode-20190907.553’
And I see the ` :position #<hash-table equal 2/65 0x1ed5a7d> ` is no longer, you fixed it.
But I found another bug, `::position` is not correct

1. M-x xref-find-references
```
(:textDocument (:uri "file:///home/txgvnn/projects/python-language-server/pyls/python_ls.py") :position (:line 1 :character 1) :contex\
t (:includeDeclaration :json-false))
```
:line and :character are wrong

2. M-x lsp-find-references
```
(:textDocument (:uri "file:///home/txgvnn/projects/python-language-server/pyls/python_ls.py") :position (:line 23 :character 7) :context (:includeDeclaration :json-false))
```
![scrot_2019-09-08-00:56:48_1366x768](https://user-images.githubusercontent.com/9713793/64478609-9c79a300-d1d4-11e9-97d6-c7c68e27dc61.png)

Project: https://github.com/palantir/python-language-server/blob/develop/pyls/python_ls.py#L25
Find references of `_StreamHandlerWrapper`

**Comment by yyoncho** [comment]
@TxGVNN tested with `emacs -q` and loading only lsp-mode and it works as expected - it asks for the identifier and when you  _StreamHandlerWrapper and press enter it shows the correct references.

**Comment by TxGVNN** [comment]
Thank you, @yyoncho

emacs -q work well, seems the bug from my configuration.

**Comment by TxGVNN** [comment]
I discovered the problem is ivy package. Do you know what is wrong in ivy?

**Comment by yyoncho** [comment]
@TxGVNN I don't know - open an issue with steps to reproduce and configuration and we will take a look.
