### ISSUE TITLE
Garbled Argument Output with CAPF (without Company)

### ISSUE THREAD

**Issue by jjzmajic** [emacs-lsp/lsp-mode#941]
**Describe the bug**
When not using company-lsp, the argument output includes characters from the language server (tested on go and python language servers) that should be stripped or parsed further. E.g.:
```python
pd.DataFrame.abs(${1:self})$0
```

**To Reproduce**
- Disable `company-mode`
- set `lsp-enable-completion-at-point` to `t`
- Complete a function with TAB. Usually a method. E.g: `pd.DataFrame.<TAB>`

**Expected behavior**
Compete method name without garbled output. Possibly use the output to suggest arguments (not really something I'm personally interested in.

**Which Language Server did you use**
lsp-python, gopls

**OS**
Linux (Pop!_OS, Arch Linux)
Emacs 26.2, 27.05

**Error callstack**
N/A

**Comment by yyoncho** [comment]
CAPF does not support snippets - see https://github.com/emacs-lsp/lsp-mode/issues/350 

> Compete method name without garbled output. Possibly use the output to suggest arguments (not really something I'm personally interested in.

To achieve this set lsp-enable-snippet to nil.

**Comment by jjzmajic** [comment]
Rtfm man, rtfm... Thanks for being patient with me @yyoncho
