### ISSUE TITLE
lsp-vue mode 代码提示如何忽略掉自定义的一些文件

### ISSUE THREAD

**Issue by zhyuanyuan** [emacs-lsp/lsp-mode#945]
Please ask your questions at https://gitter.im/emacs-lsp/lsp-mode
hi，你好。
     最近在使用lsp -mode 和 lsp-vue做vue开发，可是我们的项目非常大，其中有个文件夹中有几千个文件，每输入一个单词的时候node服务在疯狂运算，cpu运行 100%。所以我想把这个文件过滤掉，请问如何操作？

**Comment by yyoncho** [comment]
Can you provide mode details(I do not speak Chinese) -  What is taking a lot of CPU - emacs or the language server? If it is emacs please provide performance report(use profiler-start/profiler-stop and C-u tab to expand a node).

**Comment by contrun** [comment]
His/her question is how to ignore some files in the project, as those files eat cpu. If I understand him/her correctly, he/she wants the language server to ignore those files. Is that possible?

**Comment by nykma** [comment]
`vetur` will  ignore things in `.gitignore` and all `node_modules/` . This is implemented in [this function](https://github.com/vuejs/vetur/blob/master/server/src/services/typescriptService/serviceHost.ts#L386).
你用的 Vue language server 在 [这个函数里](https://github.com/vuejs/vetur/blob/master/server/src/services/typescriptService/serviceHost.ts#L386) 只忽略了 `.gitignore` 和所有的 `node_modules/` 。

**Comment by yyoncho** [comment]
Closing based on @nykma's comment.

**Comment by muirrn** [comment]
If you want to prevent a giant file from loading lsp-mode, you could customize your hook that calls `lsp` to not call it for certain files.

没试过，但如下应该可以了。按照文件名不启动`lsp`.
```elisp
(defun my/lsp-unless ()
  (unless (string-match "/my-giant-file.js$" (buffer-file-name))
    (lsp)))

;; 代替原来的lsp启动hook
(add-to-list 'vue-mode-hook #'my/lsp-unless)
```

**Comment by zhyuanyuan** [comment]
> `vetur` will ignore things in `.gitignore` and all `node_modules/` . This is implemented in [this function](https://github.com/vuejs/vetur/blob/master/server/src/services/typescriptService/serviceHost.ts#L386).
> 你用的 Vue language server 在 [这个函数里](https://github.com/vuejs/vetur/blob/master/server/src/services/typescriptService/serviceHost.ts#L386) 只忽略了 `.gitignore` 和所有的 `node_modules/` 。

Can you give me a demo?the function is too Tedious.
