### ISSUE TITLE
didSave notifications should not be sent unless server requested them

### ISSUE THREAD

**Issue by ljw1004** [emacs-lsp/lsp-mode#95]
In response to the `initialize` method, the server sends back its capabilities:

```
export interface TextDocumentSyncOptions {
  // Will save notifications are sent to the server.
  willSave?: boolean;
  // Will save wait until requests are sent to the server.
  willSaveWaitUntil?: boolean;
  // Save notifications are sent to the server.
  save?: SaveOptions;
}
```

I observed that even when the server omits the `save` field from this, lsp-mode still sends `textDocument/didSave` notifications. It shouldn't!

Here's the relevant code from lsp-methods which sends didSave notifications without first checking the server capabilities:
https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-methods.el#L784

**Comment by ljw1004** [comment]
Sorry, my mistake. `didSave` existed in v2 of the protocol, and hence all servers are required to support it.

https://github.com/Microsoft/language-server-protocol/issues/193

**Comment by vibhavp** [comment]
Not sending it when a v3 implementing server requests `lsp-mode` not to would still be a desired feature, though. There is some _basic_ support for the v3 version of the protocol, so this can be implemented.

**Comment by alanz** [comment]
Ditto for `textDocument/willSave`

**Comment by yyoncho** [comment]
Fixes by @itome with https://github.com/emacs-lsp/lsp-mode/pull/853
