### ISSUE TITLE
[Question] How exactly does lsp-mode know which server to use?

### ISSUE THREAD

**Issue by ianpan870102** [emacs-lsp/lsp-mode#950]
I'm curious how lsp-mode knows which server to use, particularly in web-mode. I currently use web-mode for js/jsx/ts/tsx and I've hooked lsp to web-mode as well. Does lsp-mode look at the current major mode or the file extension (or possibly both?)

**Comment by yyoncho** [comment]
When you are registering a server you could pass :major-modes or :activation-fn . They are used to determine whether that particular server can handle the current buffer(:actication-fn has priority). 

1. Find which servers could handle the mode(using the aforementioned properties).
2. Check whether the server is present(we are using executable-find by default).
3. If more than one server matches - use the server with higher :priority.
