### ISSUE TITLE
How to start lsp manually instead automatically?

### ISSUE THREAD

**Issue by c02y** [emacs-lsp/lsp-mode#952]
In README file, it says:
~~~
(add-hook 'XXX-mode-hook #'lsp-deferred)
~~~
this only starts lsp when you open a file in emacs, but what if I want lsp to be started only when I manually start it, since it happens a lot when I only want to view a file, no modification, no navigation, nothing else, just like `less`.

Currently lsp is started automatically, I'm using old hardware, it takes a lot of resource and time every time when I open a file.

**Comment by yyoncho** [comment]
Do not add any hook (e. g. `(add-hook 'XXX-mode-hook #'lsp)`) but do `M-x lsp`.
