### ISSUE TITLE
Too many files under a go package cause slow editing

### ISSUE THREAD

**Issue by icexin** [emacs-lsp/lsp-mode#956]
**Describe the bug**
I use gopls as the language server. If there are too many files under a go package, when I edit one of the files, every time I add a character, I will receive the diagnostics of all the files under the package, causing the emacs to be very stuck and almost impossible to edit.

**To Reproduce**
Create a 50+ go file in one directory and edit one of the files

**Expected behavior**
Not running slowly when editing.

**Which Language Server did you use**
gopls

**OS**
Mac OS High Sierra

**Comment by yyoncho** [comment]
There is not much we could on lsp-mode side except speeding up json parsing:

1. Make sure gc-cons-threshold is big enough.
2. Switch to emacs 27(build from latest master branch) with native json support.

**Comment by icexin** [comment]
This is the result of profiling, JSON parsing has a small proportion.
May it helps.

```
- #<compiled 0x1be2475>                                         12873  46%
 - lsp--parser-on-message                                       12289  44%
  - lsp--on-notification                                        11093  39%
   - lsp--on-diagnostics                                        11073  39%
    - find-buffer-visiting                                       4338  15%
     + file-truename                                             2024   7%
     + abbreviate-file-name                                       488   1%
       buffer-list                                                  2   0%
    + lsp--uri-to-path                                           2503   8%
    + seq-empty-p                                                  11   0%
    + seq-map                                                       1   0%
   + lsp--window-log-message                                        6   0%
  + lsp--read-json                                               1088   3%
  + #<compiled 0x1fe5475>                                          73   0%
 + lsp--parser-read                                               502   1%
+ company-post-command                                           3647  13%
+ timer-event-handler                                            2756   9%
+ command-execute                                                2552   9%
+ redisplay_internal (C function)                                2311   8%
+ evil-escape-pre-command-hook                                   1500   5%
+ ...                                                            1430   5%
+ flycheck-handle-signal                                          628   2%
+ evil--jump-hook                                                  26   0%
+ evil-repeat-post-hook                                            18   0%
```

**Comment by yyoncho** [comment]
Thank you! Thanks for clarifying - can you test with reverting 019e99672249535e440cbd00bb10fd228d1afa9c ?

**Comment by icexin** [comment]
After using `get-file-buffer`, the speed has improved significantly, thank you.
By the way, when I complete the variable name, the editing speed is slowing down. But with gopls, VSCode doesn't have this problem. Is it because VSCode uses different threads to handle different tasks?

**Comment by yyoncho** [comment]
> By the way, when I complete the variable name, the editing speed is slowing down.

Can you provide a bit more details? (and eventually a profiler report).

**Comment by icexin** [comment]
Finally found it's the same reason as the previous question. Thanks.

**Comment by yyoncho** [comment]
Fixed with https://github.com/emacs-lsp/lsp-mode/pull/976
