### ISSUE TITLE
python File mode specification error: (void-function lsp-make-traverser)

### ISSUE THREAD

**Issue by TPLinux** [emacs-lsp/lsp-mode#957]
**Describe the bug**

**To Reproduce**
I tried all steps and solutions , no hope 

created venv and install requirments and still not working 

I also tried to apply virtualenv-workon command to make it work but still not working and giving me the same error 

i feel disappointment

**Language Server**
lsp-python

**OS**
MacOS Mojave

**Error callstack**

when i open python file o got this error

`File mode specification error: (void-function lsp-make-traverser)`

**Comment by yyoncho** [comment]
This function and the code that reference that function was deleted 9 months ago. Please delete the content of ~/.emacs.d/elpa and redownload the latest versions of the packages.

**Comment by yyoncho** [comment]
Also, make sure that the issue reproduces when you are using `emacs -q -l lsp-start-plain.el` (the file could be downloaded from https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el ).

**Comment by TPLinux** [comment]
> This function and the code that reference that function was deleted 9 months ago. Please delete the content of ~/.emacs.d/elpa and redownload the latest versions of the packages.

I just downloaded the packages yesterday !, you should not close this issue without solving it ...!

**Comment by TPLinux** [comment]
> Also, make sure that the issue reproduces when you are using `emacs -q -l lsp-start-plain.el` (the file could be downloaded from https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el ).

This worked for me , but i want it to work with normal startup emacs , i will try to download the packages from melpa stable

**Comment by TPLinux** [comment]
i think it's solved but i still getting this error even i had it in my PATH

`Command "pyls" is not present on the path.`

**Comment by TPLinux** [comment]
SOLVED!, TY <3,  Appreciate  @yyoncho 

` '(lsp-pyls-server-command (quote ("/usr/local/bin/pyls")))`
