### ISSUE TITLE
Python ElDoc documentation can be extremely long

### ISSUE THREAD

**Issue by joewreschnig** [emacs-lsp/lsp-mode#96]
When using `lsp-mode` with [lsp-python](https://github.com/emacs-lsp/lsp-python) and [python-language-server](https://github.com/palantir/python-language-server), the ElDoc buffer shows the function signature and complete docstring (which often repeats the function signature). This is often many lines, and also a variable number of lines, so my minibuffer bounces all over while scrolling through a file.

This should be controlled by the customizable variable `eldoc-echo-area-use-multiline-p`; if this variable is `nil`, the eldoc function is supposed to truncate to a single line.

I'm not sure whether getting this right lies with `lsp-mode`, `lsp-python`, or the language server itself. I'm starting here because I think `lsp-mode` should try to enforce Emacs-isms even if the underlying language server wants to do something else by default.

**Comment by casouri** [comment]
If your problem is mini buffer when scrolling. Maybe you can set the delay of eldoc longer?

**Comment by joewreschnig** [comment]
Closing in favor of #235.
