### ISSUE TITLE
Carbon with intelephense makes Emacs hang

### ISSUE THREAD

**Issue by sollidsnake** [emacs-lsp/lsp-mode#961]
**Describe the bug**
When using the PHP backend intelephense and trying to import the Carbon library, Emacs hangs and stops responding for a while. `Ctrl-g` doesn't seem to help. This only happens if you have `lsp-ui-mode` enabled.

**To Reproduce**
1. Create a new project with a clean composer.json
2. Install Carbon:
`composer require nesbot/carbon`
3. Create a new file, include `vendor/autoload.php` and start `lsp` server with intelephense
4. Make sure you also have `lsp-ui-mode` enabled
5. After the autoload include, type `use Carbon\Carbon` and then Emacs freezes for a few seconds while your cursor is over the Carbon keyword.

**Expected behavior**
Emacs not freezing and fetching Carbon properties correctly.

**Which Language Server did you use**
`lsp-intelephense`

**OS**
Arch Linux

**Error callstack**
I uploaded the contents of `lsp-log` buffer to pastebin, because it's pretty big. It seems to be falling into some recursive endless loop.
https://pastebin.com/cB7awv61

Please let me know if there's some other information that I should add.

**Comment by yyoncho** [comment]
Can you do `M-x toggle-debug-on-quit` which will show the callstack when you press C-g?

**Comment by sollidsnake** [comment]
I only get this:
```
Debugger entered--Lisp error: (quit)
  redisplay_internal\ \(C\ function\)()
```

**Comment by yyoncho** [comment]
Ok, thank you, it does not ring any bell. I will try to reproduce it on my side tomorrow my time. If I fail to reproduce it on my side I will probably need a performance report.

**Comment by yyoncho** [comment]
I tried the steps you provided me but the issue didn't reproduce, probably I have missed something, can you provide a sample project? (I have zero php experience).

**Comment by sollidsnake** [comment]
Sure, [here's the repository](https://github.com/sollidsnake/sample-php-project/). Or, if you prefer, I'll try to guide you through in more details:

1. Create a new directory and cd into it
2. Create a file `composer.json` with the following content:
```
{
    "name": "test/test",
    "require": {
        "nesbot/carbon": "^2.22"
    }
}
```
3. Run `composer install` to install the dependencies. If you're not familiarized with composer, it's a PHP package manager, simular to npm and node. You might have it on your system's package manager repository, otherwise you can install it following the instructions on [composer's website](https://getcomposer.org/download/).
4. Create a file `index.php` with the following content:
```
<?php

include './vendor/autoload.php';
use Carbon\Carbon;

echo Carbon::now();
```
5. Enable `lsp` and `lsp-ui` and put your cursor on the line `use Carbon\Carbon`, more precisely on over the second `n`. Then Emacs should freeze while fetching Carbon documentation


If you use the repository, don't forget to run the steps `3` and `5`. I was able to reproduce it with `emacs -q`, so I don't think it's related to my setup.

**Comment by sollidsnake** [comment]
Also, to make sure you have `lsp` and `intelephense` working as expected, you can type `Carbon::[cursor here]` and try to fetch the completion candidates.

**Comment by yyoncho** [comment]
Thank you - I think that I reproduced it but on my setup(spacemacs), it does not hang but it is kind of slow. It is very slow with `emacs -q` but once you do `(setq gc-cons-threshold 100000000)` it gets much better, can you test on your side?

**Comment by sollidsnake** [comment]
Yes, it still lags but it's much faster after setting that variable

**Comment by yyoncho** [comment]
Can you apply this locally and comment on whether this solves the issue?

``` elisp

(defun lsp--buffer-string-visible ()
  "Return visible buffer string.
Stolen from `org-copy-visible'."
  (let ((temp (generate-new-buffer " *temp*"))
        (beg (point-min))
        (end (point-max)))
    (while (/= beg end)
      (when (get-char-property beg 'invisible)
        (setq beg (next-single-char-property-change beg 'invisible nil end)))
      (let* ((next (next-single-char-property-change beg 'invisible nil end))
             (substring (buffer-substring beg next)))
        (with-current-buffer temp (insert substring))
        ;; (setq result (concat result substring))
        (setq beg next)))
    (setq deactivate-mark t)
    (prog1 (with-current-buffer temp
             (s-chop-suffix "\n" (buffer-string)))
      (kill-buffer temp))))
```

**Comment by sollidsnake** [comment]
That makes it a lot better. It still has some very short lag, but it's usable now. Thanks a lot for the quick fix!
