### ISSUE TITLE
How to use/register @angular/language-service for angular project.

### ISSUE THREAD

**Issue by JSiebelink** [emacs-lsp/lsp-mode#966]
**Describe the bug**
For Angular projects, it should be possible to use the official @angular/language-service for error diagnostics, go to definition functionality, auto completion and such, when opening html templates related to typescript components/files. For the official language service, see: https://angular.io/guide/language-service and for the vscode implementation of the service: https://github.com/angular/vscode-ng-language-service

**To Reproduce**
- Clone: https://gitlab.com/Jorrieporrie/lsp-mode-angular-service
- Run npm install in root folder
- Open app.component.ts to see the component's controller with a variable called 'typoVar' and a method called 'aMethodTheTemplateShouldFind'
- Open app.component.html to see the variable and the method correctly and incorrectly referenced in the top h1 tag.

**Expected behavior**
There should be diagnostics stating that 'tyypoVar' and 'aMethooodTheTemplateShouldFind()' are not defined.

**OS**
MacOS

**Comment by yyoncho** [comment]
I think that at this point `vscode-ng-language-service` supports only node ipc connections(cc @kyliau to confirm). So the first step to make this support work is to add stdio support.

**Comment by kyliau** [comment]
the LSP server for Angular language service uses the standard vscode-languageserver package.
If you start the server with `--stdio` flag, it'd read from stdin and stdout.
See https://github.com/angular/vscode-ng-language-service/blob/2558440c8fb9a14ee7aa927777aa3be5332829b7/server/src/server.ts#L17 and https://github.com/microsoft/vscode-languageserver-node/blob/e9f3e3cdfb0fb761654bed9154e248acade7417c/server/src/main.ts#L1691
Please let me know if you need further clarification =)

**Comment by yyoncho** [comment]
@kyliau thank you. I thought that it has to be explicitly enabled. 

@JSiebelink I managed to make it work.

```
;;; Angular
(defcustom lsp-angular-language-server-command
  '("node" "/home/kyoncho/Downloads/angular/extension/server/server.js" "--stdio")
  "The command that starts the docker language server."
  :group 'lsp-angular
  :type '(choice
          (string :tag "Single string value")
          (repeat :tag "List of string values"
                  string)))

(lsp-register-client
 (make-lsp-client :new-connection (lsp-stdio-connection
                                   (-const lsp-angular-language-server-command))
                  :activation-fn (lambda (&rest _args)
                                   (string-match-p ".*\.html$" (buffer-file-name)) )
                  :add-on? t
                  :priority -1
                  :server-id 'angular-ls))
```
![emacs-27 0 50@myoncho_015](https://user-images.githubusercontent.com/13259670/62942036-20ac5680-bde0-11e9-81c1-6ce1bb475f30.png)

**Comment by JSiebelink** [comment]
Thank you so much for looking into it! I am trying the suggested config, and I manage to start the server indeed. However, right at startup, the server exits with an exit code.
![image](https://user-images.githubusercontent.com/24893462/63171581-1dada200-c03c-11e9-8c5c-aad1612f9281.png)

How did you build the actual server?

**Comment by yyoncho** [comment]
@JSiebelink I downloaded the extension from the vscode marketplace.

**Comment by JSiebelink** [comment]
Aah, I see. Let me try that.

**Comment by JSiebelink** [comment]
The same happens. Is there a way to debug the output of the server? Thank you so much for your time. I really appreciate it :)

**Comment by kyliau** [comment]
Please let me know if there's anything else I could help here. I'm working on improving the performance of the Angular language service, and a beta version of that is already in the works.

**Comment by JSiebelink** [comment]
It works! I checkout out the repo of the angular service and build it again. @kyliau : the language server actually failed with the error 'this.ngHost.setSite is not a function'. When using the latest version from the repo, this error disappears.

**Comment by yyoncho** [comment]
@JSiebelink can you test and report whether everything works?

**Comment by JSiebelink** [comment]
@yyoncho : I can confirm that it works now. I have checked out the version from the github repo, built it using npm, and configured lsp to point to the server.js file in the build output folder and it works. 
![image](https://user-images.githubusercontent.com/24893462/63184469-a71e9d80-c057-11e9-8ea1-599aa874329b.png)

**Comment by seagle0128** [comment]
Sorry for raising the question in the closed issue!

I just want to know how to disable `angular-ls` in `html` files by default. Every time I open a single html file, the annoying warning pops up

![image](https://user-images.githubusercontent.com/140797/64288305-5c2be200-cf94-11e9-8d7e-dc3f7b948c83.png)

IMO, it should check if it belongs an angular project.

**Comment by AloisJanicek** [comment]
@seagle0128  in case you don't want to use `angular-ls` right now, you can completely disable it with this : `(add-to-list 'lsp-disabled-clients '(web-mode . angular-ls))`

**Comment by seagle0128** [comment]
@AloisJanicek Thank you very much! Please consider my proposal above to make it smarter.

**Comment by VizorKit** [comment]
Does someone have the necessary steps and config listed out? I saw a mention of some config, but also an installation of something. It seemed like another person had to build that something from source?

**Comment by pedroqueiroga** [comment]
> @seagle0128 in case you don't want to use `angular-ls` right now, you can completely disable it with this : `(add-to-list 'lsp-disabled-clients '(web-mode . angular-ls))`

How do I use `angular-ls`? I have tried the steps listed here https://github.com/emacs-lsp/lsp-mode/wiki/Install-Angular-Language-server, but it doesn't work. Should we improve the documentation on how to get this to work? There is no `lsp-angular` package available for me to install through melpa.
