### ISSUE TITLE
lsp-find-references only finds references in current golang package, not project

### ISSUE THREAD

**Issue by coventry** [emacs-lsp/lsp-mode#967]
**Describe the bug**

In golang source code `lsp-find-references` will return only references within the current package, which is usually much more restrictive set than the entire project.

**To Reproduce**

Start `lsp-mode` on a multi-package golang project. Place point on a symbol which is referred to by multiple packages within the project. `M-x lsp-find-references` only lists the references within the current package.

**Expected behavior**

References from all packages in the project should be listed. Maybe there should be an option to search at the project or the package level.

It would be good if, when there's only one reference found, `lsp-find-references` emitted a message to indicate that. The current non-behavior looks like a bug in its own right, if you don't realize that it's taking you to the only instance of the symbol and therefore leaving you exactly where you were.

**Which Language Server did you use**

`gopls`

**OS**
Ubuntu 18.04

**Comment by yyoncho** [comment]
The jump to reference issue is in emacs code base and AFAIK it is already fixed in emacs 27. The list of the references is returned by the language server and it is not controlled by lsp-mode, so you should file it in the gopls repo.

**Comment by coventry** [comment]
OK. I had hoped there was some way for a client to broaden the scope.
