### ISSUE TITLE
completion in pyls seems uncomfortable

### ISSUE THREAD

**Issue by nicehiro** [emacs-lsp/lsp-mode#969]
**Describe the bug**
Choose a function candicate will select the parameters of this candidate function together. Maybe I miss some configration?

**To Reproduce**
Just tap a function with parameter, then choose a candidate.
Example:
![image](https://user-images.githubusercontent.com/17773634/62848177-d9a16100-bd0c-11e9-9e84-0c34cd07f780.png)

**Expected behavior**
With no parameters selected.

**Which Language Server did you use**
lsp-python with pyls

**OS**
Arch Linux

**Error callstack**
Nothing

**Comment by yyoncho** [comment]
Please install yasnippet or disable the snippet completion by setting lsp-enable-snippet to nil. In the latest lsp-mode there should be a message warning that it should be installed.

**Comment by yyoncho** [comment]
One more thing - the snippets work only when using company-lsp. In if you do not use it you have to disable them via lsp-enable-snippet since the lsp capf snippet support is not implemented.

**Comment by nicehiro** [comment]
> Please install yasnippet or disable the snippet completion by setting lsp-enable-snippet to nil. In the latest lsp-mode there should be a message warning that it should be installed.

Thanks! Install yasnippet fix my problem!
