### ISSUE TITLE
JavaScript support

### ISSUE THREAD

**Issue by L42y** [emacs-lsp/lsp-mode#97]
I tried to add JavaScript support by defining new client with following code:

```emacs-lisp
(lsp-define-stdio-client
           'rjsx-mode "JavaScript" 'stdio
           (lsp-make-traverser #'(lambda (dir)
                                   (directory-files dir nil "package.json")))
           "JavaScript Language Server"
           '("javascript-typescript-stdio"))
```

the `javascript-typescript-stdio` is from https://github.com/sourcegraph/javascript-typescript-langserver, but I couldn't make it works properly, getting errors like:

```
Unknown request method: workspace/xfiles
Unknown method: $/partialResult
```

did I miss something?

**Comment by alanz** [comment]
SourceGraph has an extension for a virtual file system, which is not part of the normal spec.

This is not currently implemented in emacs-lsp. I think it may only be implemented in the SourceGraph clients.

See https://github.com/sourcegraph/language-server-protocol/blob/master/extension-files.md

**Comment by vibhavp** [comment]
https://github.com/emacs-lsp/lsp-javascript

**Comment by L42y** [comment]
hurray!

**Comment by idanko** [comment]
> https://github.com/emacs-lsp/lsp-javascript

Broken link...

**Comment by ericdallo** [comment]
The javascript client now is on https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-javascript.el
