### ISSUE TITLE
 How to correctly guess the root directory

### ISSUE THREAD

**Issue by taigacute** [emacs-lsp/lsp-mode#971]
Please ask your questions at https://gitter.im/emacs-lsp/lsp-mode
Hi，A vimer new come to emacs， i used lsp-mode and set `auto-guess`， but i got something wrong, i have a project like this . when i edit the `goroutine*/**.go`， i cant get the lsp-mode work. the root is `Goroutine` .
![image](https://user-images.githubusercontent.com/41671631/62936139-9540be80-bdfb-11e9-9ccb-9fb8724a9f08.png)

**Comment by yyoncho** [comment]
1. Use lsp-describe-session to find out what are the roots used by lsp and the lsp-workspace-folders-* methods for adding/removing the folders. treemacs projects are not synched with lsp-mode folders.
2. If you want to use auto guess option refer to `project.el`/`projectile` documentation on how to setup the project roots.

**Comment by taigacute** [comment]
@yyoncho  thanks
