### ISSUE TITLE
Fail to parse workspace/executeCommand for code action (using cquery & C++)

### ISSUE THREAD

**Issue by skelutten** [emacs-lsp/lsp-mode#972]
**Describe the bug**
When getting the hint "Add one of following includes... " and applying that I get the error:

Debugger entered--Lisp error: (error "Fail to parse ’workspace/executeCommand’ /params/comman, expected std::string")
  signal(error ("Fail to parse ’workspace/executeCommand’ /params/comman, expected std::string"))
  error("Fail to parse 'workspace/executeCommand' /params/comman, expected std::string")
  lsp-request("workspace/executeCommand" (:command ["file:///repo/xyz/src/zyx.cc" [#<hash-table equal 2/65 0x32cd40d>]]))
  #f(compiled-function (command &optional args) "Create and send a 'workspace/executeCommand' message having command COMMAND and optional ARGS." #<bytecode 0x143a515>)(["file:///repo/xyz/src/zyx.cc" [#<hash-table equal 2/65 0x32cd40d>]])
  cquery--execute-command-locally-advice(#f(compiled-function (command &optional args) "Create and send a 'workspace/executeCommand' message having command COMMAND and optional ARGS." #<bytecode 0x143a515>) "cquery._insertInclude" ["file:///repo/xyz/src/zyx.cc" [#<hash-table equal 2/65 0x32cd40d>]])
  apply(cquery--execute-command-locally-advice #f(compiled-function (command &optional args) "Create and send a 'workspace/executeCommand' message having command COMMAND and optional ARGS." #<bytecode 0x143a515>) ("cquery._insertInclude" ["file:///repo/xyz/src/zyx.cc" [#<hash-table equal 2/65 0x32cd40d>]]))
  lsp--send-execute-command("cquery._insertInclude" ["file:///repo/xyz/src/zyx.cc" [#<hash-table equal 2/65 0x32cd40d>]])
  lsp--execute-command(#<hash-table equal 3/65 0x32cd009>)
  lsp-execute-code-action(#<hash-table equal 3/65 0x32cd009>)
  #f(compiled-function () (interactive nil) #<bytecode 0x32cd239>)()
  funcall-interactively(#f(compiled-function () (interactive nil) #<bytecode 0x32cd239>))
  call-interactively(#f(compiled-function () (interactive nil) #<bytecode 0x32cd239>) nil nil)
  command-execute(#f(compiled-function () (interactive nil) #<bytecode 0x32cd239>))

**To Reproduce**
Click the code action

**Expected behavior**
In this particular case - adding an included to the code

**Which Language Server did you use**
cquery

**OS**
Linux

**Error callstack**
Se above

``` emacs-lisp
(setq lsp-print-io t)
```

**Comment by yyoncho** [comment]
Please report that in cquery repo. FYI AFAIK cquery is no longer developed so it will be better to switch to ccls/clangd.
