### ISSUE TITLE
new version is unusable with Microsoft Python Language Server

### ISSUE THREAD

**Issue by prittjam** [emacs-lsp/lsp-mode#975]
**Describe the bug**
Everything stopped working

**To Reproduce**
try the newest version of lsp-mode with MSFT Python Language Server

**OS**
Linux

```

**Comment by yyoncho** [comment]
Tested with `emacs -q` and the latest version of the server(automatically downloaded and everything seems to be working fine).

**Comment by prittjam** [comment]
Hi Thanks for the the reply, it is working on certain python files it seems. However, on some files there is a status bar where the major mode is and it just keeps cycling, like it's timing out or trying to parse...

**Comment by yyoncho** [comment]
can you provide a file/project to use for reproducing the issue?

**Comment by prittjam** [comment]
it seems the problem is in dap-mode, actually....
Compilation exited abnormally with code 1
Failed to connect to localhost:32000 with error message make client process failed: Connection refused, :name, *connection-test*, :buffer, nil, :host, localhost, :service, 32000, :nowait, nil, :tls-parameters, nil [7 times]
Failed to connect to localhost:32000 with error message Failed connect: Connection refused
Failed to connect to localhost:32000 with error message make client process failed: Connection refused, :name, *connection-test*, :buffer, nil, :host, localhost, :service, 32000, :nowait, nil, :tls-parameters, nil [27 times]
No messages handler for process
error in process filter: mapc: Wrong type argument: overlayp, nil
error in process filter: Wrong type argument: overlayp, nil
user-error: Minibuffer window is not active

**Comment by yyoncho** [comment]
@prittjam can you delete the `dap-breakpoints-file` (used to be `dap--breakpoints-file`) and restart emacs?

**Comment by yyoncho** [comment]
Please reopen if you still have the issue after https://github.com/emacs-lsp/lsp-mode/issues/975#issuecomment-521881779
