### ISSUE TITLE
LSP errors in Angular 5.xx projects

### ISSUE THREAD

**Issue by adriandeveloper** [emacs-lsp/lsp-mode#979]
Bug: When loading an Angular 5 project (legacy work project), LSP is reporting that the decorators like @Output(), @Input() are experimental and are subject to change.  

![Imgur](https://i.imgur.com/e0Fk83B.png)

These errors are littered thorough the project and is causing ~~LSP to crash~~ lsp-ui to become disabled due to the amounts of `errors` it reports. 

The error suggests setting `expermintalDecorators` to true to get rid of that warning and it is setup in the `tsconfig.json` file but it seems that LSP is `ignoring` this setting.

![Imgur](https://i.imgur.com/YIx7b8j.png)

Note that this only seems to happen with Angular 5 projects and below.  I've started an Angular 8x project and there are no `expermintalDecorator` errors present.

**To Reproduce**
Load an Angular 5 project and view a .ts file. Errors should pop up if the LSP server starts. 
Other older projects the server crashes (may submit a separate bug for that later).

**Expected behavior**
When LSP starts and `expermintalDecorators `are true, there should be no errors.  

**Which Language Server did you use**
Sourcegraph's Language server and later I've set my Emacs config to use the tsserver found in `node_modules`:
```
;; lsp
(setq lsp-clients-typescript-server-args '("--stdio" "--tsserver-path" "node_modules/typescript/bin/tsserver"))
```
**OS**
Mac OS Mojave

**Error callstack**
No error other than what's displayed.

**Note**
I also use VSCode for this project (moving over to Emacs + Evil Mode) and there are no LSP errors of this nature in VSCode.

**Comment by yyoncho** [comment]
> These errors are littered thorough the project and is causing LSP to crash due to the amounts of errors it reports.

What do you mean by crash?

Can you also provide a sample project(none of the lsp-mode maintainers is familiar with JS/Angular so it is a bit hard to reproduce the issue following only your steps)?

Before me digging into the issue my gut feeling is that we should report the issue upstream because it is not lsp-mode that reads the tsconfig.json file but it is the solargraph language server and lsp-mode is just a frontend of the errors sent by the servers.

**Comment by adriandeveloper** [comment]
OK. I'll provide a demo project and post shortly.  The only Angular projects I really work on are the ones I use for work and I can't post up that code, but I'll see if I can generate another Angular 5 project.>

And by `crash`, LSP-ui is disabled.  I'll modify the original report to reflect this as I don't want to infer that the LSP-mode is crashing.  

![Imgur](https://i.imgur.com/OtQPo6H.png)

As for lsp-mode not reading the tsconfig.json file, would that still be an issue if the tsserver is coming from node_modules/typescript directory?

**Comment by yyoncho** [comment]
I see - so the issue is: Javascript language server disregards tsconfig setting

> As for lsp-mode not reading the tsconfig.json file, would that still be an issue if the tsserver is coming from node_modules/typescript directory?

This is related to language server internals which I am not familiar with.

**Comment by adriandeveloper** [comment]
Here is a fork of an [Angular 5 project](https://github.com/adriandeveloper/Angular5-Seed.git). 

When starting it in Emacs, the following appears

 ![Imgur](https://i.imgur.com/JD2U9au.png)

**Comment by yyoncho** [comment]
I deleted the tsserver in the node_modules/.bin/tsserver and it started fine. FTR the way to debug this is to check stderr buffer for the language server.

**Comment by adriandeveloper** [comment]
> I deleted the tsserver in the node_modules/.bin/tsserver and it started fine. FTR the way to debug this is to check stderr buffer for the language server.

Thanks for the debug tip.  I've deleted node_modules/.bin/tsserver and the error `Server ts-ls:pid status: starting exited with status exit` still persists. 

Looking at stderr, I also removed node_modules/typescript/.bin/tsserver with the same results.  

I may just have to see if this will error out on different language servers.

**Comment by adriandeveloper** [comment]
Ok I got lsp to run just by removing node_modules and running yarn to install the modules again.

Lsp is now running on that Angular 5 Seed app.

I'm now getting the original error message about the decorators.  

In lsp-log I have the following:

> Command "javascript-typescript-stdio" is present on the path.
Command "typescript-language-server --stdio --tsserver-path node_modules/typescript/bin/tsserver" is present on the path.
Found the following clients for /Users/adrianthomas/git-clones/Angular5-Seed/src/app/app.component.ts: (server-id jsts-ls, priority -3), (server-id ts-ls, priority -2)
The following clients were selected based on priority: (server-id ts-ls, priority -2)

Maybe there is a conflict of interest since lsp is loading two different language servers (or maybe not loading, it's detecting the `javascript-typescript-stdio` server and `typescript-language-server`

I'll have to search the docs for lsp to only use `typescript-language-server` and I may just remove the `javascript-typescript-stdio` server and only have one on my machine. 

If this doesn't resolve this then I just may have to make a branch on the language servers themselves and see if they have an idea since, as you suggested, it may not be an lsp-mode issue.

**Comment by yyoncho** [comment]
Is there anything outstanding related to this issue?

**Comment by adriandeveloper** [comment]
Still trying to find the root cause.  Filled out a similar issue on the typescript-language-server rep and no response. 

The problem is still the same.  LSP errors are generated on older Angular 5.xxx projects. 

If this isn't an LSP issue, then I'm either on my own with figuring out a solution, or just to use another tool and come back to this at a later date.  

Guess I'll just close the issue here and if there are any new developments I'll reopen. 

Thanks for your help.
