### ISSUE TITLE
[Feature Request] - Auto install LSP if possible, turn off lsp if not found.

### ISSUE THREAD

**Issue by jcs090218** [emacs-lsp/lsp-mode#982]
Since the LSPs are listed on the readme, I assume there is a a way to implement this. I think by automatically installed the possible language server will be very helpful to the user. If the environment is not been set, just turn off the `lsp-mode` and notify the user the environment has not been completely defined.

**Comment by yyoncho** [comment]
See https://github.com/emacs-lsp/lsp-mode/issues/506

**Comment by jcs090218** [comment]
Great! you might want to tag `duplicated`. And sorry about this issue!
