### ISSUE TITLE
lsp-format-buffer and error feedback when there is a formatting error

### ISSUE THREAD

**Issue by nloyola** [emacs-lsp/lsp-mode#985]
**Describe the bug**
If there is a syntax error in the file and I call `lsp-format-buffer`, I do not get visual feedback that the formatting failed.

I can see the error the formatter generated in `*lsp-log*`.

**To Reproduce**
Create a syntax error in a file and then call  `lsp-format-buffer`.

**Expected behavior**
An error should be shown to the user. Most likely in the minibuffer.

**Which Language Server did you use**
[metals-emacs](https://scalameta.org/metals/docs/editors/emacs.html)

**OS**
Ubuntu 19.04

**Error callstack**
N/A

**Comment by yyoncho** [comment]
@nloyola  Good idea, willing to give it a try?

**Comment by nloyola** [comment]
@yyoncho Sure! I will.

**Comment by jakejx** [comment]
Hi, I took a look at this issue and I noticed that there is already a default error handler in `lsp--send-request-async` already. When there is a syntax error in the file, scala metals  returns an empty list of edits. Should we have a message in the minibuffer saying that the server did not suggest any changes?

**Comment by yyoncho** [comment]
@jakejx - make sense.
