### ISSUE TITLE
lsp-find-references doesn't find all references in C++ code

### ISSUE THREAD

**Issue by abbaswasim** [emacs-lsp/lsp-mode#990]
**Describe the bug**
lsp-find-references doesn't find all references  to symbols even in the same header file. My suspicion is on how you call member variables/methods. I have played around with using `this->` and without that and in one case its not picked up in another it is.

I must say I haven't found a way to test `clangd` or `ccls` in isolation via command line yet so it might be an issue in `clangd` itself. In which case I will be more than happy to move the issue there. I have however tried both `clangd` and `ccls` with `lsp-mode` and both seems to have the same issue. Further if someone could also help with how do you test `clangd` with some hand coded `JSON-RPC` from command line that will be very useful to isolate the issue to `clangd`.

**To Reproduce**
1) Unzip the test project [lsp-clangd-test.zip](https://github.com/emacs-lsp/lsp-mode/files/3548301/lsp-clangd-test.zip)
2) Clone latest `git clone  https://github.com/emacs-lsp/lsp-mode.git`
3) Apply [lsp-start-plain.el.patch.txt](https://github.com/emacs-lsp/lsp-mode/files/3548315/lsp-start-plain.el.patch.txt) onto your `lsp-mode/scripts/lsp-start-plain.el` to test a clean installation of `emacs` as well as `lsp-mode` the patch is very simple adding your path to emacs so it can find `clangd` and gives it arguments as well as sets up `lsp-mode` for c++
4) Start emacs with `HOME=/tmp/ Emacs -q -l ./lsp-mode/scripts/lsp-start-plain.el`
5) Open `graph.hpp` from the test project
6) `M-x goto-char` and enter `1991` enter.
7) `M-x lsp-find-references` enter you should now see three references

```
/development/clangd_test/graph.hpp
34: 	void add_child(VertexId a_parent, VertexId a_child);
80: 	add_child(a_parent, a_child);
84: void Graph<T>::add_child(VertexId a_parent, VertexId a_child)
```
This is however wrong there are more references to `add_child` in the `graph.hpp` file.

8) `M-x goto-char` and `1891` enter.
9) `M-x lsp-find-references` you should now see `Not found for: add_child` even though there are references to it in the same file. 

10) try the same on the `add_child` 2 lines below the one without `this->` you will see again the 3 references. And further similar results with no references for line `87 parent.add_child(a_child);` you get no references.

Some more `lsp` and `clangd` coms I have captured are:
```
[Trace - 10:47:19 pm] Sending request 'textDocument/references - (269)'.
Params: {
  "textDocument": {
    "uri": "file:///development/clangd_test/graph.hpp"
  },
  "position": {
    "line": 83,
    "character": 18
  },
  "context": {
    "includeDeclaration": false
  }
}


[Trace - 10:47:19 pm] Received response 'textDocument/references - (269)' in 9ms.
Result: [
  {
    "uri": "file:///development/clangd_test/graph.hpp",
    "range": {
      "start": {
        "line": 33,
        "character": 6
      },
      "end": {
        "line": 33,
        "character": 15
      }
    }
  },
  {
    "uri": "file:///development/clangd_test/graph.hpp",
    "range": {
      "start": {
        "line": 79,
        "character": 1
      },
      "end": {
        "line": 79,
        "character": 10
      }
    }
  },
  {
    "uri": "file:///development/clangd_test/graph.hpp",
    "range": {
      "start": {
        "line": 83,
        "character": 15
      },
      "end": {
        "line": 83,
        "character": 24
      }
    }
  }
]


/// Failed attempt for not finding references

[Trace - 10:50:34 pm] Sending request 'textDocument/references - (1246)'.
Params: {
  "textDocument": {
    "uri": "file:///development/clangd_test/graph.hpp"
  },
  "position": {
    "line": 77,
    "character": 10
  },
  "context": {
    "includeDeclaration": false
  }
}


[Trace - 10:50:34 pm] Received response 'textDocument/references - (1246)' in 8ms.
Result: []
```

The above tells me that the issue might be in `clangd` because `lsp` is not getting the references at all but I can't test that.

**Expected behavior**
I would expect to see all of the references shown for `add_child`

**Which Language Server did you use**
I am using `lsp-mode` with `clangd` for C++
```
$ clangd --version
clangd version 8.0.1 (tags/RELEASE_801/final)
```

**OS**
macOs Mojave 10.14.6 (18G95) 
Manjaro (Arch Linux)

**Emacs**
GNU Emacs 26.2 (build 1, x86_64-apple-darwin18.6.0, Carbon Version 158 AppKit 1671.5) of 2019-05-27 on macOs but 26.2 on ArchLinux as well

**Error callstack**
There are no lsp-mode errors as such.

**Comment by yyoncho** [comment]
@abbaswasim thank you for the detailed report! Unfortunately, this issue is not in the scope of lsp-mode but it is in the scope of the language server - lsp-mode is just a frontend and the logic related to finding the references is in the language server. I got similar results when using ccls - it does not find the references when using `->`. CC @MaskRay who might have an explanation

**Comment by MaskRay** [comment]
The report is nice but it is language server specific, unrelated to a language client.

clangd 9 gets improved background indexer and you may get project-wide references if its indexer is enabled.

In ccls wiki, you can find instructions how to use `ccls -index .` to start ccls in standalone mode to index a project.

**Comment by abbaswasim** [comment]
Thanks guys, I figured so as I mentioned in the comments `clangd` is not returning the right stuff. I am struggling to isolate the issue to Language server however (not for the lack of googling for it for days). Do you have an advice on how to drive `clangd` from command line with hand written `JSON-RPC`?

@yyoncho the patch I have provided does enable `background-index` in the line `(setq lsp-clients-clangd-args '("-j=4" "-background-index" "-log=verbose"))` so this is after an index is generated but I guess `clangd` isn't able to find the references so it won't add it to the index either.

**Comment by abbaswasim** [comment]
@MaskRay I have actually build clangd 9 from source and tried that on Arch Linux with background indexer and that couldn't find it either. I guess it's time to submit a bug report there. I would still like to be able to confirm it though.

**Comment by abbaswasim** [comment]
I have actually found answer to my question. If anyone else is interested in how to test `clangd` from command line. Have a look in `[llvm-project/clang-tools-extra/clangd/test/references.test](https://github.com/llvm/llvm-project/blob/master/clang-tools-extra/clangd/test/references.test)` you can build a `lit` test file like that with your json-rpc commands and run it through `clangd` with a `-lit-test` command line argument.

`clangd -lit-test < your_json_rpc_commands.test`

**Comment by yyoncho** [comment]
> I have actually found answer to my question.

Would you mind sharing your findings?

**Comment by abbaswasim** [comment]
> Would you mind sharing your findings?

Sure but I meant the following question.

> I must say I haven't found a way to test clangd or ccls in isolation via command line yet so it might be an issue in clangd itself. In which case I will be more than happy to move the issue there. I have however tried both clangd and ccls with lsp-mode and both seems to have the same issue. Further if someone could also help with how do you test clangd with some hand coded JSON-RPC from command line that will be very useful to isolate the issue to clangd.

So the answer is already there. How to test `clangd` via command line.
