### ISSUE TITLE
Yasnippet warning shown even when it's installed

### ISSUE THREAD

**Issue by emdemir** [emacs-lsp/lsp-mode#991]
**Describe the bug**
Even if I have the yasnippet package installed, I still get the following warning:  
`Warning (emacs): Yasnippet is not present but ‘lsp-enable-snippet’ is set to ‘t’. You must either install yasnippet or disable snippet support.`
I do have `yasnippet` installed, and `(fboundp 'yas-expand-snippet)` returns `t`.

**To Reproduce**
 - Open any filetype you have a language server installed for
 - Type `M-x lsp`

**Expected behavior**
No warning.

**Which Language Server did you use**
Doesn't seem to matter, I had the issue with `typescript-language-server`, `python-language-server`, ...

**OS**
Debian 10

**LSP version**
20190827.1505 from Melpa

**Comment by yyoncho** [comment]
> You must either install yasnippet or disable snippet support.

This sentence is incorrect/misleading. It should be : 

> You must install and do `(require 'yasnippet)` or disable snippet support.

**Comment by aidalgol** [comment]
@yyoncho Why does lsp-mode not try to load yasnippet?  I think this conditional
```elisp
(fboundp 'yas-expand-snippet)
```
should be
```elisp
(featurep 'yasnippet)
```

Since yasnippet is an optional dependency, lsp-mode could `require` it with the `NOERROR` flag set.  e.g.
```elisp
(require 'yasnippet nil t)
```

**Comment by aidalgol** [comment]
I created a PR for the changes I outlined above: #1093.

**Comment by rien333** [comment]
https://github.com/emacs-lsp/lsp-mode/issues/4409 may have broken things? In any case, I've been seeing this warning again, even with yasnippet installed. It seems I can only satisfy LSP by already having yasnippet loaded (which I do not want to do on startup). 
 
 I worked around this by deferring the loading of yasnippet for a few seconds after startup — though ideally, I would like to load yasnippet only as required:
 
 ``` elisp
 (use-package yasnippet
  :defer 2 ;; needed to satisfy LSP
  :config
  (add-to-list 'yas-snippet-dirs "~/.emacs.d/snippets")
  :diminish yas-minor-mode
  :commands (yas-insert-snippet)
  :hook ((prog-mode
          nxml-mode
          conf-mode
          snippet-mode) . yas-minor-mode-on)
  :bind ("C-'" . yas-insert-snippet)
)
 ```
 
Maybe I'm using `use-package` in way that hinders this goal, though (I freely admit to not being an expert on `use-package` and `LSP` )
