### ISSUE TITLE
lsp-mode fails to connect to erlang_ls when source file is given on Emacs command line

### ISSUE THREAD

**Issue by jesperes** [emacs-lsp/lsp-mode#993]
**Describe the bug**
When opening an Erlang source file by passing it on the Emacs command line, `lsp-mode` fails to connect to the language server. If I start Emacs without arguments and then open the file using `C-x C-f` everything works fine.

**To Reproduce**
Start Emacs and specify the path to a source file on the command line, e.g. 
```
$ emacs /path/to/foo.erl
```

**Expected behavior**
Emacs should open `foo.erl` with language server support enabled.

**Which Language Server did you use**
`erlang_ls`

**OS**
Linux (Ubuntu 19.04)

**Error callstack**
The `*Messages*` buffer contains:
```
LSP :: Failed to connect to localhost:10001 with error message make client process failed: Connection refused, :name, erlang-ls::tcp, :buffer, nil, :host, localhost, :service, 10001, :nowait, nil, :tls-parameters, nil [100 times]
File mode specification error: (wrong-type-argument processp nil)
```

**Comment by robertoaloi** [comment]
It looks like the error keeps happening (occasionally) even after 1e34baa.
