### ISSUE TITLE
lsp fails to start vue-language-server

### ISSUE THREAD

**Issue by teu5us** [emacs-lsp/lsp-mode#995]
Latest Spacemacs develop branch. Tried also a minimal config with only auto-complete and lsp layers added. When I open a .vue file, I get this:

```
Request initialize failed with message: The "path" argument must be of type string. Received type undefined
```

Tried installing on Linux and Mac, keep getting the same error.

**Comment by yyoncho** [comment]
See https://github.com/vuejs/vetur/issues/1402
